### ISSUE TITLE
Improvements to Flixdoc

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1013]
We should explore what improvements can be made to flixdoc.

For example:
- Add support for inline code and tests in comments.
- Add support for running code examples directly in flixdoc.
- Add support for some form of markdown.
- Add support for sections, i.e. controlling the order that definitions occur in.
- Add support for cross-linking.
- Improved search.

Other ideas?

**Comment by mlutze** [comment]
A couple more ideas from [Scaladoc](https://docs.scala-lang.org/overviews/scaladoc/for-library-authors.html):
* Macros
* Tags
  * A `@version` tag could somehow link to the semantic version system. (#1006)
