### ISSUE TITLE
Explore a Principled Approach to User-Defined Operators

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1015]
We should come up with some principles approach to have to support user-defined operations.

Inspiration:
- https://docs.swift.org/swift-book/LanguageGuide/AdvancedOperators.html
- https://docs.scala-lang.org/tour/operators.html
- https://blog.adamant-lang.org/2019/operator-precedence/
- http://whiley.org/2016/11/15/mixfix-function-syntax-for-whiley/

**Comment by stephentetley** [comment]
Two very nice features of Haskell are firstly the ability to turn normal functions into operators by enclosing them in ticks:

~~~

"ab" `isInfixOf` "abcdefg"

~~~

And secondly, you are free to decide the precedence and associativity of user defined operators. In F# and I think Ocaml the first character of the operator indicates precedence and whether it's left or right associative.

**Comment by magnus-madsen** [comment]
We already have infix support in the way you describe :) Check it out!

**Comment by stephentetley** [comment]
Excellent!
