### ISSUE TITLE
Explore Call-By-Name

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1018]
We currently have functions like:

```scala
///
/// Returns `v` if `o` is `Some(v).` Otherwise returns `d`.
///
pub def getWithDefault(o: Option[a], d: a): a = match o {
    case None => d
    case Some(v) => v
}
```

but it might be better if the second argument was call-by-name, e.g.:

```scala
///
/// Returns `v` if `o` is `Some(v).` Otherwise returns `d`.
///
pub def getWithDefault(o: Option[a], d: Unit -> a): a = match o {
    case None => d()
    case Some(v) => v
}
```

Of course, now the problem is that we have to call the function like:

```
getWithDefault(o, () -> ...)
```

Maybe we could introduce some slightly shorter syntax, e.g.:

```
getWithDefault(o, -> ...)
```

**Comment by timjs** [comment]
Check out Unison's [delayed computations](https://www.unisonweb.org/docs/language-reference#delayed-computations). They use `'t` as an alias for the lazy type `() -> t`, and `!e` to force evaluation expression `e`, which is sugar for `e ()`.

Although I see that `!e` is already taken in Flix to be a prefix operator. Is this the only prefix operator in the language?

**Comment by magnus-madsen** [comment]
> Check out Unison's [delayed computations](https://www.unisonweb.org/docs/language-reference#delayed-computations). They use `'t` as an alias for the lazy type `() -> t`, and `!e` to force evaluation expression `e`, which is sugar for `e ()`.

Will have a look.

> Although I see that `!e` is already taken in Flix to be a prefix operator. Is this the only prefix operator in the language?

I don't recall, but I have been thinking about changing the logical operators (not, and, or) to use keywords instead of symbols (although I am not sure if everyone is on board with that).

**Comment by magnus-madsen** [comment]
I think we may also want to reserve ' for quasi-quotation (even if that is far-far-far-far in the future).

Also, I am really unsure of how lazy evaluation is really used in practice. I need someone to enlighten me. (i.e. does it need language support and what kind of language support?).

**Comment by timjs** [comment]
> Also, I am really unsure of how lazy evaluation is really used in practice. I need someone to enlighten me. (i.e. does it need language support and what kind of language support?).

Laziness can be seen as an _benign effect_ in a strict programming language (see for example chapter 37 of Harper's PFPL, 1st edition). Idris, for example, encodes laziness as a data type like:
```idris
data Lazy : Type -> Type where
     Delay : (val : a) -> Lazy a

force : Lazy a -> a
```
E.g. `if-then-else` including short circuiting behavior, can be defined [in Idris as a function](http://docs.idris-lang.org/en/latest/tutorial/typesfuns.html?highlight=Lazy#laziness):
```idris
ifThenElse : Bool -> Lazy a -> Lazy a -> a
ifThenElse True  t _ = force t
ifThenElse False _ e = force e

f : Int -> Int
f x = ifThenElse (x == 37) (Delay "Hurray!") (Delay someBigComputationWhichIsntCalculatedYet)
```
The compiler automatically inserts the `Delay` and `force` into cals when the function signature states that a parameter is of type `Lazy`, so in practice you'll never need to spell them out. This is equivalent to [Swift's `autoclosure`](https://docs.swift.org/swift-book/LanguageGuide/Closures.html#ID543) feature.

As Flix demands type annotations on every toplevel declaration, we could do exactly the same thing!

> I don't recall, but I have been thinking about changing the logical operators (not, and, or) to use keywords instead of symbols (although I am not sure if everyone is on board with that).

I'm in favor of removing prefix operators, as `not` could be a function. This simplifies the language. Not entirely sure about `and` and `or`. Although it reads way nicer (as in Python for example), it adds extra keywords to the language.

With the addition of a built in `Lazy` type, the `&&` and `||` operators could have type `Bool -> Lazy[Bool] -> Bool` which encodes short-circuiting (as in [Idris](https://www.idris-lang.org/docs/current/prelude_doc/docs/Prelude.Bool.html)). They stay normal operators, no special cases in the language!

**Comment by magnus-madsen** [comment]
> The compiler automatically inserts the Delay and force into cals when the function signature states that a parameter is of type Lazy, so in practice you'll never need to spell them out. 

> As Flix demands type annotations on every toplevel declaration, we could do exactly the same thing!

Possibly. I am not sure if this would break "principle types". 

What about non-top level types? What happens if you partially apply e.g. `ifThenElse`?

I do like the overall scheme, it seems pretty elegant.

**Comment by timjs** [comment]
> Possibly. I am not sure if this would break "principle types".

I think it will, but isn’t Flix’s type inference bidirectional?

> What about non-top level types? What happens if you partially apply e.g. ifThenElse?

You’ll need to give an annotation _or_ manually insert `Delay`and `force`.

Partial application is no problem: `ifThenElse` still needs one or more lazy argument(s).

**Comment by magnus-madsen** [comment]
> 
> I think it will, but isn’t Flix’s type inference bidirectional?
> 

No. It is based on Hindley-Milner. We require top-level signatures for software engineering reasons and less for type theory reasons. Even with top-level signatures, HM has the advantage that it never "guesses wrong" inside a function with local functions, unlike e.g. Scala.

**Comment by timjs** [comment]
I’m not really into Scala. Can you give an example when Scala “guesses wrong”?

**Comment by magnus-madsen** [comment]
Like all the time, e.g. `xs.foldLeft(Nil) {...}` does not work without an annotation on `Nil` to specify the type of the list.

**Comment by timjs** [comment]
Flix doesn't have subtyping does it? I'm talking about bidirectionality in style of [Dunfield and Krishnaswami](https://www.cl.cam.ac.uk/~nk480/bidir.pdf).

**Comment by magnus-madsen** [comment]
Right, Flix does not have sub-typing, only row types of various shapes and sizes.

**Comment by magnus-madsen** [comment]
Fixed in master. We now have lazy/force. 

We are currently researching some more powerful mechanisms to control evaluation order. More on that later.
