### ISSUE TITLE
Ensure that the Standard Library Satifies the New Flix Principles

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1034]
The Great Renaming:

Decided:
```
- Array.sortBy -> Array.sorthWith
- Array.sortBy! -> Array.sorthWith!
- MutSet.add -> MutSet.add!
- MutSet.addAll -> MutSet.addAll!
- MutSet.clear -> MutSet.clear!
- MutSet.remove -> MutSet.remove!
- MutSet.removeAll -> MutSet.removeAll!
- MutSet.retainAll -> MutSet.retainAll!
- MutSet.refine -> MutSet.refine!
- MutSet.transform -> MutSet.transform!
- MutSet.replace -> MutSet.replace!
- MutMap.adjust -> MutMap.adjust!
- MutMap.adjustWithKey -> MutMap.adjustWithKey!
- MutMap.clear -> MutMap.clear!
- MutMap.getOrElsePut -> MutMap.getOrElsePut!
- MutMap.merge-> MutMap.merge!
- MutMap.mergeWith-> MutMap.mergeWith!
- MutMap.mergeWithKey-> MutMap.mergeWithKey!
- MutMap.put-> MutMap.put!
- MutMap.refine-> MutMap.refine!
- MutMap.refineWithKey-> MutMap.refineWithKey!
- MutMap.remove -> MutMap.remove!
- MutMap.transform -> MutMap.transform!
- MutMap.transformWithKey -> MutMap.transformWithKey!
```

Undecided:
```
- get/insert or get/put
- fold as an alias for foldLeft.
- StringBuilder.* -> StringBuilder.*!
```

**Comment by stephentetley** [comment]
One thing we missed with the Array pull request was whether to use `_By` or `_With` as a suffix when passing in a helper function like a compator.

My preference is now for `_With` as I think it is more established in Flix's libraries but `sortBy` crept in with the PR.

**Comment by stephentetley** [comment]
Good - I see the decision is taken on By vs With.

I'd vote for `get/put` for accessors.

Another issue is, should we favour an `is` prefix for predicate functions e.g. `isSubsetOf`?

I say "favour" as some functions without `is_` are pretty much standard across functional programming languages and where there is well established precedent the established name is fine (e.g. `forall` `exists`).

**Comment by magnus-madsen** [comment]
> Good - I see the decision is taken on By vs With.

I think we will stick with "With" for now. I can still imagine a `.sortBy` but where instead of taking a comparator function it takes a projection function `a -> b`. For example, you would be able to do `persons.sortBy(p -> p.age)`.

> I'd vote for get/put for accessors.

I like them too. But how do you feel about this: `Map.get`,` Map.put`, `MutMap.get`, `MutMap.put`, and `MutMap.put!`. Is that reasonable or is that insane? Technically we are supposed to have `MutMap.put`, the functional version of `put`, and then also to have `put!` which is the destructive version, but at least here I see a lot of room for error.

> I say "favour" as some functions without is_ are pretty much standard across functional programming languages and where there is well established precedent the established name is fine (e.g. forall exists).

I completely agree with the sentiment. Let us `is` when it makes sense, but otherwise keep well-established functional names.

**Comment by stephentetley** [comment]
Do we need a non-destructive put on MutMap?

I think this was @ifazk 's feeling on the ArrayAdditions thread.

**Comment by magnus-madsen** [comment]
> 
> 
> Do we need a non-destructive put on MutMap?
> 
> I think this was @ifazk 's feeling on the ArrayAdditions thread.

I feels like it would be a bad idea, but we had a principle that said that mutable collections can be used as immutable, e.g. `map`, `union` and so forth. Hmm.

**Comment by stephentetley** [comment]
This is just a personal feeling, but if I can change easily (and ideally cheaply) between a MutMap and an immutable Map I'm not sure I'd need immutable update on a MutMap. I can certainly envisage situations where I might like to build a MutMap but then process it with just queries not modifications. This is like using STArrays in Haskell.

**Comment by stephentetley** [comment]
> StringBuilder

The `!` suffix would be consistent with MutMap. There's certainly scope for an additional `PureStringBuilder` module that could be used in processes that backtrack, so I have a preference for the current StringBuilder looking "imperative".

Incidentally in the String Additions I'm working on, I've got a re-implementation of `StringBuilder.append` - the current version is marked with `// TODO: Not efficient`. The new version casts the second `StringBuilder` to `java.lang.CharSequence` and appends that, I think this is the idiomatic way to do it in Java.

**Comment by magnus-madsen** [comment]
> The ! suffix would be consistent with MutMap. There's certainly scope for an additional PureStringBuilder module that could be used in processes that backtrack, so I have a preference for the current StringBuilder looking "imperative".

OK, do you want to update StringBuilder?

**Comment by stephentetley** [comment]
> OK, do you want to update StringBuilder?

I will do.

I actually hadn't realized that comment had gone into the main repository, I thought I had it only on a local branch to remind me to to look at it again.

**Comment by magnus-madsen** [comment]
> 
> 
> > OK, do you want to update StringBuilder?
> 
> I will do.
> 
> I actually hadn't realized that comment had gone into the main repository, I thought I had it only on a local branch to remind me to to look at it again.

I think it is actually my comment. I remember there being a better implementation that I for some reason had to replace by that.
