### ISSUE TITLE
Add Support for MutList

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1035]
We should add support for a growable list. Often called `ArrayList` or `Vector` or `ListBuffer`. 

We have the beginning of an implementation in `Vec.flix`, but this should be implemented, and renamed to `MutList` (to be consistent with `MutSet` and `MutMap`).

**Comment by esbenbjerre** [comment]
I guess we can close this?

**Comment by magnus-madsen** [comment]
Done!
