### ISSUE TITLE
Add liftN family of functions to Result, Option and Validation

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#1043]
The let* syntax is nice shorthand for sequencing multiple `Option` and `Result` values but it would be nice to be able to sequence multiple values on a single line. 

Haskell's liftM (liftA) family of functions are an idiomatic way to do this, because the lifters are applicative rather than monadic they would work for Validation as well.

When type classes are added to Flix, the lift family can be defined on the class rather than for concrete type but currently they would be useful and namespaces would stop naming conflicts.

Example signatures:

~~~

pub def lift2(f: (t1,t2) -> u & f, v1: Validation[t1, e], v2: Validation[t2, e]): Validation[u, e] & f =

pub def lift3(f: (t1,t2,t3) -> u & f, v1: Validation[t1, e], v2: Validation[t2, e], v3: Validation[t3, e]): Validation[u, e] & f =

~~~

Bikeshedding...

* What number do we go up to?

Haskell's standard library goes up to liftM5, I've used up to `lift10` for Flix's Validation. 

* Should we also expose `ap` the applicative function for `Option` and `Result`?
   
`ap` allows very easy defininition of the lift functions. It is already defined and exposed for `Validation`, should we add it to `Option` and `Result`.

**Comment by magnus-madsen** [comment]
> Haskell's liftM (liftA) family of functions are an idiomatic way to do this, because the lifters are applicative rather than monadic they would work for Validation as well.

Could you show me an example?

> When type classes are added to Flix, the lift family can be defined on the class rather than for concrete type but currently they would be useful and namespaces would stop naming conflicts.

I fully agree! This is already the approach we are following; we have `List.map` and `Option.map`. Later, when we have type classes, we can have `Functor` and have `List` and `Option` implement these, while preserving the functions in the namespaces (for programmers who "want to program in a simpler setting").

The proposed signatures look reasonable to me. Does the `u` name carry any significance?

>  What number do we go up to?

In `Prelude.flix` we have `__cmp` for tuples of up arity 4. This is clearly too little (!)

I would propose that we fix a number and try to support that number everywhere. We could start with say `10` (to keep the amount of code and compilation time down) with an ultimate goal of going to `20`.

> Should we also expose ap the applicative function for Option and Result?

Yes, and should we call it `ap` or `apply`? (I hope I not mixing things here?)

> ap allows very easy defininition of the lift functions. It is already defined and exposed for Validation, should we add it to Option and Result.

Agreed.

Side note: We should look more at:

https://jobjo.github.io/2019/04/24/ocaml-has-some-new-shiny-syntax.html

I would like to have some applicative syntax in Flix, but I am not sure how to do it.  I like `let*` from OCaml (see link), but I am less sold on their choice of applicative syntax. Thoughts?

**Comment by stephentetley** [comment]
This isn't a one-liner but it's typical of how I've been using liftN functions:

~~~

def readEquipmentInfo1[r](row: CsvRow): CsvResult[#{ EquipmentInfo | r }] & Impure = 
    use Work/CommonUtils.getYear;
    use Validation.lift7;
    lift7(
        (x1, x2, x3, x4, x5, x6, x7) -> { 
            let instyear = getYear(x7) |> x -> Result.getWithDefault(x, 0);
            EquipmentInfo(x1, x2, x3, x4, x5, x6, instyear).
        },
        CsvImport.getStringByLabel(row, "Reference"),
        CsvImport.getStringByLabel(row, "Common Name"),
        CsvImport.getStringByLabel(row, "Manufacturer"),
        CsvImport.getStringByLabel(row, "Model"),
        CsvImport.getStringByLabel(row, "Serial No"),
        CsvImport.getStringByLabel(row, "AssetStatus"),
        CsvImport.getStringByLabel(row, "Installed From")           
    )

~~~

`CsvImport.getStringByLabel` has the following signature with the Validation aliased so the singleton error is String:

~~~

type alias CsvResult[t] = Validation[t, String]

pub def getStringByLabel(row: CsvRow, label: String): CsvResult[String] & e =

~~~

> Does the u name carry any significance?

`u` in the type singatures of the lifters isn't particularly significant - visually I prefer it not being a final `tN` name.

> Yes, and should we call it ap or apply? (I hope I not mixing things here?)

I prefer `ap` though I'd admit it's not particularly beginner friendly. `ap` is established in Haskell, but also `apply` is a nice general name which we maybe shouldn't claim (I could imagine wanting `apply` for embedded DSLs).

I'm not sure about Ocaml's `let+` / `and+` syntax (though `let*` I've found very comfortable in Flix). `let+` / `and+` has the feature where the last line is a pure expression and you don't have to call `pure` (or e.g. Some if using Option) but I could certainly live with the following in Flix syntax if subseqent let+ bindings disallowed use of previously let+ bound variables: 

~~~

def addHeads(xs: List[Int32], ys: List[Int32], zs: List[Int32]): Option[Int32] =
    use Option.???;
    let+ x = safeHead(xs);
    let+ y = safeHead(ys);
    let+ z = safeHead(zs);
    Some(x + y + z)

~~~

I would need to think about how this desugars, though. I think this is equivalent to Haskell's new applicative-do.

**Comment by stephentetley** [comment]
Hi Magnus, I'm pretty much ready to make a pull request...

I see you've started work on the "great renaming" - do you want me to wait until you've finished that?

**Comment by magnus-madsen** [comment]
> 
> 
> Hi Magnus, I'm pretty much ready to make a pull request...
> 
> I see you've started work on the "great renaming" - do you want me to wait until you've finished that?

Yes, lets see if I can get that done later tonight.

**Comment by magnus-madsen** [comment]
> I prefer ap though I'd admit it's not particularly beginner friendly. ap is established in Haskell, but also apply is a nice general name which we maybe shouldn't claim (I could imagine wanting apply for embedded DSLs).

I will rename `apply` back to `ap`.

**Comment by magnus-madsen** [comment]
I merged #1046, but there is still some decisions to be made, #1034.

**Comment by stephentetley** [comment]
Hi Magnus - are you ready for pull request for this and #1044?

**Comment by magnus-madsen** [comment]
> 
> 
> Hi Magnus - are you ready for pull request for this and #1044?

Yes :)

**Comment by stephentetley** [comment]
Thanks - pull request submitted.

Liftn functions for Option, Result and Validation #1050

**Comment by magnus-madsen** [comment]
This can be closed right?

**Comment by stephentetley** [comment]
Yes.
