### ISSUE TITLE
PSA: What Every Flix Programmer Should Know Today

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1049]
We are currently entering a very exciting phase of Flix development; the compiler, language, and standard library are all rapidly evolving thanks to huge efforts by our little community. We are now at the point where real programs are starting to be written in Flix. 

At the moment there are three limitations Flix programmers should be aware of. We are hard at work at fixing these limitations, but in the meantime understanding them will help avoid unnecessary pain.

## Top-Level Type Signatures

At the moment, top-level type signatures are not completely correctly matched against the type (and effect) of a function body. For example, the following illegal program passes the type check:

```
def f(): List[a] = 1 :: Nil
```
but likely causes the compiler to crash.

Advice: Be extra careful when writing type signatures that are polymorphic.

Fix: Estimated within 2-6 weeks. 

## Ill-Kinded Types

At the moment, the Flix compiler admits ill-kinded types. For example:
```
def f(): Map[Int] = ...
def g(): Option[Int, Int] = ...
```
Here the wrong number of type arguments are supplied to `Option` and `Map`. The type checker may allow such programs leading to crashes later in the compiler.

Advice: Be extra careful with the usage of type constructors. Ensure that the right number of arguments is passed.

Fix: In progress, but no estimate.

### Equality, HashCode, and Ordering

Flix does not yet have type classes. Consequently notions such as equality, hashCode, and ordering are implemented in an ad-hoc manner. Essentially the compiler looks for suitable `__eq` and `__cmp` functions when needed. This mechanism works, but is brittle, and may produce compiler crashes when an `__eq` or `__cmp` function is missing.

Advice: Be careful when using sets, maps, and Datalog constraints with user-defined data types. If you do, ensure that you have defined appropriate `__eq` and `__cmp`. Not all built-in data structures (except for primitives) have these defined yet, so be sure to check. Moreover, do not use equality on arrays, channels, closures, floats, and other types that have no built-in notion of equality (or ordering).

Fix: No estimate. We eventually want to have type classes, but we may come up with an intermediate fix.

### Minor issues to be aware of

- Closures should not be moved between threads. In particular, do not create channels and send closures (functions) over them.
- We lack support for letrec-> Use top level functions for now.

### Plan

Fairly soon, once we have proper support for top-level signatures and for detecting ill-kinded types, we want to push towards ironing out bugs in the compiler. At that point, but not yet, we want to push for developers to file bug reports and then work on significantly improving the robustness of the compiler and improving the quality of error messages.

**Comment by stephentetley** [comment]
Are types going to be able to wrap functions with effects with the coming changes?

I'd like this type for a Stream datatype I'm working on as I use ref cells in the implementation:

~~~

pub opaque type Stream[a] = Unit -> (Unit -> Step[a]) & Impure

~~~


Unfortuantely I don't think I can do this at them moment (I think we can only wrap pure functional types) and my Stream module is stuck with Flix version 0.10.0 before effects were introduced.

**Comment by magnus-madsen** [comment]
> 
> 
> Are types going to be able to wrap functions with effects with the coming changes?
> 

Yes, I think this is already supported.

For example, you can write:

```
pub opaque type Stream[a, e] = Unit -> (Unit -> Step[a] & e) & Impure
```

is that what you are looking for? The syntax is a bit weird when you have higher-order functions.

**Comment by stephentetley** [comment]
Thanks Magnus, that's got me part way there. The Stream module new compiles but it crashes the compiler when I try to run a test. 

I'll see if I wrap a simpler effectful type.

**Comment by magnus-madsen** [comment]
> 
> 
> Thanks Magnus, that's got me part way there. The Stream module new compiles but it crashes the compiler when I try to run a test.
> 
> I'll see if I wrap a simpler effectful type.

This sounds like limitation one: A top-level signature does not match the type of the expression, but the compiler is not yet smart enough to figure it out. We are hard at work on that one, but it will still be some time. It's been a problem for many, but the fix to do it completely correct is not so simple.

**Comment by stephentetley** [comment]
Thanks - I think the code below is a simpler case of how I'm trying to wrap an effect.

It induces the same compiler error:

~~~

pub opaque type Logged[a, e] = Unit -> Option[a] & e

def loggedString(s: String): Logged[String, Impure]= 
    Logged(() -> {
        Console.printLine(s);
        Some(s)
    })

def runLS(ls: Logged[String, e]): String & e = 
    let Logged(f) = ls;
    match f() {
        case None => "...None..."
        case Some(s) => s
    }

@test
def test01(): String & Impure = 
    let ls = loggedString("hello");
    runLS(ls)

~~~

Error: 

~~~

Unexpected type: 'Impure'.ca.uwaterloo.flix.util.InternalCompilerException: Unexpected type: 'Impure'.
	at ca.uwaterloo.flix.language.phase.Finalize$.visitType(Finalize.scala:594)
	at ca.uwaterloo.flix.language.phase.Finalize$.$anonfun$visitType$1(Finalize.scala:543)
	at scala.collection.immutable.List.map(List.scala:223)
	at ca.uwaterloo.flix.language.phase.Finalize$.visitType(Finalize.scala:543)
	at ca.uwaterloo.flix.language.phase.Finalize$.visit$1(Finalize.scala:222)
	at ca.uwaterloo.flix.language.phase.Finalize$.visitExp(Finalize.scala:457)
	at ca.uwaterloo.flix.language.phase.Finalize$.visitDef(Finalize.scala:62)
	at ca.uwaterloo.flix.language.phase.Finalize$.$anonfun$run$2(Finalize.scala:36)
	at scala.collection.StrictOptimizedMapOps.map(StrictOptimizedMapOps.scala:30)
	at scala.collection.StrictOptimizedMapOps.map$(StrictOptimizedMapOps.scala:29)
	at scala.collection.immutable.HashMap.map(HashMap.scala:38)
	at ca.uwaterloo.flix.language.phase.Finalize$.$anonfun$run$1(Finalize.scala:35)
	at ca.uwaterloo.flix.api.Flix.phase(Flix.scala:336)
	at ca.uwaterloo.flix.language.phase.Finalize$.run(Finalize.scala:31)
	at ca.uwaterloo.flix.language.phase.Finalize$.run(Finalize.scala:27)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.$anonfun$run$1(Phase.scala:42)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.api.Flix.codeGen(Flix.scala:316)
	at ca.uwaterloo.flix.runtime.shell.Shell.ca$uwaterloo$flix$runtime$shell$Shell$$execReload(Shell.scala:477)
	at ca.uwaterloo.flix.runtime.shell.Shell.execute(Shell.scala:183)
	at ca.uwaterloo.flix.runtime.shell.Shell.loop(Shell.scala:130)
	at ca.uwaterloo.flix.Main$.main(Main.scala:167)
	at ca.uwaterloo.flix.Main.main(Main.scala)

~~~

**Comment by magnus-madsen** [comment]
I tried a partial fix in #1054. Let us see if it helps.

**Comment by stephentetley** [comment]
Thanks Magnus, excellent - the tests on both `Logged` and my Stream now run.

**Comment by magnus-madsen** [comment]
I have merged in #1047. This is a step towards ensuring that top-level signatures are corrected matched against their expressions bodies. The implementation is not yet "fully correct", but this is an important step towards that. 

For example, the following is now rejected:

```
def f(): List[a] = 1 :: Nil
```

![image](https://user-images.githubusercontent.com/2287953/79329416-0fd85580-7f18-11ea-84a5-190498f33f65.png)

Let me know if you run into unexpected type errors and paste them here.

**Comment by magnus-madsen** [comment]
With #1061 we are now even closer to proper checking of top-level type signatures. We expect everything to work correctly now excepts types with effects in them. Work continues on that.

**Comment by magnus-madsen** [comment]
I know believe the issue with top-level signatures to be fixed. 

What remains is to ensure well-kinded types.

**Comment by stephentetley** [comment]
Hi Matthias 

I would expect your program to fail typechecking. Because `InterceptorFn` has a type (effect) parameter, `Interceptor` will need one as well:

~~~

pub enum Interceptor[e] {
  case Enter(InterceptorFn[e])
}

~~~

Flix doesn't have existential types so I don't think there is a way you can hide type parameters.

The error you posted isn't the clearest it could be - I think it has caused a compiler crash rather than properly caught the type error.

**Comment by mdiin** [comment]
Hi Stephen,

That makes sense. I will try it later. But yes, the error definitely does not hint at the problem. 🙂

Thanks!

**Comment by magnus-madsen** [comment]
@mlutze This looks related to what we are working on several PRs w.r.t. effects.

**Comment by magnus-madsen** [comment]
@mdiin You may want to try a nightly: https://flix.dev/nightly/

**Comment by magnus-madsen** [comment]
All major issues are resolved (Wohoo!)

Minor issues that remain:
- We still lack let-rec,
- Closures should not be moved across threads.

I plan to make a new PSA soon.
