### ISSUE TITLE
Add sortWith to List / Add unfolds to List, Map and Set

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#1052]
Hi Magnus

I've another small set of functions that would be good to add to the standard library.

`sortWith` for List is pretty self-explanatory. I've copied Haskell's `sortBy` implementation which according to comments in the code has pretty good performance.

`unfold` would be good for the growable collections (List, Map and Set).

While I've been looking at System functions, I've found a version of unfold - `unfoldWithIterator` - to be very useful. With "traditional" `unfold` you pass in both the iterating function and the initial state to iterate on, but with `unfoldWithIterator` you pass in a function that encapsulates the state itself. This is a natural fit to work with Java's iterators.

~~~

pub def unfold(f: s -> Option[(a, s)] & e, st: s): List[a] & e =

pub def unfoldWithIterator(next: () -> Option[a] & e): List[a] & e = 

~~~

This example shows `unfoldWithIterator` in action for `contents` the function that lists all the children (files and sub-directories in directory). The helper function `step` encapsulates the Java iterator:

~~~

/// One level - not recursive
pub def contents(path: FilePath): Result[List[FilePath], String] & Impure = try {
    import new flix.runtime.library.system.marshal.UnmarshalFilesList(##java.nio.file.Path) as newIter;
    import flix.runtime.library.system.marshal.UnmarshalFilesList.hasNext();
    import flix.runtime.library.system.marshal.UnmarshalFilesList.next();
    let FilePath(p1) = path;
    let iter = newIter(p1);
    let step = () ->
        if (iter.hasNext() == false)
            None
        else {
            let x1 = iter.next();
            Some(FilePath(x1))
         };
    Ok(List.unfoldWithIterator(step))
} catch {
    case _: ##java.lang.Exception => Err("contents")
}

~~~

I've used the Map version of `unfoldWithIterator` to build a Map of environment variables acquired calling Java's `System.getEnv()`.

That makes the additions: 

~~~

List.sortWith
List.unfold
List.unfoldWithIterator
Map.unfold
Map.unfoldWithIterator
Set.unfold
Set.unfoldWithIterator


~~~

I've a branch pretty much ready if you want me to make a pull request and we can discuss details there.

Thanks

**Comment by magnus-madsen** [comment]
Hello Stephen,

This looks great! 

I have not used unfolds that much -- so it took me a bit of time to understand the code -- but I really like the addition of `unfoldWithIterator` (or perhaps `unfoldWithIter` -- thinking of `mapWithAccum`). The example shows a very nice use case, I think.

> sortWith for List is pretty self-explanatory. I've copied Haskell's sortBy implementation which according to comments in the code has pretty good performance.

I am happy with any implementation that works.

We have a Red-Black tree that could also be used to sort, but I would guess that the fastest implementation would be to copy the entire collection to an array and then call Java's heavily optimized `Arrays.sort`. Unfortunately this will not work at the moment because we have no way to construct and pass an appropriate comparator object.

**Comment by stephentetley** [comment]
Thanks Magnus, I'll change to `unfoldWithIter` then there is a minor disassociation with Java's Iterator. Although I would be expecting to use `unfoldWithIter` with Java iterators you do have to do a bit of wrapping on the Flix side so it's not a direct call on an Iterator.

**Comment by magnus-madsen** [comment]
This can be closed right?

**Comment by stephentetley** [comment]
Yes
