### ISSUE TITLE
Unit Functions - Consistency 

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1079]
We currently have multiple ways to write unit functions and their types:

Types:
```
f: () -> Int
f: Unit -> Int
```

Lambdas:
```
() -> 42
x: Unit -> 42
```

Is this a problem? Which is preferred? Should one be removed?

**Comment by stephentetley** [comment]
I've a preference for `Unit` in type sigs and `()` in expressions. 

I don't know if there's any virtue to this preference, it's just what I've become used to in F#. Haskell uses `()` for both, but `()` isn't pervasive in expressions with Haskell being lazy.

**Comment by magnus-madsen** [comment]
> I've a preference for `Unit` in type sigs and `()` in expressions.

Me too. 

We could enforce this. On the other hand, the current design is very regular. You can write: `() -> Int` to go with your `() -> 42`. Ill leave the ticket open for now.

**Comment by magnus-madsen** [comment]
I think the status quo is acceptable.
