### ISSUE TITLE
Explore Regex Support

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1081]
We should explore language level support for regular expressions.

For example, we could verify the correctness of patterns at compile-time instead of at run-time.

**Comment by mlutze** [comment]
Could we expand this to more general compile-time validation of "magic strings" through macros? Kinda similar to Scala [string interpolation](https://docs.scala-lang.org/overviews/core/string-interpolation.html), but validated at compile time. For example, a programmer could define an `id` magic string like `id"myId123x` and a macro/validator that ensures it's a proper identifier and perhaps converts it to the proper type.

**Comment by magnus-madsen** [comment]
We could, but we would need a couple of components:

- A macro language (probably a subset of the Flix language?).
- An interpreter for the macro language.
- A termination checker.
- A mechanism to ensure that the macro language is pure (Yay, we have that already!)

I think in long term such features could arrive, but probably not in the short term.

User-defined string interpolators in Scala have been widely advertised, but I don't think they have been widely used....

Maybe we should just focus on having one expressive built-in string type with interpolation support?

As for regex support. Yah, it does sound like this would be an unprincipled add-on, so I don't know. We could also try to lift it to some general regex support on any type, but that seems complicated and probably unnecessary.

Maybe- on our way to a complicated scheme like in the above bullet point list- we could just have some notion of "statically validated constants" and use a subset of the Flix language to perform such validation. This could then later become a more expressive macro system.

For example (with some invented syntax):

```
validateMyRegex("foo")
validateMyTemperatureInKelvin(300)

def validateMyRegex(s: String): Result[String, CompilerErrorMessage] = ...
def validateMyTemperatureInKelvin(i: Int32): Result[Int32, CompilerErrorMessage] = ...
```

**Comment by magnus-madsen** [comment]
Or, of course, if you prefer:

```
let regex = validateMyRegex"foo"
let temp = validateMyTemperatureInKelvin"300"
```

**Comment by magnus-madsen** [comment]
Basic support available in master.
