### ISSUE TITLE
Ensure that all Fold, Reduce, and Scan Functions are Effect Polymorphic

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1087]
Ensure that every fold/reduce and scan function is effect polymorphic.

For example:

```
pub def reduceLeft(f: (a, a) -> a & e, xs: List[a]): Option[a] & e
```

is the right signature for `List.reduceLeft`.

**Comment by magnus-madsen** [comment]
@esbenbjerre Can you take a look at this next?

**Comment by esbenbjerre** [comment]
For types such as Array and MutMap which are inherently impure, we want to keep fold, reduce and scan impure regardless of the purity of the function argument, right?

**Comment by magnus-madsen** [comment]
Right, so they accept effect polymorphic functions, but the function *itself* is always pure.
