### ISSUE TITLE
Add @deprecated annotation

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1110]

**Comment by mlutze** [comment]
What's the expected behavior when someone uses a deprecated function, given the principle "No warnings, only errors"?

I imagine the advantage here vs just removing deprecated functions is that a failed compilation could contain a deprecation message about what to use instead. Is that what we're going for?

**Comment by magnus-madsen** [comment]
It is a very good point. Maybe its the one exception that confirms the rule?

**Comment by magnus-madsen** [comment]
IIIRC someone on Reddit also suggested the same problem with the "no warnings, only errors" rule.

**Comment by magnus-madsen** [comment]
> 
> 
> What's the expected behavior when someone uses a deprecated function, given the principle "No warnings, only errors"?
> 
> I imagine the advantage here vs just removing deprecated functions is that a failed compilation could contain a deprecation message about what to use instead. Is that what we're going for?

I had an idea... which essentially side-steps the issue: We keep the notion that the compiler only has errors. A deprecation annotation is nothing more than a comment. It is a special form of comment that can be processed by the compiler (or a future language server), but it is not a warning, and it is not something that will show up by default. 

For example, we also have `@test` and this only does something when the compiler is invoked with `--test`.

**Comment by mlutze** [comment]
> Maybe its the one exception that confirms the rule?

I personally don't like the idea of compromising one of the principles for the sake of the deprecation annotation.

> It is a special form of comment that can be processed by the compiler (or a future language server), but it is not a warning, and it is not something that will show up by default.

This seems more appropriate to me. Would we also have a compiler flag `--throw-an-error-when-we-use-something-marked-as-deprecated`?

**Comment by magnus-madsen** [comment]
I think we should just view deprecations as meta-data that an IDE (e.g. through LSP) can expose. The compiler is not going to care much, but it might have a flag to print all functions that are deprecated.
