### ISSUE TITLE
java.lang.StackOverflowError in List.sortWith around 2^12 elements

### ISSUE THREAD

**Issue by esbenbjerre** [flix/flix#1119]
List.sortWith crashes with
```bash
Exception in thread "main" java.lang.StackOverflowError
	at Clo$sortMerge$39657$41776.invoke(Unknown Source)
```

2^11 elements goes OK, but 2^12 elements overflows the stack.

The code used
```
def main(): Unit & Impure =
    let n = 1 <<< 12; /// 2^12
    let elements = randomArray(n);
    let list = Array.toList(elements);
    let _ = List.sortWith((x, y) -> x <=> y, list);
    Console.printLine(Int32.toString(n));
    ()

/// Creates an array of size n with elements 0..n-1
def increasingArray(n: Int32): Array[Int32] & Impure = increasingArrayHelper(n, 0, [0; n])

/// Creates an array of size n with elements 0..n-1 in random order
def randomArray(n: Int32): Array[Int32] & Impure = fisherYatesShuffle(n - 1, increasingArray(n))

/// Helper function for `increasingArray`
def increasingArrayHelper(n: Int32, i: Int32, a: Array[Int32]): Array[Int32] & Impure =
    if (i < n)
        increasingArrayHelper(n, i + 1, Array.put(a, i, i))
    else
        a

/// Fisher-Yates shuffle
def fisherYatesShuffle(i: Int32, a: Array[Int32]): Array[Int32] & Impure =
    if (i > 1)
        let random = Random.new();
        let j = Random.nextNatWithMax(random, i + 1);
        let ith = a[i];
        let jth = a[j];
        Array.put(a, i, jth);
        Array.put(a, j, ith);
        fisherYatesShuffle(i - 1, a)
    else
        a
```

**Comment by stephentetley** [comment]
Thanks 2^12 (4096) isn't all that large, so a sort in the standard library should be expected to handle that.

I'll look at rewriting it in CPS over the weekend

**Comment by stephentetley** [comment]
With a CPS version, it's worked on n = 4096000.

I'll make a patch.

**Comment by stephentetley** [comment]
I've made a PR

**Comment by mlutze** [comment]
I think this sort of thing should ideally by caught by tests. Should we have more extensive testing of large collections?

**Comment by magnus-madsen** [comment]
> 
> 
> I think this sort of thing should ideally by caught by tests. Should we have more extensive testing of large collections?

We have lots of tests for the standard library (in the thousands) but we don't have tests on large inputs. We could add such tests, but a downside is that they take longer to run.

**Comment by mlutze** [comment]
IMO it's worth the tradeoff. I expect most devs would only run the whole test suite once before pushing, so I don't think it would slow development too much. I don't think we should have to wait for a user to discover such a bug before we do.

Maybe we could have a separate suite of tests specifically for load testing?

**Comment by Herbstein** [comment]
Tangentially related: I have a `LocalSuite` test class that I run. I configure it to only contain the classes I'm actually touching at any given point in time. It means I get to run the full test suite when adding to e.g. `List` and `Result` without having to run the big suite for the whole standard library.

**Comment by esbenbjerre** [comment]
I think this issue should be closed. We can continue any discussion related to extending the tests to cover large collection sizes can continue in a separate issue, @magnus-madsen?

**Comment by magnus-madsen** [comment]
Right. We can open a separate ticket.
