### ISSUE TITLE
Nightly Builds

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1126]
It would be useful if we could have nightly builds published somewhere.

**Comment by magnus-madsen** [comment]
https://flix.dev/nightly/

**Comment by magnus-madsen** [comment]
We should update the website to have this link somewhere appropriate.

**Comment by Herbstein** [comment]
Doing this should be possible to automate using [Github Actions](https://github.com/features/actions)

**Comment by magnus-madsen** [comment]
I should look into that. Right now I just run a script on a server to build the jar with gradle.
