### ISSUE TITLE
Add Support for Open Enums

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1132]
Add support for open enums:

```
open enum IOError {
  ...
}
```

which are simply like ordinary enums except that they cannot be exhaustively matched unless the last case is a wildcard.

**Comment by Herbstein** [comment]
The rendered RFC text for the Rust feature is readily available. 

https://github.com/rust-lang/rfcs/blob/master/text/2008-non-exhaustive.md

**Comment by mlutze** [comment]
[This paper](https://www.informatik.uni-marburg.de/~kos/papers/gpce06.pdf) describes a technique for using type classes to achieve something like an open enum result. I've reproduced the example in Flix below.

Intuitive implementation:
```scala
enum Expr {
  case Lit(Int)
  case Plus(Expr, Expr)
  // want to add `case Minus(Expr, Expr)` but this would break stuff everywhere else
}

def eval(e: Expr): Int = match e {
  case Lit(i) => i
  case Plus(e1, e2) => eval(e1) + eval(e2)
}
```

Extensible implementation:
```scala
class Expr[x]

enum Lit {
    case Lit(Int)
}

enum Plus[a, b] {
    case Plus(a, b)
}

instance Expr[Lit]

instance Expr[Plus[a, b]] with Expr[a], Expr[b]

lawless class Eval[a] with Expr[a] {
    pub def eval(x: a): Int
}

instance Eval[Lit] {
    pub def eval(x: Lit): Int =
        let Lit(i) = x;
        i
}

instance Eval[Plus[a, b]] with Eval[a], Eval[b] {
    pub def eval(x: Plus[a, b]): Int =
        let Plus(y, z) = x;
        Eval.eval(y) + Eval.eval(z)
}

/// adding a new instance

enum Minus[a, b] {
    case Minus(a, b)
}

instance Expr[Minus[a, b]]

instance Eval[Minus[a, b]] with Eval[a], Eval[b] {

  pub def eval(x: Minus[a, b]): Int32 = 
        let Minus(y, z) = x;
        Eval.eval(y) + Eval.eval(z)

}
```

It ends up being fairly verbose, of course

**Comment by magnus-madsen** [comment]
I know the arguments from Rust, but I am not convinced. I need someone to convince me first then we can consider it.
