### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1133]
On recent PRs there have been some comments on code style in Flix, indicating that we have an idea of how code should be formatted, but we don't have guidelines documented anywhere.

We should consider maintaining a style guide to codify some general standards. This could also have LSP support (?)

Related: [Code Formatter](https://github.com/flix/flix/issues/1098)

**Comment by magnus-madsen** [comment]
Yes, this is a great idea.

**Comment by magnus-madsen** [comment]
We now have `STYLE.md`.
