### ISSUE TITLE
Add Support for Record Shorthand?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1134]
For example:

```
let fstName = "Lucky";
let lstName = "Luke";
{ fstName, lstName }
````

**Comment by mlutze** [comment]
I'm conflicted about this idea: we'd be tying the name of variables into the types, which I think is definitely atypical and may invite trouble. The syntax might get sticky as well. Is `{ x }` a code block or a singleton record?

I guess this is to avoid having to do `{ fstName = fstName, lstName = lstName }` which I imagine would be a rather common pattern, so I see that it would have its uses.

**Comment by magnus-madsen** [comment]
Ah, you make a good point. Especially because `{ e }` right now just means the expression `e`. And `{ x }` would then mean the expression with variable `x`. So maybe this is bad.

**Comment by magnus-madsen** [comment]
Options:
- Leave it as is.
- Allow short hand, but only if there are multiple fields, e.g. `{ fstName, lstName }`
- ???

Probably leaning towards leaving it as-is.

**Comment by magnus-madsen** [comment]
OK, this is not going to work. I will close it for now. If someone comes up with a good idea, we can always revisit.
