### ISSUE TITLE
Remove assert!, assertEq!, and assertNot! From Prelude

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1136]

**Comment by magnus-madsen** [comment]
(Note to self: We can remove ProcessPanic once this ticket is fixed)

**Comment by stephentetley** [comment]
I'm happy to chip away at the test modules - I've just done TestOption, TestResult and TestList.

I'll make a PR for the ones I get through today this evening.

**Comment by magnus-madsen** [comment]
Very cool!

**Comment by stephentetley** [comment]
TestPrelude isn't in a namespace and doesn't have the copyright notice Apache license...

Do you want me to add it?

**Comment by magnus-madsen** [comment]
> 
> 
> TestPrelude isn't in a namespace and doesn't have the copyright notice Apache license...
> 
> Do you want me to add it?

Yes, please add the copyright header.

**Comment by stephentetley** [comment]
Do I back date it to 2016 when the file was first in the repo?

**Comment by magnus-madsen** [comment]
I am not sure. I think it is fine to put this year too.

**Comment by stephentetley** [comment]
Hi Magnus - I've made a PR removing asserts from the `language/feature` tests.

After that, I think only the definitions themselves plus a benchmark file `BenchmarkList.flix` remain.

**Comment by magnus-madsen** [comment]
> After that, I think only the definitions themselves plus a benchmark file `BenchmarkList.flix` remain.

Sounds good. I guess we are ready to remove the definitions then.

I was reading the History of F# and Standard ML paper and I am looking forward to having a clean prelude. It seems to be a common trend among languages that the prelude gets filled with all kinds of functionality that was needed at some point, but did not fit anywhere else. I hope we can avoid that :)
