### ISSUE TITLE
Disallow Duplicate Fields in Records

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1139]
And change the backend to generate more efficient code.

We keep the type system as is, like in Elm.

**Comment by mlutze** [comment]
Can this be done keeping the type system as-is? It seems to me we'll need a new "negative" RecordExtend to ensure fields are not duplicated:

```
val a = { x = 1 | b } 
// b's type must be a record without "x"
// b : { -x | _ }
```

**Comment by magnus-madsen** [comment]
Yes. This can be done by a check post type checking. This is how Elm does it (among others).

**Comment by mlutze** [comment]
I think Elm's case is different since they do not allow addition of fields to records.

Consider:
```elm
{-- Elm --}

setName r = {r | name = "NewName"}
setName { name = "OldName" } -- OK
setName { } -- Fails because no name field
```

```flix
// Flix

// Using RecordAssign
def setName(r: { name: String | t }): { name: String | t } = { name = "NewName" | r }
setName({ name = "OldName" }) // OK
setName({ }) // Fails because no existing name field

// Using RecordExtend
def addName(r: { | t }): { name: String | t } = { +name = "NewName" | r }
addName({ name = "OldName" }) // Should now fail, so type `t` is inferred to be { -name: String | _ }
addName({ }) // OK
```

If I'm missing something, do you have a source/reference for how Elm does it?

**Comment by magnus-madsen** [comment]
![image](https://user-images.githubusercontent.com/2287953/82865466-10a4d400-9f27-11ea-8a96-651c987fabe0.png)

From the paper we have been reading.

I think this means the following: After type checking, go through the AST. If we see a type that is a record and it has duplicated fields then issue a compile-time error.

**Comment by magnus-madsen** [comment]
No changes planned for now.
