### ISSUE TITLE
Minimal Prelude

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1147]
Membership of the Prelude confers God-like status on a function: it is imported everywhere and its name is almost like a keyword. So, I want to cleanup the Prelude a bit :)

Keep:

 - `identity`
- `constant`
- `flip`
- `curry`
- `uncurry`
- `fst`
- `snd`
- `swap`
- `>>`
- `|>`
- `||>`

(Of these, I am also partial towards removing `curry`, `uncurry`, `flip`, and `swap`.)

Move:

- `isNull` -> `Object.isNull` (or similar namespace)?

Remove:

- `pub enum Void { }`
- `<<` (dead along with his friend `<|`)
- `assert!`
- `assertNot!`
- `assertEq!`

Other:

- Laws will be refactored at some point in the future.
- Equality on tuples (etc) will be replaced by type class instances in the future.

If I am removing someone's favorite Prelude function, please speak up :)

Note: I have nothing against a particular function. We should just try to move them to appropriate namespaces.

**Comment by stephentetley** [comment]
I did quickly notice there was no compose (aka `<<`) in the new prelude. Maybe a `Combinators` module might be a natural home for `curry`, `uncurry`, `<<` etc.

I wonder if it's time to look at a hierarchical name-spacing?

Some of the libraries I've been working on (Time, Regex, ...) have been making me think the top level namespace could get crowed quite soon.

**Comment by magnus-madsen** [comment]
> 
> 
> I did quickly notice there was no compose (aka `<<`) in the new prelude. Maybe a `Combinators` module might be a natural home for `curry`, `uncurry`, `<<` etc.

Yes, I removed `<<`  earlier yesterday. We should definitely consider an extended prelude for such useful functions. 

> 
> I wonder if it's time to look at a hierarchical name-spacing?
> 

Yes, I think we are slowly moving in that direction.
