### ISSUE TITLE
Add String.contains

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1174]
Are we really missing this function? :)

**Comment by stephentetley** [comment]
No - it is `isInfixOf`.

`contains` is certainly a better name by itself, but `isInfixOf` is accompanied by `IsSuffixOf` and `isPrefixOf`. 

I did notice last week that String is missing a `compare` function and I think Char is too.

**Comment by stephentetley** [comment]
As String also has `startsWith` and `endsWith` there is a good argument for adding `contains`, and potentially removing `isInfixOf`, `isPrefixOf` and `isSuffixOf`.

**Comment by magnus-madsen** [comment]
> 
> 
> As String also has `startsWith` and `endsWith` there is a good argument for adding `contains`, and potentially removing `isInfixOf`, `isPrefixOf` and `isSuffixOf`.

Ah I see. I think that makes sense [to rename to contains and remove isPrefixOf and isSuffixOf]. 

List also has isPrefixOf and isSuffixOf. Should we rename those as well?

**Comment by stephentetley** [comment]
Yes for names go with `startsWith`, `endsWith` and `contains` and remove the others.

For argument order use the UFCS convention then infix and UFCS work sensibly e.g:

~~~

"Long string" `startsWith` "Long" == true

~~~

**Comment by magnus-madsen** [comment]
And 

```
"Long string".startsWith("Long") == true
````

works too

**Comment by magnus-madsen** [comment]
If the plan is:

- `isPrefixOf` ->`startsWith`
- `isInfixOf` -> `contains`
- `isSuffixOf` -> `endsWith`

Then what about:

- `Set.memberOf` etc?

And what about `List` which has both `isInfixOf` and `memberOf`?

I think part of this discussion goes to the question of whether we want to have aliases or at least some kind of "forwarders" like in #1033.

**Comment by stephentetley** [comment]
Hmmm - this becomes a bit more difficult when you consider other modules.

If you had a "contains" predicate on a Set I think it would be natural for it to test a for single element. But "contains" on a String would be natural to test for a substring (testing if a single char is in a string feels like something I would do  very rarely, I wouldn't want to waste a "prime" name on it). 

Also some names only make sense for UFCS ordered functions and vice versa...

I wonder if we should treat String as a special case because its not a really collection type?

**Comment by magnus-madsen** [comment]
Good points. I am now inclined to just change:

- `isPrefixOf` ->`startsWith`
- `isInfixOf` -> `contains`
- `isSuffixOf` -> `endsWith`

for `String` and not touch any other modules.

**Comment by magnus-madsen** [comment]
@esbenbjerre Can I ask you to make the three changes outlined in the last post? Thank you

**Comment by esbenbjerre** [comment]
Is dot-notation broken for strings?
``def main(): Bool = "yes".contains("e")

-- Resolution Error -------------------------------------------------- main/src/library/Playground.flix

>> Undefined name 'contains'.

1 | def main(): Bool = "yes".contains("e")
                             ^^^^^^^^
                             name not found
```

**Comment by magnus-madsen** [comment]
Yes, it has to be in scope. It is equivalent to `contains("e")` so you have to `use` it.
