### ISSUE TITLE
Refactor Type.Arrow to be a Type Constructor

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1203]
Question: Where should we put the effect?

**Comment by mlutze** [comment]
One (possibly overly-complex) option to address the effect question would be to introduce another type constructor & kind:

```
// type constructor ::: kind
IncompleteArrow(3) ::: * -> * -> * -> IncompleteArrow
CompleteArrow ::: Effect -> IncompleteArrow -> Arrow
```

I think it would actually be more complex than that since we'd need Arrow to store arity, but that might be a start.

**Comment by magnus-madsen** [comment]
We need the arrow to story the arity regardless.

I am thinking of just putting the effect last, so it goes: `arg1, arg2, ... argn, resultType, effect`.

**Comment by magnus-madsen** [comment]
Fixed in master. Thanks @mlutze !
