### ISSUE TITLE
Kind Variables

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1205]
As part of #999, I'd like to experiment with introducing kind variables.

The `Unbound` kind doesn't seem to work. Kind variables seem like the most "correct" solution.

Kind variables would require
* `Kind.Var(id: Int)`
* `KindUnification`
* Kind subsititution (probably as an extra map in `Substitution`

**Comment by magnus-madsen** [comment]
I think we can close this too? :)

**Comment by mlutze** [comment]
Yes!
