### ISSUE TITLE
List.length is not tail recursive

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#1226]
List.length is not tail recursive and bursts the stack on long lists. 

The simplest solution is a using a worker function with an accumulator:

~~~

pub def length(xs: List[a]): Int32 = lengthHelper(xs, 0) 

def lengthHelper(xs: List[a], ac: Int32): Int32 = match xs { 
    case _ :: rs => lengthHelper(rs, ac + 1)
    case Nil => ac
}

~~~

Or we could use a summing fold.

**Comment by magnus-madsen** [comment]
Yes. Amazing we have not caught this before :)

**Comment by stephentetley** [comment]
The upshot is my parser combinator library can now parse files (c. 14000 lines) where this becomes apparent.

**Comment by stephentetley** [comment]
Hi Magnus

I'm making a PR to add `sequence` and `transpose` to Result (and maybe change the versions in Option to be tail recursive / in CPS).

Do you want me to List.length in the PR?

**Comment by magnus-madsen** [comment]
> Do you want me to add the change to List.length in the PR?

Sure, that is fine. Thanks!

**Comment by magnus-madsen** [comment]
Fixed, but the general question of tail recursion remains.
