### ISSUE TITLE
Add "where/with" clause to Function Definitions?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1230]
With the upcoming nullity constraints, we might want to write something like:

```scala
def f(r: {ssn: String ? n, name: String? (not n or n2)}): String = ...
```

which, while hard to read, simply means: Give me a record where `ssn` and and `name` are not both simultaneously `null` (i.e. at least one is present, i.e. one of `ssn` or `name` must have `false` nullity). 

This ticket considers whether it would be easier to read an equivalent signature such as:

```scala
def f(r: {ssn: String ? n1, name: String? n2}): String where (n1 nand n2) = ... // or with (?)
```

which again expresses the same idea: We must have at least one of `ssn` or `name` be non-null.

**Comment by magnus-madsen** [comment]
Implementation plan:

Extend a Scheme with a side condition (a type).

During resolution, in the resolver, call BoolUnification on the side condition (= T).
- If it has no solution => Immediately bail with an inconsistency error.
- If it has a solution then get the mgu subst. apply it to the base

Challenge: The quantifiers may change (or grow). How can we handle that correctly?

**Comment by mlutze** [comment]
I'd like to visit this again, as I have some type-level programming I'm experimenting with, and this would help a lot.
