### ISSUE TITLE
Add String.capitalize / String.uncapitalize?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1234]

**Comment by magnus-madsen** [comment]
Before you write any code, give a quick description of how you intend to implement it. For inspiration try to take a look at other librarys (e.g. lodash, underscore from JavaScript) or what else you can find :)

The idea is to discuss an existing implementation before we try to implement it in Flix.

**Comment by ninaandrup** [comment]
`String.capitalize` would be easy to do as [underscore does it](https://github.com/esamattis/underscore.string/blob/master/capitalize.js)
```
String.toUpperCase(String.charAt(0, s)) + sliceRight(1, s)
```
Using the `toUpperCase` on the first character, and then concatenating with the rest of the string without this first character.

**Comment by magnus-madsen** [comment]
But it should also uppercase subsequent words right?

**Comment by ninaandrup** [comment]
So doing something like checking for spaces using `String.indices` first maybe, and then making every following character of a space uppercase?

**Comment by magnus-madsen** [comment]
I think we should find a reference implementation somewhere that we can be inspired by :)

**Comment by magnus-madsen** [comment]
Decided to close this because I see several ways it can be implemented, but not which one is the one a programmer would expect.
