### ISSUE TITLE
Add String.deburr?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1236]
http://hackage.haskell.org/package/deburr-0.1.0.1/docs/Text-Deburr.html

**Comment by stephentetley** [comment]
I had a quick look at doing this with `java.text.Normalizer` as suggested in the link below, but the equivalent code in Flix (calling the same Java functions) didn't work whereas an all Java prototype did.

https://stackoverflow.com/questions/3322152/is-there-a-way-to-get-rid-of-accents-and-convert-a-whole-string-to-regular-lette

I'll have to did deeper into the actual string data in Flix to see if the input was equal.

**Comment by magnus-madsen** [comment]
Before you write any code, give a quick description of how you intend to implement it. For inspiration try to take a look at other librarys (e.g. lodash, underscore from JavaScript) or what else you can find :)

The idea is to discuss an existing implementation before we try to implement it in Flix.

**Comment by magnus-madsen** [comment]
(Comment was for Nina)

**Comment by magnus-madsen** [comment]
Also too esoteric.

**Comment by stephentetley** [comment]
I'd forgotten about it, but I wrote the code here:

https://github.com/stephentetley/flix-sandbox/blob/master/src/FlixSandbox/Text/Normalizer.flix
