### ISSUE TITLE
Add log and factorial function to Int32

### ISSUE THREAD

**Issue by esbenbjerre** [flix/flix#1246]
This ticket is related to #746.
The logarithm and factorial functions are needed in order to express the time and space complexity of certain functions.

**Comment by magnus-madsen** [comment]
@esbenbjerre Do you want me to do it or do you want to take a stab at it yourself? :)

**Comment by esbenbjerre** [comment]
> @esbenbjerre Do you want me to do it or do you want to take a stab at it yourself? :)

Already implemented :)
PR is #1247.

**Comment by mlutze** [comment]
Should we have the same function for the other `Int` types?

**Comment by magnus-madsen** [comment]
> Should we have the same function for the other `Int` types?

I think that makes sense. 

This particular ticket was just because Esben needed the ability to express log2 for some complexity annotations.

**Comment by mlutze** [comment]
I think we should also consider returning `Option`s for these since the functions are not defined for negative numbers. That would require some extra consideration of how to handle that for the annotations.

**Comment by magnus-madsen** [comment]
> 
> 
> I think we should also consider returning `Option`s for these since the functions are not defined for negative numbers. That would require some extra consideration of how to handle that for the annotations.

Maybe. but that is just .. painful. But I get your point. Alternatively, we can return 0 like we do for division by zero?

**Comment by mlutze** [comment]
Yeah I think that would be better than returning a "wrong" answer or looping infinitely. This might be a good case for liquid types when/if those are implemented.
