### ISSUE TITLE
Naming convention for "ignoring" functions

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#1256]
`traverse` on lists of Option[a] and Result[a, err] is a valuable function and we have it in the standard library, but the "ignoring" version is very useful to perform an effectful action on the input list items and fail with short-circuiting if an individual action fails:

~~~

/// Result version
pub def traverse_(fn: a ~> Result[Unit, e], xs: List[a]): Result[Unit, e] & Impure = match xs { 
    case x :: rs => match fn(x) {
        case Ok(_) => traverse_(fn, rs)
        case Err(e) => Err(e)
    }
    case Nil => Ok() 
}

/// Option version
pub def traverse_(fn: a -> Option[b] & f, xs: List[a]): Option[Unit] & f = match xs { 
    case x :: rs => match fn(x) {
        case Some(_) => traverse_(fn, rs)
        case None => None
    }
    case Nil => Some() 
}

~~~

What convention should we use to indicate that these functions are called to run their effect and ignore their answers?

In Haskell the convention is to use an underscore suffix as above.

In Flix we already have a convention to use "!"as a suffix  for imperative functions. At the moment, I'd say "!" connotes destructive update rather than a more general idea of the function being imperative, but if we were against introducing another suffix symbol then `traverse!` would make sense.

Thoughts everyone?

**Comment by magnus-madsen** [comment]
I like this idea. Let me think about the naming.

Is there are particular reason why `traverse_` for Result takes an impure function but `traverse_` for  Option requires an effect polymorphic function?

**Comment by stephentetley** [comment]
Yes, `Result.traverse_` should be effect polymorphic. It was only fixed to Impure because I originally wrote it that way.

**Comment by magnus-madsen** [comment]
I thought some more and I have a few simply comments:

1. I think these functions are useful to have.
2. I am not too sold on using `_` in the name. I thought that if this was convention in Haskell I could live with it, but I have now come to learn that `_` is actually used for several things in Haskell. Naming is hard, but let me throw out some suggestions:  `traverseOne`, `traverseFirst`, `traverseUntilErr`, `traverseOk`. Maybe this can inspire some better suggestions.
3. I am okay with a naming convention that uses `traverse_` until we come up with a better idea.

**Comment by stephentetley** [comment]
There is also a convention in Haskell for `exec` as a prefix for running something for it's effect e.g. 

~~~

-- Data.Binary.Put
execPut :: PutM a -> Builder

-- Control.Monad.State
execState :: State s a -> s	-> s	

~~~

But the things being executed are generally "objects" that wrap functions rather than functions directly. Adopting it as a convention for functions potentially hides their "discoverability" as they are no longer close alphabetically.

~~~

pub def execTraverse(fn: a -> Result[b, e] & f, xs: List[a]): Result[Unit, e] & f =

~~~

Flipping it to `traverseExec` doesn't seem indicative of anything much, but it did make me think a mnemonic version `traverseX` is quite cute.

**Comment by magnus-madsen** [comment]
I am fine with `traverseX`. As you say, it is discoverable (e.g. by auto-complete) and it avoids `_` which is usually used for other things.

**Comment by stephentetley** [comment]
Thanks Magnus - good timing I'm just preparing a PR...

**Comment by magnus-madsen** [comment]
Fixed?

**Comment by stephentetley** [comment]
Yes.
