### ISSUE TITLE
Disallow type / variable collision ?

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1257]
Currently we allow declarations such as the following:
```
def id(a: a): a = a
```

`a` refers to both the parameter and its type, which seems like it might lead to confusion.

Should we detect this and throw an error?

**Comment by magnus-madsen** [comment]
I think it could be confusing, but I would not (yet) rule it out.

In Flix terms and types are separate, so you can syntactically tell if a variable is a term or type variable. 
There is no ambiguity (except possibly in the mind of the programmer).

However, we do already disallow *type variables* with suspicious names. For example:

```
def f(x: int32): Unit = ()
```

```
-- Name Error -------------------------------------------------- ???

>> Suspicious type variable 'int32'. Did you mean: 'Int32'?

1 | def f(x: int32): Unit = ()
             ^^^^^
             Suspicious type variable.


Tip: Type variables are always lowercase. Named types are uppercase.
```

**Comment by stephentetley** [comment]
I'd like to think a (hypothetical) Flix Lint would flag this up as a bad style, I'm not sure about it being a compiler error.

**Comment by magnus-madsen** [comment]
Yeah, I agree. We can always tighten it a bit later. I will leave the ticket open.

**Comment by magnus-madsen** [comment]
We are going to keep allowing this-- for now.

We may tidy the standard library a bit in the future.
