### ISSUE TITLE
Add `singleton` and `cons` to Nel

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#1259]
Hi Magnus 

As I've been preparing a PR to add `traverse_` to Result, Option and Validation, I noticed Nel doesn't have functions for `cons` (i.e. `::` on List) and `singleton` to produce an initial, one element Nel.

~~~

    ///
    /// Returns a new non-empty list containing the single element `x`.
    ///
    pub def singleton(x: a): Nel[a] = Nel(x, Nil)

    ///
    /// Returns `xs` prefixed with the new element `x`.
    ///
    pub def cons(x: a, xs: Nel[a]): Nel[a] = match xs {
        case Nel(y, ys) => Nel(x, y :: ys)
    }

~~~

As it happens I was wrong thinking I needed them to write `Validation.traverse_` - but would they be worthwhile adding anyway?

At present the implementation details of Nel "leak" into user code if you want this functionality.

**Comment by magnus-madsen** [comment]
I think we should have both. 

> At present the implementation details of Nel "leak" into user code if you want this functionality.

You mean that you would have to write something like `cons` yourself working with the constructor explicitly?

**Comment by magnus-madsen** [comment]
Yes, that is a good point. I buy it.

Question is, should it be called `cons`? Rich Hickey would call it `conj` and then allow it for `Set`, `Map`, etc. Thoughts?

**Comment by stephentetley** [comment]
Oh, I definitely prefer `cons` over `conj`.

There was a fairly recent debate on the Haskell Libraries mailing list which I think prevented adding `singleton` to Data.List but I think the feeling was that `[1]` was direct enough. With Flix's Nel we don't have that syntax sugar.

**Comment by magnus-madsen** [comment]
Fixed in master.
