### ISSUE TITLE
Error message API

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1261]
Currently some parts of error messages are ad-hoc; common patterns are handwritten.

```scala
    def message: VirtualTerminal = {
      val vt = new VirtualTerminal
      vt << Line(kind, source.format) << NewLine
      vt << ">> Definition '" << Red(sym.toString) << s"' is not accessible from the namespace '" << Cyan(ns.toString) << "'." << NewLine
      vt << NewLine
      vt << Code(loc, "inaccessible definition.") << NewLine
      vt << NewLine
      vt << Underline("Tip:") << " Mark the definition as public." << NewLine
    }
```

I'm wondering if we could make `tip` and `possibleFixes` and maybe other common patterns into methods or otherwise automate/codify the formatting further. This might enforce a more uniform messaging format.

**Comment by magnus-madsen** [comment]
We should look into this. Do you have any ideas for an API?

I am also a bit dissatisfied with the way colors are handled. 

It may be that we should not put too much effort into this until the VSCode extension is on the way. Then that can help us drive a "refresh" of error messages.

**Comment by mlutze** [comment]
Moving to a more declarative style and letting consumers handle formatting seems the right way to go, especially considering the VSCode extension.

Maybe we could move the virtual string formatting to context-ambivalent annotation such as `highlight`, `distinct1`, `distinct2`.

Then our error trait could look something like:

```scala
trait CompilationError {
   ... the other fields ...
   def message: VirtualString
   def tip: Option[VirtualString]
   def possibleFixes: Option[VirtualString]
  ... any other common patterns? ...
}
```

Using `VirtualString`s instead of `VirtualTerminal`s for more portability.

**Comment by mlutze** [comment]
Perhaps "possible fixes" could be made more abstract so that an IDE could map the fixes to automatic actions.

**Comment by magnus-madsen** [comment]
For now, I am actually going to propose we take a step in the opposite direction:

We should replace all error messages by a single string. 

This string should be able to contain some form of markup, for example:

```
"
Definition <emph>foobar</emph> is not accessible from the namespace <emph>baz</emph>
"
```

Then, this string can be formatted to: (1) strip out all markup, (2) to be printed to the terminal, (3) to be printed to VSCode, or (4) to be shown on the web.

As for "tips" and "possible fixes". The former would just be part of the error message. The latter requires a much deeper integration into the compiler. Moreover, fixes to actual errors (i.e. program repair) is often difficult. And you can have program fixes without having a compiler error. So I would want to keep these two completely separate.

**Comment by mlutze** [comment]
By moving in the opposite direction, we lose some compile-time safety of markup. For example, a missed closing tag could go uncaught, plus escaping can be a pain.

I think using a raw string with tags as a serialized format is ok, but that we should hold onto the type safety where it's reasonable to do so.

**Comment by magnus-madsen** [comment]
> By moving in the opposite direction, we lose some compile-time safety of markup. For example, a missed closing tag could go uncaught, plus escaping can be a pain.

Yes.

I am a huge fan of type safety. But I think in this case the loss is small. If we make such a mistake you will still be able to see the compiler error (just with some extra tag in it) and its easy to fix. 

What I want  to have is a uniform interface that can output rich errors both to the terminal and to VSCode- and I think this VirtualTerminal is just too cumbersome.

**Comment by mlutze** [comment]
If we want an HTML-style markup, could use Scala's built-in XML literals? I think that would provide some compile-time validation while still being highly expressive.

**Comment by magnus-madsen** [comment]
I think XML literals are deprecated and going away. I don't really want a very rich markup language, just colors. 

We could try to design some mini DSL ourselves, but I don't think it will be worth it. It would probably end up looking like our VirtualTerminal thing.

Right now, VSCode+LSP does not even support colors in diagnostics, so best we can hope for is something like:

![image](https://user-images.githubusercontent.com/2287953/93872604-ad5a6100-fcd0-11ea-95c4-f20f799497be.png)

But it would be nice if VSCode would show the full error message (not just the summary) as we have now.

**Comment by magnus-madsen** [comment]
And I am pretty sure that-- down the road-- LSP will get some form of markdown diagnostic.

**Comment by magnus-madsen** [comment]
Ironically I have been arguing that quick fixes are not really applicable to compiler errors and then I show you the one example where it would actually be useful. 

Anyway, I still *think* that if you were to go over all the compiler errors (50+?) very very few of them have obvious applicable fixes.

**Comment by magnus-madsen** [comment]
So, it turns out that VScode only supports single-line error messages (!)

There is a ticket and many people are waiting on the situation to improve.

When that happens, I will revisit this. Until then I plan to leave it as-is.

**Comment by magnus-madsen** [comment]
The outcome of this ticket is: https://github.com/flix/flix/issues/2435 which splits a message into three parts:

- A summary for VSCode.
- A message.
- A explanation (not shown by default, unless there is only one error.)
