### ISSUE TITLE
Names for short-circuiting Result and Option folds?

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#1263]
Adding the short-circuiting list folds to `Option` and `Result` would be useful... [*]

~~~

// Result
pub def foldRight(f: (a, b) -> Result[b, e] & ef, s: b, xs: List[a]): Result[b, e] & ef = 
    ...
    
pub def foldLeft(f: (b, a) -> Result[b, e] & ef, s: b, xs: List[a]): Result[b, e] & ef =
    ...


// Option
pub def foldRight(f: (a, b) -> Option[b] & ef, s: b, xs: List[a]): Option[b] & ef = 
    ...
    
pub def foldLeft(f: (b, a) -> Option[b] & ef, s: b, xs: List[a]): Option[b] & ef =
    ...
    
~~~

These folds short-circuit on the failure of the "step" function `f`, the first failure respectively produces a single Err or None for Result and Option.

In Haskell they are supplied by the `Foldable` type class and are called `foldrM` and `foldlM`.

In Flix it probably makes most sense to have them in the Result and Option namespaces (rather than in List), but what should they be called as both Result and Option already have functions `foldLeft` and `foldRight` that work on a single Result or Option?

[*] I don't propose adding them to Validation as the short-circuiting prevents collecting multiple error which is the essence of the Validation type.

**Comment by magnus-madsen** [comment]
Could they be called `foldLeftM` in their respective namespaces?

**Comment by magnus-madsen** [comment]
> [*] I don't propose adding them to Validation as the short-circuiting prevents collecting multiple error which is the essence of the Validation type.

This is a good point.

**Comment by stephentetley** [comment]
`foldLeftM` & `foldRightM` are good. If Flix had typeclasses they would be the obvious names.

I also noticed that `List.foldRight` isn't tail recursive (`List.foldLeft` is naturally tail-recursive). I'll add a fix for that in the PR.

**Comment by magnus-madsen** [comment]
Fixed in master.
