### ISSUE TITLE
Add Type Classes to ResolvedAst

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1266]
Let us iterate on these details:

```scala
  case class Root(defs: Map[Symbol.DefnSym, ResolvedAst.Def],
                  ...
                 classes: Map[Symbol.ClassSym, ResolvedAst.Class]
                  ...
```

```scala
// Q1: We need to add some type parameter to design what this type class is parameterized by, e.g. Eq[a].
case class Class(sym: Symbol.ClassSym, signatures: List[ResolvedAst.Sig])
```

```scala
// Q2: A signature should (somehow) be able to refer to the type parameter(s) of the class.
// Q3: How do we refer to the name of a signature?
case class Sig(doc: Ast.Doc, ann: List[ResolvedAst.Annotation], mod: Ast.Modifiers, sym: Symbol.???, tparams: List[ResolvedAst.TypeParam], fparams: List[ResolvedAst.FormalParam], sc: Scheme, eff: Type, loc: SourceLocation)
```

Note: here a signature does not allow for an implementation. I am not sure what to do if we want implementations in type classes? Maybe we can skip that for now?

With this, we should be able to encode the the `Eq` type class and a few other simple ones.

**Comment by mlutze** [comment]
#1274

Q1: I just threw in another field `tparams` to allow for type parameters. Is there any reason it shouldn't be so simple?
Q2: My plan is simply to match the name of the tparam with the name in the signature.
Q3: There's already a `Symbol.SigSym` that we can use. Is this what you were referring to?

> I am not sure what to do if we want implementations in type classes?

I think it would be reasonable to add another field `implementation: Def` to the `Sig` class, right?

**Comment by magnus-madsen** [comment]
> Q1: I just threw in another field tparams to allow for type parameters. Is there any reason it shouldn't be so simple?

For a first approximation, I guess that is okay. 

> Q2: My plan is simply to match the name of the tparam with the name in the signature.

Name or Type.Var? I think you mean Type.Var.

Q3: There's already a Symbol.SigSym that we can use. Is this what you were referring to?

Yes, I guess so.

**Comment by magnus-madsen** [comment]
I think this can be closed.
