### ISSUE TITLE
Principled type/kind errors

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1282]
`TypeError.NonSchemaType` and `TypeError.NonRecordType` overlap somewhat with the purpose of `TypeError.MismatchedKinds` and `TypeError.MismatchedTypes`, so some cases where I expected to get one, I got the other. (`project`, `fold`). I think part of this is `unifyTypes`'s dependency on parameter order. E.g.

```scala
    val rec = Type.mkRecordExtend("a", Type.Str, Type.RecordEmpty)
    val str = Type.Str
    val res1 = Unification.unifyTypes(rec, str) // NonRecordType
    val res2 = Unification.unifyTypes(str, rec) // MismatchedTypes
```

It would be nice to have a contract where `unifyTypes(a, b) ~== unifyTypes(b, a)`

And I would propose some principles on when a user could expect each error:
* Mismatched kinds only if not explainable with types:
  * two vars with different kinds
  * one var and a bound type with different kinds
* Mismatched types for all other cases?
* Get rid of Non(Schema|Record)Type?

The alternatives include:
* keep NonSchemaType and NonRecordType and check both vars for schema-ness and record-ness
* keep parameter order dependency and document it and try to enforce it (?)

**Comment by magnus-madsen** [comment]
The Scala compiler is able to say when a type is under/over-applied.

E.g. `Option[Int, Int]` will give a warning with "too many type arguments" whereas `Map[Int]` will give a warning with too few type arguments. I think it would be useful if we could do the same.

**Comment by magnus-madsen** [comment]
In terms of reducing the number of errors, I think it is more a question of finding the *right* errors. With more specific errors we can give better/more detailed type errors.

**Comment by magnus-madsen** [comment]
I think the only wart I see atm is the NonSchemaType / NonRecordType.

**Comment by mlutze** [comment]
Not yet. Due to subkinding, kind errors can still be caught in the Typer.
