### ISSUE TITLE
Type Classes: Keywords and Syntax

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1287]
This issue is to gather community input regarding the keywords and syntax as we develop typeclasses.

The syntax as originally implemented a few years ago was:

```
    // class
    class X[a] {
        def f(x: a): Bool
    }

    // implementation
    impl X[Bool] {
        def f(x: Bool): Bool = true
    }

    // class constraint
    class W[a] <= X[a], Y[a], Z[a]

```

Rather than `class`, we could have `trait` as in Rust.
Rather than `impl`, we could have `instance` or `imp` or `inst`.
Would could also consider a keyword to indicate class constraints rather than `<=`.

Thoughts/ideas?

**Comment by esbenbjerre** [comment]
I would vote to change impl to instance, but besides that I think the syntax is clear.

**Comment by stephentetley** [comment]
I agree with Esben and prefer `instance` but otherwise I like the syntax.

**Comment by mlutze** [comment]
Thanks for the input. I'll move forward with the `instance` and `class` syntax for now.

**Comment by magnus-madsen** [comment]
I am fine with `class` and `instance`, at least for now. We can revisit the names once we have something that is starting to work :)

**Comment by magnus-madsen** [comment]
Can I just say -- as someone who teaches undergraduates in OOP -- that the names "class" and "instance" are really unfortunate for new programmers who want to get into FP/Haskell. I understand, historically, that these names are long established, but I just feel bad for the poor programmer who thinks that a Haskell typeclass is the same as a Java class and that a typeclass instance is the same as an object... Anyway, this is a good reason to be open for new names. But lets leave the discussion for later.

**Comment by magnus-madsen** [comment]
Basic question:

Assuming that `Show` for `Int` is built-in what should the type signature be of:

```
def f(): String = show 123
```

Do you get infer that `123 : String where Show[Int]`? or what?

**Comment by mlutze** [comment]
Do you mean that the user would need to write the following?

```
def f(): String where Show[Int] = show(123)
```

I think it would be too much for a user to need to annotate for non-variable type classes, considering cases such as `Eq` and `Ord` for each time `Int`s are compared.

**Comment by magnus-madsen** [comment]
I agree. I am trying to understand what should happen.

Is that when you have the type class constraints for the entire expression, you can remove immediately handle all non-variable constraints?

**Comment by magnus-madsen** [comment]
What constraints would you expect for this:

```
def f(): Bool = Nil == Nil
```

? 

Here I might expect you get `Eq[a]` for some `a` or ?

**Comment by mlutze** [comment]
> I agree. I am trying to understand what should happen.
> 
> Is that when you have the type class constraints for the entire expression, you can remove immediately handle all non-variable constraints?

Yes, I think that non-variable constraints could be considered part of the program as a whole, but not as a part of the type, and wouldn't be considered for the purposes of type checking.

**Comment by mlutze** [comment]
> What constraints would you expect for this:
> 
> ```
> def f(): Bool = Nil == Nil
> ```
> 
> ?
> 
> Here I might expect you get `Eq[a]` for some `a` or ?

I'll need to check this. It doesn't seem right that we'd put the type constraints on an unused tvar.

**Comment by magnus-madsen** [comment]
> > What constraints would you expect for this:
> > ```
> > def f(): Bool = Nil == Nil
> > ```
> > 
> > 
> > ?
> > Here I might expect you get `Eq[a]` for some `a` or ?
> 
> I'll need to check this. It doesn't seem right that we'd put the type constraints on an unused tvar.

Maybe it is okay. I am just trying to understand the design space :)

**Comment by magnus-madsen** [comment]
I want to make an argument that `class` should be `trait` (or perhaps some other word):

- To avoid confusion between OO classes and type classes*.
- Flix, being on the JVM, actually has classes. At least in the sense that String is a class and when you interop with Java you are working with classes. When we/I start writing more documentation, imagine how confusing and how much work it will be to say "type class" or "Java class" all the time.
- Other languages, namely Scala/Rust, have gone with `trait`.
- Yet other languages have gone with other words (protocol?).

* In general I want to reuse well-established names, e.g. Functor should probably be Functor, but in this case I think a name change is warranted.

I am open to suggestions other than `trait`. (`typeclass` is also a possibility, but I think I prefer `trait`).

**Comment by mlutze** [comment]
> Flix, being on the JVM, actually has classes.

Yes, I think the interop question is a major point in favor of changing.

If we change to `trait`, should we change from `instance` as well? 
I don't love `impl` for the more subjective reason that it's hard (for me) to pronounce. Seems like it has one-and-a-half syllables whereas other keywords have an integral number.

**Comment by magnus-madsen** [comment]
What are the alternatives for `instance`?

**Comment by magnus-madsen** [comment]
![image](https://user-images.githubusercontent.com/2287953/100541782-795a6980-3246-11eb-9d22-44cb89de610f.png)

**Comment by magnus-madsen** [comment]
![image](https://user-images.githubusercontent.com/2287953/100541786-82e3d180-3246-11eb-9041-5be3525ffa20.png)

**Comment by mlutze** [comment]
(I was looking at the same exact website)

**Comment by magnus-madsen** [comment]
```
trait Eq[a] {
  ...
}
```

```
nature of the beast Eq[Int] {
  ...
}
```

**Comment by mlutze** [comment]
Some more inspiration...

![Screenshot from 2020-11-29 13-33-14](https://user-images.githubusercontent.com/19153692/100541984-c2f78400-3247-11eb-9586-c983f07e8e7c.png)
![Screenshot from 2020-11-29 13-33-45](https://user-images.githubusercontent.com/19153692/100541985-c3901a80-3247-11eb-8919-3a84742b6c7c.png)
![Screenshot from 2020-11-29 13-34-05](https://user-images.githubusercontent.com/19153692/100541986-c428b100-3247-11eb-93ff-08a68f452a76.png)

**Comment by mlutze** [comment]
What about just `imp`? Three letters is usually nice.

**Comment by magnus-madsen** [comment]
> What about just `imp`? Three letters is usually nice.

I think then we might as well go with `impl` to please any potential Rustaceans

**Comment by magnus-madsen** [comment]
What do you think about the word `spec` for specification?

```
trait Eq[a] { ... }

spec Eq[Int] {
  ...
}
```

**Comment by magnus-madsen** [comment]
I guess it would make more sense to say:

```
spec Eq[a] ...
impl Eq[Int] ...
```

**Comment by magnus-madsen** [comment]
I remark that:

```
typeclass Foo {}
namespace Foo {}
```

are the same length

**Comment by magnus-madsen** [comment]
On the other hand, we have `type alias` with a space...

**Comment by magnus-madsen** [comment]
We currently have the syntax:

```
instance ToString[(a1, a2, a3)] with [a1 : ToString, a2 : ToString, a3 : ToString] {
    def toString(t: (a1, a2, a3)): String = match t {
        case (x1, x2, x3) =>
            "(${x1}, ${x2}, ${x3})"
    }
}
```

I would like to change the top line to:

```
instance ToString[(a1, a2, a3)] <= ToString[a1], ToString[a2], ToString[a3] {
```

I see the following benefits:
- It is similar to Haskell (just with the rule mirrored).
- It is similar to Datalog (and Prolog) rules. Since Flix has embedded Datalog this is a point for consistency.
- While it is not exactly the same as an "extends" in Java, it has a similar feel, and writing it this way seems more familiar.

**Comment by mlutze** [comment]
The arrow also lends itself better to multiparameter classes, should we want those.

When we add superclasses, should the arrow point the other way?

```flix
// flix
class Ord[q] => Eq[a]
```

That way the "entailment" arrow is pointing in a direction that makes sense.
Disadvantage: the opposite of Haskell superclasses, which seem to point in the wrong direction:

```haskell
{- haskell -}
class  (Eq a) => Ord a  where
```

**Comment by esbenbjerre** [comment]
I think we should use the same arrow for superclasses. As in
```
pub class Ord[a] <= Eq[a] {
}
```
I read that as "the type class Ord extends Eq".

**Comment by magnus-madsen** [comment]
> I think we should use the same arrow for superclasses. As in
> 
> ```
> pub class Ord[a] <= Eq[a] {
> }
> ```
> 
> I read that as "the type class Ord extends Eq".

I agree that it looks nicer, on the other hand, it is wrong. If you have `Eq[a]` then that does not imply that you have `Ord[a]`. So, logically Matt's suggestion makes more sense. 

But yeah, I don't know.

**Comment by liftM** [comment]
For naming, I'd recommend `interface` for typeclass (like Idris does), and `impl` for implementation (like Rust does).

When teaching students with mostly OOP backgrounds, I basically wind up explaining typeclasses as "basically OOP interfaces" anyway. And they serve a very similar purpose (i.e. ad-hoc polymorphism), although they are lawful by convention.

Similarly, what about `interface Ord[a] extends Eq[a]`?

**Comment by magnus-madsen** [comment]
I believe the syntax is mostly in place. What remains to be discussed are the choice of keywords for `class` and `instance`.

The top contender to replace `class` is `trait`.

For `instance` I have not yet heard a "good" proposal.

**Comment by mlutze** [comment]
We have also discussed opting not to use the term ~~"superclass"~~ "supertrait", since that evokes OOP ideas of inheritance.

**Comment by liftM** [comment]
> I believe the syntax is mostly in place. What remains to be discussed are the choice of keywords for class and instance.

I might be misunderstanding, but my suggestion was to use `interface` and `impl` as keywords.

So, for example (might be getting syntax a bit wrong here, I'm using other examples in this issue thread):

```
// Typeclass
interface X[a] {
    def f(x: a): Bool
}

// Typeclass instance
impl X[Bool] {
    def f(x: Bool): Bool = true
}

pub interface Ord[a] extends Eq[a] {
}

// Typeclass instance
impl ToString[(a1, a2, a3)] when [a1 : ToString, a2 : ToString, a3 : ToString] {
    def toString(t: (a1, a2, a3)): String = match t {
        case (x1, x2, x3) =>
            "(${x1}, ${x2}, ${x3})"
    }
}
```

**Comment by magnus-madsen** [comment]
@liftM Thanks for the example.

I think `interface` shares the same issue as `class`. The JVM already has interfaces and type class are fundamentally different from interfaces. So the reason to avoid `interface` is pretty much the same as for trying to avoid `class`.

**Comment by magnus-madsen** [comment]
I think there are only really two things left I would like to discuss:

- [ ] If `class` should be renamed to `trait` (and what about `instance`?)
- [ ] If we should drop `lawless` / `unlawful` (esp. the latter).  (We will still keep the laws of course, but we can derive whether something is lawless syntactically.)

**Comment by mlutze** [comment]
@magnus-madsen This is assigned to me but it's not yet clear the action to be taken. Have we landed on `trait` and `instance` and should begin the keyword migration?
