### ISSUE TITLE
Inconsistent parameter order(s) in std. library

### ISSUE THREAD

**Issue by esbenbjerre** [flix/flix#1289]
The parameter order of functions is inconsistent across the std. library.

In some namespaces the data type is the first parameter while it is last in others.
Here are some examples
`findRight(f: a -> Bool, a: Array[a])` vs. `get(a: Array[a], i: Int32)`
`lengthHelper(xs: List[a], ac: Int32)` vs. `memberOf(a: a, xs: List[a])`
`choose[a](r: Random, a: Array[a])` vs. `forall(f: Char -> Bool, s: String)`

I think we should decide on a certain style and stick to it. Otherwise we risk making the [same error as PHP](https://softwareengineering.stackexchange.com/questions/32541/why-are-php-function-signatures-so-inconsistent).

**Comment by esbenbjerre** [comment]
I realize now that these signatures may be a conscious choice to take advantage of UFCS.

**Comment by magnus-madsen** [comment]
Yes, we should take extra care with parameter order.

We currently following Haskell where all higher-order function arguments goes first (e.g. find). This allows us to write things with pipelines. But indeed there are some issues with UFCS and some open questions (see e.g. #605). At some point, it would be nice if we could write down some principles for the order of arguments.
