### ISSUE TITLE
Add nubBy (remove duplicates) to List

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#1293]
One for when Magnus is back from holiday...

I've just noticed the List module doesn't have a function to remove duplicates, so I propose adding `nubBy`:

~~~

pub def nubBy(f: (a, a) -> Bool, xs: List[a]): List[a] =
   ...

~~~

`nubBy` is the Haskell name for this function (and `nub` for the simpler version that uses `(==)` from the `Eq` typeclass). "nub" isn't a name I particularly like, so alternative suggestions would be welcome. `removeDuplicatesBy` is very long. I think Clean called it `nodup` which I prefer to `nub` but it is still a bit cryptic.

**Comment by magnus-madsen** [comment]
I like `distinct`.

**Comment by stephentetley** [comment]
I've implemented `distinct` using builtin equality and `distinctWith` with a user supplied equality function and made a PR #1302.

**Comment by magnus-madsen** [comment]
Fixed in master.
