### ISSUE TITLE
Kind Check Ascriptions

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1294]
The following now works beautifully:

```
def f(): Unit =
    () as Map[Int]
```

```
>> Illegal uninhabited type: 'Map[Int32]' with kind '* -> *'.

2 |     () as Map[Int]
        ^^^^^^^^^^^^^^
        uninhabited type.
```

But we should also check this for ascriptions:

```
def f(): Unit =
    (): Map[Int]
```

Are there other places we should check for this too?

- `import` expressions? Maybe that is a bit out of scope. (E.g. `import java.lang.String.charAt(Option)`).
- ???

@mlutze You want to take a look? :)

**Comment by mlutze** [comment]
I think the imports may be a little more complex so I left them out of the first simple PR.
