### ISSUE TITLE
Thoughts on Array.transformWhileLeft! and Friends

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1297]
What do you guys think about a function like:

```
def transformWhileLeft!(f: a -> Option[a], a: Array[a]): Unit
```

It applies `f` to every element of `a` (in place) going left to right as long as `f` returns `Some`.

I guess an argument against might be that its a slow way to transform an array... having to construct a None/Some instead of just passing some index.

**Comment by esbenbjerre** [comment]
I like it. I can see that it would be useful to have a function which allows early termination.
