### ISSUE TITLE
Add Seq/Stream to StdLib

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1303]
It would be nice to have a lazily-loaded sequence type for e.g. iterating over lines from input without needing to load them into a list, or performing operations on infinite sequences.

**Comment by stephentetley** [comment]
I've a "pull" stream here...

https://github.com/stephentetley/flix-sandbox/blob/master/src/flix/Data/Stream.flix

The core API should be fairly well worked up, but some of the additions are a bit tentative (they might have bad names, might be unnecessary or have better alternatives, etc.).

**Comment by magnus-madsen** [comment]
I have been reading about laziness and looking at how other languages do it. I have some observations and questions:

- Laziness interacts poorly with (side)-effects so perhaps it makes sense for us to enforce that operations on lazy data structures are pure? E.g. mapping a function over a lazy list should require that the function is pure.
- Many languages seem to have a data type `Lazy` which is almost like a function except that it is memoized (remembered) by the runtime. We could probably add that easily.
- It seems that if you have a type like the above you have to careful with explicit use of `lazy/force`. For example, if a function `f` expects a lazy `Int` then you cannot call it with `42`, but you have to write `lazy 42`. I have no idea if this is actually a problem, its just an observation.
- For LazyList there seems to be an important distinction between whether the entire list is lazy or just its tail. For example, the most common implementations (e.g. in OCaml) seems to have the head be strict. But this does not feel truely lazy. So what is the appropriate definition?
- For lazy streams etc. let rec is very useful. We don't have that yet.. but eventually we will.

Bonus Question: How does all of this relate to Stephen's "pull" stream?

**Comment by stephentetley** [comment]
I think my stream and a lazy list might be orthogonal. In Haskell streams have had two big successes. One is stream fusion as a replacement for the traditional list where the stream avoids recursion and so presents opportunities for optimization. The other is replacing lazy IO with a strict but incremental alternative - strictness is an advantage for tracking resources and closing / releasing them at the right time and incremental is an obvious advantage that data processing need not lead to an explosion in memory usage. 

My stream is really an instance of the second though it is simpler than most of Haskell's streaming and iteratee / enumerator frameworks. For instance there is only one type variable in the Stream type and there is only a single new type exported by the module.

**Comment by magnus-madsen** [comment]
It sounds like it would make sense to have both types of streams in the standard library. Perhaps we could add Stephen's stream under the name "PullStream" and the lazy stream under the name "LazyList"?

**Comment by stephentetley** [comment]
Thanks Magnus, I'll rename my module to `PullStream` and look to polishing it up.

**Comment by magnus-madsen** [comment]
We now have `LazyList` and `Iterator`, but there would be room for a `Stream` kind-of thing that sits in between.
