### ISSUE TITLE
Separate Compilation of Jars?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1304]
If a Flix program is compiled with a dependency on a class that is not part of the Java class library then the JAR file must be available on the class path and loaded by the compiler. 

This has some benefits:
- An import statement requires the types of the parameters to be present (to resolve overloading), but not the return type since that cannot be overloaded and hence can be determined from the method.
- The compiler ensures that an imported class/method exists and has the right signature.

The downside is of course that not only must such JAR files be present they must also be loaded into the compiler itself.

Very soon (TM) when we get VSCode support this will become more apparent because then the programmer may not be invoking the compiler itself, but rather working with the IDE directly. This can make it awkward to set class paths etc.

The question is whether this situation is acceptable. The alternative is to:

- Demand that imports include return types (and the type of fields etc.).

and then the compiler can just blind trust this information. Of course if a signature is wrong then the program will fail at run-time.

**Comment by magnus-madsen** [comment]
@stephentetley I think you are most affected by this either way. Do you have any thoughts?

For now I am just planning to leave it as-is, but I wanted to document the state-of-affairs.

**Comment by stephentetley** [comment]
Thanks Magnus. 

At the moment when I use extra jars I have them in the `lib` directory of the Flix compiler and build the compiler to include them.

Long term, a solution where they can be distributed with a Flix library / package would be essential but I can manage with the current way of doing things.

**Comment by magnus-madsen** [comment]
The Flix compiler will now load jars provided as arguments or from the lib folder.
