### ISSUE TITLE
Add {Set/Map}.query

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1305]
Add a function that efficiently queries a *range* of elements from a Set/Map (i.e. from the underlying RBTree).

We need to introduce a data type:

```
namespace Core/Cmp { 
  enum Ordering {
    case LessThan, Equal, GreaterThan
  }
}
```

(or something like that). Then the signature of this new function is approximately:

```
def query(p: a -> Ordering, m: Set[a]): List[a]
def query(p: k -> Ordering, m: Map[k, v]): List[(k, v)]
```

The idea is that you call `p` on the element/key. If it says `LessThan` you descend left. If it says `Equal` you include the element and descend on *both* branches, and if it says `GreaterThan` you descend right. We can discuss whether or not the resulting list should be sorted. Note that query(_ -> true) should return all elements in the set/map.

Intuitively, this functionality can be used to extra all keys in a range. For example, if you have set/map of integers you can get all elements/keys in the range 5-10 by writing an appropriate predicate.

**Comment by magnus-madsen** [comment]
@esbenbjerre Can you take a look and see if it make sense? We can talk about it at our meeting.

**Comment by esbenbjerre** [comment]
That sounds interesting. Do you have any specific use case(s) in mind?

**Comment by magnus-madsen** [comment]
Yes, it is for eventually porting the Datalog solver to Flix.

There you need to store tuples. For example:

```
(Esben, 123, "abc")
(Magnus, 123, "abc")
(Maya, 456, "abc")
(Maya, 999, "def")
```

then you can issue a query such as asking for all names that start with M and where the second number is between 0 and 500 for example. Note that you cannot query for elements that have "def" as the third column. You can only select on the first column, and then on the second column, and so forth, because you have to introduce a total order on the triples (for the RBTree) and your query has to respect this ordering.

**Comment by esbenbjerre** [comment]
I've had a chance to look at this and implement the behavior on RedBlackTree, but I would like you to confirm the expected behaviour.
Say we have a set `xs` containing the elements [0, 9]. My intuition would be that the following code
```
let p = k -> if (k < 3) LessThan else if (k > 6) GreaterThan else Equal;
let res = Set.query(p, xs);
```
results in `res = List(3, 4, 5, 6)`. However, this does not fit with your description

> ... If it says LessThan you descend left. If it says Equal you include the element and descend on both branches, and if it says GreaterThan you descend right...

Is your intention to define predicates like I defined `p` or the other way around?

**Comment by magnus-madsen** [comment]
> Say we have a set `xs` containing the elements [0, 9]. My intuition would be that the following code
> 
> ```
> let p = k -> if (k < 3) LessThan else if (k > 6) GreaterThan else Equal;
> let res = Set.query(p, xs);
> ```
> 
> results in `res = List(3, 4, 5, 6)`. 

I agree with this.

In other words, if `p` says `Equal` then the result must be included in those returned by `query`. 

If `p` says `LessThan` then the element (and any smaller than it) are excluded. Similarly for `GreaterThan`.

It sounds like we are on the same page. Probably my original description was poor/incorrect.

Later, I can go over the test cases to confirm that we agree, but it sounds like we have the same understanding.
