### ISSUE TITLE
Reconsider the Role of Wildcards

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1307]
We should have a discussion of where wildcards are allowed in the language.

This includes as: expressions, patterns, types, terms, etc.

**Comment by magnus-madsen** [comment]
@esbenbjerre Can you compile a list of functions from the std. lib. where the comments in #1291 are relevant.

That is, make a list of functions where:

- The function has one or more type parameters, but they only occur in a single position.

For example `List.length` is an example, but `List.head` is not. Does it make sense?

@mlutze Let's take a look at this list and see if we feel that the feature is worth its weight (for type parameters).

**Comment by magnus-madsen** [comment]
I suspect there are very few such functions. Maybe ten or twenty (essentially just isEmpty and variants).

**Comment by magnus-madsen** [comment]
Usage of wildcard:

- Expressions: Not allowed. Gives undefined name.
- Patterns: Allowed, means that a particular value is not of interest.
- Types: Allowed, means that a particular type is not of interest.
- Terms: Allowed, means that a particular value is not of interest.

I think the cases for patterns and terms (in logic programming) are well-established. 

For expressions, `_` sometimes denotes a default value (but I dislike that) or a hole, but we already have `?hole` for holes.

For types, consider the following:

```
def foo(): _ = 123
```

which gives:

![image](https://user-images.githubusercontent.com/2287953/91970360-d2823200-ed17-11ea-9790-2ae22ba5955f.png)

While correct- it seems pretty obscure.

Let's wait for the list that Esben comes up with, but so far I am leaning more and more towards removing this feature.

**Comment by mlutze** [comment]
I think the best pro-argument is one for consistency. The "No unused variables" principle might need an asterisk :)

But on a practical level, I'm on the fence. In my opinion, even more important than "Where would this be used?" is "What kind of bugs would this prevent?" I'm having trouble coming up with a bug that would be discovered by this implementation.

**Comment by magnus-madsen** [comment]
If you write: 

```
def isEmpty(xs: List[a]) 
```

is the variable `a` really unused? Not sure...

If you write:

```
def isEmpty[a, b](xs: List[a]) 
```

then clearly `b` is unused.

I guess its a matter of opinion.

**Comment by mlutze** [comment]
I wonder if we could reasonably formalize the concept of an unused variable in order to have a more agreed-upon understanding?

**Comment by magnus-madsen** [comment]
Usually we would say that a variable is *introduce* but never used/referenced.

The problem with types is that because of "type parameter elision" you can write a type variable without really introducing it.

**Comment by magnus-madsen** [comment]
I am not sure there is anything left to reconsider at the moment.
