### ISSUE TITLE
File test improvements

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1312]
The tests for File functions are not very thorough, and depend on unrelated files such as README.md. I think we should use dedicated resources for these tests and make assertions on their output rather than just `isOk`.

**Comment by magnus-madsen** [comment]
I think @stephentetley may be working on some I/O library. But indeed, we will need to figure out an appropriate test strategy.

**Comment by stephentetley** [comment]
I've the work so far here:

https://github.com/stephentetley/flix-sandbox/tree/master/src/flix/System
