### ISSUE TITLE
Enforce Kind Annotations for Type Variables of non-Star Kind?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1316]
For discussion:

Would it make sense for us to require that type variables of non-Star (i.e. for type variables that represent anything other than regular types) kind must be annotated?

We would still allow "normal" type definitions such as:

```
enum List[t] {
    case Nil,
    case Cons(t, List[t])
}
```

but if you do something like this:

```
enum Foo[a, b, e] {
  case Bar(a, a -> b & e)
}
```

you ***must*** now write:

```
enum Foo[a, b, e: Effect] { // discuss syntax
  case Bar(a, a -> b & e)
}
```

to *explicitly* state that e is of a non-star kind.

**Comment by magnus-madsen** [comment]
Pinging @mlutze :)

**Comment by magnus-madsen** [comment]
This would also apply to: records, schemas, and other future non-star types (perhaps nullity, etc.)

**Comment by magnus-madsen** [comment]
Hmmm.. This would be quiet verbose every time you have to write a higher-order effect polymorphic function...

**Comment by mlutze** [comment]
I think this could be practical internally, potentially eliminating some of the pre-unification that happens before the typer.

But verbosity might be a problem. We could consider symbolic syntax instead, to make things more concise, but that would cost some clarity.

How would this look with type classes? Seems like these two combined in a signature might become complicated.

**Comment by magnus-madsen** [comment]
Confirmed fixed in master 🎉
