### ISSUE TITLE
Syntax Highlighting for Non-Editors

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1324]
This task is to add support for basic syntax highlighting of Flix code to commonly used libraries. (It is not related to our LSP efforts). 

I suggest (in order of priority):

- Extract a list of keywords from `Parser.scala` and paste them here.
- Add an official Flix mode to Ace (https://github.com/ajaxorg/ace)
- Add an official Flix mode to Pygments (https://pygments.org/) 
- Add an officlal Flix mode to Linguist (https://github.com/github/linguist)

Ace is the tool we use for all the Flix websites. Pygments is the tool used by Wikipedia for syntax highlighting. Linguish is used for GitHub.

Are there any other **non-editor** highlight systems that we want to support? Maybe something for latex? (how does that even work) 

(Again, this ticket has nothing to do with LSP or VScode)

**Comment by magnus-madsen** [comment]
@esbenbjerre Perhaps this is something you can look into a bit down the road.

**Comment by mlutze** [comment]
I made this hacky script a while ago for adding keywords to intellij:
No guarantees on completeness but might save a couple minutes whenever the keyword list needs to be updated.

```python
#!/usr/bin/env python3

import re
import fileinput

keywords = set()

for line in fileinput.input():
    keywords.update(re.findall(r'keyword\(\"(\w+)\"\)', line))

kw_list = list(keywords)
kw_list.sort()

for kw in kw_list:
    print(kw)
```

```
Impure
Nil
Pure
alias
and
as
case
catch
chan
class
def
default
deref
else
enum
exists
false
fold
forall
force
get
if
import
inline
instance
lat
law
lazy
let
match
mut
namespace
new
not
null
opaque
or
project
pub
ref
rel
select
set
solve
spawn
true
try
type
union
use
```

**Comment by magnus-madsen** [comment]
Tracked in #2494.
