### ISSUE TITLE
Map.inverse?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1343]
Today, in Scala, I found myself with a map `Map[String, Int]` and needing a map `Map[Int, Set[String]]`. 

Is there a name for such a function in Scala/Haskell?

**Comment by esbenbjerre** [comment]
I could not locate a function exactly like that in the standard library of Scala or Haskell.

We can easily invert the keys and values with something like
```scala
val original = Map(1 -> 2, 2 -> 3, 3 -> 4, 4 -> 4)
val inverted = original map { case (k,v) => (v, k) } // Map(2 -> 1, 3 -> 2, 4 -> 4)
val inverted2 = original map(_.swap) // Map(2 -> 1, 3 -> 2, 4 -> 4)
```
But we lose any duplicates. A solution to keep duplicates could be something like
```scala
def inverse[A, B](m: Map[A, B]): Map[B, Set[A]] =
  m.foldLeft(Map.empty[B, Set[A]]) {
    case (acc, (v, k)) =>
      acc.updated(k, acc.getOrElse(k, Set()) ++ Set(v))
  }
```
