### ISSUE TITLE
Syntactic Sugar for Lambdas

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1345]
Scala has syntactic sugar for more concise lambda expressions:

`myVar => myVar.toString` can be expressed as `_.toString`

Kotlin does does the same with a special variable `it`.

Partial application of functions takes care of a lot of this for us, but would it be helpful to have this syntax as well?

**Comment by magnus-madsen** [comment]
Maybe. See also https://github.com/flix/flix/issues/605.

But, if I recall correctly, the desugaring of `_` is somewhat complicated. Especially when there are multiple `_` and they are nested at different levels. Overall I am not yet convinced it is worth it.

**Comment by magnus-madsen** [comment]
Your example `f(myVar => myVar.toString)` can just be written as `f(toString)` because Flix has currying.

**Comment by magnus-madsen** [comment]
I am closing this. We can reconsider it later, if we feel there is a need for it.
