### ISSUE TITLE
Type Classes, Continued

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1376]
### For PR 4: Working core algorithm
- [x] Write some type classes in Flix
- [x] Add test cases for type constraints in type schemes
- [x] Determine scheme `leq` with type constraint reduction/normalization/unification
- [x] Allow instances on polymorphic types 
- [x] Allow multiple class annotation `[a: Eq, Show]`
- [x] Remove redundancy check for existence of parameter implied by class tparam
- [x] Make instances globally available
- [x] Lookup instance using both class name and parameter type mgu
- [x] Handle type constraints for enums
- [x] Come up with a list of type classes to start with (Show, Eq, Ord, PartialOrd, Add, etc..)
- [x] Fix `use class`
- [x] Ensure instances contain all class signatures
- [x] Check for overlapping instances
- [x] Ensure each instance corresponds to a class.
- [x] Ensure each class has a type parameter.
- [x] Ensure every signature uses the class tparam
- [x] Disallow arbitrary constraints on instance defs

### Remaining to do:
- [x] Fix `use sig`
- [ ] Disallow complex instances
- [x] Non-`*` class tparams
- [ ] Decide on visibility rules for classes, instances, signatures.
- [ ] Allow constraints on non-variable types in signatures
- [ ] Synthesize instances
- [ ] Infer type constraints for `==`, `<`, etc.
- [ ] Check for shadowing of type variables
- [ ] Decide on polymorphic record instance conflict resolution
- [ ] Default instances?
- [ ] Superclasses
- [ ] Redundant superclass check?
- [ ] Redundant type constraint check
- [ ] Improve syntax everywhere

### Type classes for PR 4
- [x] Show
- [x] Read

### Remaining type classes:
- [x] Functor
- [ ] Applicative
- [ ] Monad
- [ ] PartialEq + Eq
- [ ] PartialOrd + Ord
- [ ] Add
- [ ] BitAnd
- [ ] BitOr
- [ ] BitXor
- [ ] Div
- [ ] Mul
- [ ] Neg
- [ ] Not
- [ ] Shl
- [ ] Shr
- [ ] Sub
- [ ] Default?

#### (Extra notes to be turned into proper checkmarks)
* the superclasses of a class should have the same kind as the class itself
* the parameters of any predicates in an instance context should be type variables, each of which should appear in the head of the instance
* and the type appearing in the head of an instance should consist of a type constructor applied to a sequence of distinct type variable arguments
* THIH says that we must not have cyclic inheritance

**Comment by magnus-madsen** [comment]
(I edited your list)

**Comment by mlutze** [comment]
Is the numeric list too fine-grained? I think we should have type classes for the operators but would it be better to group them up? E.g. NumOps, BitOps, BoolOps?

**Comment by magnus-madsen** [comment]
I plan to go and re-read some of the papers on type classes. Its been a while. I have several various comments for us to discuss. Ill post them below, in no particular order.

**Comment by magnus-madsen** [comment]
### Type and Kind Ascription

We use the syntax `e: Type` for type ascriptions. For example:

```
let x: Int = 123
def f(x: Int): Int = x
```

It would be nice if we could mirror this at the type level, for example `Int: Type` or `x: Bool` (Boolean type level variable).

I understand that this is currently used for type classes, e.g. `x: Eq`.

**Comment by magnus-madsen** [comment]
### Single Param or Multi Param Type classes

A big question is whether we ultimately want single parameter or multi parameter type classes (and with what extensions? e.g. functional dependencies).

My understanding is that Rust opted for single parameter type classes. This keeps things simple and avoids the pitfall where multi-param type classes often required further extensions to be useful. It also allows for "shorter" syntax. 

Do we have any examples of where we would want multi param type classes? All the listed TCs are single param.

**Comment by magnus-madsen** [comment]
### Implementations inside Type Classes

Rust (and maybe Haskell?) allows you to define not just signatures, but functions with implementations inside type classes. I suggest we start by not supporting/allowing that. Supporting it also has some issues. For example, people like to define `==` in terms of `!=` and vice versa, but this then leads to infinite recursion if neither is implemented. So I suggest, for now, that type classes are pure interfaces.

**Comment by magnus-madsen** [comment]
### Using Type Classes

It is good that type classes are namespaced and have to be imported. Consequently, it is possible for programmers to define two type classes: 

```
class Student {
  def train(): Unit
}
```

```
class Ticket {
  def train(): String
}
```

and distinguish them. In the current design, we furthermore require *each* function of the trait to be imported to. I think this is fine, although of course it can be a bit tedious, for example importing `map` and `flatMap` from `Monad`. 

Question: I assume you can rename when importing?

**Comment by magnus-madsen** [comment]
### Type Class Names and Hierarchy 

I am mostly okay with adopting standard terminology from Haskell and Rust. For example, Monad should be Monad, Functor should probably be Functor, and so forth. Still there might be slight variations, for example I think Rust's use of PartialEq and Eq is more appropriate. I also do not particular like the name `Show`. What is it showing?

**Comment by mlutze** [comment]
> Do we have any examples of where we would want multi param type classes? All the listed TCs are single param.

The classic example (from my reading) is a collection class:

```haskell
 class Eq e => Collection c e where
     insert :: c -> e -> c
     member :: c -> e -> Bool
```

While we could implement this for most cases with `c` as kind `* -> *`:

```flix
class Collection[c #: * -> *] { // kind annotation
    def insert(x: e, col: c[e]): c[e]
    def member[e: Eq](x: e, col: c[e]): c[e]
}
```

if we want to say that `String` is a collection of `Char`s, for example, there's no way to do that (as far as I can tell).

**Comment by mlutze** [comment]
> ### Implementations inside Type Classes
> 
> Rust (and maybe Haskell?) allows you to define not just signatures, but functions with implementations inside type classes. I suggest we start by not supporting/allowing that. Supporting it also has some issues. For example, people like to define `==` in terms of `!=` and vice versa, but this then leads to infinite recursion if neither is implemented. So I suggest, for now, that type classes are pure interfaces.

Yes, I think implementations in classes should definitely be a future expansion. One idea I was thinking about was to allow default implementations to call each other, but to require an instance to implement minimally a subset of classes such that each function eventually leads to a "real" implementation. That might end up being too confusing for a user, however.

**Comment by mlutze** [comment]
> It is good that type classes are namespaced and have to be imported.

One thing to note about the current implementation is that the namespace used by signatures is that of the class's surrounding scope.

```flix
namespace A {
    class C1[a] {
        def f(): a
    }

    class C2[a] {
        def f(): a // !!! Error: duplicate signature
    }
}
```

> Question: I assume you can rename when importing? 

I believe renaming is currently possible for signatures, but not for classes. (To be verified).

**Comment by magnus-madsen** [comment]
> The classic example (from my reading) is a collection class:
> 
> ```haskell
>  class Eq e => Collection c e where
>      insert :: c -> e -> c
>      member :: c -> e -> Bool
> ```
> 

Yes, and yet, I have never seen or heard of it being used. (I also speculate that such an interface would be problematic: How often can you actually substitute a collection without changing the performance/semantics? - and if you could, how often would you want to.)

**Comment by magnus-madsen** [comment]
> Yes, I think implementations in classes should definitely be a future expansion. One idea I was thinking about was to allow default implementations to call each other, but to require an instance to implement minimally a subset of classes such that each function eventually leads to a "real" implementation. That might end up being too confusing for a user, however.

I mean, is it really that useful to have implementations inside interface? If a function can be defined in terms of the interface, does it really need to be *part* of the interface?

**Comment by magnus-madsen** [comment]
> 
> 
> > It is good that type classes are namespaced and have to be imported.
> 
> One thing to note about the current implementation is that the namespace used by signatures is that of the class's surrounding scope.
> 
> ```
> namespace A {
>     class C1[a] {
>         def f(): a
>     }
> 
>     class C2[a] {
>         def f(): a // !!! Error: duplicate signature
>     }
> }
> ```

OK, and this happens on declaration, not on trying to use f? I can imagine traits in the global/core namespaces that might want similarly named functions... But anyway, we can defer this till later.

**Comment by mlutze** [comment]
> I mean, is it really that useful to have implementations inside interface? If a function can be defined in terms of the interface, does it really need to be _part_ of the interface?

It seems to me, the main use-case for this is when an optimization can be made for a particular instance.

```flix
class Length[a] {
    def length(x: a): Int
    def isEmpty(x: a): Bool = length(x) == 0
}

instance Length[Array[a]] {
    def length(x: Array[a]): Int = x.length
}

instance Length[List[a]] {
    def length(x: List[a]): Int = ??? // O(n)
    def isEmpty(x: List[a]): Int = x == Nil // default implementation would be O(n)
}

Is this realistic outside this contrived example?

I think the same idea can be applied to the multiple type parameter question; I see uses for increasing efficiency in particular situations, but maybe it's too rare to warrant the additional complexity.

**Comment by mlutze** [comment]
> > > It is good that type classes are namespaced and have to be imported.
> > 
> > 
> > One thing to note about the current implementation is that the namespace used by signatures is that of the class's surrounding scope.
> > ```
> > namespace A {
> >     class C1[a] {
> >         def f(): a
> >     }
> > 
> >     class C2[a] {
> >         def f(): a // !!! Error: duplicate signature
> >     }
> > }
> > ```
> 
> OK, and this happens on declaration, not on trying to use f? I can imagine traits in the global/core namespaces that might want similarly named functions... But anyway, we can defer this till later.

Yes, on declaration. Currently I put the class within a same-named namespace so that the user does `use Show.show` to get the signature. But to get the class it's then necessary to do `use class Show.Show`, which is redundant, plus if the namespace doesn't happen to have the same name, confusion is sure to ensue. So I think that's surely something to change.

**Comment by magnus-madsen** [comment]
What about we close this ticket?

**Comment by mlutze** [comment]
> What about we close this ticket?

Fine with me. I think everything remaining has either been dropped or put in its own ticket.
