### ISSUE TITLE
Enums with non-Star Kinds

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1380]
For #1375, I want to write something like:
 
```
enum Choice[a, isAbsent, isPresent] {
    case Absent,
    case Present(a)
}

def some(x: a): Choice[a, false, _] = Present(x)
```

but:

![image](https://user-images.githubusercontent.com/2287953/94905601-6ec96100-049d-11eb-9a70-c87d2e479ca1.png)

Question is how to fix this. I might add that `Absent` and `Present` are like GADTs, so maybe:

```
enum Choice[a, isAbsent, isPresent] {
    case Absent: Choice[a, false, isPresent],
    case Present(a): Choice[a, isAbsent, false]
}
```

But, at this time, I really don't want to mess around too much with GADTs. I just need something like it for #1375.

**Comment by mlutze** [comment]
Kinds are currently inferred based on their use in the cases. I think something like #1316 would be the most straightforward solution.

```
enum Choice[a, isAbsent :: Bool, isPresent :: Bool] {
    case Absent,
    case Present(a)
}
```

(I use double `::` to distinguish these from type classes)

**Comment by magnus-madsen** [comment]
We should discuss the syntax of kind ascription and type classes.

At the term and type level, we use `123 : Int` to describe that the expression `123` has type `Int`. Note also that at the term level `1 :: Nil` is a list. 

I think it would make sense that a the type and kind level, `Int : Type` and `true: Bool` and `x: Type` and `x: Bool` should be type ascriptions. Then, if we at some point have type level lists these should probably also use `::`.

Now that leaves the question of how to annotate type classes.

**Comment by magnus-madsen** [comment]
In Haskell they use:

```
    ghci> :t (==)  
    (==) :: (Eq a) => a -> a -> Bool  
```

I am not a particular fan of that, and I don't know what the Flix equivalent would look like. What do other languages do?

**Comment by mlutze** [comment]
I don't like the Haskell syntax much either. Here are a couple other language's syntaxes:

Clean:
`min` belongs to type class `Ord`
```clean
min:: a a -> a | Ord a
```

Mercury:
`P1` belongs to type class `point`
```mercury
pred distance(P1, P2, float) <= (point(P1), point(P2))
```

I don't think either of these works particularly well for Flix, but something to think about.

**Comment by magnus-madsen** [comment]
Returning to the more immediate issue:

I would like to write:

```
    pub def toOption(c: Choice[a, isAbsent, isPresent]): a = choose c {
        case Absent     => None
        case Present(v) => Some(v)
    }
```

but here `isAbsent` and `isPresent` is assumed to have Type kind. How do we want to express such a signature?

```
    pub def toOption(c: Choice[a, isAbsent: Bool, isPresent: Bool]): a = choose c {
        case Absent     => None
        case Present(v) => Some(v)
    }
```

or 

```
    pub def toOption[isPresent: Bool, isAbsent: Bool](c: Choice[a, isAbsent, isPresent]): a = choose c {
        case Absent     => None
        case Present(v) => Some(v)
    }
```

or both?

How do you feel about the introduction of an `Ascribe` type expression, i.e. an ascribe at the type level?

(Not yet clear how we would check it in all cases, but should be easy for var cases).

**Comment by mlutze** [comment]
I prefer the second option, as it separates the declaration of type variables and term variables.

> `Ascribe`
This is interesting. But where would you expect it to be used if we annotate all tvar kinds at declaration? It seems to me that if we require all non-star kinds to be annotated, we would never have kind variables, so an ascription wouldn't be useful (?)

**Comment by magnus-madsen** [comment]
> This is interesting. But where would you expect it to be used if we annotate all tvar kinds at declaration? It seems to me that if we require all non-star kinds to be annotated, we would never have kind variables, so an ascription wouldn't be useful (?)

I think rarely. You also rarely use a normal type ascription. Only when things are complicated:

```
val f: List[a -> b & ({b1 and b2}: Bool)] = ...
```

**Comment by magnus-madsen** [comment]
Confirmed fixed in master 😄
