### ISSUE TITLE
Ninety-Nine Flix Problems

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1385]
_(copy-pasted from Gitter)_

There is a "Ninety-nine problems" set which is used to demonstrate/help learn the functionalities of the language. (https://www.ic.unicamp.br/~meidanis/courses/mc336/2009s2/prolog/problemas/) Originally written for Prolog, but there are versions for Scala, OCaml, Haskell, and probably others. Since Flix is right in the middle of those, it might be a nice additional demonstration of Flix's unique features, which we could add to the website.

This could be a good hackathon project as it would allow a new contributor to learn the language as they go.

**Comment by magnus-madsen** [comment]
https://github.com/flix/ninety-nine-problems

**Comment by magnus-madsen** [comment]
I was also thinking, maybe we should come up with our own problems. I guess this would make more sense when the language is a bit richer, but already we could have some Datalog problems.

**Comment by magnus-madsen** [comment]
The repo is there. But lets see if anyone will use it and/or maintain it.
