### ISSUE TITLE
Datalog rules with multiple atoms in the head

### ISSUE THREAD

**Issue by racerand** [flix/flix#1393]
Working with Datalog I have seen that other solvers has allowed for multiple atoms in the head to be derived by one rule, such as:
`A(x), B(y), C(z) :- D(x, y), E(y, w, z), F(z).`
This can of course be rewritten into 3 rules, but this require the recalculation of the rule 3 times, which can be resource consuming with a large body in the rule.
```
A(x) :- D(x, y), E(y, w, z), F(z).
B(y) :- D(x, y), E(y, w, z), F(z).
C(z) :- D(x, y), E(y, w, z), F(z).
```
One solution could be a rewrite in the backend to:
```
A(x) :- ABC(x, _, _).
B(y) :- ABC(_, y, _).
C(z) :- ABC(_, _, z).
ABC(x, y, z) :- D(x, y), E(y, w, z), F(z).
```
This is probably how anyone should be writing it, but someone might end up just copy-pasting their code instead. Before I had more experience with Datalog I ended up using the code dublication method.

**Comment by magnus-madsen** [comment]
I think we will defer on this feature.
