### ISSUE TITLE
Recursive functions only is a valid Flix program

### ISSUE THREAD

**Issue by racerand** [flix/flix#1424]
I found that the Flix program
```
def mapTRMC(f: a -> b & e, l: List[a]): List[b] & e =
    match l {
        case Nil => Nil
        case x :: xs => f(x) :: mapTRMC(f, xs)
    }
```
is considered valid by the compiler, even though it's not marked a @test or reference through main. I suspect it is because it is referenced by itself. No code is generated for this program, before, which means that some phase must realize that there is no entry-point, right? The AST is empty from at least the Simplifier.

I also tested this for mutual recursion, and the compiler also consider the program 
```
def rec1() : Int = rec2()

def rec2() : Int = rec1()
```
just fine.

Both these programs lack an entry-point.

**Comment by mlutze** [comment]
This could be addressed by changing the redundancy algorithm from a flat "look at each def" to a graph search starting from trivially accessible defs. But that could complicate parallelization and cause some slowdown.

**Comment by magnus-madsen** [comment]
I think, in general, we want to have a principle that is easily explained. Checking if a function is unused is ultimately undecidable. In this case, for a recursive function that uses itself, we could add a special check that says: A use of a function only counts if does not occur directly in the function itself.

**Comment by mlutze** [comment]
While the actual runtime use of the function is undecidable, a simple syntactic search over appearances of definitions within other definitions isn't too complicated, and should be pretty well explainable, I think.

**Comment by magnus-madsen** [comment]
See #1427

**Comment by racerand** [comment]
I just want to point out that the phases I have looked at looks to have an empty AST, which means that a previous phase must have removed the redundant functions. I'm guessing that the compiler reports back to the  user before actual compilation starts then?

**Comment by magnus-madsen** [comment]
Yes, you are right. The compiler is divided into a front-end and a back-end. The front-end will report such errors, whereas the back end (the tree shaker phase) is happy to remove unused functions.

**Comment by magnus-madsen** [comment]
Fixed in master.
