### ISSUE TITLE
Musings about Unit Tests

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1430]
We currently allow unit tests of the form:

```
@test
def repeat01(): Bool = List.repeat(1, -1) == Nil

@test
def repeat02(): Bool = List.repeat(1, 0) == Nil

@test
def repeat03(): Bool = List.repeat(1, 1) == 1 :: Nil
```

and

```
@test
def testArrayLit04(): Array[Int] & Impure = [1, 2, 3, 4]
```

but I wonder if we should use something like:

```
@test
def repeat01(): Test = { actual = List.repeat(1, -1), expected = Nil }
```

instead. This design could then be iterated on- with questions about extra arguments passed in the record, and the exact definition of `Test`.

**Comment by mlutze** [comment]
Another advantage of this is that it would make finer-grained test failure reporting easier. E.g., we can point out at which index in the list the difference occurred, without having to resort to macros.

**Comment by magnus-madsen** [comment]
This should be part of a future test framework.
