### ISSUE TITLE
Remove !, || and &&

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1448]
Remove support for `!`, `||` and `&&`. These should be replaced by the keywords `not`, `or`, and `and`.

This requires updates to documentation, website, and so forth too.

**Comment by esbenbjerre** [comment]
Just to be sure, does this include `∨`, `∧`, `→`, `↔` and `⊕` defined in Bool.flix?

**Comment by magnus-madsen** [comment]
> 
> 
> Just to be sure, does this include `∨`, `∧`, `→`, `↔` and `⊕` defined in Bool.flix?

Leave those intact-- for now. They may get the axe later.

**Comment by magnus-madsen** [comment]
Also for predicates. I will fix it.
