### ISSUE TITLE
Detect unconditionally recursive enums

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1452]
This enum is allowed:
```flix
pub enum E {
    case C(E)
}
```
However, this cannot be used as it is unconditionally recursive.

**Comment by magnus-madsen** [comment]
What about 

```
pub enum E {
    case C(Lazy[E])
}
```

:)

This might complicate matters.

Also, I believe we do allow:

```
pub enum Void {

}
```

which has some uses (a function that never returns).

I don't have a strong opinion. Just a few cents.

**Comment by magnus-madsen** [comment]
I think this is too much of a corner case to worry about.
