### ISSUE TITLE
The unconditional recursion checker should consider laziness

### ISSUE THREAD

**Issue by esbenbjerre** [flix/flix#1458]
Executing

```
namespace LL {

    pub enum LazyList[t] {
        case Empty,
        case Cons(t, Lazy[LazyList[t]])
    }

    pub def constant(x: a): LazyList[a] =
        Cons(x, lazy constant(x))

}

def main(): LL.LazyList[Int32] = LL.constant(42)
```
gives
```
-- Redundancy Error -------------------------------------------------- main/src/library/Playground.flix

>> Unconditionally recursive definition 'constant'. All branches will recurse indefinitely.

10 |     pub def constant(x: a): LazyList[a] =
                 ^^^^^^^^
                 unconditional recursion.
```

**Comment by magnus-madsen** [comment]
Just be clear: Constant is supposed to return an infinite stream of the same value, correct?

**Comment by magnus-madsen** [comment]
A temporary fix: `if (true) lazy constant(x) else ???` or something like that.

**Comment by magnus-madsen** [comment]
@mlutze Thoughts?

**Comment by esbenbjerre** [comment]
> Just be clear: Constant is supposed to return an infinite stream of the same value, correct?

Yes exactly.

**Comment by esbenbjerre** [comment]
> A temporary fix: `if (true) lazy constant(x) else ???` or something like that.
> 
> EDIT: To get you unstuck, not as a solution.

This is a great hack for now, thanks!

**Comment by mlutze** [comment]
> @mlutze Thoughts?

This should be a pretty straightforward fix. I can get a PR out today or tomorrow.

**Comment by magnus-madsen** [comment]
What is the plan? If the call is inside a lazy context we ignore it?

**Comment by mlutze** [comment]
> What is the plan? If the call is inside a lazy context we ignore it?

Yes, that's what we do for lambdas, and a lazy expression can be seen as kind of a special lambda `Unit -> ...`

**Comment by magnus-madsen** [comment]
Fixed! Thanks @mlutze
