### ISSUE TITLE
Documentation for non-defs

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1470]
We currently only have documentation for function definitions. It would be nice to include documentation for other items: enums, type aliases, etc.

**Comment by magnus-madsen** [comment]
Agreed, but we do have some of that:

https://doc.flix.dev/datatypes/
https://doc.flix.dev/records/

or did you have something else in mind?

**Comment by mlutze** [comment]
I was referring to standard library documentation generation.

**Comment by magnus-madsen** [comment]
Oh right, then you are right. We should export enums and type aliases.

Type aliases are eliminated before TypedAst, so we need to deal with that too.

**Comment by magnus-madsen** [comment]
Also type classes and instances (eventually).

**Comment by magnus-madsen** [comment]
I think we should collect a wishlist of features to have in Flixdoc. Then, when we have that list, we can try to find someone to realize it. However, for the short term (say next 6 months), I think it is okay what we have. For example, we would also want type classes and instances to be part of Flixdoc, so rewamping everything now might be a bit too early.

**Comment by magnus-madsen** [comment]
api.flix.dev is being reworked and has its own repo.
