### ISSUE TITLE
ConstraintSystem toString should use the programmer's column names

### ISSUE THREAD

**Issue by mb64** [flix/flix#1477]
When I run this code:
```flix
rel MyRelation(this: Int, that: String)

def main(): #{ MyRelation } = #{
    MyRelation(1, "one").
    MyRelation(2, "two").
}
```
on https://play.flix.dev/, it outputs:
```
MyRelation
------+------
 col0 | col1 
------+------
 1    | one  
------+------
 2    | two  
------+------
```
It would be nice to have the columns named `this` and `that` instead of `col0` and `col1`.

From a cursory glance at the code, it looks like [this section](https://github.com/flix/flix/blob/master/main/src/flix/runtime/fixpoint/ConstraintSystem.java#L203-L207) is responsible for naming the headers.  It looks like it tries to give it the right name, but the `attributes` are `null`.

**Comment by magnus-madsen** [comment]
Hello mb64,

Thanks for reporting this. This is definitely something we would like to fix, but there are some technical issues. 
(Currently a `rel` is like a type alias which is eliminated by the compiler and not available at run-time). 

But I agree that it would be useful if this information was preserved.

**Comment by magnus-madsen** [comment]
The whole setup w.r.t. Datalog has changed making this less relevant.
