### ISSUE TITLE
Reactive UI Framework for Flix

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1480]
Design and implement a Flix library for reactive UI applications inspired by React.

Challenges: How to reconcile the reactive API with say JavaFX?

**Comment by mdiin** [comment]
> Challenges: How to reconcile the reactive API with say JavaFX?

You could take a look at https://github.com/cljfx/cljfx, which is a Clojure wrapper for JavaFX with inspiration from React.

**Comment by magnus-madsen** [comment]
> > Challenges: How to reconcile the reactive API with say JavaFX?
> 
> You could take a look at https://github.com/cljfx/cljfx, which is a Clojure wrapper for JavaFX with inspiration from React.

Will do! (Btw, you should totally re-check out the language and VSCode plugin. We have made amazing progress :))

**Comment by magnus-madsen** [comment]
We will leave this for the community.
