### ISSUE TITLE
Split Type into Type and ProperType

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1481]

**Comment by mlutze** [comment]
This is being done to some extent in https://github.com/flix/flix/pull/1793

One option I'm considering as a further step (after kindedness is handled better) is to make the proper `Type` a GADT, so we can have stronger guarantees on the correctness of types:

```scala
sealed trait Type[K]
...
case class Apply[K1, K2](t1: Type[K1 -> K2], t2: Type[K1]) extends Type[K2]
case class Lambda[K1, K2](t1: Type.Var[K1], t2: Type[K2]) extends Type[K1 -> K2]
```

**Comment by magnus-madsen** [comment]
> ```scala
> sealed trait Type[K]
> ...
> case class Apply[K1, K2](t1: Type[K1 -> K2], t2: Type[K1]) extends Type[K2]
> case class Lambda[K1, K2](t1: Type.Var[K1], t2: Type[K2]) extends Type[K1 -> K2]
> ```

I am a big fan of GADTs, not so much of the flaky Scala implementation.

Ill let you experiment and report back :)

**Comment by magnus-madsen** [comment]
Will be discussed offline, if necessary.
