### ISSUE TITLE
Type Classes: Visibility in Signatures

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1488]
We should decide on the visibility of signatures in classes and instances. E.g. can a signature be private? What about a class?

**Comment by mlutze** [comment]
I propose the following:

* We allow private signatures, but only those with implementations. These can be used as helper functions for other signatures with implementations.
* We allow private definitions in instances, also to be used as helper functions for the implementation functions, which must be public.
  * To allow for this, each instance will need its own namespace. Can we just do something like `<class FQN>$<fresh id>`?

Every part of the interface of the class will be public, while anything used privately be a class or instance will be private.
The only thing missing that I think someone might want is the equivalent of `protected` in Java.

**Comment by magnus-madsen** [comment]
I think what you propose is very reasonable.

Let me play devils advocate for a moment: If you can have all "this stuff" inside classes/instances, would you not also want local type declarations, local type aliases, and so forth? Where does it end? With a robust name resolution scheme/strategy this is probably fine, but I don't think we have that yet. 

The conservative point is the keep what we have and defer these extensions (focusing on other aspects of TCs that we want).

The extreme point is to say:
- Ban everything private from classes/instances.
- Force everything in classes to be public by default.

What is so bad about the extreme point? If you have a complicated impl. you can always write it in the companion namespace and call it from the class/instance. You could then say: Why not go further and ban implementations from classes. Is this because we want to implement `Order` with `compare` but still allow optimized implementations of e.g. `<=`?

**Comment by mlutze** [comment]
These are all good points.

One thing to note is that the points for the companion namespace only apply to classes, not instances. Currently, instances have no real namespace, and no (private) access to the class's companion namespace.

> Is this because we want to implement Order with compare but still allow optimized implementations of e.g. <=?

I think this is something we've agreed we would like to have, so this bars the "extreme" point. But I do think it would be a principled decision to say that a class is only the interface: no type declarations, no implementations.

I'll throw out an idea of allowing `abstract instance`s, analogous to Java's `abstract class`es. This would allow for the "extreme point" while still allowing partial implementation for e.g. `Order`.


Going in the other direction, I don't see a major problem allowing other local declarations; the system we have of "a class is a namespace" should* make it easy to permit this sort of thing. 

\* _probably won't_

**Comment by magnus-madsen** [comment]
What is an "abstract instance"?

Right now we require `override` if you want to override a member in an instance.

Do you think we should also support a `final` or the converse an `open`?

**Comment by mlutze** [comment]
> What is an "abstract instance"?

An instance that has some subset of implementations, but cannot be used directly, and instead has to be implemented by a proper instance.

```flix
class C[a] {
  def doOnce(x: a): a
  def doTwice(x: a): a
}

abstract instance Idempotent C[a] {
  // doOnce still unimplemented
  def doTwice(x: a): a = doOnce(x)
}

instance C[Int] using Idempotent {
  def doOnce(x: Int): Int = 123
}
```

We add another layer:
* class is the outermost interface
* abstract instance provides a default implementation
* proper instance provides a full implementation

Of course, this all assumes we want to go with the "extreme point". IMO it keeps the class clean, but could get annoying depending on how common default implementations are.

> Do you think we should also support a final or the converse an open?

I think there's a principle to be had here, something about the **role** each part of the program/language has.
In my view (at the moment), a class is a contract between the user and instance. A `final` def in a class has no place in the contract, since the instance will surely never touch it. So it's probably better to place this in the companion namespace. Does that seem reasonable?

**Comment by magnus-madsen** [comment]
> We add another layer:
> 
>     * class is the outermost interface
> 
>     * abstract instance provides a default implementation
> 
>     * proper instance provides a full implementation

OK, I understand how. But what happens if you want to have an "abstract instance" somewhere in the middle of the type class hierarchy?

> But I do think it would be a principled decision to say that a class is only the interface: no type declarations, no implementations.

I am very sympathetic to this earlier view point. (But what to do for Order?)

We should also remember that we have instances and instances can apply each other, so you can get implementation details that way for free.

**Comment by mlutze** [comment]
```flix
class Compare[a] {
   def compare(x: a, y: a): Ordering
}

class Order[a] {
  def leq(x: a, y: a): Boolean
  ...
}

instance Order[a] with Compare[a] {
  def leq(x: a, y: a) = ??? // using Compare.compare
  ...
}
```

I was thinking about something like this. But the issue is that `Order[a]`'s type is illegal.

**Comment by magnus-madsen** [comment]
Because it requires "flexible instances" and opens the door for non-termination, right? :/

**Comment by mlutze** [comment]
I think termination is only a concern with UndecidableInatances. In this case we could have overlapping instances. So less of a problem if we implement a "most specific instance" checker.

**Comment by magnus-madsen** [comment]
> 
> 
> I think termination is only a concern with UndecidableInatances. In this case we could have overlapping instances. So less of a problem if we implement a "most specific instance" checker.

Could you not do something like:

```
instance A(x) <= B(x)

instance B(x) <= A(x)
```

and get non-termination?

**Comment by mlutze** [comment]
Ah, right. I suppose we could look for cyclicity, but I think that could get messy.

**Comment by magnus-madsen** [comment]
For now- we have decided that nothing can be private. Neither in classes nor in instances.
