### ISSUE TITLE
Type Classes: Namespacing

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1489]
We should discuss how type classes and namespaces work.

In particular, where is a signature visible? And where is an instance visible?

@mlutze Maybe you could summarize how it currently works-- to kick of the discussion.

**Comment by mlutze** [comment]
Instances are currently globally visible: if you use a signature from a class, we search the whole program for an instance that matches that signature.

Signatures themselves have to be imported. At the moment, the namespace of the signature is the same as the namespace of the class. For example:

```flix
namespace N {
    class C[a] {
        def f(x: a): a
    }

    def g[a: C](x: a): a = f(x)
}

namespace M {
    use N.f;
    ...
}
```

The result of this namespacing is that we can refer to a signature `f` without referring to the class `C` directly.

Classes themselves are also introduced by a use:
```flix
namespace O {
    use class N.C;
    ...
}

**Comment by magnus-madsen** [comment]
@mlutze 
What happens if we demand that instances are declared either:
- In the same namespace as the type class, or
- In the same namespace as the (outer most) type.

This is probably overly restrictive, but I think it could be a safer starting point.

(Question: What is the "namespace" of `Int32`? or records?)

**Comment by mlutze** [comment]
I think Haskell emits a warning for orphan instances. Considering our "no warnings" principle, I think it make sense to emit an error for this case.

> (Question: What is the "namespace" of Int32? or records?)

For primitives, could we put it in the respective library namespace?
For records, what if we only allow type classes on type aliases? Then the namespace is where the alias is declared. Perhaps too restrictive?

**Comment by magnus-madsen** [comment]
As for importing, I would suggest:

```
use Namespace/Typeclass.signature
```

This will require some disambiguation... 

Now for `ToString`, I think that:

```
use ToString/ToString.toString
```

is a bit excessive, but that is only because `ToString` is inside a namespace. We should probably just put it in the root. (Later when can use some prelude stuff to actually place it in a namespace, if we want).

**Comment by magnus-madsen** [comment]
`Core/ToString.toString` would probably also be ok

**Comment by mlutze** [comment]
There's a bit of difficulty with ambiguity.

```flix
use ToString.toString
    ^^^^^^^^ ^^^^^^^^
     class     sig

use ToString.toString
    ^^^^^^^^ ^^^^^^^^
     nspace    def
```

I got around this with classes by adding the `use class ToString` syntax. That was meant as a placeholder.

**Comment by magnus-madsen** [comment]
> 
> 
> There's a bit of difficulty with ambiguity.
> 
> ```
> use ToString.toString
>     ^^^^^^^^ ^^^^^^^^
>      class     sig
> 
> use ToString.toString
>     ^^^^^^^^ ^^^^^^^^
>      nspace    def
> ```
> 
> I got around this with classes by adding the `use class ToString` syntax. That was meant as a placeholder.

I see the problem, so we have two choices:

- New syntax (some other separator?)
- Disambiguate (e.g. we would have to consider both cases in the Namer/Resolver).

**Comment by mlutze** [comment]
Considering option 2, could we consider classes as equivalent to the namespaces with their own names? So for the case of `toString`:

```flix
namespace ToString {
    // <empty?>
}

class ToString[a] {
    def toString(x: a): String
}
```

We put signature `toString` under the namespace `ToString`. That way there's no ambiguity in `use ToString.toString`: `ToString` definitely refers to a namespace and not a class.

**Comment by magnus-madsen** [comment]
> Considering option 2, could we consider classes as equivalent to the namespaces with their own names? So for the case of `toString`:
> 
> ```
> namespace ToString {
>     // <empty?>
> }
> 
> class ToString[a] {
>     def toString(x: a): String
> }
> ```
> 
> We put signature `toString` under the namespace `ToString`. That way there's no ambiguity in `use ToString.toString`: `ToString` definitely refers to a namespace and not a class.

I think I like that.

What happens if some declares a `toString` inside `ToString` namespace?

(I would also like to explore how e.g. Rust and other languages deal with this).

**Comment by mlutze** [comment]
> What happens if some declares a `toString` inside `ToString` namespace?

I think we should throw an error. I don't see any good reason for a developer to want a separate definition with the same name as a signature.

**Comment by mlutze** [comment]
After some exploration, I no longer think the "class as namespace" idea works. It means we would have both `A/B.ToString` and `A/B/ToString.toString`, one with a slash and one with a dot.

I'm now thinking we should follow the style of enums. There's still some ambiguity to resolve, but it's not as much as I had thought:

`use A/B.ToString.toString` is unambiguously a signature, for example.

**Comment by magnus-madsen** [comment]
| What it is  | What it means |
| ------------- | ------------- |
| A/B.ToString.toString | Sig toString in class ToString in ns A/B  |
| A/B.Color.Red| Case Red in enum Color in ns A/B |
| A/B.Color| Type/TypeAlias Color in ns A/B |
| A/B.foo| Function (def) foo in ns A/B |

Yes? What did I forget? (Maybe rel declarations? annotations (which we don't have yet))?

**Comment by mlutze** [comment]
I think the parsing and disambiguation based on the little details may end up being a pain to maintain.

The class-as-namespace direction unifies the syntax and seems to work conceptually.

**Comment by magnus-madsen** [comment]
> The class-as-namespace direction unifies the syntax and seems to work conceptually.

Could you briefly summarize how this works? Or is that what is in the table above?

Would the following work in that proposal?:

```
class Monoid[m] {
  def combine(x: a, y: a): a
}

namespace Monoid {
  def combineAll[a: Monoid](l: List[a]): a
}
```

I.e. you can have similarly named namespaces and type classes (as long as their defs/sigs are disjoint)?

I assume that if you declare a method `m` in both you would get a `DuplicateDefSig` or the like, right?

**Comment by magnus-madsen** [comment]
OK, and to make your life harder. What about:

```
class Monoid[m] {
  def combine(x: a, y: a): a
  // assume defs are allowed:
  def foo(x: a): Bool = true()
}

namespace Monoid {
  def combineAll[a: Monoid](l: List[a]): a
  def true(): Bool = true // not that this is not pub.
}
```

Is this allowed?

**Comment by magnus-madsen** [comment]
And vise versa:

```
class Monoid[m] {
  def combine(x: a, y: a): a
}

namespace Monoid {
  def combineAll[a: Monoid](l: List[a]): a = /* calls combine */
}
```

**Comment by mlutze** [comment]
> Would the following work in that proposal?:
> 
> ```
> class Monoid[m] {
>   def combine(x: a, y: a): a
> }
> 
> namespace Monoid {
>   def combineAll[a: Monoid](l: List[a]): a
> }
> ```
> 
> I.e. you can have similarly named namespaces and type classes (as long as their defs/sigs are disjoint)?
> 
> I assume that if you declare a method `m` in both you would get a `DuplicateDefSig` or the like, right?

Yes, exactly. Each def and sig we trait as under the Monoid namespace. Conflicts between def and sig names are forbidden.



> OK, and to make your life harder. What about:
> 
> ```
> class Monoid[m] {
>   def combine(x: a, y: a): a
>   // assume defs are allowed:
>   def foo(x: a): Bool = true()
> }
> 
> namespace Monoid {
>   def combineAll[a: Monoid](l: List[a]): a
>   def true(): Bool = true // not that this is not pub.
> }
> ```
> 
> Is this allowed?

I think this should be allowed. 

> And vice versa:
> 
> ```
> class Monoid[m] {
>   def combine(x: a, y: a): a
> }
> 
> namespace Monoid {
>   def combineAll[a: Monoid](l: List[a]): a = /* calls combine without Monoid prefix */
> }
> ```

Yes, I think this should be allowed as well.


This also changes naming style (so parsing won't be so complicated):

What it is | What it means
-- | --
~A/B.ToString.toString~ | removed
A/B/ToString/toString | Sig or Def toString in ns A/B/ToString
A/B.Color.Red | Case Red in enum Color in ns A/B
A/B.Color | Type/TypeAlias/Class Color in ns A/B
toString | Var/Def/Sig toString
Red | Type/TypeAlias/Class/Case Red
ToString.toString | Sig or Def toString in namespace ToString
Color.Red | Case Red in enum Color OR Type/TypeAlias/Class Red in ns Color

**Comment by magnus-madsen** [comment]
You mean:

```
A/B/ToString.toString - Sig or Def
```
right? or?

**Comment by mlutze** [comment]
> You mean:
> 
> ```
> A/B/ToString.toString - Sig or Def
> ```
> 
> right? or?

Yes! Fixed.

**Comment by magnus-madsen** [comment]
I like this proposal more on more. 

I have one more question. Assuming that we allow definitions in a type class, can we articulate:

When does a def belong in a type class and when does it belong in its "companion" namespace?

For example:

This:

```
class Order[a] {
  def cmp(x: a, y: a): ...
  def min(x: a, y: a): a = ...
}
```

or this:

```
class Order[a] {
  def cmp(x: a, y: a): ...
}

namespace Order {
  def min[a: Order](x: a, y: a): a = ...
}
```

**Comment by mlutze** [comment]
My initial thought is that the class itself should contain the "core" definitions. For `Order` it might be `lt`, `gt`, `cmp`, `leq`, `geq`. Then "corollary" definitions would go in the companion namespace. `min` is usually defined in terms of comparison, so it would go in the companion.

But that's a somewhat imprecise and opinion-based idea; I'd like to have a less "debatable" principle.

Another thing to consider is that anything we put in the companion namespace can't be optimized per-instance.

**Comment by magnus-madsen** [comment]
> My initial thought is that the class itself should contain the "core" definitions. For `Order` it might be `lt`, `gt`, `cmp`, `leq`, `geq`. Then "corollary" definitions would go in the companion namespace. `min` is usually defined in terms of comparison, so it would go in the companion.
> 
> But that's a somewhat imprecise and opinion-based idea; I'd like to have a less "debatable" principle.

Indeed. It feels a bit nebulous. 

Yet, I think this is what we should do, so feel free to go ahead and merge the namespaces :)

> Another thing to consider is that anything we put in the companion namespace can't be optimized per-instance.

I am not sure what this means.

**Comment by mlutze** [comment]
> > Another thing to consider is that anything we put in the companion namespace can't be optimized per-instance.
> 
> I am not sure what this means.

For example, if we have
```
instance Ord[Unit] { ... }
namespace Order {
  def min[a: Order](x: a, y: a): a = ...
}
```

Then we end up doing extra calculations like
```
if (() <= ()) () else ()
```

But if we implement the instance for unit, we can have
```
def min(x: Unit, y: Unit): Unit = ()
```

In this case that's all probably compiled away, but with more complex data structures and classes, there may be significant speedups to be had.

**Comment by mlutze** [comment]
> Yet, I think this is what we should do, so feel free to go ahead and merge the namespaces :)

Great!

**Comment by magnus-madsen** [comment]
> But if we implement the instance for unit, we can have
> 
> ```
> def min(x: Unit, y: Unit): Unit = ()
> ```

I see. This assumes that you can override the default definition of `min` or alternatively that you re-implement `min` for every type class instance. 

I still think we need a principle for when to put stuff where, but hopefully that will come with experience.

**Comment by magnus-madsen** [comment]
The principle is that everything should go in the TC if possible. (So that it can be overriden).
