### ISSUE TITLE
Type Classes: Compile a list of the most critical parts

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1490]
We should compile a list of the core functions that should be reviewed carefully in the type class implementation.

**Comment by mlutze** [comment]
* `Scheme.lessThanEqual`
  * Checks that constraints are sufficiently declared in function definitions
* Everything in `ContextReduction.scala`
  * Checks for entailment of constraints, does simplifications on redundant constraints.
* `Monomorph.specializeSigSym`
  * Converts signatures to definitions
* `Typer.checkSigMatch`
  * Checks that instances properly implement their classes
* `Typer.checkOverlap`
  * Checks that instances don't overlap (i.e. any fully instantiated type only has one instance that matches)

**Comment by magnus-madsen** [comment]
Thanks! - I think I got a handle on it now :)
