### ISSUE TITLE
Type Classes: Should enums have class constraints?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1491]
For example, do we want to allow this:

```
enum Box[a: Eq] { 
  case Box(a)
}
```

Thus, everywhere a Box is used we must have `Eq` on its elements.

**Comment by magnus-madsen** [comment]
@stephentetley Hi Stephen, I thought you might now whether this is allowed in Haskell and whether it is useful?

**Comment by stephentetley** [comment]
IIRC DatatypeContexts were considered a misfeature of Haskell and removed as GADTs were introduced. With DatatypeContexts you still always needed to put the constraint on any function declaration that used the type so it wasn't providing any extra utility. 

I think a few people at the time of the removal debate found them use for documentation purposes.

There's some context in this like, I'll have a look for the haskell-cafe thread this evening:

https://stackoverflow.com/questions/7438600/datatypecontexts-deprecated-in-latest-ghc-why

**Comment by magnus-madsen** [comment]
Thanks Stephen! That is very useful to know. It sounds like we should omit this feature from our initial design.

**Comment by stephentetley** [comment]
I couldn't find the thread I had in mind, but there certainly is a clear majority opinion that datatype contexts (class constraints) were as misfeature:

https://gitlab.haskell.org/ghc/ghc/-/issues/8026
https://mail.haskell.org/pipermail/haskell-cafe/2013-April/107832.html
https://mail.haskell.org/pipermail/haskell-prime/2010-July/003249.html

**Comment by magnus-madsen** [comment]
@mlutze I think this means that we should not support such constraints. Will you look into removing them (now or in the next PR)?

**Comment by mlutze** [comment]
Got it!

**Comment by magnus-madsen** [comment]
Fixed.
