### ISSUE TITLE
Type Classes: Constraints vs. Kind Ascriptions

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1492]
We need to decide on the syntax for type class constraints vs. kind ascriptions. We currently have the following:

A kind ascription:

```
def f[a :# Type, b :# Bool](f: a -> a & b): Int = ...
```
The syntax `:#` was intended as a place holder.

We also have:

```
def foo[a: Eq]() ...
instance Show[List[a]] with [a : Show] { ... }
```

I am not sure what the syntax is if `a` must implement multiple type classes.

What I have suggested in the past- but this is not a strongly held opinion- is that we should reserve `:` for type and kind ascriptions, i.e. `42: Int` and `b: Type` for symmetry. But then we need something else for type classes...

**Comment by mlutze** [comment]
> I am not sure what the syntax is if a must implement multiple type classes.

At the moment it is `... with [a : Show : Read]`.

**Comment by mlutze** [comment]
What about `a :< Eq` or `a <: Eq` for type classes? It kind of indicates an "element of" relation. Though it may be confusing for those used to subtyping.

**Comment by magnus-madsen** [comment]
> What about `a :< Eq` or `a <: Eq` for type classes? It kind of indicates an "element of" relation. Though it may be confusing for those used to subtyping.

Yes and yes. It looks nice, but could also be confusing. I guess `:<` is different from `<:` (which is the sub-typing one, correct me if I am wrong).

**Comment by mlutze** [comment]
Additional question: Where should we allow kind ascriptions? Assuming we land on `:` for the syntax, do we allow e.g.
```flix
def f(x : a : Type): String = ???
```

I think that might get confusing and would expect we should only allow ascriptions on explicit tparams:
```flix
def f[a: Type](x: a): String = ???
```

**Comment by mlutze** [comment]
Perhaps we should allow them on all types which are not themselves ascriptions. For instance:

```flix
instance Functor[List : Type -> Type] {
    ...
}
```

**Comment by magnus-madsen** [comment]
> 
> 
> Additional question: Where should we allow kind ascriptions? Assuming we land on `:` for the syntax, do we allow e.g.
> 
> ```
> def f(x : a : Type): String = ???
> ```
> 
> I think that might get confusing and would expect we should only allow ascriptions on explicit tparams:
> 
> ```
> def f[a: Type](x: a): String = ???
> ```

For expressions, we have a very regular answer. If `e` is an expression then so is `e : t` and `e : tau` can be used *anywhere* that `e` can be used.

Could we not do the same for types? `t : kind` is a type and can occur anywhere a type `t` can occur.

**Comment by magnus-madsen** [comment]
(Note that `(e: Int) : Int` is also an expression.)

**Comment by magnus-madsen** [comment]
***If*** we are only going to have single parameter type classes then I find Rust's syntax pretty nice:

```
def f[a: Eq + Show + Ord](x: a): Bool = ...
```

**Comment by magnus-madsen** [comment]
There is also an option of having *two* syntaxes for type classes: one for the specific case where there is a single type variable and one with multiple params (if we are going to have those).

**Comment by magnus-madsen** [comment]
I would like to propose the following:

- We use `:` for both type and kind ascriptions (e.g. `42 : Int32 : Type`).
- We use `a has Eq` as a short-hand for `Eq[a]` in a type parameter list.
- We use `with Eq[a], ToString[a]` in long form.

A few examples:

```
pub def map[a: Type, b: Type, ef: Bool](f: a -> b & ef, xs: List[a]): List[b] & e
```

```
pub def memberOf[a has Eq](a: a, xs: List[a]): Bool = match xs {
    case Nil => false
    case x :: rs => if (x == a) true else memberOf(a, rs)
}
```

```
pub def memberOf(a: a, xs: List[a]): Bool with Eq[a] = match xs {
    case Nil => false
    case x :: rs => if (x == a) true else memberOf(a, rs)
}
```

```
pub def minimum[t : Type -> Type, a: Type](t: t[a]): Option[a] with Foldable[t], Order[a]
```


This, though, is not great:

```
pub def minimum[t : Type -> Type has Foldable, a: Type has Order](t: t[a]): Option[a] with Foldable[t], Order[a]
```

But, it could be argued that in:

```
pub def minimum[t has Foldable, a has Order](t: t[a]): Option[a] with Foldable[t], Order[a]
  // and
pub def minimum[t, a](t: t[a]): Option[a] with Foldable[t], Order[a]
  // and
pub def minimum(t: t[a]): Option[a] with Foldable[t], Order[a]
```

we should be able to easily infer the kinds of the types. (Thus the ugly scenario should never be needed).

Thoughts?

I think we should implement this -- and then we can always iterate on it.

**Comment by mlutze** [comment]
Is the "long form" to allow implicit type parameters?

**Comment by magnus-madsen** [comment]
> 
> 
> Is the "long form" to allow implicit type parameters?

No. I think the long form is just more "regular" and it can be generalized to multi param TCs, and finally, it allows you to move the TCs later in the signature (which imo makes it more readable). Its somewhat similar to what Rust does.

**Comment by magnus-madsen** [comment]
Oh, and it could in theory work for the type param elison case:

```
pub def minimum(t: t[a]): Option[a] with Foldable[t], Order[a]
```

This signature is nice because you immediately see it has one param `t` of type `t[a]` and the there is some stuff later.

**Comment by magnus-madsen** [comment]
This, of course, applies to me:

![image](https://user-images.githubusercontent.com/2287953/109970060-eae9fe00-7cf4-11eb-94e8-55f58b9a474e.png)

**Comment by mlutze** [comment]
I like the `with` syntax.

Including both ways to express it goes against my personal preference of not having more than one "right" way of doing things. But I guess this case isn't terribly offensive to me.

We might also want to consider whether these signatures might be getting too long. Is it worth introducing an "overhead" type signature, as in Haskell?

**Comment by magnus-madsen** [comment]
What is an "overhead" signature?

**Comment by mlutze** [comment]
Not sure what it's actually called. but I am referring to e.g.

```haskell
foo :: Int -> Bool -> [String] -> [Int]
foo numCookies isMonday favWords = ...
```

The types are above the formal parameters, rather than inline.

**Comment by magnus-madsen** [comment]
> 
> 
> Not sure what it's actually called. but I am referring to e.g.
> 
> ```haskell
> foo :: Int -> Bool -> [String] -> [Int]
> foo numCookies isMonday favWords = ...
> ```
> 
> The types are above the formal parameters, rather than inline.

I like cookies.

I think that Flix aims to keep types close to their terms. That is why we have the inline style in the first-place `def f(x: Int, y: Int)`.

**Comment by magnus-madsen** [comment]
We might as well also print types as:

```
>> The type scheme: 'Int32 -> Bool with Eq[Int32]' cannot be generalized to 'Int32 -> Int32'.
```

instead of:

```
>> The type scheme: 'Int32 -> Bool with [Int32 : Eq]' cannot be generalized to 'Int32 -> Int32'.
```

**Comment by mlutze** [comment]
If we want multiple classes on a tparam, what should the syntax be? E.g.

```
def f[a has Order and Functor](x: a): Bool = ???
```

Or just disallow multiple constraints and force them to the postfix position?

**Comment by magnus-madsen** [comment]
> 
> 
> If we want multiple classes on a tparam, what should the syntax be? E.g.
> 
> ```
> def f[a has Order and Functor](x: a): Bool = ???
> ```
> 
> Or just disallow multiple constraints and force them to the postfix position?

Good question. I did not think of that. I dont want to use `and` because that is used both for term and type level Booleans.

We could require the postfix position or something like:

```
def f[a has Order + Functor](x: a): Bool = ???
```

(Don't like it).

**Comment by magnus-madsen** [comment]
Alternative:

```
def f[a has Order with Functor](x: a): Bool = ???
```

@mlutze thoughts?

**Comment by magnus-madsen** [comment]
Alternatives:

- Short-hand syntax only works when type class params require a single TC.
- Drop short-hand syntax and require the `with Eq[a]` syntax on the RHS.

**Comment by mlutze** [comment]
I prefer not to have extra words in the type parameters; seems noisy.

The short-hand syntax seems quite convenient, but disallowing multiple constraints might lead to this situation:
I have `f[a has Order] ...` but then I realize I need to add another constraint. Now I have to remove from the left and add twice as much to the right.

RHS-only option has the following perks:
* Uniform with type constraints in other places
* Robust to changes, e.g. if we were to add multi-param type constraints
* Reduced overall complexity
  * don't need to check and combine left and right
  * can get rid of illegal type constraint checks

**Comment by mlutze** [comment]
I'm in favor of RHS only.

**Comment by magnus-madsen** [comment]
Just to be clear, what *do* you intend to allow on the LHS? Introduction of type parameters plus their kinds?

**Comment by mlutze** [comment]
Yes, I'm in favor of tparams and kinds on the left, type constraints on the right.

**Comment by magnus-madsen** [comment]
Just to sum up, the plan is to allow all of the following:

```scala
def map(f: a -> b & ef, xs: List[a]): List[b] & ef = ...
```

```scala
def map[a: Type, b: Type, ef: Bool](f: a -> b & ef, xs: List[a]): List[b] & ef = ...
```

```scala
def memberOf(x: a, xs: List[a]): Bool with Eq[a] = ...
```

```scala
def memberOf(x: a, xs: List[a]): Bool with Eq[a] = ...
```

```scala
def minimum(t: t[a]): Option[a] with Foldable[t], Order[a] = ...
```

(Note: If I understood correctly there is a single with clause separated by commas, i.e. this is wrong `with Foldable[t] with Order[a]`, right?)

```scala
def minimum[t : Type -> Type, a: Type](t: t[a]): Option[a] with Foldable[t], Order[a] = ...
```

Is this allowed (variables explicitly introduced but without kinds)?:

```scala
def minimum[t, a](t: t[a]): Option[a] with Foldable[t], Order[a] = ...
```

I think, either:

- Not allowed, or
- Assumes that `t` and `a` have type `Type`- but then why allow it?

I am pretty happy with the above.

We have essentially taken the Haskell style `Constraints => Type` and done two useful things (imo):

- Flipped the order `Type <= Constraints` so that the type is the first thing you see. 
- You can read the signature as "function from x to y subject to C1, C2, etc.
- We have used our keyword-based principle with the `with` connective after the return type.

For reference, compare (I hope my Haskell is right):

Haskell
```haskell
minimum :: Foldable t, Order a => t a -> Option a
```

vs. 

Flix
```scala
def minimum(t: t[a]): Option[a] with Foldable[t], Order[a] = ...
```

**Comment by magnus-madsen** [comment]
Summoning @stephentetley Do you have any reactions or concerns why this scheme would not scale/work out?

**Comment by mlutze** [comment]
> (Note: If I understood correctly there is a single with clause separated by commas, i.e. this is wrong with Foldable[t] with Order[a], right?)

Yes, this would match the syntax for classes and instances.

> Is this allowed (variables explicitly introduced but without kinds)?:

We might want to allow this if we explore the explicit tparam application idea, e.g. `toString[List[String]](Nil)` rather than `toString(Nil : List[String])`. (Can't find the related issue.)

**Comment by magnus-madsen** [comment]
> We might want to allow this if we explore the explicit tparam application idea, e.g. `toString[List[String]](Nil)` rather than `toString(Nil : List[String])`. (Can't find the related issue.)

Right. But I think we can defer that.

**Comment by stephentetley** [comment]
Thanks for the notification Magnus, I've looking briefly and it looks good - I'll try to have a fuller look tonight when I have more time.

**Comment by stephentetley** [comment]
> def minimum(t: t[a]): Option[a] with Foldable[t], Order[a] = ...

I like this style, it's very similar to F#'s `when` but with F# I think the `when` syntax appeared after some naming conventions had been established so signatures are perhaps less clear than they would be if the conventions were uniform (I'm particularly thinking about type param variables being both upper case - commonly 'T or 'U - and being lower case like other ML languages). 

With Flix getting similar syntax when it's still a young language, it won't suffer from this problem.

**Comment by magnus-madsen** [comment]
Sounds good! Thanks for the extra look.

@mlutze I think we can proceed.
