### ISSUE TITLE
Run benchmarks in workflow

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1494]
I assume this can be done with a workflow step like:
* checkout previous commit
* run benchmarks -> x
* checkout PR commit
* run benchmarks -> y
* compare x vs y, fail if there's a significant drop in performance

**Comment by magnus-madsen** [comment]
Yes, maybe as a GitHub action. (Except, of course as our current setup already shows, VMs tend to have unpredictable performance).

It would be nice if we had this infrastructure or some bot you could ask for performance review.

**Comment by magnus-madsen** [comment]
Even just a bot that pastes the result of running two commands for two different checkouts would be useful

**Comment by magnus-madsen** [comment]
Fixed. Thanks @mlutze !

**Comment by magnus-madsen** [comment]
Oh and the current command is !!!benchmark
