### ISSUE TITLE
Possible bug in effect system when nested enums use Lazy

### ISSUE THREAD

**Issue by esbenbjerre** [flix/flix#1498]
When I try to compile

```
namespace LazyList {

    pub enum LazyList[t] {
        case Empty,
        case Cons(t, Lazy[LazyList[t]])
    }

    pub def map(f: a -> b & e, xs: LazyList[a]): LazyList[b] & e = match xs {
        case Empty => Empty
        case Cons(h, t) => Cons(f(h), lazy map(f, force t))
    }

}

opaque type LazyList2[t] = Lazy[LazyList.LazyList[t]]

namespace LazyList2 {

    pub def map(f: a -> b & e, xs: LazyList2[a]): LazyList2[b] & e =
        let LazyList2(ys) = xs;
        LazyList2(lazy LazyList.map(f, force ys)) as & e

}

def main(): Int32 = 42
```
I get
```
>> The type scheme: '∀(b, 36757).b -> b -> LazyList2[b] -> LazyList2[b]'
cannot be generalized to '∀(a, b, e).a -> b & e -> LazyList2[a] -> LazyList2[b] & e'.

19 |     pub def map(f: a -> b & e, xs: LazyList2[a]): LazyList2[b] & e =
                 ^^^
                 unable to generalize the type scheme.
```
I apologize for the long example, but I've been unable to boil it down.
Am I missing something, or is this a bug?

**Comment by esbenbjerre** [comment]
I've tried adding type casting anywhere I could think of, but to no avail.

**Comment by magnus-madsen** [comment]
Does it work if you require all functions to be pure?

Right now we require that for `lazy e`, we must have that `e` is pure.

I am not sure if that is the problem.

**Comment by magnus-madsen** [comment]
If this is the case, @JonathanStarup is working on a solution.

**Comment by esbenbjerre** [comment]
> Does it work if you require all functions to be pure?
> 
> Right now we require that for `lazy e`, we must have that `e` is pure.
> 
> I am not sure if that is the problem.

It does work then, yes.
I was not aware of that limitation. I will keep all functions pure until the solution is merged in.

**Comment by magnus-madsen** [comment]
> I was not aware of that limitation. I will keep all functions pure until the solution is merged in.

We have not yet decided if it is a (i) design choice, (ii) design mistake, or (iii) limitation :D
