### ISSUE TITLE
Using :: in a namespace where a Cons type is defined

### ISSUE THREAD

**Issue by esbenbjerre** [flix/flix#1505]
I'm not sure whether this is considered a bug or not, but using the :: operator in a namespace where some other Cons type is defined, causes Flix to use that rather than the one in List.flix. This means I'm currently unable to implement a method that converts a LazyList to a List.

**Comment by magnus-madsen** [comment]
I assume you can still write `List.Cons` right?

I am not sure if this a feature or a misfeature :)

**Comment by esbenbjerre** [comment]
> I assume you can still write `List.Cons` right?
> 
> I am not sure if this a feature or a misfeature :)

This fails inside the LazyList namespace. I'm not sure why.
```
>> Undefined type 'List'.

90 |             case Cons(h, t) => toListHelper(force t, List.Cons(h, acc))
                                                          ^^^^^^^^^
                                                          type not found.
```

**Comment by magnus-madsen** [comment]
OK, I am not sure what the best solution is w.r.t. cons.

For now, I would suggest to rename `Cons` into `LazyCons` (to make progress).
