### ISSUE TITLE
Tags should be allowed to start with underscore (and then not count as unused)

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1506]
Like:

```
enum Color {
  case _Red,
  case Blue
}
```

**Comment by stephentetley** [comment]
Hi Magnus, I think something similar happens with type parameters. It means you can't have phantom types...

~~~

pub opaque type Distance[_unit] = Float64

pub enum Metres {}

pub def metres(x: Float64): Distance[Metres] = Distance(x)

def main(): Unit & Impure =
    let x : Distance[Metres] = metres(1.0f64);
    let Distance(d1) = x;
    Console.printLine("Dist: ${Float64.toString(d1)}")

~~~

The error currently is...

~~~
-- Type Error -------------------------------------------------- ..\doodles\working\Phantom.flix

>> Unable to unify the types: 'Distance' and 'Distance'.

8 |>     let x : Distance[Metres] = metres(1.0f64);
9 |>     let Distance(d1) = x;
10 |>     Console.printLine("Dist: ${Float64.toString(d1)}")

mismatched types.


Type One: Distance['a]
Type Two: Distance[Metres]

-- Type Error -------------------------------------------------- ..\doodles\working\Phantom.flix

>> The type scheme: '∀(78549).Float64 -> Distance['a]' cannot be generalized to 'Float64 -> Distance[Metres]'.

5 | pub def metres(x: Float64): Distance[Metres] = Distance(x)
            ^^^^^^
            unable to generalize the type scheme.

Possible fixes:

  (1) The function is declared as too polymorphic. Remove some type variables.
  (2) The expression body of the function is incorrect.



Compilation failed with 2 error(s).

~~~

I was trying this in "real" code about a month ago, then the error was flagging the phantom type parameter `_unit` as unused (f I remember correctly). Now the compiler seems to accept the phantom but has type errors at use-sites.

**Comment by magnus-madsen** [comment]
@stephentetley Thanks, we will look into that too.

**Comment by mlutze** [comment]
There may be some naming ambiguity here. Currently we parse underscores as lower letters, so `_Red("hello")` will look like a function call.

**Comment by mlutze** [comment]
I put the phantom types in a new issue. There are two problems going on here:
1. Using types as phantom parameters doesn't count. (The error doesn't come up in Stephen's posted code since `Metres` is marked public).
2. Issues with unification of Enums with kind variables.

**Comment by magnus-madsen** [comment]
@stephentetley 

Does the following seem to work (it works here):

```
opaque type Distance[_unit :# Type] = Float64 // notice the kind annotation

pub enum Metres {}

def metres(x: Float64): Distance[Metres] = Distance(x)

@test
def testOpaqueType34(): Bool = match metres(123.4) {
    case Distance(d1) => d1 == 123.4
}
```

NOTE: The syntax for the kind annotation `_unit :# Type` is *definitely* going to change, so beware if you start using it.

(At the moment I cannot explain *why* the annotation is needed- that is probably something we can fix in the future).
