### ISSUE TITLE
Default Imports/Uses/Prelude

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1512]
We currently abuse the global namespace as the place to declare e.g. `Option` and `List`. I think it would make more sense to move these into the `Option` and `List` namespaces. Then we implicitly insert the following uses in the top of every file:

```
use Option.Option;
use List.List;
```

Does this approach make sense? Is there a better way?

**Comment by magnus-madsen** [comment]
@mlutze Any thoughts?

**Comment by mlutze** [comment]
Scala's `Predef` defines aliases to the globally accessible types, and is the only source implicitly inserted. I think it would be easier to organize if we only import one source like this, if possible.

**Comment by magnus-madsen** [comment]
But we can't really "import a file" so how would that work? Or am I misunderstanding something?

**Comment by mlutze** [comment]
For example,

```flix
// Prelude.flix
namespace Prelude {
    use List.List;
    ...
    type alias List[a] = List.List[a]
    ...
}
```

```flix
// MyProgram.flix
namespace MyProgram {
    // implicitly: use Prelude.List;
    ...
}
```

So everything from Prelude is imported. Does that work?

**Comment by magnus-madsen** [comment]
I don't understand :)

```
namespace Prelude {
    use List.List;
    ...
    type alias List[a] = List.List[a] // Would this not cause a clash with List.List and raise an error?
}
```

OK; I guess my question is also: Do you envision a "single" use or something where we generate /n/ uses of all the stuff we see in the prelude?

**Comment by mlutze** [comment]
Essentially, it's the same as your proposal of importing each thing individually at the top of the file, but:
* The imports come from `Prelude.flix`:
  ```
  use Prelude.Option;
  use Prelude.List;
   ```
* `Prelude.flix` "forwards" the names to their respective namespaces.
  ```
  namespace Prelude {
    use List.List as List1; // to avoid clashing (I don't remember if this is the right syntax)
    pub type alias List[a] = List1[a]
  }
  ```

The advantage, in my opinion, is that we get an automatically updated list of everything that's implicitly imported.

> Do you envision a "single" use or something where we generate /n/ uses of all the stuff we see in the prelude?

I envision a list of uses:
```
use Prelude.Option;
use Prelude.List;
use Prelude.Map;
...
```

Hopefully that's clearer?

**Comment by magnus-madsen** [comment]
OK; I understand.

I am not sure about using type aliases. It is fine as long as they are erased (like now) but once they start "showing up" in type errors it might be confusing...

**Comment by magnus-madsen** [comment]
We have recently reworked the namespace (now module) mechanism.
Hence this ticket is most likely no longer relevant.
Feel free to common and/or re-open if it is.
