### ISSUE TITLE
Mutation Testing

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1516]
Since Flix has testing built-in, could we expand this to include test coverage? One (big) step further, could we expand it to include [mutation testing](https://en.wikipedia.org/wiki/Mutation_testing)?

I think when safety and correctness are core goals, testing (and eventually test testing) follows closely. On the other hand, we don't want unnecessary bloat.

**Comment by magnus-madsen** [comment]
Yes, I think mutation testing is very interesting.

Do you mean mutation testing *for the compiler* or for *Flix test suites*. I would assume the latter?

That is, to improve the coverage of a test suite for e.g. the standard library.

**Comment by mlutze** [comment]
> Do you mean mutation testing for the compiler or for Flix test suites. I would assume the latter?

Yes, the latter. Inspired by some typos in the `&&`-to-`and` transition which would ideally have been caught by unit tests.

**Comment by magnus-madsen** [comment]
Indeed. It would be nice to have a mutation testing framework. This would also make a great case that the testing framework should be built in to the compiler. I think this would make for a great (student) project for someone to pick up.
