### ISSUE TITLE
Add ToString Instances

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1528]
- [ ] Add `ToString` instances for `Map`, `Set` and `MutList`, `MustSet`, and ` MutMap`.
- [ ] Add `ToString` instances for arrays. (Cast to pure.)
- [ ] Add `ToString` instances for tuples N=2 to N=10.
- [ ] Move instances declarations in `ToString.flix` into the files where the data types are declared. (E.g. into `List.flix`).
  - If a type is built into Flix, e.g. `Int32` then the instance should stay inside `ToString.flix`.
- [ ] Move tests from `TestToString.flix` into `TestList.flix` etc. 
- [ ] Ensure that instances are declared in a consistent order and consistent place.
- [ ] Add more tests in a systematic way. 

The following should not have ToString instances:
- Channel
- Ref
- Lazy

Relevant files:
- `ToString.flix`
- `FromString.flix`
- `TestToString.flix` - (to be deleted or at least shrunk).
- `TestFromString.flix` ` - (to be deleted or at least shrunk).

**Comment by esbenbjerre** [comment]
Do you have any  thoughts on efficiency in this context?
Specifically, I consider foldRight vs. StringBuilder as & Pure.

**Comment by magnus-madsen** [comment]
> Do you have any thoughts on efficiency in this context?
> Specifically, I consider foldRight vs. StringBuilder as & Pure.

Good question. I think, for now, let us good for the clearest implementation. 

(As long as it does not overflow the stack)
