### ISSUE TITLE
Add Hash Type Class

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1531]
Improve upon the `Hash` type class:

- [ ] Move instances to proper namespaces.
- [ ] Move tests to proper namespaces.
- [ ] Add instances for Set
- [ ] Add instances for Map
- [ ] Add instances for tuples N=2 to N=10
- [ ] Add other missing instances, see e.g. #1560

Refactor existing instances, in particular  this:

```
        def hash(x: Validation[t, e]): Int = match x {
            case Success(v) => Hash.hash(v)
            case Failure(v) => Hash.hash(v)
        }
```

should be something more like:

```
        def hash(x: Validation[t, e]): Int = match x {
            case Success(v) => 3 * Hash.hash(v)
            case Failure(v) => 7 * Hash.hash(v)
        }
```

and so forth (i.e. to ensure that different constructors get different hashes...)

**Comment by esbenbjerre** [comment]
Should mutable types such as `Array`, `Mut{List, Map, Set}` have hash instances?
If we aim to keep the law that `a == b => hash(a) == hash(b)` I see some potential problems, depending on how we treat equivalence of types that uses references.

For reference, the output of hash code(s) for an `Array` in Scala
```scala
scala> Array(1,2,3).##
val res9: Int = 820074024

scala> Array(1,2,3).hashCode
val res10: Int = 150499707

scala> Array(1,2,3).##
val res11: Int = 770854681

scala> Array(1,2,3).hashCode
val res12: Int = 1852361929
```

**Comment by magnus-madsen** [comment]
Let us not add any instances for `PartialEq`, `PartialOrd`, `Eq`, `Ord` or `Hash`  for any mutable type (e.g. `Array`, `Channel`, or `Ref`).
