### ISSUE TITLE
Change type parameter order to "subject-last"

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1535]
We use "subject-last" parameter order in functions since this makes currying more natural:

```flix
def map(f: a -> b, l: List[a]): List[b] = ???
// `l` is the subject
```

At the type level, we don't follow the same convention:
* `Result[t, e]`: `t` is the subject and comes first
* `Validation[t, e]`: `t` is the subject and comes first

With the parameters reversed, we could have a more useful partial application:
* `Result[e]` has the same kind as `Option`. We can therefore declare a functor instance for it.

**Comment by magnus-madsen** [comment]
I have not thought about this before. It is interesting, but something about swapping the order of arguments to `Result` and `Validation` makes me uncomfortable. A more general question arises: What if you want a function on a non-first argument? What if you have a `Map[k, v]`? or any other type `T[a, b, c]` and you want a functor on `b`?

**Comment by mlutze** [comment]
The following seems like it should work:

```flix
type alias NewT[a, c, b] = T[a, b, c]

instance Functor[NewT[a, c]] {
    ...
}
```

However, I haven't gotten it to work yet; the compiler crashes with an invalid type error: lambda.

**Comment by magnus-madsen** [comment]
We should revisit the `Type.Lambda`. I think they can be used to overcome these issues. Do you have TAPL? The Type.Lambda is vaguely inspired by System F (although in Flix they not part of the type system-- they are eliminated before the Typer)-- but maybe that has to change?

**Comment by mlutze** [comment]
> Do you have TAPL?

Yes, I'll do some reading.

**Comment by mlutze** [comment]
I managed to resolve the lambda problem by adding some Type.simplify calls (I think).

**Comment by magnus-madsen** [comment]
Fixed in master.

**Comment by mlutze** [comment]
> Fixed in master.

Even for region params?

**Comment by magnus-madsen** [comment]
> > Fixed in master.
> 
> Even for region params?

No, but let us raise the issue when we see it? And deal with it separately.
