### ISSUE TITLE
Allow fully-qualified tags

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1540]
The following fails to parse:
```flix
def main(): Bool = 
  A/B.Color.Red != A/B.Color.Blu

namespace A/B {
    pub enum Color {
        case Red, Blu
    }
}
```

We get this error:
```
-- Parse Error -------------------------------------------------- ???

>> Parse Error:

Invalid input ".R", expected LegalLetter, optWS, Tuple, ArgumentList or '[' (line 2, column 12):
  A/B.Color.Red != A/B.Color.Blu
           ^
```

**Comment by magnus-madsen** [comment]
Interesting. Some kind of parsing bug?

**Comment by mlutze** [comment]
Yes, we allow fully-qualified names, but not `QName "." UpperName`

**Comment by mlutze** [comment]
(Related: https://github.com/flix/flix/issues/1489#issuecomment-736809579)

**Comment by JonathanStarup** [comment]
@magnus-madsen was this fixed?

**Comment by magnus-madsen** [comment]
I am closing a lot of namespace related tickets because we will soon replace the entire implementation.

Once that happens we will have to test everything from scratch.

**Comment by magnus-madsen** [comment]
But maybe I should leave the remaining tickets open...

**Comment by JonathanStarup** [comment]
I think this is a parsing thing though

**Comment by magnus-madsen** [comment]
OK, I leave it open.

(Parsing will also change).

**Comment by JonathanStarup** [comment]
Oh yeah, good point. It's gonna be nice with these whole rework

**Comment by magnus-madsen** [comment]
We have recently reworked the namespace (now module) mechanism.
Hence this ticket is most likely no longer relevant.
Feel free to common and/or re-open if it is.
