### ISSUE TITLE
Library: Add Chain Data Structure?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1543]
See:

https://typelevel.org/cats/datatypes/chain.html
https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/data/Chain.scala
https://github.com/non/chain

**Comment by stephentetley** [comment]
Hi Magnus

Is this the same as a "Join List"?

I have one here. I can fill out the implementation if you like...

https://github.com/stephentetley/flix-sandbox/blob/master/src/flix/Data/Transient/JoinList.flix

I've tended to reach for a DList when I've needed a "list builder":

https://github.com/stephentetley/flix-sandbox/blob/master/src/flix/Data/Transient/DList.flix

**Comment by magnus-madsen** [comment]
> Is this the same as a "Join List"?

Yes! Looks like it. A data structure that supports fast prepend and append.

**Comment by stephentetley** [comment]
There's also a Rose Tree (i.e. Haskell's Data.Tree) in that repository which should be generally useful:

https://github.com/stephentetley/flix-sandbox/blob/master/src/flix/Data/RoseTree.flix

What name would you want for the Chain / Join List?

**Comment by magnus-madsen** [comment]
I think I would prefer the Haskell names since they are more established.

**Comment by magnus-madsen** [comment]
I believe that `JoinList` is useful, e.g. for when you are building something with Monoids. But for RoseTrees I read a StackOverflow post that basically explained that it is very rarely used because it is very easy to define your own trees so there is little use of a "generic" tree structure:

https://cs.stackexchange.com/questions/56081/what-are-the-applications-of-rose-trees

**Comment by stephentetley** [comment]
Yes - Rose Tree's aren't universally useful because algebraic datatypes make defining trees so simple, so maybe I shouldn't have said "generally useful". 

What I find a Rose Tree useful for is generating HTML and ASCII tree's - I have functions to print both are in libraries so for a type or set of types that I want printing as a tree (rather than just pretty printing with nesting) I find it much simpler to transform them into a Rose Tree and print that rather than write a custom tree printer each time.

**Comment by magnus-madsen** [comment]
> What I find a Rose Tree useful for is generating HTML and ASCII tree's - I have functions to print both are in libraries so for a type or set of types that I want printing as a tree (rather than just pretty printing with nesting) I find it much simpler to transform them into a Rose Tree and print that rather than write a custom tree printer each time.

Do you have a link to that? I would like to see how it works out.

**Comment by stephentetley** [comment]
Thanks Magnus, I'll make some examples over the weekend.

For the `Chain` do we have a design pattern / idiom to hide the constructors of an enum to library users?

Ideally we want to prevent the `Empty` constructor appearing inside a chain e.g. `Chain(One('x'), Empty)` is bad and we should use a smart constructor to rewrite it as just `One(x)`.

**Comment by magnus-madsen** [comment]
> Ideally we want to prevent the `Empty` constructor appearing inside a chain e.g. `Chain(One('x'), Empty)` is bad and we should use a smart constructor to rewrite it as just `One(x)`.

I don't think we have a mechanism that can enforce that.

**Comment by stephentetley** [comment]
Hi Magnus, for the RoseTree I've added an example to `flix-htmldoc` that renders a directory listing:

https://github.com/stephentetley/flix-htmldoc/blob/master/test/listing-test.flix

To turn the FileObject enum into a RoseTree that can be printed is less than twenty lines and in CPS too so it should not blow the stack (lines 43 - 57).

The ASCII rendering which just uses the RoseTree module and not the HTML library looks like this:

~~~

flix-basicdb
|
+- src
|  |
|  +- Internal
|  |  |
|  |  +- PreparedStatement.flix
|  |  |
|  |  +- Prim.flix
|  |  |
|  |  `- ResultSet.flix
|  |
|  +- DbMonad.flix
|  |
|  +- PreparedStatementSetter.flix
|  |
|  `- RowEvaluator.flix
|
+- test
|  |
|  `- Test01.flix
|
+- LICENSE
|
`- README.md

~~~

I've temporarily added the HTML output and the CSS file it needs to the repository as I don't know how to host them directly. I think you would have to download them and view locally: 

https://github.com/stephentetley/flix-htmldoc/blob/master/output/dirtree.html
https://github.com/stephentetley/flix-htmldoc/blob/master/output/tree.css

The tree printer in the `HtmlDoc` library isn't very polished but it doesn't need much code in `listing-test.flix` to render the tree (lines 60 -78)

https://github.com/stephentetley/flix-htmldoc/blob/master/src/HtmlDoc/Tree.flix

**Comment by stephentetley** [comment]
I've worked Chain up to a useful lib (about 76 functions) and written tests for the exposed ones.

I'll make a PR this week.

**Comment by stephentetley** [comment]
Now a PR: 

Adding Chain module to stdlib and tests. #2590

**Comment by magnus-madsen** [comment]
Fixed in master.
