### ISSUE TITLE
Add Monoid Type Class

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1545]
```
trait Monoid[m] {
  def empty(): m
  def combine(x: m[a], y: m[a]): m[a]
}
```

Add instances for:
- Option
- List

NB: This requires higher-kinded types.

Later: Introduce Semigroup

**Comment by stephentetley** [comment]
Flix's typeclasses are now capable of supporting a Monoid typeclass.

I've started an implementation here: 

https://github.com/stephentetley/flix-sandbox/blob/master/temp/Monoid.flix

https://github.com/stephentetley/flix-sandbox/blob/master/temp/TestMonoid.flix

I'll look for other "uncontroversial" instances at the weekend and look towards making a PR. Haskell uses newtype wrappers to get round controversial instances e.g. numbers that have two sensible instances Plus (Sum) and Mult (Product). I don't propose adding those at the moment, but the basic Monoid class and instances would be nice as we need Monoid before we can have e.g. Foldable.

When Flix has Superclasses, `combine` can be refactored out of Monoid into Semigroup.

**Comment by magnus-madsen** [comment]
Very nice!

**Comment by magnus-madsen** [comment]
Fixed in master.
