### ISSUE TITLE
Kinds and kind inference

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1553]
We currently have the following kinds:
* `Type`, aka `Star`, representing the typical inhabitable types: `Int`, `Bool`, `Char`, `Enum`, `String`...
* `Bool`, representing type-level booleans, used for purity and nullability
* `Record`, subkind of `Type`, representing record types
* `Schema`, subkind of `Type`, representing schema types
* `Arrow`, representing type constructors
* `Var`, representing kind variables.

We perform limited kind inference where this is easily done from syntax:
* Function definitions
* Enum cases

Kinds are inferred syntactically:
* Effect variables: In `a -> b & c`, `c` is necessarily of `Bool` kind.
* Type-level boolean expressions: In `a -> b & c or d`, `c` and `d` are necessarily of `Bool` kind.
* Record construction: In `{| r}` and `{a: Int | r}`, `r` is necessarily of `Record` kind.
* Schema construction: In `#{| s}` and `#{A | s}`, `s` is necessarily of `Schema` kind.
* Everywhere else, we infer `Type` kind
  * (Our type-level Apply inference is currently incorrect)

In places where the kinds cannot be inferred from these methods, we create a fresh kind variable. This includes phantom type parameters, where the type cannot be inferred, and other unused type parameters, which we expect will result in a redundancy error.

Kinds are **not** currently inferred for type class parameters. These are assumed to be of `Type` kind unless otherwise annotated.

Kind variables are not treated in the same way as Type variables. No substitution or unification is ever done on kinds, only a subkind check when unifying two type variables. Kind variables are treated as both subkinds and superkinds to every other kind. In other words, they can be thought of as a wildcards, matching with anything. This behavior is incorrect, but since kind variables, except in the context of phantom types, are only assigned where a redundancy error is anticipated, it hasn't caused many issues. This may change in the future.

Questions:
* Do we want to perform kind inference at all? Requiring explicit kinds would simplify things, but would also make declarations more verbose.
* In the other direction, do we want to do "proper" kind inference? Performing substitution and unification on kind variables?
* A side-note. Is it strange to have subkinding in a language without subtyping? In some early considerations, we had the `Record` type constructor of kind `RecordRow -> Type`. This avoids a subtyping relationship while keeping things well-kinded. This may be something to revisit.
* Other considerations?

**Comment by magnus-madsen** [comment]
Additional Questions:
- Can you even have sub-kinds? I suspect that might break principal types. I know you can have polymorphic kinds (but I don't know how they are implemented).
- We use Bool kinds for two things atm. In the future there might be more. How can keep such Bools separate?
- How do other languages deal with kinds? It seems that they are often hidden away from the programmer. This suggest that we should do the same, but then type signatures have to become even more "magical".

**Comment by mlutze** [comment]
> We use Bool kinds for two things atm. In the future there might be more. How can keep such Bools separate?

I think while we want to keep them separate, it would also be nice for them to be able to interact. E.g. perhaps the purity of a function depends on the nullability of some term. Future examples might be less contrived. We could consider limited type-level functions/conversions (may need to be careful with termination). That would likely have further interesting applications, but would introduce complexity.

**Comment by mlutze** [comment]
(Crazy over-engineered idea: kind classes. Define a kind class `Boolable` for types convertable to type-level booleans)

**Comment by magnus-madsen** [comment]
In all seriousness - there is a thing called DataKinds in Haskell.

**Comment by mlutze** [comment]
Another note: the predicates in schemas have kind `Type`, despite their inability (as far as I know) to interact with other normal types except through "magic" `fold` operators, etc. A change there may also be worth exploring.

(See also https://github.com/flix/flix/issues/1169)

**Comment by mlutze** [comment]
Ur does some interesting things with kinds and records: http://impredicative.com/ur/tutorial/tlc.html

**Comment by magnus-madsen** [comment]
I think we can close this?
