### ISSUE TITLE
Type Classes: Default/Automatic Instances

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1557]

**Comment by magnus-madsen** [comment]
I think this is very important, but I think it can also totally wait until all most all other issues w.r.t. type classes have been worked out. It is really "Type Classes 2.0" and there is a huge design space w.r.t. how to support default instances (especially if you want to go beyond Eq, Hash, etc.)

**Comment by mlutze** [comment]
Superseded by https://github.com/flix/flix/issues/2154
