### ISSUE TITLE
Type Classes: Disallow complex instances

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1558]
Based on Haskell's rules:
* the parameters of any predicates in an instance context should be type variables, each of which should appear in the head of the instance
* and the type appearing in the head of an instance should consist of a type constructor applied to a sequence of distinct type variable arguments

How will this interact with records?

**Comment by mlutze** [comment]
I think this will also make non-variable constraints in signatures moot.

**Comment by magnus-madsen** [comment]
I was wondering: Why do these restrictions exist?

Is this not what FlexibleInstances and FlexibleContexts allow? (- the two most popular Haskell extensions).

**Comment by mlutze** [comment]
A few reasons:
* Less ambiguity
  * If we have `instance ToString[Option[String]]` and `instance ToString[Option[Int]]`, what happens when we do `toString(None)`? (We have to use a type annotation.)
* Keeping things simple
  * If we have `instance ToString[a]` (i.e. everything is an instance of `ToString`), there's no point in having a type class at all.
  * If we have `instance ToString[List[a]] with [Option[a] : ToString]`, this is the same as `instance ToString[List[a]] with [a : ToString]`, since if you need `Option[_] : ToString`, you can create `instance ToString[Option[a]]`

**Comment by magnus-madsen** [comment]
Thanks for the excellent writeup. That helps alot.

What about:

```
instance ToString[(Color, Color)]
```

what is the problem there? Ambiguity with the instance for ()? What if it was two new types:

```
instance ToString[ANewType[AnotherType]]
```

**Comment by mlutze** [comment]
> `instance ToString[(Color, Color)]`

In this case, I don't think there is ambiguity. However, it prevents having any sort of general tuple instance: `instance ToString[(a, b)]` since these instances overlap, meaning we'd have to do an individual instance for every possible tuple.

We can add some logic to disambiguate among overlapping instances by taking the "most specific" instance. This seems to get complicated ([see section 4.4](https://www.microsoft.com/en-us/research/wp-content/uploads/1997/01/multi.pdf))

> `instance ToString[ANewType[AnotherType]]`

Same issue, we can't have any general `ToString[ANewType[a]]` and have to specify it individually for every type parameter `a`.

**Comment by mlutze** [comment]
At the end of the paper mentioned above, the authors made the following conclusions regarding Haskell's type class system:

 Permit multi-parameter type classes.
 Permit arbitrary constraints in types and type signa-
tures (Choice 1b).
 Use the (inst) context-reduction rule only when forced
by a type signature, or when the constraint is tauto-
logical (Choice 2d). Choice 2e is also viable.
 Prohibit overlapping instance declarations
(Choice 3a).
 Permit arbitrary instance types in the head of an in-
stance declaration, except that at least one must not
be a type variable (Choice 4c).
 Permit repeated type variables in the head of an in-
stance declaration (Choice 5a).
 Restrict the context of an instance declaration to men-
tion type variables only (Choice 6b).
 No limitations on superclass contexts (Choice 7b).
 Prohibit improvement (Choice 8a).
 Permit the class variable(s) to be constrained in class-
member type signatures (Choice 9b).

I'll follow up with discussion on where we currently stands relative to these suggestions.

**Comment by mlutze** [comment]
| Decision                                 | What Haskell does (without extensions)            | What authors suggest                                                                                               | What we do                              |
|------------------------------------------|---------------------------------------------------|--------------------------------------------------------------------------------------------------------------------|-----------------------------------------|
| Multi-parameter type classes             | Single-parameter only                             | Permit multi-parameter                                                                                             | Single-parameter only                   |
| Constraints on types                     | Constraints on type variables only                | No restrictions                                                                                                    | Constraints on type variables only      |
| Context reduction                        | Reduce every context before generalization        | Use the _inst_ context reduction rule only when forced by a type signature, or when the constraint is tautological | (Needs investigation)                   |
| Overlapping instances                    | Prohibit overlapping instances                    | Prohibit overlapping instances                                                                                     | Prohibit overlapping instances          |
| Instance types                           | Simple types only: X[var_1, ..., var_n]           | Only require that one instance type must not be a variable                                                         | Simple types only: X[var_1, ..., var_n] |
| Repeated type variables in instance type | Prohibit repeated type variables                  | Permit repeated type variables                                                                                     | Prohibit repeated type variables        |
| Constraints on instance types            | Type variable constraints only                    | Type variable constraints only                                                                                     | Type variable constraints only          |
| Superclasses                             | Simple constraints only                           | No restrictions                                                                                                    | Simple constraints only                 |
| Improvement (not discussed in-depth)     | No improvement                                    | No improvement                                                                                                     | No improvement                          |
| Constraints on signatures                | No additional constraints on class type variables | No restrictions                                                                                                    | (Needs investigation)                   |

We largely follow Haskell's restrictions. I'm still a little unclear on how some of the suggested features work without introducing ambiguity or other negative effects. More to come after some rereading.

**Comment by magnus-madsen** [comment]
Context reduction is only relevant when you have super classes, AFAIK.

**Comment by mlutze** [comment]
I think one big reason to support multiparam classes is the effect system.
`ToString.toString` is currently pure, and we have to cast mutable types in order to implement it.

If we instead have 

```
class ToString[a, e : Bool] {
  def toString(x: a): String & e
}
```

Then we don't need casting, and we have a signature that better reflects the purity of the function (I think?)

**Comment by magnus-madsen** [comment]
> I think one big reason to support multiparam classes is the effect system.
> `ToString.toString` is currently pure, and we have to cast mutable types in order to implement it.

I see the point. 

However, for the base type classes (Eq, Ord, Add) it makes sense to demand purity.

For say `Functor` we could think about it since e.g. `List.map` is effect polymorphic. But does that require multi param TCs? Can we define `Functor[f]` and have `map` take an effect parameter or is that not allowed.

Finally, for e.g. `Functor` there are the functor laws that we should respect. I would suspect that these ultimately would demand purity (in conflict with e.g. List.maps effect polymorphism). For example there is the functor law:

```
map(id)(o) = o
```

but if `id` is `x -> print(x); x` then clearly this does not hold. We could of course say that such laws must only hold for pure functions.

Without knowing the literature in complete detail, I think you basically touched on the wall of our current knowledge. That is the question: "How should type classes be designed in the presence of effect systems" and I don't think that has been explored much so far. It is an interesting topic and something we could (potentially) look more into.

**Comment by magnus-madsen** [comment]
I agree now. We should disallow complex instances.

An instance must be of the form `instance MyClass[TypeConstructor(type vars...)]`.

Will you add a syntactic check?

**Comment by mlutze** [comment]
This is implemented in the Instances phase. Closable?

**Comment by mlutze** [comment]
With no objection heard, I'm closing this.
