### ISSUE TITLE
Add Uninitialized Type Class

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1561]
- [ ] Add the `Uninitialized` type class.
- [ ] Add instance for `Unit` (unit).
- [ ] Add instance for `Bool` (false).
- [ ] Add instance for `Char` (\0?).
- [ ] Add instance for `Float32` (zero).
- [ ] Add instance for `Float64` (zero).
- [ ] Add instance for `Int8` (zero).
- [ ] Add instance for `Int16` (zero).
- [ ] Add instance for `Int32` (zero).
- [ ] Add instance for `Int64` (zero).
- [ ] Add instance for `BigInt` (`null`).
- [ ] Add instance for `String` (`null`).
- [ ] Add instances for tuples from N=2 to N=10 (`null`).
- [ ] Add instance for `Option`. (returns `null`).
- [ ] Add instance for `List`.  (returns `null`).
- [ ] Add instance for `Set`.  (returns `null`).
- [ ] Add instance for `Map`.  (returns `null`).
- [ ] Refactor `MutList` etc. to use the new type class.
- [ ] Remove `default` expression

No need for tests.

```
class Uninitialized[a] {
  def uninitialized(): a
}
```

**Comment by stephentetley** [comment]
Hi Magnus 

The Default typeclass is not well liked in the Haskell world. The dislike stems from it being a lawless class and so many defaults are arbitrary and using explicit values for primitives like integers etc is recommended as a better coding style.

Maybe interop with Java would make it more viable in the Flix world, but I'm not sure.

https://mail.haskell.org/pipermail/haskell-cafe/2018-May/thread.html#129052

https://github.com/google/proto-lens/issues/194

**Comment by magnus-madsen** [comment]
OK; Good to know! I can see that it is lawless.

IIRC, the place where we need it is for the allocation of arrays. We want to be able to allocate a large array and we have to give a default value to the entries.

**Comment by magnus-madsen** [comment]
E.g. https://github.com/flix/flix/blob/master/main/src/library/MutList.flix#L597

But maybe we need to give it some kind of special treatment and hide it from ordinary programmers.

**Comment by magnus-madsen** [comment]
(Sorry for spam).

A very simple fix: Rename `Default` to something scary sounding like `Uninitialized` to highlight its intended use. 

Other potential fixes:
- Some notion of `sealed` where we (the library authors) can enforce that it is only us that can define instances of a TC.
- Some general instance `instance Default[a]` ensuring that no other instance can be implemented by user. (But we would need overlapping TCs because we would want ourselves to implement both `Default[Bool]` and `Default[Int32]`.

Summoning @mlutze  maybe he has some thoughts?

**Comment by stephentetley** [comment]
For the MutList could you get round it by initializing the new array with the head of the source MutList?

**Comment by magnus-madsen** [comment]
> For the MutList could you get round it by initializing the new array with the head of the source MutList?

Maybe. But even if it can be done in all cases, I think it makes working with arrays a lot harder than necessary.

**Comment by mlutze** [comment]
> Some general instance instance `Default[a]` ensuring that no other instance can be implemented by user. (But we would need overlapping TCs because we would want ourselves to implement both `Default[Bool]` and `Default[Int32]`.

I don't think this works (without adding compiler magic) since allowing overlapping instances would also allow a user to implement their own instance overlapping with `Default[a]`.

> Some notion of `sealed` where we (the library authors) can enforce that it is only us that can define instances of a TC.

At first glance at least, this looks promising. I can see this being put to use outside this context as well.

> Rename `Default` to something scary sounding like `Uninitialized` to highlight its intended use.

I like this.

**Comment by magnus-madsen** [comment]
Proposal: 
- Rename `Default` to `Uninitialized`.
- Introduce a keyword `sealed` on type classes which means that the user cannot write any instances.
- Use compiler magic to implement instances for `Uninitialized` compatible with Java defaults (i.e. null for non-primitives).

**Comment by magnus-madsen** [comment]
Implementation plan:

- Esben introduces the `Uninitialized` type class (with def `uninitialized()`).
- Esben introduces instance for the type class (these will be removed later, so no need for tests (!!))
- Esben refactors `MutList` (and anywhere else `default()`) is used to instead use `uninitialized`.
- Magnus/Matt removes the `default` expression.
- Magnus/Matt adds `sealed` to type classes.
- Magnus/Matt adds "magic instances"-- not yet sure how we are going to do this?

**Comment by magnus-madsen** [comment]
See https://github.com/flix/flix/issues/1603 and https://github.com/flix/flix/issues/1604

**Comment by magnus-madsen** [comment]
Esben made a nice implementation in https://github.com/flix/flix/pull/1690. But notice how the `Uninitialized` signature can propagate very far. For example:

```
pub def query[k : Uninitialized, v : Uninitialized, e](p: k -> Comparison & e, m: Map[k, v]): List[(k, v)] & e
```

This is very surprising because -- while query uses arrays underneath -- this is now exposed directly to the programmer!

I am not sure what to do about this, but it is unsettling.

Magnus

**Comment by magnus-madsen** [comment]
We are not doing this. We will keep the `default` expression - for now - as an evil, but necessary escape hatch.
