### ISSUE TITLE
Type Classes: Add Copy Type Class

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1566]
- Add the `Copy` type class.
- Add instance for `Array`.
- Add instance for `Ref`.
- Add instance for `MutSet`.
- Add instance for `MutMap`.
- Add instance for `MutList`.

**Comment by mlutze** [comment]
Could we separate deep and shallow copies into different classes?

```
class DeepCopy[a]
class ShallowCopy[a]
```

Then I think we'll certainly need instances of deep copy for immutable types, since any reasonable instance would have constraints:

```
instance DeepCopy[List[a]] with [a : DeepCopy]
```

For immutable type instances of ShallowCopy, I am not sure.

**Comment by magnus-madsen** [comment]
> Could we separate deep and shallow copies into different classes?
> 
> ```
> class DeepCopy[a]
> class ShallowCopy[a]
> ```

I think this is an interesting research question.

Let me challenge you by asking: Can you come up with a generic function where you would want to use `DeepCopy` or `ShallowCopy`? 

Going further: How would you handle:
- `List[Ref[Int]]`
- `Array[Ref[Int]]`
- `Array[List[Int]]`

How can we implement list copy such that it only copies if it contains something mutable? How would you express this? Is it useful?

**Comment by magnus-madsen** [comment]
While `Copy` is not merged, I am still not sure if it has a useful design. Can we even write a polymorphic function that makes use of it?

**Comment by magnus-madsen** [comment]
https://doc.rust-lang.org/nomicon/send-and-sync.html

**Comment by magnus-madsen** [comment]
To make this class useful I think we have to perform deep copies:

- [ ] Implement instances for all data types, e.g. Option, List, Set, and so forth.
- [ ] Each implementation must recursively call copy on its elements.

For example, the instance for List will map over the list calling copy.

**Comment by magnus-madsen** [comment]
I thought more about it and I am now even more hesitant to add anything like this. 

I think I will close this and then we can revisit later when we have better control over mutable memory.
