### ISSUE TITLE
Tail Recursion

### ISSUE THREAD

**Issue by mhyee** [flix/flix#157]
We'll need this, especially if we plan to use iteration/recursion in the Flix standard library.

Some of my benchmarks will overflow the stack, even if I set the stack size to 32 MB.

**Comment by magnus-madsen** [comment]
Plan:

1. Implement a phase `TailCalls` which replaces `ApplyRef` with `ApplyTailCall` for calls in direct tail-recursive position.
2. Implement support for `ApplyTailCall` in interpreter, symbolic evaluator, and codegen. The first two can simply perform a normal call (if they wish), whereas the codegen must (a) emit a label for the entry point of the function, and (b) replace an `ApplyTailCall` with assignments to local variables and a jump to the entry point.

**Comment by magnus-madsen** [comment]
Recently merged.
