### ISSUE TITLE
Range data structure

### ISSUE THREAD

**Issue by esbenbjerre** [flix/flix#1579]
I would like to propose a `Range` data type, similar to the one below
https://github.com/typelevel/cats-collections/blob/master/core/src/main/scala/cats/collections/Range.scala
Scala also has a built in `Range` type with similar characteristics.

The idea would be to allow for something like
```
def Range.inclusive[a : Ord](from: a, to: a): Range[a]
def Range.exclusive[a : Ord](from: a, to: a): Range[a]

Range.exclusive(1, 4) = ??? /// 1, 2, 3
Range.inclusive('a', 'z') = ??? /// 'a', 'b', ..., 'z'
```

**Comment by mlutze** [comment]
I think we'll need a stronger constraint than `Ord` for this, since I assume the implementation would use some kind of `succ` function?

**Comment by esbenbjerre** [comment]
> I think we'll need a stronger constraint than `Ord` for this, since I assume the implementation would use some kind of `succ` function?

Yes I think you are right. I guess what we really need is some bijection between the range elements and integers.

**Comment by esbenbjerre** [comment]
Looks like Haskell deals with this using the `Enum` and `Bounded` type class.

**Comment by magnus-madsen** [comment]
@esbenbjerre Want to post a proposal for how these type classes would look and how the Range.inclusive would look?

**Comment by esbenbjerre** [comment]
> @esbenbjerre Want to post a proposal for how these type classes would look and how the Range.inclusive would look?

I think it should be something like this:
```
pub class Sequence[a] with [a : Ord] {
    pub def pred(x: a): a
    pub def succ(x: a): a
}

namespace Range {
def inclusive[a : Sequence](x: a, y: a): List[a] =
    if (x > y) Nil else x :: inclusive(succ(x), y)
}
```

There are some design choices to be made, though.
In Haskell `Enum` appears to have an implicit `Ord` constraint and is considered lawless. (see https://stackoverflow.com/questions/58761160/why-isnt-enum-typeclass-a-subclass-of-ord-typeclass).
I think it's important we don't repeat the mistakes made by Haskell, so I'll have to give this some careful thinking.

**Comment by magnus-madsen** [comment]
Thanks for the link. It seems that the `Enum` TC is indeed broken and we should avoid it.

As for your proposed sequence, do you need `pred`?

What is the relation between `Range.inclusive` and `List.unfold`? (or perhaps; what should their relation be?)

**Comment by magnus-madsen** [comment]
See also https://typelevel.org/cats-collections//discrete.html

**Comment by magnus-madsen** [comment]
See also https://github.com/typelevel/cats/blob/master/kernel/src/main/scala/cats/kernel/Enumerable.scala

**Comment by magnus-madsen** [comment]
Note to self: How does this interact with laziness and with iterators?

**Comment by magnus-madsen** [comment]
I think this can wait.
