### ISSUE TITLE
Performance Benchmark Suite

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#158]
The idea is to generate a sequence of Flix programs.

Specifically, we take each lattice (e.g. parity, sign, etc.) and generate a random graph of size 1, 2, 4, 8, 16, ..., 2^22 (or so). 

The Flix program will have a static set of rules like:

```
Value(x, plus(xv, yv)) :- Op(r, x, y, "plus"), Value(x, xv), Value(y, yv).
```

and the randomly generated facts are `Op` tuples and `Value` tuples.

We should then write some infrastructure to run all benchmarks at once.

The output should be a CSV file which could like:

```
lattice,size,memory,time
```

e.g.

```
parity, 512, 1000, 3534
```

we can then graph these CSV files over time.

**Comment by magnus-madsen** [comment]
I would like to propose that we work towards the following:

- Turning `RandomGraph`, `RandomLatticeGraph`, etc. into proper classes.
- Each class would be passed arguments to its constructor, such as parameters N, M, etc and the seed.
- Each class would provide a `perfTest` method which will (a) generate the input program (b) load it into Flix (c) return a performance object (possibly the flix object).
- Introduce a range of performance test cases. For example, we could have:

```
def test("PathReachability(n = 1000, p = 0.05)") {
  val perfTest = new PerfTestPathReachability(n = 1000, p = 0.05)
  perfTest.run()
}
```

We would then need some means to aggregate performance numbers. One possibility would be to simple create a file for each test case, store the last recorded time, and then compare the numbers too see that performance is within 5%. 

@luqmana, @mhyee , I would like to hear your suggestions along these lines.

**Comment by magnus-madsen** [comment]
Possibly we could consider writing our own small test framework for this.

This would allow us to have a feature where we can compare different compiler flags. (E.g. `-XInterpreter`, `--parallel`, etc.)

**Comment by olhotak** [comment]
For performance evaluation, we should use [Scalameter](https://scalameter.github.io/) to eliminate noise from JIT recompilation and GC.

**Comment by mhyee** [comment]
See also #124. Possible duplicate.

I had mentioned before (in #124) that I did something similar for an undergraduate project. But when @magnus-madsen and I looked at my old code, it didn't seem like we could reuse very much of it. It was very specific and also a lot fancier than what we need here. But we might be able to reuse the ideas.

I'm not entirely convinced that we should be running these performance tests with ScalaTest. It might be easier than writing our own test framework (or more likely, a bunch of test scripts). But these benchmarks are going to run for a very long time, and we also don't want people to run them along with our other tests. I definitely think we want to keep correctness tests separate from performance tests.

**Comment by magnus-madsen** [comment]
I looked at Scalameter too, we need someone to investigate whether it could be useful.

I think we should probably write our own little framework. In particular, I would like to see the following:

Given two flix options objects you can instantiate a comparison, e.g.

```
val opts1 = Options.Default.copy(parallel = Parallel.Enable)
val opts2 = Options.Default.copy(parallel = Parallel.Disable)
PerfTest.compare(opts1, opts2)
```

and this would generate output like:

```
N      | Prog1 | Prog2 | Prog3
64     | 1x    | 2x    | 2x
128    | 1x    | 3x    | 3x
256    | 1x    | 5x    | 5x
...
```

(See the AsciiTable we already have)

**Comment by magnus-madsen** [comment]
solve() returns a model which now has a time object from which you can retrieve the number of nanoseconds spent solving the program. I think this should be sufficient to implement something like the above.
