### ISSUE TITLE
ToString: Optimize Implementations

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1580]
Using MutList or StringBuilder...

I think we need to come up with one good pattern (e.g. for List) and then use that everywhere.

**Comment by magnus-madsen** [comment]
@jaschdoc This can be done once we have regions fully up and working and once we have a working region-based StringBuffer, i.e. not yet, but eventually.

**Comment by magnus-madsen** [comment]
@ninaandrup Can you go through all our `ToString` implementations in the standard library and ensure that they use `StringBuilder`?

**Comment by ninaandrup** [comment]
Implementations of `ToString` not using `StringBuilder`

- [ ] `Map`
- [ ] `Nel`
- [ ] `Set`

`toString` functions not using `StringBuilder`

- [ ] `Array`

**Comment by ninaandrup** [comment]
Should I refactor them to use `StringBuilder`?

**Comment by magnus-madsen** [comment]
> Should I refactor them to use `StringBuilder`?

Yep, thanks!
