### ISSUE TITLE
Add `Mul` Type Class

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1581]
- [ ] Add the `Mul` type class.
- [ ] Add instances for `Float32`.
- [ ] Add instances for `Float64`.
- [ ] Add instances for `Int8`.
- [ ] Add instances for `Int16`.
- [ ] Add instances for `Int32`.
- [ ] Add instances for `Int64`.
- [ ] Add instances for `BigInt`.
- [ ] Rewrite `*` to be syntactic sugar for `Mul.mul`. 

Question: How should these instances be added? Compiler magic?

```
class Mul[a] {
  def mul(x: a, y: a): a
}
```

NB: I have arbitrarily chosen `Mul` as the first operator to try to typeclass-ify.

**Comment by magnus-madsen** [comment]
I have had this idea that we should add "special expressions" for compiler intrinsics. 

For example, we could extend the grammar with:

```
__INT8_MUL(e, e)
...
__INT32_MUL(e, e)
...
__INT64_MUL(e, e)
``

expressions.

Then, such expressions can be used to implement the instance for `Mul[Int32]`.

**Comment by esbenbjerre** [comment]
Is there a special reason for handling multiplication on its own?
My first guess for handling this would be having addition, subtraction, multiplication and division inside a `Num` type class. Is there a situation where we would like operation one but not the other(s)?

**Comment by magnus-madsen** [comment]
> Is there a special reason for handling multiplication on its own?
> My first guess for handling this would be having addition, subtraction, multiplication and division inside a `Num` type class. Is there a situation where we would like operation one but not the other(s)?

Good question! This is the way Rust does it. I am not sure why they do it though.

Maybe if you want string append `+`, but strings are not Num.

I think it is a more fine grained approach.

**Comment by esbenbjerre** [comment]
> Maybe if you want string append +, but strings are not Num.

But wouldn't that be covered by having a `Monoid` instance for strings?

> I think it is a more fine grained approach.

That sounds reasonable.

**Comment by magnus-madsen** [comment]
> 
> 
> > Maybe if you want string append +, but strings are not Num.
> 
> But wouldn't that be covered by having a `Monoid` instance for strings?
> 

Not if you want to use the literal symbol `+` -- that will be sugar for `Add.add` and hence will require such an instance.

We can, however, introduce a `Num` class that derives from `Add`, `Sub`, etc.

**Comment by esbenbjerre** [comment]
Ahh, I see :)
