### ISSUE TITLE
Type Classes: Add Traversable Type Class

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1582]
My favorite type class :)

Text TBD

**Comment by stephentetley** [comment]
I've got a Traversable class with the same methods as Haskell working, with instances for Option, List, Nel, Chain, RedBlackTree and Map.

I'm moving it from my working "sandbox" into a fork off Flix/master so I can make a PR for it.

**Comment by stephentetley** [comment]
It took a bit longer than expected but I've now got the code on a proper branch off flix/flix.

@magnus-madsen @jaschdoc - what is the status of Eq for RedBlackTree?

I wrote an instance on my branch to help with tests - this instance is equal if both the shape and contents are exactly equal. Is it possible trees could be equal in contents and be "effectively" equal in shape except for a rebalance? My Eq would miss this.

**Comment by magnus-madsen** [comment]
I am not sure that RedBlackTree should have an Eq instance-- exactly because it is not clear what the "right" definition of Eq is. Where does it show up in the tests?

**Comment by stephentetley** [comment]
e.g: 

https://github.com/stephentetley/flix/blob/flix-traversable/main/test/ca/uwaterloo/flix/library/TestTraversable.flix#L516


In other tests, I've seen jaschdoc wrap rbtrees with Map() at this point to use Map's Eq instance.

**Comment by stephentetley** [comment]
For a shape agnostic version, a quick to implement alternative to using Map's Eq instance is to turn the RBTree into a Chain (both are internally binary trees) and use Chain's Eq instance - this might be marginally faster.

**Comment by magnus-madsen** [comment]
I am just worried that by having dependencies on RBTree we will not be able to substitute it easily in the future, should the need arise. Making it dependent on Chain is slightly preferable because Chain is actually a data structure that is in the library and will stay there whereas RBTree (vs other trees) is more of an implementation detail.

**Comment by stephentetley** [comment]
It would be equally as easy to make a dependency on List and use List's Eq.

Personally I'd want to rewrite RBTree's `foldRight` to be in CPS before I did this (and `foldLeft` as well for consistency).

**Comment by stephentetley** [comment]
Here's the check file:

~~~


pub def equals(t1: RedBlackTree.RedBlackTree[k, v], t2: RedBlackTree.RedBlackTree[k, v]): Bool with Eq[k], Eq[v] = 
    toList(t1) == toList(t2)

pub def toRedBlackTree(xs: List[(k, v)]): RedBlackTree.RedBlackTree[k, v] with Order[k] =
    List.foldLeft((acc, kv) -> {let (k,v) = kv; RedBlackTree.insert(k, v, acc)}, RedBlackTree.empty(), xs)


pub def toList(t: RedBlackTree.RedBlackTree[k, v]): List[(k, v)] = 
    RedBlackTree.foldRight((k, v, xs) -> (k, v) :: xs, Nil, t)

def makeList(size: Int32): List[(Int32, Int32)] = 
    List.unfold(s -> if (s < size) Some(((s, s), s+1)) else None, 0)

def main(_args: Array[String]): Int32 & Impure = 
    println("Running...");
    test01();
    0

def test01(): Unit & Impure =  
    let xs = makeList(2000000);
    println("Length xs: ${List.length(xs)}");
    let ys = makeList(2000001);
    println("Length ys: ${List.length(ys)}");
    let t1 = toRedBlackTree(xs);
    let t2 = toRedBlackTree(ys);
    println("equals1: ${t1 `equals` t2}");
    println("equals2: ${t1 `equals` t1}");
    ()

~~~

**Comment by magnus-madsen** [comment]
Using list is equally fine. What is the takeaway from the code you posted? That you just need equals and toRedBlackTree?

**Comment by stephentetley** [comment]
For the RedBlackTree module I just need toList and the Eq instance: 

~~~

instance Eq[RedBlackTree[k, v]] with Eq[k], Eq[v] {
    pub def eq(t1: RedBlackTree[k, v], t2: RedBlackTree[k, v]): Bool with Eq[v] =
        toList(t1) == toList(t2)
}

///
/// Returns the tree `t` as a list. Elements are ordered from smallest (left) to largest (right).
///
pub def toList(t: RedBlackTree[k, v]): List[(k, v)] =
    RedBlackTree.foldRight((k, v, xs) -> (k, v) :: xs, Nil, t)
    
~~~

`toRedBlackTree` is in my test module for Traversable as a helper - I don't think there's a string reason to have it in the stdlib.

Do you want me to make a separate PR to add Eq to RedBlackTree, or shall I include it when I make the Traversable PR?

**Comment by magnus-madsen** [comment]
> Do you want me to make a separate PR to add Eq to RedBlackTree, or shall I include it when I make the Traversable PR?

Either is fine :-)

I still don't understand why its needed though (maybe I am just slow :P). 

Is it because you want to implement Traversable for RedBlackTree and you cannot test it without Eq? If so that makes sense, but I still wonder why RedBlackTree should have Traversable? Does it ease the implementation for Set/Map?

**Comment by stephentetley** [comment]
Yes - having a Traversable instance for RedBlackTree makes Map's Traversable instance much easier.

Without an Eq instance for RedBlackTree - test would be a lot harder to write.

**Comment by magnus-madsen** [comment]
> Yes - having a Traversable instance for RedBlackTree makes Map's Traversable instance much easier.
> 
> Without an Eq instance for RedBlackTree - test would be a lot harder to write.

OK. That makes sense then!

**Comment by stephentetley** [comment]
I've finally made a PR - #2893

**Comment by magnus-madsen** [comment]
Fixed in master!
