### ISSUE TITLE
Add Foldable Type Class

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1583]
```
class Foldable[f] {
  def foldLeft(fn: b -> a -> b & e, s: b, xs: f[a]): b & e
  def foldRight(fn: a -> b -> b & e, s: b, xs: f[a]): b & e
}
```

```
namespace Foldable {
  def combineAll[f: Foldable, a: Monoid](fa: f[a]): a
  def count[f: Foldable](fn: a -> Bool, fa: f[a]): Int32
  def exists[f: Foldable](fn: a -> Bool, fa: f[a]): Bool
  def forall[f: Foldable](fn: a -> Bool, fa: f[a]): Bool
  def findLeft[f: Foldable](fn: a -> Bool, fa: f[a]): Option[a]
  def findRight[f: Foldable](fn: a -> Bool, fa: f[a]): Option[a]
  def foldMap[f: Foldable, m: Monoid](fn: a -> b, fa: f[a]): b
  def isEmpty[f: Foldable](fa: f[a]): Bool
  def memberOf[f: Foldable, a: Eq](x: a, fa: f[a]): Bool
  def maximum[f: Foldable, a: Order](fa: f[a]): Option[a]
  def minimumBy[f: Foldable](cmp: (a, a) -> Comparison, fa: f[a]): Option[a]
  def minimum[f: Foldable, a: Order](fa: f[a]): Option[a]
  def maximumBy[f: Foldable](cmp: (a, a) -> Comparison, fa: f[a]): Option[a]
  def reduceLeft[f: Foldable, a](fn: a -> a -> a & e, fa: f[a]): Option[a] & e
  def reduceRight[f: Foldable, a](fn: a -> a -> a & e, fa: f[a]): Option[a] & e
  def toList[f: Foldable, a](fa: f[a]): List[a]
}
```

(Feel free to double check that these signatures make sense).

Documentation for all of the above signatures can be copied and adapter from e.g. List.

Instances:
- [x] Array
- [x] Option
- [x] List
- [x] Nel

Others?

**Comment by magnus-madsen** [comment]
@esbenbjerre Feel free to start on this. I am still updating the description.

**Comment by esbenbjerre** [comment]
How do you want me to treat duplicate definitions in the companion namespace? Remove them from the other (e.g., `List`) namespace?

**Comment by magnus-madsen** [comment]
What do you mean? I think we shall have both `List.exists` and `Foldable.exists`. The latter will be expressed in terms of foldLeft. The former is implemented in however `List.exists` is implemented.

**Comment by esbenbjerre** [comment]
> What do you mean? I think we shall have both `List.exists` and `Foldable.exists`. The latter will be expressed in terms of foldLeft. The former is implemented in however `List.exists` is implemented.

Okay that answers my questions.

**Comment by esbenbjerre** [comment]
For `intercalate`, should the `Monoid` instance not be on the structure instead? That is:
```
def intercalate[f: Foldable : Monoid, a](fa: f[a], a: a): f[a]
```
instead of
```
def intercalate[f: Foldable, a: Monoid](fa: f[a], a: a): f[a]
```
Otherwise I'm not sure how we would create a new collection just using `fold`?

**Comment by magnus-madsen** [comment]
> 
> 
> For `intercalate`, should the `Monoid` instance not be on the structure instead? That is:
> 
> ```
> def intercalate[f: Foldable : Monoid, a](fa: f[a], a: a): f[a]
> ```
> 
> instead of
> 
> ```
> def intercalate[f: Foldable, a: Monoid](fa: f[a], a: a): f[a]
> ```
> 
> Otherwise I'm not sure how we would create a new collection just using `fold`?

I think you are right :)

**Comment by esbenbjerre** [comment]
> I think you are right :)

Okay. Just to be sure, what do you expect it to do? It seems sort of weird to have `intercalate` without `intersperse.`
https://typeclasses.com/featured/intercalate
For reference, the `List` version of these are
```
def intersperse(a: a, xs: List[a]): List[a]
def intercalate(xs: List[a], ys: List[List[a]]): List[a]
```

**Comment by magnus-madsen** [comment]
https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/Foldable.scala#L769

But now I think this is what we call intersperse?

**Comment by esbenbjerre** [comment]
> https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/Foldable.scala#L769
> 
> But now I think this is what we call intersperse?

Yes I think the definition in `List` is inspired by Haskell which uses `intersperse` for what `intercalate` does in your link.

I think we should call it `intercalate` (reasoning below) and make it behave like `intersperse`. Not sure what to do about the definitions in `List`.

Intersperse : "scatter among or between other things; place here and there."
intercalate: "to insert or position between or among existing elements or layers."

**Comment by magnus-madsen** [comment]
NB: No need for tests (yet).

**Comment by magnus-madsen** [comment]
Let us skip the intersperse/intercalate for now.

**Comment by esbenbjerre** [comment]
What do we want `findMap` to do?

**Comment by magnus-madsen** [comment]
Can `Map` implement Foldable? Is that expressible in our system?

**Comment by esbenbjerre** [comment]
> Can `Map` implement Foldable? Is that expressible in our system?

I don't think so, I tried earlier and was gonna open a ticket for it.
In Haskell, `Map` has a `Foldable` instance on the type of the keys `k`, but I don't know how the compiler figures out the rest.

**Comment by magnus-madsen** [comment]
We should have Foldable for `Map, MutMap, Set, MutSet, MutList`.

@mlutze Is it possible to implement an instance for a type constructor that has multiple arguments?

**Comment by mlutze** [comment]
> instance for a type constructor that has multiple arguments?

I believe you should be able to do something like:
```flix
instance Foldable[Map[z] :# Type -> Type] {
    ...
}

As long as the second type param is the one we want to fold over.

We can't fold over both since the kind wouldn't be correct. (`Type -> Type -> Type`)

**Comment by esbenbjerre** [comment]
> > instance for a type constructor that has multiple arguments?
> 
> 
> 
> I believe you should be able to do something like:
> 
> ```flix
> 
> instance Foldable[Map[z] :# Type -> Type] {
> 
>     ...
> 
> }
> 
> ```
> 
> 
> 
> As long as the second type param is the one we want to fold over.
> 
> 
> 
> We can't fold over both since the kind wouldn't be correct. (`Type -> Type -> Type`)

In this case I think we want to fold over the first type parameter.

**Comment by mlutze** [comment]
> In this case I think we want to fold over the first type parameter.

I don't know if there's currently a way to do this. See also https://github.com/flix/flix/issues/1535

**Comment by esbenbjerre** [comment]
I there any reason to exclude `MutList` from having an instance?

**Comment by magnus-madsen** [comment]
No, include it please :)
