### ISSUE TITLE
Refactor ToString Implementations

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1584]
Inside `ToString.flix` we have e.g.:

```
instance ToString[Char] {
    def toString(x: Char): String = Char.toString(x)
}
```

but this means that `ToString` depends on `Char`-- but I would rather have it the other way. 

Thus move the impl. from `Char` into `ToString`:

```
instance ToString[Char] {
    def toString(x: Char): String = 
        import java.lang.Character:toString(Char);
        c.toString() as & Pure
}
```

and then change `Char` to:

```
namespace Char {
  ...
  def toString(c: Char): String = ToString.toString(c)
}
```

This applies to all instances in `ToString`.

Does it make sense?

**Comment by esbenbjerre** [comment]
Gotcha!
