### ISSUE TITLE
Add Instrinsics for Primitives Types

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1586]
This is really a tracking issue for multiple other issues, see e.g. See #1585 and #1581

- [ ] Add intrinsics for primitive types.
- [ ] Add type classes for `Add`, `Sub`, ... and so forth.
- [ ] Remove deprecated Unary and Binary expressions.

**Comment by esbenbjerre** [comment]
Should there be an `Add` instance for strings?

**Comment by magnus-madsen** [comment]
> 
> 
> Should there be an `Add` instance for strings?

Yes, at least for now :)

**Comment by esbenbjerre** [comment]
Should `Rem` and `Exp` be type checked in the same fashion as e.g. `Add`? In other words, do I just add another or case to the line below from `Typer.scala`?
```
case SemanticOperator.Int32Op.Add | SemanticOperator.Int32Op.Sub | SemanticOperator.Int32Op.Mul | SemanticOperator.Int32Op.Div
```

**Comment by magnus-madsen** [comment]
I think so, I am not math expert. What do you they return if you look at them in Java / Math?

**Comment by esbenbjerre** [comment]
> I think so, I am not a math expert. What do they return if you look at them in Java / Math?

Well the integers with addition and multiplication do form a ring, so...
Joking aside, I think yes.
Interestingly, Java does not seem to have a built in function for 32-bit exponentiation, only for 64-bit.

**Comment by esbenbjerre** [comment]
Proposal: I think we should bundle bitwise `and`, `or`, `xor`, `shl` and `shr` in a single type class, `Bits` or something like that.
Justification: I can't see any situation where a type would support only a subset of these. Also Haskell does the same https://hackage.haskell.org/package/base-4.14.1.0/docs/Data-Bits.html

I don't know if this clashes with some specific idea.

**Comment by magnus-madsen** [comment]
> 
> 
> Proposal: I think we should bundle bitwise `and`, `or`, `xor`, `shl` and `shr` in a single type class, `Bits` or something like that.
> Justification: I can't see any situation where a type would support only a subset of these. Also Haskell does the same https://hackage.haskell.org/package/base-4.14.1.0/docs/Data-Bits.html
> 
> I don't know if this clashes with some specific idea.

Rust has a trait for each: https://doc.rust-lang.org/beta/std/ops/trait.Shl.html

However, when we have superclasses, we can implement your idea by having a` Bits` that extends all of these classes!

**Comment by esbenbjerre** [comment]
> However, when we have superclasses, we can implement your idea by having a` Bits` that extends all of these classes!

Roger 👍🏻

**Comment by magnus-madsen** [comment]
We are currently missing:
- equational operators (== and !=)
- relational operators (e.g. <)
- the Boolean operators should not (yet) become type classes. Instead they can directly be rewritten to the appropriate semantic operator.

**Comment by esbenbjerre** [comment]
Would you like me to group `<`, `<=`, `>` and `>=` in a single type class, or do you want a type class for each operator?

**Comment by magnus-madsen** [comment]
> Would you like me to group `<`, `<=`, `>` and `>=` in a single type class, or do you want a type class for each operator?

In this case, one type class.

**Comment by magnus-madsen** [comment]
Fixed.
