### ISSUE TITLE
missing flatMap in VS code

### ISSUE THREAD

**Issue by jacopol** [flix/flix#1587]
When forgetting
```    use Option.flatMap;```
before a let*, VS code will report the error, but without indication of file, function, or line where the let* occurs.

**Comment by magnus-madsen** [comment]
Maybe here: https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Weeder.scala#L553

**Comment by magnus-madsen** [comment]
Fixed in master.
