### ISSUE TITLE
Decide how to structure type classes and tests

### ISSUE THREAD

**Issue by esbenbjerre** [flix/flix#1590]
TBD

**Comment by esbenbjerre** [comment]
https://github.com/flix/flix/issues/1589#issuecomment-746129512_

**Comment by magnus-madsen** [comment]
Can you, in this ticket, compile a list of the test suites where we have had to add Options.TestWithLibrary

**Comment by esbenbjerre** [comment]
> Can you, in this ticket, compile a list of the test suites where we have had to add Options.TestWithLibrary

Sure. I've listed them below. This includes two locations where I added `Options.TestWithLibrary` in #1589.

main/test/ca/uwaterloo/flix/TestTutorials.scala:23
main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala:45
main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala:144
main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala:159
main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala:217
main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala:232
main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala:271
main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala:399
main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala:447
main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala:629
main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala:641
main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala:807
main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala:846
main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala:859
main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala:308
main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala:321
main/test/flix/LangSuite.scala:11
main/test/flix/LangSuite.scala:20
main/test/flix/LangSuite.scala:52
main/test/flix/LangSuite.scala:80
main/test/flix/LangSuite.scala:89
main/test/flix/LangSuite.scala:139
main/test/flix/LangSuite.scala:154
main/test/flix/LangSuite.scala:167
main/test/flix/LangSuite.scala:183
main/test/flix/LangSuite.scala:193
main/test/flix/LangSuite.scala:194
main/test/flix/LangSuite.scala:215
main/test/flix/LangSuite.scala:229
main/test/flix/LangSuite.scala:239
main/test/flix/LangSuite.scala:248
main/test/flix/LangSuite.scala:276
main/test/flix/LangSuite.scala:286
main/test/flix/LangSuite.scala:287
main/test/flix/LangSuite.scala:289
main/test/flix/LangSuite.scala:299
main/test/flix/LangSuite.scala:322
main/test/flix/LangSuite.scala:323

**Comment by magnus-madsen** [comment]
If you can keep the lines numbers straight for later that is fine. Personally I would have pasted the names :)

**Comment by magnus-madsen** [comment]
(Before we start on this ticket, lets get more of the TCs in place and then I want to make a small change).

**Comment by magnus-madsen** [comment]
Please see: https://github.com/flix/flix/pull/1594

Once this is merged, you should be able to refactor the tests "back".

**Comment by magnus-madsen** [comment]
Of course we will probably still want to do some restructuring.

**Comment by esbenbjerre** [comment]
> Once this is merged, you should be able to refactor the tests "back".

Changes made in #1595.

**Comment by magnus-madsen** [comment]
Fixed.
