### ISSUE TITLE
Add Keyword that allows overlapping instances for a specific type class

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1604]
I think it would be interesting to have a keyword that allows, for a specific type class, to have over lapping instances.

For example, if we had this we could do:

```
sealed class allowThisClassToHaveOverlappingInstances Uninitialized[a] {
  def uninitialized(): a
}

instance Unitialized[Bool] {
  def uninitialized(): Bool = false
}

instance Unitialized[Int32] {
  def uninitialized(): Int32 = 0
}

instance Unitialized[a] {
  def uninitialized(): a = null
}
```

What do you think?

**Comment by mlutze** [comment]
I'm still working on exploring the applications for overlapping classes in general. But for this particular case, we have a "default" instance for types not specifically covered. Perhaps instead of totally allowing overlapping instances, we could just allow a default one?

**Comment by magnus-madsen** [comment]
> 
> 
> I'm still working on exploring the applications for overlapping classes in general. But for this particular case, we have a "default" instance for types not specifically covered. Perhaps instead of totally allowing overlapping instances, we could just allow a default one?

OK; but what implementation strategy would this use? Look for a specific one and then take the default?

**Comment by mlutze** [comment]
Yes something like that. We actually wouldn't even need to track constraints since we'd know that every type has an instance.

**Comment by magnus-madsen** [comment]
After re-reading the SPJ paper about type classes, I am pretty concerned about the implications of having overlapping instances.

**Comment by magnus-madsen** [comment]
If we ever add overlapping instances we may consider doing something like this, but for now I am closing this.
