### ISSUE TITLE
Introduce Label kind

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1607]
Currently, interaction between the logical language and the functional language is limited to a set of special operators: `fold`, `solve`, `<+>`, `project`.

Operations on records are also somewhat limited: field access, extension, update, and delete.

If we want, for example, to have a function that doubles the value of a record field, we can't generalize it; we have to declare the function for any field we want to operate on.

I'm not as familiar with operations on schemas, so I can't articulate the possible applications there, but it seems promising.

```flix
doubleField[f :# Label, r](field: f, rec: { field: Int | r }): { field: Int | r } = { field=rec.field * 2 | rec }
```

I imagine each label type would be a singleton type, like Unit, created on-the-fly with some special syntax, e.g. `~age`.

```flix
let record = {name = "Luke", age = 20};
doubleField(~age, record)
```

**Comment by magnus-madsen** [comment]
I think it is an open problem to combine extensible records with first-class labels! :)
