### ISSUE TITLE
Lawful and Lawless Type Classes

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1609]
I would like to have the ability to express laws inside type classes. For example:

```scala
class Eq[a] {
  def eq(x: a, y: a): Bool

  law reflexivity(): Bool = forall(x: a). eq(x, x)
  law symmetry(): Bool = forall(x: a, y: a). eq(x, y) `implies` eq(y, x)
  law transitivity(): Bool = forall(x: a, y: a, z: a). (eq(x, y) and eq(y, z) `implies` eq(x, z)
}
```

Ultimately such laws can be used for quick checking (or automated theorem proving). But for now, the important idea is to be able to state them and have them type checked.

**Comment by mlutze** [comment]
I see that we have both a `Law` declaration in the parser and `@law` annotation. Which one do we want to use?

**Comment by magnus-madsen** [comment]
I think the keyword. The question is more what the syntax should look like or whether what I have is fine.

**Comment by mlutze** [comment]
I think we could stand to lose the parentheses, since the laws aren't callable (if I understand correctly). Plus, the "Bool" is redundant since every law should be boolean in nature, right?

So perhaps something like:
```
law reflexivity = forall(x: a). eq(x, x)
```

**Comment by magnus-madsen** [comment]
> So perhaps something like:
> 
> ```
> law reflexivity = forall(x: a). eq(x, x)
> ```

Would `reflexivity` still be a def with some annotations? If so, would it implicitly have argument `Unit` and return type `Bool`.

**Comment by mlutze** [comment]
What's the range of things that can go in a law? If it's only universal quantifiers, should we give those their own type? I guess they have a theoretically have a boolean value, but then we could have a law like `law oneTwoThree = 1 + 2 == 3`.

I see them as somewhat distinct from defs, and would type them without the idea of an argument and return type. Downside is that we can't as easily reuse def-related checks.

**Comment by magnus-madsen** [comment]
I would like to experiment with the following:

- Allow laws using the current syntax (`law reflexivity(): Bool = forall(x: a). eq(x, x)`) inside type classes. (These have no effect, but are type checked etc.)
- Introduce a modifier `lawless` for type classes, e.g. `lawless class Foo[a]`.
- Introduce a modifier `unlawful` for instances, e.g. `unlawful instance Bar[String]`.
- Introduce a check: If a type class has no laws its must be declared with the `lawless` modifier. For example, `ToString` is lawless whereas `PartialOrder` is not.

Implementing this and using it does not require too much work and brings something unique to the table. Now, whether this will be useful, we shall see.

**Comment by magnus-madsen** [comment]
Interesting reading that supports some of the above: https://degoes.net/articles/principled-typeclasses

**Comment by mlutze** [comment]
Maybe this could lead to a more principled rule for which functions to include in classes and which to put in the companion namespace, in that a function with a class law using it belongs in the class; functions without class laws go outside. This follows the rule/corollary split idea mentioned before.

**Comment by magnus-madsen** [comment]
Functions outside classes may also satisfy laws. For example:

```
def sort[a: Order](l: List[a])
```

should certainly satisfy a collection of laws. So I am not sure.

**Comment by mlutze** [comment]
Are laws always going to have the signature `Unit -> Bool`? I'd like to remove some of the noise such as `tparams`, `fparams` if possible.

**Comment by magnus-madsen** [comment]
> Are laws always going to have the signature `Unit -> Bool`? I'd like to remove some of the noise such as `tparams`, `fparams` if possible.

I think, to a first approximation, that is right.

**Comment by mlutze** [comment]
It looks like in *Lattice.flix` we have some laws that don't match the `Unit -> Bool` signature, e.g.

```flix
    law greatestLowerBound1[e](⊑: (e, e) -> Bool, ⊓: (e, e) -> e): Bool =
        ∀(x: e, y: e). ((x ⊓ y) ⊑ x) and ((x ⊓ y) ⊑ y)
```

Should we comment these out for now, or try to accommodate them?

**Comment by magnus-madsen** [comment]
If you are implementing the law functionality then I suggest - in the same PR - to comment/adapt such code.

**Comment by magnus-madsen** [comment]
That particular law can be moved into its appropriate type class and then `e` will be bound by the `TC`.

**Comment by magnus-madsen** [comment]
We now have basic support for this. I will open separate tickets to discuss the syntax of laws and for adding laws to existing type classes.
