### ISSUE TITLE
Type Class Constraints and Lints

### ISSUE THREAD

**Issue by esbenbjerre** [flix/flix#1614]
I'm introducing the `Eq` type class (#1605) and have run into some problems with lints. No matter where i add `Eq` constraints I can't remove this error.
```
-- Type Error -------------------------------------------------- Map.flix

>> No instance of class 'Eq' for type 'a'.

635 |     def useIsSubmapOf(): Bool =
              ^^^^^^^^^^^^^
              no instance found
```

The mentioned line in `Map.flix` is
```
@lint
def useIsSubmapOf(): Bool =
    forall [k, v] (m1: Map[k, v], m2: Map[k, v]).
        Map.forall((k, v) -> Map.get(k, m1) == Some(v), m2) === Map.isSubmapOf(m1, m2)
```

**Comment by mlutze** [comment]
Could it be because there are no constraints on `k` and `v`? (I'm not sure if the parser even allows constraints there)

**Comment by esbenbjerre** [comment]
> Could it be because there are no constraints on `k` and `v`? (I'm not sure if the parser even allows constraints there)

It could, but I still get the error even if I add the constraints.

**Comment by mlutze** [comment]
Looks like we lose type parameter info for universal expression in the Namer: https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Namer.scala#L727

**Comment by magnus-madsen** [comment]
@lints are probably broken. Feel free to comment them out.

**Comment by esbenbjerre** [comment]
> `@lints` are probably broken. Feel free to comment them out.

Roger. Should I close the issue?

**Comment by magnus-madsen** [comment]
No, leave it for now

**Comment by magnus-madsen** [comment]
Closing.
