### ISSUE TITLE
run test cases one by one

### ISSUE THREAD

**Issue by jacopol** [flix/flix#1623]
It would be great if one could run a single test in the VS code interface.
For instance, could a clickable "Run Test" label be generated for each @test, just like "Run Main"?

Use case: after a change of the program, one (or several?) of my testcases doesn't terminate.
If I could run the test cases one by one, I could find out which one. 
(outputting the test-results one by one on-the-fly would also help of course)

**Comment by magnus-madsen** [comment]
Yes, this would be useful. Requires changed both to the compiler and VSCode plugin.

**Comment by magnus-madsen** [comment]
We are re-engineering Flix to allow any top-level function to be run. This will indirectly allow test cases to be run one-by-one.
