### ISSUE TITLE
Allow Type Parameters to be Passed Explicitly?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1625]
For example, instead of:

```
MutList.head(MutList.new(): MutList[Unit])
```

we should be able to write:

```
MutList.head(MutList.new[Unit]())
```

**Comment by mlutze** [comment]
A complication: how to handle implicit type parameters, especially when there is more than one:

```flix
def doSomething(): (a, b, a, c) & e

doSomething[String, Int, Float, Pure]() // which param goes with which tvar?
```

Without explicit type params in the signature, it's less clear the ordering of type parameters. We can go in order of first use, but this feels too "implicit" to me.

A couple ideas:
* Only allow explicit tparam passing if there are explicit tparams in the signature
* Require explicit tparams for functions with variable return types

**Comment by magnus-madsen** [comment]
> A complication: how to handle implicit type parameters, especially when there is more than one:

This is a good point! An a slight strike against type parameter elision.

**Comment by magnus-madsen** [comment]
I am closing this for now.
