### ISSUE TITLE
Product types

### ISSUE THREAD

**Issue by albertllousas** [flix/flix#1626]
Hi,
Checking your docs I can see that create a sum type is easy and straight forward with `enum`, but what about product types?

**Comment by albertllousas** [comment]
It would be great to have some keywords also to construct the different types I would suggest to have this constructors:
- `enum` -> `sum type`
- `opaque type` -> `tiny type` or `single type`
- introduce `product type`

Or just `type` for everything.

WDYT?

**Comment by magnus-madsen** [comment]
You can create a product type as a tuple, e.g. `(Int, String)`. If you want to name it, you can use a type alias.

**Comment by albertllousas** [comment]
I see, but they are not types themselves, do you have plans to add them? If you want a powerful language that, in the end, it will be used to create `domains`, it will be super useful to have product types instead of tuples with aliases.

**Comment by magnus-madsen** [comment]
Could you expand a bit? I am not sure I follow :)

Tuples are (unnamed) types like records. You can use them everywhere a type is expected.

**Comment by albertllousas** [comment]
Sure,
Here you have : https://fsharpforfunandprofit.com/posts/records/
Or: https://medium.com/@shannonbarnes_85491/algebraic-data-types-in-scala-701f3227fe91#:~:text=The%20product%20type%20in%20Scala,this%20field%20AND%20that%20field%20%E2%80%A6.

They are super useful when modelling different domains.

So, they are mainly records with labeled fields and with a type assigned, not just a bunch of props.

Does it makes sense?

**Comment by magnus-madsen** [comment]
Do you mean something like (extensible) records?:

```
/// Returns the area of the rectangle `r`.
/// The record `r` must have `x` and `y` labels, and no other labels.
def area(r: {x: Int, y: Int}): Int = r.x * r.y

/// Computes the area of various rectangle records.
/// Note that the order of labels is immaterial.
def areas(): List[Int] =
    area({x = 1, y = 2}) ::
    area({y = 2, x = 3}) :: Nil

/// Returns the area of the polymorphic record `r`.
/// Note that the use of the type variable `a` permits the record `r`
/// to have labels other than `x` and `y`.
def polyArea[a](r: {x: Int, y: Int | a}): Int = r.x * r.y

/// Computes the area of various rectangle records.
/// Note that some records have additional fields.
def polyAreas(): List[Int] =
    polyArea({x = 1, y = 2}) ::
    polyArea({x = 2, y = 3, z = 4}) :: Nil

def main(): List[Int] = polyAreas()
```

**Comment by albertllousas** [comment]
Well, not exactly, maybe I have to explore better flix before asking this kind of questions.
I am already discussing the same here 
Duplicate of #1627 

Anyways, thanks for your answers and your work here, looks promising!
