### ISSUE TITLE
Change `enum`  and `opaque type` keywords

### ISSUE THREAD

**Issue by albertllousas** [flix/flix#1627]
Hi,

Wouldn't be clear to use the `enum` and `opaque type` keyword to just `type` for both? 

If not I would suggest to change:
- `enum` -> `sum type`
- `opaque type`-> `tiny type`

WDYT?

**Comment by stephentetley** [comment]
`enum` is the syntax for an algebraic type not just a sum type, so you can have both sum and products:

~~~

    pub enum Expression { 
        case LitE(Literal)
        case BinaryE(Expression, String, Expression)
        case IfThenElseE(Expression, Expression, Expression)
    }

~~~

`opaque` is equivalent to Haskell's `newtype` - it wraps a single type with a constructor so the compiler recognizes it as a distinct type. 

A type alias is exactly an alias, it is the same type but with a different name that helps the human programmer recognize its meaning and the compiler sees it as the same type.

**Comment by albertllousas** [comment]
I see, I just wanted to propose different names, enum seems to be a bit biased from java and scala. 

Would you mind to show how to create a product type with a sum type?

**Comment by albertllousas** [comment]
Since they all are types, another way would be just to use `type` for everything.

**Comment by stephentetley** [comment]
I think I might be misunderstanding what you want, but you can certainly create a single case enum that is a tuple:

    enum Person { 
        case Person(String, Int32)
    }
    
It is more likely you would want to use a record so you have named fields:

    type alias Person = { name: String, age: Int32 }
    
You may or may not want to wrap the record with `opaque` to get a distinct type (with access via its constructor):

    opaque type Person = { name: String, age: Int32 }
    
With an opaque type access is more controlled but less convenient....
    
    def getAge(p: Person): Int32 = 
        let Person(p1) = p;
        p1.age

**Comment by albertllousas** [comment]
I didn't know that you could do this `opaque type Person = { name: String, age: Int32 }`.

It totally works for me!! thanks, I am suggesting things without playing with the lang itself, just reading the docs.

What I was suggesting was to have a clear way to create product and sum types, just using one keyword like `type` or having more clear keywords to do it, I feel that each language have its own way to do it (haskell, scala ... ) , but since you are creating a new lang, why not to be just more clear?  

```
enum Person { 
    case Person(String, Int32)
}
```
I mean, if you have to do something like this, why not to have a clear way to do product types?

**Comment by magnus-madsen** [comment]
FYI: opaque types are not yet optimized away. However that should happen with the new backend coming in the spring!
