### ISSUE TITLE
Visibility modifiers for algebraic data types

### ISSUE THREAD

**Issue by albertllousas** [flix/flix#1628]
Hi,

Do you have plans to add visibility for types?

It would be great to have it, for example, to create smart constructors.

**Comment by albertllousas** [comment]
> for types

**Comment by magnus-madsen** [comment]
Could you explain a bit more what you mean?

We currently do have visibility of types, but maybe you mean of the individual constructors?

**Comment by albertllousas** [comment]
Hi, maybe I would need to play with the language before commenting, sorry I just took a look on the docs! You are right, I meant for constructors!

**Comment by magnus-madsen** [comment]
Maybe like:

```
pub enum Foo {
  case A
  private case B
```

I don't think we want the opposite:

```
pub enum Foo {
  pub case A
  case B // implicitly private
```

I don't know. We need to come up with some syntax.

**Comment by magnus-madsen** [comment]
We have a use case in `Chain` and in `ViewLeft` etc.

**Comment by mlutze** [comment]
Is there a use case for allowing only one of the constructors? If not, I was thinking that we could reuse the `sealed` keyword:
```scala
sealed enum Foo {
    case A
    case B
}
```

**Comment by magnus-madsen** [comment]
We sealed though? Its visibility of the individual constructors as opposed to the entire type.

**Comment by mlutze** [comment]
My idea is that, if you need a constructor protected, then you probably need all the constructors protected. Otherwise, matching, etc. becomes clumsy

**Comment by magnus-madsen** [comment]
OK. You could almost say that the members of the enum are *opaque*.

(now regretting my life choices...)

**Comment by magnus-madsen** [comment]
Hmm, but there was actually a use case in `LazyList` where we want to expose some of the constructors but not all.

Not for pattern matching, but to allow you to construct them. Otherwise you have to call functions...

**Comment by magnus-madsen** [comment]
We now have opaque!
