### ISSUE TITLE
Monad comprehensions

### ISSUE THREAD

**Issue by albertllousas** [flix/flix#1629]
Hi,

Is there any plan to add monad comprehensions (aka For Comprehensions, Computation Expressions, Do expressions) to the language?

**Comment by magnus-madsen** [comment]
Hello albertllousas and welcome to our little community!

Monad comprehensions and the like is definitely something we want to add to the language. See e.g. https://github.com/flix/flix/issues/508.

We currently allow the following:

```
let* x = Some(123);
let* y = Some(456);
  Some(x + y)
```

which gets desugared into some `flatMap` calls. 

We are partially inspired by https://jobjo.github.io/2019/04/24/ocaml-has-some-new-shiny-syntax.html

We are at the cusp of being able to express the Functor, Applicative, and Monad type classes. Once this happens, we should go about creating some useful syntax for them. So in short, this is very much in the cards, and will probably arrive with one or two months.

**Comment by albertllousas** [comment]
Cool! thanks! I will try to contribute!
