### ISSUE TITLE
Remove UnaryDeprecated and BinaryDeprecated

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1639]
When the Order type class is merged in.

**Comment by magnus-madsen** [comment]
@esbenbjerre I think this can now be accomplished.

**Comment by esbenbjerre** [comment]
Do we need a semantic operator for unary plus? If not, then I'm not sure how to handle that case, e.g. in Weeder.scala:607

**Comment by magnus-madsen** [comment]
No, I don't think unary plus actually does anything.

**Comment by esbenbjerre** [comment]
> No, I don't think unary plus actually does anything.

I'm not sure I follow you. I know semantically it has no meaning, but aren't we still allowing it in expressions?
For example, if I comment out line 607 in Weeder.scala:
```
//case "+" => WeededAst.Expression.UnaryDeprecated(UnaryOperator.Plus, e, loc)
``
Then this program can't compile
```
pub def main(): Int = +1
```
```
>> Undefined name '+'.

1 | pub def main(): Int = +1
                          ^^
                          name not found
```

**Comment by magnus-madsen** [comment]
We should still allow it, but just erase it, i.e. return the underlying expression.

**Comment by esbenbjerre** [comment]
> We should still allow it, but just erase it, i.e. return the underlying expression.

Okay thanks, I think I understand now.

**Comment by esbenbjerre** [comment]
I have removed them from most places, but Synthesize and Monomorph does stuff I'm not familiar with.
What is the purpose of Synthesize now that we have type classes? How should it change?

**Comment by magnus-madsen** [comment]
Synthesize will be removed soon, but not yet! What happens if you remove the cases from synthesize and monomorph?

**Comment by esbenbjerre** [comment]
> Synthesize will be removed soon, but not yet! What happens if you remove the cases from synthesize and monomorph?

Alright that works :)
I'll open a PR shortly.

**Comment by magnus-madsen** [comment]
Uuh. What are those? It might be that they cannot be removed yet from Synth/Monomorph.

**Comment by esbenbjerre** [comment]
> Uuh. What are those? It might be that they cannot be removed yet from Synth/Monomorph.

It happened after I changed line 555 in Synthesize.scala from
```
val default = Expression.BinaryDeprecated(BinaryOperator.Equal, exp1, exp2, Type.Bool, Type.Pure, sl)
```
to
```
val default = Binary(SemanticOperator.BoolOp.Eq, exp1, exp2, Type.Bool, Type.Pure, sl)
```
I've also tried to use `Expression.InvokeMethod` but this still gives me `java.lang.VerifyError: Bad type on operand stack`.

**Comment by esbenbjerre** [comment]
Nevermind I think I solved it.
