### ISSUE TITLE
Improving interop

### ISSUE THREAD

**Issue by mhyee** [flix/flix#164]
Just a general issue about improving interop in terms of usability and performance.

As discussed in #163:

> There's at least one obvious optimization we can do (generate code that directly calls a hook, rather than an indirection to Flix.invoke / Flix.invokeUnsafe which has to do a map lookup), and maybe we can handle hook closures better (rather than wrapping a hook in a lambda). We've also discussed improving the interop interface (maybe pre-generating a bunch of functional interfaces instead of using the Invokable / InvokableUnsafe interfaces), and/or providing a bunch of implicits and macros. But it's not as obvious what we should do. For now, I'm going to close the main interop issue, and then open one or more new ones.

Let's open separate issues when we start discussing specific items. This issue is just a reminder and for high-level discussions.

**Comment by magnus-madsen** [comment]
We decided that hooks cannot be used directly as closures. To use a hook as a closure it must be wrapped in a Flix closure.

**Comment by mhyee** [comment]
This issue is about improving interop in general, not using hooks as closures. (In fact, closure conversion automatically wraps hooks as closures, so the user doesn't have to do anything.)

Specifically (and we should open separate issues for them when we start the implementation):

- [ ] Improve performance by generating code that directly calls a hook, rather than through indirection (invoke / invokeUnsafe)
- [ ] Improving the interface, so use pre-generated functional interfaces or macros instead of Invokable / InvokableUnsafe.

Re-opening this issue.

**Comment by magnus-madsen** [comment]
> Improve performance by generating code that directly calls a hook, rather than through indirection (invoke / invokeUnsafe)

I thought that was impossible? At least without two-stage compilation?

Should we try to open separate issues for each item, and describe them in more detail?

**Comment by mhyee** [comment]
>> Improve performance by generating code that directly calls a hook, rather than through indirection (invoke / invokeUnsafe)

> I thought that was impossible? At least without two-stage compilation?

We could at least remove one layer of indirection. Right now we generate a call to invoke/invokeUnsafe, passing the string name of the hook and arguments. The method then does a map lookup, and then calls the hook.

We could probably store the hooks in an array, and then calling a hook would just directly load from the array and then pass the arguments.

Or maybe there was a better way -- I'm tired right now and can't remember. At the very least, we were pretty sure this was possible.

What *does* require two-stage compilation is generating a bunch of specialized interfaces for each of the hooks (i.e. the thing we do for lambdas), so we don't have to wrap everything in an array and use Invokable / InvokableUnsafe. But we can probably work around this by generating a bunch of specialized interfaces (like Scala), or maybe using macros.

Yes, we should open separate issues, and copy the discussion here. This issue was originally meant as a placeholder, and a place to discuss other improvements we could do. So let's not close this one yet.

**Comment by magnus-madsen** [comment]
We agreed at some previous time that calling Java closures directly from the Flix run-time would be almost impossible engineering wise. Thus, to use a Java closure it must be wrapped in a Flix closure.

As for the general question of improving interop, we will open a ticket in the near future, when we get some users and hear their feedback.

**Comment by magnus-madsen** [comment]
As a side comment: I don't think this will be a performance issue for a very long time, as there are much bigger fish to fry.
