### ISSUE TITLE
Type Signature of Main

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1645]
For #1644 I need to fix the signature of main. The #977 ticket explores some grand ideas about main, but for now I need something simple that works. In particular, the notion that main can return values that are then printed needs to go.

I propose  to fix the signature of main to:

```
def main(args: Array[String]): Int & Impure
```

(Not sure if we can avoid fixing the purity/impurity).

We also temporarily add the following:

```
pub def unsafeToString(x: a): String =
    import java.util.Objects:toString(##java.lang.Object);
    toString(x as ##java.lang.Object) as & Pure
```

Thus the following works:

```
def main(): Unit & Impure =
    Console.printLine(ToString.toString(Some(123)); 0

def main(): Unit & Impure =
    Console.printLine(#{A(123).} |> unsafeToString); 0
```

(Arguably we can change `printLine` to accept something that has a `ToString` instance - but that can be explored separately.

EDIT: The returned `Int` would be the exit code.

**Comment by stephentetley** [comment]
Args as `Array[String]` would be good as far as I'm concerned, we could then implement something like Haskell's GetOpt as a library in Flix to decode the arguments.

**Comment by mlutze** [comment]
I prefer `List[String]` or something else immutable, to make purity easier. But I guess that can be addressed later.

**Comment by magnus-madsen** [comment]
I would also prefer `List[String]` but it is hard for me to construct such a list in JVM bytecode. It is much easier to pass the array. 

I think I will go with the above as an intermediate solution-- good enough for now and we can change it later.

**Comment by magnus-madsen** [comment]
Master now enforces the following signature for `main`:

```
def main(args: Array[String]): Int32 & Impure
```

The returned int is used as the exit code. (Works when invoked from Flix, but not yet from the compiled class files). 

If `main` is pure you can always cast an expression to impure `as & Impure`.

**Comment by magnus-madsen** [comment]
You can supply args to main by invoking flix with `--args "--abc --def"`.

**Comment by stephentetley** [comment]
Excellent. I'm working on porting Haskell's GetOpt. So I'll see how they work together.
