### ISSUE TITLE
Typing of Semantic Operators is too lenient

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1646]
For example:

```
        case SemanticOperator.StringOp.Concat =>
          for {
            (constrs1, tpe1, eff1) <- visitExp(exp1)
            (constrs2, tpe2, eff2) <- visitExp(exp2)
            resultTyp <- unifyTypeM(tvar, tpe1, tpe2, loc)
            resultEff = Type.mkAnd(eff1, eff2)
          } yield (constrs1 ++ constrs2, resultTyp, resultEff)
```

This does not enforce that `exp1` and `exp2` must be strings.

The same problem for many of the other semantic operators.

**Comment by magnus-madsen** [comment]
Fix it for string. Then think about how to do it elegantly for the other operators, e.g. shl shr.

**Comment by magnus-madsen** [comment]
I have fixed it for string, but we need to look into the rest of the types.

**Comment by esbenbjerre** [comment]
I've started the work on this, but I wanted to discuss whether the code duplication needed to fix this is necessary because the `SemanticOperator` is structured "backwards" in a sense.
If it had been `SemanticOperator.Op.Type` instead of `SemanticOperator.Type.Op` I think the code could be structured better. Do you remember whether this design choice was for another reason that I've missed and/or would you be willing to let me refactor it?

**Comment by magnus-madsen** [comment]
> 
> 
> I've started the work on this, but I wanted to discuss whether the code duplication needed to fix this is necessary because the `SemanticOperator` is structured "backwards" in a sense.
> If it had been `SemanticOperator.Op.Type` instead of `SemanticOperator.Type.Op` I think the code could be structured better. Do you remember whether this design choice was for another reason that I've missed and/or would you be willing to let me refactor it?

Let me think about it. I will get back to you.

I don't remember if there was a specific rationale, but I guess grouping operators by type make sense? (the current impl)

**Comment by magnus-madsen** [comment]
(now that the String concat was fixed - this ticket is less urgent)

**Comment by esbenbjerre** [comment]
> I don't remember if there was a specific rationale, but I guess grouping operators by type make sense? (the current impl)

I agree 100%, it's just that it makes the pattern matching harder to use.

I'll move on to the next ticket while you consider if refactoring is possible and/or worth it :)

**Comment by magnus-madsen** [comment]
Lets move on- for now.
