### ISSUE TITLE
Add Functor Type Class

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1647]
```
class Functor[m :# Type -> Type] {
  ///
  /// Applies the function `f` to `s` preserving its structure.
  ///
  def map(f: a ->b & e, s: m[a]): m[b] & e
}

namespace Functor {
  ///
  /// Lifts the function `f` into the functor.
  ///
  def lift[a, b, e, m: Functor](f: a -> b & e): m[a] -> m[b] & e = Functor.map(f)

  //
  // Replaces the value `a` in `s` by the given value `x` preserving the structure of `s`.
  //
  def as[a, b, m: Functor](s: m[a], x: b): m[b] = Functor.map(_ -> x)
}
```

List of instances: 
- [ ] Add instance for `Option`.
- [ ] Add instance for `List`.
- [ ] Add instance for `Nel`.
- [ ] Add instance for `Array`.
- [ ] Add instance for `MutList`.

**Comment by esbenbjerre** [comment]
No instance for `Set` and `Map`?

**Comment by magnus-madsen** [comment]
> 
> 
> No instance for `Set` and `Map`?

Set is not a Functor (because it eliminates duplicates). It is sometimes called an "unlawful" functor. I don't know about Map.

**Comment by magnus-madsen** [comment]
Here is a fun example:

```
List("a", "b", "abc").map(length).sum == 5
Set("a", "b", "abc").map(length).sum == 4 (whoops!)
```

**Comment by esbenbjerre** [comment]
> > No instance for `Set` and `Map`?
> 
> Set is not a Functor (because it eliminates duplicates). It is sometimes called an "unlawful" functor. I don't know about Map.

Of course. I remember now, we also discussed it during my tree project.

**Comment by magnus-madsen** [comment]
So while we do have `Set.map` I don't think we will have an instance for it. Then if you want to do something wrong you have to be explicit about it.

**Comment by esbenbjerre** [comment]
I can't remember if we discussed effects in relation to type classes.
Should I cast `map` in `MutList` and `Array` as pure?

**Comment by magnus-madsen** [comment]
Yes

**Comment by magnus-madsen** [comment]
Well, it depends on the effect of map itself.

**Comment by esbenbjerre** [comment]
> Well, it depends on the effect of map itself.

I actually missed that you had annotated `Functor.map` as effect polymorphic above, so I think I know what to do.
