### ISSUE TITLE
Type Classes: Add Applicative Type Class

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1649]
```
class Applicative[f] {
  def point(a: a): f[a] 
  def ap(fn: f[a] -> f[b], fa: f[a]): f[b]
}
```

Instances:
- Option
- List
- Nel

**Comment by stephentetley** [comment]
For "non-functional" Applicatives / Monads like List and Option this definition of `ap` seems correct:

pub def ap(f: m[a -> b & ef] , x: m[a]): m[b] & ef


It means we can define, for example, the family of `liftA` functions equivalent to what we have for `Option` and `Result`, see here: 

https://github.com/stephentetley/flix-monadlib/blob/master/src/Applicative.flix


I'm having problems trying to define "functional" Applicatives / Monads with polymorphic effects though (e.g State and Reader).

I'm trying to get Reader as something like this (polymorphic in "environment" `i`, effect `ef` and answer `a`): 

pub opaque type Reader[i, ef, a] = i -> a & ef

Unfortunately I can't define even Functor.map before I try to do the Applicative and Monad instances.

**Comment by mlutze** [comment]
@stephentetley Are the problems related to possible issues or weaknesses in the type class system? In particular, is it necessary to add an effect parameter to the class itself?

**Comment by magnus-madsen** [comment]
I am not sure I fully understand the problem either.

**Comment by stephentetley** [comment]
Thanks Matthew, I don't think type classes are the issue as I can't work out how to write / type Reader.map as a regular function.

Basically I want Reader to have this type (changed from an opaque type to an enum as enums might be more mature in the type checker):

~~~

    pub enum Reader[ef :# Bool, i, a] { 
        case Reader(i -> a & ef)
    }

~~~

That's to say Reader is a function from a static argument `i` to an answer `a`. In Flix, I'd like Reader to effect polymorphic in case we want the static argument to be an array for example.

This is the implementation of `map` I have, the effect annotations are guesses on my part from looking at Choice in the std lib.

`map` has to decons the enum to get `f1` - the function "from i to a". It applies `f1` to the static argument called `r` and applies the map function `f` which we'd like to be effectful so it can e.g. read an array.

~~~

    pub def mapReader[a, b, i, ef :# Bool](f: a -> b & ef, x: Reader[ef, i, a]): Reader[ef, i, b] = 
        match x { 
            case Reader(f1) => { 
                Reader(r -> {let a = f1(r); f(a)})
            }
        }

~~~

This fails with the following error:

~~~

>> Mismatched kinds for type parameter 'ef'.

115 |     pub def mapReader[a, b, i, ef :# Bool](f: a -> b & ef, x: Reader[ef, i, a]): Reader[ef, i, b] = 
                                                             ^^
                                                             Kind: Bool


115 |     pub def mapReader[a, b, i, ef :# Bool](f: a -> b & ef, x: Reader[ef, i, a]): Reader[ef, i, b] = 
                                                                           ^^
                                                                           Kind: Type

~~~

**Comment by magnus-madsen** [comment]
This sounds very much like a compiler bug-- which is good news because that is something we should be able to fix.

**Comment by magnus-madsen** [comment]
@mlutze 

Do you want to have a look or should I?

Also, I think we should really allow kind ascriptions everywhere. That way `Reader[ef, i, a]` could be annotated with kinds to see if that is where the problem is.

**Comment by magnus-madsen** [comment]
@mlutze This actually happens in the Namer:

```
-- Name Error -------------------------------------------------- foo.flix
    ^^^^^^^^
>> Mismatched kinds for type parameter 'ef'.

5 |     pub def mapReader[a, b, i, ef :# Bool](f: a -> b & ef, x: Reader[ef, i, a]): Reader[ef, i, b] =
                                                           ^^
                                                           Kind: Bool


5 |     pub def mapReader[a, b, i, ef :# Bool](f: a -> b & ef, x: Reader[ef, i, a]): Reader[ef, i, b] =
                                                                         ^^
                                                                         Kind: Type
```

**Comment by magnus-madsen** [comment]
I looked a bit. Inside `getImplicitTypeParamsFromFormalParams` we have `ef` both as of kind `Bool` and of kind `Type`. I think the problem is that when we look at `ef` inside `Reader` we think it must be `Type`, but that is not the case (here).

**Comment by magnus-madsen** [comment]
@stephentetley 

This is definitely a compiler bug, so something we can fix. We are simple inferring the kind of `ef` incorrectly in one place.

**Comment by magnus-madsen** [comment]
@mlutze 

Merging our two PRs still have not fixed the problem. This:

```
pub enum Reader[ef :# Bool, i, a] {
    case Reader(i -> a & ef)
}


pub def mapReader[a, b, i, ef](f: a -> b & ef, x: Reader[ef, i, a]): Reader[ef, i, b] =
    match x {
        case Reader(f1) => {
            Reader(r -> {let a = f1(r); f(a)})
        }
    }

```

still fails.

If I add annotations *everywhere*:

```
pub enum Reader[ef :# Bool, i, a] {
    case Reader(i -> a & ef)
}


pub def mapReader[a, b, i, ef :# Bool](f: a -> b & (ef :# Bool), x: Reader[(ef :# Bool), i, a]): Reader[(ef :# Bool), i, b] =
    match x {
        case Reader(f1) => {
            Reader(r -> {let a = f1(r); f(a)})
        }
    }
```

it still does not work :(

I guess we have more digging to do.

**Comment by mlutze** [comment]
At least it's a different error!

We're assigning `Star` kind to `Reader` since it's not immediately clear what it is. We can make the kind inference smarter by using the kinds of the parameters. This is going further along the road to fully-implemented kind inference.

**Comment by magnus-madsen** [comment]
@mlutze 

Felix will soon look into extending the standard library with more type classes, including this one.

What is the status of type signatures with kinds? It should work OK as long as they are spelled out, right?

For example, I see we already have `Foldable` which seems to work fine.

**Comment by mlutze** [comment]
Right. Kind inference is still incomplete but I don't think there are any issues when the tvars are fully annotated.

**Comment by stephentetley** [comment]
I've a solution to the problem of Reader which I think is also applicable to State (although I haven't coded up State yet).

Rather than define Reader as:

~~~

pub opaque type Reader[i, ef, a] = i -> a & ef

~~~

Use the simple pure definition: 

~~~

pub opaque type Reader[i, a] = i -> a

~~~

With carefully controlled casting to "float" the effect to the top level `Functor.map`, `Applicative.ap` and `Monad.bind` can be effectful like the versions for Identity, Option, and Result:

~~~

pub opaque type Reader[i, a] = i -> a


instance Functor[Reader[i]] { 
    pub def map(f: a -> b & ef, x: Reader[i, a]): Reader[i, b] & ef = 
        let Reader(x1) = x;
        Reader(r1 -> {let a1 = x1(r1); f(a1) as & Pure}) as & ef
}


instance Applicative[Reader[i]] { 
    pub def point(x: a): Reader[i, a] = 
        Reader(_ -> x)

    pub def ap(f: Reader[i, a -> b & ef], x: Reader[i, a]) : Reader[i, b] & ef = 
        Reader(r1 -> 
            let f1 = runReader(f, r1);
            let x1 = runReader(x, r1);
            f1(x1) as & Pure
        ) as & ef

}

instance Monad[Reader[i]] { 

    pub def bind(mx: Reader[i, a], k: a -> Reader[i, b] & ef) : Reader[i, b] & ef = 
        Reader(r1 -> 
            let x1 = runReader(mx, r1);
            let m1 = k(x1) as & Pure;
            runReader(m1, r1)
        ) as & ef

}


~~~

**Comment by magnus-madsen** [comment]
> I've a solution to the problem of Reader which I think is also applicable to State (although I haven't coded up State yet).
> 
> Rather than define Reader as:
> 
> ...

Both @mlutze and I have been chewing on this solution. Thanks for posting it.
