### ISSUE TITLE
Remove Value.Tuple

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#165]
Delete the case class `Value.Tuple` and use raw arrays.

**Comment by magnus-madsen** [comment]
Ming-Ho: Instead of calling `.equals` would it make sense to have a class with static method `.equals(AnyRef, AnyRef)` and always refer to that?

**Comment by magnus-madsen** [comment]
Except for primitives, of course.

**Comment by mhyee** [comment]
I need to think more carefully about this, but I like the idea (so far). Equality in the code generator is pretty complicated right now, as there's so many different cases.

**Comment by magnus-madsen** [comment]
Fixed in #326
