### ISSUE TITLE
Don't Propagate Argument Types into the Initial Type Environment

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1650]

**Comment by magnus-madsen** [comment]
@mlutze 

On this line:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Typer.scala#L219

We populate the initial type environment with the type of the arguments of the function.

For example:

```
def fx(x: Int32): ... = e
```

We now start type inference on `e` with `x` already in scope as a Int32. *This is wrong*. But was previously done because we did not have type classes, but we had some pseudo-overloading of `+`. (The correct solution is to do type inference and then compare the inferred type to the declared type). Now I want to change it to simply pass the empty substitution to achieve that. However, if I do so, I get type errors:

```
-- Type Error -------------------------------------------------- Eq.flix

>> No instance of class 'Eq' for type ''a'.

146 |     def eq(t1: (a1, a2, a3, a4, a5, a6, a7), t2: (a1, a2, a3, a4, a5, a6, a7)): Bool =
              ^^
              no instance found
```

So it seems that the TC mechanism (accidentally?) came to depend on this quirk.

This seems to happen only for TC instances that depend on other TC instances...

Is this something you can help look into?

**Comment by mlutze** [comment]
Sure. Is the related work on the 1645 branch?

**Comment by magnus-madsen** [comment]
No

**Comment by magnus-madsen** [comment]
My new view is that this may be a good thing and is unavoidable in practice anyway.
