### ISSUE TITLE
Backend: GenMain should invoke System.exit with the right exit code

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1654]

**Comment by JonathanStarup** [comment]
@magnus-madsen It doesn't seem like Main.main() is used? Main.scala calls NS.m_main(stringArray) and then System.exit. Should this be changed?

**Comment by magnus-madsen** [comment]
What line do you see this on?

**Comment by JonathanStarup** [comment]
JvmBackend.scala line 201 returns the function and Main.scala calls that function, followed by system exit, at line 174-188. If the GenMainClass is removed, you can still run programs as normal.

**Comment by JonathanStarup** [comment]
I don't know when Main.class is used. Main.scala runs a function that returns an integer (m in case two has type Array[String] => Int)
```
// (Main.scala line 176)
compilationResult.getMain match {
            case None => // nop
            case Some(m) =>
              // Compute the arguments to be passed to main.
              val args: Array[String] = cmdOpts.args match {
                case None => Array.empty
                case Some(a) => a.split(" ")
              }
              // Invoke main with the supplied arguments.
              val exitCode = m(args)

              // Exit with the returned exit code.
              System.exit(exitCode)
          }
```
I think its calling Ns.m_main. but it's not calling Main.class at least because everything still works if GenMainClass is deleted and the main method doesn't return int as seen in the code.

**Comment by magnus-madsen** [comment]
Ah- It used when you want to build a jar and run main!

**Comment by magnus-madsen** [comment]
Running a Flix program that way does not go through `Flix.scala`

**Comment by JonathanStarup** [comment]
Ah okay, then I should probably try that to check it works

**Comment by magnus-madsen** [comment]
`build-jar` and go

**Comment by JonathanStarup** [comment]
Cool, it works 👍
