### ISSUE TITLE
Debate: Principles for Type Classes

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1659]
## Type Classes are Mathematical Functions

A type class is conceptually a function from a type to a set of lawful
operations on values of that type. (For example, the Eq type class takes a type
and returns the function `eq` and the three laws: reflexivity, symmetry, and
transitivity that the `eq` operation must satisfy for any instance of the type
class.)

(See https://degoes.net/articles/when-to-typeclass)

## Lawful and Lawless Type Classes

Every type class must specify a collection of laws that instances of the type
class must satisfy (see above). If a type class does not or cannot specify any
laws it must be declared as lawless. (For example, the Add type class - which
defines the plus operator - is lawless.)

Examples:
- Lawful:  Eq, Order, Functor, ...
- Lawless: Add, Sub, Mul, Div, FromString, ToString, Drop...

(Clarification: These laws are not checked by the compiler - that is an
undecidable problem - but they will be usable by future QuickChecking
infrastructure.)

## Type Classes are Hierarchical

A sub-class (i.e. a type class A that refines a type class B) must specify
*additional* laws that its instances must satisfy. (For example, the Order type
class extends PartialOrder and specifies that the order is total.)

## Type Class Instances are Globally Unique

To ensure that a type class can be viewed as a (deterministic) function, the
compiler enforces that type class instances are globally unique. Informally,
this means that there cannot be multiple instances of a type class for the same
type. (For example, if you have the type `Person` there can be at most one Eq
instance anywhere in the entire program.)

## No Overlapping Instances

Overlapping instances are by default disallowed. At a use site, the compiler
ensures that there is no ambiguity in which instance is chosen. The `ambiguous`
(or `overlapping`?) modifier can be used to selectively allow overlapping
instances for a specific type class. When enabled, the compiler will choose the
most specific instance or report an error if no such instance exists. 

## Type Classes are Namespaced

Every type class belongs to a namespace. Hence it is possible to define two
operations called `foo` in different type classes as long as they are in
different namespaces. Every type class gives rise to a "companion" namespace
where functions related to that type class can be defined. Type classes have
visibility so it is possible to define type classes that are only used locally. 

(The value of this companion namespace is unclear to me. It seems better to
define operations within the type class such that their implementation can be
overwritten by specific instances.)

## Built-in  Type Classes

The compiler tries to reduce its dependence on pre-defined type classes. The
following type classes are currently "blessed" (i.e. the compiler has knowledge
of them and they are required for compilation):

- Eq, Order
- LowerBound, PartialOrder, JoinLattice, MeetLattice
- Add, Sub, Mul, Div, ...
- Copy, Drop, FromString, ToString

Sources / Inspiration:
- https://degoes.net/articles/principled-typeclasses
- http://blog.ezyang.com/2014/07/type-classes-confluence-coherence-global-uniqueness/
- https://pchiusano.github.io/2018-02-13/typeclasses.html

For more technical debate about type classes, see:
- https://github.com/flix/flix/issues/1558

Some of these may also be turned into principles.

**Comment by mlutze** [comment]
Could/should we take the lawfulness a slight step further, requiring all member functions of a lawful type class to have at least one related law?

**Comment by magnus-madsen** [comment]
> Could/should we take the lawfulness a slight step further, requiring all member functions of a lawful type class to have at least one related law?

Yes, this is a good idea! :)

**Comment by magnus-madsen** [comment]
New Principle: A function should belong to a type class (as a signature with a default implementation) if possible. This is to allow it to be redefined later.

**Comment by magnus-madsen** [comment]
New Principle: Sealed

**Comment by magnus-madsen** [comment]
New Principle?: Override modifier.

**Comment by magnus-madsen** [comment]
Added to flix.dev
