### ISSUE TITLE
Debate: Principle of Layered Language

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1664]
## Layered Language

We want Flix to be a layered programming language that can be learned gradually.
For example, a programmer should be able to work with `Option` without
knowledge of higher-order function combinators. A programmer, with knowledge of
combinators, can use higher-order functions such as `map` and `flatMap` without
knowing about Functors or Monads. Finally, a programmer with knowledge of
Functors and Monads can use these abstractions without knowledge of category
theory. In other words, Flix should provide a path from the concrete (e.g.
working directly on algebraic data types with pattern matching) to the abstract
(e.g. working with Functors and Monads).

**Comment by mlutze** [comment]
(See also https://github.com/flix/flix/issues/1010)
