### ISSUE TITLE
IFDS implementation with new codegen backend

### ISSUE THREAD

**Issue by olhotak** [flix/flix#167]
I am testing the IFDS implementation with the new codegen backend.

I get the error message:

```
-- SYNTAX ERROR -------------------------------------------------- ???

>> Illegal call.

99|PathEdge(fstof3(t), sndof3(t), thdof3(t), sndof3(t)) :- t <- seed().
                                                                ^^^^^^
A parameter list must contain at least one parameter or be omitted.
```

seed is a hook:

```
      def seed(): Set[(Itm, MLabel, Itm)] = ...
      flix.addScalaHook("seed", seed _, setTuple(3))
```

How can I call seed() from Flix?

**Comment by magnus-madsen** [comment]
- We now support zero-argument functions, so you no longer have to use dummy parameters :)
- I added `cast2flix` to the solver, but we need to come up with some more general mechanism later.

With this in place, I would like to see performance numbers again for IFDS.
