### ISSUE TITLE
Make List.zip, List.zipWith and List.unzip tail recursive and add zip3 etc

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#1672]
The List functions `zip`, `zipWith` and `unzip` aren't tail recursive. I have a PR in the works...

Porting Haskell's GetOpt, I've found I need `zip3` and `unzip3`  i.e. the versions on three lists - do they merit adding at the same time?

If we add `zip3` should we add further arities? Haskells' standard library goes up to `zip7`

**Comment by magnus-madsen** [comment]
We have a rule where we try to go to N=10, but I think this is excessive for zip. In these cases we have gone to N=2, but if you have legitimate use cases with N=3 I think we can just add those by need. It makes sense for a function like zip3 to reside in the standard library, but I think going to N=7 or N=10 is overkill. At least at the moment.

**Comment by stephentetley** [comment]
Thanks Magnus, I'm make the PR with N=3.

**Comment by magnus-madsen** [comment]
Fixed in master.
