### ISSUE TITLE
Folder/package structure in library

### ISSUE THREAD

**Issue by esbenbjerre** [flix/flix#1674]
I think we could use a better folder structure in `main/src/library` now that we have reached 60+ files.

Proposal for new folders in `library`:
`/core` (for `Char`, `String`, etc.)
`/typeclasses` (self-explanatory)
`/collections` (self-explanatory)

Others?

**Comment by magnus-madsen** [comment]
Not sure, but we definitely need a good design.

I have a student who will be working on a package manager this semester. 
Maybe that will also lead to some restructoring of the std lib.

**Comment by esbenbjerre** [comment]
> Not sure, but we definitely need a good design.
> 
> I have a student who will be working on a package manager this semester.
> Maybe that will also lead to some restructoring of the std lib.

Deja vu. Also, yes it would probably be nice to have someone look into best practice instead of reinventing the wheel.
