### ISSUE TITLE
Type Classes: Add Reducible Type Class

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1678]
`Reducible` is like `Foldable` on a non-empty collection.

Propose a design.

See http://typelevel.org/cats/api/cats/Reducible.html

**Comment by jaschdoc** [comment]
In Flix `reduceLeft` has the signature
```flix
pub def reduceLeft(f: (a, a) ->  a & ef, t: t[a]): Option[a] & ef =
```
but in cats they treat it like a non-empty fold with the equivalent Flix signature being
```flix
pub def reduceLeft(f: (b, a) -> b & ef, s: a -> b, t: t[a]): b & ef
```
What do you reckon we should do? Stick to our definition of `reduce` or adopt the cats definition?

**Comment by jaschdoc** [comment]
Could you assign me to this, please?

**Comment by magnus-madsen** [comment]
What's the status now?

**Comment by magnus-madsen** [comment]
Ah- still a few to go, I see :)

**Comment by jaschdoc** [comment]
Yeah should be 1 PR to go
