### ISSUE TITLE
Debate: Naming Issue: reduceLeft vs. reduceLeftOpt

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1679]
We currently have:

```
def reduceLeft[a, e](f: a -> a -> a & e, xs: List[a]): Option[a] & e
```

but we want to add `Reducible` which has:

```
def reduceLeft[a, e](f: a -> a -> a & e, xs: List[a]): a & e
```

This is inconsistent. Question is: Do we rename `reduceLeft` to `reduceLeftOpt` everywhere? If not, what to do about `Reducible`?

It could be argued that e.g. `List.reduceLeft` is like to be used more than `Reducible` hence should have the short name...

**Comment by esbenbjerre** [comment]
What happens when `Reducible.reduceLeft` is called on an empty collection?

**Comment by magnus-madsen** [comment]
Only non-empty collections can implement reducible! :) (i.e. only Nel for now)

**Comment by esbenbjerre** [comment]
> Only non-empty collections can implement reducible! :) (i.e. only Nel for now)

Ahh, I see. In that case I vote for changing the name.
The only argument I have against is that it is longer. On the other hand, it is more concise.
I note that Scala uses `reduceLeftOption`.

**Comment by magnus-madsen** [comment]
This naming issue also applies to minimum, maximum, etc.

**Comment by magnus-madsen** [comment]
What if we use the same name? We can have `List.reduceLeft` (returning option) and `Nel.reduceLeft` returning a value. 

Similarly, we can use the different type classes to distinguish. 

In other words, I don't think its a problem.
