### ISSUE TITLE
Debate: Should foldRight be Lazy in its argument?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1680]
We currently define `foldRight` as:

```
def foldRight[a, b, e](f: a -> b -> b & e, s: b, xs: List[a]): b & e
```

This is fine, except it means that it cannot work for infinite lists.

If we change the definition to:

```
def foldRight(f: (a, Lazy[b]) -> b, s: b, xs: LazyList[a]): b
```

then it can work infinite lists (!).

Addendum: BUT if `foldRight` is lazy then we should probably be very careful with effects/purity (!).

**Comment by esbenbjerre** [comment]
Hmm. What about a `LazyFoldable` type class instead?

**Comment by magnus-madsen** [comment]
We can, but then you cannot be polymorphic in whether the list is finite or infinite. Not sure if that is good or bad.

**Comment by magnus-madsen** [comment]
Unless there are objections, I plan to make foldRight lazy.

**Comment by magnus-madsen** [comment]
I believe the signature should be:

```
def foldRight[a, b, e](f: (a, Lazy[b]) -> Lazy[b] & e, s: Lazy[b], xs: List[a]): b & e
```

Does that make sense?

**Comment by esbenbjerre** [comment]
> I believe the signature should be:
> 
> ```
> def foldRight[a, b, e](f: (a, Lazy[b]) -> Lazy[b] & e, s: Lazy[b], xs: List[a]): b & e
> ```
> 
> Does that make sense?

Do you just want the Foldable instances changed, or across the entire std. library?

**Comment by magnus-madsen** [comment]
Across the entire std lib :)

**Comment by magnus-madsen** [comment]
This also overcomes your concern about the stack :)

**Comment by magnus-madsen** [comment]
(Since the argument returned by foldRight is *not* lazy, I think that forces you to introduce a helper for every foldRight).

**Comment by esbenbjerre** [comment]
I've been looking into this, but it turns out it that having `foldRight` lazy means we must cast a lot of functions `& Pure`, which quickly propagates to a lot of other definitions relying on `foldRight`. That is, if purity is still necessary when dealing with laziness?

**Comment by magnus-madsen** [comment]
Thanks for looking into this. It sounds more and more like Lazy needs to carry an effect.

**Comment by magnus-madsen** [comment]
We will keep foldRight eager, but add a `foldRightL`: https://github.com/flix/flix/issues/2877
