### ISSUE TITLE
Type classes: Explore function inheritance

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1689]
If `Monad` extends `Functor` can you write `Monad.map` (which is inherited from `Functor`)?

_Originally posted by @magnus-madsen in https://github.com/flix/flix/issues/1662#issuecomment-763592395_

**Comment by magnus-madsen** [comment]
If map is signature, with no implementation, I see no problem.

If, however, `map` has a default implementation in say `Functor` and `XYZ` then which would it refer to?

**Comment by magnus-madsen** [comment]
For the moment we will not do this.

**Comment by magnus-madsen** [comment]
This has implications that are beyond what we are prepared to deal with at the moment. 

We can revisit this at a later time, but it is not relevant for a MVP type class implementation.
