### ISSUE TITLE
Simple to Use Proofs and Program Verification

### ISSUE THREAD

**Issue by sirinath** [flix/flix#1697]
Can simple to use proofs be added to the language in the spirit of [Formality](https://github.com/moonad/Formality), [Why3/WhyML](http://why3.lri.fr/) or [Dafny](https://github.com/dafny-lang/dafny).

**Comment by magnus-madsen** [comment]
I think - over time - once we have features like https://github.com/flix/flix/issues/1609, https://github.com/flix/flix/issues/1153, and https://github.com/flix/flix/issues/1153 we can start to think about this. These are sort steps towards doing a bit more in type checking. But I have no plans to turn Flix into Coq.

**Comment by sirinath** [comment]
I wan thinking more in the lines of [Formality](https://github.com/moonad/Formality) and [Why3/WhyML](http://why3.lri.fr/) than Coq and Idris.

**Comment by magnus-madsen** [comment]
I think those languages are excellent, but we have no concrete plans to move Flix towards an interactive theorem prover.
