### ISSUE TITLE
Prelude has wrong definition of `uncurry`

### ISSUE THREAD

**Issue by jacopol** [flix/flix#1698]
The following correct program is rejected by flix:

`pub def wrong(f:a->a->Option[a], l:List[(a,a)]) : List[Option[a]] = List.map(uncurry(f),l)`

yields

```
-- Type Error -------------------------------------------------- ???

>> Unable to unify the type variable ''0' with the type '(a, a)'.
>> The type variable occurs recursively within the type.

1 | pub def wrong(f:a->a->Option[a],l:List[(a,a)]):List[Option[a]] = List.map(uncurry(f),l)
                                                                     ^^^^^^^^^^^^^^^^^^^^^^
                                                                     mismatched types.


Type One: ... -> ... -> ...[...] -> ...
Type Two: ... -> ... -> ...[...] -> ...
```

**Comment by magnus-madsen** [comment]
I think this might be related to: #1650

**Comment by jacopol** [comment]
Shorter example:
`pub def wrong(l:List[(a,a)],f:(a,a)->a):List[a] = List.map(f,l)`

**Comment by jacopol** [comment]
I tracked this down to the Prelude: the definition of uncurry is wrong (!)

Prelude says:
`pub def uncurry(f: a -> (b -> c & e1) & e2): (a, b) -> c & (e1 and e2) = (x, y) -> (y |> f(x))`

The correct definition is:

`pub def uncurry(f: a -> (b -> c & e1) & e2): ((a, b)) -> c & (e1 and e2) = match (x, y) -> (y |> f(x))`

**Comment by jacopol** [comment]
The definition is also overly complicated. A simpler (correct) definition would be:

`pub def uncurry(f: a -> (b -> c & e1) & e2): ((a, b)) -> c & (e1 and e2) = match (x, y) ->f(x,y)`

**Comment by mlutze** [comment]
This also raises a question about whether the lambda syntax with tuples/implicit currying needs to be revisited?

**Comment by magnus-madsen** [comment]
Interesting. So you are saying that uncurry does not, in fact, uncurry? :)

**Comment by jacopol** [comment]
Yes, the uncurry function in the library is just the identity, but now I'm confused about the effect annotations.
In particular, where does the effect of (a,b)->c & e go, given that (a,b)->c is just the same as a -> b -> c ?
