### ISSUE TITLE
Meta: Some interesting pointers to borrow ideas

### ISSUE THREAD

**Issue by sirinath** [flix/flix#1699]
- https://felix-lang.github.io/felix/, http://felix-lang.org/
- https://groupoid.space/
- https://n2o.dev/
- https://erp.uno/
- https://o83.github.io/platform.rs/
- https://www.microsoft.com/en-us/research/project/bosque-programming-language/
- https://dafny-lang.github.io/dafny/
- https://koka-lang.github.io/koka/doc/index.html
- https://www.unisonweb.org/
- http://why3.lri.fr/
- https://cakeml.org/
- https://www.adacore.com/about-spark
- https://www.fstar-lang.org/
- https://github.com/microsoft/verona
- https://www.luna-lang.org/
- http://www.ats-lang.org/
- https://www.idris-lang.org/
- https://effekt-lang.org/
- https://www.eff-lang.org/
- http://www.sac-home.org/doku.php
- https://concurnas.com/
- https://bondi.it.uts.edu.au, https://github.com/Barry-Jay/bondi, 
- https://clean.cs.ru.nl/Clean
- https://agraef.github.io/pure-lang/
- https://github.com/axch/rules
- https://www.rascal-mpl.org/
- http://maude.cs.illinois.edu/w/index.php/The_Maude_System
- https://kframework.org/, https://runtimeverification.com/k/
- http://tom.loria.fr/wiki/index.php/Main_Page
- https://www.txl.ca/
- http://www.cs.cmu.edu/~aldrich/plaid/, https://github.com/plaidgroup/plaid-languni
- http://www.unicon.org/
- http://shenlanguage.org/
- https://mercurylang.org/
- https://racket-lang.org/
- https://vale.dev/
- https://github.com/carp-lang/Carp
- https://lexi-lambda.github.io/hackett/
- https://nim-lang.org/
- https://www.red-lang.org/
- https://github.com/acl2/acl2, https://www.cs.utexas.edu/users/moore/acl2/
- http://whiley.org/
- https://github.com/tlaplus/tlaplus
- https://www.modelica.org/
- https://ptolemy.berkeley.edu/projects/embedded/caltrop/language.html
- http://tryjoinads.org/
- http://cml.cs.uchicago.edu/
- https://github.com/Hopac/Hopac
- https://github.com/polytypic/JoinCML
- http://jocaml.inria.fr/
- https://egraphs-good.github.io/

**Comment by magnus-madsen** [comment]
Thanks
