### ISSUE TITLE
Investigate compiler/interpreter performance

### ISSUE THREAD

**Issue by mhyee** [flix/flix#170]
Yesterday, while demoing the [RandomLatticeGraph](https://github.com/magnus-madsen/flix/blob/master/main/test/ca/uwaterloo/flix/util/perf/RandomLatticeGraph.scala), @luqmana found a test case that was much slower with the compiler backend than the interpreter.

I was able to reproduce it on my machine, but under certain heap sizes. Sometimes giving it more or less memory would result in the compiled bytecode being faster (as expected).

I'm going to take a closer look at it with the profiler.

[test.flix.zip is attached. The uncompressed file is 80K lines and 3MB.](https://github.com/magnus-madsen/flix/files/307283/test.flix.zip)

**Comment by magnus-madsen** [comment]
I can confirm this also happens on my machine, for PrefixSuffix, but with a different randomly generated graph.

**Comment by magnus-madsen** [comment]
Check out the flags:  -XX:MaxInlineSize and -XX:FreqInlineSize

**Comment by magnus-madsen** [comment]
The compiler is now significantly faster than the interpreter. See #457.
