### ISSUE TITLE
Formalise program transformation, compilation, optimisation and code generation using Term Rewriting, Rewriting Systems, Reduction Systems making it available to the language uses also

### ISSUE THREAD

**Issue by sirinath** [flix/flix#1700]
Can Term Rewriting be added. Languages like Pure is based on this. There is an old project https://github.com/axch/rules also to some extent https://github.com/dotty-linker/dotty which can be of inspiration for this functionality.

**Comment by stephentetley** [comment]
You could certainly implement term rewriting as a library. KURE and Strafunski[*] did this in Haskell, embedding the strategic term rewriting style that originally was developed in the language Stratego.

I will probably look at this at some point this year as it would be useful for the work I do in my day job (I did implement strategic term rewriting in SWI Prolog a couple of years ago). 

[*] Both are on Hackage.

**Comment by sirinath** [comment]
Would be a good start. 

One thing I am looking forward is that compilation and optimisation pipeline uses term rewriting. By supplying a new rule set one can have library specific optimisations. Also new optimisations can be added by adding new rules to the compilation pipeline. The compilation would in itself be more optimal and no seed of compiler plugins and phases. Dependencies between the rules will make compilation parallel and as short as possible. Also the rules need not be "fitted" into a specific compiler phase.

**Comment by sirinath** [comment]
The algorithms here https://github.com/egraphs-good/egg might be of use when implementing.

**Comment by magnus-madsen** [comment]
I think this would belong in a library, at least for the moment.
