### ISSUE TITLE
Automatic / Static Memory Usage, Ownership and Life Time Tracking

### ISSUE THREAD

**Issue by sirinath** [flix/flix#1701]
With Java Foreign Memory Access API and Off Java Heap techniques some level of memory management can be done without relying on the Java Heap and GC. This will eliminate GC overhead and unpredictability.

There are reasonable number of performance sensitive projects with use GC less Java.

So is it possible to have Life Time tracking with a view to have GC less memory management at some point in time.

Also this will make Flix more portable to in the future:
- WebAssembly
  - Wasmtime
  - Wasmer
  - [SSVM](https://github.com/second-state/SSVM)
  - Lucet
- Native
  - LLVM
  - Cranelift
- VMs
  - .NET
  - [MIR](https://github.com/vnmakarov/mir)
- etc.

Following languages are trying this in some form or the other:
- https://vale.dev/
- https://github.com/carp-lang/Carp
- https://vlang.io/

User burdened with racking ownership:
- https://www.rust-lang.org/

**Comment by magnus-madsen** [comment]
This is now happening in a Flix specific variant. The tracking issue is https://github.com/flix/flix/issues/3258.
