### ISSUE TITLE
Use Theoretically Researched and Formal Basis for Pattern Matching like Pattern Calculus

### ISSUE THREAD

**Issue by sirinath** [flix/flix#1709]
Use a researched basis for pattern matching in the language like [Pattern calculus](https://en.wikipedia.org/wiki/Pattern_calculus) with a possibility of sequential and concurrent pattern matching.

Also can make pattern matching 1st class.

**Comment by magnus-madsen** [comment]
At the moment there are no plans to add first-class patterns.
