### ISSUE TITLE
Staging, Macros and Meta Programming

### ISSUE THREAD

**Issue by sirinath** [flix/flix#1713]
Can
- [Staging](https://en.wikipedia.org/wiki/Multi-stage_programming), 
- [Macros](https://en.wikipedia.org/wiki/Macro_(computer_science)) and 
- [Meta Programming](https://en.wikipedia.org/wiki/Metaprogramming)
be added for [extensible programmin](https://en.wikipedia.org/wiki/Extensible_programming)

The language can at some point have a simple core which is enhanced through, macros and meta-programming to implement most of the functionality.  Also the same can be used to creates [DSLs](https://en.wikipedia.org/wiki/Domain-specific_language).

**Comment by magnus-madsen** [comment]
We explore this in the future, but at the moment we have no concrete plans.
