### ISSUE TITLE
Parallelism: Join Calculus, Transactional Events

### ISSUE THREAD

**Issue by sirinath** [flix/flix#1716]
Since you have CPS perhaps you can investigate possibility of incorporating features from Transactional Events, Join Calculus and Concurrent ML. Following are some pointers:

# CML

- http://cml.cs.uchicago.edu/
- https://github.com/Hopac/Hopac
- https://github.com/Hopac/Hopac.Extras

# Join Calculus

- https://github.com/Chymyst/chymyst-core, http://chemist.io/
- https://github.com/polytypic/JoinCML
- http://tryjoinads.org/
- http://jocaml.inria.fr/
- http://join.inria.fr/eng.htm
- https://sites.google.com/site/winitzki/tutorial-on-join-calculus-and-its-implementation-in-ocaml-jocaml
- http://moscova.inria.fr/join/index.shtml
- https://github.com/phaller/ScalaJoins
- https://github.com/Jiansen/ScalaJoin

# Transactional Events

- https://wasp.cs.washington.edu/tecaml/
- https://www.cs.rit.edu/~mtf/research/tx-events/

NB: [Chymyst](http://chemist.io/) is in Scala might fit in well with the current syntax.

**Comment by magnus-madsen** [comment]
We have no plans at the moment, but maybe in the future we could look into some of these.
