### ISSUE TITLE
Better (more interesting) Flix examples

### ISSUE THREAD

**Issue by mhyee** [flix/flix#172]
We have several (valid*) Flix examples, showing the expressivity of the language. However, nothing interesting happens when you run them.

We should create some small but interesting analysis examples, perhaps taking examples from presentations or even the paper. Have the analysis, along with some sample facts, and show the expected output.

*I think the IFDS and IDE examples don't even compile.

**Comment by magnus-madsen** [comment]
There is a tutorial now. You can get it by running `flix --tutorial output.flix`.

In the future we should have a whole collection of tutorials available this way.

**Comment by magnus-madsen** [comment]
Please have a look @mhyee to see if it makes sense.

**Comment by mhyee** [comment]
Yes, the tutorial in #184 makes sense. When completed and merged, we can close this issue.

Also, in the future, could you please cross-reference issues/PRs? In your PR description, you can even say "Fixes XX" and when the PR is merged, it'll automatically close the referenced issue.

**Comment by magnus-madsen** [comment]
I think we can leave this open, because we want to have more examples. But we need to think a bit more about it.

**Comment by magnus-madsen** [comment]
I am closing this. We have two tutorials and more will follow as we demo more and more analyses.

**Comment by gmlewis** [comment]
From an absolute newbie-to-flix perspective, I was poking around in the `examples` directory and found some interesting-sounding files like:
* `compiler-puzzle.flix`
* `simple-card-game.flix`

and then was struggling to figure out how to run them with `java -jar ${HOME}/tools/flix.jar`.
I was not successful, as that jar file appears to be more interested in "flix projects" than individual files.

My recommendation is that a new `README.md` be added to the `examples` directory, showing new users how they can take flix out for a spin.

I didn't want to create a new issue for this on GitHub, and this is the closest one I could find that seemed relevant.
Thanks.

**Comment by magnus-madsen** [comment]
@gmlewis Thanks for your comment. I somehow missed it. I think the easiest way is to simply paste them into a file in VSCode.

But maybe indeed we should have a README. Ill think about it.

(Meanwhile, I am closing this specific ticket as a part of my spring cleaning, since I think we now have ample examples).
