### ISSUE TITLE
Add List Literal Syntactic Sugar?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1721]
We currently have:

```
Set#{1, 2, 3}
Map#(1 -> true, 2 -> false)
```

but nothing for list. I would consider adding:

```
List#{1, 2} // or perhaps
List#[1, 2] 
```

This syntax should *not* be used in favor of `::` except when you have really long lists. For example:

```
let l = List#{
  alizarin,
  amaranth,
  amber,
  amethyst,
  apricot,
  aqua,
  aquamarine,
  asparagus,
  auburn,
  azure,
  beige,
  bistre,
  black,
  blue,
  blue-green,
  blue-violet,
  bondi-blue,
  brass,
  bronze,
  brown,
  buff,
  burgundy,
  camouflage-green,
  caput-mortuum,
  cardinal,
  carmine,
  carrot-orange,
  celadon,
  cerise,
  cerulean,
  champagne,
  charcoal,
  chartreuse,
  cherry-blossom-pink,
  chestnut,
  chocolate,
  cinnabar,
  cinnamon,
  cobalt,
  copper,
  coral,
  corn,
  cornflower,
  cream,
  crimson
}
```

would be a legitimate use case.

**Comment by magnus-madsen** [comment]
Thoughts?

**Comment by stephentetley** [comment]
I'd like to see this very much, especially if it could support something like GHC Haskell's `IsList` class that lets other list types take advantage of the syntax.

https://downloads.haskell.org/ghc/latest/docs/html/users_guide/glasgow_exts.html#overloaded-lists

**Comment by mlutze** [comment]
What is the reason for preferring the `::` syntax?

A while ago someone suggested using the `[]` syntax for lists rather than arrays. Given the "functional first" principle, I think it's a worthy consideration.

**Comment by magnus-madsen** [comment]
> What is the reason for preferring the `::` syntax?
> 
> A while ago someone suggested using the `[]` syntax for lists rather than arrays. Given the "functional first" principle, I think it's a worthy consideration.

The problem with `[]` as the primary syntax is: What does `[x, y]` mean? Is `y` the rest of the list or is this a two element list? The syntax `x :: xs` works pretty well here and has been used for a long time in the FP community. (I think Haskell uses a single `:`, but I digress).

As for `IsList` that looks like something we should look into - and maybe extend to the custom set and map syntax.

**Comment by magnus-madsen** [comment]
@stephentetley 

- The `IsList` type class is similar to e.g. our current type classes for operations, e.g. `Add`:
```
pub class Add[a] {
    ///
    /// Returns the sum of `x` and `y`.
    ///
    pub def add(x: a, y: a): a
}
```
where the compiler treats `x + y` as a call to `Add.add`.
- When you write something with the `List#{....}` syntax we simply expand it to `fromList([....])`.

is this right?

Is there any downside to this solution?

**Comment by magnus-madsen** [comment]
I am a bit uncertain about going this far:

https://gitlab.haskell.org/ghc/ghc/-/wikis/overloaded-lists

**Comment by stephentetley** [comment]
> 
>     * When you write something with the `List#{....}` syntax we simply expand it to `fromList([....])`.
> 
> 
> is this right?
> 
> Is there any downside to this solution?

That's what I imagine.

I don't remember people complaining about `IsList` on the Haskell mailing lists. 

A "downside" is that while other list types will get special syntax for construction, only `List` will have the inbuilt special syntax for pattern matching. However, the syntax `List` has for pattern matching is not so privileged that I see this as a real problem.

The extensions seem to be about enumeration syntax which Flix doesn't have anyway.

**Comment by mlutze** [comment]
> only List will have the inbuilt special syntax for pattern matching

Is that something we could change?

**Comment by stephentetley** [comment]
> 
> 
> > only List will have the inbuilt special syntax for pattern matching
> 
> Is that something we could change?

It could be changed in the compiler but it is possibly not a big win.

By adding a `ViewLeft` datatype and a function `viewLeft` I could get effective pattern matching for the `Chain` datatype:

https://github.com/stephentetley/flix-sandbox/blob/master/temp/Chain.flix

`ViewLeft` (and `ViewRight`) are probably more useful than just for Chain but they can live in the Chain module for now. 

What you get with `ViewLeft` is pattern matching on `nil` (called `NoneLeft` - I couldn't resist the pun) or `(head x rest)`. List pattern matching is more powerful because it allows arbitrary length peeking at the front of the list but most of the time you don't need to bind elements beyond head & rest.

**Comment by magnus-madsen** [comment]
I am open to this in the future, but it is not something we plan to add right now.
