### ISSUE TITLE
Self Hosting

### ISSUE THREAD

**Issue by sirinath** [flix/flix#1722]
At least by version 1.0 please target 100% self hosting.

**Comment by magnus-madsen** [comment]
What do you mean by self-hosting? Do you mean that the generated code should depend on the compiler- because we are slowly working on that.

**Comment by sirinath** [comment]
This is:
- [Self-hosting](https://en.wikipedia.org/wiki/Self-hosting_(compilers))
- [Meta-circular evaluator](https://en.wikipedia.org/wiki/Meta-circular_evaluator)

Also it might be worth while perusing [Homoiconicity](https://en.wikipedia.org/wiki/Homoiconicity) with syntactic meta programming defining the language and compilation done with term/graph rewriting. Non Lisp/Scheme language like Julia has  Homoiconicity. 

The applications of the above is:
- new versions of the language can be very quickly defined
- experimentation can be easily done
- compilation and optimisation would be very succinct
- optimisation can be library defined for special cases
- new optimisations can be easily added
- compilation will be as parallel as hardware allows an fast as possible

**Comment by magnus-madsen** [comment]
We will probably rewrite Flix in Flix at some point, but it is not a priority right now.
