### ISSUE TITLE
separate implicit and explicit type parameter code path

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1723]
So if the implicit kinds do something funky (as is their current wont), the user can annotate kinds explicitly and not have to deal with kind inference issues

**Comment by mlutze** [comment]
@magnus-madsen I don't recall all the details of our discussion. Do we want to make it so that all explicit parameters are `Type` unless otherwise annotated?

**Comment by mlutze** [comment]
Maybe we should remove the kind inference altogether, so we can come back and redo it the "right" way?

**Comment by magnus-madsen** [comment]
> 
> 
> Maybe we should remove the kind inference altogether, so we can come back and redo it the "right" way?

I think this might be a good way to go about it.

**Comment by mlutze** [comment]
Hmm, there are 243 occurrences of the string `& e` in `*.flix` files. If we disable kind inference, all these will have to be changed. Plus anything with a record or schema type. And I don't think that's any easy find-and-replace.

**Comment by magnus-madsen** [comment]
> 
> 
> Hmm, there are 243 occurrences of the string `& e` in `*.flix` files. If we disable kind inference, all these will have to be changed. Plus anything with a record or schema type. And I don't think that's any easy find-and-replace.

No, I don't think we can remove code and then come back and fix it. 

We will probably have to remove code and fix it in the same PR.
