### ISSUE TITLE
Debate: Design of a Testing Framework

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1726]
I could use some feedback for designing a testing framework. I have a doodle at #1725. 

The current solution with `@test` has worked fine, but is not really scalable. In my view:
- It is compiler magic. This has at least three downsides: (1) it requires compiler the compiler to treat `@test` functions special in several places. Such treatment is brittle. (2) It cannot be extended by the programmer. (3) It is entirely static like JUnit. You have the tests you have. You cannot write a parametrized test. You cannot write a function that computes at test.
- It is unclear how we could ever extend it to cover QuickCheck style properties.
- Did I mention it is compiler magic? It is governed by special rules w.r.t. visibility and redundancy.
- It requires a "custom runner" implemented in Scala. This gives very little flexibility.
- I have no plans to remove `@test` for the foreseeable future. We have 10k tests that use it so it will be around for a while. I would like to migrate the library tests though. 

My proposal is to write a new framework in Flix itself. Unfortunately, unlike `List` or `Option`, it seems there is a million test frameworks designs. So what to do...?

Well, I think I ultimately want the following:

- A minimal API that allows the programmer to *construct* tests.
- A separate API that executes tests and reports results (e.g. to the terminal or through some other mechanism).
- Would fit well with a future QuickCheck/SmallCheck/Typeclass Property framework.

Intuitively, the programmer writes a *test function* that when invoked returns a collection of test cases. These test cases should have names and probably be organized in a tree (but now separately from the namespace mechanism of the language). Given such a test case collection, a *test runner* executes the tests one-by-one (or in parallel for that matter) and collects the results.

Ideally each test would satisfy properties such as:
- compares results using `Eq` type class
- prints inequal values using `ToString` type class
- (optionally) provides a `Diffable` type class instances to highlight the difference between two values.

We can enforce these constraints today.

Arguably the test function would satisfy properties such as:
- it always terminates / is pure / is deterministic.
- it is const.

I hate it when the test functions crashes or fails to terminate. In JavaScript (and other languages) this has caused a lot headache when I can't even get to the point where I have the test list because the test framework crashes before. Right now, we can enforce purity, but not (yet) termination. Enforcing that the test function is pure does have the downside that test cases cannot depend on e.g. a file on disk. For example, you could not read a CSV file and create a test case for each. Note however that the tests *themselves* can be impure. 

I would like the test function to be const - that is - computable at *compile-time*. This would be a stronger requirement than what is currently understood by purity in Flix. I don't want to get into details atm. but I have some ideas. 

In my small doodle, you can see an example of some test cases (see https://github.com/flix/flix/pull/1725/files#diff-12fe2546dbe6a9a9d1df39454cc311a00b5c5741c8a5a18be75f2487bc3954c8R154)

Now for some questions I am struggle with:

- What do you think of the use of `Lazy` for the actual and expected values? I use lazy because these expression should not be evaluated by the test function but later by the test runner. One issue is that currently lazy expressions must be pure. But we obviously want to write impure test cases so either we have to change lazy or use Unit functions.
- What do you think of the use of records with `actual` and `expect` to make it *clear* which value is what?
- How should tests be named and organized in a hierarchy? My hope is that some combination of using e.g. Maps and this future const extension will prevent name clashes at *compile-time*. I briefly looked at HUnit, but their "labeling strategy" seems too liberal/unstructured to me.
- Can we define a useful `Diff` type class? How would it work?
- I tried to make the framework "extensible" by using polymorphism and row polymorphism everywhere, but ultimately I could not really make it work. My idea was that the programmer should be able to add extra fields, e.g. `timeout` to the tests (and then run them using either the original framework or using an extended framework). 
- I am not exposing the data types directly, instead I am trying to use constructors like `defineTest` and `defineSuite`.

Finally, note that while the "test framework" may look ridiculous small it is already much better than simply having `@test`!

**Comment by magnus-madsen** [comment]
I forgot to add one more concern:
- While I think it is fine to have - say - 1,000 tests in one file, it is problematic to have 1,000 tests inside *one* function due to JVM limitations. Thus, we would need some logical mechanism to split up very long tests lists. (Splitting them over multiple functions would be sufficient.)

**Comment by mlutze** [comment]
This model is nice when we have an "exact" expectation, but what if we have something like this:

```flix
def getXAndOtherStuff(): List[String] = ???

def mySuite(): Test.Suite = defineSuite("TestList") <| Map#{
        "getXAndOtherStuff" -> defineTest({
            actual = lazy List.contains("x", getXAndOtherStuff())
            expect = lazy true
        })
}
```

We end up with a message that says something like `expected true but was false`.

Some testing frameworks allow richer explanations, like `expected a to contain b but b was xyz`.
I'm not sure what the best way to allow that would be.

**Comment by magnus-madsen** [comment]
Interesting. I don't know what to do about that. You sort of want access to the Boolean expression? :/

**Comment by mlutze** [comment]
Python testing does this by looking at the AST. JUnit has a `Matcher` interface, with a `describeMismatch` and `matches` method. We could do something similar to the Matcher idea.

```flix
// NB: all of this is untested

class Matcher [a] {
  def tryMatch(x: a): MatchResult
}

enum MatchResult {
  case MatchSuccess
  case MatchFailure(String)
}

opaque type Contains[m, b] = (m[a], a)

instance Matcher[Contains[m, a]] with [m :# Foldable, a :# Eq] {
  def tryMatch(x : Contains[m, a]): MatchResult = ??? // check if the contains condition holds
}

def shouldContain[m : Foldable](container: m[a], element: a): Contains[m, a] = Contains(container, element)

Then we have something like:
... myList `shouldContain` myElement ...
```

I probably messed up some types there, but this is the rough idea.

**Comment by magnus-madsen** [comment]
It is a hard problem. Ideally I think you would want the AST of the Boolean expression, the values of all its free variables, and then to print each reduction step. That is a lot of engineering :) The above approach could work, but it is very specific to some operations.

**Comment by magnus-madsen** [comment]
On the other hand, if we have:

```
actual = Set(1, 3)    expected = Set(1, 2, 3)
```

We should easily be able to write "Expected Set(1, 2, 3), but got Set(1, 3) missing element 2".

The problem occurs when we have equality on Booleans.
