### ISSUE TITLE
Unconditional Recursion in Instance Def

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1734]
I by mistake wrote this:

```
    instance Monoid[Suite2] {
        def empty(): Suite2 = Suite2(Map.empty())

        def combine(x: Suite2, y: Suite2): Suite2 = 
            let Suite2(s1) = x;
            let Suite2(s2) = y;
                Monoid.combine(x, y)
    }
```

I wonder if we can detect such buggy code easily?

**Comment by magnus-madsen** [comment]
Also, why am I not warned that `s1` and `s2` are unused??

**Comment by mlutze** [comment]
I think we don't (yet) check instances in the Redundancy phase.

**Comment by magnus-madsen** [comment]
> 
> 
> I think we don't (yet) check instances in the Redundancy phase.

Roger. Makes sense.
