### ISSUE TITLE
Add Support for Channel Put in Select

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1735]
We should allow put operations inside select, e.g.:

```
select {
  case expChan <- exp1 => exp2
}
```

First step is to change the definition in `ParsedAst` from:

```
  case class SelectChannelRule(ident: Name.Ident, chan: ParsedAst.Expression, exp: ParsedAst.Expression)
```

to something like:

```
sealed trait SelectChannelRule

object SelectChannelRule {
  case class SelectGet(ident: Name.Ident, chan: ParsedAst.Expression, exp: ParsedAst.Expression) extends SelectChannelRule
  case class SelectPut(chan: ParsedAst.Expression, value: ParsedAst.Expression, exp: ParsedAst.Expression) extends SelectChannelRule
}
```

and add support for `SelectPut` to `Parser.scala`

**Comment by justinfargnoli** [comment]
I'll begin working on this. 

How does the following sound as a plan of action?
1. I'll read up on `parboiled2`.
2. Attempt to implement the changes mentioned above.
3. Submit a PR.
   1. If my changes look good, then we'll look at the next steps. (e.g. Changes that will need to be made to other phases of the compiler.)
   2. If I made mistakes in my implementation, then I'll continue iterating on it until it's good.

**Comment by magnus-madsen** [comment]
Sounds good!

**Comment by JeffreyBenjaminBrown** [comment]
Does [this](https://github.com/flix/flix/pull/1737) mean this issue should be closed too, and the line "Flix does not currently support put operations in select expressions" removed from [the chapter on concurrency](https://doc.flix.dev/concurrency/)?

**Comment by magnus-madsen** [comment]
> Does the fact that [issue 1737 is cloosed](https://github.com/flix/flix/pull/1737) mean this issue should be closed too? And that the line "Flix does not currently support put operations in select expressions" should be removed from [the chapter on concurrency](https://doc.flix.dev/concurrency/)?

No. I think it means that someone else has taken over that part of the implementation.

In particular there is this PR: #2696 were we are rewriting the channel implementation in Flix. When that is done, we can add puts to selects.

**Comment by magnus-madsen** [comment]
Continued in https://github.com/flix/flix/issues/4755
