### ISSUE TITLE
Delta Debugging

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#174]
Implement support for delta debugging ala jsdelta:

https://github.com/wala/jsdelta
https://en.wikipedia.org/wiki/Delta_Debugging

Assume we have a Flix program (a collection of facts and rules). 
Assume we have some rule which should *not* be true:

```
false :- A(x), B(x, y), C(y).
```

Then the idea is to compute the smallest set of facts that cause this rule to be invalidated. 

However, this is a bit expensive to do (exponential). So the idea is to use a heuristic which tries to select a small set of facts that violate the rule. At a high level the algorithm will do something like:

1. Run flix to determine that a rule is broken.
2. Partition the facts into groups/cells.
3. Randomly throw away half the groups.
4. Re-run flix and check if the rule is still broken. If so recurse on the smaller set of facts. Otherwise throw away the other half, and re-check. If the rule is still not broken, then re-partition into more groups, and repeat.

Changes needed:

1. Introduce two new `FlixException`s: `RuleException` and `TimeoutException`.
2. Introduce a `--timeout` flag which throws `TimeoutException` after the timeout.
3. Introduce a `--delta` flag to enable delta debugging.
4. Allow `true` and `false` as predicates in rules.
5. Throw `RuleException` if `false` occurs in the head of a rule where the body is true.
6. Implement a class `DeltaDebugger` which wraps a `Flix` object and repeatedly selects facts and re-evaluates the Flix program. Ideally this would not parse the program at every iteration, but only run the last phase of the compiler. Furthermore, the debugger should be interruptable / output the facts at every iteration.

**Comment by magnus-madsen** [comment]
- Implemented `TimeoutException`.

**Comment by magnus-madsen** [comment]
Implemented in #187 :dancer:

**Comment by mhyee** [comment]
For future reference, if I have a PR that addresses an issue, I typically reference the issue in the PR writeup, e.g. "This PR implements delta debugging. Blah blah. Fixes #174." Then merging the PR automatically closes the related issue.

(After all, if the code hasn't been merged in yet, the issue technically hasn't been resolved yet.)

**Comment by magnus-madsen** [comment]
Good point!
