### ISSUE TITLE
Instance declaration syntax

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1751]
I would like to update the instance declaration syntax from:

```
instance Eq[(a1, a2, a3, a4)] with [a1 : Eq, a2 : Eq, a3 : Eq, a4 : Eq]
```

to
```
instance Eq[(a1, a2, a3, a4)] with Eq[a1], Eq[a2]...
```

At the same time I would also like if we permit arbitrary types in the constraints and report if they are not type variables.

While we have #1748, I do think that complex instances should inhibit other errors, so I would the "ComplexError" to the Weeder.

In summary:

- [ ] Update instance declaration syntax.
- [ ] Allow complex types in both head and body class constraints.
- [ ] Issue Weeder errors when such complex types are encountered.

**Comment by magnus-madsen** [comment]
NB: This syntax is not necessarily the "final form", but I think it is closer to it.

**Comment by magnus-madsen** [comment]
Note: The "simple instance requirement" probably does not make sense for neither records nor Boolean types, but we will cross that bridge when we get to it. Probably we need to check the kind.

**Comment by mlutze** [comment]
> so I would the "ComplexError" to the Weeder.

I'm not sure we should do this in the Weeder, since at that point, we can only make guesses about the type based on syntax. For records, schemas, tuples, functions, partially applied types, the true "shape" of the type cannot necessarily be determined from the shape of the syntax. This same idea is the major issue with our kind inference.

It may be possible to do in the Weeder, but it seems much more robust to run the check on `ast.Type`s rather than `ParsedAst.Type`s.

**Comment by magnus-madsen** [comment]
> 
> 
> > so I would the "ComplexError" to the Weeder.
> 
> I'm not sure we should do this in the Weeder, since at that point, we can only make guesses about the type based on syntax. For records, schemas, tuples, functions, partially applied types, the true "shape" of the type cannot necessarily be determined from the shape of the syntax. This same idea is the major issue with our kind inference.
> 
> It may be possible to do in the Weeder, but it seems much more robust to run the check on `ast.Type`s rather than `ParsedAst.Type`s.

Good point! I  did not think about that. I guess there could also be uses for type aliases!

In that case, maybe we should first check for these syntactic requirements and *then* only check for the other instance requirements. The problem is that otherwise you can get obscure errors:

```
instance Eq[List[Option[String]]] {
}
```

![image](https://user-images.githubusercontent.com/2287953/109938997-e9a6da00-7cd0-11eb-8ac4-12589a0a95b4.png)

![image](https://user-images.githubusercontent.com/2287953/109939030-f0355180-7cd0-11eb-8bc2-13525b5a785a.png)


I.e. here the last error is really the real one and the overlapping instances are "fake"
