### ISSUE TITLE
Syntactic salt(?) for functions, tuples

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1752]
What's the opposite of sugar? Paprika?

It would be nice to have a robust way to create a partially applied tuple or function type. (Maybe also record and schema types)?
This can be done with type aliases, but this creates type lambdas which have trouble with unification.

Examples:
```flix

Tuple2[a, b] === (a, b)
Tuple3[a, b, c] === (a, b, c)
Function[ef, a, b] === a -> b & ef

instance Functor[Tuple2[a]] {
   ...
}
```

Alternatively, the solution might be to improve the unification as it pertains to type lambdas.

**Comment by magnus-madsen** [comment]
I think the solution is to have type lambda. The question is when/where exactly to simplify them.

We could also think about Scala-style syntax, e.g. `(Int, _)` (but maybe that should be sugar for type lambdas).
