### ISSUE TITLE
Disallow Repeated Class Constraints (in classes)

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1753]
The following program should be rejected (in the Weeder?):

```
class MyClass[c] extends Eq[c], Order[c], Eq[c]  {

}
```

because the constraint `Eq[c]` is repeated. 

I think this can be an easy syntactic check as long as we have only single param TCs.

**Comment by mlutze** [comment]
Do we want to check more generally for redundant constraints? E.g. `Order[c]` implies `Eq[c]` so you can't have both.

**Comment by magnus-madsen** [comment]
I guess so, one could be an early syntactic check and the other could be a later check, maybe in instances?

**Comment by mlutze** [comment]
I think with the possibility of fully-qualified and unqualified names intersecting, this needs to be done after resolution.

**Comment by magnus-madsen** [comment]
> 
> 
> I think with the possibility of fully-qualified and unqualified names intersecting, this needs to be done after resolution.

Can you give an example?

**Comment by magnus-madsen** [comment]
Would you then move it to the redundancy phase instead?

**Comment by mlutze** [comment]
> Can you give an example?

```flix
namespace N {
  class C[a]
  
  class D[a] with C[a], N.C[a]
}
```

We don't know that `C[a]` and `N.C[a]` are the same until resolution happens (I think).

> Would you then move it to the redundancy phase instead?

I think redundancy makes sense because:
* We can check for trivial and non-trivial redundancy at the same time.
* This really is a redundancy problem rather than something that affects semantics (unlike e.g. duplicate formal param)

**Comment by magnus-madsen** [comment]
This sounds good 👍
