### ISSUE TITLE
Law Syntax

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1759]
Proposed syntactic sugar:

```
class Order[a] with Eq[a] {

    law reflexivity: forall(x: a). x == x

    law antiSymmetry: forall(x: a, y: a). (x <= y and y <= x) `implies` x == y

    law transitivity: forall(x: a, y: a, z: a). (x <= y and y <= z) `implies` x <= z

     // approximately equivalent to
    def reflexivity(): a -> Bool = x == x
    // ...

}
```

**Comment by mlutze** [comment]
Is there any reason to allow:
1. Empty `forall`?
2. Type constraints?
3. Explicit type params?
4. Existential quantification?

**Comment by mlutze** [comment]
What should we do about the existing parametric laws? (monotone, etc.)

**Comment by magnus-madsen** [comment]
> What should we do about the existing parametric laws? (monotone, etc.)

Lets comment all of that stuff for now.

**Comment by magnus-madsen** [comment]
I agree that the current solution looks the best.

But the comment about "top-level defs" is not accurate, because we use the term top-level def for defs in the root namespace (in many other contexts). Can you come up with a different term and update the comments?

Sorry to be such a pain!
