### ISSUE TITLE
Warnings as errors

### ISSUE THREAD

**Issue by mhyee** [flix/flix#176]
Moving the discussion onto GitHub:

On Fri, Jun 24, 2016 at 12:33 PM, Magnus Madsen <...> wrote:
> Hi,
> 
> I am thinking about turning on -Xfatal-warnings which prevents the code
> from compiling if there are warnings (e.g. pattern matching warnings).
> 
> How do you guys feel about this?
> 
> -- Magnus

**Comment by magnus-madsen** [comment]
Turns out this crashes the Scala compiler :D

So we won't do it!

**Comment by mhyee** [comment]
In general, I'm fine with this, but two comments:

1. We have a lot of warnings, something like hundreds of warnings. If I remember correctly, these are deprecation warnings.

2. I've configured SBT (and hence IntelliJ, if you import from an SBT project) to compile with `-unchecked` and `-deprecation`, since those warnings are suppressed by default. We should also use `-feature`.

But if it crashes the compiler (why?), then yeah, we shouldn't do this.

But it should still be a goal to minimize the number of warnings we get.
