### ISSUE TITLE
Monomorph should reject programs with free type variables

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1761]
We have had so many problems with free type variables (i.e. when an expression is under-constrained such as `Nil == Nil` or the like). Currently Monomorphization replaces such variables with `Unit` but this has its own set of problems. Instead, I think Monomorph should emit an error when it encounters a type variable that is not be instantiated. `E.g. "ambiguous type, please add a type ascription". This means that Monomorph now has to return Validations.

I wondered if this can take place before Monomorph, but I don't think so.

**Comment by magnus-madsen** [comment]
This may cause problems for our type level Booleans, but then we can deal with that separately.

**Comment by JonathanStarup** [comment]
Currently at least it is AnyType instead of Unit
