### ISSUE TITLE
Scope of Defs/Laws inside type classes should include the members of the class

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1764]
For example, this program should work:

```
pub class C[a] {
    def foo(x: a): a

    law bar(): a -> Bool = x -> foo(x) == x
}
```

**Comment by mlutze** [comment]
To be clear, we also want to be able to use class `C` from inside without fully qualifying it, and for this also to be the case for instances, right?

**Comment by magnus-madsen** [comment]
> 
> 
> To be clear, we also want to be able to use class `C` from inside without fully qualifying it, and for this also to be the case for instances, right?

I think so yes, why not?
