### ISSUE TITLE
Type Classes MVP

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1767]
Type Classes "1.0" (MVP)

- All currently open tickets.
- Types, kinds, and signatures. 
- Standard Library extended with common classes and instances.

Type Classes "2.0"

- Add (limited) support for overlapping instances.
- Explore if signatures should be inherited (e.g. `Monad.map`).
- Add support for instances on records and schemas.

Type Classes "3.0"

- Explore how to generate instances automatically.
  - Compiler magic?
  - Macros?
- Explore whether we can support instances on type-level Booleans.

**Comment by mlutze** [comment]
When do we expect the "Great Renaming" to happen? I think we've discussed `class -> trait`, `instance -> impl`, and maybe `superclass -> trait constraint`, and perhaps others?

**Comment by magnus-madsen** [comment]
> When do we expect the "Great Renaming" to happen? I think we've discussed `class -> trait`, `instance -> impl`, and maybe `superclass -> trait constraint`, and perhaps others?

For 1.0 for sure, but I think I would like defer it to the end. (I am hoping that four things will be ready in the summer: type classes, new datalog engine, new backend, and updated documentation to go along with it).

But for these specific renamings, I am still less sure what is the right thing to do. 

However, I would like to see this:

https://github.com/flix/flix/issues/1492#issuecomment-789936993

happen soon
