### ISSUE TITLE
Record runtime structure

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1776]
It seems that the record structure is linear at runtime:
https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/jvm/GenRecordExtend.scala#L48

Meaning that the lookup time for a field is O(n). Could we use a tree or something to improve this?

**Comment by magnus-madsen** [comment]
Its difficult with scoped labels, but maybe.

**Comment by magnus-madsen** [comment]
There is no ready fix. While our current solution is O-bad, it might be O-kay because there is little overhead compared to trying to maintain a hash table or tree. Let us wait until someone complains and then we can revisit.

**Comment by magnus-madsen** [comment]
This also goes to the core of whether we really want extensible records or something more like MLSub.
