### ISSUE TITLE
Integration with Travis CI

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#178]
We now have preliminary integration with Travis CI. We can automatically compile and run the tests. 

The only issue is that we use more than 3 GBs of memory for the tests, thus the testing phase frequently fails. One reason for this is due to some space leaks. Other reasons are just the fact that we use a lot of memory.

**Comment by mhyee** [comment]
Is it because we're running tests in parallel? Is there a specific test suite (e.g. TestBackend) that consumes a lot of memory?

**Comment by magnus-madsen** [comment]
Unfortunately travis can only tell me that the process is killed and the most common reason for this is due to resource exhaustion. Furthermore, it seems to abort at arbitrary times near the end of the test suite (TestExamples) which lead me to believe memory issues.

The test are not run in parallel.

**Comment by mhyee** [comment]
Is it possible (or worth it) to run the tests locally and see? Or configure Travis to run a subset of the tests?

Or is it just running the entire test suite?

I guess what I'm really asking is "Can we do anything in the short term to get Travis working, or do we have to wait until we implement our memory optimizations?" After all, without optimizations, I'd expect memory consumption to increase, as we add more phases and complexity.

**Comment by magnus-madsen** [comment]
> Is it possible (or worth it) to run the tests locally and see?

That works. Whether parallel or not. The only time the tests or compilation fails, is if you give it the default of 128mb memory, which is just too little for scalac and us.

> Or configure Travis to run a subset of the tests?

I think I will do that next.

Not memory optimizations, leaks! E.g. we would cache tagged values across different instances of Flix!

**Comment by magnus-madsen** [comment]
It works 100% on plg2 with a clean checkout. 

```
     [java] Run completed in 31 seconds, 71 milliseconds.
     [java] Total number of tests run: 1104
     [java] Suites: completed 11, aborted 0
     [java] Tests: succeeded 1104, failed 0, canceled 0, ignored 71, pending 0
     [java] All tests passed.

BUILD SUCCESSFUL
Total time: 2 minutes 40 seconds
```

**Comment by magnus-madsen** [comment]
On plg2 I saw it use 3744 megabytes which is more than travis offers (3 GB afaik). 

Not sure why we need almost 4GB memory though?

**Comment by magnus-madsen** [comment]
I looked in the debugger, but I don't see what should cause this. The memory usage appears reasonable.

**Comment by magnus-madsen** [comment]
I just successfully ran `TestExamples` with `-Xmx128m` so I don't know what the problem is.

**Comment by magnus-madsen** [comment]
Also works for `TestAll`. hmmm.

**Comment by sirinath** [comment]
Also can you add https://gitter.im/ and http://groups.io/ also?

**Comment by magnus-madsen** [comment]
This bug seems to be related to the use of `CheckClassAdapter` #188. Hopefully once that is resolved, we will be able to resolve this one.

**Comment by magnus-madsen** [comment]
We are now in the bizarre situation where travis-ci works, and circle-ci does not.

**Comment by magnus-madsen** [comment]
I suspect that compilation of Flix may now (sometimes) require more than 3-4GB memory!

**Comment by magnus-madsen** [comment]
I was finally able to fix this issue. The build script was forking scalac which (for unknown reasons) causes a huge increase in memory usage. Without forking scalac we use around 1.5-2GB which should be fine for now, but may become a problem in the future.
