### ISSUE TITLE
Syntactic Kind Inference

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1791]
**Enums**: The following rules apply, either:
- All type variables are explicitly ascribed with a kind, *or*
- All type variables are assumed to be of kind `Star`.
- (It is illegal for only a subset of type variables to be ascribed.)
- (EDIT: Must check that kinds fit with their use within the enum).

**Type Aliases**: The following rules apply, either:
- All type variables are explicitly ascribed with a kind, *or*
- All type variables are assumed to be of kind `Star`.
- (It is illegal for only a subset of type variables to be ascribed.)
- (EDIT: Must check that kinds fit with their use within the enum).

**Type Classes**: The following rules apply, either:
- The single type variable is explicitly ascribed with a kind, *or*
- The single type variable is assumed to be of kind `Star`.
- (It is illegal for only a subset of type variables to be ascribed.)
- (EDIT: Must check that kinds fit with their use within the enum).

**Type Class Instances**: The following rules apply:
- The kinds are always derived from the kinds of the classes (Must happen after classes have been "kinded".)

**Defs**: The following rules apply, either:
- Explicit mode: All type variables are explicitly ascribed with a kind, *or*
- Implicit mode: The following syntactic rules apply. Given a type, recursively determine the type of every type variable:
  - If the type variable appears as an argument to an enum use its kind.
  - If the type variable appears as an argument to type alias use its kind.
  - If the type variable appears as an argument to type class use its kind.
  - Otherwise, consider:
    - If in a type position => type 
    - If in an effect position => boolean (e.g. on an arrow)
    - If in a record/schema position => record/schema
    - If in a Boolean position => boolean
  - If these constraints are inconsistent => error.

These rules are pretty inflexible, but they could be relaxed later.

What constructs am I missing? Laws?

Question: When should ill-kinded types be reported? During kind inference or in type inference?

**Comment by magnus-madsen** [comment]
@mlutze A first attempt.

I don't know how well these rules fit with our current architecture. You could be tempted to add a new phase or (allow kinds to be mutated on type variables...)

**Comment by magnus-madsen** [comment]
The idea is that all of the above should be computed *before* type checking. Then type inference is given two inputs: The expressions and their type annotations and its job is to *check* that the annotations are consistent with the inferred types.

**Comment by magnus-madsen** [comment]
The overall point being that type signatures are just that: A complete signature of an expression (including its kinds).

**Comment by mlutze** [comment]
An additional rule per recent discussions:

In a type application where the constructor is a variable, all arguments are assumed to have kind `Type`.
I believe that this weakens the inference to the point that unification is no longer needed.

```scala
def(x: m[Pure]): Int = ???
// m: Type -> Type
// Kind Error: Pure is kind Bool but Type was expected

def (x: m[a]): Int = ???
// m: Type -> Type
// a: Type

def (x: m[a]): Int & a = ???
// m: Type -> Type
// Kind Error: a is kind Type but Bool was expected
```

**Comment by mlutze** [comment]
I think it also means that we can deal with the subkinding question later

**Comment by magnus-madsen** [comment]
By the way, would it make sense to introduce the Kinder where it deals with everything but the signatures of defs? As an intermediate step.

**Comment by mlutze** [comment]
Since things are fairly interconnected (defs may depend on instances, instances depend on classes) I'm now thinking it may be best to keep it all together.
