### ISSUE TITLE
Libraries for Analysis, Optimisation, Code Generation in Different AST formats 

### ISSUE THREAD

**Issue by sirinath** [flix/flix#181]
Pre defined framework for analysis AST formats:
- [ ] Scala / TASTY
- [ ] [Nitra](https://github.com/rsdn/nitra)
- [ ] [Truffle](https://github.com/graalvm/truffle)
- [ ] [ROSE IR](https://en.wikipedia.org/wiki/ROSE_(compiler_framework))
- [ ] Clang AST

So you do not have to write them from scratch. Also integrate with the relevant tools.

**Comment by magnus-madsen** [comment]
We already have implemented a full compiler for Flix, but using TASTY as an intermediate format may be of some interest in the future. Right now we compile straight to JVM bytecode.

**Comment by sirinath** [comment]
I am not saying use TASTY as a IM format. What I am really looking for is libraries to analyze other languages and transpile. Say I have C# Library which I want to convert to Scala. Best way would be to generate a TASTY representation of the .net IL. Likewise C# to Java transpiling. With regard to optimisations you can take java class files or any other format and do more optimisations using Flix to generate more optimal output format also.

Perhaps you can use TASTY as an intermediate format for Flix also in which case you can have better Scala interop but I would think Nitra format might end up better though this is not in the JVM or perhaps you can target multiple formats.
