### ISSUE TITLE
Possible Bug In LSP Indexer

### ISSUE THREAD

**Issue by justinfargnoli** [flix/flix#1813]
https://github.com/flix/flix/blob/2a8cdf9bc38efee760e822d7185682d2146db7eb/main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala#L301

@magnus-madsen I think this line of code may be incorrect and that the following is what was intended.
```
index ++ Index.occurrenceOf(sym, sym.tvar) ++ visitExp(chan) ++ visitExp(body)
```
Is that correct?

**Comment by magnus-madsen** [comment]
Yes, this is definitely a bug :)
