### ISSUE TITLE
Byte Code, Bit Code, CIL, IL, IR, Native Code/Machine Code Analysis, Re Optimisation, Transpiling

### ISSUE THREAD

**Issue by sirinath** [flix/flix#182]
Is it possibile to add ability to analyse existing binary code drive a AST representation in some of the common formats (https://github.com/flix/flix/issues/181) so this code can be further optimised or traspiled to other fomats. Since some libraries may be GLP+exception or LGPL, ability to specify, what dependencies of the program is to be dynamic and static. Also integration with relevant tool chain natively.

**Comment by magnus-madsen** [comment]
If I understand the question correctly, it is whether we could have different front-ends for Flix.

I think this is currently beyond the scope of Flix. Ideally you would write your analysis in Flix and then integrate it with a source code parser/bytecode parser, etc. that would provide the facts directly to Flix.

E.g. you could use Esprima (for JavaScript) to generate the input facts, or you could use Soot for Java to generate the input facts.

**Comment by sirinath** [comment]
I was thinking both frontend and backend frameworks with also integrations to existing tool chains.
