### ISSUE TITLE
Missing Instance without source location

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1825]
I sometimes now see this:

![image](https://user-images.githubusercontent.com/2287953/112732518-b572b200-8f3a-11eb-9878-500baada0f24.png)

**Comment by mlutze** [comment]
Can you post the Flix code causing this?

**Comment by magnus-madsen** [comment]
Not really (its a lot WIP code), but I can try to look for a smaller example.

I think it happens when the TC constraints does not match the signature itself.

**Comment by magnus-madsen** [comment]
Smallish example I can across:

```


class Ring[t] with Eq[t] {
    pub def add(x: t, y: t): t

    pub def mul(x: t, y: t): t

    law distributivity: forall(x: t, y: t, z: t). Ring.mul(Ring.add(x, y), z) == Ring.add(Ring.mul(x, y), Ring.mul(y, z))
}


pub def double[t](x: t): t with Ring[t] = Ring.mul(x, x)


instance Ring[Int32] {
    pub def add(x: Int32, y: Int32): Int32 = x + y

    pub def mul(x: Int32, y: Int32): Int32 = x * y
}

instance Ring[(a, b)] with Ring[a], Ring[b] {
    pub def add(x: (a, b), y: (a, b)): (a, b) = (fst(x) `Ring.add` fst(y), snd(x) `Ring.add` snd(y))

    pub def mul(x: (a, b), y: (a, b)): (a, b) = (fst(x) `Ring.mul` fst(y), snd(x) `Ring.mul` snd(y))
}

pub def main(_: Array[String]): Int32 & Impure =
    println(double(123));
    println(double((2.2, 3.5)));
    0
```

**Comment by magnus-madsen** [comment]
![image](https://user-images.githubusercontent.com/2287953/113041331-1ea43080-919a-11eb-94c2-24c5b27c4f25.png)

**Comment by mlutze** [comment]
I'm guessing this is because `Ring[Float64]` is an "indirect" constraint for the expression (entailed by the tuple constraint). Can probably be solved by transferring the location to entailed constraints when doing checks in `ClassEnvironment`. I'll address this as part of https://github.com/flix/flix/pull/1826
