### ISSUE TITLE
Type classes and Boolean Unification

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1842]
The instance selection method assumes that, for any signature symbol and type scheme, there is only one instance with a definition that matches it. For typical types, this is achieved by:
1. Requiring instance types to be "simple", i.e. a type constructor applied to zero or more type variables
2. Disallowing overlap of instances: no two instances of the same class may have types that unify with each other
3. Requiring signatures to include the class type variable

For type-level booleans, these are not enough to distinguish instances.

```scala
lawless class C[a: Bool] {
  pub def f(): String & a or not a
}

instance C[Pure] {
  pub def f(): String = "I'm pure"
}

instance C[Impure] {
  pub def f(): String = "I'm also pure"
}

pub def g(): String = C.f()
```

This gives a cryptic error about type generalization, but the actual cause is that both `C[Pure]` and `C[Impure]` have the same type scheme for `f()`.

**Comment by mlutze** [comment]
I guess an easy fix would be to verify that, for boolean types, instantiating the type schemes with `Pure` and `Impure` will actually result in different types.

**Comment by magnus-madsen** [comment]
Thanks for posting this; I will think more deeply about its consequences.

**Comment by magnus-madsen** [comment]
I think we should go to https://github.com/flix/flix/issues/2689 and no further.
