### ISSUE TITLE
User-defined kinds

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1843]
Currently, the set of kinds is finite and predefined. (with the exception of arrow kinds). This allows for potentially non-kind-safe definitions:

Suppose we have colored boxes, and we use a phantom type because we're only allowed to unpack red boxes. I think the simplest way to do that currently in Flix is like this:

```scala
enum Red {}
enum Yellow {}
enum Blue {}

opaque type Box[a: Type, c: Type] = a

def unpackRedBox(box: Box[a, Red]): a = match box {
  case Box(contents) => contents
}

def unpackIntBox(box: Box[a, Int]): a = match box { // Compiles, even though boxes should only have colors and not numbers
  case Box(contents) => contents
}
```

But that allows us do create nonsensical definitions. With user-defined kinds, we can be more restrictive in what sorts of definitions are allowed.

```scala
kind enum Color {
  case Red
  case Yellow
  case Blue
}

opaque type Box[a: Type, c: Color] = a

def unpackRedBox(box: Box[a, Red]): a = match box {
  case Box(contents) => contents
}

def unpackIntBox(box: Box[a, Int]): a = match box { // Kind error! Int does not have kind Color
  case Box(contents) => contents
}
```

I would guess that there are other useful applications as well.

**Comment by magnus-madsen** [comment]
I think user-defined kinds are a niche feature. We can revisit in the future.
