### ISSUE TITLE
Decide on naming principles for standard library.

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1848]
This signature:

```
pub def get(k: k, m: Map[k, v]): Option[v]
```

seems reasonable. We have a variable `k` of type `k`.

But the above signature:

```
pub def memberOf(x: a, a: Array[a]): Bool
```

looks confusing to me. (I mean, I understand it, but it seems like bad style). The problem is that `a` is an array but `a` is also the type of the array elements. This seems pretty inconsistent.

_Originally posted by @magnus-madsen in https://github.com/flix/flix/pull/1834#discussion_r605607199_

**Comment by mlutze** [comment]
(Duplicate)

**Comment by magnus-madsen** [comment]
Actually this ticket has a better description than #1847

**Comment by magnus-madsen** [comment]
(Tracked in other ticket)
