### ISSUE TITLE
Debate: `List.join`, `List.joinWith`, and `List.formatWith`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1849]
If I have a `List[a]` with `ToString[a]` how do I get a string where the elements of the list a separated by ","?

**Comment by magnus-madsen** [comment]
Looking through our APIs we have many functions that seem very close, but I can't actually find anything that gets the job done.

@mlutze @stephentetley Do we already have such a function? If not, what should it be called and where should it belong?

`String.intercalate` and `String.intercalateChar` are really close, but not close enough. Should either be modified? Or does this belong on `Foldable?

**Comment by mlutze** [comment]
I don't think we currently have such a function.

IMO it makes the most sense to put it in the `Foldable` (or some collection-ish) class, since if there are special optimizations that could be done, it seems that they would come from the collection type rather than the element type, and that seems to be a decent heuristic for guiding where we should place functions in general. Thoughts?

As for a name, Scala's `mkString` comes to mind.

**Comment by stephentetley** [comment]
I don't think we already have a List.join.

Now we have typeclasses for ToString, Eq and Order there are other improvements to make to the standard libraries. Particularly we can now have `sort` for common cases (with  Order) when before we had to use `sortWith`.

**Comment by esbenbjerre** [comment]
I've previously used `List.formatWith` for this.

**Comment by magnus-madsen** [comment]
> 
> 
> I've previously used `List.formatWith` for this.

This one is also close, but its not quite there either!  How interesting. So many combinators but not the right one.

**Comment by magnus-madsen** [comment]
```
class Foldable[f: Type -> Type] {
  def join(s: String, f: f[a]): String with ToString[a]
}
```

And I guess we could have a specialized version in `List` so it is findable:

```
namespace List {
  def join(s: String, l: List[a]): String with ToString[a]
}
```

One question is if we should have `join` and `joinWith`?

**Comment by mlutze** [comment]
> One question is if we should have `join` and `joinWith`?

I think we could generalize this question to something like "When should we have a `*With` function to allow replacing a type constraint with a function doing the same thing?". And then maybe get a standard library principle out of it.

**Comment by magnus-madsen** [comment]
> 
> 
> > One question is if we should have `join` and `joinWith`?
> 
> I think we could generalize this question to something like "When should we have a `*With` function to allow replacing a type constraint with a function doing the same thing?". And then maybe get a standard library principle out of it.

Good idea.. With can mean different things do (just look at Map).

Also, I am not sure about @stephentetley comment about sortWith. Is this so you can specify your own ordering- different from `Order.compare`?

**Comment by stephentetley** [comment]
For sorting we can now add a function `sort` that takes advantage of the `Order` typeclass: 

> def sort[a](xs: List[a]): List[a] with Order[a]

We would still want to keep `sortWith` but ideally change `cmp` so it returns a `Comparison` rather than a Java style int (-1, 0, 1).

> def sortWith[a](cmp: a -> a -> Comparison, xs: List[a]): List[a]

**Comment by magnus-madsen** [comment]
A would like to start with the following minimal approach.

Add the following to `String.flix`:

```
def joinWith(s: String, f: f): String with Foldable[f] = ...
```

Example use:

```
Set#{1, 2, 3} |> String.joinWith(" , ")
```

**Comment by magnus-madsen** [comment]
@felixwiemuth Maybe you could look at this? :)

**Comment by felixwiemuth** [comment]
Sure :)

Regarding `sort` and `sortWith` see #1945.

### Making a `String` out of a `Foldable[a]` with `ToString[a]`
The way for strings with `String.formatWith` is already quite concise I'd say: `String.formatWith(ToString.toString, ",", myList)`. The good thing is also that it does not *require* a `ToString` instance, but it can easily be used.

First of all I would say that `formatWith` should move to `Foldable` (the current implementation uses `foldRight` anyway). Then there can be a shortcut in the `List` namespace and maybe a specialized `String.joinWith` defined as `Foldable.formatWith(ToString.toString)` (i.e., partially applies `formatWith`). Of course one could always use `Foldable.toList` and then `List.formatWith`, but that would be a performance disadvantage if it is not lazy.

While we are at it, I would define `String.join` as `String.joinWith("")`, so this will just concatenate all elements converted to a string. The `ToString` instance of `List` can then by the way also be define in terms of `joinWith`: `concat(joinWith(" :: ", myList), " :: Nil")` (but maybe shouldn't).

#### Other places for `joinWith`
I wonder whether `String` is actually the right place for `joinWith` and `join`. Also regarding that `formatWith` which it is based on would be part of `Foldable`.

##### Part of `ToString`
`joinWith`/`join` could be part of the `ToString` class (or maybe better namespace). This would avoid the dependency of `String` on `ToString`, and `ToString` depends on `String` anyway (surprise!). It would add `Foldable` as a dependency to `ToString` though. (Not that these dependencies would be important, but it could be taken as a hint where things "belong".)

##### Part of `Foldable`
Here the advantage would be that `joinWith`/`join` could be called directly on any `Foldable` (that also has `ToString`), i.e., when the explicit typeclass/namespace prefixes fall apart, one can just do `join` without any prefix and maybe without additional imports (not sure whether `Foldable` would have to be imported). I'm not sure whether Flix supports constraints for single type class functions that are stricter than what the type class requires (here we need `ToString`?

#### All in all
Probably there are good arguments for each variant and I just wanted to name them once. More important is the relation to and generality of `formatWith` I'd say.

**Comment by magnus-madsen** [comment]
Thanks for the writeup! My brain is processing it. Ill reply in detail, but I agree with the overall points.

**Comment by magnus-madsen** [comment]
Quick remark: If String implemented Foldable then join is a form of intersperse. (But I *don't* think String should be foldable- thats a can of worms.)

**Comment by magnus-madsen** [comment]
OK, I propose the following concrete tasks:

### Part A:

- [ ] Add `Foldable.joinWith(s: String, f: f[a]): String with Foldable[f], ToString[a] = `
- [ ] Add `Foldable.join` which calls `joinWith` with the seperator ", ".

(Note I demand that `sep` is a String.)

Following the principle of a layered design, we should also add `join` and `joinWith` to:

- [ ] `Array`
- [ ] `Nel`
- [ ] `List` / `MutList`
- [ ] `Set` / `MutSet`
- [ ] `Map` / `MutMap`
- [ ] `String`
- [ ] (`Iterator`, `LazyList`) - eventually

### Part B:

- [ ] Add `Foldable.formatWith(f: a -> b, sep: String, f: f) with Foldable[f], ToString[b]`

(Note I demand that `sep` is a String.)

Following the principle of a layered design, we should also add `formatWith` to:

- [ ] `Array`
- [ ] `Nel`
- [ ] `List` / `MutList`
- [ ] `Set` / `MutSet`
- [ ] `Map` / `MutMap`
- [ ] `String`
- [ ] (`Iterator`, `LazyList`) - eventually

**Comment by mobotsar** [comment]
@magnus-madsen
Neither Map/MutMap nor String appears to be an instance Foldable at this time, which would seem to preclude them from making use of Foldable.joinWith in a truly layered fashion. Do you intend for these to be instances of Foldable? I know that in the past you were averse to the idea of doing so for String, but if something's changed I would love to hear your rationale.

My understanding of the proposed function in Foldable is for it to behave essentially like this (ofc a more efficient implementation is probably in order)
```
pub def joinWith(sep: String, es: t[a]): String with ToString[a] =
        let el = Foldable.toList(es);
        let sl = List.map(ToString.toString, el);
        String.intercalate(sep, sl)
```
with specializations for e.g. Array of the form `pub def joinWith(sep: String, a: Array[a]): String with ToString[a] = Foldable.joinWith(sep, a)`.

**Comment by mlutze** [comment]
With the current type class design, it's not possible to have Foldable instances for Map and String. Roughly speaking, this is because the Foldable type class works with types that have exactly one type parameter. `Map[k, v]` has 2, and `String` has 0.

**Comment by magnus-madsen** [comment]
@mobotsar I think that: (1) Foldable.join/joinWith offers a generic implementation , whereas (2) the versions in each namespace is more specialized, e.g. List.joinWith with use an implementation different from Array.joinWith and so forth.

**Comment by magnus-madsen** [comment]
In other words, an implementation inside `List.join/List.joinWith` should not necessarily call `Foldable.join/joinWith`. 

(Its a bit confusing - I know - we still have quite figured out where everything should go).

**Comment by mobotsar** [comment]
@magnus-madsen
That makes sense to me; different optimizations for different collections, etc etc. I'm just going to sure the interfaces are there and that I'm happy with them before moving on to proper implementations of the join/format functions.

**Comment by mobotsar** [comment]
I do have a some concerns about the fact that existing `formatWith` functions seem to have a different signature from the one proposed here --  `fn` is of type `a -> String` instead of `a -> b` `with ToString[b]`.

Actually, I have concerns about the use of the latter signature in formatWith at all. `a -> b` `with ToString[b]` is technically more flexible, but I feel that it damages the semantics of foldWith significantly when compared to the former.

Take the following `Fodlable.formatWith` function (the terrible implementation is for illustrative purposes).
```
pub def formatWith(fn: a -> b, sep: String, f: t[a]): String with ToString[b] =
        Foldable.toList(f) |> List.map(fn) |> List.map(ToString.toString) |> String.intercalate(sep)
```
and the alternative
```
pub def formatWith(fn: a -> String, sep: String, f: t[a]): String =
        Foldable.toList(f) |> List.map(fn) |> String.intercalate(sep)
```
Conceptually, `fn` is a function that specifies how to display an element of type `a`. Only strings can be displayed is this context, so logically `fn` must return a string. Passing an `fn` with a return type other than `String` violates that intuition, and semantically changes `fn` from a formatting function to a general mapping function. In doing so, it changes `formatWith` into a weird map/fold hybrid that _isn't necessarily doing any formatting_ (instead leaving it up to a default `toString` on type `a`). This behavior doesn't mesh with the idea that `formatWith` is, in fact, a formatting function.

I think that if a user of Flix is constrained in some way such that they want to do mapping with `formatWith` instead of just mapping and passing the result to `formatWith` (and I stress that this use case seems likely to be very uncommon), then they can just trivially compose `ToString.toString` with their function and be done with it.

Finally, it seems eminently probable that the common case of `formatWith` is with an `fn` of type `a -> String`, and the notion of the _common case_ calling `toString` on a `String` for every element of the passed collection is unsettling to me.

**Comment by magnus-madsen** [comment]
@mobotsar You have convinced me, let us go with `a -> String`!

**Comment by mobotsar** [comment]
Something to be noted: `Array.formatWith` is currently of an impure type. That seems unnecessary, and so in my fork I've purified it. Posting here to hear any objections.

**Comment by mlutze** [comment]
The argument against making `Array.formatWith` pure is that the array is mutable, so two identical calls could produce different results.

**Comment by magnus-madsen** [comment]
Its a tricky business, and it has not yet been done fully correct through out the compiler, but in essence everything that touches something mutable should be impure.

**Comment by mobotsar** [comment]
Aye, so it is. I'll revert.

**Comment by mobotsar** [comment]
That does make me wonder, though, if `Foldable.formatWith`, or in fact every function in `Foldable`, should be impure, since any one might be called on a mutable collection.

I have a couple ideas for how to handle this, but it seems like something best figured out by experts, which I'm not.

**Comment by magnus-madsen** [comment]
> 
> 
> That does make me wonder, though, if `Foldable.formatWith`, or in fact every function in `Foldable`, should be impure, since any one might be called on a mutable collection.
> 
> I have a couple ideas for how to handle this, but it seems like something best figured out by experts, which I'm not.

Most collections are pure. More likely, in the future, there could be another FoldableMut type class for mutable stuff and/or a notion of frozen/borrow mutable data structures. In either case, it is the mutable collections that are current treated separately and sometimes not eligible to be member of a type class.

**Comment by magnus-madsen** [comment]
Fixed in master.
