### ISSUE TITLE
Idiomatic use of toString

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1850]
Is this idiomatic Flix:

```
    instance ToString[BodyTerm[v]] with ToString[v] {
        pub def toString(term: BodyTerm[v]): String = match term {
            case BodyTerm.Var(varSym, _) => ToString.toString(varSym)
            case BodyTerm.Lit(v, _) => ToString.toString(v)
            case BodyTerm.Wild(_) => "_"
        }
    }
```

or should it actually be:

```
    instance ToString[BodyTerm[v]] with ToString[v] {
        pub def toString(term: BodyTerm[v]): String = match term {
            case BodyTerm.Var(varSym, _) => "${varSym}"
            case BodyTerm.Lit(v, _) => "${v}"
            case BodyTerm.Wild(_) => "_"
        }
    }
```

or something else?

**Comment by mlutze** [comment]
One consideration in favor of option 1 is that it's a little more typo-proof. `ToString.toString(varSym )` (extra space) still produces the same result, whereas `"${varSym} "` (extra space) actually changes the output.

So IMO if you just want to convert something to a string, use `toString`. If more formatting is needed, then interpolation.

**Comment by magnus-madsen** [comment]
It is just that `ToString.toString` may look pretty confusing to a beginner, i.e. someone who wants to write a small program, but has not yet grasped type classes.

**Comment by mlutze** [comment]
What if `toString` (or a forwarding function) goes in Prelude?

**Comment by magnus-madsen** [comment]
> 
> 
> What if `toString` (or a forwarding function) goes in Prelude?

We could. It might be the "least offensive solution". 

But then people might still complain: Which is the right way to do it?

**Comment by magnus-madsen** [comment]
I think we should permit both with a recommendation to use string interpolation when building more complex strings.
