### ISSUE TITLE
Datalog Quasi Expressions

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1852]
For first-class Datalog constraints, we have the syntax:

```
#{ ... Datalog Constraints ... }
```

which works well.

Then we have the following quasi expressions:

- `solve e`
- `project P e`
- `facts P e`
- `|=`
- `fold e e e` (now removed)

which, like Datalog literals, requires compiler support.

When I look at these expressions, I have two concerns:

- The syntax is very irregular.
- The choice of commands seems pretty limited and very ad-hoc. (Why is `facts` a keyword but `|=` an operator?)

What I would like to do is:

- Introduce a new syntactic construct where you can write these Datalog operations.
- Introduce a broader set of useful operations.

Note: The operations would still be expressions.

Function-like:
```
solve#(e1, [e, ..., e])
union#(e1, e2, [e, ..., e])
facts#(P, e1, [e, ..., e])
isSubsetOf#(e1, e2)
toString#(e1, [e, ..., e])
```

I feel like the functional approach is the most powerful *when you can write combinators* (but that is not case here, since we have to hardcode these into the compiler). This suggests a more literate approach:

Literate I:
```
select (a, b, c) from Foo(a), Qux(b, c) in solve e [e, ..., e]
```
This would return an array of triples of the expected type.

- Note that with functions this would require something like `facts#(Result, solve#(#{ Result(a, b, c) :- ...} <+> e <+> .. e))`
- Note that `select` is already used for channels. We can use it here, but it might be confusing to the programmer.)
- What about operations such as `project`, `union`, `isSubset` and `toString` would they remain functions?

Literate II:
```
solve e [e, ..., e] from Foo(a), Qux(b, c) select (a, b, c)
```

Literate III:
```
solve e [e, ..., e] select (a, b, c) :- Foo(a), Qux(b, c).
```

Another question is whether the query should come before the program. E.g.  which would you rather see:

```
def main(...): ... = 
  solve #{
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
  } from Foo(a), Qux(b, c) select (a, b, c)
```

or

```
def main(...): ... = 
  from Foo(a), Qux(b, c) select (a, b, c) in solve #{
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
  } 
```

Thoughts on how to improve this?

NB: It would be so much better if we could just treat Datalog values like e.g. `List` and implement e.g. `Functor` but this is an open research problem (scoped labels + first-class labels), so that's beyond the scope of this ticket.

**Comment by magnus-madsen** [comment]
@bdahse @stephentetley @mlutze @JonathanStarup  Thoughts?

**Comment by stephentetley** [comment]
I really like the syntax suggestions as they adopt quite a "query comprehension" style. 

That said, I have an initial reservation as I think `select` in Flix master's Datalog is a more powerful than query comprehensions - though I'm certainly not an expert on them. 

For example in the current program I'm working on `solve` generates three _answer sets_ - one is essentially "entities" and I expect one entity for each line in the input worklist. But, I also generate "descriptions" - an entity may have a description but often it doesn't so the answer set usually has fewer results than than entity answers. Also entities have "attributes" - typically 10-15 of them, so the size of the attributes answer set is much larger than the set of entities. With `select` I can extract each answer set out of the solution and process them how I like.

I might be me misunderstanding query comprehensions - I've studied them but never written one - but because the answer is a list of tuples (the Cartesian product?) I wouldn't know how to extract these three answer sets except by writing and executing the query three times.

**Comment by magnus-madsen** [comment]
> That said, I have an initial reservation as I think `select` in Flix master's Datalog is a more powerful than query comprehensions - though I'm certainly not an expert on them.

What do you mean by `select` in Flix master? Do you mean the current `project`?

> For example in the current program I'm working on `solve` generates three _answer sets_ - one is essentially "entities" and I expect one entity for each line in the input worklist. But, I also generate "descriptions" - an entity may have a description but often it doesn't so the answer set usually has fewer results than than entity answers. Also entities have "attributes" - typically 10-15 of them, so the size of the attributes answer set is much larger than the set of entities. With `select` I can extract each answer set out of the solution and process them how I like.

Ok, I think I understand.

> I might be misunderstanding query comprehensions - I've studied them but never written one - but because the answer is a list of tuples (the Cartesian product?) I wouldn't know how to extract these three answer sets except by writing and executing the query three times.

Right, I think what you are pointing out is the following: What if I want to compute the solution to a Datalog program and retrieve say 3 relations (either as Datalog facts or as arrays). In that case, I think something like the following:

```
let m = solve <my program here> project RelationA, RelationB, RelationC
// m is now a Datalog program that contains three relations.
```

or

```
let m = solve <my program here> // note that the program is only solved once
let a1 = query m select (a, b, c) from RelationA(a, b, c)
let a2 = query m select (a, b) from RelationB(a, b)
let a3 = query m select (a, b, c, w) from RelationC(a, b, c, w)

// now a1, a2, and a3 are arrays of tuples.
```

**Comment by magnus-madsen** [comment]
Revised Proposal:

This should be understood as replacing the current operations with the following.

In terms of terminology, we usually say that `#{ ... }` is a constraint set (i.e. a collection of facts and rules that imply more facts). 

Let us call this a *database* (but remember that it also has rules).

First, we introduce a merge operator:

```
merge e1, e2, ...
```

This evaluates `e1`, `e2`, ... and combines their databases (facts and rules) into one. It is like set union. This operator is pretty much like `<+>` but replaces it with a name operator that takes a series of expressions.

Second, we introduce a new `solve` combinator:

```
solve e1, e2, ... [project A, B, ...]
```

This evaluates e1`, `e2`, ... and combines their databases. Then it merges them and computes their fixpoint (set of implies facts). Finally it optionally projects (selects) the given predicate symbols. 

Thus:

```
solve e1, e2, e3 == solve (merge e1, e2, e3)
```

This new solve combines the old `solve` and `project` into one construct. The following is allowed:

```
let m = solve e1, e2;
let aS = solve m project A;
let bS = solve m project B
```

and does not incur much extra overhead since `m` is a fact set and solving it is "free".

So far we can now solve and work with databases, but we lack a way to "extract" facts back into ordinary collects. For example, we will often want to get an array (or list?) of tuples from a relation. In master this can be done with `fold` (which is being removed) and in the current PR it can be done with `facts A e`. This proposes instead to introduce the following:

```
query e1, e2, ... select (e1', e2', ...) from A(...), B(...), ... [where e1 and e2 ...]
```

***The key to remember is: Use `solve` if you want to "stay in the Datalog world". Use `query` if you want to extract tuples. *** (I am open to better names).

The `query` construct works as follows: It evaluates  `e1`, `e2`, ... to databases and merges them (like `solve`). Then it adds a pseudo-rule:

```
$TMP(e1', e2', ...) :- A(...), B(...), ... if e1 and e2
```

and computes the fixpoint. Finally it takes the tuples inside `$TMP` and returns them as an array (or list?).

Note that the where clause is optional. 

Note also that you can perform computations in `e1'` and `e2'`.

Thus the `query` construct replaces `fold` or the newer `facts`.

**Comment by magnus-madsen** [comment]
Example 1:
```ocaml
let edges = #{ ... };
let prog1 = #{
  Path(x, y) :- Edge(x, y).
  Path(x, z) :- Path(x, y), Edge(y, z).
}
let prog2 = #{
  Vertex(x) :- Path(x, _).
  Vertex(y) :- Path(_, y).
  Unconnected(x, y) :- Vertex(x), Vertex(y), not Path(x, y).
};
let paths = solve edges, prog1 project Path
let uncon = solve paths, prog2 project Unconnected
```

Example 2:
```ocaml
let edges = #{ ... };
let prog1 = #{
  Path(x, y) :- Edge(x, y).
  Path(x, z) :- Path(x, y), Edge(y, z).
}
let paths = query edges, prog1 select (a, b) from Path(a, b)
```

Example 3:
```ocaml
let edges = #{ ... };
let prog1 = #{
  Path(x, y) :- Edge(x, y).
  Path(x, z) :- Path(x, y), Edge(y, z).
}
let backAndForth = query edges, prog1 select (a, c) from Path(a, b), Path(b, c), Path(c, a) where a != b and b != c
```

Example 4 (almost like a database):
```ocaml
let p1 = #{ Food("Apple"). Food("Burger"). }
let p2 = #{ Unhealthy("Burger"). }
let eat = query p1, p2 select String.toUpperCase(q) from Food(q), not Unhealthy(q)
// eat = Array["APPLE"]
```

Example 5 (not ideal)
```ocaml
let p = #{ Food("Apple"). Food("Burger"). }
let hasBurger = query p select true from Food("Burger")
// this returns Array[Bool] which is not that great. Can we do better?
```

**Comment by stephentetley** [comment]
This looks good. 

Maybe `evaluate` is a possible alternative name to `query`? 

In my first comment I did mean `project` rather than `select`.

Is Example 5 saying - does `Food("Burger")` exist in database `p`? If so does this point to how we might include aggregates - I don't know what the syntax should be, but suppose we could push an array "summation" function into the query then the return type would the return type of the summation - in this case Bool:

> let hasBurger = query p aggregate Food Array.memberOf("Burger")

`Array.memberOf` is an unusual aggregate function, a more typical one would be `count` (Array.length) with the return type Int32: 

> let pathCount = solve edges, prog1 aggregate Path Array.length

**Comment by stephentetley** [comment]
Replying to myself...

With more thought, aggregates probably don't add some much to Flix (unlike SQL) because Flix always has the functional language available for post-processing:

> let paths = solve edges, prog1 project Path |> Array.length

**Comment by magnus-madsen** [comment]
In the future- aggregation in the Datalog part itself could be useful, but that is beyond the scope of this specific ticket.

**Comment by magnus-madsen** [comment]
I have a preliminary implementation of `solve` and `query`:

```
solve edges, prog1 project Path
```

```
query edges, prog1 select (a, b) from Path(a, b)
```

I have two questions/concerns:

- It don't like the name `query` because it seems to suggest that no fixpoint computation is happening, but that is actually not the case. Both `solve` and `query` do the same; the difference is in the output: One returns a new Datalog program value, the other an array of facts. But they are semantically similar.
- I am a bit concerned about returning an array of tuples. While efficient, arrays are impure, which seems pretty annoying to deal  with. I am thinking of switching to a list (at the cost of performance).

**Comment by magnus-madsen** [comment]
Option 1: Combine `solve` and `query` into one construct. The syntax is sufficient to disambiguate: 

```
solve p1, p2, p3 project Edge, Path             // Returns #{Edge(...), #Path(...)}
solve p1, p2, p3 select (x, y) from Path(x, y)  // returns Array[(...)] or perhaps List[(...)]
```

Option 2: Find a better name for `query`:

![image](https://user-images.githubusercontent.com/2287953/114855882-b46ccc00-9de6-11eb-96ea-1682fa626271.png)

![image](https://user-images.githubusercontent.com/2287953/114855902-bb93da00-9de6-11eb-8e97-587bb668e623.png)

**Comment by magnus-madsen** [comment]
One more issue: It is nice that you can write:

```
query p1, p2 select (src, dst) from Path(src, dst) |> Array.memberOf((1, 10))
```

But now, if you want to insert a `where` clause this does not work:

```
query p1, p2 select (src, dst) from Path(src, dst) where dst >10 |> Array.memberOf((1, 10))
// The above does not work because the where clause eats all of "dst >10 |> Array.memberOf((1, 10))"
```

The following works but is more cumbersome:
```
(query p1, p2 select (src, dst) from Path(src, dst) where dst >10) |> Array.memberOf((1, 10))
```

**Comment by stephentetley** [comment]
It's certainly possible I'm using the wrong syntax for polymorphic constrant sets, but if not, I think I've found a typing bug with the new solver which limits the modularity of embedded Datalog programs. Program 1 compiles and runs whereas program 2 fails with a typing error.

Program 1 - the instantiated database is local to `showCapitals`:

~~~

def main(_args: Array[String]): Int32 & Impure = 
    Console.printLine("Running...");
    showCapitals();
    0

rel WorkItem(name: String, priority: Int32)
rel Capital(city: String, country: String)

def db(): #{WorkItem, Capital | r} = #{
    WorkItem("Order 01", 1).
    Capital("Copenhagen", "Denmark").
    Capital("Paris", "France").
    Capital("Lisbon", "Portugal").
}

def showCapitals(): Unit & Impure =
    let xs = query db() select (x,y) from Capital(x,y) 
                |> Array.toList
                |> List.map(pair -> {city = fst(pair), country = snd(pair)});
    List.foreach(r -> Console.printLine("${r.city} ${r.country}"), xs)

~~~

Program 2 tries to pass the database as an argument - `relns` - to `showCapitals`, this is more modular as `showCapitals` doesn't instantiate the database and only cares that `relns` includes `Capital` facts...

~~~

def main(_args: Array[String]): Int32 & Impure = 
    Console.printLine("Running...");
    showCapitals(db());
    0

rel WorkItem(name: String, priority: Int32)
rel Capital(city: String, country: String)

def db(): #{WorkItem, Capital | r} = #{
    WorkItem("Order 01", 1).
    Capital("Copenhagen", "Denmark").
    Capital("Paris", "France").
    Capital("Lisbon", "Portugal").
}

def showCapitals(relns: #{Capital | r}): Unit & Impure =
    let xs = query relns select (x,y) from Capital(x,y) 
                |> Array.toList
                |> List.map(pair -> {city = fst(pair), country = snd(pair)});
    List.foreach(r -> Console.printLine("${r.city} ${r.country}"), xs)

~~~

Unfortunately program 2 fails with this error:

~~~

-- Type Error -------------------------------------------------- ..\flix-doodle\Datalog\NewSolver1.flix

>> The type scheme: '∀('a). #{ Capital(String, String), $Result(String, String) | 'a } ~> Unit with [String : Boxable, String : Eq, String : ToString, String : Boxable, String : Eq, String : ToString, String : Boxable, String : Eq, String : ToString, String : Boxable, String : Eq, String : ToString, String : ToString, String : ToString]' cannot be generalized to '∀(r). #{ Capital(String, String) | r } ~> Unit'.

18 | def showCapitals(relns: #{Capital | r}): Unit & Impure =
         ^^^^^^^^^^^^
         unable to generalize the type scheme.


  Declared: ∀(r). #{ Capital(String, String) | r } ~> Unit
  Inferred: ∀('a). #{ Capital(String, String), $Result(String, String) | 'a } ~> Unit with [String : Boxable, String : Eq, String : ToString, String : Boxable, String : Eq, String : ToString, String : Boxable, String : Eq, String : ToString, String : Boxable, String : Eq, String : ToString, String : ToString, String : ToString]


Compilation failed with 1 error(s).
 
~~~

**Comment by magnus-madsen** [comment]
@stephentetley Thanks for reporting this. This is not intended, but i don't have a fix yet.

**Comment by magnus-madsen** [comment]
I have a fix in mind.

**Comment by magnus-madsen** [comment]
The problem described in the issue is legit, but note that the program also has a small bug (maybe not caught by the compiler)?

In that:


```
def showCapitals(relns: #{Capital | r}) // means that you can only call it with Capital facts.
// but we have:
def db(): #{WorkItem, Capital | r}
// so technical this call is illegal:
showCapitals(db());
```

However, the real issue remains that if you change `showCapitals` to take both `Capitals` and `WorkItem` then you would expect it work (and it does not yet)

**Comment by magnus-madsen** [comment]
The compiler does not catch the above issue- but it will at some point in the future- because it is a cause of unsoundness.

**Comment by magnus-madsen** [comment]
The original program now type checks on my machine.

The following modifies program (trying to point out a few things) also works:

```
def main(_args: Array[String]): Int32 & Impure =
    Console.printLine("Running...");
    // to illustrate if you only want to pass certain facts.
    showCapitals(solve db() project WorkItem, Capital); 
    Console.printLine("Done...");
    0

rel WorkItem(name: String, priority: Int32)
rel Capital(city: String, country: String)

def db(): #{WorkItem, Capital, Food(String, String) | r} = #{
    WorkItem("Order 01", 1).
    Capital("Copenhagen", "Denmark").
    Capital("Paris", "France").
    Capital("Lisbon", "Portugal").
    Food("Pizza", "This fact makes no sense").
}

def showCapitals(relns: #{WorkItem, Capital}): Unit & Impure =
    let xs = query relns select (x,y) from Capital(x,y)
                |> Array.toList
                |> List.map(pair -> {city = fst(pair), country = snd(pair)});
    List.foreach(r -> Console.printLine("${r.city} ${r.country}"), xs)
```

and prints

```
Running...
Copenhagen Denmark
Lisbon Portugal
Paris France
Done...
```

**Comment by magnus-madsen** [comment]
I have pushed the fix to the branch.

**Comment by mlutze** [comment]
Why does `def showCapitals(relns: #{Capital | r})` mean it can only be called with `Capital`s?

Shouldn't `#{Capital | r}` and `#{Capital, WorkItem | s}` unify, resulting in `r = {WorkItem, s}` ?

**Comment by magnus-madsen** [comment]
> 
> 
> Why does `def showCapitals(relns: #{Capital | r})` mean it can only be called with `Capital`s?
> 
> Shouldn't `#{Capital | r}` and `#{Capital, WorkItem | s}` unify, resulting in `r = {WorkItem, s}` ?

You are right! Forget everything I said about the call being incorrect! :)

**Comment by magnus-madsen** [comment]
Based on @mlutze comment, I think you can understand a query as follows:

If you write:

```
def foo(e: #{what should go here}): ... = 
  query e select (String.toUpperCase(x), y + 42i32) from A(x), B(y, y).
```

then what you now require of `e` is that there must be a unnary `A` predicate of type `String` and a binary `B` predicate of type `(Int32, Int32)`. Other than that, `e` may contain any other number of predicates. That is fine. But IF it contains an `A` IT BETTER BE of the type `A(String)`.

**Comment by stephentetley** [comment]
> then what you now require of `e` is that there must be a unnary `A` predicate of type `String` and a binary `B` predicate of type `(Int32, Int32)`. Other than that, `e` may contain any other number of predicates. That is fine. But IF it contains an `A` IT BETTER BE of the type `A(String)`.
> 
> EDIT: Note that there is no requirement that are any facts/rule in `e`. The empty Datalog program is also fine.

Yes - in Program 2 I want `showCapitals` to state that there are `Capital(String, String)` facts in `relns` (or none of course) and be oblivious to other potential constraints (with different type signatures) in `relns`, thus `showCapitals` is polymorphic.

**Comment by magnus-madsen** [comment]
I merged in the solver, but we are still looking for any feedback.

Currently we just polishing many small things (e.g. performance, ergonomics, or architecture) as can be seen from the myriad of tickets I created.

**Comment by magnus-madsen** [comment]
I am pretty happy with where we landed on this. We can open future tickets if further adjustments/extensions are needed.

**Comment by magnus-madsen** [comment]
I am still working on updating doc.flix.dev
