### ISSUE TITLE
Datalog: Avoid use of |> (and similar combinators) in the Interpreter

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1861]
Probably only worth considering in the most performance critical parts.

**Comment by bdahse** [comment]
This was fixed some time ago. There are no uses of `|>` or `>>` in the interpreter. Any other combinators I should be aware of?

**Comment by magnus-madsen** [comment]
Currying?

**Comment by bdahse** [comment]
> 
> 
> Currying?

There is some explicit currying, but aren't all functions curried in Flix?

**Comment by magnus-madsen** [comment]
What I mean is that:

```
def foo(x: Int, y: Int): Int = ...


def bar(): Int = 
  let g = foo(123);
  g(456)
```

is slower than

```
def bar(): Int = 
  foo(123, 456);
```
