### ISSUE TITLE
Datalog: Add support for constructs up to N=10

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1863]
We currently support N=5 in most cases. This includes:

- Boxable instances (e.g. tuples).
- `AppX` and `GuardX`
- Other places?

**Comment by stephentetley** [comment]
Hi Magnus - would you be happy with n=15?

With the old solver I was using one relation with arity 13 so 10 would be a bit small for me. I also looked at Haskell and the size of instances for tuples is 15.

I've a branch here that extends the tuple instances to 15 and the datatypes in the new solver to 10 (I wanted to get an idea of how much work there was before going to 15 in the solver). I haven't looked at tests yet also I haven't properly looked at the solver code - I've relied on the exhaustivity checks in the compiler to tell me what I needed to change:

https://github.com/stephentetley/flix/tree/flix-n-higher

**Comment by magnus-madsen** [comment]
We could probably do that. 

The choice of `N` is not really for the core solver. It is more for the interface between Flix and the solver, and it determines the maximum number of variables that can be used in a guard/head function application.

Do you have relation with `n > 10`  where you intend to pass the facts in/out of the Datalog?

**Comment by stephentetley** [comment]
I've a relation of arity 13 that I synthesize within the solver then extract it to record and finally export it to Excel row.

**Comment by magnus-madsen** [comment]
OK, let use see if we can support it. I see the following tasks (maybe we can divide the work a bit):

- Add support for N=15 tuples to in the standard library. This includes instances for `Eq`, `Order`, `ToString`, and also `Boxable`. 
- Add `factsX` for N=15 to `Solver.flix` (by the way, these will probably be renamed soon, could be before/after.)
- Add `projectIntoX` for N=15 to `Solver.flix` (by the way, these will probably be renamed soon, could be before/after.)
- Add `GuardX` and `AppX` for N=15 to the relevant places in the solver.
- Change `Lowering.scala` to support up to N=15. (I will take this one).
- Are there other places we should bump to N=15? E.g. applicative functor functions?
- Did I miss anything?

I think you already have a PR/commit that covers some of these. Maybe that can be made into a PR? Then we can use it as a starting point.

Summoning @bdahse, @mlutze, @JonathanStarup  to share a few comments / ask for comments:

- For the internals of the Datalog engine is there any concern with going up to N=15? 
- For type classes, are there any performance concerns with having many instances or high arity instances? I don't think the types are too big, my concern is more that the lists of instances for each class is becoming large and may be expensive to iterate over. `Instances.scala` is probably fine (although the overlap check could become more expensive). What about `Monomorph.scala`? I notice we have a linear scan through the instances. Could we maintain a better map, e.g. `ClassSym -> TypeConstructor -> Instances` and do faster lookups that way?
- For the backend, if we have a 15-arity tuple, it could be named `T15$Obj$Obj$Obj$Obj$Obj$Obj$Obj$Obj$Obj$Obj$Obj$Obj$Obj$Obj$Obj.class`- I guess that does not yet exceed the limit of file names lengths on some operating systems (e.g. 255 chars?) Could it Have an even longer name? I guess `T15$Float64$Float64$Float64$Float64$Float64$Float64$Float64$Float64$Float64$Float64$Float64$Float64$Float64$Float64$Float64.class` is still OK?

**Comment by stephentetley** [comment]
Thanks Magnus, I've created a PR - Relation support to N=15 #1885

**Comment by magnus-madsen** [comment]
@stephentetley 

Would it be possible for you to post your most complicated rule with high arity relations? (You can anonymize it if desired. )

**Comment by stephentetley** [comment]
Hi Magnus - `Rules.flix` is most of the Datalog, the program is basically a "macro system" with Datalog as the macro rules. There is some Datalog processing in a few other modules (reading from various Excel files and writing to an Excel file, plus some rules that are more reuasble than `equiVALVE` so they've been put in library modules), then there's quite a lot of "functional Flix" in support modules. I think I'm reading about 4000 facts from the Excel files.

/// Main rules...
https://github.com/stephentetley/work-flix/blob/master/src/scripts/ValveReport/Rules.flix       

/// Libraries of rules here:
https://github.com/stephentetley/work-flix/tree/master/src/libs/AssetLib/GenS4/Characteristics

Unfortunately there are quite a lot of dependecies and it would be quite a lot of work to extract this into something "runnable". I could look to making a model problem that does something similar but is standalone (or possibly just uses Csv files for less dependencies).

**Comment by bdahse** [comment]
> 
> 
> OK, let use see if we can support it. I see the following tasks (maybe we can divide the work a bit):
> 
>     * Add support for N=15 tuples to in the standard library. This includes instances for `Eq`, `Order`, `ToString`, and also `Boxable`.
> 
>     * Add `factsX` for N=15 to `Solver.flix` (by the way, these will probably be renamed soon, could be before/after.)
> 
>     * Add `projectIntoX` for N=15 to `Solver.flix` (by the way, these will probably be renamed soon, could be before/after.)
> 
>     * Add `GuardX` and `AppX` for N=15 to the relevant places in the solver.
> 
>     * Change `Lowering.scala` to support up to N=15. (I will take this one).
> 
>     * Are there other places we should bump to N=15? E.g. applicative functor functions?
> 
>     * Did I miss anything?
> 
> 
> I think you already have a PR/commit that covers some of these. Maybe that can be made into a PR? Then we can use it as a starting point.
> 
> Summoning @bdahse, @mlutze, @JonathanStarup to share a few comments / ask for comments:
> 
>     * For the internals of the Datalog engine is there any concern with going up to N=15?
> 
>     * For type classes, are there any performance concerns with having many instances or high arity instances? I don't think the types are too big, my concern is more that the lists of instances for each class is becoming large and may be expensive to iterate over. `Instances.scala` is probably fine (although the overlap check could become more expensive). What about `Monomorph.scala`? I notice we have a linear scan through the instances. Could we maintain a better map, e.g. `ClassSym -> TypeConstructor -> Instances` and do faster lookups that way?
> 
>     * For the backend, if we have a 15-arity tuple, it could be named `T15$Obj$Obj$Obj$Obj$Obj$Obj$Obj$Obj$Obj$Obj$Obj$Obj$Obj$Obj$Obj.class`- I guess that does not yet exceed the limit of file names lengths on some operating systems (e.g. 255 chars?) Could it Have an even longer name? I guess `T15$Float64$Float64$Float64$Float64$Float64$Float64$Float64$Float64$Float64$Float64$Float64$Float64$Float64$Float64$Float64.class` is still OK? - Probably the new backend should use shorter names.

I can't think of any problems in the Datalog solver for N = 15. Depending on how you do it, it might end up with a lot of copy-paste but I think that's it.

**Comment by magnus-madsen** [comment]
> I can't think of any problems in the Datalog solver for N = 15. Depending on how you do it, it might end up with a lot of copy-paste but I think that's it. 

OK, Good!

> There is the fact that GuardX and AppX functions are curried, so it might be expensive to write very complex guards that capture lots of variables. I.e. evaluating a Guard15 term in the interpreter requires 15 closure allocations and 15 function calls.

That's right. But hopefully most programs will not have 15 free variables.

For example, this rule from Stephen:

```
            EquiCharacteristic(aibref, s4EquiClass, "UNICLASS_DESC", "") :- 
                EquiDatum(aibref, _, _,  _, _, _,  _, _, _,  _, _, _,  _),
                ValveWorkItem(aibref, _, _, _, _, s4EquiType, s4EquiClass),
                if s4EquiType != "VALV" and not String.isEmpty(s4EquiClass).
```

While it has a high arity I count only 4 free variables.

@bdahse Another thing is that the prefix lookup on `ValveWorkItem(aibref, _, _, _, _, s4EquiType, s4EquiClass)` is not great. But Stephen says he "only" has 4k facts so its probably not a concern. If `ValveWorkItem` contained 1,000,000 facts, well then... the story would be different.

**Comment by bdahse** [comment]
> 
> 
> > I can't think of any problems in the Datalog solver for N = 15. Depending on how you do it, it might end up with a lot of copy-paste but I think that's it.
> 
> OK, Good!
> 
> > There is the fact that GuardX and AppX functions are curried, so it might be expensive to write very complex guards that capture lots of variables. I.e. evaluating a Guard15 term in the interpreter requires 15 closure allocations and 15 function calls.
> 
> That's right. But hopefully most programs will not have 15 free variables.
> 
> For example, this rule from Stephen:
> 
> ```
>             EquiCharacteristic(aibref, s4EquiClass, "UNICLASS_DESC", "") :- 
>                 EquiDatum(aibref, _, _,  _, _, _,  _, _, _,  _, _, _,  _),
>                 ValveWorkItem(aibref, _, _, _, _, s4EquiType, s4EquiClass),
>                 if s4EquiType != "VALV" and not String.isEmpty(s4EquiClass).
> ```
> 
> While it has a high arity I count only 4 free variables. (EDIT: And the if guard has only 2 free variables, i.e. it is a Guard2)
> 
> @bdahse Another thing is that the prefix lookup on `ValveWorkItem(aibref, _, _, _, _, s4EquiType, s4EquiClass)` is not great. But Stephen says he "only" has 4k facts so its probably not a concern. If `ValveWorkItem` contained 1,000,000 facts, well then... the story would be different.

I agree the iteration over `ValveWorkItem` is inefficient but that would be the case even if it had lower airty and looked like this for example `ValveWorkItem(aibref, _, s4EquiType, s4EquiClass),`

**Comment by magnus-madsen** [comment]
We still need `projectIntoX` for N!=3. Ideally up to 15.

@bdahse Do you want to attempt some useful implementations without too much duplication?

**Comment by bdahse** [comment]
> 
> 
> We still need `projectIntoX` for N!=3. Ideally up to 15.
> 
> @bdahse Do you want to attempt some useful implementations without too much duplication?

Yes I can give it a go once I'm done with #1881 .

**Comment by magnus-madsen** [comment]
> 
> 
> I'm seeing a compiler crash in the Monomorph phase for arity 6 (Flix head of master with some of my own modules which shouldn't interfere)...
> 
> ```
> 
> rel Six(a: String, b: String, c: String, d: String, e: String, f: String)
> 
> def database(): #{Six | r} = #{
>     Six("one", "two", "three", "four", "five", "six").
> }
> 
> 
> def main(_args: Array[String]): Int32 & Impure = 
>     query database() select (x1, x2, x3, x4, x5, x6) from Six(x1, x2, x3, x4, x5, x6) 
>         |> Array.foreach(print6);
>     0
> 
> def print6(x: (String, String, String, String, String, String)): Unit & Impure = 
>     let (x1, x2, x3, x4, x5, x6) = x;
>     println("(${x1}, ${x2}, ${x3}, ${x4}, ${x5}, ${x6})")
> ```
> 
> Output:
> 
> ```
> 
> ✓ Reader                                    10.9ms
> ✓ Parser                                  3033.5ms
> ✓ Weeder                                  1089.5ms
> ✓ Namer                                   1690.0ms
> ✓ Resolver                                1379.4ms
> ✓ Typer                                   3475.4ms
> ✓ Instances                                 65.2ms
> ✓ Stratifier                               164.1ms
>     Compute Dependency Graph             (  40.0ms)
>     Compute Stratification               ( 119.3ms)
> ✓ PatternExhaustiveness                    524.7ms
> ✓ Redundancy                               442.2ms
> ✓ Safety                                    39.2ms
> ✓ Documentor                                 0.0ms
> ✓ Lowering                                 147.8ms
> Exception in thread "main" java.util.NoSuchElementException
> 	at scala.collection.immutable.BitmapIndexedMapNode.apply(HashMap.scala:635)
> 	at scala.collection.immutable.BitmapIndexedMapNode.apply(HashMap.scala:633)
> 	at scala.collection.immutable.BitmapIndexedMapNode.apply(HashMap.scala:633)
> 	at scala.collection.immutable.HashMap.apply(HashMap.scala:132)
> 	at ca.uwaterloo.flix.language.phase.Monomorph$.specializeDefSym$1(Monomorph.scala:501)
> 	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:134)
> 	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:197)
> 	at ca.uwaterloo.flix.language.phase.Monomorph$.$anonfun$run$2(Monomorph.scala:198)
> 	at scala.collection.immutable.List.map(List.scala:246)
> 	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:198)
> 	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:226)
> 	at ca.uwaterloo.flix.language.phase.Monomorph$.specialize$1(Monomorph.scala:490)
> 	at ca.uwaterloo.flix.language.phase.Monomorph$.$anonfun$run$34(Monomorph.scala:678)
> 	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
> 	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
> 	at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
> 	at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:889)
> 	at ca.uwaterloo.flix.language.phase.Monomorph$.$anonfun$run$1(Monomorph.scala:670)
> 	at ca.uwaterloo.flix.api.Flix.phase(Flix.scala:507)
> 	at ca.uwaterloo.flix.language.phase.Monomorph$.run(Monomorph.scala:86)
> 	at ca.uwaterloo.flix.language.phase.Monomorph$.run(Monomorph.scala:57)
> 	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.$anonfun$run$1(Phase.scala:42)
> 	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
> 	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
> 	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
> 	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
> 	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
> 	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
> 	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
> 	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
> 	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
> 	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
> 	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
> 	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
> 	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
> 	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
> 	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
> 	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
> 	at ca.uwaterloo.flix.api.Flix.codeGen(Flix.scala:481)
> 	at ca.uwaterloo.flix.api.Flix.$anonfun$compile$1(Flix.scala:495)
> 	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
> 	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
> 	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
> 	at ca.uwaterloo.flix.api.Flix.compile(Flix.scala:494)
> 	at ca.uwaterloo.flix.Main$.$anonfun$main$6(Main.scala:183)
> 	at ca.uwaterloo.flix.util.Timer.<init>(Timer.scala:28)
> 	at ca.uwaterloo.flix.Main$.main(Main.scala:183)
> 	at ca.uwaterloo.flix.Main.main(Main.scala)
> 
> Process finished with exit code 1
> ```

Its here:

https://github.com/flix/flix/blob/master/main/src/library/Fixpoint/Solver.flix#L468

We forgot to add up to N=10 or perhaps N=15.

**Comment by stephentetley** [comment]
Thanks Magnus - I saw that `Boxable` has `liftN` and `liftNb` functions only up to N=5. Does that matter?

**Comment by stephentetley** [comment]
Here's code for up to N=15 - I can make a PR tomorrow or I'm happy if you just copy it in...


~~~

    ///
    /// Returns all facts in `d` associated with the predicate symbol `p`.
    ///
    pub def facts6(p: PredSym, d: Datalog[Boxed]): Array[(t1, t2, t3, t4, t5, t6)] with Boxable[t1], Boxable[t2], Boxable[t3], Boxable[t4], Boxable[t5], Boxable[t6] =
        let f = terms -> (unbox(terms[0]), unbox(terms[1]), unbox(terms[2]), unbox(terms[3]), unbox(terms[4]), unbox(terms[5]));
        factsOf(f, p, d) as & Pure

    ///
    /// Returns all facts in `d` associated with the predicate symbol `p`.
    ///
    pub def facts7(p: PredSym, d: Datalog[Boxed]): Array[(t1, t2, t3, t4, t5, t6, t7)] with Boxable[t1], Boxable[t2], Boxable[t3], Boxable[t4], Boxable[t5], Boxable[t6], Boxable[t7] =
        let f = terms -> (unbox(terms[0]), unbox(terms[1]), unbox(terms[2]), unbox(terms[3]), unbox(terms[4]), unbox(terms[5]), unbox(terms[6]));
        factsOf(f, p, d) as & Pure

    ///
    /// Returns all facts in `d` associated with the predicate symbol `p`.
    ///
    pub def facts8(p: PredSym, d: Datalog[Boxed]): Array[(t1, t2, t3, t4, t5, t6, t7, t8)] with Boxable[t1], Boxable[t2], Boxable[t3], Boxable[t4], Boxable[t5], Boxable[t6], Boxable[t7], Boxable[t8] =
        let f = terms -> (unbox(terms[0]), unbox(terms[1]), unbox(terms[2]), unbox(terms[3]), unbox(terms[4]), unbox(terms[5]), unbox(terms[6]), unbox(terms[7]));
        factsOf(f, p, d) as & Pure

    ///
    /// Returns all facts in `d` associated with the predicate symbol `p`.
    ///
    pub def facts9(p: PredSym, d: Datalog[Boxed]): Array[(t1, t2, t3, t4, t5, t6, t7, t8, t9)] with Boxable[t1], Boxable[t2], Boxable[t3], Boxable[t4], Boxable[t5], Boxable[t6], Boxable[t7], Boxable[t8], Boxable[t9] =
        let f = terms -> (unbox(terms[0]), unbox(terms[1]), unbox(terms[2]), unbox(terms[3]), unbox(terms[4]), unbox(terms[5]), unbox(terms[6]), unbox(terms[7]), unbox(terms[8]));
        factsOf(f, p, d) as & Pure

    ///
    /// Returns all facts in `d` associated with the predicate symbol `p`.
    ///
    pub def facts10(p: PredSym, d: Datalog[Boxed]): Array[(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10)] with Boxable[t1], Boxable[t2], Boxable[t3], Boxable[t4], Boxable[t5], Boxable[t6], Boxable[t7], Boxable[t8], Boxable[t9], Boxable[t10] =
        let f = terms -> (unbox(terms[0]), unbox(terms[1]), unbox(terms[2]), unbox(terms[3]), unbox(terms[4]), unbox(terms[5]), unbox(terms[6]), unbox(terms[7]), unbox(terms[8]), unbox(terms[9]));
        factsOf(f, p, d) as & Pure

    ///
    /// Returns all facts in `d` associated with the predicate symbol `p`.
    ///
    pub def facts11(p: PredSym, d: Datalog[Boxed]): Array[(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11)] with Boxable[t1], Boxable[t2], Boxable[t3], Boxable[t4], Boxable[t5], Boxable[t6], Boxable[t7], Boxable[t8], Boxable[t9], Boxable[t10], Boxable[t11] =
        let f = terms -> (unbox(terms[0]), unbox(terms[1]), unbox(terms[2]), unbox(terms[3]), unbox(terms[4]), unbox(terms[5]), unbox(terms[6]), unbox(terms[7]), unbox(terms[8]), unbox(terms[9]), unbox(terms[10]));
        factsOf(f, p, d) as & Pure

    ///
    /// Returns all facts in `d` associated with the predicate symbol `p`.
    ///
    pub def facts12(p: PredSym, d: Datalog[Boxed]): Array[(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12)] with Boxable[t1], Boxable[t2], Boxable[t3], Boxable[t4], Boxable[t5], Boxable[t6], Boxable[t7], Boxable[t8], Boxable[t9], Boxable[t10], Boxable[t11], Boxable[t12] =
        let f = terms -> (unbox(terms[0]), unbox(terms[1]), unbox(terms[2]), unbox(terms[3]), unbox(terms[4]), unbox(terms[5]), unbox(terms[6]), unbox(terms[7]), unbox(terms[8]), unbox(terms[9]), unbox(terms[10]), unbox(terms[11]));
        factsOf(f, p, d) as & Pure

    ///
    /// Returns all facts in `d` associated with the predicate symbol `p`.
    ///
    pub def facts13(p: PredSym, d: Datalog[Boxed]): Array[(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13)] with Boxable[t1], Boxable[t2], Boxable[t3], Boxable[t4], Boxable[t5], Boxable[t6], Boxable[t7], Boxable[t8], Boxable[t9], Boxable[t10], Boxable[t11], Boxable[t12], Boxable[t13] =
        let f = terms -> (unbox(terms[0]), unbox(terms[1]), unbox(terms[2]), unbox(terms[3]), unbox(terms[4]), unbox(terms[5]), unbox(terms[6]), unbox(terms[7]), unbox(terms[8]), unbox(terms[9]), unbox(terms[10]), unbox(terms[11]), unbox(terms[12]));
        factsOf(f, p, d) as & Pure

    ///
    /// Returns all facts in `d` associated with the predicate symbol `p`.
    ///
    pub def facts14(p: PredSym, d: Datalog[Boxed]): Array[(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14)] with Boxable[t1], Boxable[t2], Boxable[t3], Boxable[t4], Boxable[t5], Boxable[t6], Boxable[t7], Boxable[t8], Boxable[t9], Boxable[t10], Boxable[t11], Boxable[t12], Boxable[t13], Boxable[t14] =
        let f = terms -> (unbox(terms[0]), unbox(terms[1]), unbox(terms[2]), unbox(terms[3]), unbox(terms[4]), unbox(terms[5]), unbox(terms[6]), unbox(terms[7]), unbox(terms[8]), unbox(terms[9]), unbox(terms[10]), unbox(terms[11]), unbox(terms[12]), unbox(terms[13]));
        factsOf(f, p, d) as & Pure

    ///
    /// Returns all facts in `d` associated with the predicate symbol `p`.
    ///
    pub def facts15(p: PredSym, d: Datalog[Boxed]): Array[(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15)] with Boxable[t1], Boxable[t2], Boxable[t3], Boxable[t4], Boxable[t5], Boxable[t6], Boxable[t7], Boxable[t8], Boxable[t9], Boxable[t10], Boxable[t11], Boxable[t12], Boxable[t13], Boxable[t14], Boxable[t15] =
        let f = terms -> (unbox(terms[0]), unbox(terms[1]), unbox(terms[2]), unbox(terms[3]), unbox(terms[4]), unbox(terms[5]), unbox(terms[6]), unbox(terms[7]), unbox(terms[8]), unbox(terms[9]), unbox(terms[10]), unbox(terms[11]), unbox(terms[12]), unbox(terms[13]), unbox(terms[14]));
        factsOf(f, p, d) as & Pure

~~~

**Comment by magnus-madsen** [comment]
Looks good!

**Comment by magnus-madsen** [comment]
Also, if you could, add a few test cases to ensure that we never break anything again with these high arity predicates. :)

**Comment by magnus-madsen** [comment]
> 
> 
> Thanks Magnus - I saw that `Boxable` has `liftN` and `liftNb` functions only up to N=5. Does that matter?

Not for this specific problem.

There is a limitation where you can only call a function inside a constraint with at most 5 quantified variables.

**Comment by stephentetley** [comment]
Hi Magnus - I've created a PR with the facts6 to facts15 functions.

Solver adding facts6 to facts15 #1972
