### ISSUE TITLE
Datalog: What should `query` return?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1867]
It currently returns an array, but other options are: `List` or `LazyList`.

Edit it could return some "abstract value" that implements Foldable.

**Comment by JonathanStarup** [comment]
We've discussed doing this soon (related discussion #3939 #4095) and maybe you want to get a final say @stephentetley before we break everything that uses Datalog.

1) We could quite easily have query return lists. The only drawback here is that if this is not the final choice we want it would require two rewrites
2) It could return `t with Foldable[t]` to allow ourself room for change
3) Anything else?

**Comment by stephentetley** [comment]
Wouldn't an iterator be the closest to to 2. ?

**Comment by JonathanStarup** [comment]
yes but then we'd have to introduce a region like you suggested. None of you like the set option?

**Comment by magnus-madsen** [comment]
I think we should use a List pending the introduction of a vector-like type.
