### ISSUE TITLE
Datalog: What options should the Compiler/Interpreter support?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1868]
We currently support a flag to enable/disable debugging. Do we need anything else?

**Comment by bdahse** [comment]
We should probably suppress RAM comments when debugging is enabled.

**Comment by magnus-madsen** [comment]
Yes, when debugging is disabled.

**Comment by bdahse** [comment]
That's what I meant yes :)

**Comment by magnus-madsen** [comment]
I think we should just add options as we go.
