### ISSUE TITLE
Type Classes: Performance of Instance Selection

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1886]
Inside `Monomorph` we should replace this:

```
      val defns = instances.flatMap {
        inst =>
          inst.defs.find {
            defn =>
              defn.sym.name == sig.sym.name && Unification.unifiesWith(defn.spec.declaredScheme.base, tpe)
          }
      }
```

by a smarter lookup using type constructors.

**Comment by mlutze** [comment]
We also have a linear lookup in `ClassEnvironment.scala` (used by `Typer.scala`), which I think could also be replaced.

**Comment by magnus-madsen** [comment]
We should profile and use that to guide us.
