### ISSUE TITLE
Type Classes: Potential Performance Issue Around Lists

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1888]
We currently store type class constraints as `List[Ast.TypeConstraint]`.

I know I suggest this, but I am wrong. Or rather, it is time to think about something more efficient.

A set would be nice, but has two downsides:

- Ordering/Determinism of the constraints.
- What is the notion of equality on types?

**Comment by mlutze** [comment]
Before making this change, I'd first like to see the effect of apply context reduction. I think it would have a significant performance impact.

**Comment by magnus-madsen** [comment]
> 
> 
> Before making this change, I'd first like to see the effect of applying context reduction. I think it would have a significant performance impact.

I agree.

**Comment by mlutze** [comment]
@magnus-madsen I see you merged the context reduction change. Did that have a significant impact?

**Comment by magnus-madsen** [comment]
No visible impact: https://arewefast.flix.dev/d/nFYOg5FZk/flix-compiler-overview?orgId=1
