### ISSUE TITLE
Datalog: Implement Simplifier

### ISSUE THREAD

**Issue by bdahse** [flix/flix#1895]
The RAM code our Datalog compiler produces is very redundant. There are many opportunities to optimize it by deleting code. We should consider a phase that recognizes and simplifies certain patterns. Consider the program:
```
Path(x, y) :- Edge(x, y).
Path(x, z) :- Path(x, y), Edge(y, z).
```
And its RAM equivalent (facts omitted):
```
// Path(x, y) :- Edge(x, y).;
search 0$ ∈ Edge do
    if(0$[0] = 0$[0] ∧ 0$[1] = 0$[1]) then
        project (0$[0], 0$[1]) into Path
    end
end;
// Path(x, z) :- Path(x, y), Edge(y, z).;
search 0$ ∈ Path do
    if(0$[0] = 0$[0]) then
        search 1$ ∈ Edge do
            if(0$[1] = 1$[0] ∧ 1$[0] = 1$[0] ∧ 1$[1] = 1$[1]) then
                project (0$[0], 1$[1]) into Path
            end
        end
    end
end;
merge Path into ΔPath;
until(ΔPath = ∅) do
    purge ΔPath';
    // Path(x, y) :- Edge(x, y).;
    search 0$ ∈ ΔEdge do
        if((0$[0], 0$[1]) ∉ Path ∧ 0$[0] = 0$[0] ∧ 0$[1] = 0$[1]) then
            project (0$[0], 0$[1]) into ΔPath'
        end
    end;
    // Path(x, z) :- Path(x, y), Edge(y, z).;
    search 0$ ∈ ΔPath do
        if(0$[0] = 0$[0]) then
            search 1$ ∈ Edge do
                if((0$[0], 1$[1]) ∉ Path ∧ 0$[1] = 1$[0] ∧ 1$[0] = 1$[0] ∧ 1$[1] = 1$[1]) then
                    project (0$[0], 1$[1]) into ΔPath'
                end
            end
        end
    end;
    search 0$ ∈ Path do
        if(0$[0] = 0$[0]) then
            search 1$ ∈ ΔEdge do
                if((0$[0], 1$[1]) ∉ Path ∧ 0$[1] = 1$[0] ∧ 1$[0] = 1$[0] ∧ 1$[1] = 1$[1]) then
                    project (0$[0], 1$[1]) into ΔPath'
                end
            end
        end
    end;
    merge ΔPath' into Path;
    ΔPath := ΔPath'
end
```
One of the most immediate redundancies is checks like `0$[0] = 0$[0] ∧ 0$[1] = 0$[1]` where a term is tested for equality with itself. Such checks should be deleted. This can lead to if-statements with empty tests, which should also be deleted.

Consider this if-statement: `if((0$[0], 1$[1]) ∉ Path ∧ 0$[1] = 1$[0])`. Here we cannot delete any of the checks, but it would be more efficient to swap them:  `if(0$[1] = 1$[0] ∧ (0$[0], 1$[1]) ∉ Path)`. Equality can be tested in constant time whereas membership takes logarithmic time (in the size of `Path`).

Another simplification is the deletion of entire join-loops. The loop condition `until(ΔPath = ∅) do ... end` tells us that `Path` is computed in the `until` loop. That implies this entire loop can be deleted:
```
    // Path(x, y) :- Edge(x, y).;
    search 0$ ∈ ΔEdge do
        if((0$[0], 0$[1]) ∉ Path ∧ 0$[0] = 0$[0] ∧ 0$[1] = 0$[1]) then
            project (0$[0], 0$[1]) into ΔPath'
        end
    end;
```
Why? Because `ΔEdge` is empty. `Edge` was not part of the `until` loop. Therefore it must be a base relation or fully computed in a previous `until` loop. Base relations have empty delta relations and the termination criteria of the previous loop guarantees that `ΔEdge` is empty if it's a derived relation. Therefore any loop-nest that iterates over `ΔEdge` can be deleted.

If we apply all of these simplifications to the RAM program above, we get:
```
// Path(x, y) :- Edge(x, y).;
search 0$ ∈ Edge do
      project (0$[0], 0$[1]) into Path
end;
// Path(x, z) :- Path(x, y), Edge(y, z).;
search 0$ ∈ Path do
      search 1$ ∈ Edge do
          if(0$[1] = 1$[0]) then
              project (0$[0], 1$[1]) into Path
          end
      end
end;
merge Path into ΔPath;
until(ΔPath = ∅) do
    purge ΔPath';
    // Path(x, z) :- Path(x, y), Edge(y, z).;
    search 0$ ∈ ΔPath do
          search 1$ ∈ Edge do
              if(0$[1] = 1$[0] ∧ (0$[0], 1$[1]) ∉ Path) then
                  project (0$[0], 1$[1]) into ΔPath'
              end
          end
    end;
    merge ΔPath' into Path;
    ΔPath := ΔPath'
end
```
Which is not only much shorter, but also more efficient.

**Comment by bdahse** [comment]
To summarize, the Simplifier should do (at least) the following:

1. Delete checks of the form `t[i] == t[i]`.
2. Rewrite `if () then ...body... end` into `...body...`.
3. Ensure membership queries come last in any conjunctions.
4. Remove loop-nests that iterate over a relation that is known to be empty.

It might make sense to implement step 4 as a separate phase that runs very early. A RAM program can be quadratic size compared to the Datalog program so deleting entire loops can be beneficial for phases that come after 4.

**Comment by magnus-madsen** [comment]
It seems some of these are very low hanging fruit and could be implemented quickly.

**Comment by magnus-madsen** [comment]
As a general comment: It is often better to avoid redundancies during compilation than to attempt to clean them up later.

For example, presumably the constraint `t[i] == t[i]` can just be replaced by `true` just before it is emitted.

**Comment by racerand** [comment]
I have looked at `t[i] == t[i]` and it seems like a simple if statement should be able to fix it. I should be able to write up a PR quickly.

**Comment by racerand** [comment]
Something I realized while looking into this, is that when we look at the example above, then `y` in the second rule is chosen as `1$[0]` on the right hand side of the equality, and not as `0$[1]`. That is, it is the last term in which a variable occurs that represents it. In this example it doesn't make a difference, but let's look at
```
Compiler(src, dst, lang) :-
        Compiler(src, intermediate, lang),
        Compiler(intermediate, dst, lang),
        Interpreter(lang).
```
from examples/compiler-puzzle.flix. Currently it compiles to:
```
search 0$ ∈ Compiler do
        if(0$[0] = 0$[0]) then
            query {1$ ∈ Compiler | 1$[0] = 0$[1]} do
                if(1$[0] = 1$[0] ∧ 1$[1] = 1$[1]) then
                    query {2$ ∈ Interpreter | 2$[0] = 0$[2] ∧ 2$[0] = 1$[2]} do
                        if(2$[0] = 2$[0]) then
                            project (0$[0], 1$[1], 2$[0]) into Compiler
                        end
                    end
                end
            end
        end
    end;
```
If we had chosen the first term in which a variable occurs to represent it, it would compile to:
```
search 0$ ∈ Compiler do
        if(0$[0] = 0$[0] ∧ 0$[1] = 0$[1] ∧ 0$[2] = 0$[2]) then
            query {1$ ∈ Compiler | 1$[0] = 0$[1]} do
                if(1$[1] = 1$[1] ∧ 1$[2] = 0$[2]) then
                    query {2$ ∈ Interpreter | 2$[0] = 0$[2]} do
                        project (0$[0], 1$[1], 0$[2]) into Compiler
                    end
                end
            end
        end
    end;
```
This moves conditions to be checked earlier than before. But if we want subsequent phases to be able to move around the search operations, then I think that the compiler is too early a step to make this choice, apart from in the project operation.
In this example there is 1 equality in each representation that is not in the other: `1$[2] = 2$[0]` in not in the first version, and `0$[2] = 1$[2]` in the second version. As I have just shown, there are ways to optimize that would prefer one over the other.

I know this is not directly relevant for this issue, but thought it is important to bring up.

**Comment by bdahse** [comment]
@racerand I see your point about variables being unified "right-to-left", but I'm not convinced the second version is actually better (or worse). The reason being that
`query {2$ ∈ Interpreter | 2$[0] = 0$[2] ∧ 2$[0] = 1$[2]} do` 
is a nop if `0$[2] != 1$[2]`. I.e. it will literally be evaluated like an if-statement that first checks `2$[0] = 0$[2]` and then `2$[0] = 1$[2]` if the first check is true (the logic is in https://github.com/flix/flix/blob/master/main/src/library/Fixpoint/Interpreter.flix#L102 ).

So if there is a difference I believe it is a constant factor determined by how you implement the if-statement in your second example. In my understanding, the first loop certainly doesn't do any iteration that the second loop doesn't.

As for "right-to-left" vs "left-to-right", the same effect can be obtained by reordering the rule body, which is what #1884 is about.

I appreciate you looking through the code and asking questions btw :)

**Comment by racerand** [comment]
It might be a constant calculation, but it has to be done for every element in Interpreter, which is skipped in the second version.

My point is, that calculating `2$[0] = 0$[2]` and `2$[2] = 1$[2]` for each element in Interpreter will happen in the first one version, which is O(size(Interpreter)).
In the second version we replace `2$[2] = 1$[2]` with `1$[2] = 0$[2]` which we can calculate before quering Interpreter. 

I would say that your argument that the two versions are equivalent is close to saying that hightening of if statements in the queryStmt phase does not do anything for runtime.

**Comment by bdahse** [comment]
> 
> I will gladly try to benchmark this, if you will tell me how.

Take a look at https://github.com/flix/flix/blob/master/main/src/library/Benchmark/Bench.Fixpoint.flix for an example of how to write a benchmark. `benchmarkSolve` is probably the closest to what you need. Example of how to run a benchmark:
```
def main(_args: Array[String]): Int32 & Impure =
    let b = Bench/Exp/Fixpoint.benchmarkSolveIntersect();
    Benchmark.runWithBudget(b, 5i64 * Duration.oneMinute())
```

That said, I don't agree with this:

> My point is, that calculating `2$[0] = 0$[2]` and `2$[2] = 1$[2]` for each element in Interpreter will happen in the first one version, which is O(size(Interpreter)).

That would be true if query was a linear scan over Interpreter (i.e. a search). But it's not, it's a range query on an index (a red-black tree in our case).

**Comment by bdahse** [comment]
But if we take a step back from your example, I think you're suggesting unifying variables with their first occurence (assuming the loop order is the same as the rule order)? Because it might affect hoisting of if-statements.

**Comment by racerand** [comment]
> That would be true if query was a linear scan over Interpreter (i.e. a search). But it's not, it's a range query on an index (a red-black tree in our case).

Okay, so it is not linear, but it is also not constant, which is the relevant part. Seems like you're getting what I'm trying to say though:

> But if we take a step back from your example, I think you're suggesting unifying variables with their first occurence (assuming the loop order is the same as the rule order)? Because it might affect hoisting of if-statements.

That is exactly the point. In version 2 a boolExp is hoistened, while it isn't in version 1. Since `2$[0] = 0$[2] ∧ 2$[0] = 1$[2]` is equivalent to `1$[0] = 0$[1] ∧2$[0] = 0$[2]`.
But if we assume that the loop order can change, then we might not want to unify the variables to 1 occurence, but use all occurences, and then simplify later, after loop ordering is fixed, for maximum optimization potential. Though here I'm not sure if the overhead of the extra expressions that need to be sorted through is worth the potential gain.

**Comment by bdahse** [comment]
You can open a separate issue for this if you think it's worth it. It's not something I'm going to be looking into, unless it turns out to be very important for performance :)

But the way I see it, it requires a rule with at least 3 atoms and a variable that occurs in at least 3 atoms to run into this. Do you agree?

**Comment by racerand** [comment]
Yes, I agree. So for many rules, this will probably not add anything. I'll open a separate issue for further reference.

**Comment by JonathanStarup** [comment]
Fixed
