### ISSUE TITLE
Bug: Cannot use Flix as a simple Datalog solver anymore

### ISSUE THREAD

**Issue by racerand** [flix/flix#1900]
If I try to compile examples/fixpoint-computations-on-relations.flix, that is:
```
/// We can use Flix as an ordinary Datalog solver.

/// Declare some edge facts.
DirectedEdge(1, 2).
DirectedEdge(2, 3).
DirectedEdge(2, 4).
DirectedEdge(3, 5).

// Declare some constraints.
Connected(x, y) :- DirectedEdge(x, y).
Connected(x, z) :- Connected(x, y), DirectedEdge(y, z).
```
I get the error
```
Exception in thread "main" java.lang.UnsupportedOperationException: toString method shouldn't be called
```
I suspect that this has to do with how the solved program is printed. I'm guessing that it's hardcoded somewhere and needs to be changes to `Fixpoint.unsafePrint`?
Another question is if this is still relevant?

**Comment by magnus-madsen** [comment]
Top-level constraints are actually no longer supported and will be removed soon. 

I just didn't know that they crash the compiler!

**Comment by magnus-madsen** [comment]
See https://github.com/flix/flix/issues/1845

**Comment by magnus-madsen** [comment]
Go here for current syntax: https://github.com/flix/flix/issues/1852

**Comment by racerand** [comment]
That makes sense.
And thank you for the link.

**Comment by magnus-madsen** [comment]
Ill keep it open because I did not realize it was actually broken. I was just planning to remove it eventually.

**Comment by magnus-madsen** [comment]
So in that sense, thanks for speeding up its removal :)

**Comment by racerand** [comment]
You're welcome. I'm also going through other examples atm. but this seems like the biggest issue.
`examples/fixpoint-computations-with-stratified-negation.flix` also has this issue.

**Comment by magnus-madsen** [comment]
Removed support for top-level Datalog constraints. We know only have first-class Datalog constraints.
