### ISSUE TITLE
Monoid should extend Semigroup

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1910]
- [ ] Monoid should extend SemiGroup (`with .. `)
- [ ] The `Monoid.combine` function should call `SemiGroup.combine` and its documentation should be updated.
- [ ] Maybe tests need to be shuffled around?
- [ ] Add laws about `Monoid`.

Edit: I think that `lawless` can be removed from `SemiGroup`.

**Comment by ninaandrup** [comment]
Other datatypes have an instance of Monoid. For example Chain:
```
instance Monoid[Chain[a]] {
    pub def empty(): Chain[a] = Chain.empty()
    pub def combine(c1: Chain[a], c2: Chain[a]): Chain[a] = Chain.append(c1, c2)
}
```
But for Chain it also have an instance of SemiGroup:
```
instance SemiGroup[Chain[a]] {
    pub def combine(c1: Chain[a], c2: Chain[a]): Chain[a] = Chain.append(c1, c2)
}
```
Should I just delete the combine function in the `Monoid` instance? And  if it does not exist like for `Chain`, should it be added to a `SemiGroup` instance?
