### ISSUE TITLE
Datalog: deactivating lowerStmt causes silent fail of Datalog interpreter

### ISSUE THREAD

**Issue by racerand** [flix/flix#1912]
While examining the new Datalog solver I realized that if you [comment out the lowerStmt phase](https://github.com/flix/flix/blob/3b9c6fee930be554c56f8d0abbf2ad3f9b17d003/main/src/library/Fixpoint/Solver.flix#L45), then the interpreter fails silently.
I understand why it fails, but it seems bad that I am not explicitly informed of this.
I am faily certain that [this is the line that fails](https://github.com/flix/flix/blob/3b9c6fee930be554c56f8d0abbf2ad3f9b17d003/main/src/library/Fixpoint/Interpreter.flix#L199), but I am not sure.

**Comment by bdahse** [comment]
Yep, `lowerStmt` is required. If you want to see the RAM code before lowering you will have to insert a print somewhere before that. It's the last step before interpretation so it should be fine to put the print at the top of `lowerStmt`.

**Comment by magnus-madsen** [comment]
Working as intended. This is an internal implementation detail.
