### ISSUE TITLE
Type Classes: Add Group and CommutativeGroup

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1924]
Propose a design for Group and CommutativeGroup. (Explore the design in Cats, Scalaz, and Haskell).

Ideas: 
- [ ] Add an abstract `inverse` function signature.
- [ ] Add a `remove` function which is `combine(a, inverse(b))`.
- [ ] Add laws.
- [ ] Add instances.

**Comment by jaschdoc** [comment]
Haskell implementation: https://hackage.haskell.org/package/groups-0.5.3/docs/Data-Group.html
