### ISSUE TITLE
CI timeout

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1939]
I don't know exactly what happened in https://github.com/flix/flix/pull/1904#issuecomment-836027799 but I would guess that this could be mitigated by a timeout in the workflow or in the test runner.

**Comment by mlutze** [comment]
Looks like the default is 6 hours: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes

I think doing it in the test runner would be better though, since that would actually show which test caused the issue.

**Comment by justinfargnoli** [comment]
I think one of the tests deadlocked. I messaged y'all because I didn't want to waste CI time since I belive it's limited.

**Comment by magnus-madsen** [comment]
I think if something deadlocks CPU usage goes to zero and then probably GH doesnt care.

Now, if you were mining bitcoins on the other hand...

**Comment by magnus-madsen** [comment]
We have not had this problem for a while and presumably GitHub knows how to cancel long running computations.
