### ISSUE TITLE
Add support for GetIndex/SetIndex in the Parser.

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#194]
E.g.

```
def f(v: Vec[Int]): Int = v[0]
```

**Comment by mhyee** [comment]
Just to confirm, this is for vectors and not tuples? (Do we have or are we planning to have GetIndex for tuples?)

Is there a reason for using square brackets, or is it just because of C/C++/Java/etc? Or should we use Scala's syntax?

**Comment by magnus-madsen** [comment]
Uh. The issue is open, so feel free to comment. We could use them for both... or not..

**Comment by magnus-madsen** [comment]
Vectors are out. (Use Map[Int, X]). We may later add square brackets to access indices of tuples.
