### ISSUE TITLE
Update sort functions for `List` and `Array`

### ISSUE THREAD

**Issue by felixwiemuth** [flix/flix#1945]
Currently both `List` and `Array` only have a `sortWith` function which returns `Int32` (this should be changed to `Comparison`).
We discussed that we should add a function `sort : List[a] -> List[a] with Order[a]` (the same for `Array`).

In addition, we probably want to add the following [`sortOn`](https://hackage.haskell.org/package/base-4.15.0.0/docs/Data-List.html#v:sortOn) function from Haskell for `List` (and `Array`):
```
sortOn :: Ord b => (a -> b) -> [a] -> [a] 
```
This can for example be used to sort on a specific field of a record:
```
let l = {i=2, s="World"}::{i=1, s="Hello"}::Nil;
let l' = sortOn (x -> x.i) l;
l' == {i=1, s="Hello"}::{i=2, s="World"}::Nil
```
There are currently no "sort" functions outside `List` and `Array`.

Any comments @magnus-madsen ?

**Comment by magnus-madsen** [comment]
Sounds good. Would be nice to have `sortOn` for List, Nel, and Array.

**Comment by mlutze** [comment]
Scala uses the name `sortBy` for this, which I prefer slightly.

**Comment by felixwiemuth** [comment]
> Scala uses the name `sortBy` for this, which I prefer slightly.

And in Haskell, `sortBy` is the `sortWith` we have in Flix for now :D. Although I think `sortWith` is the better name for that function, and we can use `sortBy` in the sense of "sort by this property/criterion".

However, it's worth looking at the relationship of the functions around comparison and sorting in Haskell:

``` haskell
compare :: Ord a => a -> a -> Ordering
comparing :: Ord a => (b -> a) -> b -> b -> Ordering
sortBy :: (a -> a -> Ordering) -> [a] -> [a]
sortOn :: Ord b => (a -> b) -> [a] -> [a] 

```
`sortOn f` is equivalent to `sortBy (comparing f)` and ``sortBy (compare `on` f)``.

For `comparing`, the docs say "Useful combinator for use in conjunction with the xxxBy family of functions from Data.List".
However, in the `Data.List` documentation under [The "By" operations](https://hackage.haskell.org/package/base-4.15.0.0/docs/Data-List.html#g:23) it says "It is often convenient to use these functions together with `on`, for instance ``sortBy (compare `on` fst)``."
The only functions that actually take an `a -> a -> Ordering` (which `comparing` produces) in `Data.List` are:
``` haskell
sortBy :: (a -> a -> Ordering) -> [a] -> [a]
insertBy :: (a -> a -> Ordering) -> a -> [a] -> [a]
maximumBy :: Foldable t => (a -> a -> Ordering) -> t a -> a
minimumBy :: Foldable t => (a -> a -> Ordering) -> t a -> a
```

And since `comparing f` is just ``compare `on` f``, I would prefer having the more general `on` and leaving out `comparing`.

```haskell
on :: (b -> b -> c) -> (a -> b) -> a -> a -> c
```

From the [docs](https://hackage.haskell.org/package/base-4.15.0.0/docs/Data-Function.html#v:on):

> on b u x y runs the binary function b on the results of applying unary function u to two arguments x and y. From the opposite perspective, it transforms two inputs and combines the outputs.
> 
> ((+) `on` f) x y = f x + f y

Then we could implement `sortOn` as
```scala
def sortOn(f : a -> b, List[a]) : List[a] with Order[b] = List.sortWith (Order.compare `on` f)
```
The Haskell `sortOn`, however, is an optimized version which only evaluates `f` once on each element. That we could maybe just keep in mind and add a TODO comment.

**Comment by magnus-madsen** [comment]
@felixwiemuth 

I think I understand, but could I ask you to spell out the signatures of the functions we would have?

**Comment by felixwiemuth** [comment]
Sure; In short we would have the following functions:

In `Prelude.flix` as a general helper:
```scala
on : (b -> b -> c) -> (a -> b) -> a -> a -> c // See doc above

```

In `List.flix` (and analogously in `Array.flix` and `Nel.flix`):
```scala
sort : List[a] -> List[a] with Order[a]
sortWith : (a -> a -> Comparison) -> List[a] -> List[a] // Update comparison function to return `Comparison`
sortBy : (a -> b) -> List[a] -> List[a] with Order[b] // Implementation will use `on`
```

Then there are of course a lot of other useful functions in Haskell's [Data.List](https://hackage.haskell.org/package/base-4.15.0.0/docs/Data-List.html) and at some point one could go through all of them (and those of other standard libraries) and see what we think we should have. But that should probably be a more thorough pass, ensuring consistency. As I understand that is not the priority for now, right?

**Comment by magnus-madsen** [comment]
+1 for the last proposal. I think we should implement that.

As for naming - `With` vs `By` - I think we have the right names. They seam to match Scala's API and Haskell uses slightly different names, so I think it is okay. No matter what choice we make, people will have to look it up and look at the signatures.

Btw. `on` should (probably?) be effect polymorphic? whereas all the sort operations require pure functions.

**Comment by felixwiemuth** [comment]
> +1 for the last proposal. I think we should implement that.

Are you referring to the 4 suggested functions or going through the Haskell functions?

> As for naming - `With` vs `By` - I think we have the right names. They seem to match Scala's API and Haskell uses slightly different names, so I think it is okay. No matter what choice we make, people will have to look it up and look at the signatures.

Agree.

> Btw. `on` should (probably?) be effect polymorphic? whereas all the sort operations require pure functions.

Yes, `on` should be effect-polymorphic in the sense that it is pure iff both argument functions are pure.
The sort functions require pure argument functions but are impure themselves because they work on arrays.

Does Flix have infix notation (for general functions) or is that planned to be added? `on` is more readable infix (see example `((+) on f) x y` which is equivalent to `f x + f y`).

**Comment by mlutze** [comment]
> Does Flix have infix notation (for general functions) or is that planned to be added? `on` is more readable infix (see example `((+) on f) x y` which is equivalent to `f x + f y`).


Yes, backticks convert a function call to infix:
```scala
def plus(a: Int, b: Int): Int = a + b

def main(): Int = 5 `plus` 4 // returns 9
```

**Comment by felixwiemuth** [comment]
### Regarding sort functions for `List` and `Nel`
Currently sorting for `List` is implemented with mergesort. Sorting for `Nel` can luckily be implemented based on that for `List` (converting it to a list temporarily by appending the head).

However, I just wondered whether mergesort is actually the right implementation for linked lists. Depending on how expensive datatype allocations are (which occur a lot in mergesort), it could be more efficient to convert the list to an array, do quicksort there and create a list from that.
- Contrary to what is stated, space for mergesort should be `n log n`; in the quicksort variant it would just be `2n` (allocating the temporary array in addition).
- In mergesort, the whole list is destructed and constructed at least once, so that would already somewhat cover the creation of the temporary array and the final list. The allocation of the array should not cost more than all the allocations for the temporary lists in mergesort.
- Now regarding the actual sorting, the read/write within the array is probably more efficient (as more cache-friendly, sequential memory) than accessing the pointers of the linked list and allocating new elements many times (`n log n`).

In addition, we would get rid of quite a bit of code if we don't need mergesort.
