### ISSUE TITLE
Integer Widening / ToInt64?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1946]
I would like to write:

```
def main(_: Array[String]): Int32 & Impure =
    let c = chan String 1;
    spawn slow(c);
    select {
        case m <- c                    => m
        case t <- Timer.seconds(5i64)  => "timeout" // Here the i64 suffix is required
    } |> println;
    0
```

The argument to `Timer.seconds` must be an `Int64`, but there would really be no harm in passing an `Int32` and widening it.

**Comment by stephentetley** [comment]
This can be faked with a type class like Haskell's `Integral` see its use in the "generic" version of the `Data.List` API here:  

https://downloads.haskell.org/~ghc/latest/docs/html/libraries/base-4.15.0.0/Data-List.html#g:26


Below uses a simpler `WidenInt` class without the mathematical functions of `Integral` :

~~~

pub lawless class WidenInt[a] {
    pub def widenInt(x: a): Int64
}
    
/// Instances for Int8, etc..

...

namespace Timer {

    pub seconds(x: a): Timer with WidenInt[a] = 
        implementation(widentInt(x))

}

~~~

**Comment by magnus-madsen** [comment]
I am not against this, but lets wait a bit and see how big the need is.
