### ISSUE TITLE
Postfix Function Applications

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1948]
This is one of those ideas that I hope is shot down, but let me bring it up anyway.

We could consider allowing postfix function applications, e.g. I want to write:

```
// in a library somewhere:
def ms(x: t): Time with ToInt64[t] = ...
def us(x: Int64): Time with ToInt64[t] = 

// and then somewhere else

let timeout = 5 ms
```

**Comment by mlutze** [comment]
Could this be the solution to all our UFCS problems?

**Comment by magnus-madsen** [comment]
> 
> 
> Could this be the solution to all our UFCS problems?

You mean turning Flix into some wierd haskell: `array length plus(1)`?

**Comment by magnus-madsen** [comment]
I am sure this is spectacularly bad idea, yet I crave for it... Better close before anyone implements it.
