### ISSUE TITLE
Implicit laws for overridden class definitions

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1949]
The purpose of allowing the override of class definitions is to allow more efficient implementations which produce the same result as the default implementation. It seems to me that we could then generate a law saying that the default implementation and the actual implementation are equivalent. This would require some compiler magic since generally overridden definitions are inaccessible.

Example:

```scala
class Length[a] {
  def length(x: a): Int
  def lengthIsEven(x: a): Bool = length(x) % 2 == 0
}

instance Length[EvenList[a]] {
  def length(x: EvenList[a]): Int = ???
  def lengthIsEven(x: a): Bool = true
}

// generated law (not real Flix):
forall(el: EvenList) . Length.default.lengthIsEven(el) == Length.override.lengthIsEven(el)
```

Perhaps we don't generate this for `unlawful` instances.

**Comment by magnus-madsen** [comment]
Yes, in some sense the class implementation can be used as the "specification".

**Comment by magnus-madsen** [comment]
Actually this is not true if you think about it. An instance must satisfy the laws-- nothing more. An overriding instance is allowed to vary its behavior (within the laws).
