### ISSUE TITLE
Functions for reverse ordering

### ISSUE THREAD

**Issue by felixwiemuth** [flix/flix#1951]
In #1560 we started discussing how to best provide possibilities to use the reverse order of an `Order` instance.

There are currently three options (see #1560 for details on 1 and 3):

1. Introduce a name (like "reverseCompare") for the function `flip(Order.compare)`
  - Maybe the most straight-forward and easy-to-use method
2. Add a `reverse` function to `Comparison` like in [Rust](https://doc.rust-lang.org/std/cmp/enum.Ordering.html#method.reverse); this can then be used like
   `sortWith((x,y) -> compare(x,y) |> reverse, xs)` - but this is maybe not much better than
   `sortWith((x,y) -> compare(y,x), xs)` - is there a way to compose the functions without naming the arguments?
  - This might even supersede no. 1: Flipping arguments and negating the comparison result is the same, just that the latter seems more intuitive and would maybe make the additional name "reverseCompare" superfluous.
  - Haskell doesn't seem to have that (its `Ordering` type doesn't have any instance that allows negation and there is no function `Ordering -> Ordering`).
3. Introduce a wrapper typeclass [`Down`](https://hackage.haskell.org/package/base-4.15.0.0/docs/Data-Ord.html#t:Down) like in Haskell (or [`Reverse`](https://doc.rust-lang.org/std/cmp/struct.Reverse.html) in Rust).
  - This can be helpful in more complex situations

As both 1/2 and 3 have their advantage, also both could be added. It could be useful to check more languages (e.g. Java, Kotlin).

See also #1945 for discussion on sorting functions.

**Comment by magnus-madsen** [comment]
Thanks for the write-up.

I think it is important to note that if we go with `Down` then people might expect the same pattern in other places, e.g. `Any`, `All`, `Dual`, `Sum`, `Mul`, etc. etc.
