### ISSUE TITLE
Add MutDeque

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1952]
TBD

**Comment by mlutze** [comment]
Will this be complemented by an immutable deque? (More generally, should every data type have an immutable equivalent)?

**Comment by magnus-madsen** [comment]
> Will this be complemented by an immutable deque? (More generally, should every data type have an immutable equivalent)?

Depends. For those data structures where an efficient immutable version exists, yes. For those where an immutable version is impractical, no.

For Deque, I don't know what the situation is. But I know that we will need something for the channel implementation.

**Comment by magnus-madsen** [comment]
Available in master.
