### ISSUE TITLE
let? and match?

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1953]
From _Programming Flix_:

>The following let-bindings are illegal because they are not exhaustive:
```scala
let (1, 2, z) = ...
let Some(x) = ...
```

We could do a partial deconstruction, similar to `let*`, where the result becomes `None` if the match fails:
```scala
let? (1, 2, z) = (1, 2, 3);
z
// result: Some(3)
```

```scala
let? (1, 2, z) = (4, 5, 6);
z
// result: None
```

**Comment by magnus-madsen** [comment]
Interesting idea! 

Is the return type always `Option`? What if you are working with a List or Result?

**Comment by magnus-madsen** [comment]
Maybe `Applicative.pure()`?

**Comment by mlutze** [comment]
Seems like what we need is Haskell's `MonadFail`:
https://hackage.haskell.org/package/base-4.15.0.0/docs/Prelude.html#t:MonadFail

**Comment by magnus-madsen** [comment]
OK- but it will be a bit before we have MonadFail, and also it seems to require multi param TCs?

Maybe we need an intermediate solution that can be generalized later.

For example, for `let*` we currently use the `flatMap` in scope. Soon we can change this to e.g. `Monad.flatMap`. So I wonder if a similar strategy could work here?

**Comment by mlutze** [comment]
I don't see where multi-param TCs are required; as far as I can tell we just need this:

```scala
pub class MonadFail[m: Type -> Type] with Monad[m] {
  pub def fail(): m[a]
  ... // law(s)
}
```

But yes, as a first step we can simply use a local `fail()` method or similar.

**Comment by magnus-madsen** [comment]
Ah- it seems Haskell and Scala Cats differ here.

**Comment by magnus-madsen** [comment]
It seems to me that we should make it work for Result:

https://doc.rust-lang.org/edition-guide/rust-2018/error-handling-and-panics/the-question-mark-operator-for-easier-error-handling.html

**Comment by magnus-madsen** [comment]
Or am I confusing things. Do we already have that with `let*`?

**Comment by mlutze** [comment]
> Or am I confusing things. Do we already have that with `let*`?

Yes, the rust `?` looks to me like a `flatMap` (= `let*`).

The critical detail is that the "failure" value is unspecified. For Option and List, that's ok because the "failure" value is empty. But for Result and Validation, that's not as simple because their failure case has to generate a value of the error type.

**Comment by magnus-madsen** [comment]
Since we can already do `let*` I am now less convinced that this feature is important.

Do we have a realistic killer example?

(I could easily see this being a feature that exists, is never used, and later used in "Flix puzzles").

Having `let+` (or other applicative do) seems more important.

**Comment by mlutze** [comment]
This is to some extent equivalent to Scala's partial functions, which I have found useful in the past.

This example matches the behavior of Scala's List.collect
```scala
// get all the elephant names
let* animal = animals;
let? Elephant(name) = animal;
name

// equivalent to
List.flatMap(a => a match {
  case Elephant(name) => Some(name)
  case _ => None
})(animals)

// maybe we could also/instead have a shortcut for lambdas specifically
List.flatMap(case? Elephant(name) => name)(animals)
```

**Comment by magnus-madsen** [comment]
What I don't understand is whether this is tied to `Option` or not. 

I think the last should be:

```scala
List.flatMap(match? Elephant(name) => name)(animals)
```

because that's how you write a match lambda. 

It seems what we are re-inventing is `PartialFunction` from Scala. I think we should look at how OCaml, Haskell, and Scala deal with this. I guess would be neat to write:

```scala
let elephants = List.filterMap(match? Elephant(name) -> name)
```

**Comment by magnus-madsen** [comment]
Follow up. Do we want:

```
let foo = match? animal {
  case Elephant(name) => name
}
```

as sugar for something? How would that work?

**Comment by mlutze** [comment]
A use-case that is longing for this is handling JSON structures. I'd like to do the following:
```scala
let* jsonElement = parse(jsonString);
let? JsonArray(firstPerson :: _) = jsonElement; // if this element is not an array, returns `None`
let? JsonObject(person) = firstPerson; // if this element is not an object, returns `None`
let* nameElem = Map.get("name", person);
let? JsonString(name) = nameElem;
name
...
```
