### ISSUE TITLE
Debate: Type Classes: Inliner Modifier

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1959]
We currently have:

```scala
instance Order[Int32] {
    pub override def less(x: Int32, y: Int32): Bool = $INT32_LT$(x, y)
    pub override def lessEqual(x: Int32, y: Int32): Bool = $INT32_LE$(x, y)
    pub override def greater(x: Int32, y: Int32): Bool = $INT32_GT$(x, y)
    pub override def greaterEqual(x: Int32, y: Int32): Bool = $INT32_GE$(x, y)

    pub def compare(x: Int32, y: Int32): Comparison = ...
}
```

I think it would be nice if we could declare:

```scala
instance Order[Int32] {
    pub override inline def less(x: Int32, y: Int32): Bool = $INT32_LT$(x, y)
    pub override inline def lessEqual(x: Int32, y: Int32): Bool = $INT32_LE$(x, y)
    pub override inline def greater(x: Int32, y: Int32): Bool = $INT32_GT$(x, y)
    pub override inline def greaterEqual(x: Int32, y: Int32): Bool = $INT32_GE$(x, y)

    pub def compare(x: Int32, y: Int32): Comparison = ...
}
```

and then during `Monomorphization` we would replace a call to `Order.lessEqual` on `Int32` with the actual body of the signature. (Note: We must be careful that the arguments are still evaluated in the right order).

Questions:
- Do we want this?
- Does the `inline` modifier belong on instances (or should it be on classes or elsewhere)?
- Is Monomorph the right phase for this?
- Why even have an inline modifier...

**Comment by mlutze** [comment]
> Does the inline modifier belong on instances (or should it be on classes or elsewhere)?

I think anything that is in the "spec" of a type class member should be observable. Since inlineness is not observable, the instance definition seems to be the right place to do it.

> Why even have an inline modifier...

This is my question. Can we instead have heuristics that will determine which functions are good for inlining?

**Comment by magnus-madsen** [comment]
The problem with heuristics is that they are hard to reason about: "Will this be inlined?" "Oh depends on some inline score".

We could, of course, try some criteria: E.g.

- If a body exp is only a use of an intrinsic (as above) it is always inlined.
- If a body exp is a single taill call it is inlined.
- and so forth.

**Comment by mlutze** [comment]
Here are a few options I'm thinking about, in my order of preference:

1. Totally heuristics-based
  * No inline modifier. The compiler automatically inlines anything it thinks will be more efficient/better as inlined.
  * Pros: User has less to consider, little risk of inlining inappropriately
  * Cons: No direct control over behavior
2. Implicit with override
  * We have some heuristics, but you can override these by applying the inline modifier.
  * Pros: Catches the easily inlined calls. Allows inlining where the heuristics wouldn't normally call for it.
  * Cons: Not clear what will and won't be inlined. Might inline inefficiently.
3. Totally explicit
  * Inline when told to.
  * Pros: Very obvious what will inline. Allows inlining where the heuristics wouldn't normally call for it.
  * Cons: Will possibly miss a lot of easily inlined calls. Might inline inefficiently.
4. Explicit under constraints (Scala)
  * Inline modifier is a "hint", but if the function is too big, then it is not inlined.
  * Pros: Prevents some inefficient inlining.
  * Cons: Not clear what will and won't be inlined. Could still miss some easily inlined calls.

The main reason I prefer 1 is that it allows the compiler to make (semantically) safe optimizations without being explicitly told to do so (unlike 2 and 4), and that it doesn't give any illusion of choice in the matter (unlike 3 and 4).

As a user, I much prefer trusting the compiler to be smarter than I am. But I also see how it might be important to control inlining in performance-critical code.

**Comment by magnus-madsen** [comment]
Let's not have an inline keyword. We can instead define a collection of criteria and promise to fulfill those.
