### ISSUE TITLE
Polymorphic literals

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1968]
In Haskell, the literal `5` actually represents something more like `Num.fromInteger 5`, converting 5 to a generic member of the typeclass `Num`. https://www.haskell.org/onlinereport/haskell2010/haskellch6.html#x13-1360006.4.1

Pros:
* Improved brevity in generic code

Cons:
* Possibly more ambiguity issues
* Possibly worse error messages
* Overall increase in complexity

Not sure if it's worth it.

**Comment by magnus-madsen** [comment]
I am currently leaning towards "not worth" because of:

- Possibly more ambiguity issues
- Possibly worse error messages

Especially the latter with generalization errors that are hard to understand.

**Comment by magnus-madsen** [comment]
We can discuss it in the future. Possibly if we switch `Int` to be `BigInt`.
