### ISSUE TITLE
Improve support of UTF8 operators

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#197]
Find out what UTF8 operators to support, or come up with a generic scheme. 

Investigate what is done in other languages.

**Comment by mhyee** [comment]
Are these going to be built-in operators?

I think I'd prefer the approach where we don't provide built-in UTF8 operators, but provide some sort of library/import that aliases UTF8 operators.

**Comment by magnus-madsen** [comment]
I am going to remove UTF-8 ops (since they are not currently used and the implementation is brittle). Then I want to come up with a general purpose scheme that is useful.

**Comment by magnus-madsen** [comment]
Fixed.
