### ISSUE TITLE
Gitter.im seems flaky

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1974]
Hopefully they will be back to normal soon?

**Comment by magnus-madsen** [comment]
Is anyone else having problems?

**Comment by mlutze** [comment]
I haven't received any messages, but maybe I am just not that popular.

**Comment by magnus-madsen** [comment]
Can you reach the front page? Half the time it times out for me.

**Comment by mlutze** [comment]
I haven't noticed any problems with it, though I use the phone app more often than the webpage.

**Comment by magnus-madsen** [comment]
Seems better.
