### ISSUE TITLE
Writing a simple REPL

### ISSUE THREAD

**Issue by anthonyjclark** [flix/flix#1976]
Hello,

I am having two issues attempting to write a simple REPL. Here is simplified version of my current attempt.

```
def loop(): Unit & Impure =
    Console.print("repl> ");
    match Console.readLine() {
        case Some("q") => ()
        case Some(line) => Console.printLine(line); loop()
        case None => ()
    }

def main(): Unit & Impure = loop()
```

I'd like to be able to send EOF to quit the loo, but when I do so I get the following exception:

```
repl> Exception in thread "main" java.util.NoSuchElementException: No line found
        at java.base/java.util.Scanner.nextLine(Scanner.java:1651)
        at flix.runtime.library.Console.readLine(Console.java:9)
        at Console.StdIn.Clo$readLine$59979.invoke(Unknown Source)
        at Console.StdIn.Def$readLine.invoke(Unknown Source)
        at Def$loop.invoke(Unknown Source)
        at Ns.m_main(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$link$1(JvmBackend.scala:243)
        at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$getCompiledDefs$2(JvmBackend.scala:216)
        at ca.uwaterloo.flix.runtime.CompilationResult.evalToString(CompilationResult.scala:90)
        at ca.uwaterloo.flix.Main$.$anonfun$main$6(Main.scala:189)
        at ca.uwaterloo.flix.util.Timer.<init>(Timer.scala:28)
        at ca.uwaterloo.flix.Main$.main(Main.scala:189)
        at ca.uwaterloo.flix.Main.main(Main.scala)
```

Another issue is that even if I quick by typing a `q`, I end up with `Unit` being printed, and I'd rather suppress that output.

```
myprompt> flix repl.flix
repl> test
test
repl> again
again
repl> q
()
```

I apologize if these are obvious, but I could not find answers digging through the repository and issues.

(I really like what I see in this language and the documentation!)

**Comment by magnus-madsen** [comment]
Hello @anthonyjclark and welcome to our small community :)

I am away on travel right now, but it looks like you may have found a bug in our library.

Possibly you could try to write your own readLine using Java directly:

https://doc.flix.dev/interoperability/

Ill try to get back to you soon.

**Comment by magnus-madsen** [comment]
Untested, but maybe helpful:

```
type alias InputStream = ##java.io.InputStream
type alias PrintStream = ##java.io.PrintStream

pub def main(_args: Array[String]): Int32 & Impure = 
    import new java.util.Scanner(InputStream) as newScanner;
    import java.util.Scanner.hasNextLine() as hasNextLine;
    import java.util.Scanner.nextLine() as nextLine;
    import get java.lang.System:out as out;
    let o = out() as InputStream; // safe up cast
    let s = newScanner(o);
    if (hasNextLine(s)) {
        let l = nextLine(s);
        println(l);
        0
    } else 
        0
```

**Comment by anthonyjclark** [comment]
Thanks! I'll give it a try as soon as I can. I have zero Scala experience, but I can dig into this a bit more if helps.

(Also, feel free to re-title this since it might be a bug.)

**Comment by mlutze** [comment]
It seems that the stdlib `Console` depends on runtime `Console`. But `Console` was removed from runtime over a year ago: https://github.com/flix/runtime/commit/3acc9b5bded055f6a147c23ba516a276fab768e9

I assume we're supposed to be using the up-to-date runtime, and that changing the stdlib to use Java interop is the right solution for this problem.

At a higher level, do we need a better dependency management strategy? Currently all dependencies are checked in to git, which is atypical as far as I know. We're already using Gradle for automated builds, so _theoretically_ transitioning to a download-dependencies-kind-of-thing wouldn't be too difficult.

**Comment by magnus-madsen** [comment]
> It seems that the stdlib `Console` depends on runtime `Console`. But `Console` was removed from runtime over a year ago: [flix/runtime@3acc9b5](https://github.com/flix/runtime/commit/3acc9b5bded055f6a147c23ba516a276fab768e9)

I think we need to implement `Console.*` using Flix interop.

> At a higher level, do we need a better dependency management strategy? Currently all dependencies are checked in to git, which is atypical as far as I know. We're already using Gradle for automated builds, so _theoretically_ transitioning to a download-dependencies-kind-of-thing wouldn't be too difficult.

The short-term goal is to get rid of `flix-runtime.jar`. 

Longer term, we should get rid of all our dependencies.

Also longer term, we should start to rewrite parts of the compiler in Flix.

The reason the libraries are checked into Git is because (1) all build tools seem terrible, (2) we want very fine grained control over what exactly goes in the compiler (no unhappy surprises).

**Comment by magnus-madsen** [comment]
As for this bug, I think someone needs to update `Console.flix`. 

Maybe @anthonyjclark can report back whether the proposed code seems to work.

**Comment by anthonyjclark** [comment]
I just opened up my project again in VS Code and the Flix extension updated the compiler to 0.15. After making a few changes to `main` and `testMain01` (the newer compiler appears to require an `Int` return from `main`), I was able to run the original code without any exception.

It does print `No line found` to STDOUT though.

The suggested code from @magnus-madsen above results in the following error:

```
class java.io.PrintStream cannot be cast to class java.io.InputStream (java.io.PrintStream and java.io.InputStream are in module java.base of loader 'bootstrap')
```

I did not dig into this since the 0.15 release fixes the main problem. Let me know if you want me to try anything else out.

(It would also be preferable if I could suppress the `No line found` message.)

**Comment by magnus-madsen** [comment]
OK, I think we still need to do some digging/refactoring in `Console`. 

I will get to it, but if you are not blocked right now (?), it may be a bit.

**Comment by anthonyjclark** [comment]
No rush at all.

**Comment by magnus-madsen** [comment]
The example should be:

```
type alias InputStream = ##java.io.InputStream
type alias PrintStream = ##java.io.PrintStream

pub def main(_args: Array[String]): Int32 & Impure =
    import new java.util.Scanner(InputStream) as newScanner;
    import java.util.Scanner.hasNextLine() as hasNextLine;
    import java.util.Scanner.nextLine() as nextLine;
    import get java.lang.System:in as in;
    let i = in() as InputStream; // safe up cast
    let s = newScanner(i);
    if (hasNextLine(s)) {
        let l = nextLine(s);
        println(l);
        0
    } else
        0
```

**Comment by magnus-madsen** [comment]
Fixed in master. Will be in the next flix.dev/nightly.

**Comment by magnus-madsen** [comment]
@anthonyjclark Let me know if you have further questions or comments! We are happy to help.

**Comment by anthonyjclark** [comment]
Thank you. I don't have any questions at this time. I appreciate your help.
