### ISSUE TITLE
Auto-Complete Snippets

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1977]
We should collect a list of snippets for code completion in VSCode. For example, a snippet could be:

```
def ${1|function_name|}(${2|arg|}:${3|arg_type|} ): ${4|return_type|} = \n
```

I propose the following strategy:

- Look through https://github.com/flix/flix/tree/master/main/src/library for programming patterns.
- Look through the parser https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Parser.scala for keywords.

One question is how many snippets we should have, i.e. where to stop? For example, do we need a snippet for `let`?

Another questions is a good naming strategy for the placeholders in snippets.

**Comment by magnus-madsen** [comment]
Let me begin by contributing this snipppet:

```
query ${1|db} select ${2|cols} from ${3|preds} where ${4|cond}
```

**Comment by mlutze** [comment]
I'd like to understand a little more the user experience. Here's what I understand:
1. User types `def`
2. A prompt comes up offering the rest of the snippet
3. User presses `<tab>` to accept the prompt
4. The snippet appears on screen with the cursor at argument `n`
5. User fills in arg `n`
6. User presses `<tab>`
7. `n++; goto 4;`

Is that right?

**Comment by manoj2601** [comment]
yes, user can either press `<tab>` or `<enter>` to accept the prompt. Also, when the user types some string to fill arg `n`, it replaces the default string which appears at that position in the snippet.

**Comment by manoj2601** [comment]
I have listed some snippet ideas for auto-completions:

| completion Item | insertText (Snippet) | Documentation |
| -------------- | --------------------- | ------------- |
| match | `match ${1:x} {\n    case ${2:a} => ${3:/* code */} \n    case ${4:_} => ${5:/* code */} \n}` | code snippet for pattern match |
| def | `def ${1:function_name}(${2:arg}:${3:arg_type}): ${4:return_type} = \n` | code snippet to define a function |
| if | `if (${1:/* condition */}) {\n\t /* code */ \n}` | code snippet for if () |
| elif | `else if (${1:/* condition */}) {\n\t /* code */ \n}` | code snippet for else if () |
| else | `else {\n\t /* code */ \n}` | code snippet for else |
| enum | `enum ${1:Sample} { \n\tcase ${2:dataType1},\n\tcase ${3:dataType2}\n\t${4:/* add more algebric data types */}\n}` | code snippet for enum |
| opaque | `opaque type ${1:name} = ${2:type}` | code snippet for opaque type |
| type alias | `type alias $1 = $2` | code snippet for type alias |
| namespace | `namespace ${1:sample} {\n\t /* code */ \n}` | code snippet to create namespace |
|  try-catch | `try { \n\t/* code */\n} catch {\n\t/* code */\n}` | code snippet for try-catch |
| fact | `${1:Sample}(/* terms */).` | code snippet for fact |
| rule | `${1:Parent}(${2:/* terms */}) :- ${3:Child1}(${4:/* terms */}), ${5:Child2}(${6:/* terms */}).` | code snippet for rule |
| query | `query ${1:db} select ${2:cols} from ${3:preds} where ${4:cond}` | code snippet for query |
| rel | `rel ${1:Sample}(${2:x}: ${3:type}, ${4:y}: ${5:type})` | code snippet to declare predicate symbol |
| @ Annonation | `@${1\|Time, Space}($2)` | function Annonations |
| main | `def main(args: Array[String]) : Int32 & Impure = \n\t /* code */ \n0` | code snippet for main () |
| println | `println($1)` | print to standard output with newline |
| print | `print($1)` | print to standard output without newline |
| instance | `instance ${1:sample}[${2:type}] { \n\t/* code */ \n}` | code snippet for instance |


some commonly used flix keywords are listed here:  

| completion Item | insertText (Snippet) | Documentation |
| -------------- | --------------------- | ------------- |
| let | `let` | flix keyword |
| use | `use` | flix keyword |
| case | `case` | flix keyword |
| as | `as` | flix keyword |
| new | `new` | flix keyword |
| Unit | `Unit` | flix keyword |
| Bool | `Bool` | flix keyword |
| Char | `Char` | flix keyword |
| Float | `Float` | flix keyword |
| Float32 | `Float32` | flix keyword |
| Float64 | `Float64` | flix keyword |
| Int | `Int` | flix keyword |
| Int8 | `Int16` | flix keyword |
| Int32 | `Int32` | flix keyword |
| Int64 | `Int64` | flix keyword |
| String | `String` | flix keyword |
| BigInt | `BigInt` | flix keyword |
| None | `None` | flix keyword |
| Some | `Some($1)` | flix keyword |
| Pure | `Pure` | flix keyword |
| Impure | `Impure` | flix keyword |
| Nil | `Nil` | flix keyword |
| pub | `pub` | flix keyword |
| true | `true` | flix keyword |
| false | `false` | flix keyword |
| rel | `rel` | flix keyword |
| type | `type` | flix keyword |
| Console | `Console` | flix keyword |
| select | `select` | flix keyword |
| spawn | `spawn` | flix keyword |
| chan | `chan` | flix keyword |
| ref | `ref` | flix keyword |
| deref | `deref` | flix keyword |
| println | `println` | flix keyword |
| print | `print` | flix keyword |
| import | `import` | preprocessor keyword |

**Comment by magnus-madsen** [comment]
Available in master.
