### ISSUE TITLE
What information should be shown during auto-complete?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1983]
We need to decide what auto-complete should show.

For example:

![image](https://user-images.githubusercontent.com/2287953/121138004-909e9300-c837-11eb-8eba-1b24f1309f0f.png)

***Would it be better if the label on the left was `List.drop(n: Int32, l: List[...])` and on the right we could have the doc comment?***

**Comment by magnus-madsen** [comment]
@mlutze @manoj2601 @JonathanStarup

**Comment by magnus-madsen** [comment]
Better or worse?:

![image](https://user-images.githubusercontent.com/2287953/121139480-1707a480-c839-11eb-9ed9-20f0a7802d4e.png)

**Comment by magnus-madsen** [comment]
By the way- isn't it amazing that we are in a place where we can start to offer auto-complete? 😀 🥳 🚀

**Comment by magnus-madsen** [comment]
Idea has return type on the right:

![image](https://user-images.githubusercontent.com/2287953/121141928-c80f3e80-c83b-11eb-96b6-be92203fc13c.png)

I quite like that

**Comment by mlutze** [comment]
Do we control the icons on the left? Maybe effect information can be shown there?

**Comment by magnus-madsen** [comment]
> 
> 
> Do we control the icons on the left? Maybe effect information can be shown there?

Yes, but they have to be in this set:

![image](https://user-images.githubusercontent.com/2287953/121153045-06a9f680-c846-11eb-8be4-5f24dea16dc2.png)
