### ISSUE TITLE
Maintain a bit more information in TypedAst

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1984]
In particular:

- I think `Spec` should have a `tpe` which is the declared return type of the def/sig. (It currently only has eff).
  - THIS SHOULD NOT BE USED. Internally we should always use the scheme!
- I think every expression should carry some information about TC constraints. (Not sure how to do it).
- `tpeDeprecated` should be removed from `Enum`.

***This information is not so much for the compiler, but for VSCode etc.***

**Comment by mlutze** [comment]
`Enum.tpeDeprecated` is used in `JvmOps`. I'm not so familiar with that part of the compiler. What's the strategy for losing our dependency on this field?

**Comment by magnus-madsen** [comment]
> `Enum.tpeDeprecated` is used in `JvmOps`. I'm not so familiar with that part of the compiler. What's the strategy for losing our dependency on this field?

New JVM backend
