### ISSUE TITLE
Outreach

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1989]
As a continuation of #1988, I think it would be useful to reach out to the media and see if they want to do a story on Flix. 

We have a few unique features (with more on the way) that might be interesting to a broader audience. For example, our support for first-class Datalog constraints. What other topics could be interesting at this time?

What media could be relevant? Here are some ideas (I don't really follow many of these):
- [x] InfoQ?
- [ ] InfoWorld?
- [ ] zdnet?
- [ ] techcrunch?
- [ ] techrader? (are these the same?)
- [ ] hackernoon?
- [x] reddit.com/r/programminglanguages (been there already)
- [x] HackerNews (been there already)
- [ ] Lobstrs?
- [ ] Lambda the Ultimate?
- [ ] Sigplan Blog
- [x] ComputerWorld (A danish newspaper).
- [x] Ingeniøren/Version2 (A danish newspaper for engineers).

In addition, we should also focus on writing some blog posts and publicizing them. 

Another question is: Is there somewhere that would be friendly to a post where we invite new developers?

**Comment by mlutze** [comment]
There are options like [up-for-grabs](https://github.com/up-for-grabs/up-for-grabs.net) which aggregate issues for potential contributors to discover.
