### ISSUE TITLE
Internal and External Syntax for Type Variables

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1993]
Proposal for discussion:

| Notation| Description |
| ------------- | ------------- |
| a  | A type variable of kind Type.  |
| a!  | A rigid type variable of kind Type.  |
| ^a  | A type variable of kind Bool.  |
| ^a!  | A rigid type variable of kind Bool.  |
| `a  | A type variable of kind Record.  |
| `a!  | A rigid type variable of kind Record.  |
| #a  | A type variable of kind Scheme.  |
| #a!  | A rigid type variable of kind Scheme.  |

I don't know. Maybe it becomes impossible.

**Comment by mlutze** [comment]
I'm anticipating some complaint about all the ugly symbols in the error output.
In general, I prefer words over symbols, but something like `a_Bool_rigid` would become verbose very quickly.

Maybe we could add an epilogue to the error output:

```
... Type 2: a -> b & e

where
a is rigid and has kind Type
b is flexible and has kind Type
e is flexible and has kind Bool
```

That may be overly verbose as well, but maybe we could be smart somehow and only include it when it's relevant?

It doesn't address the problem much outside of error messages though.

**Comment by magnus-madsen** [comment]
> I'm anticipating some complaint about all the ugly symbols in the error output.
> In general, I prefer words over symbols, but something like `a_Bool_rigid` would become verbose very quickly.
> 
> Maybe we could add an epilogue to the error output:
> 
> ```
> ... Type 2: a -> b & e
> 
> where
> a is rigid and has kind Type
> b is flexible and has kind Type
> e is flexible and has kind Bool
> ```
> 
> That may be overly verbose as well, but maybe we could be smart somehow and only include it when it's relevant?
> 
> It doesn't address the problem much outside of error messages though.

Agree.

I was writing for *internal use*. For *external use* we should use your approach!

**Comment by magnus-madsen** [comment]
Since we have the kinder now, is this less relevant?

**Comment by mlutze** [comment]
Less relevant, but still possibly useful especially as long as we have subkinding.

**Comment by magnus-madsen** [comment]
In retrospect this not a good idea. But it would be a good idea for error messages to print the kinds of the type variables involved.

**Comment by magnus-madsen** [comment]
I decided for the following intermediate approach:

- Type variables of kind Star: `t0` ...
- Type variables of kind Bool `b0` ...
- Type variables of kind RecordRow `r0` ...
- Type variables of kind SchemaRow `s0` ...
- Type variables of kind Predicate -- `'0` ...
- Type variables of kind Arrow - `'0` ...
- Rigid type variables suffixed with `!`.
