### ISSUE TITLE
Tweaks to the Types of References

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1999]
A reference is currently given the type `Ref[t]`. 

I am thinking of making the following changes (in relation to our experiment on regions):

The new type of references will be:

```
ScopedRef[t: Type, b: Bool]
```

and then all operations will work on `ScopedRefs`. 

However, not all references will be scoped, hence it makes sense to define:

```
type alias Ref[t] = ScopedRef[t, false]
```

In prelude, as an alias for references where we do not care about their life time.

**Comment by mlutze** [comment]
What would you say about flipping the order of the parameters? It would avoid a type lambda, which doesn't cooperate well with type classes.

**Comment by magnus-madsen** [comment]
> 
> 
> What would you say about flipping the order of the parameters? It would avoid a type lambda, which doesn't cooperate well with type classes.

I don't understand. Whats the problem?

**Comment by mlutze** [comment]
This type alias
```scala
type alias Ref[t] = ScopedRef[t, false]
```
is equivalent to this type lambda
```scala
type Ref = lambda t -> ScopedRef[t, false] // not real syntax
```
There isn't a way to do this with partial application.

Changing the order of the params:
```scala
type alias Ref[t] = ScopedRef[false, t]
```
Allows us to to perform partial application and avoid the type lambda:
```scala
type alias Ref = ScopedRef[false]
```

Say we have a type class:
```scala
class Gettable[a: Type -> Type] {
  def get(x: a[b]): b
}
```
The first of these doesn't work with this type class because of the type lambda. The second one does work.

**Comment by mlutze** [comment]
See also https://github.com/flix/flix/issues/1535

**Comment by magnus-madsen** [comment]
Thanks for the explanation. I agree with the sentiment, but I am not doing to do it right now. (Just because there are many other difficulties). I can imagine in the final design we will either fix type lambda or reverse the order of the arguments! So I agree- just can't deal with it right now :)

**Comment by magnus-madsen** [comment]
`ScopedRef` is in master. Next up is `ScopedArray`.
