### ISSUE TITLE
Shadow Defs

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2000]
Here is an idea (probably not that great):

We should allow two versions of a function definition: one for the public and one with the actual code.

For example, the public version of `List.flatMap` could be:

```scala
    pub def flatMap(f: a -> List[b] & e, xs: List[a]): List[b] & e = match xs {
        case Nil => Nil
        case x :: rs => f(x) ::: flatMap(f, rs)
    }
```

which is short and idiomatic.

However, it is also slow and non-tail recursive. Hence we should have another implementation:

```scala
    pub shadow def flatMap(f: a -> List[b] & e, xs: List[a]): List[b] & e = m
      // all kinds of ugly hacks for performance.
```

**Comment by mlutze** [comment]
I think this is interesting. In some ways it is syntactic sugar for laws. (I wonder how it could work in type classes!) 

I would prefer that the actual "used" code not be special, and instead that the pretty unused code be the one that we mark. Maybe `facade` or something. That way, if someone doesn't know about this feature they can ignore it. (Layered language, least surprise)

And of course, we can have an implicit law saying `forall(x: t) . f(x) == facade_of_f(x)`
