### ISSUE TITLE
Controversial Design Choice: Purity Implies Termination

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2007]
I would like to propose the following:

- The Flix compiler is allowed to assume that a pure expression eventually terminates.

Consequently the following program:

```
let x = loop() // loop is pure;
if (true) { 1 }  else { x } 
```

may terminate because Flix is allowed to move `x` inside the if-then-else.

**Comment by magnus-madsen** [comment]
This may break "stupid"/"unsafe" code like:

```
let x = ref 0;
(x := 1) as & Pure;
deref x
```

but not:

```
{
let x = ref 0;
(x := 1)
deref x
} as & Pure
```

**Comment by mlutze** [comment]
What are the implications of this on "benign" impurity? E.g.

```
def getCard(): Card = {
  ...
  let _ = log("Got card ${card}!"); // Log is a benign impure function: technically impure, but marked pure
  card
}

...
let card = getCard();
if (true) then { defaultCard } else { card }
```

That log statement would never happen in this case, even though it might seem to the user that it should.
Is this a concern?

**Comment by magnus-madsen** [comment]
The Flix compiler will assume that all pure computations eventually terminate. If that is not the case, an expression must be marked as impure.
