### ISSUE TITLE
Compiler Optimizations

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2008]
Basically we need two phases:

Occurs:

Collect information about each sub-expression and each variable:
- How many times are each local variable used?
- Is the expression constant?
- Is the expression branchless?
- Is the expression constant modulo variables?
- Does the expression consist of a single (non-self) call with constant arguments modulo variables?
- Does the expression consist of a single unary/binary operation with constant arguments modulo variables?
- Does the expression consist of a single closure with constant arguments modulo variables?

Inliner:

Use this information to rewrite the AST:

- If a let-bound variable is not used *and* its expression is pure => remove it.
- If a let-bound variable is used *once* *and* its expression is pure => inline it.
- Inline expressions that are constants modulo variables.
- Inline expressions that consistent of a single call with constants modulo variables.

Steps
- Introduce `Occurrences` data type to `LiftedAst`.
- Use `Occurrences` in `LiftedAst`.
- Write `Occurs` phase.
- Use `occurs` inside `Inliner`.
- Add effects to `LiftedAst`.

**Comment by nicdard** [comment]
Hi! I would like to work on this :)

**Comment by nicdard** [comment]
Actually I find `Inliner.scala` in the code base that seems to implement this

**Comment by magnus-madsen** [comment]
Implemented.
