### ISSUE TITLE
Optimize MutList

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2009]
- Change the default/initial size to `8`. (This implies other changes. For example `push!` can now assume the length is never 1).
- Change `toImm` not to use `foldRight`, but instead to a directly tail recursive function. (You will probably need a helper function).

**Comment by jaschdoc** [comment]
> (This implies other changes. For example push! can now assume the length is never 1).

I'm not quite sure I follow this. Assume the user calls `new()` to create a new MutList `l`, after which they decide to call `MutList.shrinkTo(1, l)`. The result would then be a MutList of length 0. The user then calls `push!`. If `push!` assumes that the array can never be less than length 8 it would probably cough up some error. On the other hand if the rule is enforced that the length can **never** be less than 8 (and not just the initial size), the functionality of `shrinkTo!` would then be slightly less obvious and arguably reduced slighty.

**Comment by magnus-madsen** [comment]
Intuitively there is a number MIN_SIZE and this is the initial size and a shrink can never go below that.

**Comment by jaschdoc** [comment]
Alright, that resolves the problem then.

**Comment by jaschdoc** [comment]
Is your intention for `toImm` to be tail recursive? If so, `MutList.foldRight` is already tail recursive since it simply iterates over the array from the end index to 0 and applying `f` to each element.

**Comment by magnus-madsen** [comment]
> Is your intention for `toImm` to be tail recursive? If so, `MutList.foldRight` is already tail recursive since it simply iterates over the array from the end index to 0 and applying `f` to each element.

Yes, tail recursive.
