### ISSUE TITLE
Easy Upgrade

### ISSUE THREAD

**Issue by mlutze** [flix/flix#2023]
Crazy idea, inspired by the old `Linter` phase:

Sometimes when a function or such is deprecated, there's a message like "use getFoo instead".
Supposing a significant number of deprecations have an easy fix, I'm wondering if it's possible to create an "easy upgrade" operation for the packager.

Example:

```scala
...
/// The old deprecated function
@deprecated("The parameter y is redundant. Use newFoo instead.", upgradeFoo)
pub def foo(x: Int, y: Int, z: Bool): Int = {
  ...
}

/// The new recommended function
pub def newFoo(x: Int, z: Bool): Int = {
  ...
}

/// The upgrade format
upgrade upgradeFoo: forall (x: Int, y: Int, z, Bool) . foo(x, y, z) `convertsTo` newFoo(x, z)
```

For the author of the package, this creates a hidden `law` saying `forall (x: Int, y: Int, z, Bool) . foo(x, y, z) == newFoo(x, z)`.

For consumers of this package, this enables an "easy upgrade" option: when they use this option, it goes through their code and changes every instance of `foo(x, y, z)` to `newFoo(x, z)`, removing references to the old deprecated method.

Problems:
* I'm not sure how many deprecations are really this easy
* With first-class functions, I don't think this is decidable

But maybe there's something there.

**Comment by magnus-madsen** [comment]
Cool idea, but not a priority. Once we have users :)

**Comment by magnus-madsen** [comment]
(EDIT: We have like 2 deprecated functions :P)

**Comment by JonathanStarup** [comment]
this reminds me of the local work  [jsfix](https://jsfix.live/frontpage). its sounds cool but probably requries program analysis for a general solution
