### ISSUE TITLE
LazyList

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2033]
Step 1:

- Move `LazyList` and `LazyList2` out of the way. (E.g. to `OldLazyList` or just delete them outright).

Step 2: 

- Define a new `LazyList`:

```
pub enum LazyList[a] {
    case ENil,
    case ECons(a, LazyList[a]),
    case LCons(a, Lazy[LazyList[a]]),
    case LList(Lazy[LazyList[a]])
}
```

Step 3:

- Add core operations such as `filter`, `map`, `head`, etc.

Step 4:

- Add other operations.

Step 5:

- Add `Functor` and `Foldable` instances (?)

Step 6:
- Add syntactic sugar for lazy cons? (Scala uses `#::` I believe)

**Comment by magnus-madsen** [comment]
@jaschdoc @mlutze What are your thoughts on adding `e1 ::# e2` as syntactic sugar for `LazyCons(e1, lazy e2)`?

**Comment by magnus-madsen** [comment]
Is it possible to have type classes for `::` and `::#`?

**Comment by mlutze** [comment]
> What are your thoughts on adding `e1 ::# e2` as syntactic sugar for `LazyCons(e1, lazy e2)`?

A couple concerns:
1. We're hiding the `lazy`, which may be unintuitive. (Though since lazy stuff is pure, this shouldn't be a problem(?)).
2. This would be the only other right-associative operator. Scala makes all operators that end with `:` right-associative; maybe that's something to consider?

**Comment by mlutze** [comment]
> Is it possible to have type classes for `::` and `::#`?

I think so, though some magic would have to happen for the laziness.

**Comment by jaschdoc** [comment]
What is the benefit of reversing the operator syntax compared to Scala? If [Scala uses `#::`](https://www.scala-lang.org/api/2.12.9/scala/collection/immutable/Stream.html#%23::%5BB%3E:A%5D(hd:B):scala.collection.immutable.Stream%5BB%5D) then why use `::#`? Why not simply stick with `#::`? I think that would only cause confusion for people new to flix which already has syntax similar to Scala (and Rust).

**Comment by magnus-madsen** [comment]
> What is the benefit of reversing the operator syntax compared to Scala? If [Scala uses `#::`](https://www.scala-lang.org/api/2.12.9/scala/collection/immutable/Stream.html#%23::%5BB%3E:A%5D(hd:B):scala.collection.immutable.Stream%5BB%5D) then why use `::#`? Why not simply stick with `#::`? I think that would only cause confusion for people new to flix which already has syntax similar to Scala (and Rust).

Thats my bad. I remember it wrong!

**Comment by jaschdoc** [comment]
> > What is the benefit of reversing the operator syntax compared to Scala? If [Scala uses `#::`](https://www.scala-lang.org/api/2.12.9/scala/collection/immutable/Stream.html#%23::%5BB%3E:A%5D(hd:B):scala.collection.immutable.Stream%5BB%5D) then why use `::#`? Why not simply stick with `#::`? I think that would only cause confusion for people new to flix which already has syntax similar to Scala (and Rust).
> 
> 
> 
> Thats my bad. I remember it wrong!

Ah no worries then 😃
