### ISSUE TITLE
MutableFunctor class

### ISSUE THREAD

**Issue by mlutze** [flix/flix#2039]
Has a `transform!` function rather than a `map` operation.

Could apply to any mutable collection:
* `Ref`
* `Array`
* `Mutlist`
* etc.

**Comment by magnus-madsen** [comment]
Interesting. Is there a case where we want `MutableFunctor` as a type class contraint? I.e. where you want to abstract over ref and array?

**Comment by mlutze** [comment]
A (contrived, as usual) example:

```
def incrAll!(c: c[Int]): Unit & Impure with MutableFunctor[c] = {
  MutableFunctor.transform(i => i + 1, c)
}
```

Which works whether it's a list or an array.

**Comment by magnus-madsen** [comment]
Closing. We can reopen if we see a real use case ;)
