### ISSUE TITLE
Interop from Java

### ISSUE THREAD

**Issue by mlutze** [flix/flix#2043]
Currently we can use Java code from Flix, but as far as I can tell, there's not much support for calling Flix code from Java.
I'd guess that there are some major challenges, given the differences in type systems.

**Comment by magnus-madsen** [comment]
Challenges include:
- Different calling conventions.
- Instability of generated bytecode.
- Mismatch of type systems.

**Comment by magnus-madsen** [comment]
This is a non-goal. But it is a goal to have a nice facade: https://github.com/flix/flix/issues/2359

For example, we could allow you to tag non-polymorphic functions with an `export` keyword and then we would generate a stable ABI for that.
