### ISSUE TITLE
Testing quality of life changes

### ISSUE THREAD

**Issue by mlutze** [flix/flix#2047]
When compilation failures come up in *.flix files, it causes all tests in the file to show errors, which make it a pain to see exactly where the error is coming from.

I propose that `*.flix` tests which are testing compilation behavior (as opposed to computational behavior) should either be put into individual files for testing, or put into `*.scala` testing suites, in order to keep them independent.

**Comment by magnus-madsen** [comment]
Use many files => performance issues.
Put into .scala files => very bad performance issues.

If we are willing to live with that we can do it. It will kill the PI though. 

I don't see any good solution atm. I think optimizing for the common case- all tests pass make sense.

Feel free to reopen if we have better ideas.
