### ISSUE TITLE
Add back benchmark-on-demand

### ISSUE THREAD

**Issue by mlutze** [flix/flix#2053]
We previously removed this because it was fairly noisy. But I think it may be worth bringing it back, since even with some inconsistencies, it's able to detect large changes.

**Comment by mlutze** [comment]
Just need to adjust the old script to use the json output.

**Comment by magnus-madsen** [comment]
🤖 🤖 🤖 🤖

**Comment by mlutze** [comment]
Maybe the robot emoji will be the new command word
