### ISSUE TITLE
Automatic Parallelization of Purity Polymorphic Functions

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2054]
Milestone 1:
- [x] #2336

Milestone 2:
- [x] Parallelize `RedBlackTree.count` (for `Set.count` and `Map.count`)
- [x] Parallelize `RedBlackTree.minimumBy` (for `Set.minimumBy` and `Map.minimumBy`)
- [x] Parallelize `RedBlackTree.maximumBy` (for `Set.maximumBy` and `Map.maximumBy`)

Benefits unclear:
- [ ] `exists` and `forall`.

Possible, but simply too difficult:
- [ ] `differenceWith` and friends.
- [ ] `intersectWith` and friends.

Deferred:
- [ ] While `isSubsetOf` and `isProperSubSetOf` can be made parallel they are not purity polymorphic.

**Comment by magnus-madsen** [comment]
@jaschdoc I tagged this as priority. That does not mean to stress, simply that I think this is what we should work on mostly :)

**Comment by magnus-madsen** [comment]
@jaschdoc Will you update the overview? We still lack the maximumBy definitely. For the rest, try to estimate how difficult they are :)

**Comment by magnus-madsen** [comment]
I have concluded that it is only `maximumBy` that we are missing and can reasonably implement.

**Comment by jaschdoc** [comment]
https://github.com/flix/flix/blob/20d49e1ebe568d8bd9aa15d0f50b780e973b18c6/main/src/library/RedBlackTree.flix#L693
https://github.com/flix/flix/blob/20d49e1ebe568d8bd9aa15d0f50b780e973b18c6/main/src/library/Map.flix#L235

For some reason I forgot to add it to `Set`. We still need to update `MutMap` and `DelayMap` but these need updates to all the functions we've parallelized.

**Comment by magnus-madsen** [comment]
I think the latter part is what I was referring to. Not what is in RBTree but what has been surfaced.

**Comment by magnus-madsen** [comment]
Fixed in master. (Modulo outstanding tweaks).
