### ISSUE TITLE
Remove subkinding

### ISSUE THREAD

**Issue by mlutze** [flix/flix#2057]
We currently have subkinding to support the fact that, while records are first-class types, the record extension type constructor can only take other records in its second parameter. (Same for schemas). This proves to be burdensome, as a lack of parallelism between kinds and types hinders comprehension and requires additional, less-well-understood work to get it working.

This ticket is about exploring the changes necessary to remove subkinding without breaking everything else.
See also:
* https://github.com/flix/flix/issues/1791
* https://github.com/flix/flix/issues/1553
* https://github.com/flix/flix/pull/2037

Current state of things:
```
RecordEmpty: Record
RecordExtend: Star -> Record -> Record

SchemaEmpty: Schema
SchemaExtend: Star -> Schema -> Schema

Relation: Star* -> Star
Lattice: Star* -> Star

*but only tuples and unary types

Record <: Star
Schema <: Star
```

Proposed state of things:
```
RecordRowEmpty: RecordRow
RecordRowExtend: Star -> RecordRow -> RecordRow
Record: RecordRow -> Star

SchemaRowEmpty: SchemaRow
SchemaRowExtend: Predicate -> SchemaRow -> SchemaRow
Schema: SchemaRow -> Star

Relation(n): Star -> Star -> ... -> Star -> Predicate
Lattice(n): Star -> Star -> ... -> Star -> Predicate
```

For records, this follows the kinding used in _Extensible records with scoped labels_.
For schemas, it's approximately the same methd, but with predicates in the place of fields.

**Comment by mlutze** [comment]
How important is it to have first-class relations and lattices?

**Comment by magnus-madsen** [comment]
> 
> 
> How important is it to have first-class relations and lattices?

Very important
