### ISSUE TITLE
List, LazyList, and Stream - Overview

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2059]
We would like to implement a few data structures with the following definitions and properties:

LazyList:
```scala
enum LazyList[a] {
    case Nil,
    case Cons(a, Lazy[LazyList[a]]),
    case Thunk(Lazy[LazyList[a]])
}
```
A `LazyList` supports operations such as `map`, `filter`, etc. but these ***require*** their arguments to be ***pure***.

DelayList:
```scala
enum DelayList[a] {
    case Nil,
    case ECons(a, DelayList[a]),
    case LCons(a, Lazy[DelayList[a]]),
    case Thunk(Lazy[DelayList[a]])
}
```
A `DelayList` supports operations such as `map`, `filter` which are ***effect polymorphic*** and whose evaluation is **delayed** if their arguments are **pure**.

Note: We shall deal with Iterators and Generators in another ticket.

**Comment by jaschdoc** [comment]
# Status Overview

|  Function      | Iterator                      | LazyList                      | Comment |
| :--------:     | :------:                      | :------:                      | ------- |
| `append`       | TODO :heavy_multiplication_x: | ???                           |         |
| `count`        | Done :heavy_check_mark:       | ???                           |         |
| `drop`         | Done :heavy_check_mark:       | ???                           |         |
| `dropWhile`    | TODO :heavy_multiplication_x: | ???                           |         |
| `exists`       | Done :heavy_check_mark:       | ???                           |         |
| `filter`       | Done :heavy_check_mark:       | ???                           |         |
| `filterMap`    | TODO :heavy_multiplication_x: | ???                           |         |
| `findLeft`     | Done :heavy_check_mark:       | ???                           |         |
| `findMap`      | TODO :heavy_multiplication_x: | ???                           |         |
| `findRight`    | Done :warning:                | ???                           | Needs optimization |
| `flatMap`      | TODO :heavy_multiplication_x: | ???                           |         |
| `flatten`      | TODO :heavy_multiplication_x: | ???                           |         |
| `foldLeft`     | Done :heavy_check_mark:       | ???                           |         |
| `foldRight`    | Done :heavy_check_mark:       | ???                           |         |
| `forall`       | Done :heavy_check_mark:       | ???                           |         |
| `foreach`      | Done :heavy_check_mark:       | ???                           |         |
| `head`         | Done :heavy_check_mark:       | ???                           |         |
| `intercalate`  | TODO :heavy_multiplication_x: | ???                           |         |
| `intersperse`  | TODO :heavy_multiplication_x: | ???                           |         |
| `isEmpty`      | Done :heavy_check_mark:       | ???                           |         |
| `map`          | Done :heavy_check_mark:       | ???                           |         |
| `mapWithIndex` | TODO :heavy_multiplication_x: | ???                           |         |
| `maximum`      | TODO :heavy_multiplication_x: | ???                           |         |
| `maximumBy`    | TODO :heavy_multiplication_x: | ???                           |         |
| `memberOf`     | Done :heavy_check_mark:       | ???                           |         |
| `minimum`      | TODO :heavy_multiplication_x: | ???                           |         |
| `minimumBy`    | TODO :heavy_multiplication_x: | ???                           |         |
| `partition`    | TODO :heavy_multiplication_x: | ???                           |         |
| `range`        | Done :heavy_check_mark:       | ???                           |         |
| `reduceLeft`   | TODO :heavy_multiplication_x: | ???                           |         |
| `reduceRight`  | TODO :heavy_multiplication_x: | ???                           |         |
| `repeat`       | Done :heavy_check_mark:       | ???                           |         |
| `replace`      | Done :heavy_check_mark:       | ???                           |         |
| `span`         | TODO :heavy_multiplication_x: | ???                           |         |
| `take`         | Done :heavy_check_mark:       | ???                           |         |
| `takeWhile`    | Done :heavy_check_mark:       | ???                           |         |
| `toArray`      | Done :heavy_check_mark:       | ???                           |         |
| `toMap`        | Done :heavy_check_mark:       | ???                           |         |
| `toSet`        | Done :heavy_check_mark:       | ???                           |         |
| `zip`          | Done :heavy_check_mark:       | ???                           |         |
| `zipWith`      | TODO :heavy_multiplication_x: | ???                           |         |
