### ISSUE TITLE
Redundancy/Terminator: parameters only used in recursive calls

### ISSUE THREAD

**Issue by mlutze** [flix/flix#2064]
```scala
def foo(x: Int, y: Bool): Int = {
    if (x > 0) 
        x + 5
    else
        foo(x * 4, y)
}
```
`y` is useless here because it's only used in a recursive call.

We could do a lot more analysis and handle things like this
```scala
def foo(x: Int, y: Bool): Int = {
    if (x > 0) 
        x + 5
    else
        foo(x * 4, y + 999)
}
```
Since "stuff touching y" only goes to the same parameter in the recursive call.

**Comment by magnus-madsen** [comment]
This seems very specific.

**Comment by mlutze** [comment]
> This seems very specific.

Yes, fairly complex relative to the gains we would get. I think we can close.
