### ISSUE TITLE
Debate: Iterator Internals

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2076]
We currently implement iterators with two functions `done` and `next`. (Where I believe that `done` should not necessarily be pure, but at least it should be callable multiple times without advancing the underlying iterator). This is the solution used in many programming languages, including Java.

Another solution, also used in Java, is something more like: `tryNext(f: a ~> Unit): Bool` which applies `f` to the next element and returns `true`. If there is no element it returns `false`. Usually this is also paired with a `forEachRemaining` operation (but I guess that can be defined in terms of `tryNext` - so there is really only ONE fundamental operation.) Would this design be more favorable to us? 

Maybe we need to sketch an iterator with a few operations based on `tryNext`? Maybe we should investigate why they use this design? We should also ask Oskar, he is an expert on some of this stuff.

**Comment by magnus-madsen** [comment]
@jaschdoc @mlutze For your consideration

**Comment by mlutze** [comment]
Something I like about `tryNext` is that it feels a little less "crashy". It gets rid of the "always check `done` before calling `next`" rule, so in that sense it seems safer. But I haven't done any implementation in this realm, so I'd be interested in @jaschdoc's thoughts.

**Comment by magnus-madsen** [comment]
> Something I like about `tryNext` is that it feels a little less "crashy". It gets rid of the "always check `done` before calling `next`" rule, so in that sense it seems safer. But I haven't done any implementation in this realm, so I'd be interested in @jaschdoc's thoughts.

Yes, on the other hand it is more cumbersome. Imagine how you would write `head`? You pretty much have to use a local reference!

**Comment by jaschdoc** [comment]
Would `tryNext` be a wrapper around `done` and `next` in this case, such that `tryNext` would be the interface for iterator? Assuming this is the case, I agree that it is much less prone to errors to have `tryNext` essentially safeguard element queries. 

Originally, I considered `done` to be inverse of `hasNext` in Scala, such that if `done` is true then it does **not** have next element. Since `done` is impure, I would consider it okay to change the iterator in that function, as long as it is the case that `done` can be called an infinite number of times without crashing the program. Additionally, in Scala they let `hasNext` mutate / pop elements of the underlying iterator - see [Scala Iterator, `dropWhile`](https://github.com/scala/scala/blob/fd3fb314db270935845a1a8cd049a5bfcdcaab16/src/library/scala/collection/Iterator.scala#L647).


>Yes, on the other hand it is more cumbersome. Imagine how you would write head? You pretty much have to use a local reference!

I imagine you would have a local reference, but I think that would be the case for most functions / operations when using the `tryNext` solution.

**Comment by magnus-madsen** [comment]
> Would `tryNext` be a wrapper around `done` and `next` in this case, such that `tryNext` would be the interface for iterator? Assuming this is the case, I agree that it is much less prone to errors to have `tryNext` essentially safeguard element queries.

Its not a wrapper. You would literally only have a single function called `tryNext`.

**Comment by magnus-madsen** [comment]
> Originally, I considered `done` to be inverse of `hasNext` in Scala

`done` is exactly like `hashNext`, just the inverse Boolean.

**Comment by jaschdoc** [comment]
Hmm I tried re-writing some functions using `tryNext` to get a feel for it. I'm not sure I'm convinced. It seems to be that we run into the same problems using `tryNext`. Would love to hear your thoughts.

```flix
///
/// Type of the Handler function
///
type alias Handler[a] = a ~> Unit

///
/// Type of the TryNext function
///
type alias TryNext[a] = Handler[a] ~> Bool

pub enum Iterator[a] {
    case Iterator(TryNext[a])
}

namespace Iterator {

    ///
    /// Returns `Some(x)` if `x` is the first element of `iter`.
    ///
    /// Returns `None` if `iter` is empty.
    ///
    /// Consumes the first element of the iterator.
    ///
    pub def head(iter: Iterator[a]): Option[a] & Impure = {
        let Iterator(tryNext) = iter;
        let el = ref None;
        tryNext(x -> el := Some(x));
        deref el
    }

    ///
    /// Returns an iterator of all integers between `b` (inclusive) and `e` (exclusive).
    ///
    /// Returns an empty iterator if `b >= e`.
    ///
    pub def range(b: Int32, e: Int32): Iterator[Int32] & Impure =
        let i = ref b;
        let tryNext = (f: Handler[Int32]) -> {
            let res = deref i;
            if (res >= e)
                false
            else
                f(res);
                i := res + 1;
                true
        };
        Iterator(tryNext)

    ///
    ///
    ///
    pub def takeWhile(f: a -> Bool & ef, iter: Iterator[a]): Iterator[a] & Impure =
        matchEff f {
            case Pure   => takeWhileL(f as a -> Bool & Pure,   iter)
            case Impure => takeWhileE(f as a -> Bool & Impure, iter)
        }

    ///
    ///
    ///
    pub def takeWhileL(f: a -> Bool, iter: Iterator[a]): Iterator[a] & Impure =
        let Iterator(tryNext) = iter;
        let el = ref default;
        let stopped = ref false;
        let hasStopped = () -> deref stopped;
        let tn = () -> tryNext(x -> el := x);
        let takeNext = (g: Handler[a]) -> {
            if (not hasStopped() and tn() and f(deref el)) {
                g(deref el);
                true
            }
            else {
                stopped := true;
                false
            }
        };
        Iterator(takeNext)

    ///
    ///
    ///
    pub def takeWhileE(f: a -> Bool & Impure, iter: Iterator[a]): Iterator[a] & Impure =
        takeWhileEHelper(f, iter, Nil)

    ///
    ///
    ///
    def takeWhileEHelper(f: a -> Bool & Impure, iter: Iterator[a], acc: List[a]): Iterator[a] & Impure =
        let Iterator(tryNext) = iter;
        let el = ref default;
        if (tryNext(x -> el := x) and f(deref el))
            takeWhileEHelper(f, iter, (deref el) :: acc)
        else
            acc |> List.reverse |> toIter

    ///
    ///
    ///
    pub def toIter(l: List[a]): Iterator[a] & Impure =
        let cursor = ref l;
        let tryNext = (f: Handler[a]) -> {
            match (deref cursor) {
                case Nil     => false
                case x :: xs => {
                    cursor := xs;
                    f(x);
                    true
                }
            }
        };
        Iterator(tryNext)
}
```

**Comment by magnus-madsen** [comment]
@jaschdoc Thanks for the samples! This is very useful! Could you also try `map` and `filter` and `exists`?

**Comment by mlutze** [comment]
I assume I'm missing something, but why don't we implement it like OCaml's Seq?

```scala
type alias Iterator[a] = Unit ~> Node[a]

enum Node[a] {
  case Nil
  case Cons(a, Iterator[a]) 
}
```

**Comment by magnus-madsen** [comment]
> 
> 
> I assume I'm missing something, but why don't we implement it like OCaml's Seq?
> 
> ```scala
> type alias Iterator[a] = Unit ~> Node[a]
> 
> enum Node[a] {
>   case Nil
>   case Cons(a, Iterator[a]) 
> }
> ```

Interesting. Ill think about it. I wonder what the downsides are? Maybe repeated allocation of `Cons` and `Iterator`?

**Comment by magnus-madsen** [comment]
@mlutze In OCaml, what happens if you call the function twice? I guess its undefined / not allowed / depends on the iterator?

**Comment by mlutze** [comment]
Here's some info from the docs:

> Note that the concrete list node 'a node is delayed under a closure, not a lazy block, which means it might be recomputed every time we access it.

That doesn't really define any "rules", but seems to discourage re-evaluating the function.

**Comment by jaschdoc** [comment]
> @jaschdoc Thanks for the samples! This is very useful! Could you also add `map` and `filter` and `exists`?

Done! The snippet has been updated. I'm not really super happy with the `tryNext` design. It leads to some very cryptic code in my opinion.

The OCaml structure would certainly bring it closer in line with `LazyList` which would help with readability, but other than that I'm not sure what the pros and cons would be. Also, that design is what I've come to recognize as a stream but I guess they are essentially the same concept. I personally like that a lot but I'm not sure I have much input otherwise.

**Comment by stephentetley** [comment]
I've an Iterator implementation here that uses a "Stream Fusion" inspired Step datatype so it can implement `filter`. Arguably it is slightly simpler than the current library.

https://gist.github.com/stephentetley/8b014917b801fbb4777088bef16b06d9

I'm a bit worried about the division between lazy and strict for pure and impure `map` and `filter` in the current Iterator library. Is the division necessary? 
Certainly the current implementation of `mapE` is worrying as going from Iterator to List to Iterator looks like it would introduce a memory usage spike (building the list) which is against the principal of an iterator to have low memory residency.

**Comment by magnus-madsen** [comment]
> I'm a bit worried about the division between lazy and strict for pure and impure `map` and `filter` in the current Iterator library. Is the division necessary?
> Certainly the current implementation of `mapE` is worrying as going from Iterator to List to Iterator looks like it would introduce a memory usage spike (building the list) which is against the principal of an iterator to have low memory residency.

This is a good point. I don't have an answer for it yet. 

We are trying something completely new and radically different with our design of `Iterator`, `LazyList`, and `Generator`. (I have many points in favor, and I will post them at some point, but the essence is to preserve eager semantics). Nevertheless, your point stands. 

For the purpose of example, I assume one could be processing a gigantic text-file line-by-line. You would not want that to be fully materialized in main memory.

**Comment by stephentetley** [comment]
Thanks Magnus

My other concern is that we might want a "family" of Iterators.

The current iterator can handle (multiple) errors by using `Result[a, e]` as the element type, i.e. `Iterator[Result[a, e]]`

However this makes mapping and filtering a bit cumbersome as they must account for the fact that the are working on a bigger type `Result[a, e]` rather than `a`, e.g. to increment an Iterator by 10:

~~~

def incr10(iter: Iterator[Result[a, e]]): Iterator[Result[a, e]] = 
    Iterator.map(Result.map(x1 -> x1 + 10), iter)
   
~~~

Rather than the simple case:

~~~

def incr10(iter: Iterator[a]): Iterator[a] = 
    Iterator.map(x1 -> x1 + 10, iter)

~~~

With an Iterator that embeds errors we can have: 

~~~

def incr10(iter: Iterator2[err, a]): Iterator2[err, a] = 
    Iterator.map(x1 -> x1 + 10, iter)

~~~

I've an implementation of an embedded error Iterator here:

https://gist.github.com/stephentetley/f209078059d2cbedb6a758d286005e35

I'm not suggesting this Iterator should replace the current library, for instance the current Iterator has exactly the right type (and power) for turning Arrays, Lists and other collections into Iterators. But an iterator with embedded errors is potentially nicer for a File "readLines" Iterator.

**Comment by magnus-madsen** [comment]
Thanks Stephen-- The second part I am definitely on board with. I think having that as an extra data types makes total sense. Ill take a look!

**Comment by magnus-madsen** [comment]
Does the Iterator stop on the first error? Or does it collect them into a list?

**Comment by stephentetley** [comment]
> Does the Iterator stop on the first error? Or does it collect them into a list?

It stops on first.

I think you could write a "Validation Iterator" that collects all errors - but I haven't looked at this.

**Comment by stephentetley** [comment]
Hi Magnus, I'm on holiday today so I took a look at a "Validation (multiple errors) Iterator"

https://gist.github.com/stephentetley/1c5447ce783fcaccac800bc3d5ed7893

What I call "terminal functions" (e.g. fold, foreach, toList - functions that consume all the iterator) are simple enough: after first error stil continue to the end but stop looking for successes and just collect the errors.

`map`, `filter` and `zipWith` only have slight changes.

**Comment by magnus-madsen** [comment]
> I'm a bit worried about the division between lazy and strict for pure and impure `map` and `filter` in the current Iterator library. Is the division necessary?
> Certainly the current implementation of `mapE` is worrying as going from Iterator to List to Iterator looks like it would introduce a memory usage spike (building the list) which is against the principal of an iterator to have low memory residency.

I don't have a great answer yet, but what do you think about this completely novel data structure:

`Eterator[t, ef]`

which should be understood as follows: It is an iterator over elements of type `t` with suspend effect `ef`. That is, if `ef` is pure then there is no suspended effect, if impure then there is one.

Mapping and filtering (etc.) with a *pure* function is always lazy and returns an iterator of the same type.

Mapping and filtering (etc.) with a *impure* function has interesting (complicated?!) semantics:

- If the stream is pure then effect is delayed.
- If the stream is already impure then the *first* effect is released and the new effect is delayed (!!).

Maybe this is crazy ... 

But is has nice properties: We cannot get non-determinism or interference between effects due to laziness. The only thing is that the *last* suspend effect may be lost if the stream is unused.

Lets consider some examples:

```
eterator |> List.map(x -> println(x)) // prints nothing
eterator |> List.map(x -> println(x)).take(5) // prints up to the first 5 elements.
eterator |> List.map(x -> println(x)).map(x -> println("a")) // prints *all* elements. Does *not* print "a".
eterator |> List.map(x -> println(x)).map(x -> println("a")).take(5) // prints *all* elements. Then prints up to 5 "a"s.
```

This is research. So its new, different, potentially useful, and potentially subtly dangerous.

In all cases, we can always implement a `TruelyLazyIteratorThatSuspendsAllEffects` if you have a need for that :)

**Comment by magnus-madsen** [comment]
We now have a basic iterator build on `done` and `next`.
