### ISSUE TITLE
Bug in Console.readLine()

### ISSUE THREAD

**Issue by jhckragh** [flix/flix#2078]
Dear Flix developers,

If you call `Console.readLine()` more than once, then it seems that all calls except the first always return `None`.

Here's a small example:

```flix
def main(_args: Array[String]): Int32 & Impure =
    println(Console.readLine());
    println(Console.readLine());
    0
```

If I run this program with the following input file, `xs.txt`,

```
1
2
3
```

then I get

```
Some(1)
None
```

but the expected result is

```
Some(1)
Some(2)
```

I'm running the program like this:

```java -jar flix-2021-07-27.jar ReadLines.flix < xs.txt```

Looking at the source https://github.com/flix/flix/blob/master/main/src/library/Console.flix#L52-L62 I notice that a new `Scanner` is created on every invocation of `Console.readLine()`. I think this is what's causing the problem: The underlying `InputStream` is not left in a state that can be used by another `Scanner`. A possible solution is to have a singleton `Scanner` that's used for every call (like Scala does, although they use a `BufferedReader` instead of a `Scanner`).

(By the way, I like the language a lot, and I'm having fun exploring it!) ☺️

**Comment by magnus-madsen** [comment]
We should use https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/Console.html

**Comment by JonathanStarup** [comment]
I think this could be the wrong way to go, according to [this](https://www.baeldung.com/java-system-console-vs-system-out) the console is sometimes `null` which doesn't sound very pleasent. I use the input/output redirection often `run .... > output.txt` but this would result in a nullpointer exception

**Comment by magnus-madsen** [comment]
Hmm. Interesting point. Ill think about it.

**Comment by magnus-madsen** [comment]
Fixed in master.
