### ISSUE TITLE
Backend: Destination Driven Code Generation

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#208]
The current backend performs a simple recursive AST-traversal to generate bytecode, but it could use [destination driven code generation](http://www.cs.indiana.edu/~dyb/pubs/ddcg.pdf) to eliminate some unnecessary branching. 

With DDCG peephole optimizations (and other such tricks) are not necessary (according to the paper, and a talk by one of people behind Google V8).

**Comment by mhyee** [comment]
It's probably a good idea to read and understand the paper, and then apply the ideas to Flix and JVM bytecode. I tried following the paper very closely, and it didn't work out because our source and target languages are different from what's used in the paper.

**Comment by magnus-madsen** [comment]
This probably not necessary given the optimizations of the JVM.
