### ISSUE TITLE
Java collection conversion API

### ISSUE THREAD

**Issue by mlutze** [flix/flix#2085]
It would be nice to be able to, for example, call a Java function that returns a list, then easily convert that list to Flix code for manipulation.

We should also consider creating type class instances for Java types, which could save on conversion costs. (How does the orphan rule interact here?)

**Comment by magnus-madsen** [comment]
Yes. I think interop is still a work-in-progress and at some point we should have yet another iteration on its design.

**Comment by magnus-madsen** [comment]
Requires support for Java generics.

**Comment by mlutze** [comment]
The adaptor API is fulfilling this purpose
