### ISSUE TITLE
Backend: Pattern Matching Compiled to GOTO

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#209]
We currently compile pattern matching to lambda functions and calls. 

That strategy has worked well, and would work well, were it not for one important optimization: tail recursion.

Flix supports (or will soon support tail recursion #157). Notice that tail recursion is a limited form of tail call optimization. It is the common case (?), and probably the best we can hope to achieve on the JVM without new instructions for TCO.

Unfortunately, by compiling pattern matching to functions, we turn a simple function like:

```
def f(i: Int): Int = match i with {
  case n => if (n == 0) 0 else f(i - 1)
}
```

into two functions, where the tail call to `f` is _no longer in tail position inside f_.

We can avoid that by adding explicit labels and gotos to the backend ASTs. This requires changes to the interpreter, symbolic evaluator, and code generator, and should be done with care.

On the other hand, it also opens up for an intriguing possibility which may not have been explored before: Compile pattern matching based on whether the function is tail recursive, if so, try to keep everything inline, otherwise extract separate functions for each case.

**Comment by mhyee** [comment]
> On the other hand, it also opens up for an intriguing possibility which may not have been explored before: Compile pattern matching based on whether the function is tail recursive, if so, try to keep everything inline, otherwise extract separate functions for each case.

Yes, this should be considered. Compiling pattern matching into gotos seemed to be very messy for Dotty. And it also makes it harder for the JIT to inline if it's a giant function with a lot of jumps.

Also, note that destructing values in a let-binding is rewritten into a pattern match. For example, the following function is not tail recursive:

```
    def piHelper(i: BigInt, k: BigInt, l: BigInt, n: BigInt, a: BigInt, d: BigInt, t: BigInt, u: BigInt): BigInt =
      if (i == 0ii) t
      else let k1 = k + 1ii in
           let t1 = n << 1 in
           let n1 = n * k1 in
           let a1 = a + t1 in
           let l1 = l + 2ii in
           let a2 = a1 * l1 in
           let d1 = d * l1 in
           let (t2, u1) = compTpl1(a2, n1, d1, t1, u) in         // pattern match
           let (i1, a3, n2) = compTpl2(a2, n1, d1, u1, i, t2) in // pattern match
             piHelper(i1, k1, l1, n2, a3, d1, t2, u1)            // gets moved into a separate function body
```

**Comment by magnus-madsen** [comment]
In progress. Not available as a student project anymore.

**Comment by magnus-madsen** [comment]
Implemented!
