### ISSUE TITLE
Type constraints for parametrized types in laws

### ISSUE THREAD

**Issue by felixwiemuth** [flix/flix#2097]
In laws for type classes, to compare the results of different expressions, we sometimes do not only need to require `Eq` instances for plain types; for type classes with parametrized types like `Applicative[m : Type -> Type]`, we also need to require these instances for parametrized types.

For example, `Applicative` should have the following law, where we get an error for a missing `Eq` instance:

```
>> No instance of class 'Eq' for type m[a].

59 |   law identity: forall(x: m[a]). Applicative.ap(Applicative.point(identity), x) == x
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                      no instance of class 'Eq' for type m[a]
```

It is currently not possible to add this constraint:

```
>> Illegal type constraint parameter.

59 |   law identity: forall(x: m[a]) with Eq[m[a]] . Applicative.ap(Applicative.point(identity), x) == x
                                          ^^^^^^^^
                                          illegal type constraint parameter
```

See also #2096.
@mlutze

**Comment by mlutze** [comment]
The fix in progress is assuming that everything in the type constraint will be a variable. Is that a safe assumption?

E.g. no `Eq[Option[a]]` or `Eq[m[Int]`

**Comment by felixwiemuth** [comment]
I think at least for laws this should cover most if not all cases. Right now I cannot imagine a case where you'd want a specific type as type parameter, as laws are probably always general in the type parameters.

**Comment by magnus-madsen** [comment]
Merged, thanks Matt! But not 100% fixed yet right?

**Comment by mlutze** [comment]
I think the remaining problems relevant to this issue are here: https://github.com/flix/flix/issues/2099
I'll let @felixwiemuth confirm.

**Comment by felixwiemuth** [comment]
The following compile now:
```
law identity: forall(x: m[a]) with Eq[m[a]] . Applicative.ap(Applicative.point(identity), x) == x
law composition: forall(f: m[b -> c], g: m[a -> b], v: m[a]) with Eq[m[c]] . Applicative.ap(Applicative.ap(Applicative.ap(Applicative.point((f, g) -> g >> f), f), g), v) == Applicative.ap(f, Applicative.ap(g, v))
law interchange: forall(f: m[a -> b], x: a) with Eq[m[b]] . Applicative.ap(f, Applicative.point(x)) == Applicative.ap(Applicative.point(f -> f(x)), f)
```
What still does not compile is the following (and it is discussed in #2099), but the type constraint is accepted:
```
>> The type scheme: '∀(a, m, b). a -> b -> a -> Bool' cannot be generalized to '∀(a, b, m). a -> b -> a -> Bool'.

64 |   law homomorphism: forall(f: a -> b, x: a) with Eq[m[b]] . Applicative.ap(Applicative.point(f), Applicative.point(x)) == Applicative.point(f(x))
           ^^^^^^^^^^^^
           unable to generalize the type scheme.


  Declared: ∀(a, b, m). a -> b -> a -> Bool
  Inferred: ∀(a, m, b). a -> b -> a -> Bool
```

So I would say regarding the ability to specify type constraints this is solved.
