### ISSUE TITLE
Type checker claims inferred and declared type to be different in law

### ISSUE THREAD

**Issue by felixwiemuth** [flix/flix#2099]
```
>> The type scheme: '∀(a, m, b). a -> b -> a -> Bool' cannot be generalized to '∀(a, b, m). a -> b -> a -> Bool'.

70 |  law homomorphism: forall(f: a -> b, x: a). Applicative.ap(Applicative.point(f), Applicative.point(x)) == Applicative.point(f(x))
          ^^^^^^^^^^^^
          unable to generalize the type scheme.


  Declared: ∀(a, b, m). a -> b -> a -> Bool
  Inferred: ∀(a, m, b). a -> b -> a -> Bool
```
Except for the order of the variables under the forall operator the type schemes are the same.
So we either have a problem with deterministically ordering type variables or with comparing equivalent type schemes.

**Comment by mlutze** [comment]
I believe this happens because `m` is not present in the parameters or return value, so in unifying the type schemes, the `m`s cannot match each other. Something with rigidity of the class type parameter might help(?)

**Comment by magnus-madsen** [comment]
Can you change `law` to `def` with a Bool return type and some arguments to see if you get the same error?

**Comment by mlutze** [comment]
> Can you change `law` to `def` with a Bool return type and some arguments to see if you get the same error?

I anticipate an `IllegalSignature` error for that, since for sigs, the type class parameter must be part of the function signature. (But we'll see if I'm wrong)

**Comment by felixwiemuth** [comment]
This seems to reveal more problems (the following is defined in another file than the `Applicative` class as it otherwise requires the usage of `m` (for `Applicative[m]`)):

```
>> The type scheme: '∀(a, m, b). a -> b -> a -> Bool' cannot be generalized to '∀(a, b). a -> b -> a -> Bool'.

2 | pub def homomorphism(f: a -> b, x: a) : Bool = Applicative.ap(Applicative.point(f), Applicative.point(x)) == Applicative.point(f(x))
            ^^^^^^^^^^^^
            unable to generalize the type scheme.

  Declared: ∀(a, b). a -> b -> a -> Bool
  Inferred: ∀(a, m, b). a -> b -> a -> Bool
```
Now one problem is that this is actually ambiguous and would need type annotations to say which applicative instance we mean.
Another is that it misses the `Eq[m[b]]` constraint.

Other than that the correct type scheme would be the declared one (`∀(a, b). a -> b -> a -> Bool`) - even though it is comparing two `m[b]`, this should not occur in the signature.

Now adding a type annotation to specify the `Applicative` instance, it becomes more strange:

```
>> No instance of class 'Eq' for type a.

2 | pub def homomorphism(f: a -> b, x: a) : Bool = Applicative.ap(Applicative.point(f), Applicative.point(x)) : Option[b] == Applicative.point(f(x))
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   no instance of class 'Eq' for type a
```
I don't know how it comes to complain about `Eq[a]` while we only use `Eq` on `b`. Interestingly, for `pub def homomorphism(f: a -> b, x: a) : Bool with Eq[a] = ...` it gives the same error, but when adding `with Eq[b]` it actually compiles!

So maybe the whole problem is a missing ambiguity check which leads to the faulty type error at a stage where we should already have aborted?

And then in laws it is somewhat more complicated because `m` is implicitly instance of `Applicative`, even if there is no concrete instance at that point.

**Comment by felixwiemuth** [comment]
We can now add type constraints with parametrized types in laws, but the error is still the same even when adding the `Eq[m[b]]` constraint:

```
>> The type scheme: '∀(a, m, b). a -> b -> a -> Bool' cannot be generalized to '∀(a, b, m). a -> b -> a -> Bool'.

64 |   law homomorphism: forall(f: a -> b, x: a) with Eq[m[b]] . Applicative.ap(Applicative.point(f), Applicative.point(x)) == Applicative.point(f(x))
           ^^^^^^^^^^^^
           unable to generalize the type scheme.


  Declared: ∀(a, b, m). a -> b -> a -> Bool
  Inferred: ∀(a, m, b). a -> b -> a -> Bool
```

**Comment by mlutze** [comment]
What happens if you add explicit type annotations inside the law?

**Comment by felixwiemuth** [comment]
Hmm, similar error, but the inferred type scheme has a different order under the forall:

```
>> The type scheme: '∀(m, a, b). a -> b -> a -> Bool' cannot be generalized to '∀(a, b, m). a -> b -> a -> Bool'.

62 |   law homomorphism: forall(f: a -> b, x: a) with Eq[m[b]] . Applicative.ap(Applicative.point(f) : m[a -> b], Applicative.point(x) : m[a]) : m[b] == Applicative.point(f(x)) : m[b]
           ^^^^^^^^^^^^
           unable to generalize the type scheme.


  Declared: ∀(a, b, m). a -> b -> a -> Bool
  Inferred: ∀(m, a, b). a -> b -> a -> Bool
```
