### ISSUE TITLE
Backend: Compile Values to Java Classes

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#210]
We currently use classes such as `Value.Tag` and `Value.Tuple`. It would be better to compile these ad-hoc data representations directly to Java classes. 

We would probably have `Tuple2`... `TupleN` like Scala. For Enums, we would have an interface and classes (with fields) that subclass the interface.

A clever representation would represent say:

```
enum Shape {
  case Rectangle(Int, Int)
}
```

as the class:

```
class Rectangle extends Shape {
  public int f0;
  public int f1;
  public boolean equals(...) { ... }
}
```

Ideally this should also optimize nullary data constructors, i.e. `Color.Red` would be represented as singleton object of some interface.

Once this is in place -- for the general case -- an optimization on top of this might try to represents some values directly as 32 or 64-bit integers for maximum compactness.

**Comment by mhyee** [comment]
Two thoughts to consider:

- Would tuples be generic, or specialized?
- How does this work with interop?

**Comment by magnus-madsen** [comment]
We would have specialized tuples (due to monomorphization) so we would have to generate e.g.:

```
class Tuple2$IntInt {
  public f1 int;
  public f2 int;
  ...
}
```

**Comment by magnus-madsen** [comment]
Fixed.
