### ISSUE TITLE
Should `toString` be consistent with `==`?

### ISSUE THREAD

**Issue by mlutze** [flix/flix#2105]
```scala
class ToString[a] {
  pub def toString(x: a)

  law consistentWithEquals: forall (x: a, y: a) . x == y <==> ToString.toString(x) == ToString.toString(y)
}
```

**Comment by magnus-madsen** [comment]
You could imagine a `Person("Magnus", "Madsen", 35)` which is equal to `Person("Magnus", "Madsen", 36)`, but nevertheless their strings are different.

**Comment by mlutze** [comment]
So rather a one-way implication? I'm trying to make it harder to end up in a situation where I'm debugging and I print two values, see that they are the same, and come to some conclusion based on their sameness, only to find out after 30 more minutes of debugging that they're not actually equal.

**Comment by magnus-madsen** [comment]
> 
> 
> So rather a one-way implication? I'm trying to make it harder to end up in a situation where I'm debugging and I print two values, see that they are the same, and come to some conclusion based on their sameness, only to find out after 30 more minutes of debugging that they're not actually equal.

Ah ha! Been there, done that. 

Unfortunately I don't see how you can "reasonably" expect an implication in either direction.

**Comment by magnus-madsen** [comment]
Maybe we want: https://doc.rust-lang.org/std/fmt/trait.Debug.html

**Comment by magnus-madsen** [comment]
Debug could be sealed so we force the same format?

**Comment by mlutze** [comment]
Note that an implementer can always opt out of the law by marking the instance as `unlawful`.

**Comment by magnus-madsen** [comment]
Good point,  but I am still not convinced that equality has anything to do with the string representation of a value.
