### ISSUE TITLE
Move some ParseErrors to Weeder

### ISSUE THREAD

**Issue by mlutze** [flix/flix#2106]
ParseErrors are often hard to understand; we could give better error messages by loosening up parsing rules and moving the equivalent restrictions to the Weeder.

For example:
```scala
class myClass[a]
```
produces the error
```
-- Parse Error -------------------------------------------------- ???

>> Parse Error:

Invalid input "class m", expected optWS, Uses or Decls (line 1, column 1):
class myClass[a]
^
```
while if we do this in the Weeder, we could have something like:
```
-- Weeder Error -------------------------------------------------- ???

>> Weeder Error:

Invalid class name 'myClass'.
class myClass[a]
      ^^^^^^^

Tip: Class names must be capitalized.
```

This ticket is to collect ParseErrors that should be moved to the Weeder.

* IllegalNames
  * Defs
  * Classes
  * Instances
  * Sigs
  * Enums
  * Laws
  * TypeAliases
* Def lacking implementation

**Comment by magnus-madsen** [comment]
We can try, but in some cases it might lead to ambiguity -- I think. Of course not if you have literally `class foo`.
