### ISSUE TITLE
Crash with higher-order types and schema types in enums

### ISSUE THREAD

**Issue by mlutze** [flix/flix#2113]
The following code causes a crash in the Finalizer:
```scala
enum IntWrapper[a: Type -> Type] {
    case C(a[Int])
}
```

```
Unexpected type: ''0[Int32]'.
```

**Comment by magnus-madsen** [comment]
Its probably a bug in typer or monomorph, because type variables should have been eliminated.

**Comment by mlutze** [comment]
```scala
// Pre-Kinder implementation
enum ESchema[a] {
    case CSchema1(a)
    case CSchema2(#{ R | a })
}
rel R(i: Int)
```

```scala
// Post-Kinder implementation
enum ESchema[a: Schema] {
    case CSchema1(a)
    case CSchema2(#{ R | a })
}
rel R(i: Int)
```

also causes a crash:
```
Unexpected type: 'Relation[Int32]'.
```

**Comment by mlutze** [comment]
I think this needs to wait for the new backend (assuming that will be getting rid of `MonoType.Var`). Monotypes have no way of expressing the application of a variable to a type, and it seems that adding such a type would have repercussions all throughout the backend.

**Comment by magnus-madsen** [comment]
OK

**Comment by stephentetley** [comment]
Is any work scheduled to look at this?

I've just found another instance of the error working with graded monads:

~~~

pub enum Builder[r: Region, ka: Type, st: Region -> Type, ef: Bool, a: Type](
    st[r] -> (a -> Result[String, ka] \ ef) -> Result[String, ka] \ ef
)
        
~~~

I can use a `st: Type` type for `st` without the region but it does make the types of functions built on Builder nicer if they can reference the `r` parameter.

**Comment by magnus-madsen** [comment]
I was going to ask @JonathanStarup to look into the backend (for this specific issue) post OOPSLA deadline (15 april), so probably not before then. But it is on the drawing board for spring/summer. 

(That's probably a bit sad to hear, since you are trying to use the feature now :()

Unfortunately it is not really a bug, but an architectural issue that has to be resolved.

**Comment by stephentetley** [comment]
Thanks Magnus, I can live with / revert back to "kind: Type" types. Good to know there are plans to investigate the issue though.

**Comment by mlutze** [comment]
Fixed by enum monomorphization
