### ISSUE TITLE
Kinder: Replace KindedAst?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2115]
- [ ] Explore if `KindedAst` can be removed by adding an extra variant `UnkindedVar` to `Type`.
- [ ] Rename tests to be of the form `Test.Kind.Def`, `Test.Kind.Enum`, and so forth.
- Kinder:
  - [ ] Rename `visitExpression` to `visitExp`.

**Comment by magnus-madsen** [comment]
Kinder could also be made parallel over defs.

**Comment by mlutze** [comment]
After some exploration, it seems a little awkward to remove the `KindedAst`:
1. The different kinds of type parameters (pre- and post-kinding) create a complex subtyping structure. 
2. The tvars associated with expressions all start as `UnkindedVar`, only to be directly ascribed as `Var`s in the `Kinder`. 
  * For some of them, we could assign kinds in the `Resolver`, but then we don't have the nice invariant that `UnkindedVar`s exist exclusively before kinding, and (Kinded) `Var`s exist exclusively after kinding.
  * We could also assign to `null`, but that just feels wrong.

**Comment by mlutze** [comment]
We've decided to keep the KindedAst. Can we close this or do we need to revisit it?
