### ISSUE TITLE
Improve type errors for functions applied to too many arguments

### ISSUE THREAD

**Issue by felixwiemuth** [flix/flix#2133]
(This is at commit eaddef0e1eb3c6a67d0d33599bf950676071e361)

Applying the following 2-argument function
```
def g(x: Int32, y: String) : Bool = true
```
to 3 arguments gives the following error:
```
>> Unable to unify the types: 'Bool' and 'Bool -> '80784 & '80785'.

10 |   let x = g(1, "hello", true);
               ^^^^^^^^^^^^^^^^^^^
               mismatched types.

Type One: Bool
Type Two: Bool -> '80784 & '80785
```
While (because of currying) it is correct that after applying two arguments a function type is expected to apply further arguments, the error could be more helpful:
- It could explicitly mention that a 2 argument function is applied to 3 arguments.
- It could rather say "Couldn't match expected type 'Bool -> t' with actual type 'Bool'".
- Furthermore the return type variable and effect variable should of course have more readable names in line with other error messages.

As a comparison, in Haskell we get
```
Prelude> g 1 "hello" True

<interactive>:22:1: error:
    • Couldn't match expected type ‘Bool -> t’ with actual type ‘Bool’
    • The function ‘g’ is applied to three arguments,
      but its type ‘p10 -> [Char] -> Bool’ has only two
      In the expression: g 1 "hello" True
      In an equation for ‘it’: it = g 1 "hello" True
    • Relevant bindings include it :: t (bound at <interactive>:22:1)
```

**Comment by magnus-madsen** [comment]
We now have `UnderApplied` and `OverApplied` type errors. They are not perfect, but they are better than what was there.
