### ISSUE TITLE
[Newtyper]: Infinite Recursion in Interpreter

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#214]
We are now finally able to typecheck the following program:

```
def head[a](xs: List[a]): a = match xs with {
    case Nil => ???
    case y :: ys => y
}

def map[a, b](f: a -> b, xs: List[a]): List[b] = match xs with {
    case Nil => Nil
    case y :: ys => f(y) :: map(f, ys)
}

def f(z: Int): Int = head(map(x -> x, 1 :: 2 :: 3 :: Nil))

rel R(x: Int)

R(f(42)).
```

Unfortunately we get infinite recursion somewhere inside `map`. (when running with `--Xinterpreter`, the codegen doesn't have support for generics):

```
Exception in thread "main" java.lang.StackOverflowError
	at ca.uwaterloo.flix.runtime.Interpreter$.eval(Interpreter.scala:115)
	at ca.uwaterloo.flix.runtime.Interpreter$.eval(Interpreter.scala:116)
	at ca.uwaterloo.flix.runtime.Interpreter$.evalArgs(Interpreter.scala:439)
	at ca.uwaterloo.flix.runtime.Interpreter$.eval(Interpreter.scala:75)
...
```

I don't think it is because of the code in the interpreter. Possible error locations are:

1. Pattern matching compilation of lists.
2. Closure conversion.
???

**Comment by mhyee** [comment]
How large of a stack did you give it? Does it eventually work, given an enormous stack, or does it still overflow?

Can you simplify the test case any more?

Have you looked at the `ExecutableAst` just before it's consumed by the interpreter? Does it look reasonable?

**Comment by magnus-madsen** [comment]
The list has 4 items, so it makes no sense that it should blow the stack. I haven't debugged much, because I am working on other parts of the type system.

**Comment by magnus-madsen** [comment]
I have found the bug - in the frontend - lets see if I can fix it.

**Comment by magnus-madsen** [comment]
Fixed.
