### ISSUE TITLE
Remove lawful superclass criterion

### ISSUE THREAD

**Issue by mlutze** [flix/flix#2145]
The `Boxable` class has two superclasses `Order` and `ToString`. It is currently `lawless`. It would be nice to make it `lawful`, with a law saying `forall(x: a) with Eq[a] . unbox(box(x)) == x`. However, since `ToString` is `lawless`, `Boxable` must be lawless, as we don't allow `lawful` subclasses of `lawless` superclasses.

For this specific case, this could be solved by making `ToString` `lawful` (see https://github.com/flix/flix/issues/2105).

But a more general solution, if it seems this could come up elsewhere, would be to remove the check requiring superclasses to be at least as strict as the subclass.

**Comment by magnus-madsen** [comment]
Here is what I believe:

- `ToString` must be lawless because there are no rules about how to print a value.
- `Boxable` extends `ToString`.
- If `ToString` is an outlaw then by association `Boxable` is also an outlaw.

None of this should prevent `Boxable`  from having a law. It just cannot be lawless.

changemyview

The above could be an argument against lawful/lawless in general!

**Comment by mlutze** [comment]
I think that "extends"/"superclass" is not the right association. (We use it everywhere, though I don't think we should.)
Instead we can say that `Boxable` has a `ToString` constraint.

It seems reasonable to me that a class could have a lawless constraint and use the associated signatures in such a way that the class's laws are not violated. For example:

```scala
class Boxable[a] with ToString[a], Order[a] { // ToString is lawless
   // ... sigs ...
  law toStringUnchanged: forall (x: a) . "${x}" == "${box(x)}"
}
```

We still don't care what the strings are, but we require that they be consistent between boxed and unboxed values.

Another example with a different idea:
```scala
class ConsistentToString[a] with ToString[a], Eq[a] { // ToString is lawless
  law consistentWithEquals: forall (x: a, y: a) . x == y <==> "${x}" == "${y}"
}
```

In this case we effectively add a law to `ToString`, ensuring it is consistent with equality. Because the law is the whole point of this class, it would be unfortunate to have to make it `lawless` just because `ToString` is.

**Comment by magnus-madsen** [comment]
OK, I am convinced.
