### ISSUE TITLE
Rename `PartialOrder.partialCompare` to `PartialOrder.lessEqual`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2151]
- [ ] Rename `PartialOrder.partialCompare` to `PartialOrder.lessEqual`
- [ ] Refactor the fixpoint solver to use `lessEqual`.
- [ ] Refactor all examples etc. to use `lessEqual`.
- [ ] Check that all tests run.

**Comment by JonathanStarup** [comment]
The code has a todo note about changing the return type from boolean to Comparison, but the boolean should remain with this change right? This is a purely about renaming?

**Comment by magnus-madsen** [comment]
> 
> 
> The code has a todo note about changing the return type from boolean to Comparison, but the boolean should remain with this change right? This is a purely about renaming?

This is just the renaming-- for now
