### ISSUE TITLE
Improve Stratifier

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2152]
Phase 1:
- [ ] Collect Datalog program "pipelines" that use negation.
  - E.g. look through GitHub (grep.app) for Datalog programs. Add to examples/Datalog.
  - Add AlpineClub to examples.
  - Add "Parts" to examples.
  - Extend existing programs with pipelines.

Phase 2:
- [ ] Work on type system.

Phase 3:
- [ ] Consider local stratification.

More text to come.

**Comment by JonathanStarup** [comment]
phase 1 has its own issue #2415

**Comment by magnus-madsen** [comment]
We are working on this "offline".
