### ISSUE TITLE
Add new `Deriver` Compiler Phase

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2154]
Add a `Deriver` phase after `Typer` but before `Instances` to automatically derive instances for certain type classes:

Phase 1:
- [x] Add a derives clause to enum declarations (#2155)

Phase 2:
- [x] #2156
- [x] #2157
- [x] #2158
- [x] Use mechanism for `Option`, `List` etc?

Phase 3:
- [x] Boxable (#2159)

Phase 4:
- [x] Add an examples to `./examples/`.
- [x] Refactor existing examples to use the derive mechanism.
- [ ] Add examples to www.flix.dev.

Phase 5:
- [x] Deriver: Hash
- [ ] ~Deriver: PartialEq/PartialOrder?~

*Note:* If the `Deriver` phase is disabled then the compiler works as-if no type class instances are automatically generated.

**Comment by mlutze** [comment]
Type constraint checking is done in the Typer; I think this has to be done before then.

**Comment by magnus-madsen** [comment]
> Type constraint checking is done in the Typer; I think this has to be done before then.

Alright. That should still be OK, right?

**Comment by mlutze** [comment]
I think so.

**Comment by magnus-madsen** [comment]
@stephentetley Heads-up: You'll probably find these features useful as they land in master :)

Note: We cannot yet deal with records, so if you have records in enums you will still have to write your own instances.

**Comment by stephentetley** [comment]
Thanks Magnus - I was about to make a PR last week for `Eq`, etc. on `Comparison` when I saw this issue.

**Comment by mlutze** [comment]
Should the added example contain `Boxable` info, or do we keep that hidden?

**Comment by magnus-madsen** [comment]
> 
> 
> Should the added example contain `Boxable` info, or do we keep that hidden?

Let us keep it hidden. I think the docs on TC should mention what Boxable is and why it exists, but everywhere else we can keep it secret, I think.

**Comment by magnus-madsen** [comment]
What other type classes should we automatically derive?

I think its too soon to consider `PartialEq` / `PartialOrder` because there are other issues with those classes that we have not yet resolved.

**Comment by magnus-madsen** [comment]
What other considerations are left for this ticket?

**Comment by mlutze** [comment]
- Still need to add a specific example for the website
- We have questions about efficiency: I think those are handled by other tickets
- Haskell derives some other classes: `Bounded`, `Enum`, `Read` (`FromString`). I think those also can wait.

**Comment by magnus-madsen** [comment]
- Instances for Records and Schemas.

**Comment by magnus-madsen** [comment]
So, only the fun tasks remain? 😃 😆

**Comment by mlutze** [comment]
Does that count as a `chore` commit? :'(

**Comment by magnus-madsen** [comment]
> Does that count as a `chore` commit? :'(

It counts as a `docs` commit. Your favorite!
