### ISSUE TITLE
Add `with` syntax to enum declarations

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2155]
Add support for the following syntax:

```scala
enum Color with Eq, Order, ToString {
  ...
}
```

(I am open to discuss the syntax).

Ensure that:

- [ ] A type class name is never repeated. 
- [ ] Every type class name is one of `Eq`, `Order`, and `ToString`.

**Comment by mlutze** [comment]
Should opaque types support this too?

**Comment by magnus-madsen** [comment]
> Should opaque types support this too?

No, lets not do it for now. We can revisit later and try to be smart.
