### ISSUE TITLE
Backend: Generate the `ReifiedSourceLocation` class.

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2174]

**Comment by JonathanStarup** [comment]
@magnus-madsen is the format method used anywhere? I'm assuming these three methods can be removed
```java
    public String format() {
        return this.source + ":" + this.beginLine + ":" + this.beginCol;
    }

    public boolean equals(Object o) {
        if (this == o) {
            return true;
        } else if (o != null && this.getClass() == o.getClass()) {
            ReifiedSourceLocation source1 = (ReifiedSourceLocation)o;
            return this.beginLine == source1.beginLine && this.beginCol == source1.beginCol && this.endLine == source1.endLine && this.endCol == source1.endCol && Objects.equals(this.source, source1.source);
        } else {
            return false;
        }
    }

    public int hashCode() {
        return Objects.hash(new Object[]{this.source, this.beginLine, this.beginCol, this.endLine, this.endCol});
    }
```

**Comment by JonathanStarup** [comment]
HoleError, MatchError, NotImplementedError, RuleError, SwitchError all rely on ReifiedSourceLocation so they all break now although the tests don't notice. @magnus-madsen if you merge this I can fix the dependencies tomorrow, but otherwise I can fix it all in one PR if you want.

**Comment by magnus-madsen** [comment]
> 
> 
> @magnus-madsen is the format method used anywhere? I'm assuming these three methods can be removed
> 
> ```java
>     public String format() {
>         return this.source + ":" + this.beginLine + ":" + this.beginCol;
>     }
> 
>     public boolean equals(Object o) {
>         if (this == o) {
>             return true;
>         } else if (o != null && this.getClass() == o.getClass()) {
>             ReifiedSourceLocation source1 = (ReifiedSourceLocation)o;
>             return this.beginLine == source1.beginLine && this.beginCol == source1.beginCol && this.endLine == source1.endLine && this.endCol == source1.endCol && Objects.equals(this.source, source1.source);
>         } else {
>             return false;
>         }
>     }
> 
>     public int hashCode() {
>         return Objects.hash(new Object[]{this.source, this.beginLine, this.beginCol, this.endLine, this.endCol});
>     }
> ```

I think those might actually be used. At least in certain rare circumstances.

**Comment by magnus-madsen** [comment]
Maybe not format.

**Comment by magnus-madsen** [comment]
> 
> 
> HoleError, MatchError, NotImplementedError, RuleError, SwitchError all rely on ReifiedSourceLocation so they all break now although the tests don't notice. @magnus-madsen if you merge this I can fix the dependencies tomorrow, but otherwise I can fix it all in one PR if you want.

In what sense?

**Comment by JonathanStarup** [comment]
I couldn't find format referenced in the project but I'll keep the others then.

The other errors take a ReifiedSourceLocation as constructor argument, but I've changed the existing code to push the new ReifiedSourceLocation so there is a jvm error "this constructor doesn't exist" if you just write def main(...): Int & Impure = ???

**Comment by magnus-madsen** [comment]
OK, so then everything has to be in the same PR so we don't break anything.

**Comment by JonathanStarup** [comment]
Alright, ill rename the PR and fix them all there 👍

**Comment by JonathanStarup** [comment]
Is there any reason why only some of the exceptions have tickets on them?

**Comment by magnus-madsen** [comment]
> 
> 
> Is there any reason why only some of the exceptions have tickets on them?

which are missing?

**Comment by JonathanStarup** [comment]
NotImplementedError, RuleError, SwitchError. And actually they all extend the old FlixError, which will also have two versions if you merge the other issue. Maybe I should just generate everything in flix-runtime.jar? The only one that is referenced in the compiler itself is FlixError, which I didn't catch earlier (Tester.scala 111, Main.scala 206).

Maybe everything should just be generated at once (except Char/Console possibly)?

**Comment by magnus-madsen** [comment]
I believe that `RuleError` and `SwitchError` are not used anymore. I am not sure about the rest. You should try to see.
