### ISSUE TITLE
Backend: Concurrency: Generate the `GlobalCounter` class.

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2176]

**Comment by JonathanStarup** [comment]
I am not sure what the issue here is, can't `java.util.concurrent.atomic.AtomicInteger` just be used directly

**Comment by magnus-madsen** [comment]
> I am not sure what the issue here is, can't `java.util.concurrent.atomic.AtomicInteger` just be used directly?
> 
> EDIT: oh I see, it's just to house a single static instance of an atomic integer

Yes, we need a global counter for the entire program. 

Fun question: Can it ever overflow? Google suggests not likely.
