### ISSUE TITLE
Datalog: Report variables that are used once as an error

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2180]
For example:

```
Path(x, y) :- Edge(x, y) // OK, makes sense.
Path(1, 2) :- Edge(1, dst) // dst is only used once.
```

should report that `dst` should be replaced by `_`. This could probably happen in the safety phase (or perhaps earlier?)

**Comment by JonathanStarup** [comment]
Maybe it would make sense to be able to name variables used once _abc to allow a middle ground between abc and _

**Comment by magnus-madsen** [comment]
> Maybe it would make sense to be able to name variables used once _abc to allow a middle ground between abc and _

Agreed. Using `_color` should be OK. Like we do for let.

**Comment by JonathanStarup** [comment]
How are the normal varibles handled? is it early desugaring to _ or is it handled later?

**Comment by magnus-madsen** [comment]
> How are the normal varibles handled? is it early desugaring to _ or is it handled later?

What do you mean? I think you should look in `Redundancy`.

**Comment by JonathanStarup** [comment]
What do you expect from `A(x) :- B(_y), C(_y)`? This should be an error right?

**Comment by magnus-madsen** [comment]
> What do you expect from `A(x) :- B(_y), C(_y)`? This should be an error right?
> 
> It doesn't automatically give an error like `A(_y) :- B(_y)` since the right side isn't "variable use" but more like declaration, but I feel like it should result in the same 'Hidden variable used' error

Yes, this should probably be an error.
