### ISSUE TITLE
LSP: Use Markdown for Hover

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2210]
For example here:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/api/lsp/provider/HoverProvider.scala#L66
https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/api/lsp/provider/HoverProvider.scala#L76
https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/api/lsp/provider/HoverProvider.scala#L89

We can return the string wrapped in backticks with the Flix language. Like so:

```
```flix
<string goes here>
```

**Comment by magnus-madsen** [comment]
@jhckragh Did we cover all types of hovering?

**Comment by jhckragh** [comment]
Yes, at least as far as I can tell. The PR #2286 should cover all the existing hovers. 🙂

**Comment by magnus-madsen** [comment]
Great!
