### ISSUE TITLE
LSP: Add support for codeAction

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2215]
Add skeleton support for codeActions that simply return the empty list.

**Comment by magnus-madsen** [comment]
@nicdard We don't have any code actions yet, but we could prepare the infrastructure to have them. 

Maybe there is a trivial code action we can come up with, just so that we can test the pipeline?

**Comment by magnus-madsen** [comment]
One idea is if you write:

```
pub enum Color {
  case Red, ...
}
```

then we could have a CodeAction to `"Add derive Eq"`.

**Comment by nicdard** [comment]
Seems good to me!

**Comment by magnus-madsen** [comment]
@nicdard Gentle ping :)

Do you think you could add a skeleton implementation? Just one that returns no code actions.

**Comment by nicdard** [comment]
Sorry! Yes sure last weekend I was travelling in the end, this other weekend I'll be working on this instead :) Sorry for all delays, really!

**Comment by magnus-madsen** [comment]
No worries, appreciate your help and expertise!

**Comment by nicdard** [comment]
I have started looking at this task :)

**Comment by magnus-madsen** [comment]
Fixed in master.
