### ISSUE TITLE
Unclosed interpolation

### ISSUE THREAD

**Issue by mlutze** [flix/flix#2219]
This
```scala
"${test"
```
Is not an error. Should it be?

**Comment by magnus-madsen** [comment]
What is it? I guess its the string "${test"?

**Comment by magnus-madsen** [comment]
In JavaScript such a thing is not allowed. I am not sure how we would reject it in the parser.

**Comment by mlutze** [comment]
Yes. It also seems that anything that cannot be parsed as an expression is just parsed as a string, e.g.
```scala
"${(noClosingParen}"
```
[Playground](https://play.flix.dev/?q=CYUwZgBAtghglgOwBQH0BcECCAnbMCeA2gMoAu2iA5gLoCUGAkgqRAGQQNQAOArtiBAC8EAN4AoCJIhcKzADbIARABIRi2gG4JUmYlIKkKkUgQB7AMJzTAZyoAFGPwQBfdVqkQAjGOdA)

**Comment by magnus-madsen** [comment]
It should be fixed, but its probably not terrible urgent. I assume it will require some hacking in the parser.

**Comment by magnus-madsen** [comment]
Fixed in master.
