### ISSUE TITLE
Add `min` and `max` to `PartialOrder`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2229]
Add `min` and `max` functions to `PartialOrder`.

Note that because two elements `x` and `y` may be incomparable (and hence not have a max/min) these functions must return `Option`.

**Comment by JonathanStarup** [comment]
Stuck since PartialOrder cannot currently depend on Option

**Comment by magnus-madsen** [comment]
We cannot do this at the moment because of the way the standard library is structured.
