### ISSUE TITLE
Brainstorm: Ideas for Quickfix

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2243]
- Undefined Def/Var => Suggest to create function definition.
- Undefined Def/Var => Suggest to `use` existing def.
- Undefined Enum Case => Suggest to create enum case.
- Undefined Enum Case => Suggest to import case.
- Undefined Type => Suggest to create type.
- Undefined Type => Suggest to `use` existing type.
- Derive `Eq`, `Order`, `ToString` etc.
- ... Look through other errors...

**Comment by magnus-madsen** [comment]
https://www.jetbrains.com/resharper/features/quick_fixes.html

**Comment by magnus-madsen** [comment]
@sockmaster27 Maybe you can start looking into whether there is some code action that you can implement on top of what we know have? It could be something from the above list or something else.

**Comment by magnus-madsen** [comment]
What i don't understand is how a code action becomes associated with a source location.

**Comment by sockmaster27** [comment]
The returned actions can then choose to make changes at any position in the entire workspace.

**Comment by magnus-madsen** [comment]
Ok. I managed to get something to work 👍 

I have now a good template in `CodeActionProvider` which you can build on. Have a look :)

**Comment by magnus-madsen** [comment]
Proposal for errors to handle:

- `ResolutionError.UndefinedName` - propose automatic import (i.e. a use)
- `ResolutionError.UndefinedVar` - propose automatic import (i.e. a use)
- `ResolutionError.UndefinedClass` - propose automatic import (i.e. a use)
- `ResolutionError.UndefinedOp" - propose automatic import (i.e. a use)
- `ResolutionError.UndefinedEffect" - propose automatic import (i.e. a use)
- `ResolutionError.UndefinedTag" - propose automatic import (i.e. a use)
- `ResolutionError.UndefinedType" - propose automatic import (i.e. a use)

- `ResolutionError.UnusedDefSym" - propose to prefix with `_`.
- `ResolutionError.UnusedEnumSym" - propose to prefix with `_`.
- `ResolutionError.UnusedEffectSym" - propose to prefix with `_`.
- `ResolutionError.UnusedFormalParam" - propose to prefix with `_`.
- `ResolutionError.UnusedTypeParam" - propose to prefix with `_`.
- `ResolutionError.UnusedVarSym" - propose to prefix with `_`.

**Comment by magnus-madsen** [comment]
- `TypeError.ImpureDeclaredAsPure` - propose to add `\ IO`.
- `TypeError.EffectfulDeclaredAsPure` - propose to add the effect.
- `TypeError.MissingEq` - propose to derive Eq // to implement Eq
- Ditto for `Ord` and `ToString`.

**Comment by mlutze** [comment]
`TypeError.MissingInstance` - propose to add a type constraint if it's a variable from the signature

**Comment by jaschdoc** [comment]
Not sure if this is a quick fix but would be nice to have a suggestion that reduces `x -> f(x)` to `f`

**Comment by sockmaster27** [comment]
@magnus-madsen 
> * `TypeError.ImpureDeclaredAsPure` - propose to add `\ IO`.
> * `TypeError.EffectfulDeclaredAsPure` - propose to add the effect.

What's the difference between these and `TypeError.MismatchedEffects`?

**Comment by magnus-madsen** [comment]
> @magnus-madsen
> 
> > * `TypeError.ImpureDeclaredAsPure` - propose to add `\ IO`.
> > * `TypeError.EffectfulDeclaredAsPure` - propose to add the effect.
> 
> What's the difference between these and `TypeError.MismatchedEffects`?

Yeah there is some overlap, but I think:

- ImpureDeclaredAsPure -> Declared as Pure, but requires `IO`.
- EffectfulDeclaredAsPure -> Declared as Pure, but requires a specific (user-defined) effect (e.g. `Console`).
- MismatchedEffects -> I think this is a more generic one where the effects are simply mismatched. 

Indeed the design is not great, but I think the point was to try to have a few error messages that were more specific than one general error message.

**Comment by sockmaster27** [comment]
Perhaps for unused variables and functions etc. we should also offer to simply remove them?

**Comment by magnus-madsen** [comment]
> Perhaps for unused variables and functions etc. we should also offer to simply remove them?

No. It is easy to delete code. We want quickfixes that help programmers learn the language.

**Comment by magnus-madsen** [comment]
> > * `ResolutionError.UnusedEnumSym` - propose to prefix with `_`.
> 
> Prefixing with `_` doesn't appear to have any effect on enums specifically

Ok. Maybe take a look in the `Redundancy` phase.

**Comment by sockmaster27** [comment]
> No. It is easy to delete code. We want quickfixes that help programmers learn the language.

Good point

**Comment by magnus-madsen** [comment]
Feel free to browser through the various errors and come up with more suggestions for quickfixes. Then post them here and we can discuss :)

**Comment by mlutze** [comment]
1. How hard would it be to make a CPS quickfix? Take a naive recursive function and make it CPS. Probably very hard?

2. Local visitor transformation. Take a function `A` and put its body into a local function `B`, which is called by `A`.

3. Helper extraction. Take a local function and extract it to a top-level private function, where local variables are changed to parameters.

**Comment by magnus-madsen** [comment]
We shall continue further brainstorming as GitHub discussions.
