### ISSUE TITLE
Improvements to Autocomplete

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2246]
- [x] #2247
- [x] #2248
- [x] #2249
- [x] #2250
- [x] #2251
- [x] #2252
- [x] Stabilize auto completion s.t. it feels less janky.

**Comment by paulbutcher** [comment]
- [ ] When you type a pipeline e.g. xs |> List.len and auto-complete we should drop the last argument to the function.

**Comment by paulbutcher** [comment]
> * [ ]  Stabilize auto completion s.t. it feels less janky.

Can we consider this done?

**Comment by magnus-madsen** [comment]
> > * [ ]   Stabilize auto completion s.t. it feels less janky.
> 
> Can we consider this done?

Ill ask the student programmers to play around with it and report back :)

**Comment by magnus-madsen** [comment]
- [ ] https://github.com/flix/flix/issues/2252
- [ ] Auto-complete record fields, predicate symbols.
- [ ] Auto-complete named types.
- [ ] Auto-complete tags.

**Comment by magnus-madsen** [comment]
Ideas for snippets:

- Maybe import (since its a bit complicated).

**Comment by magnus-madsen** [comment]
A bit of strangeness:

![image](https://user-images.githubusercontent.com/2287953/173250348-c8281ad8-02c2-440e-8b08-97462ff80dad.png)

**Comment by paulbutcher** [comment]
Hmm - I can see the same thing. Will investigate.

**Comment by paulbutcher** [comment]
https://github.com/flix/flix/issues/3938

**Comment by magnus-madsen** [comment]
It would be cool if we could do more precise ranking:

![image](https://user-images.githubusercontent.com/2287953/178008951-1962a1c1-fd37-4d39-9711-c09581166dfc.png)

You probably rarely want `Identity` and much more often want `Int32`. Could be an interesting (student) project to collect some statistics and use them to influence the ranking.

**Comment by paulbutcher** [comment]
> > > * [ ]    Stabilize auto completion s.t. it feels less janky.
> > 
> > 
> > Can we consider this done?
> 
> Ill ask the student programmers to play around with it and report back :)

Did you manage to reach a conclusion on this @magnus-madsen?

**Comment by magnus-madsen** [comment]
> > > > * [ ]     Stabilize auto completion s.t. it feels less janky.
> > > 
> > > 
> > > Can we consider this done?
> > 
> > 
> > Ill ask the student programmers to play around with it and report back :)
> 
> Did you manage to reach a conclusion on this @magnus-madsen?

I think the general feeling was that it works _much better_ than before 👍 (but still not at the level of a "professional" IDE like IDEA or the JavaScript plugin in VSCode... Hard to get there too.).

**Comment by paulbutcher** [comment]
Cool. Can we encourage reports of any janky behaviour so that we can improve over time?

**Comment by magnus-madsen** [comment]
Continued in https://github.com/flix/flix/issues/4554
