### ISSUE TITLE
LSP: Add auto-completion for `match exp (of type Foo)`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2252]
Alternatively, we could also start by just offering:

match x { ... all cases .. }

for all enums defined in the current file or namespace.

**Comment by magnus-madsen** [comment]
@paulbutcher Might be a fun project?

**Comment by paulbutcher** [comment]
I'm taking a look at this, and I can't see any way to get the type of a variable or expression from `Index` in the LSP (which is what would enable me to generate the correct cases)? Am I missing something?

**Comment by magnus-madsen** [comment]
> I'm taking a look at this, and I can't see any way to get the type of a variable or expression from `Index` in the LSP (which is what would enable me to generate the correct cases)? Am I missing something?

From Index you can get a `Entity.LocalVar(sym, tpe)` I think?

**Comment by magnus-madsen** [comment]
But unfortunately `ResolutionError.UndefinedName` cannot give you the types of symbols in scope because the "failure" happens before type inference :/

**Comment by magnus-madsen** [comment]
I think you have to do something like:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala#L267

**Comment by JonathanStarup** [comment]
Maybe you could also auto complete on `match Type`, this would become `match ??? { case A => ??? case B => ??? }`

**Comment by magnus-madsen** [comment]
See https://github.com/flix/flix/issues/4554
