### ISSUE TITLE
Backend: Improve support for Try-Catch

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2255]
We currently support the try-catch construct:

```scala
    pub def readLines(f: String): Result[List[String], String] & Impure = try {
            import new java.io.File(String) as newFile;
            import java.io.File.toPath();
            import java.nio.file.Files:newBufferedReader(##java.nio.file.Path);
            let javaFile = newFile(f);
            let javaPath = javaFile.toPath();
            let reader = javaPath.newBufferedReader();
            Ok(readAll(reader))
        } catch {
            case _: ##java.io.IOException => Err("I/O Error")
        }
```

This works, but has some bugs / limitations:

- [ ] We cannot bind a variable in the catch clause. This means we cannot get access to the error message!
- [ ] Unsure if it works with multiple different exception types.
- [ ] Unsure if it works with a default case.

This issue is a bit gnarly: I tried to fix it myself sometime ago, but I was never able to understand the right bytecode to generate. I am hoping a fresh pair of eyes will be useful!

Note: Flix users should NOT use exceptions. Flix does not support exceptions. This feature exists only for interop with Java.

**Comment by JonathanStarup** [comment]
I should be fixed now. I am unsure what you mean about a default case, wouldn't that just be `case e: ##java.lang.Exception => ...`

**Comment by JonathanStarup** [comment]
Nevermind, There is a problem regarding nested try-catch. the visitTryCatchBlock(..) calls are prioritized in order of occurrence, so when we generate the try-catches they are prioritized in reverse (i.e. the inner handler will never be hit unless allowed to by the type of exceptions involved)

**Comment by JonathanStarup** [comment]
@magnus-madsen This requires a traversal of the expressions, do you prefer a new phase, add it to finalize, or an extra traversal in genExpression?

**Comment by magnus-madsen** [comment]
Why does it require an extra traversal? Is it not just a question of the type of traversal?

**Comment by JonathanStarup** [comment]
I was thinking that any initial `visitExp(exp)` calls must first call `visitTryCatch(exp)`. I don't know how to add any info from the return value of visitExp since the instruction construction is instant. Maybe thunk the instruction generation?

**Comment by magnus-madsen** [comment]
What if we start by calling recursively? That would visit the inner expression first.

**Comment by JonathanStarup** [comment]
The exception handlers have to come before their labels are visited. So in the case of an outer try-catch with an inner expression there needs to be emitted the code: inner handlers -> outer handlers -> inner code -> outer code.
