### ISSUE TITLE
Improve Performance of Select Test Suites

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2269]
The following test suites could run faster if they used `LibraryNix` instead of what they currently use.

- [x] TestRedundancy (10s)
- [x] TestTyper (9s)
- [x] TestInstances (5s)
- [x] TestWeeder (1s)
- [x] TestParser (1s)
- [x] Combine LibrarySuite into one single Flix test (need to resolve name clashes).

It might even be worth toggling between different libraries in each individual test.

**Comment by magnus-madsen** [comment]
@mlutze Do you want to take an initial stab at this. Just see if there is some performance to be gained?

**Comment by magnus-madsen** [comment]
I see changes, but not necessarily speedups. Let see what happens on the PI 4.

**Comment by magnus-madsen** [comment]
I think these specific suites can be improved the same way:

- [ ] TestNamer
- [ ] TestResolver
- [ ] TestPatExhaustiveness

For others, its probably not worth it.

**Comment by mlutze** [comment]
PI 4?

**Comment by magnus-madsen** [comment]
Raspberry PI 4 

https://arewefast.flix.dev/

**Comment by magnus-madsen** [comment]
![image](https://user-images.githubusercontent.com/2287953/132122691-6f9993e5-e4b0-4c14-a67b-90b2eb5ab974.png)

Clear improvement
