### ISSUE TITLE
semicolon after cases of match/switch

### ISSUE THREAD

**Issue by olhotak** [flix/flix#228]
In the parser, the end of a case in a match has an optional semicolon, but the end of a case in a switch does not allow a semicolon. Is this inconsistency intentional?

**Comment by magnus-madsen** [comment]
Not sure exactly what you are referring to. Can you write the example?

**Comment by olhotak** [comment]
https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Parser.scala#L435
has optSC.

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Parser.scala#L445
does not have optSC.

Why the difference?

**Comment by magnus-madsen** [comment]
Yes. That is certainly an inconsistency.

**Comment by magnus-madsen** [comment]
We should have a discussion of where (and if) we want optional semi-colons. Previously, we decided that periods in facts/rules had to be non-optional #116.

**Comment by magnus-madsen** [comment]
I want to ask, and I don't have a strong opinion myself, should be remove optional semi colons?

**Comment by magnus-madsen** [comment]
Thinking more about it. In let-binding semi-colons are non-optional semantically meaningful entities, e.g.:

```
let foo = 42;
let bar = 21;
  foo + bar
```

Here `;` has a definite meaning and is NOT optional. One could argue that we should not make semi-colons optional anywhere if there is a use of them where they are non-optional.

**Comment by mhyee** [comment]
To be honest, I wasn't a big fan of removing the `let x = 42 in x` syntax, since the one-line `let x = 42; x` doesn't look as nice. But that's a different matter.

Anyway, I think we should remove optional semicolons. The semicolons in switch/match don't seem to serve any purpose (we don't need them for parsing).

**Comment by magnus-madsen** [comment]
It is true that `let x = 42; x` looks weird. But in real code:

```
let x = foo;
let y = bar;
  x + y
```

It looks pretty nice imho. 

I will remove optional semicolons. At least then there won't be any confusion about their use.

**Comment by magnus-madsen** [comment]
Removed optional semicolons.
