### ISSUE TITLE
Demote array length to semantic operator

### ISSUE THREAD

**Issue by mlutze** [flix/flix#2284]
Array length has a special syntax that clashes with record field selection, so we disallow `length` as a field in records.

We can get rid of this by introducing a new semantic operator `ArrayLength`, and calling `Array.length()` instead of using the postfix notation.

**Comment by magnus-madsen** [comment]
Whats the purpose? Whats the advantage? Is it because you find it irregular that you can write `a.length`?

**Comment by mlutze** [comment]
Yes, it seems weird to me that we have this special syntax for arrays that limits the expression of records. The `.length` syntax unnecessarily exposes the primitiveness of arrays.

I guess the same could be said about all array operations, but the other ones don't cost us anything since they don't conflict with other syntax.

**Comment by magnus-madsen** [comment]
I think there is consensus not to do this at this time. It can be revisited as part of a bigger refactoring, if the need arises.
