### ISSUE TITLE
LSP: Add Support for `lsp/documentSymbols`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2290]
## Flix Symbols:

We need to determine which of these are relevant:

- [ ] `DefnSym` / `SigSym`
- [ ] `EnumSym`
- [ ] `ClassSym`
- [ ] `VarSym`?
- [ ] `TypeAliasSym`?

What should we start with? Perhaps `DefnSym` or `EnumSym`?

Note that we have namespaces, but there is no namespace declaration as such.

**Comment by magnus-madsen** [comment]
@nicdard I suggest we work in this new ticket.

**Comment by nicdard** [comment]
I Magnus, I am having a bit of busy days due to Autumn semester start, I will resume my work as soon as I completely settle down. Looking forward to it!

In the meanwhile: I would start to work with those symbols who have a direct translation in a `SymbolKind` supported by LSP (as you suggested some things in Flix are not the same as in LSP, like `namespaces`). I would therefore opt for `EnumSym` or `ClassSym`. What do you think?

**Comment by magnus-madsen** [comment]
You could start with `EnumSym` there is definitely a 1-1 match.

I expect once you have one symbol in place everything will be easy!

**Comment by nicdard** [comment]
Cool!

I was trying to build the jar for the project after pulling latest updates, but `./gradlew jar` outputs more than 100 errors. For instance:
```
> Task :compileScala
[Error] /home/nicola/Documents/projects/flix/main/src/ca/uwaterloo/flix/Main.scala:21: object Shell is not a member of package ca.uwaterloo.flix.runtime.shell
[Error] /home/nicola/Documents/projects/flix/main/src/ca/uwaterloo/flix/Main.scala:52: not found: type SocketServer
[Error] /home/nicola/Documents/projects/flix/main/src/ca/uwaterloo/flix/Main.scala:109: not found: value Packager
[Error] /home/nicola/Documents/projects/flix/main/src/ca/uwaterloo/flix/Main.scala:113: not found: value Packager
[Error] /home/nicola/Documents/projects/flix/main/src/ca/uwaterloo/flix/Main.scala:117: not found: value Packager
[Error] /home/nicola/Documents/projects/flix/main/src/ca/uwaterloo/flix/Main.scala:117: not found: value loadClasses
```

Is there any fast solution to this probem @magnus-madsen ?

**Comment by nicdard** [comment]
No worries, sorry for it, I think I have fixed the issue :)

**Comment by nicdard** [comment]
https://github.com/flix/flix/pull/2375

**Comment by magnus-madsen** [comment]
Whats the status on this? Should we close it and then open new tickets for potential improvements?

**Comment by nicdard** [comment]
> Whats the status on this? Should we close it and then open new tickets for potential improvements?

I think so, as for now we decide that the feature are ok
