### ISSUE TITLE
Default instances

### ISSUE THREAD

**Issue by mlutze** [flix/flix#2295]
So far we have seen a couple potential type classes with the following properties:
1. implemented by every type (possibly under some conditions)
2. the same implementation for all types except a small subset

The such cases of which I am aware are:
1. `Default`/`Uninitialized`
2. `Boxable`

Both of these deal with the JVM primitive–object dichotomy, but there may be other use-cases.

My proposal is a **principled** overlapping instance, labeled a `default` instance.

```scala
default instance Boxable[a] {
  // ... defs that are currently default defs in the class
}
...
default instance Uninitialized[a] {
  pub def value(): a = null
}
```

With the default instance, a type is considered a member of the class if:
1. It has a non-default instance (as normal), or
2. All the class's type constraints are fulfilled (in which case the default instance is used)

In order to prevent the overlap from becoming a problem, we place the following restrictions on default instances:
1. The class must be `sealed`
2. The instance must not have type constraints

**Comment by magnus-madsen** [comment]
Boxable currently requires type constraints, right?

**Comment by mlutze** [comment]
> Boxable currently requires type constraints, right?

Type constraints on the class, but not on the instance.

**Comment by magnus-madsen** [comment]
Ah right

**Comment by magnus-madsen** [comment]
I think this is sensible. It would mostly be for our own consumption.

**Comment by magnus-madsen** [comment]
Do we need this anymore, now that we have typematch?

**Comment by mlutze** [comment]
Typematch covers our use-cases. Maybe eventually we will see a need for a more principled approach, so this idea could come back. But I think we can close this for now.
