### ISSUE TITLE
Non-tail recursive Eq of List

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2304]
https://arewefast.flix.dev/

Did we break something in the compiler?

**Comment by magnus-madsen** [comment]
![image](https://user-images.githubusercontent.com/2287953/132682748-8fc47e99-8cc7-44dc-97d7-6ebc98d8b78f.png)

**Comment by magnus-madsen** [comment]
@mlutze 
Possibly, but not necessarily, https://github.com/flix/flix/pull/2300 did this

**Comment by magnus-madsen** [comment]
It did not fail on GitHub CI

**Comment by magnus-madsen** [comment]
A few comments:
- We probably should not have tests that go up to 10_000 of anything (unless lazy).
- Probably something with equality/laziness changed in an unexpected way. This #2305 does not solve the problem, but just comments the problematic test cases.

**Comment by mlutze** [comment]
The `eq` function for `List` *should* be tail-recursive (assuming a short-circuiting `and`), but I'll look at what we're generating.

**Comment by magnus-madsen** [comment]
I don't think `e1 and e2` gets compiled to anything that is tail recursive.

**Comment by magnus-madsen** [comment]
We could:

- Open a ticket on tail recursion of lazy operators.
- Open a PR to restore List.eq (other types). Just so master is fixed.
- Open a ticket to discuss the best way to derive tailrec code.
