### ISSUE TITLE
Generalized instance for tuples

### ISSUE THREAD

**Issue by mlutze** [flix/flix#2312]
For a lot of classes we currently have a set of instances for tuples up to size 10. It would be nice to be able to declare a general tuple instance for a class that covers all tuples.

**Comment by magnus-madsen** [comment]
In general (pun intended) that is hard. 

For `Eq` or `Order` sure, but what about much richer type classes? Can we always assume a pointwise approach. 

Also, whats the downside? Some code in the standard library? That we rarely have to change?

Of course a problem is the "10" limit (which in Scala was 22- and even they lifted that).

**Comment by magnus-madsen** [comment]
I wonder what the problem would be if we upgraded to 20 everywhere. Would that reveal any breakages? (Type inference timeouts? Too long class names? etc)
