### ISSUE TITLE
Speed-up Lazy?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2328]
How can we speed-up lazy? Things to try:

- Remove the `initialized` Boolean and instead use the null/non-nullness of the closure?
- Delay the lock: Check the `value` field. If non-null return it. Otherwise, lock, re-read it and so forth.

@JonathanStarup If I update the ticket with a suitable benchmark and can you experiment with the above?

**Comment by mlutze** [comment]
> Remove the initialized Boolean and instead use the null/non-nullness of the closure?

If I write `force lazy null` does it deadlock?

**Comment by magnus-madsen** [comment]
> 
> 
> > Remove the initialized Boolean and instead use the null/non-nullness of the closure?
> 
> If I write `force lazy null` does it deadlock?

1. If you write `null` in a Flix program I will send Krampus after you (https://en.wikipedia.org/wiki/Krampus)
2. In the above program `null` because `_ -> null` which is a closure that is not null. So its not a problem. Basically we are saying, once the closure has been evaluated once it should not be evaluated again so we set it to null. We can then use this as a test to determine if the closure has been evaluated before.

**Comment by magnus-madsen** [comment]
Program:

```
use Benchmark.Benchmark;
use Benchmark.defBenchmark;

pub def bench1(): Benchmark = 
     defBenchmark("List", () -> { 
         List.range(1, 10_000) |>
         List.map(x -> x + 1) |>
         List.map(x -> x + 1) |>
         List.map(x -> x + 1)
    })

pub def bench2(): Benchmark = 
     defBenchmark("LazyList", () -> { 
         LazyList.range(1, 10_000) |>
         mapE(x -> x + 1) |>
         mapE(x -> x + 1) |>
         mapE(x -> x + 1 as & Impure)
    } as & Pure)

pub def mapE(f: a -> b & ef, l: LazyList[a]): LazyList[b] & Impure =
    let r = MutList.new();
    mapERec(f, l, r);
    MutList.foldRight((x, xs) -> ECons(x, xs), ENil, r)

def mapERec(f: a -> b & ef, l: LazyList[a], r: MutList[b]): Unit & Impure =
    match l {
        case ENil         => ()
        case ECons(x, xs) => 
            MutList.push!(f(x), r);
            mapERec(f, xs, r)
        case LCons(x, xs) => 
            MutList.push!(f(x), r);
            mapERec(f, force xs, r)
        case LList(xs)    => mapERec(f, force xs, r)
    }
    
def main(_args: Array[String]) : Int32 & Impure = 
    let bs = [bench1(), bench2()];
    Benchmark.runWithBudget(bs, 15_000_000_000i64);
    0
    
```
