### ISSUE TITLE
[Library] Update comments

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#233]
In the current library files (except `Int8.flix` which I updated) the following style is used:

```
    /**
     * Returns the number of bits used to represent an `Int16`.
     */
    def size: Int32 = 16
```

this should be changed to:

```
    ///
    /// Returns the number of bits used to represent an `Int16`.
    ///
    def size: Int32 = 16
```

which is the new style of comments supported by flixdoc.

**Comment by magnus-madsen** [comment]
@liampalmer43 Can we close this one now?

**Comment by liampalmer43** [comment]
@magnus-madsen Yes, sounds good.  I'm not sure how to close this issue, maybe I don't have permission to?
