### ISSUE TITLE
Add `toLazyList` to std lib

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#2347]
We should have conversion functions to `LazyList` in other data structures in the standard library.

- [x] List (maybe refactor to `List.toLazyList`)
- [x] Array
- [x] Set
- [x] Map

Others?

Related to #2307

**Comment by mlutze** [comment]
High-level question: what is the guiding principle for when to have the conversion function as `toX` and when to have it as `fromX`. The advantage of the latter is that the base original type's namespace doesn't need to know about the existence of the new type.

**Comment by jaschdoc** [comment]
Good point, however, I think if you choose the `fromX` convention you run into a weird problem from a usability perspective, where the newer data structures have more conversion functions `Y.fromX` than older ones. Suppose you want to convert back to data structure `X` now. It would make sense to have a `Y.toX` function, however, now there's the problem of having
- mixed two naming conventions and
- not having the same abstractions on every data structure.

I think we have to pick between
1. Every data structure being updated to "know about" the newly added data structure which leads to more a little work when adding new data structures.
2. Newer data structures having more conversion capabilities which leads to both inconsistent naming and user confusion.

Either way we should to add bi-directional conversion functions so I'd argue the consistency in naming is worth more in the long run.

**Comment by magnus-madsen** [comment]
I don't think we have any `fromX` nor should we have any.

**Comment by magnus-madsen** [comment]
It also nice to be able to type `List.` and see what is available, including `toLazyList`, `toMap` etc.

**Comment by jaschdoc** [comment]
Related to #2307
