### ISSUE TITLE
Tweaks to LazyList.map

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2349]
```
    ///
    /// Returns the result of applying `f` to every element in `l`.
    ///
    /// Applies `f` lazily (i.e. the tail is not forced).
    ///
    def mapL(f: a -> b, l: LazyList[a]): LazyList[b] = match l {
        case ENil         => ENil
        case ECons(x, xs) => LList(lazy LCons(f(x), lazy mapL1(f,       xs)))
        case LCons(x, xs) => LList(lazy LCons(f(x), lazy mapL1(f, force xs)))
        case LList(xs)    => LList(                 lazy mapL1(f, force xs))
    }

    // TODO: DOC
    def mapL1(f: a -> b, l: LazyList[a]): LazyList[b] = match l {
        case ENil         => ENil
        case ECons(x, xs) => LCons(f(x), lazy mapL1(f,       xs))
        case LCons(x, xs) => LCons(f(x), lazy mapL1(f, force xs))
        case LList(xs)    => LList(      lazy mapL1(f, force xs))
    }
```

This avoids some Lazy cells. Are there other opportunities like this? (Where we have double use of lazy?) Most care about core operations. Perhaps `flatMap`?

**Comment by jaschdoc** [comment]
# List of *too lazy* functions
- `LazyList.mapL`
- `LazyList.reverse` (maybe this should be lazy when invoking reverse, which on demand invokes an eager helper function)
- `LazyList.dropWhileL`
- `LazyList.dropHelper`
- `LazyList.filterL`
- `LazyList.flatten`
- `LazyList.zip` (should again maybe just return `LList(lazy zipHelper(l1, l2))`
- `LazyList.flatMapL`
- `LazyList.maWithIndexLAcc` (which should probably be renamed to `mapWithIndexHelper` and have the main fucntion return `LList(lazy mapWithIndexHelper(f, l, 0))`
- `LazyList.filterMapL`
- `LazyList.intercalate`

**This is a rough list and some of the functions may not belong in the list.**

**Comment by jaschdoc** [comment]
Related to #2307
