### ISSUE TITLE
Upper or Lowercase namespaces

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#235]
We currently allow namespaces to be both lower and uppercase, e.g.:

```
namespace my.NICE.NameSpace {}
```

This is inconsistent with many other parts of the language which is now case-sensitive. 

Furthermore, languages such as Java/Haskell/C++ enforce various styles. 

Java has packages (lower) and classes (upper): `java.lang.String`.
Haskell has all upper modules `Data.List`.
C++ has lowercase namespaces (?) `std::chrono::duration`.

I propose that we enforce lowercase namespaces. Thoughts?

**Comment by mhyee** [comment]
I don't remember if the namespace convention in Java/Haskell/C++ is *encouraged* or *enforced*.

However, in Flix, we do enforce capitalization of function and relation/lattice names, so it makes sense to enforce capitalization of namespaces.

I have a slight preference for uppercase (specifically, PascalCase), but I wouldn't object to all lowercase.

**Comment by magnus-madsen** [comment]
I changed my mind, I now prefer uppercase names. I think, ideally the Flix standard library would offer a fairly flat hierarchy of names, e.g. you would have `List`, `Set`, `Map` namespaces. I don't see the need to put these into a `Data` namespace as in Haskell.

I'm going to enforce uppercase namespaces once I get around to it.

**Comment by magnus-madsen** [comment]
Namespaces must now be uppercase.
