### ISSUE TITLE
Add support for let-rec

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#237]
Add support for let-rec (or similar primitive) to allow the use of recursive nested functions.

For example (proposed syntax):

```
def length[a](xs: List[a]): Int = {
  def visit[a](ys: List[a], c: Int): Int = match ys with {
    case Nil => c
    case r :: rs => visit(rs, c + 1)
  };  // <----- semi colon required
  visit(xs, 0)
}
```

(The outer block expression is just for readability.)

This ticket needs to address two issues:

(1) The syntax for nested functions.
(2) The compilation to letrec and/or interactions with lambda lifting.

**Comment by magnus-madsen** [comment]
Alternative syntax with explicit letrec and no types:

```
def length[a](xs: List[a]): Int = {
  let rec visit = (ys, c) => match ys with {
    case Nil => c
    case r :: rs => visit(rs, c + 1)
  };
  visit(xs, 0)
}
```

**Comment by magnus-madsen** [comment]
@mhyee I would like to hear your 2 cents on the syntax issue.

**Comment by magnus-madsen** [comment]
Here is python

```python
def make_adder(x):
    def add(y):
        return x + y
    return add
```

OCaml:
```ocaml
let f x =
      let g y = y * 5 in
      g (x + 1);;
```

**Comment by mhyee** [comment]
Let me see if I'm understanding this correctly. We already have nested functions:
```
def f(x): Int =
  let g = x -> x + 1; // was this the syntax for lambdas? what about 0-arg lambdas?
    g(x)
```

But we want *recursive* nested functions. In the example above, `g()` can't call itself.

---

I don't have a strong opinion (yet) on the syntax, but a few issues come to mind.

1. What does the syntax look like if we have mutual recursion between two nested functions?
2. What does the syntax look like if we interleave other let-bindings with nested function definitions?
3. How ugly does it get if we have many layers of nested functions?
4. If we omit types (as in the OCaml-ish second proposal you posted), can our type system handle that?

Our syntax has been mostly inspired by Scala, but the let-bindings have an OCaml flavour. Either of the two proposals you made should be fine, but I think I'm leaning slightly towards the first Scala-ish one. (The symmetry of the two function definitions looks slightly nicer to me.) I also think the Scala-style syntax would work better with the issues I outlined above.

**Comment by magnus-madsen** [comment]
I'll try to answer your questions bearing in mind that we haven't adopted a specific solution yet.

> 1. What does the syntax look like if we have mutual recursion between two nested functions?

> 2. What does the syntax look like if we interleave other let-bindings with nested function definitions?

> 3. How ugly does it get if we have many layers of nested functions?

You would probably write:
```
def foo(..): Int = 
  def bar(...): Int = ... 
  let xyz = 42;
  def baz(...): Int = ...;
  let uvq = 21;
    bar()
```

and foo, bar, and baz could all call each other recursive. Furthermore, baz can reference xyz, but not uvq. Mixing things like this would probably be bad style, so instead you would do:

```
def foo(..): Int = 
  def bar(...): Int = ... 
  def baz(...): Int = ...;
  let xyz = 42;
  let uvq = 21;
    bar()
```

or

```
def foo(..): Int = 
  let xyz = 42;
  let uvq = 21;
  def bar(...): Int = ... 
  def baz(...): Int = ...;
    bar()
```

Depending on where you need the lets. Note that we have block expressions, so if you want:

```
def foo(..): Int = {
  def bar(...): Int = { 
     ... 
  };
  def baz(...): Int = {
      ...  
  };
  let xyz = 42;
  let uvq = 21;
    bar()
}
```

> If we omit types (as in the OCaml-ish second proposal you posted), can our type system handle that?

Yes! I believe so, which is cool :-)

**Comment by magnus-madsen** [comment]
@JonathanStarup I am preparing a PR that adds support to the frontend. Then you can take over with the backend :)

**Comment by magnus-madsen** [comment]
Example to test:

```
pub def map(f: a -> b, l: List[a]): List[b] =
    def loop(m, acc) = match m {
        case Nil => acc
        case x :: xs => loop(xs, f(x) :: acc)
    };
    loop(l, Nil)

def main(_args: Array[String]): Int32 & Impure =
    map(x -> x + 1, 1 :: 2 :: Nil) |> println;
    0
```

**Comment by magnus-madsen** [comment]
@JonathanStarup I have added support for `LetRec` all the way through until `GenExpression`.

Could I ask you to take a look at what needs to happen there?

**Comment by magnus-madsen** [comment]
Another example to test with:

```
pub def indexOf(a: a, l: List[a]): Int32 with Eq[a] =
    def loop(m, i) = match m {
        case Nil     => -1
        case x :: xs => if (x == a) i else loop(xs, i + 1)
    };
    loop(l, 0)

def main(_args: Array[String]): Int32 & Impure =
    indexOf(2, 1 :: 2 :: Nil) |> println;
    0

```

**Comment by JonathanStarup** [comment]
So there is no mutual recursion? no forward referencing?

**Comment by magnus-madsen** [comment]
Not yet, so far just straight self recursion.

**Comment by magnus-madsen** [comment]
We take it one step at a time

**Comment by magnus-madsen** [comment]
LambdaLift l. 185:

```
      case SimplifiedAst.Expression.LetRec(varSym, exp1, exp2, tpe, loc) =>
        val e1 = visitExp(exp1)
        val e2 = visitExp(exp2)
        e1 match {
          case LiftedAst.Expression.Closure(defSym, freeVars, _, _) =>
            val idx = freeVars.indexWhere(freeVar => varSym == freeVar.sym, 0)
            if (idx == -1)
              LiftedAst.Expression.Let(varSym, e1, e2, tpe, loc)
              else
              LiftedAst.Expression.LetRec(varSym, defSym, Some(idx), e1, e2, tpe, loc)
            
          case _ => throw InternalCompilerException(s"Unexpected expression: '$e1'.")
        }
```

**Comment by magnus-madsen** [comment]
Amazing! Fixed after 5 years! Whew-- a lot has happened in the interim.
