### ISSUE TITLE
Brainstorm Ideas for CodeHints

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2382]

**Comment by mlutze** [comment]
Related question: how do hints relate to the "no warnings" principle?

**Comment by magnus-madsen** [comment]
> Related question: how do hints relate to the "no warnings" principle?

A warning in a traditional compiler is a message that the program may contain a bug or at least worrisome behavior. Such things are hard errors in Flix. 

A code hint is merely a suggestion. The code may be perfect fine as it is. Nothing is wrong. But it may give you some information about your code that you did not know.

**Comment by magnus-madsen** [comment]
We now have some useful code hints in master. 

We will continue to add them as we discover them.

CodeHints are not warnings, but more like extra information that is provided to VSCode (e.g. like auto-completion etc.).
