### ISSUE TITLE
Re-implement FormatType

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2386]
We should re-implement `FormatType` such that it assumes that types are well-kinded.

For ill-kinded types we can have a different pretty printer.

I propose the following strategy:

- Define a `SimpleType` AST.
- Translate `Type` into `SimpleType`. (The idea being that `SimpleType` is a representation closer to how types are printed.)
- Pretty Print `SimpleType` taking precedence into account. (E.g. print with the "right" number of parantheses).

**Comment by magnus-madsen** [comment]
I would also like a flag that can be enabled to print non-abbreviated types.

**Comment by mlutze** [comment]
Worth noting that well-kinded does not imply fully-applied

**Comment by mlutze** [comment]
One major issue that still needs resolution is the question of type variable names.

**Comment by magnus-madsen** [comment]
> One major issue that still needs resolution is the question of type variable names.

I think now that the right solution is to always do it w.r.t. a function signature. Of course that is not easy, because often we just have the type.

**Comment by mlutze** [comment]
Also, what should the formatting of `Region` be?

**Comment by magnus-madsen** [comment]
> 
> 
> I don't think they would be very rare. Say we try to unify `(Int, Int, Int)` with `(Int, Int)`. I think we'd end up with a message that says we cannot unify `(?, ?, ?)` with `(?, ?)`.

Yuck. I think we should not put in the `?`. I think if we have `(Int, Int, Int)` and `(Int, Int)` we should show the full type. I think our mistake has been to overly aggressively use `?`. We can still use it on other cases, e.g. `... -> Int` and `... -> Bool`. But we should be more sparingly with it. Maybe we should start almost without `?` and then just gradually add it in?

**Comment by magnus-madsen** [comment]
> 
> 
> How should we distinguish between relations and lattices? The old `FormatType` just threw a `<>` in there; I don't really know where that came from.

Its `(String, String, A)` or `(String, String; A)`. Its the semicolon that distinguishes.

**Comment by magnus-madsen** [comment]
> 
> 
> Also, what should the formatting of `Region` be?

For now, just something verbose e.g. `Region<r>` or whatever.

**Comment by mlutze** [comment]
> We could restrict FormatType to Kind Star?

I don't think we can without missing a lot of important cases. `List` has kind `Type -> Type` and we want to be able to say something like `There is already an instance of Functor for List`.

**Comment by mlutze** [comment]
Note to self: We can use the topological order of type aliases to ensure that they're unfolded as lazily as possible.

**Comment by mlutze** [comment]
@magnus-madsen The big blocker on this is the NameContext question. But the formatting of types in general is mostly orthogonal to that. I propose we start by merging the SimpleType stuff, using the current faulty naming mechanism, and work on NameContext separately.

**Comment by magnus-madsen** [comment]
Roger

**Comment by mlutze** [comment]
Resource for handling precedence: https://stackoverflow.com/questions/27471937/showsprec-and-operator-precedences

**Comment by magnus-madsen** [comment]
See also https://github.com/flix/buwb/blob/master/src/Bools.js#L191
