### ISSUE TITLE
Workspace Symbols should probably not contain library symbols?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2387]
Currently:

![image](https://user-images.githubusercontent.com/2287953/135587362-5cc814c7-541f-4d9f-8fbe-5eba2cfadfef.png)

**Comment by magnus-madsen** [comment]
I would expect it should only contain those symbols from the project itself.

**Comment by nicdard** [comment]
I think we can try to reduce them to only those within the project by checking for a "/" starting in the source uri
Do you think it can work?

**Comment by magnus-madsen** [comment]
> I think we can try to reduce them to only those within the project by checking for a "/" starting in the source uri Do you think it can work?

Maybe thats a bit too simple. But I don't know of a better solution. @mlutze ?

Perhaps we should look at the input files?

**Comment by nicdard** [comment]
Yes I don't really like this solution I proposed as well, but I don't really know another too :)

**Comment by mlutze** [comment]
A couple more considerations: 
In a well-formed Flix project, (probably) everything that should be indexed for this case is under `src` or `test`. So that case is easy(?)

We also have `fpkg` files that we might not want to index, whether or not in a proper project.

Intellij has a sort of manifest file that stores information about folders marked as source root, test root, etc. This is nice and principled but I think people would generally prefer a solution that "just works"

**Comment by magnus-madsen** [comment]
I think workspace symbols should only be those in the actual workspace (not in fpkgs or anywhere else).

**Comment by nicdard** [comment]
I have observed however that in typescript projects also those in `node_modules` are indexed

**Comment by magnus-madsen** [comment]
Hmm. Its just very slow to send all symbols to VSCode (imo). 

@nicdard How about we start with your proposal, we ignore symbols that start with `/`?--- as a temporary hack

**Comment by nicdard** [comment]
For me it's ok :+1:

**Comment by mlutze** [comment]
Will this also fix hints on stdlib functions?

**Comment by magnus-madsen** [comment]
From the Hinter? No... Which hints are bothering you?

**Comment by mlutze** [comment]
![Screenshot from 2021-10-02 12-01-58](https://user-images.githubusercontent.com/19153692/135711675-f31e9904-0362-462a-8b4b-fbc05facac05.png)

**Comment by magnus-madsen** [comment]
What was the decision on this?
