### ISSUE TITLE
Parser ambiguity

### ISSUE THREAD

**Issue by olhotak** [flix/flix#239]
Daniel found a grammar ambiguity between / as a namespace separator and division. Specifically, in `Math/min(1,2)` should this mean min in the Math namespace, or the enum constant Math divided by min(1,2)?

**Comment by magnus-madsen** [comment]
Cool. 

Ming-Ho and I were already aware of this potential ambiguity, but we did not decide what is "the right thing to do". At that time, we agreed that Math/min(1, 2) should parse as Math.min applied to (1, 2), and not as Math divided by min(1, 2).

**Comment by magnus-madsen** [comment]
If you want to divide Math by min(1,2) you just add a space, as in `Math / min(1, 2)`.

**Comment by magnus-madsen** [comment]
I remember we were talking about various separators, but the good ones `.`, `:`, and `::` are already taken.

**Comment by olhotak** [comment]
What about `#`? That's what Scala uses for selecting a member of a type.

**Comment by magnus-madsen** [comment]
Fixed by changing the syntax of namespaces.
