### ISSUE TITLE
Minimal MutDeque

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2410]
Implement a minimal and *well-tested* `MutDeque` which supports:

- [ ] `new`
- [ ] `size`
- [ ] `isEmpty`
- [ ] `popFront`
- [ ] `popBack`
- [ ] `pushFront`
- [ ] `pushBack`

Every other operation should be deferred to the future.

**Comment by JonathanStarup** [comment]
a capacity function could also be nice so `size == capacity` can be checked

**Comment by jaschdoc** [comment]
Oh wait I just realized the original MutDeque I made returns `Optional`. Why not just use that?

**Comment by magnus-madsen** [comment]
> Oh wait I just realized the original MutDeque I made returns `Optional`. Why not just use that?

Yes, let us use Option for partial operations.
