### ISSUE TITLE
Experimental and Deprecated Features

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2413]
An experimental feature is something that is available in the Flix compiler and/or standard library. An experimental feature may either make it into the language proper or be removed in the future. It is best not to rely on experimental features.

A deprecated feature is scheduled for removal and will be deleted from the compiler and/or standard library at some point.

Current Experimental Features:
- `reify` and `reifyType`.
- LetRegion
- `LazyList` / `Stream` / `DelayList` / `RevList` / `Iterator` -- please do not use any of these yet.

Current Deprecated Features:
- ~Uniform Function Call Syntax (UFCS) - pending removal, but waiting until `String` etc. has been updated.~
- ~`forall` and `exists`~
- ~`~>` impure arrow.~
- ~Eq, Order, and ToString (?) instances for refs and arrays.~

**Comment by magnus-madsen** [comment]
> 
> 
> Also deprecated:
> 
>     * Those space and time annotations

I am on the fence, but possibly yes. I don't think users should be using them at least.

**Comment by magnus-madsen** [comment]
> What about the `forall` and `exists` expressions?

I forget, are they not used in laws? If not then I guess we should remove them?

**Comment by mlutze** [comment]
> > What about the `forall` and `exists` expressions?
> 
> I forget, are they not used in laws? If not then I guess we should remove them?

They are not used. `forall` is just part of the syntax for declaring laws.

**Comment by magnus-madsen** [comment]
UFCS has been removed.

**Comment by magnus-madsen** [comment]
@mlutze Do you want to take a stab at removing forall/exists? 

Next up is `~>`, but its blocked by some bug in #2032.

**Comment by mlutze** [comment]
> @mlutze Do you want to take a stab at removing forall/exists?
> 
> Next up is `~>`, but its blocked by some bug in #2032.

This means removing the Linter completely, right?

**Comment by magnus-madsen** [comment]
> > @mlutze Do you want to take a stab at removing forall/exists?
> > Next up is `~>`, but its blocked by some bug in #2032.
> 
> This means removing the Linter completely, right?

Hmm. I forgot about that.

**Comment by magnus-madsen** [comment]
I think we can create tickets for when a specific feature becomes deprecated.
