### ISSUE TITLE
Add Support for Separate Compilation

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2414]
Purpose:

We want to support separate compilation, i.e. Java classes should not be loaded during compilation nor do they even have to exists. This will allow more easy use of external jars and also allow us to reference code not yet generated (e.g. `GlobalCounter`). The downside is that typos become runtime errors in the generated code.

Milestone 1: 
- Modify `FinalAst` to not use `java.lang.reflect.X` but instead to have either type descriptors or a small AST that represents the type of constructors, fields, methods, etc. Specifically we need
  - className.
  - method or field name (if not constructor).
  - full type signature.

Milestone 2:
- Modify all ASTs up until KindedAst? to not use `java.lang.reflect.X`.

Milestone 3:
- Eliminate use of  `java.lang.reflect.X` everywhere.
- Change surface syntax to carry full types (e.g. types of fields and return types).
- Update standard library everywhere.

EDIT: Consider an extra optional phase / switch that can check that classes exists.

**Comment by magnus-madsen** [comment]
> > The downside is that typos become runtime errors in the generated code.
> 
> So if I do `import java.util.OopsTypo`, I won't know it's an error until I run it?

That's right!

**Comment by mlutze** [comment]
> > > The downside is that typos become runtime errors in the generated code.
> > 
> > 
> > So if I do `import java.util.OopsTypo`, I won't know it's an error until I run it?
> 
> That's right!

This seems like a *huge* drawback! Could we instead do something like a `synthetic` or `native` keyword, so that 99% of the time we check that the class exists, unless we explicitly say that it will be generated later?

**Comment by magnus-madsen** [comment]
> > > > The downside is that typos become runtime errors in the generated code.
> > > 
> > > 
> > > So if I do `import java.util.OopsTypo`, I won't know it's an error until I run it?
> > 
> > 
> > That's right!
> 
> This seems like a _huge_ drawback! Could we instead do something like a `synthetic` or `native` keyword, so that 99% of the time we check that the class exists, unless we explicitly say that it will be generated later?

It is a *huuuuuuge* drawback! But it also has *huuuuuuge* benefits. I think that the solution will be either a flag to toggle the check (could be on by default) or alternatively a keyword. Nevertheless, this ticket is mostly about supporting both use cases. Then we can always fight over the default.

The problem at the moment is that we *cannot even use the code we generate*. Which is a *HUUUUUGE* inconvenience :D

**Comment by magnus-madsen** [comment]
> Or maybe more adventurous options like (system.time, threadID) or [UUID](https://docs.oracle.com/javase/8/docs/api/java/util/UUID.html)

All seems dangerous because two channels could be allocated back-to-back- in the same time instant essentially.

**Comment by magnus-madsen** [comment]
The conclusion was that we need the JARs but we don't have to run their static initializers etc. Thus we should be safe.
