### ISSUE TITLE
Datalog Examples

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2415]
- Compile a list of (active) Datalog projects (DLV, Souffle, ...).
- Compile a list of Datalog-like project (Datomic, Logicblox?, QL, ...)
- Record what kind of negation they support (if any).
- Collect a list of benchmarks from each project:
  - A real program (not a synthetic one).
  - Especially if it it uses negation.
- Search GitHub or StackOverflow for real Datalog programs.

Once a large list has been collected,
- Select a subset.
- Translate them to Flix.
- Try to make use of `query` and negation.

**Comment by JonathanStarup** [comment]
# Re-occurring rewriting patterns:
## Negated Wildcards
```
A(x) :- not B(x, _).
```
becomes
```
BFirst(x) :- B(x, _).
A(x) :- not BFirst(x).
```
## Modification in Negated Predicates
```
A(x) :- B(x), not C(xPlusOne), if xPlusOne== x + 1.
// xPlusOne is only negatively bound and cannot compile.
```
becomes
```
CPlusOne(x) :- C(x+1).
A(x) :- B(x), not CPlusOne(x).
```
