### ISSUE TITLE
Monomorph Enums and Tags

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#2417]
Right now Enums and tags are carried through the compiler with type-variables. This means that 
```
enum Something[a] {
  case A(Int)
  case B(a, Bool)
}
```
is represented like written all the way untill JVM generation where classes are generated based on type variable uses (maybe `Something$Int16` and `Something$Obj`).

Instead the enums could be monomorphed like functions are in the monomorph phase such that the enum is duplicated for each instantiation. If `a` is used as `Int`, `Option[Bool]` and `List[Option[Int]]` then the above is transformed to
```
enum Something$Int {
  case A(Int)
  case B(Int, Bool)
}
enum Something$Option$Int {
  case A(Int)
  case B(Option[Int], Bool)
}
enum Something$List$Option$Int {
  case A(Int)
  case B(List[Option[Int]] Bool)
}
``` 
This would then be reduced to the follwing set in the JVM generation phase (Int should be Int32 in general):
```
enum Something$Int {
  case A(Int)
  case B(Int, Bool)
}
enum Something$Obj {
  case A(Int)
  case B(Obj, Bool)
}
```
The cases might also need suffixes but I'm not sure. In the generated code cases are prefixed with the name of the enum so there is no collision there.

**Comment by mlutze** [comment]
I think this would fix https://github.com/flix/flix/issues/2113

**Comment by mlutze** [comment]
Fixed by enum monomorphization
