### ISSUE TITLE
[Frontend] Disambiguation of types in namespaces

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#242]
```
namespace foo {

    def f: Option[Bool] = None

}
```

```
-- TYPER ERROR --------------------------------------------------- foo.flix

>> Unknown type 'Option' (in namespace 'foo').

37|    def f: Option[Bool] = None
              ^^^^^^
```

**Comment by mhyee** [comment]
Is the right solution to search in the root namespace? What if there's a conflict? Do we want to generalize this and have some sort of `import` statement?

**Comment by magnus-madsen** [comment]
>> Is the right solution to search in the root namespace?

Not sure. It ultimately depends on whether and how imports will work, but in this case it seems reasonable.

>> What if there's a conflict?

The Namer reports duplicate definitions. The disambiguation has a deterministic order in which it performs lookups.

>> Do we want to generalize this and have some sort of import statement?

I think ultimately we want some kind of import statement, but we would need to think about what can be imported and how resolution should work.

**Comment by badouralix** [comment]
This issue is closed but the bug is still present in the [release v0.1](https://github.com/flix/flix/releases/tag/v0.1). Is there any workaround?

**Comment by magnus-madsen** [comment]
Import statements are planned, but not something anyone is correctly working on.

Do that answer your question, or did you have something else in mid?

**Comment by badouralix** [comment]
Yes, it does answer my question! Thanks 👍 
I am looking forward to the import statements, if it is the way to use compound types (other than tuples) in namespaces.
