### ISSUE TITLE
Add Tests for `reify`, `reifyEff`, `reifyBool`, and `reifyType`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2425]
- [ ] Add `Test.Exp.Reify.flix` tests.
- [ ] Add `Test.Exp.ReifyBool.flix` tests.
- [ ] Add `Test.Exp.ReifyEff.flix` tests.
- [x] #2427

**Comment by magnus-madsen** [comment]
Low priority.

**Comment by jaschdoc** [comment]
What other expressions / values / "things" can we use `reify` on other than effects? I'm not quite sure what the nuances are and I'd like to work on this when I get stuck sometime so this low-hanging fruit can be picked.

**Comment by magnus-madsen** [comment]
Superseded by `matchtype`.
