### ISSUE TITLE
Proposal: Only allow Unit & Impure statements and add ignore function 

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#2432]
When using impure functions with Result values like this
```
def loadResource(id: String): Result[Unit, String] & Impure = ...
```
it is easy to write code like
```
// ...
loadResource();
// ...
```
where the result is not handled. Places where you want to ignore the output anyway can be supported like so:
```
def ignore(_: _ & Impure): Unit & Impure = ()
```
```
// ...
loadResource() |> ignore;
// ...
```

**Comment by magnus-madsen** [comment]
Proposal:

- [ ] Add a check to `Redundancy` for `Stm` that emits a new error `UnusedValue` when a statement has a non-`Unit` type.
- [ ] Add a function `def ignore(_: a): Unit = ()` to `Prelude`. (Note: This my `ignore` is not impure).
- [ ] (To be debated): Add an expression `discard e` which evaluates to `e` and returns `()`. 

The last is an alternative to `ignore`, allowing one to write:

```
discard loadResource();
....
```

**Comment by magnus-madsen** [comment]
@JonathanStarup Do you want to take a stab at this?

**Comment by JonathanStarup** [comment]
@magnus-madsen I will close this. Should we add the `ignore` function to prelude? It is not listed in the new issue. Is this useful in higherorder functions?

**Comment by magnus-madsen** [comment]
Ignore in addition to `discard`? I think we can discuss it at the meeting.
