### ISSUE TITLE
Improve type errors for overriding type class functions with effects

### ISSUE THREAD

**Issue by felixwiemuth** [flix/flix#2438]
When overriding a type class function and defining it by delegating to a function of mismatching type, we get following not-so-readable error.

```
57 |     override pub def liftM2(f: t1 -> t2 -> r & e, m1 : Option[t1], m2 : Option[t2]) : Option[r] & e = Option.flatMap2(f, m1, m2)
                          ^^^^^^
                          unable to generalize the type scheme.


  Declared: ∀(t1, t2, e, r). t1 -> t2 -> r & e -> Option[t1] -> Option[t2] -> Option[r] & e
  Inferred: ∀(t1, t2, c, '66185). t1 -> t2 -> Option[c] & e -> Option[t1] -> Option[t2] -> Option[c] & '66185
```
Note that in addition to the numeric effect variables, in the inferred version the effect variable `e` is not quantified and the order of the variables under the forall is also swapped.

It is similar when also forgetting to declare the effect:
```
57 |     override pub def liftM2(f: t1 -> t2 -> Option[r] & e, m1 : Option[t1], m2 : Option[t2]) : Option[r] = Option.flatMap2(f, m1, m2)
                          ^^^^^^
                          unable to generalize the type scheme.


  Declared: ∀(t1, t2, e, r). t1 -> t2 -> Option[r] & e -> Option[t1] -> Option[t2] -> Option[r]
  Inferred: ∀(t1, t2, r, '66185). t1 -> t2 -> Option[r] & e -> Option[t1] -> Option[t2] -> Option[c] & '66185

57 |     override pub def liftM2(f: t1 -> t2 -> r & e, m1 : Option[t1], m2 : Option[t2]) : Option[r] = Option.flatMap2(f, m1, m2)
                          ^^^^^^
                          unable to generalize the type scheme.


  Declared: ∀(t1, t2, e, r). t1 -> t2 -> r & e -> Option[t1] -> Option[t2] -> Option[r]
  Inferred: ∀(t1, t2, c, '66185). t1 -> t2 -> Option[c] & e -> Option[t1] -> Option[t2] -> Option[c] & '66185
```

When instead only the effect declaration is missing, the error is fine:
```
57 |     override pub def liftM2(f: t1 -> t2 -> r & e, m1 : Option[t1], m2 : Option[t2]) : Option[r] = None
                          ^^^^^^
                          mismatched signature.


Expected scheme: ∀(t1, t2, e, r). t1 -> t2 -> r & e -> Option[t1] -> Option[t2] -> Option[r] & e with Monad[Option]
Actual scheme:   ∀(t1, t2, e, r). t1 -> t2 -> r & e -> Option[t1] -> Option[t2] -> Option[r] with Monad[Option]
```

Probably related to #2132 and #2133.

**Comment by magnus-madsen** [comment]
@mlutze Is it here:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Instances.scala#L156

we should be adding some friendlier messages?

**Comment by mlutze** [comment]
For this particular issue, it's difficult because typing comes before instance checking. So if you have a type error in your definition, we're going to catch that before we verify that your definition is actually the right one.

**Comment by felixwiemuth** [comment]
As far as I can see there is actually nothing wrong here with type classes. It is only about checking that the definition's type matches the declared type.

The issue here is that we get incorrect type schemes printed (not all variables quantified, numeric variables, different order). I updated the description with the "not all variables quantified" issue I just discovered.

**Comment by magnus-madsen** [comment]
@athas and I will explore this in a future project.

(Note to self: Effect errors can also arise from incorrect overriding of TC instances / assoc effects).
