### ISSUE TITLE
Refactor compiler messages to use rich strings and remove `VirtualTerminal`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2440]
The idea is to replace the `message`  and `summary` VirtualTerminal objects with rich strings like:

```
Foo bar baz <Red>This is Red</Red>
```

and then we will simply substitute `<Red>` and `</Red>` before printing.

I consider the VirtualTerminal as failed experiment.

**Comment by mlutze** [comment]
I agree that it's low-priority. But at least #1 should be very easy to implement (just make sure conversion is successful) and would get us a few thousand free checks,
