### ISSUE TITLE
Add principle on compiler messages

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2443]
# Compiler Messages

Flix compiler messages are designed around the following considerations:

A compiler message has three parts: (i) a summary, (ii) a main message, and (iii) an explanation. 

- The summary is a online description of the problem.
- The main message is a multi-line description of the problem which also shows the place(s) in the code where the problem occurs.
- The explanation describes *why* the problem occurs and *what* can be done to fix it.

By the default the explanation is not shown, unless: (a) the compiler is run with `--explain` (which can also be enabled in VSCode) or (b) there is three or less compiler messages.

The idea is to capture the fact that 80% of the time, a Flix programmer only needs minimal information to fix a problem, and 20% of the time he or she needs more information to understand the issue.

# Language in Compiler Messages

The text used in the compiler messages should be:

- Crisp, concise, and clear.
- Use a friendly tone. 
- Avoid "blaming" the programmer, but rather describe the problem matter-of-factly.

# Get to the point:

- "Duplicate definition foo" is better than "The function foo is defined twice" because the world "Duplicate immediately tells you what is wrong"

# Explain. should compare to other languages

**Comment by magnus-madsen** [comment]
@jaschdoc @JonathanStarup @mlutze Looking for feedback:

![image](https://user-images.githubusercontent.com/2287953/142991733-367a2b46-bf12-42be-a0da-3dc5be900337.png)

**Comment by magnus-madsen** [comment]
I think we should swap "Compiler Message" for "Compiler Error" to be more specific.

**Comment by mlutze** [comment]
I think we should also aim for consistency, e.g. using the same vocabulary among all the messages.

**Comment by magnus-madsen** [comment]
> I think we should also aim for consistency, e.g. using the same vocabulary among all the messages.

You mean a new principle? We could even list some of the words. ("undefined", "unexpected", "mismatched")

**Comment by JonathanStarup** [comment]
I don't know if this can be made into a principle but I think it's important to show (maybe just indicate) all relevant information.

I had a jvm error `no such field "value"`. This confused me because I was 100 percent sure it was there. It turned out the type of the field was wrong, so the message `no such field "value" of type Int` would have aided me in debugging. A Flix case could be a stratification error. Right now we list the loop as `A -> B -> C`. which is fine at the moment since the name is all that is considered. But if arity or types become relevant, they shouldn't be left out.

**Comment by jaschdoc** [comment]
What's your philosophy on presenting very technical messages to the user? I find that some of the boolean unification error messages can be cryptic and for programmers new to Flix they may not be helpful at all. Purity is not a hard concept to grasp for newcomers but the boolean formulae may just be a tad too technical.
Should we consider leaving technical matters out of the message / defer it to the explanation and write something like: "Mismatched Purity: fun1 is Impure, but fun2 expects f to be pure" - you can probably tell that I'm still not quite sure why those errors appear.
On the other hand, if I know what all the stuff means then it may be annoying to be forced to have `--explain` enabled for these errors and then have longer error messages for other things I find trivial (like unused variables for instance).

**Comment by magnus-madsen** [comment]
> What's your philosophy on presenting very technical messages to the user? I find that some of the boolean unification error messages can be cryptic and for programmers new to Flix they may not be helpful at all. Purity is not a hard concept to grasp for newcomers but the boolean formulae may just be a tad too technical. Should we consider leaving technical matters out of the message / defer it to the explanation and write something like: "Mismatched Purity: fun1 is Impure, but fun2 expects f to be pure" - you can probably tell that I'm still not quite sure why those errors appear. On the other hand, if I know what all the stuff means then it may be annoying to be forced to have `--explain` enabled for these errors and then have longer error messages for other things I find trivial (like unused variables for instance).

I think the messages should say that something was impure, but it was expected to be pure. Saying true is not false is useless. (Of course it requires more engineering effort to get to that point).
