### ISSUE TITLE
Add Flix support to Ace

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2445]
See https://github.com/ajaxorg/ace

**Comment by jaschdoc** [comment]
Reading list
https://github.com/ajaxorg/ace/blob/master/src/mode/scala_highlight_rules.js

**Comment by magnus-madsen** [comment]
@mR4smussen Is taking a look at this :)

**Comment by sockmaster27** [comment]
PR to upstream or fork?

**Comment by magnus-madsen** [comment]
Upstream,  if they allow it.

**Comment by magnus-madsen** [comment]
Our goal is to get all of these upstreamed

**Comment by sockmaster27** [comment]
See ajaxorg/ace#5356

**Comment by magnus-madsen** [comment]
Yay!
