### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#245]
As discussion previously, it is a common occurrence to have a data type for which not all values are legal. Take for example the interval lattice. We would like to define a variant `Range(Int, Int)` which denotes an interval from `b` to `e`. However, nothing prevents us from constructing the interval `Range(5, -5)` which is invalid.

Ondrej has proposed that such illegal values are identified with bottom. Thus e.g. `Range(5, -5)` and `Range(15, -15)`  would both be considered as bottom. This solves the problem of invalid values, but it destroy structural equality. However, we can fix that by picking one of these invalid values, say `Range(-1,1)` as the unique representative of bottom and mapping all other invalid values to this value.

In other words, we allow the programmer to define a `normalization` function:

```
def norm(e: Range): Range
```

which maps Range values into Range values. In this case both `Range(5, -5)` and `Range(15, -15)` would be mapped to `Range(1, -1)`.

Now, every time the tag `Range(b, e)` is constructed, the compiler must insert an explicit call to `norm`, i.e. `norm(Range(b, e))` except inside the `norm` function itself.

Furthermore, in a law like:

```
law monotone(f: ...): Bool = \forall(x: Range). ....`
```

The compiler must _also_ generate a let binding like so:

```
let x' = norm(x); ...
```

or alternatively when enumerating a type the norm function must be taken into account.

A few questions I still have:

(1) Does still strategy always work? 
(2) Are there any issues with inserting `norm` calls?
(3) What syntax should we use to associate a norm function with a type? Perhaps:

```
@normalization
def norm(...): ... = ...
```

(4) Does any other language have this feature?

**Comment by magnus-madsen** [comment]
The transformation itself should be fairly simple and would map a SimplifiedAst to a SimplifiedAst.

**Comment by magnus-madsen** [comment]
I am a bit worried about the ergonomics of this feature.

For example, here is how you would implement plus:

```
def plus(e1: Range, e2: Range): Range = match (e1, e2) with {
   case (Range(1, -1), _) => Range(1, -1)
   case (_, Range(1, -1)) => Range(1, -1)
   case (Range(b1, e1), Range(b2, e2)) => Range(b1 + b2, e1 + e2)
}
```

The way bottom is implicitly handled by the first two cases is a bit awkward, but worse (for Int8):

```
Range(0, 1) + Range(127, 127) = Range(127, -128) = Bottom
```

which is *not* what you wanted, and *not* monotone. 

Maybe this is not really a problem (afterall it is `plus` which is buggy and does not check for overflow), but it might still be confusing that the overflow is silently converted (normalized) to bottom (!).

**Comment by magnus-madsen** [comment]
In fact, in a refinement type system the line:

```
case (Range(b1, e1), Range(b2, e2)) => Range(b1 + b2, e1 + e2)
```

would trigger a warning that `b1 + b2` may overflow.

On the other hand, I remember there were some examples where normalization was really useful.

**Comment by olhotak** [comment]
(4) Does any other language have this feature?

Java and lots of others have equals and hashCode. There are various papers showing why these are a bad idea, e.g. Mandana Vaziri, Frank Tip, Stephen Fink, Julian Dolby:
Declarative Object Identity Using Relation Types. ECOOP 2007: 54-78

An arbitrary lattice can have any shape, and various numbers of elements. The basic features that a language has, such as primitive datatypes, and tuples and other features for constructing derived datatypes, enforce specific￼￼ constraints on how many elements any given type can have, and therefore prevent us from implementing some lattices. You can create any lattice by starting with a powerset lattice and collapsing elements. This is inefficient, so you generally want to pick a better starting point than the powerset lattice, but the step of collapsing elements is essential to going from the lattice that you implement with the type construction facilities down to the exact lattice that you wanted.

For functions such as plus, they should always be defined for normalized values, so match(norm(e1), norm(e2) ... instead of match(e1, e2). In fact, if we declare e1 and e2 to be of types, it should be Flix itself that enforces that all values are always normalized, and should not even allow you to pass unnormalized value to functions or store them in variables or anything.

The bug in the plus function has nothing to do with normalization. Without normalization, you get Range(127, -128), which is also not what you wanted, because it's an empty interval, and it's also not monotone.

**Comment by magnus-madsen** [comment]
>  it should be Flix itself that enforces that all values are always normalized

Yes. I agree and that is the transformation I discussed. Insert calls to `norm` on every `Range` constructor.

> For functions such as plus, they should always be defined for normalized values, so match(norm(e1), norm(e2) ... instead of match(e1, e2)

Why? I thought that the translation scheme would ensure that only normalized values flow through the program (except into `norm` itself).


However, there are some issues I tried to point out, but I was not being very explicit.

(1) *Currently* in a universal quantification (for the verifier): 
```
\forall x: T. <exp>
```
The compiler (verifier) has strategy for enumerating every value of type `T`. For infinite types (or components which are infinite), the compiler uses symbolic values.

Now, this strategy breaks with normalization (or has to take normalization into account) because the verifier is effectively constructing values (which may be illegal). So, it *can* be handled, but it is a special case to consider. Simplify inserting calls to `norm` for every constructor is not enough. I imagine a similar corner case with interop.

(2) Given an *incorrect* implementation, what kinds of errors can you expect?

My observation with the overflow was that a refinement type system (is that the correct name?) would immediately say that Range(b1 + b2, ...) is illegal because of overflow, whereas with our normalization the error would "occur later" saying that for such and such input the function is not monotone (and no overflow error would even be reported).

I am not arguing against this feature, I would like to have it. 
I am just trying to understand all the corner cases.

**Comment by olhotak** [comment]
(1) I don't get the problem. Let U be the type that you want to implement and T be the non-normalized Flix implementation/approximation of that type. You want to prove a property P(u) forall u in U. That's the same as proving P(norm(t) forall t in T.

(2) What's an overflow error? How is it defined in the typeclass laws? I think we're confusing two different things here, verification and execution. In the verification case, it does make sense to mark some outcomes as illegal and ask the verifier to report them.

**Comment by magnus-madsen** [comment]
(2) If the type Range(b: Int, e: Int) has the constraint that b < e then the verifier will ensure that is the case when you construct a Range value. If you allow any Range(b, e) to be valid (and then later map it to bottom) then you will get some other, possibly a monotonicity error. The difference is that e.g. an overflow error will be reported immediately and closest to the error location. A normalization step can *mask errors* and cause incorrect behavior to be observed later.

**Comment by magnus-madsen** [comment]
Here is what I imagine:


Assume the code is:

```
def plus(x: Range, y: Range): Range = match (x, y) with {
   // ...
   case (Range(b1, e1), Range(b2, e2)) => Range(b1 + b2, e1 + e2) // ups, forgot about overflow.
   // ...
}
```

***Scenario 1:***

We have declared `Range` with the constraint that `b <= e`.

```
==== VERIFIER ERROR  ====

   case (Range(b1, e1), Range(b2, e2)) => Range(b1 + b2, e1 + e2) // ups, forgot about overflow.
                                                 ^^^^^^^^^^^
                                                  fails to satisfy constraint b <= e.
```

***Scenario 2:***

With a normalization function:

```
==== VERIFIER ERROR  ====
Function plus is not monotone:

  Range(0, 0) + Range(127, 127) = Range(127, 127)
  Range(0, 1) + Range(127, 127) = Bot

```


Does this highlight the difference?

**Comment by magnus-madsen** [comment]
Here is an example of what I was talking about:

![image](https://cloud.githubusercontent.com/assets/2287953/21572922/efd28220-ceac-11e6-9e35-b15134c742ef.png)

This error message is *correct*, but *imprecise* because the `Range(-1, -9223372036854775808)` interval is actually `Bot`. To print the correct value, we would have to apply `norm` to values displayed in error messages, but that is fairly tricky...

**Comment by olhotak** [comment]
The conceptual idea is that normalization is a type constructor that takes an existing type A and a function f: A -> C, and creates a new type B, where B is the image of A under f. B is a subset of C, and B could be a subset of A, but does not necessarily need to be: A and C (and thus B) could be disjoint. Therefore, when reporting a counterexample to some property drawn from B, it would make sense to report the element of B that is the counterexample rather than a preimage of the counterexample from A.

**Comment by magnus-madsen** [comment]
Do you mean something like this?

```
enum Animal {
  case Fox,
  case Giraf,
  case Pickachu
}

enum Color from(f) {
  case Blue,
  case Red,
  case Yellow
}

def f(a: Animal): Color = match a with {
  case Fox => Red
  case Giraf => Yellow
  case Pickachu => Yellow
}

Note that here `B` (the image of A) is `Red` and `Yellow`, but not `Blue`.

**Comment by olhotak** [comment]
The idea is that B is some set that is difficult to express in Flix directly. For example, A could be pairs of integers (easy to express in Flix directly), and B could be { empty } union { (a,b) | a <= b }. You would define A in terms of Flix directly, and B as a new type defined using A and a function f. The function f does need to have a type A -> C, where C is some Flix type, but the idea is that it creates a new type B that is a subset of C. In your example, A is Animal, C is Color, and B is the set {Red, Yellow}, which is not explicitly defined in the Flix code.

**Comment by magnus-madsen** [comment]
@olhotak Can I give you the homework of writing some pseudo-code like above so I can see what it looks like?
