### ISSUE TITLE
Iterator - 2nd Attempt

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2459]
Introduction: 
An iterator is an ephemeral data structure. Accessing the elements of an iterator destroys it in the process. The benefit is that previous elements of the iterator can be garbage collected. To ensure safe use of an iterator, we adopt the following principles:

- All `Iterator` operations are marked Impure.
- A set of lazy operations transform an `Iterator` but require pure function arguments.
- A set of eager operations transform an `Iterator`, are effect polymorphic, and return `List`s.
- Terminal operations (e.g. `toList` or `foldLeft`) are effect polymorphic.
- To avoid common mistakes, `Iterator` has a smaller API than lists. (E.g. no `isEmpty`, no `count` etc.)
- `Iterator` does not implement any type classes.

Phase 1:

- [x] Start with an empty file (but feel free to reuse old code / tests where it makes sense).
- [x] Reuse the definition of `done` and `next`.
- [x] Add `range` and `repeat`.
- [x] Add `toIterator` to `Array`, `List`, `Nel`, `Set`, `Map`. 
- [x] Add terminal operations: `toArray`, `toList`, `toSet`, `toMap`.

Phase 3:
- [x] Add `filter` which is effect polymorphic and returns a `List`.
- [x] Add `map` which is effect polymorphic and returns a `List`. 
- [x] Add `foreach` which is effect polymorphic and returns `Unit`.

Phase 4:
- [x] Add `lazyFilter` which return a new iterator, is lazy, and requires a pure function.
- [x] Add `lazyMap` which returns a new iterator, is lazy, and requires a pure function.

Phase 5:

- [x] Add `toIterator` to Foldable.
- [x] Add `replace` which returns an iterator.
- [x] Add `append` which takes two iterators.
- [x] Add `zip` which zips two iterators into an iterator.
- [x] Add `lazyZipWith` which returns a new iterator, is lazy, and requires a pure function.
- [x] Add `zipWith` which is effect polymorphic and returns a `List`.

Phase 6:
- [x] Add terminal operations: `foldLeft` and `reduceLeft` which are effect polymorphic.

Phase 7:
- [x] Add `take` and `takeWhile` which returns a `List`.
- [x] To be determined: What about `drop` and `dropWhile`?

Phase 8:
- (Later): `flatMap`, `intercalate`, `intersperse` (lets stop here).

Checklist:

- [ ] Ensure _ALL_ operations are marked as impure.
- [ ] Ensure that there are _NO_ type class instances (no Eq, no Order, no ToString, no Functor, no Foldable).
- [ ] Ensure that every operation describes how much of the iterator it consumes.
- [ ] Ensure that comments make sense.
- [ ] Ensure that all functions occur in reasonable order.

**Comment by magnus-madsen** [comment]
I assume that a lot of functionality can be reused.

**Comment by jaschdoc** [comment]
I'm a bit unsure how to implement `lazyFilter`. If we simply wrap the original `next` function in a new next function like
```flix
...
let next1 = {
    let x = next();
    if (f(x)) x else ???
}
...
```
Then what do we return in the next function? It's also an option to implement a recursive function which invokes `next` until an element is found that satisfies `f` but that would lead to lots of crashes. Consider the program:
```flix
let f = _ -> false;
let iter = List.range(0, 1000) |> List.toIterator
let iter1 = Iterator.filter(f, iter);
let _ = Iterator.toList(iter1); // its `done` function returns false,
                                // but when `next` is invoked the end
                                // is reached and it turns out that 
                                // `done` was actually true and an
                                // empty iterator has its `next
                                // function invoked`, crashing the program.
```
One solution to this could be to return an iterator of type `Iterator[Option[a]]`. Did you have something else in mind?

**Comment by magnus-madsen** [comment]
I think you need to use a local mutable variable. Look at `filterL` here: https://github.com/flix/flix/commit/688f8fed038a3e27b2de084d078feee31e16c92d#diff-3780f9b0cfdda9f3c0ba59ce6e7fd3002f63dda21a762311f4eed7e6d6ef47a5

**Comment by magnus-madsen** [comment]
I suggest we complete `flatMap`, `intersperse` and `intercalate` and then stop there.
