### ISSUE TITLE
Implementation of `mod`/`%`/`rem`

### ISSUE THREAD

**Issue by mlutze** [flix/flix#2462]
The current implementation of `%` for integers is the same as the one for Java (except that we have `x % 0 == 0`):

```
-3 % -3 = 0
-2 % -3 = -2
-1 % -3 = -1
0 % -3 = 0
1 % -3 = 1
2 % -3 = 2
3 % -3 = 0

-3 % 3 = 0
-2 % 3 = -2
-1 % 3 = -1
0 % 3 = 0
1 % 3 = 1
2 % 3 = 2
3 % 3 = 0
```

The negative results might be surprising to some users, since we typically think of the modulus operator returning a result in the range `0 ... m`, and indeed in mathematics, `-1` is congruent to `2` modulo `3`, but the results of `-1 % 3` and `2 % 3` are different.

The question is: should we change the `%` implementation to return a mathematical modulus operation?

**Comment by JonathanStarup** [comment]
i think that unless people know the difference in advance, they expect mod to be positive (euclidean) so i think that should be the default (disagreeing with most other languages apparently). For the people in the know the other could be called truncMod or something more precise (not the best name). I think this sort of naming leads people who dont know the distinction to the right one. 

I dont know when you want the truncated modulo (in `a % b` it has the sign of a) so maybe its just a matter of speed?
