### ISSUE TITLE
TestLazyList triggers bad performance

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2483]

**Comment by magnus-madsen** [comment]
Its a parsing performance bug. Fun!

**Comment by magnus-madsen** [comment]
@mlutze What was it we changed recently?

**Comment by mlutze** [comment]
The named parameters change is a possible culprit. How do you know it's parsing-related?

**Comment by magnus-madsen** [comment]
Ill have a fix in the morning.
