### ISSUE TITLE
Add `.editorconfig` and `.gitattributes` config files?

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#2490]
These config files ensure that editors / IDEs behave consistently across different devices and that git converts and stores files in the same format. Additionally, tab sizes can be fixed such that custom IDE settings don't collide (using format file shouldn't change hundreds of lines).

Links
https://editorconfig.org/
https://git-scm.com/docs/gitattributes
https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes

I suggest using something like this for the `.editorconfig` file.
```editorconfig
# Top-most EditorConfig file
root = true

[**.{scala, md, flix, iml}]
end_of_line = lf
insert_final_newline = true
charset = utf-8
indent_style = space
indent_size = tab
trim_trailing_whitespace = true

[**.{scala, md, iml}]
tab_width = 2

[**.flix]
tab_width = 4
```

Note that VSCode requires downloading an extension for it to respect editorconfig

**Comment by magnus-madsen** [comment]
@jaschdoc Since you strong-armed me into adding .editorconfig we might as well add .gitattributes.

**Comment by jaschdoc** [comment]
Hehe okay dokay
