### ISSUE TITLE
Rethinking Interop

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#251]
The purpose of this ticket is to explore how we can improve interop with Java and Scala.

### Current State of Affairs

The main interface to Flix is the `Flix` class. Each instance of this class has a compiler, solver, model, etc. 

Flix values come in two kinds: Internal Flix values which (currently) are a mixed bag of members of the `Value` class/object and Java natives (e.g. `java.lang.Integer`.). Then there are the wrapped Flix values hidden behind the `IValue` which is supposed to make it transparent how Flix internally represents objects. There is also `IType` which presents type information from the compiler in a implementation independent way. Then there are hard-coded hacks in certain places for native Java/Scala collections.

Then there are hooks, again two kinds: Safe and Unsafe. Each is either an `Invokeable` or `InvokableUnsafe`:

```
@FunctionalInterface
trait Invokable {
  def apply(args: Array[IValue]): IValue
}
```

and

```
@FunctionalInterface
trait InvokableUnsafe {
  def apply(args: Array[AnyRef]): AnyRef
}
```

The interface for using these is:

```
def addHook(fqn: String, tpe: IType, inv: Invokable): Flix
def addHookUnsafe(fqn: String, tpe: IType, inv: InvokableUnsafe)
```

(Note that the type of the hook must be passed to `addHook` which is cumbersome, but necessary for type checking).

The idea was to have a "type safe" interface (which would be less performant) and an unsafe interface.

I think we have generally failed with this design:

- The `Value` class is a mess. We need a table that clearly shows how each type should be represented.
- Both `Flix` and `Value` have helper function constructors, e.g. `mkInt32` it is not clear which are supposed to be used.
- Exposing types even through `IType` is a mess.
- Exposing values via `IValue` and wrapper objects is/was perhaps a good idea, but is also a mess.  For example, why have `getInt8` when all it does is a cast. There is no type safety to be gained.

## New Proposal

General:

- Delete `IType`.
- Delete `IValue`.
- Delete constructors functions from `Flix`
- Delete constructors functions from `Value`.

### Values

Use the following table:

| Flix Type | Java Representation  |
|-----------|------------------------|
| BigInt      |java.math.BigInteger  |
|Closure    |flix.runtime.Closure(1)|
| Int8         |java.lang.Byte             |
| Int16       |java.lang.Short           |
| Int32       |java.lang.Integer        |
| Int64       |java.lang.Long           |
| Tag          |flix.runtime.Tag(2)     |
| Tuple      |scala.TupleN(3)          |
| Str           |java.lang.String         |

(1) A plain old Java class similar to:

```
final case class Closure(name: Symbol.DefnSym, bindings: Array[AnyRef])
```
Q: Is this only used by the interpreter?

(2) A plain old Java class similar to:
```
class Tag (name: String, value: AnyRef)
```

(3) Assuming the bytecode needed to call the constructor is reasonable and not magic.

Q: What about sets and maps?

### Adding Facts

We currently have no mechanism to add facts. Add the following methods to the Flix class:

```
def addFact(fqn: String, Array[AnyRef]) // Generic
def addFact(fqn: String, java.util.List[AnyRef]) // Generic Java
def addFact(fqn: String, java.util.Iterator[AnyRef]) // Generic Java
def addFact(fqn: String, scala.collection.TraversableOnce[AnyRef]) // Generic Scala
```

Here `fqn` is the name of the relation or table, e.g. could be just `"VarPointsTo"` or could be `analysis.domains/VarPointsTo`.

Q: We could allow you to add multiple facts at the same time, but is there any reason? You might aswell write the for loop yourself.

### Extracting Facts

We currently have the interface:

```scala
class Model(definitions: Map[Symbol.DefnSym, () => AnyRef],
            relations: Map[Symbol.TableSym, Iterable[List[AnyRef]]],
            lattices: Map[Symbol.TableSym, Iterable[(List[AnyRef], AnyRef)]]) {

  def getConstant(sym: Symbol.DefnSym): AnyRef =

  def getConstant(name: String): AnyRef = 
  def getRelation(name: String): Iterable[List[AnyRef]] =

  def getRelationOpt(name: String): Option[Iterable[List[AnyRef]]] =

  def getLattice(name: String): Iterable[(List[AnyRef], AnyRef)] =

  def getLatticeOpt(name: String): Option[Iterable[(List[AnyRef], AnyRef)]] =
```

Here I wonder whether the fields `definitions`, `relations`, and `lattices` should really be public or not.

Fundamentally, what are the things you want to do with the result?

Maybe all you need is:

```scala
trait Model {
  def eval(fqn: String): AnyRef = 
  def tableOf(fqn: String): java.lang.Iterator[Array[AnyRef]] =
}
```

but what about all sorts of convenience methods for Java and Scala?

This needs to be thought out more.

### Calling Java/Scala Functions from Flix: Part 1

Proposal: Delete hooks (both safe and unsafe). 

Add external definitions. In Flix:

```
namespace foo {
  external def sym(x: Int32, y: Int32): Int 
}
```

and link it:

```
flix.addExternal("foo/sum", (x: Int, y: Int) => x + y))
```

The type of `addExternal` would then have to be:

```
def addExternal[...](fqn: String, f: scala.Function2[...])
def addExternal[...](fqn: String, f: scala.Function3[...])
def addExternal[...](fqn: String, f: scala.Function4[...])
...
```

later we would also add `JFunction` for Java interop.

### Calling Java/Scala Functions from Flix: Part 2

Currently not possible. We used to have the old syntax `#foo.bar.baz()` but no more. Do we have any uses cases where this is needed? Perhaps it would be useful for the library, e.g.:

```
def reverse(x: Int32): Int32 = #java.lang.Integer.reverse(x)
```

but we would have to be careful with boxing.

**Comment by mhyee** [comment]
Yeah, `IType` seems to have only made things messier and more annoying.

Also, right now our only experience with interop is the IFDS implementation. I'm also using Flix for a class project, so we'll see how that goes.

> (1) A plain old Java class similar to:
>
> `final case class Closure(name: Symbol.DefnSym, bindings: Array[AnyRef])`
>
> Q: Is this only used by the interpreter?

Yes. (And I suppose the SymbolicEvaluator has something similar). The code generator produces bytecode that uses `invokedynamic` to construct the closure class at run time.scala

> (3) Assuming the bytecode needed to call the [tuple] constructor is reasonable and not magic.

Unfortunately, there's a bit of magic because Tuple is generic, but to avoid boxing, the Scala standard library has specialized versions.

```
// val a = (1,2)
// create a Tuple2 object (specialized for ints)
         0: new           #15                 // class scala/Tuple2$mcII$sp
         3: dup
// load the tuple elements (1 and 2)
         4: iconst_1
         5: iconst_2
// call the constructor with the tuple elements
         6: invokespecial #18                 // Method scala/Tuple2$mcII$sp."<init>":(II)V
         ...
// val b = (1, "two", 'c')
// create a Tuple3 object
        10: new           #20                 // class scala/Tuple3
        13: dup
// load the tuple element 1 and box it
        14: iconst_1
        15: invokestatic  #26                 // Method scala/runtime/BoxesRunTime.boxToInteger:(I)Ljava/lang/Integer;
// load the tuple element "two" from the constant pool
        18: ldc           #28                 // String two
// load the tuple element 'c' and box it
        20: bipush        99
        22: invokestatic  #32                 // Method scala/runtime/BoxesRunTime.boxToCharacter:(C)Ljava/lang/Character;
// call the constructor with the tuple elements
        25: invokespecial #35                 // Method scala/Tuple3."<init>":(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V
        ...
```

> Q: What about sets and maps?

I think we've discussed this before. Do we want our sets/maps to be defined in terms of Scala? But if we want to interop with Java, then maybe we should use Java sets/maps (which can be converted to Scala), except that they're mutable.

> We used to have the old syntax #foo.bar.baz() but no more. Do we have any uses cases where this is needed? Perhaps it would be useful for the library, e.g.:
>
> `def reverse(x: Int32): Int32 = #java.lang.Integer.reverse(x)`
>
> but we would have to be careful with boxing.

Yeah, boxing is a general problem we'll have to deal with. I also don't see a use case for directly referring to a Java static method, when you could always wrap it in a lambda and then use `addExternal`

**Comment by magnus-madsen** [comment]
>  I also don't see a use case for directly referring to a Java static method, when you could always wrap it in a lambda and then use addExternal

Yes,  you could use addExternal, but that is a bit cumbersome. If we could call static methods then all the goodies on e.g. `java.lang.Integer` and `java.lang.String` become immediately available. However, in the case of String, most of the useful methods are instance methods. How do we call those?

I was going to propose something like this:

```
def toUpperCase(s: Str): Str = #java.lang.String.toUpperCase(s)
```

so, during resolution of the method `java.lang.String.toUpperCase` if it is an instance method, then the first argument supplied in the call is assumed to be the `this` parameter. 

What do you think about this hack?

**Comment by mhyee** [comment]
If we really want to call external instance methods (without using `addExternal`), then I think this is a reasonable approach. Would it be clearer to use different syntax, or does that make things worse?

Also, at the moment, I would oppose to generalizing this to Flix method calls, e.g. making `3.bitcount resolve to `bitcount(3)`. I think we've discussed this before, and there are some nice use cases, but I don't see a strong need for it now.

**Comment by magnus-madsen** [comment]
PR #939 adds support for importing Java fields and methods.
