### ISSUE TITLE
Type.Var has no way to distinguish between the declaration site of the variable and the variable itself.

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2510]
Thus, for syntax highlighting, we cannot highlight both of these occurrences:

![image](https://user-images.githubusercontent.com/2287953/138650832-bc645efa-06f4-4741-bb6e-1b1eaba122b5.png)

**Comment by magnus-madsen** [comment]
@mlutze What do you think? 

Would we have `Symbol.UnkindedTypeVar` and `Symbol.KindedTypeVar` and `Type.Var` or what?

I think this refactoring will clarify a lot w.r.t. source locations because we will finally be able to talk about *two occurrences but of the same variable**.

**Comment by mlutze** [comment]
It seems reasonable to me. 

I took a shot at this previously with a slightly different implementation and things turned into a mess.

I'm not sure we can get rid of `Type.KindedVar` with this, but that question can be answered when trying out this implementation.

**Comment by magnus-madsen** [comment]
OK

**Comment by mlutze** [comment]
The first problem I'm hitting is that not every type refers to type symbol. Usually a `*Sym` means that it's present in the source code, right?

**Comment by magnus-madsen** [comment]
> The first problem I'm hitting is that not every type refers to type symbol. Usually a `*Sym` means that it's present in the source code, right?

What do you mean? Usually Sym means that something has a unique name.

**Comment by magnus-madsen** [comment]
The first step could be to introduce `Symbol.TypeVar(id: Int)` and then let `Type.Var` refer to that. Presumably that would require many lines to be changed, but would otherwise be straightforward?

**Comment by magnus-madsen** [comment]
> The first step could be to introduce `Symbol.TypeVar(id: Int)` and then let `Type.Var` refer to that. Presumably that would require many lines to be changed, but would otherwise be straightforward?

@mlutze Do you think this is viable?

**Comment by mlutze** [comment]
Yes, I think it would be ok, especially given our new synthetic/real location distinction.

**Comment by magnus-madsen** [comment]
Missing items (could be a new ticket):

- LSP hover
- LSP rename
- LSP find references

Some strange locations:

```
pub def mapWithKey(f: (k, v1) -> v2 & ef, m: Map[k, v1]): Map[k, v2] & ef =
    let Map(t) = m;
    Map(RedBlackTree.mapWithKey(f, t))
```

**Comment by mlutze** [comment]
![Screenshot from 2022-04-01 22-29-49](https://user-images.githubusercontent.com/19153692/161336976-45f2ebdc-63aa-4812-a7c3-51842b381c8c.png)

The last `ef` is not highlighted since it looks like we just don't visit the effect of sigs and defs.

The `k` and `v1` I'm still looking into but I suspect it has something to do with substitutions that happen on the second line.

**Comment by magnus-madsen** [comment]
Why is the RedBlackTree blue?

**Comment by mlutze** [comment]
Closing this. #3463 tracks the remaining items
