### ISSUE TITLE
Compiler progress output leaving trailing characters

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#2520]
When I run a program I see some leftover characters from the compiler status messages.
Specs: flix version 0.24.0, windows (not powershell), vscode run
The output of the program is this:
```
123123 edges were added                                                         x
```
Where the trailing x shouldn't be there. It is a leftover from a progress line like this
```
 [/] [Weeder] getVar                                          TestMain.flixe.flix
```

The program:
```
def main(_args: Array[String]): Int32 & Impure = 
    "${123123} edges were added" |> println;
    0
```

**Comment by magnus-madsen** [comment]
I think the solution is to  simply cut the string at length 80

**Comment by mlutze** [comment]
> I think the solution is to simply cut the string at length 80

Or do a nice `...` thingy at the end

**Comment by JonathanStarup** [comment]
random note: the files show should probably update every x time if possible (to show slow files, not just every x file)
