### ISSUE TITLE
Argument order of repeat

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#2531]
If you want to make a 10x50 array initialized with 0 you can write
```
use Array.repeat;
let arr = repeat(repeat(0, 10), 50);
```
but with pipes it could be nice to write
```
let arr = 0 |> repeat(10) |> repeat(50);
```
but this is not possible with the current value-first order of arguments. repeat is supported on many different types so they should all be changed for consistency.

**Comment by magnus-madsen** [comment]
- [ ] Find all functions named `repeat` and change them to take the number first and the subject second.

**Comment by magnus-madsen** [comment]
Fixed in master.
