### ISSUE TITLE
Parsing Error: Apply record field

### ISSUE THREAD

**Issue by mlutze** [flix/flix#2532]
This
```scala
pub def foo(): Int = {
  let r = { f = x -> x + 1 };
  (r.f(5))
}
```
produces a parsing error.
```
>> Parse Error:

Invalid input '(', expected LegalLetter, optWS, '.', "::" or ":::" (line 3, column 7):
  (r.f(5))
      ^
```

It's related to the parentheses around the expression `(r.f(5))` because this:
```scala
pub def foo(): Int = {
  let r = { f = x -> x + 1 };
  r.f(5)
}
```
parses without issue.

**Comment by magnus-madsen** [comment]
`Apply` requires a `Primary` but `RecordSelect` is above that in the grammar. 

Not sure exactly how to restructure.

**Comment by JonathanStarup** [comment]
From the referenced PR, `r.field[i]` does not parse and it seems like it should.

**Comment by magnus-madsen** [comment]
Fixed in master.
