### ISSUE TITLE
Bool.not function

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#2533]
Based on the program below I think it would be nice to have a `not` function in Bool.flix. It seems natural to include and would also allow `List.map(Bool.not, list)`
```
def reachable(edges: Array[(Int, Int)], start: Int, end: Int): Bool =
    let e = project edges into Edge;
    let lp = #{
        Path(x, y) :- Edge(x, y).
        Path(x, z) :- Path(x, y), Edge(y, z).
    };
    // this is the negated answer
    query (solve e, lp) select () from Path(start, end) |> Array.isEmpty
    // which means it have 
    // This could be nice to have
    // query (solve e, lp) select () from Path(start, end) |> Array.isEmpty |> Bool.not
```

**Comment by magnus-madsen** [comment]
- [ ] Add `Bool.not`
- [ ] Add `Bool.and` (the first argument of type Bool and then second of type `Lazy[Bool]`.)
- [ ] Add `Bool.or` (as above).

A few test cases for each should be good.

@ninaandrup Could I ask you to do it?

**Comment by magnus-madsen** [comment]
Fixed in master.
