### ISSUE TITLE
DelayMap

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2534]
Add a new data type `DelayMap`:

```
enum DelayMap[k, v] {
    case Map(RedBlackTree[k, Lazy[v]])
}
```

Phase 1:

- [x] `def empty()`
- [x] `def singleton(k: k, v: v)`
- [x] `def isEmpty(m: Map[k, v]): Bool`
- [x] `def get(k: k, m: Map[k, v]): Option[v] with Order[k]` // NB: This forces evaluation of the element.
- [x] `def insert(k: k, v: v, m: Map[k, v]): Map[k, v] with Order[k]`

Phase 2:
- [x] `def insertWith(f: (v, v) -> v & ef, k: k, v: v, m: Map[k, v]): Map[k, v] & ef with Order[k]` // NB: Purity polymorphic. If `f` is eager then it must be evaluated. Otherwise it can remain lazy.
- [x]  `def insertWithKey(f: (k, v, v) -> v & ef, k: k, v: v, m: Map[k, v]): Map[k, v] & ef with Order[k]` // NB: The above can probably just be implemented by calling this.

Phase 3:
- [x] `def map(f: v1 -> v2 & ef, m: Map[k, v1]): Map[k, v2] & ef with Order[k]` // NB: Purity polymorphic. 
- [x] `def mapWithKey(f: (k, v1) -> v2 & ef, m: Map[k, v1]): Map[k, v2] & ef with Order[k]` // NB: Purity polymorphic. 

Phase 4: 
- [x] `def union(m1: Map[k, v], m2: Map[k, v]): Map[k, v] with Order[k]` // should be lazy
- [x] `def unionWith(f: (v, v) -> v & ef, m1: Map[k, v], m2: Map[k, v]): Map[k, v] & ef with Order[k]` // NB: Purity polymorphic.

Phase 5:
- [ ] `def adjust(f: v -> v & ef, k: k, m: Map[k, v]): Map[k, v] & ef with Order[k]` // NB: Purity polymorphic.
- [ ] `def adjustWithKey(f: (k, v) -> v & ef, k: k, m: Map[k, v]): Map[k, v] & ef with Order[k]` // NB: Purity polymorphic.
- [ ] `def update(f: v -> Option[v] & ef, k: k, m: Map[k, v]): Map[k, v] & ef with Order[k] ` // NB: Purity polymorphic.
- [ ] `def updateWithKey(f: (k, v) -> Option[v] & ef, k: k, m: Map[k, v]): Map[k, v] & ef with Order[k]` //NB: Purity polymorphic.

Please do not make changes to `RedBlackTree`-- unless we have talked about it first.

Feel free to implement `toList` or whatever for testing.

(By `Map` I mean `DelayMap`- just lazy copy paste).

Feel free to reuse implementation from `Map.flix`.

**Comment by jaschdoc** [comment]
Are `Map` and `DelayMap` supposed to be used interchangeably? `def insert(k: k, v: v, m: Map[k, v]): Map[k, v] with Order[k]` takes a `Map` and Produces a `Map`. Is this on purpose or should the types be `DelayMap`?

**Comment by magnus-madsen** [comment]
> 
> 
> Are `Map` and `DelayMap` supposed to be used interchangeably? `def insert(k: k, v: v, m: Map[k, v]): Map[k, v] with Order[k]` takes a `Map` as a parameter and produces a `Map`. Is this on purpose or should the types be `DelayMap`?

Everything should be DelayMap

**Comment by jaschdoc** [comment]
I'm completely stuck on this `mapWithKey`. I have no idea why the type system throws this error.

```
>> The type scheme: '∀(k, v, b). k -> v -> b -> DelayMap[k, a] -> DelayMap[k, v]' cannot be generalized to '∀(k, v, ef, b, a). k -> v -> b & ef -> DelayMap[k, a] -> DelayMap[k, b] & ef'.

101 |     pub def mapWithKey(f: (k, v) -> b & ef, m: DelayMap[k, a]): DelayMap[k, b] & ef =
                  ^^^^^^^^^^
                  unable to generalize the type scheme.


  Declared: ∀(k, v, ef, b, a). k -> v -> b & ef -> DelayMap[k, a] -> DelayMap[k, b] & ef
  Inferred: ∀(k, v, b). k -> v -> b -> DelayMap[k, a] -> DelayMap[k, v]

```

Here is the code.

```flix
namespace RedBlackTree {
    use RedBlackTree.RedBlackTree.{Leaf, DoubleBlackLeaf, Node};
    use RedBlackTree.Color.{Red, Black, DoubleBlack};

    pub def mapWithKey(f: (k, v) -> b & ef, tree: RedBlackTree[k, v]): RedBlackTree[k, b] & ef = match tree {
        case Node(color, left, k, v, right) => Node(color, mapWithKey(f, left), k, f(k, v), mapWithKey(f, right))
        case _                              => Leaf
    }

}

namespace DelayMap {
use RedBlackTree.RedBlackTree;
    ///
    /// Returns a map with mappings `k -> f(k, v)` for every `k -> v` in `m`.
    ///
    pub def mapWithKey(f: (k, v) -> b & ef, m: DelayMap[k, a]): DelayMap[k, b] & ef =
        let DMap(tree) = m;
        if (reify ef)
            let f1 = (k, v) -> lazy f(k, force v) as & Pure;
            DMap(RedBlackTree.mapWithKey(f1, tree))
        else
            let f1 = (k, v) -> {
                let x1 = f(k, force v);
                lazy x1
            };
            DMap(RedBlackTree.mapWithKey(f1 as & Impure, tree)) as & ef
```

**Comment by jaschdoc** [comment]
Same thing happens here:
```flix
namespace DelayMap {
    use RedBlackTree.RedBlackTree;

    ///
    /// Returns the union of `m1` and `m2` where key collisions are resolved with the merge function `f`, taking both the key and values.
    ///
    pub def unionWithKey(f: (k, v, v) -> v & ef, m1: DelayMap[k, v], m2: DelayMap[k, v]): DelayMap[k, v] & ef with Order[k] =
        if (reify ef)
            unionWithKeyHelper((k, v1, v2) -> lazy f(k, force v1, force v2) as & Pure, m1, m2)
        else
            let f1 = (k, v1, v2) -> {
                let x = f(k, force v1, force v2) as & Impure;
                lazy x
            };
            unionWithKeyHelper(f1 as & Impure, m1, m2) as & ef

    ///
    /// Helper function for `unionWithKey`.
    ///
    def unionWithKeyHelper(f: (k, Lazy[v], Lazy[v]) -> Lazy[v] & ef, m1: DelayMap[k, v], m2: DelayMap[k, v]): DelayMap[k, v] & ef with Order[k] =
        use RedBlackTree.{blackHeight, foldRight, insertWith};
        let DMap(xs) = m1;
        let DMap(ys) = m2;
        if (blackHeight(xs) < blackHeight(ys))
            DMap(foldRight((k, v) -> insertWith(f, k, v), ys, xs))
        else
            DMap(foldRight((k, v) -> insertWith((_, v1, v2) -> f(k, v2, v1), k, v), xs, ys))
}
```
>> The type scheme: '∀(k, v). k -> v -> v -> v -> DelayMap[k, v] -> DelayMap[k, v] -> DelayMap[k, v]' cannot be generalized to '∀(k, v, ef). k -> v -> v -> v & ef -> DelayMap[k, v] -> DelayMap[k, v] -> DelayMap[k, v] & ef'.

151 |     pub def unionWithKey(f: (k, v, v) -> v & ef, m1: DelayMap[k, v], m2: DelayMap[k, v]): DelayMap[k, v] & ef with Order[k] =
                  ^^^^^^^^^^^^
                  unable to generalize the type scheme.


  Declared: ∀(k, v, ef). k -> v -> v -> v & ef -> DelayMap[k, v] -> DelayMap[k, v] -> DelayMap[k, v] & ef
  Inferred: ∀(k, v). k -> v -> v -> v -> DelayMap[k, v] -> DelayMap[k, v] -> DelayMap[k, v]

```
The effect is ignored for some reason. Maybe it has something to do with lazy values always being pure and so when returning `lazy x` in the function `f1` the type system assumes the function must be pure??? I'm really not sure what's going on.

**Comment by magnus-madsen** [comment]
Its the problem with lazy again. If you write `lazy e` then you must cast `e` to pure.

**Comment by magnus-madsen** [comment]
Here `let f1 = (k, v) -> lazy f(k, force v) as & Pure;` you cast the result to pure, but the real problem is **also** that `lazy f(...)` forces `f` to be pure which is not consistent with the signature you want to use. So you should do something like `lazy (f(...) as & Pure)`.

**Comment by jaschdoc** [comment]
You're a lifesaver :1st_place_medal:

**Comment by magnus-madsen** [comment]
Think of it this way, when you say `lazy e` you are implicitly saying that `e` is pure thus you cannot generalize it to effect polymorphic.

**Comment by magnus-madsen** [comment]
@jaschdoc Do you have a mental map of which of the above we have now and which are missing?

**Comment by jaschdoc** [comment]
Yes, we only need phase 5 which I'm fairly close to finishing

**Comment by jaschdoc** [comment]
I think I'm struggling with the `lazy` keyword again and the compiler message is not very helpful. It doesn't tell me where my error could be or gives any pointers to possible solutions.

```flix

    ///
    /// Updates `m` with `k -> v1` if `k -> v` is in `m` and `f(k, v) = Some(v1)`. Otherwise, returns `m`.
    ///
    pub def updateWithKey(f: (k, v) -> Option[v] & ef, k: k, m: DelayMap[k, v]): DelayMap[k, v] & ef with Order[k] =
        let DMap(t) = m;
        if (reify ef)
            let f1 = (k, v) -> {
                let res = lazy match f(k, force v) {
                    case Some(v1) => v1
                    case None     => force v
                } as & Pure;
                Some(res)
            };
            DMap(RedBlackTree.updateWith(f1, k, t))
        else
            let f1 = (k, v) -> match f(k, force v) {
                case Some(v1) => Some(lazy v1)
                case None     => None
            };
            DMap(RedBlackTree.updateWith(f1, k, t)) as & ef
```

```
>> The type scheme: '∀(k, v). k -> v -> Option[v] -> k -> DelayMap[k, v] -> DelayMap[k, v]' cannot be generalized to '∀(k, v, ef). k -> v -> Option[v] & ef -> k -> DelayMap[k, v] -> DelayMap[k, v] & ef'.

223 |     pub def updateWithKey(f: (k, v) -> Option[v] & ef, k: k, m: DelayMap[k, v]): DelayMap[k, v] & ef with Order[k] =
                  ^^^^^^^^^^^^^
                  unable to generalize the type scheme.


  Declared: ∀(k, v, ef). k -> v -> Option[v] & ef -> k -> DelayMap[k, v] -> DelayMap[k, v] & ef
  Inferred: ∀(k, v). k -> v -> Option[v] -> k -> DelayMap[k, v] -> DelayMap[k, v]
```

**Comment by magnus-madsen** [comment]
I think your use of lazy forces f to be pure.

Ill merge in #2592 soon. Hopefully that can help.

**Comment by jaschdoc** [comment]
I tried rewriting `updateWithKey` to use `reifyEff(f)` but the error persists. When `f` has an effect `ef` the result must still be of type `Option[Lazy[v]]`, but whenever the `lazy` keyword is used within a function body, the entire function is deemed pure which is obviously not true. The `updateWithKeyE` function causes the issue.
```flix

    ///
    /// Updates `m` with `k -> v1` if `k -> v` is in `m` and `f(k, v) = Some(v1)`. Otherwise, returns `m`.
    ///
    pub def updateWithKey(f: (k, v) -> Option[v] & ef, k: k, m: DelayMap[k, v]): DelayMap[k, v] & ef with Order[k] =
        reifyEff(f) {
            case Pure(g) => updateWithKeyL(g, k, m)
            case _       => updateWithKeyE(f, k, m)
        }

    ///
    ///
    ///
    def updateWithKeyL(f: (k, v) -> Option[v], k: k, m: DelayMap[k, v]): DelayMap[k, v] with Order[k] =
        let DMap(t) = m;
        let f1 = (k, v) -> {
            let res = lazy match f(k, force v) {
                case Some(v1) => v1
                case None     => force v
            };
            Some(res)
        };
        DMap(RedBlackTree.updateWith(f1, k, t))

    ///
    ///
    ///
    def updateWithKeyE(f: (k, v) -> Option[v] & ef, k: k, m: DelayMap[k, v]): DelayMap[k, v] & ef with Order[k] =
        let DMap(t) = m;
        let f1 = (k, v) -> {
            let res = f(k, force v);
            match res {
                case Some(v1) => Some(lazy v1)
                case None     => None
            }
        };
        DMap(RedBlackTree.updateWith(f1, k, t))
```
```
>> The type scheme: '∀(k, v). k -> v -> Option[v] -> k -> DelayMap[k, v] -> DelayMap[k, v]' cannot be generalized to '∀(k, v, ef). k -> v -> Option[v] & ef -> k -> DelayMap[k, v] -> DelayMap[k, v] & ef'.

222 |     pub def updateWithKey(f: (k, v) -> Option[v] & ef, k: k, m: DelayMap[k, v]): DelayMap[k, v] & ef with Order[k] =
                  ^^^^^^^^^^^^^
                  unable to generalize the type scheme.


  Declared: ∀(k, v, ef). k -> v -> Option[v] & ef -> k -> DelayMap[k, v] -> DelayMap[k, v] & ef
  Inferred: ∀(k, v). k -> v -> Option[v] -> k -> DelayMap[k, v] -> DelayMap[k, v]
```

**Comment by magnus-madsen** [comment]
Its more complicated because f takes two arguments, so essentially you have to uncurry and then recurry. It is a bit hard to explain.

**Comment by magnus-madsen** [comment]
I suggest you try to use `reifyEff` first in some simpler cases. Then. when that is done, try to get it to work for a made up examples with a function of two arguments.

**Comment by magnus-madsen** [comment]
The essence of the latter is something like:

```
reify(uncurry(f)) { case Pure(g) => foo(curry(g))
```
```

**Comment by jaschdoc** [comment]
Alright, thanks, I'll try fiddling with it
