### ISSUE TITLE
`Int32.parseHex`

### ISSUE THREAD

**Issue by mlutze** [flix/flix#2539]
Or some better name. We don't have anything for parsing non-base 10 numbers

**Comment by JonathanStarup** [comment]
Maybe a general method, implemented by [`Integer.parseInt(s, radix)`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Integer.html#parseInt(java.lang.String,int)) could be nice instead of hex specifically.

**Comment by mlutze** [comment]
Related: https://github.com/flix/flix/pull/3005

**Comment by magnus-madsen** [comment]
Lets add `Int32.parse(s, radix)` and `Int64.parse(s, radix)`.

**Comment by ninaandrup** [comment]
Do we want subject last? `Int32.parse(s: String, radix: Int32)` or  `Int32.parse(radix: Int32, s: String)`?

**Comment by magnus-madsen** [comment]
I consider the string to be the subject, so the string should be last.
