### ISSUE TITLE
Http Client

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2547]
I would like to design an API for a HttpClient based on `java.net.http.HttpClient`. 

Does anyone know if this code can be ported to Flix:

```
   HttpClient client = HttpClient.newBuilder()
        .version(Version.HTTP_1_1)
        .followRedirects(Redirect.NORMAL)
        .connectTimeout(Duration.ofSeconds(20))
        .proxy(ProxySelector.of(new InetSocketAddress("proxy.example.com", 80)))
        .authenticator(Authenticator.getDefault())
        .build();
   HttpResponse<String> response = client.send(request, BodyHandlers.ofString());
   System.out.println(response.statusCode());
   System.out.println(response.body());  
```
(I don't mean all of it, but the essential parts at least-- like just getting e.g. flix.dev over https).

**Comment by magnus-madsen** [comment]
@JonathanStarup Could you take a look?

**Comment by JonathanStarup** [comment]
I think this would work fine. There are static methods, instance methods, static fields, and constructors. i assume `request` is nothing fancy but it looks doable. The builder sequence probably looks quite nice if the java imports are subject last

**Comment by magnus-madsen** [comment]
OK; If it looks feasible Ill ask one of the student programmers to look into it (eventually).

**Comment by magnus-madsen** [comment]
@ninaandrup I don't know if we support enough of Java to wrap HttpClient, but could you take a look and maybe make a first draft for some kind of API? Thanks!

**Comment by magnus-madsen** [comment]
Its possibly you get stuck, then just let me know :) See e.g. https://github.com/flix/flix/issues/2546

**Comment by ninaandrup** [comment]
I'm a bit unsure of how it is possible to do [`HttpClient.newBuilder()`, since this returns a `HttpClient.Builder`](https://docs.oracle.com/en/java/javase/12/docs/api/java.net.http/java/net/http/HttpClient.html#newBuilder()), which is an interface and not a class. I cannot seem to find any implementation of the interface.

**Comment by ninaandrup** [comment]
> I'm a bit unsure of how it is possible to do [`HttpClient.newBuilder()`, since this returns a `HttpClient.Builder`](https://docs.oracle.com/en/java/javase/12/docs/api/java.net.http/java/net/http/HttpClient.html#newBuilder()), which is an interface and not a class. I cannot seem to find any implementation of the interface.

I should look at https://github.com/flix/flix/issues/2546, right?

**Comment by JonathanStarup** [comment]
```
def main(_args: Array[String]): Int32 & Impure =
    import static java.net.http.HttpClient.newBuilder(): ##java.lang.Object & Impure;
    import java.lang.Object.toString(): String & Impure;
    let _ = newBuilder() |> toString |> println;
    0
```

**Comment by JonathanStarup** [comment]
ah yes, `##java.net.http.HttpClient$Builder` works

**Comment by mlutze** [comment]
Since this will be wrapping a lot of Java stuff, you might find this tool useful: https://github.com/mlutze/fcwg

**Comment by magnus-madsen** [comment]
I suggest someone explores this in a separate library first.
