### ISSUE TITLE
Resolved operator loses the symbol text

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2550]
![image](https://user-images.githubusercontent.com/2287953/139596441-2d45f070-0175-4d85-b2c7-73a85eebfd5b.png)

The problem here is that `+` is replaced by `Add.add` (which is good), but now the AST is `add` which is not an operator.

**Comment by magnus-madsen** [comment]
@mlutze Thoughts on how to fix this? (Other than renaming `Add.add` to `Add.+`?).

I think we should care.

**Comment by mlutze** [comment]
Is it too naive just to add a bit to `Expression.Def` saying whether it's an op or not?

**Comment by magnus-madsen** [comment]
> 
> 
> Is it too naive just to add a bit to `Expression.Def` saying whether it's an op or not?

Hmm. I don't know. Every solution I can think of feels like a hack.

**Comment by mlutze** [comment]
What is the advantage of having a separate "operator" token?

**Comment by magnus-madsen** [comment]
and should operators even be colored differently?

**Comment by magnus-madsen** [comment]
Its a feature not a bug; after all `+` is a function.
