### ISSUE TITLE
Record types source locations off-by-one

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2551]
![image](https://user-images.githubusercontent.com/2287953/139596568-dc2fa1dc-9177-4bcb-b041-9bc304fbaa9b.png)

**Comment by mlutze** [comment]
When I hover the un-highlighted `}`, I still get a type popping up. So the LSP must know that the type is located there, right?

**Comment by magnus-madsen** [comment]
But what is happening then? :)

**Comment by magnus-madsen** [comment]
![image](https://user-images.githubusercontent.com/2287953/139634573-1386471a-92e8-40f9-8400-6d54c44e17d5.png)

Not related to records?

**Comment by mlutze** [comment]
VSCode debugger says that it should be colored:

![Screenshot from 2021-11-01 11-36-52](https://user-images.githubusercontent.com/19153692/139659148-b8bea05f-39f8-4fc3-b162-d4555ea6a1e9.png)

Is it possible that something else in VSCode is taking precedence?

**Comment by magnus-madsen** [comment]
I see the same, but I don't understand whats the problem.

Its probably not a bug in VSCode, right? Too many people would have found it.

**Comment by jhckragh** [comment]
The output from the Flix language server looks good. A semantic token request for the following code:

```flix
pub def setX(r: {x :: Int, y :: Int}, v: Int): {x :: Int, y :: Int} =
    { x = v | r }
```

yields the following response:

```json
{"id": "3", "status": "success", "result": {"data": [0, 8, 4, 3, 0, 0, 5, 1, 6, 0, 0, 3, 20, 10, 0, 0, 1, 8, 10, 0, 0, 5, 3, 10, 0, 0, 5, 8, 10, 0, 0, 5, 3, 10, 0, 0, 6, 1, 6, 0, 0, 3, 3, 10, 0, 0, 6, 20, 10, 0, 0, 1, 8, 10, 0, 0, 5, 3, 10, 0, 0, 5, 8, 10, 0, 0, 5, 3, 10, 0, 1, 6, 1, 7, 0, 0, 4, 1, 6, 0, 0, 4, 1, 6, 0]}}
```

which translates to:

```
[LINE:COL] 'TEXT' (TYPE)
------------------------
[0:8] 'setX' (FUNCTION)
[0:13] 'r' (PARAMETER)
[0:16] '{x :: Int, y :: Int}' (TYPE)
[0:17] 'x :: Int' (TYPE)
[0:22] 'Int' (TYPE)
[0:27] 'y :: Int' (TYPE)
[0:32] 'Int' (TYPE)
[0:38] 'v' (PARAMETER)
[0:41] 'Int' (TYPE)
[0:47] '{x :: Int, y :: Int}' (TYPE)
[0:48] 'x :: Int' (TYPE)
[0:53] 'Int' (TYPE)
[0:58] 'y :: Int' (TYPE)
[0:63] 'Int' (TYPE)
[1:6] 'x' (PROPERTY)
[1:10] 'v' (PARAMETER)
[1:14] 'r' (PARAMETER)
```

This seems fine. BUT note that some of the tokens are overlapping! This doesn't seem to be supported by VS Code currently. A quick search leads to https://github.com/microsoft/language-server-protocol/issues/1077#issuecomment-685832959. That comment is about a year old, so maybe things have changed. What we're seeing here suggests that it's still not supported by VS Code. More discussion can be found here: https://github.com/microsoft/vscode/issues/86415#issuecomment-587327402

**Comment by magnus-madsen** [comment]
How do you see that the tokens are overlapping? I don't understand how you can tell that from the numbers.

**Comment by jhckragh** [comment]
It's obscured a bit by the way I've listed the tokens—sorry about that! But it can be seen by keeping the *length* of each token in mind. For example, consider these tokens:

```
[0:16] '{x :: Int, y :: Int}' (TYPE)
[0:17] 'x :: Int' (TYPE)
[0:22] 'Int' (TYPE)
```

The first token starts in column 16 and has a length of 20; so it spans until column 35. The next token starts and ends within this span. And so on. So the tokens overlap each other. 🙂

Here's a kind of visualization, where the tokens below lie on top of the tokens above:

```
{x :: Int, y :: Int}
 ^^^^^^^^
 x :: Int
      ^^^
      Int
```

**Comment by magnus-madsen** [comment]
Thanks- useful! @mlutze I think we need to consider NOT printing some of the type source locs?

**Comment by mlutze** [comment]
> Thanks- useful! @mlutze I think we need to consider NOT printing some of the type source locs?

Yes. Maybe we should start with just doing the enums and primitives? So in general we can hover the words but not the symbols.

**Comment by magnus-madsen** [comment]
> 
> 
> > Thanks- useful! @mlutze I think we need to consider NOT printing some of the type source locs?
> 
> Yes. Maybe we should start with just doing the enums and primitives? So in general we can hover the words but not the symbols.

I think that would also look nicer.
