### ISSUE TITLE
Set and map literals have imprecise source locations

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2553]
![image](https://user-images.githubusercontent.com/2287953/139596759-afbb4892-0bee-4569-8eb8-c83630eb9251.png)

Not sure exactly how to fix.

**Comment by magnus-madsen** [comment]
The reason everything is green is because it is translated into `Map.insert` and `Map.empty`.

**Comment by magnus-madsen** [comment]
@mlutze Thoughts on how to fix?

**Comment by mlutze** [comment]
For the color issue, my immediate thought is to have a field saying that this came from syntactic sugar.

For the location, this seems like it may be an easy fix in weeder, no?

**Comment by magnus-madsen** [comment]
What if we use just the `Map#` and `Set#` part for the location of the rewrites? I guess it could be confusing if there is an error with the insert?
