### ISSUE TITLE
rel/lat declarations are treated as types

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2554]
![image](https://user-images.githubusercontent.com/2287953/139596809-115418ec-da2e-4518-8ee5-0ad4f2602123.png)

**Comment by magnus-madsen** [comment]
I am guessing the entirely of the rel declaration ends up in the type somehow.

**Comment by mlutze** [comment]
This is fixed as a side-effect of https://github.com/flix/flix/pull/2560

**Comment by magnus-madsen** [comment]
Not completely slowed:

![image](https://user-images.githubusercontent.com/2287953/139672743-b7fc1bd0-3813-4ef0-a881-5e61250da3eb.png)

**Comment by magnus-madsen** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/2287953/139701053-22edd8f9-3e3c-468b-a482-c3dae6489a42.png)
