### ISSUE TITLE
Redundant `map2`

### ISSUE THREAD

**Issue by felixwiemuth** [flix/flix#2562]
In multiple datatypes `m` we have a function `map2(f: (a, b) -> c & ef, a: m[a], b: m[b]): m[c] & ef`, with different meaning:

- In `List`, `Array`, `String` it is the same as `zipWith`
- In `Option` it is the same as `lift2`/`liftA2`

I think the name can be a bit confusing, as the relation to `Functor.map` is not entirely obvious, especially regarding the different meanings in the examples above.

Maybe it is best to drop the redundant `map2` definitions and use the more standard names `zipWith` and `lift2` (which are already there).

For `Option` one would maybe rather use applicative style anyway: `f <$> o1 <*> o2` (in Haskell notation) which is equivalent to `lift2(f, o1, o2)`.

**Comment by magnus-madsen** [comment]
Good point. I am leaning towards dropping `map2`.

**Comment by magnus-madsen** [comment]
Does `f <$> o1 <*> o2` parse correctly in Flix today?

**Comment by felixwiemuth** [comment]
> Does `f <$> o1 <*> o2` parse correctly in Flix today?

No, that is Haskell syntax. I don't think we have symbolic operators for `map` and `ap` yet?

**Comment by magnus-madsen** [comment]
@stephentetley Do you concur that we should drop the map2 functions?

**Comment by stephentetley** [comment]
I would agree with dropping them.

**Comment by magnus-madsen** [comment]
- [ ] Delete `String.map2` (and tests)
- [ ] Delete `Array.map2` (and tests)
- [ ] Delete `Array.flatMap2` (and tests)
- [ ] Delete `List.map2` (and tests)
- [ ] Delete `List.flatMap2` (and tests)
- [ ] Delete `Option.map2` (and tests)
- [ ] Delete `Option.flatMap2` (and tests)

**Comment by felixwiemuth** [comment]
See notes on [`flatMapX`](https://github.com/flix/flix/issues/1648#issuecomment-956172368) in the Monad dicussion why we might want to have `flatMap2`.

**Comment by magnus-madsen** [comment]
We will go with removal for now. We can always add back if there is a need.
