### ISSUE TITLE
`List.splitAt`

### ISSUE THREAD

**Issue by mlutze** [flix/flix#2573]

**Comment by esbenbjerre** [comment]
`def splitAt(n: Int32, xs: List[a]): (List[a], List[a]) = (List.take(n, xs), List.drop(n, xs))` maybe?

**Comment by mlutze** [comment]
Yes :) I was thinking that it was wasteful to traverse twice. But maybe it doesn't make too much of a difference.

**Comment by esbenbjerre** [comment]
> Yes :) I was thinking that it was wasteful to traverse twice. But maybe it doesn't make too much of a difference.

Good point, but if we do this:
```
def splitAtHelper(k: Int32, acc: List[a], xs: List[a]): (List[a], List[a]) =
    match xs {
        case y :: ys if k > 0 => splitAtHelper(k - 1, y :: acc, ys)
        case _ => (acc, xs)
    }

def splitAt(n: Int32, xs: List[a]): (List[a], List[a]) =
    splitAtHelper(n, Nil, xs)

def main(_args: Array[String]): Int32 & Impure = 
    splitAt(2, 1 :: 2 :: 3 :: 4 :: Nil) |> println; // prints (2 :: 1 :: Nil, 3 :: 4 :: Nil)
    0
```
We would need to reverse `acc`. In this case I think the time complexity stays the same.

**Comment by magnus-madsen** [comment]
Seems straightforward.
