### ISSUE TITLE
[Parser] Comments and WhiteSpace

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#258]
```
///
/// Foo
/// fsefa
rel R(x: Int)

/// This is A
///
rel A(x: Int)

//fs asd fas

/* fsd fasd */

///
/// This is B
///
rel B(x: Int)

///
/// This is C
///
rel C(x: Int)
```

**Comment by magnus-madsen** [comment]
This also affects classes, enums, etc.

**Comment by magnus-madsen** [comment]
@JonathanStarup @mlutze Would either of you be interested in debugging this? 

I would like it fixed so I can work on api.flix.dev :)

**Comment by magnus-madsen** [comment]
It should work for:

- classes
- enums
- type aliases
- defs

I think it works for defs, but for the rest we just get empty comment strings even though they are there.

**Comment by JonathanStarup** [comment]
I think the problem is parser line 1718 where the definition of single line comments (used by optWs) includes `/// asdfasdf`
```scala
def SingleLineComment: Rule0 = rule {
      "//" ~ zeroOrMore(!NewLine ~ ANY) ~ (NewLine | EOI)
    }
```

**Comment by JonathanStarup** [comment]
Also because of optWs in the documentation parsing and the choice in pureWS
```scala
def Documentation: Rule1[ParsedAst.Doc] = {
    // Matches real whitespace.
    def PureWS: Rule0 = rule {
      quiet(zeroOrMore(" " | "\t" | NewLine))
    }

    // Matches triple dashed comments.
    def TripleSlash: Rule1[Seq[String]] = rule {
      oneOrMore(PureWS ~ atomic("///") ~ (capture(zeroOrMore(!NewLine ~ ANY)) ~ (NewLine | EOI)))
    }

    // Optionally matches a triple dashed comment and then any whitespace.
    rule {
      SP ~ optional(TripleSlash) ~ SP ~ optWS ~> (
        (sp1: SourcePosition, o: Option[Seq[String]], sp2: SourcePosition) => o match {
          case None => ParsedAst.Doc(sp1, Seq.empty, sp2)
          case Some(lines) => ParsedAst.Doc(sp1, lines, sp2)
        })
    }
  }
```
you can write documentation like this?
```flix
/// This

/// Is documentation

/// for `f`
// these are just comments after the docs

// because there is optWS

def f(): unit = ()
```

**Comment by magnus-madsen** [comment]
I think we should only capture triple comments `///` that appear right before one of the four constructs.

**Comment by JonathanStarup** [comment]
I feel like it would be sensible to disallow `///` is its not a doc comment. If I write
```
/// documentation ...
// comment
def f(): Unit = ()
```
I cant really observe what happened. Does f have a documentation comment or not? I think strictness here would give the clarity that if it compiles then you did it correctly.
