### ISSUE TITLE
Improving declaration locations

### ISSUE THREAD

**Issue by mlutze** [flix/flix#2584]
In the Weeder, we throw away the full locations of the declarations and replace them with the symbol locations.
This is bad because:
1. It's redundant because we always have the symbol and its location on hand anyway.
2. We lose the location of the entire def, which would be useful for some LSP stuff

In order to fix this safely (i.e. without breaking things that depend on current locations), we follow these steps:
1. Remove the `loc` field from the declaration in all the `*Ast`.
2. Repair everything that breaks as a result of this, by replacing `loc` with `sym.loc`
3. Add back the `loc` field, this time using the location of the entire declaration.

This must be done for:
- [x] Defs
- [x] Sigs
- [x] Laws
- [x] Classes
- [x] Instances
- [x] Enums
- [x] Type Aliases
- [x] Opaque Types
- [x] Namespaces

**Comment by mlutze** [comment]
I guess namespaces don't make it past the Namer

**Comment by magnus-madsen** [comment]
> 
> 
> I guess namespaces don't make it past the Namer

True. At least not yet.

**Comment by magnus-madsen** [comment]
Fixed?

**Comment by mlutze** [comment]
Fixed!
