### ISSUE TITLE
Multi-parameter type classes

### ISSUE THREAD

**Issue by mlutze** [flix/flix#2587]
This was previously visited in another ticket, but that one was closed.

I'm interested in this feature primarily for better incorporating effects into classes.

### Problem
Currently we do casting to make mutable types conform to the signatures of type classes. For example:

```scala
instance Eq[MutList[a]] with Eq[a] {
        pub def eq(xs: MutList[a], ys: MutList[a]): Bool = {
           ... compare the lists ...
        } as & Pure
}
```

This is necessary because `Eq.eq` has the type signature `(a, a) -> Bool & Pure`.
It means that we are lying about effects when we do `mutList1 == mutList2`.

### Proposed Solution
With multi-parameter type classes, this is no longer necessary:

```scala
class Eq[ef, a] {
  pub def eq(x: a, y: a): Bool & ef
}
```

```scala
instance Eq[MutList[a]] with Eq[a] {
        pub def eq(xs: MutList[a], ys: MutList[a]): Bool & ef = {
           ... compare the lists ...
        } // no cast!
}
```

### Challenges

Multi-parameter type classes can complicate many things:
1. Overlapping instances
2. Resolution of instances
3. Idea of complex instances
4. Probably other things

I think these complications can mostly be addressed by requiring a functional dependency on the parameters. Specifically, all parameters should be uniquely determined by the final (subject) parameter. This way, overlapping instances, resolution of instances, and the idea of complex instances remains the same; we ignore the non-subject parameters for these purposes.

### Bonus

Multi-parameter type classes can also be used for other things:

```scala
class Collection[a, c] {
    pub def toList(x: c): List[a]
}

instance Collection[Char, String] {
    pub def toList(x: String): List[Char] = String.toList(x)
}
```

The functional dependency restriction would limit the scope of other applications.

**Comment by magnus-madsen** [comment]
Quick Q: Why should equality be allowed to have side-effects? That would break most reasoning you could otherwise do.

**Comment by mlutze** [comment]
I think it's important to have a notion of ("instantaneous") equality on mutable values. But maybe this is not the solution.

Still, the feature would still apply to e.g. `ToString`

**Comment by magnus-madsen** [comment]
If we have ownership (or similar) or some notion of `frozen` then it would still be possible to have equality on mutable data types. Nevertheless, I question it: It is very dangerous to have e.g. a `Set[Ref[Int32]]`. Its easy to see that mutation can break the set-ness of the set. 

Separately, MPTC come with a lot of challenges. Probably they are not useful unless you add functional dependencies on top. But I am not convinced this is the direction to go. There are other directions for more modularity, including algebraic effects, macros, and other forms of compile-time evaluation. TLDR: I have never been convinced of MPTCs.

**Comment by JonathanStarup** [comment]
What is the correct way to define comparisons on mutable structures right now? Do it without using Eq?

**Comment by magnus-madsen** [comment]
> What is the correct way to define comparisons on mutable structures right now? Do it without using Eq?

It is an open question: Options are:

- Implement eq and cast to pure. (This is not correct).
- Change Eq to mark it as impure.
- Change Eq to allow impurity based on some extra type param (what Matt is exploring, but I am hesitant about).
- Not allowed (could make sense). 
- ??? some other mechanism that makes it safe.

**Comment by magnus-madsen** [comment]
Do we have a valid use case? 

Here is a really bad use case:

```
let x = ref 0;
let y = ref 1;
let s = Set#{x, y};
x : = 1
```

**Comment by mlutze** [comment]
Here's another fun (though perhaps not convincing) application:

```scala
class Int32able[canFail, a] {
    pub def toInt32(x: a): Choose[a, true, canFail]
}

instance Int32able[false, Int16] {
    pub def toInt32(x: Int16): Choose[Int16, true, false] = Present(Int32.toInt16(x))
}

instance Int32able[true, Int64] {
    pub def toInt32(x: Int64): Choose[Int64, true, true] = match Int64.toInt32 {
        case None => Absent
        case Some(y) => Present(y)
    }
}
```

**Comment by JonathanStarup** [comment]
If you do some fixpoint computation with mutable structures and check for progress naively `if (old == new) stop else continue` then you need an equality check

**Comment by magnus-madsen** [comment]
> If you do some fixpoint computation with mutable structures and check for progress naively `if (old == new) stop else continue` then you need an equality check

Indeed. Two solutions come to mind: We need to return a frozen array and/or we can still provide a `sameElements` or similar function.

**Comment by magnus-madsen** [comment]
> 
> 
> Here's another fun (though perhaps not convincing) application:
> 
> ```scala
> class Int32able[canFail, a] {
>     pub def toInt32(x: a): Choose[a, true, canFail]
> }
> 
> instance Int32able[false, Int16] {
>     pub def toInt32(x: Int16): Choose[Int16, true, false] = Present(Int32.toInt16(x))
> }
> 
> instance Int32able[true, Int64] {
>     pub def toInt32(x: Int64): Choose[Int64, true, true] = match Int64.toInt32 {
>         case None => Absent
>         case Some(y) => Present(y)
>     }
> }
> ```

Maybe for a research paper, but for real-world use I don't believe it. You would rather have two TCs then: One that is failable and one that is not.

**Comment by magnus-madsen** [comment]
I feel like this ticket has convinced me that we should drop most TC instances (especially equality) for mutable data.

**Comment by stephentetley** [comment]
A monad transformer library like Iavor Diatchki's MonadLib or Haskell's "standard" MTL would need multi-param type classes. Such a library would be quite a compelling use-case.

https://hackage.haskell.org/package/monadLib

**Comment by magnus-madsen** [comment]
I would like to propose that we add a few other features before we consider MPTC. In particular, I'd like to see the complex instance restriction lifted and to explore algebraic data types in more detail.

**Comment by magnus-madsen** [comment]
We may add this some day, but in the short-run I am not convinced of the use cases. (Of course I understand that there are use cases and what they are; but I am not sure they warrant this feature). In particular, I want to see how the algebraic effect story plays out before considering this.
