### ISSUE TITLE
Retire `Int`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2588]
The word `Int` is an alias for `Int32` as seen here:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Resolver.scala#L1470

We want to:

- [ ] Remove `Int` as an alias for `Int32` (i.e. remove the above line).
- [ ] Refactor everywhere in the standard library where `Int` is used to use `Int32` instead.

This will probably involve many changes, so it maybe worth breaking the PR into smaller pieces.

**Comment by magnus-madsen** [comment]
@ninaandrup Ill assign this to you, but it has very low priority for now.

**Comment by magnus-madsen** [comment]
@ninaandrup Any idea on how many percent done?

**Comment by ninaandrup** [comment]
> @ninaandrup Any idea on how many percent done?

All the Library tests pass now. But I do not know how many percentage done.

**Comment by magnus-madsen** [comment]
Will you let me know when done and when we should remove `Int` from the compiler?

**Comment by ninaandrup** [comment]
> Will you let me know when done and when we should remove `Int` from the compiler?

Yes, I'll do that :-)

**Comment by magnus-madsen** [comment]
Fixed in master.
