### ISSUE TITLE
New Backend

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#2591]
## Rewriting the backend to use a frame transformer DSL
* [x] Make ErasedAst be a copy of FinalAst
* [x] Make the eraser transform FinalAst to ErasedAst but return FinalAst
* [x] Change JvmBackend to use ErasedAst
* [ ] Add explicit cast expressions and introduce them as needed in the eraser
* [x] Add instruction transformations
* [ ] Change the (internal) compilation method to return a frame transformer
* [ ] Collect jvm type information in `BackendObjType` objects. This will reduce the `GenXYZClass` work to calling `BackendObjXYZ.generateBytecode(...)`
    * [x] Fields #3932
    * Methods/constructors/genByteCode methods
        * [x] #4001
        * [x] #4015
        * [x] #4016
        * [x] #4019
        * [x] #4072
        * [x] #4094
        * [x] #4098
* [ ] Rewrite cases one by one 
* [ ] Rewrite gen classes
  * [x] #2604
  * [x] #2612
  * [x] #2637
  * [x] #2639
  * [x] #2660
  * [x] #2698
  * [x] #2721
  * [x] #2782
  * [x] #2797
  * [x] #2845
  * [x] #2891
  * [x] #2898
  * [x] #3884
  * [ ] Function classes
  * [ ] Closures
  * [ ] Lazy
  * [x] ...
  * [ ] Enum Interfaces
  * [ ] Main
  * [ ] namespaces?
  * [ ] tags
  * [ ] tuples
  * [ ] tuple interfaces
  * [ ] Make documentation, naming, and format consistent

## Adding type safety
* [ ] Add PType/RType to model the jvm types
* [ ] Add type index to erased expressions
* [ ] Add types for dsl instructions and cases (this probably has to be done in one go)

## Additional Issues:
* [ ] Maximal parallelism #3531
* [ ] Type string generation and memoization (store strings in the type values?)
* [x] #2417
* [x] #2715 
* [ ] #2359
* [ ] Support of nested array types (#3332)
* [ ] Type set collection in the eraser to avoid multiple AST passes (collection of things like the set of all types)

But I think these are separate and muddled the previous attempt

**Comment by magnus-madsen** [comment]
We can start building the DSL based on the `GenUnit` and similar simple classes and then go from there.

**Comment by magnus-madsen** [comment]
Use DSL in:

- [ ] `GenUnit`
- [ ] `GenGlobalCounterClass`
- [ ] `GenMatchErrorClass`
- [ ] `GenRefClasses`
- [ ] `GenRecordEmpty`
- [ ] `GenRecordExtend`
- [ ] ...

Trying to go from easy to harder.

**Comment by JonathanStarup** [comment]
@magnus-madsen Should I run phase benchmarks during this process to monitor the performance effect or is arewefast sufficient?

**Comment by magnus-madsen** [comment]
> 
> 
> @magnus-madsen Should I run phase benchmarks during this process to monitor the performance effect or is arewefast sufficient?

We can do a bit of both. Changing GenUnit will not affect performance. We know that. Changing GenExp is of course different.

**Comment by magnus-madsen** [comment]
@JonathanStarup Is this ticket still useful?

**Comment by JonathanStarup** [comment]
I think not
