### ISSUE TITLE
Debate: Sugar for let-bound lambdas?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2597]
We can currently write:

```scala
def filterMap(f: a -> Option[b] & ef, xs: Chain[a]): Chain[b] & ef =
    let step = (ac, x) -> match f(x) {
        case None    => ac
        case Some(v) => snoc(ac, v)
    };
    foldLeft(step, empty(), xs)
```

but what if we could write:

```scala
def filterMap(f: a -> Option[b] & ef, xs: Chain[a]): Chain[b] & ef =
    let step(acc, x) = match f(x) {
        case None    => ac
        case Some(v) => snoc(ac, v)
    };
    foldLeft(step, empty(), xs)
```

and:

```scala
def filterMap(f: a -> Option[b] & ef, xs: Chain[a]): Chain[b] & ef =
    let step(acc: Chain[b], x: a): Chain[b] & ef = match f(x) {
        case None    => ac
        case Some(v) => snoc(ac, v)
    };
    foldLeft(step, empty(), xs)
```

Note: I am not reusing the def syntax here.

**Comment by JonathanStarup** [comment]
Maybe this is confusing with the let match syntax? maybe lambda could be a keyword instead of let here?

**Comment by magnus-madsen** [comment]
> Maybe this is confusing with the let match syntax? maybe lambda could be a keyword instead of let here?

Can you give an example? (Btw the syntax is borrowed from OCaml)

**Comment by JonathanStarup** [comment]
Like here in channel
```
pub def put(e: Boxed, c: Mpmc): Mpmc & Impure =
        let Mpmc(_, channelLock, unBuffered, _, elementDeque, _, waitingPutters) = c;
        lock(channelLock);
```
The difference is just casing right? `let mpmc(...) = ...` would be a function?

**Comment by magnus-madsen** [comment]
> Like here in channel
> 
> ```
> pub def put(e: Boxed, c: Mpmc): Mpmc & Impure =
>         let Mpmc(_, channelLock, unBuffered, _, elementDeque, _, waitingPutters) = c;
>         lock(channelLock);
> ```
> 
> The difference is just casing right? `let mpmc(...) = ...` would be a function? Channel is maybe not a good example since it would've been a record if not for efficiency. but its a possible confusion when using opaque types.

OK, I understand the point now.

**Comment by magnus-madsen** [comment]
We could go for: 
```scala
def filterMap(f: a -> Option[b] & ef, xs: Chain[a]): Chain[b] & ef =
    def step(acc, x) = match f(x) {
        case None    => ac
        case Some(v) => snoc(ac, v)
    };
    foldLeft(step, empty(), xs)

def filterMap(f: a -> Option[b] & ef, xs: Chain[a]): Chain[b] & ef =
    def step(acc: Chain[b], x: a): Chain[b] & ef = match f(x) {
        case None    => ac
        case Some(v) => snoc(ac, v)
    };
    foldLeft(step, empty(), xs)
```

**Comment by magnus-madsen** [comment]
> 
> 
> Like here in channel
> 
> ```
> pub def put(e: Boxed, c: Mpmc): Mpmc & Impure =
>         let Mpmc(_, channelLock, unBuffered, _, elementDeque, _, waitingPutters) = c;
>         lock(channelLock);
> ```
> 
> The difference is just casing right? `let mpmc(...) = ...` would be a function? Channel is maybe not a good example since it would've been a record if not for efficiency. but its a possible confusion when using opaque types.

I see two solution:

- We do not consider it a problem (because casing resolves ambiguity)
- We can drop support for let-match and force the programmer to use pattern matching. (This may or may not have other benefits).

**Comment by JonathanStarup** [comment]
> We do not consider it a problem (because casing resolves ambiguity)

I think the errors will also be good for guidance here since the two behave so differently so any confusion should be resolved quickly

**Comment by mlutze** [comment]
> We could go for:
> 
> ```scala
> def filterMap(f: a -> Option[b] & ef, xs: Chain[a]): Chain[b] & ef =
>     def step(acc, x) = match f(x) {
>         case None    => ac
>         case Some(v) => snoc(ac, v)
>     };
>     foldLeft(step, empty(), xs)
> 
> def filterMap(f: a -> Option[b] & ef, xs: Chain[a]): Chain[b] & ef =
>     def step(acc: Chain[b], x: a): Chain[b] & ef = match f(x) {
>         case None    => ac
>         case Some(v) => snoc(ac, v)
>     };
>     foldLeft(step, empty(), xs)
> ```

I like this syntax

**Comment by magnus-madsen** [comment]
We also need to deal with letrec and decide whether it would correspond to a letrec.

**Comment by JonathanStarup** [comment]
What is letrec?

**Comment by magnus-madsen** [comment]
> What is letrec?

A let rec is a recursive binding where the variable name is visible inside its definition.

For example:

```
let f = x -> f(x) // undefined variable x.
let  rec f = x -> f(x) // f is visible in its definition.
```

**Comment by magnus-madsen** [comment]
We need to both frontend and backend extensions to support let-rec.

**Comment by JonathanStarup** [comment]
Yea okay, I though it was implemented already and I couldn't find it. I think the nested def corresponding to let rec would be nice and feels expected. It is the same way in python

**Comment by magnus-madsen** [comment]
A possible idea is to allow both forms. The let would then be non-generalizing whereas the def would generalize.

**Comment by magnus-madsen** [comment]
Fixed in master.
