### ISSUE TITLE
Remove Attribute from AST

### ISSUE THREAD

**Issue by mlutze** [flix/flix#2622]
Relations and lattices are desugared into type aliases in the Weeder, and attributes are turned into types. But we still have a lot of things related to attributes throughout the front end of the compiler. Is there any good reason to keep these around?

**Comment by magnus-madsen** [comment]
Here is a different question. Could we use the current type alias mechanism for things of Kind.Relation and Kind.Lattice?

**Comment by magnus-madsen** [comment]
As a general comment: We are slightly moving away from removing things from the AST because it prevents us from having good IDE support. E.g. with `use` its a mistake that they are removed because we cannot report errors accurately nor give proper LSP highlighting/jump to definition etc. etc.

**Comment by mlutze** [comment]
> Here is a different question. Could we use the current type alias mechanism for things of Kind.Relation and Kind.Lattice?

Can you be more specific? In general, type aliases can be of any kind:

```scala
type alias NotFalse = Pure // Bool
type alias IntMap = Map[Int] // Type -> Type
```

The limitations are mostly syntactic, I think: we can't currently express a relation or lattice alone on the RHS.

**Comment by magnus-madsen** [comment]
Can we do:

https://github.com/flix/flix/blob/master/examples/analysis/IDE.flix#L103

as regular type aliases?

**Comment by magnus-madsen** [comment]
If something like this:

```scala
rel Person(fstName: String, lstName: String)
pub def foo(): #{ Person } = #{ Person("M", "M"). }

// type alias Person = Person(/*fstName*/ String, /*lstName*/ String)
// pub def bar(): #{ Person } = #{ Person("M", "M"). }
```
worked.

then we could entirely get rid of these silly declarations.

**Comment by mlutze** [comment]
I think it would be a fairly straightforward Parser/Weeder change

**Comment by magnus-madsen** [comment]
> I think it would be a fairly straightforward Parser/Weeder change

If it can be done, then I am happy to completely get rid of the `rel/lat` declarations. 

Do you think the syntax `type alias F = Person(String, String)` is course for concern?

**Comment by mlutze** [comment]
I don't think it's ambiguous, but it may be nontrivial to parse it without backtracking.

**Comment by magnus-madsen** [comment]
> I don't think it's ambiguous, but it may be nontrivial to parse it without backtracking.

If you want to try it out and it works, I would be happy to completely replace `rel/lat` with type aliases.

**Comment by mlutze** [comment]
I just started to explore this. A problem I've hit is that the Relation type doesn't actually carry the name of the relation.

**Comment by magnus-madsen** [comment]
We could just remove the feature? Or no?

**Comment by mlutze** [comment]
> We could just remove the feature? Or no?

Which feature exactly?

**Comment by magnus-madsen** [comment]
The ability to declare `rel` and `lat`.

**Comment by magnus-madsen** [comment]
@stephentetley Do you use to ability to declare `rel` and `lat`?

Would you miss them if we removed them *before* having some new solution in place based on type aliases?

**Comment by stephentetley** [comment]
Yes I almost always declare `rel` and `lat` rather than use them implicitly, but I can keep my projects that use Datalog pinned to a previous version of the compiler until there is a new solution.

**Comment by magnus-madsen** [comment]
> Yes I almost always declare `rel` and `lat` rather than use them implicitly, but I can keep my projects that use Datalog pinned to a previous version of the compiler until there is a new solution.

OK. No, in that case we keep the feature until a replacement is ready :)

**Comment by magnus-madsen** [comment]
(We are just trying to express this feature as a special case of type alias).

**Comment by magnus-madsen** [comment]
@stephentetley If we get rid of `rel/lat` I think you can just:

```
type alias P[r: SchemaRow] = #{ A(Int32) | r }

def foo(): P[#(B(Int32))] = #{ B(123). }
```

**Comment by magnus-madsen** [comment]
I guess it does not exactly achieve the same thing.

**Comment by magnus-madsen** [comment]
Tracked in #5769.
