### ISSUE TITLE
Towards incremental compilation (in the frontend)

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2628]
Idea: Every phase currently looks something like:

```
def run(root: KindedAst.Root)(implicit flix: Flix): Validation[TypedAst.Root, CompilationMessage]
```

We change this to something like:

```
def run(root: KindedAst.Root, oldRoot: TypedAst.Root, changed: List[File])(implicit flix: Flix): Validation[TypedAst.Root, CompilationMessage]
```

Inside the phase, we now recompute the new AST from the `root` and `oldRoot`. For example, we can compute the result as the fusion of `oldRoot` + the new stuff from `root` that is in `changed`.

EDIT: I think we should only try to do this until the Typer. To speedup the VSCode integration. Later we can think about extending it.

**Comment by magnus-madsen** [comment]
Front-end phases:

```
Deriver                          0,7 ms (00,0%)
Reader                           0,9 ms (00,0%)
Instances                        2,0 ms (00,1%)
Terminator                       3,8 ms (00,1%)
Safety                           4,0 ms (00,1%)
Stratifier                      11,0 ms (00,4%)
Kinder                          18,0 ms (00,6%)
PatternExhaustiveness           21,7 ms (00,8%)
Weeder                          36,6 ms (01,3%)
Namer                           46,2 ms (01,6%)
Redundancy                      53,0 ms (01,9%)
Parser                         110,8 ms (03,9%)
Resolver                       120,1 ms (04,3%)
Typer                          740,1 ms (26,3%)
```

**Comment by magnus-madsen** [comment]
@mlutze What if we start by trying to make the Typer incremental?

In `run` what happens if we are given the new KindedAst and the old TypedAst. 

We recheck everything in the new KindedAst (but only if it comes from the change source location).

Will that work and be correct?

**Comment by mlutze** [comment]
I don't immediately see any issues with it; and it seems fairly straightforward to implement.

**Comment by magnus-madsen** [comment]
Tracking issue #2970
