### ISSUE TITLE
Redundancy bug with nested let match

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#2631]
This program has an wrong error that `CustomString` is never used
```
opaque type CustomString = String
opaque type Wrap = CustomString

pub def f(w: Wrap): Unit =
    let Wrap(CustomString(_s)) = w;
    ()
```

**Comment by magnus-madsen** [comment]
Depends. No value of CustomString is ever created. Hence all your code is dead. In particular there is no value of type `Wrap`.

**Comment by magnus-madsen** [comment]
We have discussed whether this is overly harsh.

**Comment by JonathanStarup** [comment]
Because the types aren't public? so `f` is just unusable from the outside?

**Comment by magnus-madsen** [comment]
Well, the program never constructs a value of type `CustomString` so its not used. You cant even call `f`, right?

**Comment by JonathanStarup** [comment]
no that's true. I assumed they were implicitly public since I was allowed to write `Wrap` in the argument
