### ISSUE TITLE
Query and solve not highlighted as keyword

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#2632]
0.25.0 on vscode

![image](https://user-images.githubusercontent.com/32037926/141696325-da3d33ac-29da-4040-b93f-e04331862344.png)

Also wrong independently
```
pub def f(): Array[Unit]  =
    let s = solve ???;
    query s select () from P()
```

**Comment by magnus-madsen** [comment]
Probably related to the source locations used here:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Weeder.scala#L1417
