### ISSUE TITLE
Add code size reporting to https://arewefast.flix.dev/

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2633]
It would be nice to have a graph that prints the code size over time.

@JonathanStarup Let us discuss.

**Comment by JonathanStarup** [comment]
You mean the generated code?

**Comment by magnus-madsen** [comment]
Yes, in bytes

**Comment by JonathanStarup** [comment]
Can be closed, fixed by #2652

**Comment by magnus-madsen** [comment]
Almost there. Just need to wait a few hours.

**Comment by magnus-madsen** [comment]
Available:

https://arewefast.flix.dev/

currently bottom left.
