### ISSUE TITLE
Refactor and remove unsafe use of effects in the standard library

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2642]
Remove unsafe Array instances (see `Array.flix`):
- [x] Remove Eq instance.
- [x] Remove Order.
- [x] Remove Functor.
- [x] Remove Foldable.
- [x] Remove ArrayOps namespace.
- [x] Remove any tests associated with the above.

Remove unsafe MutList instances (see `MutList.flix`):
- [x] Remove Eq instance.
- [x] Remove Order.
- [x] Remove Functor.
- [x] Remove Foldable.
- [x] Remove ToString.

Remove unsafe MutSet instances (see `MutSet.flix`):
- [x] Remove Foldable.
- [x] Remove ToString.

Remove unsafe MutMap instances (see `MutMap.flix`):
- [x] Remove ToString.

Other things:
- [x] Remove redundant cast in `DelayMap.insertWithKeyL`.
- [x] Remove redundant cast in `DelayMap.mapWithKeyL`.
- [x] Investigate redundant cast in `Chain.mapAccumRightHelper`.
- [x] Remove cast and make `Iterator.filter` impure.
- [x] Remove cast and make `Iterator.map` impure.
- [x] Remove cast and make `Iterator.foreach` impure.
- [x] Remove redundant cast in `LazyList.findRightAcc`.
- [x] Remove redundant cast in `LazyList.foldRightAcc`.
- [x] Remove redundant cast in `LazyList.reduceRight`.
- [x] Remove redundant cast in `List.foldRight`.

(If any of these give trouble, just ping me).

**Comment by magnus-madsen** [comment]
@ninaandrup @jaschdoc I think Nina can do the first part and Jakob can do the second part ("other things").

**Comment by magnus-madsen** [comment]
For those following along at home, we have to make these changes to ensure the soundness of the type and effect system. If - say Array implements Foldable - then it is possibly to write pure code that is actually not pure which could fool (a future version) of the compiler into emitting incorrect code.

**Comment by magnus-madsen** [comment]
Separately we might consider how we can support e.g. `Foldable` on `Array` or `MutList`.

**Comment by jaschdoc** [comment]
I'm a bit unsure how to get rid of the casts in `LazyList.{findRight, foldRight, reduceRight}` (also there are no casts in the helper function `*Acc`) and `List.foldRight`. I've written an explanation of my thoughts at the cast in the code below.
```flix
    pub def foldRight(f: (a, b) -> b & ef, s: b, l: LazyList[a]): b & ef =
        foldRightAcc(f, s, l, ks -> ks as & ef) // without the cast, the lambda bound to variable 
                                                // k would have type `b -> b & Pure`
                                                // which would not allow for
                                                // invoking f which results in type b & ef. 

    def foldRightAcc(f: (a, b) -> b & ef, s: b, l: LazyList[a], k: b -> b & ef): b & ef = match l {
        case ENil         => k(s)
        case ECons(x, xs) => foldRightAcc(f, s,       xs, ks -> k(f(x, ks)))
        case LCons(x, xs) => foldRightAcc(f, s, force xs, ks -> k(f(x, ks)))
        case LList(xs)    => foldRightAcc(f, s, force xs, k)
    }
```

**Comment by magnus-madsen** [comment]
> 
> 
> I'm a bit unsure how to get rid of the casts in `LazyList.{findRight, foldRight, reduceRight}` (also there are no casts in the helper function `*Acc`) and `List.foldRight`. I've written an explanation of my thoughts at the cast in the code below.
> 
> ```
>     pub def foldRight(f: (a, b) -> b & ef, s: b, l: LazyList[a]): b & ef =
>         foldRightAcc(f, s, l, ks -> ks as & ef) // without the cast, the lambda bound to variable 
>                                                 // k would have type `b -> b & Pure`
>                                                 // which would not allow for
>                                                 // invoking f which results in type b & ef. 
>                                                 ////////////////////////////////////////////
> 
>     def foldRightAcc(f: (a, b) -> b & ef, s: b, l: LazyList[a], k: b -> b & ef): b & ef = match l {
>         case ENil         => k(s)
>         case ECons(x, xs) => foldRightAcc(f, s,       xs, ks -> k(f(x, ks)))
>         case LCons(x, xs) => foldRightAcc(f, s, force xs, ks -> k(f(x, ks)))
>         case LList(xs)    => foldRightAcc(f, s, force xs, k)
>     }
> ```

1. You are right, sir.
2. It is an interesting case. It is because we don't have subtyping on effects.
3. I would leave the following comment on the cast: "// NB: Cast requires because the identity continuation is pure, but the intermediate continuations are effect polymorphic". (See if you can wrap it appropriately.

**Comment by magnus-madsen** [comment]
@ninaandrup I know some of these cannot easily be removed, but I think some of the later ones can. Will you try to make a PR that deals with the `MutList` and `MutSet` etc.?

**Comment by magnus-madsen** [comment]
@ninaandrup It seems I did not entirely do my own homework when designing your tasks. We can merge #2707 and then let me get back to you :)

**Comment by magnus-madsen** [comment]
@ninaandrup I think ToString and Foldable can also be removed from `MutSet`. For the rest, Ill get back to you.

**Comment by magnus-madsen** [comment]
Also, `MutMap`'s ToString

**Comment by ninaandrup** [comment]
> @ninaandrup I think ToString and Foldable can also be removed from `MutSet`. For the rest, Ill get back to you.

Yes, I made a PR #2705

**Comment by magnus-madsen** [comment]
@ninaandrup For the remaining ill try to give some more clear instructions. 

Overall the idea is to remove instances, but without removing functions in the namespaces.

Let us start with `Eq[MutList]`. I suggest that we:

- [ ] Copy the `eq` function from the instance into the `MutList` namespace and rename it to `eq!`. (Notice that I have added a ! to the name)
- [ ] Remove the cast (the `as & ef` part). 
- [ ] Remove the Eq instance.
- [ ] Refactor all tests MutList tests. In particular, if a test was `a == b` where a and b are mut lists then it becomes ```a `MutList.eq!` b```. Feel free to import `eq!` in which case it becomes ```a `eq!` b```.

Makes sense? Lets start with that.

**Comment by ninaandrup** [comment]
> @ninaandrup For the remaining ill try to give some more clear instructions.
> 
> Overall the idea is to remove instances, but without removing functions in the namespaces.
> 
> Let us start with `Eq[MutList]`. I suggest that we:
> 
> * [ ]  Copy the `eq` function from the instance into the `MutList` namespace and rename it to `eq!`. (Notice that I have added a ! to the name)
> * [ ]  Remove the cast (the `as & ef` part) and mark it as `& Impure`.
> * [ ]  Remove the Eq instance.
> * [ ]  Refactor all tests MutList tests. In particular, if a test was `a == b` where a and b are mut lists then it becomes `` a `MutList.eq!` b ``. Feel free to import `eq!` in which case it becomes `` a `eq!` b ``.
> 
> Makes sense? Lets start with that.

Makes sense! I will try to get this done soon

**Comment by mlutze** [comment]
>     * [ ]  Copy the `eq` function from the instance into the `MutList` namespace and rename it to `eq!`. (Notice that I have added a ! to the name)

@magnus-madsen The principle relating to `!` says it is only used for marking _destructive_ functions, not impure functions in general. Do we need to readdress this principle?

**Comment by magnus-madsen** [comment]
> > ```
> > * [ ]  Copy the `eq` function from the instance into the `MutList` namespace and rename it to `eq!`. (Notice that I have added a ! to the name)
> > ```
> 
> @magnus-madsen The principle relating to `!` says it is only used for marking _destructive_ functions, not impure functions in general. Do we need to readdress this principle?

Possibly. Do you have a better name suggestion for the impure unsafe `eq`? I was thinking we could reuse `!`. But indeed eq! is not destructive, so it is a bit misleading...

**Comment by mlutze** [comment]
Maybe something like `eqNow` because the equality only holds at the moment of comparison?

**Comment by magnus-madsen** [comment]
> Maybe something like `eqNow` because the equality only holds at the moment of comparison?

It doesn't if there is concurrency.

**Comment by magnus-madsen** [comment]
It only holds if you have two unique pointers.

**Comment by JonathanStarup** [comment]
* with pure functions nothing happens and you always get the same result on repeated calls
* with non-destructive calls nothing happes and you may get different results on repeated calls
* with destructive calls things may happen and you may get different results on repeated calls

**Comment by magnus-madsen** [comment]
We agree that when we remove `instance Eq[Array]` etc. We should replace it by an `eq` function in the `Array` namespace that is impure. We can then use it as ```foo `Array.eq` bar``` (or maybe use it first and then just write `eq`).

**Comment by magnus-madsen** [comment]
@ninaandrup I think this should get you unblocked on removing Eq and Order for `MutList` (maybe start here) and `Array`.

**Comment by magnus-madsen** [comment]
We can't progress until the Datalog engine has been reworked.

**Comment by magnus-madsen** [comment]
@ninaandrup I did that refactoring on the Datalog engine. I think you can now proceed.

I would start with a PR that removes `Array.Order` and refactors the tests to call `Array.compare`. (I don't want to remove any tests, just to refactor them).

**Comment by magnus-madsen** [comment]
@ninaandrup I think you can start on removing the Eq instance for Array (and refactoring the tests to use `Array.eq` instead).

**Comment by magnus-madsen** [comment]
Fixed in master.
