### ISSUE TITLE
Type class instances for effect polymorphic functions

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2644]
The `Eq` type class requires purity:

```
pub class Eq[a] {
    pub def eq(x: a, y: a): Bool
```

Possibly this is the right choice. This means that e.g. `Array` cannot implement `Eq`.

The `Foldable` type class is effect polymorphic:

```
pub class Foldable[t : Type -> Type] {
    pub def foldLeft(f: (b, a) -> b & ef, s: b, t: t[a]): b & ef
}
```

Again, this means that `Array` cannot implement `Foldable`.

Clearly, it is *unsound* to allow a mutable data structure to implement `Eq` or `Foldable` and then just use an effect cast.

So what can be done?

- We introduce a new set of type classes? `FoldableImpure`?
- We only allow instances for unique pointers? (How would that work exactly?)
- We introduce a notion of `frozen` that "copies" (?) a mutable data structure into an immutable one.
- We do nothing. We can still provide e.g. `Array.sameElements` or we can even call it `Array.eq` that is impure.

**Comment by magnus-madsen** [comment]
https://openjdk.java.net/jeps/8261007

**Comment by mlutze** [comment]
Supposing we introduce `FoldableImpure`,

```scala
pub class FoldableImpure[a] {
    pub def foldLeft(f: (b, a) -> b & ef, s: b, t: t[a]): b & Impure
}
```

I would guess that most of the time when a programmer has some function `f(x: a): T with FoldableImpure[a]`, they would also want to be able to accept a pure `Foldable`.

To support this, we could:
1. Add a `FoldableImpure[a]` class constraint to `Foldable[a]`. Then we have to do effect casting in pure instances of `FoldableImpure`.
2. Make the user just writes the function twice.
3. Add an effect parameter to the type class (see #2587)

**Comment by magnus-madsen** [comment]
The more I think about it the more I am convinced that these higher abstractions should require their underlying data structures to be pure. If you want to fold on array you can use `Array.foldLeft` but it will be impure.
