### ISSUE TITLE
Re-export inherited definitions from type classes

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2649]
For every type class that extends another type class, we should re-export its definitions.

For example, `Order` extends `Eq`. Since `Eq` declares:

```
pub class Eq[a] {
    pub def eq(x: a, y: a): Bool

    pub def neq(x: a, y: a): Bool = not Eq.eq(x, y)
}
```

we should "re-export" these in `Order`. That is, after all the signatures of `Order` (but before its laws).

```
    ///
    /// Returns `true` if and only if `x` is equal to `y`.
    ///
    /// Re-exported from the `Eq` type class.
    ///
    pub def eq(x: a, y: a): Bool = Eq.eq(x, y)

    ///
    /// Returns `true` if and only if `x` is not equal to `y`.
    ///
    /// Re-exported from the `Eq` type class.
    ///
    pub def neq(x: a, y: a): Bool = Eq.neq(x, y)
```

We should do this for other type classes too, e.g. `SemiGroup`, `Monoid`, `Functor`, `Applicative`, etc. etc.

**Comment by magnus-madsen** [comment]
@ninaandrup Could I ask you to look into this? Does it make sense? 

If so, please make a PR for one type class at a time (starting with the simpler ones). E.g. `Re-export signatures from Eq to Order` or similar.

**Comment by magnus-madsen** [comment]
@ninaandrup This has low priority, so just when you get around to it.

**Comment by magnus-madsen** [comment]
@mlutze One problem is that if we re-export a function then Flix complains about missing laws. Then we would have to repeat those laws. How do we fix that? 

I like the idea of re-exporting because it solves the diamond problem by forcing the programmer to choose which superclass to use while at the same time allowing e.g. `Order` to have both `lessEqual` and `eq` (from `Eq`).

**Comment by magnus-madsen** [comment]
We could also re-export the laws? Declare a law that calls the other law?

**Comment by mlutze** [comment]
Laws are not callable currently, since they are not added to any namespace.

Maybe we need a marker for re-exported signatures so we know not to check them for laws.

Is it nice to have the laws in the sub class? I'm on the fence about it.

**Comment by magnus-madsen** [comment]
It seems we do need a re-export construct. Hmm.

**Comment by magnus-madsen** [comment]
@ninaandrup It seems we need to do some work before you can get started. So this is blocked for now.

**Comment by magnus-madsen** [comment]
Need to rethink.

**Comment by magnus-madsen** [comment]
Not sure this is a good idea.
