### ISSUE TITLE
Bug in Typer. ReassembleExp case FixpointProjectOut

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#2653]
The type of `mergeExp` and `SolveExp` are array types here and shouldn't use `tpe`
```
case KindedAst.Expression.FixpointProjectOut(pred, exp1, exp2, tvar, loc) =>
        val e1 = visitExp(exp1, subst0)
        val e2 = visitExp(exp2, subst0)
        val stf = Stratification.Empty
        val tpe = subst0(tvar)
        val eff = Type.mkAnd(e1.eff, e2.eff, loc)

        val mergeExp = TypedAst.Expression.FixpointMerge(e1, e2, stf, tpe, eff, loc)
        val solveExp = TypedAst.Expression.FixpointSolve(mergeExp, stf, tpe, eff, loc)
        TypedAst.Expression.FixpointProjectOut(pred, solveExp, tpe, eff, loc)
```
The weeder rewrite here for reference (Ive reformulated a bit)
```
// Performs the following rewrite:
          //
          // query e1, e2, e3 select (x, y, z) from A(x, y), B(z) where x > 0
          //
          // =>
          //
          // ProjectOut( merge e1, 2, e3,  #{ #Result(x, y, z) :- A(x, y), B(y) if x > 0 } )
```

**Comment by JonathanStarup** [comment]
I'm not entirely sure how to fix this, do you have an idea @mlutze?

**Comment by mlutze** [comment]
I'm rather confused by the whole thing. Why do we have such an AST transformation in the Typer? Shouldn't that have been done in the Weeder instead?

**Comment by magnus-madsen** [comment]
IIRC. Its because it cannot be done earlier because of type inference. (But I could be wrong).

**Comment by magnus-madsen** [comment]
I would simply put a break point and figure out what the types should be.

**Comment by mlutze** [comment]
> IIRC. Its because it cannot be done earlier because of type inference. (But I could be wrong).

If that's the case, we should add a comment or else I will complain about it again in 2 months :)

**Comment by JonathanStarup** [comment]
The problem with doing the rewrite in the weeder is that you have to cheat in ways you couldn't do yourself. 
if you do `query e select (x, y, z) from A(x, y), B(z) where x > 0` where e is a closed schema, then you can't actually add `$Result` like the transformation wants to `project out $Result from (solve (merge e #{ #Result(x, y, z) :- A(x, y), B(z) if x > 0 } )` since `e` never contains `#Result`.

The weeder basically wants to use the `open schema` operator some of us talked about (#2519), where you can open a constraintset. I think it's nice to have the transformation in the weeder, so maybe I can just add an open Ast node in the weeder ast that gets removed again in the typer?

**Comment by magnus-madsen** [comment]
Will this allow you to move the transformation from Typer to Weeder?

**Comment by magnus-madsen** [comment]
A separate issue is that we are trying to avoid doing too many transformations due to the way it degrades error reporting.

**Comment by JonathanStarup** [comment]
> Will this allow you to move the transformation from Typer to Weeder?

Thats the only problem I can see, so yes

**Comment by magnus-madsen** [comment]
> > Will this allow you to move the transformation from Typer to Weeder?
> 
> Thats the only problem I can see, so yes

What about type checking. Will it not be much more complicated?

**Comment by JonathanStarup** [comment]
> What about type checking. Will it not be much more complicated?

It just works like normally, the typer just have to unify the constraint value with and open row with the `$Result` predicate

**Comment by magnus-madsen** [comment]
OK, want to try to make a PR?

**Comment by magnus-madsen** [comment]
But how is the row stuff related to the wrong type though? Arent they orthogonal issues?

**Comment by JonathanStarup** [comment]
they are unrelated, I just wanted to see if I could make the typer fix it for me instead of creating the types myself
