### ISSUE TITLE
Remove `~>` syntax

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2657]
- [x] Flix compiler
- [x] Flix standard library
- [x] "Programming Flix"
- [x] flix.dev
- [x] Fix issue with `query` and `queryWith` in `RedBlackTree` and friends.

**Comment by KengoTODA** [comment]
The following commit has finished the necessary work on the "Programming Flix" side. refs https://github.com/flix/programming-flix/pull/68

https://github.com/flix/programming-flix/commit/5a5417fdefdd07a548d6872e0420ef89e1b50667

**Comment by magnus-madsen** [comment]
@KengoTODA Thanks! Almost done then :)

**Comment by magnus-madsen** [comment]
Thanks!
