### ISSUE TITLE
Source locations of qualified names

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2663]
Here:

![image](https://user-images.githubusercontent.com/2287953/142614106-1fcacd51-d8dd-4aaf-b73d-c2f42da8035a.png)

Do we really think that the namespace should be colored?

**Comment by magnus-madsen** [comment]
@mlutze @jhckragh What do you think?

We could change the source location to only be associated with "map" or we could have two locations?

**Comment by mlutze** [comment]
My expectation would be that when I click on LazyList, it would take me to the LazyList namespace. So `LazyList` and `Map` would be two separate tokens.

**Comment by magnus-madsen** [comment]
> 
> 
> My expectation would be that when I click on LazyList, it would take me to the LazyList namespace. So `LazyList` and `Map` would be two separate tokens.

In that case `Expression.Def` and `Expression.Sig` would need more information.

One issue is that a namespace cannot be clicked because it may reside in multiple files.

**Comment by magnus-madsen** [comment]
Fixed in master.
