### ISSUE TITLE
Help find a good name for `LazyList` etc.

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2664]
We have two data structures that are purity polymorphic (i.e. they vary their behavior depending on the purity or impurity of their arguments). We currently call them `LazyList` and `DelayMap`.

Other names that have been floated are:

- `DemandList`
- `ByNeedList`.
- `PPList` (uh oh)

Help suggest some names for these data structures.

**Comment by magnus-madsen** [comment]
- `OpportuniscList`
- `LoafingList`

**Comment by mlutze** [comment]
`PurityDependentList` (`PDList`)
`DisciplinedList`
`CircumstantialList`
`ReluctantList`
`ContingentList`

**Comment by magnus-madsen** [comment]
- `PurityAwareList`

**Comment by jaschdoc** [comment]
`AutoList`
`DefaultList`
`EffectList` or `EList`

**Comment by magnus-madsen** [comment]
`DeferList`
`DeferredList`

**Comment by magnus-madsen** [comment]
`ReifiedEffectList`
`ReifiedPurityList`

**Comment by magnus-madsen** [comment]
`PurityList`
`PureList`

**Comment by magnus-madsen** [comment]
Time to vote: https://strawpoll.com/k52xbhu29

**Comment by magnus-madsen** [comment]
We decided on DelayList and DelayMap.
