### ISSUE TITLE
Syntax for effectful function types

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2665]
The function type:

```scala
Int32 -> Bool -> String
```

is right associative, i.e. it means `Int32 -> (Bool -> String)`. This is good because most often you want the function to take one argument at a time. The special case is when you have a function argument in which case you put parens.

What happens when we have effects? Currently we have the syntax:

```scala
Int32 -> Bool & Impure
```

But what about:

```scala
Int32 -> Bool & Impure -> String
Int32 -> Bool & ef-> String
```

We would like to parse it as `Int32 -> (Bool & Impure -> String)` and `Int32 -> (Bool & ef -> String)` but that is incorrect!

This suggests that I messed up when I came up with the syntax.

A solution has to move the effect to the left of the return type, e.g.:

```scala
Int32 -> Impure & Bool-> String
Int32 -> ef & Bool-> String
// or
Int32 & Impure -> Bool-> String
Int32 & ef -> Bool-> String
```
I am not happy with either.

The syntax:

```scala
Int32 {ef} -> Bool -> String
Int32 {Impure} -> Bool -> String
```

is also an option

**Comment by mlutze** [comment]
There was also this mid-arrow idea that came up before: `-ef>` or `-{ef}>`

**Comment by esbenbjerre** [comment]
Is it possible to do
```
Int32 -> Impure[Bool] -> String
Int32 -> ef[Bool] -> String

Impure[Int32] -> Bool-> String
ef[Int32] -> Bool-> String
```
?

**Comment by magnus-madsen** [comment]
> Is it possible to do
> 
> ```scala
> Int32 -> Impure[Bool] -> String
> Int32 -> ef[Bool] -> String
> 
> Impure[Int32] -> Bool-> String
> ef[Int32] -> Bool-> String
> ```
> 
> ?

Possible yes, but I think it is very ugly :) Also `ef[Int32]` clashes with type application, so maybe not even possible :)

**Comment by magnus-madsen** [comment]
```
Int32 \ ef -> Bool -> String
Int32 \ ef1 -> Bool \ ef2 -> String
Int32 \ ef1 and ef2-> Bool \ ef2 -> String
```

**Comment by magnus-madsen** [comment]
We can also place the effect on the right of the arrows:

```
Int32 -> ef & Bool -> String
Int32 -> ef1 & Bool -> ef2 & String
Int32 -> ef1 & Bool -> ef2 & String -> Option[Int32] & (ef1 and ef2)
```

or with `\`:

```
Int32 -> ef \ Bool -> String
Int32 -> ef1 \ Bool -> ef2 \ String
Int32 -> ef1 \ Bool -> ef2 \ String -> Option[Int32] \ (ef1 and ef2)
```

**Comment by magnus-madsen** [comment]
I am currently leaning towards:

```
Int32 {ef} -> Bool -> String
Int32 {Print} -> Bool -> String
Int32 {Impure} -> Bool -> String
```

**Comment by JonathanStarup** [comment]
Maybe `Int32 {ef}-> Bool -> String` would more clearly attach the effect to the function

**Comment by magnus-madsen** [comment]
I think we stick with the current syntax for now.
