### ISSUE TITLE
NoFormatter - must still format, not just with colors

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2678]
This:

```
def main(_args: Array[String]): Int32 & Impure = 
    println("Hello World!");
    0

def main(_args: Array[String]): Int32 & Impure =
    println("Hello World!");
    0
```

gives

```
-- Name Error -------------------------------------------------- foo.flix

>> Duplicate definition 'main'.

foo.flix:5:5the first occurrence was here.

foo.flix:1:5the second occurrence was here.
```

The problem is that `NoFormatter` should still "format" just not with colors!

**Comment by magnus-madsen** [comment]
@jaschdoc This is pretty urgent, so work on it as soon as you get a chance :)

**Comment by magnus-madsen** [comment]
I think one solution is to move `line`, `code`, `underline`, etc. into `Formatter` trait itself. Then e.g. `blue` is called it will automatically reuse the right one.

**Comment by jaschdoc** [comment]
How do we underline text if there's no ANSI terminal environment? The `underline` function currently depends on the Console object but that isn't a valid dependency in the general case when moving `underline` to the `Formatter` trait.
