### ISSUE TITLE
Allow complex instances for true/false

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2689]
I would like to allow e.g.:

```
instance Functor[Result[e]] // note I swapped the type arguments
```

and equally important

```
instance Eq[Vector[true]] // which means the vector is immutable.
```

@mlutze What are the things we should consider?

**Comment by mlutze** [comment]
The following is assuming we still don't want overlapping instances.

1. Partially-applied enums are not considered complex and are already possible, so we just need to make changes to the standard library to support `Functor[Result[e]]`
2. It seems we will also need to support more complex constraints such as `Foo[Tree[a]]` rather than only variable constraints.
3. We still shouldn't support variable-only instances: `instance Foo[a]` since this is equivalent to simply declaring the polymorphic functions.
4. In general, one should very carefully consider whether to use a complex instance. For example, if we do `Foo[Option[Int]]` it then means that for any other `Option[a]` type we have to declare the instance explicitly, rather than benefiting from a general `Foo[Option[a]]` instance. This suggests that we have a principle relating to when to use complex instances. We might even want to consider only allowing it on boolean types for now?

**Comment by magnus-madsen** [comment]
Thanks for the nice write up. See my comments below.

> 1. Partially-applied enums are not considered complex and are already possible, so we just need to make changes to the standard library to support `Functor[Result[e]]`

OK, you mean that just swapping the order of arguments would work? 

> 2. It seems we will also need to support more complex constraints such as `Foo[Tree[a]]` rather than only variable constraints.

Why do you think so? What is `Foo` here?

> 3. We still shouldn't support variable-only instances: `instance Foo[a]` since this is equivalent to simply declaring the polymorphic functions.

Agreed. 

> 4. In general, one should very carefully consider whether to use a complex instance. For example, if we do `Foo[Option[Int]]` it then means that for any other `Option[a]` type we have to declare the instance explicitly, rather than benefiting from a general `Foo[Option[a]]` instance. This suggests that we have a principle relating to when to use complex instances. We might even want to consider only allowing it on boolean types for now?

Okay.

What is the delta from what we have now to just allowing:

```
instance Eq[Vector[true]]
```

where 

```
enum Vector[_imm: Bool, a: Type]
```?

Maybe it is very close, if we already have it for partially applied enums? (Do we have any tests for that)? 

We could restrict it to just `true/false` also.

**Comment by magnus-madsen** [comment]
Is this supposed to work:

```
pub enum Foo[a, b] 

instance Eq[Foo[String]] {

  pub def eq(x: Foo[String, a], y: Foo[String, a]): Bool = ???

}
```

or what is supposed to work?

**Comment by mlutze** [comment]
> Thanks for the nice write up. See my comments below.
> 
> > 1. Partially-applied enums are not considered complex and are already possible, so we just need to make changes to the standard library to support `Functor[Result[e]]`
> 
> OK, you mean that just swapping the order of arguments would work?

Yes, if we just change the declaration to `enum Result[e, t]`, we'll be able to make `instance `Functor[Result[e]]`

> 
> > 2. It seems we will also need to support more complex constraints such as `Foo[Tree[a]]` rather than only variable constraints.
> 
> Why do you think so? What is `Foo` here?

I'll change it to `Eq` for the example:

```scala
def mkTree(x: a): Tree[a] = ???

def treesEq(x: a, y: a): Bool with <constraints> = {
    mkTree(x) == mkTree(y)
}

/// Without complex instances
instance Eq[Tree[a]] with Eq[a] { ... }

/// With Complex instances
instance Eq[Tree[Int]] { ... }
instance Eq[Tree[String]] { ... }

```
With only simple instances we infer `Eq[Tree[a]]`. Only one instance can possibly unify with this, so we see what constraints it entails, which is just `Eq[a]`, so we `<constraints>` needs to be `Eq[a]`

With complex instances, we don't have enough information to pick an instance. Either `Tree[Int]` or `Tree[String]` could unify with `Tree[a]` so `<constraints>` has to be `Eq[Tree[a]]`


> 
> What is the delta from what we have now to just allowing:
> 
> ```
> instance Eq[Vector[true]]
> ```
> 
> where
> 
> ```
> enum Vector[_imm: Bool, a: Type]
> ```
> 
> ?
> 
> Maybe it is very close, if we already have it for partially applied enums? (Do we have any tests for that)?
> 
> We could restrict it to just `true/false` also.

I believe we have tests for partially-applied enums. I'm not totally sure yet what the implications will be on instance resolution, but I'm not immediately aware of any major problems.

**Comment by mlutze** [comment]
> Is this supposed to work:
> 
> ```
> pub enum Foo[a, b] 
> 
> instance Eq[Foo[String]] {
> 
>   pub def eq(x: Foo[String, a], y: Foo[String, a]): Bool = ???
> 
> }
> ```
> 
> or what is supposed to work?

Currently, the closest thing to that which works is:
```scala
pub enum Foo[a, b] 

instance Eq[Foo[a, b]] {

  pub def eq(x: Foo[a, b], y: Foo[a, b]): Bool = ???

}
```

After allowing complex instances, the following will work:
```scala
pub enum Foo[a, b] 

instance Eq[Foo[String, a]] {

  pub def eq(x: Foo[String, a], y: Foo[String, a]): Bool = ???

}
```

(Note the addition of the type variable `a`).

I'll note as well in your first example you also need an additional type variable to make it the right kind:
```scala
instance Eq[Vector[true]]
// should be
instance Eq[Vector[true, a]]
```

**Comment by magnus-madsen** [comment]
I think going from just:

```
pub enum Foo[_a: Bool, _b: Type] 
instance Eq[Foo[a, b]] {
  pub def eq(x: Foo[a, b], y: Foo[a, b]): Bool = ???
}
```

to:

```
pub enum Foo[_a: Bool, _b: Type] 
instance Eq[Foo[true, b]] {
  pub def eq(x: Foo[a, b], y: Foo[a, b]): Bool = ???
}
```

would be very useful.

**Comment by magnus-madsen** [comment]
Essentially only allowing true/false in addition to (distinct) type variables.

**Comment by mlutze** [comment]
We can avoid adding complex constraints if we only allow one instance for the Bool. (e.g. `instance Eq[Foo[true, a]]` prevents `instance Eq[Foo[false, a]]`. I think this is reasonable because if you do want one instance for `true` and one for `false`, you can just use a polymorphic instance and match on the Bool in the signature. Thoughts?

**Comment by magnus-madsen** [comment]
> We can avoid adding complex constraints if we only allow one instance for the Bool. (e.g. `instance Eq[Foo[true, a]]` prevents `instance Eq[Foo[false, a]]`. I think this is reasonable because if you do want one instance for `true` and one for `false`, you can just use a polymorphic instance and match on the Bool in the signature. Thoughts?

Sounds reasonable, but both true and false might be relevant.
