### ISSUE TITLE
Add `Channel.spawnWithChannel`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2703]
I think it would be nice to have something like:

```
def spawnAndAwait(f: Unit -> a & ef]): a & ef = let c = chan 0; spawn(f()); <- chan
```

**Comment by JonathanStarup** [comment]
Would is the cast the output to `ef`? Otherwise it would always be Impure right?

Is the purpose to spawn and wait for an element on some channel? Why do you spawn then? 

It seems like no one has access to `c` here, isn't the last expression just blocking?

**Comment by magnus-madsen** [comment]
> Is the purpose to spawn and wait for an element on some channel? Why do you spawn then?

Yes, you are right. it makes no sense. :)

**Comment by magnus-madsen** [comment]
What about:

```
def spawnAndAwait(f: Unit -> a & ef]): Channel[a] & ef = let c = chan 0; spawn(f()); chan
```

**Comment by JonathanStarup** [comment]
I think that's nice. this is basically a future code pattern right?

**Comment by JonathanStarup** [comment]
I think a Future.flix library would be doable but I don't know if its needed for anything

**Comment by magnus-madsen** [comment]
As it turns out my idea here is spectacularly bad! :)

The problem is that in both the future nursery system and future 2nd class system, the above code would not work, since it violates the properties needed. In particular, `spawnWithChannel` spawns a thread that outlives its scope, moreover it has to be impure. For now, I think we should stick with writing the code explicitly. Then once the two new systems arrive we can think about a Future library.
