### ISSUE TITLE
Boxable

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2708]
We have two separate issues with boxable:

- Do we want to use type classes or reification to implement it?
- How do we deal with boxes that do not require Order and ToString?

**Comment by magnus-madsen** [comment]
Proposal: We address (B) first and then we consider (A).

**Comment by JonathanStarup** [comment]
I think an implementation with reify makes a lot of sense. box/unbox can always be implemented but sometimes the Boxable type class has to be included explicitely (`def f(v: t): Unit with Boxable[t] = ...`).
```
def box(v: t): Boxed = match reifyType t {
    case ReifiedBool => BoxedBool(v as Bool)
    case ErasedType => BoxedObject(v as ##java.lang.Object, None, None)
    case _ => ??? // etc.
}

def unbox(b: Boxed): t = match b {
    case BoxedBool(v) => v as t
    case BoxedObject(v) => v as t
    case _ => ??? // etc.
}
```

**Comment by magnus-madsen** [comment]
The problem is that the Datalog solver requires `Order` and `ToString`.

We could overcome this by:

```
def boxWithOrder(v: t): Boxed with Order[t], ToString[t]
```

**Comment by magnus-madsen** [comment]
Also, what about:

```
pub def lift2(f: t1 -> t2 -> t): Boxed -> Boxed -> Boxed with Boxable[t1], Boxable[t2], Boxable[t]
```

?

**Comment by magnus-madsen** [comment]
The fact that the Datalog engines requires both `Order` and `ToString` could be fixed by either (a) introducing a common super class or (b) introducing a `Debug` type class and have all types implement that.

**Comment by JonathanStarup** [comment]
> 

Doesn't the exact same code work? 
```
(b1: Boxed) -> (b2: Boxed) -> box(f(unbox(b1), unbox(b2)))
```

**Comment by magnus-madsen** [comment]
> Doesn't the exact same code work for lift2?
> 
> ```
> (b1: Boxed) -> (b2: Boxed) -> box(f(unbox(b1), unbox(b2)))
> ```

What about the Order and ToString instances?

**Comment by JonathanStarup** [comment]
> The problem is that the Datalog solver requires Order and ToString.

Yeah I think that would work. Then you would get `Order`/`ToString` requirements when you project in/out

**Comment by JonathanStarup** [comment]
> The fact that the Datalog engines requires both `Order` and `ToString` could be fixed by either (a) introducing a common super class or (b) introducing a `Debug` type class and have all types implement that.

What would debug include? Can the engine only depend on one type class?

**Comment by JonathanStarup** [comment]
Wouldn't the change be to replace `Boxable[a]` with `Order[a], ToString[a]` and use 
```
def boxWithOrder(v: t): Boxed with Order[t], ToString[t]
```

**Comment by JonathanStarup** [comment]
Wouldn't the change be to replace `Boxable[a]` with `Order[a], ToString[a]` and use 
```
def boxWithOrder(v: t): Boxed with Order[t], ToString[t]
```

**Comment by magnus-madsen** [comment]
> Wouldn't the change be to replace `Boxable[a]` with `Order[a], ToString[a]` and use
> 
> ```
> def boxWithOrder(v: t): Boxed with Order[t], ToString[t]
> ```

Yes, in theory. But now look at e.g. `Solver.flix`. It becomes a bit long.

**Comment by magnus-madsen** [comment]
But maybe it is the price we have to pay.

**Comment by JonathanStarup** [comment]
whoa yea, thats's unpleasent

**Comment by JonathanStarup** [comment]
`type alias OrderAndString[a] = a with Order[a], ToString[a]` is not supported but would fit well here

**Comment by mlutze** [comment]
Is there an issue with this:
```scala
class OrderedBoxable[a] with Boxable[a], Order[a], ToString[a]
```
