### ISSUE TITLE
Add Lattice instances to Set?

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#2714]
Should the the instances for the lattice classes be added to Set?

I think there is a single canonical instance of the lattice classes for Set, so it should have them implemented:

~~~

instance LowerBound[Set[a]] with Order[a] {
    pub def minValue(): Set[a] = Set.empty()
}

instance PartialOrder[Set[a]] with Order[a] {
    pub def lessEqual(x: Set[a], y: Set[a]): Bool with Order[a] = x <= y
}

instance MeetLattice[Set[a]] with Order[a] {
    pub def greatestLowerBound(x: Set[a], y: Set[a]): Set[a] with Order[a] = Set.intersection(x, y)
}

instance JoinLattice[Set[a]] with Order[a] {
    pub def leastUpperBound(x: Set[a], y: Set[a]): Set[a] with Order[a] = Set.union(x, y)
}

~~~

I believe we can live without `UpperBound` and still have a viable lattice for Datalog. Is this true?

...

There is also the lattice for Bool which as far as I know is canonical, `LowerBound` and `UpperBound` are already in the stdlib:

~~~

instance PartialOrder[Bool] {
    pub def lessEqual(x: Bool, y: Bool): Bool = x <= y
}

instance MeetLattice[Bool] {
    pub def greatestLowerBound(x: Bool, y: Bool): Bool = x and y
}

instance JoinLattice[Bool] {
    pub def leastUpperBound(x: Bool, y: Bool): Bool = x or y
}

~~~

**Comment by magnus-madsen** [comment]
Both would work, but they would not necessarily be very useful/efficient.

**Comment by stephentetley** [comment]
I've been using the Set instances / lattice though I'm pretty sure my sets will be small.

I haven't had a use for the Bool lattice except for learning about lattices.

The Bloom language also had lattices for Bag (List?) and Map. I suspect both would be less efficient than Set.

**Comment by magnus-madsen** [comment]
Mathematically speaking there are also two instances for Set. One where the lattice is flipped upside down.

**Comment by magnus-madsen** [comment]
I think we can add these instances, but I am slightly hesitant.

**Comment by magnus-madsen** [comment]
I think we did this, right?

**Comment by stephentetley** [comment]
Yes - it looks like @JonathanStarup did it last month. Thanks.
