### ISSUE TITLE
Hoist class size exception to flix error

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#2716]
If you have too many methods in a Flix namespace (around ~850 atm depending on signature size) then asm throws an error when trying to get the byte array out of the class writer. We should probably catch this error and propagate it is a nice looking flix error

**Comment by magnus-madsen** [comment]
I see the point, but its a bit difficult in the current architecture. What does the Java compiler do?

**Comment by magnus-madsen** [comment]
Maybe an earlier phase should limit the number of functions?

**Comment by JonathanStarup** [comment]
Hmm yea. Maybe I was a bit quick. The limiting factor right now is Ns, which will be removed(?) The next limiting factor is probably the method size of 65xxx bytes which is harder to check before the backend.

**Comment by magnus-madsen** [comment]
I am closing because I don't think we need to handle this. Soon we will not be running into these limits before we run into other limits.
