### ISSUE TITLE
Delimiter

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2717]
Using `$` as a delimiter in JVM classes is suboptimal because decompilers treat them as inner classes.

We need to choose a delimiter allowed on Windows and Linux filesystems. I suggest either `%` or `@`.

**Comment by JonathanStarup** [comment]
Should this also be something that is reserved in Flix or is that not a concern?

**Comment by magnus-madsen** [comment]
It should be reserved. We will check on that.

**Comment by magnus-madsen** [comment]
#2722 fixes it in the backend, but we should probably move `JvmName.Delimiter` into `Flix` and use it everywhere.

**Comment by magnus-madsen** [comment]
- [ ] Move `JvmName.Delimiter` to `Flix.Delimiter`.
- [ ] Replace all occurrences of "$" in `Weeder` with `Flix.Delimiter`.
- [ ] Replace the one occurrences in `Resolver`.
- [ ] Replace the four occurrences in `Symbol`.
- [ ] Replace the one occurence in `JvmOps` near line 261.

**Comment by magnus-madsen** [comment]
It seems I did not find all $ signs. Need to look more.

**Comment by JonathanStarup** [comment]
> It seems I did not find all $ signs. Need to look more.

for some reason intelllij really struggled to search for `$` for me, seems like an easy enough task but it couldn't find them all

**Comment by magnus-madsen** [comment]
No worries. Time will tell if I got them all :P
