### ISSUE TITLE
Semantic Commit Messages

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2718]
Add the following to `STYLE.md`:

# Pull Requests

- Pull requests should use [Semantic Commit Messages](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716).
  - We use the types: `feat`, `fix`, `docs`, `style`, `refactor`, `test`, `chore`.
  - The summary should be a single sentence in past tense (all lower case except for names).
  - For example: `feat: added annotations for purity polymorphism`.
- Pull requests should be a small as possible. 
  - An ideal pull request is between one and a few hundred lines of code.
- When you create a pull request, click `Files Changes` to ensure that everything looks as you expect.
  - The easier a pull request is to understand the faster it will be merged. A win-win.
- If the pull request fixes a bug the summary should end with (fixes #9999).
- If the pull request is related to a ticket the summary should end with (related to #9999).

**Comment by mlutze** [comment]
Presumably this only matters for the merging commit. I can still have whatever terrible commit messages I use while the PR is in progress?

**Comment by magnus-madsen** [comment]
> Presumably this only matters for the merging commit. I can still have whatever terrible commit messages I use while the PR is in progress?

Thats right. But for the PR title.

**Comment by JonathanStarup** [comment]
> * If the pull request fixes a bug the summary should end with (fixes #9999).
> * If the pull request is related to a ticket the summary should end with (related to #9999).

Wouldn't it be easier to read along if it is at the top?

**Comment by magnus-madsen** [comment]
> > * If the pull request fixes a bug the summary should end with (fixes #9999).
> > * If the pull request is related to a ticket the summary should end with (related to #9999).
> 
> Wouldn't it be easier to read along if it is at the top?

The summary is just one sentence. Not a whole block of text.
