### ISSUE TITLE
Add principle about annotations

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2724]
Flix has both annotations and modifiers. Both annotations and modifiers are part of Flix and cannot be defined by programmers. That is, there are no user-defined annotations or modifiers. In Flix:

A modifier is part of the language itself. A modifier typically impacts the meaning of a program. Incorrect use of modifiers may prevent compilation or even break a program. Modifiers cannot be declared by the user. There is simply a fixed set.

An annotation is essentially a form of documentation. Unlike a comment an annotation has a fixed name and semantics (set by us). Annotations are not user-definable (because that could lead to multiple annotations that mean the same thing and it could also lead to confusion about what an annotation means). Annotations serve as a compress way to represent information.

**Comment by mlutze** [comment]
+ how we decide between keywords and annotations, please!

**Comment by magnus-madsen** [comment]
This is covered in the principles paper.
