### ISSUE TITLE
closures have thread-safety issues

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#2741]
When a closure is transported and used on different threads, they all operate on the same set of argument- and result fields. To fix this we need to ensure unique objects for each thread. My solution:

* Add a `fetchFunctionObject(): Fni$...` function that conservatively could make a new dublicate of `this` for each call (the current behaviour is to always return `this`).
* The call protocal work like usual, except you need to call this function on your closure object and work on the closure returned from the function. ( we can later optimzie the object allocation, maybe store a thread ID of the closure creater/last dublicator)

**Comment by magnus-madsen** [comment]
OK. This sounds like the minimal delta that can make it work. It will probably be slow, but then we can iterate from there.

**Comment by JonathanStarup** [comment]
> OK. This sounds like the minimal delta that can make it work. It will probably be slow, but then we can iterate from there.

You thinking of optimizations other than thread id tracking?

**Comment by magnus-madsen** [comment]
> > OK. This sounds like the minimal delta that can make it work. It will probably be slow, but then we can iterate from there.
> 
> You thinking of optimizations other than thread id tracking?

No just that. But without it you will copy an object per call. That is probably not cheap :) We shall see.
