### ISSUE TITLE
Add `RedundantPurityCast` and `RedundantEffectCast`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2753]
This is now flagged:

```
def foo(): Int32 = 123 as & Pure
```

**Comment by magnus-madsen** [comment]
@JonathanStarup @mlutze Any thing else we want to flag? 

I think having these checks is useful before we start eliminating a lot of casts with our work on the import mechanism and the 2nd class values. This will help us refactor code better. And, as you can see, I found three places in the std. lib. where this was already happening.

**Comment by mlutze** [comment]
Nothing comes to mind.
