### ISSUE TITLE
Minor change to cast syntax

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2755]
Proposal. Instead of the current:

```
exp as & Pure
```

require:

```
exp as _ & Pure
```

to make clear that the type stays the same.

EDIT: This would also apply to ascribe.

**Comment by JonathanStarup** [comment]
does this also include nested types `List[_]`. That would be nice

**Comment by magnus-madsen** [comment]
> does this also include nested types `List[_]`. That would be nice

Like ensuring its a list but not caring about its element?

**Comment by JonathanStarup** [comment]
Yes

**Comment by magnus-madsen** [comment]
OK. I understand. That is more difficult, but we could certainly do it after this ticket.

**Comment by magnus-madsen** [comment]
I think this should wait until the new import syntax is in.

**Comment by magnus-madsen** [comment]
We agreed to do this.

**Comment by magnus-madsen** [comment]
@jaschdoc One more cast thing. Sigh... :)

We want `unsafecast exp as _ \ IO` not just `unsafecast exp as \ IO`

**Comment by jaschdoc** [comment]
Do we want this for ascriptions in addition to the cast syntax? I.e. `let x: _ \ IO`?

**Comment by magnus-madsen** [comment]
> Do we want this for ascriptions in addition to the cast syntax? I.e. `let x: _ \ IO`?

No

**Comment by jaschdoc** [comment]
Roger
