### ISSUE TITLE
[Smallfix] Allow Custom Operators ala Scala

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#276]
In Scala you are allowed to define your own operators, but their precedence and associativity is derived from the first character of the operator. 

For example, 

the operator `+++` will have its precedence derived from `+`. 
the operator `***` will have its precedence derived from `*`,
the operator `<` will have its precedence derived from `<`.  

etc.

**Comment by mhyee** [comment]
This is one of those Scala features that I'm not sure how I feel about.

When I first learned this, my reaction was "wat?" It seems like a hack to determine precedence based on the first character (and right-associativity based on operators ending with `:`), and can really bite you if you don't know what you're doing.

On the other hand, it's simpler and more uniform than manually specifying precedence, which is [what Haskell does](https://www.haskell.org/onlinereport/decls.html#sect4.4.2).

**Comment by magnus-madsen** [comment]
I am aware of four points in the design space:

1. Disallow user-defined operators.
2. Allow user-defined operators, but only for operators that already exist, e.g. `+` (aka "overloading").
3. Allow arbitrary user-defined operators -- Scala style -- but use the first character to deal with precedence, etc.
4. Allow arbitrary user-defined operators and precedence.

The tricky thing about 4. is that it requires semantic analysis to understand how to parse an expression; i.e. you have to parse the program to collect the operators, and then "re-parse" the expressions. Furthermore, in any given expression there is no way to know the precedence without knowing all the operators. In contrast, the Scala solution **may** be a sweet spot: It does not require semantic analysis, you call the precedence by merely looking at the expression (no need to know what the operators do), and finally: It is easy to implement.

**Comment by magnus-madsen** [comment]
F# seems to emulate Scala aswell:

https://docs.microsoft.com/en-gb/dotnet/articles/fsharp/language-reference/symbol-and-operator-reference/index

**Comment by magnus-madsen** [comment]
Actually, there is a 5th of option: Give user-defined operators the highest priority, but do not distinguish between them.

**Comment by magnus-madsen** [comment]
Implemented.
