### ISSUE TITLE
cannot run flix file with `[` in name

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#2762]
In the latest vscode release I press run on a file like this:
![image](https://user-images.githubusercontent.com/32037926/144421093-cdc7bca3-1ead-4921-a6a8-1269bf5496e7.png)
The program here is called `qw[].flix`
I get an error:
```
Exception in thread "main" java.lang.IllegalArgumentException: 'c:...\qw\[\].flix' must be a file.
        at ca.uwaterloo.flix.api.Flix.addPath(Flix.scala:296)       
        at ca.uwaterloo.flix.Main$.$anonfun$main$4(Main.scala:184)  
        at scala.collection.immutable.List.foreach(List.scala:333)  
        at ca.uwaterloo.flix.Main$.main(Main.scala:181)
        at ca.uwaterloo.flix.Main.main(Main.scala)
```

**Comment by magnus-madsen** [comment]
Why would you have [ in the file name? :(

Is this a Flix issue or vscode issue is the question (or both)

**Comment by magnus-madsen** [comment]
No matter where this bug is, I am not really sure what to do with it. Do we plan to support strange file names on all platforms?

**Comment by JonathanStarup** [comment]
I think its a symptom of a more general error, when a file is referenced in command, it says `c:\\Users\\foo\\AppData\\Roaming\\Code\\User\\globalStorage\\flix.flix\\flix.jar`. I don't know why this is the correct file but it should just be `c:\Users\foo\AppData\Roaming\Code\User\globalStorage\flix.flix\flix.jar` and that works fine. It looks like there is an extra level of escape characters

**Comment by magnus-madsen** [comment]
https://github.com/flix/vscode-flix
https://www.npmjs.com/package/shell-quote

Question is: Why does a library with 11mill downloads not work correctly? Are we using it wrong.

**Comment by magnus-madsen** [comment]
https://github.com/flix/vscode-flix/blob/master/client/src/handlers/handlers.ts#L78

**Comment by JonathanStarup** [comment]
I think the problem is that `quote` is intended for string arguments? If you needed to pass your program the string `c:user\something\other` you would indeed have to write `c:user\\something\\other`. The package doesn't really have examples with paths so im not sure how to do that.

Im also unsure if it supports windows cmd? https://github.com/substack/node-shell-quote/issues/38

**Comment by magnus-madsen** [comment]
Maybe we need another library?

**Comment by JonathanStarup** [comment]
maybe. [puka](https://www.npmjs.com/package/puka) also mentions that it's only for string passing, which is maybe also the case for shell-quote? [This](https://www.npmjs.com/package/shelljs) looks nice but it seems it executes the commands directly

**Comment by magnus-madsen** [comment]
I am not sure we should even try to deal with file names that contain strange characters. In any case, it would be a VSCode issue.
