### ISSUE TITLE
Introduce `Debug` type class

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2769]
The debug type class:

```
class Debug[a] {
  pub def format(x: a): String
}
```

The `Debug` type class is *automatically* implemented for all types. It cannot be defined by the user.

In particular, the default implementation could `reifyType`.

The output of `Debug.format` is compiler-defined. Specifically:

- IntX are printed as `123i32`
- Strings are quoted ""
- Chars are single quoted.
- etc.

**Comment by magnus-madsen** [comment]
@mlutze If instances of this class are always available should the compiler know?

**Comment by mlutze** [comment]
Yes, I think we'd want to avoid requiring `with Debug[a]` everywhere. We can probably do this by magically adding a `Debug[a]` (for free `a`) to the `ClassEnvironment`

**Comment by magnus-madsen** [comment]
I guess one issue is how to find the "magical instance"? E.g. for records?

**Comment by magnus-madsen** [comment]
Question: What if the function carried an indent argument? Then we could use it to pretty print.

For example, an implementation of Map could wrap:

```
Map#{
  a -> b..
  c -> d
```

See #2769

**Comment by mlutze** [comment]
We'll need to do it as late as Monomorph I believe, and generate the definitions as they come?

**Comment by mlutze** [comment]
> Question: What if the function carried an indent argument? Then we could use it to pretty print.
> 
> For example, an implementation of Map could wrap:
> 
> ```
> Map#{
>   a -> b..
>   c -> d
> ```
> 
> See #2769

(Wrong thread?)

**Comment by magnus-madsen** [comment]
Edit: https://github.com/flix/flix/pull/2770

**Comment by magnus-madsen** [comment]
OK, so it sounds like:

- The Debug instance for enums could be derived the usual way. 
- The Monomorpher would automatically derived instances for other types.

Not sure what to do for e.g. function types, maybe just print their type or object identifier.

**Comment by magnus-madsen** [comment]
Its problematic if we only support up to N=10 tuples and someone has a longer tuple. That would crash the compiler. Same problem for functions. Maybe this is fixed by having the Monomorpher rescue us an providing a default "no debug instance" string.

**Comment by mlutze** [comment]
Surely the monomorpher could generate functions for arbitrarily long tuples, no?

**Comment by magnus-madsen** [comment]
Another question is: How would this feature interact neatly with string interpolations? Because those are tied to `ToString`.

**Comment by magnus-madsen** [comment]
> Surely the monomorpher could generate functions for arbitrarily long tuples, no?

Yes, but I would prefer not to add 1500 lines of code just for this one feature/type class.

**Comment by magnus-madsen** [comment]
But maybe we have to.

**Comment by mlutze** [comment]
> Another question is: How would this feature interact neatly with string interpolations? Because those are tied to `ToString`.

Maybe a special debug formatting string?

```scala
// prefix
d"value of x here is: ${x}"

// interpolation symbol
"value of x here is ###{x}"
```


> > Surely the monomorpher could generate functions for arbitrarily long tuples, no?
> 
> Yes, but I would prefer not to add 1500 lines of code just for this one feature/type class.

Generalized type classes for all tuple lengths could be useful for a lot of different features, I think. (Boxable, equality, order...)

**Comment by magnus-madsen** [comment]
We now have `stringify` as an alternative.
