### ISSUE TITLE
Use LetRec in Standard Library

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2774]
The goal of this ticket is to eliminate all top-level `helper`, `visit`, and `acc` functions.

For example, here is the current implementation of `List.indexOf`:

```scala
pub def indexOf(a: a, xs: List[a]): Int32 with Eq[a] = indexOfHelper(a, xs, 0)

def indexOfHelper(a: a, xs: List[a], acc: Int32): Int32 with Eq[a] = match xs {
    case Nil => -1
    case x :: rs => if (x == a) acc else indexOfHelper(a, rs, acc+1)
}
```

With the new let-rec / local def construct this should be rewritten to:

```scala
pub def indexOf(a: a, l: List[a]): Int32 with Eq[a] =
    def loop(m, i) = match m {
        case Nil     => -1
        case x :: xs => if (x == a) i else loop(xs, i + 1)
    };
    loop(l, 0)
```

Notice how `mapHelper` has been moved into `indexOf` and renamed to `loop`.

A few rules:

- [x] The local function should be called `loop` (not xyzHelper, not xyzAcc, etc.)
- [x] The local function should not have any type annotations.
- [x] This refactoring is not expected to break any test cases.

I suggest that this refactoring is performed one namespace at a time (and maybe even in smaller chunks). We could start with:

- [ ] `List`
- [ ] `File`
- [ ] `Int32`

to build some experience.

**Comment by magnus-madsen** [comment]
@jaschdoc Could I ask you to refactor specifically the following functions to use a local `loop`:

- length
- range
- take
- drop
- reverse
- filter
- map
- foldLeft
- foldRight
- unzip
- memberOf
- exists
- forall

(its okay to do these overall several PRs).

The reason for this very specific list is that they are used inside `BenchmarkList` and we want to see the performance impact.

**Comment by jaschdoc** [comment]
Could you assign me to this please? I use that to get an easy overview of what I'm working on.

**Comment by jaschdoc** [comment]
Is this for recursive / visitor functions only or also for helper functions like `File.readBytesWithHelper` which simply improves readability? See https://github.com/flix/flix/blob/471ec75b2201f5462fd82a26435bb72592a8b06f/main/src/library/File.flix#L354

**Comment by magnus-madsen** [comment]
> Is this for recursive / visitor functions only or also for helper functions like `File.readBytesWithHelper` which simply improves readability?
> 
> https://github.com/flix/flix/blob/471ec75b2201f5462fd82a26435bb72592a8b06f/main/src/library/File.flix#L354

I think it depends. In this case it might be better to leave it.  But in most cases -- when the helper is very simple -- we should inline it.

**Comment by jaschdoc** [comment]
I think we can close this issue, as it's tracked in #3163
