### ISSUE TITLE
change tense requirement on pull request title

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#2785]
[This line](https://github.com/flix/flix/blob/ada298a631389e90f69e63d09fe130d294b2fa4b/docs/PULLREQUEST.md?plain=1#L5) of the pull request format
`The summary should be a single sentence in past tense (all lower case except for names).`
is a bit awkward for me to adhere to sometimes and I don't see what the reason for it is. [The reference in the file](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716) says present tense and I think that sometimes imperative sentences fit the PR best ("indent cases") and in that case the subject can also be left out while being grammatically correct ("I indented cases" require "I" and "indented cases" is not really a sentence).

I don't think its worth the effort to uphold this requirement so I feel it should be left out. The title should just be clear.

**Comment by magnus-madsen** [comment]
You are right. Let us change it. Will you update the wording and the examples?
