### ISSUE TITLE
Problem with Map-literals

### ISSUE THREAD

**Issue by jacopol** [flix/flix#2793]
This code is rejected by Flix:
```
def main(_args: Array[String]): Int32 & Impure = 
    let name = "name";
    let _map1 = Map#{"name"->4};
    let _map2 = Map#{name->4};
    0 as & Impure
```
The first singleton map is accepted (here the key is a concrete string "name"), 
but the second singleton map is refused (here the key is the identifier name).
The parsing seems to go wrong here:
```
>> Parse Error:
Invalid input '}', expected '_', Digit, '.', "i8", "i16", "i32", "i64" or "ii" (line 4, column 29):
    let _map2 = Map#{name->4};
                            ^
```

**Comment by magnus-madsen** [comment]
(I think there may be another ticket).

The problem is that `name -> 4` can be parsed as a function.

**Comment by jacopol** [comment]
I see. So for the moment, I need to write this as ``let _map2 = Map.insert(name,4,Map#{});``, right?

**Comment by mlutze** [comment]
`Map.singleton(name, 4)` for this particular case would be prettier :)

**Comment by magnus-madsen** [comment]
Whats the real solution? Should we switch the arrow to `=>`?

**Comment by mlutze** [comment]
That would work. We could also unsugar it a little by requiring tuples `Map#{("a", 1234), ("b", 5678)}` but that might be too heavy.

In Scala `->` is an infix function, which I think is a nice general solution. 

I'm especially interested in making it simply comma separated somehow because I still have hopes for desugaring `XYZ#{...}` into `XYZ.fromList(...)`.

**Comment by magnus-madsen** [comment]
@jacopol Do you have any opinion on the syntax?

**Comment by jacopol** [comment]
Not really: both key->value and key=>value are equally easy to type and read, I suppose. The variant with (key,value) is slightly more complicated. In particular when value has some brackets of its own, the readability gets worse.

**Comment by magnus-madsen** [comment]
I have not heard any objections, let us change the syntax to `Map#{123 => 456}`.

**Comment by magnus-madsen** [comment]
Here 

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Parser.scala#L954

**Comment by magnus-madsen** [comment]
@jaschdoc Ill give this one to you too :)

**Comment by magnus-madsen** [comment]
@ninaandrup Ill give this to you. Let me know if you have questions.
