### ISSUE TITLE
parsing and syntax-highlighting of print-patterns with map-literals

### ISSUE THREAD

**Issue by jacopol** [flix/flix#2798]
The last line of this program seems ungrammatical, but it is accepted by the flix-compiler
```
    let f = x->x;
    let _ = println("${Map.empty()}") as & Pure;
    let _ = println("${Map#{}}") as & Pure;
    let _ = println("${f(Map#{})}") as & Pure;
    let _ = println("${f(Map#{}}") as & Pure;
```
The output of this program is:
```
Map#{}
Map#{}
Map#{}
${f(Map#{}}
```
Also, the syntax-highlighting of all but the first let _ is a bit off
![highlight](https://user-images.githubusercontent.com/6709349/145423726-d0ea9984-762e-478e-a9fc-10eb1f854816.png)

**Comment by JonathanStarup** [comment]
@magnus-madsen i think the highlighting part is still an issue?
