### ISSUE TITLE
Can not use dot to access a lambda field in a record and call it

### ISSUE THREAD

**Issue by weihsiu** [flix/flix#2805]
i am not able to access a lambda field of a record and then call it in a single expression.  store the value of the lambda and then call it works fine though.

```
type alias Func = { func :: Int32 -> Int32 }

def test(f: Func): Int32 =
    f.func(1) // doesn't compile: Invalid input '('...
    // below works
    let func = f.func;
    func(1)
    
def main(_args: Array[String]): Int32 & Impure = 
    test({ func = i -> i + 1 }) |> println;
    0
```

**Comment by magnus-madsen** [comment]
I think we already have ticket about this somewhere... Trying to remember.

**Comment by magnus-madsen** [comment]
You can use `(f.func)(...)` as a work-around until we get it resolved.

**Comment by weihsiu** [comment]
Cool, thanks!  Closing for now.
