### ISSUE TITLE
Miscellaneous library issues

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2819]
- [x] `Array.foreachAccum` should not be public.
- [x] `Chain.flatMapHelper` should not be public.
- [x] `Channel.select` should not be public.
- [x] `Enviroment` --- all comments should be of the form `Returns XYZ`.
- [ ] `Fixpoint.Ast.VarSym` -- inline `compare` and write separate Eq instance. (Maybe needs @JonathanStarup help?)
- [ ] `Fixpoint.Ram.RamSym` - same comment as above.
- [x] `List.ap` has a TODO- remove it.
- [x] Inline `ToStringOps.arrayToStringHelper` where it is used.
- [x] `Prelude.on` - remove the code comment.
- [x] `Console.Ansi` should not be public.
- [x] Applicative should be public
- [x] Monad should be public
- [x] `Monoid.combine` fix documentation
- [x] `Set` The set argument should be renamed from `xs` to `s`. If there are two sets they should be `s1` and `s2`.
- [x] `List` The list argument should be renamed from `xs` to `l`. Similar to above.
- [x] `Nel` The list argument should be renamed from `xs` to `l`. Similar to above.
- [x] Rename `LazyList.lazyFilter -> filterL`
- [x] Rename `LazyList.lazyMap -> mapL`
- [x] Rename `LazyList.lazyZipWith -> zipWithL` (the reason for these renames is that otherwise the filter operations are not placed together in flixdoc nor in auto-complete).
- [x] `Set.count` should explain (using some standard phrase) that it is parallel when pure.
- [ ] List argument in `Result.foldLeftM` and `Result.foldRightM` should be called `l` not `xs`.
- [x] Mark `Object.toString` as `@Unsafe`.
- [x] Prelude `time` and `space` should be marked as `@Internal`.
- [x] `Option`, `List`, etc. etc. should be pub.

This should probably be done in several PRs.

**Comment by magnus-madsen** [comment]
@jaschdoc Ill give you this one :)

**Comment by jaschdoc** [comment]
> Rename LazyList.lazyFilter -> filterL
Rename LazyList.lazyMap -> mapL
Rename LazyList.lazyZipWith -> zipWithL (the reason for these renames is that otherwise the filter operations are not placed together in flixdoc nor in auto-complete).

Do you mean `Iterator.lazy*`?

**Comment by JonathanStarup** [comment]
why should Channel.select be private? If that should be private then the other methods should too since the whole class is internal?

**Comment by magnus-madsen** [comment]
> > Rename LazyList.lazyFilter -> filterL
> > Rename LazyList.lazyMap -> mapL
> > Rename LazyList.lazyZipWith -> zipWithL (the reason for these renames is that otherwise the filter operations are not placed together in flixdoc nor in auto-complete).
> 
> Do you mean `Iterator.lazy*`?

Yes, I think so.

**Comment by magnus-madsen** [comment]
> why should Channel.select be private? If that should be private then the other methods should too since the whole class is internal?

Maybe it should be `@Internal`. My point is that end-users should not start using it because then you cannot change it!

**Comment by JonathanStarup** [comment]
I think all the current channel functions should be internal then

**Comment by jaschdoc** [comment]
`>* Fixpoint.Ast.VarSym -- inline compare and write separate Eq instance. (Maybe needs atJonathanStarup help?)
>* Fixpoint.Ram.RamSym - same comment as above.

Where do you want to inline the `compare` function and how should `VarSym` and `RamSym` be compared?

**Comment by magnus-madsen** [comment]
Thats confusing. What I mean is:

- Implement the Eq type class directly.
- Implement the Order type class directly.

Dont rely on an external function.

**Comment by jaschdoc** [comment]
Ah thanks, that makes sense.
