### ISSUE TITLE
Option doesn't not work well with pipelines

### ISSUE THREAD

**Issue by sveri** [flix/flix#2820]
As discussed and changed in https://github.com/flix/flix/issues/2801it I would suggest to change the parameter of Option.getWithDefault too.

**Comment by magnus-madsen** [comment]
Change:

- [ ] `Option.getWithDefault` and 
- [ ] `Option.withDefault` 

to be consistent with their friends in `Result`.

**Comment by magnus-madsen** [comment]
The same also applies to `Validation.flix`.
