### ISSUE TITLE
Redesign and simplify `Console` API

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2823]
What about:

- `Console.readLine` - (uses `java.io.Console`).
- `Console.print` - (uses `System.out`).
- `Console.println` - (uses `System.out`).
- `Console.flush` - (uses `System.out`).

Drop everything else. 

What about the color support? How can simplify and still keep that? Proposal:

- Keep `Console/Color.{red, green ...}`
- Add `Console/Color.{bgRed, bgGreen, etc.}`
- Drop the color enums (or make them private?)
- Add `Console/Color.hex`
- Add `Console/Color.rgb`
- Keep supporting private infrastructure.
- Add an example.

What about stdin? I suggest

- Add `System/stdIn()` which returns an iterator over a result of strings.

**Comment by magnus-madsen** [comment]
@mlutze @JonathanStarup Thoughts?

**Comment by magnus-madsen** [comment]
See also e.g. https://github.com/chalk/chalk

**Comment by mlutze** [comment]
Should `print*` flush automatically? Buffered output can be unintuitive and usually if we want high-performance output we'd use an output stream instead.

I think color support is nice, but I don't see it as a core feature; in most languages it would be a third-party library. How does color support compare with the "Small, but comprehensive standard library" principle?

**Comment by magnus-madsen** [comment]
> Should `print*` flush automatically? Buffered output can be unintuitive and usually if we want high-performance output we'd use an output stream instead.

We can, but it would be non-standard (but maybe all those implementations are wrong.)

> I think color support is nice, but I don't see it as a core feature; in most languages it would be a third-party library. How does color support compare with the "Small, but comprehensive standard library" principle?

Indeed, but `chalk` is one of the most popular libraries for JavaScript. 

Moreover, people will probably start by writing small Flix terminal apps, so lets give them some call!

**Comment by JonathanStarup** [comment]
I think access to system in should be supported still. either by static generated class or a wrapper of buffered reader that says "please dont use me multiple places". Even if none of those are the best way, I think there should be a flix thing instead of people doing one of the above in java code.

**Comment by magnus-madsen** [comment]
I made some progress in #2846. The tasks are now:

- [ ] Implement `Console.readLine()`.  // uses java.io.Console
- [ ] Implement `Console.print()`.   // uses java.io.Console
- [ ] Implement `Console.printLine()`. // uses java.io.Console
- [ ] Implement `System/StdIn.readLines()`. // uses System.stdin
- [ ] Expand `Console` with helper functions for all the colors in `Ansi`.
- [ ] Add background colors and helper functions for background colors.

**Comment by magnus-madsen** [comment]
@JonathanStarup Do you want to take a step at the first 3-4?

I think the colors can be done by student programmer.

**Comment by JonathanStarup** [comment]
Yes. good idea with `readlines`.
