### ISSUE TITLE
How tell signatures apart from defs in type classes?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2824]
Here is what we show for `Eq`:

![image](https://user-images.githubusercontent.com/2287953/145776981-77455f76-8e05-4545-bb99-5fa34f582cdd.png)

How can we distinguish between `eq` (which is "abstract") and `neq` which has a default implementation?

Suggestions:

- Do nothing. 
- Show `def neq(...): Bool = ...` where the `= ...` is what tells you that it has an implementation.
- Add a `default` keyword and require it on non-signatures. (Or alternatively an annotation?)
- Add a `abstract` keyword and require it on signatures.

I am leaning towards doing nothing or `default`.

**Comment by magnus-madsen** [comment]
@mlutze Ping :)

**Comment by mlutze** [comment]
I don't see a major advantage to requiring a `default` keyword. The goal is mainly for Flixdoc, right? What if we put the signatures in different groups, like `Abstract Signatures` and `Implemented Signatures` (or a better word than "implemented")?

**Comment by magnus-madsen** [comment]
OK, I like that.

**Comment by magnus-madsen** [comment]
Need a good name

**Comment by magnus-madsen** [comment]
What about just:

```
Signatures:

...


Definitions:
...
```

and internally (in JSON) they are called `defs` and `sigs`.

**Comment by mlutze** [comment]
> What about just:
> 
> ```
> Signatures:
> 
> ...
> 
> 
> Definitions:
> ...
> ```
> 
> and internally (in JSON) they are called `defs` and `sigs`.

This seems reasonable. Could we have some hovertext or other side-documentation that says what the difference is?

**Comment by magnus-madsen** [comment]
> 

I think this belongs somewhere else.
