### ISSUE TITLE
Reflecting on Annotations and Modifiers

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2826]
What they are (my current view- need to write it up):
- A **modifier** is part of the language itself. A modifier typically impacts the meaning of a program. Incorrect use of modifiers may prevent compilation or even break a program. Modifiers cannot be declared by the user. There is simply a fixed set.
- An **annotation** is essentially a form of documentation. Unlike a comment an annotation has a fixed name and semantics (set by us). Annotations are not user-definable (because that could lead to multiple annotations that mean the same thing and it could also lead to confusion about what an annotation means). Annotations serve as a compress way to represent information.

In this ticket I want to cover our current annotations and modifiers and discuss what should be removed and what should be added:

Annotations:
- ~[x] `@Benchmark` - eventually remove~
- [x] `@Deprecated`  - keep (and allow version/string). Add support to api.flix.dev
- [x] `@Law` - (internal annotations, but I guess we could also make it external)?
- [x] `@Lint` - remove
- ~[x] `@Test` - eventually remove~
- [x] `@LazyWhenPure` - keep
- [x] `@ParallelWhenPure` - keep
- [x] `@Time` - undecided
- [x] `@Space` - undecided

In addition, I would like to propose:

- [x] `@Parallel` (this function uses parallel evaluation).
- [x] `@Lazy` (this function uses lazy evaluation).
- [x] `@Unsafe` (Use of this function is unsafe and discouraged. The programmer accepts responsibility. We would use this for dangerous internal functions, e.g. `Unsafe.println` or similar). 
- ~[x] `@Hide` (an alternative to `@Unsafe` -- this hides the function, regardless of its visibility from api.flix.dev) Why would this be necessary? Sometimes we have public functions (e.g. from the Datalog engine) that we use in different places, but nevertheless would like to hide. Not sure, the argument here is weak.~
- [x] `@Experimental` (this functionality is under development, it may be removed or changed in the future without warning). We would use this for all our experimental features before they enter Flix proper.

Modifiers:
- `inline` - remove (unless it has an internal use case???)
- `lawless` - keep
- `override` - keep, definitely.
- `public` - keep, definitely.
- `scoped` - work in progress.
- `sealed` - keep, definitely.
- `synthetic` - use unclear? 
- `unlawful` - maybe remove?

I don't have any suggestions for new modifiers.

**Comment by JonathanStarup** [comment]
It's probably too much but it feels like general documentation also fits the annotation pattern.
```
@doc("Returns the inverse matrix ... ")
```

**Comment by mlutze** [comment]
I don't think `@Law` is even used internally.

I'm unconvinced by `@Hide`. If a user is not supposed to be able to access something, it seems like it should be enforced by a real language visibility level (`private`, etc.).

I agree that `unlawful` should be removed. We're moving in the direction of saying that an instance _really_ has to follow these laws, and `unlawful` just feels like a cheat to be unprincipled.

**Comment by magnus-madsen** [comment]
Added `@Experimental`, `@Parallel`, `@Lazy`, and `@Unsafe`. 
Removed `@List` and `@Law`. (We have the `law` keyword.)
Dropped the idea of `@Hide`. Let us use visibility instead!

For the modifiers, `synthetic` seems useful. So let us keep it. 

I want to remove:

- [ ] inline
- [ ] unlawful

The latter requires some refactoring. Maybe @mlutze can look at it at somepoint.

**Comment by mlutze** [comment]
Does `unlawful` really require refactoring? I don't think we actually have any checks for it anywhere.

**Comment by magnus-madsen** [comment]
> Does `unlawful` really require refactoring? I don't think we actually have any checks for it anywhere.

 I think I saw some code when I tried to remove it.

**Comment by magnus-madsen** [comment]
@mlutze This function in `Solver.flix`:

```
    pub def projectInto3[f: Type -> Type, t1: Type, t2: Type, t3: Type](p: PredSym, ts: f[(t1, t2, t3)]):
        Datalog[Boxed] with Boxable[t1], Boxable[t2], Boxable[t3], Foldable[f] =
```

is part of the Flix standard library and should never be called by any Flix users. It is used by the Flix `Lowering` phase.

The problem is that if `projectInto3` is private then it is flagged as unused (because it is). It is only after `Lowering` it is used.

How do we fix this?

Either keep it `pub` and add `@Hide` or make it private and add `@IgnoreUnused`? or ??? or ???

**Comment by mlutze** [comment]
Maybe we need an `internal` visibility modifier that entirely prevents use in source code, except by other `internal` functions?

**Comment by JonathanStarup** [comment]
> [...] or make it private and add @IgnoreUnused [...]

Doesn't lowering call it from places that requires pub?

**Comment by magnus-madsen** [comment]
> > [...] or make it private and add @IgnoreUnused [...]
> 
> Doesn't lowering call it from places that requires pub?

Yes, but the checks happen before lowering, so you can break the rules.

**Comment by magnus-madsen** [comment]
Added `@Internal`. Removed `inline` and `unlawful`.
