### ISSUE TITLE
Disallow keywords as variable and type variable names

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#2828]
This works fine at the moment but it feels wrong.
```flix
pub def f(): Unit & Impure =
    let if = 2;
    println(if);
    if (true) println() else println();
    ()
```
I think it would be sensible to disallow keywords as variable/patterns and it would also help the parser backtrack and give better errors.

**Comment by mlutze** [comment]
One argument against this is that we still experiment quite a bit with syntax, so having the list of valid variable names change with each new feature we're testing would be yet another thing for users to have to manage.

I'm not sure whether that's a strong enough reason though. Certainly a variable called "if" is begging for trouble.

**Comment by jaschdoc** [comment]
As an aside, would it make sense to maintain a list of keywords used in master? This would allows us to slowly reserve the ones that are stable and experiment with others. Plus there's a nice side effect of being able to easily set up some keyword highlighting in IntelliJ :+1:

**Comment by magnus-madsen** [comment]
I don't have a strong opinion, but some languages have experimented with "soft keywords" which is essentially what we have.

**Comment by magnus-madsen** [comment]
This program is also fun:

```
pub def f(): Unit & Impure =
    let if = x -> println(x);
    if(123);
    ()
```

**Comment by magnus-madsen** [comment]
Question: Where would keywords be disallowed? Variables? What about type variables? What about functions? What about enums?

**Comment by JonathanStarup** [comment]
Things related to expressions first of all but I think that it's easier to keep track of the rules (as a flix user) if they are disallowed everywhere.

**Comment by magnus-madsen** [comment]
I suggest:

- [ ] Ban keywords as variable names.
- [ ] Ban keywords as type variable names.
- [ ] Perform these checks in the Weeder (to give nice error messages).

**Comment by JonathanStarup** [comment]
There is also incentive to disallow them in the parser itself because it allows the parser to give better error locations and possibly messages

**Comment by magnus-madsen** [comment]
> There is also incentive to disallow them in the parser itself instead of the weeder because it allows the parser to give better error locations and possibly messages

I am not sure. My experience has been the opposite. Consider this:

```
def main(_args: Array[String]): Int32 & Impure = 
    println("Hello World!");
    let x: float32 = ???;
    0
```

which gives:

![image](https://user-images.githubusercontent.com/2287953/145966388-20ca3a38-d435-4d8f-a2ee-48d363643372.png)

that seems very precise to me.

**Comment by JonathanStarup** [comment]
Yea that's true when the parser doesn't fail. A program like this
```
def g(): Unit = ();
pub def f(): Unit = ()
```
says very nicely that pub is undefined but if the parser fails on something like
```
def g(): Unit = ();
def f(): Unit = ()
```
Is now says 
```
Invalid input "):", expected FormalParam or '=' (line 2, column 7):
def f(): Unit = ()
      ^
```

**Comment by magnus-madsen** [comment]
We are in the process. This is being tracked in another ticket.
