### ISSUE TITLE
Add `@Parallel` annotations to `RedBlackTree`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2833]

**Comment by jaschdoc** [comment]
I think you can close this issue. As far as I can see, the relevant functions both have `@Parallel` and `@ParallelWhenPure` annotations.
We should maybe discuss (in another thread) which functions should be public / private (`seqCount, parCountSeq, parCount, count`). There are some inconsistencies at the moment (like `map` and `count` having different access modifiers on their respective helper functions).

**Comment by magnus-madsen** [comment]
OK. Will you open a ticket?
