### ISSUE TITLE
Add `@Lazy` annotations to `DelayMap` and `LazyList`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2834]
For example, `append` should be marked as `@Lazy`, but `memberOf` should not. 

The `@Lazy` annotation means "this function may use lazy evaluation" (i.e. its computational cost and time is deferred).

**Comment by magnus-madsen** [comment]
What about adjust and friends in DelayMap. Should they be `@Lazy` or `@LazyWhenPure`? :)

**Comment by magnus-madsen** [comment]
Maybe same comments about insert and friends?

**Comment by jaschdoc** [comment]
I'm not sure `insert` is lazy. Sure, the value is lazy but the value is evaluated before being passed to `insert`.
