### ISSUE TITLE
Add capability-safety to polymorphic effects?

### ISSUE THREAD

**Issue by kephas** [flix/flix#2837]
Pure code is guaranteed to have *zero* side effect, but Impure code could potentially have *any* side effect.

There could be a middle ground, where a function is guaranteed to only have side effects made possible by the authority it receives in its arguments, a.k.a. object-capabilities (cf. [Robust Composition](http://erights.org/talks/thesis/index.html), Mark S. Miller's PhD thesis on the subject).

```flix
def read(in: ReadCap): Result[String, String] & OcapImpure
```

**Comment by kephas** [comment]
Is there a way to help?

**Comment by magnus-madsen** [comment]
Depends on your background and how much time you are willing to commit. Stuff is a bit complicated. Send me a private message on gitter and we can talk.

**Comment by magnus-madsen** [comment]
We are working on "something related to this" in https://github.com/flix/flix/issues/3000
