### ISSUE TITLE
Improve color support for `Console`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2853]
- [ ] Ensure we have helper functions for all colors in `Ansi`.
- [ ] We have functions like `green`, but we also need functions like `greenBright`.
- [ ] Extend the `Ansi` enum with background colors (E.g. BackgroundGreen).
- [ ] Add helper functions for the above named `bgGreen` etc.
- [ ] Add an example.

The above comments probably make more sense after reading `Console.flix`.

You can test by `println(Console.green("this is green"))` if you run in a real terminal (not inside IDEA).

**Comment by ninaandrup** [comment]
Where should I add the example? And should it just demonstrate how to use the colors?

**Comment by magnus-madsen** [comment]
Here: `https://github.com/flix/flix/tree/master/examples`

Maybe something that prints a colorful message.

**Comment by magnus-madsen** [comment]
You can look at the other examples to get an idea for the their size. Probably aim for like 8-10 lines.

**Comment by ninaandrup** [comment]
> You can look at the other examples to get an idea for the their size. Probably aim for like 8-10 lines.

Yes, makes sense

**Comment by magnus-madsen** [comment]
Next:

- [ ] bright colors
- [ ] take an argument `a` with a ToString instance.
- [ ] underline and bold
- [ ] add a `hex` function that takes a string e.g. "#CC33AE".

**Comment by magnus-madsen** [comment]
- [ ] Decide whether to introduce `Console.Color` namespace.
- [ ] Decide whether to rename e.g. `green` to `fgGreen`.

**Comment by magnus-madsen** [comment]
@ninaandrup I lost my overview. Can you make a list of what remains? This ticket seems to have various issues and then there is #2869

**Comment by ninaandrup** [comment]
> @ninaandrup I lost my overview. Can you make a list of what remains? This ticket seems to have various issues and then there is #2869

Still missing:

- [ ] take an argument a with a ToString instance (#2869)
- [ ]  bold (& underline)
- [ ]  add a hex function that takes a string e.g. "#CC33AE".
- [ ] Rename e.g. `green` to `fgGreen`.
- [ ] Maybe introduce `Console.Color` namespace.

**Comment by magnus-madsen** [comment]
OK, I definitely think we should do the first 3 (except underline is apparently not standard, so let us skip it).

I don't know about 4 or 5. What do you think?

**Comment by ninaandrup** [comment]
> OK, I definitely think we should do the first 3 (except underline is apparently not standard, so let us skip it).
> 
> I don't know about 4 or 5. What do you think?

I think it would be nice to have some distinction between `bgGreen` and `green`. But on the other hand I think `green` is better than `fgGreen`, because fg is a bit confusing. Maybe something like `textGreen` would make more sense. But then I do not know if simply `green` is fine?

I think I have to look at the code a bit more to decide if we should introduce `Console.color`. What are your considerations?

**Comment by magnus-madsen** [comment]
> > OK, I definitely think we should do the first 3 (except underline is apparently not standard, so let us skip it).
> > I don't know about 4 or 5. What do you think?
> 
> I think it would be nice to have some distinction between `bgGreen` and `green`. But on the other hand I think `green` is better than `fgGreen`, because fg is a bit confusing. Maybe something like `textGreen` would make more sense. But then I do not know if simply `green` is fine?
> 
> I think I have to look at the code a bit more to decide if we should introduce `Console.color`. What are your considerations?

OK. Let us keep what we have for now. We will save an eventual rename / color namespace for later.

**Comment by ninaandrup** [comment]
> > > OK, I definitely think we should do the first 3 (except underline is apparently not standard, so let us skip it).
> > > I don't know about 4 or 5. What do you think?
> > 
> > 
> > I think it would be nice to have some distinction between `bgGreen` and `green`. But on the other hand I think `green` is better than `fgGreen`, because fg is a bit confusing. Maybe something like `textGreen` would make more sense. But then I do not know if simply `green` is fine?
> > I think I have to look at the code a bit more to decide if we should introduce `Console.color`. What are your considerations?
> 
> OK. Let us keep what we have for now. We will save an eventual rename / color namespace for later.

Sounds good!

**Comment by magnus-madsen** [comment]
@ninaandrup  Do you think we can close this? Are there more things to be done?

**Comment by ninaandrup** [comment]
> @ninaandrup Do you think we can close this? Are there more things to be done?
We did have this to decide

> [ ] Decide whether to introduce `Console.Color` namespace.

But maybe it can be for another issue?

**Comment by magnus-madsen** [comment]
OK, lets leave it for now.
