### ISSUE TITLE
Add `Foldable.foreach` and use it in `File.appendLines`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2857]

**Comment by ninaandrup** [comment]
Addition to ticket:
Use `Foldable.foreach` in:

- [ ] `File.writeLines`
- [ ] `File.writeBytes`
- [ ] `File.appendBytes`

**Comment by magnus-madsen** [comment]
Done?

**Comment by ninaandrup** [comment]
> Done?

Yes :)
