### ISSUE TITLE
Restructure concurrency primitives

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2868]
Move:

- [ ] `Condition-> Concurrent.Condition`
- [ ] `ReentrantLock` -> Concurrent.ReentrantLock`
- [ ] `Ticker` -> Concurrent.Channel.Ticker`
- [ ] `Timer` -> Concurrent.Channel.Timer`
- [ ] `Channel -> Concurrent.Channel`.

This means both files and namespaces.

**Comment by magnus-madsen** [comment]
@JonathanStarup Are you okay with these changes?

**Comment by JonathanStarup** [comment]
maybe Concurrency instead of concurrent? but it looks good

**Comment by magnus-madsen** [comment]
> maybe Concurrency instead of concurrent? but it looks good

I thought about it, but all other languages seem to use `concurrent`, right? Scala, Java?

**Comment by JonathanStarup** [comment]
hmm there seems to be adjectives/verbs/nouns/... in java. yeah I don't know then. I can't find style guides mentioning anything other than prefixes or capitalization.

**Comment by ninaandrup** [comment]
> 

Does this mean making a folder for the flix files? Just to make sure

**Comment by magnus-madsen** [comment]
> > 
> 
> Does this mean making a folder for the flix files? Just to make sure

Folders and moving files around.
