### ISSUE TITLE
Simplify `StringBuilder`?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2870]
We currently have:

```
pub def appendInt32!(sb: StringBuilder, i: Int32): Unit & Impure =
pub def appendInt64!(sb: StringBuilder, i: Int64): Unit & Impure =
```

any reason not just to have:

```
pub def append!(sb: StringBuilder, x: a): Unit & Impure with ToString[a] =
```

**Comment by magnus-madsen** [comment]
@stephentetley What do you think?

**Comment by stephentetley** [comment]
Yes, that certainly makes sense.

**Comment by ninaandrup** [comment]
There is already
```
pub def append!(sb1: StringBuilder, sb2: StringBuilder): Unit & Impure =
```
Should this have a new name? Or let the new `append!` have another name?

**Comment by ninaandrup** [comment]
And should I delete `appendString!`, since this can use the new `append!`?

**Comment by magnus-madsen** [comment]
I think you can leave `appendString` for now. As for the existing `append!` with sb1 as a StringBuilder, I would say too bad. We change it. If you want to append two string builders you have to do it yourself.

**Comment by ninaandrup** [comment]
Should as many functions as possible? Like `appendFloat32!` even though it does not use `appendString` as it is implemented now?

**Comment by magnus-madsen** [comment]
Yes, delete `appendFloat32` etc.

**Comment by magnus-madsen** [comment]
Fixed in master.
