### ISSUE TITLE
Add `Commutative` and `Associative` annotations?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2871]
Or some other mechanism. These are just really very common laws that apply to functions.

**Comment by mlutze** [comment]
I think it would be nice to be able to apply arbitrary laws to functions. But I guess this runs into the homemade annotations problem described previously.

**Comment by magnus-madsen** [comment]
In some sense various type classes capture this notion.

**Comment by magnus-madsen** [comment]
Maybe in the future.
