### ISSUE TITLE
Add `toMapWith`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2872]
Add a function:

```
pub def toMapWith(f: a -> b, s: Set[a]): Map[a, b] = ???
```

to:

- [ ] `List`
- [ ] `Nel`
- [ ] `Set`
- [ ] `Option`
- [ ] `Result`
- [ ] `Foldable`

Add a few test cases for each.

**Comment by magnus-madsen** [comment]
Done?

**Comment by ninaandrup** [comment]
> Done?

Yes :-)
