### ISSUE TITLE
Extend `Foldable` with extra conversion functions

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2873]
Extend `Foldable` with:

- [ ] `toChain`
- [ ] `toMutDeque`
- [ ] `toMutMap`
- [ ] `toMutSet`
- [ ] `toLazyList`
- [ ] ...

Add tests for each function.

**Comment by magnus-madsen** [comment]
What about regions? I guess they will need them as arguments.

**Comment by magnus-madsen** [comment]
All of these functions should take a region parameter.

**Comment by magnus-madsen** [comment]
(Well except toLazyList which does not require it).

Also my list is not complete.

**Comment by ninaandrup** [comment]
The only collections left are `MultiMap` and `RedBlackTree`. We only have `Map.toMultiMap` at the moment, and no `toRedBlackTree` functions at all. Do we want these in `Foldable`?

**Comment by magnus-madsen** [comment]
> The only collections left are `MultiMap` and `RedBlackTree`. We only have `Map.toMultiMap` at the moment, and no `toRedBlackTree` functions at all. Do we want these in `Foldable`?

OK, then I think we are done :)
