### ISSUE TITLE
`eq` and `sameElements`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2874]
For each of the following:

- `Array`
- `MutDeque`
- `MutList`
- `MutSet`
- `MutMap`

refactor:

- [ ] such that it has a `sameElements`
- [ ] does not have an `eq`

To avoid confusion, I have decided that `eq` should "reserved" for things that implement `Eq`. Calling the degraded version of `eq` for `sameElements` matches Scala and draws attention to the fact that this is not just an ordinary eq.

**Comment by ninaandrup** [comment]
Both `Array` and `MutList` have both `eq` and `sameElements`. Should I just keep `sameElements` and delete `eq`?

And the rest have neither. Should I add a `sameElements` for these?

**Comment by magnus-madsen** [comment]
> Both `Array` and `MutList` have both `eq` and `sameElements`. Should I just keep `sameElements` and delete `eq`?

Yes

 
> And the rest have neither. Should I add a `sameElements` for these?

Yes

**Comment by magnus-madsen** [comment]
@ninaandrup Done or not yet?

**Comment by ninaandrup** [comment]
> @ninaandrup Done or not yet?

I need to make sameElements functions for `MutDeque`,  `MutSet` and `MutMap`, but I will get to it now.

**Comment by magnus-madsen** [comment]
@ninaandrup Can we close this?

**Comment by ninaandrup** [comment]
> @ninaandrup Can we close this?

Yes :-)
