### ISSUE TITLE
Ensure that every collection has a `foreach`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2875]
- [ ] Option
- [ ] Result
- [ ] List
- [ ] Nel
- [ ] Chain
- [ ] Set
- [ ] Map
- [ ] Array
- [ ] MutDeque
- [ ] MutList
- [ ] MutSet
- [ ] MutMap
- [ ] LazyList
- [ ] DelayMap

**Comment by magnus-madsen** [comment]
@ninaandrup I think you can also take a look at this :)

**Comment by ninaandrup** [comment]
Already has a `foreach`:
- Option
 - Result
 - List
 - Nel
 - Chain
 - Set
 - Map
 - Array
 - MutList
 - MutSet
 - MutMap
- DelayMap
 
Missing a `foreach`
- MutDeque
- LazyList

**Comment by magnus-madsen** [comment]
Next thing: 

Go through the library by searching for uses of `foldLeft` and see if there are some uses of `foldLeft` where we might as well use `foreach`? You can see this if for example a fold starts with the unit value `()` or seems to ignore the "acc" parameter.

Does it make sense?

**Comment by ninaandrup** [comment]
Uses of `foldLeft` that should be `foreach`

- [ ] `Array.joinWith`

Not done yet.

**Comment by ninaandrup** [comment]
I think everything is done now.
