### ISSUE TITLE
Add `foldRightLazy`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2877]
Add a function:

```
// TODO: Add right after foldRight in the respective namespace.
// TODO: Add documentation.
pub def foldRightL(f: (a, Lazy[b]) -> b & , s: b, l: List[a]): b & ef = 
    def loop(xs) = match xs {
        case Nil     => s
        case y :: ys => f(y, lazy loop(ys))
    };
    loop(l)
```

to all of these namespaces:

- [x] List
- [x] Nel
- [x] Set
- [x] Map
- [x] Option
- [x] Result
- [x] MutList
- [x] MutSet
- [x] MutMap
- [x] LazyList
- [x] DelayMap

Ensure that there are 3-4 unit tests for each function (as appropriate).

Then:

- [ ] Investigate if `Foldable` can support a foldRightL expressed in terms of foldRight. I am not sure...

This PR can be broken down into smaller PRs.

**Comment by magnus-madsen** [comment]
@nicdard Will take a look at this.

**Comment by nicdard** [comment]
```
pub def foldRightL(f: (a, Lazy[b]) -> b & ef, s: b, l: List[a]): b & ef =
        def loop(xs) = match xs {
            case Nil     => s
            case y :: ys => f(y, lazy loop(ys))
        };
        loop(l)
```

With the previous implementation, when trying to run the compiler I get this error:
```
The inferred effect: 'Pure' cannot be generalized to 'ef'.

689 |     pub def foldRightL(f: (a, Lazy[b]) -> b & ef, s: b, l: List[a]): b & ef =
                  ^^^^^^^^^^
                  unable to generalize the effect.
```

I tried multiple things, also an approach similar to what is currently implemented for `foldRight` with an helper function but it doesn't mix well with `Lazy`

Since I am very fresh, do you have any hint?

**Comment by nicdard** [comment]
Thinking about it, why do you want the signature to be:

```pub def foldRightL(f: (a, Lazy[b]) -> b & , s: b, l: List[a]): b & ef = ```

to work on an infinite list shouldn't the `l: List[a]` be lazy?

**Comment by magnus-madsen** [comment]
Ah yes, I think the argument has to be pure, i.e. f should be pure.

**Comment by magnus-madsen** [comment]
@nicdard There will be an implementation for all kinds of data structures, both list and lazy list.

foldRightL is for infinite things, but also for things with early termination. E.g. if you multiply by zero.

**Comment by nicdard** [comment]
> @nicdard There will be an implementation for all kinds of data structures, both list and lazy list.
> 
> foldRightL is for infinite things, but also for things with early termination. E.g. if you multiply by zero.

Thanks for the guidance!

**Comment by nicdard** [comment]
Stands `Nel` for non-empty list?

**Comment by magnus-madsen** [comment]
> Stands `Nel` for non-empty list?

That is right
