### ISSUE TITLE
Extra lines in error messages with source code 

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2880]
```
>> Unable to unify the Boolean formulas: 'print' and ''0 ∧ ('1 ∧ '2)'.

16 |>     let f = x -> {

17 |>         doPrint();

18 |>         doRead();

19 |>         doWrite();

20 |>         x
```

**Comment by jaschdoc** [comment]
Could you give a brief explanation of the issue? Not quite sure I follow what the exact problem is

**Comment by magnus-madsen** [comment]
Expected:

```
16 |>     let f = x -> {
17 |>         doPrint();
18 |>         doRead();
19 |>         doWrite();
20 |>         x
```

**Comment by jaschdoc** [comment]
Could you paste a minimal program that causes this?

**Comment by magnus-madsen** [comment]
Here is one:

```
pub def foo(): Unit =
    true
    + 
    42
```

**Comment by jaschdoc** [comment]
> Here is one:
> 
> ```
> pub def foo(): Unit =
>     true
>     + 
>     42
> ```

Hmm this produces
```
>> Unable to unify the types: 'Bool' and 'Int32'.

13 |>     true
14 |>     +
15 |>     42

mismatched types.

Type One: a -> a -> a
Type Two: Bool -> Int32 -> t884230 & b884231
```

How do I produce a `MismatchedBools` type error?

**Comment by magnus-madsen** [comment]
Oh. Maybe my version is broken then. let me investigate locally.

**Comment by magnus-madsen** [comment]
On master:

![image](https://user-images.githubusercontent.com/2287953/147823942-c6946b55-06de-43da-bc7f-bc1a4994d0e8.png)

**Comment by magnus-madsen** [comment]
Hmm. But it looks right in the terminal. How can that be?

**Comment by jaschdoc** [comment]
Yeah that's weird. Maybe the `currentline` has a windows line separator? My error was also produced by the compiler built from master

**Comment by jaschdoc** [comment]
Hmm I spent an hour fighting Windows and finally managed to build the compiler from master. I still get the same error message as I did before (with no extra newlines). I'm running OpenJDK 17.0.1

**Comment by magnus-madsen** [comment]
Also inside VSCode?

**Comment by jaschdoc** [comment]
Yes, same output window as your screenshot

**Comment by magnus-madsen** [comment]
Ill check on a different computer tomorrow.
