### ISSUE TITLE
Long comments

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2901]
How should we format long comments that are broken in the Flix source code:

![image](https://user-images.githubusercontent.com/2287953/147262010-639759ee-1905-464c-bae8-286c2d94e9e5.png)

Suggestion: 

- We kill newlines unless there are two back-to-back. (can be implemented in the Weeder)

**Comment by magnus-madsen** [comment]
We could also adopt (a limited form) of markdown and use https://github.com/remarkjs/react-markdown

**Comment by magnus-madsen** [comment]
Using react-markdown:

![image](https://user-images.githubusercontent.com/2287953/147264428-2876a074-38e5-44e2-a54d-a095ce2c63b7.png)

We might still want to do the processing describe above.

**Comment by JonathanStarup** [comment]
> * We kill newlines unless there are two back-to-back. (can be implemented in the Weeder)

Should it be the weeders responsibility to interpret the text? Shouldn't that just be handled externally. You can format html text or md or whatever in your documentation program.

**Comment by magnus-madsen** [comment]
We do as @JonathanStarup suggests and keep what we have in the compiler.
