### ISSUE TITLE
Introduce `new` operator to allocate new (mutable) data structures in regions

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2904]
Allow us to write:

```scala
new MutSet[t...]
```

as sugar for the function call:

```scala
Newable.new(r): MutSet[t..., r] // where `r` is some region.
```

The idea of the `new` expression is that it would automatically try to pickup the region from the closet scope.

**Comment by magnus-madsen** [comment]
We can now write: 

```
let s = new MutSet(r);
```

@jaschdoc Can I ask you to use that in `MutSet` tests?

**Comment by magnus-madsen** [comment]
(NB: The "MutSet" part is not yet used)

**Comment by magnus-madsen** [comment]
@nicdard Could I ask you to add `new` as a keyword to VSCode? I think it should be the same color as other keywords, e.g. let, def etc.

**Comment by nicdard** [comment]
Sure :)

**Comment by nicdard** [comment]
https://github.com/flix/vscode-flix/pull/189

**Comment by magnus-madsen** [comment]
Fixed in master.
