### ISSUE TITLE
Fix access modifiers for `RedBlackTree` parallel functions

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#2909]
As mentioned in #2833, the access modifiers for helper functions for parallel function in `RedBlackTree` are inconsistent with each other. We should decide exactly which ones are public and which ones are not. I think all the helper functions should be private (`parMap`, `parMapSeq`, `seqMap`) and simply only have the `map` interface.

**Comment by magnus-madsen** [comment]
Agreed. Everything private.

**Comment by jaschdoc** [comment]
Will be fixed by #2923

**Comment by jaschdoc** [comment]
I think we fixed this already?
