### ISSUE TITLE
predicate lower case error messages

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#2919]
With the following program:
```flix
def main(_args: Array[String]): Int & Impure =
    let _p = #{
        A(x) :- b(x).
        C(12) :- d(x).
    };
    println("Hello World!");
    0
```
gives these errors
![image](https://user-images.githubusercontent.com/32037926/147412407-eda73ece-e20e-4856-b934-4560195ec421.png)
and `e(x) :- F(x)` is just a parser error. I think these errors should mention that predicates cannot be lowercase

**Comment by magnus-madsen** [comment]
We can revisit with the new parser.
