### ISSUE TITLE
Applicative - product3, product4 and product5 ?

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#2935]
Now we have `product` in Applicative (which is `product2`) should we add versions for 3-, 4- and 5-tuples so we match the arity we have for the `liftA` functions?

I don't propose we should do anything about selecting from `product3`, `product4` and `product5` (vis `productLeft` and `productRight` for `product(2)`) as the combinators `(<*)` and `(*>)` let us do that.

~~~

pub def product3(fa: m[a], fb: m[b], fc:m[c]): m[(a, b, c)] with Applicative[m] =
    Applicative.liftA3((a, b, c) -> (a, b, c), fa, fb, fc)

// etc.

~~~

**Comment by magnus-madsen** [comment]
We can yes. Going to 5 should be no problem.

**Comment by stephentetley** [comment]
Thanks Magnus, I'll make a PR.

**Comment by magnus-madsen** [comment]
We fixed this right?

**Comment by stephentetley** [comment]
Yes, its fixed!
