### ISSUE TITLE
Mismatched signature with effects

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2938]
```
pub enum ReaderEff[ef: Bool, i: Type, a: Type] {
    case ReaderEff(i -> a & ef)
}

instance Functor[ReaderEff[ef, i]] { 
    pub def map[a: Type, b: Type, i: Type, ef: Bool](f: a -> b & ef, x: ReaderEff[ef, i, a]): ReaderEff[ef, i, b] & ef = ??? as & ef
}
```

```
Mismatched signature 'map' required by class 'Functor'.

6 |     pub def map[a: Type, b: Type, i: Type, ef: Bool](f: a -> b & ef, x: ReaderEff[ef, i, a]): ReaderEff[ef, i, b] & ef = ??? as & ef

                ^^^
                mismatched signature.

Expected scheme: ∀(ef, i, a, ef, b). a -> b & ef -> ReaderEff[ef, i, a] -> ReaderEff[ef, i, b] & ef with Functor[ReaderEff[ef, i]]
Actual scheme:   ∀(a, b, i, ef, ef, i). a -> b & ef -> ReaderEff[ef, i, a] -> ReaderEff[ef, i, b] & ef with Functor[ReaderEff[ef, i]]

Explanation:
Tip: Modify the definition to match the signature.
```

**Comment by mlutze** [comment]
_copy-pasted from PR_

> Minimal broken program:
> 
> ```
> pub enum ReaderEff[ef: Bool, i: Type, a: Type] {
>     case ReaderEff(i -> a & ef)
> }
> 
> instance Functor[ReaderEff[ef, i]] { 
>     pub def map[a: Type, b: Type, i: Type, ef: Bool](f: a -> b & ef, x: ReaderEff[ef, i, a]): ReaderEff[ef, i, b] & ef = ??? as & ef
> }
> ```
> 
> @mlutze Maybe you have some insight on this?

I think it might be because the`Functor` class expects the `ef` of the function to be independent from the functor argument `x`, but since `ef` is also in the type of `x`, it fails to unify.

**Comment by mlutze** [comment]
This is not a bug. Associated effects may allow the behavior we want here.
