### ISSUE TITLE
Community Build

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2943]
I think it would be nice to have a GitHub CI action which is essentially: 

```
java -jar flix init
java -jar flix install user1/repo1
java -jar flix install user2/repo2
java -jar flix install user3/repo3
java -jar flix build
```

Of course one challenge is that we do break things from time to time and then it would be necessary to ignore the breakage of the build. Is it allowed to have failable GitHub CI?

**Comment by mlutze** [comment]
> Is it allowed to have failable GitHub CI?

The [`continue-on-error`](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error) flag might be what is needed.

**Comment by mlutze** [comment]
Actually, it looks like if we don't add the `community-build` workflow to the required status checks list, then a failure will be reported but will not block merging.

**Comment by magnus-madsen** [comment]
@stephentetley Do you have some packages that we should include in the community build? 

We would use it to ensure that we don't cause unintentional breakages, only intentional ones :)
