### ISSUE TITLE
Add `ParOps.mapValues` for `Map[K, V]` and use it broadly

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2974]
The idea is to have a function `mapValues` which applies a function `V1 => V2` to all values in a Map in parallel and rebuilds the map.

We can then use it in several places in the compiler.

**Comment by magnus-madsen** [comment]
- Improve performance of mapValues.
- Use mapValues instead of map everywhere possible. (A search for ParOps.map should be reasonable.)

**Comment by sockmaster27** [comment]
It seems that all remaining relevant occurrences of `ParOps.parMap` are paired with a `Validation.sequence`.

**Comment by magnus-madsen** [comment]
Maybe we want a ParOps function that uses sequence?

**Comment by magnus-madsen** [comment]
I think we should add a more general function where you give it a `Map[k, a]` and a function `a => Validation[b, e]` and then it gives back `Validation[Map[k, b], e]`. Does that make sense?

Then we could use it everywhere!

**Comment by sockmaster27** [comment]
Would this be for the sake of performance or only code readability?

**Comment by magnus-madsen** [comment]
Readability and maintenance.
