### ISSUE TITLE
Introduce `Iterable` and use it for the standard liberary

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2996]
In the standard library we have several signatures like:

![image](https://user-images.githubusercontent.com/2287953/147887098-5fbd8f3a-cee7-49f0-aa78-317754569bbe.png)

This is not very usable because it means that if I have a collection - say a `List[a]` - then I cannot add all its elements to a `MutSet`.

We could use `Foldable` - but only pure collections can implement `Foldable` hence we would not be able to add e.g. an `Array[a]` to a `MutSet[a]`. To overcome this, I propose to introduce a new type class `Iterable` and use it in the signature of e.g. `MutSet.addAll!`. I don't propose to use this type class for the immutable collections, i.e. they can implement it, but I am not yet proposing that e.g. `Set.union` should work with `Iterable`. (This would also not work great because then the operation would always be impure).

This is the tracking issue for:

- [x] #2997
- [x] #2998
- [x] #2999
- [ ] Determine: Can `toIterator` be implemented with `foldRightLazy`?

**Comment by ninaandrup** [comment]
I'm not sure, how `Iterable` is supposed to work. Do you have any inspiration, I can look at?

**Comment by ninaandrup** [comment]
> I'm not sure, how `Iterable` is supposed to work. Do you have any inspiration, I can look at?

It should just convert the collection to a `Iterator`, right?

**Comment by magnus-madsen** [comment]
> > I'm not sure, how `Iterable` is supposed to work. Do you have any inspiration, I can look at?
> 
> It should just convert the collection to a `Iterator`, right?

Yes

**Comment by magnus-madsen** [comment]
To be revisited.
