### ISSUE TITLE
Implement `Iterable` instances

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2998]
Implement `Iterable` instances for all collection types (the usual list).

**Comment by mlutze** [comment]
Reopening because it looks like there are still some more to do.

What's the plan for handling concurrent modification?

**Comment by ninaandrup** [comment]
The missing implementations (using `RedBlackTree`):

- [ ] `Map`
- [ ] `DelayMap`
- [ ] `MutMap`
- [ ] `Set`
- [ ] `MutSet`

**Comment by magnus-madsen** [comment]
To be revisited.
