### ISSUE TITLE
Frontend support for algebraic effects

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3001]
We begin by introducing a new constructs for declaring algebraic effects, for invoking them, and for handling them. 

### Part 1: Declarations

An algebraic effect is declared as follows:

```scala
eff Console {
  def readLine(): String
  def println(s: String): Unit
}
```

An algebraic effect consists of an *effect name* and a collection of *effect operations*. An algebraic effect declaration is somewhat similar to a class declaration. Two important differences (which must be enforced by the compiler):
- An algebraic effect (i.e. `Console`) cannot be parameterized by a type parameter.
- All operations (i.e. `readLine`, `println`) must be monomorphic (i.e. they cannot have type or effect parameters.)

### Part 2: Use of Effects

An algebraic effect operation is invoked (called) as follows:

```scala
let s = do Console.readLine();
do Console.println(String.toUpper(s))
```

An algebraic effect operation is handled as follows:

```scala
let f = _ -> { do Console.readLine(); |> String.toUpper } ;
try f() with {
  case Console.readLine() => resume("ABC")
  case Console.println(s) => resume()
} // evaluates to "ABCABC"
```

We need three expressions:

- `Exp.Do`
- `Exp.TryWith`
- `Exp.Resume`

We also need to rename the current `try` to something like `javatry` or whatever.

### Strategy:

- We should work phase-by-phase.
- In each phase we rename "eff" to "pur" in an initial PR.
- Then we add the new constructs.
- Importantly subsequent phases should discard/ignore the new stuff so we can test in VSCode.
- We add test cases that work up to the phase we have reached.

### Discussion

A few decisions:

- Effect names are upper case (`Console`).
- Effect operations are lower case (`println`).
- We require `do` in front of effect operation invocations (`do Console.println("hello")`).
- We treat effects as namespaces for the purpose of `use`.
- We use `try...with` as the keywords for handlers.
- We write handlers as `with { def println(...) = ..., def baz(...) = ...}`.

Open questions:

- Do we want to allow partial application of effect operations?
- Do we want syntactic sugar for multiple handlers? "try try"
- Can the continuation `resume` "escape"?

**Comment by mlutze** [comment]
> * An algebraic effect (i.e. `Console`) cannot be parameterized by a type parameter.
> * All operations (i.e. `readLine`, `println`) must be monomorphic (i.e. they cannot have type or effect parameters.)

Why these restrictions? I guess monomorphization becomes difficult/impossible?

> Do we want to use the `handle` keyword or should we use `try`?

I prefer `handle` since `try` implies some form of failure, which isn't always the case.

**Comment by magnus-madsen** [comment]
> Why these restrictions?

It's because of the current plan for how to implement it in the type system. (I can give some more details offline. This is still active research.)

**Comment by kephas** [comment]
Aren't these effects a lot like Free Monads and `try` the equivalent of [`foldFree`](https://hackage.haskell.org/package/free-5.1.7/docs/Control-Monad-Free.html#v:foldFree)?

**Comment by magnus-madsen** [comment]
> Aren't these effects a lot like Free Monads and `try` the equivalent of [`foldFree`](https://hackage.haskell.org/package/free-5.1.7/docs/Control-Monad-Free.html#v:foldFree)?

I don't know :) We have not yet decided on the exact semantics.

it seems there are many choices to be made: https://github.com/lexi-lambda/eff/blob/master/notes/semantics-zoo.md

**Comment by JonathanStarup** [comment]
@magnus-madsen outdated?

**Comment by magnus-madsen** [comment]
Not until we support sets.
