### ISSUE TITLE
Enum with parens as syntax error

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3002]
```scala
enum E {
    case C() 
}
```

This gives a kind error (because `()` is a record row) but it would be better to give a syntax error.

**Comment by JonathanStarup** [comment]
If there is no ambiguous meaning, this could also just be the same as `case C`

**Comment by magnus-madsen** [comment]
What's the benefit of allowing this? Is it more regular?

**Comment by magnus-madsen** [comment]
We could also parse it and then ban it.

**Comment by mlutze** [comment]
I prefer not to allow it, to maintain a "one right way to do it" where reasonable.

**Comment by magnus-madsen** [comment]
> I prefer not to allow it, to maintain a "one right way to do it" where reasonable.

OK, then let us ban it.
