### ISSUE TITLE
Proposition to add the ability to remove names from scope

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#3009]
The motivation example is patterns like this
```flix
def compile(e: Expression): Value =
    def visit(e: Expression, context: Context): Value = match e {
        case Add(e1, e2) => visit(e1, context) + visit(e2, context)
        case ...
    };
    visit(e, Context.empty())
```
This is illegal because `e` is shadowed. The solution is to rename one of them, maybe to rename the inner `e` to `e1`. Now you can code along in the body of `visit` but mentally you might have forgotten the renaming of `e` and use the outer expression by mistake. These scenarios where you can't meaningfully distinct the two expressions lead to situations where you often can misremember whatever arbitrary renaming you did to fix the shadowing. This can be solved by strong principles (e.x. always renaming the outer thing to `e0`) but I think a language construct to remove names from scopes have some value here. They guarantee that you can never mess up (in cases where you don't need the outer variable of course).

A `forget e { ... }` expression could just remove e from the scope inside the block or a `let` equivalent version `forget e;` where you do not regain e in scope. These are however hard to use with let bindings since you want the new binding to escape the block that is unscoped, so a construct like `without e def visit(e: Expression, context: Context): Value = ...` is perhaps more useful.

I think this solution can be improved but I think it could be a nice addition since it is useful but also very much optional

**Comment by magnus-madsen** [comment]
Other crazy ideas:

```
def compile(outer e: Expression): Value =
    def visit(e: Expression, context: Context): Value = match e {
        case Add(e1, e2) => visit(e1, context) + visit(e2, context)
        case ...
    };
    visit(e, Context.empty())
```

or


```
def compile(once e: Expression): Value =
    def visit(e: Expression, context: Context): Value = match e {
        case Add(e1, e2) => visit(e1, context) + visit(e2, context)
        case ...
    };
    visit(e, Context.empty())
```

**Comment by esbenbjerre** [comment]
I believe stuff like this makes it harder to reason about programs. You could argue that it's a special feature which should be used under special circumstances only, but personally I don't like it.

**Comment by mlutze** [comment]
> I believe stuff like this makes it harder to reason about programs. You could argue that it's a special feature which should be used under special circumstances only, but personally I don't like it.

I agree. Is there something else we can do to support the "visitor" pattern that doesn't require an asterisk on a principle?

**Comment by JonathanStarup** [comment]
Do you have an example? when you see `e` and want to find the definition you have to scan backwards until you find the declaration like before.

But I guess you do have a point, this is essentially reintroducing shadowing
