### ISSUE TITLE
Add `sum` and `sumWith`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3013]
For List:

```
def sum(l: List[Int32]): Int32
def sumWith(f: a -> Int32, l: List[a]): Int32
```
I suggest that this be placed right after `count` in the respective files.

- [ ] Add to all data structures.
- [ ] Add to `Foldable`.
- [ ] Add purity polymorphic version to `Set/Map` and their friends.

**Comment by mlutze** [comment]
Could we generalize to this?
```scala
def sum(l: List[a]) with Add[a]: a
```

**Comment by magnus-madsen** [comment]
Yes, but nein. Because `Add` has no meaning. We could generalize it to Monoid or CommutativeMonoid.

**Comment by jaschdoc** [comment]
Should it be implemented directly or can it just call `fold` like `count` does most of the time?

**Comment by magnus-madsen** [comment]
> Should it be implemented directly or can it just call `fold` like `count` does most of the time?

That's fine. But I want sumWith to be purity polymorphic :)

**Comment by jaschdoc** [comment]
For **all** data structures?

**Comment by magnus-madsen** [comment]
> For **all** data structures?

For Set and Map

**Comment by magnus-madsen** [comment]
You can start with the standard folds and then in a separate PR, we can do the purity polymorphic for set/map.

**Comment by magnus-madsen** [comment]
Fixed in master.
