### ISSUE TITLE
Internal compiler exception on too many free variables

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#3014]
This line here in lowering sometimes throws an exception. Shouldn't this be a proper flix exception when correct programs can cause this error? Lowering probably should cause errors so the check so possibly be done earlier.
```scala
private def mkGuard(fvs: List[(Symbol.VarSym, Type)], exp: Expression, loc: SourceLocation)(implicit root: Root, flix: Flix): Expression = {
    // Compute the number of free variables.
    val arity = fvs.length

    // Check that we have <= 5 free variables.
    if (arity > 5) {
      throw InternalCompilerException("Cannot lift functions with more than 5 free variables.")
    }
```

**Comment by magnus-madsen** [comment]
It could be a checker somewhere in the frontend or we should raise the limit or both.

**Comment by JonathanStarup** [comment]
I vote both

**Comment by magnus-madsen** [comment]
Every compiler has these weird built-in limits. Its hard to deal with them correctly. Usually its better to just raise the limit.

**Comment by magnus-madsen** [comment]
Wontfix - at least not now.
