### ISSUE TITLE
Add `product` and `productWith`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3026]
For List:

```
def product(l: List[Int32]): Int32
def productWith(f: a -> Int32, l: List[a]): Int32
```
I suggest that this be placed right after `sumWith` in the respective files.

- [ ] Add to all data structures.
- [ ] Add to `Foldable`.
- [ ] Add purity polymorphic version to `Set/Map` and their friends.

**Comment by jaschdoc** [comment]
I think we can close this now
