### ISSUE TITLE
Compile a list of "Did you know"?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3032]
- Did you know that the most expensive compilation phases in Flix are parallel? For example, Flix will type check each definition of your program in parallel.
- Did you know that Flix disallows unused variables and shadowed variables? Research has shown that such redundancies are correlated with bugs. 
- ... 

We can use these for tweets etc.

**Comment by JonathanStarup** [comment]
These also sound like the kind of messages intellij shows on startup but I don't know if a random msg on flix startup in vscode is appropriate

**Comment by mlutze** [comment]
> These also sound like the kind of messages intellij shows on startup but I don't know if a random msg on flix startup in vscode is appropriate

Maybe once we have ~100 of them so it's not just the same thing every time.

**Comment by magnus-madsen** [comment]
Fixed in master.
