### ISSUE TITLE
Add `Foldable.joinWith` and `X.joinWith`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3047]
Add 

```scala
pub def joinWith(f: a -> String, sep: String, f: f[a]): String = ...
```

to `Foldable`. 

Add

```scala
pub def joinWith(f: a -> String, sep: String, l: List[a]): String = ...
```

and similar to each collection namespace. (These can just call Foldable, except for mutable data structures which must be impure).

In each case , the implementation should use a `StringBuilder` for efficiency. (Note this requires a cast)

**Comment by magnus-madsen** [comment]
Fixed in master.

**Comment by jaschdoc** [comment]
I have only implemented `join` not `joinWith` so this should still be open

**Comment by magnus-madsen** [comment]
Wooops
