### ISSUE TITLE
Add version to Flix project

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#3050]
Right now flix packager init creates
* build/
* lib/
* src/
* target/
* test/
* HISTORY.md
* LICENSE.md
* README.md

Shouldn't there be a flix version somewhere? A project.json file or something like that?

**Comment by mlutze** [comment]
Maybe this should go in the package dependency file when we add that

**Comment by magnus-madsen** [comment]
We have it in the manifest.
