### ISSUE TITLE
VSCode: use partial compilation for running tests, etc.

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3054]

**Comment by magnus-madsen** [comment]
If I understood correctly, this would entail keeping the Flix compiler "alive". 

The advantage of the current model (even if slower) is that you get a completely fresh Flix instance and that you can even launch multiple of them. 

If we keep the compiler running (and something goes wrong), things may stop working. Also, its not even clear how we would launch the compiler and communicate with it.

**Comment by mlutze** [comment]
My idea was that we can use partial compilation to speed up tests

**Comment by magnus-madsen** [comment]
What do you mean?

**Comment by mlutze** [comment]
When a user clicks "run test", it would leverage the current partial compilation to execute it, rather than reloading the whole standard library etc.

**Comment by magnus-madsen** [comment]
We kind of have this now!
