### ISSUE TITLE
`Import nullable`

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3058]
Continuing along the "safer imports" path, could we handle `null`s at the import site with something like the following?

```java
// Java code that we import
public static String getString() {
    if (...) {
        "hello"
    } else {
        null
    }
}
```

```scala
/// Flix wrapper
def getString(): Option[String] = {
    import static nullable thing.StringMachine.getString(): & Pure;
    getString()
}
```

`nullable` automagically converts the return type into an `Option[String]` (or eventually `m[String] with MonadFail[m]`)

Maybe we could also do something where we automagically wrap exceptions with `Result`

**Comment by magnus-madsen** [comment]
I like the idea. How do you know it associates with the return type and not with the arguments?

**Comment by magnus-madsen** [comment]
Also, how would you annotate the return type? (My intention is that return types should be annotated).

**Comment by mlutze** [comment]
> I like the idea. How do you know it associates with the return type and not with the arguments?

Fair point. I'm not sure how to solve this elegantly.

> Also, how would you annotate the return type? (My intention is that return types should be annotated).

The two obvious options are
1. Use the Java type `String`
2. Use the Flix type `Option[String]`

There are definitely drawbacks to both ways, but I think option 2 is more clear overall.

**Comment by magnus-madsen** [comment]
What about a function in `Object` that lifts a function to return an `Option`? That seems pretty easy?

E.g.

```
def getString(): Option[String] = {
    import static Thing.StringMachine.getString(): String & Pure;
    let getSafeString = Object.nullable(getString())
```

or whatever you want to call it.

**Comment by mlutze** [comment]
> What about a function in `Object` that lifts a function to return an `Option`? That seems pretty easy?
> 
> E.g.
> 
> ```
> def getString(): Option[String] = {
>     import static Thing.StringMachine.getString(): String & Pure;
>     let getSafeString = Object.nullable(getString())
> ```
> 
> or whatever you want to call it.

I think we already have one of those :)

**Comment by magnus-madsen** [comment]
What is it called and where is it?

**Comment by mlutze** [comment]
> What is it called and where is it?

`Object.toOption`

**Comment by mlutze** [comment]
Ah, but it doesn't lift the function but converts the result. I read your comment to quickly.
