### ISSUE TITLE
Don't write bytecode to files by default

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3059]
Here is my proposal:

- When the Flix compiler is invoked it should compile and run the program. However there is no reason to write the class files to anywhere.
- Unless the Flix compiler is invoked using the build system e.g. `build`, `run`, `package` etc.
- Or unless `--target ...` is specified.

Why? Because right now we clutter the `build` and `target` folders (not sure why we use both) and they are never cleaned up. This wastes space and causes some issues in VSCode. Oh and writing to the disk is slow. 

@JonathanStarup @mlutze What do you think?

**Comment by mlutze** [comment]
Are the class files ever used on the next run? If they're just overwritten then I agree there doesn't seem to be any point in keeping them around, except maybe for rare debugging purposes.

**Comment by magnus-madsen** [comment]
> Are the class files ever used on the next run? If they're just overwritten then I agree there doesn't seem to be any point in keeping them around, except maybe for rare debugging purposes.

Just straightup overwritten. Note that changes to the program might even result in files with different names!
