### ISSUE TITLE
Introduce `++` and `Append` type class?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3063]
Do we want `++` tied to an `Append` type class?

Instances would include:

- List
- Chain
- LazyList
- Set
- Map?

Not `MutSet` nor `Iterator` because they are impure. 

- What about `:::`?
- What about lazy append (e.g. iterator)?

**Comment by mlutze** [comment]
What would the laws be? It seems it would have to have a super class in order to have a useful law.

**Comment by magnus-madsen** [comment]
> What would the laws be? It seems it would have to have a super class in order to have a useful law.

This would not have laws, like `Add`. If you want laws I think this would either be `SemiGroup` or `CommutativeSemiGroup` (take your pick)

**Comment by magnus-madsen** [comment]
I think we could add `++` to the parser as an alias for `SemiGroup.combine` (or alternatively a new class).

**Comment by mlutze** [comment]
Could/should string concatenation then be `++` rather than `+`?
