### ISSUE TITLE
Parser combinator library

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3064]
TBD

**Comment by mlutze** [comment]
Note that Stephen already has a functioning parser combinator library: https://github.com/stephentetley/flix-parsec

**Comment by stephentetley** [comment]
Thanks Matthew. 

Flix-parsec is a bit of a mess at the moment, I actually think it should be two parsers - one that moves a pointer about in an immutable String (the current behavior, which seems fast) and one that consumes a token list (more flexible and behaves like Haskell's Parsec).

I'm not sure when I'll get round to working on this - I've a "day job" project that is my high priority at the moment.

**Comment by magnus-madsen** [comment]
For now, lets keep parser libraries outside of the Flix Standard Library.

If a shiny, well-designed library arrives, we can revisit :)
