### ISSUE TITLE
Overview of Missing Type Classes

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3066]
- [x] https://github.com/flix/flix/issues/1681
- [x] https://github.com/flix/flix/issues/1922
- [x] https://github.com/flix/flix/issues/1678
- [x] https://github.com/flix/flix/issues/1927
- [x] #3067
- [x] #3068
- [x] https://github.com/flix/flix/issues/1924

**Comment by magnus-madsen** [comment]
@jaschdoc I suggest to defer the groups until last. That means Reducible would probably be next.

**Comment by magnus-madsen** [comment]
@jaschdoc You are still on this, but right now the focus is all the region stuff :)

**Comment by jaschdoc** [comment]
I think we can close this now
