### ISSUE TITLE
Missing `Validation.flatMap`?

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3072]

**Comment by magnus-madsen** [comment]
Validation is not a monad, only an applicative functor.

**Comment by magnus-madsen** [comment]
Buuut, sometimes it is treated as a monad.. Hmm

**Comment by mlutze** [comment]
So eventually we'll have a `let+` but not a `let*` for `Validation`?

**Comment by magnus-madsen** [comment]
Probably yes

**Comment by magnus-madsen** [comment]
If you have the time (who has :)) take a detailed look at:

https://typelevel.org/cats/datatypes/validated.html

and when you emerge from the Wildlands report back!

(Side-note: Maybe `Validated` should use NonEmptyChain instead of Nel?)

**Comment by mlutze** [comment]
I took a non-detailed look and here is my naive proposal.

```scala
/// `|` to signify parallel
let| x0 = e0;
let| x1 = e1;
let| x2 = e2;
e3
```

desugars to

```scala
Validation.sequece(e0 :: e1 :: e2 :: Nil)
   |> Validation.map(match x0 :: x1 :: x2 :: Nil -> e3)
```

**Comment by mlutze** [comment]
> I took a non-detailed look and here is my naive proposal.
> 
> ```scala
> /// `|` to signify parallel
> let| x0 = e0;
> let| x1 = e1;
> let| x2 = e2;
> e3
> ```
> 
> desugars to
> 
> ```scala
> Validation.sequece(e0 :: e1 :: e2 :: Nil)
>    |> Validation.map(match x0 :: x1 :: x2 :: Nil -> e3)
> ```

I realit that we need heterogeneous lists for this, but don't worry. I have a plan for that which only requires custom kinds and GADTs.

**Comment by magnus-madsen** [comment]
![image](https://user-images.githubusercontent.com/2287953/150112445-36516dfb-f562-4132-b74a-0d9dcda3aea3.png)

**Comment by magnus-madsen** [comment]
I am not against; but I definitely don't think we should add this before we have some more experience with all the monadic stuff and its syntax. I suggest to defer a long way down the road :)
