### ISSUE TITLE
Disallow irrelevant modifiers for instance 

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#3079]
Right now any of the general modifiers can be written before instance
![image](https://user-images.githubusercontent.com/32037926/150120390-95c58433-1f57-4b3c-9d66-52a9c73289b9.png)
but `pub` does nothing for example

**Comment by magnus-madsen** [comment]
https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Weeder.scala#L149
