### ISSUE TITLE
Rename `opaque` keyword?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3086]
such that we can use it for visibility of enum cases.

**Comment by mlutze** [comment]
* `clear`
* `wrap`
* `new`

**Comment by JonathanStarup** [comment]
maybe `box`/`boxed`

**Comment by magnus-madsen** [comment]
Why do we even need the keyword? Could the compiler not just figure it out for itself?

**Comment by JonathanStarup** [comment]
Do `type X = Int32` for the opaque version and `type alias X = Int32` for the alias?

**Comment by mlutze** [comment]
> Do `type X = Int32` for the opaque version and `type alias X = Int32` for the alias?

That seems backward to me. If it just looks like an assignment `type X = Int32` then that should be an alias IMO, while a boxed type should have a keyword.

**Comment by magnus-madsen** [comment]
Reminder me again. I think we are trying to free the `opaque` keyword so we can use it for visibility, eg:
```
pub enum Color {
  case Red
  opaque case Blue // cannot be access outside the namespace of Color
}
```

Also:

```
pub opaque enum Color // marks all cases as opaque
```

Meanwhile, we need a new short hand to say:

```
pub enum Bar { case Bar(Int32) } // which used to be opaque type Bar = Int32
```

**Comment by magnus-madsen** [comment]
How about:

```
pub singleton enum Bar = Int32
```

or something thar reuses the `enum` keyword?

**Comment by JonathanStarup** [comment]
Does it have to be a keyword? `pub enum Bar = Int32` doesn't match anything else I think?

**Comment by magnus-madsen** [comment]
> Does it have to be a keyword? `pub enum Bar = Int32` doesn't match anything else I think?

Could do it. Thoughts?

**Comment by mlutze** [comment]
What about `pub enum Bar(Int32)`? It feels a little more intuitive to me, since we see what the single case looks like.

**Comment by JonathanStarup** [comment]
And we could also `pub opaque enum Bar(Int32)` to be an enum with a single opaque case

**Comment by magnus-madsen** [comment]
> What about `pub enum Bar(Int32)`? It feels a little more intuitive to me, since we see what the single case looks like.

OK. Let's do it!

**Comment by magnus-madsen** [comment]
I think we add a new case around here:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Parser.scala#L183

then we refactor the std lib and remove the old syntax.

**Comment by magnus-madsen** [comment]
What about TC constraints? Would that be:

```
pub enum Bar(a) with Eq[a]
```

?

**Comment by mlutze** [comment]
> What about TC constraints? Would that be:
> 
> ```
> pub enum Bar(a) with Eq[a]
> ```
> 
> ?

Enums don't have constraints, but we can derive instances:

```scala
pub enum Bar(a) with Eq
```

**Comment by magnus-madsen** [comment]
I need the syntax `enum Bar(Int32)` for a paper.

@mlutze Want to take a swing? You don't have to remove the opaque stuff.

**Comment by magnus-madsen** [comment]
We are removing this:

```
opaque type MutSet[t: Type, r: Region] = ScopedRef[Set[t], r]
```

in favor of this:

```
enum MutSet[t: Type, r: Region](ScopedRef[Set[t], r])
```

@ninaandrup can you go through the standard library and make these changes? (I think a search for either `enum` or `opaque` should suffice).

**Comment by magnus-madsen** [comment]
Once completed, Matt can remove opaquetype from the compiler :)

**Comment by magnus-madsen** [comment]
Once #3858 is merged in:

@mlutze Will you remove `opaque` from the compiler?

@ninaandrup Will you:

Remove: 
  examples/opaque-types.flix (from flix/flix and flix/flix.dev)

Rename:
  Test.Dec.OpaqueType.flix -> Test.Dec.Enum.Singleton.flix

**Comment by magnus-madsen** [comment]
@stephentetley Heads-up: We are about to replace the opaque enum syntax with just `enum Foo(String)`.

**Comment by mlutze** [comment]
Looks like there are still a few uses of `opaque type` in the tests: https://github.com/flix/flix/runs/6665781109?check_suite_focus=tru

**Comment by ninaandrup** [comment]
> @ninaandrup Can you look at those?

I had accidentally turned on file mask for `.flix` in IntelliJ. #3867 should fix it :-)

**Comment by magnus-madsen** [comment]
@ninaandrup Will you update flix.dev and doc.flix.dev as necessary? Thanks!
