### ISSUE TITLE
Foldable.foldMap

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3089]
- expose in names spaces
- make effect poly morphic
- make purity polymorphic

**Comment by jaschdoc** [comment]
Could you explain this a bit more? We already have a `Foldable.foldMap`. Do you want each implementing data structure to override it?

**Comment by magnus-madsen** [comment]
I have no idea. I don't remember. If you look at api.flix.dev does everything look consistent?

Maybe it should just be effect polymorphic (if it is not already?)

**Comment by jaschdoc** [comment]
I'll make it effect polymorphic to begin with. What type of purity polymorphism do you reckon is appropriate here? We could spawn a thread that evaluates `f(x)` when folding and then combine all of the results?

**Comment by magnus-madsen** [comment]
I think we can wait with the purity polymorphic stuff.

**Comment by magnus-madsen** [comment]
What's the status with this? :)

**Comment by jaschdoc** [comment]
I think @ninaandrup add it to namespaces and I made it effect polymorphic some time ago. Still not sure what you had in mind for the purity polymorphic stuff :)

**Comment by ninaandrup** [comment]
Yes, I added it to namespaces in #3743

**Comment by magnus-madsen** [comment]
So we can close?

**Comment by jaschdoc** [comment]
I think so
