### ISSUE TITLE
Functor should be `pub`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3091]
Are there other TCs that should be pub which are not?

**Comment by mlutze** [comment]
Should all top-level definitions be required to be `pub`, since they're _effectively_ `pub` either way?

**Comment by jaschdoc** [comment]
> Should all top-level definitions be required to be `pub`, since they're _effectively_ `pub` either way?

Wouldn't that violate the private by default principle?

**Comment by magnus-madsen** [comment]
I suggest we mark `Functor` (etc) as `pub`. Then separately we figure out what to do about visibility of top-level declarations.
