### ISSUE TITLE
Add `Identity` type and instances

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3092]
```
pub enum Identity[a] { case Identity(a) }
```

and implement `Monad`.

**Comment by mlutze** [comment]
Could we make Monad derivable for enums matching this shape?

**Comment by magnus-madsen** [comment]
> Could we make Monad derivable for enums matching this shape?

Probably yes. I don't think Monad can be derived in general though. Functor can. 

However, I am skeptical of any further automatic derivations.

**Comment by stephentetley** [comment]
I'll be very pleased to see this in the stdlib.

I expect it to be very helpful for writing laws.

**Comment by stephentetley** [comment]
I've created a PR - #3094 

"feat: Add the Identity Functor/Monad - #3092"

**Comment by magnus-madsen** [comment]
Fixed in master.
