### ISSUE TITLE
StringBuilder subject-last

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3098]

**Comment by magnus-madsen** [comment]
@ninaandrup Can you take a look at this one? :)

**Comment by ninaandrup** [comment]
Needs refactoring:

- [ ] `append!`
- [ ] `appendString!`
- [ ] `appendLine!`
- [ ] `appendLineWith!`
- [ ] `appendLines`
- [ ] `appendLinesWith!`
- [ ] `intercalate!`
