### ISSUE TITLE
Packager: empty lib folder

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3099]
The packager checks that a `lib` folder exists when verifying that the current directory is a Flix project. For many basic projects, this folder will be empty, meaning that version control will ignore it. Even when it is not empty, these dependencies would probably be ignored in version control (and `install` used locally). As a result, CI ends up saying "this is not a Flix project" and fails.

**Comment by magnus-madsen** [comment]
Proposal? To not require it?

**Comment by mlutze** [comment]
I think so, but I'm not 100% sure.

If we don't require it, then we might have a situation where I make my own lib folder, thinking it's not part of the spec, and it conflicts somehow.

If we do require it, and we just put a `.deleteme` file in it, then I'd probably just put `/lib` in my `.gitignore` anyway, so we have the same problem.

So I vote we don't require it.

**Comment by JonathanStarup** [comment]
i think `.gitkeep` is used for this issue (though is doesn't really matter). we could add a --git flag to the init call. It could have a basic .gitignore for jvm things and add the keep files to the empty folders.

**Comment by magnus-madsen** [comment]
Do we create a .gitignore atm?

**Comment by mlutze** [comment]
> Do we create a .gitignore atm?

No

**Comment by magnus-madsen** [comment]
If we allow it to not exist then the packager should be sure to create it when a package is installed.
