### ISSUE TITLE
Math library

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3105]
We could start with a wrapper around `java.lang.Math`

**Comment by magnus-madsen** [comment]
We do already have some functionality in the numeric namespaces, e.g. `Int32`.

**Comment by magnus-madsen** [comment]
While we could start to wrap e.g. `java.lang.Math`, I am not sure if this is the right long term approach. Why not just import each method? And if that is too cumbersome, perhaps we need to improve interop?
