### ISSUE TITLE
Add non-empty chain (`Nec`?)

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3113]
A `Chain`, but non-empty. 

My intuition is that it would be defined as:

```
pub enum Nec[a] {
  case Nec(Chain[a], a, Chain[a])
}
```

**Comment by magnus-madsen** [comment]
@stephentetley Is this something you would be interested in implementing (eventually)? 

I ask because you did `Chain` and so if you do `Nec` I am sure we will have a consistent design/set of operations/documentation.

No urgency, and if not, I will probably just ask one of the student programmers to do it.

**Comment by stephentetley** [comment]
Hi Magnus, I'd just started looking at this for a weekend hack and thought I'd better check the issues again to see if anyone else had started it...

I'll see how much I can do over the weekend hopefully getting as far as a PR, though I've also got a work related project that needs attention.

**Comment by stephentetley** [comment]
I've submitted a PR - #3139 feat: add Nec (Non-empty Chain) data structure #3113
