### ISSUE TITLE
Prepare `DelayList` for release

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#3122]
I've looked over `DelayList` and here are some of the issues I found.

~~**Functions that could be added**~~
~~`init`~~

~~**Use LetRec?**~~

~~**Docs that need fixing**~~
~~`append`~~
~~`intersperse`~~

**Rename these**
~~`x: a` to `a: a`~~
~~`mapL` to `mapLazy` and `mapE` to `mapEager` etc.~~
~~`ks -> ks` to use `identity`~~

**Functions**
~~- `intersperse` - Could be more lazy. I don't like the `LCons` case that forces the tail, maybe adding an `insert` helper function could alleviate the problem? I'm not sure about this~~
~~- `intercalate` - Same as above~~
~~- `zip` - Simplify. Have the base cases with `ENil` and otherwise just delegate to `zipHelper` and wrap in `LList` i.e. `LList(lazy zipHelper(l1, l2))`~~

~~Discussion: Should private lazy functions have the `@Lazy` annotation? Currently, some do and some don't.~~

~~Maybe the file should also be reordered again. `Map` is in the middle, `fold`s and `filter` is near the bottom and maybe they should be at the top s.t. the further down the file you read the functions are less commonly used and perhaps more complex?~~

@magnus-madsen What's your input?

**Edit**
Add `SemiGroup` instance
Add `Monoid` instance
Add `Applicative` instance
Add `Monad` instance
Add `Traversable` instance

Related to #3153

**Comment by magnus-madsen** [comment]
- I think adding `init` does not make too much sense. 
- We should use let rec.
- Please fix the docs.
- I would *not* rename x: a to a:a
- I would keep mapE and mapL.
- I would use identity instead of `ks -> ks`.
- Probably just leave intersperse and intercalate. 
- Simplify zip.

Add missing instances.

**Comment by magnus-madsen** [comment]
- Check doc for intercalate and intersperse.

**Comment by magnus-madsen** [comment]
- Add sumWith, product, productWith

**Comment by magnus-madsen** [comment]
I think we should also remove `toString`.

**Comment by jaschdoc** [comment]
> * I would _not_ rename x: a to a:a

Why not? I remember you being in favor of this. I'd argue this makes the code more readable:
```flix
    @Experimental
    pub def memberOf(a: a, l: LazyList[a]): Bool with Eq[a] = match l {
        case ENil         => false
        case ECons(x, xs) => x == a or memberOf(a,       xs)
        case LCons(x, xs) => x == a or memberOf(a, force xs)
        case LList(xs)    =>           memberOf(a, force xs)
    }
```
The pattern match has a beautiful `x :: xs` structure :)

**Comment by jaschdoc** [comment]
Roger that

**Comment by jaschdoc** [comment]
What do you think of the intermediate `LList`s that are created in `drop` and `dropWhile`? https://github.com/flix/flix/blob/cd4600b5f439f6431f37f38b574bd078d155fc2a/main/src/library/LazyList.flix#L919

I suggest only having the calling function defer it as `LList(lazy dropHelper(n, l))` and once invoked it should just return once the "drop" is performed i.e. the helper should not return any `LList`s (also note that it will be using inner functions but this is just to illustrate the point). Thoughts?

**Comment by magnus-madsen** [comment]
Lets leave most of the stuff for now. Wrap this up quickly (finish the changes you want) and then move onto make DelayMap parallel. I would like to start doing experiments soon (deadline in a bit more than two weeks) and I need some time :)

**Comment by magnus-madsen** [comment]
We will continue this ticket after the deadline in a few weeks time.
