### ISSUE TITLE
add cache to stratifiction?

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#3129]
The current stratifier does not cache its graphs like done previously. The graph now contains arity, denotation, name, and term types.
The term types makes makes caching difficult. Can we introduce caching back?

* Caching using strict equality on types works but are probably a bit slow and reduces the reuse of the code.
* Caching using unification as equality would maximize reuse but would probably be even slower.

**Comment by magnus-madsen** [comment]
Cool idea, but until there is any performance impact, there is no reason to do it (yet).

I tagged it as future so we can find it later.
