### ISSUE TITLE
Refactor the way tests are automatically constructed

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3144]
- [x] Refactor `LangSuite.scala` to match the structure of `LibrarySuite.scala`.
- [x] Refactor `TestExamples.scala` to match the structure of `LibrarySuite.scala` (and rename to `ExampleSuite`)
- [x] Delete `FlixTest`.

**Comment by magnus-madsen** [comment]
Except it seems that the PR times out :(

**Comment by ninaandrup** [comment]
> I suggest you do this one group of tests at a time, starting with expressions.
> 
> Does it make sense?

I'm not quite sure what you mean by expressions? Is it everything in `Test.Exp...`?

**Comment by magnus-madsen** [comment]
Extra work will be needed for the cases where the options are non-standard. 

This is because some of the std lib has been copied into these tests and will probably need to be removed.

**Comment by magnus-madsen** [comment]
I suggest you break it into a series of smaller PRs.

**Comment by ninaandrup** [comment]
> I suggest you break it into a series of smaller PRs.

Alright, I'll get started on this :)

**Comment by magnus-madsen** [comment]
I think what remains is to:

- [ ] Use a single call to `mkTestDir` in `CompilerSuite`.
- [ ] Go through each Flix test file (.flix) and see if there is some repeated library code that should be erased.
- [ ] Ensure each file uses the right namespaces.

**Comment by magnus-madsen** [comment]
(For example, if I search for `enum Option` in the test folder there is a lot of repetition).

**Comment by ninaandrup** [comment]
> I think what remains is to:
> 
> * [ ]  Use a single call to `mkTestDir` in `CompilerSuite`.
> * [ ]  Go through each Flix test file (.flix) and see if there is some repeated library code that should be erased.
> * [ ]  Ensure each file uses the right namespaces.
> * [ ]  Look at TestExamples and do the same thing?

I think the only thing left is the last one with `TestExamples`. Should I go through the files in `examples` and make sure there is no dublicate code or what do you mean?

**Comment by magnus-madsen** [comment]
But you already managed to delete `FlixTest` right? So I think then maybe we are done?

**Comment by magnus-madsen** [comment]
I think we are done!
