### ISSUE TITLE
Refactor tests in `LangSuite` not to depend on the library

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3146]
For example, the line:

```
  new FlixTest("Test.TypeAlias.Rel", "main/test/flix/Test.TypeAlias.Rel.flix")(Options.TestWithLibAll),
```

needs to have the `TestWithLibAll` removed and then the content of `Test.TypeAlias.Rel.flix` needs to be updated. Either by copying small fragments of the std lib into it or by removing its usage of the std lib or a mix.

**Comment by JonathanStarup** [comment]
For tests using datalog this might be very difficult

**Comment by magnus-madsen** [comment]
> For tests using datalog this might be very difficult

Yes. For those, we should probably put them into a different folder.

**Comment by magnus-madsen** [comment]
New idea: Everything should depend on the library and then we should use incremental compilation (and have a bigger server).
