### ISSUE TITLE
Overview of let rec in library

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#3163]
This meta issue tracks the progress of refactoring the standard library to use let rec instead of helper functions.

- [x] #3150
- [x] #3151
- [x] #3152
- [x] #3153 - now called `DelayList`.
- [x] #3154
- [x] #3155
- [x] #3156
- [x] #3157
- [x] #3158
- [x] #3159
- [x] #3160
- [x] #3161
- [x] #3162
- [x] #3288
- [x] #3582

Old issue: #2774

**Comment by magnus-madsen** [comment]
@jaschdoc Just before we close this, I would like you to do a pass through all the namespaces and see if there are some places were we unnecessarily introduced local `loop` functions that are not necessary. (E.g. as we discussed in #3355). Once that is done then this ticket can be closed 🚀

**Comment by jaschdoc** [comment]
Roger :slightly_smiling_face:

**Comment by jaschdoc** [comment]
We did it (I hope)!
