### ISSUE TITLE
[Bug] Typo in TestSolver

### ISSUE THREAD

**Issue by neynt** [flix/flix#317]
@zxqfl found a typo in datastore/package.scala line 59 today.

      case k: Key5[_] =>
        val a = new Array[Any](5)
        a(0) = k.v0
        a(1) = k.v1
        a(2) = k.v2
        a(3) = k.v3
        a(4) = k.v3 // <---
        a.asInstanceOf[Array[ValueType]]

**Comment by magnus-madsen** [comment]
Thanks @neynt, I will get it fixed.

**Comment by magnus-madsen** [comment]
Fixed in master.
