### ISSUE TITLE
Add `fix` modifier

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3171]
- [x] Add `fix` keyword to frontend.
- [x] Add check for `fix` and `not`.
- [x] Add `fix` keyword support to Stratifier/Ullman.
- [x] Add `fix` keyword support to Datalog runtime.
- [x] Add check that rejects illegal use of lattice variables. (Suggest to use `fix`).
- [ ] Add positive test cases that use fix explicitly.
- [ ] Add negative test cases that use fix explicitly and wrongly.
- [x] Add test cases that uses lattices.
- [ ] Cleanup `Stratifier.run` to avoid too many intermediate collections.
- [x] Refactor query to use `fix` and get rid of `SelectFragment`.
- [x] Refactor documentation and error messages
- [x] https://github.com/flix/flix/issues/3179
- [x] VSCode keyword

**Comment by JonathanStarup** [comment]
> * [ ] Add check that rejects illegal use of lattice variables. (Suggest to use `fix`).

#3180 fixes this

**Comment by magnus-madsen** [comment]
@JonathanStarup I refactored the Weeder and Parser. What I would you to do is to quickly add 5 positive test cases that uses `fix` (i.e. correct programs) and 5 negative test cases that use `fix` (i.e. create cycles). After that, take a look the stratification error message bug. Thanks!

**Comment by magnus-madsen** [comment]
@JonathanStarup In #3183 I switched to using the word "Strongly". Maybe we should do that too internally?

**Comment by JonathanStarup** [comment]
> @JonathanStarup In #3183 I switched to using the word "Strongly". Maybe we should do that too internally?

I think that's nice. So a strong dependency requires the body to be fully evaluated before (lattice/negation/potentially aggregation) and a weak dependency can be recursive.

I can make a PR where I change the wording of everything or maybe split Datalog engine and Stratifier into seperate parts?

I would maybe also propose that we change Fixed/Loose into Fixed/NotFixed or NonFixed. Loose feels a bit arbitrary and hard to remember

**Comment by magnus-madsen** [comment]
Just some tests. Try to think about how to structure them in a good way.

Feel free to do the Strong/Weak renaming in UllmansAlgorithm and Stratifier.flix

**Comment by JonathanStarup** [comment]
We also need to add the keyword in vscode etc.

**Comment by magnus-madsen** [comment]
> We also need to add the keyword in vscode etc.

Already done yesterday!

**Comment by JonathanStarup** [comment]
Ah, the nightly build didn't pick it up yet I suppose

**Comment by magnus-madsen** [comment]
You probably just need to update your VSCode plugin.

**Comment by magnus-madsen** [comment]
@JonathanStarup Can I ask you to add some tests (positive and negative) so we can change gears back to work on the paper?

**Comment by magnus-madsen** [comment]
What remains? Do we have both sufficient positive and negative test cases (I seem to remember there was a lot, but only of one type?)

**Comment by magnus-madsen** [comment]
>  A lot of the datalog examples now use fix through query. I can look them over and update them to have actual test cases?

Really? Which programs?

> 3 negative tests using String/Int32 and Rel/Lat

We have 3 negative examples that use `fix`? I guess a bit more would be useful.

**Comment by JonathanStarup** [comment]
> Really? Which programs?

delivery-date, palindrome, stratifier, IDE.

I thought I saw more red lines when I broke the query thing, but these use fix through query
