### ISSUE TITLE
Wrong stratification error

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#3179]
```flix
def main(_args: Array[String]): Int32 & Impure =
    let p = #{
        T(12). A(;12).
        R(x) :- T(x), not C(x).
        C(x) :- T(x), not B(x).
        B(x) :- T(x), A(;x).
        B(x) :- not B(x).
    };
    query p select x from B(x) |> println;
    println("Hello World!");
    0
```

This program reports that there is a negative cycle between `C` and `C`, both in line 4.

**Comment by JonathanStarup** [comment]
The bug is that the predicate that breaks the stratification limit is not necessarily part of a negative cycle

**Comment by JonathanStarup** [comment]
@magnus-madsen am not sure how to detect strong cycles in general. I could do floyd warshall O(V^3) where a strong edge has weight -infinity. I don't know if there's something smarter/faster?

**Comment by magnus-madsen** [comment]
Question: Would the following work?

Consider each strong edge and see if it is on a cycle?

**Comment by JonathanStarup** [comment]
yes I think so.. for each strong edge (h <- b) see if h can reach b. That would be |negative edges| * |edges| * |Vertices|

**Comment by JonathanStarup** [comment]
Actually we can just modify ullmans algorithm to keep track of "reaching strong predicates". `A :- not/fix B` would mean that A is reached by everything that reaches B union {B} and `A :- B` would mean that A is reached by everything that reached B.
We run ullmans algorithm with this extra info ( |V| * |E| * T(copying sets around) ) and then we scan the predicates in the end for one that can reach itself
