### ISSUE TITLE
stratifier bug projecting polymorphic predicates

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#3193]
```flix
def main(_args: Array[String]): Int32 & Impure =
    let p = #{
        A(12).
    };
    solve p project B;
    println("Hello World!");
    0
```
This programs hits this case in the stratifier
```scala
private def termTypes(tpe: Type): List[Type] = eraseAliases(tpe) match {
    case Type.Apply(Type.Cst(TypeConstructor.Relation | TypeConstructor.Lattice, _), t, _) => t.baseType match {
      case Type.Cst(TypeConstructor.Tuple(_), _) => t.typeArguments // Multi-ary
      case Type.Cst(TypeConstructor.Unit, _) => Nil
      case _ => List(t) // Unary
    }
    case _ => throw InternalCompilerException(s"Unexpected type: ${tpe} :: ${tpe.loc} :: ${tpe.getClass}")
  }
```
This makes sense since the terms of `B` is a type variable. I'm not sure if the stratifier should be more lenient or it is a mistake that it is neither a relation or a lattice

**Comment by magnus-madsen** [comment]
I think this program should be allowed -- even if it is strange.

**Comment by JonathanStarup** [comment]
> I think this program should be allowed -- even if it is strange.

Yes but it shouldn't be this error. Should the typer allow predicates to be fully polymorphic in the schema row? If so then we need to allow the denotation to be unknown in the labelled edges of the stratification.
