### ISSUE TITLE
performance possibilities in the stratifier

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#3198]
* Instead of ullman's algorithm we can use a dfs based scc algorithm, check that no scc contains a strong edge, and then sort the scc topologically to find the actual strata.
* The cycle finding in stratification error reporting checks all strong edges for cycles, instead it could be limited to those reachable by the predicate that caused ullman's algorithm to find an error in the transposed graph.
* There is possibly improvements available in regards to rerunning the cycle detection for each expression instead of using a dynamic scc algorithm that supports edge deletions.

**Comment by magnus-madsen** [comment]
Of course -- right now -- we don't have any evidence that there is a performance bottle neck.

**Comment by JonathanStarup** [comment]
No I don't think it will impact the compiler much, these should be strictly faster however so it felt like a waste not to write it down.

**Comment by magnus-madsen** [comment]
We may revisit in the future.
