### ISSUE TITLE
Optimize DelayMap.map

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3209]
When `DelayMap.map` is given an impure function we could split the job into two:

- First we force the entire tree in parallel.
- Second we apply `f` sequentially from left-to-right.

**Comment by jaschdoc** [comment]
Could you assign me to this, please? :)

**Comment by magnus-madsen** [comment]
This is not too important, if you did not start yet, you can do #3211 first.

**Comment by jaschdoc** [comment]
Roger, PR should be open though

**Comment by magnus-madsen** [comment]
Ok :)
