### ISSUE TITLE
Statistics on use of ReifyEff

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3211]
![image](https://user-images.githubusercontent.com/2287953/154477858-de96704a-f08f-4366-98f5-beb88c11be9d.png)

**Comment by magnus-madsen** [comment]
@jaschdoc I would like this in a few days if possible. (Sorry to stress.)

**Comment by jaschdoc** [comment]
No worries. Coming right up after #3210

**Comment by jaschdoc** [comment]
I'll have this ready sometime Sunday

**Comment by jaschdoc** [comment]
For `Set` and `Map` do you want the Test column to show the total number of tests for that data structure? and for the Functions column, should it be the total number of function in the data structure or just the ones that have been refactored to be parallel?

**Comment by magnus-madsen** [comment]
Good question. My brain is spinning.

**Comment by magnus-madsen** [comment]
Fuck it. Its too complicated to measure/explain. New proposal: 

- Forget about the +/-. Just count _everything_. Total lines, total tests, etc.

**Comment by jaschdoc** [comment]
| Data Structure | Lines (Added / Removed) | Tests | Functions | Term. | Non-Term. |
|----------------|-------------------------|-------|-----------|-------|-----------|
| Set            | +106  / -6              | 384   | 5         | ....  | ...       |
| Map            | ...                     | 591   | 11        | ...   | ...       |
| DelayList      | +1158 / -0              | 498   | 54        | ...   | ...       |
| DelayMap       | +786  / -0              | 298   | 57        | ...   | ...       |

**Comment by magnus-madsen** [comment]
Second, lets just count the following:

- Number of functions that are LazyWhenPure
- Number of functions that are ParallelWhenPure
- Number of functions that are both.

This replaces the term/non-term stuff.

**Comment by jaschdoc** [comment]
Alright roger that

**Comment by magnus-madsen** [comment]
If you try to build a table with that then we can iterate a bit on it.

**Comment by jaschdoc** [comment]
Sure, I'll keep aggregating data :+1:

**Comment by jaschdoc** [comment]
Should be done now

**Comment by magnus-madsen** [comment]
@jaschdoc:

A  few comments:

- Does `Map` really have 80 *public* functions? (Maybe it does- I do see 74 on api.flix.dev)
- I would think both map and mapWithKey in DelayMap should be PWP/LWP?

**Comment by jaschdoc** [comment]
Yes we added quite a lot of functions to Map when introducing Max/Min Keys/Values and sum/product keys/values. I searched for `pub def` and subtracted the number of type class instance functions (before the namespace) yielding 90-10.

I'll look into mapWithKey in DelayMap

**Comment by jaschdoc** [comment]
Updated table, fixed `DelayMap.map` in #3220

**Comment by jaschdoc** [comment]
Updated table

**Comment by jaschdoc** [comment]
Should we close this?

**Comment by magnus-madsen** [comment]
Yes. its submitted.
