### ISSUE TITLE
`MutList.append!` subject-last

### ISSUE THREAD

**Issue by ninaandrup** [flix/flix#3221]
We have the new implementation of `MutList.append!` using `Iterable`.
```
pub def append!(v: MutList[a], t: t[a]): Unit & Impure with Iterable[t]
```
Should it be subject last? Such that `v` is the last argument.

**Comment by ninaandrup** [comment]
Maybe it would make sense to make `v` the last argument, if we think of the function as:
`append` the elements of `t` to `v`.

**Comment by magnus-madsen** [comment]
I think the MutList should be last, yes.
