### ISSUE TITLE
Improve String Support

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#323]
Add support for string concatenation and other string operations from the Java standard library.

**Comment by magnus-madsen** [comment]
Now that we have support for native methods we should discuss what string operations to support. I would suggest starting with something very basic.

See also flix/main/src/library/String.flix

**Comment by FlaminGuy** [comment]
String concatenation is already supported. 
Using native methods I think we can support most of methods on Java's string class.

**Comment by magnus-madsen** [comment]
Yes. Can you give a proposal of functions to support?

**Comment by FlaminGuy** [comment]
contains, split, substring, toUpperCase and toLowerCase? anything else?

**Comment by magnus-madsen** [comment]
Fixed.
