### ISSUE TITLE
Allow return type annotations on nested defs / let-recs

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#3239]
Allow annotations like so:
```flix
def main(_args: Array[String]): Int32 & Impure = 
    def f(x: Int32): Int32 = x*x;
    f(2) |> println;
    0
```
The return annotation of `f` is currently rejected by the parser

**Comment by mlutze** [comment]
In top-level defs, no effect annotation means `Pure`. Should we have the same expectation for inner defs?

**Comment by magnus-madsen** [comment]
> In top-level defs, no effect annotation means `Pure`. Should we have the same expectation for inner defs?

No, we should infer it.

**Comment by mlutze** [comment]
I'm realizing that reusing the top-level function syntax makes it difficult for the parser to determine if a function is nested or not. A user can make things more explicit by including braces in the outer functions.

**Comment by mlutze** [comment]
It seems that the only thing letting the parser distinguish between a top-level function and a nested function is the return type ascription. Any thoughts on how to fix this? We could do something like `let def ...` instead, but that would not be pretty IMO.

**Comment by magnus-madsen** [comment]
Should they really be the same? Annotations? Modifiers? The fact that type parameters can be omitted. It seems there are many differences.

**Comment by mlutze** [comment]
I agree that there are substantial differences in general. But it seems to me that there's an overlap in representation. E.g. an annotation would indicate a top-level def, but the lack of one wouldn't indicate a nested def.

**Comment by magnus-madsen** [comment]
I think we should keep the grammars separate. They are sufficient different that trying to merge them into one is probably not worth it. They become separate in the AST after parsing anyway, right?

**Comment by mlutze** [comment]
Even if we keep the parsing rules separate, we still need something to distinguish them syntactically since otherwise the two different rules can still match the same code.

**Comment by magnus-madsen** [comment]
They can? Expressions are not allowed at the top level, is that not enough?
