### ISSUE TITLE
Disallow single-letter operator definitions

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3244]
This is allowed:
```scala
def |(t1: Ty, t2: Ty): Ty = Or(t1, t2)
```

But it cannot be used:
```
>> Parse Error: Invalid input "| ", expected '[', '.', "::", ":::", ':', "as", Op, '`', "<+>", **, *, /, mod, rem, +, -, <<<, >>> or <= (line 39, column 34):
def anyTag(): Ty = Not(anyProd() | anyArrow() | anyInt())
                                 ^
```

We either disallow the declaration, or allow its use.

**Comment by magnus-madsen** [comment]
I think we could allow it. I wonder why it does not go through.

**Comment by mlutze** [comment]
> I think we could allow it. I wonder why it does not go through.

The parser only checks for two-, three-, and more-character operations.

**Comment by magnus-madsen** [comment]
Outdated.
