### ISSUE TITLE
Unreserve `&&` and `||`

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3246]
These are reserved in the parser (despite begin replaced by `and` and `or`) .

```scala
def anyTag(): Ty = Not(anyProd() || anyArrow() || anyInt())
```
gives
```
>> Parse Error: Invalid input "|| ", expected '[', '.', "::", ":::", ':', "as", Op, '`', "<+>", **, *, /, mod, rem, +, -, <<<, >>> or <= (line 39, column 34):
def anyTag(): Ty = Not(anyProd() || anyArrow() || anyInt())
                                 ^
```

**Comment by magnus-madsen** [comment]
We can unreserve them, but would it not be better to give an explicit error message that use `and`, `or`, and `not` instead?

**Comment by magnus-madsen** [comment]
Should they be able to? Maybe they define them as or and and, which would also be bad.

I think it would be nice if we just gave a neat error message.
