### ISSUE TITLE
`List.toNel`

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3248]
Returning an option, of course

**Comment by stephentetley** [comment]
I added `List.toNel` and `List.toNec` to the PR:  `refactor: Change Validation to use Nec rather than Nel (related to #3232) #3233`

**Comment by mlutze** [comment]
I knew I'd seen it somewhere! Thanks, Stephen.

**Comment by magnus-madsen** [comment]
So its done?

**Comment by mlutze** [comment]
> So its done?

Yes, fixed by https://github.com/flix/flix/pull/3233
