### ISSUE TITLE
Support symbolic operators in nested functions

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3249]
```scala
def usingSymbolicFunctionsInAFunction():Bool & Pure = 
   def <><(x:Int32, y:Int32) = x * x * y;
   (10 <>< 4) == 400
```

**Comment by JonathanStarup** [comment]
This could maybe be combined with the addition of return type annotation in a refactoring where top-level functions share more parsing rules with nested functions

**Comment by magnus-madsen** [comment]
Presumably this is a one line fix somewhere in the parser?
