### ISSUE TITLE
Monad instance for `Lazy`?

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3251]

**Comment by magnus-madsen** [comment]
We can, I would think

**Comment by magnus-madsen** [comment]
What's the use case?

**Comment by mlutze** [comment]
It would help in avoiding a lot of `force`/`lazy` clutter when dealing with lazy structures.

Say we have a lazy tree:
```scala
enum LazyTree[a] {
    case Leaf
    case Node(a, Lazy[LazyTree[a]], Lazy[LazyTree[a]])
}
```

and we want to manipulate it somehow, lazily

```scala
pub def nodes(tree: LazyTree[a]): LazyList[a] match tree {
    case Leaf => LazyNil
    case Node(x, lt1, lt2) =>
        let tail = {
            let* t1 = lt1;
            let* t2 = lt2;
            nodes(t1) `lazyConcat` nodes(t2)
        };
        LazyCons(x, tail)
}
```

compared with

```scala
pub def nodes(tree: LazyTree[a]): LazyList[a] match tree {
    case Leaf => LazyNil
    case Node(x, lt1, lt2) =>
        let tail = lazy {
            let t1 = force lt1;
            let t2 = force lt2;
            nodes(t1) `lazyConcat` nodes(t2)
        };
        LazyCons(x, tail)
}
```

The latter case is not too different, but the issue IMO is that we explicitly exit the "lazy" space, which makes it easy to make a mistake like this:

```scala
pub def nodes(tree: LazyTree[a]): LazyList[a] match tree {
    case Leaf => LazyNil
    case Node(x, lt1, lt2) =>
        let tail = {
            let t1 = force lt1;   // these `force`s are done eagerly, so this function is not maximally lazy
            let t2 = force lt2;
            lazy (nodes(t1) `lazyConcat` nodes(t2))
        };
        LazyCons(x, tail)
}
```

**Comment by mlutze** [comment]
One big issue though: `Lazy` requires the expression to be pure, which isn't the case for `Monad` (because the function can be effect-polymorphic).

**Comment by magnus-madsen** [comment]
> One big issue though: `Lazy` requires the expression to be pure, which isn't the case for `Monad` (because the function can be effect-polymorphic).

For this reason we cannot do it. I am also not sure whether such a Monad instance would not just be confusing. 

(I have some notes on some research for a more general approach to this problem).

For now, I just suggest that we accept that `Lazy` is not a `Monad`.
