### ISSUE TITLE
Disallow unused recursive inner function (let rec)

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#3255]
When an inner function is recursive it is possible to avoid calling it (as it's not unused due to recursion?). This program illustrates the error.
```flix
pub def bad(n: Int32): Int32 =
    def loop(i, acc: Int32) = if (i < n) loop(i + 1, acc + acc) else acc;
    0
```

**Comment by magnus-madsen** [comment]
@mlutze What was are judgement w.r.t. to his? What happens for normal top-level functions?

**Comment by mlutze** [comment]
As I recall, we have a special check to see if it's a recursive call. So a recursive call doesn't count as a use.

**Comment by magnus-madsen** [comment]
OK, so the same would apply here?

**Comment by mlutze** [comment]
Supposedly this was fixed for top-level defs (https://github.com/flix/flix/issues/1424), but it seems that master doesn't catch it, so we must have had a regression. I don't want to play the blame game but it was [definitely my fault](https://github.com/flix/flix/commit/97d61f989c4838a0e1cc1d0f687b1f503d495621#diff-5ecd875c02c24b3cd2f0bdabb31dcff2685b3d60341acaf8729b8289aff3b2d6L333).

I'll fix both :)

**Comment by magnus-madsen** [comment]
Fault? It was an experiment that did not work out :)
