### ISSUE TITLE
Syntax of Regions, ScopedRefs, and ScopedArrays

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3268]
Flix is introducing regions 🚀 🎉 

OK, but what is a region?

A region is mechanism that allows you to write a pure function that internally uses mutation. Here is an example:

```scala
def sum(x: Int32, y: Int32, z: Int32): Int32 & Pure =
    let region r;           // introduce a region called r.
    let sum = ref 0i32 @ r; // the "local variable" sum belongs to region "r"
    sum := deref sum + x;   // add x to sum
    sum := deref sum + y;   // add y to sum
    sum := deref sum + z;   // add z to sum 
    deref sum               // the region "r" is over. 
```

Regions are useful because they allow us to write code in an imperative style. Here is another example:

```scala
def sum(items: List[Int32]): Int32 =
    let region r;
    let sum = ref 0 @ r;
    def loop(l) = match l {
        case Nil => ()
        case x :: xs => 
            sum := deref sum + x;
            loop(xs)
    };
    loop(items);
    deref sum
```

Regions work with higher-order effect polymorphic functions so we can also write:

```scala
def sum(items: List[Int32]): Int32 =
    let region r;
    let sum = ref 0 @ r;
    items |> List.foreach(x -> {
        sum := deref sum + x
    });
    deref sum
```

Regions can be used for user-defined data structures. For example:

```scala
pub def f(): Int32 = 
    let region r;
    let s = MutSet2.emptyWithRegion(r);
    MutSet2.add!("hello", s);
    MutSet2.add!("world", s);
    MutSet2.size(s)
```

Here is the implementation of `MutSet` without regions:

```scala
opaque type MutSet[t] = Ref[Set[t]]

pub def add!(x: a, s: MutSet[a]): Unit & Impure with Order[a] =
    let MutSet(ms) = s;
    ms := Set.insert(x, deref ms)
```

And here it is with regions:

```scala
opaque type MutSet[t: Type, r: Bool] = ScopedRef[Set[t], r]

pub def add!(x: a, s: MutSet[a, r]): Unit & r with Order[a] =
    let MutSet2(ms) = s;
    ms := Set.insert(x, deref ms)
```

What is new:
- The `MutSet` type now takes two type parameters: the type `t` of its elements and region `r` of itself.
- The signature of `add!` now takes a `MutSet` with a region and its effect is no longer `Impure` but rather `r` (which can be understood as "has an effect in region `r`").

Questions:
- Is the above understandable?
- Do we want to introduce syntactic sugar for regions to call them out? For example, maybe we should write `MutSet[t, r]` as `MutSet[t] @ r` or `'r MutSet[t]` or ... 
- The `Bool` kind annotation of `MutSet` is a correct, but it seems pretty far from what a programmer would understand. 
- How do we read aloud a signature such as `def add!(x: a, s: MutSet[a, r]): Unit & r with Order[a]`? I would say something like, given an `x` and a mutable set `s` belonging to region `r` ... returns Unit and has an effect in region `r`.

**Comment by magnus-madsen** [comment]
@JonathanStarup @mlutze @jaschdoc @ninaandrup @stephentetley I would like to hear your input :)

**Comment by JonathanStarup** [comment]
Randomly listed thoughts:
* `let region r; ...` gave me the thought that `r` is a value. Maybe a syntax like `region r {...}` could diffirentiate it from let bindings. This would also allow the scope to be limited in the method more naturally like `let x = something; let pureThing = region r { ... }; ...`. On second read, is region a value here `let s = MutSet2.emptyWithRegion(r);`?
* I like the idea of syntactic sugar to separate the effect type from the value type to align with the notation `Int32 & Impure`
* Should you ever use plain `Ref` instead of ScopedRef? 
* Does ScopedRef use compiler support or is it purely library?
* If the scopedRef escapes what happens? Is it just impure forever or is it an error? what happens here?
```flix
def sum(items: List[Int32]): ScopedRef[Int32, r] =
    let region r;
    let sum = ref 0 @ r;
    def loop(l) = match l {
        case Nil => ()
        case x :: xs => 
            sum := deref sum + x;
            loop(xs)
    };
    loop(items);
    sum
```

**Comment by ninaandrup** [comment]
I like the `sum` examples a lot.
What are the pros of using a variable in a region rather than an accumulator?

I'm not sure, I fully understand the `MutSet2`.

**Comment by magnus-madsen** [comment]
Thanks for all your comments. I will try to go through them one-by-one.

**Comment by magnus-madsen** [comment]
>     * `let region r; ...` gave me the thought that `r` is a value. Maybe a syntax like `region r {...}` could diffirentiate it from let bindings. This would also allow the scope to be limited in the method more naturally like `let x = something; let pureThing = region r { ... }; ...`. On second read, is region a value here `let s = MutSet2.emptyWithRegion(r);`?

Good question. Conceptually a region is not a value, but a special type. However, sometimes we need to pass that type to a function, but Flix does not allow us to explicitly pass type variables! To work around this, a region is both a value and a type. The value is erased to Unit at runtime (or should be at least). What should we do about that? Do we want new syntax for passing type variables or is it okay that a region is both a value and a special type?

For the syntax, I like it. We could try to experiment with it `region r { ... }`. Two questions: Do you not feel this would be inconsistent with `let`? A `let` has a scope that extends to the rest of the expression already... And what about the fact that it requires extra indentation? 

>     * I like the idea of syntactic sugar to separate the effect type from the value type to align with the notation `Int32 & Impure`

I have also been thinking about writing `& region(r)` to make clear that it talks about the effect in the region `r`.

>     * Should you ever use plain `Ref` instead of ScopedRef?

In high-quality code, no. But you can. It means to use the global region which means you are always impure.

>     * Does ScopedRef use compiler support or is it purely library?

Its part of the type and effect system, so it requires compiler support.

> 
>     * If the scopedRef escapes what happens? Is it just impure forever or is it an error? what happens here?
> 

The compiler will (eventually) ensure that cannot happen. It already handles the easy cases, but not the hard cases.

>     * "The Bool kind annotation of MutSet is a correct, but it seems pretty far from what a programmer would understand." I think theres several uses for Bool types right? You talked about keeping track of list reversion and things like that. It seems like it could be nice to have a kind of opaque Bool Type like Scope or Reversion to differentiate different kind of Bool types

Yes, or maybe we write `r: Region` and then use `region(r)` to turn that into something of kind Bool.

Good comments, thanks!

**Comment by magnus-madsen** [comment]
> * You're aware of my opinion on this, but I'll mention it again :) . I'm very much in favor of subject-last type parameters to support currying (especially important for type classes).

:-)

>     * My concern regarding the syntactic sugar is that it might obscure that the `r` is actually a part of the full `MutSet` type. With `MutSet[t] @ r` it looks as though `MutSet[t]` is already a full type application.

That is true, but the point is also to distinguish the "real type" `MutSet[t]` from some information about it (its region). We don't write `f: Function2[a, b, ef]` either :)

>     * Jonathan mentioned `opaque kind`; I agree with the idea, but would tend more toward `kind alias` so that the formulas can interact.

I am now thinking we should have a new kind `Region` and then a constructor `region: Kind.Region -> Kind.Bool` that lifts a region into an effect constant.

**Comment by magnus-madsen** [comment]
> I like the `sum` examples a lot. 

Thanks!

> What are the pros of using a variable in a region rather than an accumulator?

Possibly nothing. But if you are used to e.g. Java programming you might prefer a less functional-style and a more imperative style.

**Comment by magnus-madsen** [comment]
> When it comes to syntactic sugar I personally think we should hold off doing anything until we've used it for a while and found some pain points or have come across some trivial patterns. 

That seems reasonable. We can experiment with different kinds of syntax.

> I agree with Jonathan that `let Region r;` can be confusing and `let r = Region;` is not pretty either (and that would also be syntactic sugar, (no?) which I just argued we shouldn't do). Would it be possible to write `let sum = ref 0 @ r` without declaring `r` anywhere i.e. declaring and initializing a region in place? I guess that's syntactic sugar too hehe.

We can try to use a heuristic to always use the "nearest" region. 

> What would the type of `MutSet2.emptyWithRegion` be?

It would be `pub def emptyWithRegion(r: Region[r]): MutSet2[a, r] & r = ...`

> Does `r` go out of scope on `deref` or because it's the end of the scope for the function?

End of scope of the let. 

> `opaque type MutSet[t: Type, r: Bool] = ScopedRef[Set[t], r]` does this allow for `MutSet` with and without regions? I.e. `MutSet[t, true]` is a `MutSet` with a region and using `False` would be `MutSet` as we know it from the current library.

Yes, `MutSet[t, false]` would be like a global `MutSet` today. `MutSet[t, true]` is more tricky, and possibly should not exist.

**Comment by JonathanStarup** [comment]
> For the syntax, I like it. We could try to experiment with it region r { ... }. Two questions: Do you not feel this would be inconsistent with let? A let has a scope that extends to the rest of the expression already... And what about the fact that it requires extra indentation?

My thought was that it would be annoying that let has the rest of the expression. I was thinking something like 
```flix
def f(): Unit =
    let a = ...; // pure
    let b = region r { ... }; // pure but locally impure
    let c = ...; // pure
    ...
```
with the let syntax this would have to be 
```flix
def f(): Unit =
    let a = ...; // pure
    let b = {
        let region r;
        ...
    }; // pure but locally impure
    let c = ...; // pure
    ...
```

**Comment by magnus-madsen** [comment]
> I'm a big fan of passing type variables. 

But are you not only a fan because of poor type inference? Do you like to write more annotations?

**Comment by magnus-madsen** [comment]
Regions cannot be fully inferred because they are part of the meaning of the program and we cannot read the mind of the programmer. We can however have a default where if a region is declared it is used by default.

**Comment by JonathanStarup** [comment]
> > I'm a big fan of passing type variables.
> 
> But are you not only a fan because of poor type inference? Do you like to write more annotations?

hmmm, good point. I forgot that. I think that it would never be a bad thing. You can use it when you have a type error to assert the types you think are true. That is nice for debugging. It might not be important with complete inference though. It is still nice here though if the region is part of the type. If the region is separate then it doesn't relate to this at all.

**Comment by magnus-madsen** [comment]
We now have some working syntax. We can revisit the syntax as we grow wiser. Thanks for all your input!
