### ISSUE TITLE
Restructuring the Typer for Better Errors

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3271]
Ideas:

- [ ] Re-ordering the calls to `unifyM` may give better type error messages. 
- [ ] Unify type constituents and not large types. For example, don't construct a large function type and then unify it, but instead unify its arguments one-by-one. 
- [ ] Introduce a `expectTypeM(expected = , actual = )` which takes one "expected type" and one inferred type (e.g. for `IfThenElse` we expect a `Bool`). Another example e.g. `RecordSelect` where we know we expect a `Record` base type.

Expression to reconsider:

- [ ] `Exp.Apply`
- [ ] `Exp.Unary`
- [ ] `Exp.Binary`
- [ ] `Exp.IfThenElse`
- [ ] `Exp.Let`
- [ ] `Exp.LetRec`
- [ ] `Exp.LetRegion`
- [ ] `Exp.Match`
- [ ] Skip `Exp.Choose`
- [ ] `Exp.RecordEmpty`
- [ ] `Exp.RecordSelect`
- [ ] `Exp.RecordExtend`
- [ ] `Exp.RecordRestrict`
- [ ] `Exp.ArrayList`
- [ ] `Exp.ArrayNew`
- [ ] `Exp.ArrayLoad`
- [ ] `Exp.ArrayStore`
- [ ] `Exp.ArraySlice`
- [ ] `Exp.RefWithRegion` -- not sure?
- [ ] `Exp.InvokeConstructor`
- [ ] `Exp.InvokeMethod`
- [ ] `Exp.PutChannel`
- [ ] `Exp.Force`
- [ ] Not sure about Datalog exprs

**Comment by nicdard** [comment]
I would like to help with this :)

**Comment by nicdard** [comment]
Cool thanks a lot!

**Comment by magnus-madsen** [comment]
Fixed in master.
