### ISSUE TITLE
Design Choices: Abstraction for Datalog

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3297]
Introduce two new expressions (syntax to be determined):

- [ ] Abstraction: `[P, Q, ...] => e` where `e` is a Datalog expression.
- [ ] Application `[P => Q] e` where `e` is a Datalog expression.

The runtime semantics of `[P, Q, ...] => e` is to evaluate `e` to a Datalog value `v`. Then to alpha rename every predicate symbol other than P and Q to fresh names. This renaming must be done at runtime, it cannot be done at compile-time due to polymorphism. For example, this would break:

```
def f(x: a): #{ Q(...) } = [Q] #{ P(x). } // P is renamed.
f(123) <+> f("hello") // would fail if P is renamed statically. Thus P must be renamed for every abstraction.
```

The runtime semantics of `[P => Q] e` is to evaluate `e` to a Datalog value `v`. Then `Q` is alpha renamed in `v` to obtain `v'`. Then `P` is renamed to `Q` in `v'`. (Alternative is to add two Datalog rules that copy facts back and forth. Obviously this is not free.)

Typing:
- Abstraction: Unify `e` with a row with the expect predicates. Construct a new row.
- Application: Subtract and add. 

Task:
- [ ] Implement in Flix.
- [ ] Prove soundness.

TODO:
- [ ] Interaction with stratified negation?
- [ ] Interaction with type class constraints and polymorphism?
- [ ] Can renaming (application) be expressed as abstraction (hiding)? 
- [ ] We may consider two more primitive operations: `hide` (alpha renames predicate symbols to fresh names). `rename` renames one symbol to another (assuming no clash can occur).
- [ ] Relation rows?
- [ ] What about typos? Renaming or hiding things that do not exist.

Notes:

- Transitive reduction is unique on an acyclic graph. Can be made unique by SCC. (Useful for at least presenting these graphs).
- Represents rows more efficient? 
- Question of output vs extendable semantics.

**Comment by JonathanStarup** [comment]
This is the continuation of https://github.com/flix/flix/issues/3051?

**Comment by magnus-madsen** [comment]
This is somewhat different.
