### ISSUE TITLE
Don't crash on negative input to `Timer`

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3301]
Instead we can just wait for 0 time.

**Comment by magnus-madsen** [comment]
I think this is refering to some code in Timer.flix, but I am not 100% sure.

**Comment by mlutze** [comment]
> I think this is refering to some code in Timer.flix, but I am not 100% sure.

Yes, specifically the `sleepAndSend` function. We can also consider the `Ticker.sleepSendAndRepeat` function.

**Comment by magnus-madsen** [comment]
OK, so if either number is negative, we interpret it as 0? (Why not as infinity?)

**Comment by mlutze** [comment]
For me "I want this two seconds ago" means "I want this ASAP", not "I want this never" :)

**Comment by magnus-madsen** [comment]
OK, fair.

**Comment by ninaandrup** [comment]
Should I take a look at `Ticker.sleepSendAndRepeat`?

**Comment by magnus-madsen** [comment]
Yes

**Comment by ninaandrup** [comment]
The mention from PR `feat: List.splitAt` was a mistake
