### ISSUE TITLE
List.merge

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3302]
```scala
pub def merge(l1: List[a], l2: List[a]): List[a] with Order[a] = ...
```

**Comment by magnus-madsen** [comment]
Like append and sort, or what?

**Comment by mlutze** [comment]
Effectively yes, assuming the input lists are sorted, so it's in linear time. Like the `merge` part of `mergeSort`.

I just had to implement this myself, and was thinking that if OCaml's [batteries-not-included standard library](https://ocaml.org/api/List.html) has this, we probably should too.

**Comment by magnus-madsen** [comment]
Aha. Yes
