### ISSUE TITLE
Update stdlib function names that clash with keywords

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3307]
- [ ] `as`
- [ ] `and`
- [ ] `choose`
- [ ] `choose*`
- [ ] ~`forall`~
- [ ] `from`
- [ ] `get`
- [ ] `mod`
- [ ] ~`new`~
- [ ] `not`
- [ ] `or`
- [ ] `project`
- [ ] `query`
- [ ] `rem`
- [ ] `select`
- [ ] `solve`
- [ ] `try`

**Comment by mlutze** [comment]
What does crossed out mean here? Soft keywords?

**Comment by magnus-madsen** [comment]
It means we have to decide. We have useful functions called `new` and `forall`.

**Comment by magnus-madsen** [comment]
I would suggest to do one keyword at at time.

**Comment by mlutze** [comment]
`forall` could just become `forAll`

**Comment by magnus-madsen** [comment]
> `forall` could just become `forAll`

Not a big fan. Always do you mean the local variables or the keyword 😆

**Comment by magnus-madsen** [comment]
Did we solve this with `ReservedWords`?
