### ISSUE TITLE
Bitwise ops should bind tighter than equality

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3308]
This is currently a type error:
```
        getMethodModifiers(m) &&& 4096 != 0
```

The current correction is to add parentheses, but I don't think they should be necessary.

**Comment by mlutze** [comment]
Looks like our current precedence matches C's: https://en.cppreference.com/w/c/language/operator_precedence

It just feels wrong to me...

**Comment by JonathanStarup** [comment]
I've sometimes thought that maybe parenthesis should be obligatory unless you think that the average user knows the parsing rules involved. In this example I wouldn't know what the precedence is so I would have to look it up or experiment, so maybe a strict solution would be to disallow using non-common operators like `&&&` in a precedence dependent way. This is probably too controversial and restrictive to be implemented but I think I'd support it.

**Comment by magnus-madsen** [comment]
We plan to remove bitwise operators as custom syntax.
