### ISSUE TITLE
Non-Research Priorities

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3314]
A prioritized list of priorities for the working programmer:

Features:
- [x] Ensure that the examples on flix.dev, play.flix, and programming-flix are up to date.
- [x] Ensure that the documentation covers the central parts of the language (esp. type classes and effects).
- [x] Type errors and printing of types.
- [x] Improve Java interop. (How?)
- [x] #3328
- [x] #850
- [x] #3087
- [x] #1287
- [ ] #2510 (see also 1440, 2929)
- [ ] #3335
- [x] #2447

Bugs:
- [x] #2520
- [x] #2880

**Comment by stephentetley** [comment]
I've logged an issue with JVM interop - JVM interop - "creating interfaces" #3328

I also have another issue with passing arrays between Flix and Java, but I haven't yet reduced it to a small example.

**Comment by magnus-madsen** [comment]
Thanks Stephen. If you have more suggestions we are happy to hear about them!

**Comment by stephentetley** [comment]
A proper solution for the monad/effect problem rather than casting would be good:

https://github.com/flix/flix/issues/1649

This came up in the Traversable typeclass - see bottom of the thread: 

https://github.com/flix/flix/pull/2893

**Comment by JonathanStarup** [comment]
Maybe this should be added? #2546
