### ISSUE TITLE
Unconditional recursion check for local definitions

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3315]
This is currently allowed:
```scala
pub def f(): Bool =
    def g() = g();
    true
```

**Comment by magnus-madsen** [comment]
Question: Is this check really so important? Sure its nice, but would it better to take it out, and wait for a proper termination checker to arrive?

**Comment by mlutze** [comment]
It's a fair question. The other redundancy checks have certainly saved me from bugs in the past, but I don't think I've ever run into this error in the wild.

**Comment by magnus-madsen** [comment]
And if you did, you would probably discover it fairly quickly. Meanwhile it's a whole dedicated phase.

**Comment by mlutze** [comment]
https://github.com/flix/flix/pull/3318
