### ISSUE TITLE
Validation.product

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3317]
And perhaps other Applicative methods, since we don't have an applicative instance for it yet

**Comment by mlutze** [comment]
In the `Applicative` namespace we have `product`, `product3`, `product4`...

These should be implemented in `Validation`, specialized for the `Validation` type.

We might also want to look for other functions from `Applicative` to bring into the `Validation` namespace, as well as considering adding them to `Result`, `Option`, etc.

**Comment by magnus-madsen** [comment]
Possibly that description is not clear enough. Could you make a bullet point list? :)

**Comment by mlutze** [comment]
### What I want

The functions I am specifically requesting are:

- `Validation.product: Validation[t1, e] -> Validation[t2, e] -> Validation[(t1, t2), e]`
- `Validation.product3: Validation[t1, e] -> Validation[t2, e] -> Validation[t3, e] -> Validation[(t1, t2, t3), e]`
- `Validation.product4: Validation[t1, e] -> Validation[t2, e] -> Validation[t3, e] -> Validation[t4, e] -> Validation[(t1, t2, t3, t4), e]`
- `Validation.product5: Validation[t1, e] -> Validation[t2, e] -> Validation[t3, e] -> Validation[t4, e] -> Validation[t5, e] -> Validation[(t1, t2, t3, t4, t5), e]`

### More to consider:
#### Extending to other types

For parallelism, we can do the same functions for `Result`:
- `Result.product: Result[t1, e] -> Result[t2, e] -> Result[(t1, t2), e]`
- `Result.product3: Result[t1, e] -> Result[t2, e] -> Result[t3, e] -> Result[(t1, t2, t3), e]`
- `Result.product4: Result[t1, e] -> Result[t2, e] -> Result[t3, e] -> Result[t4, e] -> Result[(t1, t2, t3, t4), e]`
- `Result.product5: Result[t1, e] -> Result[t2, e] -> Result[t3, e] -> Result[t4, e] -> Result[t5, e] -> Result[(t1, t2, t3, t4, t5), e]`

And for `Option`
- `Option.product: Option[t1, e] -> Option[t2, e] -> Option[(t1, t2), e]`
- `Option.product3: Option[t1, e] -> Option[t2, e] -> Option[t3, e] -> Option[(t1, t2, t3), e]`
- `Option.product4: Option[t1, e] -> Option[t2, e] -> Option[t3, e] -> Option[t4, e] -> Option[(t1, t2, t3, t4), e]`
- `Option.product5: Option[t1, e] -> Option[t2, e] -> Option[t3, e] -> Option[t4, e] -> Option[t5, e] -> Option[(t1, t2, t3, t4, t5), e]`

But since the latter two have `flatMap`, I don't think it's as important.

#### Extending to other functions
- `Validation.productLeft: Validation[t1, e] -> Validation[t2, e] -> Validation[t1, e]`
- `Validation.productRight: Validation[t1, e] -> Validation[t2, e] -> Validation[t2, e]`
