### ISSUE TITLE
Re-engineer the `mut` keyword

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3322]
Remove the `mut` keyword (later we can re-introduce it once it has a meaning).

An option might be that: `mut MutSet[t]` becomes `MutSet[t, r]` and `r` is included in the effect of the function.

For example, this:

```
pub def transform!(f: a -> a & ef, s: mut MutSet[a]): Unit with Order[a] =
```

could be sugar for this:

```
pub def transform!(f: a -> a & ef, s: MutSet[a, r]): Unit & reg(r) with Order[a] =
```

(Note: Maybe `reg(r)` becomes `rw(r)`)

**Comment by magnus-madsen** [comment]
@jaschdoc Can I ask you to remove all uses of the `mut` keyword from the standard library?

Changing the parser here: https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Parser.scala#L1390 might be helpful.

**Comment by jaschdoc** [comment]
Yes, could you assign me to this?

**Comment by mlutze** [comment]
Tracking proposal from closed issue #3370 :

```scala
pub def addAll!(s1: MutSet[a, r1], s2: MutSet[a, r2]): Unit & Read(r1, r2), Write(r2) with Order[a] = ...
```

can become

```scala
pub def addAll!(s1: read MutSet[a], s2: write MutSet[a]): Unit with Order[a] = ...
```

**Comment by magnus-madsen** [comment]
@mlutze Do you want to take a stab at this? Maybe just start by writing a textual description of how it can be implemented.

**Comment by mlutze** [comment]
The simplest solution is to desugar this in the Weeder. We just introduce some fresh variables, apply them in the formal param types, add them to the type params, and add them to the effect.

The downside of doing it in the Weeder is that we probably end up with confusing type and kind errors. But if we introduce Region kinds down the road, it would help a lot in improving the error messages.

So IMO as a first implementation we can do it in the Weeder.

**Comment by magnus-madsen** [comment]
OK. We don't have to do this just yet, we still struggle with the Bool Unification part.

**Comment by magnus-madsen** [comment]
Too early. We need more experience.
