### ISSUE TITLE
Java Swing frame closes immediately after creation

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3327]
I have the following code:
```java
import javax.swing.*;  
public class Main {  
    public static void main(String[] args) {  
        JFrame frame = new JFrame();
            
        frame.setSize(200, 300);
        frame.setLayout(null);
        frame.setVisible(true);
    }  
}
```

I replicated this in Flix:
```scala
def main(_args: Array[String]): Int32 & Impure =
    import new javax.swing.JFrame() as newJFrame;
    let frame = newJFrame();

    JFrame.setSize(frame, 200, 300);
    JFrame.setLayout(frame, null as ##java.awt.LayoutManager);
    JFrame.setVisible(frame, true);

    0 // exit code
```

Where `JFrame` is a wrapper around the real JFrame imports.

The issue is that whereas in Java, the program stays alive after the window is created, Flix kills the program immediately after the window is created.

**Comment by magnus-madsen** [comment]
This exposes a weakness in our design. We enforce a return code and we call System.exit. This closes the program, but in an ordinary Java program execution can continue even if main exists. Not sure how we can fix that!

**Comment by magnus-madsen** [comment]
(This means Java also violates the structured concurrency principle).

**Comment by JonathanStarup** [comment]
I think we could support this in a nice way by allowing main to either 1) return unit which doesn't not call system exit 2) return Int which does call system exit.

As we talked about, you could also give a channel to the new thread that the main thread will wait for.

**Comment by magnus-madsen** [comment]
> I think we could support this in a nice way by allowing main to either 1) return unit which doesn't not call system exit 2) return Int which does call system exit.
> 
> As we talked about, you could also give a channel to the new thread that the main thread will wait for.

We could implement this by type checking `main` twice or alternatively by introducing:

```
class ExitCode[a] {
  def exit(x: a): Int32
}
```

then implement it for `Int32` and `Unit`. THEN we wrap main:

```
def main(...): ... = exp
// becomes
def main(...): ... = exit(exp)
```

Thoughts? Crazy?

**Comment by magnus-madsen** [comment]
Returning a String would then give "no instance for ExitCode` or whatever.

**Comment by magnus-madsen** [comment]
Alternative: We implement:

```
def exit(x: a): Int32 = match reifyType x {
  case ReifiedInt32 => x as Int32 // Does this actually work??
  case _                  => 0
}
```

and we wrap main in `exit`.

**Comment by magnus-madsen** [comment]
In either case we are not solving the problem of main actually exiting too early.

**Comment by mlutze** [comment]
I like the `ExitCode` class idea. We might `seal` the class to limit it to reasonable types.

**Comment by JonathanStarup** [comment]
> In either case we are not solving the problem of main actually exiting too early.

my intention was that if main return unit we do not call exit. so the behaviour of main changes if you return unit.

**Comment by JonathanStarup** [comment]
I think my opinion is that this is okay, since you can create a `Channel[Unit]` and give that to the spawned thread. The main can then wait for this channel. This could even be `Channel[Int32]`

**Comment by magnus-madsen** [comment]
https://github.com/rust-lang/rfcs/blob/master/text/1937-ques-in-main.md

**Comment by magnus-madsen** [comment]
We no longer call `System.exit`.
