### ISSUE TITLE
Add marshaling functions between Flix and Java for for Map, List and Set

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#3333]
In Flix `List`, `Map` and `Set` are entirely different types to their Java namesakes so if we are calling Java methods that produce or consume lists, maps or sets we need to marshal between the Flix and Java representations.

`Environment.getEnv` in Flix's standard library marshals a Java `Map` into a Flix one but the code is private to the module so it is not reusable (or polymorphic).

I think we should have polymorphic library functions to do this marshaling - I've an initial implementation here:

https://github.com/stephentetley/charset-locale/blob/master/src/Marshal.flix

Before I make a PR - should the marshaling functions go in the modules of their respective collection types?
 
Also the base numeric types in Java (`int`, `long` etc.) cannot be put in generic collections so I think we will need to add wrappers for their respective convertors to Flix's number types, e.g.:

~~~

def valueOf(i: Int32): ##java.lang.Integer = 
    import static java.lang.Integer.valueOf(Int32): ##java.lang.Integer & Pure;
    valueOf(i)

def intValue(i: ##java.lang.Integer): Int32 = 
    import java.lang.Integer.intValue(): Int32 & Pure;
    intValue(i)

~~~

Does anyone have preferences for the naming of these functions?

Thanks

**Comment by magnus-madsen** [comment]
We now have better interop. We still need Java generics support- but that can be tracked elsewhere.
