### ISSUE TITLE
LSP: Add Support for InlayHints

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3334]
The feature is not yet in LSP, but it is in VSCode:

https://github.com/microsoft/vscode/blob/778b74a2159983ba09568d069ef9c9ecd858f783/src/vscode-dts/vscode.d.ts#L4570-L4732

Google image search for "VSCode inline hint" to see what it is.

Ideas for inline hints:

- [ ] Types of let-bindings.
- [ ] Types of local variables in lambdas or defs.
- [ ] Effects (?)
- [ ] Formal parameters at call sites?
- [ ] Use of type classes?

**Comment by nicdard** [comment]
I can help with this :)

**Comment by magnus-madsen** [comment]
@nicdard Will work on this.

**Comment by nicdard** [comment]
https://github.com/flix/flix/issues/3383
