### ISSUE TITLE
Clean up Scopy stuff

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3351]
Since Scopedness, etc. seems to be replaced by Regions, we should clean up things relating to the old experiment

**Comment by magnus-madsen** [comment]
Yes.. What do you have in mind? Can you make a list :)

**Comment by mlutze** [comment]
At least the following:
- [ ] Scopedness.scala
- [ ] `scoped` keyword in Parser
- [ ] scoped field in VarSym
- [ ] tests
