### ISSUE TITLE
Refactor `Array` to use `ScopedArray`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3363]
Maybe split into multiple PRs?

**Comment by jaschdoc** [comment]
What do we do with the `Newable` instance? We could of course just return an array of a fixed size, say 8, but does it really make sense to talk about a `new ScopedArray(r)`?

**Comment by magnus-madsen** [comment]
I don't think refs and arrays will have newable instances.

**Comment by jaschdoc** [comment]
I think I've progressed as far as possible until #3836, #3811 and #3801 are closed.

**Comment by magnus-madsen** [comment]
Very cool!

What use of non-region arrays remain then?

**Comment by jaschdoc** [comment]
> Very cool!
> 
> 
> 
> What use of non-region arrays remain then?

In the entire library or just in `Array`?

**Comment by magnus-madsen** [comment]
> > Very cool!
> > What use of non-region arrays remain then?
> 
> In the entire library or just in `Array`?

Everywhere

**Comment by jaschdoc** [comment]
Should we rename this or close it? As of 2dbd2325c4bdf222254f75f1177671fb745921f4 we only have `ScopedArray`s. Should this issue maybe be renamed to something like "use regions in Array"?

**Comment by jaschdoc** [comment]
Yes, but just to avoid confusion, would it make sense to rename the issue then?

**Comment by magnus-madsen** [comment]
> Yes, but just to avoid confusion, would it make sense to rename the issue then?

I guess we have the other issue.
