### ISSUE TITLE
Add test cases for regions

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3367]
Add `Test.Exp.Region.flix` which tries to use regions in various ways.

**Comment by magnus-madsen** [comment]
I propose a systematic approach:

- Uses references and regions (e.g. could just duplicate most test cases for both).
- Test cases that use 1, 2, and 3 nested regions.
- Test cases that use 1, 2, 3 data structures nested inside each other (e.g. array inside array inside array).
- Test cases that mix both multiple regions and multiple data structures.

**Comment by jaschdoc** [comment]
Can we re-open this issue? @magnus-madsen
