### ISSUE TITLE
Debate whether to introduce read and write of a region

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3370]
We currently have:

```scala
pub def add!(x: a, s: MutSet[a, r]): Unit & reg(r) with Order[a] = ...
```

where the `reg(r)` parts specifies that the effect of `add!` is to *read* and *write* the mutable set `s`. 

In other words, we can say that `add!` "has an effect on region `r`". The proposal is to split the `reg(r)` effect into two: `Read(r)` and `Write(r)`. The advantage is that the programmer (and also the compiler) would have a lot more information about how the program behaves. 

Thus we would have:

```scala
pub def add!(x: a, s: MutSet[a, r]): Unit & Read(r) and Write(r) with Order[a] = ...
```

We have `Read(r)` because to update the set we still have to read it.

A more interesting case is:

```scala
pub def addAll!(s1: MutSet[a, r1], s2: MutSet[a, r2]): Unit & reg(r1) and reg(r2) with Order[a] = ...
```

which becomes:

```scala
pub def addAll!(s1: MutSet[a, r1], s2: MutSet[a, r2]): Unit & Read(r1) and Read(r2) and Write(r2) with Order[a] = ...
```

The syntax is a bit verbose: We might write:

```
Read(r1), Read(r2), Write(r2)
``` 

instead. Then we might say that write always includes read, so we could write:

```
Read(r1), Write(r2)
``` 

Or alternatively, allow you to group:

```
Read(r1, r2), Write(r2)
``` 

Thus, we could have:

```scala
pub def addAll!(s1: MutSet[a, r1], s2: MutSet[a, r2]): Unit & Read(r1, r2), Write(r2) with Order[a] = ...
```

Finally, and separately, #3322 proposes that this could be something like:

```scala
pub def addAll!(s1: read MutSet[a], s2: write MutSet[a]): Unit with Order[a] = ...
```

allowing us to entirely drop the region parameters and have them inferred.

**Comment by magnus-madsen** [comment]
@JonathanStarup @mlutze @jaschdoc @ninaandrup @stephentetley Do you have any thoughts? Do you foresee any issues?

**Comment by mlutze** [comment]
Grouping seems very nice, and I like the `(r1...)` syntax with parentheses rather than braces, to distinguish from a type application.

Will this mean getting rid of the `!` convention?

**Comment by magnus-madsen** [comment]
> Will this mean getting rid of the `!` convention?

Getting rid of it or we can enforce it as a check.

**Comment by JonathanStarup** [comment]
I remember Jonathan being against read as a subset of write. I remember being convinced but I forgot the example. I think its useful in some concurrency examples. The read and write keyword could still be assume that write includes read for usability but It would be cool if they were separate I think.

**Comment by magnus-madsen** [comment]
> Jonathan was against read as a subset of write. I remember being convinced but I forgot the example. I think its useful in some concurrency examples. The read and write keyword could still assume that write includes read for usability but It would be nice if they were separate.

They will have to be separate for technical reasons, so Jonathan will win by default :) But the question is whether the sugar for say `Write(r)` automatically includes `Read(r)` -- which I think it should!

**Comment by magnus-madsen** [comment]
@nicdard Another request for you:

I would like to write `\ {ef, Read(r1), Write(r1, r2)}` can we color `Read` and `Write` in to make them stand out? They are effects so a different color from most other stuff would be nice. Currently we use "purple" for `Impure` which `Read/Write` are set to replace.

**Comment by magnus-madsen** [comment]
Open to ideas:

![image](https://user-images.githubusercontent.com/2287953/159531282-f35cce24-5f99-48e6-accd-359147476893.png)

**Comment by magnus-madsen** [comment]
@jaschdoc Will you try to refactor `MutSet` to use our new amazing annotations? Note that there is no functional difference yet between read and write, but try your best to use both :)

**Comment by jaschdoc** [comment]
Sure thing :)

**Comment by jaschdoc** [comment]
Also, I personally like this version the most:
```scala
pub def addAll!(s1: read MutSet[a], s2: write MutSet[a]): Unit with Order[a] = ???
```
I think the signatures are becoming quite long (horizontally) with the current `reg(r)` syntax

**Comment by magnus-madsen** [comment]
> Also, I personally like this version the most:
> 
> ```scala
> pub def addAll!(s1: read MutSet[a], s2: write MutSet[a]): Unit with Order[a] = ???
> ```
> 
> I think the signatures are becoming quite long (horizontally) with the current `reg(r)` syntax

Agreed. That will come later.

**Comment by nicdard** [comment]
> @nicdard Another request for you:
> 
> I would like to write `\ {ef, Read(r1), Write(r1, r2)}` can we color `Read` and `Write` in to make them stand out? They are effects so a different color from most other stuff would be nice. Currently we use "purple" for `Impure` which `Read/Write` are set to replace.

I add them to the same category of impure then :)

**Comment by magnus-madsen** [comment]
Fixed in master.
