### ISSUE TITLE
Issue with type aliases and records

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3371]
This should be well-typed, but is rejected.

```scala
type alias EmptyRec = {}
pub def emptyRec(): EmptyRec = {}

pub def f(): { x :: Int32 } = { x = 1 | emptyRec() }
```

Bigger question: The lazy-unfold type alias strategy is meant to give nicer error messages. But it comes with a lot of issues like this. Should we rethink it?

**Comment by magnus-madsen** [comment]
Are you sure?

This program works:

```
type alias EmptyRec = {}
pub def emptyRec(): EmptyRec = {}

pub def f(): { x :: Int32 } = { +x = 1 | emptyRec() } // note the plus
```

but notably this does not:

```
type alias EmptyRec = {}
pub def emptyRec(): EmptyRec = {}

pub def f(): { x :: Int32 } = { x = 1 | {} }
```

This suggests the alias mechanism is fine.
