### ISSUE TITLE
vscode feature: derived instances

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#3378]
For users that do not know it would be very useful to see what the derived instances are and maybe even be able to insert them?

```
pub enum Things with Order {
    case A,
    case B
}
```
Sometimes its not intuitive what it might be so it would be nice to see

**Comment by magnus-madsen** [comment]
Do you mean to "show" the generated code?

**Comment by JonathanStarup** [comment]
> Do you mean to "show" the generated code?

yes, but if that is impractical, then a description in words. I just didn't even know where to look when I did it so I experimented with some code. Basically I wanted some documentation on what the derived classes do.

**Comment by magnus-madsen** [comment]
OK, so maybe more of a documentation issue.

**Comment by magnus-madsen** [comment]
I guess hover on TC constraint to show doc could also be useful.

**Comment by JonathanStarup** [comment]
> I guess hover on TC constraint to show doc could also be useful.

Doc for order could be nice but its moreso what the derivation does for A and B since its quite arbitrary. I would want something like "The derived order instance compares different cases by written order and pointwise by terms on two same cases" do you know what I mean?

**Comment by magnus-madsen** [comment]
> > I guess hover on TC constraint to show doc could also be useful.
> 
> Doc for order could be nice but its moreso what the derivation does for A and B since its quite arbitrary. I would want something like "The derived order instance compares different cases by written order and pointwise by terms on two same cases" do you know what I mean?

Yes. You say arbitrary, but I would actually say there is pretty much only one possible implementation of Eq, Order, and ToString that is reasonable.
