### ISSUE TITLE
Add InlayHints Provider

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3383]
See:

https://github.com/microsoft/vscode-languageserver-node/pull/772
https://github.com/microsoft/language-server-protocol/issues/956
https://github.com/microsoft/language-server-protocol/commit/c63b5f5266b3ffc1c83747f782cc70f0fa1e38e8

The documentation is a bit spread out at the moment.

**Comment by magnus-madsen** [comment]
We should discuss exactly what hints to provide. I suggest we start with:

- Hints for let-bindings (and other bindings)
- Hints for formal parameters in lambdas.

**Comment by nicdard** [comment]
I would like to help with this :)

**Comment by magnus-madsen** [comment]
@nicdard How about you start a draft on the `InlayProvider` and look into the VSCode API.

**Comment by nicdard** [comment]
Yes :) I have seen they merged the proposal in LSP 3.17, so I am wondering that maybe we can already start implementing them as in the upcoming lsp version, what do you think?

Otherwise we can try also first with the VSCode API I don't know how much time will pass for them to release the new protocol

**Comment by magnus-madsen** [comment]
> Yes :) I have seen they merged the proposal in LSP 3.17, so I am wondering that maybe we can already start implementing them as in the upcoming lsp version, what do you think?
> 
> Otherwise we can try also first with the VSCode API I don't know how much time will pass for them to release the new protocol

We can wait for LSP, but we can already start on the compiler-side I guess

**Comment by nicdard** [comment]
Sure!

**Comment by magnus-madsen** [comment]
In master.
