### ISSUE TITLE
Add region example

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3392]
Add an example of regions that goes like this:

```
def deduplicate(l: List[a]): List[a] with Eq[a] = 
  region r {
     ... allocate mut set...
     ... l.foreach(push to mut set)...
     ... l.filter(mut set member of)...
```

Add some comments.

It would be nice if this example could be added to examples but also used on the front page of flix.dev

**Comment by magnus-madsen** [comment]
@jaschdoc Do you want to take a stab at this?

**Comment by jaschdoc** [comment]
Yes! :)
