### ISSUE TITLE
Misc Type/LSP issues

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3402]
From #2452 

- [x] When hovering on function names at the place of definition the type is `Bool`. That seems slightly off?
- [x] Hovering on variables that are bound as parameters to a function yield the type `t4812954 & Pure` but in parameter list (where the variable is bound) gives type `a` (if it was declared as type `a`)
- [x] Effects (as you mentioned) have slightly different syntax but with no white space after the arrow. Intentional? Example: `k -> (k ->{ef} Comparison)`
- [ ] No hovering help on type aliases (but was that ever a feature)?
- [x] When using autocomplete for type class instances, the auto complete uses the new syntax for effects (as per the example above) but that's not valid as a Flix program.

- [ ] I'm not sure, if this is how it is supposed to be, but when hovering over a function imported from java, the message is a bit confusing with Pure and Impure.
```
import new java.io.File(String): ##java.io.File & Impure as newFile;
let javaFile = newFile(f);
```

**Comment by mlutze** [comment]
> I'm not sure, if this is how it is supposed to be, but when hovering over a function imported from java, the message is a bit confusing with Pure and Impure.

![Screenshot from 2022-04-01 09-34-28](https://user-images.githubusercontent.com/19153692/161217246-f3e156bc-52db-433d-95b3-38c9dfa15eaf.png)

We get this annotation because the lambda `newFile` is an effectful function, but simply referencing the lambda is Pure.
