### ISSUE TITLE
Add test cases for `new`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3404]

**Comment by jaschdoc** [comment]
I've added a single test in the related PR, but what specifically do you think we should test for the `new` expression?

**Comment by magnus-madsen** [comment]
> I've added a single test in the related PR, but what specifically do you think we should test for the `new` expression?

Just trivial stuff. Basically:

```
def mytest01() ... = region r {
  let x = new Foo;
  doOneThingWith(x)
}
```

then add 3 tests for each collection, and tests for our mutable collections. Something like this.

**Comment by magnus-madsen** [comment]
There is nothing deep. Its just to have tests if we change things. 

(Yes, you could argue that we already test new elsewhere, but that is common).

**Comment by magnus-madsen** [comment]
@jaschdoc What's the status on this. Blocked or?
