### ISSUE TITLE
Treat all top-level entities as implicitly public

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3437]

**Comment by mlutze** [comment]
Do we want any kind of `RedundantModifierError` so you can't put `pub` on a top-level function?

Otherwise the only effect of this change (as far as I can tell) is to remove all `Unused*` errors from top-level stuff.

**Comment by magnus-madsen** [comment]
Lets wait a bit with that error and see how it plays out.

**Comment by magnus-madsen** [comment]
I would just start by treating all top-level things as public.

**Comment by mlutze** [comment]
Do you think it's better to add the `pub` modifier implicitly or to conditionally disable the redundancy check? The former seems cleaner but unnecessarily adding things to the AST that aren't in the source may cause trouble (like with type vars, etc.)

**Comment by magnus-madsen** [comment]
> Do you think it's better to add the `pub` modifier implicitly or to conditionally disable the redundancy check? The former seems cleaner but unnecessarily adding things to the AST that aren't in the source may cause trouble (like with type vars, etc.)

Lets implicitly add the `pub` modifier. I think that is okay and fits most closely with what you would expect.
