### ISSUE TITLE
Add `unification.BoolMinimization`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3440]
Add a class `BoolMinimization` which contains its own representation of Boolean formulas and functions for converting between types and this internal representation.

In particular, I think `BoolMinimization` should have a type like:

```
sealed trait Formula

object Formula {
  case object True
  case object False
  case class Var(Type.Var)
  case class Not(Formula)
  case class And(List[Formula])
  case class Or(List[Formula])
}
```

It should have smart constructors, e.g. `mkOr` etc. 

It should have `fromType` and `toType`.

It should have a function `toNNF` to convert to NNF.

It should have a function `toCNF` to convert to CNF.

Finally, it should have some form of unit propagation mechanism.

**Comment by JonathanStarup** [comment]
You can assign me

**Comment by magnus-madsen** [comment]
Will do. Jakob will soon have some examples that exhaust the compiler.

**Comment by magnus-madsen** [comment]
Example from Jakob:

```
opaque type MutMap1[k: Type, v: Type, r: Region] = ScopedRef[Map[k, v], r]

pub def mergeWithKey!(f: (k, v, v) -> v & ef, m1: MutMap1[k, v, r1], m2: MutMap1[k, v, r2]): Unit \ { ef, Read(r1, r2), Write(r1, r2) } with Order[k] =
    let MutMap1(mm1) = m1;
    let MutMap1(mm2) = m2;
    let x = deref mm1;
    let y = deref mm2;
    let res = Map.unionWithKey(f, x, y);
    mm2 := res
```

gets a complicated Boolean effect.

**Comment by JonathanStarup** [comment]
From our previous talks I thought you wanted DNF, is CNF a typo or do you want conjunctive normal form?

**Comment by magnus-madsen** [comment]
I want CNF to have unit propagation.

**Comment by JonathanStarup** [comment]
I see, makes sense. So at some point this class should have both transformations?

**Comment by magnus-madsen** [comment]
Even better example:

```
opaque type MutMap1[k: Type, v: Type, r123: Region] = ScopedRef[Map[k, v], r123]

pub def mergeWithKey!(f: (k, v, v) -> v & ef, m1: MutMap1[k, v, r1], m2: MutMap1[k, v, r2]): Unit \ { ef, Read(r1, r2), Write(r1, r2) } with Order[k] =
    let h = () -> {
        let MutMap1(mm1) = m1;
        let MutMap1(mm2) = m2;
        let x = deref mm1;
        let y = deref mm2;
        let res = Map.unionWithKey(f, x, y);
        mm2 := res
        };
    h()
```

hover on `h`.
