### ISSUE TITLE
Crash when deriving `Order` for empty enum

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3443]
```scala
pub enum E with Eq, Order
```
crashes with
```
head of empty list
```

**Comment by magnus-madsen** [comment]
`IllegalDerivationForEmptyEnum` or something like that? And we can just throw it on all the type classes than can be derived.

**Comment by mlutze** [comment]
I don't think this should be illegal though.

**Comment by magnus-madsen** [comment]
> I don't think this should be illegal though.

Why? It is most likely a mistake from the programmer and we should try to help.

There is only one empty type anyway right? And its name is Void. Should we have that and should it have an equals etc? Maybe, but then at least it would be built into the language.

**Comment by mlutze** [comment]
> There is only one empty type anyway right? And its name is Void. Should we have that and should it have an equals etc? Maybe, but then at least it would be built into the language.

Or maybe, all empty types are isomorphic to the void type. But I think that empty types could still be useful. For example, if we have a phantom type.

```scala

enum Red
enum Black

enum RBTree[color, a] { ... }

```

If we want to derive equality or ToString on this then we need a `ToString` or `Eq` instance for `Red` and `Black`

**Comment by magnus-madsen** [comment]
Hmmm. But if it is a phantom type why would it participate in a type constraint?

**Comment by magnus-madsen** [comment]
I would rather ban it and then re-allow it if there is a convincing use case.

**Comment by magnus-madsen** [comment]
This is also a good starter issue.

**Comment by dignissimus** [comment]
I'd like to work on this

**Comment by magnus-madsen** [comment]
> I'd like to work on this

The trail starts in `Deriver.scala`
