### ISSUE TITLE
LSP: Type variables

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3463]
Remaining after https://github.com/flix/flix/issues/2510

- [x] type variables in effects
- [x] type variables in type constraints
- [x] hover
- [x] rename
- [x] find references
- [x] investigate weird coloring of non-type variables
- [x] investigate missing coloring of type variables
- [x] goto definition
- [x] highlight

![Screenshot from 2022-04-01 22-29-49](https://user-images.githubusercontent.com/19153692/161336976-45f2ebdc-63aa-4812-a7c3-51842b381c8c.png)

**Comment by magnus-madsen** [comment]
Rename still needs to handle:

- enums
- type aliases
- type classes

**Comment by magnus-madsen** [comment]
Why this:

![image](https://user-images.githubusercontent.com/2287953/161617496-c96367be-286f-423e-bd3b-02cf2ea9f614.png)

?

**Comment by mlutze** [comment]
> Why this:
> 
> ![image](https://user-images.githubusercontent.com/2287953/161617496-c96367be-286f-423e-bd3b-02cf2ea9f614.png)
> 
> ?

Still haven't figured that out...

**Comment by mlutze** [comment]
> Why this:
> 
> ![image](https://user-images.githubusercontent.com/2287953/161617496-c96367be-286f-423e-bd3b-02cf2ea9f614.png)
> 
> ?

This is linked to how we handle fparams and substitutions in the Typer.
In `Typer.typeCheckDecl` we create a substitution during inference. We call `visitSpec` on the def's `spec`, which in turn applies the substitution to the types of the formal parameters. This substitution may map from type variables in the formal parameters to type variables in the expression. (E.g. `k` to `t8675309`).

Since after we apply the substitution, the formal params no longer contain the original type variables, the indexer/semantictokenfinderthingy does not recognize their locations.

Q: Why is the first `k` and `v1` colored?
A: SemanticTokensProvider traverses type parameters separately from formal parameters. The first `k` and `v1` are the _declaration_ sites of these tvars in addition to `use` sites.

Q: Why is the last `k` colored?
A: `Typer.visitSpec` does not traverse the return type or the effect for some reason.

Q: What can we do about this?
A: We have some hacking options for fixing this (e.g. somehow forcing the substitution to prioritize keeping the formal params), but really we need to rework substitution/type inference altogether and do it the "right" way.
