### ISSUE TITLE
Document how to import inner classes

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#3470]
If you want to reference the class inner class [`HttpClient.Version`](https://docs.oracle.com/en/java/javase/12/docs/api/java.net.http/java/net/http/HttpClient.Version.html) you have to write `##java.net.http.Httpclient$Version`. This fact should probably be present on [the interop page of flix.dev](https://doc.flix.dev/interoperability/)

**Comment by paulbutcher** [comment]
Ah! Yes, I think so.
