### ISSUE TITLE
[Typer] Type Constructor Errors

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#348]
The following:

```
def f(x: Result[Int]): Unit = ???
```

should not type check (because Result is a type constructor of two arguments).

**Comment by magnus-madsen** [comment]
Requires an implementation of kinds.

**Comment by magnus-madsen** [comment]
@mlutze Do you know if this now fails? :)

**Comment by mlutze** [comment]
This is still not caught. I'll see what I can do!

**Comment by magnus-madsen** [comment]
So, `Result[Int]` is a valid type. It is just that it has kind `* -> *`, and not kind `*` as required for types that have values (e.g. variables).

Do you think we should add a check (somewhere???) that ensures that variables/formal parameters/??? have kind `*`?

**Comment by mlutze** [comment]
Yes, I think that's the right way to do it.

The places we'll need to perform this check are:
* function parameters
* enum cases
* predicates
* anywhere else?


Do we allow/want to allow partial application in type aliases?

```
type alias IntResult = Result[Int]
```

**Comment by magnus-madsen** [comment]
> Do we allow/want to allow partial application in type aliases?

Yes.

I will try to think of other places for the check. Would this be in the Resolver?

**Comment by mlutze** [comment]
Yes, I think it makes sense to do it there since this sort of kind error arises upon resolution.

**Comment by magnus-madsen** [comment]
I think only required for function parameters and enum cases.

Not for enums themselves nor for predicates/relations/lattices/type aliases.
