### ISSUE TITLE
Use `VarText` in `Typer` to give meaningful variable names

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3481]
- Use meaningful FallBack type variable names.
- Require all type variables to have a fallback name?

**Comment by magnus-madsen** [comment]
@mlutze Do you want to take a stab at this?

**Comment by magnus-madsen** [comment]
Oh, I guess maybe we want to enforce that there is always a fallback name.

**Comment by magnus-madsen** [comment]
We can close?

**Comment by mlutze** [comment]
We have not yet enforced that there is always a fallback name.
