### ISSUE TITLE
Entry point code lens shows for any array type

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3486]
E.g.
```scala
def basldifuhsrlgi(args: Array[Int32]): Unit = ???
```

**Comment by magnus-madsen** [comment]
https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/api/lsp/provider/CodeLensProvider.scala#L106

**Comment by mlutze** [comment]
This is made moot by other entry point decisions.
