### ISSUE TITLE
outlaw variables that occur in lattice position and key position in rule bodies

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#3489]
`A(x) :- B(x; l), C(l, x).` should be disallowed.

Should `A(x) :- fix B(x; l), C(l, x).` be allowed?

**Comment by magnus-madsen** [comment]
What's the status on this?

**Comment by magnus-madsen** [comment]
@JonathanStarup What's the status on this?

**Comment by JonathanStarup** [comment]
Ah, sorry about the hanging issue.

In short, its closed.

The only remaining question is whether a rule like `A(2) :- fix B(2; x), C(2, x).` should be allowed. Right now its not but maybe that's overly cautious.
