### ISSUE TITLE
Add Early and Late TreeShaker

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3504]
- [ ] Rename `TreeShaker` to `LateTreeShaker`.
- [ ] Add `EarlyTreeShaker` as a copy immediately before the `Monomorph` phase.
- [ ] Determine if there is any performance impact.

**Comment by jaschdoc** [comment]
I think I may need help for this. I tried doing this a couple of months ago but without any success really. Maybe we should discuss in person or @mlutze can help me with this at some point?

**Comment by magnus-madsen** [comment]
I think this can wait till the internship starts and then we should sit down and talk about it :)
