### ISSUE TITLE
LSP: Hide `@Internal` names from autocomplete, etc.

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3514]

**Comment by magnus-madsen** [comment]
@nicdard Did we already do this? I seem to remember, but maybe I am wrong.

**Comment by nicdard** [comment]
I am not sure, need to check better, I don't recall any work on autocomplete to be fair :sweat_smile: 

Also, sorry for the long waiting, but now I am back to work :)

**Comment by magnus-madsen** [comment]
For example, `Fixpoint.unsafeCast` is marked as `@Internal` and should be hidden from auto-complete.

In the same way that we presumably hide non-pub functions?

**Comment by magnus-madsen** [comment]
@paulbutcher recently rewrote the auto-completer, perhaps he wants to take a stab at this?
