### ISSUE TITLE
Update `main` in project and in documentation

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3518]
The new signature of `main` is simply:

```
def main(): Unit & Impure= ...
```

With arguments:

```
def main(): Unit & Impure= 
  let args = Environment.getArgs();
  ...
```

This ticket has two tasks:

- [ ] Update the signatures of all `main` functions in the Flix project. We now have many signatures that look like:

```
def main(): Int32 & Impure =
   ...
   0 // exit code
```

these should simply become:

```
def main(): Unit & Impure =
   ...
```

Most end with a `println` which returns `Unit` so it works out.

- [ ] Update our website and all documentation.

**Comment by magnus-madsen** [comment]
@ninaandrup Can I ask you to do this? :) This take precedence over the `foldRight` stuff. 

Let me know if you nee more information. TLDR: The goal is to change return types to `Unit` and get rid of `0 // exit code` things.

**Comment by magnus-madsen** [comment]
@stephentetley Heads-up. This is a breaking change. Sorry.

On the upside, you can now run: 

```
java -jar c:\\tmp\\flix\\flix.jar --entrypoint Foo/Bar.qux c:\\tmp\\flix\\src\\Main.flix
```

and it will run ` Foo/Bar.qux` as main and print the result (if non-Unit):

![image](https://user-images.githubusercontent.com/2287953/162964213-25f6ebd3-6db1-4465-adcc-398a3c6e4036.png)

**Comment by magnus-madsen** [comment]
@ninaandrup Also, main should no longer be `pub`.

**Comment by stephentetley** [comment]
> @stephentetley Heads-up. This is a breaking change. Sorry.

Thanks Magnus, no problem. 

BTW I've just discovered you can include *.pkg as well as flix source files in the command line to the Flix compiler. That is a really helpful feature.

**Comment by ninaandrup** [comment]
> @ninaandrup Can I ask you to do this? :) This take precedence over the `foldRight` stuff.
> 
> Let me know if you nee more information. TLDR: The goal is to change return types to `Unit` and get rid of `0 // exit code` things.

Sure, I'll start this today :)

**Comment by magnus-madsen** [comment]
Whats the status on this?

**Comment by ninaandrup** [comment]
> Whats the status on this?

Everthing should be up to date :-)
