### ISSUE TITLE
Build master jar

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3528]
The nightly jar has the disadvantage of being as much as 24 hours behind. It would be nice to have a _really_ bleeding edge jar available.

**Comment by JonathanStarup** [comment]
> The nightly jar has the disadvantage of being as much as 24 hours behind. It would be nice to have a _really_ bleeding edge jar available.
> 

If the workload is a concern it could also be triggered on request.

**Comment by magnus-madsen** [comment]
Once we get the build server...

**Comment by jaschdoc** [comment]
> Once we get the build server...

Is that going to be on AWS or what are your plans? I took a brief look at it, but I'm not sure I have any input you couldn't figure out yourself :)

**Comment by magnus-madsen** [comment]
The plan is for the new build server to build a JAR for every PR merged into master and then to make these available.

**Comment by magnus-madsen** [comment]
Plan is to build a JAR on every merge (once the new shiny server is online).
