### ISSUE TITLE
Parallelize JVM Backend

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3531]
We should be able to generate many of the classes in parallel.

**Comment by JonathanStarup** [comment]
You can assign me

**Comment by magnus-madsen** [comment]
Isnt the backend already fairly parallel? Is there even room, for more parallelism?

**Comment by JonathanStarup** [comment]
all of the gen calls in the backend could be parallel (after the type collection stuff)

**Comment by magnus-madsen** [comment]
Yeah, but each mini phase is already parallel right?

**Comment by JonathanStarup** [comment]
I rember it as being done some places and some places not. There's also multiple independent ast passes done in sequence to collect the different kind of types.

**Comment by magnus-madsen** [comment]
Fixed in master.
