### ISSUE TITLE
Add Flix support to Highlight.js

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3539]

**Comment by magnus-madsen** [comment]
@jaschdoc Perhaps this is something you could look into next week? :) Just to get extremely basic syntax support (probably by re-using some other language's grammar). 

(We can use this for doc.flix.dev which is based on Highlight.js).

**Comment by magnus-madsen** [comment]
Feel free to ping me on Gitter with questions.

**Comment by jaschdoc** [comment]
Is this student programmer label intentional (was added a while back)? :)

**Comment by magnus-madsen** [comment]
Its up to you :)

**Comment by jaschdoc** [comment]
I've been reading up on the docs for contributing to highlight.js. I think we should create a repo under the Flix organization where we host the language definition / grammar for Flix (for highlight.js). Thoughts?

https://github.com/highlightjs/highlight.js/blob/main/docs/language-contribution.rst (first part)

**Comment by magnus-madsen** [comment]
Oh, but they write this "Request a repository at the highlightjs organization"

**Comment by magnus-madsen** [comment]
Reading that document makes me super confused. But I guess they are trying to say that they do not accept language PRs?

**Comment by jaschdoc** [comment]
Yes, so the way I understand it is: They don't accept language PRs into the core anymore so any new functionality is through 3rd party language extensions which means a repo that's hosted and maintained by someone else. They do, however, accept hosting the new language extension **repository** in the highight.js organization so the extensions are all in one place (and possibly make it seem more legit?). This also means that people have to manually add flix support to highlight js when they want to use it on their website (by downloading our language specification for highlight.js). Does that make sense?

**Comment by magnus-madsen** [comment]
Yes. So should we create a flix/highlight.js repo? What should be in this?

**Comment by jaschdoc** [comment]
> Yes. So should we create a flix/highlight.js repo? What should be in this?

Yes I think so. This is where our language definition of flix for highlight.js is hosted. So it probably contains a few js files and possibly some other stuff too.

**Comment by magnus-madsen** [comment]
@jaschdoc I have created flix/highlight.js and given you (write) access. I suggest you still work in PRs though.

**Comment by magnus-madsen** [comment]
@jaschdoc If you are a bit blocked on the other tickets, this might be something useful to work on.

**Comment by jaschdoc** [comment]
Could I ask you to create an empty repo where the language definition itself will be hosted? The highlight.js fork will still be necessary (I think) but for the language specification we need a separate repo

**Comment by magnus-madsen** [comment]
I think you just add it to their repository

**Comment by magnus-madsen** [comment]
Next to the other languages, no?

**Comment by jaschdoc** [comment]
No, they no longer host language definitions in the core repo.

**Comment by magnus-madsen** [comment]
Ok. Can you start in your own and then i will create one later.

**Comment by jaschdoc** [comment]
We now have basic syntax highlighting. I think we can close the issue :smile:
