### ISSUE TITLE
Add Parser support for AE

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3542]
Preparation:
- [x] Rename effects to purity. (e.g. `eff -> pur`).

Constructs:

- [x] Introduce `Declaration.Eff`.
- [x] Introduce `Expression.Do`.
- [x] Introduce `Expression.Resume`.
- [x] Introduce `Expression.TryWith` (combined with `try`...`catch`)
- [x] Introduce syntax for effect sets.
- [x] Introduce kind for effect sets.
- [x] (Introduce `use` syntax for effects)?

**Comment by magnus-madsen** [comment]
The form of try-with should be:

```
try e with Effect {
  def op1(....) = ...
}
```

where `Effetct` is the name of the effect and `op1` is one of its unqualified operations.

**Comment by magnus-madsen** [comment]
- Allow `try e with Foo` (no braces)

**Comment by mlutze** [comment]
```ebnf
effect set with empty ::= effect set | "{}";
effect set ::= singleton | set | "{", "Pure", "}";
set ::= "{", { singleton }, "}";
singleton ::= read | write | effect | plus | minus | intersect | complement | "Impure";
read ::= "Read", args;
write ::= "Write", args;
effect ::= ? upper name ?;
plus ::= singleton, "+", singleton;
minus ::= singleton, "-", singleton;
intersect ::= singleton, "&", singleton;
complement ::= "~", singleton;
args ::= "(" { var } ")";
var ::= ? lower name ?;
```

**Comment by magnus-madsen** [comment]
Feel free to split into multiple PRs if relevant.
