### ISSUE TITLE
Add Weeder support for AE

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3543]
Preparation:
- [x] Rename effects to purity. (e.g. `eff -> pur`).

Constructs:

- [x] Introduce `Declaration.Eff`.
- [x] Introduce `Expression.Do`.
- [x] Introduce `Expression.Resume`.
- [x] Introduce `Expression.TryWith`.

Checks:
- [x] Effects must return `Unit`.
- [x] Reject effects with type parameters (but allow them to be parsed).
- [x] Duplicate Modifier.
- [x] Require public (or?)
- [x] `resume` only under handlers
- [x] Ban effects called `Pure`, `Read` and `Write`. (Maybe even have an error for each to explain whats up)
- [x] Ban effects on operations
- [x] Ban ascriptions of op formal parameters

**Comment by mlutze** [comment]
What's the plan for imports? Just Pure/Impure for now?
