### ISSUE TITLE
Modify variable order in BoolUnification

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3568]
- First fresh variables/synthetic variables.
- The real variables.

**Comment by magnus-madsen** [comment]
In #3569 we currently use Ast.VarText, but I think we need something more solid.

**Comment by magnus-madsen** [comment]
This is indirectly related to: #3548

**Comment by magnus-madsen** [comment]
Maybe we should use source location something something?

**Comment by mlutze** [comment]
Source location and VarText are both unreliable at the moment, but VarText is probably better. What we really need is to enforce that `VarText.type == VarText.Fallback <==> SourceLocation.type == Synthetic`

**Comment by magnus-madsen** [comment]
I already switched to using SourceLocationType or whatever its called.
