### ISSUE TITLE
Typeclass Troubles

### ISSUE THREAD

**Issue by milse113** [flix/flix#3575]
```
class Eq[a] {
    def eq(x: a, y: a): Bool
    def neq(x: a, y: a): Bool = not Eq.eq(x, y)
}
```
This code doesn't compile, despite being from the official page. When adding pub before both defs, making:
```
class Eq[a] {
    pub def eq(x: a, y: a): Bool
    pub def neq(x: a, y: a): Bool = not Eq.eq(x, y)
}
```
It fixes the initial error, but an error saying "Each signature of a lawful class must appear in at least one law." still persists. I'm completely unable to make any typeclasses because of this error

**Comment by magnus-madsen** [comment]
Hello @milse113. Thanks for reporting this.

Are you using the latest stable or on master?

We have recently been making changes, so I think maybe the website is now ahead of the new syntax?

In any case, this should work on *master*: https://github.com/flix/flix/blob/master/main/src/library/Eq.flix

**Comment by milse113** [comment]
I'm using whatever VSCode automatically downloads, which I believe is stable

**Comment by milse113** [comment]
@magnus-madsen I'm using whatever VSCode automatically downloads, which I believe is stable. Should I be using master?

**Comment by magnus-madsen** [comment]
You can grab a nightly from here: https://flix.dev/nightly/

Put in the root of your project. Then this syntax should work:

```
class Eq[a] {
    pub def eq(x: a, y: a): Bool
    pub def neq(x: a, y: a): Bool = not Eq.eq(x, y)
}
```

**Comment by mlutze** [comment]
Note that `Eq` is already defined by the standard library, so the collision there might be related.

**Comment by milse113** [comment]
@magnus-madsen it works!

@mlutze I checked for that by refactoring `Eq` to `Eqq` before making the PR; I should've specified that my bad. Whatever the case, my problem is seemingly solved! Thanks all!

**Comment by magnus-madsen** [comment]
No worries- and thanks for reporting it!

By the next stable release we should ensure our docs and impl are fully in sync.

Have fun with Flix!
