### ISSUE TITLE
Boolean Minimization: Experiment with Quine McCluskey

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3580]
TBD

See https://en.wikipedia.org/wiki/Quine%E2%80%93McCluskey_algorithm

**Comment by JonathanStarup** [comment]
@magnus-madsen maybe we should create an overview ticket for all the boolean stuff?

**Comment by magnus-madsen** [comment]
Yes, I will do that. I think Robert will attempt an implementation of Quine McCluskey (in Java (?))

**Comment by JonathanStarup** [comment]
Okay, cool 👍
