### ISSUE TITLE
Boolean Minimization: Experiment with BDDs

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3581]
We want to experiment with using BDDs to minimize the Boolean formulas that come out of the SVE algorithm.

Concretely, I envision the following steps:

- [ ] Add the PJBDD package to the Flix project
  - see https://gitlab.com/sosy-lab/software/paralleljbdd
  - see https://www.sosy-lab.org/research/pub/2021-ATVA.PJBDD_A_BDD_Library_for_Java_and_Multi_Threading.pdf
- [ ] Add a class `BoolMinViaBDDs` to `/main/src/ca/uwaterloo/flix/language/phase/unification`
- [ ] The class should have a function that take a `Type` and calls `BoolFormula.fromType` to convert it to a Boolean formula.
- [ ] Then this formula should be converted to a BDD using the library (thus minimizing it implicitly). 
- [ ] Then the BDD should be converted back to a formula which is converted back to a type with `BoolFormula.fromType`.

That's it. Then we should make sure that all tests run and see if performance improves or degrades.

After that, if there is time/interest, we could experiment with rewriting these 20 lines: https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/unification/BoolUnification.scala#L126-L143 to use the BDD package directly.

**Comment by AnnaBlume99** [comment]
**Experiment 0: Cost of using PJBDD library**
Using the PJBDD library requires two dependencies:

- -	pjbdd-v.1.0.10-10.jar (257 KB)
- -	guava-31.1-jre.jar (2891 KB)

Total: 3148 KB

**Experiment 1: BDD minimization vs table minimization**
-	testAll time
o	Minimization with table:
	2 min 56 seconds
	2 min 58 seconds
o	Minimization with BDD
	3 min 14 sec
	3 min 17 sec

-	sum size of formulas
o	Minimization with table: 4642
o	Minimization with BDD: 1545

-	run Main with Xbenchmark-throughput
o	Minimization with table:
Throughput (best): 17.698 lines/sec (with 16 threads.)
  min:  6.830, max: 17.698, avg: 15.714, median: 17.086
  The highest throughput was in iteration: 4 (out of 10).
  The ratio between the best and worst iteration was: 2,6x.
Finished 10 iterations on 61.482 lines of code in 42 seconds.
o	Minimization with BDD:
Throughput (best): 18.219 lines/sec (with 16 threads.)
  min:  6.622, max: 18.219, avg: 15.734, median: 17.103
  The highest throughput was in iteration: 7 (out of 10).
  The ratio between the best and worst iteration was: 2,8x.
Finished 10 iterations on 61.482 lines of code in 42 seconds.

**Comment by magnus-madsen** [comment]
Looks very promising. Nice!

**Comment by magnus-madsen** [comment]
@jacopol Check out the above initial experiment. (Yes, it does not beat the table, but almost, and we still do a lot of stupid conversion back and forth. In the next experiments we will give BDDs an even more fair playing ground.)
