### ISSUE TITLE
Rename `ScopedRef`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3590]
The goal of this PR - through several steps - is to refactor `Ref` to always be of the form `Ref[t, r]`, i.e. with both a type and region parameter. 

We take these steps (each in a separate PR):

- Rename the type alias `Ref` (in `Prelude.flix`) to `FooRef`. Refactor as required.
- Rename `ScopedRef` to `Ref` in `Resolver` and `FormatType`. Refactor as necessary. 
- Remove `FooRef`.

**Comment by magnus-madsen** [comment]
I think this can be undertaken.

**Comment by magnus-madsen** [comment]
@jaschdoc I would like you to work on this soon :)

**Comment by jaschdoc** [comment]
Could you add a high priority label? :)

**Comment by magnus-madsen** [comment]
> Could you add a high priority label? :)

Marking things high-priority is my middle name :D

**Comment by magnus-madsen** [comment]
Done?
