### ISSUE TITLE
Refactor `toMutDeque`, `toMutList`, `toMutMap`, `toMutSet` to use regions

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3610]
Refactor all:

- [ ] toArray
- [ ] toMutDeque
- [ ] toMutList
- [ ] toMutMap
- [ ] toMutSet

to use regions. 

This applies both to collection namespaces and to classes. 

The region parameter should be last. (At least that's the current thinking).

**Comment by jaschdoc** [comment]
Come to think of it, I think regions should be **before** the subject in the parameter order so we can still use `|>`:
```scala
pub def toArray(c: Chain[a], r: Region[r]) : ScopedArray[a, r] \ Write(r) = ??? // breaks pipelines like below

    pub def sort(c: Chain[a]): Chain[a] with Order[a] = region r {
        c |> toArray(r) |> Array.sort |> Array.toChain
    }
``

**Comment by magnus-madsen** [comment]
Added your comments to #3601. I don't have an answer, so I suggest we keep them last for now (that works with "implicit regions" btw.) Then later we will have to decide (and maybe refactor).
