### ISSUE TITLE
Prevent substitution of type variables in function signatures

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3643]
After type inference, if there is exactly one boolean variable in the type signature:
- `ef -> t = variable's mapping in sig`
- make `ef` rigid
- `subst2` = unify `ef` and `t`
- make `ef` non-rigid in `subst2`
- use `subst1 @@ subst2` as the substitution moving forward

In the future we will do this for all tvars, but limiting to one boolean variable for now.

The idea is that this will prevent the variable in the signature from being replaced by the substitution.

**Comment by magnus-madsen** [comment]
No longer relevant?

**Comment by mlutze** [comment]
No longer relevant.
