### ISSUE TITLE
Completely eliminate FreeVar

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3658]

**Comment by JonathanStarup** [comment]
I still think that the current situation where it is freevars until lamba lift is sensible. before that point it is actually a list of free variables instead of arguments to a function.

**Comment by magnus-madsen** [comment]
> I still think that the current situation where it is freevars until lamba lift is sensible. before that point it is actually a list of free variables instead of arguments to a function.

What's the gain? If we don't use that information than we always try to have the most general information.
