### ISSUE TITLE
Build Server Setup - Imhotep

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3672]
- [ ] Add A record for `build.flix.dev` (or similar?)
- [ ] Change passwords.
- [ ] Configure something like `arewefast.flix.dev` but run action on:
- [ ] PR merge.
- [ ] Request from bot (?)

In addition to time, we should track the specific PR id. 

See https://github.com/appleboy/ssh-action

**Comment by mlutze** [comment]
What's the status on this?

**Comment by magnus-madsen** [comment]
I guess done?

**Comment by magnus-madsen** [comment]
Well, except the do statistics on merge part.
