### ISSUE TITLE
[Library] Float32 and Float64

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#368]
Minor changes:

- Add a function `isFinite(x: Float32)` which returns true if `x` is a non-infinite and non-NaN number.
- Add a function `isInfinite(x: Float32)` which returns true if `x` is an infinite and non-NaN number.
- Add a function `isNan(x: Float32)` which returns true if `x` is NaN***.
- Rename `undefined` to `nan`.
- ***Fix test cases for undefined()***

similarly for Float64.

*** I don't know if you can actually implement this without additional compiler support (?)

**Comment by mhyee** [comment]
[JLS Section 15.21.1](http://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.21.1):

> Floating-point equality testing is performed in accordance with the rules of the IEEE 754 standard:
>
>    * If either operand is NaN, then the result of `==` is `false` but the result of `!=` is `true`.
>
>      Indeed, the test `x!=x` is `true` if and only if the value of `x` is NaN.

**Comment by magnus-madsen** [comment]
@mhyee Thanks, that is great. I did not know that. So:

```
def isNan(x: Float32): Bool = x != x
```

**Comment by magnus-madsen** [comment]
By the way, should it be `nan` or `naN`. Flix does not allow uppercase function names.

**Comment by mhyee** [comment]
I think `nan` looks nicer than `naN`.

**Comment by magnus-madsen** [comment]
I agree that `nan` is more pretty. So we should have `nan` and `isNan`.

**Comment by magnus-madsen** [comment]
Fixed in #392
