### ISSUE TITLE
add `zipWithIndex` to select data structures

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#3682]
Add `zipWithIndex` to all (ordered) collections and to Foldable. 

Related to #3666.

**Comment by magnus-madsen** [comment]
@ninaandrup Ill give this to you for when you are done with foldRight.

**Comment by mlutze** [comment]
See also https://github.com/flix/flix/issues/2669

**Comment by magnus-madsen** [comment]
I have decided for a much simpler plan: We should add `zipWithIndex` to:

- `Chain`
- `Nec`
- `List`
- `Nel`
- `DelayList`

but nothing else. Thus we don't have to add `zipWithIndex` to `RedBlackTree` nor do we have to add it to `Foldable`.

@ninaandrup Does that make sense?
