### ISSUE TITLE
Weeder effects cleanup

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3684]
I think we should include the statement "resume must occur in an effect handler" in the summary and message itself, and then leave the explain = None [in `IllegalResume` error]

_Originally posted by @magnus-madsen in https://github.com/flix/flix/pull/3657#discussion_r866510352_

Add some comments [to `SyntacticEnv`].

_Originally posted by @magnus-madsen in https://github.com/flix/flix/pull/3657#discussion_r866510956_

Add a few more test cases [for `IllegalResume`].

_Originally posted by @magnus-madsen in https://github.com/flix/flix/pull/3657#discussion_r866511104_

**Comment by magnus-madsen** [comment]
Not sure if all of these were completed.
