### ISSUE TITLE
[Library] BigFloat ?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#369]
We have support for arbitrary sized integers, but no such support for decimal/rational/floating point numbers. Do we need that? Java offers `BigDecimal` that we could use in the backend.

**Comment by mhyee** [comment]
[YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it). Let's wait until there's a convincing use case. (Which we do for BigInts.)

**Comment by magnus-madsen** [comment]
Agreed. Let us see if someone wants it.
