### ISSUE TITLE
Add Namer support for AE

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3690]
Preparation:
- [x] Rename effects to purity. (e.g. `eff -> pur`).
- [x] Rename `UseTypeOrClass` to `UseTypeOrClassOrEffect`
- [x] Rename `UseDefOrSig` to `UseDefOrSigOrOp`

New Constructs:
- [x] Introduce `Declaration.Eff`.
- [x] Introduce `Declaration.Op`
- [x] Introduce `Expression.Do`.
- [x] Introduce `Expression.Resume`.
- [x] Introduce `Expression.TryWith`.
- [x] Introduce all the effect types

Modified Constructs
- [x] Include effects on specs
- [x] Include effects on arrow types

Checks:
- [x] Effect name collision with Classes/Types
- [x] Op name collision with defs/sigs

**Comment by mlutze** [comment]
@magnus-madsen anything else? Also, better idea for `UseTypeOrClassOrEffect` naming?

**Comment by magnus-madsen** [comment]
Need better names; no ideas come to mind.

**Comment by magnus-madsen** [comment]
- Merge DuplicateUpper/Lower Name

**Comment by mlutze** [comment]
DuplicateLowerName contains an --explain thingy about overloading not supported. If we merge them, we'll have it on both upper and lowercase errors. Is that acceptable?

**Comment by magnus-madsen** [comment]
> DuplicateLowerName contains an --explain thingy about overloading not supported. If we merge them, we'll have it on both upper and lowercase errors. Is that acceptable?

Can you paste

**Comment by mlutze** [comment]
```scala
  /**
    * An error raised to indicate that the given def `name` is defined multiple times.
    *
    * @param name the name.
    * @param loc1 the location of the first definition.
    * @param loc2 the location of the second definition.
    */
  case class DuplicateLowerName(name: String, loc1: SourceLocation, loc2: SourceLocation) extends NameError {
    def summary: String = s"Duplicate definition of '$name'."

    def message(formatter: Formatter): String = {
      import formatter._
      s"""${line(kind, source.name)}
         |>> Duplicate definition of '${red(name)}'.
         |
         |${code(loc1, "the first definition was here.")}
         |
         |${code(loc2, "the second definition was here.")}
         |""".stripMargin
    }

    def explain(formatter: Formatter): Option[String] = Some({
      """Flix does not support function overloading, i.e. you cannot define two functions
        |with the same name, even if their formal parameters differ.
        |
        |If you want two functions to share the same name you have to either:
        |
        |    (a) put each function into its own namespace, or
        |    (b) introduce a type class and implement two instances.
        |""".stripMargin
    })

    def loc: SourceLocation = loc1
  }
```
