### ISSUE TITLE
Remove `!` from all functions in the standard library

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3695]
For example, `MutList.append!` should just be `MutList.append` since soon the types will give us the same information.

**Comment by magnus-madsen** [comment]
Wait.. This does not work because we have e.g.:

- `Array.reverse` and `Array.reverse!`
- `Array.replace` and `Array.replace!`

**Comment by jaschdoc** [comment]
Maybe we could give the functions with `!` a more appropriate name like `Array.reverseInPlace` or `Array.replaceInArray` or something else.

**Comment by magnus-madsen** [comment]
We cant do it
