### ISSUE TITLE
Suggestion: better error message when top level definition lacks type annotations

### ISSUE THREAD

**Issue by athas** [flix/flix#3696]
While [this restriction is mentioned here](https://doc.flix.dev/functions/) I was quite mystified at first.

The definition

```Flix
def fib(n: Int32) = n
```

produces a syntax error saying `Invalid input ") ="`.

The definition

```Flix
def fib(n) = n
```

produces an error saying `Invalid input "n) ="`.  I think an error in the vein of "top level definitions must explicitly declare parameter and return types" would be better.

Incidentally, is there a grammar for Flix anywhere?

**Comment by magnus-madsen** [comment]
Hello Athas and welcome to our little community ;-)

There is no official grammar, only this beast: https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Parser.scala

@mlutze We could easily make type annotations on the return type optional in the parser and then give a better error in the weeder, right?

**Comment by JonathanStarup** [comment]
> Hello Athas and welcome to our little community ;-)
> 
> There is no official grammar, only this beast: https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Parser.scala
> 
> @mlutze We could easily make type annotations on the return type optional in the parser and then give a better error in the weeder, right?

I think we should think about doing this for more things. We could also try to parse def bodies with a trailing ; and give a nice error later. We could also try parsing namespaces with a missing } etc.
