### ISSUE TITLE
add `Random.shuffle`

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#3697]
I'm not sure what properties are needed or if it should be on a typeclass but I'd like a shuffle function
```
def shuffle(r: Random.Random, c: Collection): Collection = ???
```
where Collection is at least Array and List

**Comment by magnus-madsen** [comment]
@ninaandrup Can you add an **impure** function `Array.shuffle` that shuffles an `Array[a]`.

Then, we should add `shuffle` impure functions to the various namespaces that essentially do `x |> toArray |> shuffle |> toX`.

**Comment by JonathanStarup** [comment]
> I think something simple like: https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle should do.
> 
> It essentially just swapping each `a[i]` with a random j.

It's important here what range j is from. I remembered this and selected any j which gave biased results. I just wanted to note that it's easy to make the wrong choice if you don't look at reference material.

**Comment by ninaandrup** [comment]
If I have to make a `shuffle` function for the rest of the collections I have to make `toArray` and `toX` functions as well. Do we want `shuffle` for more collections?

**Comment by magnus-madsen** [comment]
> If I have to make a `shuffle` function for the rest of the collections I have to make `toArray` and `toX` functions as well. Do we want `shuffle` for more collections?

Which collections are missing a shuffle? Sets and maps  cannot be shuffled because they are always sorted :)

**Comment by ninaandrup** [comment]
> > If I have to make a `shuffle` function for the rest of the collections I have to make `toArray` and `toX` functions as well. Do we want `shuffle` for more collections?
> 
> Which collections are missing a shuffle? Sets and maps cannot be shuffled because they are always sorted :)

I think it is only `Nec` and `Nel`
