### ISSUE TITLE
Benchmarking statistics

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3703]
Currently we report the fastest run for each phase in `--Xbenchmark-phases`.
It seems more reasonable to report the **median** run, since this will be more robust to outliers.
We can also look into reporting other statistics, such as the standard deviation, or even the full list of timings, which might allow better analysis of testing results.

**Comment by JonathanStarup** [comment]
In defense of taking the minimum, I think that it is harder to do the median on the JVM where it has to "warm up" and all of that. I think some tools have some warmups rounds that does not count in the statistics.

**Comment by magnus-madsen** [comment]
https://arewefast.flix.dev/ suggests that max, median, and avg are all usable.

**Comment by magnus-madsen** [comment]
I would probably pick either the average or the median.

**Comment by mlutze** [comment]
We could consider adding some warmup rounds.
