### ISSUE TITLE
`List.IndexOf` should return `Option`

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3712]
Currently it returns `-1` if the value is not a member of the list, which is counter to our general style.

**Comment by magnus-madsen** [comment]
We should also check if `Chain` etc. should have an index of.

**Comment by ninaandrup** [comment]
Other namespaces with `indexOf` functions returning `-1`

- `Chain`
- `Nec`

**Comment by magnus-madsen** [comment]
Done?

**Comment by ninaandrup** [comment]
> Done?

Yes :-)
