### ISSUE TITLE
`RigidityEnv`

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3715]
Currently we treat rigidity as an innate property of a type variable. But I don't think this is the case. Rather, it is a property depending on how we are looking at the variable; the same variable can be rigid or not in different circumstances. This is made more clear by recent changes to rigidify and derigidify variables before and after a calculation.

I propose we remove the `rigidity` field from type variable syms, and instead add a `renv: Map[Symbol.TypeVarSym, Rigidity]` to `unifyTypes`, etc. This would correspond to a more natural expression of rigidity and would get rid of some of the complex rigidity manipulation.

**Comment by magnus-madsen** [comment]
I think I like this idea. Could you do a "study" to investigate how much code would need to change? I assume that InferMonad and Typer would have to carry these environments. What about the Kinder and what about regions?

**Comment by magnus-madsen** [comment]
Also; do you see any way to refactor towards this, or does it require all changes in one go?

**Comment by mlutze** [comment]
I added an extra parameter to `Unification.unify` and related functions to trigger an error. Here's where the errors are:

| File | Unify Count | Rigidity Count |
| --- | --- | --- |
| Scheme | 1 | 5 |
| Type | 0 | 2 |
| FormatType | 0 | 2 |
| Instances | 2 | 0 |
| Monomorph | 3 | 0 |
| Namer | 0 | 3 |
| Regions | 0 | 1 |
| Stratifier | 1 | 0 |
| Typer | 93 | 3 |
| JvmOps | 0 | 1 |
| BoolUnification | - | 4 |
| Unification | - | 5 |

I think the Kinder should be unaffected. Regions has a heuristic where it determines if a type is a region based on its kind and rigidity. This will turn into a regular kind check in the future, right? Meanwhile maybe we add a flag to `TypeVarSym` to say whether it's a region?

**Comment by mlutze** [comment]
> Also; do you see any way to refactor towards this, or does it require all changes in one go?

What about this:
1. progressively add `renv` everywhere, but don't use it
2. switch to using `renv`
3. progressively remove `Rigidity` everywhere

**Comment by magnus-madsen** [comment]
Sounds good, but lets discuss it in detail on Monday.
