### ISSUE TITLE
CLI: commands and options

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3720]
The CLI has the following **commands**:
* `init`
* `check`
* `build`
* `build-jar`
* `build-pkg`
* `run`
* `test`
* `install`

and the following **options**:
* `args`
* `benchmark`
* `doc`
* `explain`
* `help`
* `interactive`
* `json`
* `listen`
* `lsp`
* `output`
* `test`
* `threads`
* `version`

and the following **experimental options**:
* `Xbenchmark-code-size`
* `Xbenchmark-incremental`
* `Xbenchmark-phases`
* `Xbenchmark-throughput`
* `Xdebug`
* `Xlib`
* `Xstatistics`
* `Xstrictmono`

It seems to me that several of the "options" are really **commands**, since they don't modify anything but rather indicate what action to take:
* `benchmark`
* `doc`
* `help`
* `interactive`
* `lsp`
* `test`
* `version`
* `Xbenchmark-code-size`(?)
* `Xbenchmark-incremental`
* `Xbenchmark-phases`
* `Xbenchmark-throughput`

**Comment by magnus-madsen** [comment]
I think it is pretty much only `doc` that remains and then to maybe hide the `--X` options?

**Comment by magnus-madsen** [comment]
Ignoring the experimental options, I think we have come pretty close:

```
The Flix Programming Language 0.42.0
Usage: flix [init|check|build|build-jar|build-pkg|doc|run|benchmark|test|repl|lsp] [options] <args>...

Command: init
  creates a new project in the current directory.
Command: check
  checks the current project for errors.
Command: build
  builds (i.e. compiles) the current project.
Command: build-jar
  builds a jar-file from the current project.
Command: build-pkg
  builds a fpkg-file from the current project.
Command: doc
  generates API documentation.
Command: run
  runs main for the current project.
Command: benchmark
  runs the benchmarks for the current project.
Command: test
  runs the tests for the current project.
Command: repl
  starts a repl for the current project, or provided Flix source files.
Command: lsp port
  starts the LSP server and listens on the given port.
  port

  --args <a1, a2, ...>     arguments passed to main. Must be a single quoted string.
  --entrypoint <value>     specifies the main entry point.
  --explain                provides suggestions on how to solve a problem.
  --github-key <value>     API key to use for GitHub dependency resolution.
  --help                   prints this usage information.
  --json                   enables json output.
  --listen <port>          starts the socket server and listens on the given port.
  --no-install             disables automatic installation of dependencies.
  --threads <value>        number of threads to use for compilation.
  --version                prints the version number.
```

**Comment by magnus-madsen** [comment]
(experimental options will come and go-- that is their nature).
