### ISSUE TITLE
Removing Scheme (mostly)

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3731]
We carry a scheme from `NamedAst` through to `TypedAst`, where thereafter we carry 2 schemes (inferred and declared).
The scheme is a useful abstraction for managing typing, but is a burden for everything else, as it is an extra AST node that is redundant with the parameters + return type + effect.

I think we can remove Scheme at least from the early ASTs without doing any harm. I think it's also likely that we can remove it even from later ASTs, only using it as needed in the Typer.

**Comment by magnus-madsen** [comment]
OK, agreed.

**Comment by magnus-madsen** [comment]
Status?

**Comment by mlutze** [comment]
Still WIP. Taking it incrementally.

**Comment by magnus-madsen** [comment]
Status?

**Comment by mlutze** [comment]
I think we're in a much better spot than we were. There's still a bit of weirdness around enums, but I don't plan on revisiting it unless it annoys me again :)
