### ISSUE TITLE
[Library] Map

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#374]
General:
- Rename `Map.null` to `Map.isEmpty`.

Documentation:
- Add comment to `Map.empty` to say that it has the syntactic sugar `@{}`.
- Add comment to `Map.singleton` to say that it has the syntactic sugar `@{x}`.

Additional Functions:
- Add `toList`.
- Add `exists`, `forall` and `exists`.
- Add `count`.
- Add `find`, `findLeft`, and `findRight` (assuming some order)
- Add `reduceOpt`, `reduceLeftOpt`, and `reduceRightOpt` (assuming some order).

A question we may need to consider is whether the above functions should be passed the keys of the map. My current thoughts are that they should just work on the values.

**Comment by liampalmer43** [comment]
In scala, `exists`, `forall` and `count` take functions that are passed the keys and the values.  What do you think about doing the same thing here?  For the `reduce` functions, we could do what was done with fold (have `reduceOpt` and `reduceOptWithKey`).

**Comment by magnus-madsen** [comment]
> In scala, exists, forall and count take functions that are passed the keys and the values.

I agree.

> For the reduce functions, we could do what was done with fold (have reduceOpt and reduceOptWithKey).

Yes, agreed.

**Comment by magnus-madsen** [comment]
Fixed in #398
