### ISSUE TITLE
Add `foldMap` to collections

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3743]
Add `foldMap` to every collection (after the usual folds).

**Comment by stephentetley** [comment]
I've found a relational version of `foldMap` very handy - relations aren't monoids so this can't be done with the one we already have in Foldable:

~~~

  ///
  /// Returns the result of mapping each element and combining the results.
  ///
  pub def foldMap(f: a -> #{| r} & ef, t: t[a]): #{| r} & ef with Foldable[t] =
      Foldable.foldLeft((acc, x) -> acc <+> f(x), #{}, t)

~~~

Is a good candidate for adding to Foldable - with a new name of course?

(An alternative would be starting a module of relation builders and consumers in the stdlib).

**Comment by magnus-madsen** [comment]
Interesting. Could you give an example of a use?

**Comment by magnus-madsen** [comment]
(Datalog program values are commutative monoids, but the type system does not allow us to express that-- yet)

**Comment by stephentetley** [comment]
> Could you give an example of a use?

Basically any time I'm making a relation from a list...

https://github.com/stephentetley/work-flix/blob/d3d5e63e765f9d5f87d4e123dc185ab58a1d0b2d/work-flix-apps/S4Loader/src/S4Loader/Floc/Gen/WorkList.flix#L102

**Comment by ninaandrup** [comment]
It should be like the `foldMap` from `Foldable`, right?
```
///
/// Returns the result of mapping each element and combining the results.
///
pub def foldMap(f: a -> b & ef, t: t[a]): b & ef with Monoid[b] =
    Foldable.foldLeft((acc, x) -> Monoid.combine(f(x), acc), Monoid.empty(), t)
```

**Comment by magnus-madsen** [comment]
Yes, just "specialized" to the specific collection.

**Comment by ninaandrup** [comment]
I have done:

- `Array` *
- `Chain` *
- `DelayList` *
- `Iterator` *
- `List`
- `MutDeque` *
- `Set`

*not merged

I need to do:

- [ ] `MutList`
- [ ] `MutSet`
- [ ] `Nec`
- [ ] `Nel`

Am I missing any?
Then there is `foldMapWithKey` for `Map`

**Comment by ninaandrup** [comment]
@magnus-madsen I think this can be closed, if I did not miss any collections in the list above
