### ISSUE TITLE
Semantic tokens for constraint params

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3745]
Would it be possible to use different tokens to distinguish between lexically scoped variables and quantified variables in a Datalog rule?

**Comment by magnus-madsen** [comment]
@nicdard Do you know if we can have different classes of local variables?

**Comment by nicdard** [comment]
I have been searching through the docs, but such feature doesn't seem to be in place. One thing we could do is to use a parameter token for the quantified veriables, as they are bounded to the quantifier. However I think that we should then treat the quantifier as an anonymous function kind of, as it is defining a scope. What do you think?

**Comment by magnus-madsen** [comment]
> 

Hmm. Seems like a hack. Maybe we should just wait for VSCode to improve.
