### ISSUE TITLE
Wrong highligting of camel case named hole

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#3756]
![image](https://user-images.githubusercontent.com/32037926/168467033-d9e33f00-edc6-4c4c-a4b2-9a306a60ca08.png)

0.28.0

**Comment by magnus-madsen** [comment]
Allow uppercase letters here:

https://github.com/flix/vscode-flix/blob/master/syntaxes/flix.tmLanguage.json#LL152C56-L152C56
