### ISSUE TITLE
Add `_.toMutDeque`

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#3761]
There is currently no way of converting any data structure to a `MutDeque` without doing it manually.

**Comment by magnus-madsen** [comment]
Done?

**Comment by ninaandrup** [comment]
Is there any data structure that would be nice to have a `toMutDeque` on, that I have not made yet?

**Comment by magnus-madsen** [comment]
> Is there any data structure that would be nice to have a `toMutDeque` on, that I have not made yet?

All of them? :)

**Comment by ninaandrup** [comment]
> > Is there any data structure that would be nice to have a `toMutDeque` on, that I have not made yet?
> 
> All of them? :)

Then I'll keep working my way through the collections :-)

**Comment by ninaandrup** [comment]
A list for myself for the missing collections:

- [ ] DelayMap
- [ ] Map
- [ ] MultiMap
- [ ] MutMap
- [ ] MutSet
- [ ] RedBlackTree
- [ ] Set

**Comment by ninaandrup** [comment]
This should be reopened. I forgot that I still need to do the `*Map`, `Set` and `RedBlackTree`. Closed by https://github.com/flix/flix/pull/3948

**Comment by magnus-madsen** [comment]
What's the status on this?

**Comment by ninaandrup** [comment]
> What's the status on this?

We still need a `toMutDeque` in `DelayMap`, `MultiMap`, `MutMap`, `MutSet` and `RedBlackTree`

**Comment by magnus-madsen** [comment]
👍
