### ISSUE TITLE
Add MultiMap?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3777]

**Comment by stephentetley** [comment]
Do you mean like this?

https://hackage.haskell.org/package/multi-containers

I'm on holiday tomorrow so I'll see how much I can do in a day.

**Comment by magnus-madsen** [comment]
Yes, I think so :)

**Comment by magnus-madsen** [comment]
> I'm on holiday tomorrow so I'll see how much I can do in a day.

Cool! But remember to take some holiday too :)

**Comment by stephentetley** [comment]
I've made two multimaps - one `Map[k, Bag[v]]` and one `Map[k, Set[v]]` , as we don't have a Bag type the first one uses a `Nec` internally for the Bag.

There are forty something functions in the APIs of both with tests for about half of the BagMultiMap. Not bad day's work.

Temporarily here until they are ready to put in a PR: 

https://github.com/stephentetley/flix-sandbox/tree/master/src/FlixSandbox/TestBed

**Comment by magnus-madsen** [comment]
That sounds amazing! 👍

**Comment by stephentetley** [comment]
I've made a PR

> feat: add bag and set multimaps (cf. Add MultiMap?) #3822

**Comment by JonathanStarup** [comment]
@magnus-madsen this was closed by #3822
