### ISSUE TITLE
`use` namespace

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3789]
I'd like to be able to `use` a namespace so that I can have qualified definitions without having to use the fully qualified name.

```scala
def coolName(): String = {
    use Matt/Stuff/CoolThing;
    CoolThing.getName()
}
```

I hoping this would help solve the annoying problem of needing to import signatures even though you've already imported the class:
```scala
namespace N {
    class C[a] {
        def f(): a
    }
}

namespace M {
    use N.C;
    def g(): String = C.f() // rather than `N/C.f`
}
```

**Comment by magnus-madsen** [comment]
This was fixed, right?

**Comment by JonathanStarup** [comment]
Yes
