### ISSUE TITLE
[Library] Discussion: reduceOpt and friends.

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#379]
We offer functions like: `reduceOpt`, `reduceLeftOpt`, and `reduceRightOpt`. The `Opt` part of the name is derived from Scala which has both `reduce` and `reduceOption` (where the former is unsafe and the latter is safe). Since Flix does not offer partial functions, the question is whether there is any need to tag on `Opt` to the name?

**Comment by magnus-madsen** [comment]
The same also goes for e.g. `List.headOpt` and `List.lastOpt`.

**Comment by mhyee** [comment]
I think it's fine to use the shorter names. There might be some initial confusion, but it's clearly documented, and the type checker will complain.

**Comment by magnus-madsen** [comment]
I think there is agreement to make this change. Specifically,

```
List.headOpt -> List.head
List.last -> List.last
List.reduceLeftOpt -> List.reduceLeft
List.reduceOpt -> List.reduce
List.reduceRightOpt -> List.reduceRight
```

**Comment by magnus-madsen** [comment]
We should also rename the operations in Set.

**Comment by magnus-madsen** [comment]
Fixed.
