### ISSUE TITLE
All `forall`, `exists`, etc. should be effect polymorphic

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3798]
@ninaandrup Take a look at api.flix.dev and come up with a list of functions like `forall`, etc. that are not effect polymorphic, but should be. (Pretty much all functions should be effect polymorphic going forward).

**Comment by ninaandrup** [comment]
I found:

- `List.count`
- `List.toMapWith`
- `List.sortBy`
- `List.distinctWith`

**Comment by ninaandrup** [comment]
Do we want to discuss other functions, or should this be closed?
