### ISSUE TITLE
Add FunctorFilter

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3819]
Add a new type class `FunctorFilter`:

```scala
pub class FunctorFilter[m : Type -> Type] with Functor[m] {

    ///
    /// Applies the partial function `f` to every element in `x` collecting the results.
    ///
    pub def filterMap(f: a -> Option[b] & ef, x: m[a]) : m[b] & ef 

    //
    // Applies `f` to every element in `x`. Keeps every element that satisfies `f`.
    //
    pub def filter(f: a -> Bool & ef, x: m[a]): m[a] & ef = filterMap(x -> if (f(x)) Some(x) else None), x)

}
```

- [ ] Add instances for all *immutable* collections. (Several collections already seem to have a `filterMap` function).
- [ ] Add test cases.
- [ ] (Optional) add laws.

`Functor`, `FunctorFilter`, and `Monad` will be key ingredients for our upcoming monadic-do.

**Comment by magnus-madsen** [comment]
@stephentetley Would you be interested in implementing this type class? :)

**Comment by stephentetley** [comment]
Yes - I can look at it this week.

**Comment by magnus-madsen** [comment]
> Yes - I can look at it this week.

No rush :)

**Comment by stephentetley** [comment]
I've done the instances (tests to do).

Unfortunately non-empty collections (`Nel` , `Nec` and `Identity`) can't be "filterable" - I hope this doesn't limit the plans for monadic-do.

**Comment by magnus-madsen** [comment]
> I've done the instances (tests to do).
> 
> Unfortunately non-empty collections (`Nel` , `Nec` and `Identity`) can't be "filterable" - I hope this doesn't limit the plans for monadic-do.

Hmmm. That's true. But I think it should be okay, I would mean that if you did `for (x <- xs; if x > 5)` and `xs` was `Nel` it would be rejected, but thats what you would want anyway, right? It would still work for just `for (x <- xs)`, if I understand correctly myself.
