### ISSUE TITLE
Feature Request: List.filterNot

### ISSUE THREAD

**Issue by bbstilson** [flix/flix#3831]
Similar to [Scala](https://www.scala-lang.org/api/2.13.x/scala/collection/immutable/List.html#filterNot(p:A=%3EBoolean):List[A]), it would be nice to have a `filterNot` along with a `filter`.

For example, being able to remove empty elements from a list:

```scala
let xs = "" :: "a" :: "b" :: "" :: "c" :: Nil;
xs
    |> List.filterNot(String.isEmpty)
    |> List.foreach(println)

// a
// b
// c
```

**Comment by mlutze** [comment]
Hi @bbstilson and welcome to the community!

I'll note that your example is possible without too much pain using the function composition operator:

```scala
let xs = "" :: "a" :: "b" :: "" :: "c" :: Nil;
xs
    |> List.filter(String.isEmpty >> Bool.not)
    |> List.foreach(println)
// a
// b
// c
```

But your `filterNot` example is a bit more legible and fluent, so I agree it is worth considering.

**Comment by magnus-madsen** [comment]
I think we should avoid having "xyzNot"-- simply because there would be too many variants to support.

Instead we should ensure that it is easy to get the negation, e.g. as shown with `String.isEmpty >> Bool.not`.
