### ISSUE TITLE
Rename `static` region to `Static`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3844]
Rename `static` region to `Static`.

1. Add `type alias Static = false` to Prelude.flix
2. Refactor the standard library to use `Static` instead of `static`.
3. Refactor the compiler to remove special treatment of `static`.

To make (2) easier, open `Weeder.scala` and change line 2683 to print `ident.loc` and throw an exception. 

This will make it easy to track down all uses of the old `static`.

**Comment by jaschdoc** [comment]
I think the solution you've outlined above clashes with the current way we use regions. `static` is afaik an alias for `() as & Impure`. The new definition would be compatible with type level use i.e. `Array[a, Static]` but when used as a term the types of course don't match. Type casting`false` also doesn't work as it throws a parse error.

**Comment by magnus-madsen** [comment]
> I think the solution you've outlined above clashes with the current way we use regions. `static` is afaik an alias for `() as & Impure`. The new definition would be compatible with type level use i.e. `Array[a, Static]` but when used as a term the types of course don't match. Type casting`false` also doesn't work as it throws a parse error.

I don't understand :/

But you could try by starting to change it here: https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Weeder.scala#L2692
