### ISSUE TITLE
Ensure that all `toXYZ` functions take a region parameter

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3845]
Ensure that all `toXYZ` functions take a region parameter unless its to an immutable collection. (E.g. toMutSet needs a region param, toList does not).

@ninaandrup Can you compile such a list? 

it is possible it is already the case, I just want to check.

**Comment by ninaandrup** [comment]
All the `toMut*` functions take a region parameter as well as `toArray` functions. This is all the mutable collections, right?
