### ISSUE TITLE
Parametric type classes for `Iterable` (and more)

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3861]
By popular demand, I'm bringing back the MPTC suggestion (but calling it differently), with a specific target of `Iterable`.

The issue we are having with `Iterable` is that we are not sure how to create a common signature for mutable values (which have regions) and immutable values (lacking regions). The basic problem is that e.g., `List` does not have a region parameter; it is implicitly in some `Pure`-like region. I believe we can address this issue using multiparameter type classes.

```scala
// sample iterator type
pub enum MyIterator[r: Region, a: Type](Unit -> Option[a] & r)

// an iterator uses both the data type's region and its own region
def mkIterator(next: Unit -> Option[a] & r1, r: Region[r]): MyIterator[r1 and r, a] = ???

// sample iterable class
// r is the data's region
// elm is the element type
// a is the collection type
// (elm is not strictly necessary for the idea; 
//  but it is necessary for the demo due to the order of Array's type parameters)
pub class MyIterable[r: Region, elm: Type, a: Type] {
    pub def toIterator(x: a, r1: Region[r1]): MyIterator[r and r1, elm]
}

// an instance of Iterable for List
// a list is immutable, so using it doesn't touch any region
instance MyIterable[Pure, a, List[a]] {
    // the created iterator has its own region, but no other region
    pub def toIterator(x: List[a], r1: Region[r1]): MyIterator[r1, a] = mkIterator(_ -> List.head(x), r1)
}

// an instance of Iterable for Array
// it uses the region of the Array
instance MyIterable[r1, a, ScopedArray[a, r1]] {
    // the created iterator uses two regions: the array's region and the iterator's own region
    pub def toIterator(x: ScopedArray[a, r1], r2: Region[r2]): MyIterator[r1 and r2, a] = mkIterator(_ -> Some(x[0]), r2)
}
```

One of the big concerns regarding MPTCs is that they introduce complexity and potential ambiguity. But I think we avoid a significant amount of complexity simply by requiring a functional dependency of all of the parameters on one of the parameters. That is, the _last_ parameter uniquely determines all the others. For example:

```scala
// if we have this instance
instance MyIterable[r1, a, ScopedArray[a, r1]]

// then we cannot have this instance since they overlap
instance MyIterable[true, a, ScopedArray[a, r1]] // ERROR!

// but of course the dependent (non-last) parameters may overlap
instance MyIterable[r1, a, MutListf[a, r1]]
```

To draw a comparison to OOP, it is something like the following:
```scala
trait MyIterable[r, elm]

class ScopedArray[a, r1] extends MyIterable[r, elm]
```

In the literature, this proposal seems to correspond to [parametric type classes](https://www.researchgate.net/publication/221252382_Parametric_Type_Classes), hence my re-titling the idea. With that in mind, one might consider a different syntax that distinguishes the parametric types from the "subject" type.

The issue of the extra parameters hanging about might be addressed by introducing something like class aliases to hide them.

The implementation in the compiler is fairly straightforward. Recall that a working implementation was built in four hours :)

**Comment by magnus-madsen** [comment]
https://doc.rust-lang.org/reference/trait-bounds.html

**Comment by magnus-madsen** [comment]
What should we do with e.g. `Foldable`? Should all `Foldable`s have a region (but that is not functional-first) or should we have both `Foldable` and `MutFoldable`?

**Comment by mlutze** [comment]
Supposing we had class aliases, `Foldable[a]` could just be an alias for `FoldableMut[Pure, a]`, so users don't have to know about `FoldableMut` if they're working in a purely functional style.

**Comment by mlutze** [comment]
But I think it would be a shame to separate them completely, since then we couldn't generalize over e.g. `(Mut)?List`

**Comment by magnus-madsen** [comment]
Still relevant?

**Comment by mlutze** [comment]
No, this is superseded by associated types
