### ISSUE TITLE
Refactor Datalog solver to use regions

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3896]
We should refactor the Datalog engine to use regions (while collecting information about the refactoring for the case study).

I propose the following approach:

- [ ] Declare a new region in `solveWithStratification` (I think that's the entry point, right?)
- [ ] Add a `r: Region[r]` parameter to every function in `Fixpoint` which appears to need such an argument. (Need to discuss if it should be first or last.)
- [ ] Refactor the Arrays in `Fixpoint.Ram` to use regions.
- [ ] Refactor the Arrays in `Fixpoint.Ast` to use regions (may require tweaks to `Lowering`.

Each should be a separate PR. Possibly with sub-PRs, if feasible.

While doing this work, keep notes of interesting observations. E.g. is the refactoring straightforward? Are there interesting choices to be made? Are some restructuring required or not?

**Comment by magnus-madsen** [comment]
We should also ask ourselves, is there any reason for the Ram AST to use arrays? Maybe we could just use a list.

Then we would only need a region for the actual database. I would probably suggest that.

But do take a look at the code.

**Comment by JonathanStarup** [comment]
As far as I can see arrays are used for 1) random access and 2) array reuse for efficiency

1) could be solved by an immutable vector
2) seems like the cost of functional code here.

**Comment by JonathanStarup** [comment]
Additional todos:
* [ ] Actually impure toString methods should not implement ToString typeclass

**Comment by magnus-madsen** [comment]
I would suggest to break this into smaller tasks than can be merged one by one.

**Comment by JonathanStarup** [comment]
> I propose to change the data structures ie ast and ram to use lists (then in the future they can use vectors) and to keep using arrays for the search env and to use mutable collections for the databases. This makes sense and seems like a useful use case for regions.

So this means that lookups will be linear? as a temporary performance cost?

**Comment by magnus-madsen** [comment]
> > I propose to change the data structures ie ast and ram to use lists (then in the future they can use vectors) and to keep using arrays for the search env and to use mutable collections for the databases. This makes sense and seems like a useful use case for regions.
> 
> So this means that lookups will be linear? as a temporary performance cost?

I don't think so, because we don't do any lookups for the AST/RAM enums.

**Comment by magnus-madsen** [comment]
All the performance critical stuff is in searchEnv and db and there we will continue to use arrays/mut maps (but with regions).

**Comment by magnus-madsen** [comment]
How far are we? :)

**Comment by JonathanStarup** [comment]
There should be one or two PR's left
