### ISSUE TITLE
Lattice instances for collection types?

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#3907]
Are we able to use set operations as common strategy to design the lattice methods of collection types - at least where the collection naturally supports set operations.

The instances would be:

LowerBound.minValue ~ empty
PartialOrder.lessEqual ~ isSubset
JoinLattice.leastUpperBound ~ union
MeetLattice.greatestLowerBound ~ intersection

My understanding is that the Bloom language used this strategy - see the tech report linked to below especially section 3.5:

https://dsf.berkeley.edu/papers/UCB-lattice-tr.pdf

For the Map instances I think we can improve on the simple `union` (which is left biased) and use `unionWith` to take an inner `leastUpperBound` on the keys. For consistency `greatestLowerBound` follows this scheme:

~~~

instance LowerBound[Map[k, v]] {
    pub def minValue(): Map[k, v] = Map.empty()
}

instance PartialOrder[Map[k, v]] with Order[k], Eq[v] {
    pub def lessEqual(m1: Map[k, v], m2: Map[k, v]): Bool = m1 `Map.isSubmapOf` m2
}

instance JoinLattice[Map[k, v]]with Order[k], Eq[v], JoinLattice[v] {
    pub def leastUpperBound(m1: Map[k, v], m2: Map[k, v]): Map[k, v] =
        Map.unionWith(JoinLattice.leastUpperBound, m1, m2)
}

instance MeetLattice[Map[k, v]] with Order[k], Eq[v] {
    pub def greatestLowerBound(m1: Map[k, v], m2: Map[k, v]): Map[k, v] =
        Map.intersectionWith(MeetLattice.greatestLowerBound, m1, m2)
}

~~~

**Comment by magnus-madsen** [comment]
Yes.. We can probably do this. Where do you need it?

Using Map lattices in Datalog would be possible, but forego the performance of relations which are optimized by semi-naive evaluation.

I guess my question boils down to: What's the use case? (and would Datalog w/ relations/lattices not be better?)

**Comment by magnus-madsen** [comment]
What I mean is that Flix already supports lattice predicates, e.g.:

```
L(1, 2, 3; elm) // note semicolon
```

Here `L` is effectively a map lattice.

**Comment by stephentetley** [comment]
Thanks Magnus - I don't have a specific use-case, I was working towards adding lattice instances for MultiMap and Map didn't have any.

If we should be using lattice predicates rather than a Map in the lattice position I'll decline from proposing that we add the Map instances.

Should MultiMap have lattice instances?

**Comment by magnus-madsen** [comment]
We can add the instances; it sound and fine to have them, but in practice I would hope they are rarely used.

**Comment by stephentetley** [comment]
Cool, I'll make a PR for the Map instances, then look at the MultiMap ones.

**Comment by magnus-madsen** [comment]
I am closing this, but feel free to add the MultiMap instances, if you want.
