### ISSUE TITLE
Drop VarText?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3920]
Can we?

**Comment by magnus-madsen** [comment]
@mlutze What happens if we drop this now? I think it should be okay, no?

**Comment by mlutze** [comment]
What do you mean by dropping it? Do variables no longer carry any text? I don't understand how that would work.

Note that the recent naming advancements only fixed everything for the documentation, but error messages are still filled with nameless or pseudonymed variables.

**Comment by magnus-madsen** [comment]
Doh'. What I meant it: Do we still propagate varText during unification? If we do, my question is whether we need to any more.

**Comment by mlutze** [comment]
I removed the propagate logic in the rigidity PR after an experiment that showed it made no difference under the new system

**Comment by magnus-madsen** [comment]
OK, so VarTexts are no longer modified, correct?

If so, we can close this.

**Comment by mlutze** [comment]
Correct.
