### ISSUE TITLE
VSCode: precompile stdlib

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3927]
Autocomplete doesn't work if your workspace starts out with errors, because it needs a TypedAst to generate suggestions. If we instead compile only the standard library on launch, then we get the majority of autocomplete even in a file with errors. With incremental compilation, this should not add much time to compilation, since we'll save the compiled stdlib.

**Comment by magnus-madsen** [comment]
Not sure this is a good idea. It would also run higher risk of "timing out" the communication with LSP.
