### ISSUE TITLE
June Meeting: Topics to Discuss

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3933]
- [x] Discuss `discard` expression.
- [x] Discuss regions and type classes (e.g. `Functor` and `Foldable`).
- [x] Status of `Iterable` and `Iterator`
- [ ] Discuss other region topics (implicit regions, region first or last, etc).
- [ ] Discuss deprecation of some annotations (and annotations with expressions).
- [ ] Brainstorm immutable `Vector`.
- [ ] Brainstorm for-each and for loops.
- [x] Brainstorm `Graph` namespace.
- [x] Brainstorm Flix principles. 
- [x] Brainstorm type and/or effect cast syntax.
- [x] Record syntax.
- [ ] Array.get and List.get
- [ ] Update "What every Flix programmer should know".

Outcome:

- We should add a `debug` expression like thing. 
- Try to see if we can change `::` to `=` for records.
- Add `X.nth` to all collections that are like a sequence (List, Chain, ...)
- Add Vector data type.

**Comment by magnus-madsen** [comment]
Suggestions for topics are welcome.

**Comment by paulbutcher** [comment]
If it's not already on the list, can I suggest Clojure's implementation as a candidate for immutable vectors?

https://hypirion.com/musings/understanding-persistent-vector-pt-2

**Comment by stephentetley** [comment]
@mlutze - have you seen this?

https://homepages.dcc.ufmg.br/~camarao/controlling-the-scope-of-instances-in-Haskell-sblp2011.pdf

**Comment by JonathanStarup** [comment]
Encapsulation: How and when enum cases should be hidden from external use

**Comment by jaschdoc** [comment]
If there is time: guidelines for ordering the source of the library (alphabetically, logically similar functionality (how do we even measure this?), etc.)

**Comment by jaschdoc** [comment]
Related tickets
#4039
#2755
#3951
#3950
#4082

Anything else?

**Comment by stephentetley** [comment]
> Brainstorm immutable Vector.

As an intermediate step - a RandomAccessList [*] is very easy to implement (much easier than a Hash-mapped Trie). I've one waiting the benchmarking fix #3992 to see how well it works for indexing, but it wouldn't be much effort to make it work with an older version of the compiler before benchmarking was broken.

[*] To a user it is basically a list but internally it is cleverer to support more efficient indexing. The many reference is Chris Okasaki's book, but there is e.g a Haskell implementation on Hackage.

**Comment by JonathanStarup** [comment]
That looks very cool, what are the drawbacks? when is it worse than plain list?

From what I talked with magnus I think he wants an in-built fixed size vector with constant time lookup. I think its important to make clear if we need fixed-size, flexible size, or both.

**Comment by stephentetley** [comment]
Thanks Jonathan. 

Chris Okasaki says on page 133 of Purely Functional Data Structures:

> Skew binary random-access lists are a good choice for applications that take advantage of both the list-like aspects and the array-like aspects of random-access lists. Although there are better implementations of lists, and better implementations of (persistent) arrays none are better at both.

My implementation with just a few, essential functions is here at the moment: 

https://github.com/stephentetley/flix-sandbox/blob/master/src/FlixSandbox/RandomAccessList.flix


Random-access lists are much closer to (cons) lists than arrays so they won't be competitive to arrays for array biased workloads. However like (cons) lists they are persistent so you could use them within code that does backtracking.

I was a bit disappointed with them when I first started the implementation (as they were so much closer to lists than arrays) but after looking at how complex hash-mapped tries are, I decide I liked them. A fair comparison would be to `Map[Int32, v]` although this models a sparse array whereas random-access list models a contiguous one.
