### ISSUE TITLE
query/select/from expressions should allow region attribution?

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#3939]
As far as I can work out query/select/from expressions always produce the answer array in the static region. (Probably) Like array literals they should allowed to be on the left-hand side of ampersand region attribution operator so we can write this:

~~~

def tc(r: Region[r]): Array[(Int32, Int32), r] \ Write(r) =
    let p = #{
        TC(x, y) :- Edge(x, y).
        TC(x, y) :- TC(x, z), Edge(z, y).

        Edge(1, 3).
        Edge(2, 1).
        Edge(2, 4).
        Edge(4, 2).

    };
    (query p select (a, b) from TC(a, b)) @ r
    
~~~    

I suggest _probably_ as at some point in the future query/select/from maybe should produce a frozen array, immutable vector or even an iterator or list rather than an array. 

In the meantime there is a workaround by using a full cast:

> (query p select (a, b) from TC(a, b)) as Array[(Int32, Int32), r] \ Write(r)

**Comment by magnus-madsen** [comment]
> I suggest probably as at some point in the future query/select/from maybe should produce a frozen array, immutable vector or even an iterator or list rather than an array.

This is really what we need. But we don't have it yet.

**Comment by stephentetley** [comment]
Is there merit to making an immutable array module by wrapping Flix's current array with an enum and not exposing any mutating functions?  (Implementations of `map` , `filter` etc. would return new copies of the array.)

Frozen arrays are likely to be some time before being available from Java, but we might hope that there wouldn't be a big change to the API if we are able to swap to them at some point.

https://openjdk.java.net/jeps/8261007


I've coded enough of a Flix version to see what it would look like - shall I work it up to the point where it has a useful API?

~~~

pub enum ImmArray[a: Type](Array[a, Static])

instance ToString [ImmArray[a]] with ToString[a] {
    pub def toString(arr: ImmArray[a]): String = 
        let ImmArray(arr1) = arr;
        Array.toString(arr1) as & Pure
}

namespace ImmArray {

    pub def fromArray(arr: Array[a, r]): ImmArray[a] \ Read(r) = fromArrayHelper(arr) as \ { Read(r) }

    def fromArrayHelper(arr: Array[a, r]): ImmArray[a] & Impure = 
        let len = Array.length(arr);
        if (len < 1)
            ImmArray([] @ Static)
        else {
            let first = arr[0];
            let arr1 = [first; len] @ Static;
            Array.foreachWithIndex((x, i) -> arr1[i] = x, arr);
            ImmArray(arr1)
        }

    pub def get(i: Int32, ia: ImmArray[a]): a = 
        let ImmArray(ia1) = ia;
        ia1[i] as & Pure


    pub def length(ia: ImmArray[a]): Int32 = 
        let ImmArray(ia1) = ia;
        Array.length(ia1)

    pub def map(f: a -> b & ef, ia: ImmArray[a]): ImmArray[b] & ef =  mapHelper(f, ia) as & ef
    
    def mapHelper(f: a -> b & ef, ia: ImmArray[a]): ImmArray[b] & Impure = 
        let len = length(ia);
        if (len < 1)
            ImmArray([] @ Static)
        else {
            let first = f(get(0, ia));
            let arr1 = [first; len] @ Static;
            foreachWithIndex((x, i) -> arr1[i] = f(x), ia);
            ImmArray(arr1)
        }

    pub def foreachWithIndex(f: (a, Int32) -> Unit & ef, ia: ImmArray[a]): Unit & ef =
        let ImmArray(ia1) = ia;
        Array.foreachWithIndex(f, ia1) as & ef

}

~~~

**Comment by magnus-madsen** [comment]
I thought about three approaches:

- Adding a `Vector` like you describe (which is a data type wrapping an array and with casts). I dislike this because I think we would have to duplicate everything in `Array`.
- Adding a `Vector` to Flix itself (e.g. `[|1, 2, 3|], exp[|0|]`). I dislike this because we would still have to duplicate everything in `Array`, but at least it would be without casts!
- Add persistent arrays: https://github.com/flix/flix/issues/3933#issuecomment-1153284115 (could be interesting, if someone wants to do it. Would still need casts though...)

So being a bit dissatisfied with everything, I have so far elected to do nothing.

**Comment by JonathanStarup** [comment]
Couldn't all of these be implementations of the same interface? So we could add the namespace like Steven proposes with casts without committing to any of them.

**Comment by JonathanStarup** [comment]
If users do not open up the `ImmArray` enum in the above, we can just reimplement the functions of the namespace with on of the other solutions.

**Comment by JonathanStarup** [comment]
> I see. So we would just unwrap and forward to `Array.XYZ`?

Yes, but probably with complications like `mapHelper` in Stephens code

**Comment by magnus-madsen** [comment]
We have decided that `query` will return a `List`. Later this can be changed to an immutable vector. 

(Thus solving the purity issue.)

**Comment by magnus-madsen** [comment]
(PR will be merged soon).
