### ISSUE TITLE
Add `for-yield` loop construct

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3951]
Add support for:

```scala
for (pat <- exp) yield exp_body
```

as a `ForYield` node in the AST after `Choose`.

Desugar as follows in the `Weeder`:

```scala
for (pat <- exp) yield exp_body
  ==>
Functor.map(match pat -> exp, exp_body)

for (pat1 <- exp1; pat2 <- exp2) yield exp_body
  ==>
Monad.flatMap(match pat1 -> 
    Functor.map(match pat2 -> exp_body, exp2), exp1)
```

(Note: We should discuss whether to use a different type class than foreach).

TODO: Add `if` construct.

**Comment by magnus-madsen** [comment]
@jaschdoc This should be a fun programming exercise for the internship.

**Comment by jaschdoc** [comment]
Do we want to support multiple yield expressions?

**Comment by magnus-madsen** [comment]
I propose:

```
for (x <- xs; if exp1; y <- ys; if exp2) exp3
```

becomes

```
List.flatMap(x -> 
    if (exp1)
        List.flatMap(y -> 
            if (exp2) 
                Applicative.point(exp3) 
            else 
                MonadZero.empty(), l2)
    else 
        MonadZero.empty(), l1);
```

Does that make sense @jaschdoc ?

**Comment by jaschdoc** [comment]
Yes I believe so :)

**Comment by jaschdoc** [comment]
So no arbitrary nesting of guards?

**Comment by magnus-madsen** [comment]
What do you mean?

**Comment by jaschdoc** [comment]
Nevermind, I thought about it and the question doesn't make sense hehe :)

**Comment by jaschdoc** [comment]
Related issue(s) (will be updated when other issues are created):
#4214

**Comment by magnus-madsen** [comment]
Fixed in master (some issues remain).
