### ISSUE TITLE
A type class for immutable values?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3956]
Would it be possible to have a type class that captures immutable values?

I was thinking something like a marker:

```
sealed class Immutable[t]

instance Immutable[Bool]
instance Immutable[String]

enum List[t] with ..., Immutable {... }
```

The compiler would ensure that we never implement `Immutable` for `Ref[t, r]` or `Array[t, r]`.

Possibly all the instances should be derived and not expressed in Flix.

**Comment by magnus-madsen** [comment]
@mlutze Would this be feasible?

**Comment by mlutze** [comment]
> @mlutze Would this be feasible?

It seems feasible. What's the utility?

**Comment by magnus-madsen** [comment]
We now have `Sendable`-- not perfect of course.
