### ISSUE TITLE
[Parser] Bug in Map Literals

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#396]
```
def toMap[k,v](o: Option[(k, v)]): Map[k, v] = match o with {
        case None => @{}
        case Some((k, v)) => @{k -> v}
}
```

```
-- Parse Error -------------------------------------------------- ???

>> Parse Error:

Invalid input '}', expected LegalLetter, "->", '.', '(' or optWS (line 3, column 38):
        case Some((k, v)) => @{k -> v}
```

**Comment by magnus-madsen** [comment]
It may be a clash with lambdas, which also start `x -> ...`. Not sure.

**Comment by magnus-madsen** [comment]
We need to revisit the literal syntax for maps (and possibly sets).

The problem with `@{x -> 42}` is that `x -> 42` is a lambda expression, not a map element. One fix could be to use pairs, e.g. `@{(x, 42)}` or a fat arrow, e.g. `@{x => 42}`. 

Thoughts??

**Comment by mhyee** [comment]
I prefer the fat arrow, and pairs is probably an acceptable alternative.

Though it's a bit confusing that we use `->` for functions (and might use `=>` for maps) when it's the other way around in Scala. Was this because of parsing `=>` in pattern matching? Would this also be a problem with maps?

**Comment by magnus-madsen** [comment]
Map literals have been reworked to Map#{ ... }. I think (?) this solves the problem.
