### ISSUE TITLE
Numeric functions and subject last

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#3963]
It seems to me that many of the numeric functions, like `Int64.clampToInt` does not adhere to subject last.
```
pub def clampToInt32(x: Int64, minimum: Int32, maximum: Int32): Int32
```

**Comment by stephentetley** [comment]
Potentially `minimum` and `maximum` should be in a record as well to simulate named arguments.

**Comment by ninaandrup** [comment]
@magnus-madsen I have made the functions
```
clampToInt*(minimum: Int32, maximum: Int32, x: Int*): Int*
```
to
```
clampToInt*(minimum: {minimum :: Int32}, maximum: {maximum :: Int32}, x: Int*): Int*
```
do we maybe want to use `min` and `max` instead such that it is not too long?

**Comment by stephentetley** [comment]
> clampToInt*(min: {min :: Int32}, max: {max :: Int32}, x: Int*): Int*

I wonder if this is a nicer signature:

> clampToInt*(range: {min :: Int32, max :: Int32}, x: Int*): Int*

My wager is that no-one would ever partially apply just min so we might as we make a tangible range.

**Comment by magnus-madsen** [comment]
Agree with Stephen. Let's do that.

**Comment by JonathanStarup** [comment]
related to this #3977, it could be cool to have range objects that the std lib could use. Minimum, maximum, and maximum inclusive/exclusive. Cool but maybe also too cumbersome.

**Comment by magnus-madsen** [comment]
I agree a Range type or type class (?) would be nice. Not sure what the best practice is. Suggestions welcome.

**Comment by ninaandrup** [comment]
This should be closed. All numeric functions have been refactored to subject last :-)
