### ISSUE TITLE
Add `peekFront`, `peekBack`, and arbitrary lookup to `MutDeque`

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#3967]
Could also be called `pollFront`/`pollBack`. The lookup function is called a lot of different things, maybe `get`?

**Comment by magnus-madsen** [comment]
`peek` usually means to look, but not change. `poll` usually means to change.

**Comment by magnus-madsen** [comment]
- Add `peekFront`
- Add `peekBack`
