### ISSUE TITLE
Thunk default in `Option.getWithDefault`

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#3981]
```
pub def getWithDefault(d: a, o: Option[a]): a = match o {
        case None    => d
        case Some(v) => v
    }
```
Could be written like this to allow `?unreachable` as the default fx.
```
pub def getWithDefault(d: Unit -> a, o: Option[a]): a = match o {
        case None    => d()
        case Some(v) => v
    }
```

**Comment by magnus-madsen** [comment]
I thought about this problem before, but since we don't have by-name parameters I don't know what a good solution is.

**Comment by mlutze** [comment]
We could do `Lazy` but that would only allow pure values anyway.

Java's maps have a `getOrCompute` function, which would work for us.

**Comment by magnus-madsen** [comment]
I am closing this. If there is a more general proposal, we can open a "discussion".
