### ISSUE TITLE
Consider alternative approach to auto complete prioritisation

### ISSUE THREAD

**Issue by paulbutcher** [flix/flix#3982]
Auto complete can currently return hundreds of possible completions. For example typing "m" will match enums such as `Map`, defs such as `File.mkdir`, type classes such as `Mod`, keywords like `match`, local variables starting with "m", etc. And the situation will only get worse as we add more auto completions.

Currently, completions are prioritised statically according to what type of completion they are. But clearly, how likely a particular completion is to be correct depends upon context. So if the user is typing:

```
  def myFun(a: ⁁
```

Then an enum or type alias is probably the right completion, a def probably isn't.

Whereas if the user is typing:

```
  def myFun(a: Int32): Int32 =
    p⁁
```

Then a def or local variable are probably the right completions, types etc. probably not.

So I propose that we move to a system in which most completions have "low" priority, but particular types of completion can have their priority boosted depending on context. So, for example, if we see a ":" immediately before the cursor, we would boost enums and type aliases.

I suggest this as a starting point for priorities:

1: Highest (for cases where we have a very high confidence, such as `instance` or `with` completions).
2: Boost (for cases such as the above).
5: Local variables (reasonably high priority, because they're local and therefore likely to be of interest)
7: defs, sigs, and keywords (which typically apply without any special context)
8: enums and type aliases (which typically only make sense within a special context, so will be boosted if that applies)

Thoughts?

**Note**, if at some point in the future we have an incremental compiler, then we can use the parser to determine the context with high accuracy. But in the meantime simple regular expression matching will get us quite a long way, I think.

**Comment by magnus-madsen** [comment]
> So I propose that we move to a system in which most completions have "low" priority, but particular types of completion can have their priority boosted depending on context. So, for example, if we see a ":" immediately before the cursor, we would boost enums and type aliases.

Strongly agree with this idea!

**Comment by magnus-madsen** [comment]
I guess the current "previous token that can guide us" are:

- `with` followed by a type class name.
- `instance` followed by a type class name.
- `:` followed by a type.

A few more ideas:

- `.` followed by a tag or record field.
- `use` followed by a fully-qualified name (there many variants though).
- `query` followed by a local variable
- `from` followed by a predicate symbol

**Comment by magnus-madsen** [comment]
I am keeping this open because there are some other ideas that can be taken into account.

**Comment by paulbutcher** [comment]
> I would like if when I type `: In` it would suggest `Int32` before `Int8`. There are many such situations with other types too. Not sure what the best approach is.

I see the utility of this. For built-in types, we could simply order the list by hand using judgement. But a better solution would be to gather data on actual usage (either usage on the part of the user, or globally).

Perhaps a cache of the last n used completions, ordered by most recently used. Sort auto complete suggestions so that any matching completions which appear in the cache appear first (in the order in which they appear in the cache). And then remaining completions appear in default (i.e. alphabetic) order?

**Comment by magnus-madsen** [comment]
> Ah. That assumes that we know when a completion is used. And I'm not sure that the LSP tells us when the user uses one of the suggestions that we made?

It does not tell us directly. I like your idea of starting with a hand-picked order. Later maybe a student project could use some statistics.

**Comment by magnus-madsen** [comment]
Continued in https://github.com/flix/flix/issues/4554
