### ISSUE TITLE
Simple improvents to the REPL

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3989]
- [x] Allow `\` as a line terminator (i.e. for multi-line inputs).
- [x] Allow `\\` as syntax for starting and ending a multi-line input (i.e. with having to type `\` on each individual line).
- [x] Do not trigger a compilation before an expression is entered. 
- [x] Do not print a progress bar (set option on Flix object).
- [x] Fix `Input input cannot be ...`
- [ ] User defined `~/.flix/Prelude.flix`?
- [x] VSCode open REPL thingy.
- [x] Update `Unknown` command text to not suggest `:run` (since it does not exist anymore.)
- [x] Determine whether to start in "file mode", "project model" or "empty mode".
- [x] Add a command that allows adding/reloading a specific file.
- [x] Rename `Shell` to `repl`? Rename command to launch it?
- [x] Add build commands. 
- [x] Maybe show progress bar on first compile?
- [x] Add `:doc`:

**Comment by paulbutcher** [comment]
Will do, although I'll try to get my head around the code generation side of `object` first?

**Comment by magnus-madsen** [comment]
> Will do, although I'll try to get my head around the code generation side of `object` first?

Sure. No rush on either! :)

**Comment by magnus-madsen** [comment]
Oh- we could also allow the user to run build commands, e.g. `build-jar` from the repl!

**Comment by magnus-madsen** [comment]
> > Fix Input input cannot be ...
> 
> @magnus-madsen what did you have in mind here?

The word "input" repeats.

**Comment by paulbutcher** [comment]
> The word "input" repeats.

🤣 I was assuming that there was something deeper going on. NP 👍

**Comment by paulbutcher** [comment]
> Allow \ as a line terminator (i.e. for multi-line inputs).

I've been looking at this, and I can't make up my mind whether JLine is going to be on our side or against us.

The default parser (which is what we're currently using) provides [`eofOnEscapedNewLine`](https://github.com/jline/jline3/blob/1315fc0bde9325baff8bc4035dbf29184b0b79f7/reader/src/main/java/org/jline/reader/impl/DefaultParser.java#L57) which on the face of things does exactly what we want. Here's how the REPL works with it set:

```
flix> 1 + \                                                                     
> 2
3
```

It also provides `eofOnUnclosedQuote` and `eofOnUnclosedBracked` which do something similar with quotes and brackets, for example:

```
flix> "this is a
dquote> multiline string"
this is a                                                                       
multiline string
```

All great, but this escape processing conflicts with Flix syntax, for example:

```
flix> def sub(x: Int32, y: Int32): Int32 \ { } = ???                            
Error: Input cannot be parsed.
flix> def sub(x: Int32, y: Int32): Int32 \\ { } = ???
Ok.                                                                             
```

All of which is a long-winded way of saying I'm not sure whether the right thing to do is to disable JLine's escape character processing and handle everything ourselves, or whether we should be leveraging this functionality.

My knowledge of JLine isn't currently sufficient to judge, and the documentation is unhelpfully sparse.

Do we have anyone within the project who understands JLine sufficiently to make an informed judgement?

**Comment by magnus-madsen** [comment]
> Do we have anyone within the project who understands JLine sufficiently to make an informed judgement?

Not better than you :) Thanks for the investigation!

I think, ultimately, Flix uses `\`, `"`, and `{}` in too many places that we can rely on JLine to reasonably solve the problem for us. 

Two solutions, one easy and one hard:

- We start with explicit `\` and we handle them ourselves. 
- We can try to figure out if we can get the Parboiled2 Parser to tell us if "Does this parse as an incomplete expression?" If so, we continue to ask for more input. 

I suggest to investigate both in parallel.

**Comment by magnus-madsen** [comment]
- Maybe show progress bar on first compile?

**Comment by paulbutcher** [comment]
> Add a command that allows adding/reloading a specific file.

I'm not convinced of the utility of this. Can we perhaps punt it until/unless we have a firm use case?

**Comment by paulbutcher** [comment]
> Rename Shell to repl? Rename command to launch it?

I think that this is done?

**Comment by magnus-madsen** [comment]
> > Do not trigger a compilation before an expression is entered.
> 
> I'm not sure that this is a good idea? If there are syntax errors in the project or file specified on the command line, we probably want to know about it before entering expressions?

Agreed. We leave it as is.

**Comment by magnus-madsen** [comment]
> > Add a command that allows adding/reloading a specific file.
> 
> I'm not convinced of the utility of this. Can we perhaps punt it until/unless we have a firm use case?

Sure. But I think its this: You have the REPL open. You change a file in your editor and save it. Now what are you supposed to do?

**Comment by magnus-madsen** [comment]
Or is that already supported?

**Comment by paulbutcher** [comment]
> Or is that already supported?

It's already supported by `:reload`. The difference is that `:reload` reloads either the entire project or every file that was specified on the command line (i.e. there's no way to tell the REPL to just reload this specific file).

I'm not sure that I can see a reason why I might want to only reload a single file though?

**Comment by magnus-madsen** [comment]
> > I guess we use Shell internally and how REPL externally. I think REPL is the right name-- at least for the user facing part.
> 
> That's the current situation, yes. Do you think it's worth renaming the internal code?

Its probably fine.

**Comment by paulbutcher** [comment]
@magnus-madsen Any thoughts on this comment from #4199?

> The more I think about this, the more uneasy I become about Windows being a second-class citizen. We should either do the work to allow us to use the most recent version of JLine, or ditch JLine completely, I think.

**Comment by paulbutcher** [comment]
Yes, just build commands left.

User-defined prelude is something that does get used quite heavily in Clojure-land, but then Clojure-land is more REPL-centric. I have no problem with us leaving this until it's proven necessary (or otherwise).

**Comment by paulbutcher** [comment]
I've just created #4284 which adds all the `Packager` commands to the REPL. I suggest that we close this ticket (given that we're going to hold off on user-defined prelude for now) once that's merged?
