### ISSUE TITLE
A way to create a `Nel` from a list plus an element.

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#4018]
I want to create
```
def createNel(x: a, l: List[a]): Nel[a]
```
I can create a Nel with `singleton(x)` but I cannot append the list to it without `List.toNel` which returns an option and thus requires an `?unreachable` case. 

I'm not sure what the solution is. Maybe allow a broader range of things in append? like iterable? This would require two append methods so it also seems a bit weird. Maybe the `createNel` should just be in `Nel.flix`.
```
def append[a](l1: Nel[a], l2: Nel[a]): Nel[a]
```

**Comment by mlutze** [comment]
Doesn't the `Nel` constructor take an element and a list?

Either way, I agree that there's a general issue of interop between `Nel` and `List`. It would be cool to have something like `List[isEmpty: Bool, a: Type]` but that requires GADTs.

**Comment by magnus-madsen** [comment]
I think its fine to use Nel directly.
