### ISSUE TITLE
[CodeGen] Add Source Locations to Generated Code

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#402]
The Flix compiler accurately tracks the source locations of every expression and declaration. 

The bytecode generated by the code generator should use this information to aid in debugging.

See 

http://asm.ow2.org/asm50/javadoc/user/org/objectweb/asm/tree/LineNumberNode.html

and

http://asm.ow2.org/asm50/javadoc/user/org/objectweb/asm/tree/ClassNode.html#sourceDebug
http://asm.ow2.org/asm50/javadoc/user/org/objectweb/asm/tree/ClassNode.html#sourceFile

**Comment by magnus-madsen** [comment]
This one is a good case study:

```
def f(): List[Int] = m()

def m(): List[Int] =
    let o = Some(42);
    match o with {
        case y => List.map(x -> ???, List.range(1, 10))
        case _ => ???
    }
```

If you run this code and insert a breakpoint for `UserException` then we can see how much information the generated code preserves.

**Comment by magnus-madsen** [comment]
@FlaminGuy We can close this right?

**Comment by FlaminGuy** [comment]
I believe so.
