### ISSUE TITLE
Inexhaustive match in Datalog engine

### ISSUE THREAD

**Issue by mlutze** [flix/flix#4027]
Here in `IndexSelection.flix`: https://github.com/flix/flix/blob/master/main/src/library/Fixpoint/IndexSelection.flix#L152
```scala
    def prefixHelper(i: Int32, prefix: List[BoolExp[v]], rest: List[BoolExp[v]], eqs: List[List[BoolExp[v]]]): (List[BoolExp[v]], List[BoolExp[v]]) =
        match eqs {
            case e :: es =>
                let (p, r) = List.partition(match BoolExp.Eq(RamTerm.RowLoad(_, j), _) -> i == j, e);
                prefixHelper(i + 1, prefix ::: p, rest ::: r, es)
            case Nil => (prefix, rest)
        }
```

The `match BoolExp.Eq ...` is not exhaustive. This was uncaught because of a bug in exhaustiveness checking.

See https://github.com/flix/flix/pull/4026

**Comment by magnus-madsen** [comment]
@JonathanStarup Can you take a look?

**Comment by JonathanStarup** [comment]
to fix the fixpoint code?

**Comment by magnus-madsen** [comment]
> to fix the fixpoint code?

Yes
