### ISSUE TITLE
[CodeGen] Emit Monomorphed Classes for Enums

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#403]
In the current implementation, the code generator uses `Value.Tag` to represent enums (tagged values).

A better approach is for the code generator to generate Java interfaces and classes for each enum.

For example, the enum:

```
enum Color {
  case Red(Unit),
  case Green(Unit),
  case Blue(Unit)
}
```

should become a Java interface:

```java
interface Color {
  public String getTag()
  public Object getValue()
}
```

and three Java classes:

```java
class Red extends Color {
  public Unit value = null
  // constructor
  // implementations of:
  // - getTag
  // - getValue
  // - equals
  // - hashCode
  // - toString
}
...
```

**Comment by FlaminGuy** [comment]
I don't see any reason to have interfaces for Enum super types. Enum field is never used in `Codegen.scala`. It only uses tag.      
We can just have a general interface like:
`interface EnumInterf {`
`  public String getTag()`
`  public Object getValue()`
`}` 
And for comparison we can just use `instanceof` and `getValue()`,

**Comment by magnus-madsen** [comment]
Compare the signatures:

```
def foo(x: EnumInterf): ... = ...
```

```
def foo(x: Color): ... = ...
```

The latter (1) gives the JVM more information about what possible values can occur, (2) is useful if someone wants to call a Flix method from Java, and (3) makes debugging/understanding the compiled code easier.

That said, I think you have a point that we should have TWO interfaces, like so:

```
interface Tag {
  public String getTag()
  public Object getValue()
}

interface Color { ... }

class Red implements Color, Tag
```

Since that gives the best of both worlds. We can talk about tags abstractly using the "Tag" interface and more concretely using the "Color" interface.

**Comment by magnus-madsen** [comment]
To clarify, the `Tag` interface itself should probably not be emitted by the code generator, but already defined as part of Flix. Perhaps in `ca.uwaterloo.flix.runtime.Tag` or similar.

**Comment by magnus-madsen** [comment]
Fixed.
