### ISSUE TITLE
Refactor LSP Structures

### ISSUE THREAD

**Issue by mlutze** [flix/flix#4032]
- [ ] `occurrenceOf` / `useOf` / `defOf` is confusing and seems inconsistent. I think this should be simplified to `useOf` and `defOf` if possible. If not possible, documentation explaining the differences is necessary.
- [ ] `Entity.Exp` and `Entity.Type` are broad and clumsy as we have to re-match on the expression/type and throw away most cases. A dedicated entity for each applicable expression and type would be clearer and easier to maintain (e.g. `Entity.ExpUse`, etc.)
- [ ] `ImplementationProvider.classAt` looks like it could be simplified since we have `InstanceSym`s
- [ ] There is a lot of repetition which might be reducible with some abstractions, such as using the `Locatable` trait
- [ ] In general, documentation is sparse. Something at the head of each file at least would help a lot (see #3444)

**Comment by magnus-madsen** [comment]
What about things that are neither defs nor uses? E.g. predicate symbols. 

What do propose to replace `Entity.Exp` by?

**Comment by mlutze** [comment]
> What about things that are neither defs nor uses? E.g. predicate symbols.

I think these deserve their own category of things.


> What do propose to replace `Entity.Exp` by?

My current model keeps it, but divides entities into precise (e.g., a sym use) and imprecise (e.g. an expression)

**Comment by magnus-madsen** [comment]
Outdated.
