### ISSUE TITLE
Syntax of Records and Record Types

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4033]
Why is this inconsistent:

```
let _r: { x :: Int32 } = { x = 123 };
```

Can we change it to:

```
let _r: { x = Int32 } = { x = 123 };
```

**Comment by magnus-madsen** [comment]
@mlutze Does this require a single line change in the `Parser` and then a lot of work in the standard library?

**Comment by mlutze** [comment]
> @mlutze Does this require a single line change in the `Parser` and then a lot of work in the standard library?

I think so

**Comment by magnus-madsen** [comment]
@stephentetley We are changing the syntax of records types to match their expression syntax (see above). Sorry for any breakages, but this should be a purely search-and-replace fix.

**Comment by stephentetley** [comment]
Thanks for the heads up, Magnus. I won't update to head until I've got plenty of time.

**Comment by magnus-madsen** [comment]
@stephentetley OK, but I don't want to break your code and prevent you from following master, so how about we support both syntaxes for a transition period (it causes not breakages) and then you can refactor over time?

**Comment by stephentetley** [comment]
A transition period wouldn't be necessary for me, I'd just need to do it over a weekend when I've whole day to do it all.

**Comment by magnus-madsen** [comment]
OK, but there is no harm in us supporting both for a short while.
