### ISSUE TITLE
`MutList.get` should return `Option[a]`

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#4039]
It currently returns `a` or crashes the program if there is no element at the position. This is quite unsafe in my opinion.

**Comment by magnus-madsen** [comment]
Why do we even have such a function? I would say remove it and any other function like this.

**Comment by mlutze** [comment]
Why remove it? Is random access not part of the mutable list API?

**Comment by magnus-madsen** [comment]
The problem is: If you want random access then its probably for performance and then you don't want to be allocating Options. So what to do?

**Comment by JonathanStarup** [comment]
i think the option versions are okay, it feels mean to abandon people if they want functional random access. O(1)+option allocation still seems better than O(n). 

Although another option is to make a map the canonical choice here but that probably isnt faster.

**Comment by magnus-madsen** [comment]
I have added this to the meeting for discussion.
