### ISSUE TITLE
Use Nel in `RelOp`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4043]

**Comment by JonathanStarup** [comment]
Do you still want me to look into this, @magnus-madsen?

**Comment by magnus-madsen** [comment]
Yes

**Comment by JonathanStarup** [comment]
Constraints are stored as a single enum with a denotational tag. The head terms of the constraint are non-empty only if it is a lattice predicate. The nullary relational predicates have no terms internally, so relational terms can be empty. We can either:

1) Split the `Constraint` enum into `RelConstraint` and `LatConstraint`. This will add code in places that do not distinguish.
2) Make nullary predicates carry a unit value such that all term lists are non-empty.
3) Do nothing.

**Comment by magnus-madsen** [comment]
OK, do nothing then.
