### ISSUE TITLE
Review standard library for use of `Static` and `Impure`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4047]
We should review the standard library to ensure that every use of `Static` and/or `Impure` is necessary, 
i.e. if regions can be used instead, they should be. 

We are already refactoring the Datalog engine in: https://github.com/flix/flix/issues/3896

But we still have all these occurrences left:

![image](https://user-images.githubusercontent.com/2287953/175834008-67d1b8ab-d6d4-4456-b72d-83022878cbc6.png)

and

![image](https://user-images.githubusercontent.com/2287953/175834020-8679ff72-aa1b-4a2d-ac62-e61f10e2d820.png)

**Comment by magnus-madsen** [comment]
@JonathanStarup Ill make you the "Static and Impure" czar. Basically, if you could figure out which of these can be fixed (and what it would take), and then we can hopefully delegate those tasks to Jakob or Nina. 

Obviously a lot of `Impure` annotations are fine and should stay. For `Static` I would expect most can disappear. Agree?

**Comment by jaschdoc** [comment]
Same issue as #3841?

**Comment by jaschdoc** [comment]
> [ ] (Static import, Impure import) `getArgs` should instead import as `Array[String, r]` in a local region.

The impure import is correct, no? Should be impure to interact with a stateful environment.

**Comment by magnus-madsen** [comment]
> > (Static import, Impure import) `getArgs` should instead import as `Array[String, r]` in a local region.
> 
> The impure import is correct, no? Should be impure to interact with a stateful environment. Do you want it to write to a local region instead?

Function has to be impure, import is correct, but could return a List.

**Comment by JonathanStarup** [comment]
But the program arguments are fixed for the whole program duration, so it should always return an array with the same content (the array returned is even a copy so you can't mess that part up). Thats why it shouldn't be impure imo but just be a regioned array

**Comment by magnus-madsen** [comment]
What's the overall picture now?

**Comment by JonathanStarup** [comment]
## `as & Pure`
22/62 occurrences
* `DelayMap` thread related RBT calls
* `Map` thread related RBT calls
* `Set` thread related RBT calls
36/62 occurrences
* Benchmarking (28)
* Fixpoint (8)

## Impure

**Comment by magnus-madsen** [comment]
I suggest we:

- Leave the DelayMap and RBT stuff alone.
- Come up with a refactoring of Benchmarking (will you propose something?)
- Leave the File stuff alone.
- Leave the Channel stuff alone.
- I am not sure what can be done for Choose since it is non-deterministic.

**Comment by JonathanStarup** [comment]
> Leave the Channel stuff alone.
> I am not sure what can be done for Choose since it is non-deterministic.

I think that 
```
def choose[a](r: Random, a: Array[a, Static]): Option[a] & Impure
```
should be
```
def choose[a](r: Random, a: Array[a, r]): Option[a] & Impure
```
Since this allows calling `choose` on non-static arrays.

---

One of the `File` functions I thought about was
```
def readBytes(f: String): Result[Array[Int8, Static], String] & Impure
```
The above function could also be written:
```
def readBytes(r: Region[r], f: String): Result[Array[Int8, r], String] & Impure
```
The obvious downside of this kind of refactoring is that we now have a region argument that does not remove the impurity. Still, the upside of using regions is that a future change might remove the effect (like with algebraic effects) and thus only expose the region effect if Static is not used. So I think the general question is: should the Static region be used in production code, or is it primarily a tool for work-in-progress code?

**Comment by JonathanStarup** [comment]
@magnus-madsen I think this can be closed, There's no Impure and Static is only used in relation to things like file/system/imports
