### ISSUE TITLE
Mark enums as opaque in the standard library

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4048]
These enums:

- `DelayList` and `DelayMap`.
- `Set` and `Map`.

**Comment by magnus-madsen** [comment]
What's opaque supposed to do? Disallow pattern matching?

**Comment by mlutze** [comment]
> What's opaque supposed to do? Disallow pattern matching?

Yes, and construction. Users are forced to interact with values of the type via the provided functions.

**Comment by mlutze** [comment]
This is still relevant, though blocked until the opaqueness change is made (Opaque types only destructable in their companion namespace)
