### ISSUE TITLE
error message when running top-level function

### ISSUE THREAD

**Issue by jacopol** [flix/flix#4079]
The following error was generated, but didn't point to the actual problem:

```
>> The entry point mainX cannot be found.

Possible fixes:

  (1)  Change the specified entry point to an existing function.
  (2)  Add an entry point function mainX.

Compilation failed with 1 error(s).
```

The actual solution in my case would have been:
  (3) Ensure that mainX is "pub"

**Comment by JonathanStarup** [comment]
I'd also like to add to this error now that there is a ticket. if you write `NsA/NsB/NsC.function` i'd like to know where it went wrong e.g `NsC` not found.

**Comment by mlutze** [comment]
@JonathanStarup You mean if the namespace doesn't exist, we should indicate that instead of saying that the function at that path doesn't exist?

**Comment by magnus-madsen** [comment]
Assume fixed.
