### ISSUE TITLE
Regions & Java imports should not throw a redundancy error

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#4082]
The function below throws a redundancy error since the term level `r` is not used within the function. A solution to the problem is to introduce a line `let _ = r;` on the line above `Array.toList(...)`. Should we add some exceptions to the redundancy check when it comes to regions? Maybe if the region is used at the type level then the redundancy is considered okay?
```flix
pub def split(regex: {regex :: String}, s: String): List[String] = region r {
    import java.lang.String.split(String): Array[String, r] \ Write(r);
    Array.toList(split(s, regex.regex))
}
```

**Comment by magnus-madsen** [comment]
Outdated.
