### ISSUE TITLE
Redundant import of tag when importing opaque type

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#4124]
When importing an opaque type we both have to import the type and also its tag. It'd be nice if could simply import the type and use that name for the tag. E.g. in the example below I would like to simply import `MyEnum` with `use SomeNamespace.MyEnum`.

```flix
namespace UsesTheOtherNamespace {

    pub def foo(): Bool =
        use SomeNamespace.MyEnum.MyEnum;
        let MyEnum(x) = MyEnum(false);
        x

}

namespace SomeNamespace {

    pub enum MyEnum(Bool)

}
```

**Comment by magnus-madsen** [comment]
We have recently reworked the namespace (now module) mechanism.
Hence this ticket is most likely no longer relevant.
Feel free to common and/or re-open if it is.
