### ISSUE TITLE
A few statistics

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4128]
I would like to collect some statistics that I need for a paper submission on Friday.

- The number of functions that use records, like `Array.replace` (per namespace).
- The number of functions that exists both in immutable and mutable version (e.g. Array.reverse and Array.reverse) (per namespace).
- The total number of destructive functions (probably just all public functions that have ! in their name).

(Note I only care about public `pub` functions).

Feel free to use https://api.flix.dev/ or search the source code. 

In any case, if there is doubt pick the lower / safer number.

**Comment by magnus-madsen** [comment]
@ninaandrup Will you be able to count these things for me in the next few days? :)

**Comment by ninaandrup** [comment]
Namespaces | Functions with records |  Functions both immutable/mutable
-- | -- | --
Array | 2 | 7
Choice | 1 | 0
Console | 1 | 0
DelayList | 1 | 0
File | 10 | 
Int8 | 7 |
Int16 | 9 |
Int32 | 1 | 
Int64 | 1 | 
Iterator | 1 |
List | 1 |
MutList | 1 |
MutSet | 1 |
Nec | 1 | 
Nel | 1 |
Option | 1 |
Result | 2 |
Set | 1 |
String | 22 |
Validation | 1 |


I have omitted the namespaces with 0 of both

**Comment by ninaandrup** [comment]
And there is 64 public functions that have ! in their name.
