### ISSUE TITLE
(style) Decide syntax for `override` for std lib

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#4129]
We have a few places in the library where type class instances override some of the implementations but it's not consistent where people have put the `override` keyword. Specifically we should decide whether we write `override pub def` or `pub override def`. This obviously has very low priority.

Here's an example from `Nec`:

```flix
instance Traversable[Nec] {
    pub def traverse(f: a -> m[b] & ef, t: Nec[a]): m[Nec[b]] & ef with Applicative[m] = Nec.traverse(f, t)
    pub override def sequence(t: Nec[m[a]]): m[Nec[a]] with Applicative[m] = Nec.sequence(t)
}

instance Reducible[Nec] {
    pub def reduceLeftTo(f: (b, a) -> b & ef1, g: a -> b & ef2, l: Nec[a]): b & (ef1 and ef2) = Nec.reduceLeftTo(f, g, l)
    pub def reduceRightTo(f: (a, b) -> b & ef1, g: a -> b & ef2, l: Nec[a]): b & (ef1 and ef2) = Nec.reduceRightTo(f, g, l)
    override pub def head(l: Nec[a]): a = Nec.head(l)
    override pub def last(l: Nec[a]): a = Nec.last(l)
    ...
}
```

**Comment by mlutze** [comment]
In scala, `override` comes first: https://docs.scala-lang.org/style/declarations.html

**Comment by magnus-madsen** [comment]
I think override first.

See also https://github.com/flix/flix/discussions/6173
