### ISSUE TITLE
[CodeGen] Remove All Dependencies on Value class From the Code Generator

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#415]
Eliminate all usages of the `Value` class, including `mkBool`, `mkChar` etc.

**Comment by FlaminGuy** [comment]
Unless we want to unify Interpreter with CodeGen then we still need `Value`.

**Comment by magnus-madsen** [comment]
What do you mean?

**Comment by FlaminGuy** [comment]
Value and things inside it like Tag and those functions are used heavily in interpreter so I'm not sure we can get rid of value without changing Interpreter.

**Comment by magnus-madsen** [comment]
Oh right. What I meant is to remove all dependencies on value from the code generator :)

**Comment by magnus-madsen** [comment]
We still need to get rid of all dependencies on Value in TestBackend, but we can do that as part of the refactor of TestBackend.

**Comment by magnus-madsen** [comment]
Fixed! :D
