### ISSUE TITLE
feat: generalize collection in `StringBuilder`

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#4152]
I think a version of this function should exist that works with Foldable perhaps.
`pub def appendLinesWith!(f: a -> String & ef, a: Array[a, r1], sb: StringBuilder[r2]): Unit \ { ef, Read(r1), Write(r2) } = ...`

**Comment by magnus-madsen** [comment]
Maybe not in foldable, but somewhere else?

**Comment by magnus-madsen** [comment]
(I don't think Foldable should depend on StringBuilder)

**Comment by JonathanStarup** [comment]
> Maybe not in foldable, but somewhere else?

I agree, I think that the function should still be in `StringBuilder` but just generalize `Array` to `Foldable`
