### ISSUE TITLE
Collect a list of functions that can crash

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4168]
- Array.get
- Array.put
- Channel.new(-1)

**Comment by JonathanStarup** [comment]
Does a[42] count?

**Comment by paulbutcher** [comment]
Can arithmetic operations crash with overflow, underflow, rounding?

**Comment by paulbutcher** [comment]
Any IO function can potentially crash with an `IOException`

**Comment by magnus-madsen** [comment]
(I needed this for a paper, but that is now out.)

I guess we could debate whether to annotate these functions with `@Unsafe`.
