### ISSUE TITLE
Refactor "Old" Flix Benchmarks to new Flix syntax

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#417]
The benchmarks are available at:

http://git.uwaterloo.ca/

(requires special access)

**Comment by magnus-madsen** [comment]
The benchmarks are here:

https://github.com/flix/benchmarks

**Comment by magnus-madsen** [comment]
Changes necessary:

- Replace `in` by `;`
- Zero argument functions must be called with parens, so not `f`, but `f()`.
- Namespaces must be uppercase.
- Constructors can avoid enum prefix, so not `Foo.Bar` but just `Bar`

**Comment by magnus-madsen** [comment]
@FlaminGuy This is something you can work if get stuck or blocked on what you are currently looking into.

**Comment by magnus-madsen** [comment]
It would be useful to have this information soon so that we have an idea of how we compare to say Scala.

**Comment by magnus-madsen** [comment]
Hey, what is the status on this?

**Comment by FlaminGuy** [comment]
I haven't done anything about them yet. I will do it after references and optimization of enum cases.
