### ISSUE TITLE
ArrayLoad should be effect-polymorphic

### ISSUE THREAD

**Issue by mlutze** [flix/flix#4190]
Currently in the Typer its purity is set to `Impure` in the reconstruction step

**Comment by mlutze** [comment]
and slice.... just need to check all of them :D

**Comment by magnus-madsen** [comment]
What? How can that be true and not give us problems?

**Comment by mlutze** [comment]
It happens after type inference, so I assume that's why

**Comment by magnus-madsen** [comment]
Ah okay
