### ISSUE TITLE
Add custom error messages for missing instances of `Functor`, `Monad`, and `FunctorFilter`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4192]
This becomes relevant after foreach and for-yield has been added.

**Comment by jaschdoc** [comment]
I guess the error messages should be for missing instances of:
- `Monad`
- `MonadZero`
- `Applicative`
- `Iterable`

What do you reckon they should say? Something like "Missing instance of `Monad`. Hint: If you're trying to iterate over the collection with a for-loop, you have to add an instance of the type class to the collection`.

**Comment by magnus-madsen** [comment]
Yes, but let us hold of a bit.

**Comment by magnus-madsen** [comment]
Deferred until later.
