### ISSUE TITLE
Non-pure recursive functions

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#4210]
Recursive pure functions can soundly and correctly be typed with any effect
```
def f(n: Int32): Bool & Impure =
    if (n == 0) true else not f(n-1)
```
This is however not beneficial when refactoring code from impure code to pure code. This has been brought up before but I am more convinced of its relevancy after being in this situation four times during the refactoring of the datalog engine.

**Comment by magnus-madsen** [comment]
I agree but its not really solvable.
