### ISSUE TITLE
Enforce `let` before bindings?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4219]
Do we want to have a syntactic principle where bindings should be prefixed by `let` in most (all?) cases?

E.g.

```
foreach(let x <- xs)
for (let x <- xs)
```

**Comment by magnus-madsen** [comment]
@JonathanStarup @mlutze @jaschdoc Thoughts?

**Comment by JonathanStarup** [comment]
I lean towards let

**Comment by jaschdoc** [comment]
I agree that it is nice in for-loops, but I'm hesitant to add it to match-cases as it just adds more visual clutter.

**Comment by magnus-madsen** [comment]
Lets not do it.
