### ISSUE TITLE
Zipper on RedBlackTree

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4222]
We need a zipper on the RedBlackTree such that we can navigate it efficiently and use the zipper as the basis for the Iterator implementation.

**Comment by stephentetley** [comment]
I can't see a PR for RedBlackTree.iterator already?

If there isn't one then is a Jean-Christophe Filliatre style inorder iterator good enough?

http://www.lri.fr/~filliatr/publis/enum2.pdf

~~~

namespace Inorder {

    use RedBlackTree.RedBlackTree;
    use RedBlackTree.RedBlackTree.{Node, Leaf, DoubleBlackLeaf};

    pub def inorder(f: (k, a) -> Unit & ef, t: RedBlackTree[k, a]): Unit & ef = match t {
        case Node(_, ltree, k, v, rtree) => {inorder(f, ltree); f(k, v); inorder(f, rtree)}
        case _                           => ()
    }

    pub enum Enum[k, v] { 
        case End
        case More(k, v, RedBlackTree[k,v], Enum[k, v])
    }

    def left(t: RedBlackTree[k, v], e: Enum[k, v]): Enum[k, v] = match t {
        case Leaf => e
        case DoubleBlackLeaf => e
        case Node(_, ltree, k, v, rtree) => left(ltree, More(k, v, rtree, e))
    }

    pub def iteratorWithKey(r: Region[r], t: RedBlackTree[k, a]): Iterator[(k, a), r] \ { Write(r) } =
        let start = left(t, End);
        let state = ref start @ r;
        let done = () -> match (deref state) {
            case End => true
            case _   => false
        };
        let next = () -> match (deref state) {
            case End                  => bug!("Call to next not guarded by done")
            case More(k, v, rtree, e) => {
                state := left(rtree, e);
                (k,v)
            }
        };
        Iterator(done, next)
}

~~~

The `inorder` function isn't needed and is just for reference.

Filliatre's iterator is a defunctionalized version of a CPS iterator so one would hope it is stack safe. This would need verifying of course.

**Comment by magnus-madsen** [comment]
How does it work? It uses continuations to capture the current "position" in the tree?

**Comment by magnus-madsen** [comment]
There is no iterator. We need something like the above on RedBlackTree and then we can use it on Set and Map.

**Comment by stephentetley** [comment]
Maybe it is easier to comprehend without the `Enum` type which is just a List specialized to have three values (key, value, right tree) for the for the element.

Here `Enum` is now called `Stack` because it is the pending stack of triples to be processed: 

~~~

namespace Inorder {

    use RedBlackTree.RedBlackTree;
    use RedBlackTree.RedBlackTree.{Node, Leaf, DoubleBlackLeaf};


    type alias Stack[k, v] = List[(k, v, RedBlackTree[k,v])]

    def left(t: RedBlackTree[k, v], es: Stack[k, v]): Stack[k, v] = match t {
        case Leaf                        => es
        case DoubleBlackLeaf             => es
        case Node(_, ltree, k, v, rtree) => left(ltree, (k, v, rtree) :: es)
    }

    pub def iteratorWithKey(r: Region[r], t: RedBlackTree[k, a]): Iterator[(k, a), r] \ { Write(r) } =
        let stack1 = left(t, Nil);
        let state = ref stack1 @ r;
        let done = () -> match (deref state) {
            case Nil => true
            case _   => false
        };
        let next = () -> match (deref state) {
            case Nil                 => bug!("Call to `next` not guarded by `done`")
            case (k, v, rtree) :: es => {
                state := left(rtree, es);
                (k,v)
            }
        };
        Iterator(done, next)


}

~~~

The `left` function has to be run first , it chases down the left side of a Tree until it finds the leftmost node. As it goes left it builds a stack of key, value and right trees triples to be evaluated later. Once you are in the iterator proper you haven't fully flattened the RBTree (you still have righthand sides in the pending stack), so in the `next` of the iterator you still have to find left on the head of the stack.

**Comment by magnus-madsen** [comment]
Thanks; that helps!

Would you be interested in adding it to RedBlackTree and then using it in Set/Map?

**Comment by stephentetley** [comment]
Yes I can start on it tomorrow (Wednesday) evening, and MultiMap as well.

Do you want two iterators - one with just values and with keys and values?
