### ISSUE TITLE
Add `WISHLIST.md`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4223]
A file we can add good suggestions to which we do not yet have the time to pursue.

- Machine learning-based rankings of auto-complete suggestions.
- Flix written in in Flix.
- A machine-checked compiler.
- A purple unicorn.
- A fearsome dragon.
- ...

and things labelled `future`.

Things not wished for:
- Async and await.

**Comment by JonathanStarup** [comment]
Verification things like quickcheck/termination prover etc?
