### ISSUE TITLE
Polish `foreach`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4224]
- [x] Add `foreach` as keyword snippet to `CompletionProvider`.
- [x] Add `foreach` as a keyword to https://github.com/flix/vscode-flix.
- [ ] Figure out what goes wrong with the syntactic highlight of the second foreach: ![image](https://user-images.githubusercontent.com/2287953/178248163-8b5100dd-5085-4b6a-9d99-e80ebc71df25.png)
- [x] Use `foreach` in all our mutable `ToString` instances. 
- [x] Ensure every collection has an `iterator` (e.g. `MutList` seems to lack one).
- [x] https://github.com/flix/flix/issues/4225
- [x] Refactor the de-sugaring to call `Iterator.foreach(f, Iterable.iterator(X))`.
- [x] Add `iterator` to prelude as an alias for `Foldable.iterator`.
- [x] Ditty for `enumerator`.
- [ ] Add custom compiler message for missing instance of `Iterable`.

**Comment by jaschdoc** [comment]
- [ ] Add foreach as keyword snippet to CompletionProvider.
- [ ] Add foreach as a keyword to https://github.com/flix/vscode-flix.
- [ ] Figure out what goes wrong with the syntactic highlight of the second foreach: image
- [ ] Use foreach in all our mutable ToString instances.
- [ ] Ensure every collection has an iterator (e.g. MutList seems to lack one).
- [ ] https://github.com/flix/flix/issues/4225
- [ ] Refactor the de-sugaring to call Iterator.foreach(f, Iterable.iterator(X)).
- [ ] Add iterator to prelude as an alias for Foldable.iterator.
- [ ] Ditty for enumerator.
- [ ] Add custom compiler message for missing instance of Iterable.

**Comment by jaschdoc** [comment]
Hmm not sure about your vscode thing. Mine works just fine.
![Screenshot from 2022-07-14 14-56-06](https://user-images.githubusercontent.com/60233376/178987617-6fe61614-450d-476f-912f-413badbe9aa1.png)

**Comment by jaschdoc** [comment]
Do we want enumerator on maps to return an iterator of type `Iterator[(k, v, Int32), r]`?
Instead of `Iterator[((k, v), Int32), r]

**Comment by magnus-madsen** [comment]
> Do we want enumerator on maps to return an iterator of type `Iterator[(k, v, Int32), r]`? Instead of `Iterator[((k, v), Int32), r]`

I think enumerators on maps would be a bit silly? How about we just omit them?

**Comment by jaschdoc** [comment]
Alright sounds good.

**Comment by jaschdoc** [comment]
What do you think we should do with the `Ident` issue? https://github.com/flix/flix/issues/4224#issuecomment-1184564176
