### ISSUE TITLE
Iterable (redux)

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4225]
Replace `Iterable` by:

```
///
/// A type class for Iterable region-based collections.
///
pub class Iterable[m: Type -> Region -> Type] {

    ///
    /// Returns an iterator over `m`.
    ///
    pub def iterator(i: m[a, r]): Iterator[a, r] \ {Read(r), Write(r)}

}
```

Implement instances for all mutable collections and for `Iterator` itself (!) (Delete all instances for immutable collections.)

**Comment by jaschdoc** [comment]
Should `iterator` take a region parameter? E.g. `def iterator(r1: Region[r2], m: m[a, r2]): Iterator[a, r1 and r2] \ ...` ?

**Comment by magnus-madsen** [comment]
> Should `iterator` take a region parameter? E.g. `def iterator(r1: Region[r2], m: m[a, r2]): Iterator[a, r1 and r2] \ ...`?

No, it reuses the region of the mutable data type.

**Comment by jaschdoc** [comment]
So what is the issue with iterating over `RedBlackTree`? I think @ninaandrup found a solution back when she worked on it.

**Comment by magnus-madsen** [comment]
> So what is the issue with iterating over `RedBlackTree`? I think @ninaandrup found a solution back when she worked on it.

We need a zipper like data structure.
