### ISSUE TITLE
Refactor Boolean Infrastructure

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4235]
- [ ] Rename `BoolTable` to `BoolAlgTable` or BoolAlgebraTable?
- [x] Ensure `BoolTable` is completely independent of `Type`. (Maybe introduce `BoolMinimization` class?
- [ ] Rename `BoolFormula` to `BoolAlgebra`
- [ ] Redocument `BoolFormula` so it is agnostic about formula vs set expression.
- [ ] Rename `True/False` to Top/Bot or maybe Universe/Empty or ?

**Comment by mlutze** [comment]
> Redocument `BoolFormula` so it is agnostic about formula vs set expression.

What terminology should I use?
- Latticelike (`join`, `meet`) or (`lub`, `glb`)
- Nontechnical (`both`, `either`)
- Something else?

**Comment by magnus-madsen** [comment]
> 

What does the literature use?

**Comment by magnus-madsen** [comment]
I suggest to use the lattice terms:

- Top, Bot, Join, Meet.
