### ISSUE TITLE
Polish Set Effects

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4236]
- [x] Non-public op: The *explanation* should state: An effect operation must be public. 
- [x] Introduce a distinct error message for duplicate op. (If there is already one, its text should be updated).
- [ ] Update error message: "Unexpected effect parameter(s)". Also, it should not say tip in the explanation.
- [x] Undefined operation has extra quotes. 
- [x] Add auto-complete support for `do ...`.
- [x] Add Goto-def for operations.
- [x] The `Redundancy` phase rejects a stm exp `do op; exp2`.
- [x] Effect sets are formatted as `Print + Throw`, but should it not be `{Print, Throw}`?
- [x] Add `without` to VSCode.
- [x] Add `without` to auto-complete suggestions.
- [x] Allow sugar `without Throw,NonDet,Print`
- [x] ~Its very confusing that we use `&` for two things. Proposal (temporarily) rename `&` to `&&` and `|` to `||` for the set part.~
- [ ] Cleanup typer.
- [x] Use effects in monomorphization (?)
- [x] Explore if we can pretty print `ef & (not ConcreteEffect)` as `ef - ConcreteEffect`.
- [x] Ensure Redundancy phase runs for effect handlers
- [ ] Add a metric truckload of tests (both positive and negative)
- [ ] Check for unused effects

#### Bugs:
- [x] Effect.Set (`& { }`)
- [ ] Formulas are not always simplified: `String -> Unit \ (Throw + (e3713740 & Print)) & (~Print)`.
- [ ] Semantic highlighting is sometimes broken: `let _a = f(u -> do Throw.throw(u));`.

#### Future work:
- [ ] Add rename support for effect operations.
- [ ] Add rename support for effects.

**Comment by magnus-madsen** [comment]
I suggest to do small targeted PRs for better reviews instead of everything at once :)

**Comment by mlutze** [comment]
> Semantic highlighting is sometimes broken: `let _a = f(u -> do Throw.throw(u));`.

Unable to reproduce

**Comment by mlutze** [comment]
Renaming Effs and Ops is a little tricky. We do the same namespacing trick as Classes, using a companion namespace, so changing an Eff name is tantamount to changing a namespace name. We don't currently support renaming classes or sigs because of this difficulty.

**Comment by mlutze** [comment]
> Allow sugar `without Throw,NonDet,Print`

Note that this will introduce a parsing ambiguity. Consider: `let x = (e without Throw, None, Fish)` Is `x` a tuple or a singleton?

**Comment by magnus-madsen** [comment]
> Renaming Effs and Ops is a little tricky. We do the same namespacing trick as Classes, using a companion namespace, so changing an Eff name is tantamount to changing a namespace name. We don't currently support renaming classes or sigs because of this difficulty.

OK; lets wait with this one.

**Comment by magnus-madsen** [comment]
> > Allow sugar `without Throw,NonDet,Print`
> 
> Note that this will introduce a parsing ambiguity. Consider: `let x = (e without Throw, None, Fish)` Is `x` a tuple or a singleton?

OK, lets not do. Perhaps we could allow a set?

**Comment by mlutze** [comment]
> > > Allow sugar `without Throw,NonDet,Print`
> > 
> > 
> > Note that this will introduce a parsing ambiguity. Consider: `let x = (e without Throw, None, Fish)` Is `x` a tuple or a singleton?
> 
> OK, lets not do. Perhaps we could allow a set?

Yes, but only a set of constants, right?

**Comment by magnus-madsen** [comment]
I updated the checklist.

**Comment by mlutze** [comment]
> Non-public op: The explanation should state: An effect operation must be public.

The `IllegalPrivateDeclaration` is a single error covering classes, instances, and effects. I could:
1. Make the error message general enough, e.g., `The following declarations must be public: X, Y, Z`
2. Pass an enum parameter to the error to determine the message
3. Create a separate error object for each case

> Introduce a distinct error message for duplicate op. (If there is already one, its text should be updated).

Because of the way namespaces are handled, an operation may not share a name with a definition, so the error message is sufficiently general to cover def-def, def-sig, def-op, sig-op, sig-sig, op-op duplications. If we want something more specific, we could maintain what type of declaration each is and pass it into the message somehow. Is it worth it?

> Add auto-complete support for do ....

The idea is that after a `do` we get all the operations that could be called?

**Comment by magnus-madsen** [comment]
> > Non-public op: The explanation should state: An effect operation must be public.
> 
> The `IllegalPrivateDeclaration` is a single error covering classes, instances, and effects. I could:
> 
>     1. Make the error message general enough, e.g., `The following declarations must be public: X, Y, Z`

OK, let's ensure that the error message is sufficiently general.

> Because of the way namespaces are handled, an operation may not share a name with a definition, so the error message is sufficiently general to cover def-def, def-sig, def-op, sig-op, sig-sig, op-op duplications. If we want something more specific, we could maintain what type of declaration each is and pass it into the message somehow. Is it worth it?

Good point. Let's leave the error message, but ensure it is sufficiently general.

> The idea is that after a `do` we get all the operations that could be called?

Yep. We only get effect operations (or at least with high priority).

**Comment by magnus-madsen** [comment]
What is the problem with renaming an effect **operation** again?

**Comment by mlutze** [comment]
The location of an `OpSym` carries its entire fully-qualified name, with namespace and effect name. So we can't narrow it down to only the operation part. Some hacky options that I don't like:
1. Only include the unqualified part in the location (this is done for DefSyms, I think)
2. Examine the location of the sym and only modify the text from the last `.` onward

A better solution IMO is to give the namespace part and the unqualified name part different locations, but this is probably a more complex design change.

**Comment by magnus-madsen** [comment]
But its only the op name part that is renamed, no? E.g. `print` to `print2`?

**Comment by magnus-madsen** [comment]
> Right, but `OpSym` points to `Console.print`, so a rename (I think) would try to change `Console.print` to `print2`.

Because `OpSymUse` does not save its constituents I guess?

**Comment by magnus-madsen** [comment]
But I still think it could just overwrite it with the new name. (At least until we allow `use` of effect-- we don't have that yet, right?)

**Comment by mlutze** [comment]
> Because `OpSymUse` does not save its constituents I guess?

Right.

> But I still think it could just overwrite it with the new name. 

But then we get "can't find `print2`" errors :(

> (At least until we allow use of effect-- we don't have that yet, right?)

Effects are namespaces so you should be able to do `use Console.print; ... do print("hello")`

**Comment by magnus-madsen** [comment]
> > Update error message: "Unexpected effect parameter(s)". Also, it should not say tip in the explanation.
> 
> Is this referring to the error about type parameters on effects?

I forget.

**Comment by magnus-madsen** [comment]
Do we want to ban unused effects?

**Comment by mlutze** [comment]
> Do we want to ban unused effects?

Yep, it's in the list.

> Do we want to create a few separate ticket for the bigger items?

Yes, I have one for the tests already.
