### ISSUE TITLE
Improvements to `spawn` and the `par` construct

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4262]
I got excited about Project Loom -- due to land in the fall -- which brings us light-weight threads. 
Thus I started playing around with a few things.

For example, imagine that we want to write a parallel `List.map`. Today, we can do it like (ignore effect s for now):

```scala
def parMap(f: a -> b, l: List[a]): List[b] & Impure = match l {
    case Nil => Nil 
    case x :: xs => 
        let c = chan b 1;
        spawn (c <- f(x));
        (<- c) :: parMap(f, xs)
}
```

This works, but its a bit cumbersome. Let's try some improvements. Assume that `spawn` were to return a channel on which the result of its expression is sent, then we could write:

```scala
def parMap(f: a -> b, l: List[a]): List[b] & Impure = match l {
    case Nil => Nil 
    case x :: xs =>         
        (<- spawn (c <- f(x))) :: parMap(f, xs)
}
```

***Except*** that would not be parallel! Because the channel read would block *before* the recursive call. 

Let's try something else:

```scala
def parMap(f: a -> b, l: List[a]): List[b] & Impure = match l {
    case Nil => Nil 
    case x :: xs => 
       Cons <||| (spawn2(f(x)), parMap(f, xs))
}

def <|||(f: ((t, List[t])) -> List[t], p: (Channel[t], List[t])): List[t] = ???
```

The trick here is that `spawn2` returns a channel which cause evaluation to immediately proceed. Inside `<|||` we await the result of the channel and then call f (which is cons) on the result. This can work and requires minimal changes.

But now I have an even grander idea: Allow the programmer to write:

```scala
def map(f: a -> b, l: List[a]): List[b] & Impure = match l {
    case Nil => Nil 
    case x :: xs => Cons(par f(x), map(f, xs))
}
```

which instructs the compiler that it is allowed to evaluate the function argument `f(x)` in parallel and continue execution. 

We can imagine two forms. Either: `f(par exp1, exp2, par exp3)`. Or a form on the call itself `par f(exp1, exp2, exp3)`, but I think the former might be best.

How does `f(par exp1, par exp2, exp3)` desugar? I think something like:

```scala
let a1 = spawn exp1;
let a2 = spawn exp2;
let a3 = exp3;
f(<- a1, <- a2, a3)
```

***Insight***: The deeper insight here is that in Flix function calls are evaluate left-to-right. The par construct allows us to ease this requirement by evaluating arguments in parallel (i.e. unordered).

**Comment by magnus-madsen** [comment]
@JonathanStarup @mlutze @jaschdoc I would like your thoughts.

**Comment by JonathanStarup** [comment]
> Assume that spawn were to return a channel [...]

What size should the channel have? And what if you put something into the channel before the spawn does? Maybe these questions are just answered by "Don't do that.". We've previously discussed this, and we talked about:
* If you want multiple spawns to use one channel, then the spawn would return unit, thus creating a useless channel that contains a unit value.
* It could be implemented as a regular function if needed, although call-by-value makes it awkward.

**Comment by paulbutcher** [comment]
> So par is Pure?

There's a strong argument to suggest that `par` should be forbidden unless the expression(s) it's applied to are pure?

**Comment by magnus-madsen** [comment]
> > So par is Pure?
> 
> There's a strong argument to suggest that `par` should be forbidden unless the expression(s) it's applied to are pure?
> 
> (having reread it, perhaps that's what you meant?)

I was not (yet) thinking about effects, but I think forcing e to be pure and making par itself pure would be great. This would essentially give us pure parallelism.

**Comment by magnus-madsen** [comment]
> What size should the channel have? And what if you put something into the channel before the spawn does? Maybe these questions are just answered by "Don't do that.". We've previously discussed this, and we talked about:

I think the channel has size one. Later, possibly, it could be a "ReceiveOnlyChannel". In the interim, sending on the channel would be forbidden (but not enforced).

**Comment by magnus-madsen** [comment]
> > We can imagine two forms. Either: f(par exp1, exp2, par exp3). Or a form on the call itself par f(exp1, exp2, exp3), but I think the former might be best.
> 
> What makes you prefer the former? What's the material difference between `f(par exp1, par exp2, par exp3)` and `f(par exp1, exp2, par exp3)`

I have no preference (yet). I think `f(par exp1, exp2, par exp3)`  is actually a bit broken, but it would mean: Evaluate exp1 in parallel then evaluate exp2 in the current thread, AND THEN evaluate exp3 (on a new thread). Thus exp2 happens before exp3. I guess it could be necessary if `exp2` was impure (for some reason).

**Comment by paulbutcher** [comment]
OK, that makes sense.

To enumerate the possibilities:

1. It could be function definition level (i.e. all calls to the function evaluate all arguments in parallel):
    ```
    def par f(a1: T1, a2: T2, a3: T3) ...
    ```
2. It could be per argument at the definition level:
    ```
    def f(par a1: T1, par a2: T2, a3: T3) ...
    ```
3. It could be function call level (i.e. calls to the function evaluate arguments in parallel or not depending on whether `par` is given):
    ```
    par f1(exp1, exp2, exp3)
    ```
4. It could be per argument at the call level:
    ```
    f1(par exp1, par exp2, exp3)
    ```

Anything I've missed?

My instinct is to prefer option 1.

**Comment by JonathanStarup** [comment]
> It could also be a general expression `par exp` anywhere (but that raises some questions about what it means).

It could mean, as you said, that when the Ast has multiple expressions to compute, it will compute the `par` expressions in parallel. This would be relevant for arguments, tuple elements, operands of binary expressions, etc. `f(par 2)` would be a redundancy error since there is only a single expression on the Ast level.

If the expression must be pure, and the par expression is pure, why does the programmer need to write it? Because the "sufficiently smart compiler" is infeasible?

**Comment by magnus-madsen** [comment]
> If the expression must be pure, and the par expression is pure, why does the programmer need to write it? Because the "sufficiently smart compiler" is infeasible?

Loom will make parallelism cheap, but not free, so the programmer probably still has to opt into it.

**Comment by paulbutcher** [comment]
This isn't a serious suggestion. But while it occurs to me:

If we have an expression level `par`, we could also have an expression level `lazy`.

So `par f(x, y, z)` means "eagerly evaluate x, y, and z in parallel and then call f once all of them have finished evaluating". And `par x + y` means "eagerly evaluate x and y in parallel, and then add them once both are available".

`lazy` is effectively the inverse of `par`:

So `lazy f(x, y, z)` means call `f`, and only evaluate `x`, `y`, and `z` when (or if) they're used. And `lazy x and y` means "evaluate `x`. If `x` is false return false, if `x` is true, evaluate `y` and return it"

**Comment by magnus-madsen** [comment]
Interesting observation. Let me mull over it.

**Comment by mlutze** [comment]
I think there's an issue with putting it at the function definition level, which is that it messes with our standard notions of how purity works.

Instead of only knowing about the types of its arguments, a function now has to know about the purity of the expressions used to give them.
```
par def f(x: a, y: b): c = ???

def getThingImpure(): a & Impure
...
f(getThingImpure(), getThingImpure()) // this is rejected because f's arguments need to be pure

let x = getThingImpure();
let y = getThingImpure();
f(x, y) // this is accepted because variable expressions are pure
```

So the scheme of `f` here is something like `forall a, b . (a % Pure) -> (b % Pure) -> c`.
I haven't looked to deeply, but I imagine things become quite complicated when we get into currying and partial application.

All this to say, it seems much easier to me to put it at the call site rather than the definition site.

**Comment by magnus-madsen** [comment]
If we put it at the definition site, the semantics would probably be "run this argument in parallel" -- if pure. That said, I am not sure what the major benefit of having it at the definition site would be. Do we have one example where you would want that over having it at the call site? I think having it at the call site would offer the most flexibility.

**Comment by magnus-madsen** [comment]
> This isn't a serious suggestion. But while it occurs to me:
> 
> If we have an expression level `par`, we could also have an expression level `lazy`.
> 
> So `par f(x, y, z)` means "eagerly evaluate x, y, and z in parallel and then call `f` once all of them have finished evaluating". And `par x + y` means "eagerly evaluate x and y in parallel, and then add them once both are available".
> 
> `lazy` is effectively the inverse of `par`:
> 
> So `lazy f(x, y, z)` means call `f`, and only evaluate `x`, `y`, and `z` when (or if) they're used. And `lazy x and y` means "evaluate `x`. If `x` is false return false, if `x` is true, evaluate `y` and return it"

I have actually been thinking of something similar. For example, if we were to define "and" in the language, we would want its second argument to be lazy, e.g. `def and(x: Bool, lazy y: Bool)` at the definition site and then at the call site we should make the second argument lazy. Scala can already do this with its by-name parameters.

**Comment by magnus-madsen** [comment]
@mlutze Which of these do you prefer:

3. It could be function call level (i.e. calls to the function evaluate arguments in parallel or not depending on whether `par` is given):
    ```
    par f1(exp1, exp2, exp3)
    ```
4. It could be per argument at the call level:
    ```
    f1(par exp1, par exp2, exp3)
    ```

**Comment by mlutze** [comment]
I prefer 4, per argument.

- It allows for an easier transition to `par e` as a more-generally used expression
- It more clearly associates the parallelism (and thus necessity for purity) with each expression

**Comment by magnus-madsen** [comment]
@athas We would like your input on a subject within your expertise:

We are thinking of adding a feature to make parallelism more accessible in Flix.
The general Flix concurrency story is based on channels and threads. 
This proposal does not modify or replace that, but aims to scratch an itch and look cool.

# Proposal 1

We allow a programmer to write this syntactic form: 
```
par f(exp1, exp2, exp3)
```
We require exp1, exp2, and exp3 to be pure (per the effect system). This means: evaluate exp1, exp2, and exp3 on new threads (i.e. in parallel), wait for their results, and then call f.

# Proposal 2

Same core idea, but instead the syntax is (e.g.):
```
f(par exp1, par exp2, exp3, exp4)
```
which means: evaluate exp1 and exp in parallel, then evaluate exp3 sequentially followed by exp4. Wait for the results and call f. 

What have we gained? Two things:

- We have a form of parallelism without explicit channels.
- This form of parallelism remains pure (since there are no explicit channels and no mechanism thus to introduce non-determinism.)

What do you think? Also, do you think this is just cheap parlor tricks?

**Comment by athas** [comment]
I think a more fundamental solution would be to use futures, which would require pure expressions.  Your `spawn` is basically that, right?  Futures are general enough to implement both of those proposals in user code, except that your `parMap` would require two traversals (one to create all the futures and one to wait for them).  I don't think there is much value in having designated syntax for evaluating the arguments to a function in parallel.  It's harmless, but too much syntactic sugar leads to language diabetes.

**Comment by magnus-madsen** [comment]
> I think a more fundamental solution would be to use futures, which would require pure expressions. Your `spawn` is basically that, right? Futures are general enough to implement both of those proposals in user code, except that your `parMap` would require two traversals (one to create all the futures and one to wait for them). I don't think there is much value in having designated syntax for evaluating the arguments to a function in parallel. It's harmless, but too much syntactic sugar leads to language diabetes.

At the moment spawn has type `a -> Unit` and you then communicate the result out of the process via channels (which is impure). 

>  Futures are general enough to implement both of those proposals in user code, except that your parMap would require two traversals (one to create all the futures and one to wait for them)

Yes, indeed. What I was trying to do is figure out a way to avoid that which looks pleasing :)

**Comment by paulbutcher** [comment]
The big difference between Magnus' proposals and futures (to my mind) is that futures would require (as Flix currently stands, at least) passing a function to the future (hence writing a lambda or similar) and some syntax to deference the future? (Unless I'm missing something). 

We could do away with at least some of that additional noise if we had something like Scala's call by value (or the lazy arguments we were discussing above) though. So perhaps laziness is more fundamental building block?

**Comment by magnus-madsen** [comment]
Based on these discussions, I have created: https://github.com/flix/flix/issues/4286
