### ISSUE TITLE
Add `upcast` expression

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4264]
Add an expression `upcast exp` (after `Cast`). The `upcast` expression enables safe casts and should be used without concern.

The `upcast exp` works as follows:

- The `Typer` allows `exp` and `upcast exp` to have any types.
- Post type inference, in `Safety, we check that the upcast is sound.

The soundness rules include:

- Casting a pure expression to an effect polymorphic or impure expression.
- Casting a Java object to one of its super-types.

This can then be generalized for functions: 
- Casting a pure function to an effect polymorphic or impure function.
- Casting a function that returns a Java object to one that returns a subtype (and so forth).

I suggest to start with simple rules and then extend them gradually. 

The plan is to start with https://github.com/flix/flix/issues/4248 to see if that approach is feasible and to identify the locations where `upcast` is useful. This ticket is then about extending that functionality.

**Comment by mlutze** [comment]
We should also add this to the desugaring done in the `Weeder`. Currently `import ...(): SomeType & SomeEff` desugars to `... as SomeType & SomeEff` (a regular cast). Desugaring instead to an `upcast` would cover part of the idea suggested in https://github.com/flix/flix/issues/2867

**Comment by magnus-madsen** [comment]
> We should also add this to the desugaring done in the `Weeder`. Currently `import ...(): SomeType & SomeEff` desugars to `... as SomeType & SomeEff` (a regular cast). Desugaring instead to an `upcast` would cover part of the idea suggested in #2867

On second thought, this may not work. Remember upcast is not an actual cast. In particular, it does not take any type or effect arguments!

**Comment by magnus-madsen** [comment]
TODO:
- `UnsafeUpcast` should only take expected and actual tpe as arguments.
- Replace `upcast` function.
- Add support for JVM subtyping.
