### ISSUE TITLE
feat: Add `tail` to `Foldable` and related namespaces

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#4265]
We have `head` but there's no tail.

One complication: `Nel` and `Nec` do not return Option

**Comment by magnus-madsen** [comment]
What type should `tail` return?

**Comment by JonathanStarup** [comment]
Okay, I think you could
1) add `def tail(f: f[m]): Option[m] with Foldable[f]` to the type class
2) add tail to every namespace that has head

1 is probably controversial but I think 2 should happen for sure

![image](https://user-images.githubusercontent.com/32037926/183028443-5e331f5e-b3ea-4181-a9e8-01feb26d8f39.png)
![image](https://user-images.githubusercontent.com/32037926/183028481-1f3f0aa6-a829-4b02-a6b1-4319b7614b1c.png)

**Comment by magnus-madsen** [comment]
We have `Foldable.last`. You cannot have `Foldable.tail`, but you do have `Iterator.drop(1)` and `Collectable`.
