### ISSUE TITLE
Add List Literal

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#4280]
I want to write `List#(1, 2, 3)` or maybe `List#{1, 2, 3}`

**Comment by magnus-madsen** [comment]
This has been discussed before. There is a ticket somewhere. Stephen was in favor, but I was on the fence.

I still think what you want is immutable vectors.

**Comment by JonathanStarup** [comment]
I think my broader thought is that it feels odd to be functional-first but sometimes envy the syntax of arrays when working with lists. Is there any reason things like `[1; 100]` exist when it could be implemented as `Array.repeat` using the same java calls as the backend?

**Comment by magnus-madsen** [comment]
> I think my broader thought is that it feels odd to be functional-first but sometimes envy the syntax of arrays when working with lists. Is there any reason things like `[1; 100]` exist when it could be implemented as `Array.repeat` using the same java calls as the backend?

Fair point. This seems more like an argument for removing array literals than for adding more literals :)

**Comment by JonathanStarup** [comment]
Continued in #4760
