### ISSUE TITLE
Maybe: refactor `LocalVar` in Entity

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#4285]
Taken from TODO comment above case class `LocalVar` in Entity:
```
Split this into LetBound and SelectBound?
```

**Comment by mlutze** [comment]
IMO Entity needs a more significant redesign, where we have both a `DefDeclaration` entity and a `DefUse` entity, etc., possibly boiling down to even more specific cases. Currently we have a lot of matching with default cases, which makes it difficult to know what is missing.

**Comment by magnus-madsen** [comment]
Do either of you have a sketch?

**Comment by mlutze** [comment]
I did some minor exploration here: https://github.com/flix/flix/pull/4290

There are a couple of issues (not yet addressed in that PR)
1. Entities whose location is exactly the same as another, meaning that it's ambiguous which is selected, and
2. Entities nested inside other entities, where the inner entity has no associated action but blocks the action of the outer entity.

I think that both of these can be addressed by introducing an optional `parent` field, so (for 2) if there's no action, the action of the parent is used, and (for 1) we can see which location is more precise by seeing which is "younger" in the ancestry.

**Comment by magnus-madsen** [comment]
We are removing Entity soon.
