### ISSUE TITLE
NewObject and ClosureConv/LambdaLift

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4291]
- [x] Add expression to `JvmMethod` throughout the backend ASTs.
- [x] In `ClosureConv`, handle `JvmMethod` in `NewObject` almost like `Lambda`.
- [x] In `LambdaLift`, visit `JvmMethod` expression.
- [x] Post `LambdaLift`, refactor `JvmMethod` to have an expression of type `Expression.Closure` (and not just `Expression`).
- [x] Refactor `GenExpression.NewObject` case as follows. For each `JvmMethod`, `i`, generate code for its ` `Expression.Closure` and store the result in field `i` of the allocated object. 
- [x] Refactor `GenAnonClasses` to create a closure field for each `JvmMethod`.

**Comment by magnus-madsen** [comment]
A good starting point would be to extend the generated classes with a field for each JvmMethod. The field should a closure of the appropriate type (`JvmOps.getClosureClassType(sym)`).

**Comment by paulbutcher** [comment]
I think that this is close-able now?
