### ISSUE TITLE
Polish Effects - Part II

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4308]
- [ ] Add specific generalization error for when a pure function is missing an effect.
- [ ] Add specific generalization error for when a purely effect polymorphic function is missing an effect.
- [ ] Add specific generalization error for when a function, with a specific set of effects, is missing a specific effect.
- [ ] Add a specific error for unification errors of the form "Unable to unify the Boolean formulas: 'e11475774 - Console' and 'ef''."
- [x] Add auto-complete for effect names.
- [x] Add high-priority auto-complete when the prefix is `\` or `\ {`.
- [ ] A miss-spelled effect name generates "Undefined type 'Consol'". Update message or add two messages. 
- [x] The empty effect set should be formatted as `{ }` not as "Empty" (In my view).
- [ ] (Discuss) Disallow repeated effects (at least for constants, e.g. `{ Console, Throw, Console }`. (We don't have to handle all crazy cases, just the obvious simple ones.) (I believe we disallow other repeated things, right?)
- [ ] ~Add a redundancy check for empty effects, e.g. `def woof(f: Unit -> Unit \ { ef - ef }): Unit = f()`. (I think this should just be on a best effort, but might be useful.)~
- [ ] LSP: Allow rename of operations (should be safe).
- [ ] LSP: Highlight of an effect should **also highlight all operations associated with that effect** (Both Jonathans will love this).
- [x] LSP: Minimize signatures showed on hover. 
- [x] LSP: Add auto-complete for `without`.
- [x] LSP: Hover should hide Boolean part if it is pure.

### Tabled
- [ ] Add a Redundancy check for `def fooooo(f: Unit -> Unit \ Throw): Unit \ Throw = f() without Console`?

**Comment by mlutze** [comment]
> LSP: Hover should hide Boolean part if it is pure.

Just the boolean part, but not empty set?

**Comment by mlutze** [comment]
> LSP: Minimize signatures showed on hover.

This is referring to inferred types, right? I don't think we should minimize declared types since changing their shape could confuse the user.

**Comment by magnus-madsen** [comment]
> > LSP: Minimize signatures showed on hover.
> 
> This is referring to inferred types, right? I don't think we should minimize declared types since changing their shape could confuse the user.

Yep

**Comment by mlutze** [comment]
> LSP: Highlight of an effect should also highlight all operations associated with that effect (Both Jonathans will love this).

Do we also want to highlight signatures and defs associated with that effect? I believe that's what Jonathan of Aarhus was looking for.

**Comment by mlutze** [comment]
> The empty effect set should be formatted as { } not as "Empty" (In my view).

We cannot always do this because `{ }` is the empty record as well. But we can do this for places we know are sets.

**Comment by magnus-madsen** [comment]
> > LSP: Minimize signatures showed on hover.
> 
> This is referring to inferred types, right? I don't think we should minimize declared types since changing their shape could confuse the user.

Yes

**Comment by magnus-madsen** [comment]
> > Add a Redundancy check for `def fooooo(f: Unit -> Unit \ Throw): Unit \ Throw = f() without Console`?
> 
> What is this check searching for?

I think at minimum a `without` expression is useless if the underlying expression is pure. A stronger requirement would be if the underlying expression has a non-polymorphic constant effect set.

**Comment by magnus-madsen** [comment]
> > LSP: Highlight of an effect should also highlight all operations associated with that effect (Both Jonathans will love this).
> 
> Do we also want to highlight signatures and defs associated with that effect? I believe that's what Jonathan of Aarhus was looking for.

I think you click on "Console" and it shows you all mentions of "Console" PLUS all mentions of `do Console.XYZ`, but no more. What more than that?

**Comment by magnus-madsen** [comment]
> > The empty effect set should be formatted as { } not as "Empty" (In my view).
> 
> We cannot always do this because `{ }` is the empty record as well. But we can do this for places we know are sets.

OK, agreed.

**Comment by magnus-madsen** [comment]
> Jonathan wants to highlight every source of the effect. 

OK; I think that is too difficult to define precisely. I would be happy with just highlighting the direct `do` operations for now.

**Comment by magnus-madsen** [comment]
@mlutze Will you tick off the solved tasks? :)

**Comment by JonathanStarup** [comment]
> > Jonathan wants to highlight every source of the effect.
> 
> OK; I think that is too difficult to define precisely. I would be happy with just highlighting the direct `do` operations for now.

Highlight every function application where the function has the return effect. We cannot check the application expression effect because of cases like `f(do F)` where `F` will taint the application expression. Is this precise enough?

**Comment by mlutze** [comment]
> Add a redundancy check for empty effects, e.g. def woof(f: Unit -> Unit \ { ef - ef }): Unit = f(). (I think this should just be on a best effort, but might be useful.)

This is a little tricky, since we use smart constructors which turn `ef - ef` into `Empty` automatically. But this is also an issue for LSP stuff as this is all lost. I will pull this into its own ticket for its complexity.

**Comment by magnus-madsen** [comment]
We can pick up the minor pieces later.
