### ISSUE TITLE
Improve phase documentation

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#4321]
Every phase should document what it does better (including examples and explaining it other than just reading off the type signature etc.)

**Comment by JonathanStarup** [comment]
I think this will be good for new devs, but there are downsides.

1) comments become outdated and require upkeep (would every new error in redundancy require doc changes?)
2) it is hard to do for less coherent phases, like safety or weeder

1 can be solved by keeping it high-level (so perhaps not examples?) such that no change requires doc changes.

**Comment by magnus-madsen** [comment]
The biggest problem is: How can we encourage ourselves and others to write documentation? 

We should probably start with doc.flix.dev before even thinking of internal documentation.
