### ISSUE TITLE
Add syntactic sugar for FunctionalInterfaces

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4330]
We are rapidly approaching the point where we can write:

```
let f = object ##java.util.function.IntPredicate {
  def test(x: Int32): Bool = x > 5
}
```

For these special function interfaces, it would be nice if we had some simpler syntax.

**Comment by stephentetley** [comment]
def: 
> pub object GreaterThan5[##java.util.function.IntPredicate] = { def test(x: Int32): Bool = x > 5 }

use: 
> strm1 |> Stream.filter(GreaterThan5.test)

**Comment by stephentetley** [comment]
Actually my suggestion above doesn't make sense if objects are first-class values.

**Comment by magnus-madsen** [comment]
> Actually my suggestion above doesn't make sense if objects are first-class values.
> 
> Are objects ever going to have more than one method?

Yes, they can be. If you implement an interface or extend a class.

**Comment by JonathanStarup** [comment]
I don't think there is much to omit (except `{}`) unless you want to omit the def header? Maybe with a pun
```
let f = (x -> x > 5) classified ##java.util.function.IntPredicate
```

**Comment by magnus-madsen** [comment]
@paulbutcher What is the status today? We can write such implementations but they are verbose?

**Comment by paulbutcher** [comment]
> @paulbutcher What is the status today? We can write such implementations but they are verbose?

There's an example in the NewObject tests:

https://github.com/flix/flix/blob/master/main/test/flix/Test.Exp.Jvm.NewObject.flix#L296

I wouldn't say that it's too verbose?

**Comment by magnus-madsen** [comment]
At least its clear. Should we close and then we can always revisit?

**Comment by paulbutcher** [comment]
WFM
