### ISSUE TITLE
_WithIndex functions - functional arg subject last?

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#4331]
This is a very minor point, but should the higher-order functions supplied to _WithIndex traversals be subject last (index first)?

E.g currently we have...

> pub def mapWithIndex(f: (a, Int32) -> b & ef, l: List[a]): List[b] & ef =

but should it be...

> pub def mapWithIndex(f: (Int32, a) -> b & ef, l: List[a]): List[b] & ef =

I suspect it will be very, very rare to write the supplied function as a curried function with just the index[*], so there won't be much benefit to a change except consistency towards the "subject last" principle.

[*] I've been unable to think of an example for `mapWithIndex` where a curried function would be any clearer.

**Comment by magnus-madsen** [comment]
This makes sense to me. It is also consistent with `enumerator`.
