### ISSUE TITLE
Incrementalize `Instances` Phase and Instances part of Typer

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4335]
If we want to speedup the test suite significantly, it would help to incrementalize these two since they account for ~40% of compilation time.

**Comment by magnus-madsen** [comment]
@mlutze Maybe there is something simple we can do relying on the stability part?

**Comment by magnus-madsen** [comment]
We have 45 instances, but it takes 100ms to check them in parallel. o_O

**Comment by mlutze** [comment]
There are several phases which only do checking, not transformation. I think it would be reasonable for all such phases to handle something less expensive than a validation.

**Comment by magnus-madsen** [comment]
Will this https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Instances.scala#L248 not call e.g. checkOrphan multiple times on the same instance?

**Comment by magnus-madsen** [comment]
https://github.com/flix/flix/issues/4336
