### ISSUE TITLE
Changes to the Effect System

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4346]
We are changing the effect system. The changes will bring several long-term benefits which will be described separately.

But for now, here is what you need to know:

- If your program worked before, it should work now (but you will need to make some syntactic changes).
- We are (gradually) changing the language of effects from Boolean formulas to set expressions. 
- The effect separator is changing from `&` to `\`. 
- The `Impure` effect is now the `IO` effect. 
- As before, but to repeat it, unsound effect casts are incredibly dangerous. Do not use them.
- We are adding a new *safe* `upcast e` expression which can be used in those rare cases where an effect cast is needed.

We will keep the old `& Impure` syntax a round for a while, but eventually it will be gone.

Thus,

If before you wrote:

```scala
def >>(f: a -> b & ef1, g: b -> c & ef2): a -> c & (ef1 and ef2) = ...
```

You should now write:

```scala
def >>(f: a -> b \ ef1, g: b -> c \ ef2): a -> c \ { ef1, ef2 } = ...
```

If before you wrote:

```scala
def println(x: a): Unit & Impure = ...
```

You should now write:

```scala
def println(x: a): Unit \ IO = ...
```

These changes will start to take place over the next few weeks. 
I will write in this ticket when the syntax is in place and should start to be used (on master). 

The syntax for reading or writing to a region is:

```
def slice(b: Int32, e: Int32, a: Array[a, r]): Array[a, r] \ { Read(r), Write(r) }
```

Note that the effect system does not yet distinguish between reads and writes; they are treated as the same.

### Flix Language and Standard Library

The current plan is for the Flix language to come with three built-in effects: `IO` and `NonDet` and region effects. In general, everything that touches the outside world will be marked as `IO`. `NonDet` will be used for pure parallelism but where the order (i.e. result) may be non-deterministic. Regions will be used as currently. In the future, we will try to split them into Read/Write.

**Comment by mlutze** [comment]
(Code block 2 edited by Matt)

**Comment by JonathanStarup** [comment]
I think we need documentation for effects. This would: 1) be a place for new people to learn about purity, and 2) A place to explain exactly what each effect encompasses (`Write(r)` also represents allocation, reading system time is IO, etc.).

**Comment by magnus-madsen** [comment]
We are updating the syntax such that `{ ... }` must always describe a concrete effect set.

For example:

```
def on(f: (b, b) -> c & ef1, g: a -> b & ef2, x: a, y: a): c \ { ef1, ef2 } = f(g(x), g(y))
```

should now be:

```
def on(f: (b, b) -> c & ef1, g: a -> b & ef2, x: a, y: a): c \ ef1 + ef2 = f(g(x), g(y))
```

**Comment by JonathanStarup** [comment]
> We are updating the syntax such that `{ ... }` must always describe a concrete effect set.

What is a concrete set? a subset of IO/NonDet/Pure and read/write regions?

**Comment by mlutze** [comment]
> > We are updating the syntax such that `{ ... }` must always describe a concrete effect set.
> 
> What is a concrete set? a subset of IO/NonDet/Pure and read/write regions?

Yes, exactly.
