### ISSUE TITLE
import as syntactic sugar for type alias

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4349]
We could allow:

```
import org.eclipse.jetty.server.Request
```

at the top-level as syntactic sugar for:

```
type alias Request = ##org.eclipse.jetty.server.Request
```

**Comment by paulbutcher** [comment]
How would you propose handling a situation like this?

```
import x.y.Foo
import a.b.Foo
```

?

**Comment by magnus-madsen** [comment]
> How would you propose handling a situation like this?
> 
> ```
> import x.y.Foo
> import a.b.Foo
> ```
> 
> ?

Should be disallowed. Then we should probably allow you to rename one of them.

**Comment by magnus-madsen** [comment]
Fixed in master. (But we need a better long-term solution).
