### ISSUE TITLE
change grammar of `object` to allow a type

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4350]
Thus we would allow:

```
type alias Handler= ##org.eclipse.jetty.server.handler.AbstractHandler
// ...
object Handler {

}
```

**Comment by magnus-madsen** [comment]
@paulbutcher I don't think there is a downside other than we need a check somewhere that the type is of the right shape.

**Comment by paulbutcher** [comment]
This makes sense. Related, it would be good to allow aliases within method parameter lists too (which may be related to your comment https://github.com/flix/flix/pull/4348#discussion_r928298115)?

Can you give me a hint about what a check for it being the right shape might look like?

**Comment by magnus-madsen** [comment]
> This makes sense. Related, it would be good to allow aliases within method parameter lists too (which may be related to your comment [#4348 (comment)](https://github.com/flix/flix/pull/4348#discussion_r928298115))?
> 
> Can you give me a hint about what a check for it being the right shape might look like?

Do aliases not work for arguments? They should?
