### ISSUE TITLE
Add support for arrays to NewObject

### ISSUE THREAD

**Issue by paulbutcher** [flix/flix#4353]
Look at this after #2591 is complete.

(also varargs)

**Comment by magnus-madsen** [comment]
But does it work with some arrays or what?

**Comment by paulbutcher** [comment]
Right now, it doesn't work with any arrays at all. The major reason for this is that `JvmType.toDescriptor` doesn't know how to generate an array descriptor:

https://github.com/paulbutcher/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/jvm/JvmType.scala#L29

I could create something analogous to the code within the `Expression.InvokeMethod` case:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala#L848

But given that I assume that part of what @JonathanStarup is going to be doing is handling these things properly, it seems better wait until he's done so?

**Comment by JonathanStarup** [comment]
I think we should copy the hack for now so we at least support 1-dimensional arrays until the new backend arrives

**Comment by paulbutcher** [comment]
OK, I'll see what I can come up with.
