### ISSUE TITLE
Refactor `NewObject` tests to use imports/type aliases

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4365]

**Comment by paulbutcher** [comment]
Is the motivation behind this to make them more readable? Or...?

I assume we don't want to switch all of them to using aliases (we need to make sure that we have some tests without aliases too?)

**Comment by magnus-madsen** [comment]
I think using `import` for Java types should be the default. Hence I think all tests should use it, except for a specific collection of tests that ensure you can also explicitly write the full type.

**Comment by magnus-madsen** [comment]
Merged #4369.

**Comment by paulbutcher** [comment]
@magnus-madsen, do we also want to allow aliases to be used in method imports? So:

```
import flix.test.TestVoidInterface;

  @test
  def testVoidInterface01(): Bool & Impure =
    import static flix.test.TestVoidInterface.runTest(TestVoidInterface): Bool;
    let anon = object TestVoidInterface {
      def testMethod(_this: TestVoidInterface): Unit = ()
    };
    runTest(anon)
```

could become:

```
import flix.test.TestVoidInterface;

  @test
  def testVoidInterface01(): Bool & Impure =
    import static TestVoidInterface.runTest(TestVoidInterface): Bool;
    let anon = object TestVoidInterface {
      def testMethod(_this: TestVoidInterface): Unit = ()
    };
    runTest(anon)
```

**Comment by paulbutcher** [comment]
While I'm thinking about things that might make Java interop nicer, perhaps we could make importing multiple classes from a namespace nicer? Something like:

```
import org.eclipse.jetty.server.{Handler, Request, Server};
```

instead of 

```
import org.eclipse.jetty.server.Handler;
import org.eclipse.jetty.server.Request;
import org.eclipse.jetty.server.Server;
```

**Comment by paulbutcher** [comment]
And similarly when importing methods? Perhaps:

```
    import jakarta.servlet.ServletResponse {
      getWriter(): PrintWriter & Impure;
      setContentType(String): Unit & Impure;
    }
```

**Comment by magnus-madsen** [comment]
> @magnus-madsen, do we also want to allow aliases to be used in method imports? So:

Yes. But I foresee ambiguity issues.

**Comment by magnus-madsen** [comment]
> While I'm thinking about things that might make Java interop nicer, perhaps we could make importing multiple classes from a namespace nicer? Something like:
> 
> ```
> import org.eclipse.jetty.server.{Handler, Request, Server};
> ```
> 
> instead of
> 
> ```
> import org.eclipse.jetty.server.Handler;
> import org.eclipse.jetty.server.Request;
> import org.eclipse.jetty.server.Server;
> ```

Definitely. Perhaps this is something you can look into? :)
