### ISSUE TITLE
Refactor `& Impure` to `\ IO` in Standard Library and Tests

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4377]
See https://github.com/flix/flix/issues/4346

**Comment by magnus-madsen** [comment]
@ninaandrup @jaschdoc This is a big refactoring I hope you can both help with :) I suggest to work by namespaces. Most likely a search and replace can be useful with minor manual adjustments.

**Comment by ninaandrup** [comment]
I thought the compiler had already been refactored to support the new syntax - I should probably have read the other ticket a bit more thoroughly. I'll just leave the PR for when it becomes relevant :-)

**Comment by magnus-madsen** [comment]
> I thought the compiler had already been refactored to support the new syntax - I should probably have read the other ticket a bit more thoroughly. I'll just leave the PR for when it becomes relevant :-)

I think it should work-- or-- @mlutze

**Comment by mlutze** [comment]
It _should_ work

**Comment by magnus-madsen** [comment]
This is mostly refactored now. What we need to do is update the documentation at flix.dev and doc.flix.dev.

@ninaandrup Can you help with that? :)

**Comment by ninaandrup** [comment]
> This is mostly refactored now. What we need to do is update the documentation at flix.dev and doc.flix.dev.
> 
> @ninaandrup Can you help with that? :)

Is it a new repository for doc.flix.dev instead of [this repository](https://github.com/flix/programming-flix) after updating to the mdbook ?

**Comment by magnus-madsen** [comment]
Yes, its flix/book
