### ISSUE TITLE
[CodeGen] Add backend support for References

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#438]
At some point, to experiment with effects, would like to have basic references in Flix.

Currently there is no way to create or use references in the surface syntax, but I have added the following three nodes to the backend ast:

```
case class Reference(exp: ExecutableAst, tpe: Type, loc: SourceLocation)

case class Dereference(exp: ExecutableAst, tpe: Type, loc: SourceLocation)

case class Assignment(exp1: ExecutableAst, exp2: ExecutableAst, tpe: Type, loc: SourceLocation)
```

In the future these should probably be renamed to `Ref` and `Deref`, but since we already have a reference node (to refer to a symbol) we would need to rename that throughout the compiler to make the name available.

I also added a type constructor `Ref`.

**Comment by magnus-madsen** [comment]
I renamed these to `Ref`, `Deref`, and `Assign`.

**Comment by magnus-madsen** [comment]
@FlaminGuy I have implemented references throughout the compiler, except for the backend. Tests are in `TestReferences.flix`.

You should be able to add backend support now. Probably as a phase `RefGen` which generates a `Box` class specialized to each type of a ref (basically pretty similar to how tuples are handled).

**Comment by FlaminGuy** [comment]
We don't need another phase. It only needs almost 8 classes which can be implemented by hand.

**Comment by FlaminGuy** [comment]
This is already in!
