### ISSUE TITLE
Inlay hint for the parameter I am typing

### ISSUE THREAD

**Issue by mlutze** [flix/flix#4382]
IntelliJ can give hints about the name and type of the parameter that I am typing. We get these a little with autocomplete, but with higher-order functions and long signatures, it can be hard to read. It would be nice to have either an inlay hint or some other popup that shows only the name and type of the parameter I am working with.

**Comment by magnus-madsen** [comment]
Example? I can think of several things you could have in mind.

**Comment by magnus-madsen** [comment]
(Also not sure we can provide it).

**Comment by mlutze** [comment]
For example, I always forget the order of parameters in `List.foldLeft`'s function

If it would pop up with something like:

```scala
(x, y) ||> List.foldLeft($)
                         ^ [f: (in, out) -> out]
// ( $ is the cursor)
```

it would be very handy IMO

**Comment by magnus-madsen** [comment]
Ah yes, but that is way beyond what we can support currently. Right? :)

**Comment by magnus-madsen** [comment]
IDEA is like next level with these things.

**Comment by magnus-madsen** [comment]
Cant support this.
