### ISSUE TITLE
Method import doesn't check return type

### ISSUE THREAD

**Issue by paulbutcher** [flix/flix#4395]
`import` checks that parameter types are correct, but doesn't check the return type, leading to subsequent issues.

For example, the following compiles:

```
import java.util.ArrayList;
import java.lang.Object;
import java.util.AbstractCollection;

// The main entry point.
def main(): Unit & Impure =
    import new java.util.ArrayList(): ArrayList & Impure as newArrayList;
    import java.util.ArrayList.add(Object): Unit & Impure;
    import java.util.AbstractCollection.toString(): String & Impure;
    let al = newArrayList();
    add(al, "Hello World!" as Object);
    println(toString(al as AbstractCollection))
```

But when run crashes with:

```
java -jar /Users/paulbutcher/Projects/flix-playground/flix.jar --entrypoint main /Users/paulbutcher/Projects/flix-playground/src/Main.flix /Users/paulbutcher/Projects/flix-playground/test/TestMain.flix 
paulbutcher@Pauls-MBP flix-playground % java -jar /Users/paulbutcher/Projects/flix-playground/flix.jar --entrypoi
nt main /Users/paulbutcher/Projects/flix-playground/src/Main.flix /Users/paulbutcher/Projects/flix-playground/tes
t/TestMain.flix 
Exception in thread "main" java.lang.VerifyError: Bad type on operand stack     
Exception Details:
  Location:
    Def%main%173003.invoke()LCont%Obj; @27: checkcast
  Reason:
    Type integer (current frame, stack[0]) is not assignable to 'java/lang/Object'
  Current Frame:
    bci: @27
    flags: { }
    locals: { 'Def%main%173003', 'java/lang/Object', 'java/lang/Object' }
    stack: { integer }
  Bytecode:
    0000000: 2ab4 000e 4c2a b400 114d 2bc0 0013 c000
    0000010: 132c c000 15c0 0015 b600 19c0 001b 2a5f
    0000020: b500 1e01 b0                           

        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
```

**Comment by paulbutcher** [comment]
This isn't entirely straightforward to fix because `WeededAst.InvokeMethod` doesn't preserve the return type (making it impossible to check in the resolver.

@magnus-madsen: I think the solution requires adding the return type to `WeededAst.InvokeMethod` and then plumbing it through to the resolver. Sound reasonable?

**Comment by magnus-madsen** [comment]
> This isn't entirely straightforward to fix because `WeededAst.InvokeMethod` doesn't preserve the return type (making it impossible to check in the resolver.
> 
> @magnus-madsen: I think the solution requires adding the return type to `WeededAst.InvokeMethod` and then plumbing it through to the resolver. Sound reasonable?

You mean the declared return type right? I think that sounds reasonable.

**Comment by paulbutcher** [comment]
> You mean the declared return type right? I think that sounds reasonable.

Yes, I do. I'll get onto it.
