### ISSUE TITLE
Introduce `CaseSym`?

### ISSUE THREAD

**Issue by mlutze** [flix/flix#4413]
Cases are currently simply `Ident`s. It would be more consistent with our other declarations to give them proper symbols.

**Comment by magnus-madsen** [comment]
What about fields and predicates? I think they get a name but not a symbol.

**Comment by mlutze** [comment]
But those are for structural types. You can't point to a field and say "this is where it is declared"

**Comment by magnus-madsen** [comment]
> But those are for structural types. You can't point to a field and say "this is where it is declared"

Fair point. In that case I am sold.

**Comment by mlutze** [comment]
This becomes a little scary as the EnumSym + Name.Tag pattern goes all the way to the backend.

**Comment by magnus-madsen** [comment]
I think its many changes, but all of them trivial. We don't mess with tags.
