### ISSUE TITLE
Inlay hints broken during editing

### ISSUE THREAD

**Issue by paulbutcher** [flix/flix#4415]
Inlay hints are cool, but they're broken for source code that won't parse (which is most of the time when editing source code).

For example, imagine I want to turn this:

<img width="524" alt="Screenshot 2022-07-31 at 21 41 45" src="https://user-images.githubusercontent.com/61163/182044559-7d5f86ad-0633-42a7-afe1-ba9bc075a276.png">

into:

<img width="780" alt="Screenshot 2022-07-31 at 21 44 03" src="https://user-images.githubusercontent.com/61163/182044642-5ae3dadf-a22f-4df8-b396-06f560a676af.png">

The inlay hint displays just fine at the start and end points. But here's what it looks like while halfway through editing:

<img width="780" alt="Screenshot 2022-07-31 at 21 44 59" src="https://user-images.githubusercontent.com/61163/182044678-d8df2d04-b265-4932-93bd-b0843fd799ee.png">

The more complex the source, the worse this gets.

I believe that we should only display inlay hints if the AST is current (rather like this change which only displays code lenses if the AST is current #3999).

**Comment by magnus-madsen** [comment]
Agreed
