### ISSUE TITLE
Unary + is too permissive

### ISSUE THREAD

**Issue by paulbutcher** [flix/flix#4418]
It's possible to write anything after a unary plus, and it simply returns its argument:

```
flix> +(3, 2)                                                                   
(3, 2)                                                                          
flix> +"foo"
foo                                                                             
```

**Comment by magnus-madsen** [comment]
> We currently have a `Neg` type class. Should we have a `Pos` one as well?

It just seems like overkill. What's the purpose of unary plus anyway? :-/

**Comment by mlutze** [comment]
Maybe we should just remove it then?

**Comment by magnus-madsen** [comment]
Anyone who wants to keep it?

**Comment by mlutze** [comment]
FWIW, Haskell and OCaml don't have it.

**Comment by magnus-madsen** [comment]
Really?

**Comment by magnus-madsen** [comment]
Okay- then lets (try to) remove it.

**Comment by mlutze** [comment]
> Really?

Ocaml allows it in literals, e.g., `+5` but not `+a`
But Haskell doesn't seem to allow it at all.

I've allowed it in literals in my PR.
