### ISSUE TITLE
Inconsistent fromString return type

### ISSUE THREAD

**Issue by paulbutcher** [flix/flix#4420]
`Int32.fromString` (and other numeric types) returns `Result`, whereas `FromString.fromString` returns `Option`.

**Comment by stephentetley** [comment]
It's inconvenient that they are different but I wouldn't want to lose the `Result` version as it makes clear that a parse failure is an `Err`.

Maybe the `Result` version could be called `parse` ?

**Comment by magnus-madsen** [comment]
> It's inconvenient that they are different but I wouldn't want to lose the `Result` version as it makes clear that a parse failure is an `Err`.
> 
> Maybe the `Result` version could be called `parse` ?

Seems like a reasonable compromise.

**Comment by paulbutcher** [comment]
I'm not sure what we're suggesting here, so can I clarify. Are we:

1. Suggesting that both `Int32` (and every other numeric type) have both a `parse` (returning `Result`) and `fromString` (returning `Option`), or
2. Suggesting that we rename `fromString` in `Int32` (and every other numeric type) to `parse`

?

**Comment by paulbutcher** [comment]
FWIW, if the `Result` version is valuable, given that it's easy enough to convert a `Result` to an `Option`, I'm not sure I see the value in providing versions which return both `Option` and `Result`

**Comment by magnus-madsen** [comment]
Actually, when do want Result? The error would be a string which is unspecified right? (I.e. whatever java spits out in whatever language)? And an Option can be converted to a Result.

If we want both, I would propose to have:

- FromString, XYZ.fromString returning option
- ParseString, XYZ.parseString returning Result[XYZ, String]

**Comment by magnus-madsen** [comment]
@stephentetley Any reason why `Option.toErr("message here")` and just returning an Option is insufficient?

**Comment by stephentetley** [comment]
> @stephentetley Any reason why `Option.toErr("message here")` and just returning an Option is insufficient?

That's fine actually - mostly I wrap `Int32.fromString` in some sort of parsing monad so supplying my own error is no problem.

**Comment by magnus-madsen** [comment]
Roger. Then let us ensure that all `fromString` returns `Option`s.
