### ISSUE TITLE
Underscore doesn't work with greek, math, or operator names

### ISSUE THREAD

**Issue by paulbutcher** [flix/flix#4422]
In general preceding a name with an underscore marks the definition as unused. But this only works with uppercase and lowercase names. Flix also supports greek, math, and operator names, but preceding these with an underscore results in a parse error, e.g.:

```
namespace Test {
  def ⊆(): Unit = ???
}
```

Gives:

```
>> Unused definition '⊆'. The definition is never referenced.
❌ -- Redundancy Error -------------------------------------------------- file:///Users/paulbutcher/Projects/flix-playground/src/Main.flix

>> Unused definition '⊆'. The definition is never referenced.

2 |   def ⊆(): Unit = ???
          ^
          unused definition.

Explanation:
Possible fixes:

  (1)  Use the definition.
  (2)  Remove the definition.
  (3)  Mark the definition as public.
  (4)  Prefix the definition name with an underscore.
```

But then:

```
namespace Test {
  def _⊆(): Unit = ???
}
```

Gives:

```
❌ -- Parse Error -------------------------------------------------- file:///Users/paulbutcher/Projects/flix-playground/src/Main.flix

>> Parse Error: Invalid input "def _⊆", expected Use, Import, "namespace", ' ', ' ', PossibleDocComment, PureWS, Annotations, Modifiers or Definition (line 2, column 3):
  def _⊆(): Unit = ???
  ^
```

**Comment by mlutze** [comment]
Did you copy-paste the wrong error after your parser change? It doesn't have an underscore there.

**Comment by paulbutcher** [comment]
> Did you copy-paste the wrong error after your parser change? It doesn't have an underscore there.

Nope. That's the error. Sans underscore.

**Comment by paulbutcher** [comment]
Weird, right?

**Comment by magnus-madsen** [comment]
I would like to revisit our handling of identifiers at some point and ensure that everything is consistent. I think right now we allow slightly different identifiers in slightly different places.

**Comment by paulbutcher** [comment]
> Weird, right?

I woke up at 2am this morning and realised my stupid mistake. False alarm (and apologies: the mistake was so stupid I'm not going to embarrass myself further by describing it).

So actually, I think the the simple change above does work. I'll dig a bit more and convince myself that it really does and put together a PR.

**Comment by paulbutcher** [comment]
> I would like to revisit our handling of identifiers at some point and ensure that everything is consistent. I think right now we allow slightly different identifiers in slightly different places.

I guess you're talking about the fact that operator names can't be used for variables? Are there any other inconsistencies that you're aware of?

**Comment by magnus-madsen** [comment]
Just a general feeling that what we allow is not entirely consistent.

**Comment by magnus-madsen** [comment]
We should support underscores in all names.

What's the rationale for keeping greek and math names? To satisfy the academics? :)

**Comment by paulbutcher** [comment]
> What's the rationale for keeping greek and math names? To satisfy the academics? :)

That is an excellent question. It's a "cute" feature, but arguably more of a nuisance than help in reality. I certainly wouldn't object to their loss.

**Comment by paulbutcher** [comment]
Presumably you're aware of homoglyph attacks in Javascript. Getting rid of unicode in source would basically kill these before they get started in Flix.

**Comment by paulbutcher** [comment]
https://certitude.consulting/blog/en/invisible-backdoor/

**Comment by magnus-madsen** [comment]
Only lowercase names can be greek and math right? You cannot name an enum with a math letter?

**Comment by magnus-madsen** [comment]
I agree keeping unicode out seems useful.

**Comment by paulbutcher** [comment]
> Only lowercase names can be greek and math right? You cannot name an enum with a math letter?

Correct.

**Comment by magnus-madsen** [comment]
OK; I think what we have is reasonable. Very strict, but with just a little bit to appeal to academics and hardcare FP people. Thoughts?

**Comment by magnus-madsen** [comment]
I would value the math operators over the greek letters, btw.

**Comment by paulbutcher** [comment]
> Presumably you're aware of homoglyph attacks in Javascript. Getting rid of unicode in source would basically kill these before they get started in Flix.

So I'm wrong. Disallowing unicode within names would address the vulnerability above, but not this style of vulnerability:

https://trojansource.codes

Which uses unicode within comments and/or strings to construct an attack.

**Comment by magnus-madsen** [comment]
OK, but that depends on what we allow in comments right?

**Comment by paulbutcher** [comment]
> OK, but that depends on what we allow in comments right?

And strings.

**Comment by paulbutcher** [comment]
From that article:

> ## The defense
Compilers, interpreters, and build pipelines supporting Unicode should throw errors or warnings for unterminated bidirectional control characters in comments or string literals, and for identifiers with mixed-script confusable characters.
Language specifications should formally disallow unterminated bidirectional control characters in comments and string literals.
Code editors and repository frontends should make bidirectional control characters and mixed-script confusable characters perceptible with visual symbols or warnings.

**Comment by paulbutcher** [comment]
I think we're already OK regarding identifiers (we don't allow mixed-script or confusable characters).

But we currently allow anything in comments/strings?
