### ISSUE TITLE
Allow non-exhaustive matches in `for-yield` using MonadZero

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4429]
We can allow:

```
def f(): Unit = 
    let xs = Some(1) :: None :: Nil;
    let _r = for (Some(w) <- xs) 
        yield w;
    ()
```

with a different translation where the essence is:

```
match tmp {
  case Some(w) => ...
  case _ => MonadZero.empty()
}
```

**Comment by magnus-madsen** [comment]
Although this would be inconsistent with the foreach loop. Hmm.

**Comment by magnus-madsen** [comment]
> Although this would be inconsistent with the foreach loop. Hmm.

The foreach loop could also have an empty branch.

**Comment by magnus-madsen** [comment]
@jaschdoc @mlutze @JonathanStarup 

Do we want non-exhaustive (but safe) pattern matches in loops? E.g.

```
for (Some(123) <- o)
```

(If the pattern is not matched, we just skip that iteration).

I am leaning towards no.

**Comment by mlutze** [comment]
Strong "no". Seems like it would lead to bugs e.g. if I add a case to my enum.

**Comment by mlutze** [comment]
Though maybe if an alternate syntax makes it clear that it's not exhaustive, it might be safer.

**Comment by jaschdoc** [comment]
I'm also in favor of disallowing non-exhaustive matches. You get the same functionality by writing
```flix
for (x <- l) yield match x {
    case ... => ???
    case ... => ???
}
```

**Comment by magnus-madsen** [comment]
Agreed, it is a terrible feature. Let's not allow non-exhaustive matches.
