### ISSUE TITLE
Autumn Meeting: Topics to Discuss

### ISSUE THREAD

**Issue by mlutze** [flix/flix#4430]
- [ ] Package manager
- [ ] Debug expression, debug mode
- [ ] CLI Principles
- [ ] Monad/DelayMonad
- [ ] Discuss other region topics (implicit regions, region first or last, etc).
- [ ] Discuss deprecation of some annotations (and annotations with expressions).
- [ ] Brainstorm immutable `Vector`.
- [ ] Brainstorm for-each and for loops.
- [ ] Record syntax.
- [ ] Array.get and List.get
- [ ] Update "What every Flix programmer should know".
- [ ] Guidelines for ordering the source of the library
- [ ] Namespaces: interactions with declarations, privacy, opaqueness
- [ ] Encapsulation: How and when enum cases should be hidden from external use

I've copy-pasted unchecked topics and a few things from comments below the June Meeting (https://github.com/flix/flix/issues/3933)
Feel free to remove anything that has been decided or add anything that is missing.

Note to self or whoever documents the meeting: Be sure to link any created issues to keep track of resolution of discussion items.

**Comment by JonathanStarup** [comment]
# Records vs ADTs 
 I do not know when to use `Point(x, y)` vs `{x=Int32, y=Int32}` vs `Point({x=Int32, y=Int32})` 
  
 |                         | ADT | Records | ADT with record | 
 | :---------------------- | :-: | :-----: | :-------------: | 
 | Pattern matching        | ✔ | ❌ | ❌ | 
 | Direct data access      | ❌ | ✔ | ❌ | 
 | Internally extensible   | ✔ *if opaque* | ✔ | ✔  
 | Externally extensible   | ❌ | ✔ | ❌ | 
 | Works with typeclasses  | ✔ | ❌ | ✔ |

**Comment by magnus-madsen** [comment]
Agenda:

- Quick round to introduce everyone and discuss recent work.
- Magnus: Quick update on Daniel and Anna.
- Magnus: Quick update on recent progress.
- What every Flix programmer should know.
- Discuss: Debug expression.
- Discuss: CLI/repl principles
- Discuss: Package manager.
- Other topics.

**Comment by JonathanStarup** [comment]
namespace ticket @magnus-madsen https://github.com/flix/flix/issues/4167
