### ISSUE TITLE
bug using `let _ =` in entrypoint

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#4440]
```
def main(): Unit \ IO =
    let _ = 12;
    println("hello")
```
this does not output anything
```
def main(): Unit \ IO = f()
def f(): Unit \ IO =
    let _ = 12;
    println("hello")
```
This fixes the issue

**Comment by JonathanStarup** [comment]
Somehow this is how it looks in the bytecode output (in flix syntax)
```
def main(x: Unit): Unit \ IO =
    let var = ();
     match (reifyType a) {
        case ReifiedUnit => ()
        case _ => println(ToString.toString("hello"))
    }
```

**Comment by magnus-madsen** [comment]
Perhaps we could kindly ask @ChrBondi if has time to look at it. Otherwise I can take a look at some point.

**Comment by JonathanStarup** [comment]
I don't know if it makes sense, but given that we've only found it on the entry function, it might also be the entrypoint wrapper that's wrong somehow.

**Comment by magnus-madsen** [comment]
> I don't know if it makes sense, but given that we've only found it on the entry function, it might also be the entrypoint wrapper that's wrong somehow.

I checked, but I think its OK.

**Comment by magnus-madsen** [comment]
Fixed in master. (Not sure how).
