### ISSUE TITLE
Explore Associated Types vs. MPTC

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4485]

**Comment by mlutze** [comment]
Noting some previous discussion here:

- Associated types allow for more concise signatures, as the non-primary type of a class doesn't have to appear in the signature.
- Associated types don't allow for unifying among the types, for example to say that types `a` and `b` must both be `Collection`s of values of type `t`.
- MPTCs complicate resolution significantly, resulting in ambiguities; overall they seem unprincipled.
- Parametric type classes make the resolution much simpler and turn MPTCs into classes where the associated types are part of the signature.

My current preference is to use parametric type classes, but to make the associated types optional in the signature, with a syntax like this `... with Collection<Char>[a]` (explicit) or `... with Collection[a]` (elided/existentially quantified)

**Comment by magnus-madsen** [comment]
> Associated types don't allow for unifying among the types, for example to say that types a and b must both be Collections of values of type t.

Are you sure about this? See Section 3.1 in "Associated Type Synonyms"

**Comment by magnus-madsen** [comment]
By the way, do you see a use for associated types for effects with multiple type parameters? Could one imagine such a thing?

**Comment by mlutze** [comment]
We should also take note of the particular use cases we are interested in. To my knowledge, the `Iterable` problem is the main issue we agree on:

(using a parametric type class syntax)
```scala
class Iterable<ef>[m: Type -> Type] {
    pub def iterator(r: Region[r], x: m[a]): Iterator[r + ef, a]
}
```

I'm also interested in a mutability-dependent `ToString`.

**Comment by magnus-madsen** [comment]
> I'm also interested in a mutability-dependent ToString.

What's this?

**Comment by mlutze** [comment]
> > I'm also interested in a mutability-dependent ToString.
> 
> What's this?

`ToString` is effectful if it's on a mutable type (or uses the region, as appropriate)

**Comment by mlutze** [comment]
> > Associated types don't allow for unifying among the types, for example to say that types a and b must both be Collections of values of type t.
> 
> Are you sure about this? See Section 3.1 in "Associated Type Synonyms"

It requires a bit of magic (type-level `==`) but you're right.

**Comment by mlutze** [comment]
@stephentetley I'd like to ask for your input on this. I recall reading a comment in one of your repositories that suggested that MPTCs were needed for a certain implementation. Can you explain your use-case? Would associated types or parametric type classes be sufficient or would you need full MPTC power?

**Comment by stephentetley** [comment]
Thanks Matthew, the Haskell classes around Monad and monad transformers are examples. E.g. `MonadError`, `MonadReader`, `MonadState`.

MTL uses MPTCs and fundeps:

https://hackage.haskell.org/package/mtl-2.3/docs/Control-Monad-Error-Class.html
https://hackage.haskell.org/package/mtl-2.3/docs/Control-Monad-Reader.html
https://hackage.haskell.org/package/mtl-2.3/docs/Control-Monad-State-Lazy.html

At the moment I'm simulating `MonadError` by always having the error type as a String.

The other nice use case I've mentioned is VectorSpace which moved from MPTC and fundeps to associated types

https://hackage.haskell.org/package/vector-space
https://hackage.haskell.org/package/vector-space-0.16/docs/Data-VectorSpace.html

**Comment by magnus-madsen** [comment]
Thanks Stephen,

We have this idea that we can add MTPC with a built-in default requirement of a fundep on the first (last?) argument. This seems to be very close to Associated Types. Then, we could simplify the syntax s.t. if the full TC is `with T[a, b, c]` but `b` and `c` are determined from `a` then you can just write `with T[a]` (or so we think). @mlutze Right?

**Comment by mlutze** [comment]
@mlutze Right?

That's right.

**Comment by mlutze** [comment]
One thing that I note after an initial look at the transformers is that they seem primarily to be intended for features that might alternatively be implemented with regions and/or effects and handlers, though I'm not sure there's full feature parity.

**Comment by stephentetley** [comment]
MPTCs make representing syntax in the "Final Tagless" style much more convenient as you can have multi-sorted syntax - see Section 5.1 of the paper below which actual uses Object Algebras though they are very closely related to the Final Tagless style.

Type-Safe Modular Parsing
https://i.cs.hku.hk/~bruno/papers/sle17.pdf
