### ISSUE TITLE
Default to 4 space tabs in VSCode plugin

### ISSUE THREAD

**Issue by paulbutcher** [flix/flix#4492]
Currently the VSCode plugin defaults to whatever the default tab setting is (normally 2 spaces?). Should it default to 4 spaces?

**Comment by magnus-madsen** [comment]
Yes, I would say so. (I think VSCode uses the current file to guess the current indentation too ??)

**Comment by paulbutcher** [comment]
It does, which means that it guesses 4 tabs for the pre-generated `Main.flix` file. But create a new file, or edit the pre-generated `Test.flix` file and tabs are whatever the default is.

**Comment by magnus-madsen** [comment]
I see. No idea where to change it, probably in the plugin somewhere.
