### ISSUE TITLE
faulty unification of datalog programs and return types

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#4506]
I am a bit unsure in which system this error lives, but there are two issues with returning datalog values (and ascriptions).

1) underspecified types are sometimes accepted (`distinctPairs` do not mention `Pair` in its type, omiting `Fact` is not allowed). This also applies to ascriptions.
```
pub def bug(): List[(Int32, Int32)] =
    query #{Fact(1). Fact(2).} <+> distinctPairs()
    select (x, y) from Pair(x, y)
    
def distinctPairs(): #{Fact(Int32) | r} =
    #{Pair(x: Int32, y: Int32) :- Fact(x), Fact(y), if x != y.}
```
2) Incorrect type class handling (This results in an empty list instead of `(1,2)::(2,1)::Nil` because the condition is always false. The asciption of x or y to Int32 fixes this as shown above)
```
pub def bug(): List[(Int32, Int32)] =
    query #{Fact(1). Fact(2).} <+> distinctPairs()
    select (x, y) from Pair(x, y)
    
def distinctPairs(): #{Pair(Int32, Int32), Fact(Int32) | r} =
    #{Pair(x, y) :- Fact(x), Fact(y), if x != y.}
```

**Comment by JonathanStarup** [comment]
From @paulbutcher (this compiles)
```
def foo(): #{ Thingy(String) | s } = #{
    Widget("x").
}
```

**Comment by magnus-madsen** [comment]
Fixed in master.
