### ISSUE TITLE
About `Order`

### ISSUE THREAD

**Issue by mlutze** [flix/flix#4519]
We require the `Order` class in order to put something into a standard set. But this feels a little strange to me. It means that we end up putting `Order` on a lot of things that aren't really comparable (e.g., some enum like `Color`) just so we can put it in a set. What does `Red > Blue` mean? The implementation of `Set` leaks out.

I'm not totally sure of the solution, but one option is to make `Hash` take the place of `Order` and use a hash-based treemap instead.

**Comment by magnus-madsen** [comment]
Would you give up on folds to achieve this on your new (hash) set?

**Comment by mlutze** [comment]
I would. We have an `UnorderedFoldable` or some such, right? So we can still fold in some sense. For me, a set is unordered. If someone wants an ordered set then they should use an `OrderedSet` (or RBTree etc.)

**Comment by magnus-madsen** [comment]
What's makes you think hashing is more natural than Order? Quick, answer this: What properties should Hash satisfy?

**Comment by mlutze** [comment]
> What's makes you think hashing is more natural than Order? Quick, answer this: What properties should Hash satisfy?

Consistent with equals. Though of course that doesn't mean anything since we could do e.g. `hash(x) = 0`. So some idea of "reasonably spread out values" is there though I don't know how to express it.

But hashing relates more directly to identity/equality, which is the only property a member of a set should have.

On the more practical side, I have been in something like this situation:

```scala
// first name, last name
enum Person(String, String) with Eq, Order // just adding order here so I can throw it in a set later

...
List.sort(people) // sorts by first name
// it has an order so it must be by last name since that's what I'm used to
// oh no it's sorted by first name so I lost all my crypto!
```

vs
```scala
// first name, last name
enum Person(String, String) with Eq, Hash // hash so I can put it in a set

...
List.sort(people) // error
// oh there's no order on Person; guess I will do `sortBy` to sort by last name
```

**Comment by magnus-madsen** [comment]
Next problem is how  to implement an immutable set based on hashes. Its not easy.

**Comment by JonathanStarup** [comment]
> Next problem is how  to implement an immutable set based on hashes. Its not easy. 

you can do a tree but use the hashes as key right? shouldn't be hard but that maintains the log factor in performance of course.

**Comment by mlutze** [comment]
> > Next problem is how  to implement an immutable set based on hashes. Its not easy.
> 
> you can do a tree but use the hashes as key right? shouldn't be hard but that maintains the log factor in performance of course.

I think the complication is what happens in case of collision. Scala and Haskell both do complex stuff with bitsets from what I've seen

**Comment by JonathanStarup** [comment]
> I think the complication is what happens in case of collision. Scala and Haskell both do complex stuff with bitsets from what I've seen

is it not enough to have a linear time bucket and rely on the quality of the hash function?

**Comment by paulbutcher** [comment]
For reference, the quality of the hashing function is *very* important. See this Clojure bug for details:

https://archive.clojure.org/design-wiki/display/design/Better%2Bhashing.html

**Comment by paulbutcher** [comment]
(in particular, relying on Java's hashing functions will lead to heartbreak).

**Comment by mlutze** [comment]
> (in particular, relying on Java's hashing functions will lead to heartbreak).

I guess it's a bad sign that I based the hashing function on Java's...

**Comment by magnus-madsen** [comment]
What's the plan here? I am not against having *mutable* sets and maps based on hashes. But I don't see a reason to change anything else.

**Comment by paulbutcher** [comment]
This is only tangentially related, but it really is a nuisance that for-yield doesn't currently work with ordered collections.

I'm not unduly worried about whether we use red black trees or hashes (in practice, there's little to choose between them). But I would be strongly in favour of for-yield working with all our major collections, either by losing the ordering requirement, or rejigging the implementation of for-yield.

**Comment by magnus-madsen** [comment]
> This is only tangentially related, but it really is a nuisance that for-yield doesn't currently work with ordered collections.

Do you mean the issue with map or something else?

**Comment by paulbutcher** [comment]
> Do you mean the issue with map and Set or something else?

It applies to Set, Map, and DelayMap, I think (anything implemented as a red black tree, and I think that's it?).

**Comment by JonathanStarup** [comment]
> What's the plan here? I am not against having mutable sets and maps based on hashes. But I don't see a reason to change anything else.

Why not have a RBTree implementation using hashing? no ordering requirement and average complexity stays the same.

**Comment by magnus-madsen** [comment]
Remember that the order requirement exists to ensure we can have meaning min/max/foldLeft/foldRight and tons more.

**Comment by magnus-madsen** [comment]
Deterministic map etc.

**Comment by mlutze** [comment]
> Remember that the order requirement exists to ensure we can have meaning min/max/foldLeft/foldRight and tons more.
> Deterministic map etc.

I'm not sure I buy this argument. In the rare case where you need this then you can opt into a `SortedMap`. `UnorderedFoldable` should be sufficient for the vast majority of use-cases.

The "we don't want to rely on good hashing" argument is what has me on the fence though.

**Comment by paulbutcher** [comment]
FWIW I think of maps, sets, etc. as fundamentally unordered and would be very happy to opt-in to a `SortedSet` (or whatever) on the rare occasions where I care.

**Comment by magnus-madsen** [comment]
I can talk about this at length, but I prefer to do that in person over a beer or coffee :-)

Ultimately the problem is that hashing is non-deterministic which breaks purity. If you do `map` over a `Map` you cannot know what order you will see the elements in.

**Comment by paulbutcher** [comment]
Hmm, I'm not sure I understand why that would be the case. The hashing function is deterministic, so why wouldn't the order also be deterministic? It would be unrelated to any kind of "natural" order, but deterministically so?

**Comment by paulbutcher** [comment]
(although FWIW, I'm not sure I want to have a dog in the ordered/non-ordered fight: what I do want to advocate for is some means by which all "major" collections are supported by for-yield)

**Comment by magnus-madsen** [comment]
Check this out: https://openjdk.org/jeps/431

**Comment by JonathanStarup** [comment]
> Check this out: https://openjdk.org/jeps/431

This does not argue against unordered collections right?

**Comment by magnus-madsen** [comment]
I would say it highlights limitations of unordered collections.

**Comment by magnus-madsen** [comment]
Perhaps this is something that can be continued in "discussions". 

Meanwhile the status is:

- Set and Map will remain ordered.
- We can add mutable HashSet and HashMaps (if desired).
- We can add immutable HashSet and HashMaps too (but I am less sure of their usefulness).
