### ISSUE TITLE
Two improvements to `par`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4535]
Given `par (exp1, exp2, exp3)` or `par exp1(exp2, exp3)` it would be useful if:

- We only create `n - 1` spawns/channels since we can reuse the current thread for one of the expressions (say the last).
- If `exp_i` is a variable or literal then there is no reason to spawn anything. For example, in `par (exp1, 42, w, exp4)` we should only spawn for `exp1` and `exp4` (and actually only for say `exp1` (or `exp4`) since we can reuse the current thread.

**Comment by jaschdoc** [comment]
What about literals and default expressions? I.e.
```scala
Unit
Null
True
False
Char
Float32
Float64
Int8
Int16
Int32
Int64
BigInt
Str
Default
```

**Comment by magnus-madsen** [comment]
> What about literals and default expressions? I.e.
> 
> ```scala
> Unit
> Null
> True
> False
> Char
> Float32
> Float64
> Int8
> Int16
> Int32
> Int64
> BigInt
> Str
> Default
> ```

All of those, except default.

**Comment by jaschdoc** [comment]
Oh I didn't read the ticket properly, sorry. I just now saw that you already explicitly mentioned literals.

**Comment by magnus-madsen** [comment]
I think the two changes should be done in two separate PRs.

**Comment by magnus-madsen** [comment]
What's the status on this? Is there any blockage?

**Comment by jaschdoc** [comment]
I don't think anything is blocked here. Just refining the implementation. Should be done soon :)

**Comment by jaschdoc** [comment]
I do have one question, though: If we don' parallelize variables, should also apply that rule to Defs?

**Comment by magnus-madsen** [comment]
I would think so?

**Comment by magnus-madsen** [comment]
See https://github.com/flix/flix/issues/4609
