### ISSUE TITLE
Refactor BoolUnification and SetUnification to use `Formula`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4539]
Possibly need to split `Formula` into two. 

I think by immediately translating from types into something simpler will significantly simplify the implementation.

**Comment by magnus-madsen** [comment]
- [ ] Refactor/Eliminate BoolTypes

**Comment by magnus-madsen** [comment]
@mlutze Will you look at removing calls to `BoolTypes` from the compiler (and see if it has any bad performance impact)?

**Comment by mlutze** [comment]
> 

Yep

**Comment by mlutze** [comment]
Is the this complete to the extent that the alternative implementation is unblocked?

**Comment by magnus-madsen** [comment]
As far as I know. But still a few things I can improve.

@AnnaBlume99 You are not blocked, right?

**Comment by JonathanStarup** [comment]
@magnus-madsen outdated?

**Comment by magnus-madsen** [comment]
IDK: I suppose we don't have sets yet, but I am not sure what this specific ticket was about.
