### ISSUE TITLE
Create duplicate error for shadowed variable

### ISSUE THREAD

**Issue by mlutze** [flix/flix#4544]
Currently only the first variable is highlighted in VSCode.

**Comment by mlutze** [comment]
I think it is doable. The `Redundancy.scala` phase is where this happens.

**Comment by magnus-madsen** [comment]
> Is this something reasonably simple? If so I'd love to take a look.

I think so, I would expect one line somewhere.

**Comment by magnus-madsen** [comment]
Would it not be better two report two errors, one for each location. That's typically what we do. For example for duplicate variables we report both sites.
