### ISSUE TITLE
Refactor TestBackend

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#455]
Refactor `TestBackend` and try to move the tests into separate Flix test files, see e.g. `TestPatternMatch.flix`

**Comment by magnus-madsen** [comment]
I will help with some of this, including how to organize.

**Comment by FlaminGuy** [comment]
One thing to consider for this is I don't think we should write a `Flix` program in `TestBackend`. I think we should use `mocking` more to test specific functions and data paths. We can mock everything like visitor method to see exactly what is calling what.
http://www.scalatest.org/user_guide/testing_with_mock_objects

**Comment by magnus-madsen** [comment]
Here is an example of the kind of refactoring I have in mind:

https://github.com/flix/flix/commit/7531ece106318d43df47da8d32e344c33938a369

**Comment by magnus-madsen** [comment]
Implemented.
