### ISSUE TITLE
Improvements to auto-complete

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4554]
- [x] Auto-complete `case T...` (with priority for enums in the same file)
- [x] Auto-generate complete pattern matches (?) (E.g. with `match Type` with template on `Type`)
- [x] Auto-complete predicate names `P...`.
- [x] Match should sort by source location for the tags- see ReifiedType
- [x] Auto-complete field names `r.X...`.
- [x] Auto-complete uses `use X.Y...`
- [x] Auto-complete imports `import ...` (with fqn class name)
- [x] Complete of unit functions.
- [x] Use hardcoded list of packages/classes from `classlist` (but heavily filtered).
- [x] Improve suggestions when completions should be provided (e.g. after `def _`).
- [x] Improve suggestions in context `[...]`.
- [x] Refactor `CompletionProvider` to not have a separate argument for `javaClasses`.
- [x] Built-in names for Arrays, Sender/Receiver, etc. (Remove Channel).
- [x] Remove `Int8` and other rarely used types from completions (?) / or give them lowest priority.
- [x] Improve prioritization (e.g. `Int32` is much more likely than `Identity`). 
- [x] Remove auto-completion of tags. 
- [ ] (Use `TypedAst.Root` modules for `use` completion.)
- [x] Idea: "A new type of hole that refers to an expression" and then provide auto-complete for things "relevant" to that expressions.
- [x] (Magnus) Prompt on `?` in VSCode extension.

Situations that should *NOT* trigger auto-complete:

- [x] Prefix is `def`
- [x] Prefix is `enum`
- [x] Prefix is `type alias`
- [x] Prefix is `class`
- [x] Prefix is `let` or `let*`
- [x] Prefix is `namespace`

**Comment by paulbutcher** [comment]
Completion isn't currently namespace aware. So if I have:

```
namespace Foo {
    pub def frobnicate(x: Int32): Int32 = ???
}

namespace Bar {
    import Foo.frobnicate;

    pub def munge(): Int32 =
        frob⁁
}
```

And accept the completion, I get:

```
namespace Foo {
    pub def frobnicate(x: Int32): Int32 = ???
}

namespace Bar {
    import Foo.frobnicate;

    pub def munge(): Int32 =
        Foo.frobnicate(?x)
}
```

Where I probably don't want the `Foo.` prefix.

**Comment by paulbutcher** [comment]
Completion doesn't currently handle functions that take no arguments well. Given:

```
def foo(): Unit = ???

def bar(): Unit =
    fo⁁
```

Accepting the completion gives:

```
def foo(): Unit = ???

def bar(): Unit =
    foo(?_unit)
```

**Comment by paulbutcher** [comment]
Auto complete isn't aware of `import`, so:

```
import some.package.Frobnicator;

def foo(): Unit =
    let x: Frob⁁
```

Doesn't suggest `Frobnicator` as a possible completion.

**Comment by magnus-madsen** [comment]
@Daniel-Anker-Hermansen I added some suggestions for when to disable auto-complete.

**Comment by magnus-madsen** [comment]
@Daniel-Anker-Hermansen Matt will help by adding this for you: https://github.com/flix/flix/issues/4979

**Comment by paulbutcher** [comment]
`use` (and I guess `import` too) completion isn't curly-bracket-aware. Imagine that namespace `Foo` has public `bar` and `qux` definitions:

```
use Foo.f⁁
```

Correctly offers both `foo` and `bar` as completions, and inserts them correctly.

But:

```
use Foo.{f⁁}
```

Correctly offers both `foo` and `bar` but accepting one of them results in:

```
use Foo.{Foo.foo}
```

**Comment by magnus-madsen** [comment]
@Daniel-Anker-Hermansen 

Are with completions broken?

```
def sort(l: List[a]): List[a] with 
```

**Comment by paulbutcher** [comment]
@magnus-madsen did you intend to close this ticket? There are still a number of things mentioned here that haven't been addressed?

**Comment by magnus-madsen** [comment]
@mlutze @JonathanStarup @jaschdoc @paulbutcher 

Daniel has now completed the implementation work. It would be useful if you could "kick the tires" so to speak, and see if everything works well. That is, everything that has been implemented in the above list.

Note that I am not asking for "ideas for new features" (e.g. namespace aware completion) but rather that the above list of completions now work reasonable well. In particular, I think we have now reached a milestone where auto-completion is as good as it can get until we take the next steps towards an error tolerant parser and frontend.

**Comment by magnus-madsen** [comment]
Note that I am also interested in when the plugin should NOT give any completions (because it gets in the way).

**Comment by mlutze** [comment]
One example where the plugin gives bad completions is when I'm using a cons operator:


```scala
match x {
    case hd :: |      // suggests types here
}
```

I assume this happens because it looks for a `:`

**Comment by magnus-madsen** [comment]
Here:

```
def trydiv(x: Int32, y: Int32): Result[Int32, Stri|]
```

I don't get any completions.

**Comment by magnus-madsen** [comment]
Here:

```
enum Suite with Eq, |
```

I don't get any completions.

**Comment by magnus-madsen** [comment]
Here I get some strange suggestions:

```
enum Rank with Eq, Order {
    case Number(I|)
}
```

**Comment by magnus-madsen** [comment]
When writing `case` I often get this suggestion:

```
Choice[...]
```

**Comment by magnus-madsen** [comment]
Here I get strange suggestions:

```
    match (p1, p2) {
        case (Nil, N|)
    }
```

**Comment by magnus-madsen** [comment]
Can we suggest `println` over `print`? :)

**Comment by magnus-madsen** [comment]
Underscore `_|` should never give any suggestions.

**Comment by magnus-madsen** [comment]
Auto-complete for `Sender` seems to have a bug (it shows some spurious brace).

**Comment by magnus-madsen** [comment]
I think hard coded support for the following constructors would be useful: `None, Some, Ok, Err, Nil`.

**Comment by magnus-madsen** [comment]
Missing match complete here:

```
enum Tree[a] {
    case Leaf(a),
    case Node(Tree[a], Tree[a])
}

def map(f: a -> b, t: Tree[a]): Tree[b] = mat|
```

**Comment by magnus-madsen** [comment]
A type alias should trigger "type mode":

```
type alias M = Str|
```

**Comment by magnus-madsen** [comment]
Auto-completing `true` and `false` should not add space after.

**Comment by magnus-madsen** [comment]
Add `par` keyword.

**Comment by magnus-madsen** [comment]
@Daniel-Anker-Hermansen Here is a summary of bugs that I believe can easily and quickly be fixed:

- [ ] The char `:` is always followed by a type, unless its `::` or `:::`.
- [ ] Missing type completions for `def f(): Result[Int32, Stri|]`. We should at least be able to do something if the right char is `]`.
- [ ] Allow multiple with completions, e.g. `enum Suite with Eq, |`
- [ ] Case completions propose expressions, instead of types, e.g. `case Number(I|)`
- [ ] Case completions often propose a strange `Choice[...]` type.
- [ ] What would it take to prioritize `println` over `print`?
- [ ] Underscore `_` should never offer any suggestions.
- [ ] The completion for `Sender` and `Receiver` are bugged (missing region and spurious brace).
- [ ] I think we should hardcode support for the tags: `None`, `Some(x)`, `Ok(x)`, `Err(?)` and `Nil`.
- [ ] def foo(): ... = match| does not prompt. Maybe hard to fix?
- [ ] `type alias M = ` should trigger type completion mode.
- [ ] Auto-complete of `true` and `false` should not add a space after.
- [ ] Missing `par` keyword.

**Comment by jaschdoc** [comment]
When I type `iterator` it suggests `iterator` which doesn't exist in the Prelude. Perhaps it should suggest `Foldable.iterator` instead?

**Comment by magnus-madsen** [comment]
> When I type `iterator` it suggests `iterator` which doesn't exist in the Prelude. Perhaps it should suggest `Foldable.iterator` instead?

There is an iterator though: https://github.com/flix/flix/blob/master/main/src/library/Iterator.flix#L36

**Comment by jaschdoc** [comment]
Never mind then. I was getting type errors using that over `Foldable.Iterator` though... weird 🤔
