### ISSUE TITLE
[CodeGen] Add support for LetRec 

### ISSUE THREAD

**Issue by FlaminGuy** [flix/flix#456]
I should add support with LetRec using dynamic invocations and lambda metafactory.

For more information, see:
http://cr.openjdk.java.net/~briangoetz/lambda/lambda-translation.html
http://docs.oracle.com/javase/8/docs/api/java/lang/invoke/LambdaMetafactory.html

**Comment by magnus-madsen** [comment]
If possible, let's talk more in the week, but before let rec I would like us to do some cleanup and more work on the enums / tuples / other code gen.

**Comment by FlaminGuy** [comment]
Sure! I just wanted to have a ticket for this.

**Comment by FlaminGuy** [comment]
Can you assign this to me @magnus-madsen?
I want to have this in my issues.

**Comment by magnus-madsen** [comment]
We need to make some changes to the AST in order to support this:

Here I will try to write down the necessary changes:

- `VarSym` needs to know if it is a free (captured variable)
- `Def` needs to know if it is a lifted let-rec lambda.

Possibly `VarSym` needs to have a field name.
