### ISSUE TITLE
Measuring Performance Over Time

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#457]
The purpose of this ticket is to track the performance over time while we make changes to the backend.

**Comment by magnus-madsen** [comment]
With `Value` class:

```
Name:                  Time (ms)          Ops (ops/s)
benchmark01                 36.6                 27.3
benchmark02                220.2                  4.5
benchmark03                 56.8                 17.6
benchmark04                134.7                  7.4
benchmark05                 76.7                 13.0
benchmark06                 59.6                 16.8
benchmark07                 39.5                 25.3
benchmark08                 45.6                 21.9
benchmark09                114.3                  8.8
```

with generated classes:

```
Name:                  Time (ms)          Ops (ops/s)
benchmark01                 27.8                 36.0
benchmark02                342.3                  2.9
benchmark03                 41.9                 23.9
benchmark04                111.9                  8.9
benchmark05                 75.1                 13.3
benchmark06                 45.8                 21.8
benchmark07                 30.5                 32.8
benchmark08                 51.8                 19.3
benchmark09                 92.9                 10.8
```

Side by side:

```
Name:                  Time (ms)          Time (ms) 
benchmark01                 36.6                 27.8
benchmark02                220.2                342.3
benchmark03                 56.8                 41.9
benchmark04                134.7                111.9
benchmark05                 76.7                 75.1
benchmark06                 59.6                 45.8
benchmark07                 39.5                 30.5
benchmark08                 45.6                 51.8
benchmark09                114.3                 92.9
```

**Comment by FlaminGuy** [comment]
I'm surprised, I get a way better result that this and it makes sense because of how benchmark02 requires us to untag and untuple multiple times. In my machine I get 142 vs 254.
I think we should come up with a better way to measure performance because the current test is very unstable.        
Maybe we should run it on a machine with a huge ram to avoid garbage collection and other side effects of the OS.       
Also, I think we are better off calculating 80th percentile over 100 times running the test than taking the average. This way we through out very low and very high results which usually aren't the real case performance.

**Comment by magnus-madsen** [comment]
> Maybe we should run it on a machine with a huge ram to avoid garbage collection and other side effects of the OS.

I agree.  But I think instead of more ram a better approach might be to try to use smaller lists.

> Also, I think we are better off calculating 80th percentile over 100 times running the test than taking the average. This way we through out very low and very high results which usually aren't the real case performance.

I completely agree. Using the average is what other tools does, but I think we should a percentile or even  better just the median. 

We should also increase the warm-up rounds substantially. I will open a ticket for this later.

**Comment by magnus-madsen** [comment]
Still, the benchmarks clearly show an improvement. The `08` is just a fluke, the overall trend is clear enough.

**Comment by FlaminGuy** [comment]
This table shows the bench mark result which `New` is my current pull request after adding singleton pattern for enums with constant field and removing `tag` field from enums. `Current` is the time for the current main branch after generating classes for enums and tuples and `Old` is before generating classes for enums and tuples. 

| Test Name        | New Time (ms)           | Current Time (ms)  | Old Time (ms) |
| ------------- |:-------------:| -----:|----: |
|benchmark01     | 4.0 | 4.2 |  5.0  |
| benchmark02     | 6.1     |   7.2 |    17.1   |
| benchmark03 | 5.9      |    7.2 |       8.5  |
|benchmark04     | 6.0 | 6.6 |    7.8  |
| benchmark05      | 5.4      |   5.5 |     6.1 |
| benchmark06 | 10.8      |    11.9 |       13.1  |
|benchmark07     | 7.3 | 8.4 |    8.6  |
| benchmark08      | 4.9      |   5.1 |     6.5  |
| benchmark09 | 3.9      |    4.6 |      4.8   |
|benchmark10     | 5.1 | 5.2 |    4.8  |
| benchmark11      | 10.8      |   11 |     12.7  |
| benchmark12 | 13.8      |    16 |       19.9  |
|benchmark13     | 4.1 | 4.7 |    10.0  |
| benchmark14      | 8.3      |  7.8 |     17.9  |
| benchmark15 | 11.5      |    12.2 |       13.8  |
| benchmark16 | 17.1      |    18 |     20.9    |

Overall, I like the new benchmark evaluation. I ran it couple of times and it looked pretty stable to me.

**Comment by magnus-madsen** [comment]
This is with the median right?

**Comment by FlaminGuy** [comment]
Yes, this is the median. I just copy pasted the new benchmark stuff to old builds.

**Comment by magnus-madsen** [comment]
It would be interesting to add the `sonar-analysis` too. Can you try that?

**Comment by magnus-madsen** [comment]
And these:

https://github.com/flix/flix/issues/417

**Comment by FlaminGuy** [comment]
Can't we just add `sonar-analysis` as one of the benchmark tests? is it reachable?

**Comment by magnus-madsen** [comment]
I am going to move sonar-analysis out of the repository soonish, so not really. (Also, it is significantly slower than the list tests which run fast).

We might consider moving it to the other repo with the other benchmarks (nbody, etc.)

**Comment by magnus-madsen** [comment]
Compiled code vs. interpreted code:

```
Actual Rounds: 50
  Name:             Median (compiled)     Median (interpreter)
  benchmark01                  4.5                1099.3
  benchmark02                  6.0                1454.6
  benchmark03                  7.7                1419.7
  benchmark04                  5.6                2084.1
  benchmark05                  5.0                1930.5
  benchmark06                 11.5                3427.7
  benchmark07                  7.6                2347.0
  benchmark08                  4.7                2081.7
  benchmark09                  3.6                1420.9
  benchmark10                  4.2                1568.7
  benchmark11                 10.8                2624.2
  benchmark12                 21.8                5137.2
  benchmark13                  4.6                4831.1
  benchmark14                  8.2               10823.5
  benchmark15                 11.9                3383.2
  benchmark16                 18.0                5395.8
```

As we see, the compiled code is now significantly faster than the interpreter.
