### ISSUE TITLE
flix playground code doesn't compile

### ISSUE THREAD

**Issue by renatoathaydes** [flix/flix#4576]
I clicked on https://play.flix.dev/
Then, clicked on `Compile & Run`.

Got this error:

```
-- Parse Error -------------------------------------------------- <input>

>> Parse Error: Invalid input ';', expected "choose*", "choose", "chan", LegalLetter, ':', "->", ArgumentList, '[', '.', ::, :::, Op, '`', <+>, **, * or / (line 31, column 22):
    query p select (c; d) from ReadyDate(c; d);
                     ^
```

**Comment by renatoathaydes** [comment]
Oh sorry, I must've visited the site earlier and there was a localStorage code snippet there , the editor was using that... I don't remember anymore what I was trying...

Cleaned localStorage and the code works now.

Sorry!

**Comment by magnus-madsen** [comment]
No worries! Have fun using Flix
