### ISSUE TITLE
[CodeGen] toString of Enums

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#458]
I would like to specialise the `toString` method of enums for to specific use cases.

- As a rule, the unit value should never be printed. For example, if there is a `case Red` then it it is implicitly `case Red(Unit)` but should still be printed as just `Red`. The only exception is when printing the unit value itself which should be printed as `()`. 

- The `Cons` tag of the `List` enum should be printed infix as `::`. Hence the list `Cons(1, Cons(2, Cons(3, Nil)))` should be printed as `1 :: 2 :: 3 :: Nil`.

**Comment by magnus-madsen** [comment]
If I write:

```
def f: List[Int] = 1 :: 2 :: Nil
```

and run `--main f` I get:

```
Exception in thread "main" java.lang.IncompatibleClassChangeError: Found interface ca.uwaterloo.flix.api.Tuple, but class was expected
	at ca.waterloo.flix.enums.List.object.Cons.toString(Unknown Source)
	at ca.uwaterloo.flix.runtime.Value$.pretty(Value.scala:390)
	at ca.uwaterloo.flix.Main$.main(Main.scala:127)
	at ca.uwaterloo.flix.Main.main(Main.scala)
```

**Comment by FlaminGuy** [comment]
The error was because I was calling a method on an interface with `INVOKEVIRTUAL`. The reason I didn't use `INVOKEINTERFACE` instead of `INVOKEVIRTUAL` at the first place was that in order for `INVOKEINTERFACE`to work, `true` has to be passed into `visitMethodInsn`.

**Comment by magnus-madsen** [comment]
Fixed.
