### ISSUE TITLE
`par` block

### ISSUE THREAD

**Issue by mlutze** [flix/flix#4601]
From what I understand, we currently allow `par` before tuples and function calls, where the arguments are calculated in parallel.

This disagrees with my typical writing style. I prefer to bind the result of complex calculation to a variable and then to use the variable as the argument to a function. This seems very typical.

In order to allow this style, I propose the `par` block:

```scala
...
par {
    x <- foo(a, b, c) |> bar(d)
    y <- calculateY()
    z <- doThingy() |> combineWith(e, f, g)
};
baz(x, y, z)
...
```

x, y, and z are calculated in parallel. In my opinion this is clearer than the current `par` syntax.

**Comment by magnus-madsen** [comment]
Would it not be more idiomatic to say

```
par (x <-exp, y <- exp) exp
```

following our foreach loop etc?

Alternatively,

```
let (x, y) = par (exp, exp)
```

Is also OK, no?

**Comment by mlutze** [comment]
> ```
> let (x, y) = par (exp, exp)
> ```
> 
> Is also OK, no?

I don't like this one because in case `exp` is long and if there are many of them, we'll want to put them on separate lines. Then the variable is separated from the expression, which can lead to bugs by accidentally switching two expressions, and adds refactoring complexity, in that there are two places rather than one to change in case we remove or add a parallel line.

**Comment by mlutze** [comment]
> Would it not be more idiomatic to say
> 
> ```
> par (x <-exp, y <- exp) exp
> ```
> 
> following our foreach loop etc?

This one seems fine to me

**Comment by magnus-madsen** [comment]
But, it also nice to write `Node(par (exp, exp, exp))`. How would you support that?

**Comment by magnus-madsen** [comment]
What about par-yield?

**Comment by mlutze** [comment]
> But, it also nice to write `Node(par (exp, exp, exp))`. How would you support that?

Can't we have both?

Though it makes the standard de-inline refactoring harder.

**Comment by magnus-madsen** [comment]
See https://github.com/flix/flix/issues/4609
