### ISSUE TITLE
Compilation error when implementing interfaces

### ISSUE THREAD

**Issue by Daniel-Anker-Hermansen** [flix/flix#4605]
```
type alias KeyEvents = ##java.awt.event.KeyListener
type alias Event = ##java.awt.event.KeyEvent
def main(): Unit \ IO =
  region r {
    let mut = MutList.new(r) ;
    let _anon = new KeyEvents { 
      def keyPressed(_this: KeyEvents, event: Event): Unit = (mut |> MutList.push!(event))
      def keyTyped(_this: KeyEvents, _event: Event): Unit = ()
      def keyReleased(_this: KeyEvents, _event: Event): Unit = ()
    };
    ()
  }
```

**Comment by mlutze** [comment]
Can you also post the error this causes?

**Comment by Daniel-Anker-Hermansen** [comment]
Exception in thread "main" java.lang.VerifyError: Bad local variable type x
Exception Details:
Location:
Anon$16467.<init>()V @13: aload_3
Reason:
Type top (current frame, locals[3]) is not assignable to reference type
Current Frame:
bci: @13
flags: { }
locals: { 'Anon$16467' }
stack: { 'Anon$16467', 'Clo%main%175228', 'Clo%main%175228' }
Bytecode:
0000000: 2ab7 000a 2abb 000c 59b7 000d 592d c000
0000010: 0fb5 0013 b500 162a bb00 1859 b700 19b5
0000020: 001c 2abb 001e 59b7 001f b500 22b1

at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
    at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
    at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3427)
    at java.base/java.lang.Class.getMethods(Class.java:2019)
    at ca.uwaterloo.flix.language.phase.jvm.Bootstrap$.methodsOf(Bootstrap.scala:102)
    at ca.uwaterloo.flix.language.phase.jvm.Bootstrap$.$anonfun$bootstrap$2(Bootstrap.scala:37)
    at scala.collection.IterableOnceOps.foldLeft(IterableOnce.scala:646)
    at scala.collection.IterableOnceOps.foldLeft$(IterableOnce.scala:642)
    at scala.collection.AbstractIterable.foldLeft(Iterable.scala:919)
    at ca.uwaterloo.flix.language.phase.jvm.Bootstrap$.$anonfun$bootstrap$1(Bootstrap.scala:36)
    at ca.uwaterloo.flix.api.Flix.subphase(Flix.scala:619)
    ...

**Comment by paulbutcher** [comment]
I have cut this down to what seems to be a minimal replication:

```
import java.lang.Runnable

def main(): Unit \ IO =
    let x = [1, 2, 3];
    let _anon = new Runnable {
      def run(_this: Runnable): Unit = println(Array.length(x))
    };
    ()
```

The problem seems to be related to regions, if I change `x` to a list instead of an array, then there's no problem:

```
import java.lang.Runnable

def main(): Unit \ IO =
    let x = 1 :: 2 :: Nil;
    let _anon = new Runnable {
      def run(_this: Runnable): Unit = println(List.length(x))
    };
    ()
```

I guess there's something wrong with how I'm generating the code for the closure implementing the method body:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/jvm/GenAnonymousClasses.scala#L91

But right now I'm not sure what.

Any insight you can provide to help me work it out @mlutze?

**Comment by mlutze** [comment]
@JonathanStarup might be off more help for backend stuff.

**Comment by JonathanStarup** [comment]
Here is the annonymous class. You can see that ALOAD 3 is out of bounds, there is only `this` at 0 and a closure at `1`.
```
public final class Anon$23393 implements java/lang/Runnable {

  // access flags 0x1
  public LClo1%Obj%Obj; clo0

  // access flags 0x1
  public <init>()V
    ALOAD 0
    INVOKESPECIAL java/lang/Object.<init> ()V
    ALOAD 0
    NEW Clo%main%174964
    DUP
    INVOKESPECIAL Clo%main%174964.<init> ()V
    DUP
    ALOAD 3 // THIS LINE IS ERROR
    CHECKCAST java/lang/Object
    PUTFIELD Clo%main%174964.clo0 : Ljava/lang/Object;
    PUTFIELD Anon$23393.clo0 : LClo1%Obj%Obj;
    RETURN
    MAXSTACK = 4
    MAXLOCALS = 4

  // access flags 0x1
  public run()V
    ALOAD 0
    GETFIELD Anon$23393.clo0 : LClo1%Obj%Obj;
    INVOKEVIRTUAL Clo1%Obj%Obj.getUniqueThreadClosure ()LClo1%Obj%Obj;
    DUP
    ALOAD 0
    PUTFIELD Fn1%Obj%Obj.arg0 : Ljava/lang/Object;
    INVOKEVIRTUAL Fn1%Obj%Obj.unwind ()Ljava/lang/Object;
    CHECKCAST dev/flix/runtime/Unit
    RETURN
    MAXSTACK = 3
    MAXLOCALS = 1
}

```

**Comment by magnus-madsen** [comment]
Most likely Something something with variable numbers, lambda lifting etc of new obj . (Sent from phone)

**Comment by magnus-madsen** [comment]
Sounds like a missing recursive call somewhere

**Comment by paulbutcher** [comment]
So it sounds like it's not something wrong with how I'm generating the code for the closure, but instead is something wrong with how the closure is being constructed in the first place? Suggestions for how best to track this down gratefully received!

**Comment by magnus-madsen** [comment]
Still on phone. In the minimal example, does it work if you introduce a variable for the length?

**Comment by magnus-madsen** [comment]
It works with list?? Hmmm

**Comment by JonathanStarup** [comment]
I've updated my comment with more information, i don't think its a simple bug but rather a conceptual one

**Comment by paulbutcher** [comment]
> pardon my intrusion

Your intrusion is very (very!) welcome. I'm still very much feeling my way through how code generation works, and quite a bit of what I wrote had the feeling of "voodoo programming" (i.e. copy the structure of similar code without really understanding how it's doing what it's doing).

I've been working through the code generation in the debugger, and had come to a similar conclusion. Now I just need to work out what I need to do differently...

**Comment by JonathanStarup** [comment]
1) make Anon do nothing in its constructor
2) generate `anon.cloi = gen(methods[i])` for each method in the exp generation method, following the `new Anon` call (this could also be constructor arguments but we do direct instantiation like this in the compiler generally

It's essentially moving the code for the Anon constructor to the genExp case

**Comment by paulbutcher** [comment]
> (sidenote, why does the compiler say that this is impure?)

Because `new` is side-effecting (it's creating a new object), a different one each time. See, for example:

https://github.com/flix/flix/blob/master/main/test/flix/Test.Exp.Jvm.NewObject.flix#L24-L36

**Comment by JonathanStarup** [comment]
> > (sidenote, why does the compiler say that this is impure?)
> 
> Because `new` is side-effecting (it's creating a new object, a different one each time). See, for example:
> 
> https://github.com/flix/flix/blob/master/main/test/flix/Test.Exp.Jvm.NewObject.flix#L24-L36

ah yes, of course, thank you

**Comment by magnus-madsen** [comment]
Great teamwork 👍 

@Daniel-Anker-Hermansen Can you progress now?
