### ISSUE TITLE
View package source in VSCode

### ISSUE THREAD

**Issue by mlutze** [flix/flix#4606]
It seems to me that we could unpack the appropriate file and display it in a temporary pane

**Comment by JonathanStarup** [comment]
big fan, although there are multiple files. My dream would be that flix can make vscode call the doc command on the package and the show the json file in a nice javadoc like layout

**Comment by magnus-madsen** [comment]
I am all for this, but nothing will happen until we have a dedicated VSCode person. 

Tagging as future, but closing.
