### ISSUE TITLE
Not current message in hover is incorrectly syntax highlighted

### ISSUE THREAD

**Issue by paulbutcher** [flix/flix#4611]
I just stumbled over the new "not current" warning in the LSP (which is nice). But I noticed that the message is being incorrectly syntax highlighted as though it was Flix source:

<img width="771" alt="Screenshot 2022-09-24 at 13 35 48" src="https://user-images.githubusercontent.com/61163/192098512-e9788a00-4252-40a1-8c8a-8b7ac34682ba.png">

(note that the "not" is shown in red as though it was a keyword).

I'm not sure why what I'm seeing differs from the screenshot in #4186 though? Has something else changed since this was added?

@jaschdoc might have some insight?

**Comment by magnus-madsen** [comment]
This is a limitation of VSCode which uses the Flix grammar for highlighting error messages.

**Comment by paulbutcher** [comment]
> This is a limitation of VSCode which uses the Flix grammar for highlighting error messages.

Is this a known limitation (i.e. is there a bug/feature ticket tracking it or similar)?

**Comment by magnus-madsen** [comment]
The VSCode API and LSP API have _a lot of limitations_. I could write a book. We would have many tickets, so not sure what to do.

**Comment by magnus-madsen** [comment]
In this case the issue is that messages are formatted as a programming language (e.g. the message is highlighted as it if was Flix code). Yes, I know 😮

**Comment by paulbutcher** [comment]
Yes, I understand that that's what's happening. But I was wondering whether it's a known issue that's being tracked (because if it is, then there might be some suggestions for how best to work around it)? Or, whether it's us misunderstanding the API (like, for example, we were misunderstanding how autocomplete worked).

**Comment by magnus-madsen** [comment]
See https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#hover

**Comment by paulbutcher** [comment]
OK, having read the documentation and looked at the source, I'm 99% sure that this isn't a limitation of VSCode, but is a limitation of how we're using the interface.

We're returning markdown, and we wrap the entire message in ` ```flix `:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/api/lsp/provider/HoverProvider.scala#L82-L85

If we were to move the `mkCurrentMsg` outside of the syntax coloured region, I'm pretty sure it wouldn't be syntax coloured.

**Comment by magnus-madsen** [comment]
Yes. True. But then people complain that syntax is not highlighted and then we need to be ever smarter. I just wish there was an actual way to specify the formatting.

**Comment by paulbutcher** [comment]
Right. But we get to choose what we put inside the ` ```flix ` and what we put outside? Why can't we have the message about the information being potentially out of date outside and the Flix code inside?

**Comment by magnus-madsen** [comment]
> Right. But we get to choose what we put inside the `` ```flix `` and what we put outside? Why can't we have the message about the information being potentially out of date outside and the Flix code inside?

I think we could, if we somehow retain this information in our error messages.

**Comment by magnus-madsen** [comment]
Maybe the hover provider can simply disable it for error messages and keep it for everything else?

**Comment by paulbutcher** [comment]
You're overthinking it, I think. It's much easier than that. See the PR I've just created.

**Comment by paulbutcher** [comment]
(perhaps there are other cases that this doesn't fix, but this certainly seems to do the trick for the case I created this bug for).
