### ISSUE TITLE
Infinite loop with type classes

### ISSUE THREAD

**Issue by mlutze** [flix/flix#4618]
```scala
instance Hash2[Int32] {
    pub def hash(x: Int32): Int32 = Hash.hash(x)
}
```

Calling `Hash2.hash(0)` causes a loop

**Comment by mlutze** [comment]
This happens because we don't give instance defs unique namespaces and instead throw them into the parent namespace of the instance. I'm wondering now whether it would be better for there to be an `InstDefSym` which would separate instance defs from regular ones.

**Comment by JonathanStarup** [comment]
```
trait Hash2[t] {
    pub def hash(x: t): Int32
}
instance Hash2[Int32] {
    pub def hash(x: Int32): Int32 = Hash.hash(x)
}
def main(): Int32 = Hash2.hash(42)
```
This prints 42 on master
