### ISSUE TITLE
Commands, REPL, and Packager 0.5

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4623]
This ticket is intended to outline a **stop-gap** design for the Flix commands, repl, and packager.

It is not meant to be a final design, but merely to overcome some current weaknesses. In particular, the inconsistent treatment of a project by various components of the Flix compiler (VSCode, REPL, commands).

The goal is to harmonize.

We have these commands:

- init
- check
- build
- build-jar
- build-pkg
- run
- benchmark
- test
- install
- (doc)
- (lsp)
- (repl)

**Requirement 1:** We should be able to execute all of the above commands from: (a) the command line, (b) the repl, and (c) VSCode via the REPL. The commands should do the *same* no matter how they are invoked.

**Requirement 2:** VSCode will always have a repl running. In this the above commands can be executed, either by typing them or by invoking the corresponding command from VSCode or from a CodeLens.

**Requirement 3:** A Flix project has a specific layout (see below), but a user should be able to ***gradually*** opt-in to it. This means that you should be able to start with an empty directory and then add a `Main.flix` file. Later you can add a `src` folder, you can add a `lib` folder and so forth. 

**Requirement 4:** A Flix package must have a specific layout (see below). The `build-pkg` command will ***enforce*** this layout and refuse to build anything else.

We continue with current layout:

```
src/
lib/
test/
README.md
LICENSE.md
HISTORY.md -- We can drop this if desired.
```
Later, we will probably need a package manifest and lockfile, but that is for another time. The `build-pkg` command will require **exactly** this layout. It will refuse to do anything if any of the components are missing. 

**Requirement 5:** The above commands will work with any project that has some of the above structure. For example, **if** there is a `src` folder it will be used, if there is a `test` folder it will be used, if there is a `lib` folder it will be used, and so forth. 

**Requirement 6:** For all commands, except `build-pkg` Flix will also consider *.flix directly in the root directory (non-recursively). Thus its okay to have a folder with a single `Main.flix` file.

**Requirement 7**: No command can be invoked with any paths. Doing so is illegal. Flix can still be invoked with a list of files and packages. This means to compile and run those files and packages. (Commands can have flags, e.g. `-Xfoo`, but this is not intended for end-users).

Required changes:
- [x] The commands should use the same names in the repl, i.e. we should have `:build-jar` (I am OK with `:jar` as an alias).
- [ ] VSCode should be updated to use the right names (per above).
- [ ] VSCode should use exactly the same set of files as all of the commands (current dir + src + test + lib)
- [x] `init` should simply create files that do not exist (and warn if there are sources in the root).
- [x] Drop `HISTORY.md` (?)
- [ ] REPL, Packager, and SourceFiles should share more of the same infrastructure. In particular, the same way to find the project files.
- [x] Flix should standardize on `build` and not use `target`.
- [x] CodeLenses should be updated with `run` and `run test`.

**Comment by JonathanStarup** [comment]
I'd also request that you can run (a list of) files independent of file structure and the current working directory. I think some languages have `--script`. Also shouldn't we allow folders in the given list of files?

**Comment by magnus-madsen** [comment]
> I'd also request that you can run (a list of) files independent of file structure and the current working directory. I think some languages have `--script`. Also shouldn't we allow folders in the given list of files?

You can already do that right? Just run the compiler with all the files and with `--entrypoint`?

**Comment by magnus-madsen** [comment]
@mlutze Could I ask you to fix the `init` command?

@paulbutcher Could I ask you to look into harmonizing the repl with the packager. In both cases I would expect them to work as follows: 

- All files *.flix in current working directory (non-recursively).
- All files *.flix in src and test (recursively).
- Add jars and packages in lib.

**Comment by magnus-madsen** [comment]
@mlutze I can't find anywhere we use the `target` folder. Can you?

**Comment by magnus-madsen** [comment]
Maybe its in the vscode plugin?

**Comment by paulbutcher** [comment]
> @paulbutcher Could I ask you to look into harmonizing the repl with the packager?

Will do, but not until sometime next week (I'm heading off motor racing for the weekend 😊).

**Comment by magnus-madsen** [comment]
@mlutze It was in vscode.

**Comment by magnus-madsen** [comment]
This means to ensure there is one code path for "finding" the right files:

```
if (toml file) 
  do A
else {
  // use consistent set of criteria to find flix files, packages, and libs.
}
```

**Comment by JonathanStarup** [comment]
I was surprised to find that the reply didn't look in `src` before having some other folders (calling `init` fixed it); quite annoying. I am in support of this motion.

**Comment by magnus-madsen** [comment]
(ticket outdated)
