### ISSUE TITLE
Add new debugging facilities

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4646]

**Comment by mlutze** [comment]
I was thinking of introducing an alternative string interpolation like `"the value of myVar is: #{myVar}"` where it calls `mkDebugString(myVar)` or whatever instead of `toString(myVar)`

**Comment by magnus-madsen** [comment]
@JonathanStarup Can you sketch how we can even implement this magic toString? I don't see it myself

**Comment by magnus-madsen** [comment]
@JonathanStarup @mlutze @jaschdoc 

I have merged support for `debug(expr` into `master`. Please try it out! :)

**Comment by JonathanStarup** [comment]
So what parts of debug works now? I thought it would be a keyword, but its both a keyword and a function? 

So missing aspects are this magic toString and optimizer behaviour?

**Comment by JonathanStarup** [comment]
> @JonathanStarup Can you sketch how we can even implement this magic toString? I don't see it myself

My idea was just to call java.lang.object.toString, but then we of course need to know object vs primitive

**Comment by JonathanStarup** [comment]
you mean like this? (i forgot syntax of type case)
```
def debug(x: a): Unit = match reifyType(x) {
    case Obj => $magicToStringObj$(x as ##java.lang.object)
    case _ => ...
} as \ {}
```

**Comment by mlutze** [comment]
Yes, or

> you mean like this? (i forgot syntax of type case)
> 
> ```
> def debug(x: a): Unit = match reifyType(x) {
>     case Obj => $magicToStringObj$(x as ##java.lang.object)
>     case Int32 => $magicToStringInt32$(x as Int32)
>     case _ => ...
> } as \ {}
> ```

Yes, though we don't need magic ToString, right? Just Object.toString and Integer.toString etc.

**Comment by JonathanStarup** [comment]
> though we don't need magic ToString, right? Just Object.toString and Integer.toString etc.

Ah good point, yes, the backend objects just need to implement sensible implementations of toString yeah. So it's actually just
```
def debug(x: a): Unit =
    import java.lang.object.toString(##java.lang.object): String;
    match reifyType(x) {
    case Obj => toString(x as ##java.lang.object)
    case Int32 => Int32.toString(x as Int32)
    case _ => ...
} as \ {}
```

**Comment by magnus-madsen** [comment]
> but a lot of the cases in the match give their own weird runtime/compiletime errors

Can you be more specific? Are we generating the wrong code? 

@mlutze Are we even allowed to use the ToString type class in the above scenario?

**Comment by mlutze** [comment]
> @mlutze Are we even allowed to use the ToString type class in the above scenario?

I think we can use it, but I don't think we have to. We can just use the respective dedicated toString function.

**Comment by JonathanStarup** [comment]
When I build, only with the boolean case i get `Index 1 out of bounds for length 1re%183508`

**Comment by JonathanStarup** [comment]
# Issue 2 - verifier error on incorrect casts
In the String (Object) monomorphed `mydebug` it will generate code for the Int32 case, which has a incorrect cast `(int)"hello"` which results in a verifyError, instead of running the code.

**Comment by JonathanStarup** [comment]
I don't know how to fix the JVM generation, its maybe easier to eliminate the reifications in the monomorphization process? its static type reification right?

**Comment by mlutze** [comment]
Why do you use strings in your examples? I think that may be the cause of the issue, since when we monomorphize `f` to `Int32` we have an invalid call of Int64.toString(x) where `x` is really an `Int32`.

**Comment by JonathanStarup** [comment]
It was just to clarify that it wasn't the reification that causes the problem, but the same thing happens in code generation for reification. There is a unreachable branch of code that uses incorrect types

**Comment by JonathanStarup** [comment]
Aha, i found a fix for issue 2! cast the function, not the argument

```
enum Test(Int32)

def main(): Unit \ IO = {
    mydebug("hello");
    mydebug(Test(2));
    mydebug(());
    mydebug(true);
    mydebug('a');
    mydebug(32.5f32);
    //mydebug(64.5f64);
    mydebug(8i8);
    mydebug(16i16);
    mydebug(32i32);
    //mydebug(64i64);
    mydebug([1, 2, 3]);
    ()
}

def mydebug(x: a): Unit \ IO =
    import java.lang.Object.toString(): String;
    let magic = match reifyType a {
        case ErasedType => toString as a -> String
        case ReifiedUnit => _ -> "()"
        case ReifiedBool => (b -> if (b) "true" else "false") as a -> String
        case ReifiedChar => Char.toString as a -> String
        case ReifiedFloat32 => Float32.toString as a -> String
        //case ReifiedFloat64 => Float64.toString as a -> String
        case ReifiedInt8 => Int8.toString as a -> String
        case ReifiedInt16 => Int16.toString as a -> String
        case ReifiedInt32 => Int32.toString as a -> String
        //case ReifiedInt64 => Int64.toString as a -> String
        case ReifiedArray(_) => toString as a -> String
        case _ => _ -> "WIP"
    };
    println(magic(x))
```

**Comment by magnus-madsen** [comment]
How can the reifyType support enums?

**Comment by mlutze** [comment]
> How can the reifyType support enums?

Is that necessary? I thought backend would handle that

**Comment by JonathanStarup** [comment]
Isn't is just ErasedType? the enum objects will just implement a sensible toString

**Comment by JonathanStarup** [comment]
@magnus-madsen here is a working implementation. It's a bit unfortunate that it forces some tests to have the whole library even though they don't use anything. Maybe libMin should be expanded?

**Comment by magnus-madsen** [comment]
Question/Problem: How do you propose to deal with enums? Note that you cannot use the ToString of the enum because you do not have that type constraint on `a` in `debug`!

**Comment by magnus-madsen** [comment]
Ditto for tuples, records, etc.

**Comment by JonathanStarup** [comment]
I would just call toString on the sub-constructs (or the primitive method on primitives) for tag/tuples/records.

TupleIntIntObj would generate code for 
```java
"(" + Integer.toString(field0) + ", " + Integer.toString(field1) + "," + field2.toString() + ")"
```
Same idea for records (will build this recursively) and tags (will prefix their tag name)

**Comment by mlutze** [comment]
Does recursive records mean it ends up being like `{x = 1 | {y = 2 | {}}}`?

**Comment by JonathanStarup** [comment]
> Does recursive records mean it ends up being like `{x = 1 | {y = 2 | {}}}`?

That's the easiest, but we could add another method for generating tail strings, so the first toString call, calls tailString on the next and so on recursively. This could generate `{x = 1       , y = 2       }` (spaces illustrate different calls).

**Comment by magnus-madsen** [comment]
How many `toString` methods would you end up generating?

**Comment by magnus-madsen** [comment]
> Does recursive records mean it ends up being like {x = 1 | {y = 2 | {}}}?

It is still much better than what we currently have.

**Comment by magnus-madsen** [comment]
> I would just call toString on the sub-constructs (or the primitive method on primitives) for tag/tuples/records.

I would like to see that in action. At least for enums, just to see how it would work.

**Comment by magnus-madsen** [comment]
Followed by #4664
