### ISSUE TITLE
Ambiguous types compile erroneously

### ISSUE THREAD

**Issue by paulbutcher** [flix/flix#4649]
Some examples of programs which compile and which shouldn't:

```
import java.sql.Statement;
enum Statement

def foo(): Statement = ???
```

```
enum Statement
enum Foo
type alias Statment = Foo

def foo(): Statement = ???
```

```
import java.sql.Statement;
use Foo.Statement;

namespace Foo {
    pub enum Statement
}

def foo(): Statement = ???
```

```
use Foo.Statement;

namespace Foo {
 pub enum Statement
}
enum Statement
def foo(): Statement = ???
```

Split from #4392

**Comment by mlutze** [comment]
We maintain a separate import environment and use environment, right? I think we may want to combine these so that a type name can only point to one type.

Then when we add to the environment, we check if the name is already there and throw a `DuplicateUse/Import` error.

**Comment by paulbutcher** [comment]
We do, and that will address *some* of these problems.

But that wouldn't address:

```
import java.sql.Statement;
enum Statement

def foo(): Statement = ???
```

Or

```
enum Statement
enum Foo
type alias Statment = Foo

def foo(): Statement = ???
```

Or

```
use Foo.Statement;

namespace Foo {
 pub enum Statement
}
enum Statement
def foo(): Statement = ???
```

**Comment by mlutze** [comment]
Maybe when handling an Enum déclaration we should also check the use env. I strongly prefer that this is caught at the declaration site rather than the use site.

**Comment by paulbutcher** [comment]
That makes sense, but we would also need to handle type aliases too? Perhaps we should amalgamate uses, imports, and type aliases into a single environment within the namer? But right now type aliases are handled rather differently: mostly within the resolver whereas uses and imports are mostly handled in the namer?

Is this a complete list of everything, or is there anything else we need to consider:

* imports
* uses
* enums
* type aliases

**Comment by mlutze** [comment]
I think there is some env where type aliases and enums are already grouped. Classes are also in there. Like "use upper name"?

**Comment by paulbutcher** [comment]
I guess you're thinking of `lookupUpperName`?

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Namer.scala#L245

That looks worth trying. And (from reading the source) it looks like as well as classes, we also need to check for effects?

I'll see if I can come up with a PR.

**Comment by magnus-madsen** [comment]
We first need to decide whether to report the error on use or on declaration/import. If the latter then we cannot use any of the lookup functions. On the other hand, it might be useful to start there since this is what we currently have.

**Comment by paulbutcher** [comment]
Oops - one of the above examples is a red herring: I misspelled `Statement` in the one with `type alias` and `enum`. This isn't a bug (the others are though).
