### ISSUE TITLE
Flix: init command broken

### ISSUE THREAD

**Issue by paulbutcher** [flix/flix#4651]
This seems to be a regression: running "Flix: init" from the VSCode command palette gives:

<img width="1556" alt="Screenshot 2022-10-08 at 15 48 47" src="https://user-images.githubusercontent.com/61163/194713375-2b315536-f8de-4306-a08f-added537ccaa.png">

**Comment by magnus-madsen** [comment]
Hmm

**Comment by magnus-madsen** [comment]
I have removed the `init` command from VSCode (not from the the compiler). Its broken in VSCode because it can be invoked while no directory is open (no idea if it then creates a project in some random folder). Need to resolve this on the VScode side before re-enabling it.

**Comment by paulbutcher** [comment]
I'll add this to the list of things for me to think about in the new project/dependency work.

**Comment by magnus-madsen** [comment]
The issue is also more on the VSCode/repo side, not in Flix.
