### ISSUE TITLE
Consider whether method imports should default to IO (old Impure) effect

### ISSUE THREAD

**Issue by paulbutcher** [flix/flix#4661]
Split out from #4392

Pros:
* (probably) less typing overall
* Safer to assume Java methods are impure by default?

Cons:
* Inconsistent with Flix functions
* Less readable/explicit

**Comment by magnus-madsen** [comment]
I think the point was that IO will be common, so should  you be forced to write that every.single.time.? But maybe it is cathartic.

**Comment by paulbutcher** [comment]
Oh! I completely misunderstood the intention of this! So it's more that we want to make the effect portion of an `import` non-optional? You might say that the method is pure or impure, but you have to say one or the other?

**Comment by magnus-madsen** [comment]
Current behavior is OK.
