### ISSUE TITLE
Improve `debug`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4664]
A concrete list of improvements:

- [x] Add support for Unit (JLS)
- [x] Add support for `toString` on records
- [x] Add support for `toString` on closures
- [x] Refactor `Test.Exp.Debug` to test `debugString` directly (ML)
- [x] Add support for debug interpolation `"x = #{x}` should desugar to a call to `debugString` (ML)
- [x] Fix redundancy issue (?) (ML)
- [x] Add debug variants.
- [x] Make debug work like the identity function.
- [x] Format floating point with suffix (e.g. `f64`) (ML)
- [x] Format integers with suffix (e.g. `Int32`) (ML)
- [x] Format strings with quotes " (ML)
- [x] Format arrays with `Arrays.deepToString` (ML)
- [ ] #4679
- [x] #4680
- [ ] #4698

**Comment by JonathanStarup** [comment]
Also add custom redundancy hoops right? to allow `debug(Test(42)); 2`

**Comment by magnus-madsen** [comment]
> Also add custom redundancy hoops right? to allow debug(Test(42)); 2

Yes, does that not work already?

> At the backend we only have Int32 -> Bool, and only object for non-primitive things. I am also a bit sceptical about the usefulness. This is all in the type? isn't it better just to keep it brief for readability.

Good point! Not sure then. We could keep just the purity? (Maybe that information is gone too?)

> I feel the same about number suffixes. Its all known statically

Programmers could be confused. The point of the debug statement is to be very precise.

**Comment by magnus-madsen** [comment]
Another reason for keeping the suffixes: https://en.wikipedia.org/wiki/Homoiconicity

**Comment by JonathanStarup** [comment]
> We could keep just the purity? (Maybe that information is gone too?)

Maybe we could find the name sometimes, but I think `Fun#18y4271` has all the information you need.

> Then you can copy-paste a printed value into a program.

hmm. but the same logic could be said about normal `toString` right? and I think its a good thing that it isn't `42.5f32` by flix syntax you can't paste it anywhere else than flix

**Comment by mlutze** [comment]
@JonathanStarup can we also fix unit type and paramless enums in the back-end?

```
debug(Card(Hearts, N(5)))
```
gives
```
[main/test/ca/uwaterloo/flix/library/TestPrelude.flix:233] Card(Hearts(dev.flix.runtime.Unit@46cc127b), N(5))
```

**Comment by magnus-madsen** [comment]
This feature is the most exciting of the year!

![image](https://user-images.githubusercontent.com/2287953/195051222-3b76c1b2-7984-4bfc-a597-0ce1a457b983.png)

**Comment by magnus-madsen** [comment]
What would it take for us to support this:

```
let a = 2;
let b = dbg!(a * 2) + 1;
//      ^-- prints: [src/main.rs:2] a * 2 = 4
assert_eq!(b, 5);
```

**Comment by mlutze** [comment]
Seems easy enough just to pull the string out of the source location of the expression.

**Comment by magnus-madsen** [comment]
@mlutze Do you think we should use the suffixes or not?

**Comment by magnus-madsen** [comment]
I think its important to quotes strings. Consider the difference between `Option(None)` and `Option("None")`. This is also why I suggest to keep the suffixes.

**Comment by mlutze** [comment]
I'm leaning toward including the suffix. I imagine a case where I print out a value and say "oh it's acting weird because it's an Int32 instead of an Int64"

**Comment by magnus-madsen** [comment]
Proposal 1:
- Make `debug` return the expression so you can write `debug(x) + 1`.

Proposal 2:
- Introduce `debug`, `debugWithLine`, and `debugWithLineAndSource` (which prints the string, the string with the file and line number, and the string with the file, line, and expr).
- Since these names are long, call them `dbg!`, `dbg!!` and `dbg!!!` instead.

(Addendum: For proposal 1 to work, we probably have to tweak unused result).

**Comment by magnus-madsen** [comment]
@mlutze Will you add the suffixes, quotes, and array stuff?

**Comment by magnus-madsen** [comment]
@JonathanStarup I think it would be really useful of closures could print their monomorphed type. Is that an option?

**Comment by JonathanStarup** [comment]
> I'm leaning toward including the suffix. I imagine a case where I print out a value and say "oh it's acting weird because it's an Int32 instead of an Int64"

You cannot be surprised by this unless you use casts right? (pedantic note, but this scenario is impossible because of the issue about casting between cat1 and cat2 types discovered earlier)

> Introduce debug, debugWithLine, and debugWithLineAndSource [...]

These don't have to exist in the prelude. The weeder can just modify `debug(17)` to `println("something: %{17})` for all three versions. If you insist on using the java sout we could still have the single `debug: String -> Unit` or `debug: String -> String` to allow this alternative print definition.

**Comment by JonathanStarup** [comment]
> @JonathanStarup I think it would be really useful of closures could print their monomorphed type. Is that an option?

We could do that yes. I still think that's just distracting for the majority of users, unless you're a compiler debugger. I think maybe we agree/make clear what the purpose of debug is. I don't feel like a flix programer can fix their program based on the monomorphed types. They can just hover the types right? that's more information

**Comment by JonathanStarup** [comment]
> 

If you want more information, you can go to the printed source location and see the type IMO. I think I'm also leaning toward keeping strings short so even big composite values are nice to read). Maybe that's also a point of disagreement, whether to maximize information or minimize size.

**Comment by magnus-madsen** [comment]
> > I see your point, but its still more information than just printing "closure"?
> 
> If you want more information, you can go to the printed source location and see the type IMO. I think I'm also leaning toward keeping strings short so even big composite values are nice to read). Maybe that's also a point of disagreement, whether to maximize information or minimize size.

But its hard to see the monomorphed types. (But yes, I agree that is mostly for us). Even so, in some cases, it might be instructive to tell the programmer "This is a a function from Int to Int!"

**Comment by JonathanStarup** [comment]
> But its hard to see the monomorphed types.

I think this is better solved by being able to print ASTs, then you can also see other parts than just the backend type.

I like the quotes around strings, I don't think the number suffixes are good, but I feel less strongly about this although I do think brevity is better than the monomorphed types.

**Comment by JonathanStarup** [comment]
I agree, I just wanted to argue that they shouldn't be in the prelude, but it seems you also did it that way 👍

**Comment by JonathanStarup** [comment]
* In regard to closures/functions. If the function is a top-level function, could it just show its name?
* We also need nice strings for refs
* We also need nice strings for lazy

**Comment by magnus-madsen** [comment]
> * In regard to closures/functions. If the function is a top-level function, could it just show its name?

We could, but isn't everything a top-level function after lambda lifting?

>     * We also need nice strings for refs

We could dereference, but not sure.

>     * We also need nice strings for lazy

I don't think we can do this because we should not force the value.

**Comment by paulbutcher** [comment]
> I don't think we can do this because we should not force the value.

One of the things I would definitely want when debugging is some way to tell the difference between a lazy value that's been realised and one that not yet. Could we print the value if it's been realised and something like "unrealised lazy value" if not?

**Comment by JonathanStarup** [comment]
> We could, but isn't everything a top-level function after lambda lifting?

The things that are top-level in source are class `Def$...` and know their name. Closures are class `Clo$...` and don't know.

I agree with Ref/Lazy, my point was more that right now its random hashes and `%`. Maybe we should just make it prettier

**Comment by JonathanStarup** [comment]
> > I don't think we can do this because we should not force the value.
> 
> One of the things I would definitely want when debugging is some way to tell the difference between a lazy value that's been realised and one that not yet. Could we print the value if it's been realised and something like "unrealised lazy value" if not?

Ah good point, we could definitely do that!

**Comment by mlutze** [comment]
String isn't one of the reified types so I think the only way to do the string escape stuff is to use Java reflection...

**Comment by magnus-madsen** [comment]
> String isn't one of the reified types so I think the only way to do the string escape stuff is to use Java reflection...

Could it not be?

**Comment by mlutze** [comment]
It could, but I thought that reifyType was meant for handling ugly java primitive/reference stuff. Since String is a reference type it wouldn't qualify.

**Comment by magnus-madsen** [comment]
> It could, but I thought that reifyType was meant for handling ugly java primitive/reference stuff. Since String is a reference type it wouldn't qualify.

I think String falls into a special category because its a built-in type.

**Comment by magnus-madsen** [comment]
Once this ticket is complete, we should test the feature well and then I want to release a new version.

**Comment by JonathanStarup** [comment]
Shouldn't the string also be escaped in general? `\n` instead of new lines etc.

**Comment by mlutze** [comment]
We can't do it totally reliably, with all the Unicode craziness, but I have a best-effort implementation that addresses the most common and obvious ones.

**Comment by magnus-madsen** [comment]
> We can't do it totally reliably, with all the Unicode craziness, but I have a best-effort implementation that addresses the most common and obvious ones.

Sounds good. I believe Java has some escaping mechanisms no?

**Comment by JonathanStarup** [comment]
I think reifytype seems a bit confusing to me. It pretends to be compiletype reification right? but it's actually a runtime type check. So if you check for ErasedType before Unit then the unit case is never hit? (unit is an object after all). This also means that you can trick it with casts in your program.

Does it make guarantees on theses object types. If the argument is a string, should you always hit the string case or is it okay that you might hit the erasedType case sometimes? maybe the value under reification is nested in things and erased away etc.

**Comment by magnus-madsen** [comment]
> I think reifytype seems a bit confusing to me. It pretends to be compiletype reification right?

It is a compile-time construct (but perhaps its not simplified at compile-time).

> Does it make guarantees on theses object types. If the argument is a string, should you always hit the string case or is it okay that you might hit the erasedType case sometimes? maybe the value under reification is nested in things and erased away etc.

I think `ErasedType` is for non-star kind types.

**Comment by magnus-madsen** [comment]
I would hope the Optimizer removes the redundant cases, but I am not sure.

**Comment by JonathanStarup** [comment]
It doesn't seem like it. But if it did 100% of the time, then the issues with casting between cat types would disappear

**Comment by magnus-madsen** [comment]
@mlutze Do you have anything more on the formatting? I was hoping to ship a new version soon :)

Also, what is everyones thoughts on the names? (I note that rust uses `dbg` (because `debug` was taken) and that Elixir also use dbg).

**Comment by mlutze** [comment]
> @mlutze Do you have anything more on the formatting? I was hoping to ship a new version soon :)

I'll have something together soon.

> Also, what is everyones thoughts on the names? (I note that rust uses `dbg` (because `debug` was taken) and that Elixir also use dbg).

I have a slight preference for `debug`, but without any good reason.

**Comment by mlutze** [comment]
Are the `@Internal` names we introduce in the prelude still polluting the namespace?

**Comment by magnus-madsen** [comment]
> Are the `@Internal` names we introduce in the prelude still polluting the namespace?

What do you mean?

**Comment by mlutze** [comment]
I cannot define my own `stringify` function because there's already one in the prelude. But that's weird because there's no `stringify` function in the prelude API

**Comment by JonathanStarup** [comment]
I can do that, but what was the decision? named functions and `Closure` or?

**Comment by magnus-madsen** [comment]
> I can do that, but what was the decision? named functions and `Closure` or?

I was arguing for type plus effect. If the name is useful (i.e. not some auto-generated, lifted name) then we could also use that.

**Comment by JonathanStarup** [comment]
> > I can do that, but what was the decision? named functions and `Closure` or?
> 
> I was arguing for type plus effect. If the name is useful (i.e. not some auto-generated, lifted name) then we could also use that.

There is no effect in the backend. Ill add names to the meaningfully named ones.

**Comment by magnus-madsen** [comment]
@mlutze If you do the suffixes then I can package up a release? :)

**Comment by magnus-madsen** [comment]
@mlutze @JonathanStarup @jaschdoc @paulbutcher I think  we are feature complete, try to test it out! :)

**Comment by paulbutcher** [comment]
I've been having a play, and it looks good, but...

It doesn't seem to be possible to use `debug` in a pipeline?:

```
def foo(x: Int32): Int32 =
    1 |> debug
```

Gives:

```
>> Unable to unify the types: 'Int32' and 'String'.

2 |     1 |> debug
        ^^^^^^^^^^
        mismatched types.

Type One: t3664412 -> ((t3664412 -> t3664418 & b3664413 \ e3664415) -> t3664418 & b3664413 \ e3664415)
Type Two: Int32 -> ((String -> (?result3664424 -> ?result3664424 & Impure)) -> ?result3664409 & ?pur3664410 \ ?eff3664411)
```

and 

```
def foo(x: Int32): Int32 =
    1 |> debug!
```

gives

```
>> Undefined name 'debug!'.

2 |     1 |> debug!
             ^^^^^^
             name not found


Explanation:
Tip: Possible typo or non-existent definition?
```

**Comment by magnus-madsen** [comment]
Yes, that's a limitation we have to document. Its a statement-like construct. Not really a function.

Another limitation that we have to document is that if you use it in inside a pure function and the result of that function is not used, the optimizer will eliminate the entire call, and nothing will be printed (which is what you would expect if you think about it, but may at first be confusing).

**Comment by paulbutcher** [comment]
Oh! That's a real pity 😟.

Is there anything stopping us from making it function-like? Using it in a pipeline would be *really* useful. You could just stick `|> debug` on the end of any expression (or in the middle of any pipeline) and get an output of the value at that point.

**Comment by paulbutcher** [comment]
A concrete example where it's basically impossible to insert a statement, but it would be *really* useful to get debugging is for-comprehensions. When a comprehension gets complicated it can be really useful to see intermediate values, e.g.:

```
for(i <- List.range(0, 10);
    j <- List.(i, 10) |> debug)
    yield (i, j)
```

**Comment by magnus-madsen** [comment]
> 

I fully agree. I am not sure how to do it though-- because if we make into a function then that would have to be pure which the optimizer would wreck havoc on. Not sure if someone else can see an easy solution.

**Comment by paulbutcher** [comment]
Can we really not just mark the function with an annotation that the optimiser recognises as meaning "hands off"?

**Comment by magnus-madsen** [comment]
> Can we really not just mark the function with an annotation that the optimiser recognises as meaning "hands off"?

Not really because that information is propagated through the program. (In the general case).

**Comment by paulbutcher** [comment]
This really is essential in my view: the whole point of a debugging construct like this is to make it possible to get debugging out of a function without having to tear the structure of the function apart. If you have to tear the function to bits to see what's going on within it, then you're never sure you're debugging what you think you are.

**Comment by magnus-madsen** [comment]
You can use it "in expression position", but not as a value. 

```
for(i <- List.range(0, 10);
    j <- debug(List.range(i, 10))
    yield (i, j)
```

The difference might seem trivial (i.e. why can't we just "fix it"...) but things that are values (i.e. first-class) are fundamentally different from things that are not. The `debug` thing is fundamentally unsound (i.e. broken to use a more precise word), but its broken in a very specific way that we are able to tolerate with some very specific hacks. 

For example, if we have `let _unused = f(x); e` and `f(x)` is pure then the optimizer is allowed to remove the let-binding. Note that such unused let-bindings occur all the time, not because the programmers writes them, but because they naturally arise from inlining and simplifications. The trouble is that if `debug` is a value then it could be f! and then we should not remove the binding. But we cannot know this because debug breaks all the rules about purity. 

So again I am 100% in agreement about the feature, but I don't know how to implement it, unless you give up on any program transformations.

**Comment by magnus-madsen** [comment]
I think Matt pointed out that debug is already "broken" with this example:

```
def inc(x: Int32): Int32 = debug(x + 1)

def main(): Unit \ IO = 
  let _dontcare = inc(123);
  println("Hello")
```

which only prints hello.

**Comment by paulbutcher** [comment]
Ah, OK, that might be good enough.

In which case, can we (as a minimum) put in a better error message so that it's obvious to the programmer what's happening if they use `debug` as a value?

**Comment by magnus-madsen** [comment]
> In which case, can we (as a minimum) put in a better error message so that it's obvious to the programmer what's happening if they use debug as a value?

I think we can do that.

**Comment by magnus-madsen** [comment]
Although this does not work with debug! and debug!! right?

**Comment by paulbutcher** [comment]
> Although this does not work with debug! and debug!! right?

Exactly what I was going to say. The problem is that the programmer will naturally assume that `... |> debug!` will work, and we need to either make that work, or display a helpful error message explaining why it doesn't

**Comment by magnus-madsen** [comment]
Here is a hack on top of a hack: https://github.com/flix/flix/pull/4702

Note that `debug!` and `debug!!` now works-- just that they print n/a except for the actual value logged.

**Comment by magnus-madsen** [comment]
How it "works":

- If you use `debugX` as a direct call (i.e. `debugX("FOO")` you will get source location and source code. Otherwise those are missing. 
- If the debug expression occurs as a STATEMENT the compiler will not remove it. Otherwise it will be removed if the expression it occurs within is unused. 

Example:

```
debug!("hello"); // prints filename and hello 
1 + 2
```

```
(w -> debug!(w))("too clever for my own good");
1 + 2
```

prints nothing.

**Comment by paulbutcher** [comment]
This is all feeling too clever to me. If we can't do it properly, then I think we should stick with the status quo _**plus**_ a sensible error message if `debug`, `debug!`, or `debug!!` are used as values.

**Comment by magnus-madsen** [comment]
> This is all feeling too clever to me. If we can't do it properly, then I think we should stick with the status quo _**plus**_ a sensible error message if `debug`, `debug!`, or `debug!!` are used as values.

Which parts? The missing source locations for debug! and debug!! or the fact that debugs might not print at all? The former we can iterate on, the latter is a consequence of hacking around purity.

**Comment by magnus-madsen** [comment]
In any case, I suggest to try it out. Its not that bad.

**Comment by paulbutcher** [comment]
So, we have a choice between "bad things".

If our production code is `a |> b |> c` and the programmer wants to see what `b` returns, they will expect that they could write either `a |> debug!(b) |> c` or `a |> b |> debug! |> c`. They will expect that both will be equivalent.

They can't be, because of fundamental issues. So we have to choose between:

1. A helpful error message explaining why the second form doesn't work

or

2. The second works, but doesn't (quite) do what the programmer expects (it won't output the location).

**Comment by magnus-madsen** [comment]
I would lean towards 2 (but only because its still does the fundamental job-- its just some information is missing) and because its easier to move code around while debugging (both with and without !! work everywhere). We could document it as "!" and "!!" **tries** to provide more information (if available). Second, I would hope, with some changes I have not figured out yet, we could potentially fix `debug!` and `debug!!` in non-statement position.

**Comment by paulbutcher** [comment]
I can live with that 👍

**Comment by magnus-madsen** [comment]
Also; this is our first attempt at a debug function. I think we did pretty ok. :)

**Comment by JonathanStarup** [comment]
I already have some requests 😁 Lines are massively long when I debug things. I'd like paths to be shorter via project relative paths

**Comment by magnus-madsen** [comment]
> I already have some requests 😁 Lines are massively long when I debug things. I'd like paths to be shorter via project relative paths

I have seen that too. I think that applies to the whole compiler. Question is: What should the path be? What you supply to the compiler or?

**Comment by magnus-madsen** [comment]
We can at least abbreviate to X chars.

**Comment by magnus-madsen** [comment]
Or perhaps only the filename?

**Comment by JonathanStarup** [comment]
> Or perhaps only the filename?

I also though about this, I don't think filenames will lead to confusion often. A minus is that you cannot scan a list of debugs based on the folder, but then again, when do you have that many debugs 🤷‍♀️

**Comment by magnus-madsen** [comment]
I will close this ticket, so lets open new tickets for specific issues with debug.
