### ISSUE TITLE
Ease the `ImpureDiscardedValue` check

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4673]
Proposal:

We ease the `ImpureDiscardedValue` to only disallow impure expressions that discard enums tagged `@MustUse`. (`Result` would be such an enum).

**Comment by JonathanStarup** [comment]
If the default should be safe (the programmer hasn't told us, so we don't know), then it should be the other way around with `@Discard` that allows implicit `discard`. Isn't optional information rarer than "pure" computations on mutable structures?

**Comment by magnus-madsen** [comment]
One issue: We cannot tag `Int32` so that would always be non-discardable, I assume.

**Comment by magnus-madsen** [comment]
Another issue: What about polymorphic types?

**Comment by JonathanStarup** [comment]
I don't mean on the types, since they can be used in both contexts. I mean on the functions.
```
/// Returns the number of removed elements.
@Discard
def removeDublicates(a: Array[Int32, r]): Int32 \ {Write(r), Read(r)} = ???

/// Returns the sum of the elements of the array.
def sum(a: Array[Int32, r]): Int32 \ Read(r) = ???
```
Same type, different context. The second function is not `@Discard` since its "imperative pure"; don't call it if you don't use the result.
