### ISSUE TITLE
Introduce `Mask`?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4681]
Proposal to have:

- Ascribe: Asks the typer to verify a type and effect is as expected. Safe.
- Cast: Tells the typer that an expression has the given type and effect. Unsafe.
- Mask: Is type checked as pure, but treated as impure post type inference. Unsafe.

We can then possibly refactor Debug to use `Mask`.

**Comment by JonathanStarup** [comment]
Is the use case custom logging where you want the same behavior? If so, isn't that supposed to be solved by effects?

**Comment by magnus-madsen** [comment]
> Is the use case custom logging where you want the same behavior? If so, isn't that supposed to be solved by effects?

The use case is to have a more general mechanism (internally) than a very specific "Debug" expression.

**Comment by mlutze** [comment]
What's the syntax?

Where should the typing change come in? It seems like it needs to come after regions but before redundancy.

**Comment by magnus-madsen** [comment]
Not sure if there is any surface syntax. The magic happens in Typer and Redundancy.

**Comment by magnus-madsen** [comment]
The syntax could be `mask e` which is typed as pure (no matter the effect of e), but which is treated as impure after type inference.

**Comment by magnus-madsen** [comment]
Its a bit hard to use in the surface language though. I mean you could do `mask println()`, but you could not write a function that does that (because it would be pure).
