### ISSUE TITLE
Cannot upcast String

### ISSUE THREAD

**Issue by mlutze** [flix/flix#4693]
String is a subclass of CharSequence, but we cannot upcast String to CharSequence

I would guess there's a similar issue with BigInteger -> Number, Array -> Object

**Comment by magnus-madsen** [comment]
@jaschdoc Would this work now?

**Comment by jaschdoc** [comment]
Yes we even have a test for it :)

```flix

    @test
    def testUpcast17(): Unit =
        let f = (_: ##java.lang.CharSequence) -> ();
        f(upcast "hello")

```
