### ISSUE TITLE
Document the new debugging facilities

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4698]

**Comment by paulbutcher** [comment]
@magnus-madsen any idea why this:

```
List.range(0, 10) |> List.map(x -> x + 1) |> debug |> List.toSet
```

Outputs:

```
Cons(1, Cons(2, Cons(3, Cons(4, Cons(5, Cons(6, Cons(7, Cons(8, Cons(9, Cons(10, Nil))))))))))
```

Whereas this:

```
List.range(0, 10) |> debug(List.map(x -> x + 1)) |> List.toSet
```

Outputs:

```
Obj -> Obj   
```

?

**Comment by magnus-madsen** [comment]
If you follow the types:

The type of `List.range(0, 10) |> List.map(x -> x + 1) |>` is a list, so you would expect to see a list.

The type of  `List.map(x -> x + 1)` is a function, so you would expect Obj -> Obj.

In the latter case, what you wanted is probably:

```
List.range(0, 10) |> List.map(x -> debug(x + 1)) |> List.toSet
```

(if the goal is to see each element)

**Comment by paulbutcher** [comment]
Ah! Because it's curried. Got it.

**Comment by paulbutcher** [comment]
Which is a good argument for choosing to implement the value style of `debug`: that's almost certainly what you want in a pipeline.

**Comment by magnus-madsen** [comment]
> Which is a good argument for choosing to implement the value style of `debug`: that's almost certainly what you want in a pipeline.

Agreed. Good that you and @JonathanStarup convinced me.

**Comment by magnus-madsen** [comment]
Interesting that a PR in one repo can fix an issue in another.
