### ISSUE TITLE
Error message for uncapitalized enum cases (possible dublicate)

### ISSUE THREAD

**Issue by AStenbaek** [flix/flix#4701]
I was unable find a issue mentioning this.
The error message from not capitalizing the case in an enum, is not very helpful.
Consider the following code:
```flix
enum Foo {
    case bar,
}
```
Which produces the error:
```
>> Parse Error: Invalid input "{     case b", expected "with", CaseBody or Declaration (line 1, column 10):
enum Foo {
         ^
```

**Comment by paulbutcher** [comment]
Along similar lines: #3996

**Comment by magnus-madsen** [comment]
Outdated. We have a new parser.
