### ISSUE TITLE
bug: Record restriction is a mutating operation 

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#4704]
This program shows that `r1` lost the `z` field.
```
pub def example(): Int32 = {
    let r1 = {x = 1, y = 1, z = 1};
    let r2 = {-z | r1};
    (r1.z + r2.y) |> (i -> {debug(r1); i})
}
```

**Comment by magnus-madsen** [comment]
Indeed. The runtime semantics are wrong. 

```
    def RestrictFieldMethod: InstanceMethod = Record.RestrictFieldMethod.implementation(this.jvmName, IsFinal, Some(
      caseOnLabelEquality {
        case TrueBranch =>
          thisLoad() ~ GETFIELD(RestField) ~ ARETURN()
        case FalseBranch =>
          thisLoad() ~
            DUP() ~ GETFIELD(RestField) ~
            ALOAD(1) ~
            INVOKEINTERFACE(Record.RestrictFieldMethod) ~
            PUTFIELD(RestField) ~
            thisLoad() ~ ARETURN()
      }
    ))
```

we should not modify any thing.

**Comment by JonathanStarup** [comment]
It is okay if restrict causes linear allocations. I guess that's the same for list remove?

**Comment by JonathanStarup** [comment]
I guess that's what you'd expect, If we want some performance back, we could stop implementing update as restrict+extend

**Comment by magnus-madsen** [comment]
Yep, its unavoidable. Cost of doing business.

**Comment by JonathanStarup** [comment]
Its pretty hard to trigger this with the optimizer so I'm not sure what a testcase looks like. My initial triggering program is complex enough for the optimizer to give up.
