### ISSUE TITLE
Show built-in functions in API documentation

### ISSUE THREAD

**Issue by paulbutcher** [flix/flix#4712]
Right now, https://api.flix.dev only shows functions that are implemented in the standard library. This means that there's no documentation for built-in functions and operators (e.g. `debug`, `<=>`, ...).

**Comment by magnus-madsen** [comment]
I need to update it, its still at 0.31.0

**Comment by paulbutcher** [comment]
> I need to update it, its still at 0.31.0

Ah, that might help with `debug`, but it won't with things like `<=>`?

**Comment by magnus-madsen** [comment]
I don't even recall what `<=>` is :)

**Comment by paulbutcher** [comment]
It's the "spaceship" operator, which returns -1, 0, or 1 depending on whether it's operands are <, =, or >

But there are lots of built-in operators which don't appear in the documentation: `::`, `:::`, ... Basically any operator that the parser knows about.

**Comment by mlutze** [comment]
Could we turn those operators into actual definitions and get Flixdoc for them with minimal effort?

**Comment by magnus-madsen** [comment]
Fixed in master.
