### ISSUE TITLE
Rename `FunctorFilter` to `Filterable` ?

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#4713]
Now we have a `Witherable` class a la PureScript and Haskell should we rename `FunctorFilter` to `Filterable` ?

[1] https://hackage.haskell.org/package/witherable-0.4.2/docs/Witherable.html

[2] https://pursuit.purescript.org/packages/purescript-filterable/2.1.0

**Comment by magnus-madsen** [comment]
I think that sounds reasonable. 

I forget if FunctorFilter is even used anywhere?

**Comment by stephentetley** [comment]
> I forget if FunctorFilter is even used anywhere?

It's a superclass of `Witherable`. It can be filled out a bit more e.g. with `mapMaybe` and `catMaybe` to make it more useful.

I'll make a PR with just the renaming for the time being...

**Comment by stephentetley** [comment]
PR #4715 submitted: 
refactor: rename FunctorFilter to Filterable, issue #4713
