### ISSUE TITLE
Allow closures to implement suitable functional interfaces (e.g. `IntFunction`)

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4721]

**Comment by JonathanStarup** [comment]
I can do the backend if somebody can do typer implementation

**Comment by magnus-madsen** [comment]
You can test by starting with a cast. Then I will find someone to do the frontend. (@mlutze?)

**Comment by mlutze** [comment]
I can do the front end if somebody can give me more details about what's needed :)

**Comment by magnus-madsen** [comment]
> I can do the front end if somebody can give me more details about what's needed :)

Yes. When we lookup at Java type and see e.g. `IntFunction` we should translate it/treat it as `Int32 -> Int32`

**Comment by magnus-madsen** [comment]
Maybe we can treat `##java.util.function.IntFunction` as pseudo-type alias for `Int32 -> Int32`?

**Comment by mlutze** [comment]
In `Resolver` we already translate `java.lang.String` to `String` and `java.lang.BigInteger` to `BigInt`, so it seems like we can do a similar translation there.

Do we want to curry e.g. `BiFunction` or make it a tuple?

**Comment by magnus-madsen** [comment]
> Do we want to curry e.g. BiFunction or make it a tuple?

Not sure

But lets start with `IntFunction` and see if we can make it work! :)

**Comment by magnus-madsen** [comment]
@mlutze @JonathanStarup 

Perhaps what would be most sensible now is that you add support for e.g. `IntUnaryOperator`, refactor the code to be generalizable, and then @jaschdoc can add support for most of the stuff in https://docs.oracle.com/javase/8/docs/api/java/util/function/package-summary.html ?

**Comment by magnus-madsen** [comment]
Its kind of crazy what they have there.

**Comment by stephentetley** [comment]
Thanks Magnus, I've updated my library code with the new `IntNumber` and it passes `check`, I haven't got to writing / running tests yet.

**Comment by magnus-madsen** [comment]
> Thanks Magnus, I've updated my library code with the new `IntNumber` and it passes `check`, I haven't got to writing / running tests yet.

Let us know how it goes :)

**Comment by stephentetley** [comment]
I've got a PR almost ready that adds `IntPredicate`.

**Comment by magnus-madsen** [comment]
@stephentetley Thanks! Perhaps you could be persuaded to add the other functions that you deem useful?

(I don't think we necessarily need everything in `java.util.Function`, but a few more would surely be useful?)

**Comment by stephentetley** [comment]
Thanks Magnus - yes I'll look at adding more functions. 

Ideally I'd like to cover the ones needed by Java's Stream API, which I'm trying to wrap but hopefully can give an interface that feels close to native Flix.

**Comment by magnus-madsen** [comment]
@stephentetley Are we planning to add more or should I close this?

**Comment by stephentetley** [comment]
I don't think I'll be adding any more soon, so the ticket can be closed as far as I'm concerned.
