### ISSUE TITLE
Class loader thoughts

### ISSUE THREAD

**Issue by paulbutcher** [flix/flix#4728]
While looking at package management, I've been looking into how the compiler uses class loaders. Here is what I believe the current situation to be:

* The compiler itself runs under the system class loader (this is the default for "normal" Java code).
* The compiled code runs under [`FlixClassLoader`](https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/jvm/FlixClassLoader.scala).
* Any jar files are loaded by [`ExternalJarLoader`](https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/util/ExternalJarLoader.scala).

Both `FlixClassLoader` and `ExternalJarLoader` delegate to the system class loader (this is the default if you don't provide an explicit parent when constructing a class loader, which neither of them do).

The consequence of this is that everything within the Flix compiler is available to compiled Flix code, e.g.:

```
pub def main(): Unit \ IO = 
    import static ca.uwaterloo.flix.util.Toucan.leToucan(): String \ {};
    println(leToucan())
```

```
flix> :eval main()                                                              
                                                                                
░░░░░░░░▄▄▄▀▀▀▄▄███▄░░░░░░░░░░░░░░
░░░░░▄▀▀░░░░░░░▐░▀██▌░░░░░░░░░░░░░
░░░▄▀░░░░▄▄███░▌▀▀░▀█░░░░░░░░░░░░░
░░▄█░░▄▀▀▒▒▒▒▒▄▐░░░░█▌░░░░░░░░░░░░
░▐█▀▄▀▄▄▄▄▀▀▀▀▌░░░░░▐█▄░░░░░░░░░░░
░▌▄▄▀▀░░░░░░░░▌░░░░▄███████▄░░░░░░
░░░░░░░░░░░░░▐░░░░▐███████████▄░░░
░░░░░le░░░░░░░▐░░░░▐█████████████▄
░░░░toucan░░░░░░▀▄░░░▐█████████████▄
░░░░░░has░░░░░░░░▀▄▄███████████████
░░░░░arrived░░░░░░░░░░░░█▀██████░░


()
```

Right now, this is necessary because the channel code needs to access classes such as `ca.uwaterloo.flix.runtime.interpreter.Channel`, but it causes problems:

* Firstly, it allows compiler internals to "leak" into Flix code, which might not be discovered until you create a Jar file and then discover that it's missing dependencies.
* More seriously, if a Fix program depends upon a Jar file which the compiler also depends upon, there will be uncontrolled conflicts.
  * This is a problem today, but will become a much larger problem when we integrate Maven, because Maven has *lots* of dependencies, many of which are in very common use (I've already hit this while using Jetty to write a webserver in Flix: Maven depends upon many of the same libraries as Jetty).

The solution is simple, I think: stop both `FlixClassLoader` and `ExternalJarLoader` from delegating to the system class loader.

Before we do so, we will need to move the channel code into the runtime, but I believe that that's the only code currently within the compiler that's legitimately accessed by compiled Flix code.

One other thing we should do: we're not currently setting the thread context class loader. This causes problems for libraries that rely upon it such as Log4j, so we should do so.

Does anyone see any issues with the above?

**Comment by magnus-madsen** [comment]
Another side note: We should actually never load any classes in the JVM. Instead, we should parse the JARs and class files and extract their signatures.

**Comment by paulbutcher** [comment]
> Another side note: We should actually never load any classes in the JVM. Instead, we should parse the JARs and class files and extract their signatures.

Just to make sure I understand correctly: you're talking about within the compiler (i.e. within the code running within the system class loader), yes? The *compiled* code will definitely have to load classes from Jar files, yes?

**Comment by magnus-madsen** [comment]
> > Another side note: We should actually never load any classes in the JVM. Instead, we should parse the JARs and class files and extract their signatures.
> 
> Just to make sure I understand correctly: you're talking about within the compiler (i.e. within the code running within the system class loader), yes? The _compiled_ code (running within `FlixClassLoader`) will definitely have to load classes from Jar files, yes?

Yes, when compiling the code there is no need to load it. Its only if we run it, we have to load it. (Or fork another JVM with the right classpath?)

**Comment by paulbutcher** [comment]
> (Or fork another JVM with the right classpath?)

That's definitely a possibility, but my instinct is that it's probably excessively heavyweight. I would think that the current class loader approach, with the modifications I suggest above, should be more than sufficient.

**Comment by paulbutcher** [comment]
> Sidenote, `main/src/dev/flix/runtime/Global.java` is also involved here in a weird way. We use it in the std lib code but also generate an equivalent class for the output code. It certainly doesn't seem like a proper solution but I'm unsure how to fix it. Maybe we generate this one class before running the compiler? or we hardcode imports to accept these signatures? I'm not sure

Yes, I also noticed that. I suggest that I get the channel stuff done, and then I'll take a look at this.

**Comment by magnus-madsen** [comment]
If we do not delegate to the system class loader, will Flix code still be able to use Java code? (E.g. String)?

**Comment by paulbutcher** [comment]
> If we do not delegate to the system class loader, will Flix code still be able to use Java code? (E.g. String)?

Yes (I've tested this)

**Comment by magnus-madsen** [comment]
To summarize, I propose:

- [ ] Emitted bytecode should not depend on the Flix compiler (nor on Scala). 
  - [x] I believe Scala dependency has been solved.
  - [ ] I am unsure about `GlobalCounter`.
  - [ ] We need to get rid of `Channel.java` dependency. (Obliterate everything in `flix/main/src/ca/uwaterloo/flix/runtime/interpreter`)
- [ ] Change `FlixClassLoader` to not delegate to the system class loader.
- [ ] Change `ExternalJarLoader` to not delegate to the system class loader.
- [ ] (Eventually: Do not use class loaders in the compiler itself.)

**Comment by paulbutcher** [comment]
By `GlobalCounter` do you mean `main/src/dev/flix/runtime/Global.java`? (I can't find anything called `GlobalCounter`)

**Comment by magnus-madsen** [comment]
@JonathanStarup I think once `Channel.java` is gone we can get rid of `Global` too, right or?

**Comment by paulbutcher** [comment]
One thing to add to your list:

- [ ] set thread context class loader

**Comment by JonathanStarup** [comment]
> @JonathanStarup I think once `Channel.java` is gone we can get rid of `Global` too, right or?

No, this is used for
* Datalog engine (Global unique ID)
* Channels (Global unique ID)
* Environment (storing program args in a static place)
