### ISSUE TITLE
Upcast IntX to IntY, FloatX to FloatY

### ISSUE THREAD

**Issue by mlutze** [flix/flix#4735]

**Comment by magnus-madsen** [comment]
Do you mean widening? Do we not have that in the namespaces?

**Comment by magnus-madsen** [comment]
clampToInt32 and toInt64.

**Comment by magnus-madsen** [comment]
I would NOT use upcast for this.

**Comment by magnus-madsen** [comment]
No implicit coercions!

**Comment by mlutze** [comment]
> No implicit coercions!

It wouldn't be implicit though :)

**Comment by mlutze** [comment]
We have it in the namespaces, but it would be nice if it cooperated with the other safe upcasting stuff.

**Comment by magnus-madsen** [comment]
What's wrong with using `Int32.toXYZ`?

**Comment by magnus-madsen** [comment]
I really think when you do such a conversion it should be called out.

**Comment by mlutze** [comment]
My concern is that Java effectively treats `long` as a super type of `int`, and our `upcast` keyword is missing out on that.


But, I see how this ends up being a lot more complex than a regular cast as we have to inject a real conversion operation rather than working at the type level.

**Comment by magnus-madsen** [comment]
No upcasts with semantics.
