### ISSUE TITLE
BigDecimal

### ISSUE THREAD

**Issue by mlutze** [flix/flix#4736]
It would be nice to have a `BigDecimal` type in the standard library.

See also #719

**Comment by stephentetley** [comment]
I've taken a look at this as it's a feature I've wanted for a long time. 

I've got support working in the compiler, I need to do the tests and stdlib updates.

**Comment by magnus-madsen** [comment]
Compiler support could be one PR with library support to follow.

**Comment by stephentetley** [comment]
> Compiler support could be one PR with library support to follow.

Okay

First discussion point - what to use for the literal suffix? If we use "ff" as per `BigInt` 's "ii" there is a problem that "ff" might be read as a hex number, although `Float32` and `Float64` already have this problem.

**Comment by magnus-madsen** [comment]
> > Compiler support could be one PR with library support to follow.
> 
> Okay
> 
> First discussion point - what to use for the literal suffix? If we use "ff" as per `BigInt` 's "ii" there is a problem that "ff" might be read as a hex number, although `Float32` and `Float64` already have this problem.

I never liked `ii`. I am open to suggestions.

**Comment by stephentetley** [comment]
I'm largely agnostic?

Does @mlutze have an opinion as he does a lot of work on the parser?

**Comment by magnus-madsen** [comment]
Do we know of any other languages that use some established suffix?

**Comment by mlutze** [comment]
I'm partial to making it the default, but maybe it's too early for that.

**Comment by magnus-madsen** [comment]
> 

BigDecimal, right (not BigInt). But in any case, we would want a suffix to be precise. 

And yes, I think its a bit too early.

**Comment by stephentetley** [comment]
Looking at hex numbers they will always have an "0x" prefix, so the "ff" suffix for BigDecimal is probably not a headache for the parser. So I'm now leaning towards "ff" especially if it is always lowercase.

**Comment by stephentetley** [comment]
Compiler changes are now submitted: 

PR #4748 - feat: add compiler support for BigDecimal (related to #4736)

**Comment by stephentetley** [comment]
And stdlib changes submitted: 

PR #4752 - feat: add stdlib support for BigDecimal (related to #4736)
