### ISSUE TITLE
Improved ReifyType

### ISSUE THREAD

**Issue by mlutze** [flix/flix#4739]
Option 1:

We can change reifyType to be essentially a type-case expression:

```
typematch x {
    case y: Int32 => ...
    case y: Array[String, Static] => ...
    case y: Map[String, Bool] => ...
    case _ => ...
}
```

Then monomorph replaces the expression with 
```
let y = x;
...
```

The nice thing is that here we don't have to cast anything anymore. Plus we can match on any type we want.
But, erased types might cause complications; we can likely get around this with safety checks.
Matching on any type you want might lead to unprincipled design.

Option 2:

Add a parameter to reifyType cases;
```
pub enum ReifiedType2 {
    case ErasedType(##java.lang.Object),
    case ReifiedUnit(Unit),
    case ReifiedBool(Bool),
    case ReifiedChar(Char),
    case ReifiedFloat32(Float32),
    case ReifiedFloat64(Float64),
    case ReifiedInt8(Int8),
    case ReifiedInt16(Int16),
    case ReifiedInt32(Int32),
    case ReifiedInt64(Int64),
    case ReifiedBigInt(BigInt),
    case ReifiedString(String),
    case ReifiedArray(ReifiedType, ##java.lang.Object)
}
```

And do magic replacements as in Option 1.

```
typematch x {
    case ReifiedInt32(y) => ...
    case ReifiedArray(String, y) => ...
    case _ => ...
}
```

Some casts are still needed since `ReifiedArray` can be of any type.

**Comment by magnus-madsen** [comment]
I think we need option 1 with the requirement that its eliminated in monomorph.

**Comment by magnus-madsen** [comment]
Plus:
- The requirement there is a default cause (because there are infinitely many types (?)).
- The ability to use wildcards `Array[t, _]`.
- (Unsure about overlapping cases. Maybe we don't care for now).
- Implemented an entirely new construct `TypeMatch` with `TypeMatchCase` etc.

**Comment by magnus-madsen** [comment]
(Clever use of this construct can probably loop the compiler; but this feature is intended for internal use anyway.)

**Comment by magnus-madsen** [comment]
@mlutze Do you want to sketch an implementation by showing how TypedAst would be extended?

**Comment by magnus-madsen** [comment]
What should happen for:

```
typematch Nil
```

?

**Comment by JonathanStarup** [comment]
What is the usecase for arbitrary types? It seems overly complicated for current usecases

**Comment by magnus-madsen** [comment]
> What is the usecase for arbitrary types? It seems overly complicated for current usecases. Is it to make it future proof (instead of adding cases like we did for string?)

Arbitrary as in what? 

I think its more that we get it for free, so why not allow it. The real issue is with how to deal with type variables.

**Comment by JonathanStarup** [comment]
Arbitrary as in match on any type. It makes sense that it should work, but as your question shows, implementing option 2 seems more straightforward and also solves the current issues. Option 1 might be better long term though.
