### ISSUE TITLE
Add path extraction methods to `File`.

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#4745]
When using functions such as `File.list` or `File.walk` you just get single strings. I would like to split this thing into a list of folders (strings) and a filename string. 

```scala
/// `"asd/qwe/zxc.txt"` -> `"asd" :: "qwe" :: Nil`
def folders(p: String): List[String] = ???
/// `"asd/something.cool.txt"` -> `something.cool.txt`
def fileName(p: String): String = ???
```
If there can be parser errors on paths, then they return option instead.

**Comment by magnus-madsen** [comment]
If you propose some signatures I can have a student programmer look at it.

**Comment by magnus-madsen** [comment]
I think this module can be reworked.
