### ISSUE TITLE
Add `Sub`/`Add` instances to tuples

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#4747]
* `(1, 1) - (2, 3) == (-1, -2)`
* `(1, -2) + (2, 3) == (3, 1)`

**Comment by magnus-madsen** [comment]
I am not sure if this is a good idea. Adding too many TC instances can also lead to subtle bugs.

**Comment by JonathanStarup** [comment]
It could be nice though to do linear algebra on pairs/triples etc. (with the short syntax)

**Comment by magnus-madsen** [comment]
I don't think we should provide these instances, but a library is free to add them.
