### ISSUE TITLE
Re-Engineer Channels

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4755]
This ticket supersedes previous tickets.

- [x] Merge #4738
- [x] Add `$CHANNEL_GET(exp)$` to internal syntax (see e.g. `$INT32_ADD$`). Use in `Channel.recv`.
- [x] Add `$CHANNEL_PUT(exp1, exp2)$` to internal syntax. Use in `Channel.send`.
- [x] Add `$CHANNEL_NEW(exp)` to internal syntax. Use in `Channel.{buffered,unbuffered}`.
- [x] Remove surface syntax `chan`
- [x] Remove surface syntax `<- exp` and replace by `Channel.recv(exp)` everywhere (library, tests...)
- [x] Remove surface syntax `exp1 <- exp2` and replace by `Channel.send(exp2, exp1)` everywhere (library, tests...)
- [x] Split the type `Channel[t]` into `Sender[t]` and `Receiver[t]`. Drop `Channel[t]`.
- [x] Support sub-millisecond sleep in `Thread.sleep`.
- [x] Update documentation.
- [x] Remove channel code downstream of `Lowering`.
- [x] Remove old channel code in `runtime/interpreter`.
- [x] Remove `MonoType.Channel` (if possible?)
- [x] Investigate if `elmType` can be dropped from `ChannelNew` expression
- [x] Update select syntax to `case x <- recv(exp)` (and optionally `case x <- Channel.recv(exp)`).
- [x] Decide if `recv` and `send` should have keyword status in VSCode
- [x] #4845
- [x] #4846
- [x] #4847
- [x] #4848
- [x] Rename `Immutable` to `Sendable`. 
- [x] Figure out where to check instances of `Imm`
- [x] #4850

Later (requires other things to progress):
- [ ] What effect should spawn have?

**Comment by paulbutcher** [comment]
Also: remove channel code downstream of Lowering (made unnecessary by https://github.com/flix/flix/pull/4738

**Comment by paulbutcher** [comment]
Grr, and as I've just discovered, we also need to rewrite the `par` code which is creating old-style channel ASTs during lowering 😟

**Comment by paulbutcher** [comment]
We seem to have lost the suggestion of changing the channel creation syntax to `Channel.bounded` or `Channel.unbounded`?

(although, thinking about it, perhaps `Channel.buffered` and `Channel.unbuffered` would be better?)

**Comment by paulbutcher** [comment]
(or is the intent that `chan Int32 10` returns a pair?)

**Comment by magnus-madsen** [comment]
It returns a pair, like on rust 🙂

**Comment by magnus-madsen** [comment]
And indeed I used the words `buffered` and `unbuffered`.

**Comment by paulbutcher** [comment]
> And indeed I used the words `buffered` and `unbuffered`.

Ah yes, sorry that I missed the switch.

Are we still planning to do this, as I don't see it in the list of tasks above?

**Comment by magnus-madsen** [comment]
> Are we still planning to do this, as I don't see it in the list of tasks above?

Yep, I added it to the list.

**Comment by paulbutcher** [comment]
Regarding "Add CHANNEL_NEW(exp) to internal syntax", this requires type information, but `ParsedAst.Expression.Intrinsic` doesn't include any type information.

Is there some way that I can get hold of it as things stand? Or should I extend `ParsedAst.Expression.Intrinsic` to include type information? Or take some other approach?

**Comment by paulbutcher** [comment]
> Regarding "Add CHANNEL_NEW(exp) to internal syntax", this requires type information, but `ParsedAst.Expression.Intrinsic` doesn't include any type information.
> 
> Is there some way that I can get hold of it as things stand? Or should I extend `ParsedAst.Expression.Intrinsic` to include type information? Or take some other approach?

@magnus-madsen any thoughts on this?

**Comment by magnus-madsen** [comment]
> > Regarding "Add CHANNEL_NEW(exp) to internal syntax", this requires type information, but `ParsedAst.Expression.Intrinsic` doesn't include any type information.
> > Is there some way that I can get hold of it as things stand? Or should I extend `ParsedAst.Expression.Intrinsic` to include type information? Or take some other approach?
> 
> @magnus-madsen any thoughts on this?

I think- we should start by changing NewChannel to not carry any type information. This could be a separate PR.

Everything should still work without a specific type. 

(The smart way would be to leave ParsedAst.Expression.NewChannel as-is, but change WeededAst.Expression.NewChannel to longer carry a type and modify the remaining ASTs the same way).

**Comment by magnus-madsen** [comment]
If you get stuck on the above, let me know, and I can make an attempt.

**Comment by paulbutcher** [comment]
Regarding "", I've tried changing `Thread.sleep` to:

```
    pub def sleep(d: Duration): Unit \ IO =
        import static java.lang.Thread.sleep(Int64, Int32): Unit \ IO as jsleep;
        let Duration(nsTotal) = d;
        let ms = nsTotal / 1_000_000i64;
        let ns: Int32 = Int64.clampToInt32(min = 0, max = 1_000_000, nsTotal mod 1_000_000i64);
        jsleep(ms, ns)
```

But this results in all of our LibMin tests failing 😟

Any suggestions for how to best proceed?

**Comment by magnus-madsen** [comment]
Failing for what reason?

**Comment by paulbutcher** [comment]
Int64.clampToInt32 isn't available with LibMin.

**Comment by magnus-madsen** [comment]
> Int64.clampToInt32 isn't available with LibMin.

Can we just inline that functionality or not?

**Comment by paulbutcher** [comment]
> Can we just inline that functionality or not?

That works (and, thinking about it, is probably better: there's no need to do the clamping in this case because we know the value will fit into an Int32).

**Comment by paulbutcher** [comment]
@magnus-madsen regarding:

> Investigate if elmType can be dropped from ChannelNew expression

I looked pretty hard at this and couldn't see a way to do so: do you have some insight that I don't?

**Comment by paulbutcher** [comment]
@magnus-madsen regarding:

> Remove MonoType.Channel (if possible?)

The problem is caused by this test:

```
    @test
    def testNullChannel01(): Receiver[String] = null as Receiver[String]
```

I assume it's the cast that causes the problem, but I'm still not sure why that means that it makes it through to the finalizer? Suggestions welcome.

**Comment by paulbutcher** [comment]
Ah! Found it: we weren't calling `visitType` in the `Expression.Null` case in the lowerer.

**Comment by magnus-madsen** [comment]
> @magnus-madsen regarding:
> 
> > Investigate if elmType can be dropped from ChannelNew expression
> 
> I looked pretty hard at this and couldn't see a way to do so: do you have some insight that I don't?

Can you remind me where we use the elmType?

**Comment by paulbutcher** [comment]
It's used as follows:

1. We create it as a `Type.freshVar` in the kinder to enable the type to be inferred
2. We use it in the typer to create a `Sender` and `Receiver` of the right type
3. We use it during lowering to create a channel variable of the right type.

**Comment by magnus-madsen** [comment]
> It's used as follows:
> 
>     1. We create it as a `Type.freshVar` in the kinder to enable the type to be inferred
> 
>     2. We use it in the typer to create a `Sender` and `Receiver` of the right type
> 
>     3. We use it during lowering to create a channel variable of the right type.

Gotcha. I think we can do the following:

In `Lowering` we know that a channel must have type `Sender[t]` or `Receiver[t]`. Thus it is safe to write a function like:

```
def getChannelElmType(t: Tpe): Type = ... match here... throw exception if not Sender or Receiver.
```

(I believe we had such code earlier). 

The only sticking point is that we _must_ call `Type.eraseAliases` before the pattern match (because the programmer could be using a type alias).

**Comment by paulbutcher** [comment]
OK, got you. I did consider that, but:

1. It doesn't allow us to get rid of `elmTpe` entirely (it's still necessary in the `TypedAst`)
2. The type isn't either `Sender[t]` or `Receiver[t]`, it's `(Sender[t], Receiver[t])`. I could drag the type out of that, but it's pretty deeply nested and it felt like the cure being worse than the disease.

Happy to revisit if you think it's the right thing to do though. Let me know.

**Comment by paulbutcher** [comment]
@magnus-madsen, I think the "Update select syntax to case x <- recv(exp) (and optionally case x <- Channel.recv(exp))." can be considered done?

And, let me know what you would like me to do about "Investigate if elmType can be dropped from ChannelNew expression" (see comment above).

**Comment by magnus-madsen** [comment]
> @magnus-madsen, I think the "Update select syntax to case x <- recv(exp) (and optionally case x <- Channel.recv(exp))." can be considered done?

Yes! and thanks :)

**Comment by magnus-madsen** [comment]
OK; we keep `elmType`.

**Comment by paulbutcher** [comment]
Oh, I think "Update documentation." is also done,  yes?

**Comment by paulbutcher** [comment]
Can I check what the proposal is? Are we suggesting:

1. That we rename `Immutable` to `Sendable` but keep things exactly the same otherwise (i.e. nothing that takes a region parameter can be `Sendable`)? Or
2. That we rename `Immutable` to `Sendable` and special-case some non-immutable types (most obviously channels) so that they are `Sendable`)?

**Comment by magnus-madsen** [comment]
1. Rename `Immutable` to `Sendable`.

(Later we can expand on what `Sendable` allows.)

**Comment by magnus-madsen** [comment]
I think `Sendable` should mean "can be passed to `send`" (and would correspond to Rust's `Send`)

**Comment by paulbutcher** [comment]
On that basis then yes, I agree that we should rename it 👍

**Comment by paulbutcher** [comment]
Regarding the problem of being able to write `instance Immutable[Array[...]]`, I propose that I move the check for region kinded type parameters from deriver to safety (where we can check all instances). 

Are there other options we should be considering?

**Comment by magnus-madsen** [comment]
> Regarding the problem of being able to write `instance Immutable[Array[...]]`, I propose that I move the check for region kinded type parameters from deriver to safety (where we can check all instances).

I think that is what we should do. Move it there or have it in both places.

**Comment by magnus-madsen** [comment]
Two tasks left:

- Do we want color for send and recv in VSCode (or are they just functions) (But not in select? confusing).
- I think we should add special error message for missing `Sendable` instance.

**Comment by paulbutcher** [comment]
> * Do we want color for send and recv in VSCode (or are they just functions) (But not in select? confusing).

I don't feel massively strongly about this, but I would probably treat them as simple functions (and I don't think it would be particularly confusing to do so).
