### ISSUE TITLE
Re-Engineer Array Syntax

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#4760]
It's easier to write array literals than list literals, which (wrongly, I think) pushes users towards arrays for ease of use.

| Operation | Array | List |
| --- | --- | --- |
| empty | `[] @ r` | `Nil` |
| singleton | `[k] @ r`| `k :: Nil` |
| handful | `[a, b, c, d] @ r` | `a :: b :: c :: d :: Nil` |
| repeated* | `[k; n]` | `List.repeat` |
| slice* | `arr[1 .. 2]` | `List.slice` |
| nth* | `arr[i]` | not available |
| length | `arr.length` | `List.length` |

1. I think that it's weird that these unsafe array operations are so readily available
2. I think that it's weird that List and Array do not have the same syntax support (functional first?)
3. I think that `List.nth` should exist. I know the `argument not to include it, but there are times when "lookup index `i` in linear time" is what they want, and it feels weird to force people to implement it themselves.

Proposed actions (from least to most controversial)
- [ ] Remove `[k; n]` syntax (`Array.repeat` already exists)
- [ ] Remove `arr[1 .. 2]` syntax (`Array.slice` already exists)
- [ ] Add `List#{a, b, c}` syntax like Map/Set
- [ ] Remove `arr.length`
- [ ] Add `List.nth`
- [ ] Remove `arr[i]` syntax (`Array.nth` already exists)

**Comment by mlutze** [comment]
I think we may still want an `unsafeGet` function for arrays. The main reason for using arrays is their speed, so a user should be able to opt into the possibility of OOB errors.

We do ultimately need some syntax to express these operations in the source code (otherwise how do we implement the `Array.get` in the standard library?) but hiding them behind a syntax like `$ArrayGet$(i, a)` is doable.

One thing to add to your table: `x.length` is a special syntax for arrays and it means that we cannot have a record with a field called `length`.

**Comment by magnus-madsen** [comment]
Overall I agree 👍 

I think we should have vectors (which are exactly like arrays, but immutable). They could probably have some of this syntax.

**Comment by magnus-madsen** [comment]
I think we can easily begin with:

- [ ] Replace `[k; n]` by `$ARRAY_REPEAT$` and `Array.repeat` 
- [ ] Replace `a[i..j]` by `$ARRAY_SLICE$` and `Array.slice` 

(The test cases would use `$ARRAY_REPEAT$` and `$ARRAY_SLICE$`

(Separately: Maybe our repeat functions should be called fill?)

**Comment by magnus-madsen** [comment]
> > `$ARRAY_REPEAT$` and `$ARRAY_SLICE$`
> 
> Do they have to be builtin? The backend calls a couple java functions, so couldn't we just move the implementation to the flix code?

Is there not something with the types? or?

**Comment by magnus-madsen** [comment]
Ultimately float arrays and string arrays should not be the same.

**Comment by JonathanStarup** [comment]
they both just need to case on the type (primites + non-primitive)

**Comment by magnus-madsen** [comment]
@jaschdoc 

I think you can take a stab at:

- [ ] Replace `[k; n]` by `$ARRAY_REPEAT$` and `Array.repeat` 
- [ ] Replace `a[i..j]` by `$ARRAY_SLICE$` and `Array.slice`

**Comment by magnus-madsen** [comment]
Later, we can try to implement both functions as non-primitives using type match!

**Comment by magnus-madsen** [comment]
-[ ] Rework `[...]` literals to `Array#{...} @ r` literals.

**Comment by jaschdoc** [comment]
Copy that

**Comment by mlutze** [comment]
If that's not already done, we should probably mark the crashable functions as `unsafe`.

**Comment by jaschdoc** [comment]
# Work list

- [x] Replace `[k; n]` by `$ARRAY_REPEAT$` and `Array.repeat`
- [x] Replace `a[i..j]` by `$ARRAY_SLICE$` and `Array.slice`
- [ ] Rework `[...]` literals to `Array#{...} @ r` literals
- [ ] Rework `arr[idx]` to `Array.get`
- [ ] Rework `arr[idx] = exp` to `Array.put`
