### ISSUE TITLE
Refactorings post merge of `typematch`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4773]
- [x] Rewrite `stringify` to use `typematch`
- [x] Rewrite `reifyEff` uses in the standard library to use `typematch`.
- [x] Remove `Reify` expression from compiler.
- [x] Remove `ReifyType` expression from compiler.
- [x] Remove `ReifyEff` expressiom from compiler.
- [x] Remove `ReifiedBool` from Prelude.
- [x] Remove `ReifiedType` from Prelude.
- [x] Add `typematch` keyword to VSCode.
- [x] Remove `default` keyword from VSCode.
- [x] https://github.com/flix/flix/issues/4772
- [x] https://github.com/flix/flix/issues/4726
- [x] https://github.com/flix/flix/issues/4727
- [x] Add tests for reflection on records and Datalog values.
- [x] https://github.com/flix/flix/issues/2428
- [ ] Reject type match for Channel and Schema types (they are lost).

**Comment by JonathanStarup** [comment]
- [ ] Remove Boxable

**Comment by magnus-madsen** [comment]
Can we remove Boxable?

**Comment by JonathanStarup** [comment]
with match type can't you implement `def box(x: a): Boxed` and `def unbox(b: Boxed): a` instead of relying on the `Boxable` type class?

**Comment by magnus-madsen** [comment]
> with match type can't you implement `def box(x: a): Boxed` and `def unbox(b: Boxed): a` instead of relying on the `Boxable` type class?

What happens to the Eq-Order constraints? That's the issue I think.

**Comment by JonathanStarup** [comment]
> What happens to the Eq-Order constraints? That's the issue I think.

Ah yes, `def box(x: a): Boxed with Order[a], Eq[a]` and `def unbox(b: Boxed): a`

**Comment by JonathanStarup** [comment]
Oh I see. I wasn't aware of that issue. Is this hard to solve or is it "just" a matter of passing the correct information along? Could the typer/monomorpher stash the needed information in the AST node?

**Comment by mlutze** [comment]
Note about replacing reifyBool:

```
typematch ((x, y) -> {println(x); println(y)}) {
    case f: _ -> _ \ {} => true
    case f: _ => false
}
```

Returns `true` because of pure currying.

**Comment by mlutze** [comment]
Also, `default` does not seem doable via typematch. What do we match on?

**Comment by JonathanStarup** [comment]
> Also, `default` does not seem doable via typematch. What do we match on?

the return type?

**Comment by magnus-madsen** [comment]
> Note about replacing reifyBool:
> 
> ```
> typematch ((x, y) -> {println(x); println(y)}) {
>     case f: _ -> _ \ {} => true
>     case f: _ => false
> }
> ```
> 
> Returns `true` because of pure currying.

Yes, but if you write out the whole function its fine, right?

**Comment by magnus-madsen** [comment]
> Also, `default` does not seem doable via typematch. What do we match on?

Indeed yes. Does that mean we actually need two constructs? :(

**Comment by magnus-madsen** [comment]
> > Also, `default` does not seem doable via typematch. What do we match on?
> 
> the return type? oh typematch operates on values. I was under the belief it would be on types.

It matches on the types (but from a value) and it binds that value to a new variable with a more specific type.

**Comment by mlutze** [comment]
We have added `Proxy[_]` which allows for matching on arbitrary types, even without a witness value. This should allow implementation of a `default` function.

**Comment by magnus-madsen** [comment]
@mlutze Just missing my tests? :P

**Comment by magnus-madsen** [comment]
Updated TODOs.
