### ISSUE TITLE
Two issues from the ProgAnalysis Course

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4783]
- Patterns in the body of rules.
- Closed rows as arguments.

**Comment by JonathanStarup** [comment]
Patterns in bodies would be nice, but even beyond that, it would nice with partial matches in rules like `A(x) :- B(Some(x))` where the rule only applies if there is a match

**Comment by magnus-madsen** [comment]
Unfortunately its tricky to implement.

**Comment by magnus-madsen** [comment]
Fixed in master.
