### ISSUE TITLE
Discussion on the implicit region of methods like `NS.iterator`.

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#4792]
A function like `MutList.iterator` takes no region argument. This seems fine and doesn't feel like it disallows programs (why not use the existing region?) but i had this example.
```scala
/// Starts from 1 char and gets longer and longer.
def prefixes(r: Region[r], s: String): Iterator[String, r] = region r1 {
  let sb = new StringBuilder(r1);
  let pfs = new MutList(r1);
  foreach(c <- String.iterator(r, s)) {
    StringBuilder.append!(c, sb);
    MutList.push!(StringBuilder.toString(sb), pfs)
  };
  MutList.iterator(pfs)
}
```
First observation: A type error occurs because `r1` escapes its scope in the last line. The reason I made `r1` in the first place is because I want the compiler to aid me in my intention of not leaking `sb` and `pfs`.

I think this is a nice way to use regions which really takes advantage of explicit regions. It does however have different needs compared to using regions "by need" (omitting `r1`) where you just want the path of least resistance.

I wanted to highlight this optional way of using regions and the fact that this way of coding is not really supported with functions that only use their parent region. The only way out here would be to make the mutlist into something immutable and then into an iterator.

**Comment by magnus-madsen** [comment]
Interesting observations. The question is then: Should all "allocators" be given a region or just some?

**Comment by magnus-madsen** [comment]
What's your proposal? That "some" functions  should not reuse their region? All functions?

**Comment by JonathanStarup** [comment]
> What's your proposal? That "some" functions  should not reuse their region? All functions?

I think, just considering this use case, it should be all functions. The problem is that there is no way out if there isnt (without runtime cost).

A side benefit is that iterator functions on mutable/immutable data will be aligned.

**Comment by magnus-madsen** [comment]
Perhaps what we really want (though maybe I don't like it) is:

- Every function that does allocation must take a region.
- Add support for implicit parameters (to regions can be passed implicitly by the compiler).
- Add support for a form of default arguments where if no region is in scope, we re-use the region of the receiver object.

**Comment by JonathanStarup** [comment]
> Perhaps what we really want (though maybe I don't like it) is:
> 
> - Every function that does allocation must take a region.
> - Add support for implicit parameters (to regions can be passed implicitly by the compiler).
> - Add support for a form of default arguments where if no region is in scope, we re-use the region of the receiver object.

some of these things does feel more natural in a world where regions are just type parameters and you can optionally apply a type to the call.

**Comment by magnus-madsen** [comment]
> some of these things does feel more natural in a world where regions are just type parameters and you can optionally apply a type to the call.

But in the ideal world, we would always infer such types.

**Comment by magnus-madsen** [comment]
@JonathanStarup Can you try to come up with a list of functions that you would like to take an extra region parameter? (no urgency on this).

**Comment by JonathanStarup** [comment]
> > some of these things does feel more natural in a world where regions are just type parameters and you can optionally apply a type to the call.
> 
> But in the ideal world, we would always infer such types.

Isn't it hard in this case? I specifically want to assign a region which makes the program untyped, even though a region exists which makes the program welltyped.

**Comment by magnus-madsen** [comment]
I was looking at your example again, but now I feel less sure its legit.

The iterator is over the mutable list. Hence you would expect reading from the iterator would have an effect in the mutable list. This seems to be what you propose to avoid, but I am not sure that would be sound. 

I think iterator could have the signature:

```
def iter(reg: Region[r1], l: MutList[t, r2]): Iterator[t, r1 and r2])
```

but then you would immediately be "hit" with r2 escapes its scope.

**Comment by magnus-madsen** [comment]
Today it takes an iterator.
