### ISSUE TITLE
Rename `namespace` to `mod`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4800]
Proposal to rename the `namespace` keyword to `mod`:

Potential advantages:

- [ ] The `mod` keyword is 3 chars wide which is a design goal for keywords.
- [ ] The `mod` keyword would be familiar to Rust users now that we are moving towards a namespace mechanism close to theirs.

Disadvantages:

- [ ] Breaking change for no real reason (bike shedding).
- [ ] We use the word module for what is not "really" a modular in the academic PL sense (see e.g. ML modules).

We can make the change incrementally (i.e. allow both `namespace` and `mod` for a while).

In terms of terminology, we would write:

```
mod A/B/C {
  pub def f(): Int32=...
}
```

then the entire listing is a "module" whereas "A/B/C" is the "namespace of the module". I think such terminology would be useful.

**Comment by paulbutcher** [comment]
If we just want to make it shorter, we could go with `ns`? (modulo similar comments about bikeshedding)

**Comment by magnus-madsen** [comment]
> If we just want to make it shorter, we could go with `ns`? (modulo similar comments about bikeshedding)

Thought about it earlier: Two things:

- We like 3 letter keywords (because they equal 4 spaces with 1 space).
- I like the idea of being able to say `mod A/B/C { }` defines a module (the content) in the namespace `A/B/C`. If we use the keyword `ns` its less clear whether namespace refers to the name `A/B/C` or its content.

**Comment by magnus-madsen** [comment]
@mlutze @JonathanStarup Like it or hate it or no opinion?

**Comment by mlutze** [comment]
Neutral :)

**Comment by JonathanStarup** [comment]
Note that we already have `12 mod 2` (not that's it's close conceptually or syntactically)

**Comment by magnus-madsen** [comment]
We will change to `mod` as part of the other changes.

**Comment by magnus-madsen** [comment]
We need to rename `namespace X/Y/Z` to `mod X.Y.Z` everywhere.
We should also update any uses.

**Comment by magnus-madsen** [comment]
@jaschdoc The goal is to replace `namespace X/Y/Z` by `mod X.Y.Z` in the Flix Standard Library.

According to @mlutze this should just work (TM).
