### ISSUE TITLE
Less friendly `null`

### ISSUE THREAD

**Issue by mlutze** [flix/flix#4803]
Currently `null` is a proper keyword in Flix, which gives the wrong impression that it is a well-behaved citizen. I propose we change this to `$Null$` or something less nice.

**Comment by JonathanStarup** [comment]
I think it is intended for use if youre doing java interop though. for those people it might be too unfriendly

**Comment by magnus-madsen** [comment]
`null` is already unfriendly in that you have to cast.

**Comment by magnus-madsen** [comment]
I think for interop anything other than `null` would be confusing. The fact that it has its own type seems useful.
