### ISSUE TITLE
Remove all uses of `Try` from the compiler. Inspect all uses of `try-catch` to ensure no unintended exceptions are caught

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4822]

**Comment by magnus-madsen** [comment]
@mlutze Will you do a search for `Try`. I can we can leave the exception stuff for later.

**Comment by mlutze** [comment]
There are no uses of `Try`. There is one use of `Using`, which shares some semantics, but getting rid of it would mean replacing it with a `finally`, which is ugly
