### ISSUE TITLE
Add ascription to the new expression

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#4839]
`let x = new ThisThingHereIsIgnoredAndshouldBeAnAscription(r)`

**Comment by magnus-madsen** [comment]
I think we need to re-think new perhaps?

**Comment by JonathanStarup** [comment]
Shouldn't it just be `new Something(r)` -> `(Newable.new(): Something[_])` (if you can find the arity of the type

**Comment by magnus-madsen** [comment]
It could be, but I am not sure.

**Comment by magnus-madsen** [comment]
It could also be:

`new Something(r) -> Something.new(r)`

Thus it is a call to a specifically named method in a namespace.

(We could still retain the `Newable` TC for other use cases.)

**Comment by magnus-madsen** [comment]
We are dropping `New` and `Newable`.
