### ISSUE TITLE
Require `Imm` instance for `Channel.send` and `Channel.recv`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4846]
- [ ] Modify the signature of `Channel.send` to require an `Imm[t]` instance.
- [x] ~Modify the signature of `Channel.recv` to require an `Imm[t]` instance.~

This ensures that channels can only be used for immutable message passing; we cannot share mutable data, hence we cannot have data races. (This is strictly not true yet, because a spawn expression could close over a shared mutable data structure-- this we have to resolve).

**Comment by magnus-madsen** [comment]
@mlutze Do we want to enforce this for `NEW_CHANNEL` or do you think doing it in the library is sufficient?
@mlutze Is it right that marker type class have no compile/runtime representation? They are simply erased?

**Comment by magnus-madsen** [comment]
@paulbutcher @mlutze Is it actually sufficient to enforce `Imm` for `send`? (What does the signature of recv need?)

**Comment by mlutze** [comment]
> @mlutze Do we want to enforce this for `NEW_CHANNEL` or do you think doing it in the library is sufficient? 

I think the library is sufficient. We already have some unsafe "raw" expressions like `DIV`, and this gives us room to hack in the std lib if we know what we're doing is safe.

> @mlutze Is it right that marker type class have no compile/runtime representation? They are simply erased?

Correct.

> @paulbutcher @mlutze Is it actually sufficient to enforce Imm for send? (What does the signature of recv need?)

Sufficient, yes, probably. But isn't it better for the user to have it on both, just to have full information?

**Comment by magnus-madsen** [comment]
> Sufficient, yes, probably. But isn't it better for the user to have it on both, just to have full information?

Let's say that `recv` lacks `Imm` would that mean you could not do `recv` followed by `send`?

**Comment by mlutze** [comment]
> > Sufficient, yes, probably. But isn't it better for the user to have it on both, just to have full information?
> 
> Let's say that `recv` lacks `Imm` would that mean you could not do `recv` followed by `send`?

No. Either way, the constraints on the overall expression would be the same: `Imm[a]`, whether that comes from both or just `send`.

**Comment by magnus-madsen** [comment]
What about function signatures and error messages?

**Comment by mlutze** [comment]
The only place it matters is when you have a `recv` in a function without a `send`. Then we get error messages like

```scala
pub def recv45Things(): List[a] {
    ... recv(myChan()): a ...
}
```
"Ah you forgot that `a` needs to be immutable!"

So we have to throw the `Imm` constraint on it.

```scala
pub def recv45Things(): List[a] with Imm[a] {
    ... recv(myChan()): a ...
}
```

Overall I think this is nice as it provides a bit of extra documentation. But I can also see the other side of the argument: extra typing :)

**Comment by magnus-madsen** [comment]
In my mind your example proves the opposite point: Receiving should not require any specific knowledge. Doing so just means there is more typing for no gain (?)

**Comment by paulbutcher** [comment]
Presumably we should also require it for `Channel.buffered` and `Channel.unbuffered`?

**Comment by magnus-madsen** [comment]
> Presumably we should also require it for `Channel.buffered` and `Channel.unbuffered`?

We could. The question here is that: should we have (unnecessary) constraints that (1) give errors earlier but (2) makes code more cumbersome to write?

**Comment by magnus-madsen** [comment]
Conceptually it is really only the "send" operation that is dangerous.

**Comment by paulbutcher** [comment]
Understood, but it seems wrong to allow `Channel.buffered` to create a channel that could never be used?

**Comment by magnus-madsen** [comment]
> Understood, but it seems wrong to allow `Channel.buffered` to create a channel that could never be used?

Indeed. So maybe that's the argument.

**Comment by magnus-madsen** [comment]
So we add it to `buffered/unbuffered/send`, but what about `recv`?

**Comment by paulbutcher** [comment]
Just to make sure that I understand the problem we're trying to avoid: we're concerned that we would have to add `with Imm[t]` to a function that calls `Channel.recv` (and no other channel functions)? Is that it, or is there anything else?

**Comment by magnus-madsen** [comment]
And this is only if you write code that is generic over channels.

**Comment by paulbutcher** [comment]
Cool. In which case I don't have any strong feelings, but would be happy to leave it off `recv` (and also, I guess, `select`).

**Comment by magnus-madsen** [comment]
Since select is only in the compiler we would have to add the imm constraint there which is complex. Thus it might be better to leave it of recv and select.
