### ISSUE TITLE
Add a custom error message for missing instance of `Imm`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4847]
Add a specialized message for missing `Imm` instance. Like here:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Typer.scala#L297

**Comment by paulbutcher** [comment]
So this would be easy enough to do, but I'd like us to consider a few things before going ahead:

* The code and text for `MissingEq`, `MissingOrder`, and `MissingToString` are basically identical (just inserting different type class names where appropriate, plus a note about `Eq` being required for `Order`. Adding `Sendable` would increase this duplication further.
* We *almost* have a custom error message for each derivable type class (the only missing ones are `Boxable` and `Hash`. Wouldn't it make sense to have a custom error for each?

So, left to my own devices, I would amalgamate these all into a single `MissingDerivable` error which has a little code to customise the error messages as appropriate.

Thoughts?

**Comment by magnus-madsen** [comment]
I suggest to just add it: Then comes the task of writing better error messages, but that is now more easy, since the error is already special cased.
