### ISSUE TITLE
Add regioned random

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#4851]
Based on #3702 and discussion with @mlutze I'm convinced we should have a regioned, seeded(!),random datatype/namespace.

Reasoning: A random generator with a given seed is just a fancy iterator with a hash/noise function. If iterators can have regions then so can a random number generator.

Most of the time when you use a non-seeded random number (like a call to `List.shuffle` with a fresh `Random`), the only nondeterministic part is the seed. I think that we should only have a regioned random concept (no non-determinism) with a `def seed(): Int64 \ NonDet` function (which could be argued to be `IO` but maybe `NonDet` is a useful distinction).

For non-seeded random, you would call `Random.new(r, Random.seed())` which would have effect `{r, NonDet}`.

**Comment by magnus-madsen** [comment]
Do you think algebraic effects would be a potential solution? Then the handler could give you purity with a fixed seed?

**Comment by JonathanStarup** [comment]
I think both should exist. The effect operation random would have to be handled by something right?

**Comment by magnus-madsen** [comment]
> I think both should exist. The effect operation random would have to be handled by something right?

True, yes. (But you would not have to pass a random object).
