### ISSUE TITLE
List.foreach and others - nameclash?

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#4860]
As `foreach` is now used for comprehension syntax, should the `foreach` function on List and the other collections be renamed?

**Comment by mlutze** [comment]
We could change it to `forEach` to match the camel-case of our other functions. We could do the same with `forAll` since that's a keyword for laws.

**Comment by stephentetley** [comment]
`forEach` has precedent in the Java world so that would be a reasonable option.

**Comment by stephentetley** [comment]
If there is consensus for `forEach` and `forAll` for the functions I'm happy to make a PR...

**Comment by mlutze** [comment]
Let's ask @magnus-madsen to be certain.

**Comment by magnus-madsen** [comment]
The conflict is that we have both a keyword and a function with the same name?

If so, I am ok with forEach

**Comment by stephentetley** [comment]
> The conflict is that we have both a keyword and a function with the same name?

Yes `foreach` is now a keyword for comprehensions (`forall` which I would propose changing at the same time has been a keyword for a long time)..

**Comment by magnus-madsen** [comment]
Ok. This is agreeable to me.

**Comment by stephentetley** [comment]
PR submitted - #4868 to fix the function names.
