### ISSUE TITLE
Two issues with use imports

### ISSUE THREAD

**Issue by Daniel-Anker-Hermansen** [flix/flix#4880]
```
use Foo.NotBar

enum Foo {
    case Bar
}
```
typechecks and compiles but is nonsense. If you use NotBar you get ```>> Undefined tag 'NotBar'.``` where you attempted to use it.

```
use Foo.Bar.qux

namespace Foo {
    pub class Bar[t] {
        pub def qux(a: t): Unit
    }
}
```
gives the follwoing error ```>> Parse Error: Invalid input ".q", expected LegalLetter, UpperCaseName, ".{" or ';' (line 1, column 12):
use Foo.Bar.qux```
however
```
use Foo/Bar.qux

namespace Foo {
    pub class Bar[t] {
        pub def qux(a: t): Unit
    }
}
```
typechecks.

**Comment by JonathanStarup** [comment]
I think example two is sensible enough, you are accessing the `Bar` namespace so it should be delimited by `/`.

**Comment by Daniel-Anker-Hermansen** [comment]
but Bar is not a namespace and if I want to import the class I have to write:
```use Foo.Bar```
while
```use Foo/Bar```
gives an error.

**Comment by JonathanStarup** [comment]
My understanding is that `Bar` is both a class and a namespace
```
namespace Foo {
    pub class Bar[t] {
        pub def qux(a: t): Unit
    }
}


namespace Test {
    use Foo.Bar

    pub def barAsType(): t with Bar[t] = ???

    // this fails with `Undefined name 'Bar.qux'.`
    pub def barAsNamespace(): Unit = Bar.qux
}
```
So `Foo.Bar` is the class and `Foo/Bar` is the namespace. I'm not saying that its intuitive but I think it makes sense to some degree

**Comment by magnus-madsen** [comment]
We have recently reworked the namespace (now module) mechanism.
Hence this ticket is most likely no longer relevant.
Feel free to common and/or re-open if it is.
