### ISSUE TITLE
Enums cannot be `use`d in inner namespaces

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#4882]
In namespace `B` you cannot use `Enum` directly (`Undefined type 'Enum'.`) and you cannot `use` to introduce it (`Duplicate declaration 'Enum'.`)
```
namespace A {
    enum Enum { case Case }
    namespace B {
        use A.Enum
    }
}
```
```
namespace A {
    enum Enum { case Case }
    namespace B {
        type alias E = Enum
    }
}
```

**Comment by magnus-madsen** [comment]
We have recently reworked the namespace (now module) mechanism.
Hence this ticket is most likely no longer relevant.
Feel free to common and/or re-open if it is.
