### ISSUE TITLE
Bug: Classloader changes stop the compiler loading `java.sql` and potentially other Java SE classes

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#4898]
Paul's changes to the classloader in commit 2945605 (Oct 29) have had the unfortunate consequence that `java.sql` is no longer available to the Resolver stage of Flix's compiler.

While the Flix compiler can see external jars if you pass their path to the compiler through the packager looking in the `lib` directory or on the command line you can't do this for the SE classes as they are supplied with the JDK and are `.jmod` files in Java 9 and above.

To see the problem, create a new project and add the following code as a module in the `src` directory

~~~ 

/// Time.flix

namespace Interop/Sql {
    
    pub enum Time(##java.sql.Time)


}

namespace Interop/Sql/Time {

    use Interop/Sql.Time
    use Interop/Sql.Time.Time

    pub def mkTime(i: Int64): Time = 
        import new java.sql.Time(Int64): ##java.sql.Time \ {} as newTime;
        newTime(i) |> Time



}

~~~

Invoke with `java -jar flix.jar test` ...

~~~

-- Resolution Error -------------------------------------------------- E:\coding\flix\loader-test\src\Time.flix

>> Undefined Java class 'java.sql.Time'.

20 |     pub enum Time(##java.sql.Time)
                       ^^^^^^^^^^^^^^^
                       undefined class.

-- Resolution Error -------------------------------------------------- E:\coding\flix\loader-test\src\Time.flix

>> Undefined Java class 'java.sql.Time'.

31 |>         import new java.sql.Time(Int64): ##java.sql.Time \ {} as newTime;
32 |>         newTime(i) |> Time

undefined class.

-- Resolution Error -------------------------------------------------- E:\coding\flix\loader-test\src\Time.flix

>> Undefined Java class 'java.sql.Time'.

31 |         import new java.sql.Time(Int64): ##java.sql.Time \ {} as newTime;
                                              ^^^^^^^^^^^^^^^
                                              undefined class.
                                              
~~~                                               

Unfortunately this breaks my JDBC wrapper library.

**Comment by magnus-madsen** [comment]
Thanks Stephen,

Does it work if we remove the "null" class loaders? If so, I suggest that we do that until we can find a longer-term solution.

@paulbutcher Do you know why this is happening? I must admit I am now a bit confused about how these things work.

**Comment by magnus-madsen** [comment]
@stephentetley Does it work now? :)

**Comment by stephentetley** [comment]
Yes - no problems! Thanks
