### ISSUE TITLE
bug: adding region to test changes result

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#4917]
Why does the following test break when wrapping it in a region? The expressions within the regions should still have effects, right?
```flix
    @test
    def mapWithKey06(): Bool \ IO = // This passes
        let range = List.range(0, 2000);
        let m = List.zip(range, range) |> List.toMap;
        let a = new MutList(Static);
        discard Map.mapWithKey((k, v) -> { let b = new MutList(Static); MutList.push!(k, b); MutList.append!(MutList.toList(b), a); v }, m);
        MutList.toList(a) == range
```
i.e. changing to
```
    @test
    def mapWithKey06(): Bool = region r { // This fails
        let range = List.range(0, 2000);
        let m = List.zip(range, range) |> List.toMap;
        let a = new MutList(r);
        discard Map.mapWithKey((k, v) -> { let b = new MutList(r); MutList.push!(k, b); MutList.append!(MutList.toList(b), a); v }, m);
        MutList.toList(a) == range
    }
```

**Comment by jaschdoc** [comment]
There is no compilation error, just assertion error.
VSCode tells me that the lambda given to `mapWithKey` has type `Int32 -> (Int32 -> Int32 & r)` and that the discard expression has type `Unit & r`.
Using `let _ = Map.mapWithKey(...)` shows that the variable `_` has type `Map[Int32, Int32]`.
Thus `mapWithKey` proceeds to the parallel section and returns a list that isn't ordered.
Maybe the bug is with `reifyEff`?

**Comment by jaschdoc** [comment]
Here's an updated test that provides a bit more information:
```flix

    @test
    def mapWithKey06(): Bool = region r {
        let range = List.range(0, 2000);
        let m = List.zip(range, range) |> List.toMap;
        let a = new MutList(r);
        let f = (k, v) -> { let b = new MutList(r); MutList.push!(k, b); MutList.append!(MutList.toList(b), a); v };
        let _ =  Map.mapWithKey(f, m);
        Assert.eq(MutList.toList(a), range)
    }
```

**Comment by jaschdoc** [comment]
![Screenshot from 2022-11-14 16-31-09](https://user-images.githubusercontent.com/60233376/201700349-2e050e09-6066-4951-8fef-7c35dd06926a.png)
![Screenshot from 2022-11-14 16-31-34](https://user-images.githubusercontent.com/60233376/201700353-f3079eb1-7d77-48df-8c8c-3bed8f665afa.png)
![Screenshot from 2022-11-14 16-31-47](https://user-images.githubusercontent.com/60233376/201700354-1093ad21-5762-4ac6-b803-61911f6e769c.png)

**Comment by magnus-madsen** [comment]
I suspect either reifyEff or monomorphization is broken.

**Comment by magnus-madsen** [comment]
If I throw `print` into the `f` it seems to work.

**Comment by magnus-madsen** [comment]
Hm `flix.options.xstrictmono` gives me an exception :S

**Comment by magnus-madsen** [comment]
Well, at least I can confirm something is wrong.

**Comment by mlutze** [comment]
You can hover the three dots under `mapWithKey` and see that the hinter also thinks you should use parallel eval.

**Comment by magnus-madsen** [comment]
> > If I throw `print` into the `f` it seems to work.
> 
> Yes but that reintroduces `IO`, right? So the effect set is non-empty again. (The `& r` should also be a non-empty effect set, right? 🤔)

Yes, it was just for debugging.

**Comment by magnus-madsen** [comment]
I think the problem is that rigid scope variables gets instantiated to `true` instead of false.

**Comment by magnus-madsen** [comment]
I think this is wrong: https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala#L91

**Comment by mlutze** [comment]
> I think this is wrong: https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala#L91

That fixes it for me

**Comment by magnus-madsen** [comment]
> > I think this is wrong: https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala#L91
> 
> That fixes it for me

By doing what?

**Comment by mlutze** [comment]
Swapping True -> False

**Comment by mlutze** [comment]
> @mlutze Is there any way to tell if the variable is rigid? Should we preserve region until Monomorph?

No, but there is a `isRegion` parameter in TypeVarSym which we can use.

**Comment by magnus-madsen** [comment]
What about preserving region and then instantiating its variable to false.

I think that's the correct approach.

**Comment by magnus-madsen** [comment]
(Maybe its called scope internally)

**Comment by mlutze** [comment]
> What about preserving region and then instantiating its variable to false.
> 
> I think that's the correct approach.

Yes that seems appropriate.

**Comment by magnus-madsen** [comment]
@jaschdoc @mlutze 

@jaschdoc If you write 5 good tests and paste them here, I will ask Matt to fix the issue :)

**Comment by jaschdoc** [comment]
Alright, I'll come up with some tests :) I've prepared the std lib tests for now (#4921).
