### ISSUE TITLE
LSP: Hovering on function with effectful function parameter highlights rest of type as string

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#4919]
Hovering on
```flix
discard Map.mapWithKey((k, v) -> { let b = new MutList(r); MutList.push!(k, b); MutList.append!(MutList.toList(b), a); v }, m);
```
is highlighted as in the screenshot below (this is probably due to the effect named`ef'`):
![hover](https://user-images.githubusercontent.com/60233376/201698244-c7d36299-3155-4edc-94b0-06aabbf242fb.png)

**Comment by magnus-madsen** [comment]
Thanks. Indeed this will be fixed once we drop `'` from effects (which will happen eventually).
