### ISSUE TITLE
Rename `as` (i.e. cast) to something longer and more dangerously sounding?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4920]

**Comment by magnus-madsen** [comment]
Random proposal 1: `cast exp:type`
Random proposal 2: `unsafe_cast exp:type`.
Random proposal 2: `unchecked_cast exp:type`.

**Comment by mlutze** [comment]
The `:` makes parsing annoying I think since it collides with regular ascriptions

**Comment by magnus-madsen** [comment]
> The `:` makes parsing annoying I think since it collides with regular ascriptions

What if we pick whatever is lower than `Expression.Ascribe` that should work no?

**Comment by magnus-madsen** [comment]
Other than the underscore, I quiet like:

```
unsafe_cast 123: Int32
```

**Comment by mlutze** [comment]
```
123 dangerously Int32
```

**Comment by mlutze** [comment]
```
sudo 123: Int32
```

**Comment by JonathanStarup** [comment]
Another option is to use whatever syntax, but make it so that you get the same info thing as when you call a `@Unsafe` function

**Comment by magnus-madsen** [comment]
See https://github.com/flix/flix/issues/4939
