### ISSUE TITLE
LSP Server should not use null for root, but rather Option

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4934]

**Comment by magnus-madsen** [comment]
i.e. this https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala#L88

should become `Option[Root]`.

**Comment by jaschdoc** [comment]
Oops I linked this prematurely. This should still be open

**Comment by magnus-madsen** [comment]
@jaschdoc Can you list the providers that are left?

**Comment by magnus-madsen** [comment]
Nevermind, I got some new ideas.

**Comment by magnus-madsen** [comment]
I think once the frontend is more robust in the face of errors, we should only (some of) the providers if the AST is available.

**Comment by jaschdoc** [comment]
> @jaschdoc Can you list the providers that are left?

For the sake of completeness:
- [ ] ImplementationProvider
- [ ] RenameProvider
- [ ] SymbolProvider
- [ ] FindReferencesProvider
- [ ] SemanticTokensProvider
- [ ] InlayHintProvider
- [ ] ShowAstProvider

**Comment by magnus-madsen** [comment]
Fixed.
