### ISSUE TITLE
Namespace redesign

### ISSUE THREAD

**Issue by mlutze** [flix/flix#4935]
My proposed redesign of namespaces has some key principles:

1. Embracing companion namespaces
2. Single notation for `uses` (no `A/B/C.D`)
3. No conflicting declarations

To the end user, `uses` will always look like `use A.B.C.D.E`, and will always refer to a list of namespaces (`A.B.C.D.E`) followed by a specific symbol. This is the same as what we currently have, except:
1. We will use `.` instead of `/` to separate namespaces.
2. Enum cases will be in their parent enum's namespace, rather than being a special case.

For example:
```scala
namespace N {
    use E.C // need to import from the nested namespace
    
    def f(): E = E.C // or can just use from E
    
    pub enum E {
        case C
    }
}

namespace M {
    use N.E     // use the enum
    use N.E.C   // use the case
}
```

Note in particular that this becomes illegal:
```scala
namespace N {
    pub enum E {
        case C
    }

    namespace E { // this is ok: companion namespace for E
        enum C      // ERROR! conflicts with case C above
    }
}
```

"Embracing companion namespaces" means that:
1. Classes can use private functions from their companion namespaces.
2. Opaque enums can only be deconstructed from their companion namespaces.

**Comment by JonathanStarup** [comment]
1. In a world with namespace aliasing in the last example, what does `use N.E` mean? does it alias the namespace and import the enum?
2. With the unification of `/` and `.`. This means that enum cases and nested namespaces can collide right? Enum `E` with case `C` and its companion namespace with nested namespace `C`
3. Couldn't all of this be achieved without pulling `E` out of the namespace? A companion namespace could be a namespace `X` with enum `X` *inside* it, instead of enum `X` with namespace `X` *beside* it. In my eyes this introduces less special treatment (your last two points are achieved for free)

**Comment by mlutze** [comment]
> 1. In a world with namespace aliasing in the last example, what does `use N.E` mean? does it alias the namespace and import the enum?

Yes. So after `use N.E` you can do `E.myFunc` and `E.C`

>     2. With the unification of `/` and `.`. This means that enum cases and nested namespaces can collide right? Enum `E` with case `C` and its companion namespace with nested namespace `C`

Yes. But I think that's ok. Then we have a companion namespace for the Case (whatever that means).

>     3. Couldn't all of this be achieved without pulling `E` out of the namespace? A companion namespace could be a namespace `X` with enum `X` _inside_ it, instead of enum `X` with namespace `X` _beside_ it. In my eyes this introduces less special treatment (your last two points are achieved for free)

Yes, but I think the `use MyEnum.MyEnum` pattern is really ugly. "Beside" companion namespaces here also match the current behavior of type classes.

**Comment by JonathanStarup** [comment]
> Yes, but I think the use MyEnum.MyEnum pattern is really ugly. "Beside" companion namespaces here also match the current behavior of type classes.

I'm not saying I want to change any functionality, I kind of like the double import, but just syntactically change how a companion namespace looks, that the enum is inside the namespace. This way, the only thing "magic" about companion namespaces is that `MyEnum.MyEnum` is actually referred to as `MyEnum`. If we had export then all of this could be implemented by implicitly adding `export E` at the top of namespace `E` if it has an enum called `E`. Does that make sense?

**Comment by mlutze** [comment]
So you're saying that we do something like this:

```scala
namespace List {
    pub enum List[a] { ... } // linked to parent namespace
 
    pub def map(...) { ... }

    pub enum Something { ... } // not linked to parent namespace
}


namespace N {
    pub def f(): List[a]
    // use List without full path
}
```

It reminds me of a Java constructor. I'm not strongly opposed to this, but it would be nice for it to be consistent with classes:

```scala
namespace Eq {
    pub class Eq[a] {
        pub def eq(x: a, y: a): Bool = ???
    }

    pub def blah(): String = ...
}

namespace N {
    pub def asdf(x: a): String with Eq[a] = ???
}
```

So here `Eq` really means `Eq.Eq`.

**Comment by JonathanStarup** [comment]
Yeah I agree with that.

* I've realized `export` is not enough to implement companions (unless you allow `export` to merge namespaces).
* With the "inside" solution like your `List` example, `List.List` is a name that looks like it should exist but it doesn't

I feel less convinced about my own idea

**Comment by magnus-madsen** [comment]
Can we close this?

**Comment by mlutze** [comment]
Yeah I think we've mostly landed on something we can live with for now
