### ISSUE TITLE
Rework Casts

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4939]
- [ ] Remove `Prelude.upcast`.
- [x] Modify the syntax of `exp as Type` to `unsafe_cast exp: Type`.
- [x] Modify the syntax of `supercast(exp)` to `super_cast exp`.
- [x] Retain the syntax `upcast exp`.

**Comment by magnus-madsen** [comment]
@jaschdoc I would like to get this in place next. Let me know if you have questions.

**Comment by mlutze** [comment]
We do have one non-snake keyword: `typematch`

**Comment by magnus-madsen** [comment]
True

**Comment by jaschdoc** [comment]
> Remove `Prelude.upcast`

I think this may be harder than just removing it. We'd have to revert to using `unsafe_cast` instead of `upcast` most places, since the boolean formulas are rather complex and that's where we got stuck last time.

**Comment by magnus-madsen** [comment]
> > Remove `Prelude.upcast`
> 
> I think this may be harder than just removing it. We'd have to revert to using `unsafe_cast` instead of `upcast` most places, since the boolean formulas are rather complex and that's where we got stuck last time. So do we just go back to regular unsafe casts for this step?

I would like something very simple:

Given a pure function (possibly curried) then upcast should allow you to cast that to any function (no matter its effects), but with the same argument types.

**Comment by JonathanStarup** [comment]
sorry for the late objection, but i think `unsafeCast` or `unsafecast` is more flix-like. I also don't think it should be toooo hostile since you have to use it for effect subtyping that's not caught by `upcast`.

**Comment by mlutze** [comment]
Shouldn't all effect subtyping be caught by upcast?

**Comment by magnus-madsen** [comment]
We have:

- `super_cast` (underscore)
- `type alias` (space)
- `typematch` (nothing)

Anything we missed? Oh snakeCase.

**Comment by magnus-madsen** [comment]
> > Shouldn't all effect subtyping be caught by upcast?
> 
> if then, i dont see "valid" use of casting no

I don't understand what Matt and you are discussing :)

**Comment by JonathanStarup** [comment]
I often use casts for effect subtyping in foldleft and things like that, so it seems mean to me to make cast hostile if you must use it in some valid situations.

**Comment by JonathanStarup** [comment]
I needed to collect a list of functions, in which some of them printed to the terminal. Thus the pure functions needed to be impure. Upcast didn't work there because of polymorphism in the function type.

**Comment by magnus-madsen** [comment]
Can we rid ourselves of `upcast` in Prelude (or not yet?)

**Comment by jaschdoc** [comment]
> Can we rid ourselves of `upcast` in Prelude (or not yet?)

Not yet, not without handling purity formulas with more than one variable. Often `identity` is cast to something that has a rather complex boolean formula and that upcast is rejected when using the `upcast` expression (rather than the Prelude function)

**Comment by magnus-madsen** [comment]
Can we rework the `upcast` expression to work as follows: If the actual type is a totally pure function then there is no check for the effects?

**Comment by jaschdoc** [comment]
I think that would be reasonable. I'll take a stab at it.

**Comment by magnus-madsen** [comment]
My ultimate goal (if possible):

- Merge `upcast` and `supercast` as follows: We allow casting between two types following the Java subtype relation (dealing with co and contra-variance as needed for function types). On the effect side, we allow a totally pure function to be cast to an effectful function. (If the function is not pure then the both function types must have exactly the same effects).

**Comment by jaschdoc** [comment]
Hopefully, once https://github.com/flix/flix/pull/5007 is merged we can remove `upcast` from `Prelude`

**Comment by magnus-madsen** [comment]
Not yet done, still needs to remove `Prelude.upcast`.
