### ISSUE TITLE
Comment issue

### ISSUE THREAD

**Issue by athas** [flix/flix#4947]
I'm writing this function, which is commented according to established best practice:

```Flix
def inc1(x: Int32): Int32 \ {} =
  /* now add the number */
  x + 1
```

But then I wanted to try something else and commented out the function

```Flix
/*
def inc1(x: Int32): Int32 \ {} =
  /* now add the number */
  x + 1
*/
```

But this gives me a parse error.

**Comment by magnus-madsen** [comment]
Wait... Did you not write about this? 

Oh my. This is your favorite "hobby horse" https://futhark-lang.org/blog/2017-10-10-block-comments-are-a-bad-idea.html

**Comment by JonathanStarup** [comment]
I kind of like the idea of removing block comments, I also don't think we really use them?

> The only feature of block comments that cannot be replicated directly is inserting a comment in the middle of a line, but this is probably a niche usage.

I somethings use this to change `something(complicated, b, c)` into `something(??? /* complicated /*, b, c)` when doing type-error debugging
