### ISSUE TITLE
Add new type of expression hole

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4978]
Add a new expression: `ident?` to the grammar.

Here is the expected TypedAst:

```
case class HoleWithExp(exp: TypedAst.Expression, tpe: Type, pur: Type, eff: Type, loc: SourceLocation) extends TypedAst.Expression
```

Notably I skipped on the symbol and instead there is always an expression.

(This would also be a Var expression but we don't capture that-- so we can generalize later).

**Comment by JonathanStarup** [comment]
What does this look like? is it kind of the same as `let x: Output = input |> ???`

**Comment by magnus-madsen** [comment]
We have not decided yet, but we were thinking of `localVar?`.

**Comment by magnus-madsen** [comment]
This is to assist with auto-completion as you have been requesting :)

**Comment by JonathanStarup** [comment]
> We have not decided yet, but we were thinking of `localVar?`.

Maybe its more consistent use the existing `?` prefix to make these magic things more consistent. Maybe just use `?anything`. Or without breaking anything existing it could be `??anyhing`
