### ISSUE TITLE
Null casts should use `super_cast` not `unsafe_cast`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5002]

**Comment by magnus-madsen** [comment]
Searching for `unsafe_cast null` should be easy.

**Comment by mlutze** [comment]
I'm not sure about this. `super_cast` means "the compiler will check that what I am doing is safe"

**Comment by magnus-madsen** [comment]
> I'm not sure about this. `super_cast` means "the compiler will check that what I am doing is safe"

And its safe for any reference type? Or you mean, its not OK for Flix?

**Comment by mlutze** [comment]
Not OK for Flix IMO. Since in general, `String` means non-nullable String.
