### ISSUE TITLE
Idea for how to optimize `Substitution`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5004]
Change:

```
case class Substitution(m: Map[Symbol.KindedTypeVarSym, Type])
```

to

```
case class Substitution(m: Map[Symbol.KindedTypeVarSym, Type], trueVars: Set[Symbol.KindedTypeVarSym])
```

(as part of this refactoring, it might be useful make `Substitution` into a non-case class and to have some more constructors in the companion).

The hope is that keeping `trueVars` as a set separate from `m` will be speed-up the compiler. On the other hand, it does require some more booking in Substitution, but lets try it and see if it is worth it.

**Comment by magnus-madsen** [comment]
@mlutze Could be fun, want to give it a go?

**Comment by magnus-madsen** [comment]
@AnnaBlume99 has some time this week, so I will ask her to take a look.

**Comment by AnnaBlume99** [comment]
Can I have a bit more explanation of what trueVars represents and what to use it for?

**Comment by magnus-madsen** [comment]
In the map `m` there is a million of variables that are mapped to `true`.

I wonder if it would be more efficient to keep them in a separate set.

**Comment by magnus-madsen** [comment]
Try to print `m` (e.g. every time a Subst. is constructed.)
