### ISSUE TITLE
Bug: unable to run *any* Flix program due to new cast syntax

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#5008]
A fresh jar built from d6d49d3a8b57dda2fc046809723c008959aa636f cannot run a program since the hidden function that prints main hasn't been updated to use `unsafe_cast exp as Type`. However, when searching for ` as ` in the Flix compiler (this repo) all casts have been refactored to `unsafe_cast exp as Type` so I'm not sure where the missing case is.
```
     __   _   _
    / _| | | (_)            Welcome to Flix v0.34.0
   | |_  | |  _  __  __
   |  _| | | | | \ \/ /     Enter an expression to have it evaluated.
   | |   | | | |  >  <      Type ':help' for more information.
   |_|   |_| |_| /_/\_\     Type ':quit' or press 'ctrl + d' to exit.
      
flix> :eval main()                                                              
-- Parse Error -------------------------------------------------- <shell>       

>> Parse Error: Invalid input "as", expected '[', '.', ::, :::, ':', "without", Op, '`', <+>, **, *, /, mod, rem, +, -, <<<, >>> or <= (line 2, column 17):
println(main()) as \ IO
                ^

flix> 
```

**Comment by jaschdoc** [comment]
Maybe @JonathanStarup knows something about this?

**Comment by JonathanStarup** [comment]
Hmm I would guess the main wrapper maybe? Have you looked at lowering? @mlutze

**Comment by mlutze** [comment]
I'm guessing the shell creates the code.
It's not in the main wrapper since that manipulates the AST directly.

**Comment by magnus-madsen** [comment]
https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/runtime/shell/Shell.scala#L305

should be an easy fix

**Comment by jaschdoc** [comment]
> https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/runtime/shell/Shell.scala#L305
> 
> should be an easy fix

Hmm weird, I used the find in project function in IntelliJ and that didn't find it :o
