### ISSUE TITLE
Clarify `Chain/Nec.snoc`

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#5057]
`def snoc[a](c: Chain[a], x: a): Chain[a]`
Its fun but 1) its not an easy name to find without prior knowledge and 2) its not subject last

**Comment by mlutze** [comment]
I think we need some naming principles more broadly.

**Comment by JonathanStarup** [comment]
yeah 👍 the issue here is also the fact that `append` is conceptually overloaded

**Comment by magnus-madsen** [comment]
The `snoc` name is actually well-established. Its no different from `Cons`, where does that name come from?

**Comment by stephentetley** [comment]
`snoc` 's arg order is also well established, _but_ it still might be worth changing it to subject last.

Flix code often uses `|>` but we rarely use functions as operators even though we can. 

~~~

Chain.empty() `snoc` 1 `snoc` 2

~~~

... is probably not better than ...

~~~

Chain.empty() |> snoc(1) |> snoc(2)

~~~

... if the compiler inlines `|>`.

**Comment by mlutze** [comment]
What if we kept the canonical `snoc` but added an `addRight` or something like that?

**Comment by JonathanStarup** [comment]
I didn't know it was established, then I suppose its okay. But I think we should decide on one naming/ordering and implement it for list/mutlist etc.

**Comment by mlutze** [comment]
I think `snoc` is really is own thing though . To me it says "make a new structure with `x` added to the end in O(1) time". Other structures can't do that.
