### ISSUE TITLE
Introduce SemanticOperator

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#506]
We currently have a class `Operator` and `BinaryOperator`:

```
object BinaryOperator {

  case object Plus extends ArithmeticOperator

  ...
}
```

The problem with this approach is that `Plus` is overloaded. Is it plus on `Int32` or on `Float64`? Consequently, the backend relies on types to determine the meaning of an operator. It would be better to introduce a `SemanticOperator` like so:

```
sealed trait SemanticOperator

object SemanticOperator {

  object Int32 {
    case object Add extends SemanticOperator  
    case object Sub extends SemanticOperator  
  }

  object BigInt {
    case object Add extends SemanticOperator  
    case object Sub extends SemanticOperator  
   }

}
```

or similar.

**Comment by magnus-madsen** [comment]
@FlaminGuy 

I would like to make these changes incrementally. For example, I could introduce the changes above and then change the signature of:

```
    case class Binary(op: BinaryOperator, exp1: ExecutableAst.Expression, exp2: ExecutableAst.Expression, tpe: Type, loc: SourceLocation) extends ExecutableAst.Expression
```

to

```
    case class Binary(op: BinaryOperator, sop: SemanticOperator, exp1: ExecutableAst.Expression, exp2: ExecutableAst.Expression, tpe: Type, loc: SourceLocation) extends ExecutableAst.Expression
```

then you could do refactorings in the backend to rely on `sop` and once done we would move the `op` field of `Binary` (and `Unary`). 

Would that work?

**Comment by FlaminGuy** [comment]
sure, just push your changes to a new branch.

**Comment by magnus-madsen** [comment]
@FlaminGuy I have introduced the SemanticOperator. Will you make adjust to the backend, then I will make adjustments to the symbolic evaluator, and we can get rid of unary/binary operator in the backend.

**Comment by magnus-madsen** [comment]
Basically, the SemanticOperator replaces then need for inspecting types when generating code and should make the implementation more clean (and correct):

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/ast/SemanticOperator.scala

**Comment by mlutze** [comment]
Done?

**Comment by magnus-madsen** [comment]
Not, the backend still uses a mismatch of BinaryOperator and SemanticOperator.
