### ISSUE TITLE
`Ref.ref(r, e)` and `Ref.deref(r)`

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#5063]
Names should be something unreserved, but it would be nice for pipes/composition

**Comment by mlutze** [comment]
Maybe also ``Ref.transform`

**Comment by JonathanStarup** [comment]
> Maybe also ``Ref.transform`

like map?

**Comment by mlutze** [comment]
> > Maybe also ``Ref.transform`
> 
> like map?

Yes, `x := f(deref x)` vs `x |> transform(f)`

**Comment by magnus-madsen** [comment]
See https://github.com/flix/flix/issues/5194
