### ISSUE TITLE
Experiment with error recovery in the parser

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5065]
The program:

```
def main(): Unit \ IO = 
    let x = 123;
    
```

Does not parse and gives the error message:

```
❌ -- Parse Error -------------------------------------------------- file:///c%3A/tmp/flix/Main.flix

>> Parse Error: Unexpected end of input, expected UnaryOp1, UnaryOp2 or Ref (line 3, column 5):
```

What I would like to try is to write a wrapper around the parser that will run it. If it fails, it will extract the line, column, and expected input, and try to insert a token, and re-run the parser. It will be keep doing this until a clean parse happens or a timeout is reached.

For example, in the above, we could try to insert `()` unit at the parse error position.

On the other hand, for the program:

```
def main(): Unit \ IO = {
    let x = 123;
    x + 1
```

we would try to insert an `}`.

I am not sure how to "guess" what to insert, but we could have a collection of things like `}`, `)`, `()`, and so forth.

**Comment by magnus-madsen** [comment]
I have no idea if this will work well, but if it does, we can use it together with #5026 to make VSCode work for incomplete programs.

**Comment by JonathanStarup** [comment]
Wouldn't this run in `retries * parserTime`?

It could also be nice to catch extra `;` but because bindings doesn't have to be enclosed, this is difficult
```
def f(): Int32 =
    let x = 12;
    42;

def g(): Int32 = 12 
```
The error here is after 12 (<sub>I think we should require `{let ...}` but maybe that's just me</sub>)

**Comment by magnus-madsen** [comment]
> Wouldn't this run in retries * parserTime?

Worst case, yes. Hence that's why its an experiment :)

**Comment by JonathanStarup** [comment]
Maybe we can trigger behaviour based on the list of expected things / the parser position.

We could also experiment with cutpoints (on `def` fx) to try and optimize the parser

**Comment by magnus-madsen** [comment]
We are getting a new parser :)
