### ISSUE TITLE
Change syntax of `HoleWithExp` from `localvar?` to `localvar???`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5066]
- [ ] Change syntax to `localvar???`
- [ ] Allow arbitrary expression `exp???`?

**Comment by JonathanStarup** [comment]
Isn't `exp???` the same as `???(exp)` or `exp |> ???` and the autocomplete based on the function type of `???` instead of the type of `exp.tpe -> exp???.tpe`

**Comment by magnus-madsen** [comment]
I don't think `exp???` is generally syntactically valid?

**Comment by JonathanStarup** [comment]
No, I just felt like `???(exp)` is as good as `exp???` and that doesn't introduce new constructs

**Comment by magnus-madsen** [comment]
Oh I see, but does `???(exp)` actually get the job done?

**Comment by JonathanStarup** [comment]
What is the job? but it feels like `???(exp)` and `???(localVar)` should allow the same things as `exp???` and `localVar???`

**Comment by magnus-madsen** [comment]
What I mean is, I am not sure we/Daniel has implemented `???(exp)` to work as well as `localvar?`

**Comment by JonathanStarup** [comment]
Oh yeah I don't think ``???(exp)` helps but shouldn't it be able to use the existing code? I haven't looked at the implementation, so I'm sorry if I'm too presumptuous

**Comment by magnus-madsen** [comment]
I want to change the syntax to `localVar???` to free up the syntax to be used for `Result`.

**Comment by magnus-madsen** [comment]
@mlutze Ill ask you because you did the parser. I am not sure if any other changes are needed, but please do test.

What do we think of allowing it for arbitrary expressions?

**Comment by mlutze** [comment]
My fear for allowing it for arbitrary expressions is that we end up with a lot of code where the user is thinking of it like a pipeline but the code comes out as a big nest.

**Comment by mlutze** [comment]
So getting something similar working for pipelines would be a high priority  IMO

**Comment by JonathanStarup** [comment]
I agree with that, supporting "find function" on holes of function types would just allow `???(exp)`

**Comment by magnus-madsen** [comment]
Does this mean we need special parsing for `???(name)`?

Perhaps `???name` should also work?

**Comment by magnus-madsen** [comment]
Also, if we write `???(name)` when and where should the cursor be when once requests an auto-complete?

**Comment by JonathanStarup** [comment]
no no i like `???(name)` because it already exists, it just needs the autocomplete, which should always be after the hole `???|(name)` or if using pipe `name |> ???|` or wherever the hole. I don't think we need named holes

**Comment by magnus-madsen** [comment]
@JonathanStarup You can try to give it a go.

The starting point is here: https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala#L135
