### ISSUE TITLE
Disallow non-variable and non-constant patterns in body atoms

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5067]
The grammar for `TypedAst` for constraints has:

```
    sealed trait Body extends TypedAst.Predicate

    object Body {

      case class Atom(pred: Name.Pred, den: Denotation, polarity: Ast.Polarity, fixity: Ast.Fixity, terms: List[TypedAst.Pattern], tpe: Type, loc: SourceLocation) extends TypedAst.Predicate.Body

      case class Guard(exp: TypedAst.Expression, loc: SourceLocation) extends TypedAst.Predicate.Body

      case class Loop(varSyms: List[Symbol.VarSym], exp: TypedAst.Expression, loc: SourceLocation) extends TypedAst.Predicate.Body

    }
```

The safety phase should check that the `terms` passed to `Atom` are only variables and constants.

If not, it should emit a `SafetyError` saying that such patterns are not supported.

**Comment by magnus-madsen** [comment]
The right place to start is around here: https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Safety.scala#L539

**Comment by magnus-madsen** [comment]
The goal is to reject programs that contain constraints like:

```
A(x) :- B(Some(x)).
```

which currently crash the compiler.

**Comment by mlutze** [comment]
IMO this should be its own AST node rather than reusing pattern. Resolver is messy as a result of the reuse. See also https://github.com/flix/flix/issues/4854

**Comment by magnus-madsen** [comment]
@mlutze We want to allow patterns some day, we just dont have engine support yet. In that case, is it ok?

**Comment by mlutze** [comment]
> @mlutze We want to allow patterns some day, we just dont have engine support yet. In that case, is it ok?

Yes, in that case it's worth the slight weirdness in resolver.

**Comment by magnus-madsen** [comment]
@AStenbaek CC
