### ISSUE TITLE
Add `OpenSchema` expression

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5068]
Given the program:

```
def isCyclic(db: #{Edge(Int32, Int32)}): Bool = 
    let pr = #{
        Path(x, y) :- Edge(x, y).
        Path(x, z) :- Path(x, y), Edge(y, z).
    };
    not (query db, pr select () from Cycle() |> List.isEmpty)
```

We get the type error:

```
❌ -- Type Error --------------------------------------------------

>> Unable to unify the types: '#(  )' and '#( Path(Int32, Int32) | s0 )'.

6 |     not (query db, pr select () from Cycle() |> List.isEmpty)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             mismatched types.

Type One: #{ Edge(Int32, Int32) }
Type Two: #{ Edge(t0, t0), Path(t0, t0) | s1 }
```

because the argument `db` is a ***closed row***.

The type of `db` is `#{Edge = ... | {}}`. Notice that this type (which is like a list) ends in `{}`. The idea is for the compiler to change this to `#{Edge = ... | r}` for a fresh type variable `r`. This needs to happen around here:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Typer.scala#L305

where `getSubstFromParams` should open the rows.

Note that the transformation must ***only*** take place if there is a closed row.

**Comment by JonathanStarup** [comment]
> The type of g is [...]

by `g` do you mean `db`?

**Comment by magnus-madsen** [comment]
> > The type of g is [...]
> 
> by `g` do you mean `db`?

Fixed

**Comment by magnus-madsen** [comment]
Ill let Andreas take a crack at this.

**Comment by magnus-madsen** [comment]
@AStenbaek CC

**Comment by magnus-madsen** [comment]
Assigned to JLS because we need this for another project.

**Comment by magnus-madsen** [comment]
@stephentetley This feature might be useful to you...

**Comment by stephentetley** [comment]
Thanks Magnus, I must get back to using Datalog, last year I seemed caught up in other things.
