### ISSUE TITLE
Introduce Vals in addition to Defs

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#507]
Introduce a new syntactic construct:

```
val myConstant: Int = 42
```

which is a compile time constant that can be referenced as `myConstant`.

The expression on the rhs must be a literal, a tag, or a tuple (i.e. a constant!)

Flix `val`s are like Scala `val`s but more restricted: In Scala a `val` can be any expression and its evaluation may have side-effects or fail to terminate. In Flix we aim to avoid that.

**Comment by magnus-madsen** [comment]
At the moment we don't want this; as it would imply running code before main.
In the future we might able to support such constants and inline them into the program.

**Comment by mbarbar** [comment]
Sorry to revive this old thread. I've been thinking about this problem for another language and I'm curious how constant usage looks in Flix.

Must an expression like _2πr_ be written as `2 * pi() * r` (assuming `r` is an argument)? Is there a nicer or more idiomatic way to write `pi()`?

**Comment by magnus-madsen** [comment]
> Sorry to revive this old thread. I've been thinking about this problem for another language and I'm curious how constant usage looks in Flix.
> 
> Must an expression like _2πr_ be written as `2 * pi() * r` (assuming `r` is an argument)? Is there a nicer or more idiomatic way to write `pi()`?

I think that's reasonable. A constant is really just a Unit function. 

The compiler will inline it.
