### ISSUE TITLE
Channel.timeout is impure but should use region

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5076]

**Comment by paulbutcher** [comment]
@magnus-madsen I'm confused. Here's the source of `Channel.timeout`:

https://github.com/flix/flix/blob/master/main/src/library/Channel.flix#L60

It is both impure (which it has to be because it calls `spawn` which is itself impure) and uses a region. What needs changing?

**Comment by magnus-madsen** [comment]
Ah right. Because spawn is impure.

**Comment by paulbutcher** [comment]
> Ah right. Because spawn is impure.

FWIW, I still think that this shouldn't be true in perpetuity. But it's true for now.

**Comment by magnus-madsen** [comment]
Yes, it will change.

**Comment by paulbutcher** [comment]
So does anything need doing with this? Or can it be closed?
