### ISSUE TITLE
BDD Variable Ordering

### ISSUE THREAD

**Issue by SSoelvsten** [flix/flix#5079]
**Context**:
The performance of Binary Decision Diagrams lies in how compact they can be represented: all BDD operations take polynomial time in relation to the BDD size. That is, even with very few variables, the BDD can be exponentially large and so most of the benefits of using BDDs go away. An example of this is shown on [Wikipedia](https://en.wikipedia.org/wiki/Binary_decision_diagram#Variable_ordering).

This can in part explain some of the bad performance and memory overhead witnessed when using decision diagrams as the backend for the Boolean Unification.

> **Rule of Thumb**: 
> Two variables in a BDD ought to be close together in the variable ordering, if they are strongly related.

**Suggestion**:
One may want to consider investigating whether the last-resort *use BDDs* case can hurt less by improving the variable ordering. To this end, one should explore different heuristics that are computable by the compiler. For example, based on the AST one could derive the number of computational "steps" between two variables: the fewer steps, the closer they should be in the ordering.

**Comment by magnus-madsen** [comment]
Thanks @SSoelvsten, we should check that out!

**Comment by magnus-madsen** [comment]
We are now longer using BDDs. We switched to Boolean rings :)

**Comment by SSoelvsten** [comment]
Why not *the power of both*? Have you heard of our lord and savior, [PolyBoRi](https://www.sciencedirect.com/science/article/pii/S0747717109000273). :wink:

Jokes aside, great you found something better than BDDs! This comment is primarily left here as a reference.
