### ISSUE TITLE
Type Classes: Applicative and Monadic Syntax

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#508]
***What:***
Languages such as F#, Haskell, and Scala offer various do-, for-, or monadic-style comprehensions. 

We would like explore this design space in Flix.

***Prerequisites:***
An actual implementation (i.e. desugaring) would requires some form of type classes. 

***Detailed Description:***

- Understanding type classes such as Functor, Applicative, and Monad.
- Understanding how these relate to the comprehensions offered by F#, Haskell, and Scala.
- Describing the limitations of the current designs (e.g. lack of applicative and comonadic support in Scala/Dotty)

**Comment by albertllousas** [comment]
Any update in this topic? It would be great to have monadic comprehensions in Flix.

**Comment by magnus-madsen** [comment]
We should refactor let* to work with our new type classes.
