### ISSUE TITLE
`zipWithIndex` and `mapWithIndex` inconsistent

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#5080]
`zip` uses `(a, Int32)` while `map` wants a `(Int32, a) -> ...` function. I think index first is the most practical.

flatMapWithIndex could also be nice since `zipWithIndex >> flatMap` is not too nice with its tuple argument.

#### `(Int32, a)` "Correct"
* `{Array, Chain, DelayList, Iterator, List, Nec, Nel, String}.zipWith` (if used `c |> C.zipWith(C.indices(c))`)
    * `MutList` is missing
* `Iterator.zipWithL` (if used `i |> Iterator.zipWithL(Iterator.indices(i))`)
* `{Array, Chain, DelayList, Iterator, List, Nec, Nel, Option, String}.zip` (if used `c |> C.zip(C.indices(c))`
    * `MutList` and `Result` is missing
* `{Array, Chain, DelayList, List, MutList, Nec, Nel, String}.mapWithIndex`
    * `Iterator` is missing
* `{Array, MutList}.forEachWithIndex`
    * `Chain`, `DelayList`, `Iterator`, `List`, `Nec`, `Nel`, `String`, `Option`, `Result` is missing. `MutDeque` could maybe be argued.
* `{Array, Mutlist}.transformWithIndex!`
    * `MutDeque` could be argued

#### `(a, Int32)` "Wrong"
* `{Chain, DelayList, Iterator, List, Nec, Nel}.zipWithIndex`
    * `Array`, `MutList` is missing

#### Other notes
* Only `Array` and `String` has `indices`. It should be all namespaces with `zipWithIndex`
* It would be really nice to have `Tuple.liftX` like `Result`/`Option`/etc. Then with `indices`, `zip`, and `Tuple.lift` you could easily achieve all the flatMapWithIndex variants you want and have to rely less on std lib.

**Comment by stephentetley** [comment]
Some of these inconsistencies got fixed in the summer:

#4331 _WithIndex functions - functional arg subject last?

**Comment by magnus-madsen** [comment]
Could either of you compile a list of what functions should be changed?

**Comment by magnus-madsen** [comment]
> It would be really nice to have Tuple.liftX like Result/Option/etc. Then with indices, zip, and Tuple.lift you could easily achieve all the flatMapWithIndex variants you want and have to rely less on std lib.

What does this mean?

**Comment by JonathanStarup** [comment]
`mapWithIndex(f, l)` is the same as `map(lift2(f), zipwithIndex(l))`. In my case I needed `flatMapWithIndex` and it would be easier to make up with `Tuple.liftX` like here

**Comment by stephentetley** [comment]
`Iterable.enumerator` is also "wrong".

I've a branch ready that changes `zipWithIndex` and `enumerator` if we have agreement that they should be `Int32` first.

**Comment by JonathanStarup** [comment]
@stephentetley you can reference this issue and i can give it a review if you like?

**Comment by stephentetley** [comment]
Thanks Jonathan - the branch is here:

https://github.com/stephentetley/flix/tree/zipwithindex

Unfortunately it's not as complete as I thought it was - if I change `List.zipWithIndex` to index/Int32 first I get an error much like the blocking issue in #5189

~~~

-- Type Error -------------------------------------------------- <unknown>

>> Expected type: 'a' but found type: 'Int32'.

0 | 
   
   expression has unexpected type.

~~~

Maybe something desugars to it but I can't find an obvious candidate.

**Comment by stephentetley** [comment]
Actually - it might not be a problem. I think I just missed changing `List.toArray` at the same time.

I'll look at changing the tests and see if it all works after all.

**Comment by stephentetley** [comment]
Changing `zipWithIndex` and `enumerators` arg orders has worked out quite nicely, so I've made a PR - #5201

**Comment by magnus-madsen** [comment]
@stephentetley I think we (you) fixed this right?
