### ISSUE TITLE
BU Explosion

### ISSUE THREAD

**Issue by mlutze** [flix/flix#5086]
```
    pub def findRight(f: a -> Bool \ ef, l: List[a]): Option[a] \ ef =
        loop(f, l, () -> None)
    
    def loop(f: a -> Bool \ ef, ll: List[a], k: Unit -> Option[a] \ {ef - ef2}): Option[a] \ ef = match ll {
        case Nil => k()
        case x :: xs => loop(f, xs, () -> if (f(x)) Some(x) else k())
    }
```

Need to use flag `--Xno-bool-effects`

**Comment by magnus-madsen** [comment]
Works on my machine. 

Does it help if you add `--Xbdd-threshold 4`?

**Comment by mlutze** [comment]
> Does it help if you add `--Xbdd-threshold 4`?

Yes

**Comment by magnus-madsen** [comment]
What happens on your machine?

**Comment by mlutze** [comment]
Without threshold I get OOM

**Comment by magnus-madsen** [comment]
The example is not really complex enough that this should happen...

**Comment by mlutze** [comment]
Just `java -jar flix.jar Main.flix --Xno-bool-effects`

```
openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)
```

```
   size_t MaxHeapSize                              = 4135583744   
```

**Comment by magnus-madsen** [comment]
You mean with or without `--Xno-bool-effects`?

**Comment by magnus-madsen** [comment]
`"C:\Program Files\Eclipse Adoptium\jdk-19.0.1.10-hotspot\bin\java.exe" -Xmx2g ca.uwaterloo.flix.Main foo.flix`

works for me.

**Comment by mlutze** [comment]
`--Xno-bool-effects` is required to make it blow up.

**Comment by magnus-madsen** [comment]
> `--Xno-bool-effects` is required to make it blow up.

I don't even understand then. Does --Xno-bool-effects not disable effects? This is not a performance problem then, but a bug (?)

**Comment by mlutze** [comment]
The example uses set subtraction, which is not representable in the boolean algebra and is replaced by some other thing.

Without `--Xno-bool-effects` the boolean unification fails and the error is reported.

With `--Xno-bool-effects` the boolean unification is skipped and we proceed to set unification, which causes the overflow.
