### ISSUE TITLE
Monadic Sugar for `Result`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5117]
Proposal:

Assume `foo` and `bar` are failable (returns a Result). Then I would like the following sugar:

```ocaml
let x = foo()?;
let y = bar()?;
  Ok(x + y)
```

is equal to:

```ocaml
let* x = foo();
let* y = bar();
  Ok(x + y)
```

(which is straightforward sugar for calls to `flatMap`.)

More interestingly I want:

```ocaml
Ok((foo()?, bar()?)) // returns a pair or fails.
```

which is sugar for:

```ocaml
let* tmp1 = foo();
let* tmp2 = bar();
  Ok((tmp1, tmp2))
```

Note that:

```ocaml
Ok((foo()?, qux(), bar()?))
```

is sugar for:

```ocaml
let* tmp1 = foo();
let tmp2 = qux();
let* tmp3 = bar();
  Ok((tmp1, tmp2, tmp3))
```

since evaluation order must be preserved.

The de-sugaring here is **not** straightforward. In particular, we must preserve evaluation order.

**Comment by JonathanStarup** [comment]
Maybe there's some syntactic tension with all the hole expressions `???`/`?hole`/`var?`

**Comment by magnus-madsen** [comment]
> Maybe there's some syntactic tension with all the hole expressions `???`/`?hole`/`var?`

Yes. but I think that can be resolved. The bigger issue is the desugaring of the above. I don't yet quite see how to do it.

**Comment by JonathanStarup** [comment]
In an inefficient way, couldn't you transform to ANF and change all `let ... = ...?` to `let*`?

**Comment by magnus-madsen** [comment]
> In an inefficient way, couldn't you transform to ANF and change all `let ... = ...?` to `let*`?

Not all lets are monadic. But you are potentially on the right track, I believe.

**Comment by JonathanStarup** [comment]
Yeah just the lets with a ? body.

**Comment by magnus-madsen** [comment]
@JonathanStarup @mlutze Do you see a way to implement this either in Weeding or Lowering without reworking the ASTs dramatically?

**Comment by JonathanStarup** [comment]
does reworking mean reworking the form of the Ast classes or reworking the shape of the input AST?

**Comment by magnus-madsen** [comment]
I think starting with just figuring out how to deal with `Ok((foo()?, qux(), bar()?))` would be interesting.

**Comment by JonathanStarup** [comment]
@magnus-madsen @mlutze The translation from the meeting was the same as above! except with weird terminology. Catch binders in the monad when needed and selectively transform to anf. Completely same method for a different purpose

**Comment by mlutze** [comment]
But if we're emulating effects, why not just have a `Result` effect?

**Comment by magnus-madsen** [comment]
> But if we're emulating effects, why not just have a `Result` effect?

- Lack af polymorphic effects.
- Results are faster.
- Probably more reasons.

**Comment by magnus-madsen** [comment]
> @magnus-madsen @mlutze The translation from the meeting was the same as above! except with weird terminology. Catch binders in the monad when needed and selectively transform to anf. Completely same method for a different purpose

Cool. Once we start on that work, perhaps this ticket will become more clear.
