### ISSUE TITLE
@Skip annotation doesn't

### ISSUE THREAD

**Issue by paulbutcher** [flix/flix#5118]
Adding the `@Skip` annotation to a test doesn't skip the test. Replacing the `@test` annotation with `@Skip` results in an "Unused definition" error.

**Comment by magnus-madsen** [comment]
https://github.com/flix/flix/blob/master/main/test/ca/uwaterloo/flix/util/FlixSuite.scala#L80

**Comment by magnus-madsen** [comment]
https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala#L1001

**Comment by magnus-madsen** [comment]
Give a man a fish... or something something show him the lines to change :)

**Comment by JonathanStarup** [comment]
Also why is the capitalization different? `Skip` vs `test`

**Comment by magnus-madsen** [comment]
> Also why is the capitalization different? `Skip` vs `test`

Actually all annotations are supposed to be uppercase now. Indeed we have `@Test` (and `@test` is old).

**Comment by mlutze** [comment]
`test` is deprecated in favor of `Test`, no?

**Comment by magnus-madsen** [comment]
Good question. I have no strong opinion. I guess if you write Skip it should imply Test. I think the most idiomatic would be to write both.

**Comment by paulbutcher** [comment]
OK, I've just realised that `@Skip` *does* work when you run tests in a user application (i.e. by running either `java -jar flix.jar test` or `java -jar flix.jar <filename> --test`).

It doesn't work when tests are run via `./gradlew testAll` though.

Is there any reason why these two different means of running tests don't use the same test runner? I'm wondering whether the right thing to do is to add skip functionality to the `./gradlew testAll` case, or whether the right thing to do is to unify the two different ways of running tests?

I've also realised in this process that the stdout/stderr redirection we've been discussing in #5123 isn't present when tests are run via `./gradlew testAll`. Again, I'm not sure I understand why the difference?

**Comment by magnus-madsen** [comment]
One is for the compiler and one is for Flix programs. The setups are very different.

**Comment by paulbutcher** [comment]
Which implies that the answer to my question above is that I should add skip functionality to the `./gradlew testAll` case and not unify the two different ways of running tests?

**Comment by magnus-madsen** [comment]
But the compiler tests reuse the library tests with a special runner.

**Comment by magnus-madsen** [comment]
Yes, i would say so

**Comment by paulbutcher** [comment]
Re the question above about `@Skip` being additional to or a replacement for `@Test`, I've left the functionality as-is (which is that it should be used in addition to `@Test`).
