### ISSUE TITLE
Boolean Unification Flags

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5124]
(Applies to master)

Choose one of:

- `--Xbenchmark-frontend`
- `--Xbenchmark-throughput` (frontend + backend)

(This selects the benchmark "mode")

Optionally add one or more of:

- `--Xno-bool-cache`  (disable caching of queries)
- `--Xno-bool-specialcases` (disable hardcoded special cases)
- `--Xno-bool-table` (disables minimization of Boolean formulas via tabling)
- `--Xbdd-threshold n` (if a query has `n` or more variables then switch to BDDs)
- `--Xbool-classic` (when used on combination with `--Xno-bool-cache` corresponds to [Madsen, 2020]. No longer works today; runs out of memory).

Note that ` --Xno-bool-table` probably does not terminate, but the combination of `--Xno-bool-table --Xbdd-threshold 2` might.

EDIT: The `--json` flag can be used to get JSON out (e.g. for processing in Python).
EDIT2: `--Xqmc` has no effect. (Pending merge of that code).

**Comment by magnus-madsen** [comment]
@athas CC

**Comment by athas** [comment]
Cases we want to benchmark, in narrative order:

1. `--Xbool-classic --Xno-bool-cache --Xno-bool-specialcases` (expectation: very slow, possibly nonterminating)
2. `--Xbool-classic` (expecation: very slow, possibly nonterminating)
3. `--Xbdd-threshold 0 --Xno-bool-cache --Xno-bool-specialcases -Xno-qmc` (works, slow)
4. `--Xbdd-threshold 0 --Xno-bool-cache --Xno-bool-specialcases` (works much better)
5. `--Xbdd-threshold 0` (better)
6. `--Xbdd-threshold 5` (better)
7. `--Xbdd-threshold 100` (worse)

**Comment by magnus-madsen** [comment]
An experiment with this flag `--Xno-bool-unif` (https://github.com/flix/flix/pull/5444) suggests that with everything enabled Boolean unification costs `5.5%` of total time spent in the *frontend*. In comparison, our previous paper has the cost at `10%` for the whole compiler. (The whole compiler is about 2x as expensive as the front-end, so a lose measurement suggests from `10%` to `2.5%` -- AND complexity of formulas has of course increased).

**Comment by magnus-madsen** [comment]
To discuss next time: Caching has a huge impact of improving the performance of tabling, but almost no impact on the BDD path. (One possibility is that this is because the BDD library itself does caching, but I do not know.)

**Comment by mlutze** [comment]
> Cases we want to benchmark, in narrative order:
> 
>     1. `--Xbool-classic --Xno-bool-cache --Xno-bool-specialcases` (expectation: very slow, possibly nonterminating)
> 
>     2. `--Xbool-classic` (expecation: very slow, possibly nonterminating)
> 
>     3. `--Xbdd-threshold 0 --Xno-bool-cache --Xno-bool-specialcases -Xno-qmc` (works, slow)
> 
>     4. `--Xbdd-threshold 0 --Xno-bool-cache --Xno-bool-specialcases` (works much better)
> 
>     5. `--Xbdd-threshold 0` (better)
> 
>     6. `--Xbdd-threshold 5` (better)
> 
>     7. `--Xbdd-threshold 100` (worse)

Binary search for optimal threshold :)

**Comment by athas** [comment]
![image](https://user-images.githubusercontent.com/55833/218723802-189cd548-3f12-42e9-9f31-6741fa9d8480.png)

**Comment by athas** [comment]
Configuration 1 uses an extreme amount of memory.  Configuration 2 does not use that much memory, but it does use a lot of time (didn't wait for it to finish).

**Comment by magnus-madsen** [comment]
Try: `--Xbenchmark-phases`
Try: --Xprint-bool-unif foo.flix` (must run with empty file foo.flix).

Add flags/hooks for:

- How many queries into each "phase/funnel" (i.e. how many hit which part of the compiler).
-
