### ISSUE TITLE
Consider returning non-zero exit code in Packager when running tests that fail

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#5126]
Maybe we should consider replacing the `().toOK` in the function below with something that checks whether `Tester.run` was successful. This in turn requires that `Tester.run` returns a result as well (or something that is non-unit). This would allow GitHub actions to fail when tests fail (right now it always succeeds when the project compiles, regardless of test results). The snippet is from `Packager`.

```scala
def test(p: Path, o: Options): Result[Unit, Int] = {
  implicit val flix: Flix = new Flix().setFormatter(AnsiTerminalFormatter)
  build(p, o) flatMap {
    compilationResult =>
      Tester.run(Nil, compilationResult)
      ().toOk
  }
}
```

**Comment by magnus-madsen** [comment]
Sounds reasonable.

**Comment by jaschdoc** [comment]
Fixed in master
