### ISSUE TITLE
Introduce `let x = exp?` syntax

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5135]
As a step towards #5117 I would like to introduce the following *forward compatible* syntax:

```
let x = exp1?;
let y = exp2?;
exp3
```

This would be equivalent to the current:

```
let* x = exp1;
let* y = exp2;
exp3
```

but hardcoded to `Result`.

(This requires some other syntax for HoleWithExp)

**Comment by JonathanStarup** [comment]
Is it a temporary restriction/feature that it only works for Result, or is that permanent?

**Comment by magnus-madsen** [comment]
> Is it a temporary restriction/feature that it only works for Result, or is that permanent?

I think it will be special cased to `Result`. This has advantages: We can give better errors etc.

**Comment by magnus-madsen** [comment]
Separately there will be some monadic syntax (`for`) that `Result` also can participate in. 

But the point is to have a construct that just "solves" error handling.

**Comment by magnus-madsen** [comment]
We have forA and forM.
