### ISSUE TITLE
Add `MustUse` annotation for enums and enforce it in `Redundancy`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5140]
- [ ] Add a` @MustUse` annotation for enums:

```
@MustUse
pub enum Result[t, e] with Eq, Order, ToString, Sendable {
    case Ok(t),
    case Err(e)
}
```

- [ ] Modify the `DiscardedValue` to only give errors for enum types marked as `@MustUse` (see https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala#L391)

**Comment by mlutze** [comment]
Could this be a type class instead? Not sure what the exact consequences would be, but we are identifying a _class_ of _types_ here, right?

**Comment by magnus-madsen** [comment]
> Could this be a type class instead? Not sure what the exact consequences would be, but we are identifying a _class_ of _types_ here, right?

I had the same thought.
