### ISSUE TITLE
Rework Casts (Redux Redux)

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5142]
Here is my 3rd attempt at a collection of workable cast constructs.

I now think we cannot have one upcast construct because supercasts and effect casts are fundamentally different. 

We simply cannot have casts that are as expressive as I thought. The problem is that we lose information during type inference which comes back to bite us. We have to go back to basics.

- [ ] Simplify the check for `supercast` in `Safety` to ONLY allow a cast from one Native type to another. Nothing else. No type variables. No effect variables. No Functions (with co/contra variant typing). Reject everything which is not a cast from one Java type to another. 
- [ ] Change the type rule for `upcast` to enforce that the expected type must have the form `a -> b & pur \ ef` for some `a`, `b`, `pur`, and `ef`.
- [ ] Simplify the check for `upcast` in `Safety` to ONLY allow casts from one effect to a more general effect. No co/contra variant effect typing. 
- [ ] Make `Prelude.identity` effect polymorphic (via an unsafe cast to `ef`).
- [ ] Remove `Prelude.upcast`.

**Comment by magnus-madsen** [comment]
@AStenbaek I would like you to look into this once the other tasks are complete.

I think it would give some insight into the type and effect system.

**Comment by mlutze** [comment]
> Simplify the check for supercast in Safety to ONLY allow a cast from one Native type to another.

This includes `String -> Charsequence`, right?

**Comment by magnus-madsen** [comment]
> > Simplify the check for supercast in Safety to ONLY allow a cast from one Native type to another.
> 
> This includes `String -> Charsequence`, right?

No, you would have to eta expand it.

**Comment by mlutze** [comment]
> > > Simplify the check for supercast in Safety to ONLY allow a cast from one Native type to another.
> > 
> > 
> > This includes `String -> Charsequence`, right?
> 
> No, you would have to eta expand it.

Sorry, poorly expressed. I'm not talking about function types here.

I mean, we can still supercast `String` to `CharSequence`, right? Even though `String` is not really native

**Comment by magnus-madsen** [comment]
- [ ] Ensure `super_cast` works with `null`.
