### ISSUE TITLE
Override Foldable.toDelayList in DelayList instance

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#5146]
Just return the delaylist.
Currently, if `m` is a delaylist then it will materialize everything in
`Foldable.toDelayList(m)`

**Comment by mlutze** [comment]
Is materializing everything part of the foldable contract though?

**Comment by jaschdoc** [comment]
Not sure. It just seems like something unintentional that a function accidentally materializes a delaylist

**Comment by mlutze** [comment]
I guess it should be unobservable anyway since the delayed calculations are pure.

**Comment by jaschdoc** [comment]
So you agree?

**Comment by mlutze** [comment]
> So you agree?

Oui
