### ISSUE TITLE
Please allow middle-clicking on api.flix.dev

### ISSUE THREAD

**Issue by athas** [flix/flix#5171]
I cannot middle- or ctrl-click the menu items to the left on api.flix.dev.  This makes it annoying to open several pages simultaneously, which is needed when cross-referencing things.

**Comment by magnus-madsen** [comment]
OK, I will allow it.

(More seriously, is it some JS not working or what?)

We are planning to switch to a fully static html-based approach soon.

**Comment by athas** [comment]
It is probably some JS thing.

**Comment by magnus-madsen** [comment]
Fixed. We now generate static HTML for your enjoyment!
