### ISSUE TITLE
Automatic curryfication causes typing problems

### ISSUE THREAD

**Issue by thomas-colcombet** [flix/flix#5180]
The following code should take a list of ordered pairs, and reverse them (then print it).
```
def main(): Unit & Impure =
    let l: List[(Int32,Int32)] =  (1,2)::Nil ;
    let swap_l: List[(Int32,Int32)] = List.map( (x,y) -> (y,x),  l);
    println(swap_l)
```
but it yields:
```
>> Expected type: '? -> ?' but found type: '(?, ?)'.

4 |     let swap_l: List[(Int32,Int32)] = List.map( (x,y) -> (y,x),  l);
                         ^^^^^^^^^^^^^
                         expression has unexpected type.
```
I understand it as a problem of automatic curryfication of  (x,y) -> (y,x)  (but I may be wrong).

I do not know how to avoid this problem.

**Comment by mlutze** [comment]
Hi @thomas-colcombet,

The lambda you defined there is indeed a curries lambda. To create a lambda over a tuple, you can use this syntax: `match (x, y) -> (y, x)`

**Comment by thomas-colcombet** [comment]
Thanks a lot @mlutze, 
indeed this works perfectly.

Maybe this syntax could be mentionned in the 'function' part of the doc (that talks about automatic currying), rather than in the pattern-matching section.

**Comment by magnus-madsen** [comment]
I will add a note to the documentation.
