### ISSUE TITLE
Add `Collectable` type class

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5190]
- [ ] Add `Collectable` type class:

```
class Collectable[m: Type -> Type] {
    pub def collect(iter: Iterator[a, r]): m[a] \ r
}

instance Collectable[List] {
    pub def collect(iter: Iterator[a, r]): List[a] \ r = Iterator.toList(iter)
}
```

- [ ] Add instances for all immutable collections.
- [ ] Add instance for `Result`. (Add test cases.) -- if possible?
- [ ] Add instance for `Validation`. (Add test cases.) -- if possible?
- [ ] Add instance for `Option`. (Add test cases.) -- if possible?

Note: Collectable only supports collecting into immutable collections. We can lift that restriction with associated types later.

**Comment by magnus-madsen** [comment]
@stephentetley Did you want to take a stab at this?

**Comment by stephentetley** [comment]
I was going to, but I got stuck with trying to refactor `Iterator`. I could try with the current `Iterator`.

**Comment by magnus-madsen** [comment]
Roger. Let me know if you get stuck again, and I will take a look.

Happy new years! 🎆

**Comment by stephentetley** [comment]
Happy New Year to you too, Magnus!

I've taken a proper look at `Collectable` now and I've become doubtful that it will work out as a good abstraction. Ignoring mutable collections for the time being:

Firstly it works fine for `List` and `Chain`.

`Set` - instance needs `Order` constraint on the element type so can't match the class signature for `collect`.

`Nec` and `Nel` - the answer type is wrapped in an `Option` so doesn't match the class signature for `collect`.

`Map` - input stream needs to be a pair and first element needs an `Order` constraint so doesn't match the generic `collect`.

`Result` and `Option` - no single obvious idea of "collecting". `Option` can be written with the current definition of `collect` where it takes the "head" of the iterator (or `None`) but this seems a very particular idea of collecting. Result can't even do this because we need to produce some default `e` (error type) in the case of an empty iterator. 

Even in a future with associated types I think there may still be too much variance in the signature of `collect` to work well.

**Comment by magnus-madsen** [comment]
Good points. I will have to think more about it.

> Set - instance needs Order constraint on the element type so can't match the class signature for collect.

Hmm. I wonder how they make it work in Rust, since surely they need either `Order` or `Hash`?

**Comment by magnus-madsen** [comment]
Does any one read Rust? 

https://doc.rust-lang.org/stable/src/std/collections/hash/map.rs.html#3015-3025

What is that expressing?

**Comment by stephentetley** [comment]
Rust has associated types so I think it is using them to make `Pair(key, value)` then element (Item) of the Hash Map iterator.

I don't know Rust well but it looks like you can specify constraints on the implementation and not just the trait class. Hence the line: 

> K: Eq + Hash + Copy,

**Comment by magnus-madsen** [comment]
I think we can overcome most of these problems with associated types. (Then we can also have such contraints on the instances, AFAIK).

In any case, I would like to push ahead with `Collectable`, even if the first version will only support `List` and `Chain`.

In fact, why don't we, at least temporary just change the signature to `pub def collect(iter: Iterator[a, r]): m[a] \ r with Order[a]`.

This is too restrict, but we can lift the requirement later.

**Comment by stephentetley** [comment]
I'll make a go with the `Order[a]` constraint that means we can have `List`, `Chain` and `Set` instances.

I'll also look at simulating `Collectable` in Haskell so I can see what we might get with associated types.

**Comment by stephentetley** [comment]
Ive upload a PR - #5222

**Comment by stephentetley** [comment]
`Set` and `Map` instances work out nicely in Haskell:

~~~

{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE KindSignatures #-}

module Collectable where

import Data.Map(Map)
import qualified Data.Map as M

import Data.Set(Set)
import qualified Data.Set as S

-- fake
newtype Iterator a r = Iterator [a]

instance Show a => Show (Iterator a r) where
   show (Iterator xs) = "Iterator $ " ++ show xs

iteratorFromList :: [a] -> Iterator a r 
iteratorFromList xs = Iterator xs

-- fake
newtype Chain a = Chain [a]

class Collectable (t :: *) where
    type Elem t :: *
    collect :: Iterator (Elem t) r -> t


instance Collectable [a] where
    type Elem [a] = a
    collect (Iterator xs) = xs


instance Collectable (Chain a) where
    type Elem (Chain a) = a
    collect (Iterator xs) = Chain xs


instance Ord a => Collectable (Set a) where
    type Elem (Set a) = a
    collect (Iterator xs) = S.fromList xs

instance Ord k => Collectable (Map k v) where
    type Elem (Map k v) = (k, v)
    collect (Iterator xs) = M.fromList xs


test01 :: Map Char Int
test01 = collect $ iteratorFromList [('a', 97), ('b', 98)]


{-
-- Righfully fails with a type error
nonsense :: Map Char a
nonsense = collect $ iteratorFromList ['a', 'b', 'c', 'd']
-}

~~~

I think reasonable instances for `Nel` and `Nec` are too much to ask for - at that point we would probably need an non-empty iterator. Likewise `Option` and `Result` are not enough like "collections" to fit `Collectable`.

**Comment by magnus-madsen** [comment]
Thanks for confirming that this works in Haskell! (Also a bit relieved!)

As for `Option` and `Result`, I agree, they should be handled separately. I think Rust has a `try_collect` or similar.

**Comment by magnus-madsen** [comment]
Are associated types enabled by default without any pragmas?

**Comment by stephentetley** [comment]
Thanks Magnus, pragmas are probably still needed with the current GHC release. 

I'm on GHC 8.4.2 which included the "platform" libraries but is now quite old - that version certainly needs them.

**Comment by magnus-madsen** [comment]
Is it possible to express an instance that turns `Iterator[Result[e, t]]` into `Result[List[t], e]` with the first error encountered?

**Comment by stephentetley** [comment]
> Is it possible to express an instance that turns Iterator[Result[e, t]] into Result[List[t], e] with the first error encountered?

Yes, I was a bit surprised we can, but I think the code below does it:

Additions to above module ....

~~~

data Result e a = Err e | Ok a
    deriving (Eq, Ord, Show)

runResultIter :: Iterator (Result e a) r -> Result e [a]
runResultIter (Iterator xs) = step [] xs
    where
        step _   (Err e : _)  = Err e
        step acc (Ok x : rs)  = step (acc ++ [x]) rs
        step acc _            = Ok acc

instance Collectable (Result e [a]) where
    type Elem (Result e [a]) = Result e a
    collect iter = runResultIter iter


type ErrMsg = String

test02 :: Result ErrMsg [Int]
test02 = collect $ iteratorFromList [Ok 1, Err "Bad"]

test03 :: Result ErrMsg [Int]
test03 = collect $ iteratorFromList [Ok 1, Ok 2]

~~~

Output from running: 

~~~

*Collectable> test02
Err "Bad"
*Collectable> test03
Ok [1,2]

~~~

**Comment by magnus-madsen** [comment]
Excellent, right? :)

**Comment by stephentetley** [comment]
Yes looks right - it's a bit unintuitive now the `t` of `Collectable` isn't `kind :: * -> *` though (aka kind `Type -> Type` in Flix).
