### ISSUE TITLE
Experiment with using gradle for dependency management

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5199]
Goals:

- [ ] Use gradle to manage dependencies (e.g. we should be able to get rid of jars in the `lib` folder).
- [ ] We must be able to pin the version of some libraries (e.g. pjbdd).
- [ ] We should be able to build a fat `flix.jar` of approximately the same size and compatible with Java 11.
- [ ] The solution must continue to work with GitHub CI and arewefast.flix.dev.
- [ ] Compile time should be comparable.
- [ ] Must integrate well into Intellij IDEA. In particular, our current workflow must not be slowed down. If this requires some configuration or specific setup of IDEA that is fine-- as long as it works and can be documented.

Ensuring our workflow is not disrupted is the most important.

Non-goals (i.e. things that should not be done for this specific experiment):

- Adding any new dependencies.
- Upgrading any dependencies (that will follow).

**Comment by paulbutcher** [comment]
@magnus-madsen I think we can close this?
