### ISSUE TITLE
Add more `toString`s

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5214]
Add:

- [ ] `MutDeque.toString`
- [ ] `MutList.toString`
- [ ] `MutSet.toString`
- [ ] `MutMap.toString`

all of these should have an effect in the associated region.

Note we should _not_ implement `ToString` for these. (Maybe one day with associated types. Maybe not...)

**Comment by JonathanStarup** [comment]
Maybe not the correct place to post, but has anyone looked at toString methods for `Array[Array[Int32, r], r]`, for example? Maybe a toString method where the toString function for the element is given explicitly?

**Comment by magnus-madsen** [comment]
> Maybe not the correct place to post, but has anyone looked at toString methods for `Array[Array[Int32, r], r]`, for example? Maybe a toString method where the toString function for the element is given explicitly?

There is `Array.joinWith`.

**Comment by stephentetley** [comment]
I'll take a look at this and add `forEachWithIndex` where needed as well.

**Comment by stephentetley** [comment]
PR #5248
