### ISSUE TITLE
Remove support for implicit regions

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5215]

**Comment by paulbutcher** [comment]
Can I check what the intent of this is? Is it:

* To avoid things like `ref` picking up the "nearest" region automagically?
* To avoid `region r` magically introducing both a term-level and type-level variable?

(FWIW, I think that we should fix both of these, but I'm not sure which this issues is intended to address?)

**Comment by magnus-madsen** [comment]
This one:

To avoid things like ref picking up the "nearest" region automagically?

**Comment by paulbutcher** [comment]
Can we do the other one too? 😊

**Comment by magnus-madsen** [comment]
> Can we do the other one too? 😊

I am not sure exactly what you mean? That you have to name the type level variable or that there should only be term/type level?

**Comment by paulbutcher** [comment]
That there should be a clear indication in the syntax that *two* variables are being introduced. One way to do this might be:

```
region rh @ r { ... }
```

Although there are clearly plenty of other options.

**Comment by stephentetley** [comment]
Hope this isn't treading on Matthew's toes - I've looked at the tests suites and changed them to use an explicit region where they matched this grep 

> find . -name "*.flix" | xargs grep -n " ref " | grep -v "@"

(Can't guarantee if finds everything.)

I'll make a PR once I've got one problem to compile.

**Comment by mlutze** [comment]
Thanks Stephen, no toe-treading done :)

**Comment by mlutze** [comment]
Remaining uses after Stephen's PR: (#5253)

```
   1725 main/test/ca/uwaterloo/flix/library/TestArray.flix
     20 main/test/ca/uwaterloo/flix/library/TestDebug.flix
      3 main/test/ca/uwaterloo/flix/library/TestFile.flix
      3 main/test/ca/uwaterloo/flix/library/TestFoldable.flix
     94 main/test/ca/uwaterloo/flix/library/TestMutList.flix
     42 main/test/ca/uwaterloo/flix/library/TestMutMap.flix
      1 main/test/ca/uwaterloo/flix/library/TestObject.flix
      3 main/test/ca/uwaterloo/flix/library/TestReducible.flix
      1 main/test/ca/uwaterloo/flix/library/TestToString.flix
      1 main/test/flix/Test.Eff.Advanced.flix
      2 main/test/flix/Test.Eff.Polymorphism.flix
     14 main/test/flix/Test.Exp.ArrayLength.flix
    171 main/test/flix/Test.Exp.ArrayLit.flix
      2 main/test/flix/Test.Exp.Concurrency.Buffered.flix
      2 main/test/flix/Test.Exp.Concurrency.Unbuffered.flix
     18 main/test/flix/Test.Exp.Discard.flix
      2 main/test/flix/Test.Exp.Force.flix
      1 main/test/flix/Test.Exp.Jvm.InvokeConstructor.flix
      2 main/test/flix/Test.Exp.Jvm.InvokeStaticMethod.flix
      2 main/test/flix/Test.Exp.Jvm.NewObject.flix
      1 main/test/flix/Test.Exp.Mask.flix
      1 main/test/flix/Test.Exp.Ref.Deref.flix
      4 main/test/flix/Test.Exp.Tag.flix
     33 main/test/flix/Test.Exp.TypeMatch.flix
      2 main/test/flix/Test.Java.Function.flix
```

(Found by hacking the compiler to print the location each time we have to infer)
