### ISSUE TITLE
Remove `new` and `Newable`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5217]
- [ ] Remove the `Newable` type class.
- [ ] Remove `new` syntax.
- [ ] Remove `new` from LSP completion.
- [ ] Remove `new` from VSCode highlight.

**Comment by mlutze** [comment]
What's the reasoning behind this. IMO it's more principled for a syntactic sugar to be tied to a type class.

**Comment by magnus-madsen** [comment]
> What's the reasoning behind this. IMO it's more principled for a syntactic sugar to be tied to a type class.

Good point. Maybe we should just drop the syntax?

**Comment by magnus-madsen** [comment]
Notice that right now in `new Foo(exp)` the `Foo` part has no meaning!!!

**Comment by magnus-madsen** [comment]
This works:

```
def main(): Unit \ IO = 
    region rh {
        let fruits = new MutList(rh);
        MutSet.add!("Apple", fruits);
        MutSet.add!("Pear", fruits);
        MutSet.add!("Mango", fruits);
        MutSet.forEach(println, fruits)
    }
```
:D

**Comment by mlutze** [comment]
Yeah I don't really see a purpose to the syntax. I guess it's nice to have a uniform way to create a data structure?

**Comment by magnus-madsen** [comment]
> Yeah I don't really see a purpose to the syntax. I guess it's nice to have a uniform way to create a data structure?

Cheap parlor trick?

**Comment by mlutze** [comment]
> > Yeah I don't really see a purpose to the syntax. I guess it's nice to have a uniform way to create a data structure?
> 
> Cheap parlor trick?

If we're prioritizing that, we could have a lot of fun during the hackathon...

**Comment by magnus-madsen** [comment]
So the vote is to remove it?

**Comment by mlutze** [comment]
That's my vote.

**Comment by magnus-madsen** [comment]
OK, I updated the ticket.

**Comment by mlutze** [comment]
Note that `new` is still a keyword in the interop syntax.

**Comment by magnus-madsen** [comment]
True that

**Comment by magnus-madsen** [comment]
@jaschdoc Ill give you this one too. Its not urgent, but if you get stuck on other things you can do it.

**Comment by jaschdoc** [comment]
> This works:
> 
> ```
> def main(): Unit \ IO = 
>     region rh {
>         let fruits = new MutList(rh);
>         MutSet.add!("Apple", fruits);
>         MutSet.add!("Pear", fruits);
>         MutSet.add!("Mango", fruits);
>         MutSet.forEach(println, fruits)
>     }
> ```
> 
> :D

We actually had this test in the library suite :/

```
    @test
    def toString02(): Bool = region rc {
        let m = new MutList(rc);
        MutMap.put!(1, 101, m);
        MutMap.toString(m) == "MutMap#{1 => 101}"
    }
```

**Comment by jaschdoc** [comment]
> Remove new from VSCode highlight.

Is this a good idea for interop as Matt pointed out? I guess you still want it highlighted when using java stuff

**Comment by magnus-madsen** [comment]
> > Remove new from VSCode highlight.
> 
> Is this a good idea for interop as Matt pointed out? I'd say you still want it highlighted when using java stuff.

Fair point.
