### ISSUE TITLE
Allow `super_cast` from `null`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5227]
The following program:

```
def f(): String = 
    let s: String = super_cast null;
    s
```

gives:

```
❌ -- Safety Error --------------------------------------------------

>> The following supercast is unsafe and not allowed.

2 |     let s: String = super_cast null;
                        ^^^^^^^^^^^^^^^
                        the supercast occurs here.

Actual type:      Unit
Tried casting to: String
```

but this should be allowed.

I think the fix can be made around here: 

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Safety.scala#L489

**Comment by paulbutcher** [comment]
Is this related to https://github.com/flix/flix/issues/5170 at all?

**Comment by magnus-madsen** [comment]
> Is this related to #5170 at all?

No, I don't think so.

**Comment by mlutze** [comment]
I suggest that we disallow upcasting to `String` and `BigInt` and `BigDecimal` in this case.

**Comment by magnus-madsen** [comment]
> I suggest that we disallow upcasting to `String` and `BigInt` and `BigDecimal` in this case.

OK. I think @yisraelU may try this later.

**Comment by yisraelU** [comment]
Will take a look

**Comment by yisraelU** [comment]
Should super_casting be allowed for all Native types from null also?
something like this in the isJavaSubtype method
```
    case (Type.Cst(TypeConstructor.Null, _), Type.Cst(TypeConstructor.Native(right), _)) =>
     true
```

**Comment by magnus-madsen** [comment]
No. Mostly because there is never a need.

**Comment by mlutze** [comment]
I thought upcasting to native types was the primary use-case?

I don't like this:
```scala
let x = super_cast null;
String.length(x)
```
because it looks safe but actually crashes at runtime.

**Comment by yisraelU** [comment]
ok so to clarify , this requirement is to specifically allow super_cast from a flix null to a Flix string?
doesnt this imply mutability or a crash at runtime ?

**Comment by magnus-madsen** [comment]
Fixed in master.
