### ISSUE TITLE
Restrictable Variants

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5229]
Tasks:

Phase 1:
- [x] Rename the syntax `choose` to `relational_choose` and `choose*` to `relational_choose*`.
- [x] Rename `Test.Exp.Choose` to `Test.Exp.RelationalChoose` and `Test.Exp.ChooseStar` to `Test.Exp.RelationalChooseStar`.
- [x] Rename `Expression.Choose` to `Expression.RelationalChoose` and rename `ChoiceRule` to `RelationalChoiceRule`, and rename `ChoicePattern` to `RelationalChoicePattern`.

Phase 2:
- [x] Add `Expression.Choose` with syntax `choose e { ... }` and `choose* e {...}`
- [x] Add restrictable enum syntax: `restrictable enum Color[s][...] {...}`. Add `Declaration.RestrictableEnum` and `RestrictableCase`.
- [x] Add `Symbol.RestrictableEnum` and `TypeConstructor.RestrictableEnum`.
- [x] #5244
- [x] Post `Resolver` add a `Expression.RestrictableTag`.
- [x] Add Resolver check for valid `choose*` body
- [ ] Translate all these constructs to normal enums and matches in `Lowering` instead of monomorph.
- [x] Add parametric Kind for these special restriction types
- [x] Add `Cons of exp` annotation and allow it as the `choose*` body in Resolver`
- [ ] Add LSP support
- [x] Add type/kind annotation
- [ ] Improve unification performance #5336

Phase 3: 
- [ ] Kind inference.
- [x] Type inference
- [ ] remove `of`
- [ ] Open sets (???).
- [ ] Equality (etc).
- [ ] Ponder this #5398

Phase 4:
- [ ] Generalize and reuse code to avoid unnecessary duplication.
    - [ ] Reuse Symbols? 
- [ ] Tests. #5311
- [ ] Review code together.

Cleanup:
- [ ] Figure out why this PR  made the resolver performance drop https://github.com/flix/flix/pull/5265

Features:
* Must refer to tags by enum namespace (`Expr.tag`)

**Comment by JonathanStarup** [comment]
I think we need to add a new parametric kind for the restriction type parameters

**Comment by JonathanStarup** [comment]
Should we add `~` or is the existing `not` sufficient?

**Comment by mlutze** [comment]
> Should we add `~` or is the existing `not` sufficient? We could also add `-`

There should already be a ~ for set effects.

**Comment by mlutze** [comment]
I'm using `RESTR-VARS` as the `TODO` tag for this project.
E.g.

```scala
case UnkindedType.RestrictableEnum(_, _) => ??? // TODO RESTR-VARS
```

**Comment by magnus-madsen** [comment]
- Don't use `enum` as a variable name.

**Comment by mlutze** [comment]
- [ ] fix error messages
