### ISSUE TITLE
Exceptions in Flix

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#523]
The book Functional Programming in Scala by Paul Chiusano and Rúnar Björnsson gives an excellent description of the problems with exceptions and why they are not well-suited for functional programming. (See chapter 4).

I am leaving this ticket here as a reminder of the presented issues and as an argument of why we should refrain from adding exceptions to Flix.

**Comment by FlaminGuy** [comment]
Well that was quick 😆
