### ISSUE TITLE
Add `instanceof` binary expression?

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#5238]
To interface with Java libraries that make heavy use of visitors having something equivalent to Java's `instanceof` would be very useful.

I don't think this would be covered by the new `typematch` operation, am I right? I'm anticipating `instanceof` would have to go all the way down to bytecode.

I've started a branch to investigate...

**Comment by magnus-madsen** [comment]
We can, and yes it probably needs to go down to bytecode.

(And yes, type match is not the right tool.)

**Comment by stephentetley** [comment]
Thanks for the confirmation on typematch, Magnus.

**Comment by magnus-madsen** [comment]
We might want yet another match construct-- to avoid the `check then cast` anti-pattern from Java.

**Comment by stephentetley** [comment]
I've made a draft PR #5760

**Comment by magnus-madsen** [comment]
Fixed in master.
