### ISSUE TITLE
Add restrictable Type parsing, e.g. `List<s>[Int32]`

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#5240]
Related to #5229

**Comment by JonathanStarup** [comment]
@mlutze Do you think that `<var>` should just be possible in the parser wherever `[Type]` is possible? And then output a normal type application. It feels like this loses information but I'm not sure what alternatives there are

**Comment by mlutze** [comment]
Yeah that's probably the simplest solution for now. We can revisit later.

**Comment by mlutze** [comment]
(though that should be `<Type>` in case we want to do e.g. `{Cons}`

**Comment by JonathanStarup** [comment]
Closed per discussion with magnus. Delete the `<...>` syntax since any "magic" would require a different type apply in the typer also
