### ISSUE TITLE
Add `case class ChoiceRule(pat: ChoicePattern, exp: Expression)` to  ASTs after the Weeder.

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#5244]
What should we allow initially? Only tags with variables? 

```
case Tag(x, y ,z) => anything
```

And then for `choose*` we check that the body of the case is either a tag or a tag annotation?

**Comment by magnus-madsen** [comment]
Maybe we start without the `of` syntax and we the rhs always be a tag expression?
