### ISSUE TITLE
Possibly unsafe use of Java memory model?

### ISSUE THREAD

**Issue by paulbutcher** [flix/flix#5260]
While looking at modifying `compileForceMethod` as part of #5123, I think I've discovered a potentially unsafe use of the Java memory model.

If I'm reading the code correctly, then each `lazy` type is represented by a class of the form:

```
public final class Lazy%Typename {
  public java.lang.Object expression = ...;
  public Typename value;
  public final synchronized Typename force() { ... }
  public Lazy%Typename(java.lang.Object) { ... }
}
```

And the code that's generated for `force` takes the form:

```
  Lazy%Typename x = ...;
  if (expression == null)
    return x.value;
  else
    return x.force();
```

Assuming that I'm understanding correctly, this is safe in the event that `x.expression` is non-null, but not otherwise. The reason is that there's no synchronization point in the thread reading `x.expression`, which means that there's no guarantee that the view of memory from the reading thread will be consistent.

The solution, I believe, is to make `expression` `volatile`.

(but it's possible I'm misunderstanding).

@JonathanStarup can you confirm/refute?

**Edited:** because it's `expression` that's checked, not `value`. But the problem remains the same.

**Comment by JonathanStarup** [comment]
The intention is that

1: If `expression = null` use the computed result
2: Obtain the lock of the lazy object
3: Check again that `expression = null`. If someone computed the value between 1 and 3, we now reuse that value
4: compute the value

So only one thread can be in force at a time, and the start of that method checks that the concurrent "forces" didn't already do the work.

So I read up on volatile, and as you're saying, the check in step 3 might see an old value of expression, unless we add volatile?

It seems correct to me, concurrency in java is more difficult then I thought, good to have you! 😁

**Comment by JonathanStarup** [comment]
Sidenote: this bug would be almost impossible to catch empirically since we require pure lazy expressions, good catch

**Comment by paulbutcher** [comment]
> So I read up on volatile, and as you're saying, the check in step 3 might see an old value of expression, unless we add volatile?

No, the problem is in step 1, not step 3.

Step 3 is safe because the code performing it holds the lock (as will any other code that performs it) and the act of acquiring a lock and releasing a lock imposes constraints on the visibility of effects in memory.

Step 1 is not safe because we're checking for `expression = null` without any synchronisation. That means, effectively, *all bets are off* when it comes to inter-thread memory consistency. In particular, it would be possible for `expression` to appear to be `null`, but `value` would still appear to have its old value. To make this concrete, the following code:

```
def main(): Unit \ IO = region r {
    let x = lazy 42;
    spawn { force x };
    println(force x)
}
```

Could (as the code currently stands) output: `0`.

To put things another way: `volatile` is never necessary if the variables in question are only ever accessed while holding a lock. The problem is that we're *sometimes* accessing `expression` while holding a lock and *sometimes* accessing it without holding a lock. That's why `volatile` is necessary in this case.

**Comment by JonathanStarup** [comment]
Aah okay, makes sense 👍

**Comment by magnus-madsen** [comment]
The original reason was:
- Locks are expensive.
- Evaluating a pure expression is not observable.
- Hence lets check for non-null without a lock and use it, if available, and before locking.

Yes, this means the same expression could be evaluated twice (but again this does not matter).

In any case, I am OK with a ReetrantLock around everything, since I don't think `Lazy` should be used much anyway.

**Comment by magnus-madsen** [comment]
... Not knowing the code in detail... I am not sure if the above is sound _if more than one field is involved_. Is that the case (???)

**Comment by paulbutcher** [comment]
@magnus-madsen, I suspect you may be getting the question of replacing `synchronized` with `ReentrantLock` confused with this issue, which is completely unrelated.

The error case here is not that the expression could be evaluated twice. The error case is that a *completely incorrect* value could be seen by code using `lazy`. Take a look at the [code above](https://github.com/flix/flix/issues/5260#issuecomment-1374544318): the value returned could be zero, not 42. This is not an efficiency issue, this is a correctness issue.

The solution is not to wrap everything in `ReentrantLock` (switching to `ReentrantLock` is a solution to the fact that `synchronized` is not interruptible, and I'm not proposing to do away with the check of `expression` before claiming the lock). The solution is to make `expression` `volatile`. This will *slightly* decrease efficiency (because it will involve flushing values to memory) but not doing so leaves the possibility of code behaving incorrectly (so I don't think it's an option).

**Comment by paulbutcher** [comment]
> ... Not knowing the code in detail... I am not sure if the above is sound _if more than one field is involved_. Is that the case (???)

Yes, this is exactly the case. In fact, it's the fact that more than one field is involved that causes the problem in the absence of `volatile` (because without `volatile` there are no ordering guarantees).

**Comment by paulbutcher** [comment]
@magnus-madsen, @JonathanStarup: what follows is an attempt to explain the Java memory model which will hopefully make the above clearer.

Firstly: Java makes *zero* guarantees about inter-thread memory visibility for incorrectly synchronised code. Here's some example code from my book which illustrates the point:

```java
public class Puzzle {
  static boolean answerReady = false;
  static int answer = 0;
  static Thread t1 = new Thread() {
      public void run() {
        answer = 42; 
        answerReady = true; 
      }
    };
  static Thread t2 = new Thread() {
      public void run() {
        if (answerReady)
          System.out.println("The meaning of life is: " + answer);
        else
          System.out.println("I don't know the answer");
      }
    };

  public static void main(String[] args) throws InterruptedException {
    t1.start(); t2.start();
    t1.join(); t2.join();
  }
}
```

There are three possible things that this code could output:

1. "The meaning of life is: 42"
2. "I don't know the answer"
3. "The meaning of life is: 0"

The interesting one is the last one: it looks like the order of `answer = 42 and `answerReady = true` have been swapped. This is completely correct behaviour because the code is not correctly synchronised.

It gets worse. If we rewrite `run` as follows:

```java
public void run() { 
    while (!answerReady) 
        Thread.sleep(100);
    System.out.println("The meaning of life is: " + answer);
}
```

It would be permissible behaviour for the code to _never exit_ (because `answerReady` may never appear to be `true`).

Correct behaviour requires that *both* the thread writing to memory and the thread reading from memory are correctly synchronised. The Java memory model defines synchronisation points at which all memory effects must become visible. These synchronisation points include things like:

* acquiring an object's lock (i.e. `synchronized`)
* calling `join`

The problem with the code for `lazy` as it currently stands is that the code which sets `expression` to `null` is correctly synchronised (it's doing so while it holds the object's lock). But the code that's checking for `expression` being `null` is not correctly synchronised.

There are various ways in which we could address this, but the way I'm suggesting is to make `expression` `volatile`.

If you want the nitty gritty details: https://docs.oracle.com/javase/specs/jls/se8/html/jls-17.html

**Comment by magnus-madsen** [comment]
I see. I thought there was only a single field.

**Comment by paulbutcher** [comment]
To be fair there would still be a problem if there was only a single field, if the lazy value wasn't primitive (in the absence of correct synchronisation, the memory model makes no guarantee that every element of a non primitive object will be visible in memory simultaneously). 

Bottom line is never write to or read from a (non constant) value which may be accessed by multiple threads without both the reading and writing threads being correctly synchronised.
