### ISSUE TITLE
Add a `throw` expression

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5307]
- [ ] Add a `Throw` expression right before `TryCatch` to all ASTs and phases.
- [ ] Any value can be thrown.
- [ ] In `Safety`, check that the thrown value is a subtype of `Throwable`.
- [ ] Add test cases.
- [ ] (Later) Think about how throw should work with the effect system.

Note: This `throw` and `try-catch` should not be used in Flix code-- they only exist for interoperability with Java.

**Comment by paulbutcher** [comment]
What's the use case for throwing from Flix code?

**Comment by magnus-madsen** [comment]
> What's the use case for throwing from Flix code?

Purely for interoperability.

**Comment by paulbutcher** [comment]
Ah, I got you. So this is for supporting Java interfaces where throwing an exception is a "required" part of using the interface.

Hmm. I can think of some means by which we could do this (e.g. having the return value of all Java functions be something like `Either[Exception, t]`) but the cure may be worse than the disease?

**Comment by magnus-madsen** [comment]
> Ah, I got you. So this is for supporting Java interfaces where throwing an exception is a "required" part of using the interface.

Yes.

**Comment by paulbutcher** [comment]
> Hmm. I can think of some means by which we could do this (e.g. having the return value of all Java functions be something like Either[Exception, t]) but the cure may be worse than the disease?

Actually, the more I think about it, the less I dislike it. 

This will only apply to methods that we implement ourselves (i.e. within `new` expressions). So the effect would be quite constrained.

Might be easier to implement than plumbing `throw` all the way through the AST too?

**Comment by magnus-madsen** [comment]
I could see that as a feature, by mandating it, I am less sure.

**Comment by magnus-madsen** [comment]
In any case, I do actually think we want to have an Expression.Throw internally. (No matter what we surface to users).

**Comment by paulbutcher** [comment]
I guess I don't feel too strongly about this: just my natural inclination whenever there's a tradeoff between making Flix more complicated in order to have better Java interop is to push back against it (mainly because I perceive many of Scala's problems to have arisen from excessively prioritising Java interop)
