### ISSUE TITLE
Restrictable Variant Testing

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#5311]
Related to #5229.

# Expressions
* `choose`
    * Properties 
        * Input upper bounded by case set
    * Forms
        * Supply literal tag
        * Supply tag union
        * Combine chooses, check literal tag validity
        * Composition?
* `choose*`
    * Input upper bounded by case set
    * Output lower bounded by non-stable case set
    * Output upper bounded by case set union non-stable set
* New tag
    * Lower bounded by tag
* `of`

# Features
* Unit Termed enum (`case Not()`)
* Simple enum (`case Not(Bool)`)
* Recursive enum (`case Not(Expr[s])`)
* Polymorphic enum (`case Not(t)`)
* Polymorphic recursive enum (`case Not(Expr[s][t])`)

Missing tech
* Nested enum (`case Not(Some(Bool))`, this option is restrictable) [Needs kind annotation and less hacks]
* Polymorphic index type in enum (`case Not(Expr[t][s])`) [Needs kind annotation probably]
* Mutual recursive enums (`case Not(Expr2[t][s])`) [Needs kind annotation probably]

**Comment by magnus-madsen** [comment]
Looks very nice 👍
