### ISSUE TITLE
Github bug template

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#5322]
We could add a nice template to file bug reports

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

Here's an example from another repo

https://github.com/microsoft/PowerToys/issues/new?assignees=&labels=Issue-Bug%2CTriage-Needed&template=bug_report.yml&title=

**Comment by magnus-madsen** [comment]
I think it is a good idea long-term, but short term we just want people to report whatever they want to report :)
