### ISSUE TITLE
Remove infix `rem` and `mod` expressions

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#5338]
This program does not parse. It seems to be an issue whenever a `def` precedes a `mod` declaration (because its parsed as the `mod` operator).
```scala
def f(): Unit = ???
mod Inner {
    pub def f(): Unit = ???
}
```
Will this be the final drop that makes us require `{...}` for multiline defs?

**Comment by magnus-madsen** [comment]
No, rather I think its the death of `mod` and `rem` as keywords. Why do they get special treatment? They are so rarely used. And they are just functions.

**Comment by JonathanStarup** [comment]
Then they're also findable in Api and can have doc comments

**Comment by magnus-madsen** [comment]
And auto complete and work on pipelines

**Comment by magnus-madsen** [comment]
- [ ] Remove support for infix `rem` and `mod` expressions.
- [ ] Instead, add library functions for them.
- [ ] Refactor tests etc.

**Comment by magnus-madsen** [comment]
@stephentetley Thanks Stephen

**Comment by magnus-madsen** [comment]
@stephentetley I think this solved now?

Are there other expressions we should consider "demoting" to "just" functions?

**Comment by stephentetley** [comment]
It's solved in the compiler - will the VsCode extension have them as keywords?

**Comment by magnus-madsen** [comment]
> It's solved in the compiler - will the VsCode extension have them as keywords?

Apparently they were never keywords to begin with.
