### ISSUE TITLE
Add region to `MutSet`, `MutList`, etc?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5350]
I think maybe `MutSet` and friends should keep a reference to their region. This would make it easier to work with e.g. #5349.

**Comment by stephentetley** [comment]
I'll take a look at this if no-one's started on it.

**Comment by stephentetley** [comment]
PR #5428 

`MutList` and `MutDeque` already had a region in the enum so only `MutMap` and `MutSet` needed work doing.

**Comment by magnus-madsen** [comment]
Fixed right?
