### ISSUE TITLE
Should `slice` functions (Array.slice, String.slice, etc.) have named arguments?

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#5393]
Should `slice` functions have named arguments? 

Currently Array.slice is:

~~~

pub def slice(r1: Region[r1], b: Int32, e: Int32, a: Array[a, r]): Array[a, r1] \ { Read(r), Write(r1) } =

~~~

However I forgot that the third parameter was "end" and not "length" so had a a bug until I checked the implementation.

~~~

pub def slice(r1: Region[r1], start: {start = Int32}, end: {end = Int32}, a: Array[a, r]): Array[a, r1] \ { Read(r), Write(r1) } =

~~~

**Comment by magnus-madsen** [comment]
I think so yes.

**Comment by stephentetley** [comment]
Thanks Magnus - I'll use named params for Vector and can look at changing the other versions after Vector is done.

**Comment by stephentetley** [comment]
Now a PR... #5427

**Comment by magnus-madsen** [comment]
Fixed in master.
