### ISSUE TITLE
Remove syntax for bitwise operations in favor of functions?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5397]
Do we want to demote bitwise operations, e.g. `>>>` to normal functions? Dropping their explicit syntax. 
I think this would be a reasonable simplification. I don't see why a modern primarily functional language would have explicit syntax for these.

**Comment by mlutze** [comment]
Also exponentiation?

**Comment by stephentetley** [comment]
Possibly the bitwise operations don't even need "symbolic" names?

With Java (and so Flix) not having unsigned integer types maybe bit shifting is always going to be very rare.

**Comment by magnus-madsen** [comment]
I think there are still some operators left to consider.

**Comment by magnus-madsen** [comment]
- BitwiseOr
- BitwiseXor
- BitwiseAnd

should probably also go.

**Comment by magnus-madsen** [comment]
And also complement.

**Comment by magnus-madsen** [comment]
@stephentetley Would you be interested in removing the remaining bitwise operations?

**Comment by stephentetley** [comment]
Yes I'll look at it after `instanceof`.

**Comment by stephentetley** [comment]
I should have a PR ready tomorrow (Thursday, 26), I've done the work I just need to update the branch to head.

**Comment by magnus-madsen** [comment]
Fixed in master.
