### ISSUE TITLE
Broken assumption of restrictable variant implementation

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#5398]
In the typing of choose(*) we assume that the index variable of an enum does not occur within its other type parameters. Below is a program where that is not true. I've not forced the unsoundness into an example, I've hit timeouts while trying.
```
restrictable enum Expr[s][t] {
    case Cst(Bool)
    case Var(t)
    case Not(Expr[s][t])
    case And(Expr[s][t], Expr[s][t])
    case Or(Expr[s][t], Expr[s][t])
    case Xor(Expr[s][t], Expr[s][t])
}

def map(f: a -> b \ ef, e: Expr[s][a]): Expr[s][b] \ ef = choose* e {
    case Expr.Cst(b) => Expr.Cst(b)
    case Expr.Var(x) => Expr.Var(f(x))
    case Expr.Not(x) => mkNot(map(f, x))
    case Expr.And(x, y) => mkAnd(map(f, x), map(f, y))
    case Expr.Or(x, y) => mkOr(map(f, x), map(f, y))
    case Expr.Xor(x, y) => mkXor(map(f, x), map(f, y))
}

def mkNot(e: Expr[s][t]): Expr[s ++ <Expr.Not>][t] = {
    open Expr.Not(open_as Expr e)
}

def mkAnd(e1: Expr[s1][t], e2: Expr[s2][t]): Expr[s1 ++ s2 ++ <Expr.And>][t] = {
    open Expr.And(open_as Expr e1, open_as Expr e2)
}

def mkOr(e1: Expr[s1][t], e2: Expr[s2][t]): Expr[s1 ++ s2 ++ <Expr.Or>][t] = {
    open Expr.Or(open_as Expr e1, open_as Expr e2)
}

def mkXor(e1: Expr[s1][t], e2: Expr[s2][t]): Expr[s1 ++ s2 ++ <Expr.Xor>][t] = {
    open Expr.Xor(open_as Expr e1, open_as Expr e2)
}

def embedExpression(e: Expr[s][t]): Expr[s][Expr[s][t]] = {
    map(_t -> e, e)
}
```

**Comment by JonathanStarup** [comment]
@magnus-madsen @mlutze 

Also see that map can be typed when guiding the unification :D

**Comment by magnus-madsen** [comment]
Can you explain better what the issue is?

**Comment by JonathanStarup** [comment]
In choose* typing:
1. We type the bodies with `E[case_i][targs_i...]` (`case_i` is the index var of the case and `targs_i` is a list or type arguments for the case)
2. We construct an unconstrained output type `E[index_out][targs_out...]`
3. We unify all `targs_i` with `targs_out`. This would normally not influence the index of the output, but here, the targs contain our index variable so something wrong _could_ happen here 

After looking at it with Matt, we couldn't observe any unsoundness so maybe its not a problem. We don't have proof that its okay or that its not okay

**Comment by magnus-madsen** [comment]
What about this?
