### ISSUE TITLE
[Backend] Introduce Block and Goto

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#542]
We would like to support more efficient compilation of pattern matching. We can achieve this by adding a restricted form of blocks and jumps.

We introduce a new symbol type `Symbol.LabelSym` and two new expressions:

```scala
 case class Branch(exp: Expression, branches: Map[Symbol.LabelSym, Expression], ...)
```

and 

```scala
case class JumpTo(sym: Symbol.LabelSym, ...)
```

Each are expressions and have a type and a source location.

A `Jump` expression must occur nested inside a `Block` expression.

We can define the semantics in terms of an interpreter. We equip the interpreter with a new table `labels: Map[Symbol.LabelSym, Expression]` and whenever the interpreter encounters the expression `Jump(sym)` it selects `sym` from the `labels` tabel and evaluates its expression. Similarly, when the interpreter encounters `Block(branches)` it overwrites the `labels` map to include the new branch targets.

***Open Question:*** Can a jump only target its inner most block?

We can now change the generated code for pattern matching.

Given:

```scala 
match x with {
  case PATTERN_1 => BODY_1
  case PATTERN_2 => BODY_2
  ...
  case PATTERN_N => BODY_N
}
```

we generate:

```scala
Block(
  branches = Map(
    case1 -> if (PATTERN_1 OK) BODY_1 else (goto case2),
    case2 -> if (PATTERN_2 OK) BODY_2 else (goto case3),
    ...
    caseN -> if (PATTERN_N OK) BODY_N else (goto unmatched),
    unmatched -> MatchError
    ), 
  default = case1
)
```

We can easily generate this code by first creating the labels `case1`, `case2`, ..., `caseN` and `unmatched` and then we can generate each expression afterwards.

**Comment by magnus-madsen** [comment]
I will add this to the SimplifiedAst and ExecutablAst and then we can add code generation support.

**Comment by magnus-madsen** [comment]
@mhyee Its been a while since we looked at pattern matching. Do you have 2 cents on this, or is it too far away?

@FlaminGuy Do you foresee any problems with code generation for `Block` and `Jump`?

**Comment by mhyee** [comment]
I have some stupid questions:

- Is this an improvement because we're using (structured) gotos and not a bunch of lambdas? I think we discussed this at some point, but I don't remember if we had a good reason for not doing it. (Other than lack of time.)

- How do you handle variable binding and scope? For example:

```scala
match (42, "foo") with {
  case (x, _) => let y = x; ...
  case (_, x) => let z = x; ...
}
```

- It seems like this should work for nested pattern matching, but I'd still try a small example and see what happens.

**Comment by magnus-madsen** [comment]
Thanks for your time.

> Is this an improvement because we're using (structured) gotos and not a bunch of lambdas? I think we discussed this at some point, but I don't remember if we had a good reason for not doing it. (Other than lack of time.)

We *may* gain two benefits: (1) We can avoid alot of closure creation. Looking at the generated code *a lot* of closures are generated and passed around. However, it could be that the JIT deals with these efficiently, so we cannot know if we will gain any speedup. (2) We gain the ability to do tail recursive calls. Currently even the simplest function, which uses pattern matching, cannot be tail recursive since the lambdas obscure the tail recursive call.

> How do you handle variable binding and scope? For example:

Each case becomes essentially this:

```
 if (PATTERN_1 OK) BODY_1 else (goto case2)
```

Here `BODY_1` includes code to unwrap/destruct a tag or tuple. So, the generated code looks something like this:

```
if (matchVar is Cons) let tmp = untag matchVar; ... else (goto case2).
```

> It seems like this should work for nested pattern matching, but I'd still try a small example and see what happens.

I believe so, since the pattern tests just become boolean expressions.

**Comment by mhyee** [comment]
I remember now (mostly): our assumption was that by compiling each case into its own method, the JIT could do a better job at optimizing the code, rather than try to optimize a giant method with a bunch of gotos. We never tested this hypothesis (but implementing this task would let us evaluate!), and it was based on anecdotes about the Scala compiler.

Speaking of which, I wonder how Dotty does it.

> We may gain two benefits: (1) We can avoid alot of closure creation. Looking at the generated code a lot of closures are generated and passed around. However, it could be that the JIT deals with these efficiently, so we cannot know if we will gain any speedup. (2) We gain the ability to do tail recursive calls. Currently even the simplest function, which uses pattern matching, cannot be tail recursive since the lambdas obscure the tail recursive call.

I would not be surprised if lambdas are handled efficiently, because of `invokedynamic`. But supporting tail recursion is a pretty compelling reason.

**Comment by magnus-madsen** [comment]
Yes, we will learn! But the thing is, even in a bit pattern, you could always take:

```
match x with {
  case PATTERN_1 => BODY_1
  case PATTERN_2 => BODY_2
  ...
  case PATTERN_N => BODY_N
}
```

The non-tail recursive `BODY_X` and extract them to separate functions to reduce the size of the function. It is only the pattern matching code (which is probably often small) and the tail recursive calls that would need to stay in the function itself.

**Comment by magnus-madsen** [comment]
I have added two ast nodes:

```scala
case class Branch(exp: ExecutableAst.Expression, branches: Map[Symbol.LabelSym, ExecutableAst.Expression], tpe: Type, loc: SourceLocation)

case class JumpTo(sym: Symbol.LabelSym, tpe: Type, loc: SourceLocation)
```

@FlaminGuy will you add backend support (in a separate PR) and then afterwards I can rewrite the pattern matching code to use labels and jumps which hopefully will give us a big boost in performance.

**Comment by magnus-madsen** [comment]
@mhyee @FlaminGuy 

Speedup with branches and labels:

Bench | Factor
-- | --
benchmark01 | 1.2
benchmark02 | 2.0
benchmark03 | 2.0
benchmark04 | 1.4
benchmark05 | 1.2
benchmark06 | 1.2
benchmark07 | 1.4
benchmark08 | 1.6
benchmark09 | 1.3
benchmark10 | 1.2
benchmark11 | 1.2
benchmark12 | 1.2
benchmark13 | 1.8
benchmark14 | 1.6
benchmark15 | 1.1
benchmark16 | 1.0
benchmark17 | 1.1
benchmark18 | 1.3
benchmark19 | 1.4
benchmark20 | 1.5

**Comment by magnus-madsen** [comment]
Implemented.
