### ISSUE TITLE
Remove `ArraySlice` from compiler

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5431]

**Comment by magnus-madsen** [comment]
I think `Array.slice` should really just be `copyOfRange` (?)

**Comment by magnus-madsen** [comment]
@stephentetley Do you want to give this a stab? 

I think we simply need to rename `copyOfRange` to `slice` and then delete code from the compiler.

**Comment by magnus-madsen** [comment]
I started something here: https://github.com/flix/flix/pull/5453 but its not finished.

**Comment by magnus-madsen** [comment]
@jaschdoc Want to take a stab at this?

**Comment by jaschdoc** [comment]
Sure!
