### ISSUE TITLE
Repurpose `Array` pattern matches for `Vector`s?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5435]

**Comment by mlutze** [comment]
I think the slicing ones might be too much. We probably don't want to encourage O(n) pattern matches.

**Comment by magnus-madsen** [comment]
OK, so pattern matches should be O(1). This suggests that we could only pattern match on an exact-sized array. 

But that does not seem very useful, so perhaps better not to have pattern matching at all. (We also don't have it on Chains or Sets).

(Note that one could have views of vectors, since they are immutable, but I digress...)

**Comment by magnus-madsen** [comment]
https://github.com/flix/flix/issues/5440
