### ISSUE TITLE
Refactor `CompletionProvider`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5437]
- [x] Split `CompletionProvider` into several providers.
- [x] Refactor each new Provider into a class.

Add the following interface:

```
trait Completer {
  def matches(context: CompletionContext): Bool
  def excluded(context: CompletionContext): Bool
  def getCompletions(...): Iterable[Completion]
}
```

**Comment by magnus-madsen** [comment]
@LukasRonn I think there are two more completers we can extract:

- `HoleCompleter` and 
- `FromErrorCompleter`.

**Comment by magnus-madsen** [comment]
Once that is done, I would like to see these next steps:

Refactor the signature of `Completer` from:

```scala
def getCompletions(implicit context: CompletionContext, flix: Flix, index: Index, root: Option[TypedAst.Root], delta: DeltaContext): Iterable[Completion]
```

to

```
def getCompletions(ctx: CompletionContext)(implicit flix: Flix, index: Index, root: TypedAst.Root): Iterable[Completion]
```

(I have made the `root` non-Optional, hence inside `LanguageServer` we should only call `autoComplete` if there is a `root`.

**Comment by magnus-madsen** [comment]
We should also change `Completion.toCompletionItem` to:

```scala
def toCompletionItem(ctx: CompletionContext)(implicit Flix: flix)
```

so we can get rid of these two objects from the different completion data types.

**Comment by LukasRonn** [comment]
Yes,

I'll start from the top and work my way down. :)

**Comment by LukasRonn** [comment]
When the last PR is merged, all tasks regarding refactoring of `CompletionProvider` should be done. :)
