### ISSUE TITLE
Should StringBuilder carry around a region token?

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#5456]
The mutable collections `MutList` and friends now carry around a region token, should (mutable) `StringBuilder` do the same?

**Comment by magnus-madsen** [comment]
Do rule of thumb is: A region is a capability token ("permission") to allocate memory in its associated region.

If a mutable data structure needs to allocate additional memory, in the same region in which it was created, then it should hang onto its token. 

If there is no such need there is typically no need.

In the case of `StringBuilder` I don't know.

**Comment by stephentetley** [comment]
Thanks Magnus. 

A (growing) `StringBuilder` will want to _claim_ more memory to grow in, but all that memory is encapsulated in the `StringBuilder` and isn't exposed to the outside world. Because the memory is internal I'm not sure if "claiming" more is exactly the same as allocating.

**Comment by magnus-madsen** [comment]
Yeah, it if comes from Java then it does its own thing.

**Comment by magnus-madsen** [comment]
So, I think we do not need this.

**Comment by stephentetley** [comment]
Thanks - I was just writing to say I agree.
