### ISSUE TITLE
Add syntactic sugar for `Applicative`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5462]
Something like:

```
enum JSON
enum ParseError 

def parseName(_: JSON): Validation[ParseError, String] = ???
def parseAge(_: JSON): Validation[ParseError, Int32] = ???

def run1(json: JSON): Validation[ParseError, String] = 
    forSomething (
        name <- parseName(json); 
        age  <- parseAge(json)
    ) yield {
        "Hello ${name}. You are ${age} years old!"
    }
```

where we need to find a good keyword for `forSomething`.

**Comment by magnus-madsen** [comment]
We could rename `for` to `forM` and then call this `forA`. Just saying...

**Comment by magnus-madsen** [comment]
@stephentetley I am trying to understand what would be the correct desugaring of the above `forSomething` in Flix.  Can you offer any advice?

**Comment by stephentetley** [comment]
@magnus-madsen I'll have a think, `forSomething ... yield` looks quite close to Idiom brackets...

**Comment by magnus-madsen** [comment]
I am wondering if it is just lift the body and then `<*>`.

**Comment by stephentetley** [comment]
Strictly applicative translations would follow these examples: 

~~~

// Case 1.
forSomething (
    nameA <- expA 
) yield {
    expY/{freevars: nameA}
}
=> ((nameA -> expY(nameA)) <$> expA)

// Case 2.
forSomething (
    nameA <- expA;
    nameB <- expB
) yield {
    expY/{freevars: nameA, nameB}
}
=> (((nameA, nameB) -> expY(nameA, nameB)) <$> expA) <*> expB


// Case 3.
forSomething (
    nameA <- expA;
    _     <- expB;
    nameC <- expC
) yield {
    expY/{freevars: nameA, nameC}
}
=> ((((nameA, nameC) -> expY(nameA, nameC)) <$> expA) *> expB) <*> expC

~~~

Haskells applicative-do allow for data dependencies (which are monadic) see sections 22 and 2.3 as to how they can be desugared:

https://simonmar.github.io/bib/papers/applicativedo.pdf

For simplicity `forSomething ... yield` could outlaw data dependencies.

**Comment by magnus-madsen** [comment]
I think the translation gets messy when there are many variables. I was looking at:

https://typelevel.org/cats/typeclasses/applicative.html

And wondering if we would want to add `mapN`, e.g. : 

```
...
def map3(f: (a, b, c) => d, x1: F[a], F[b], F[c]): F[d]
...
```

I think this would be an easy starting point that could be improved on later. We could go to N=10 after which you would get an error. Then, when the need naturally arises, we could try a smarter desugaring.

Thoughts?

**Comment by stephentetley** [comment]
We already have the `liftA` family in Applicative - isn't that the `mapN` function?

**Comment by stephentetley** [comment]
Translating to `liftA` would need something extra to work with anonymous expressions (as per Case 3).

**Comment by magnus-madsen** [comment]
The last example seems useful.

**Comment by stephentetley** [comment]
Actually, I don't think anonymous expressions need to synthesize a variable name. I think they could just be underscore.

**Comment by magnus-madsen** [comment]
> Actually, I don't think anonymous expressions need to synthesize a variable name. I think they could just be underscore.

I think we can simply reuse whatever the programmer wrote.

**Comment by magnus-madsen** [comment]
@jaschdoc If you could take a stab at this next. That is, to add a `forA` construct:

```
forA (
    name <- parseName(json); 
    age  <- parseAge(json)
) yield {
    "Hello ${name}. You are ${age} years old!"
}
```

which desugars to:

```
Applicative.liftA2((name, age) -> "Hello ${name}. You are ${age} years old!",  parseName(json),  parseAge(json))
```

**Comment by magnus-madsen** [comment]
@stephentetley I am wondering if `liftAX` should not really be named `mapX` since they actually take both function and its arguments?

**Comment by stephentetley** [comment]
Haskell is a bit inconsistent with itself - `liftM` and `liftA` lift (pure) function applications to their following inputs, but `liftIO` and `MonadTrans.lift` monadic actions into another monad.

I think changing Flix's `liftX` functions to `mapX` would be fine.
