### ISSUE TITLE
Future of `for`, `forA`, and `forM`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5464]
I propose that we support three `for`-constructs: one applicative and one monadic, and one that infers whether its applicative or monadic. 

The form of `for`, `forA`, and `forM` are:

```
forX (
  x <- f();
  y <- g();
) yield x + y
```

- A `forA` will require an applicative instance.
- A `forM` will require a monad instance.
- A `for` will either require an applicative or monad depending on whether the expressions are independent.

Note the syntax is designed such that its easy to switch between the three. 
Note also that one cannot use the "wrong" syntax because the desugaring requires appropriate instances on the various type classes. For example, if one were to use `forM` with `Validation` the typer would complain.

> Why do we need this?

We want sugar for working with `Result` and `Validation`-- i.e. for both monads and applicatives. We only have for monads.

> Why not just `for` then?

Two reasons: 

- Explicit is better than implicit, by having `forA` and `forM` programmers can be explicit about what they want. 
- For teaching and understanding, `forA` and `forM` make clear what is going on.

> But why then `for`?

- Because experienced programmers -- who understand applicatives and monads -- need concise syntax.
- Because sometimes "leaving it up to the system" is fine.

> Why not `afor` and `mfor`? 

I think they look ugly. Other suggestions are welcome.

**Comment by stephentetley** [comment]
Sounds good - I definitely prefer `forA` to `afor`.
