### ISSUE TITLE
Add ability to reference external classes without requiring them to be passed to flix as dependencies.

### ISSUE THREAD

**Issue by Sintrastes** [flix/flix#5478]
I'm not sure if this is possible/reasonable, but I thought I'd ask, as it seems like this might be a more straightforward way than [this ticket](https://github.com/flix/flix/issues/2359) to get some interop (Java calling Flix) that would be useful in attempting to call flix from an Android project.

The idea is, I'd like to be able to compile code like:

```
def main(): Unit \ { IO } =
    import new com.myorg.SomeClass(): ##com.myorg.SomeClass \ IO as newSomeClass;
    import com.myorg.SomeClass.callback(x: Int32): Unit \ IO as callback;
    
    callback(newSomeClass, 42)
```

in Flix, where I don't actually pass in a jar/class file where `com.myorg.SomeClass` or `com.myorg.SomeClass.callback()` are defined, so I am free to define those classes in Java, such that when I add the built Flix jar as a dependency to my Android project and call `Main.main()` from Flix to register this callback, all the classes will be resolved properly. 

This obviously wouldn't be great behavior by default, so maybe this could be a flag such a `-XNoDependencyChecking`.

**Comment by magnus-madsen** [comment]
Most compilers, including Flix, do not allow "linking" against unknown code because it could violate type safety.

In your example, `callback` is supposed to take an `Int32`, but what if that was a typo, and it actually takes a `String`?

But lets see we allow ignore that and hope the best; Another problem is then that the above type signature might not contain enough information because Java has both class methods and interfaces methods, and we need to know what is what to generate the right bytecode.

**Comment by magnus-madsen** [comment]
So while I appreciate the usefulness of the feature, I am not sure we can readily add it.

**Comment by Sintrastes** [comment]
@magnus-madsen That makes sense. In the mean-time, a work-around I've found is essentially just to put a jar with compiled stub definitions for the classes I need to reference in `libs`.

**Comment by magnus-madsen** [comment]
@Sintrastes Nice. Do you have anything up and running? :)

**Comment by Sintrastes** [comment]
@magnus-madsen Not quite, but I think I'm close.

**Comment by magnus-madsen** [comment]
Roger. I'd be happy to see a screenshot if/when it works :)

**Comment by Sintrastes** [comment]
@magnus-madsen Posted this to gitter, but figured I'd post here as well in case you didn't see it. 
![hello_flix](https://user-images.githubusercontent.com/4064213/220183317-9b94c198-8820-4ae6-bd72-3c7d7fa555e4.png)
