### ISSUE TITLE
Use `Vector` in Datalog engine

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5484]
Each in their own PR:
- [ ] As a replacement for `List` in `Fixpoint/Ram`
- [ ] As the return type of `factsX` in `Solver.flix`.
- [ ] As a replacement for `List` in `Fixpoint/Ast`

**Comment by JonathanStarup** [comment]
https://github.com/flix/flix/blob/master/main/src/library/Fixpoint/Tuple/Tuple.flix

This should also be replaced by Vector

**Comment by sockmaster27** [comment]
I'm having some trouble with the `factsX` part. After replacing the type in the Flix source I naturally get the error:
```
#
# An unexpected error has been detected by the Flix compiler:
#
#   Unable to unify: 'PredSym -> (Datalog[Boxed] -> Vector[t111892])' and 'PredSym -> (Datalog[Boxed] -> List[Bool])'.
...
```
I find it very hard to tell where exactly in the compiler the `List` type is specified. I know it ends up [here](https://github.com/flix/flix/blob/19c1bafe2de9fd3e61394c5835c74785ee861361/main/src/ca/uwaterloo/flix/language/phase/Lowering.scala#L815), but I'm struggling with finding out where this `tpe` originates from.

**Comment by magnus-madsen** [comment]
@sockmaster27 I suggest we look at it together in person.

**Comment by magnus-madsen** [comment]
Also have a look here:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Typer.scala#L1865
