### ISSUE TITLE
Split `Stratifier` into two phases: `Dependencies` and `Stratifier`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5503]
... and use `SoftFailure`

**Comment by magnus-madsen** [comment]
@JonathanStarup This is obviously not urgent.

**Comment by JonathanStarup** [comment]
Dependencies creates a LabelledGraph, how should that be given to the stratifier phase?

**Comment by magnus-madsen** [comment]
Add it to TypedAst.Root and make it empty initially.
