### ISSUE TITLE
Package Management Test Matrix

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5510]
Assume we have some project configuration that uses both Flix packages and Maven packages.

- [ ] Shell works on Windows
- [ ] Shell works on Linux
- [ ] Shell works on MacOS
- [ ] Commandline works on Windows
- [ ] Commandline works on Linux
- [ ] Commandline works on MacOS
- [ ] VSCode works on Windows
- [ ] VSCode works on Linux
- [ ] VSCode works on MacOS
- [ ] Only downloads missing dependencies.
- [ ] Works while offline.
- [ ] Packager produces Flix packages that are compatible with the dependency manager.

**Comment by magnus-madsen** [comment]
@AnnaBlume99 I plan to use this as we safely integrate into Flix.

(You are on Windows right?, so Ill ask people with Linux/Mac help test).

**Comment by AnnaBlume99** [comment]
Yes I am using Windows

**Comment by mlutze** [comment]
If there are non-manual tests, e.g. for the command line, we may be able to run them in CI on different platforms (https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on)

**Comment by magnus-madsen** [comment]
No issues reported :)
