### ISSUE TITLE
VSCode doesn't pass arguments to shell

### ISSUE THREAD

**Issue by mlutze** [flix/flix#5522]
e.g. --Xno-bool-effects is not having an effect on the shell

**Comment by magnus-madsen** [comment]
"Where" are you setting these arguments?

**Comment by mlutze** [comment]
In the extension settings

**Comment by magnus-madsen** [comment]
How to reproduce:

1. Check out the flix/vscode-flix project and run it (F5).
2. Go to Extensions -> Flix -> Extension Settings -> Enter "--Xstatistics" in "Extra Flix Args"
3. Exit the Window (File -> Close Window)
4. Hit F5 again
5. Open a directory with a flix file and open the file.
6. Observe that in "Output" it prints a bunch of stuff like:
```
ParYield,7
Region,3
ArrayNew,2
PutChannel,2
NewChannel,1
Spawn,1
ArrayStore,1
VectorLoad,1
```
7. Goto "Terminal" and select "REPL"
8. Notice that the command is `java -jar c:\\tmp\\flix2\\flix.jar repl` which lacks the `--Xstatistics` flag.
9. Debugging can start in the function named "createSharedRepl". 
10. Ultimately less than 10 lines of code should be needed to fix the issue.
