### ISSUE TITLE
Resolve Transitive Dependencies

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5551]
Phase 1:
- [x] We should change GitHub releases to be a pair: (pkg, toml) file. In GitHub terminology I think this means there should be two "Assets" associated with every release. We need to be able to download and store each as two separate actions.
- [x] The repo https://github.com/magnus-madsen/helloworld now has both fpkg and toml.
- [x] Magnus will ask people to update their releases.

Phase 2:
- [x] We should download all TOML files our dependencies (transitively). Thus, at the end, we will have a set of `project-v123.toml` files floating around. 

Phase 3:
- [x] We should then compute set of Flix packages to download and download them. In this case, because we only use fixed versions, we will download 1 Flix pkg per toml file.

Phase 4:
- [x] We extract all Maven dependencies from the downloaded TOML files and feed them into the maven dependency resolution in one go.

**Comment by magnus-madsen** [comment]
@AnnaBlume99 I believe this is now done, right?

**Comment by AnnaBlume99** [comment]
Yes it should be :)
