### ISSUE TITLE
False redundancy errors

### ISSUE THREAD

**Issue by mlutze** [flix/flix#5557]
The new error aggregation stuff replaces expressions with error nodes, but this eliminates knowledge of uses of symbols, and causes false redundancy errors.

We can:
1. Disable redundancy errors when other errors are present
2. Store a list of used symbols in the error node

Option 2 seems much more in the spirit of the error aggregation path.

**Comment by mlutze** [comment]
Storing the locations of the used symbols could also help support hovering even when the nodes are errors

**Comment by magnus-madsen** [comment]
Disable redundancy for that particular function in the same manner as using `???`?

The problem with (2) is that its hard to compute in all the places an error might occur... And what happens when you want other information stored there too?

**Comment by magnus-madsen** [comment]
We might want a list of when Expr.Error is really used.

**Comment by mlutze** [comment]
> (3) Disable redundancy for that particular function in the same manner as using `???`?
> 
> The problem with (2) is that its hard to compute in all the places an error might occur... And what happens when you want other information stored there too?

3 doesn't work for e.g. uses of defs and enums, things external to the function.

IMO just listing the symbol locations gives the majority of useful info. We can add them all to the index and token provider.

**Comment by mlutze** [comment]
It should be easy to get symbols for any expression after resolver
