### ISSUE TITLE
`List.map2` semantics

### ISSUE THREAD

**Issue by mlutze** [flix/flix#5558]
The `List.map2` function IMO has strange semantics, performing the function `f` on each pair in the product of `l1` and `l2`.

Those used to the OCaml stdlib will find this strange, since the OCaml `map2` function effectively zips the lists and performs the function pairwise.

**Comment by magnus-madsen** [comment]
Well, we use `mapX` for applicative map now...

And you have `zipWith` no?

**Comment by mlutze** [comment]
Yes, I guess `zipWith` is the name for it. I just think that it complicates things to use this common-ish name for a different function.

**Comment by jaschdoc** [comment]
Maybe `mapProduct` would be clearer?

**Comment by mlutze** [comment]
Note also the difference between `List.product` and `Applicative.product` :)

**Comment by magnus-madsen** [comment]
I think we need to rid ourselves of `product` (of the integer kind). It is a rare use case anyway.
