### ISSUE TITLE
Refactoring `ErasedAst` - Continued

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5564]
Overall Goal: In preparation for some later, more difficult refactorings, we want to move every expression which is _not_ introducing or using a variable _or_ a control expression into one of the `Intrinsic` types.

I believe the following can be moved to `IntrinsicX`.
- [ ] `Closure`.
- [ ] `Unary` - naturally just becomes an Intrinsic1.
- [ ] `Binary` - naturally just becomes an Instrinsic2.
- [ ] `ScopeExit`

The rest I think we are either variable introductions/uses or affect control.

- Maybe we can desugar `IfThenElse` to `Branch` and `JumpTo`?
- Not sure what to do about `NewObject` (?)

Later: 

- [ ] In `ErasedAst.scala` change `ErasedAst.Expression` to just `Expression.
- [ ] Rename `Erased.Expression` -> `ErasedAst.Expr`.

Debate:
- [ ] We could merge `IntrinsicX` into one type foregoing a bit of type safety?

**Comment by jaschdoc** [comment]
> Maybe we can desugar `IfThenElse` to `Branch` and `JumpTo`?

I'm not sure how you would go about this. There is no way to generate code that tests the condition in the `if` expression with the `ErasedAst`. Otherwise we would have the make something that's equivalent to `IfThenElse` which is just a unnecessary relabeling.
Also, the `Branch` Ast node relies on `IfThenElse` when being generated.

**Comment by magnus-madsen** [comment]
@JonathanStarup Could I ask you take a look at `ErasedAst` and help inform us what further changes we should make to enable an "easy" refactoring towards AE/fine-grain CBV? 

(My plan is to whip `ErasedAst` into a specific shape and then go backwards through the compiler doing the same to the preceding ASTs).
