### ISSUE TITLE
Remove `X.product` functions

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5567]
Remove:

- [ ] Array.product / Array.productWith
- [ ] Chain.product / Chain.productWith
- [ ] DelayList.product / DelayList.productWith
- [ ] ...

Note we are removing functions that compute the multiplication of integers, i.e. functions approximately of the form `f[Int32] -> Int32].

Not all functions named product. E.g. we keep `Applicative.product`.

**Comment by jaschdoc** [comment]
What about the `sum` / `sumWith` functions? It seems reasonable to remove those as well now that we're at it.

**Comment by magnus-madsen** [comment]
The `sum` and `sumWith` functions are still useful.

I think the point was that `product` and `productWith` are much less likely to be used and their names clash with another function we want to call `product`. That was their reason for removal.
