### ISSUE TITLE
Refactor `Char.toInt32` and `Char.fromtInt32` to not use `unsafe_cast`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5582]
If that is possible?

**Comment by magnus-madsen** [comment]
@mlutze @JonathanStarup I tried to find a Java method that does the trick, but maybe you are better at Googleling than me?

**Comment by mlutze** [comment]
I think there are problems with this since Java uses UTF-16, which means that conversion from an Int is a partial function. Java has `Character.toChars` which seems like a total function since it returns an array of characters. `Character.codePointAt` is the inverse.

**Comment by magnus-madsen** [comment]
I decided to delete them (if possible).
