### ISSUE TITLE
Packager requires LICENSE.md

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#5585]
When building a fpkg the packager requires a LICENSE.md. Maybe it should allow anything with `LICENSE` in the name or simply `LICENSE.md`, `LICENSE`, `LICENSE.txt`. Perhaps it shouldn't be required at all. At any rate, I found this slightly annoying when building an fpkg.

**Comment by magnus-madsen** [comment]
Working as intended. 

If I allow you to call the file whatever you want then there would be inconsistencies and you could have multiple license files.

**Comment by jaschdoc** [comment]
What about just `LICENSE` (no file ending) which quite common on GitHub?

**Comment by magnus-madsen** [comment]
I would say markdown seems better in every way.

**Comment by jaschdoc** [comment]
It seems to me that some licenses have formatting in the source file, which sometimes collides markdown and GitHub. For instance, GitHub doesn't recognize that Flix has an Apache 2.0 License. It does, however, see that there is a license file.
