### ISSUE TITLE
Strange `flix init` behavior in existing project

### ISSUE THREAD

**Issue by mlutze** [flix/flix#5588]
When I run `flix init` in an existing project, the following happens:

* `src/Main.flix` is created
* `test/TestMain.flix` is created
* `flix.toml` is created
* `LICENSE.md` is **MODIFIED** to contain both the default text and new text
* `README.md` is **MODIFIED** to contain both the default text and new text

**Comment by magnus-madsen** [comment]
I thought it should bail by saying there is already a project?

**Comment by magnus-madsen** [comment]
This should be fixed.
