### ISSUE TITLE
Possible bug related to stratification of non-atoms

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#560]
Consider the program:

```
        rel A(x: Int)
        rel B(x: Int)
        rel R(x: Int)

        A(1).
        A(2).
        A(3).

        B(3).

        R(x) :- A(x), not B(x). // rule1

        false :- not R(1).  // rule2
        false :- not R(2).  // rule3
        false :- R(3).  // rule4
```

Here I would expect rule2-4 to be put into stratum 3, but they are put into stratum 0.

**Comment by magnus-madsen** [comment]
Probably something needs to happen here:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala#L120

**Comment by magnus-madsen** [comment]
@jmittert Hello Jason, I don't know if you have time or interest. But perhaps you could take a look at this.

However, #559 needs to be merged in first (to enable stratification in the solver), which will happen in a few days at most.

**Comment by jmittert** [comment]
Sure, looks like #559 is merged, so I'll take a look this weekend.
