### ISSUE TITLE
Add basic support for regexs to the stdlib?

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#5614]
I thought there already was a issue to add regexs to the standard library but I can't find it...

I've had a library for a couple of years now - `flix-regex` - that wraps Java's `java.util.regex` package but it has never really been nice enough for general use. The sticking point has always been that Java's `java.util.regex.Matcher` is quite imperative and should be wrapped as a monad (or maybe an iterator or effect...) but monad support in Flix is still pretty raw.

However I think we can get a very useful initial regex API for Flix by not exposing `Matcher` at all and providing just two modules: one wrapping `java.util.regex.Pattern` and the other a module of utility functions like Flix's `String` except using `Pattern` instead of `String` in functions like `replace`, `startsWith` etc. :

~~~

pub def split(pattern: {pattern = Pattern}, s: String): List[String]
pub def replaceFirst(from: {from = Pattern}, to: {to = String}, s: String): String
pub def replace(from: {from = Pattern}, to: {to = String}, s: String): String
pub def startsWith(prefix: {prefix = Pattern}, s: String): Bool

~~~

We can add something that wraps `java.util.regex.Matcher` when monads (or effects) are a bit more settled in Flix.

I've `Pattern` and the majority of the String API already written, the latter needs disentangling from `flix-regex` but I hope to have it done over the weekend.

**Comment by magnus-madsen** [comment]
What's the reason that `java.util.regex.Matcher` is stateful?

If it is to cache the compiled state machine then that might be something that could benefit from language support.

I am thinking 
```
let pat = regex"abc*"
```

which instructs the compiler to build a cached `Matcher` for the regex while also checking -- at compile-time -- that the regex is valid. 

I would be happy to merge in a pure API (then later would could do something like the above). 

In terms of functionality, what functions should we offer?

**Comment by stephentetley** [comment]
`java.util.regex.Matcher` is basically an iterator with some fancy additions (and it doesn't quite match Java's `iterator` interface). 

> let pat = regex"abc*"

... should produce a `Pattern` rather than a `Matcher`. `Matcher` needs a `Pattern` and an input string - its position in the input string is the `Matcher` state. `Pattern` is a compiled and presumably optimized regex - the `Pattern` object actually has the factory method for `Matcher` (`Matcher` itself doesn't have a constructor though it could easily have one). 

Java has `MatchResult` which is like a frozen snapshot of the state of the `Matcher` - unfortunately it doesn't work with named capture groups - for that reason I think we should ignore it in Flix. I've used an "evaluator monad" in my higher level Regex library to access named and indexed captures (the evaluator monad is essentially a mini parser combinator library), but this is a bit raw for the stdlib.

With compile time regexs, capture groups could be very cute combined with (algebraic) pattern matching - I think F# has this through active patterns - e.g. bind the names within a capture group:

~~~

match "Tetley, Stephen" {
    case Pattern#"(?<last>\\p{Alpha}+), (?<first>\\p{Alpha}+)" => { firstName = first, lastName = last }
    ...
}

~~~

This might be outside the scope of Java's Pattern module unfortunately and would need a parser in Scala - I don't think you can query a `Pattern` to return all capture names or upper bound of indexed captures.
