### ISSUE TITLE
Add Regular Expression Constants

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5634]
- [ ] Add a new `Ast.Constant.Regex(java.lang.String)` class (after `Str`).
- [ ] Add a new `ParsedAst.Constant.Regex` class.
- [ ] Extend the parser to allow the syntax `regex"string"`.
- [ ] In `Weeder` check that the string is a valid regex (by compiling it with Java).
- [ ] Add a new type constructor `Regex`.
- [ ] In the `Lowering` phase replace `Ast.Constant.Regex` with an `InvokeStatic` to `Pattern.compile`.

(Later we can extend the compiler to cache the result of `Pattern.compile` somewhere.)

**Comment by magnus-madsen** [comment]
@stephentetley Would you be interested in this? (Otherwise I can ask Jakob.)

**Comment by stephentetley** [comment]
Thanks Magnus - I'd be open to trying in about two months, but I really need to get my libraries working again with Flix head so that's my immediate priority.

**Comment by magnus-madsen** [comment]
Of course. Sorry for all the churn. Hopefully the package manager, which arrives soon, will help a bit.

**Comment by stephentetley** [comment]
I've started looking at this and have gone through the parser and weeder so far.

**Comment by mlutze** [comment]
Thanks Stephen! Feel free to open a PR while it's in progress.

**Comment by stephentetley** [comment]
Thanks Matthew, I've just made a WIP PR.

**Comment by stephentetley** [comment]
The PR now compiles and passes tests: #5707

**Comment by magnus-madsen** [comment]
Fixed in master.
