### ISSUE TITLE
Add support for external JARs to `flix.toml`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5638]

**Comment by magnus-madsen** [comment]
@stephentetley Can you help explain exactly what is needed? Is it enough with the ability to point to a URL/path?

**Comment by stephentetley** [comment]
I'd like / need to be able to include jars that aren't hosted on Maven and are "co-developed" with a Flix library. Ideally I'd like to keep the Java src and the Flix source in the same project. E.g. 

https://github.com/stephentetley/interop-base

At the moment provide the compiled `jar` of the Java part of the project and bundle it in `lib`. I could certainly make the jar a release so that have an immutable url.

**Comment by magnus-madsen** [comment]
Got it. I think we will allow you a way to specific a link to an immutable URL for a JAR file. 

You can still keep the Java sources together with the Flix source, but -- at least for now -- it would be up to other tooling to build the jar and upload it to that URL.

**Comment by magnus-madsen** [comment]
By the way, what features are missing from interop for these things to be in Flix itself?

**Comment by stephentetley** [comment]
I think all the wrappers are just to get round the array marshaling bug - #3332.

**Comment by magnus-madsen** [comment]
> I think all the wrappers are just to get round the array marshaling bug - #3332.

If you can confirm this is the major holdup, I can try to see if we can get it resolved.

**Comment by magnus-madsen** [comment]
Follow-up question: Is this mostly for string arrays or could it be all kinds of Java arrays?

**Comment by stephentetley** [comment]
I think it can be for all types of java array as I wrapped List<OpenOption> in this file:

https://github.com/stephentetley/interop-base/blob/26886d98944cefbbbd38b826acca0f8def455223/src-java/flixinterop/nio/file/Filesz.java#L36

**Comment by magnus-madsen** [comment]
I got confused about the tickets, but I have a fix coming. See https://github.com/flix/flix/issues/3332

**Comment by magnus-madsen** [comment]
(even with the fix we should still support custom jars)

**Comment by Sintrastes** [comment]
It would also be nice to be able to point to a specific dir (instead of or in addition to `lib`) where jars can be found.

This is incredibly useful for Android support, as it means we don't have to manually copy `android.jar` for the particular Android SDK version we are interested in into `lib`.

**Comment by magnus-madsen** [comment]
```
[jar-dependencies]                                  # Dependencies on Flix packages.
"url:https://google.com/foo.jar"              = "something here?"
```

**Comment by AnnaBlume99** [comment]
Flix and Maven dependencies have two sections - one for normal dependencies and one for dev-dependencies. Should there be two types of jar-dependencies as well?

**Comment by magnus-madsen** [comment]
> Flix and Maven dependencies have two sections - one for production dependencies and one for development dependencies. Should there be two types of jar-dependencies as well?

Hm. Do we actually use the dev ones? Not yet right?

I think we should just allow it in the ordinary sections for now.

**Comment by AnnaBlume99** [comment]
> > Flix and Maven dependencies have two sections - one for production dependencies and one for development dependencies. Should there be two types of jar-dependencies as well?
> 
> Hm. Do we actually use the dev ones? Not yet right?

Currently all the dependencies are tagged with either "Production" or "Development" when parsing them, but they are all treated exactly the same after that.

**Comment by AnnaBlume99** [comment]
> ```
> [jar-dependencies]                                  # Dependencies on Flix packages.
> "url:https://google.com/foo.jar"              = "something here?"
> ```

It is not possible to have a key in a table without a value, so either we have to write:
`[jar-dependencies]                                  # Dependencies on Flix packages.
"url:https://google.com/foo.jar"              = "..."`
where "..." can be anything and is just ignored, or we have to have a different way of doing it. Maybe it could be as a list:
`[other-dependencies]                                  # Dependencies on Flix packages.
"jar"              = ["url:https://google.com/foo.jar"]`
What do you think?

**Comment by magnus-madsen** [comment]
Let use the key as the filename!:

```
[jar-dependencies]                                  # Dependencies on Flix packages.
"a.jar" = "url:https://google.com/foo.jar"
"b.jar" = "url:https://yahoo.com/foo.jar"
```
