### ISSUE TITLE
Brainstorm Eager/Lazy Functor

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5642]
```
enum Eval[a: Type, ef: Bool] {
    case Eval(Unit -> a \ ef)
}

def defer(f: Unit -> a \ ef): Eval[a, ef] = Eval(f)

def map(f: a -> b \ ef1, e: Eval[a, ef2]): Eval[b, ef1 and ef2] = match e {
    case Eval(g) => Eval(_ -> f(g()))
}


def unsafeRun(e: Eval[a, ef]): a \ ef = match e {
    case Eval(f) => f()
}

// pub class GradedFunctor[m: Bool -> Type -> Type] {
//     pub def map(f: a -> b \ ef1, x: m[ef, a]): m[ef and ef1, b]
// }

```

**Comment by mlutze** [comment]
Here's my idea for an over-generalized version using associated types:

```scala
class FancyFunctor[m: Type -> Type] {
    type ImmEff[m, ef: Eff]: Eff        // the immediate effect of mapping over this type
    type Out[m, ef: Eff]: Type -> Type  // the output type

    pub def map(f: a -> b \ ef, x: m[a]): Out[m, ef, b] \ ImmEff[m, ef] = ???
}

instance FancyFunctor[List] {
    type ImmEff[List, ef] = ef
    type Out[m, ef: Eff] = List

    pub def map(f: a -> b \ ef, List[a]): List[b] \ ef
}

instance FancyFunctor[MutList[r]] {
    type ImmEff[MutList[r], ef] = {r, ef}
    type Out[MutList[r], ef] = MutList[r]

    pub def map(f: a -> b \ ef, x: MutList[r, a]): MutList[r, b] \ {r, ef} = ???
}

instance FancyFunctor[a -> _ \ ef] {                    // partially-applied function constructor
    type ImmEff[a -> _ \ ef, ef2] = Pure                // no immediate effect
    type Out[a -> _ \ ef, ef2] = a -> _ \ {ef, ef2}     // add the effect to the set

    pub def map(f: b -> c \ ef2, x: a -> b \ ef): (a -> c \ {ef, ef2}) \ Pure = ???
}
```

Probably impractical since it could in principle allow mapping to different type constructors

**Comment by magnus-madsen** [comment]
If this actually works, it might be interesting for the paper at least.

**Comment by mlutze** [comment]
Note that it requires a little bit more than basic associated types since ImmEff and Out have multiple parameters. It is not yet clear to me whether this is a problem.

**Comment by Sintrastes** [comment]
Is the idea that this definition will eventually replace the current `Functor`?

I guess I'm just thinking a bit longer term in terms of a more general version of `Monad`/`Applicative`, and the monadic/applicative foreach syntaxes.

If eventually there is both a `GradedFunctor`, `Functor`, `Applicative`, `GradedApplicative`, etc... how do we deal with name conflicts with the typeclass members? 

In my experiments (`IxFunctor`, which is similar to @magnus-madsen 's `GradedFunctor`) I've been using an `ix` prefix (e.x. `ixMap`), but that seems a little clunky. One of the reasons effect polymorphism is nice is we don't have to worry about distinctions like `map` v.s. `mapM` in Haskell, but if we have two separate hierarchies for graded v.s. non-graded, it seems like we reproduce that problem.  

But I guess maybe @mlutze 's example (or something similar to it) might solve this problem by encompassing both cases.

**Comment by Sintrastes** [comment]
I can think of at least four different "flavors" of the functor/applicative/monad/etc... typeclass hierarchy that might be useful:

1. Non-effectful only, e.x:

```
class Functor[m] {
    def map(f: a -> b, x: m[a]): m[b]
}
```

2. The current approach, totally effect polymorphic.

```
class Functor[m] {
    def map(f: a -> b \ ef, x: m[a]): m[b] \ ef
}
```

3. A generalization of the current approach where the type is graded over effects:

```
class Functor[m] {
    def map(f: a -> b \ ef, x: m[ef, a]): m[b] \ ef
}
```

4. Examples where a type is a functor only in the context of a specific (specified) effect:

```
class Functor[m, ef] {
    def map(f: a -> b \ ef, x: m[ef, a]): m[b] \ ef
}
```

**Comment by Sintrastes** [comment]
Then again, I'm not sure all four of these cases are actually necessary. Less may be sufficient in practice, and I think what @mlutze came up might be general enough to deal with at least all of the examples I've come across when trying to build an FRP library.

**Comment by magnus-madsen** [comment]
You raise many interesting questions. I think this a research-level problem and we don't have any answers yet :) I'd be happy to see related literature, if there is any.

There seems to be an inherent tension between eagerness and laziness and how that is reflected in the types. In a sense this is good because it exposes the nature of the code. For example, the current Flix `functor` is clear that the effect must happen immediately when you apply `map`.

Did you check out Stephens graded monad lib? It sounds like he has experiments similar to yours:

https://github.com/stephentetley/graded-lib/tree/master/src

While not helpful to your specific challenges, we are currently trying to address a related challenge:

We have both `List[t]` and `MutList[r, t]` and we would like both to be `Functor`. Currently that is impossible because they do not have the same kind. We hope we can fix this with "associated effects" (which are similar to "associated types" which themselves are similar to multi-param type classes). Its possible a complex use of associated effects could also unify the different type classes, but less clear if such a unification would be workable.

**Comment by magnus-madsen** [comment]
In any case, I created this ticket because we are looking into it, but I unfortunately I don't have any answers for you yet. I would try to start out with your own type classes (or perhaps Stephen's) and if they are a "good fit" when can explore whether they can be integrated and/or unified.

**Comment by Sintrastes** [comment]
For what it's worth, from the definition of "graded category" I came up with in my [MS thesis](https://digitallibrary.tulane.edu/islandora/object/tulane%3A90929/datastream/PDF/view), I think the most natural notion of (endo)functor would align fairly closely with the existing definition in Flix -- mapping preserves the grade (effect).

However, in my larger unfinished draft of my thesis and notes (which I had to whittle down considerably due to time constraints / my sanity), I explored a few more general definitions of graded category which might end up reproducing more general notions of "graded functor". I'd have to look at some of my old notes and see what might be relevant. I think I remember a notion of "partially grade-preserving functor" at least, which I think would correspond to cases where effects are preserved, but an additional effect is introduced

I'm assuming you're probably familiar with the research surrounding [granule](https://github.com/granule-project/granule). From what I remember, they were mostly concerned with resources usage and linear types, but I think they did a few things that might be relevant to graded effect systems. It's been awhile since I've really dug into their work.

**Comment by magnus-madsen** [comment]
> For what it's worth, from the definition of "graded category" I came up with in my [MS thesis](https://digitallibrary.tulane.edu/islandora/object/tulane%3A90929/datastream/PDF/view), I think the most natural notion of (endo)functor would align fairly closely with the existing definition in Flix -- mapping preserves the grade (effect).

Interesting. I should take a look.

> I'm assuming you're probably familiar with the research surrounding [granule](https://github.com/granule-project/granule). From what I remember, they were mostly concerned with resources usage and linear types, but I think they did a few things that might be relevant to graded effect systems. It's been awhile since I've really dug into their work.

No, but thanks for the pointer.

**Comment by magnus-madsen** [comment]
@Sintrastes 
We will continue this work/research offline, but we can send you a draft of our ideas, once we have it :)

**Comment by magnus-madsen** [comment]
@mlutze Will you make sure these notes are in the paper draft?
