### ISSUE TITLE
Add let-bindings to for- and related constructs

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#5663]
Basically just add `pat = exp` as a let binding as suggested by @mlutze. They also have this in Scala.

**Comment by magnus-madsen** [comment]
Its a bit annoying that `<-` is two chars and `=` is one, for alignment.

**Comment by mlutze** [comment]
IMO matching Scala would be nice as it's less surprising to a user. (By the way, allowing braces here would be nice, for the same reason.)

**Comment by magnus-madsen** [comment]
I wish we could solve the alignment issue. I think that is important.

**Comment by jaschdoc** [comment]
What about `:=`? We could also just use `=` for both assignments and generators and then desugar the expression after typing

**Comment by mlutze** [comment]
> What about `:=`? We could also just use `=` for both assignments and generators and then desugar the expression after typing

`:=` is strange since it's the reference assignment operator and implies mutation, which is not really happening here.

I don't think we can use `=` for both: there's no good way to disambiguate between the cases since it could be that you want a `Result[X, Y]` in the middle rather than unpacking it to a `Y`.

**Comment by mlutze** [comment]
Any more thoughts on this? It's pretty painful adding `point` everywhere.

**Comment by mlutze** [comment]
I also think that alignment is not a big issue since variables with different name lengths mess up alignment anyway.

**Comment by jaschdoc** [comment]
Agreed. I think alignment was the blocking factor (which I think is not really a big issue)

**Comment by mlutze** [comment]
Pinging this one again. It's been identified by a user as an annoyance.

**Comment by magnus-madsen** [comment]
@mlutze @JonathanStarup @jaschdoc What syntax do we want here? Just:

```
x = 123; y <- ...; z = ...
```

Not sure what to think.

**Comment by mlutze** [comment]
IMO matching Scala is least surprising

**Comment by jaschdoc** [comment]
> IMO matching Scala is least surprising

I agree with this.


Additionally, should we allow for-comprehensions to start with let-binding and / or if-else expressions? I.e., we only require that it contains *at least one* `x <- xs` fragment.

**Comment by jaschdoc** [comment]
We could also make let-bindings more explicit:

```flix
foreach (
    x <- xs;
    let (a, b) = (1, 2);
    y <- ys
) yield ...
```

**Comment by mlutze** [comment]
> > IMO matching Scala is least surprising
> 
> I agree with this.
> 
> 
> Additionally, should we allow for-comprehensions to start with let-binding and / or if-else expressions? I.e., we only require that it contains *at least one* `x <- xs` fragment.
> 
> (I think `forA` is special as it cannot contain if-else expressions at all)

I'm not sure if starting with an `if` is ever useful, is it?

For `let`, I can see it somewhat useful in that the scope of the bound variable is reduced, but it would be nice to have an example of where that comes up

**Comment by magnus-madsen** [comment]
I don't think for-comprehensions should be allowed to start with if or let.

Second, I think we should use the let keyword, so that if you want a normal binding inside a for you have to write let.

Lets make these changes, then we can merge in, and iterate later.
