### ISSUE TITLE
Add a `release` command to simplify package management

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5669]
The idea is that the command should bundle the project into a `fpkg` file and upload a release to GitHub using the GitHub API.

**Comment by magnus-madsen** [comment]
- Explore a bit how cargo does it.

**Comment by sockmaster27** [comment]
Do we have the information of which Git(hub) repository the current project belongs to? If we don't, can it be inferred or should it be included in the flix.toml?

**Comment by magnus-madsen** [comment]
(optionally)

**Comment by sockmaster27** [comment]
Okay, then the process would be:
1. Check if GitHub repo and version number is supplied by flix.toml
2. Compute new version number
3. Ask for confirmation: "Release version 1.2.3 of github:user/repo? [y/n]"
4. Update flix.toml with new version number
5. Commit change to GitHub with a message like "release version 1.2.3" and tag
6. Compile project and create release

Do we currently have any way of writing back into the flix.toml file?

**Comment by sockmaster27** [comment]
> I guess we would need to store such information in the toml

Alternatively, we could look in `.git/config`. It looks like this:
```
[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
[submodule]
	active = .
[remote "origin"]
	url = https://github.com/sockmaster27/flix.git
	fetch = +refs/heads/*:refs/remotes/origin/*
...
```
Not sure exactly what format this is, but it doesn't seem like too much work to get to that `https://github.com/user/repo.git` and extract the information from there. 
Then we wouldn't have to clutter the toml, and it would probably work better when forking and such,

**Comment by sockmaster27** [comment]
Or if we don't want to rely on parsing, we could instead bet on the fact that git is installed and launch `git ls-remote --get-url origin`

**Comment by magnus-madsen** [comment]
Your overall plan with the steps sound good. But I may I propose a simplified approach that we implement first:

1. User runs flix release
2. We ask/prompt for version and repository
3. We push the artifact to that repository

This way we can start with implementing the barebones of the GitHub API stuff before considering everything around it.

**Comment by magnus-madsen** [comment]
@mlutze CC

**Comment by magnus-madsen** [comment]
(In any case, let us _not_ depend on .git). 

It is possible to have a different git setup but still pushing to another GitHub repo.

**Comment by sockmaster27** [comment]
>     2. We ask/prompt for version and repository

Shouldn't we then just start by implementing a `release` sans `major`/`minor`/`patch` that looks at the version in the toml?

**Comment by magnus-madsen** [comment]
> > ```
> > 2. We ask/prompt for version and repository
> > ```
> 
> Shouldn't we then just start by implementing a `release` sans `major`/`minor`/`patch` that looks at the version in the toml?

Ah yes, lets do that! So we just need to prompt for the repo?

**Comment by sockmaster27** [comment]
Wouldn't it almost be easier to add it to the toml straight away?

**Comment by magnus-madsen** [comment]
> Wouldn't it almost be easier to add it to the toml straight away?

If you want. I guess its an optional field? What should it be called and what is its form?

We would need to extend tests etc.

**Comment by sockmaster27** [comment]
I was just thinking like 
```
github = "user/repo"
```

**Comment by mlutze** [comment]
How do you want to deal with authentication? Just the existing API key option?

**Comment by magnus-madsen** [comment]
> How do you want to deal with authentication? Just the existing API key option?

Yes.

**Comment by magnus-madsen** [comment]
@sockmaster27 I would like to have this to have priority.

**Comment by sockmaster27** [comment]
Should the assets only include than the `.fpkg` or also the flix.toml?

**Comment by magnus-madsen** [comment]
May I suggest that we change `github` field to: `repository` which can then have a value like `github:magnus-madsen/foo`.

This seems more future proof and more inline with how the other parts of `flix.toml` is designed.
