### ISSUE TITLE
Data.Map.intersectionWith should have a more polymorphic type

### ISSUE THREAD

**Issue by athas** [flix/flix#5689]
Currently the combination operator is `a -> a -> a` (plus effect boilerplate), but I argue it should be `a -> a -> b`.

**Comment by stephentetley** [comment]
Haskell has an even more general type for `intersectionWith`:

~~~

intersectionWith :: Ord k => (a -> b -> c) -> Map k a -> Map k b -> Map k c 

~~~

**Comment by athas** [comment]
Oh yeah, that's better.  Please do that.

**Comment by stephentetley** [comment]
I'll take a look at this...

**Comment by stephentetley** [comment]
Now a PR:

https://github.com/flix/flix/pull/5830

**Comment by magnus-madsen** [comment]
Fixed in master.
