### ISSUE TITLE
Eliminate BigInt/BigDecimal/Regex in `Simplifier`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5709]
In the `Simplifier` phase, we want to replace operations on `BigInt/BigDecimal/Regex` with direct calls to `InvokeMethod` and `InvokeStatic`.

- [x] BigDecimal
- [x] BigInt
- [ ] Regex

**Comment by magnus-madsen** [comment]
I wonder if these are even needed in the AST at all...

**Comment by magnus-madsen** [comment]
For example, can we implement `Add` for `BigInt` (`Add.flix`) directly with import?

**Comment by jaschdoc** [comment]
*import* as in Java import?

**Comment by magnus-madsen** [comment]
Compare:

```
instance Add[Int64] {
    pub def add(x: Int64, y: Int64): Int64 = $INT64_ADD$(x, y)
}

instance Add[BigInt] {
    pub def add(x: BigInt, y: BigInt): BigInt = $BIGINT_ADD$(x, y)
}

instance Add[String] {
    pub def add(x: String, y: String): String =
        import java.lang.String.concat(String): String \ {};
        (x `concat` y)
}

```

**Comment by magnus-madsen** [comment]
I think we can get simply get rid of ` $BIGINT_ADD$(x, y)` no?

**Comment by magnus-madsen** [comment]
We only need to keep the literals as part of the language/compiler.

**Comment by jaschdoc** [comment]
Yeah, I think you are probably right.

**Comment by magnus-madsen** [comment]
I think that would be very nice. Want to try it out for `BigInt.add` and see how it goes?

**Comment by jaschdoc** [comment]
Yes, I'll do it after https://github.com/flix/flix/pull/5828

**Comment by jaschdoc** [comment]
I'm not sure where the regex stuff in `Simplifier` is. I took a brief look at it, and there does not seem to be any regex related code there.

**Comment by magnus-madsen** [comment]
I think there is some constant
