### ISSUE TITLE
Remove `compileBinaryExpr` in `GenExpression`

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#5713]
"Flatten" `compileBinaryExpr` by matching on the semantic operator and generating JVM instructions directly.

- [x] Refactor `compileArithmeticExpr`
- [x] Refactor `compileExponentiateExpr`
- [x] Refactor `compileComparisonExpr`
- [x] Refactor `compileLogicalExpr`
- [x] Refactor `compileBitwiseExpr`
- [ ] Investigate if type hierarchy in `SemanticOperator` can be refactored to have fewer branches. E.g. `Int8.Add` up to `Int32.Add` (inclusive) all share the same JVM instruction, so maybe they can have one immediate common super type.

@magnus-madsen could you add `student-programmer` label and assign this to me?

**Comment by magnus-madsen** [comment]
I think we should able to:

- Inline `readVar`
- Inline `compileUnaryExpr`
- Combine `visitComparisonPrologue` and `visitComparisonEpilogue` into one function that takes two instructions (?) (or one instruction, I am confused).
- 


Can we comment the uses of e.g. `I2D`? What does it do?

**Comment by jaschdoc** [comment]
> Combine `visitComparisonPrologue` and `visitComparisonEpilogue` into one function that takes two instructions (?) (or one instruction, I am confused).

Maybe just a function that takes a lambda that generates the correct instructions (both the method call on the visitor and the number of instructions vary).

**Comment by magnus-madsen** [comment]
> > Combine `visitComparisonPrologue` and `visitComparisonEpilogue` into one function that takes two instructions (?) (or one instruction, I am confused).
> 
> Maybe just a function that takes a lambda that generates the correct instructions (both the method call on the visitor and the number of instructions vary).

I think that would make the code much more complicated to understand.

**Comment by jaschdoc** [comment]
> > > Combine `visitComparisonPrologue` and `visitComparisonEpilogue` into one function that takes two instructions (?) (or one instruction, I am confused).
> > 
> > 
> > Maybe just a function that takes a lambda that generates the correct instructions (both the method call on the visitor and the number of instructions vary).
> 
> I think that would make the code much more complicated to understand.

Okay, so just leave it as is?

**Comment by magnus-madsen** [comment]
Why can it not be a function that takes two arguments?

**Comment by jaschdoc** [comment]
Because the number of instructions "in the middle" vary along with method calls. `BigInt` is quite different from `Char`:

https://github.com/flix/flix/blob/d588421a711f34db6158a4401631ba2e4880e34d/main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala#LL385C7-L385C7

https://github.com/flix/flix/blob/d588421a711f34db6158a4401631ba2e4880e34d/main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala#L463

Otherwise, we should match on the semantic operator again or have some parameters that have type `Option[...]`, e.g.
```scala
def genComparison(op: Option[Insn], const: Option[Insn], cmp: Option[Insn]): Unit = ???
```

**Comment by magnus-madsen** [comment]
BigInt will go away with #5709. Does that solve the problem?

**Comment by jaschdoc** [comment]
No. `String` still uses a method call, requiring 3 instructions and Float operations require 2 instructions whereas 8-32 bit ints (along with char and bools) require only 1 instruction.

**Comment by magnus-madsen** [comment]
Maybe we should special case those?

**Comment by magnus-madsen** [comment]
But perhaps this can wait till after https://github.com/flix/flix/issues/5709

**Comment by jaschdoc** [comment]
Sure, but Floats still take up quite a lot of space. Maybe we just add 2 additional functions `genPrimitiveComparison` and `genFloatComparison`?

**Comment by magnus-madsen** [comment]
> Sure, but Floats still take up quite a lot of space. Maybe we just add 2 additional functions `genPrimitiveComparison` and `genFloatComparison`?

Yes.

**Comment by magnus-madsen** [comment]
The goal is to have simple, stupid code that everyone can understand.

**Comment by magnus-madsen** [comment]
There were still a few lose ends to tie up right?

**Comment by jaschdoc** [comment]
Correct :)
