### ISSUE TITLE
Remove `ParsedAst.Declaration.Relation` and `ParsedAst.Declaration.Lattice`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5769]
Objective:

- Remove `ParsedAst.Declaration.Relation`
- Remove `ParsedAst.Declaration.Lattice`

How:
- Remove all code that uses these (e.g. in `Parser` and further down in the compiler pipeline).
- Refactor the few examples that are left which use this feature.

**Comment by 2022H1030042G** [comment]
Hi, I would like to work on it. Is it available?

**Comment by magnus-madsen** [comment]
> Hi, I would like to work on it. Is it available?

Yes. That would be nice.

Let me know if you need any help and feel free to open a pull request while the work is in progress 👍

**Comment by 2022H1030042G** [comment]
@magnus-madsen , Can you give some details like where the changes are required and how to implement those changes?

**Comment by magnus-madsen** [comment]
I would start by opening `ParsedAst.scala` and then remove the two case classes outlined above. Then I would recompile which would give some compiler errors and then I would carefully remove that code too.

**Comment by 2022H1030042G** [comment]
From what I can understand, initially these two lines needs to be removed?:

https://github.com/flix/flix/blob/42d2f6a8c6f1d3b6761f1fa31637125dd657876f/main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala#L215

https://github.com/flix/flix/blob/42d2f6a8c6f1d3b6761f1fa31637125dd657876f/main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala#L228

**Comment by magnus-madsen** [comment]
Yes

**Comment by 2022H1030042G** [comment]
Are there any proper instructions that you can share while setting up the project locally?

**Comment by magnus-madsen** [comment]
Did you try https://github.com/flix/flix/blob/master/docs/BUILD.md ?

**Comment by 2022H1030042G** [comment]
Yes, I did. When I compile it, I believe it works fine, but when running tests using class 'TestAll' nothing happens, the icon keeps on loading. The screenshots of both compilation and Testing are attached.

1. Compilation: ![compiling,](https://user-images.githubusercontent.com/17452290/234172288-a38f61ca-8d34-4902-8d44-ebcf220418cc.png)

2. Testing:
![testing](https://user-images.githubusercontent.com/17452290/234172548-eb431610-72b4-48b9-9cbf-f14c41c99f96.png)

**Comment by mlutze** [comment]
It looks like tests are being run using Gradle. Can you verify step 3.ii. from the build directions again?

**Comment by 2022H1030042G** [comment]
Here is a screenshot for the same:

![build directions](https://user-images.githubusercontent.com/17452290/234203861-133dadb5-6ccc-4794-803c-eca919ea543c.png)

**Comment by mlutze** [comment]
![tmp](https://user-images.githubusercontent.com/19153692/234205044-441b5393-673f-475c-a25d-0958ae8cbcfa.jpg)

You should be able to change these to IntelliJ IDEA.

**Comment by 2022H1030042G** [comment]
@magnus-madsen @mlutze , after removing the line mentioned above I am able to compile the files successfully, but there are 14 test cases that have failed.

**Comment by 2022H1030042G** [comment]
Sure, please refer: #5783

**Comment by magnus-madsen** [comment]
Fixed in master.
