### ISSUE TITLE
UseCompleter does not work if the module ends with a dot

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5802]

**Comment by magnus-madsen** [comment]
@LukasRonn Perhaps you can take a look.

**Comment by JonathanStarup** [comment]
I have a random wish for uses and i don't know where to put it. Its about "backwards" suggestions
```
use flatM_    ---> suggest: Monad.flatMap
mod A.B { def f(): Unit = () }
use B.f_  --> suggest: A.B.f
```

**Comment by magnus-madsen** [comment]
> I have a random wish for uses and i don't know where to put it. Its about "backwards" suggestions
> 
> ```
> use flatM_    ---> suggest: Monad.flatMap
> mod A.B { def f(): Unit = () }
> use B.f_  --> suggest: A.B.f
> ```

This is difficult. But we can put it on the wish list.

**Comment by LukasRonn** [comment]
> I have a random wish for uses and i don't know where to put it. Its about "backwards" suggestions
> 
> ```
> use flatM_    ---> suggest: Monad.flatMap
> mod A.B { def f(): Unit = () }
> use B.f_  --> suggest: A.B.f
> ```

What change do you want to see? What should it suggest instead?

**Comment by LukasRonn** [comment]
> @LukasRonn Perhaps you can take a look.

Can you maybe elaborate a little bit about the issue?
