### ISSUE TITLE
Storage and scale

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [flix/flix#582]
If I am posting this question in the wrong place, please let me know.

I am new to Flix. I hope to use it as a Datalog server for a knowledge graph application. It might have to deal with big graphs, maybe a few million nodes. Is that kind of use case feasible?

**Comment by magnus-madsen** [comment]
Hello Jeffrey,

Thanks for your interest in Flix. At the moment, the performance of the Datalog engine has not been our primary focus. The implementation is not poor, it does use the right algorithms and it is parallel, but it has not been optimized aggressively yet. We have used it with several hundreds of thousands of facts. However, if you plan to have millions of facts (or more) I would look elsewhere for now. My best bet would be the Souffle Datalog engine or perhaps bddbdd. You are of course welcome to try out Flix and see if it scales, and if not to give us more information, although we cannot guarantee to fix any performance issues quickly.

**Comment by magnus-madsen** [comment]
You are welcome to join us on https://gitter.im/flix/Lobby for more info.
