### ISSUE TITLE
LiftedAst should carry effects for Array* Expressions

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5820]
i.e. it should have a `pur` field like all other expressions which is derived from the Typer.

**Comment by jaschdoc** [comment]
I think it already does this since array expressions are now under `Expr.ApplyAtomic` which has a `pur` / effect field.

**Comment by magnus-madsen** [comment]
Hmm. Indeed. Are the effects correct though? Then should be pure for vectors

**Comment by jaschdoc** [comment]
I'll double check.

**Comment by magnus-madsen** [comment]
Ah but should be pure

**Comment by magnus-madsen** [comment]
The ones from vector

**Comment by jaschdoc** [comment]
Roger. I think they were still impure before switching to `AtomicOp`, though. I will change it to `Pure`
