### ISSUE TITLE
Ast.Purity should have two types of impurity: Control and Other

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5821]

**Comment by JonathanStarup** [comment]
I think one complication is that pure functions can use control things inside that influence the compilation of those expressions. Calls to these functions here cannot always be treated the same
```
def f(): Int32 = 42
def f(): Int42 = try {
    do Fail()
} handle {
    case fail(k) => k(42)
}
```

**Comment by JonathanStarup** [comment]
Fixed on master
