### ISSUE TITLE
Use `Ast.CallType` in `LiftedAst`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5824]
- [ ] Merge `ApplyClo` and `ApplyCloTail` using `Ast.CallType` to distinguish them (i.e. `ApplyCloTail` is a tail call).
- [ ] Ditto for `ApplyDef` and `ApplyDefTail`.

You can see how it looks in `ErasedAst`.

**Comment by jaschdoc** [comment]
Same of OccurrenceAst?

**Comment by magnus-madsen** [comment]
Yeah why not
