### ISSUE TITLE
Rework `SemanticOperator.StringOp`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5835]
- [ ] Remove `SemanticOperator.StringOp.Eq` -- replace by TC instance
- [ ] Remove `SemanticOperator.StringOp.NotEq` -- replace by TC instance
- [ ] Desugar `Concat` to `InvokeMethod`.

**Comment by mlutze** [comment]
Why not make concat a TC instance too?

**Comment by magnus-madsen** [comment]
Can we?

**Comment by magnus-madsen** [comment]
We build strings internally, would be a bit annoying.

**Comment by magnus-madsen** [comment]
@jaschdoc Where did we end up?

**Comment by jaschdoc** [comment]
We eliminated `StringOp.Eq/Neq` so we only have `Concat` left in the compiler.

Short summary of new / changed behavior:
`StringOp.Eq` is necessary for checking equality when pattern matching, but during compilation we instead generate code that invokes the `Eq` instance on Strings at runtime. The TC instance is implemented via Java's `String.equals` method.

**Comment by magnus-madsen** [comment]
Roger.
