### ISSUE TITLE
Nix flakes and packages

### ISSUE THREAD

**Issue by yzia2000** [flix/flix#5843]
I was wondering if we could package the builds on nixpkgs and or create a nix flake for this project so it can be easy for users and developers to get started with using or contributing to the programming language

**Comment by magnus-madsen** [comment]
I think someone already packaged the compiler for Nix. Is that what you had in mind?

**Comment by yzia2000** [comment]
> I think someone already packaged the compiler for Nix. Is that what you had in mind?

Ah I just noticed the Flix package in the unstable channel.

Then I was wondering if we could add a flake to the project with derivations and shell commands along with dependencies that will be required for development.

**Comment by magnus-madsen** [comment]
> Then I was wondering if we could add a flake to the project with derivations and shell commands along with dependencies that will be required for development.

I am afraid I don't know what that means :)

Maybe `doc/BUILD.md` can be used as a starting point?

**Comment by magnus-madsen** [comment]
I believe there is a nix package now.

https://search.nixos.org/packages?channel=unstable&show=flix&from=0&size=50&sort=relevance&type=packages&query=flix
