### ISSUE TITLE
Update community build

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5845]
- [ ] Add `stephentetley/flix-either`
- [ ] Add `stephentetley/flix-time`
- [ ] Drop `magnus-madsen/helloworld`

Anything else?

**Comment by stephentetley** [comment]
`flix-time` has dependencies that are a long way from polished and it is unstable itself.

`stephentetley/flix-htmldoc` is a possible candidate. Currently it has a dependency on `data-lib` but that is now just really the `RoseTree` module. I can make `RoseTree` a separate project like `flix-either` then `flix-htmldoc` will have stable dependencies.

**Comment by magnus-madsen** [comment]
Ok; so should we add `st/flix-either` and `st/flix-htmldoc`?

**Comment by stephentetley** [comment]
> Ok; so should we add `st/flix-either` and `st/flix-htmldoc`?

Yes, thanks.

**Comment by magnus-madsen** [comment]
Thanks Stephen.

**Comment by stephentetley** [comment]
I've updated `flix-htmldoc` to use a dependency `stephentetley\flix-rosetree` that should be pretty stable.
