### ISSUE TITLE
Redesign effect syntax

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5858]
We are redesigning the effect syntax:

# Proposal 1:

Basic examples:
```scala
def foo(): Unit       // implicitly pure
def foo(): Unit \ {}  // explicitly pure
def foo(f: a -> b \ ef): Unit \ ef // effect polymorphic
```

Complex examples:
```scala
def foo(f: a -> b \ ef1, g: a -> b \ ef2): Unit \ (ef1 + ef2)
def foo(f: a -> b \ ef1, g: a -> b \ ef2): Unit \ (ef1 - ef2)
def foo(f: a -> b \ ef1, g: a -> b \ ef2): Unit \ (ef1 & ef2)
def foo(f: a -> b \ ef1, g: a -> b \ ef2): Unit \ (~ef1 + ef2)
def foo(f: a -> b \ ef1, g: a -> b \ ef2): Unit \ (ef1 + ef2 + {Print})
def foo(f: a -> b \ ef1, g: a -> b \ ef2): Unit \ (ef1 + ef2) + {Print, Throw}
def foo(f: a -> b \ ef1, g: a -> b \ ef2): Unit \ (ef1 + ef2) - {Print, Throw}
```

We allow two types of syntactic sugar:

(A) A singleton effect `{E}` can be written as just `E`:
```scala
def foo(f: a -> b \ ef1, g: a -> b \ ef2): Unit \ ef1 + ef2 + Throw
def foo(f: a -> b \ ef1, g: a -> b \ ef2): Unit \ ef1 + ef2 + Throw + Print
```

(B) The specific form `ef1 + ... efn + E1 ... + En` (and permutations thereof) can be written as: `{ef1, ..., efn, E1, ..., En}`.

```scala
def foo(f: a -> b \ ef1, g: a -> b \ ef2): Unit \ {ef1, ef2, Throw}
def foo(f: a -> b \ ef1, g: a -> b \ ef2): Unit \ {ef1, Print, ef2}
```

With type aliases:

```scala
type alias Foo[ef1, ef2] = ef1 - (~ef2)
def foo(f: a -> b \ ef1, g: a -> b \ ef2): Unit \ {ef1, ef2, Throw, Foo[ef1, ef2]}
```

With associated effects:

```scala
def foo(f: a -> b \ ef1, g: a -> b \ ef2): Unit \ {ef1, ef2, Throw, Iterable.Eff[a]}
```

Painful corner cases:
```scala
def foo(): Unit \ {-} // explicitly pure, non-standard syntax needed in non-`\` positions.

type alias EmptyRecord = {}
type alias PureEffect = {-}
type alias Foo = Bar[{-}]
```

**Comment by stephentetley** [comment]
What are the operators?

**Comment by mlutze** [comment]
> What are the operators?

Good question :)

- The `+` operator says "both of these effects are present". So it's "union" for set-type effects, and "and" for boolean-type effects.
- The `&` operator says "the intersection of these effects is present": "intersection" for sets, "or" for booleans
- The `~` operator is complement in the respective system: "set complement" for sets, "not" for booleans
- The `-` operator is syntactic sugar for `ef1 & (~ef2)` (likely more meaningful for the set system)

It is likely that vast majority of cases will only be using `+`.

**Comment by JonathanStarup** [comment]
Two small additions:
- I like proposal 2 without the braces, i.e. `Unit \ ef1 + ef2 + Print`
- I'd bring up an old comment from Jaco that `Unit \ {Print, Throw}` looks like you're subtracting print and from from the set `Unit`

**Comment by magnus-madsen** [comment]
We should keep in mind that a union of effects likely to be the most common annotation-- by far.

**Comment by mlutze** [comment]
I'm OK with 1 if we only allow vars and constants (qnames) inside sets.

I also think that instead of a weird `{-}` syntax, we should either:
- just make a built-in type called `Pure`, or
- Use kind inference to determine which one we mean

**Comment by magnus-madsen** [comment]
> I'm OK with 1 if we only allow vars and constants (qnames) inside sets.

OK. Let us do it then! (Once we are done with papers...)

> I also think that instead of a weird `{-}` syntax, we should either:
> 
>     * just make a built-in type called `Pure`, or

Let us just introduce a type alias called `Pure` (or hardcoded constant or whatever).

I still want to be able to write `{}` in a effect position though.

**Comment by magnus-madsen** [comment]
Fixed in master.
