### ISSUE TITLE
Infinite loop with type classes (again)

### ISSUE THREAD

**Issue by Release-Candidate** [flix/flix#5877]
This function `hmm` calls itself in an infinite loop instead of `SomeName.hmm`:
```flix
trait SomeName[a] {
    pub def hmm(x: a): a
}

instance SomeName[Int32] {
    pub def hmm(x: Int32): Int32 = ???
}

def hmm(x: a): a with SomeName[a] = SomeName.hmm(x)

@Test
def test(): Bool =
    Assert.eq(2, hmm(1))
```

See also https://github.com/flix/flix/issues/4618

**Comment by JonathanStarup** [comment]
Works (crashes) on master

**Comment by magnus-madsen** [comment]
> Works (crashes) on master

Sorry, it is not fixed then or what?

**Comment by JonathanStarup** [comment]
the bug was that there was a infinite loop instead of a crash. on master it crashes. so it seems fixed

**Comment by mlutze** [comment]
Crashes meaning HoleError, I assume
