### ISSUE TITLE
Drop the `opaque` modifier

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5887]
... but bring it back later...

**Comment by sockmaster27** [comment]
Does this include removing everything relating to opaque enums, or should it only be 'disabled' i.e. hidden from the public interface?

**Comment by sockmaster27** [comment]
Should I remove stuff like `case class OpaqueEnum ... extends ResolutionError` and the `getEnumAccessibility` function, or just leave them in?

**Comment by magnus-madsen** [comment]
> Should I remove stuff like `case class OpaqueEnum ... extends ResolutionError` and the `getEnumAccessibility` function, or just leave them in?

I would say yes, @mlutze What do you think?

My goal here is to pull things out that do not work and then we can always reintroduce them later once we have a clear understanding.

**Comment by mlutze** [comment]
Yes, that's fine. Though `getEnumAccessibility` will still need to exist, since there's still a difference between public and private.
