### ISSUE TITLE
Char - add wrappers for the JDK functions `getNumericValue`, `digit` and `forDigit`

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#5891]
Flix's Char module is missing functions to get the numeric values of characters representing digits e.g. '8' => 8.

I propose we add wrappers over Java `Character.getNumericValue` (both char and codepoint), `Character.digit` and `Character.forDigit`.

`Character.getNumericValue(char)` doesn't handle Unicode supplementary characters hence also include the code point version.

`Character.digit` and `Character.forDigit` allows alternative radices so they are more powerful than `getNumericValue`.

**Comment by magnus-madsen** [comment]
Fixed in master?

**Comment by stephentetley** [comment]
> Fixed in master?

Yes - I've been looking at wrapping some of the other code point functions in `java.lang.Character` but they'll need a bit more thinking about.
