### ISSUE TITLE
Refactor code generation for Arrays

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5917]
This is a hard one.

I would like to refactor the code generation for arrays (i.e. `Array*` in the AST).

I would like two things:

1. To get rid of all of this nonsense:

```
        if (elmType == MonoType.Str) {
          visitor.visitTypeInsn(ANEWARRAY, "java/lang/String")
        } else if (elmType.isInstanceOf[MonoType.Native]) {
          val native = elmType.asInstanceOf[MonoType.Native]
          val name = native.clazz.getName.replace('.', '/')
          visitor.visitTypeInsn(ANEWARRAY, name)
        } else if (jvmType == JvmType.Object) { // Happens if the inner type is an object type
          visitor.visitTypeInsn(ANEWARRAY, "java/lang/Object")
        } else { // Happens if the inner type is a primitive type
          visitor.visitIntInsn(NEWARRAY, AsmOps.getArrayTypeCode(jvmType))
        }
```

We need a more principled approach.

2. To properly support multidimensional arrays: https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-6.html

The key is to ensure that we always create arrays of the right type. 

This should be possible since we have all the information we need.

However, one simplification that might be useful would be to introduce a new `MonoType.ArrayMultiDim`:

```
  case class ArrayMultiDim(tpe: MonoType, dim: Int32) extends MonoType
```

Let me know if you have questions.

**Comment by magnus-madsen** [comment]
You might want to come up with a (written) plan before starting on the implementation.

**Comment by magnus-madsen** [comment]
@jaschdoc Are you up for this next? :)

**Comment by magnus-madsen** [comment]
Or would you rather work on another feature?

**Comment by JonathanStarup** [comment]
Ive looked at this a bit so if you need extra hands or opinions im here :)

**Comment by jaschdoc** [comment]
> @jaschdoc Are you up for this next? :)

Yes. I had delayed it until all the record stuff was wrapped up but I will start working on it soon :)

**Comment by magnus-madsen** [comment]
https://docs.oracle.com/javase/specs/jls/se7/html/jls-10.html
https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-6.html#jvms-6.5.multianewarray

**Comment by jaschdoc** [comment]
> ```scala
> case class ArrayMultiDim(tpe: MonoType, dim: Int32) extends MonoType
> ```
> 
> So now there's the two equivalent types `ArrayMulttiDim(Int, 2)` and `Array(Array(Int))`?

I have merged the two types in #6404

**Comment by JonathanStarup** [comment]
> I have merged the two types in #6404

That makes sense, but there's still `AMD(Int, 2)` and `AMD(AMD(Int, 1), 1)`

**Comment by JonathanStarup** [comment]
> To properly support multidimensional arrays

What is it that we don't support? I've forgot how it goes wrong

**Comment by jaschdoc** [comment]
> > I have merged the two types in #6404
> 
> That makes sense, but there's still `AMD(Int, 2)` and `AMD(AMD(Int, 1), 1)`

Yes, I suppose we could just examine the inner type `tpe` of `MonoType.Array(tpe)` and check if it is also an array type, to decide whether to emit a `multianewarray` or just a `anewrarray` instruction.

**Comment by magnus-madsen** [comment]
What we don't support: The Flix type `Array[Array[Int32]]` becomes an array objects that are `Array[Int32]`.

**Comment by magnus-madsen** [comment]
Is is just multianewarray? Will it not also require changes to other instructions?

**Comment by JonathanStarup** [comment]
> What we don't support: The Flix type `Array[Array[Int32]]` becomes an array objects that are `Array[Int32]`.

`Array[Object]` ?

> Is is just multianewarray? Will it not also require changes to other instructions?

So it's a performance thing? Wasn't there som interop typing issues

**Comment by magnus-madsen** [comment]
Its both performance and interop. A Java method could expect `int[][]` which we cannot currently create.

**Comment by JonathanStarup** [comment]
Hmm. It feels to me that we need two versions of `eraseType`. We don't we to generate the `Fn2Int32Array[Array[Int32]]` interface but when we erase things in certain contexts, like casting, we don't want to erase the outer layers of arrays.

**Comment by magnus-madsen** [comment]
> Hmm. It feels to me that we need two versions of `eraseType`. We don't we to generate the `Fn2Int32Array[Array[Int32]]` interface but when we erase things in certain contexts, like casting, we don't want to erase the outer layers of arrays.

There is no problem here: `Array[Array[Int32]]` is an object and so in the function its erased to object. Then later it is cast to its actual type.

**Comment by jaschdoc** [comment]
> Is is just multianewarray? Will it not also require changes to other instructions?

A quick scan and search on https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-6.html#jvms-6.5.multianewarray only comes up with `multianewarray`

**Comment by magnus-madsen** [comment]
Forget about `multianewarray`. The new goal is simply to ensure we always generate correct bytecode (i.e. that we emit the right anewarray instructions with the right types).
