### ISSUE TITLE
instance auto-complete doesn't work sometimes

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#5922]
I cannot get auto-complete of instances to work (`instance _`) when written after:

short enums (it does work after full `enum Name { case .... }`)
```
enum Test(Int32)

instance _
```

defs
```
pub def f(): Unit = ()

instance _
```

**Comment by magnus-madsen** [comment]
Yeah, its because `"instance"` could be an expression. Not likely to be fixed before the new parser arrives, unfortunately.
