### ISSUE TITLE
Re-introduce `Bool` kind and Boolean operators `or`, `and`, etc.

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5928]
... But keep this a completely separate kind from effects.

**Comment by magnus-madsen** [comment]
Thus I envision we end up with two complete separate sets of kinds and type constructors.

Makes sense?

**Comment by magnus-madsen** [comment]
Thus the two become untangled. And we can promote the type-level Booleans as a separate and stable feature.

**Comment by mlutze** [comment]
Yep, understood

**Comment by magnus-madsen** [comment]
What remains other than #6066 ?

**Comment by mlutze** [comment]
I think we are done, at least for the surface level stuff. More refactorings remain on the inside.

**Comment by magnus-madsen** [comment]
> I think we are done, at least for the surface level stuff. More refactorings remain on the inside.

Like what?

**Comment by magnus-madsen** [comment]
I think we could close this? The refactoring will come naturally later.

**Comment by mlutze** [comment]
Sure
