### ISSUE TITLE
Generalize Boolean algebra

### ISSUE THREAD

**Issue by mlutze** [flix/flix#5962]
In order to support different kinds better, I propose we make the following changes to the Boolean algebra API:

- `BoolAlg` just has the `mkTrue`, `mkFalse`, etc functions
- We implement a `BoolAlg` for `Type`
  - one for `Eff` kind
  - one for `Bool` kind
  - maybe later one for `CaseSet` kinds
- We introduce a `BoolConverter` trait for translating between different representations

My hope is that we'll be able to finish decoupling Boolean algebra from types.

**Comment by magnus-madsen** [comment]
> We introduce a BoolConverter trait for translating between different representations

Translation is not always cheap.

**Comment by mlutze** [comment]
> Is there are reason we cannot just start by switching on the kind inside unify?

Files like `McCluskyAlgorithm` (or whatever it is) make use of `Type.False`, etc. which won't support additional kinds.

> Translation is not always cheap.

We should not be doing any additional translation. Once to fast representation, and once back.

**Comment by magnus-madsen** [comment]
It seems that one could implement BoolAlg?

**Comment by mlutze** [comment]
> It seems that one could implement BoolAlg?

Yes, that's the idea.

**Comment by mlutze** [comment]
It will be clearer if I just make a PR draft :)

**Comment by JonathanStarup** [comment]
done or outdated @mlutze ?

**Comment by magnus-madsen** [comment]
I think this is outdated. At least there is nothing specific that is actionable.
