### ISSUE TITLE
Add `WithHandler` completion

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5995]
Add completion for:

```
def f(): Unit = try { ... } with [EffectList + Operations]
```

**Comment by magnus-madsen** [comment]
@xdesou01 Matt and/or myself can explain in more detail. This should not be attempted before the others.

**Comment by xdesou01** [comment]
> Add completion for:
> 
> ```
> def f(): Unit = try { ... } with [EffectList + Operations]
> ```

Is the goal here to complete the necessary Effects and Operations?

**Comment by magnus-madsen** [comment]
I am not sure how easy this is. The first task is to see in Parser2 line 2488 whether you can introduce a new syntactic context for WithHandler and get it to trigger on e.g.:

```
def main(): Unit \ IO = 
    try { println("Hello World!") }
    with C 
```
