### ISSUE TITLE
Add `Void` type to `Prelude.flix`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6006]
... in preparation for the return type of exceptions.

Add

```
///
/// The empty type.
///
pub enum Void
```

just before Proxy.

**Comment by JonathanStarup** [comment]
@magnus-madsen doesn't `?void` acomplish the same?

**Comment by JonathanStarup** [comment]
but `?void` also has type `a` right?

**Comment by magnus-madsen** [comment]
> but `?void` also has type `a` right?

Yes, but I need to able to write:

```
pub eff Throw {
  def throwIt(): Void
}
```

:-)

**Comment by JonathanStarup** [comment]
Ah yes the signature cant be polymorphic, makes sense

**Comment by magnus-madsen** [comment]
Fixed in master.
