### ISSUE TITLE
Add `absurd` expression as an alias for an empty match

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6008]
Add an expression `absurd e` as sugar for `match e {}`.

Desugar in `Weeder`.

**Comment by mlutze** [comment]
I think this will run into complications as there are some places that expect a match to be nonempty.

**Comment by magnus-madsen** [comment]
> I think this will run into complications as there are some places that expect a match to be nonempty.

That is why we have a ticket to fix all of those issues :)

**Comment by jaschdoc** [comment]
When would this be used?

**Comment by mlutze** [comment]
It has an intended use-case with algebraic effects. In short, an exception effect returns the Void type (since it never returns).

**Comment by JonathanStarup** [comment]
Is this outdated @mlutze? I think we fixed it via `Void` magic instead right?

**Comment by magnus-madsen** [comment]
I think my Void hack is good enough for now.
