### ISSUE TITLE
bug in `LambdaLift.visitExp` case `LambdaClosure`

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#6028]
The constructed Def has a nonsense type (The formal parameters are not included in the type of the function). This leads to crashing Defs in the backend, but the closure call of `sym` is using `Clo$sym` and the def is generated under `Def$sym`. This `Def$sym` thing is then unused. (kind of, the def expression is used to generate the `Clo$sym` body in a correct way, it uses info from the closure expression itself instead of the types in the def).

This can be seen in the generated code where some `Def$xxxx` uses arguments beyond their arity, i.e. implementing `Fn1$Obj$Obj` and using `arg0` and `arg1`

**Comment by mlutze** [comment]
Beautiful

**Comment by magnus-madsen** [comment]
![image](https://github.com/flix/flix/assets/2287953/55e37e88-4a02-4f6a-94e7-9bd71d189abc)

**Comment by magnus-madsen** [comment]
I understand the issue, but what's the argument that separating capture and non-captured params is the right way to go? What's the intuition? (Presumably the alternative is simply to fix the types).

**Comment by JonathanStarup** [comment]
It also seems a bit premature imo to split the argument lists pre-backend since these phases actually do not care what argument is what. The problem is that that backend cannot partially apply functions (applied one argument to a `Fn2$Char$Char$Char` does not result in a `Fn1$Char$Char` object) and therefore the code generation needs to know these partially applied positions explicitly. 

The current state (ignoring the malformed defs that are generated) is that for a closure like `x -> x + a` it is represented as a function with arguments `a: Int32, x: Int32` and a tracked type of `Int32 -> Int32` (notice that this ignores `a`). This means that we already have split captured arguments and actual arguments (and the backend uses this fact) but its just done in a very round-about way that makes the tpe hard to reason about.

**Comment by magnus-madsen** [comment]
Ooof.. That is nasty.
