### ISSUE TITLE
Benchmarker: less rounds/adaptive

### ISSUE THREAD

**Issue by mlutze** [flix/flix#6040]
The benchmarker currently runs 50000 rounds every time it is invoked. This seems like too many for some cases (e.g. if I have a big list)

**Comment by JonathanStarup** [comment]
+ 25000 warmup rounds

**Comment by magnus-madsen** [comment]
@athas had a student who did some excellent work on this. I wonder if the thesis is publicly available?

**Comment by JonathanStarup** [comment]
@mlutze outdated i believe?

**Comment by mlutze** [comment]
Ouaip
