### ISSUE TITLE
Variable shadowing error should take precedence over type checking

### ISSUE THREAD

**Issue by ZiyaoWei** [flix/flix#6044]
E.g.,

<img width="724" alt="image" src="https://github.com/flix/flix/assets/940823/a8c75574-25c1-46e0-ae8c-a70374a2403a">

Because `a` is shadowing another `a` defined above, as a user the type error is not super helpful since that alone doesn't fix the issue.

This seems like it might be nontrivial since the redundancy checking phase happens after the typer phase and depends on the typing information?

**Comment by magnus-madsen** [comment]
> This seems like it might be nontrivial since the redundancy checking phase happens after the typer phase and depends on the typing information?

Yes, this would be difficult to "fix".

**Comment by JonathanStarup** [comment]
on master i get a redundancy error
