### ISSUE TITLE
Eliminate `Ast.Constant.Regex` in `Simplifier`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6047]
I don't mean to delete `Ast.Constant.Regex`, but rather in `Simplifier` it should be translated to `Expression.NewObject`.

**Comment by jaschdoc** [comment]
What object should it be translated to? `Pattern`? Or should we compile it?

https://docs.oracle.com/en/java/javase/19/docs/api/java.base/java/util/regex/package-summary.html

https://docs.oracle.com/en/java/javase/19/docs/api/java.base/java/util/regex/Pattern.html

**Comment by magnus-madsen** [comment]
What does the backend do? I think we should do what it does.

**Comment by magnus-madsen** [comment]
Looks like a call to `Pattern.compile`. Nothing fancy.

**Comment by jaschdoc** [comment]
`GenExpression` just calls `Pattern.compile` on the pattern, so I think we should translate it to an `InvokeStaticMethod` expression instead.

**Comment by magnus-madsen** [comment]
Yes.

**Comment by jaschdoc** [comment]
Perfect
