### ISSUE TITLE
Add support for mutable structs

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6056]
This is a proposal for the addition of mutable structs:

```rust
struct Node[t: Type, r: Region] {
  data: t,
  prev: Option[Node[t, r]]
  next: Option[Node[t, r]]
}
```

## What is a struct?
- A struct is a nominal type (i.e. it has a name, e.g. `Node`).
- A struct always lives in a region (so it is like an `Array` or `Ref`).
- A struct consists of a sequence of mutable fields (so it is a bit like a Java class).

## `Ref`s and `Struct`s

We can use structs to model references:

```rust
struct Ref[t: Type, r: Region] {
  value: t
}
```

This means we can choose to: (a) drop references internally in the compiler or (b) drop references completely.

## Example 1

Before:
```rust
pub enum MutList[a: Type, r: Region] {
    case MutList(Region[r], Ref[Array[a, r], r], Ref[Int32, r])
}
```

After:
```rust
pub struct MutList[a: Type, r: Region] {
  rc: Region[r],
  data: Array[a, r],
  size: Int32
}
```

## Example 2

Before:
```rust
pub enum MutDeque[a: Type, r: Region] {
    case MutDeque(Region[r], Ref[Array[a, r], r], Ref[Int32, r], Ref[Int32, r])
}
```

After:
```rust
pub struct MutDeque[a: Type, r: Region] {
  rc: Region[r],
  data: Array[a, r],
  front: Int32,
  back: Int32
}
```

## Why not records? When to use each?

We can emulate `struct`s, yet I think it is worth adding explicit support.

- I think of records as closely related to tuples: You use a record once a tuple "grows too large" and you need labels to distinguish its components. Like tuples, records are mostly used to hold immutable data.
- I think, on the other hand, `struct`s (like `Array`s and `Ref`s) should be used to model mutable data structures (e.g. mutable linked lists, mutable double linked lists etc.)

_Note:_ I propose the terminology that a record has labels whereas a struct has fields.

## Syntax and Open Questions
- I propose `new MutDeque { field1 = exp1, ... }` as syntax to create a struct. 
- I propose `exp1 . f = exp2` to update the field of a record.
- I would like to have `exp . f` to access field `f`, but that clashes with the syntax for records. Not sure how we can overcome that.

## Plan
- My plan is to add structs as a step towards _fearless concurrency_ (e.g. [1]).
- By adding a new mutable type, it will be easier to experiment with extra restrictions on it, leaving `Array`s and `Ref`s as they are. 
- Once we have a system like [1] in place for structs then it will be simple to enable structs in the entire compiler and to port the same requirements to `Ref`s and `Array`s`. It will also be straightforward to refactor the standard library.

[1] https://dl.acm.org/doi/abs/10.1145/3519939.3523443

**Comment by magnus-madsen** [comment]
We would need a lot of machinery:

- A new `Symbol.StructSym`.
- A new `Name.StructField(ident: Ident.Name)`
- A new expression `StructNew(exps: List[StructFieldExp], exp: Expr)` (the 2nd argument is the region)
- A new expression `StructGetField(exp, Name.StructField, fld: Name.StructField)`
- A new expression `StructPutField(exp1: Expr, fld: Name.StructField, exp2: Expr)`
- A new pair of a struct field and label `StructFieldExp(fld: Name.StructField, exp: Exp)`

I would start with some fake syntax to avoid issues (during development):
- `struct_new Foo(fld1 = exp1, ...) @ exp`
- `struct_get_fld exp fld`
- `struct_put_fld exp1 fld exp2`

**Comment by jaschdoc** [comment]
> I propose `new MutDeque { field1 = exp1, ... }` as syntax to create a struct.

I think we should leave out the `new` keyword and just let the name of the struct disambiguate between records and structs.

**Comment by magnus-madsen** [comment]
I suggest we do this phase by phase, i.e. each PR adds support to one phase.

(Yes, a subsequent PR may have to tweak previous PRs, but that is OK too.)

**Comment by magnus-madsen** [comment]
Before we get started there is one issue to be fixed: https://github.com/flix/flix/issues/6399

**Comment by JonathanStarup** [comment]
So a struct is a singleton enum where all terms (type `t`) are implicitly a reference (type `Ref[t, r]`?

First question: If I want some non-mutable data in my struct (like a non-dynamic size), I will just have to use an enum?

Second question: The following translation is not correct since the `Region[r]` becomes `Ref[Region[r], r]` in the struct version?
```scala
pub enum MutDeque[a: Type, r: Region] {
    case MutDeque(Region[r], Ref[Array[a, r], r], Ref[Int32, r], Ref[Int32, r])
}
```
```scala
pub struct MutDeque[a: Type, r: Region] {
  rc: Region[r],
  data: Array[a, r],
  front: Int32,
  back: Int32
}
```

**Comment by magnus-madsen** [comment]
> So a struct is a singleton enum where all terms (type t) are implicitly a reference (type Ref[t, r]?

No? What do you mean? You can update each field of a struct independently. Rather a struct is a generalization of `Ref`.

**Comment by magnus-madsen** [comment]
The translation for `MutDeque` you show is exactly how it would look and it would work as expected.

**Comment by magnus-madsen** [comment]
A struct is nominal (named type). It has fields each of which are mutable (ref-like), if you will. A reference is then just a special form of struct:

```
struct Ref[r, t] {
  pointer: t
}
```

**Comment by jaschdoc** [comment]
Would it make sense for structs to have fields marked as `mut`? E.g.
```scala
struct Ref[r, t] {
  pointer: mut t
}
```

**Comment by magnus-madsen** [comment]
> Would it make sense for structs to have fields marked as `mut`? E.g.

Not yet. This requires a lot more than just adding a keyword :)

**Comment by jaschdoc** [comment]
Updated the comment sorry :)

**Comment by magnus-madsen** [comment]
> mut fields (short for mutable) could be desugared to references maybe and other fields are immutable like any other value.

This would add an extra layer of indirection. If any desugaring takes places it would be ref -> struct (but most likely we just drop refs).

**Comment by JonathanStarup** [comment]
> > So a struct is a singleton enum where all terms (type t) are implicitly a reference (type Ref[t, r]?
> 
> No? What do you mean? You can update each field of a struct independently. Rather a struct is a generalization of `Ref`.

Yeah that part makes sense. What I'm saying is that in the `enum` version I cannot reassign another value to `Region[r]` because it's not a `Ref[Region, r]` but in the `struct` version I could write `mutDeque.rc = someOtherRegionOfTheSameType` since all fields are updatable as you've said. This also means that accessing `rc` is impure in the struct version where its pure in the enum version.

**Comment by JonathanStarup** [comment]
How do i know what the effect of accessing `data` is? `r1` or `r2`
```scala
pub struct MutDeque[a: Type, r1: Region, r2: Region] {
  rc: Region[r1],
  data: Array[a, r2],
  front: Int32,
  back: Int32
}
```

**Comment by magnus-madsen** [comment]
> How do i know what the effect of accessing `data` is? `r1` or `r2`

We will need some special syntax (or convention) that tell us which region the struct belongs to. Assuming its the _last_ parameter (e.g. like for Ref and Array), accessing `data` would have effect `r2`.

**Comment by jaschdoc** [comment]
Are fields private by default, i.e. do we make public fields opt-in? The way I imagine it is that private fields are only accessible from the companion namespace / module. I don't know if this would require some more work in the namespace implementation or even the scope of such a feature, but I think it would tie in nicely as a “least surprising” feature.
Additionally, it makes sense to restrict client access to a struct if every field is mutable to avoid unnecessary shared ownership / mutability.

**Comment by magnus-madsen** [comment]
> Are fields private by default, i.e. do we make public fields opt-in? The way I imagine it is that private fields are only accessible from the companion namespace / module. I don't know if this would require some more work in the namespace implementation or even the scope of such a feature, but I think it would tie in nicely as a “least surprising” feature. Additionally, it makes sense to restrict client access to a struct if every field is mutable to avoid unnecessary shared ownership / mutability.

I would suggest we do this after we have a MVP.

**Comment by magnus-madsen** [comment]
I don't think we need visibility. I propose that fields are only directly accessible in the companion module.

This is like enforcing that all outside access must be via functions defined in the module.

**Comment by magnus-madsen** [comment]
> How do i know what the effect of accessing `data` is? `r1` or `r2`

I propose new syntax:

```scala
pub struct MutDeque[a: Type, r1: Region] @ r2 {
  rc: Region[r1],
  data: Array[a, r2],
  front: Int32,
  back: Int32
}
```
(We can debate better syntax later).

**Comment by magnus-madsen** [comment]
How many objects would a Node require?

**Comment by JonathanStarup** [comment]
Hmm I think we can solve that for closed records. constant time lookup, ref field optimization. 

Structs and records seem very related so I think we should give it a go as desugaring and compiler optimizations before adding them explicitly.

**Comment by magnus-madsen** [comment]
> Hmm I think we can solve that for closed records. constant time lookup, ref field optimization.
> 
> Structs and records seem very related so I think we should give it a go as desugaring and compiler optimizations before adding them explicitly.

The problem is that extensible records do not have O(1) access time.

**Comment by magnus-madsen** [comment]
Structs generalize refs though. So once we have structs, we can get rid of refs (it becomes a polymorphic struct with one field).

**Comment by JonathanStarup** [comment]
> The problem is that extensible records do not have O(1) access time.
We could improve on it. maybe trade slower extension with faster lookup

**Comment by JonathanStarup** [comment]
But also, from the user point of view, structs can't have immutable fields. So if you want that you have to go back to records anyway? Or if we add immutable fields to structs then structs and records have even more overlap.

**Comment by JonathanStarup** [comment]
> Structs generalize refs though. So once we have structs, we can get rid of refs (it becomes a polymorphic struct with one field).

But structs are also more complex and we don't have them now, so its not like it saves effort
