### ISSUE TITLE
Disable type parameter redundancy for non-Star kinded params?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6057]
The proposal is to allow this:

```
pub enum Color[isWarm: Bool] {
  // ...
}
```

because `isWarm` has non-Star kind.

Of course we also have record rows where redundancy might be appropriate... Hmm. We could also just disable it for select kinds?

**Comment by magnus-madsen** [comment]
CC @mlutze @JonathanStarup

**Comment by JonathanStarup** [comment]
Ill close this since i agree that `_isWarm` is fine
