### ISSUE TITLE
Add examples for type-level programming with Booleans

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6062]
(text to be added)

**Comment by JonathanStarup** [comment]
I think Wadlers pretty printer could be interesting

**Comment by magnus-madsen** [comment]
> I think Wadlers pretty printer could be interesting. The implementation itself is also not very big, its the first 200 ish lines of https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/dbg/Doc.scala

What's the typelevel property you want?
