### ISSUE TITLE
Emit packager status/logging messages to stderr

### ISSUE THREAD

**Issue by mlutze** [flix/flix#6068]
Currently these are sent to stdout, which breaks anything consuming e.g. JSON output.

**Comment by magnus-madsen** [comment]
Or suppress non-errors if `--json` is present?

**Comment by mlutze** [comment]
> Or suppress non-errors if `--json` is present?

Maybe as a quick fix. But IMO it is reasonable for the user to want loggy info while piping the result somewhere else. We just need to be more principled with distinguishing between primary and secondary output.

**Comment by magnus-madsen** [comment]
> > Or suppress non-errors if `--json` is present?
> 
> Maybe as a quick fix. But IMO it is reasonable for the user to want loggy info while piping the result somewhere else. We just need to be more principled with distinguishing between primary and secondary output.

Roger

**Comment by mlutze** [comment]
> What the packager is printing is not really errors though...

True, but stderr is not exclusively for errors. [POSIX says](https://pubs.opengroup.org/onlinepubs/9699919799/functions/stderr.html) `for writing diagnostic messages`

**Comment by magnus-madsen** [comment]
Ok
