### ISSUE TITLE
Add `EnumTagCompleter`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6076]
This one is conceptually tricky, so should be attempted last.

**Comment by xdesou01** [comment]
Could I see a use case for this as well?

**Comment by magnus-madsen** [comment]
Its when you have:

```
mod Aaa.Bbb {
  enum Color { case Red }
}
```

and type `Aaa.Bbb.Color.`

**Comment by xdesou01** [comment]
> Its when you have:
> 
> ```
> mod Aaa.Bbb {
>   enum Color { case Red }
> }
> ```
> 
> and type `Aaa.Bbb.Color.`

I see, thanks
