### ISSUE TITLE
Rework `resume`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6108]
I propose that we enforce handlers always take the continuation:

```scala
def main(): Unit = 
    try {
        do MyMod.MyPrint.print("Hello")
    } with MyMod.MyPrint {
        def print(_s, _k) = ()
                      ^^ required
    }
```

This simplifies the frontend and helps us get type inference correct.

Later, we can view such handlers as:

```scala
def main(): Unit = 
    try {
        do MyMod.MyPrint.print("Hello")
    } with MyMod.MyPrint {
        def print(_s, resume) = /* uses resume */
    }
```

and finally later we can simply implicitly introduce `resume`:

```scala
def main(): Unit = 
    try {
        do MyMod.MyPrint.print("Hello")
    } with MyMod.MyPrint {
        def print(_s) = /* uses resume */
    }
```

**Comment by magnus-madsen** [comment]
I would rework `HandlerRule` to take `fparams` (plural) and `kparam` (singular).

**Comment by JonathanStarup** [comment]
It could also be
```
def print(s)(resume) = ...
```
To syntactically see if the resumption argument is present or not.

We could interpret
```
def print(s) = ...
```
as 
```
def print(s)(resume) = resume(...)
```
since people always seem to forget to call resume anyway

**Comment by magnus-madsen** [comment]
@JonathanStarup What do you think about dropping resume?

**Comment by magnus-madsen** [comment]
(As a keyword etc)

**Comment by JonathanStarup** [comment]
seems okay, its unused right now
