### ISSUE TITLE
Rename `SemanticOperator`  to `PrimitiveOperator`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6111]

**Comment by magnus-madsen** [comment]
or PrimitiveOp?

**Comment by magnus-madsen** [comment]
@jaschdoc Did we rename it already? Should we rename it again? :D

**Comment by jaschdoc** [comment]
I think we renamed it to `SemanticOp` just to shorten it. Renaming seems like bike shedding?

**Comment by magnus-madsen** [comment]
OK. No bike shedding.
