### ISSUE TITLE
Fixing escaping regions

### ISSUE THREAD

**Issue by mlutze** [flix/flix#6142]
### Problem

#5604: Purified regions are reintroduced into substitutions, outside the region.

This is due to substitutions being non-idempotent. We have something like `a -> a + r` in a substitution, so while type `a + r` is purified to `a` on exiting the region, it is de-purified to `a + r` once the substitution is applied.

### Proposal

Unification now has an additional parameter: a _purity environment_ `penv`. When we call `unify(t1, t2, penv)`, the `penv` tells us which type variables have been purified. We treat these type variables as `Pure` rather than as type variables.

For example,

```
unify(a, r, {r})                   = {a => Pure}
unify(a, r, {})                    = {a => r}
unify(a, b -> c \ r, {r})          = {a => b -> c \ Pure}
unify(a -> b \ e, c -> d \ r, {r}) = {a => c, b => d, e => Pure}
```

Effectively, from outside the region, we are looking at it through a purifying lens, rather than trying to change the result directly.

#### New Problem

This introduces a new problem, as the `Regions` check will no longer work when every region looks `Pure` from the outside. I believe this can be addressed by using unification levels; in short, we introduce an `lenv` in unification, which helps inform rigidity of variables based nesting depth of regions.

**Comment by magnus-madsen** [comment]
Maybe we can borrow some brainpower from @jacopol

**Comment by JonathanStarup** [comment]
@mlutze outdated?

**Comment by mlutze** [comment]
Yes
