### ISSUE TITLE
bug with type variables in declared def schemes post monomorph

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#6151]
Maybe remove the schemes at an earlier point or fix the unification done in `Monomorph.specializeDef` to include the declared scheme

Example:
```
def: MutMap.new$137931
declared scheme: Region[IO] -> MutMap[Unit, Unit, IO] \ IO
inferred  scheme: Region[IO] -> MutMap[RamSym[Boxed], MutMap[Vector[Boxed], Boxed, IO], IO] \ IO
```

**Comment by magnus-madsen** [comment]
I think it makes sense to remove schemes after monomorph.

**Comment by JonathanStarup** [comment]
inferred scheme is no longer
