### ISSUE TITLE
Packager / Maven dependencies - version numbers should allow things that aren't numbers

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#6155]
Currently the Packager disallows Maven dependencies that don't have proper semantic version numbers. Unfortunately this is too restrictive in practice as it is common to find Java packages that don't strictly use semantic version numbers, e.g:

https://mvnrepository.com/artifact/io.netty/netty-common/4.1.94.Final

**Comment by magnus-madsen** [comment]
Yikes. Okay.

**Comment by stephentetley** [comment]
Do we lose anything compelling if we change `MavenDependency` to have a String version tag rather than a `SemVar` one?

**Comment by magnus-madsen** [comment]
> Do we lose anything compelling if we change `MavenDependency` to have a String version tag rather than a `SemVar` one?

No. I think you can do that :)

**Comment by stephentetley** [comment]
Thanks - I'll make a PR tomorrow evening.

**Comment by magnus-madsen** [comment]
Fixed?

**Comment by stephentetley** [comment]
Yes
