### ISSUE TITLE
Use `AtomicOp` in `LoweredAst`

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#6161]

**Comment by magnus-madsen** [comment]
This is the last AST now, right? :)

**Comment by jaschdoc** [comment]
Aside from DocAst, yes.

**Comment by magnus-madsen** [comment]
Ok-- is there some cleanup left in the phases?

**Comment by jaschdoc** [comment]
I'm not sure yet, I'll have to check it out, but there shouldn't be any bloat really or temporary code aside from a minor thing in `DocAst`.

**Comment by jaschdoc** [comment]
It may be possible to simplify vectors into arrays in `Lowering`, but that would, of course, pollute the responsibilities of the `Lowering` phase. However, it seems we could just use an `Array` exp with a pure effect everywhere we use `Vector`. The upshot is that we reduce the code size even further. Thoughts?

**Comment by jaschdoc** [comment]
By the same token, if we cannot move `Vector` to `Atomic` in the `Lowering` phase we cannot move `Cast` there either since some of the other parts of `Lowering` depend on the `Cast` expression. Just leaving this here, so we have a list of special expressions.

**Comment by magnus-madsen** [comment]
Lowering is before monomorph right? If so I am not sure it can work.

**Comment by jaschdoc** [comment]
Correct

**Comment by magnus-madsen** [comment]
I don't think types can be erased before monomorph. Maybe ask Matt?

**Comment by mlutze** [comment]
No. This will break type classes, since they use the type information to decide which instance to use. If a `Vector` becomes an `Array` before monomorph, then we call `MyTypeClass[Array].mySignature` where we should call `MyTypeClass[Vector].mySignature`.

**Comment by magnus-madsen** [comment]
What's the overall status on AtomicOp. Is it done throughout the phases?

**Comment by jaschdoc** [comment]
One more PR for this and we're done with the essentials. Then we just need to refactor DocAst but it currently handles atomics via a helper function defined in DocAst (so that's slightly ugly)

**Comment by magnus-madsen** [comment]
> One more PR for this and we're done with the essentials. Then we just need to refactor DocAst but it currently handles atomics via a helper function defined in DocAst (so that's slightly ugly)

OK, and maybe do a final validation/checkup pass through everything.
