### ISSUE TITLE
Remove `Tail` Ast nodes from `DocAst`

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#6212]
@JonathanStarup do you think it would be possible to remove `DocAst.Expression.ApplyCloTail` and `DocAst.Expression.ApplyDefTail` now that they are being removed in https://github.com/flix/flix/pull/6202 ? I looked at their non-tail definitions, and it seems they are equivalent.

**Comment by magnus-madsen** [comment]
Just to be clear, its not that tail calls are removed. It is that we use a different representation (CallType).

**Comment by jaschdoc** [comment]
Yes, but if we are trimming the Ast nodes, then we may as well reduce it in `DocAst :)

**Comment by magnus-madsen** [comment]
> Yes, but if we are trimming the Ast nodes, then we may as well reduce it in `DocAst :)

Agreed!

**Comment by magnus-madsen** [comment]
@jaschdoc Will you be able to do this?

**Comment by jaschdoc** [comment]
Yes, certainly.
