### ISSUE TITLE
Drop `tpe` and `purity` from `Def`s in the backend?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6235]
They can be inferred from the `exp`... And they should always be consistent anyway.

Thoughts?

**Comment by magnus-madsen** [comment]
Backend means: Reduced, Lifted, Simplified, and Lowered Asts. (Perhaps start with ReducedAst and see how it goes).

**Comment by magnus-madsen** [comment]
> `And they should always be consistent anyway`
> 
> When I looked into the monomorpher it seems that they are not always consistent, especially regarding effects. But I agree that we should push towards it

OK- so some pain may occur :/

**Comment by JonathanStarup** [comment]
https://github.com/flix/flix/blob/718dfd3fa5f58cae8f3bf684b11f630bb2483307/main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala#L753C6-L753C6

This line, if changed to forcedly expect `Type.Impure` crashes 2 tests.

It seems like the def purity and exp purity aligns in all but one case where the def effect is `Unit + (~Unit)`. I think the solution is to give monomorph a retouch and use `TypeNormalization` in appropriate places.

**Comment by magnus-madsen** [comment]
Wait, an effect can be Unit or did you mean something else?

**Comment by magnus-madsen** [comment]
@JonathanStarup There are also some issues left with the Monomorph. You can try to enable Verifier and see.

**Comment by JonathanStarup** [comment]
> Wait, an effect can be Unit or did you mean something else?

I think the monomorpher erasure made something a unit and messed up the type
