### ISSUE TITLE
Upgrade to Scala 3

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6270]
- Get it to compile with minimal changes.
- Ensure all Flix tests pass.
- Find out if Scala3 compiler is faster/slower.
- Find out the produced flix.jar is smaller/larger.
- Find out if the runtime performance of the Flix compiler is faster/slower.

**Comment by jaschdoc** [comment]
Close this and reopen whenever it is relevant again to reduce the number non-actionable issues?
