### ISSUE TITLE
Issues with verifier

### ISSUE THREAD

**Issue by mlutze** [flix/flix#6284]
It's not easy to tell, because they all appear so many times, but this one seems to be repeating in a bunch of variations:
```
Mismatched types near RedBlackTree.flix:479:37

  tpe1 = Bool
  tpe2 = Enum(RedBlackTree$5011954)
```
Here it expects a `Bool` but receives an enum variant. For context, this is the line (479) in question:
```
case Node(Color.Black, Node(Color.Red, Node(Color.Red, a, k1, v1, b), k2, v2, c), k3, v3, d) =>
```

Also this one appears many times:
```
Mismatched types near GetOpt.flix:193:23

  tpe1 = Bool
  tpe2 = Tuple(List(Enum(List$2396337), Enum(List$2396335), Enum(List$2396335), Enum(List$2396335)))
```
I'm not sure if it's the same problem though, because it only seems to appear with a `Tuple` containing a `List` in which an `Enum` appears at least once.  Line 193 looks like this
```
case (OptionKind.NonOpt(x),    ArgOrder.Permute)            => (os, x :: xs, us, es)
```
Could it be a problem with match in general? Where would that appear in the verifier?

_Originally posted by @sockmaster27 in https://github.com/flix/flix/pull/6261#issuecomment-1651711548_

**Comment by magnus-madsen** [comment]
Probably the types are wrong in the desugaring of pattern matches in the `Simplifier`.

**Comment by magnus-madsen** [comment]
Not sure where the bug is, but we can add an if-then-else to all IfThenElse expressions that throw an exception.

E.g.

```
case class IfThenElse(....) {
  assert(tpe == exp2.tpe)
  assert(tpe == exp3.tpe)
}
```

to track down the bug.

**Comment by magnus-madsen** [comment]
@jaschdoc Maybe you can help look into this?

**Comment by magnus-madsen** [comment]
The `Verifier` has to be enabled by adding it to the compiler pipeline in `Flix.scala` (it works on ReducedAst).

Then you can run all tests to see the output.

**Comment by magnus-madsen** [comment]
Fixed in master.
