### ISSUE TITLE
Add `Reader` class

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6297]
```scala
///
/// A type class for types which are resources that can be accessed as bytes.
///
class Reader[t] {
    ///
    /// Reads `k` bytes from the underlying resource and writes them into `b`.
    ///
    /// Returns `Ok(k)` to signify that `k` bytes was successfully read and written to `b`.
    ///
    /// Guarantees that `0 <= k < length(b)`.
    ///
    /// Returns `Err(e)` if some underlying I/O error occurs.
    ///
    pub def read(b: Array[Int8, r], r: t): Result[IOError, Int32] \ {r, IO}
}
```

**Comment by magnus-madsen** [comment]
@stephentetley I have a PR which adds this class which is inspired by Go/Rust. Conceptually it is similar to `InputStream`, but I prefer to use a "fresh name" for it and to be consistent with Go/Rust.

Would you be interested in adding some instances (for files and sockets) and adding a `BufReader`?

We would like this implement this ourselves because down the road we will replace `IO` with an assoc effect which will enable us to use it in combination with algebraic effects.

**Comment by magnus-madsen** [comment]
- https://github.com/flix/flix/issues/6402
- https://github.com/flix/flix/issues/6403

**Comment by stephentetley** [comment]
Thanks Magnus, yes I'm happy to look at this.
