### ISSUE TITLE
Add `HtmlDocumentor`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6309]
Add a new object `HtmlDocumentor` (next to `Documentor.scala`) which takes a `TypedAst.Root` and generates static html files.

The phase should output HTML files to `build/doc` and should generate one HTML per module.

For example:

- `List.html`
- `Fixpoint.Ast.html`

and so forth.

The generated HTML should mirror the __right hand side__ of https://api.flix.dev/ (source code here: https://github.com/flix/api.flix.dev).

The stylesheet should be re-usable, as is.

Once we can generate the right-hand side, we can focus on how to generate a menu on the left and how to support search.

It is important to structure the class as a collection of small private functions that each generate HTML snipplets for their input. Following the structure of the AST would be useful.

Later we will have to decide on how to include the CSS and favicons, etc.

The goal is to generate fully static HTML pages, style them with CSS, and only use minimal JavaScript for search.

The goal is also to slightly restructure how some information is presented, but we will get to that.

**Comment by magnus-madsen** [comment]
@sockmaster27 Here is a nice bigger assignment that would be nice to have implemented.

**Comment by magnus-madsen** [comment]
The new phase can be connected around here: https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/api/Flix.scala#L586

**Comment by sockmaster27** [comment]
Should it include the standard library?

**Comment by magnus-madsen** [comment]
> Should it include the standard library?

Yes, it should look like what is on `api.flix.dev`.

**Comment by sockmaster27** [comment]
Is the purpose strictly to document the standard library, or should it also be usable to document user code?

**Comment by magnus-madsen** [comment]
> Is the purpose strictly to document the standard library, or should it also be usable to document user code?

Ah, ultimately both. You can imagine the programmer massing which module(s) to include.

**Comment by sockmaster27** [comment]
I think it would be hard to keep linking to the GitHub source if we also want to be compatible with users documenting their local code and including packages.

The easiest and most consistent solution is probably to include the source code in the page (or as its own page), like docs.rs does it.

**Comment by magnus-madsen** [comment]
I think we just need to know the repository url.

**Comment by sockmaster27** [comment]
But what if the user hasn't published their code? Should we then link to the local file? Is it even possible to link to specific line then?

**Comment by magnus-madsen** [comment]
A few specific goals:

- [ ] Reproduces the same style as on api.flix.dev
- [ ] Avoids bootstrap (if feasible).
- [ ] Emits valid HTML according to some validator.
- [ ] Structured around a collection of small `visitXYZ` functions.
- [ ] Does not rely on JavaScript (at least for milestone 1).
- [ ] Escape HTML (but we can start with a very simplistic approach).
