### ISSUE TITLE
Add HtmlDocumentor (v2)

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6327]
- [x] Milestone 1: #6309 is to replicate everything from api.flix.dev as static html pages. 
- [x] Milestone 2: Add a menu on the left. Unlike the current menu, it should not show the entire project, but instead it should just be a summary (bullet point list) of the defs (etc) in the current module. Thus it would mirror the structure of Rustdoc which also just shows "children" on the left.

Milestone 3:
- [x] Don't show type parameters on defs.
- [x] Don't show `\ Pure`.
- [x] Annotations on one line. (Placement of source button is also not aligned with them?)
- [x] Add Flix version somewhere.
- [x] Add a link to the top of the menu which allows navigation back to Prelude.html (e.g. could be "Flix").
- [x] Show "Signatures" by default (if possible).
- [x] I think using a monospaced font for the menu is a bit too aggressive. Perhaps we could try 'Roboto' or something?
- [x] Emit HTML before resources (so if a crash happens due to broken JAR at least the HTML is there.)

Milestone 4:
- [x] Output `Prelude` as the filename `index.html`
- [x] Effects should come right after classes (and then enums and type aliases) both on the page and in the menu.
- [x] A "<- back" link after "Flix" in the menu might be useful when in a sub module.
- [x] A "link" button next to source would be useful, e.g. this would point to e.g. `Adaptor.html#def-toLinkedList` and allow one to link directly to an item.
- [x] Rename "ops" to `Operations` and show by default.

Milestone 5: 
- [x] Merge classes/effects/enums with their module (i.e. List.html should show the definition of list, Foldable.html should show the Foldable class and so forth).

**Comment by sockmaster27** [comment]
> * Don't show type parameters.

Does this only apply to definitions (and signatures) or classes and enums too?

**Comment by magnus-madsen** [comment]
Lets only go with definitions:

![image](https://github.com/flix/flix/assets/2287953/cf2744da-82a1-4ed2-b60f-7ec4b04318fe)

**Comment by magnus-madsen** [comment]
(I am updating the lists a bit)

**Comment by magnus-madsen** [comment]
@sockmaster27 I updated the list. Still looking for more smaller improvements.

**Comment by magnus-madsen** [comment]
@sockmaster27 Let me know if you need help understanding milestone 4. Its a bit difficult to understand, but the idea is that instead of showing e.g. "List" enum has in Prelude, we want to show it in "List.html" above everything else. 

This is because flix has so-called companion modules. So really we have:

```
enum List { ... }
mod List {...}
```

and we would like both to be shown in `List.html`.

**Comment by sockmaster27** [comment]
> * Annotations on one line. (Placement of source button is also not aligned with them?)

I can put them on a single line, but aligning the source link with them is, first of all, surprisingly hard and requires a lot of restructuring, plus I personally think it makes more sense to have them aligned with the function head anyway, since that is the line the link is referring to. This is also identical to how it was done on the old site.

**Comment by magnus-madsen** [comment]
> > * Annotations on one line. (Placement of source button is also not aligned with them?)
> 
> I can put them on a single line, but aligning the source link with them is, first of all, surprisingly hard and requires a lot of restructuring, plus I personally think it makes more sense to have them aligned with the function head anyway, since that is the line the link is referring to. This is also identical to how it was done on the old site.

OK, do what you think is best then.

**Comment by magnus-madsen** [comment]
This is a very general rule. 

This was introduced after the now old api.flix.dev was written-- hence the difference.

**Comment by magnus-madsen** [comment]
It is a bit like how Rust has say structs and impls -- does that make sense?

**Comment by sockmaster27** [comment]
So _any_ time a type is introduced - inside or outside the library - which has the same name as a module  - inside or outside the library - it will appear as if it was part of that module?

**Comment by magnus-madsen** [comment]
> So _any_ time a type is introduced - inside or outside the library - which has the same name as a module - inside or outside the library - it will appear as if it was part of that module?

I would think of this way: A Flix program contains a number of modules. Each module has may have many members: definitions, types, etc. But it may also have __one special member__ (e.g. a type or type class or effect) which must be shown before all its other members.

**Comment by sockmaster27** [comment]
That makes sense, but in terms of the implementation would this still be correct, or am i misunderstanding something?

**Comment by sockmaster27** [comment]
You want the enum `Benchmark` to be removed from `Prelude.html`, and instead added to `Benchmark.html`, right?
I'm just wondering exactly how to implement it. Should any enum just be moved to a module with the same name if one is available?

**Comment by magnus-madsen** [comment]
> You want the enum `Benchmark` to be removed from `Prelude.html`, and instead added to `Benchmark.html`, right? 

Yes. But also show "at the top" in some prominent way. Perhaps shown right after the headline, as we see here:

https://doc.rust-lang.org/std/cmp/enum.Ordering.html

> Should any enum just be moved to a module with the same name if one is available?

Yes. So an enum `Foo.Bar.Baz` should be shown in `Foo.Bar.Baz.html`.

**Comment by magnus-madsen** [comment]
`Foldable` is a good example. Currently `Foldable.html` is pretty much empty. But after the refactoring the "class Foldable" box will be there at the top. Perhaps like so:

![image](https://github.com/flix/flix/assets/2287953/6a14cda7-2b47-4f73-9053-80d3e91696f1)

**Comment by magnus-madsen** [comment]
I will move a few issues into their own ticket.

**Comment by magnus-madsen** [comment]
I would like Milestone 5 to take priority over other tasks (when what is currently waiting to be merged is done).

It would probably require some iterations back and forth to get it right. Let me know if you have questions. Perhaps we could also discuss a mockup before you write any code.

**Comment by magnus-madsen** [comment]
Milestone 4 complete 🎆 .
Moved Milestone 6 to its own ticket.

**Comment by magnus-madsen** [comment]
Do you think we can close this now?
