### ISSUE TITLE
Totality of Arithmetic Operations

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#635]
The Pony language has an interesting solution to the problem of division being a partial operator:

https://tutorial.ponylang.org/gotchas/divide-by-zero.html

They simply define division by zero to yield zero.

**Comment by mlutze** [comment]
Is this issue simply to implement this feature, or is it to explore the implications of such an implementation?

**Comment by magnus-madsen** [comment]
We want to implement it. Otherwise division has to be impure.

The implementation can probably be done in a few lines together with some test cases.

**Comment by mlutze** [comment]
Which phase would this go into?

**Comment by magnus-madsen** [comment]
It would go here:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/runtime/interpreter/Interpreter.scala#L526

(and related places)

and around here:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala#L1624

somewhere.

Note that it should be implemented for Int8, Int16, Int32, Int64, and BigInt. The question is whether the floats should also give 0 or give NaN? Maybe best to leave the float semantics in place?

**Comment by mlutze** [comment]
WIP here: https://github.com/flix/flix/pull/972

I decided just to make changes to the integer types (for now). When I made changes to the float types there seemed to be some side effects on other methods involving infinity and NaN.

I was thinking we might also want to add an operator or stdlib function to "safely" divide? e.g. 

```
if (b == 0) None else Some(a / b)
```

**Comment by magnus-madsen** [comment]
> WIP here: #972
> 
> I decided just to make changes to the integer types (for now). When I made changes to the float types there seemed to be some side effects on other methods involving infinity and NaN.
> 
> I was thinking we might also want to add an operator or stdlib function to "safely" divide? e.g.
> 
> ```
> if (b == 0) None else Some(a / b)
> ```

Rust does this. So they have an set of operations (not just div) that all return options. For example, if a plus operation overflows it returns None. We could do that, if someone is willing to do the work, but it might be a bit soon to add such a specialized feature.

**Comment by magnus-madsen** [comment]
Fixed in master thanks to @mlutze
