### ISSUE TITLE
Add support for user-defined effects to `HtmlDocumentor`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6362]
The Flix Standard Library does not (yet) contain any effects with operations, but here is an example:

```
eff MyConsole {
    pub def print(s: String): Unit

    pub def println(s: String): Unit
}
```

We can currently show effects, but not their operations. (Operations are most like signatures of a class).

(I created this as a separate ticket because you need above example to have something to test with.)

**Comment by sockmaster27** [comment]
We actually already do :)
![image](https://github.com/flix/flix/assets/61235930/4c1918aa-d33d-4632-a833-0f6787a1189f)

I'll change the name to 'Operations' though
