### ISSUE TITLE
Rename "record field" to "record label" everywhere

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6399]
The idea is that records will have "labels" and in the future structs will have "fields".

This means everywhere in the compiler (but also on doc.flix.dev and flix.dev), we need "record field" to become "record label".

**Comment by jaschdoc** [comment]
Should I rename `Name.Field`? I suppose it should remain `Field` as it will be used for structs too.

**Comment by magnus-madsen** [comment]
> Should I rename `Name.Field`? I suppose it should remain `Field` as it will be used for structs too.

No. We will have both `Name.Label` and `Name.Field`-- they will not be the same, because they are conceptually not the same.

So Yes, rename it too.
