### ISSUE TITLE
Split `Weeder` into `Weeder` and `Desugar`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6421]
The idea is to split the weeder into two: one that performs all the syntactic checks and one that rewrites constructs (e.g. `form`).

Crucially, the `Desugar` phase should not emit any errors at all. It should simply translate expressions into other expressions.

I suggest to do this incrementally: 

- [x] Introduce a new ast `DesugaredAst` based on `WeededAst`.
- [x] Introduce a phase `Desugar` between `Weeder` and `Namer` (at first this would be more or less the identity function).
- [ ] Move one translation at a time from `Weeder` into `Desugar`.

**Comment by magnus-madsen** [comment]
@jaschdoc I would like this to be the next PR because we will be building on it soonish.

Does the task and outline seem sensible?

I prefer small PRs.

**Comment by jaschdoc** [comment]
Yes :)

**Comment by jaschdoc** [comment]
- [ ] Introduce a new ast `DesugaredAst` based on `WeededAst`.
- [ ] Introduce a phase `Desugar` between `Weeder` and `Namer` (at first, this would be more or less the identity function).
- [ ] Move one translation at a time from `Weeder` into `Desugar`.

**Comment by jaschdoc** [comment]
- [x] Infix
- [ ] LambdaMatch
- [x] ApplicativeFor
- [x] ForEach
- [x] MonadicFor
- [x] ForEachYield
- [ ] LetMatch
- [ ] LetImport (?)
- [ ] Static (?)
- [ ] Tuple
- [ ] RecordLit (?)
- [ ] RecordOperation (?)
- [ ] FCons
- [ ] FAppend
- [ ] ListLit
- [ ] SetLit
- [ ] MapLit
- [ ] Interpolation
- [ ] FixpointSolveWithProject
- [ ] FixpointQueryWithSelect
- [ ] Debug (?)

**Comment by magnus-madsen** [comment]
- Cleanup and reorder.

**Comment by magnus-madsen** [comment]
- Liftharded symbols/names/strings to top of `Desugar` class.

**Comment by jaschdoc** [comment]
>  Liftharded

What does this mean?

**Comment by magnus-madsen** [comment]
It means to move the constant strings to the top of the file (e.g. "Functor")

**Comment by magnus-madsen** [comment]
Are we getting close to done? What is missing?

**Comment by jaschdoc** [comment]
Should we move this to Desugar? It's technically a desugaring, but I'm not sure it's worth delaying it to Desugar. If we move it, it would help clearly separate Weeder and Desugar.
```scala    
    case ParsedAst.Expression.Static(sp1, sp2) =>
      val loc = mkSL(sp1, sp2)
      val tpe = Type.mkRegion(Type.EffUniv, loc)
      WeededAst.Expr.Region(tpe, loc).toSuccess

```

**Comment by magnus-madsen** [comment]
Nah. We only more meaningful things.

**Comment by jaschdoc** [comment]
I just discovered that it actually eliminates the `WeededAst.Expr.Region` ast node, so it's basically just a renaming to `WeededAst.Expr.Static`. See https://github.com/flix/flix/pull/6854

**Comment by jaschdoc** [comment]
Also, is this a desugaring or just unfolding the syntactic structure to an ast?
```scala
    case ParsedAst.Expression.RecordOperation(_, ops, rest, _) =>
      // We translate the sequence of record operations into a nested tree using a fold right.
      foldRight(ops)(visitExp(rest, senv)) {
        case (ParsedAst.RecordOp.Extend(sp1, ident, exp, sp2), acc) =>
          mapN(visitExp(exp, senv), visitIdent(ident)) {
            case (e, id) =>
              WeededAst.Expr.RecordExtend(Name.mkLabel(id), e, acc, mkSL(sp1, sp2))
          }

        case (ParsedAst.RecordOp.Restrict(sp1, ident, sp2), acc) =>
          mapN(visitIdent(ident)) {
            case id => WeededAst.Expr.RecordRestrict(Name.mkLabel(id), acc, mkSL(sp1, sp2))
          }

        case (ParsedAst.RecordOp.Update(sp1, ident, exp, sp2), acc) =>
          mapN(visitExp(exp, senv), visitIdent(ident)) {
            case (e, id) =>
              // An update is a restrict followed by an extension.
              val inner = WeededAst.Expr.RecordRestrict(Name.mkLabel(id), acc, mkSL(sp1, sp2))
              WeededAst.Expr.RecordExtend(Name.mkLabel(id), e, inner, mkSL(sp1, sp2))
          }
      }
```

**Comment by jaschdoc** [comment]
Also I think we should reconsider https://github.com/flix/flix/pull/6767 as it clearly separates Weeding / error checking and actual desugaring. Right now the code for it is just one big monster.

**Comment by jaschdoc** [comment]
I have done a review of Weeder and we should be done once we resolve the following issues:

- [ ] https://github.com/flix/flix/issues/6421#issuecomment-1840721795
- [ ] https://github.com/flix/flix/issues/6421#issuecomment-1840729007
- [ ] https://github.com/flix/flix/issues/6421#issuecomment-1840741744
- [ ] https://github.com/flix/flix/pull/6855
- [ ] https://github.com/flix/flix/issues/6421#issuecomment-1807202859

**Comment by jaschdoc** [comment]
@magnus-madsen I need your input on https://github.com/flix/flix/issues/6421#issuecomment-1840769751 :)

**Comment by magnus-madsen** [comment]
> I just discovered that it actually eliminates the `WeededAst.Expr.Region` ast node, so it's basically just a renaming to `WeededAst.Expr.Static`. So it could make sense to move it. See #6854

I think this is so small its not worth worrying about. Also not clear what will happen to static.

**Comment by magnus-madsen** [comment]
> Also, is this a desugaring or just unfolding the syntactic structure to an ast?

I think there are just unfolding. We are not really desugaring one construct into a set of different constructs.

**Comment by magnus-madsen** [comment]
> * Liftharded symbols/names/strings to top of `Desugar` class.

Lets do this later.

**Comment by magnus-madsen** [comment]
> @magnus-madsen I need your input on [#6421 (comment)](https://github.com/flix/flix/issues/6421#issuecomment-1840769751) :)

I answered all 4. So it seems we are close to done for this round?

Any last cleanup to do? Maybe you can take a quick look through Desugar and make sure its neat and tidy.
