### ISSUE TITLE
HtmlDocumentor should only show public definitions, not private

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6464]
`List.agreeHelper` is private:

![image](https://github.com/flix/flix/assets/2287953/46e94e3d-6869-44f5-93b2-762f7815dc92)

**Comment by sockmaster27** [comment]
Is this on the main branch?

**Comment by magnus-madsen** [comment]
> Is this on the main branch?

This was with your JAR, so yes.

**Comment by magnus-madsen** [comment]
It seems like a regression actually.

**Comment by sockmaster27** [comment]
> It seems like a regression actually.

Yeah, I refactored this part in the last PR
