### ISSUE TITLE
HtmlDocumenter: Menu should include classes, effects, types, etc. as modules

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6484]
![image](https://github.com/flix/flix/assets/2287953/6723286e-6c84-4bb4-9fc0-197440dec277)

Since e.g. `Applicative` -- a type class -- defines a module, it should also be listed in the module section. 

So Modules cover everything, and what follows is a more detailed breakdown.

**Comment by magnus-madsen** [comment]
Thus if you don't know what you are looking for  you can skim modules, but if you know you are looking for a class or type, you can jump there.

///Alternatively/// we should combine everything into one menu and use the colors to distinguish?

**Comment by magnus-madsen** [comment]
Perhaps the best is that Modules simply includes classes, enums, effects.

**Comment by sockmaster27** [comment]
I actually put in some effort to make sure they were _not_ included, haha.

I think including them twice would be very confusing, and since they can't share names and are all 'modules' anyway I think this is already the most well structured way of presenting them.

**Comment by magnus-madsen** [comment]
But its very strange to use. I look for the Applicative module and it does not exist! (But it does exist!)

**Comment by sockmaster27** [comment]
I guess it depends on the mental model. If you define `class Associative` and `mod Associative`, is it a class with a module attached, a module with a class attached or is it two separate entities that are associated with each other?

**Comment by sockmaster27** [comment]
If the terminology is 'companion module' I'd say the first one makes more sense.

**Comment by magnus-madsen** [comment]
I would say every class (etc) implicitly defines a module.

**Comment by magnus-madsen** [comment]
I think once this is done/restored then I will upload the new version to api.flix.dev and we can move onto other things for a while :)

**Comment by sockmaster27** [comment]
So did we want them to appear twice? Once under 'submodules' and once under 'classes', 'enums' or 'effects'?

**Comment by magnus-madsen** [comment]
> So did we want them to appear twice? Once under 'submodules' and once under 'classes', 'enums' or 'effects'?

Yep

**Comment by magnus-madsen** [comment]
It seems stuff is still missing, e.g. some type classes?

**Comment by sockmaster27** [comment]
> It seems stuff is still missing, e.g. some type classes?

Should the classes without a companion module also be shown under modules?

**Comment by magnus-madsen** [comment]
> > It seems stuff is still missing, e.g. some type classes?
> 
> Should the classes without a companion module also be shown under modules?

Yes. Better to think of it this way: Every class, effect, or type gives rise to a module.

**Comment by sockmaster27** [comment]
> > > It seems stuff is still missing, e.g. some type classes?
> > 
> > Should the classes without a companion module also be shown under modules?
> 
> Yes. Better to think of it this way: Every class, effect, or type gives rise to a module.

Then I think we should rethink the menu, because if every single class, effect and enum is also a module then I don't see the point of dividing them into sections.

**Comment by magnus-madsen** [comment]
> > > > It seems stuff is still missing, e.g. some type classes?
> > > 
> > > 
> > > Should the classes without a companion module also be shown under modules?
> > 
> > 
> > Yes. Better to think of it this way: Every class, effect, or type gives rise to a module.
> 
> Then I think we should rethink the menu, because if every single class, effect and enum is also a module then I don't see the point of dividing them into sections.

What's your proposal? It might be useful if you know you are looking for a class or a type?

**Comment by magnus-madsen** [comment]
How about you implement what I propose and I can deploy it. Then afterwards you can sketch/describe/implement your own proposal?

**Comment by sockmaster27** [comment]
> What's your proposal? It might be useful if you know you are looking for a class or a type?

Ultimately, I think this would be solved by a search function, where you would only use the overview to discover things you didn't know you were looking for. At that point it would be preferable not to have the same thing appear twice, but only under the most precise category.

Until then, I guess we can add companion modules under submodules too, to not confuse the user who has only used  the companion part of an item, or have written their own module and is looking for it there. I'm even a bit skeptical about whether this is worth optimizing for, since it brings quite alot of bloat to the size of the menu.

I'm even less convinced that an item without a companion module should appear as a submodule, since I don't see any reason you would be looking for it there.

**Comment by magnus-madsen** [comment]
@sockmaster27 

This does not look right, does it?:

![image](https://github.com/flix/flix/assets/2287953/7db0410d-3acb-467e-a788-88433e949785)
