### ISSUE TITLE
Add `MutDisjointSet`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6485]
i.e. a union-find data structure with union-by-rank and path-halving

We should have an API like:

```scala
enum MutDisjointSet[t, r] {
    // Parent
    // Rank
    case MutDisjointSet(Ref[Option[MutDisjointSet[t, r], r], Ref[Int32, r])
}

def singleton(rc: Regionr[r], x: t): MutDisjointSet[t, r] \ r // aka makeSet
def find(x: MutDisjointSet[t, r]): MutDisjointSet[t, r]
def union(x: MutDisjointSet[t, r], y: MutDisjointSet[t, r]): Unit \ r
def equivalent(x: MutDisjointSet[t, r], y: MutDisjointSet[t, r]): Bool \ r = find(x) == find(y)
```

The above is just a doodle.

It is possible that `equivalent` requires use of `java.lang.Objects.equals` because we cannot compare for object identity in Flix (yet).

https://en.wikipedia.org/wiki/Disjoint-set_data_structure

EDIT: Wikipedia drops the "optionality" of the parent pointer in favor of just linking it to itself.

**Comment by magnus-madsen** [comment]
@jaschdoc Would you be interested in this? There is a deadline of approx 3 weeks.

**Comment by magnus-madsen** [comment]
Possible one `MutDisjointSet` data type is not enough and we need both a `MutDisjointSet` and a `Node` data type. 

For example, if we want to iterate over all elements in the forest or if we want to find the node for a specific value `x`.

**Comment by jaschdoc** [comment]
Sounds good. I'm on it
