### ISSUE TITLE
Add support for qualified `use`s

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6515]
We should bikeshed the syntax, but the essence is:

```
mod A.B.C.D {
  def foo(): Unit = ()
}
```

somewhere else:

```
use A.B.C.D;
D.foo()
```

**Comment by magnus-madsen** [comment]
@JonathanStarup I know you would like this too :)

**Comment by magnus-madsen** [comment]
@stephentetley Do you have any thoughts on this?

**Comment by JonathanStarup** [comment]
Here's the previous issue #3789

**Comment by stephentetley** [comment]
Yes - I would like this too.

I suppose there is the issue of whether to use / import single modules or namespaces, e.g.:

~~~

/// Import "one level up from D" ...
use A.B.C;
C.D.foo()

~~~

I think I could live comfortably with just importing modules a la Magnus's example rather than my example.

**Comment by magnus-madsen** [comment]
This feature does already exist/work ??

**Comment by JonathanStarup** [comment]
using the nested modules `A.B.C`:
- You cannot `use A.B; use B.C`
- You can `use A.B` and call `B.f()` (also works if `B` is a class)
- You can `use A.B` and call `B.C.f()`

**Comment by magnus-madsen** [comment]
I think this is already implemented.
