### ISSUE TITLE
Parser2 symbols as functions

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6524]
It would be nice if we could support writing e.g.:

```
List.foldLeft(0, +, l)
```

**Comment by magnus-madsen** [comment]
CC @herluf-ba

**Comment by magnus-madsen** [comment]
(As future work)

**Comment by herluf-ba** [comment]
Right now the lexer produces these tokens:
```
NameUpperCase Dot NameLowerCase ParenL LiteralInt32 Comma Plus Comma NameLowerCase ParenR Eof
```
Which should be sufficient as far as the lexer is concerned. We still need to modify later phases to make this work though 🙂
