### ISSUE TITLE
Path to Java 21

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6579]
- [x] Flix compiles with JDK 21.
- [x] Bump JDK to 21 on GitHub CI.
- [x] Remove `--Xvirtual-threads`.
- [x] Upgrade to ASM 9.6
- [x] Update gradle to emit bytecode for JDK 21.
- [x] Emit JDK 21 bytecode.
- [x] Use VirtualThreads
- [x] Require Java 21 in VSCode.
- [x] Update website to say we require Java 21
- [x] Update documentation to say we require Java 21

**Comment by stephentetley** [comment]
This will be nice for implementing a Flix QuickCheck. I got stuck before because I needed functions in Java's `SplittableRandom` that weren't introduced until Java 17.

**Comment by magnus-madsen** [comment]
I think there are also some Array and String methods we may want to make use of.

**Comment by magnus-madsen** [comment]
We are now Java 21 🥳
