### ISSUE TITLE
Replace dependence on `scala-parallel-collections` with ordinary Java

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6583]
The idea is to drop the use of `scala.collection.parallel._` and instead use ordinary Java threads/thread pools/fork join.

I recommend to start by changing the `build.gradle` file to remove the dependency so its easy to see what has to be changed.

**Comment by magnus-madsen** [comment]
@sockmaster27 Once the PR with `parMapSeq` is in, you can look at this.

**Comment by magnus-madsen** [comment]
@sockmaster27 Let me know if you need more information.

**Comment by magnus-madsen** [comment]
Inspiration may be found in: https://github.com/flix/flix/pull/6584

**Comment by sockmaster27** [comment]
> Inspiration may be found in: #6584

What's the reason for not just merging this?

**Comment by magnus-madsen** [comment]
> > Inspiration may be found in: #6584
> 
> What's the reason for not just merging this?

We are not switching to Java 21 just yet.

**Comment by magnus-madsen** [comment]
But in any case- that PR alone is not sufficient.

Also its not clear if VirtualThreads are even better than ordinary threads, so it would be nice to have an ordinary thread implementation.

**Comment by magnus-madsen** [comment]
I think we are stuck on this. Let me look into it and report back.

**Comment by magnus-madsen** [comment]
Fixed in master.
