### ISSUE TITLE
Allow meta-constructor in `typematch`?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6585]
E.g. allow:

```scala
     typematch(f) {
          case Pure(g) => parMapWithKey(g, t)
          case _       => seqMapWithKey(f, t)
     }

```

**Comment by magnus-madsen** [comment]
@mlutze What do you think about this syntactic sugar?

**Comment by mlutze** [comment]
Can we define that in the standard lib?

```scala
enum EffMatch[a: Type, b: Type, ef: Eff] {
    case Pure(a -> b)
    case Impure(a -> b \ ef)
}

def effmatch(x: f: a -> b \ ef): EffMatch[a, b, ef] = typematch f {
    case g: a -> b \ Pure => Pure(g)
    case _: _ => Impure(f)
}

**Comment by magnus-madsen** [comment]
Interesting idea

**Comment by magnus-madsen** [comment]
I propose to add this to the Prelude (What Matt had, but renamed)

```
enum Purity[a: Type, b: Type, ef: Eff] {
    case Pure(a -> b)
    case Impure(a -> b \ ef)
}

def purityOf(f: a -> b \ ef): Purity[a, b, ef] = typematch f {
    case g: a -> b \ Pure => Pure(g)
    case _: _ => Impure(f)
}
```

Although: I think the name `Pure` clashes with the effect of the same name?

If the name is taken, perhaps `PureFn`and `ImpureFn` can be used.

While this little trick makes the code cleaner, it still does not solve the problem for curried functions.

**Comment by magnus-madsen** [comment]
@jashdoc Could you take a stab? Add the above enum and function, and then use it in two different places so we can see how it looks/feels.

**Comment by jaschdoc** [comment]
Sure :)
