### ISSUE TITLE
Parse `ApplicativeFor` with `ForFragment`

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#6601]
Currently, it's uing `GeneratorFragment` ensuring that only `x <- collection` can be parsed, but we can just handle this requirement in the `Weeder`, making it simpler in the parser, and yielding better error messages.

**Comment by magnus-madsen** [comment]
We are replacing `Parser.scala` completely, so maybe this is not relevant?

**Comment by jaschdoc** [comment]
This is a matter of calling a function that returns a certain type or calling a function that returns a (general) super type. Are we not going to have the same problem? Or is this sort of error handling then moved to the new parser?

**Comment by magnus-madsen** [comment]
I don't follow. If it is an easy fix then go ahead. Otherwise let us wait and see what happens with the new parser.

**Comment by jaschdoc** [comment]
I'll let this rest for a bit. It's easy to do, but I'll see if it's relevant as I move more stuff to `Desugar`.

**Comment by jaschdoc** [comment]
Not worth changing
