### ISSUE TITLE
ParOps operations and naming

### ISSUE THREAD

**Issue by mlutze** [flix/flix#6613]
- On linear collections
  - `map`
  - `sequence`
  - `traverse`
  - `fold`
- On maps
  - `mapValues`
  - `traverseValues`
  - `sequenceValues`
- On listmaps
  - `mapValues`
  - `traverseValues`
  - `sequenceValues`

**Comment by magnus-madsen** [comment]
If you come up with a proposal, we can discuss it.

Maybe this is more of a December-have-fun-ticket :)
