### ISSUE TITLE
Change Effect handlers to receive `resume` explicitely

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#6642]
Current syntax
```flix
eff MyEffect {
    pub def yield(): Unit
}
```
```flix
try {
    // ...
    do MyEffect.yield();
    // ...
} with MyEffect {
    def yield() = resume(())
}
```
My proposed syntax
```flix
try {
    // ...
    do MyEffect.yield();
    // ...
} with MyEffect {
    def yield(resume) = resume(())
}
```
Which additionally could allow you to omit the call to resume if you don't have the explicit argument
```flix
try {
    // ...
    do MyEffect.yield();
    // ...
} with MyEffect {
    def yield() = ()
}
```

**Comment by magnus-madsen** [comment]
Seems reasonable. Presumably it becomes the last argument.

**Comment by JonathanStarup** [comment]
I could also just be done internally (which I have to do now to lift the body) but I think exposing it to source is nice for the programmer

**Comment by magnus-madsen** [comment]
I think the ultimate decision can be made later, but for now we can do what you prefer.
