### ISSUE TITLE
Use parallel evaluation throughout the compiler

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6655]
Add or rework parallel evaluation in:

- [x] ~`Reader`~ -- deliberately not parallel, because disk IO does not benefit from parallel reads.
- [x] `Namer` -- rework to have parallelism at the unit level, i.e. we should use parallelism on `program.units` in `run`.
- [x] `Resolver` -- introduce parallelism (but not yet clear how)
- [x] `Deriver` -- introduce parallelism in `run` over `root.enums`.
- [x] `Redundancy` -- seems more parallelism would be possible, e.g. in `checkRedundantTypeConstraints` 
- [x] `TreeShaker1/TreeShaker2` -- these phases are conceptually similar and already use parallelism, but the speedup is not much. Can anything be done?
- [x] `MonoDefs` -- an improvement here would be to forego the global queue context and split it into a "LocalContext" and a "GlobalContext".
- [x] `MonoTypes` -- similar to `MonoDefs`.
- [x] `Simplifier` -- this phase has a dead mutable map `toplevel` which can be removed, then all functions should be un-nested from `run` and finally the phase can be made parallel. Probably this should be done in multiple PRs.
- [x] `ClosureConv` -- this function can use a light cleanup and then it is easy to make parallel.
- [x] `LambdaLift` -- this phase relies on a mutable map `toplevel`. To make it parallel we need to guard access to it. 
- [x] `TailRec` -- this phase can easily be made parallel. Good place to start.
- [x] `Inliner` -- it seems this phase can be made parallel.
- [x] `Reducer` -- trivial to make parallel. Good place to start.
- [x] `VarNumbering` -- trivial to make parallel. Good place to start.
- [x] `JvmBackend` -- this is a beast. A few places there is room for parallelism:
  - In `JvmOps.typesOf` -- can be parallel or even precomputed?
  - ....

**Comment by magnus-madsen** [comment]
The tool for understanding these things is `Xperf` and then running `plots.py` in `build/perf` and looking at e.g. `speedupWithPar`:

![image](https://github.com/flix/flix/assets/2287953/6b5be84a-7e56-4b69-80cb-b4c2610f42d0)

**Comment by magnus-madsen** [comment]
Hey @stephentetley would you be interested in helping us with this? What we need is to find the right abstractions for `ParOps` and then to apply them consistently throughout the compiler.

**Comment by stephentetley** [comment]
Hi Magnus, yes I'd be happy to help. I'll be a bit busy for the next fortnight though.

**Comment by magnus-madsen** [comment]
I was procrastinating and this turned out to be great fun-- so I did all the easy work :)

There will be another ticket with further ideas.
