### ISSUE TITLE
Break apart enums in backend

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#6685]
Right now, an enum is a collection of cases that are kept that way throughout the compiler. We type-specialize each enum to its uses, which means that enum cases like `Option.Nil` will be generated many times. We could avoid this redundancy be considering enum cases as the base element and reuse whenever possible.

**Comment by magnus-madsen** [comment]
We could even go further and just have only tags and use `Object` as the type of enums.

**Comment by magnus-madsen** [comment]
Any case, I think you are the only one who can make these changes (when eventually you find the time).
