### ISSUE TITLE
Code/Meta seperation in `build/`

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#6712]
Right now auxiliary information is put along side actual generated code, e.g. `build/asts/...` is right next to `build/Clo$main$146782`. We should have `build/code/` and `build/meta/` or something like that.

It also looks prettier when looking for meta stuff instead of immediately seeing 100s of compiled java classes.

**Comment by magnus-madsen** [comment]
We should place generated classes into a `build/class` folder.

**Comment by magnus-madsen** [comment]
I think this is a small change. Probably have to change a path in one place and ensure that build-jar still works.
