### ISSUE TITLE
MismatchingReturnType error location should be more precise

### ISSUE THREAD

**Issue by ZiyaoWei** [flix/flix#6719]
Currently the error location when an imported Java method has the wrong return type is not precise enough. E.g., for

```
def main(): Unit \ IO =
    import java.net.http.HttpResponse.body(): ##java.lang.String \ IO as body;
    println("Hello world")
```

the error is

```
-- Resolution Error -------------------------------------------------- /Users/wzy/Projects/chess/traps.flix

        >> Mismatched return type for method 'body' in class 'java.net.http.HttpResponse'.

2 |>     import java.net.http.HttpResponse.body(): ##java.lang.String \ IO as body;
3 |>     println("Hello world")

mismatched return type.
Declared type: Cst(Str,/Users/wzy/Projects/chess/traps.flix:2:47:2:65)
Expected type: Cst(Native(class java.lang.Object),<unknown>:0:0:0:0)
```

the string representations of the types here could use some love too.

Would be happy to try to fix this and would appreciate some code pointers :-)

**Comment by magnus-madsen** [comment]
Hi @ZiyaoWei 

Here is the source: https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala#L756

**Comment by magnus-madsen** [comment]
Not sure if we have a pretty printer for unkinded types, @mlutze Do you know?

But you should be able to use a more precise source location.

**Comment by mlutze** [comment]
> Not sure if we have a pretty printer for unkinded types, @mlutze Do you know?
> 
> But you should be able to use a more precise source location.

We do not

**Comment by magnus-madsen** [comment]
I think format type is a whole separate can of worms. You can create a ticket, but for this specific issue I would try to do something else/simpler.

**Comment by JonathanStarup** [comment]
Outdated with the new interop
