### ISSUE TITLE
Rework Validation

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6746]
Phase 1:

- [x] Drop all `sequenceT` functions -- they are unused.
- [x] Add a smart constructor `Validation.success(t)`
- [x] Add a smart constructor `Validation.softFailure(t, e)`
- [x] Add a smart constructor `Validation.softFailures(t, es)` -- takes a list of errors
- [x] Add a smart constructor `Validation.hardFailure(e)`
- [x] Add `toResult: Result[(t, List[e]), List[e])` to Validation -- `Success` and `SoftFailure` are both treated as `Result.Ok`
- [x] Drop implicit class `ToSuccess`.
- [x] Drop implicit class `ToSoftFailure`.
- [x] Drop implicit class `ToFailure`.
- [ ] Make `Success` case class private.
- [ ] Make `SoftFailure` case class private.
- [ ] Make `Failure` case class private.
- [ ] Rename `Failure` case class to `HardFailure`.
- [x] Introduce `Recoverable` trait next to `CompilationMessage`
- [x] Introduce `Unrecoverable` trait next to `CompilationMessage`.
- [x] Modify the signature of `softFailure/softFailures` to take a `Recoverable`. Adjust errors as required.
- [x] Modify the signature of `hardFailure/hardFailures` to take an `Unrecoverable`. Adjust errors as required.
- [x] `ap` and `flatten` should be private, if possible.
- [x] `SuccessNil`, `SuccessNone`, and `SuccessUnit` should be private (or removed if unused).
- [ ] `withSoftFailure` should require `Recoverable`
- [ ] `withSoftFailures` should require `Recoverable`
- [x] Rename `get` to `unsafeGet`
- [x] Drop `map` directly on `Validation` and instead introduce `mapN` for a single argument (for consistency).
- [ ] Refactor `Validation.fold` to `Validation.foldLeft`. It should be curried and take a Validation as zero arg. 
- [ ] Ensure every function is tested.
- [ ] Move all private functions last in Validation (public, private) should be the order.
- [ ] Drop `traverseX`. Instead use `traverse` or better `withSoftFailure`...
- [ ] Drop `sequenceX` use `traverse`.
- [ ] Drop `sequence` use `traverse`. 

Multiple meaningful PRs please.

**Comment by magnus-madsen** [comment]
@jaschdoc I think starting to use `Validation.success(foo)` one phase at a time is the next reasonable thing to do.

**Comment by magnus-madsen** [comment]
I think the next step is to introduce `toResult` as outlined above, and then to make case classes private.

**Comment by jaschdoc** [comment]
>  Drop map directly on Validation and instead introduce mapN for a single argument (for consistency).

I think we need this for the for-comprehension in Flix.scala

```scala
 afterReader <- Reader.run(getInputs)
      afterLexer <- Lexer.run(afterReader, cachedLexerTokens, changeSet)
      afterParser <- Parser.run(afterReader, entryPoint, cachedParserAst, changeSet)
      afterWeeder <- Weeder.run(afterParser, cachedWeederAst, changeSet)
      afterDesugar <- Desugar.run(afterWeeder, cachedDesugarAst, changeSet)
      afterNamer <- Namer.run(afterDesugar)
      afterResolver <- Resolver.run(afterNamer, cachedResolverAst, changeSet)
      afterKinder <- Kinder.run(afterResolver, cachedKinderAst, changeSet)
      afterDeriver <- Deriver.run(afterKinder)
      afterTyper <- Typer.run(afterDeriver, cachedTyperAst, changeSet)
      afterEntryPoint <- EntryPoint.run(afterTyper)
      _ <- Instances.run(afterEntryPoint, cachedTyperAst, changeSet)
      afterPredDeps <- PredDeps.run(afterEntryPoint)
      afterStratifier <- Stratifier.run(afterPredDeps)
      afterPatMatch <- PatMatch.run(afterStratifier)
      afterRedundancy <- Redundancy.run(afterPatMatch)
      afterSafety <- Safety.run(afterRedundancy)
```

**Comment by magnus-madsen** [comment]
> I think we need this for the for-comprehension in Flix.scala

Ok, let me think.

**Comment by jaschdoc** [comment]
I'm not sure it's a good idea, but we could add an implicit class in `Flix.scala` that wraps `Validation.mapN` and provides a (scala) `map` implementation.

**Comment by magnus-madsen** [comment]
> I'm not sure it's a good idea, but we could add an implicit class in `Flix.scala` that wraps `Validation.mapN` and provides a (scala) `map` implementation. That way it's only declared where it's relevant.

Possibly. For now I have suggested to get rid of usages of `map` everywhere, except for `Flix.scala`

@mlutze Do you have any opinion?

**Comment by mlutze** [comment]
> > I'm not sure it's a good idea, but we could add an implicit class in `Flix.scala` that wraps `Validation.mapN` and provides a (scala) `map` implementation. That way it's only declared where it's relevant.
> 
> Possibly. For now I have suggested to get rid of usages of `map` everywhere, except for `Flix.scala`
> 
> @mlutze Do you have any opinion?

I thought we already had this somewhere.

**Comment by jaschdoc** [comment]
- [ ] Add `mapErr`.

**Comment by jaschdoc** [comment]
Should we consider adding distinct types `SoftResult` and `HardResult` that extend `Result`? That way we have exhaustiveness checking and callers of `Validation.toSoftResult/toHardResult` will handle all cases. We can do this in a separate PR to https://github.com/flix/flix/pull/7006 and https://github.com/flix/flix/pull/7005

**Comment by magnus-madsen** [comment]
No, I think its fine the way it is.

**Comment by magnus-madsen** [comment]
Your comments in #7381 suggest I need to rethink the overall approach :[

**Comment by magnus-madsen** [comment]
I have decided to pause this while I rethink the overall approach.

**Comment by magnus-madsen** [comment]
We are planning to get rid of Validation.
