### ISSUE TITLE
Add a free effect to `?hole` or `???`

### ISSUE THREAD

**Issue by octylFractal** [flix/flix#6851]
Currently, if I have a function where I know I'm going to need an effect, such as `IO`, in the future, I cannot mark it with that and use a hole to leave it unimplemented, as follows:
```
def my_future_io_function(): Unit \ IO = ?hole
```

The compiler will complain `Expected effect 'IO' but found effect: 'Pure'.`

I can work around this with `checked_ecast(?hole)` instead, but I feel like I shouldn't need to write extra code depending on what kind of unimplemented function I want.

Flix version `0.42.0`.

**Comment by mlutze** [comment]
This is discussed in this issue: https://github.com/flix/flix/issues/2540

Maybe it is worth reviving.

**Comment by JonathanStarup** [comment]
For future readers: `???()` or `?hole()` achieves the same result, of emitting an unknown effect

**Comment by magnus-madsen** [comment]
I think we can add a free effect both.

**Comment by mlutze** [comment]
Isn't this already implemented?

**Comment by magnus-madsen** [comment]
You tell me :)

**Comment by mlutze** [comment]
Not yet: #8362
