### ISSUE TITLE
enum with Order is incorrectly derived in some cases

### ISSUE THREAD

**Issue by octylFractal** [flix/flix#6856]
With the following code:
```
enum HandType with Order, Eq {
    case OnePair
    case TwoPair
    case ThreeOfAKind
    case FullHouse
    case FourOfAKind
}

pub def main(): Unit \ IO =
    println("OnePair < TwoPair: ${HandType.OnePair < HandType.TwoPair}");
    println("TwoPair < ThreeOfAKind: ${HandType.TwoPair < HandType.ThreeOfAKind}")
```

It unexpectedly prints:
```
OnePair < TwoPair: true
TwoPair < ThreeOfAKind: false
```

Clearly, since the `TwoPair` comes before `ThreeOfAKind`, it should print `true` in both cases.

Removing `FullHouse` or `FourOfAKind` appears to fix the problem, so it is likely related to the size of the enum for some reason.

[Playground](https://play.flix.dev/?q=KYOwrgtgBAEghiAJgFQJ4AdhQO4EsAuAFlAPIBOiwZANFAKICOUA3gFBQdQDGcAzliRDAACnFxl2nHvyjJsAe1HjJHaVmSEywYCQBmAQQDSuJCu58sAMTAAbGzHlh+ZtVEuOyeoycSsAvqys6GAARlCUulAQYiAAFACUAFxQAKogBFAAOlAAkiRQALxm6GQm+DZxAESCImJkUAA8sgpKZMkAJMzwSGiYAHQ1rY2wCCgYwH1yinV+lfEA3MWlIOVVU0NNGlo6BsZIHV2jvRPrdcPdY-1b2l57iLPxQA)

**Comment by magnus-madsen** [comment]
That is strange! Thanks for reporting @octylFractal

**Comment by magnus-madsen** [comment]
@octylFractal You could try a nightly from https://flix.dev/nightly/

**Comment by octylFractal** [comment]
How would I do that with the VS Code extension?

**Comment by magnus-madsen** [comment]
Just put the jar in the same folder as the source.

**Comment by magnus-madsen** [comment]
Fixed in latest release.
