### ISSUE TITLE
Systematic Erasure and boxing

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#6885]
Currently erasure and boxing is done all over the place in the backend. I think we should have a dedicated erasure and boxing phase (which we have also talked about for a while). This would:
- Reduce complexity in the backend
- commit all erasure logic to one set place

But where should the phase be placed? Current phases are
- ...
- Optimizer (inlining etc)
- TreeShaker2 (removed dead code?)
- Reducer (collect all types and local parameters)
- EffectBinder (effect normal form, maintain local parameters)
- VarOffsets (give variables an offset)
- Backend (gen code)

It seems to me that it makes sense to erase and box before collecting the set of all types. My suggestion is the following
1. move the local parameter analysis from Reducer to a) EffectBinder or b) a new phase after EffectBinder
2. Add erasure and boxing logic go reducer
3. if 1b is chosen, maybe this new phase should also find the local parameters instead of EffectBinder
4. It seems to me that the information collection (var offsets, all types, anon classes, etc) should happen after all transformations are done and just before generation. This would mean that phases should really be erasure -> effectBinder -> collectTypes -> collectAnonClasses -> localParams -> varOffsets. These phases would be very small so it might not be like that in practice, but i think this ordering is better and will not have complications like effectbinder having to maintain previously collected information.

**Comment by magnus-madsen** [comment]
I guess it would be simplest to add a new phase before Reducer. Do you agree?

**Comment by magnus-madsen** [comment]
Do we understand where boxing is needed? I assume this is when going to and from Java?

**Comment by magnus-madsen** [comment]
Possibly Eraser could be from LiftedAst to LiftedAt then?

**Comment by JonathanStarup** [comment]
Uhm yeah that could work. Lifted already seems to have casts, ill give it a go

**Comment by JonathanStarup** [comment]
Fixed in master (eraser is wip but is on the way)
