### ISSUE TITLE
Filter NS methods

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#6901]
All reachable functions have a `Def$someFunction` class based on the tree shaker. These classes have an `invoke` function that uses our calling convention. For some subset of those functions, we generate a matching `NS.m_someFunction` that calls `Def$someFunction` but unwinds the trampoline. This PR limits those `NS.m_` methods to those that might be used.

**Comment by magnus-madsen** [comment]
How does this improve on the tree shaker? I would that's it main job. Why does this logic belong in the backend?

**Comment by JonathanStarup** [comment]
All reachable functions have a `Def$someFunction` class, based on the tree shaker. These classes have invoke which uses our calling convention. For some subset of those functions we generate a matching `NS.m_someFunction` that calls `Def$someFunction` but unwinds the trampoline. This PR is limiting those `NS.m_` methods to those who might actually be used.
