### ISSUE TITLE
Make function calls invokevirtual again

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#6907]
`Thunk` was made an interface for effect purposes, but a new direct implementing abstract class should be made below such that its methods become `INVOKEVIRTUAL`.

The specific method is `Thunk.invoke`. Thunk has to be a functional interface because of `ResumptionCons.rewind` and `Handler.installHandler`. This fix is not simple, but perhaps those two methods could use another interface that mimics `Thunk`, which could then be converted into an actual `Thunk` at relevant points. This would allow `Thunk` to become an abstract class again, making method invocations use `INVOKEVIRTUAL`.

I don't know if it is possible.

**Comment by magnus-madsen** [comment]
What would be the purpose / advantage?

**Comment by JonathanStarup** [comment]
The first big performance drop off the worst benchmark seems to come from this change. made that benchmark x20 slower

**Comment by magnus-madsen** [comment]
This is not the Datalog benchmark, right? Because I made that slower for other reasons.

**Comment by magnus-madsen** [comment]
I dont see why invokeinterface vs invokevirtual should have different performance.

**Comment by JonathanStarup** [comment]
afaik invokevirtual has a fixed method index because of single inheritance, while interface methods have differnet offsets per class. I can look again at the exact commit and investigate

**Comment by magnus-madsen** [comment]
> afaik invokevirtual has a fixed method index because of single inheritance, while interface methods have differnet offsets per class. I can look again at the exact commit and investigate

OK

**Comment by JonathanStarup** [comment]
![image](https://github.com/flix/flix/assets/32037926/8ae2659c-fc3d-4838-bae8-6a1b0978fa12)

Oh it happened while the benchmarks didn't work. They are both inside the jump but your PR seems more likely

**Comment by magnus-madsen** [comment]
Definitely my PR.
