### ISSUE TITLE
Does `Chain.equals` have worse performance than necessary?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6917]
I worry it is O(N ** 2), but instead we could just convert to list and compare those.

**Comment by magnus-madsen** [comment]
Maybe this is actually not the case. I am not sure.

**Comment by magnus-madsen** [comment]
@stephentetley Does Chain have a linear equality function? Can calling viewLeft repeatedly lead to problems or is it fine?

**Comment by stephentetley** [comment]
The current version seems better to me than converting to lists as it has opportunities for early exit: If you convert to lists, you have to do fully recursive right views of both chains, and you only get the chance of early exit once you start scanning the lists. With the current implementation you get the chance of early exit at each recursive step of `Chain.equals`. 

Note that `Chain.viewLeft` does not straighten the right hand arm of `Chain` constructors it encounters, it just does the work it needs to find the left end. This  work is pushing the other left elements onto the right chain so it isn't cost free, but if the tree shape of the chain is favourable you are avoiding recursively processing every element of the chain.

**Comment by magnus-madsen** [comment]
Ok, I think I get it :)
