### ISSUE TITLE
Escape for flixdoc

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6918]
Issue with html escaping of some chars, see e.g.
https://api.flix.dev/Monad.html

**Comment by sockmaster27** [comment]
Looks like it's not getting fixed anytime soon: https://github.com/rjeschke/txtmark/issues/52 
As I see it the only option is to swap out the markdown library for a heavier one, but maybe that's fine anyway: https://github.com/JetBrains/markdown

**Comment by magnus-madsen** [comment]
Can we fix it ourselves? Either by an ugly unescaping hack? or maybe escaping ourselves first?

What do you we use the library for anyway?

**Comment by sockmaster27** [comment]
It's the library we're using for parsing the markdown in the doc comments. The panic mode that we're using simply escapes any `<` and `>`, but for whatever reason `<` becomes not just `&lt;` but `&amp;lt;`. 
I guess we can just do a search and replace for that, but it will of course create some weird effects if you ever wanted to write that literally.

**Comment by sockmaster27** [comment]
Or we could do the escaping before manually I supposed.

**Comment by sockmaster27** [comment]
> Or we could do the escaping before manually I suppose.

Unfortunately, this doesn't seem to be possible because the `&` character is always escaped by the markdown parser no matter what mode it is running in.
I guess at this point it would be sound to search and replace all `&amp;` with a `&` after the fact, but that's 3 passes for every doc comment.

**Comment by magnus-madsen** [comment]
What happens if we use the new intellij library? Does it solve it?

**Comment by sockmaster27** [comment]
> What happens if we use the new intellij library? Does it solve it?

No, unfortunately it just made it worse...
