### ISSUE TITLE
Install Java 21 on playground and build server

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6928]

**Comment by magnus-madsen** [comment]
@mlutze I can do it on playground, can you do it on the server? (arewefast)

**Comment by mlutze** [comment]
Yes

**Comment by magnus-madsen** [comment]
I ended up using a prebuilt deb.

**Comment by mlutze** [comment]
Fixed in arewefast.

I wanted to use sdkman but it's incompatible with fish shell, so I also used a prebuilt deb.
