### ISSUE TITLE
Make use of Java 21

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6934]
Flix now targets Java 21. We should take advantage of that:

- We already use `VirtualThread`s.
- We now have access to a much expanded Java Standard Library. Can we make advantage?
- Are there new bytecodes we should use?

**Comment by magnus-madsen** [comment]
@stephentetley Do you know if there are new methods in Java we would like to take advantage of? E.g. in String?
@JonathanStarup Do you know if there are any new bytecodes or similar we should be using?

**Comment by stephentetley** [comment]
There is the new Class File API coming with Java 22, rather than 21:

https://openjdk.org/jeps/457

It is more modern than ASM, but I imagine it would be work for Flix to move to it.

**Comment by magnus-madsen** [comment]
> There is the new Class File API coming with Java 22, rather than 21:
> 
> https://openjdk.org/jeps/457
> 
> It is more modern than ASM, but I imagine it would be work for Flix to move to it.

We will definitely explore that-- eventually.
