### ISSUE TITLE
Improvements to `Chain`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6989]
We go again:

- [x] `Chain` should not extend `Iterable` instead we should implement the required methods directly (e.g. `map`).
- [x] Drop `concat` and `iterator` methods.
- [x] Drop `Many` case class.
- [ ] `Empty`, `Link`, and `Proxy` should not be case classes. Just normal classes with vals. They should still be private.
- [ ] Why do we have both `apply` and `from` methods. Can we settle on one? I am OK with from.
- [x] Implement `foreach`.
- [ ] Rewrite `toList` to use a buffer and call `foreach`.

**Comment by magnus-madsen** [comment]
@jaschdoc Lets do this next-- together with the open PRs.

**Comment by magnus-madsen** [comment]
> IMO we should have both `apply` and `from`, but not two of each.

Why?

**Comment by magnus-madsen** [comment]
> They serve different purposes. `apply` is for a chain "literal", and `from` is for conversion from another Iterable.

Argument accepted.

**Comment by jaschdoc** [comment]
- [ ] override `toString`

**Comment by jaschdoc** [comment]
> `Empty`, `Link`, and `Proxy` should not be case classes. Just normal classes with vals. They should still be private

Why? We can't do pattern matching in the trait then :/ I guess that forces us to write things in object oriented style?
