### ISSUE TITLE
Testing Handlers

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7014]
This is a tracking issue for systematic testing of handlers.

- [x] #7015
- [x] #7016
- [x] #7017
- [x] #7018
- [x] #7019
- [x] #7059
- [x] #7060
- [x] #7063
- [x] #7098
- [x] #7099
- [x] #7146

Note: We are writing tests. It is possible some tests will break because of bugs-- that's what we hope to discover.

**Comment by JonathanStarup** [comment]
Conditions upon which effects are sensitive:
- Operation return type
- Operation argument types
- Try-with body type
- Tail position of `do` and `try with`

**Comment by magnus-madsen** [comment]
Iteration 1 complete. Question is what to do from here. I think we need multiple effects and interesting continuations.
