### ISSUE TITLE
Add `Test.Handler.Ask.flix`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7019]
Following this pattern:

```
eff Ask {
    pub def ask(x: Int32): Unit
}

def generator(x: Int32): Unit \ Ask =
    do Ask.ask(x); generator(x + 1)

def sample(limit: Int32): List[Int32] =
    try {
        generator(0); Nil
    } with Ask {
        def ask(x, k) = if (x == limit) Nil else x :: k()
    }

@Test
def testSample01(): Bool =
    Assert.eq(Nil, sample(0))
```

with several testSamples

**Comment by magnus-madsen** [comment]
@jaschdoc 

I have reopen this because what I would like in the next step is the above pattern repeated for each type (as outlined in the other ticket).

For example, I think what we have is `Test.Handler.Gen.Int32.flix`

**Comment by jaschdoc** [comment]
Roger

**Comment by magnus-madsen** [comment]
See https://github.com/flix/flix/issues/7059 for an update.

**Comment by jaschdoc** [comment]
So can we close this now that you have made issues for the remaining tasks?

**Comment by jaschdoc** [comment]
Do you also want tests for each primitive type and `AtomicInteger` for this?

**Comment by magnus-madsen** [comment]
> Do you also want tests for each primitive type and `AtomicInteger` for this?

Yes please. Thank you sir.
