### ISSUE TITLE
Nondeterministic compilation with threads = 1

### ISSUE THREAD

**Issue by mlutze** [flix/flix#7044]
Before the threads update, compilation was reasonably deterministic and sequential when I did `threads = 1`. This was useful for debugging, as printlns come in the same order and symbol IDs are consistent.

Since the threads update, even when I set `threads = 1`, the compilation appears multithreaded: I have interlaced output and inconsistent IDs.

Is there any easy way to remedy this?

**Comment by magnus-madsen** [comment]
I think the key may be to provide a sequential version of `ParOps.parMap`:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/util/ParOps.scala#L36

Could you try that?

**Comment by magnus-madsen** [comment]
There is already access to the `Flix` object, so it should be easy to grab the `Options` object, and determine if `threads = 1`. If so, we can do a linear pass.

**Comment by mlutze** [comment]
fixed by #7048
