### ISSUE TITLE
Optimization of Enum Representation

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#7071]
Goals regarding Enums and their tags.
- Since the backend generates tags of enums separately (no actual tie to defining enum) we should take advantage of that.
  - #7119
- Enums cannot be erased since the backend does some optimization for unit tags and have special toString implementation for tuple tags. This should be taken care of in a earlier phase. Ideas for the Enum (now tag) optimization phase
  - unit tags should not carry any information at all (`Option[Type]` instead of `Type`)
  - This idea could be extended to "low arity types" like Bool, Option[Bool], Result[Bool, Unit], etc. The optimization means that only k instances will exist for type arity k.
  - Enums with a single case should be translated away completely.
  - Multi-term tags cannot be represented directly because the source code might use the tuple gained form `untag`. So a flag will probably have to added to fix the toString issue

All in all this results in
1. fewer cases overall (less specialization from MonoTypes)
2. Fewer instructions (singleton enum optimization)
3. Enum value erasure (simpler backend code and smaller types post Eraser)
4. Fix the recursive enum bug in #6850

**Comment by magnus-madsen** [comment]
Is this a fair summary:

- [ ] Drop Enum interfaces.
- [ ] Change Tag to have an optional expression / type.
- [ ] Rework `toString` to be best effort. (This is for debugging anyway...)

What else?

**Comment by JonathanStarup** [comment]
Changing MonoTypes is a big one which includes changing the last. maybe Lowering could do it, thus LoweredAst will have cases: List[Case] instead of enums: List[Enum] or something like that

**Comment by magnus-madsen** [comment]
> Changing MonoTypes is a big one which includes changing the last. maybe Lowering could do it, thus LoweredAst will have cases: List[Case] instead of enums: List[Enum] or something like that

Changing the last what?

**Comment by JonathanStarup** [comment]
last -> ast. the loweredAst i think

**Comment by JonathanStarup** [comment]
outdated and fixed/ongoing
