### ISSUE TITLE
Return value of Bool function is wrong

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7086]
This program:

```
@Test 
def fail(): Bool = false
```

Succeeds. If we look in Tester near line 197, the problem is that the result seems to be `null`.

**Comment by JonathanStarup** [comment]
Seems that the tester class calls the function directly (which has been value wrapped) instead of `Ns.m_function` where the flix calling convention is taken care of

**Comment by JonathanStarup** [comment]
The function types are erased, so All `Ns.m_function` think they return objects, no matter what they actually return. that's my bad, fixing asap
