### ISSUE TITLE
The `IO` effect should behave like any other effect

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7091]
We currently model `IO` as the top element of the effect lattice. But instead, we should simply treat `IO` as any other effect, except it cannot be handled. This refactoring will fix some issues with the effect system and allow code to mix user-defined effects with `IO` effects.

Currently this program type checks:

```
eff Ask {
    pub def ask(): String
}

def main(): Unit \ IO = 
    do Ask.ask();
    println("Hello World!")

```

but it should not because it has unhandled effects.

In any case, this refactoring should probably not happen until the new type system is in place.

**Comment by magnus-madsen** [comment]
There are some dragons here with monomorphization because we cannot replace IO by Universe and expect unification to succeed. I think we have to monomorphize with the concrete effects.

**Comment by mlutze** [comment]
Should Java operations have IO or Impure effect? I guess IO because Impure just breaks everything?

**Comment by mlutze** [comment]
Does `Static` region become its own thing too?

**Comment by magnus-madsen** [comment]
I think keep everything IO. The goal is just to make it a separate effect, not top.
