### ISSUE TITLE
Unconfident wording in effect error

### ISSUE THREAD

**Issue by mlutze** [flix/flix#7116]
```
'r + IO' appears to be a superset of 'IO'.
Consider using 'checked_ecast'?
```

Surely we _know_ that it's a subset. We should just say "is a subset"

**Comment by JonathanStarup** [comment]
It seems that it is wrong sometimes, so maybe not 😄 (from #7118)
```
'Pure' appears to be a superset of 'e1 + e0'.
```

**Comment by mlutze** [comment]
Maybe instead all our type errors should be tentative. "We're not totally sure, but we think there might be a problem with this type"

**Comment by JonathanStarup** [comment]
Gone?
