### ISSUE TITLE
`foreach` on iterator

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#7122]
why can I not write foreach for an iterator?

```
>> Expected argument of type ''0[t1]', but got 'Iterator[(Int32, t), r1 + r2, r1]'.

5 |         foreach((index, asd) <- Array.enumerator(reg, b)) {
                                    ^^^^^^^^^^^^^^^^^^^^^^^^
                                    expected: ''0[t1]'

The function 'Iterable.iterator' expects its 2nd argument to be of type ''0[t1]'.

Expected: '0[t1]
  Actual: Iterator[(Int32, t), r1 + r2, r1]
```

Answer: Iterators are one-shot and thereafter empty, so they shouldn't be operated on directly

**Comment by magnus-madsen** [comment]
Lack of associated types, afaik

**Comment by magnus-madsen** [comment]
But also, foreach is for collections. And an iterator is not a collection.

**Comment by JonathanStarup** [comment]
Okay, then my follow up question is, I want to do something 10000 times, how do I write my loop? I don't want to materialize the numbers first so that lead me to `Iterator` but then I can't write my foreach loop

**Comment by magnus-madsen** [comment]
> Okay, then my follow up question is, I want to do something 10000 times, how do I write my loop? I don't want to materialize the numbers first so that lead me to `Iterator` but then I can't write my foreach loop. DelayList? although that is experimental

We need a Range data type which is immutable and Iterable.

**Comment by LionelMeli** [comment]
Hi Jonathan,

when you said:
> I don't want to materialize the numbers first

This means the kind of code below doesn't fit your expectation ? (based on issue -> Range module #7128)
[`   foreach(i <- Iterator.toList(Iterator.range(rc, 15, 43))) 
{ println(i) }`]

**Comment by JonathanStarup** [comment]
you are right. That code is about the same as `foreach(i <- List.range(15, 43))  { println(i) }` since you first build the list and then iterate through it.

**Comment by LionelMeli** [comment]
Ok, I understand. Hence the issue: Range module https://github.com/flix/flix/issues/7128

**Comment by JonathanStarup** [comment]
Yeah the solution is the range thing, I guess the range function is somewhat related but doesn't make or break this example. I will rephrase the main text for clarification around iterable
