### ISSUE TITLE
Add to Console

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#7151]
from scalas AnsiColor

```scala
  final val RESET      = "\u001b[0m"
  /** ANSI bold
    * @group style-control
    */
  final val BOLD       = "\u001b[1m"
  /** ANSI underlines
    * @group style-control
    */
  final val UNDERLINED = "\u001b[4m"
  /** ANSI blink
    * @group style-control
    */
  final val BLINK      = "\u001b[5m"
  /** ANSI reversed
    * @group style-control
    */
  final val REVERSED   = "\u001b[7m"
  /** ANSI invisible
    * @group style-control
    */
  final val INVISIBLE  = "\u001b[8m"
```

**Comment by LionelMeli** [comment]
Hi Jonathan,
I'm interrested by this issue.

**Comment by JonathanStarup** [comment]
Cool, I think you can add to `Console` in the style of this https://github.com/flix/flix/blob/master/main/src/library/Console.flix#L176-L176

You can read a bit more on the codes here for information to put in documentation https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_(Control_Sequence_Introducer)_sequences

**Comment by LionelMeli** [comment]
We could at least add as you listed: Reversed, Blink, Reset & Invisible (Bold is already implemented). I implement these one at 1st step.

**Comment by JonathanStarup** [comment]
Yeah, that would be consistent with https://www.scala-lang.org/api/current/scala/io/AnsiColor.html# too

**Comment by LionelMeli** [comment]
Blink doesn't work under Powershell (Windows 10) or WSL Ubuntu 22.04. However others Ansi codes work properly (except Italic under WSL Ubuntu)

**Comment by JonathanStarup** [comment]
I think thats good then :)
