### ISSUE TITLE
List of reserved keywords used in the standard library

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7163]
TBD

**Comment by magnus-madsen** [comment]
@herluf-ba If you can generate a list of defs and local variables whose name should change, I can ask one of the student programmers to fix it.

**Comment by herluf-ba** [comment]
@magnus-madsen 
```
word     file
static   Prelude.flix:4:16
static   Concurrent/Channel.flix:84:21
static   Concurrent/Channel.flix:126:20
static   Concurrent/Channel.flix:127:45
mod      BigInt.flix:45:13
not      BigInt.flix:145:9
new      Fixpoint/Compiler.flix:91:17
new      Fixpoint/Compiler.flix:98:17
query    Fixpoint/Interpreter.flix:75:55
query    Fixpoint/Interpreter.flix:119:15
query    Fixpoint/Ram/RelOp.flix:35:25
debug    Prelude.flix:131:5
for      Traversable.flix:58:13
mod      Int32.flix:66:13
mod      Int64.flix:66:13
open     File.flix:74:13
mod      Int8.flix:66:13
not      Bool.flix:55:13
and      Bool.flix:60:13
or       Bool.flix:65:13
mod      Int16.flix:66:13
solve    Fixpoint/Solver.flix:35:13
project  Fixpoint/Solver.flix:95:13
project  Fixpoint/Solver.flix:109:36
project  Fixpoint/Solver.flix:109:52
query    Fixpoint/Solver.flix:720:17
choose   Random.flix:28:13
query    Fixpoint/Simplifier.flix:116:42
query    Fixpoint/Simplifier.flix:120:58
query    Fixpoint/Simplifier.flix:123:60
++       SemiGroup.flix:40:9
query    Fixpoint/IndexSelection.flix:116:21
query    Fixpoint/IndexSelection.flix:122:59
query    Fixpoint/IndexSelection.flix:125:59
```

**Comment by magnus-madsen** [comment]
@jaschdoc I would like you to get on this quick. It should not take too long.

We are trying to ensure that keywords are not used as names for functions (or local variables).

In the future, the Parser will support writing e.g. `List.forAll(and, ...)`. So its OK to remove `Bool.and` for now.

Only, my suggestions should not require huge changes. If they do, let me know.

With that said, here is my proposal for iteration 1:

- [ ] `Map.query` becomes `Map.rangeQuery`.
- [ ] `Map.queryWith` becomes `Map.rangeQueryWith`.
- [ ] Local variables in the solver named `query` become `squery` (see table above for their occurrences).
- [ ] `Solver.solve` becomes `Solver.run` (note may require changes to `Lowering`).
- [ ] `Solver.solveWithStratification` becomes `Solver.runWithStratification`.
- [ ] `Random.choose` becomes `Random.oneOf`.
- [ ] Drop `IntX.mod` and `IntX.rem`. I assume they do not have dependencies, let me know if they do.
- [ ] Drop `Bool.{not, and, or}`. I assume they do not have dependencies, let me know if they do.
- [ ] Rename `Compiler` use of local variable `new`  to `newr`.

**Comment by magnus-madsen** [comment]
@herluf-ba I posted a list for @jaschdoc to work one. Once he is done, we can iterate. I suspect we will need to get your PR rebased (etc) because some of the list seems outdated, but I also suspect its incomplete.

**Comment by magnus-madsen** [comment]
- `open` will no longer be a keyword. We will rename it to `open_variant`.
- I believe `project` is now called `inject`.

**Comment by jaschdoc** [comment]
> * Drop `IntX.mod` and `IntX.rem`. I assume they do not have dependencies, let me know if they do.

They have dependencies in the std lib.

**Comment by magnus-madsen** [comment]
@herluf-ba I am starting to think that `mod` and `rem` should not be keywords.

**Comment by jaschdoc** [comment]
We had that at one point, but we opted for the library implementation

**Comment by herluf-ba** [comment]
@magnus-madsen `rem` sure, but `mod` is used to declare modules!
```scala
mod Bool {
   //...
}
```

**Comment by magnus-madsen** [comment]
Oh thats right!

**Comment by JonathanStarup** [comment]
Why are we dropping Int.rem and Int.mod? Bool.and/or too. Those functions seem really useful

**Comment by magnus-madsen** [comment]
> Why are we dropping Int.rem and Int.mod? Bool.and/or too. Those functions seem really useful

We will keep them, but we need new names because `mod` is a keyword. So at least a new name for it.

**Comment by magnus-madsen** [comment]
@jaschdoc Will you rename `Random.choose` also? Then we are done, I believe :)
