### ISSUE TITLE
Add method to parse Int8 to Char

### ISSUE THREAD

**Issue by LordBurtz** [flix/flix#7166]
Hi there, 
after trying out the Flix programming language for a few things I noticed that a Int8 to Char method is missing, which I find inconvenient and would like to add   some method as
```flix
def int8tochar(i: Int8): Char
``` 
to the standard lib

I have to implementation design in mind, either using pure flix like
```flix
def int8tochar(i: Int8): Char = match i {
    case 0i8  => '\u0000' // Null character
    ...
```
Or something along the lines of using an unsafe cast from int8 to java int to java char to flix char (im looking into this atm)

Any ideas and input appreciated!  
Please keep in mind that this is my first time opening a issue here so please excuse if its lacking quality (open to editing stuff)

**Comment by LordBurtz** [comment]
Thanks for the input, I would prefer to keep it in Int8 after giving the name some thought would name it `asByteToChar` because thats what really happens..  
Having it in Int32 makes no sense (to me) as we can't treat the Int32 range and int <-> char conversion is based on having 8 bits.. 

About the implementation details:  
After tinkering a bit I can't see a way forward with function calls into Java as long as `var c = (char) i` isnt supported as a import method (correct me if I am wrong here but I couldn't find something in The Book or in the api reference..  
Using `java.lang.Class.cast` isn't an option as using this piece of pure java code   
```java
public class Main {
    public static void main(String[] args) {
        var i = new Integer(65);
        var c = new Character('c');
        System.out.println(c.getClass().cast(i));
    }
}
```
errs with 
```
Exception in thread "main" java.lang.ClassCastException: Cannot cast java.lang.Integer to java.lang.Character
        at java.base/java.lang.Class.cast(Class.java:3606)
        at Main.main(Main.java:5)
```
Ill open an issue on SO to ask for a solution for casting Integer to Character without using primitives and (cast) but until then I see no other way then implementing it natively (which btw if its not too off-topic, isnt an option because of?)

**Comment by mlutze** [comment]
I've opened an issue for casting primitives: #7170

**Comment by magnus-madsen** [comment]
The cast seems unsafe:

A narrowing conversion of a char to an integral type T likewise simply discards all but the n lowest order bits, where n is the number of bits used to represent type T. In addition to a possible loss of information about the magnitude of the numeric value, this may cause the resulting value to be a negative number, even though chars represent 16-bit unsigned integer values. 

So I think the return type should be `Option[Char]`. I am not sure, but maybe:

https://docs.oracle.com/javase/8/docs/api/java/lang/Character.html#toChars-int-

can be used. With an additional check first?

**Comment by LordBurtz** [comment]
For future reference.. I had a look around and [CodePoint.toChars](https://api.flix.dev/CodePoint.html#def-toChars) can be used which uses [java.lang.Character.toChars](https://docs.oracle.com/javase/8/docs/api/java/lang/Character.html#toChars-int-) under the hood, but..  
Wouldn't it be nice to have some proper text parsing capabilities?  
I am interested in this project and looking for some issues to contribute a bit and learn some more, so I am thinking of creating a proper text parsing library (maybe like `Data.Text`)

**Comment by magnus-madsen** [comment]
I would suggest to create a package. If it is high quality and commonly usable, we can think about including it in the std lib 👍
