### ISSUE TITLE
Drop `Def.purity` from `LiftedAst` and `ReducedAst`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7168]

**Comment by magnus-madsen** [comment]
@JonathanStarup Can I give this to a student programmer? The idea is just to use the defs exp.purity right?

**Comment by JonathanStarup** [comment]
i think, because of typematch and monomorph, these two purities dont match exactly. it should be okay/better to use exp.purity but its not just redundant

**Comment by magnus-madsen** [comment]
@sockmaster27 The idea is simply that Def should not have a purity field in these two ASTs. Instead, if the purity is needed, it can be found by accessing the def.exp.purity.
