### ISSUE TITLE
make Optimizer handle unused parameters

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#7172]
In the AST there is a lot of unused parameters (looking specifically at `_lift$xyz` variables. After a run of the optimizer, there variables are inlined somehow, resulting in a lot of binders like `let _lift$150000: Unit = ();`. They are not easily removed as they keep appearing while closures are inlined so we should avoid them being produced at all.

I think this can be fixed in `Inliner.bindFormals` line 342.

There needs to be a check for purity too since arguments to unused parameters might be impure

**Comment by magnus-madsen** [comment]
I think its hard: You have to ensure both evaluation order and that work is not duplicated.

The current approach is good, because it is obviously correct. Moreover, the inliner deals with it appropriately.

What you really want is more iterations, but that is tradeoff in time-space.

**Comment by JonathanStarup** [comment]
I don't think what i want is more iterations. My issue with this is that the optimizer generates useless letbinders which means that no amount of iterations will remove them completely

**Comment by magnus-madsen** [comment]
But also double work...

**Comment by JonathanStarup** [comment]
I've made a PR, I think the additional lines are merited by its efficiency
