### ISSUE TITLE
Compile error in code from documentation

### ISSUE THREAD

**Issue by stetimi** [flix/flix#7202]
I tried out the programmable effects / divide example from the documentation, it gave this error in VS:
```
Unable to unify the types 'Void' and 'Int32'.(Type Error)
```
```
eff Throw {
    pub def throw(): Void
}

def divide(x: Int32, y: Int32): Int32 \ Throw = 
    if (y == 0) {
        do Throw.throw()
    } else {
        x / y
    }
```

**Comment by magnus-madsen** [comment]
What Flix version? Note this feature is still under development.

**Comment by stetimi** [comment]
I see the issue in 0.43, but 0.44 looks fine.
I saw it was under development, but I'm just trying Flix out for fun.
