### ISSUE TITLE
Up and down arrows show control characters in the repl

### ISSUE THREAD

**Issue by stetimi** [flix/flix#7203]
This is on both Flix versions I've tried, 0.43 and 0.44.
Up arrow shows ^[[A for instance, rather than giving me the last line.
I'm running on a Mac, if that makes any difference.

**Comment by magnus-madsen** [comment]
I see the same. Does it only happen inside vscode or also in a proper terminal?

**Comment by magnus-madsen** [comment]
You could try to bump the JLine version:

https://github.com/flix/flix/blob/master/build.gradle#L19

and see if it helps.

**Comment by stetimi** [comment]
Both vs code & in terminal. It's quite a pain as I have to keep cutting and pasting code I'm trying out.
I'll get a build from source and try out the version bump.

**Comment by magnus-madsen** [comment]
I wonder what it could be because we rely on JLine for this stuff and one what assume that it works.

**Comment by stetimi** [comment]
I found this: https://groups.google.com/g/jline-users/c/kT6CbU_NUtw?pli=1

**Comment by stetimi** [comment]
I did a bit of digging. It looks like the Flix repl is using a custom class loader which isn't loading some files contained in the jline .jar file.
If I comment out the line below which sets the custom class loader into the thread, up/down arrows work in the REPL.

https://github.com/flix/flix/blob/fa648ab2db0facaddc138a934ab13c5275cc0a01/main/src/ca/uwaterloo/flix/util/ExternalJarLoader.scala#L28

**Comment by magnus-madsen** [comment]
> I did a bit of digging. It looks like the Flix repl is using a custom class loader "ExternalJarLoader" which isn't loading some files contained in the jline .jar file. If I comment out the line below which sets the custom class loader into the thread, up/down arrows work in the REPL.
> 
> https://github.com/flix/flix/blob/fa648ab2db0facaddc138a934ab13c5275cc0a01/main/src/ca/uwaterloo/flix/util/ExternalJarLoader.scala#L28

Ok. But I believe there is a good reason we use such a class loader. I think it is because we must keep user code separate from Flix compiler code.

But I wonder why JLine would be loaded using it. Perhaps its an ordering issue?

**Comment by magnus-madsen** [comment]
But setting something on the current thread is very puzzling to me.

**Comment by magnus-madsen** [comment]
Git blames gives: https://github.com/flix/flix/pull/4788

**Comment by magnus-madsen** [comment]
I think we should that specific line. Even if the intention was correct, I don't think it works correctly anymore.

**Comment by magnus-madsen** [comment]
I can also confirm that removing that line solves the problem.

**Comment by magnus-madsen** [comment]
Do you want to make a PR?

**Comment by stetimi** [comment]
Note: JLine gets the current current thread's context classloader to load terminal providers:
https://github.com/jline/jline3/blob/19c031c0bccaeea6a4346bc82c04c7bd3ec18888/terminal/src/main/java/org/jline/terminal/spi/TerminalProvider.java#L55

Sure, I can make a PR, though tomorrow as it's late here in Hong Kong.
