### ISSUE TITLE
Internal  `DIV`, `MOD` and `REM` should check for zero?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7221]

**Comment by magnus-madsen** [comment]
@JonathanStarup We used to have these operations check for 0. Did we lose that at some point? Or is it because the check is in Flix code? (Which we are about to remove.)

**Comment by JonathanStarup** [comment]
I don't remember changing or implementing any of that. Shouldn't native operations be native, no matter the zero crash case?

**Comment by magnus-madsen** [comment]
Not sure, but soon we will be removing e.g. `Int32.mod` and then what?

I think at "native operation" is native w.r.t. Flix semantics.

**Comment by JonathanStarup** [comment]
Currently operations check for zero on the library side. This seems better for maintenance and modification to me.

Can I close this issue @magnus-madsen?

**Comment by magnus-madsen** [comment]
OK
