### ISSUE TITLE
Add `build-fatjar` option

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7224]
The purpose of this ticket is to add support for building fatjars: https://stackoverflow.com/questions/11947037/what-is-an-uber-jar-file

A fatjar is simply a JAR file that contains all the required bytecode to run a program, i.e. the direct classes produce by the Flix compiler plus all classes in all dependent JARs.

We can break the task down as follows:

- [ ] Add a new command `build-fatjar` (see `Main.flix`)
- [ ] Extend `Bootstrap` with a new function `buildFatJar`. 
- [ ] Like `buildJar`, `buildFatJar` should include all classes generated by the Flix compiler, but it most also collect all classes in all JAR files in the `lib` folder). In other words, it should find all those JAR files, unpack them, and then repack their content into the fat jar. Think of it as creating a zip file with the content coming from one folder and many other zip files.
- [ ] Test it. For example, by creating a Flix package that depends on some Maven library (see https://doc.flix.dev/packages.html#adding-maven-dependencies)

**Comment by ZentsuGo** [comment]
Hello, I will try to work on it.

**Comment by magnus-madsen** [comment]
Fixed in master. Thanks @ZentsuGo
