### ISSUE TITLE
Keywords: `new`, `get`, `from`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7281]
@herluf-ba has identified that we use `new`, `get`, `set`, `from` both in Flix code and as keywords.

With the new parser this will no longer be possible. What shall we do in each case?

# `new` 
We use it as keyword in imports:
```
import new java.io.File(String): ##java.io.File \ IO as newFile;
```
but we also use it to construct new collections, e.g. `MutList.new`.

# `get` and `set`
We use them as keywords in imports:

```
import get flix.test.TestClass.boolField: Bool \ IO as getField;
import set flix.test.TestClass.boolField: Unit \ IO as setField;
```

But we also use it for e.g. `Map.get` (very common).

# `from`
We use it as a keyword in queries:

```
query movies, actors, directors, rule select title from MovieWithoutDirector(title) |> println
```

But we also use it e.g. here:

```
pub def replace(from_: {from_ = a}, to: {to = a}, s: Set[a]): Set[a] with Order[a] =
    if (memberOf(from_.from_, s)) insert(to.to, remove(from_.from_, s)) else s
```

# What to do

No matter what we do, we will have breakages. My proposal:

- `new` -- I think it is sensible that `new` would be a keyword. We may want to rework the import syntax down the road, but probably we will want a `new` construct of sorts. However, it does mean that our smart constructors like `MutList.new` will have to be renamed. Perhaps `MutList.create`? or `MutList.empty`?
- `get` and `set` -- I would hate to lose `Map.get`. I would rather we rename the import mechanism. Perhaps it could be `import getter ...` or whatever. We are likely to iterate on the import mechanism -- because it is not great -- so I think breakage here is okay. Its not like import statements are considered elegant or pretty by anyone.
- `from` -- not sure what to do. Its pretty rarely used as a field/variable. We could always do `src/dst`. But on the other hand, `query .. from` is also rarely used... But that syntax is already in several published papers.

**Comment by magnus-madsen** [comment]
@stephentetley @mlutze @JonathanStarup @jaschdoc I would like to hear your thoughts.

**Comment by JonathanStarup** [comment]
* An overall point: All these are used in combination with another keyword, do they actually have to be reserved words? when `query` and `import` are reserved do these combinations also have to be? 
* `new` another option, is that the import should be `import constructor java.lang.Object(): ##java.langObject \ IO as newObject`
* `get` `set` - I think that `getField` or `getter` is good.

**Comment by magnus-madsen** [comment]
> An overall point: All these are used in combination with another keyword, do they actually have to be reserved words?

Yes, because we do lexing before parsing, so we no longer have any context.

**Comment by stephentetley** [comment]
Could we follow `checked_cast` etc. and have two word, snake case keywords? 

> import java_constructor java.io.File(String): ##java.io.File \ IO as newFile;

> import java_field_getter flix.test.TestClass.boolField: Bool \ IO as getField;
> import java_field_setter flix.test.TestClass.boolField: Unit \ IO as setField;

It's not the prettiest of syntax but jvm imports are always encapsulated in functions so the cumbersomeness is largely hidden.

**Comment by jaschdoc** [comment]
- I like `getter`, `setter`, `constructor`. It's both more visible and we get to keep the std lib names for `get`, `set`.
- I think we should keep `query ... from`. I did a quick search through the library and we only use `from` as a parameter for `replace` where I think we could either just use `src/dst` or `update`, `newItem`, `oldItem`, `replacement`, `old` etc. Just to demonstrate that we should be able to come up with a new pair of words to describe the same relationship between the parameters. We also have `DelayList.from(n: Int32): DelayList[Int32]` but that should fairly easy to rename, e.g., `unroll`, `generateFrom`, `startFrom`.

**Comment by mlutze** [comment]
A note about `new`: if we ever support Java interop in the other direction, then we probably need to disallow `new` as a definition name anyway.

I lean slightly toward Stephen's proposal. It means we don't pollute the namespace. And it follows the general philosophy that unsafe code should be an eyesore, and calling into Java is inherently unsafe. It can be wrapped in a beautiful, safe interface.

In contrast, querying is safe, and should thus be pretty. I'm OK with losing `from` as an identifier for the sake of it.

**Comment by magnus-madsen** [comment]
I see some convergence. I will be adding tickets:

- https://github.com/flix/flix/issues/7295

**Comment by herluf-ba** [comment]
Should `project` be a keyword? It is used with `solve ... project ...`

**Comment by magnus-madsen** [comment]
I think `project` should be a keyword.

**Comment by magnus-madsen** [comment]
- https://github.com/flix/flix/issues/7308
- https://github.com/flix/flix/issues/7303
- https://github.com/flix/flix/issues/7302

**Comment by magnus-madsen** [comment]
Inspired by @stephentetley, I would propose:

```
import java_new java.io.File(String): ##java.io.File \ IO as newFile;
import java_get_field flix.test.TestClass.boolField: Bool \ IO as getField;
import java_set_field flix.test.TestClass.boolField: Unit \ IO as setField;
```

These names are not great, but: (a) they are unambiguous and will not cause any problems, and (b) we now have some new ideas for how to improve interop, either to supplement or perhaps entirely replace.

**Comment by magnus-madsen** [comment]
What remains: What shall we do about functions named `new`? We have a lot of `MutList.new` etc. I would suggest to rename them to `empty`.

**Comment by herluf-ba** [comment]
That would work 👍  And I like `empty`

**Comment by mlutze** [comment]
I am fine with `empty` and the `java_*` stuff.

**Comment by JonathanStarup** [comment]
i think empty implies a single reusued object and feels slightly weird for mutable objects

**Comment by magnus-madsen** [comment]
> i think empty implies a single reusued object and feels slightly weird for mutable objects

I agree. But do you have a better suggestion? (Scala also calls its empty).

**Comment by magnus-madsen** [comment]
- https://github.com/flix/flix/issues/7331
- https://github.com/flix/flix/issues/7329

**Comment by magnus-madsen** [comment]
We are going to try to get this done quickly, so when breakages have to be fixed they can be done in one go.

**Comment by JonathanStarup** [comment]
New is already not a keyword according to https://github.com/flix/flix/issues/7331 right? or is new also used in other places?

**Comment by herluf-ba** [comment]
`new` is also used in a `Expression.NewObject`. Here's an example from `Test.Exp.Jvm.NewObject.flix`
```
    let anon = new TestVoidInterface {
      def testMethod(_this: TestVoidInterface): Unit = ()
    };
```

**Comment by JonathanStarup** [comment]
Then we can use `java_new` both places perhaps. but otherwise i guess empty is the best option

**Comment by magnus-madsen** [comment]
I think we can keep `new` for java objects. We can always use the current scope to disambiguate.
