### ISSUE TITLE
Decide what to do about `++`, `&&`, `--` to make them context-free tokens

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7303]
The problem is that we cannot make the token of e.g. `++` context dependent.

**Comment by magnus-madsen** [comment]
@JonathanStarup @mlutze What do you want to do about these? (they come from restrictable variants).

What's the plan for restrictable variants going forward? Should we drop the feature or maintain it or leave it in its current state of limbo? (I believe it only works up until type checking).

**Comment by mlutze** [comment]
I vote for removal.

**Comment by magnus-madsen** [comment]
Lets wait a bit with removal. I suggest we rename to:

- `~~` becomes `rvnot`
- `++` becomes `rvadd`
- `&&` becomes `rvand`
- `--` becomes `rvsub`

**Comment by magnus-madsen** [comment]
@jaschdoc Do you think you can do it? I am talking about these lines:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Parser.scala#L1428-L1444

And updates to examples, e.g.

https://github.com/flix/flix/blob/master/examples/larger-examples/restrictable-variants/boolean-formulas.flix

**Comment by magnus-madsen** [comment]
@herluf-ba and now these are fixed too :)

(Well, you have to add `rvadd` and friends).
