### ISSUE TITLE
Rename uses of `project`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7308]
It is becoming a keyword, so cannot be used as the name of function or variable etc.

**Comment by jaschdoc** [comment]
I looked over everything. It's *only* used as a keyword luckily, so we can just close this.

**Comment by magnus-madsen** [comment]
@herluf-ba You can make it into a keyword 👍 (or report where it is used, if ever).

**Comment by herluf-ba** [comment]
`project` is used as a definition name in `Solver.flix` from the standard library.
```
    ///
    /// Project all facts in the given Datalog program `d` that has `p` in its head.
    ///
    @Internal
    pub def projectAll(p: PredSym, d: Datalog[v]): Datalog[v] with Order[v] = match d {
        case Datalog(facts, _) =>
            let pFacts = Vector.filter(match Constraint(HeadAtom(head, _, _), _) -> head == p, facts);
            Datalog(pFacts, Vector.empty())
        case Model(db) =>
            Map.rangeQuery(ramSym -> match ramSym {
                case RamSym.Full(predSym, _, _) => match predSym <=> p {
                    case Comparison.EqualTo => Comparison.EqualTo
                    case cmp => cmp
                }
                case _ => Comparison.LessThan
            }, db) |>
            List.toMap |>
            Model
        case Join(d1, d2) => union(projectAll(p, d1), projectAll(p, d2))
    }
```

It is a little tricky to rename since that function is `@Internal` and is actually referenced directly in the Lowering phase. 
On my branch, I renamed it `projectAll` to continue work. @magnus-madsen What do you think about this?

**Comment by magnus-madsen** [comment]
@jaschdoc Can you rename the function and change lowering? You can just call it projectAll or whatever.

**Comment by magnus-madsen** [comment]
@herluf-ba `project` should now be done.
