### ISSUE TITLE
Ensure that every collection has an `empty` function

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7330]
For example, `List` seems to lack such a function.

**Comment by jaschdoc** [comment]
Does it make sense to have an `empty` function for non-empty collections like `Nec`? Maybe a `from` function suffices?

**Comment by magnus-madsen** [comment]
> Does it make sense to have an `empty` function for non-empty collections like `Nec`? Maybe a `from` function suffices? We already have `singleton`

No. There it does not make sense.
