### ISSUE TITLE
Improved Interoperability: Take Three

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7332]
- [x] https://github.com/flix/flix/issues/7760
- [x] https://github.com/flix/flix/issues/7761
- [x] Add test cases for the new infrastructure
- [x] Add support for reading/writing static fields.
- [x] Allow import to add types to the use env
- [x] Fiddle with syntax
- [x] Add `unsafe` block which "handles" `IO`
- [x] Update documentation (book, etc.)
- [x] Refactor Flix Standard Library
- [x] Add `FromJava` and `ToJava`
- [ ] Add support for Java generics
- [ ] (Much later) remove old import stuff

**Comment by JonathanStarup** [comment]
close as outdated? @magnus-madsen

**Comment by magnus-madsen** [comment]
I suppose we can close it. Still a couple of things remaining.
