### ISSUE TITLE
`desugarJvmX` should not insert an unchecked_cast if the effect is already IO

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7333]

**Comment by magnus-madsen** [comment]
@JonathanStarup Could you investigate?

**Comment by JonathanStarup** [comment]
I have thoughts:
1. We could "trust the user" and just hardcode the Jvm instruction to have the annotated type, but this would go against checking that code bases do not have "just trust me" code
2. We could omit the cast in Desugar if the annotated effect is literally `IO` (we are before type checking so an alias will result in a cast)
3. we could post-typechecking remove unchecked casts that we know to be safe/redundant

I vote for 2 or 3. What are your thoughts @magnus-madsen?

**Comment by magnus-madsen** [comment]
In this ticket I don't want to deal with the trust issue. We are doing that separately.

What I need is that if you annotate IO then you should not get an unchecked effect cast because the default is IO. 

(At least I would hope that the default effect of e.g. InvokeMethod is IO)

**Comment by JonathanStarup** [comment]
So option 2 or 3? 2 is the simplest but also has sharp edges

**Comment by magnus-madsen** [comment]
> Do you want option 1 then? never have AST casts for imports?

If the user writes `\ {}` then obviously a cast is needed, right?

**Comment by magnus-madsen** [comment]
The point is that we will check for the presence of unchecked_casts, but once should be penalized for having an unsafe cast if we have actually written the IO effect.

**Comment by JonathanStarup** [comment]
> If the user writes \ {} then obviously a cast is needed, right?

In a sense, but the AST node could just say that it has effect `{}` instead of being `IO` and then casted to `{}`

**Comment by JonathanStarup** [comment]
> The point is that we will check for the presence of unchecked_casts, but once should be penalized for having an unsafe cast if we have actually written the IO effect.

And what about the inverse - should you be penalized if you write something that's not `IO`?

**Comment by magnus-madsen** [comment]
> > The point is that we will check for the presence of unchecked_casts, but once should be penalized for having an unsafe cast if we have actually written the IO effect.
> 
> And what about the inverse - should you be penalized if you write something that's not `IO`?

Yes

**Comment by JonathanStarup** [comment]
and do you want 

> The point is that we will check for the presence of unchecked_casts, but once should be penalized for having an unsafe cast if we have actually written the IO effect.

Okay, and do you want `IO + IO` to also avoid the cast? or just for literal, unaliased `IO`?

**Comment by magnus-madsen** [comment]
Just for `IO`. If you do anything stupid then you have to fix your code :)
