### ISSUE TITLE
Improvements to `FastBoolUnification` post merge

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7363]
- [x] Each function should compute with its own substitution.
- [x] Always consider at least N permutations.
- [x] Rework `TooComplexException` to carry a specific error message.
- [x] Remove tests etc inside the class.
- [ ] Refactor `Or` to have the same representation as `And`.
- [x] ~Refactor `extended` not to throw exception?~

**Comment by JonathanStarup** [comment]
Superceded by #7699
