### ISSUE TITLE
Towards Sub-Effecting

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7377]
- [ ] Make the representation of `Or` in `FastBoolUnification` equal to that of `And`.
- [ ] Copy `FastBoolUnification` to `FastSetUnification`.
  - [ ] Rename `Not`, `And`, `Or` to `Complement`, `Intersection`, and `Union`.
  - [ ] Add elements (`elms`) as a base case instead of True/False, and add elements to `Union` and `Intersection`.
- [ ] Modify constraint generation to account for sub-typing for a handful of expressions, most notably Apply and ITE.

**Comment by JonathanStarup** [comment]
Can I close this as outdated? @magnus-madsen

**Comment by magnus-madsen** [comment]
The items might be outdated, but we have not merged sub-effecting yet, so let us keep it.
