### ISSUE TITLE
Should we remove the test `UndefinedName.03`?

### ISSUE THREAD

**Issue by herluf-ba** [flix/flix#7397]
in `TestResolver.scala` we find the test:

```scala
  test("UndefinedName.03") {
    val input =
      s"""
         |def foo(): #{ R } = #{}
       """.stripMargin
    val result = compile(input, Options.TestWithLibNix)
    expectError[ResolutionError.UndefinedName](result)
  }
```

This test uses a deprecated syntax for fixpoint contraint sets. Should we remove it?

**Comment by magnus-madsen** [comment]
@mlutze There is no way to define `R` right? Or can we write a type alias with the right kind? I don't think so, but I am not sure. In any case, I would probably just remove this.

**Comment by mlutze** [comment]
> @mlutze There is no way to define `R` right? Or can we write a type alias with the right kind? I don't think so, but I am not sure. In any case, I would probably just remove this.

We don't have a syntax for standalone predicates, so it's not possible.

**Comment by magnus-madsen** [comment]
@herluf-ba Remove the test. We don't want to support such free standing predicate aliases.

**Comment by JonathanStarup** [comment]
Could `R` not be a schema?

**Comment by magnus-madsen** [comment]
> Could `R` not be a schema? i forgot the syntax but with records it would be `type alias R = (x = Int32)`

It cannot no. It could be a unary predicate R(), but thats it.
