### ISSUE TITLE
Should we remove the test `UnexpectedArgument.04`?

### ISSUE THREAD

**Issue by herluf-ba** [flix/flix#7398]
In `TestTyper.scala` we find the test
```scala
test("Test.UnexpectedArgument.04") {
    val input =
      """
        |def f(x: Bool, y: Bool): Bool = ???
        |
        |law l: forall (x: Int32, y: Bool) . f(x, y)
        |""".stripMargin
    val result = compile(input, Options.TestWithLibNix)
    expectError[TypeError](result)
  }
```

This uses a `law` that is not within a `trait` type class, which is becoming a parse error with the new parser.
Note that the test is testing something to do with the arguments, not that a `law` cannot occur here.
Is it safe to remove this test?

**Comment by magnus-madsen** [comment]
@mlutze I think we should just drop laws outside traits. (We could also drop them all together). Then I would bring them back when we have actual support. But I guess a reasonable compromise is to just keep laws in traits for now. Thoughts?

**Comment by mlutze** [comment]
I like laws outside of traits, but I agree that we need support to make them useful.

I agree just to keep them on traits for now.

**Comment by magnus-madsen** [comment]
@herluf-ba Refactor the test to put the law into a trait.

We don't want to support free-standing laws.
