### ISSUE TITLE
Add `TryCatch` exception type check to `Safety`

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#7414]
Currently you can write

```
try 42 catch {
    case ex: #java.lang.String => ex
}
```

Safety should check that the exception type (`java.lang.String` here) is a subtype of `java.lang.Throwable`

**Comment by stetimi** [comment]
Doesn't look too tricky.. I could take a look

**Comment by stetimi** [comment]
Should this be closed now?

**Comment by magnus-madsen** [comment]
Yes
