### ISSUE TITLE
Flixdoc: show instances

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7435]
When viewing a trait: https://api.flix.dev/Eq.html

We should have a list of instances that are implemented by that trait at the bottom.

For example, Eq has many instances, e.g. for most collections.

**Comment by magnus-madsen** [comment]
Ideas for improvements?

Perhaps we will want show how associated types/effects are defined by each instance.

https://doc.flix.dev/associated-types.html

**Comment by magnus-madsen** [comment]
Reopened because I was hoping we could come up with some improvements.

**Comment by magnus-madsen** [comment]
When we open a type, e.g. https://api.flix.dev/List.html it would be cool if we could see what traits its implements.

**Comment by sockmaster27** [comment]
Is this done or are we missing something?

**Comment by magnus-madsen** [comment]
I think we are done.
