### ISSUE TITLE
Complexity Annotations

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#746]
In addition to #448, which proposes a limited form of termination analysis, it would be interesting to have a collection of annotations for the performance ("complexity") of functions. 

A first step could be to annotate the standard library functions with their complexity.

Later we could explore WCET program analyses or other techniques to verify the annotations.

For example,

```scala
@Time(1) @Space(1)
pub def isEmpty[a](xs: List[a]): Bool = match xs with {
    case Nil => true
    case _ => false
}
```

or

```scala
@Time(length(xs)) @Space(n)
pub def last[a](xs: List[a]): Option[a] = match xs with {
    case Nil => None
    case x :: Nil => Some(x)
    case x :: rs => last(rs)
}
```

or

```scala
@Time(time(f) * length(xs)) @Space(n)
pub def map[a,b](f: a -> b, xs: List[a]): List[b] = match xs with {
    case Nil => Nil
    case x :: rs => f(x) :: map(f, rs)
}
```

**Comment by mlutze** [comment]
Is `length` in this case a "magic function"? How would you envision denoting something more complex such as the number of unique values in a list?

**Comment by magnus-madsen** [comment]
This is quite an open-ended project.

For your specific question, I am not sure. Could it be the length function itself, if that had a complexity annotation, or does that not work?

**Comment by mlutze** [comment]
I don't think that would work, since when we refer to length in the complexity annotation, we want its result, not its own complexity, right?

**Comment by magnus-madsen** [comment]
Yes, you are right. I must have been confused.

**Comment by magnus-madsen** [comment]
Research question: How would you "empirically test" such annotations?

**Comment by magnus-madsen** [comment]
More research questions:

- Do we want to enforce certain complexity requirements? E.g. that hashCode is constant or linear time?
- How do we deal with polymorphism? E.g. insert in a tree or hash table depend on the compare/hash complexity.

**Comment by esbenbjerre** [comment]
```
@Time(time(f) * length(xs)) @Space(space(f))
pub def findRight(f: a -> Bool, xs: List[a]): Option[a] = match xs {
    case Nil => None
    case x :: rs => Option.withDefault(findRight(f, rs), if (f(x)) Some(x) else None)
}
```
`findRight` is not tail recursive. Shouldn't it then be `@Space(space(f) * length(xs))`?

**Comment by magnus-madsen** [comment]
> ```
> @Time(time(f) * length(xs)) @Space(space(f))
> pub def findRight(f: a -> Bool, xs: List[a]): Option[a] = match xs {
>     case Nil => None
>     case x :: rs => Option.withDefault(findRight(f, rs), if (f(x)) Some(x) else None)
> }
> ```
> 
> `findRight` is not tail recursive. Shouldn't it then be `@Space(space(f) * length(xs))`?

OK; that is a fair point. I was not thinking at this level of precision, but you are right.

**Comment by esbenbjerre** [comment]
Would you prefer me to refactor it to this level of precision or keep it "simpler"?

**Comment by magnus-madsen** [comment]
> 
> 
> Would you prefer me to refactor it to this level of precision or keep it "simpler"?

I think you should refactor it to the extend possible.
