### ISSUE TITLE
A method import with an IO effect should not introduce an unchecked cast

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7465]

**Comment by magnus-madsen** [comment]
I think the point is that for some signatures there is no cast:

```
import static java.lang.System.exit(Int32): Unit \ IO;
```

return type and effect match, so no need for a cast.

**Comment by magnus-madsen** [comment]
@JonathanStarup How can we fix this?

**Comment by magnus-madsen** [comment]
Maybe we can remove such casts in type reconstruction?

**Comment by JonathanStarup** [comment]
I think that's a good approach
1) the hack that I introduced can be removed
2) unchecked cast of null is also rewritten away, so we already do it a little bit

**Comment by magnus-madsen** [comment]
> I think that's a good approach
> 
>     1. the hack that I introduced can be removed
> 
>     2. unchecked cast of null is also rewritten away, so we already do it a little bit

Can you make an attempt? I have a student that would like to build on this.
