### ISSUE TITLE
Parser: Add more tests to `FuzzerSuite`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7491]
We currently have two fuzzers:

- We can compile all prefixes of a file.
- We can compile a file where we remove one line from the input.

In addition, I would propose fuzzers to:
- Duplicate a line
- Swap two lines

Please feel free to come up with more interesting fuzzers.

Running these fuzzers is slow, so we only run them on three small programs. It might be worth to run all the fuzzers on all the examples programs we have, just to see if we can find any errors.

**Comment by magnus-madsen** [comment]
@herluf-ba What about fuzzing post-lexer? I imagine we could mess with the stream of tokens (e.g. dropping/cutting/duplicating) Would that be difficult? Would it be worthwhile?

**Comment by herluf-ba** [comment]
I think it would require "hacking" the pipeline in `Flix.scala` to mess with the token stream post-lexer. 
That makes it really hard to add any such tests to a CI/CD pipeline, but as a one off experiment maybe it makes sense.

I fell that it is more valuable testing in a way as close how a user would interact with Flix though. Any test modifying the token-stream I can think of, could have been written as text input and passed through the pipeline normally. For instance, if we want to test "drop token", I think just deleting the equivalent text is easier and more valuable.
