### ISSUE TITLE
Memory usage for `gradle test`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7541]

**Comment by magnus-madsen** [comment]
@stephentetley I created a `gradle.properties` in the project root with:

```
org.gradle.jvmargs=-Xmx4g -Xms128m
```

and I can run `./gradlew clean test`. Does that work for you?

(I should note that sometimes if you don't run clean indeed you might get strange errors.)

Another note: I believe GitHub runners only have 7GB of memory, so it should be possible.

Can you check and report back?

**Comment by stephentetley** [comment]
Thanks Magnus, not a success I'm afraid.

I killed `./gradlew clean test` after 1 hour 17 minutes. Prior to new typer `test all` would about 10-12 minutes on my PC.

I still saw the same sort of memory errors as per the trace posted to the discussion thread, I think after 20 to 30 minutes the JVM was just trying to service the memory problems and unable to evaluate any further tests.

**Comment by magnus-madsen** [comment]
That's annoying. I will have to check whether my configuration is actually respecting gradle.properties.

Whats your OS and Java version? How much memory does the JVM use with/without the gradle.properties?

I am also puzzled because the GitHub runners should only have 7GB memory and they seem to run fine.

The good news is that we will replace the Boolean unification stuff, which is very likely the culprint, with a better strategy in the near future (see #7542)

**Comment by stephentetley** [comment]
Windows (and PowerShell though I can't see that would make a difference). Java 21.

I can tray again on Ubuntu at the weekend although that didn't work within IntelliJ.

**Comment by magnus-madsen** [comment]
I can confirm that the memory usage increases to about 9GB.

Not sure why Gradle is not respecting my limit :/

**Comment by magnus-madsen** [comment]
As an experiment, in `build.gradle` can you try to change the task to:

```
task testAll(dependsOn: ['testClasses'], type: JavaExec) {
    mainClass = 'org.scalatest.tools.Runner'
    args = ['-s', 'ca.uwaterloo.flix.TestAll', '-o']
    jvmArgs = ['-Xmx4g']
    classpath = sourceSets.test.runtimeClasspath
    standardInput = System.in
}
```

This is dropping the `-P` flag for parallel execution and enforcing a memory limit.

**Comment by magnus-madsen** [comment]
On my my machine, when limited to 3G, the testAll still completes within a reasonable time.

**Comment by magnus-madsen** [comment]
(Note to self: `gradle.properties` is not used when running with `type: JavaExec`).

**Comment by magnus-madsen** [comment]
@stephentetley Hi Stephen. Did you have a chance to try without the `-P` flag?

**Comment by stephentetley** [comment]
Thanks Magnus, I forgot to try. I will look at it tomorrow evening.

**Comment by stephentetley** [comment]
I can now run `gradlew.bat test` with Flix head. I haven't tried through IntelliJ but I'd be hopeful it would work as it seems the memory residency problem is fixed - I'm not hearing my PC paging and I can use other programs will `gradlew.bat test` runs in the background.

**Comment by magnus-madsen** [comment]
We have modified master so tests no longer run in parallel. (Only parallel within one Flix instance). That should make memory usage smaller and predictable.

We have also started tracking memory usage here: https://arewefast.flix.dev/

Let me know if it still does not work within IDEA.
