### ISSUE TITLE
Parser: `Parser2.currentSourceLocation` calls `token.text.length` which always materializes the lazy text

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7571]

**Comment by magnus-madsen** [comment]
I am not even sure `currentSourceLocation` is correct. At least for multi-line tokens it seems "obviously" wrong.

**Comment by magnus-madsen** [comment]
I have changed the lazy val to a def, but this does not fundamentally alter the problem that it is called too often.

**Comment by herluf-ba** [comment]
@magnus-madsen This gets fixed in #7603 . But we should move back to `lazy` then I think.
