### ISSUE TITLE
Reduce backend ast caching

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#7576]
AST's in the backend are cached to enable ast printing on crash. This requires memory ofc. can this be reduced?

**Comment by magnus-madsen** [comment]
We could reintroduce a debug flag or require you to run some LSP command to enable debugging?

**Comment by magnus-madsen** [comment]
Not sure how it works in command line mode today? Do you print the asts to disk as you go?

**Comment by magnus-madsen** [comment]
What else can be done?

**Comment by JonathanStarup** [comment]
you give asts with `--Xprint-phase a, b, c` (or something like that). in that case we can just print when we hit relevant asts

but if you have a runtime crash, its nice to print the asts because the runtime crash might not be easily reproduced and if you run the compiler again with debug flags the names of functions will be different from the runtime error

**Comment by magnus-madsen** [comment]
I think we waste at least 30% of total memory keeping the later ASTs around.

It seems we have three use cases:

- Printing some ASTs to disk by request.
- Printing all ASTs to disk because of a crash.
- Showing an AST via VSCode.

These are easily supported if we store everything. If we don't then I am not sure.

**Comment by JonathanStarup** [comment]
@magnus-madsen should asts be printed "online" right as they're computed, or still after compilation like before?

**Comment by magnus-madsen** [comment]
> @magnus-madsen should asts be printed "online" right as they're computed, or still after compilation like before?

I think now we can print them online. Then you can also free memory immediately (?)

**Comment by JonathanStarup** [comment]
> > @magnus-madsen should asts be printed "online" right as they're computed, or still after compilation like before?
> 
> I think now we can print them online. Then you can also free memory immediately (?)

only downside is that priting to file can fail - do we stop everything or let compilation continue?

**Comment by magnus-madsen** [comment]
> > > @magnus-madsen should asts be printed "online" right as they're computed, or still after compilation like before?
> > 
> > 
> > I think now we can print them online. Then you can also free memory immediately (?)
> 
> only downside is that priting to file can fail - do we stop everything or let compilation continue?

As in IO error? If you get that I think everything is broken anyway.

**Comment by magnus-madsen** [comment]
E.g. if you have no more disk space probably you will not be able to write class files anyway.
