### ISSUE TITLE
Leftover type constraints

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#7594]
In the `while(progress)` loop of `ConstraintSolver.resolve` it doesn't check for `cur.isEmpty` at the end.

8 tests have leftover constraints that are not reported (all of type Trait or Purification)

**Comment by JonathanStarup** [comment]
@magnus-madsen

**Comment by magnus-madsen** [comment]
@mlutze Thoughts? The problem is that the progress can return false, but still there can be constraints.

**Comment by mlutze** [comment]
The responsibility of the `resolve` function is to reduce constraints as far as possible and report errors that are _definitely_ errors under any context. E.g. `Int ~ String`

In the Typer, the function that calls `resolve` checks for leftover constraints.

Which tests have leftover constraints?

**Comment by JonathanStarup** [comment]
Sorry, misreading on my part. and then faulty verification of my wrong understanding 😄 works as expected
