### ISSUE TITLE
Parser: Doc comments are not included

### ISSUE THREAD

**Issue by sockmaster27** [flix/flix#7608]
The `node.doc` attribute of all AST nodes is empty when it reaches the `HTMLDocumentor` phase.

This means that running the `:doc` command produces this
![image](https://github.com/flix/flix/assets/61235930/40f65fb1-1921-48c3-8804-4902d0963273)
when it should be producing this
![image](https://github.com/flix/flix/assets/61235930/0dd3eac0-1313-4334-ac70-7b4fc31e908c)

Could it be a problem with the new parser?

**Comment by sockmaster27** [comment]
@herluf-ba

**Comment by herluf-ba** [comment]
@sockmaster27 Thanks for letting me know about this! I got around to making a fix in #7668 .
To me it seems like everything is working. Could you jump on that branch and have a quick verify perhaps? :-)

**Comment by sockmaster27** [comment]
@herluf-ba
Looks good!

**Comment by magnus-madsen** [comment]
Unsure if comments for enums and traits were lost, or just never supported?

**Comment by herluf-ba** [comment]
@magnus-madsen No, they were definitely supported. Could you give an example of an `enum`/`trait` that's missing it's documentation? I can't seem to find one. Note that some don't have a doc-comment in source.

**Comment by herluf-ba** [comment]
Oh never mind! I just found the trait `Div`. That one is missing it's doc.
