### ISSUE TITLE
Parser: issue with semantic tokens / source locations

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7637]
See here:

![image](https://github.com/flix/flix/assets/2287953/5a409429-5e17-4c24-b5d3-f72bbd922649)

It seems that the parsing/weeding/desugaring of `+` makes it token span too long. I think this behavior is new. 

Note how the literal of `x` is colored compared to `y`.

**Comment by herluf-ba** [comment]
Yep, that seems like a Parser issue.

**Comment by magnus-madsen** [comment]
Downgraded priority.

**Comment by magnus-madsen** [comment]
@herluf-ba Reupgraded priority because wrong source locations are bad for other compiler errors.
