### ISSUE TITLE
Parser: missing syntax error

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7649]
```
instance Order {
    
}
```

**Comment by herluf-ba** [comment]
Just to make sure, An empty instance should produce an error? It is a one-or-more situation?

**Comment by magnus-madsen** [comment]
Its the missing type parameters that should produce an error, not the curly braces.

**Comment by magnus-madsen** [comment]
You cannot have an instance Order, you must have an instance Order of something.

So `instance Foo[Bar]` without curly braces is OK.

**Comment by herluf-ba** [comment]
Ah, that makes sense. That's actually an easy fix then. Thanks for clarifying, I will get around to it soon 👍
