### ISSUE TITLE
Bug in Stratify

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7658]
This seems wrong:

```
case Join(d1, d2) => Map.unionWith(Int32.max, stratify(d1), stratify(d2))
```

**Comment by magnus-madsen** [comment]
@JonathanStarup Agree this is wrong?

**Comment by JonathanStarup** [comment]
Yes, it should collect the two recursive dep graphs, and then solve the combined graphs

**Comment by JonathanStarup** [comment]
almost just 
```def stratify(d) = mkDepGraph(d) |> stratifyHelper```
excect that it needs the initial maps with all zeroes.

**Comment by magnus-madsen** [comment]
Ok. Will you attempt at fix?
