### ISSUE TITLE
Weeder: crash without match body

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7678]
```
/// An algebraic data type for binary trees with leaves.
enum Tree[a] {
    case Leaf(a),
    case Node(Tree[a], Tree[a])
}

/// A higher-order function that transforms a tree with
/// elements of type `a` to a tree with elements of type `b`.
def map(f: a -> b, t: Tree[a]): Tree[b] = match t
```

The crash occurs later in the pipeline, but I think the Weeder should just emit an error when the body is missing.

**Comment by magnus-madsen** [comment]
I marked this as high priority because it is common when doing normal programming.

**Comment by magnus-madsen** [comment]
The exact same bug also occurs with an empty handler body:

```
    @Test
    def testMutualRecursive05(): Bool =
        let result = try {
            mutual1(10)
        } with AskTell ;
        Assert.eq(Some(84), result)
```

Presumably it would also occur with an empty try-catch body.

**Comment by herluf-ba** [comment]
It just so happens that #7693 fixes the issue with `match`. I'll make a separate PR with the empty handler body and try-catch body cases 👍
