### ISSUE TITLE
[Concurrency] Parsing of Spawn

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#769]
Quentin pointed out that the following does not parse:

```
def main(): Unit  = 
  let c0 = chan Unit 1; 
  spawn (c0 <- (); <- c0)
```

but it probably should?

**Comment by JonathanStarup** [comment]
I feel like the parsing of the would be inconsistent. This parsing allows omitting the brackets like `spawn c0 <- ()` and is consistent with IfThenElse `if (true) (1;())` doesn't parse but `if (true) {1;()}` does. Maybe the expectation above comes from spawn looking like a function?

**Comment by magnus-madsen** [comment]
Allow Tuple production to refer to Expression.Statement at 

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Parser.scala#L735
