### ISSUE TITLE
Parser: replace `Pure` with `{}` and empty record with `{|}`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7701]
We have decided to make the following change:

- The syntax for the empty record `{}` should become `{|}`, meanwhile
- The syntax for the empty effect set `Pure` should become `{}`

**Comment by magnus-madsen** [comment]
@herluf-ba There is no rush. We could do this later.

**Comment by magnus-madsen** [comment]
What about the expression for the empty record?

**Comment by herluf-ba** [comment]
> What about the expression for the empty record?

I don't  see any issue with the empty record being still being `{}`. The parser always knows if it's supposed to expect an expression or a type. So it can dissern between `{}` the empty record literal and `{}` the empty effect set type literal.
