### ISSUE TITLE
Parser: crash with doc comment

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7726]
This

```
/// An algebraic data type for shapes.
enum Shape {
    case Circle(Int32),          /// circle radius
    case Square(Int32),          // side length
    case Rectangle(Int32, Int32) // height and width
}
```

seems to crash Flix/VSCode

**Comment by magnus-madsen** [comment]
It seems inserting doc comments and other comments here and there quickly lead to crashes.

**Comment by herluf-ba** [comment]
@magnus-madsen This was fixed together with some changes I made to comment parsing recently 👍
VScode or running from terminal no longer crashes `master` or branch at #7725.
