### ISSUE TITLE
Add `InvokeMethod2` to front-end ASTs

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7749]
Add a new node:

```scala
case class InvokeMethod2(ident: Name.Ident, exp: Expr, exps: List[Expr], loc: SourceLocation) extends Expr
```

Just below the existing `InvokeMethod`.

To begin with, we should just support the syntax:

```
.name1.name2(exps..) // Note the prefix dot
```

Here `name2` is a `Name.Ident`. We should also parse `name1` as a `Name.Ident`, but wrap it in an `Expr.Var`.

That way, we can later extend the parser without making changes to the rest.

**Comment by magnus-madsen** [comment]
CC @chanattan @JonathanStarup @mlutze

**Comment by JonathanStarup** [comment]
`InvokeImplicitMethod`?

**Comment by JonathanStarup** [comment]
Your example code doesnt really match the structure of the asts, i guess we add it to parsedAst as a JvmOp and then later an atomic op also

**Comment by magnus-madsen** [comment]
> Your example code doesnt really match the structure of the asts, i guess we add it to parsedAst as a JvmOp and then later an atomic op also

Why not? Compare it to WeededAst.Expr.InvokeMethod.

**Comment by magnus-madsen** [comment]
> Your example code doesnt really match the structure of the asts, i guess we add it to parsedAst as a JvmOp and then later an atomic op also

Looking at JvmOp I would not add it there. The structure is very different. InvokeMethod is now much closer to Apply than it is to an import.

**Comment by JonathanStarup** [comment]
Yes, we also concluded that after some tinkering
