### ISSUE TITLE
Add `InvokeConstructor2` and `InvokeStaticMethod2` to frontend

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7768]
Use the order: InvokeConstructor2, InvokeMethod2, and InvokeStaticMethod2 everywhere.

In WeededAst it should look like:

```scala
case class InvokeConstructor2(clazzName: Name.Ident, exps: List[Expr], loc: SourceLocation) extends Expr

case class InvokeMethod2(exp: Expr, methodName: Name.Ident, exps: List[Expr], loc: SourceLocation) extends Expr

case class InvokeStaticMethod2(clazzName: Name.Ident, methodName: Name.Ident, exps: List[Expr], loc: SourceLocation) extends Expr
```

In ResolvedAst it should look like:

```scala
case class InvokeConstructor2(clazz: Class[_], exps: List[Expr], loc: SourceLocation) extends Expr

case class InvokeMethod2(exp: Expr, methodName: Name.Ident, exps: List[Expr], loc: SourceLocation) extends Expr

case class InvokeStaticMethod2(clazz: Class[_], methodName: Name.Ident, exps: List[Expr], loc: SourceLocation) extends Expr
```

The idea is that the programmer will write:

```
import java.lang.Foo
.Foo.method()
```

After import resolution we will know that Foo is `Class[java.lang.Foo]`.

**Lets us also take this opportunity to rename `name` on `InvokeMethod2` to `methodName` everywhere.**

**Comment by magnus-madsen** [comment]
CC @chanattan @mlutze

**Comment by chanattan** [comment]
Wouldn't it be InvokeConstructor (no 2) instead?
Or I simply don't recall the difference between the 2 versions and the non-2 versions.
@magnus-madsen

**Comment by magnus-madsen** [comment]
> Wouldn't it be InvokeConstructor (no 2) instead? Or I simply don't recall the difference between the 2 versions and the non-2 versions. @magnus-madsen

What do you mean?

But yes, everything we add should be called "2" for now-- to avoid clashes with the old stuff.

**Comment by chanattan** [comment]
Thank you. I mean, in the current code I find no InvokeConstructor2() class, only InvokeConstructor().

**Comment by magnus-madsen** [comment]
> Thank you. I mean, in the current code I find no InvokeConstructor2() class, only InvokeConstructor().

Yes, I meant for you to add InvokeConstructor2, InvokeMethod2 (already done), and InvokeStaticMethod2 :)
