### ISSUE TITLE
Extend Method Resolution

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7769]
Each can be its own PR:

- [x] Add support for the types: `BigInt`, `BigDecimal`, and `String`
- [x] Add `TypeError.MethodNotFound` and `TypeError.AmbiguousMethod` and use these when the result set is empty or > 2.
- [x] Add support for the type `Native` (which has a reference to a class)

**Comment by magnus-madsen** [comment]
CC @chanattan @mlutze

**Comment by chanattan** [comment]
#7844 should take care of the three above tasks.
