### ISSUE TITLE
Add Support for Pattern Matching on Records

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#777]
We should allow records to be destructed with pattern matching, e.g.:

```
match r with {
  case { fstName, lstName } => 
}
```

**Comment by magnus-madsen** [comment]
@nicdard This might actually be a good medium-sized project. It involves minor changes to the frontend of the compiler, a bit more work in typer, and some work in the Simplifier. In any case, it can be done by starting from some test cases and then working one phase at a time.

**Comment by nicdard** [comment]
Very cool, thanks! I would really likes to take it feel free to assign this to me :)
Also it goes together with refactoring the pattern matching code that we discussed right?

**Comment by magnus-madsen** [comment]
Not entirely, but that could be a natural thing to do after.

To get started, I would: (1) Write a few programs that use pattern matching on records (obviously they will not work yet). (2) Extende ParsedAst.Pattern with some record constructs (they should probably look closely like their Expression friends) and (3) Try to extend the Parser.

Once that works, you can work phase-by-phase.

I suggest to open a pull request as soon as you have some test cases. (See Text.Exp.Match.XYZ).

**Comment by nicdard** [comment]
Perfect! Thanks for the guide :)

**Comment by nicdard** [comment]
I am starting to work on this :)

**Comment by magnus-madsen** [comment]
@jaschdoc I think you have the expertise to do this once the backend stuff clears the queue. What do you think?

**Comment by jaschdoc** [comment]
I'd love to give it a try!

**Comment by jaschdoc** [comment]
It seems OCaml allows these patterns for records
```scala
{ x }
{ x : Int32 }
{ x : Int32 = 1 }
{ x = 1 }
{ x, y : Int32 = 2 | _ }
```
https://v2.ocaml.org/releases/5.0/htmlman/patterns.html

**Comment by magnus-madsen** [comment]
Does it not allow `{ l1 = x }`?

**Comment by jaschdoc** [comment]
What are `l1` and `x` here?

**Comment by magnus-madsen** [comment]
> What are `l1` and `x` here?

The l1 would be the field, and `x` would be a freely chosen variable.

For example, if you had two point records, you could do:

```
match (p1, p2) {
case ({x = x1, y = y1}, {x = x2, y = y2}) => 
```

I agree we will want other patterns, I just think this is a reasonable place to start.

**Comment by jaschdoc** [comment]
> The l1 would be the field, and `x` would be a freely chosen variable.

Yes it does. I forgot to write that in the post above.
