### ISSUE TITLE
Add automatic derivation of coerce

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7784]
... for singleton enums ...

**Comment by mlutze** [comment]
Should there also be uncoerce?

**Comment by magnus-madsen** [comment]
How does  that work? There could be many options

**Comment by mlutze** [comment]
It's determined by the expected type.

```
enum Thing(String) with Coerce

def makeThing(x: String): Thing = uncoerce(x)
```

I don't have an actual use-case, but I like the symmetry :)

**Comment by mlutze** [comment]
One use-case I have is something like `Coerce.map` for when we want to do something to the inner type:
```
mod Coerce {
    def map(f: Coerce.Out[a] -> Coerce.Out[a] \ ef, x: a): a \ ef = {
        x |> coerce |> f |> uncoerce
    }
}
```

**Comment by magnus-madsen** [comment]
Can I ask you to update doc.flix.dev?

**Comment by magnus-madsen** [comment]
or alternatively, should coerce be auto-derived?

**Comment by mlutze** [comment]
> Can I ask you to update doc.flix.dev?

Yes, I'll reopen for tracking

> or alternatively, should coerce be auto-derived?

No, that would expose an implementation detail
