### ISSUE TITLE
Irrefutable Patterns

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#780]
Determine whether we should add support for irrefutable patterns in various places through the language, e.g.:

```scala
def f((x, y): (Int, Int): Unit = // matches on a pair or perhaps
def f((x: Int, y: Int)): Unit = 
def f({x: Int, y: Int}): Unit = // matches on a record.
```

and so on.

More realistic examples:

```scala
def fst((x: Int, y: Int)): Int = x
def area({x: Int, y: Int}): Int = x * y
```

**Comment by magnus-madsen** [comment]
Maybe later.

**Comment by JonathanStarup** [comment]
@magnus-madsen this would be really nice with the name parameters
, this `def f(regex: {regex::String}, s: String): String = regex.regex` could be `def f({regex::String}, s: String): String = regex`

**Comment by magnus-madsen** [comment]
True, but its also very complicated-- both on the user side and on the compiler-side. Hence I suggest that this is one of those nice-to-have, but not need-to-have. Better to add it later when the language is much more mature.
