### ISSUE TITLE
Benchmark.flix triggers crash

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7828]

**Comment by magnus-madsen** [comment]
@mlutze Can you take a look? It used to work. But I guess the file was not under unit testing?

**Comment by mlutze** [comment]
That's weird, it's part of the standard library

**Comment by mlutze** [comment]
Can't reproduce. Anyway, this is part of a known class of errors where we cannot handle error types. Should be resolved with the new solver.
