### ISSUE TITLE
Pattern Matching

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#783]
Rewrite the pattern matcher and extend it by:

- Adding irrefutable patterns everywhere applicable (#780).
- Adding pattern matching on records (#777).
- Adding pattern matching on arrays.
- Adding binary pattern matching ala Erlang.
- Adding regular expression pattern matching.
- Adding non-linear patterns.
- Adding user-defined patterns.
- Adding GADTs (advanced).
- Adding pattern matching to logic rules.

**Comment by mlutze** [comment]
A couple more ideas:
* Adding pattern matching on references
* Adding pattern matching on lazy (like OCaml)

**Comment by mlutze** [comment]
* String interpolation in patterns (might be redundant with regular expressions)

**Comment by magnus-madsen** [comment]
We can open specific tickets about specific types of pattern matching we want.

I think, for now, the only thing we want is on records.
