### ISSUE TITLE
Add simple tests for `InvokeMethod2`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7833]
In combination with #7769

- [ ] Add tests for calling methods on `BigInt` (`Test.Exp.InvokeMethod2.flix`)
- [ ] Add tests for calling methods on `BigDecimal`  (`Test.Exp.InvokeMethod2.flix`)
- [ ] Add tests for calling methods on `String`  (`Test.Exp.InvokeMethod2.flix`)
- [ ] Add tests for calling zero argument methods.  (`Test.Exp.InvokeMethod2.ZeroArg.flix`)
- [ ] Add tests for method chaining `foo.bar().baz()`  (`Test.Exp.InvokeMethod2.Chaining.flix`)
- [ ] Add tests for calling methods overloaded by arity: (`Test.Exp.InvokeMethod2.Overload.Arity.flix`)
  - [ ] Add tests for calling each `String.indexOf` overload  
  - [ ] Add tests for calling each `String.lastIndexOf` overload
  - [ ] Add tests for calling each `String.replace` overload
  - [ ] Add tests for calling each `String.split` overload
- [ ] Add tests for calling methods overloaded by types: (`Test.Exp.InvokeMethod2.Overload.Types.flix`)
  - [ ] Add tests for calling each `String.valueOf` overload
  - [ ] Add tests for calling each `String.replace` overload
- [ ] Add tests for calling methods with subtyping: (`Test.Exp.InvokeMethod2.Overload.Subtypes.flix`)
  - [ ] Add tests for calling `String.contains`
  - [ ] Add tests for calling `String.equals`
- [ ] Add tests for calling methods with subtyping on `Null` (`Test.Exp.InvokeMethod2.Overload.Null.flix`)
- [ ] Add negative tests for `AmbiguousMethod` and `MethodNotFound` to `TestTyper` (at least 3 for each error)

I suggest to use multiple names spaces as outlined in parens above.

**Comment by magnus-madsen** [comment]
CC @chanattan

**Comment by magnus-madsen** [comment]
@chanattan It would be good to have some chaining tests where the return type is different.

**Comment by chanattan** [comment]
@magnus-madsen valueOf is a static method and is not supported by invokeMethod2 but will be with invokeStaticMethod2.
`String.replace` has no overloading by arity, I moved the tests to type overload.
`split` can not be supported yet.
The rest is being worked on.

**Comment by chanattan** [comment]
- [ ] Add tests for calling methods on BigInt (Test.Exp.InvokeMethod2.flix)
- [ ] Add tests for calling methods on BigDecimal (Test.Exp.InvokeMethod2.flix)
- [ ] Add tests for calling methods on String (Test.Exp.InvokeMethod2.flix)
- [ ] Add tests for calling zero argument methods. (Test.Exp.InvokeMethod2.ZeroArg.flix)
- [ ] Add tests for method chaining foo.bar().baz() (Test.Exp.InvokeMethod2.Chaining.flix)
- [ ] Add tests for calling methods overloaded by arity: (Test.Exp.InvokeMethod2.Overload.Arity.flix)
    - [ ] Add tests for calling each String.indexOf overload
    - [ ] Add tests for calling each String.lastIndexOf overload
    - [ ] Add tests for calling each String.replace overload
    - [ ] Add tests for calling each String.split overload
- [ ] Add tests for calling methods overloaded by types: (Test.Exp.InvokeMethod2.Overload.Types.flix)
    - [ ] Add tests for calling each String.valueOf overload
    - [ ] Add tests for calling each String.replace overload
- [ ] Add tests for calling methods with subtyping: (Test.Exp.InvokeMethod2.Overload.Subtypes.flix)
    - [ ] Add tests for calling String.contains
    - [ ] Add tests for calling String.equals
- [ ] Add tests for calling methods with subtyping on Null (Test.Exp.InvokeMethod2.Overload.Null.flix)
- [ ] Add negative tests for AmbiguousMethod and MethodNotFound to TestTyper (at least 3 for each error)

**Comment by chanattan** [comment]
Do we mix static calls with InvokeMethod2 test files? @magnus-madsen

**Comment by magnus-madsen** [comment]
Fixed in master.
