### ISSUE TITLE
[Concurrency] Allow channel creation without buffer size

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#784]
Allow the following:

```scala
def send(x: Channel[Int]): Unit = x <- 42; ()
def main(): Int = 
    let c = chan; // notice that there is no channel size and no type
    spawn send(c);
    <- c
```

**Comment by magnus-madsen** [comment]
Remove size and type.

**Comment by magnus-madsen** [comment]
A question how we can remove both the type and size while keeping the grammar consistent.

**Comment by justinfargnoli** [comment]
> ```
> def foo(): ... = 
>   let chan = 123;
>   let foobar = chan
> ```
> In the last line, does chan create a new channel or is it a read of the local variable named chan?
> (You can of course argue that local variables should not be named chan- but that then goes beyond the original problem.) 

An example from @magnus-madsen, via private messages on Gitter, of ambiguity that could arise via this change.

**Comment by magnus-madsen** [comment]
Fixed in master.
