### ISSUE TITLE
`and` ambiguity between Flix keyword and `BigInteger`'s method

### ISSUE THREAD

**Issue by chanattan** [flix/flix#7841]
This issue is related to support for `InvokeMethod2` on type `BigInteger` from Java, from PRs #7769 and #7833.

The program, with `BigInteger` java interoperability set, is the following:

```
def testInvokeMethod2_09(): Bool \ IO =
    let val = 150ii;
    val#and(-100ii) == 148ii
```

It gives a parsing error, as `and` is both a Flix keyword and a method from `BigInteger`:
The same goes for methods like `mod`.

```
-- Parse Error (OtherExpr) -------------------------------------------------- /home/csok/IdeaProjects/flix/test.flix

>> Expected <Name> or <name> before 'and'.

46 |     val#and(-100ii) == 148ii
             ^^^
             Here
Hint: 'and' is a keyword.

-- Parse Error (Unknown) -------------------------------------------------- /home/csok/IdeaProjects/flix/test.flix

>> Expected at least one <Ident>.

46 |     val#and(-100ii) == 148ii
             ^^^^^^^^^^^
             Here
```

In other programming languages, methods are not allowed to have the same name as a keyword of the language, if I recall correctly.
Should we prioritize a java method call over a keyword for this context?

**Comment by JonathanStarup** [comment]
Works on master
