### ISSUE TITLE
[Concurrency] Deadlock

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#786]
The following (generated) program:

```scala
def eval(): Unit = {
  let c11 = chan Unit 0;
  let c9 = chan Unit 0;
  let c10 = chan Unit 0;
  spawn { c11 <- () } ;
  spawn { c10 <- () } ;
  spawn { c9 <- ()  } ;
  select {
    case nocare <- c9 => <- c11 ; <- c10
    case nocare <- c9 => <- c11 ;
      select {
        case nocare <- c10 => ()
        case nocare <- c10 => ()
       }
     case nocare <- c11 => <- c9 ; select {
       case nocare <- c10 => ()
       case nocare <- c10 => ()
     }
   };
   ()
}

def loop(n: Int): Unit =
  if (n == 0) {
    ()
  } else {
    eval();
    loop(n - 1)
  }

def main(): Unit = loop(100)
```

does not terminate (deadlocks).

By construction the program should not have any deadlocks, as a careful analysis of the program will show.

@JonathanStarup @SimonMeldahl I know you are busy with the CPS stuff, but it is also important if you can look into this, since it affects correctness of the code we already have "out there".

**Comment by acieroid** [comment]
See there for a potential fix: https://github.com/flix/flix/compare/master...acieroid:master

**Comment by magnus-madsen** [comment]
The fix has been merged.
