### ISSUE TITLE
Move `Ast.*` to `shared`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7871]
The idea is to get rid of Ast.scala and instead have new files in the shared folder.

Lets do one thing at a time: We can start with, in separate PRs:

- Add shared/Denotation.scala
- Add shared/Polarity.scala

**Comment by magnus-madsen** [comment]
@sockmaster27 You can slowly start on this. One PR per move.

The idea is simply to move things out of the Ast.scala file and into their own file in the shared package.

**Comment by magnus-madsen** [comment]
@sockmaster27 Can we complete this?

**Comment by sockmaster27** [comment]
3 to go
