### ISSUE TITLE
Refactor the Standard Library to always use `import` for Java types

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7872]
For example:

```
mod Adaptor {

    /// ...
    pub def comparator(_: Proxy[a]): ##java.util.Comparator \ IO with Order[a] =
```

should become

```
mod Adaptor {
    import java.util.Comparator

    /// ...
    pub def comparator(_: Proxy[a]): Comparator \ IO with Order[a] =
```

- Ensure that all imports occur just after the module declaration (i.e. inside it).
- Ensure that imports are alphabetically sorted.

EDIT: Updated example based on discussion.

**Comment by JonathanStarup** [comment]
~Should they not be inside the `mod`? ~

Ah I was just about to complain that we don't enforce it - but they do have to be inside the mod

**Comment by magnus-madsen** [comment]
Hmm. I guess they have to be inside the module.

**Comment by jaschdoc** [comment]
We still can't import in instances :/

**Comment by magnus-madsen** [comment]
> We still can't import in type class instances :/ I can try to fix it but maybe someone already has that assigned to them?

What does @mlutze

**Comment by jaschdoc** [comment]
Use regex `def .* ##`

**Comment by jaschdoc** [comment]
Should be done now

**Comment by magnus-madsen** [comment]
Thanks!
