### ISSUE TITLE
Refactor Namer

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7875]
Each in separate PR:

- [x] Reformat file with Intellij IDEA
- [x] Fix all warnings reported by Intellij IDEA (e.g. unused variables should be _ and functions should be private)
- [x] visitType has a local visit function that can simply be removed
- [x] Replace calls to `toSoftFailure` with usage of sctx (i.e. just add the error).
- [ ] Methodically remove Validation from all function return types. 
  - Break into smaller PRs, e.g. start with the leaves of the computation, e.g. visitType, visitHeadPredicate and so forth.

Try keep local variables, e.g. if the code is:

```
    case DesugaredAst.Expr.IfThenElse(exp1, exp2, exp3, loc) =>
      val e1 = visitExp(exp1, ns0)
      val e2 = visitExp(exp2, ns0)
      val e3 = visitExp(exp3, ns0)
      mapN(e1, e2, e3) {
        NamedAst.Expr.IfThenElse(_, _, _, loc)
      }
```

then it simply becomes

```
    case DesugaredAst.Expr.IfThenElse(exp1, exp2, exp3, loc) =>
      val e1 = visitExp(exp1, ns0)
      val e2 = visitExp(exp2, ns0)
      val e3 = visitExp(exp3, ns0)
      NamedAst.Expr.IfThenElse(e1, e2, e3, loc)
```

Note: Don't inline the visitExp calls.

Keep the structure: don't make other changes during the refactor.

If during the refactor a validation is needed, just do Validation.success(foo). This keeps each PR clean.

If you see code without local variables, e.g.:

```
    case DesugaredAst.Expr.FixpointInject(exp, pred, loc) =>
      mapN(visitExp(exp, ns0)) {
        case e => NamedAst.Expr.FixpointInject(e, pred, loc)
      }
```

please introduce them, e.g. here we would have an `e`.

**Comment by magnus-madsen** [comment]
Enjoy your work by seeing how much prettier direct-style is, and seeing if --Xbenchmark-phases improves. (I expect 2x improvement!)

**Comment by jaschdoc** [comment]
- [ ] Reformat file with Intellij IDEA
- [ ] Fix all warnings reported by Intellij IDEA (e.g. unused variables should be _ and functions should be private)
- [ ] `visitType` has a local visit function that can simply be removed
- [ ] Replace calls to `toSoftFailure` with usage of `sctx` (i.e. just add the error).
- [ ] Methodically remove `Validation` from all function return types.
