### ISSUE TITLE
Rework records to use hash instead of dot

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7897]
- [x] Refactor the compiler to use `#` instead of `.` for `RecordSelect`
  - The key change needs to happen in `Parser2.scala` near line 1298.
  - In addition lines 840-845 in `Weeder2.scala` should be commented and later repurposed for Java fields/methods. Printing the source location here may help identify all the places in the standard library that has to be updated.
- [x] Refactor the entire standard library and tests to use new syntax `#`-based syntax.
- [x] Update `RecordSelect` in `DocAst.scala`
- [x] Update `LabelCompleter.scala` to work correctly with `#`.
- [x] Ensure VSCode formatting looks OK
- [x] Update syntax on https://doc.flix.dev
- [x] Update samples on https://flix.dev
- [x] Update samples on https://play.flix.dev

**Comment by jaschdoc** [comment]
- [ ]  Refactor the compiler to use `#` instead of `.` for `RecordSelect`
    - The key change needs to happen in `Parser2.scala` near line 1298.
    - In addition lines 840-845 in `Weeder2.scala` should be commented and later repurposed for Java fields/methods. Printing the source location here may help identify all the places in the standard library that has to be updated.
- [ ]  Refactor the entire standard library and tests to use new syntax `#`-based syntax.
- [ ]  Update `RecordSelect` in `DocAst.scala`
- [ ]  Update `LabelCompleter.scala` to work correctly with `#`.
- [ ]  Ensure VSCode formatting looks OK
- [ ]  Update syntax on https://doc.flix.dev
- [ ]  Update samples on https://flix.dev
- [ ]  Update samples on https://play.flix.dev

**Comment by jaschdoc** [comment]
What do you mean by `Ensure VSCode formatting looks OK`?

**Comment by magnus-madsen** [comment]
> What do you mean by `Ensure VSCode formatting looks OK`?

Just that syntax highlighting is not broken for some unknown reason.

**Comment by magnus-madsen** [comment]
Note: I am the only one who can update the playground and website, but you can do a cumbersome pass through the documentation. Thanks!

**Comment by jaschdoc** [comment]
I'm still unsure how to fix parsing of function application after record select, e.g.,

```flix
(ide#eshCallStart)(n, d, p)
```
which should just be
```flix
ide#eshCallStart(n, d, p)
```
(from [IDE.flix](https://github.com/flix/flix/blob/ed1f0027598bc592c18d24c82b1ff57cc108f082/examples/larger-examples/program-analysis/IDE.flix#L66C56-L66C83))

Maybe just parse record select before application, i.e., swap lines `1324-1329` with `1331-1340` in `Parser2`?

**Comment by magnus-madsen** [comment]
Yeah... I don't know :)

**Comment by jaschdoc** [comment]
Investigating :)

**Comment by jaschdoc** [comment]
I think everything is done now (except for the weird thing that happened here https://github.com/flix/flix/pull/7930#issuecomment-2186258865)
