### ISSUE TITLE
Improvement to java import / java type autocompletion

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#7900]
I think we can extract some common java type autocompletion out of the import completion provider and new object completion provider https://github.com/flix/flix/pull/7605 so we can autocomplete java types anywhere they are used. This would allow us to provide suggestions when defining functions and catch rules.

**Comment by jaschdoc** [comment]
Maybe this also requires adding a new `SyntacticContext` like `JavaType`

**Comment by magnus-madsen** [comment]
Let us look into it once the NewObject PR is unblocked.

**Comment by magnus-madsen** [comment]
I think if fixed this? Because now you can only import Java types in an actual import decl and there we have auto-complete.

**Comment by jaschdoc** [comment]
True
