### ISSUE TITLE
Structs: Add test cases for struct declarations: `Test.Dec.Struct.flix`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7937]

**Comment by magnus-madsen** [comment]
@dghosef While we cannot merge in the test cases before all tasks in #7923 are complete, I strongly recommend to create a draft PR with some struct declaration examples -- since that might be useful during implementation and to discuss syntax. You can be inspired by `Test.Dec.Enum`.

**Comment by magnus-madsen** [comment]
I suppose we have some tests, but do we feel good about coverage?

**Comment by dghosef** [comment]
Any specific tests we're missing? In terms of struct declarations, this coverage is similar to Enums

**Comment by magnus-madsen** [comment]
> Any specific tests we're missing? In terms of struct declarations, this coverage is similar to Enums

I was asking you :) If you think we are good then we are good 👍

**Comment by dghosef** [comment]
Oh I see. One case we don't have is, for example, a field which is an option of a recursive struct(like a Binary Tree), but that is covered in struct put / struct get. Should I move that here too?

**Comment by magnus-madsen** [comment]
I think its OK
