### ISSUE TITLE
Java: Refactor Standard Library to use `InvokeConstructor2`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7944]
We have the right syntax for `InvokeConstructor2` so we can start to refactor the library. See below for an example.

We need to update the following files. I suggest one PR per file:

- [x] Adaptor
- [x] BigDecimal
- [x] BigInt
- [x] File
- [ ] Files
- [x] Float64
- [x] Int16
- [x] Int32
- [x] Int64
- [x] Int8
- [x] Random
- [x] StringBuilder
- [x] CyclicBarrier
- [x] ReetrantLock
- [x] System

For example:

```
pub def toBigDecimal(x: Int32): BigDecimal =
    import java_new java.math.BigDecimal(Int32): BigDecimal \ {} as fromInt32;
    fromInt32(x)
```

can become:

```
import java.math.BigDecimal

pub def toBigDecimal(x: Int32): BigDecimal =
    unsafe new BigDecimal(x)
```

**Comment by chanattan** [comment]
We have to add a parser functionality support to make it work with `|>`, however this seems like higher-order java interoperability stuff that we have not talked about yet.

**Comment by magnus-madsen** [comment]
Ah yes. We will have to discuss.

**Comment by magnus-madsen** [comment]
@chanattan Once the modules are refactored, we should have the old InvokeConstructor throw an exception in Weeder

**Comment by magnus-madsen** [comment]
@chanattan Just two modules to go :)

**Comment by magnus-madsen** [comment]
After those there test cases to fix.

**Comment by magnus-madsen** [comment]
@chanattan Can you get rid of the last usages of `import java_new` -- Thanks!

**Comment by chanattan** [comment]
@magnus-madsen could you check the array PR before I can fix the last java_new please?

**Comment by magnus-madsen** [comment]
Fixed in master.
