### ISSUE TITLE
[Backend] Boxing Issue

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#798]
```
def main(): Int =
    let n: Int = native method java.lang.Integer.parseInt("22") as Int;
    n
```

```
Exception in thread "main" java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    Def$main.invoke(LContext;)V @10: astore
  Reason:
    Type integer (current frame, stack[0]) is not assignable to reference type
  Current Frame:
    bci: @10
    flags: { }
    locals: { 'Def$main', 'Context', top, 'java/lang/Object' }
    stack: { integer }
  Bytecode:
    0000000: 2ab4 000c 4e12 1ab8 0020 3a04 1504 2a5f
    0000010: b500 12b1  
```

**Comment by magnus-madsen** [comment]
Looks like typing issue:

![image](https://user-images.githubusercontent.com/2287953/56721955-5270b300-6746-11e9-8b9b-a4c77ac5c701.png)

**Comment by magnus-madsen** [comment]
Problem is that (1) the native method is not assigned a result type, (2) a cast does not cause a unification. A type ascription can be used to force the return type.

**Comment by magnus-madsen** [comment]
The real solution is to force the programmer to give a full type specification for native methods.

**Comment by ifazk** [comment]
Could change the Typer to infer the return type by using `method.getReturnType`? That sounds like a more real solution to me.

**Comment by magnus-madsen** [comment]
@ifazk Is this now fixed?

**Comment by ifazk** [comment]
#800 Cannot deal with some complicated return types. For example, if the return type is a [`ParameterizedType`](https://docs.oracle.com/javase/7/docs/api/java/lang/reflect/ParameterizedType.html) (types like `Collection<String>`) or a [`TypeVariable`](https://docs.oracle.com/javase/7/docs/api/java/lang/reflect/TypeVariable.html). For these cases, #800 will infer a fresh type variable as the return type, leading to similar issues.
But it is fixed for all other return types: primitive types, class types, arrays of these types, etc.

**Comment by magnus-madsen** [comment]
Closing. I know we don't have a complete fix, but we have a separate ticket for better interop.
