### ISSUE TITLE
Import style

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7999]
We had a chat here and agree on the following style:

- Imports must be alphabetically sorted.
- Imports occur before uses.
- We should not use grouping: one import per line. 
- Minimal renaming: An import _should only be renamed if there is a clash_. If there is no clash, no rename.
- Imports should not use semicolons.

**Comment by magnus-madsen** [comment]
CC @jaschdoc @chanattan As you refactor, you can start to apply this style.

**Comment by jaschdoc** [comment]
What about inner classes like `Map$Entry`? Should we rename these to `Entry` in the import?

**Comment by jaschdoc** [comment]
The following files must be changed to the new import style:

- [ ] https://github.com/flix/flix/pull/7977/files
- [ ] https://github.com/flix/flix/pull/7980/files
- [ ] https://github.com/flix/flix/pull/7901/files
- [ ] https://github.com/flix/flix/pull/7909/files
- [ ] https://github.com/flix/flix/pull/7953/files

**Comment by magnus-madsen** [comment]
> What about inner classes like `Map$Entry`? Should we rename these to `Entry` in the import?

I suppose so. @mlutze Thoughts?

**Comment by mlutze** [comment]
> > What about inner classes like `Map$Entry`? Should we rename these to `Entry` in the import?
> 
> I suppose so. @mlutze Thoughts?

I agree
