### ISSUE TITLE
Structs: Add structs expressions to `Lexer`, `Parser`, and `Weeder`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#8000]
We should add expressions for working with structs.

Here is approximately what we want in `WeededAst`:

```scala
case class StructNew(qname: Name.QName, exps: List[(Name.Ident, Expr)], exp: Expr, loc: SourceLocation) extends Expr
case class StructGetField(exp: Expr, field: Name.Ident, loc: SourceLocation) extends Expr
case class StructPutField(exp1: Expr, field: Name.Ident, exp2: Expr, loc: SourceLocation) extends Expr
```

(Maybe `Name.Ident` should be `Name.StructField`?)

I would put these right before `ArrayNew`.

Ultimately, we will want syntax like:

```
let s = new A.B.C.Node { prev = exp1, next = exp2 } @ exp // the last exp is the region.
s.prev.next = s.next.next
```

But the above syntax conflicts with our current syntax, so until we resolve that, I propose the following __temporary__ syntax: 

```
let s = struct new A.B.C.Node { prev = exp1, next = exp2 } @ exp // the last exp is the region.
s€prev€next = s€next€next
```

If you have better suggestions, feel free to propose them :)

**Comment by dghosef** [comment]
Is `exp` in `StructNew` for the region?

**Comment by dghosef** [comment]
Also should `qname` be instead of type `Type` since there may be type variables(I think - I might be wrong about this)

For example: 
let s = new A.B.C.Node[Int32] { prev = exp1, next = exp2 } @ exp

**Comment by magnus-madsen** [comment]
> Is `exp` in `StructNew` for the region?

Yes

**Comment by magnus-madsen** [comment]
> Also should `qname` be instead of type `Type` since there may be type variables(I think - I might be wrong about this)
> 
> For example: let s = new A.B.C.Node[Int32] { prev = exp1, next = exp2 } @ exp

No, the type variables would be inferred. I guess there is a question of the name being imported (via `use`). 
But I think we can start with just a QName.

**Comment by JonathanStarup** [comment]
@dghosef this is outdated right?

**Comment by dghosef** [comment]
Yea. Thanks
