### ISSUE TITLE
Sub typing

### ISSUE THREAD

**Issue by sirinath** [flix/flix#804]
Though it might not be sub classing, some form of sub typing needs to be introduced to make it palatable with mainstream programmers. It can me subclassing plus and minus additional rules to be more robust.

**Comment by magnus-madsen** [comment]
I think subtyping is beyond the scope of what we can easily support with Hindley-Milner style type-inference. That said, we do need a good story for interop with Java and we will need some kind of machinery to deal with subtyping in that case.

**Comment by sirinath** [comment]
To keep portability of back ends make sure interop is not only tied to Java. Keep thinking of possible LLVM, Webasm, .Net backends

**Comment by sirinath** [comment]
Maybe you can extend Hindley-Milner style type-inference for System F sub. This may not be readily apparent but with further research this might be doable.

**Comment by magnus-madsen** [comment]
I am closing this, but we may explore support for ML_sub offline.
