### ISSUE TITLE
uniform `size`/`length` on enums and traits

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#8049]
`MutDeque.size`, `Array.length`, `Iterable[t]` doesnt have length, etc

**Comment by magnus-madsen** [comment]
What's your proposal? It seems a `List` has a length but a `Set` has a size. Then there are things in between.

**Comment by JonathanStarup** [comment]
Anything that is a (finite) collection of things should have a size, and that's the trait... Foldable?
