### ISSUE TITLE
Language Server Protocol Support

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#806]
We should add support for the language server protocol:

https://microsoft.github.io/language-server-protocol/

https://langserver.org/

so that we can get auto-completion and error messages in editors such as visual studio code.

We should also add Flix language add-on to VS code such that it is easy to install and get Flix support.

A big part of this project will be about understanding the LSP and figuring out a good architecture such that we can add it to the Flix compiler.

**Comment by anthonyabeo** [comment]
Hi @magnus-madsen, 

I will like to work on this project. Besides the links above what else do I need to know?

**Comment by magnus-madsen** [comment]
Cool! You will probably need to learn a lot of Flix compiler internals. I suggest that you start by looking into the above links and writing an initial plugin. Then when you get to the point where you want information from the compiler, e.g. what is the type of this expression, I can help you with how to get such information.

**Comment by anthonyabeo** [comment]
Will do @magnus-madsen .

**Comment by stephentetley** [comment]
I made a start on a VS Code plugin here:

https://github.com/stephentetley/vscode-flix

I've only looked at syntax highlighting, and it's already a bit out-of-date. And character literals don't work properly...

Please feel free to take any code that is useful.

**Comment by anthonyabeo** [comment]
Thanks, @stephentetley. The tmLanguage.json file came in very handy. 

I put an initial skeleton up here. https://github.com/anthonyabeo/flix-vscode-extension. 

Currently, the plug-in is able to start the language server and connect to it. Also, very basic on-Hover and auto-completion features are supported. 

When you type "b", "l" or "t", the auto-complete will suggest "Button", "ListView" and "TextView" respectively.

Feedback is welcome.

**Comment by magnus-madsen** [comment]
I tried following the instructions, but I am not sure exactly what to do.

1. I clone the project.
2. I open it in VSCode
3. I run npm install from the terminal.

Then I am not sure what to do. Pressing ctrl+shift+B gives a drop down. I can choose npm: compile.
Pressing F5 gives me a drop down with Java and Node.

**Comment by anthonyabeo** [comment]
I have pushed the launch and task file. You can pull the changes and try again.

**Comment by magnus-madsen** [comment]
I got it to work. Very cool!

Let us try to talk about some of the next steps. I know nothing about VSCode, but I am more than happy to help on the compiler side.

Syntax:
- The current set of keywords can be manually extracted from: https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Parser.scala Simply look for strings in "atomic".
- Can we highlight types differently e.g. built-types but also user-defined types?

Semantics:
- How do we hook up VSCode to the Flix compiler? I think starting with auto-completion is probably too hard, but what about something like "Show Type" (for an expression) or "Jump To Definition" for a definition or local variable?
- I don't speak LSP, but I can easily write an API where if you give me a bunch of files I can provide the source location for a given definition symbol or local variable. Or give you the type of an expression.

How do such queries look? Do I get the name as a string or the source position or what? How do I get the relevant files in the project? Can we easily write a LSP server in Java/Scala and interface it with the Flix compiler?

I am happy to provide an easily consumable API if you can tell me what it should look like. (Working on the actual LSP protocol I will leave to you).

**Comment by magnus-madsen** [comment]
EDIT: More content:

Syntax
- Can we add coloring for annotations, e.g. @lint?
- Is it possible to color an effect, e.g. `& Pure` in a light grey (or just some color to distinguish it from a keyword)?

Semantics:
- How can we report compilation errors to the programmer? E.g. how to get squiggly red lines?

**Comment by magnus-madsen** [comment]
@anthonyabeo I started on an JSON-style interface here #1051. 

My plan is to have an architecture where we have your `client.ts` and `server.ts` and then `server.ts` should be extended to:

1. Start the Flix compiler with the `--lsp` flag and a port.
2. To connect to this port (using the websocket protocol).
3. To translate LSP requests (e.g. onHover) into requests to the server (in JSON).
4. To translate the response from the server (a JSON object) into an appropriate LSP response.

What do you think?

While I hack on the JSON api, the next steps on your end would be to figure out how to do the following:

1. Start the Flix compiler from `server.ts`.
2. Send a JSON request that contains all the files to be compiled (not sure how this works, but the Flix compiler obviously needs the path to the files).
3. Send a JSON request to ask for e.g. the type of an expression at given line and col.

**Comment by anthonyabeo** [comment]
@magnus-madsen I have added some syntax highlighting changes. Still far from complete.

**Comment by magnus-madsen** [comment]
@anthonyabeo Great! I have made a lot of progress in #1051. Soon you should be able to start the Flix compiler and connect to a websocket to query it. For example, have a look at `Request.scala`. 

Currently I can support something like:

```
{"request":"compile","paths":["foo.flix"]}
{"request":"typeAndEffOf","position":{"line":1,"col":36}}
{"request":"gotoDef","position":{"line":4,"col":87}}
{"request":"shutdown"}
```

**Comment by magnus-madsen** [comment]
![image](https://user-images.githubusercontent.com/2287953/79001541-ece02700-7b4e-11ea-9885-cfb46dcdd410.png)

**Comment by magnus-madsen** [comment]
I merged in #1051. A pre-built JAR is available here:
https://flix.dev/release/flix-v0.12-pre.jar

You start Flix with:

```
java -jar flix.jar --lsp 8000
```

and then you can connect to that port and issue commands.

The currently support commands can be seen here:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala#L44

Hopefully this should be enough to get started on a better plugin for VSCode.

We will refine the available commands as we learn more about how everything fits together.

**Comment by magnus-madsen** [comment]
@anthonyabeo While there is no rush, are you up for working on this task?

**Comment by anthonyabeo** [comment]
@magnus-madsen yes I am. Juggling this alongside work is taking a toll, but I am.

**Comment by magnus-madsen** [comment]
> @magnus-madsen yes I am. Juggling this alongside work is taking a toll, but I am.

OK, no worries, don't get stressed :-)

**Comment by anthonyabeo** [comment]
> @anthonyabeo I started on an JSON-style interface here #1051.
> 
> My plan is to have an architecture where we have your `client.ts` and `server.ts` and then `server.ts` should be extended to:
> 
>     1. Start the Flix compiler with the `--lsp` flag and a port.
> 
>     2. To connect to this port (using the websocket protocol).
> 
>     3. To translate LSP requests (e.g. onHover) into requests to the server (in JSON).
> 
>     4. To translate the response from the server (a JSON object) into an appropriate LSP response.
> 
> 
> What do you think?
> 
> While I hack on the JSON api, the next steps on your end would be to figure out how to do the following:
> 
>     1. Start the Flix compiler from `server.ts`.
> 
>     2. Send a JSON request that contains all the files to be compiled (not sure how this works, but the Flix compiler obviously needs the path to the files).
> 
>     3. Send a JSON request to ask for e.g. the type of an expression at given line and col.

@magnus-madsen I think the architecture is sound, and we can work with that. 

For point (2), a document from the server.ts point of view is not necessarily the file, but the string text in the file. Would that work with the current implementation of the compiler?

**Comment by magnus-madsen** [comment]
> For point (2), a document from the server.ts point of view is not necessarily the file, but the string text in the file. Would that work with the current implementation of the compiler?

Not sure. The compiler needs to entire project to compile anything. I would try to ask the API to give all files in the project somehow.

**Comment by anthonyabeo** [comment]
> I merged in #1051. A pre-built JAR is available here:
> https://flix.dev/release/flix-v0.12-pre.jar
> 
> You start Flix with:
> 
> ```
> java -jar flix.jar --lsp 8000
> ```
> 
> and then you can connect to that port and issue commands.
> 
> The currently supported commands can be seen here:
> 
> https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala#L44
> 
> Hopefully this should be enough to get started on a better plugin for VSCode.
> 
> We will refine the available commands as we learn more about how everything fits together.



> > For point (2), a document from the server.ts point of view is not necessarily the file, but the string text in the file. Would that work with the current implementation of the compiler?
> 
> Not sure. The compiler needs the entire project to compile anything. I would try to ask the API to give all files in the project somehow.

ok. I'm sure we can make it work. 

I started playing around with the compiler. It looks really cool. I'll try it out some more to get a better understanding.

**Comment by anthonyabeo** [comment]
Hi @magnus-madsen , 

I pushed some changes, specifically, the onHover functionality. It is a bit wonky at the moment but will work to make it better. I am having the learn TypeScript alongside the LSP so I am unable to move as fast as i'd like.

Kindly try it out and send feedback.

**Comment by magnus-madsen** [comment]
Cool! I guess I need some instructions because I get the message:

Error: Unable to a ccess jarfile ../flix-v0.12-pre.jar

but I do see it in the server folder. Maybe there is path problem?

**Comment by magnus-madsen** [comment]
OK; I overcome the first path problem by setting it explicitly in the source code, but now I get stuff like:

```
Error while reading from remote connection: java.nio.file.NoSuchFileException: \c%3A\Work\GitHub\misc\foo\test.flix
```

Is there maybe a library we can use to ensure that we handle paths correctly on all platforms?

**Comment by anthonyabeo** [comment]
I have made some changes using the library `file-uri-to-path` to convert the URI to paths. Try it out and let me know how it goes. Plus I moved the `flix-v0.12-pre.jar` to the `out` directory.

**Comment by magnus-madsen** [comment]
Error: 
Unable to access jarfile c:\Work\GitHub\misc\flix-vscode-extension\server\out\flix-v0.12-pre.jar

**Comment by magnus-madsen** [comment]
The path exists but does not contain the jar.

**Comment by magnus-madsen** [comment]
After moving the Jar there manually, I get:

```
[2020-04-25 16:05:47] [/127.0.0.1:58418]: Adding path: '\%3A\ork\itHub\iscoo	est.flix'.
```

**Comment by anthonyabeo** [comment]
Ok. Hovering over some items shows the type while some shows `undefined`.

**Comment by magnus-madsen** [comment]
I uploaded a new JAR of `https://flix.dev/release/flix-v0.12-pre.jar`.

It does not fix the path issues in the VS server, but it does make internal handling of paths more consistent. 

With some hacks, I was able to get VSCode to show:

![image](https://user-images.githubusercontent.com/2287953/80288614-45134d80-8739-11ea-83d8-352f6dc6afaa.png)

But I think there are some issues with the lifecycle/workflow in the server. I guess its still a work in progress :) I get errors about too many event registrations and some times I see stale data.

**Comment by anthonyabeo** [comment]
Cool. Glad we could make progress on this.

I am not very comfortable with JS events lifecycle with all the callbacks and async programming at the moment. As you mentioned, that is the main issue with the server currently. 

Should I work on cleaning that up next or implementing the goto Definition capability?

**Comment by magnus-madsen** [comment]
I think we should get the bugs sorted out first: the paths and event cycles.

**Comment by magnus-madsen** [comment]
PS: You should only call the "compile" target when the program changes, not every time the client hovers on something.

**Comment by anthonyabeo** [comment]
I have pushed some changes. The "compile" target is called only when the file is opened or is modified.

**Comment by magnus-madsen** [comment]
This is now being managed in https://github.com/flix/vscode-flix.
