### ISSUE TITLE
Remove support for `##` fully-qualified Java names

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#8087]

**Comment by magnus-madsen** [comment]
I started on a PR here: https://github.com/flix/flix/pull/8088

**Comment by magnus-madsen** [comment]
@jaschdoc You are also welcome to take a look at this.

The goal is to ensure that we never use ##, but instead import everything that is needed.

**Comment by jaschdoc** [comment]
Do you want me to remove `##` imports from the std lib or remove support for it in the compiler?

**Comment by magnus-madsen** [comment]
> Do you want me to remove `##` imports from the std lib or remove support for it in the compiler?

1. Refactor the standard library and tests
2. Remove support for ##

The latter may require changes to the community.

We may also discover that we are not fully ready to get rid of ##.
