### ISSUE TITLE
CI IDE Tests seem to fail

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#8101]
See e.g. https://github.com/flix/flix/pull/8097

(Disabled the workflow for now)

**Comment by sockmaster27** [comment]
It runs fine locally, so I suspect that it fell out of sync with the compiler.
Could you try reactivating it and seeing what happens?

**Comment by magnus-madsen** [comment]
I have re-enabled it. Let us see what happens.

**Comment by magnus-madsen** [comment]
Seems to work 👍 Nice 🚀
