### ISSUE TITLE
All type errors should mention their types

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#8104]
Over/underapplied function errors become annoying since they don't include their type

**Comment by magnus-madsen** [comment]
@JonathanStarup Can you give an example, so a student programmer can work on it?

**Comment by JonathanStarup** [comment]
example bad error (weird program but still bad)
```
def example(y: Int32): Int32 = (_x -> y) + _x -> y
```

**Comment by JonathanStarup** [comment]
mostly fixed by #8452
