### ISSUE TITLE
Add `Box` trait

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#8155]
Add a new trait `Box`. Here is some code to get started:

```scala
// Add copyright header
import java.lang.Integer

///
/// A trait for primitive types that can be boxed and unboxed.
///
trait Box[a] {
    type Boxed
    
    ///
    /// Returns the boxed representation of the given `x`.
    ///
    pub def box(x: a): Box.Boxed[a]
    
    ///
    /// Returns the unboxed representation of the given `x`.
    ///
    pub def unbox(x: Box.Boxed[a]): a
}

// Add all instances, please keep them in the same order as in e.g. Eq

instance Box[Int32] {
    type Boxed = Integer
    pub def box(x: Int32): Integer = unsafe Integer.valueOf(x)
    pub def unbox(x: Integer): Int32 = unsafe x.intValue()
}


```

(None of this should be confused with Boxed and Boxable which are used by the Datalog engine and will be moved into that namespace eventually.)

**Comment by JonathanStarup** [comment]
What is the abstraction useful for? couldn't it just be functions in the Box namespace, e.g. `Box.integer(x: Int32): Integer`

**Comment by magnus-madsen** [comment]
> What is the abstraction useful for? couldn't it just be functions in the Box namespace, e.g. `Box.integer(x: Int32): Integer`

Not much, but it means you don't have to think.

**Comment by magnus-madsen** [comment]
Fixed in master.
