### ISSUE TITLE
Introduce `redef` keyword

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#8268]
- [x] Introduce `redef` keyword as a short hand for `override def`.
- [x] Refactor the standard library and tests to use `redef`.
- [x] Remove support for `override`. (Or better put it behind `--Xdeprecated` flag)
- [x] Update the KeywordOtherCompleter (new in, old out)
- [x] Update VSCode keywords (new in, old out)
- [x] Update Highlight.js keywords (new in, old out)
- [x] Update doc.flix.dev
- [x] Update flix.dev

Note: This should not concern visibility, so this changes nothing w.r.t. `pub`.

**Comment by magnus-madsen** [comment]
@jaschdoc Next I would drop the requirement that declarations in instances must be public. 

Then you can refactor instances to use `redef`.

**Comment by magnus-madsen** [comment]
What do you mean? I suppose what I was trying to communicate is that first changing everything to use redef, and then changing everything to drop pub seems like double work. Might as well do it in one pass.

**Comment by jaschdoc** [comment]
Should I also remove the `pub` constraint in the trait declaration?

**Comment by magnus-madsen** [comment]
What do you mean?  I am only asking for changes to instances at this time.

**Comment by jaschdoc** [comment]
Alright. In Rust the `pub` keyword is unused on trait declarations because it defines an interface where all members are public. I though that it would be relevant to this. I will, however, only rework the instances for now.

**Comment by jaschdoc** [comment]
But do we allow private functions on a trait declaration?

**Comment by magnus-madsen** [comment]
> But do we allow private functions on a trait declaration?

We have not decided. But it could make sense.

**Comment by jaschdoc** [comment]
- [ ] Introduce redef keyword as a short hand for override def.
- [ ] Refactor the standard library and tests to use redef.
- [ ] Remove support for override. (Or better put it behind --Xdeprecated flag)
- [ ] Deprecate `pub` keyword
- [ ] Update the KeywordOtherCompleter (new in, old out)
- [ ] Update VSCode keywords (new in, old out)
- [ ] Update Highlight.js keywords (new in, old out)
- [ ] Update doc.flix.dev
- [ ] Update flix.dev

**Comment by magnus-madsen** [comment]
I think we just need to get rid of the pub in `pub redef` for instances.

**Comment by jaschdoc** [comment]
I think we can close this now
