### ISSUE TITLE
Enable Scala Optimizer?

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#8271]
https://docs.scala-lang.org/overviews/compiler-options/optimizer.html

The scala optimizer is not enabled by default - should we / could we enable it?

**Comment by magnus-madsen** [comment]
Try to see if it improves performance

**Comment by magnus-madsen** [comment]
E.g. for XPerf --frontend --n 21

**Comment by magnus-madsen** [comment]
```
Xperf --frontend --n 51 @ Intel

-opt:default: 
  min: 98,018, max: 128,655, avg: 114,607, median: 112,482

-opt:local: 
  min: 103,269, max: 132,748, avg: 119,127, median: 117,365
  average increase: 1.04x

-opt:inline:ca.uwaterloo.**
  min: 97,566, max: 140,188, avg: 124,510, median: 126,459
  average increase: 1.09x
```

**Comment by magnus-madsen** [comment]
It is not nothing, but it also not a lot. Is it worth it?

I suppose we could try to insert some inline annotations manually.

**Comment by JonathanStarup** [comment]
Yeah i wanted to use @inline but saw that it doesnt to anything by default.

they also say that it primarily fixes megamorphic call sites and the jvm handles the rest, so maybe it doesnt even matter in my case

**Comment by JonathanStarup** [comment]
but i guess 9% for free is nice
