### ISSUE TITLE
Add Additional Array Operations to the Standard Library

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#828]
Add support for additional array operations:

```
- append (concatenates two arrays)
- reverse (reverses the order of elements)
- shuffle (randomizes the order of elements)
- dimensions (functions for construction of higher-dimensional arrays)
- fold, map, flatMap, and friends from List.
```

**Comment by stephentetley** [comment]
I'm looking at this along with the String operations #832.

Work so far is here:

https://github.com/stephentetley/flix-doodle/tree/master/stdlib

**Comment by magnus-madsen** [comment]
Let me know if you desire some feedback at some point.

**Comment by stephentetley** [comment]
Thanks Magnus 

I'm a bit busy for the next three weeks so I might not get much done. I should be picking it back up after that.

One thing that did occur tonight in the String functions although I imagine it is going to crop up elsewhere is it's idiomatic in Java to use -1 to indicate failure for a function that would return a positive Int on success (in this case String.indexOf).

In Flix would it be preferable to return Option[Int] with None for failure instead?

**Comment by magnus-madsen** [comment]
I think it is more appropriate to return an Option. You can look at how e.g. list is implemented to see when we use Options:

https://flix.dev/api/#/List

**Comment by stephentetley** [comment]
What is the plan for testing for equality of Arrays?

At present the tests I'm writing convert the array to a list and compare lists which is workable, but it would be nice to test the arrays directly.

**Comment by magnus-madsen** [comment]
We don't have a good short term plan.

The long term plan is to add type classes and then have an Eq type class that controls equality.

Now, that still leaves the question of when are two arrays equal? I am thinking that either they are equal when they have the same reference in memory or alternatively, we should simply not support equality on arrays!

That said, we can have a function `sameElements` that takes two arrays and determines if their *elements* are the same.

Thoughts?

**Comment by stephentetley** [comment]
Thanks Magnus. I can certainly implement `sameElements` and use that in the short term.

Unthinkingly I'm used to structural equality as the default (Haskell and F#), looking now I see that Scala has reference equality as the default.

The "pro" of structural equality is with it, you can use arrays as the key of Map-like things (you might also need ordering as per Haskell, but there isn't a big leap to structural ordering from structural equality). However, there might be a good argument that arrays should never be keys for a Map.

**Comment by stephentetley** [comment]
Also, I think (untested...) that structural equality would work natural on Arrays of Arrays, `sameElements` doesn't.

**Comment by magnus-madsen** [comment]
I think the issue with array equality is that people might expect different things: a functional programmer would probably expect two arrays to be equal when their elements are whereas an imperative programmer might expect to arrays to be equal if they share the same location in memory. Since we cannot "satisfy both", it might be better to simply not define any notion of equality on arrays (once we have type classes). Meanwhile, we should then stick with `sameElements`.

As for arrays of arrays, the `sameElements` function would require that the array type `a` implements `Eq[a]` hence it would only be possible to ask for `sameElements` on arrays that support equality of its elements. Since arrays by default, per the above, does not support equality, the `sameElements` function would simply not work on an array of arrays. Thus we would avoid any ambiguity. (In meantime, before we get type classes, I think we should just implement `sameElements` and only use it for arrays of non-arrays.

In general, we might want to consider whether the following is a good principle (see the list of other principles on website):

- For immutable data types, such as bool, int, option, result, list, sets and maps we provide a default implementation of equals that checks whether the elements are the same.
- For mutable data types, such as arrays, mutable lists, mutable sets, string buffers, etc. etc. we do not provide any built-in notion of equality.

(With type classes, the programmer is of course able to provide such instances himself, if desired).

**Comment by stephentetley** [comment]
Hi Magnus - do you want me to "update" the existing tests for Array and String (#832) while I'm preparing the pull requests?

By "update" I mean eliminating the `assert!` functions and add the block title comment for the function being tested.

**Comment by magnus-madsen** [comment]
> 
> 
> Hi Magnus - do you want me to "update" the existing tests for Array and String (#832) while I'm preparing the pull requests?
> 
> By "update" I mean eliminating the `assert!` functions and add the block title comment for the function being tested.

Yes, that would be excellent :)

**Comment by stephentetley** [comment]
What should the result be of imperative actions on an array?

Currently we have `put` that returns the modified array: 

~~~

put(a: Array[a], i: Int, x: a): Array[a]

~~~

Obviously, because the array has been mutated, whatever bound the array in the first place will also see the mutated array:

~~~

pub def put01(): Bool = 
    let a = ['a','b','c'];
    let _ = Array.put(a, 2, 'C');
    Array.memberOf('C', a)  // true

pub def put02(): Bool = 
    let a = ['a','b','c'];
    Array.put(a, 2, 'C');
    Array.memberOf('C', a)  // true

pub def put03(): Bool = 
    let a = ['a','b','c'];
    let b = Array.put(a, 2, 'C');
    Array.memberOf('C', a) && Array.memberOf('C', b) // true

~~~

Are there advantages to returning Unit instead...

~~~

put(a: Array[a], i: Int, x: a): Unit

~~~

`put02` shows we can ignore the result of `standard-put` without binding it, so `put-returning-Unit` isn't an advantage there, but maybe it is nice to limit aliases to the same array and potentially the signature of `put-returning-Unit` is more obviously imperative?

As it happens, I hadn't thought if this until now (I've only implemented two imperative functions so far - `mapInPlace` and `replaceInPlace`) but it would be nice to have a convention.

Thanks.

**Comment by magnus-madsen** [comment]
I think you are absolutely right. It makes no sense for put to return the array. I think it should just return unit.

**Comment by stephentetley** [comment]
Thanks Magnus. Ironically returning `Unit` has made the `put` tests longer but overall I think it's preferable.

Are there plans to make Uniform Function Call Syntax work with modules?

I'm wondering if the imperative functions should have argument ordering that allows UFCS. `put` already has, but the ones I've written don't at present.

**Comment by magnus-madsen** [comment]
> Are there plans to make Uniform Function Call Syntax work with modules?

I am not sure I follow? UFCS works with function calls.

> I'm wondering if the imperative functions should have argument ordering that allows UFCS. put already has, but the ones I've written don't at present.

Ah yes. Maybe this is related to #605. In general there is some "tension" between argument order that works for pipelining and UFCS.

**Comment by magnus-madsen** [comment]
By the way, you might want to take a look at #957 since this is going to impact arrays.

**Comment by stephentetley** [comment]
Thanks, I was really meaning qualified names rather than "modules", e.g so you can do:

~~~

a.Array.reverseInPlace()

~~~

The possibly better alternative would be to "open" namespaces so you could use unqualified names.

**Comment by magnus-madsen** [comment]
We plan to have a "use" mechanism so that you can write:

```
use Array.reverseInPlace;

def foo(): Unit = 
  reverseInPlace(...)
```

and

```
def foo(): Unit = 
  use Array.reverseInPlace;
  reverseInPlace(...)
```

depending on preference.

**Comment by stephentetley** [comment]
Thanks Magnus - with namespace imports I wonder if argument order can be resolved when the functions are imported?

i.e Allow functions defined for composition (with the 'subject' the last argument) to be imported with their arguments rotated right by 1, or functions defined for UFCS (with the 'subject' first) to be rotated left by 1 so the subject is last.

In the short term, for Array I'm going to follow the example of List and even the imperative functions can follow the argument order of their functional versions.

A cosmetic issue - are you happy with the `*InPlace` suffix as used in Scala for imperative functions for Flix?

Also `List.toMap` (and the copy I've written for Array) use `foldRight` to build the map, should they use `foldLeft` instead?

If you have duplicate keys in the input, using `foldRight` means the first definition gets used. If I wasn't aware of the implementation I would expect the later definitions to override earlier ones. The List test `toMap04` shows the current behavior

~~~

@test
def toMap04(): Bool = assert!(List.toMap((1, true) :: (1, false) :: Nil) == Map#{1 -> true})

~~~

**Comment by magnus-madsen** [comment]
> Thanks Magnus - with namespace imports I wonder if argument order can be resolved when the functions are imported?

This is an interesting idea. I will try to think about it.

> In the short term, for Array I'm going to follow the example of List and even the imperative functions can follow the argument order of their functional versions.

OK, consistency is good. But of course then you can't write `a.foreach`. Hmm. We should try to come up with something, but I don't know what.

> A cosmetic issue - are you happy with the *InPlace suffix as used in Scala for imperative functions for Flix?

Do you have any examples? 

> If you have duplicate keys in the input, using foldRight means the first definition gets used. 

I think this is a good argument that foldRight is the right thing to do! You are welcome to change it for list.

**Comment by stephentetley** [comment]
Hi Magnus

The effects system looks great and the annotation burden isn't too high, but is there a way override impurity? 

For instance, `get` is naturally impure as it may cause an out-of-bounds error...

~~~

pub def get(a: Array[a], i: Int): a @ Impure = a[i]

~~~

But I would expect the signature of `tryGet` to be pure. Obviously the implementation would need some annotation where it calls `a[i]`

~~~

pub def tryGet(a: Array[a], i: Int): Option[a] @ Pure =
    if (i >= 0 || i < length(a))
        Some(a[i])
    else
        None

~~~

Thanks

**Comment by magnus-madsen** [comment]
Yes. The correct way to do this is to tell the type system that an operation is safe by using a cast.

The syntax is: 

```
exp as Type @ Impure
```

E.g.

```
a[0] as Int @ Pure
```

**Comment by stephentetley** [comment]
Thanks Magnus, I've annotated the library functions so now I'm onto the tests...

Are array literals Impure? And if so, should they be Pure?

**Comment by magnus-madsen** [comment]
It is a thorny issue. The problem is that allocating a new array is not referentially transparent:

```
let x = [1, 2, 3];
(x, x)
```

is not equivalent to:

```
([1, 2, 3], [1, 2, 3])
```

Since the two array addresses will have different addresses and so the two pieces of code could be distinguished. This could be "fixed" by disallowing equality by identity, but I don't think we want to do that either. Thus, at the moment, we have a very broad definition of what is pure. We can then potentially lessen it in the future.

**Comment by stephentetley** [comment]
Thanks Magnus - I can certainly manage with the current behaviour.

Is Alloc going to be an effect itself at some point? I think it is in Daan Leijen's Koka language.

**Comment by magnus-madsen** [comment]
> Is Alloc going to be an effect itself at some point? I think it is in Daan Leijen's Koka language.

What do you mean by alloc? 

I think that constructs that allocate values where the pointer is "visible" (through equality) should have an effect. Thus, allocating an array has an effect. But allocating `Some(42)` does not.

Fortunately, we can always change these requirements to suit our purposes :)

**Comment by stephentetley** [comment]
From the Daan's papers (I don't really know the Koka language, although the libraries look very well thought out...), Koka has several effects especially `exn` (thowing exceptions), `io` (as per Haskell's IO monad) and `alloc<h>` (with `read<h>` and `write<h>`) for accessing heap memory. I think `alloc<h>`, `read<h>` and `write<h>` can all be "run" like Haskell's ST monad so an externally pure function can use mutable data within itself as long references to the mutable data don't leak.

**Comment by magnus-madsen** [comment]
It is a long-term goal to look into algebraic effects (like those in Koka). When that day arrives, we will need a more powerful effect system. Or rather, we will need to augment the existing effect system with different notions of effects.

**Comment by magnus-madsen** [comment]
FYI: I made final edits to the effect system and merged it into master. I ended up with light adjustments to the syntax, as these example demonstrates:

```scala
def printLine(s: String): Unit & Impure = Console/StdOut.printLine(s)

def map(f: a -> b & e, xs: List[a]): List[b] & e = match xs {
        case Nil => Nil
        case x :: rs => f(x) :: map(f, rs)
    }

pub def >>(f: a -> b & e1, g: b -> c & e2): a -> c & {e1, e2} = x -> g(f(x))
```

I do not expect further changes to the syntax. I hope the refactor will not be too hard :)

**Comment by stephentetley** [comment]
Thanks Magnus, the new syntax looks nice and I prefer '&' rather than '@' as it is distinct from the annotation mark. I've been busy working on 'factimport' but I'll try to get back to work on the Array operations this week.

**Comment by stephentetley** [comment]
Hi Magnus, I'm about ready to make a pull request. There are some API issues to sort out before though, firstly:

For the find functions (`find`, `findLeft`, `findRight`, `findIndexOf`, ...) I'm returning an `Option` with `None` for failure and `Some(i)` where i is positive for success. I think we agreed up-thread that this was the nicer way to do things but List is currently still using (-1) for failure for similar functions.

Shall I continue to return `Option` and List can be updated at some point?


Thanks - I've probably got 5 or so more queries - do you want a list or shall we do them one at once?

**Comment by magnus-madsen** [comment]
> For the find functions (find, findLeft, findRight, findIndexOf, ...) I'm returning an Option with None for failure and Some(i) where i is positive for success. I think we agreed up-thread that this was the nicer way to do things but List is currently still using (-1) for failure for similar functions.

Yes, I think we should go the functional way. List operations that return -1 should then be patched in the future.

> Thanks - I've probably got 5 or so more queries - do you want a list or shall we do them one at once?

I think you should just list all of them :)

**Comment by magnus-madsen** [comment]
I guess the find operations on `List` do return Option. It just that `indexOf` for some reason does not.

**Comment by stephentetley** [comment]
Thanks Magnus, right...

1. Is `mkStringBy` a good enough name? This is for the "array-to-string" function. It's the same name Scala uses with the By suffix added as we need to supply the helper function, but I haven't seen other functions in Flix use abbreviations like "mk" for "make".

2. `findIndices` and `indices` return lists, should they return arrays?
The rationale from them returning lists is that the length is unknown during construction and converting to an array is extra work at the end, but `filter` already does this.

   I think I'm moving towards them returning arrays for consistency.

3. `foreachAccum` - a version of foreach with an accumulator.
Should this be called `foreachWithAccum` for consistency with the `__WithIndex` functions?

I think the other issues are actually code style ones, so probably they will be easier to go over in the pull request.

**Comment by magnus-madsen** [comment]
All good questions. I do not know if I can provide good answers :) 

We may have to use our best judgement. 

>     1. Is `mkStringBy` a good enough name? 

For `List`, we use `intersperse`, but this is a more general function for inserting an element between elements. I think we need a good name for a function that converts elements to strings and inserts a string as a separator. Maybe `mkStringBy` is that name? We don't have any other `mk` functions though. Brainstorming: `showWith`, `showAndIntersperseWith`? Ugh, those are worse. `separatedBy` perhaps? 

>     2. `findIndices` and `indices` return lists, should they return arrays?
>        The rationale from them returning lists is that the length is unknown during construction and converting to an array is extra work at the end, but `filter` already does this.
>        I think I'm moving towards them returning arrays for consistency.

I have this problem numerous times for other data types! I think there should be some principle that says if you are working with List, Sets, Maps, Arrays then operations on those should try to return collections of the same type. But obviously this is not always the case, see e.g. `Map.valuesOf`.

> 
>     3. `foreachAccum` - a version of foreach with an accumulator.
>        Should this be called `foreachWithAccum` for consistency with the `__WithIndex` functions?
> 

Good question. I don't particularly like the `Accum` short-hand. What is the signature of this function? 

As a general comment, we have tried to use common names from Scala, Haskell, OCaml whenever possible. We should continue to do so. We can also looks a library such as lodash from JS to see if they have good names.

**Comment by magnus-madsen** [comment]
We should also try to align the relevant names and functions for arrays with those of mutable sets and maps, see e.e.g. https://github.com/flix/flix/blob/master/main/src/library/MutSet.flix#L83

**Comment by stephentetley** [comment]
1. `mkStringBy`

Haskell has a `showListWith` that is similar, but it fixes the output to conform to Haskell's array syntax:

~~~

showListWith :: (a -> ShowS) -> [a] -> ShowS

Show a list (using square brackets and commas), given a function for showing elements.

~~~

Interestingly Haskell's convention is usually to suffix with `By` if you are passing in a worker function rather than `With`.

Maybe "format" is a word we could use. With something like "toString" or "show" there's potentially an expectation to have the output as valid Flix, "format" seems a bit looser.

How about `formatBy` or possibly `formatSepBy`?


2. `findIndices` and `indices`

I'll change to return arrays. I'm not sure saving the final step of converting the intermediate list is worth it.

3. `foreachAccum`

~~~

///
/// Apply the effectful function `f` to all the elements in the array `a`.
///
pub def foreachAccum(f: (a, st) ~> st, s: st, a: Array[a]): st & Impure =
    foreachAccumHelper(f, a, length(a), s, 0)

~~~

Maybe `foreachWithState`? 
The function it derives from is Haskell's `mapAccumL`. 

I've just noticed the comment needs improving as I copied the text from `foreach`.

**Comment by magnus-madsen** [comment]
> Interestingly Haskell's convention is usually to suffix with `By` if you are passing in a worker function rather than `With`.

How does that compare with e.g. `Data.Map`'s use of `with`? https://hackage.haskell.org/package/containers-0.6.2.1/docs/Data-Map.html

When to use `By` and when to use `With`?

> How about `formatBy` or possibly `formatSepBy`?

Yes, maybe `formatBy` or `separatedBy`. 

> Maybe `foreachWithState`?
> The function it derives from is Haskell's `mapAccumL`.

I like both. If Haskell is already using `Accum` as a word, I think we could do that too.

**Comment by stephentetley** [comment]
Ah, it looks like Haskell uses both `With` and `By` depending on the module (I was looking at `Data.List`). In `Data.List` there is `zipWith` and the rest use `By` - but the docs note that `By` is a convention when generalizing an existing function, so it looks like `With` is more "neutral". For Flix as we don't have `format` function maybe `formatWith` is better.

I prefer "format_" as a stem over "separated_" as "format" seems more suggestive of a `String` result. I'll go with `formatWith` for now, it can always be changed in the pull request.

I'll continue with `foreachAccum` - it's shorter if we ever want, say, `foreachAccumWithIndex`.

**Comment by stephentetley** [comment]
Hi Magnus, I'm a bit lost trying to squash the commits in my fork - the comments won't be relevant to the master repository. 

Is it a pain to make the pull request without squashing my branch? I know some repositories like commits to be squashed.

Thanks

**Comment by magnus-madsen** [comment]
> 
> 
> Hi Magnus, I'm a bit lost trying to squash the commits in my fork - the comments won't be relevant to the master repository.
> 
> Is it a pain to make the pull request without squashing my branch? I know some repositories like commits to be squashed.
> 
> Thanks

No problem. I can just squash them when I merge them into master.

**Comment by stephentetley** [comment]
A lot of the usual higher order functions (filter, folds, etc.) plus a sort were added with pull request #1032.

**Comment by magnus-madsen** [comment]
Hi Stephen. 

I am thinking of closing this ticket and then opening new tickets for additional features. Would that be okay?

**Comment by stephentetley** [comment]
Yes that's fine.
