### ISSUE TITLE
Extend the `Safety` phase to check the security context for all dangerous operations

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#8316]
In the `Safety` phase, guard sensitive operations. They are:

- [ ] UncheckedCast
- [ ] UncheckedMaskingCast
- [ ] Throw
- [ ] InvokeMethod
- [ ] InvokeStaticMethod
- [ ] GetField
- [ ] PutField
- [ ] GetStaticField
- [ ] PutStaticField
- [ ] NewObject (?)

InvokeConstructor is already implemented and can be used as a template.

**Comment by AStenbaek** [comment]
If I understand correctly: `TryCatch` actually allows constructing an object does it not? If so we should consider how we avoid creation of forbidden objects via this.

**Comment by magnus-madsen** [comment]
> If I understand correctly: `TryCatch` actually allows constructing an object does it not? If so we should consider how we avoid creation of forbidden objects via this.

Does it? Do you have an example?

**Comment by AStenbaek** [comment]
This is solely based on what I saw here:
```scala
      case Expr.TryCatch(exp, rules, _, _, loc) =>
        val nestedTryCatchError = if (inTryCatch) List(IllegalNestedTryCatch(loc)) else Nil
        nestedTryCatchError ++ visit(exp)(inTryCatch = true) ++
          rules.flatMap { case CatchRule(sym, clazz, e) => checkCatchClass(clazz, sym.loc) ++ visit(e) }
```

I will see if I can cook something up.

**Comment by AStenbaek** [comment]
I have added rudimentary checks as discussed. Except for `TryCatch`, I agree on the "dangerous" cases.
