### ISSUE TITLE
Add String Operations to the Standard Library

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#832]
We should consider whether to add functions such as:

- indent
- isBlank
- indexOf
- lastIndexOf
- lines
- repeat
- replace
- split
- trim
- padEnd
- padStart
- stripLineEnd
- linesWithSeparators
- capitalize
- stripPrefix
- stripSuffix
- isAscii
- trimEnd
- trimStart
- truncate
- truncateWith
- words

And operations from List.flix.

Additional operations from:

https://commons.apache.org/proper/commons-lang/javadocs/api-release/org/apache/commons/lang3/StringUtils.html

```
- abbreviate
- abbreviateMiddle
- center
- etc
```

**Comment by stephentetley** [comment]
I've made a start on this here:

https://github.com/stephentetley/flix-doodle/tree/master/stdlib


The functions are in new modules (String2 and Array2) so I can develop them with the interpreter, at some point I will move them onto a fork of the standard library.

**Comment by magnus-madsen** [comment]
Cool!

**Comment by magnus-madsen** [comment]
The interop support is probably a bit wonky. We hope to fix that in the future. Let me know if you run into problems.

**Comment by stephentetley** [comment]
Thanks Magnus. 

Currently can you only call overloaded native functions if they have unique arities?

If I try to wrap java.lang.String.replace, e.g. with this:

~~~

pub def replace(oldChar: Char, newChar: Char, s: Str): Str =
    native method java.lang.String.replace(s: Str, oldChar: Char, newChar: Char) as Str

~~~

I get this error:

~~~

<[34m-- Name Error -------------------------------------------------- flix-doodle\stdlib\String2.flix
<[0m
>> Ambiguous method '<[31mreplace<[0m' in class '<[36mjava.lang.String<[0m' with expected arity 3.

110 |         native method java.lang.String.replace(s: Str, oldChar: Char, newChar: Char) as Str
                            <[31m^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<[0m
                            ambiguous method.
                            

~~~

Java's replace has two arity 3 implementations (counting the receiver as 1 argument):

~~~

String	replace(char oldChar, char newChar)	

String	replace(CharSequence target, CharSequence replacement)

~~~

**Comment by magnus-madsen** [comment]
The support for calling overloaded methods is a bit lacking. Using type ascriptions (e.g. oldChar: Char), as you do, usually helps, but not always. I wonder if in this case there is some erasure going on.

The implementation is here:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Namer.scala#L1400

If you want to take a look.

In the future we want to have an import mechanism where you can specify a complete JVM signature and have it imported under a local name, but unfortunately no-one is working on that at the moment.

**Comment by magnus-madsen** [comment]
On second thought, can you try the ascription:

```
pub def replace(oldChar: Char, newChar: Char, s: Str): Str =
    native method java.lang.String.replace(s: Str, oldChar: ##java.lang.Character, newChar: ##java.lang.Character) as Str
```
?

**Comment by stephentetley** [comment]
Thanks Magnus. 

Unfortunately using ##java.lang.Character as a type tag doesn't work:

~~~

    pub def replace(oldChar: Char, newChar: Char, s: Str): Str =
        native method java.lang.String.replace(s: Str, oldChar: ##java.lang.Character, newChar: ##java.lang.Character) as Str
        
~~~        
   
Error message:
   
~~~
        
<-[34m-- Name Error -------------------------------------------------- E:\coding\flix\flix-doodle\stdlib\Replace.flix
<-[0m
>> Undefined method '<-[31mreplac<-[0m' in class '<-[36mjava.lang.String<-[0m' with expected arity 3.

6 |         native method java.lang.String.replace(s: Str, oldChar: ##java.lang.Character, newChar: ##java.lang.Character) as Str
                          <-[31m^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<-[0m
                          undefined method.

~~~

I'll investigate what's happening in lookupNativeMethod...

**Comment by stephentetley** [comment]
Hi Magnus - I'm back working on this and Array Operations #828. My fork is here:

https://github.com/stephentetley/flix

Unrelated to the standard library, but please could you bump the Scala version numbers in `build.gradle` to: 

```

    implementation 'org.scala-lang:scala-library:2.13.1'
    implementation 'org.scala-lang:scala-reflect:2.13.1'

```

2.13.0 has a bug on Windows due to PostfixOps stopping Flix from compiling.

Also to get Flix interactive working in Intellij I've had to add this to `build.grade` :

```

run {
    standardInput = System.in
}

```

Thanks

**Comment by magnus-madsen** [comment]
I have done so in #922. I hope I added the `standardInput` in the right place. Otherwise, let me know.

**Comment by magnus-madsen** [comment]
Looking at it, I am not really sure where the `standardInput` option is supposed to go. Intellij was telling me that the `run` block is illegal at the top-level?

I build flix with Intellij idea myself, so I actually only use the gradle script for the build server.

Anyway, let me know if it works / doesn't work.

**Comment by stephentetley** [comment]
Thanks Magnus. 

I haven't seen Intellij complaining about `run` at the top-level. 

Maybe my "sandbox" is a bit messed up. Previously I was running Flix in Intellij following the instructions in `doc/BUILD.md` but with the current sandbox Intellij seemed to do a Gradle import of the project directly (I couldn't mark `main/src` and `main/test` as *source* or *test* ...). Changing the Scala version plus adding the `run` block at the top level in `build.Gradle` meant I could build and run interactive and `testAll` from the Gradle panel.

With `standardInput` only defined in the `task testAll` I can't run interactive - it builds but terminates immediately as it is not waiting for stdin.

I know very little about Gradle (my background is Haskell/ F#), but I was following this comment:

https://discuss.gradle.org/t/how-can-i-execute-a-java-application-that-asks-for-user-input/3264/2

**Comment by magnus-madsen** [comment]
OK, I can try to add the run block to the top-level. I will give that a go.

There is indeed a situation where Intellij asks to do an import, but the import does not seem to work correctly. That's a separate thing I should look into.

**Comment by stephentetley** [comment]
Hi Magnus

What type should the string function `matches` have?

Here is the straight-forward implementation:

```

    ///
    /// Returns `true` if the string `s` matches the `regex`.
    ///
    pub def matches(s: Str, regex: Str): Bool = native method java.lang.String.matches(s, regex) as Bool

```

If you supply an ill-formed regex then an exception is thrown:

```

flix> String.matches("ABCDE", "+")
String.matches("ABCDE", "+")Dangling meta character '+' near index 0
+
^java.util.regex.PatternSyntaxException: Dangling meta character '+' near index 0
+
^
        at java.base/java.util.regex.Pattern.error(Pattern.java:2015)
        ...

```

The options for the return value seem to be:

1. Bool + Exception
2. Option[Bool]
3. Result[Bool, Str]    - Str for error message or possibly some other type
4. Bool                 - use catch to trap the exception and return false

Personally I'm leaning towards 4. The drawback is you lose some information (whether or not the regex was valid) but as you obviously cannot match against a broken regex `false` is a valid answer. Possibly I'd rename the function to `isMatch` which then distinguishes that it is not a direct equivalent of the Java function.

What do you think?

Thanks.

**Comment by magnus-madsen** [comment]
This is a good question. I wonder how other programming languages deal with this issue?

I would prefer 4 too. Option 1 is not really an option, because Flix does not plan to have exceptions. Option 2 is not good, because it loses the error. So either Option 3 or 4 seems most appropriate. 

It seems that in some languages using a regex is a two step process: First you compile the regex (which could fail, e.g. by returning a Result) and then you can use it for matching. I guess that would be another way to "solve" the problem. Although it is also nice to have a  `matches` function directly on String.

**Comment by stephentetley** [comment]
Thanks Magnus, I'll go with 4.

**Comment by stephentetley** [comment]
Maybe it will be end up being a separate pull request, but I've also started to look at wrapping Java's StringBuilder so we can (hopefully) make Strings efficiently.

**Comment by stephentetley** [comment]
Hi Magnus

Is it easier for you to comment on / review a pull request or a branch?

Currently, I have a branch off Flix head with StringBuilder changes here (branch `string-builder`):

https://github.com/stephentetley/flix/tree/string-builder

There are three new modules plus I've added `lineSeparator` to `String.flix`.

The new modules are:

main/src/flix/runtime/library/MonoStringBuilder.java
main/src/library/StringBuilder.flix
main/test/ca/uwaterloo/flix/library/TestStringBuilder.flix

`MonoStringBuilder.java` wraps java.lang.StringBuilder an monomorphic methods to append to the string builder so the the Flix can avoid problems with calling overloaded Java methods.

Except `length` I've only considered append functions. The underlying Java string builder has methods for insert at and replace but I'm a bit dubious about these - my personal feeling is that a *String Builder* is a black box and you should know what you are putting into it rather than inspect its contents. Maybe there are reasons to know the length before you turn the String Builder into a String so I've included that one.

`StringBuilder.flix` is the Flix API. Between the Java version and the Flix API I return void / Unit for all 
append calls, the Java convention is to return the String Builder again but you have mutated it anyway.

I couldn't get a StringBuilder-StringBuilder `append` to work with the JVM (I was seeing "Bad Operand..." runtime errors however I tried to add annotations to the Flix types), so currently `append` converts the second StringBuilder to a string and appends the string. Hopefully this is not particularly inefficient.

`TestStringBuilder.flix` contains the tests.

I've added `lineSeparator` tests to `TestString.flix`. They are a bit abstract / obscure - escaped characters in Flix string literals didn't seem to work as I would expect them to, so I couldn't use string literals in the test.

There is a one line change to `main/src/ca/uwaterloo/flix/api/Flix.scala` to include StringBuilder in the libraries loaded by the Flix shell at startup.

Happy New Year!

**Comment by magnus-madsen** [comment]
Hello Stephen! Happy new years!

It is much easier to me to comment on a pull request. That way I can add comments to the code.

What is the role of the string builder? Is it to support certain operations in a faster way?

> I couldn't get a StringBuilder-StringBuilder append to work with the JVM (I was seeing "Bad Operand..." runtime errors however I tried to add annotations to the Flix types), so currently append converts the second StringBuilder to a string and appends the string. Hopefully this is not particularly inefficient.

Yeah, these errors are a plague, but we have a good solution planned, but no-one is working on it at the moment. For now, I think we try to make do, and then we get better interop, we will be able to cleanup the interop code.

If you make a PR I will be happy to look over the code.

**Comment by stephentetley** [comment]
String Builder should be more efficient than `+` when you are repeatedly concatenating strings.

A typical use in Flix would be `flatten`:

~~~

    ///
    /// Concatenate an array of strings into a single string.
    ///
    pub def flatten(xs: Array[Str]): Str =
        let sb = StringBuilder.new();
        Array.iter(s -> StringBuilder.appendStr(sb, s), xs);
        StringBuilder.toString(sb)

~~~

`iter` is the apply an effectful function to an array's elements function:

~~~

pub def iter(f: a -> Unit, xs: Array[a]): Unit = ...

~~~

In Java using `+` on strings does more copying that using a String Builder, but apparently nowadays compilers try to rewrite repeated uses of `+` in source code to use String Builder:

https://stackoverflow.com/questions/4645020/when-to-use-stringbuilder-in-java

...

Unrelated to String Builder, has the Java source for the primitives used by the Char module calls gone missing? As far as I can tell they only exist now in `flix-runtime.jar`.

**Comment by magnus-madsen** [comment]
> Unrelated to String Builder, has the Java source for the primitives used by the Char module calls gone missing? As far as I can tell they only exist now in flix-runtime.jar.

It is here:

https://github.com/flix/runtime/tree/master/src/main/java/flix/runtime/library

The idea was to maintain the the Flix runtime is a separate repo for the small separate Jar, but this has not been 100% followed at the moment.

**Comment by magnus-madsen** [comment]
Hello Stephen,

This PR, #936, which will be merged soon, adds support for string interpolation.

Just FYI.

(NB: You cannot use non-string variables in interpolations yet)

**Comment by stephentetley** [comment]
Thanks for the notice Magnus, I also saw issue #937 about string escapes, I had been wondering what their status was.

I haven't got very far with auditing the additions for strings and arrays prior to making pull requests, with being back at work after Christmas my time to look at them has been a bit disjointed. Positively I have got pretty printing and a parser combinator modules working as I've been working on these piecemeal. I've also made some progress with "fact loaders" for CSV and and SQLite.

**Comment by magnus-madsen** [comment]
> Thanks for the notice Magnus, I also saw issue #937 about string escapes, I had been wondering what their status was.

Still no support for string escapes, but if there is an urgent need I can probably add them fairly quickly.

> I've also made some progress with "fact loaders" for CSV and and SQLite.

Sounds interesting and useful!

**Comment by stephentetley** [comment]
Thanks Magnus, string escapes aren't especially pressing. 

For the Parser Combinators and Pretty Printer, it would be nice to have an interim solution for `toString` and `fromString` for the primitive types. Currently I work around this with a Java module that uses `String.ValueOf(...)` for `toString` and the respective static parse function for `fromString` and Flix wrappers over the java:

Java primitives:

~~~

public static String ValueOfByte(byte i) {
    return String.valueOf(i);
}

public static byte ReadByte(String s) throws Exception {
    return Byte.parseByte(s.trim());
}

// etc.

~~~

Flix wrappers:
~~~

pub def showInt8(i: Int8): Str = 
    native method flix.runtime.library.ReadShowWrapper.ValueOfByte(i) as Str

pub def readInt8(s: Str): Result[Int8, Str] = try {
    let i = native method flix.runtime.library.ReadShowWrapper.ReadByte(s) as Int8;
    Ok(i)
} catch {
    case _: ##java.lang.NumberFormatException => Err("readInt8")
}

// etc.

~~~

**Comment by magnus-madsen** [comment]
I think this is a reasonable solution for now. We could add the show/read methods to the Int8, etc. namespaces. 

Do you need the wrapper? Does it not work if you try to call the String.valueOf method directly? Similarly for the parse methods?

(Maybe there is a problem with overloading?)

**Comment by magnus-madsen** [comment]
By the way, there is also methods like `Integer.toString(i)` and `Integer.valueOf(s)`. Maybe these can be called directly because they are less overloaded.

**Comment by stephentetley** [comment]
Thanks Magnus

I've started a branch for `toString` and `fromString`. The conversion functions for the number types are done but I need to write the tests.

I went with `toString` rather than `valueOf` for the number-to-string conversions. Apparently `valueOf` is "safer" in Java in the presence of nulls (I believe if `valueOf` is invoked on a `null` it prints "null" whereas `toString` throws an exception), but I wouldn't imagine this is a scenario that will happen with Flix.

I did seem to need a Java wrapper for the `toString` functions but didn't need to wrap the `parseInt` family of functions. I suspect this is because there are both the `static` and "dot" method invocation versions of `toString` in Java which would look the same to Flix's `native` calls. 

Calling BigInteger's constructor with a string needed a Java wrapper.

**Comment by stephentetley** [comment]
Hi Magnus, should `lineSeparator()` be Pure or Impure?

It is different between OSes though it won't be different between program runs on the same machine.

For an analogue in Haskell, there is `pathSeparator :: Char` in System.FilePath which is pure but I'm not sure this is considered good practice anymore.

**Comment by magnus-madsen** [comment]
I think it should be pure because it returns the same value for every execution. (But indeed it differs for different OSes).

**Comment by stephentetley** [comment]
Thanks - I'm fine with that.

**Comment by stephentetley** [comment]
I'm pretty much ready to make a pull request for the bulk of this work, which adds about 80 functions to the String module.

I've also been working on a Regex module but this isn't ready yet (I split off the String functions onto a new branch this week so they could be make an independent pull request).

**Comment by stephentetley** [comment]
I've created a pull request:

Add operations to String #1071

**Comment by magnus-madsen** [comment]
Hi Stephen. 

I am thinking of closing this ticket and then opening new tickets for additional features. Would that be okay?

**Comment by stephentetley** [comment]
Yes that's fine.
