### ISSUE TITLE
Refactor the standard library to use the `Ref` module

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#8352]
Refactor the standard library to use the `Ref` module instead of the `ref/deref/=` expressions:

- `ref foo @ rc` becomes `Ref.fresh(foo, rc)`
- `deref foo` becomes `Ref.get`
- `foo := bar` becomes `Ref.put`

See e.g. MutDeque.flix where this already been partially done.

I suggest one PR per module/Flix file.

**Comment by magnus-madsen** [comment]
@sockmaster27 This has high priority because @dghosef depends on it.

**Comment by sockmaster27** [comment]
I can't find any uses of `foo := bar`. Has that been changed already?

**Comment by magnus-madsen** [comment]
> I can't find any uses of `foo := bar`. Has that been changed already?

Possibly it was already refactored. You can open Desugar, goto line 667, and print all source locations where a reference assignment occurs.

**Comment by magnus-madsen** [comment]
You can look at https://github.com/flix/flix/pull/8372 and see which tests fail.

**Comment by sockmaster27** [comment]
Is this done?

**Comment by magnus-madsen** [comment]
Yes, I think so.
