### ISSUE TITLE
Refactor `MutList` to use a struct

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#8387]

**Comment by sockmaster27** [comment]
Do we have a good solution for instancing `IndexableMut`? It needs mutable access to `v->values` but it can't live inside the module. Should we introduce a `MutList.put()`?

**Comment by magnus-madsen** [comment]
> Do we have a good solution for instancing `IndexableMut`? It needs mutable access to `v->values` but it can't live inside the module. Should we introduce a `MutList.put()`?

I would wait to use Indexable and IndexableMut.. We are not done implementing them just yet.

**Comment by sockmaster27** [comment]
But they're already there, they just need to be adapted. Should I remove them?

**Comment by magnus-madsen** [comment]
> But they're already there, they just need to be adapted. Should I remove them?

Oh, I misunderstood. You are saying the problem is that you cannot access the fields of the struct where the instance is defined.

**Comment by sockmaster27** [comment]
> Oh, I misunderstood. You are saying the problem is that you cannot access the fields of the struct where the instance is defined. Is that right?

Yes. exactly

**Comment by magnus-madsen** [comment]
OK. I understand. Then I think you add get and put.
