### ISSUE TITLE
Banish region values 👻

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#8388]
I want to remove regions as values:
- They feel bad syntactically - often one trivial correct choice, and it's cumbersome to carry the region value around
- if we rule out actual semantics to regions, like deallocation (see other issue why I think that is a good choice), the region value itself will always continue to be a dead value not used for anything

So the region value is a cumbersome un-inferred type application - not great.

Let's say we remove region values. What would that entail? Regions could, for the most part, be inferred, but for the sake of the programmer and current region escape checking, it will not always work.

How do we maintain the `something @ rc` and `empty(rc)` behavior when it is nice and wanted:
- We add an `exp @ r` as a general expression that says that `exp,` whatever type it is, uses the region `r.`
  - You can now write `Array.empty()` or `Array.empty() @ r` if you want to.
- This new `@` smart annotation is pretty fancy. In its base form, it could require a known lefthand side, and annotate the rightmost type variable, like `Array[_, r]` or `Ref[r]`. It can also be smarter with a new type constraint.

**Comment by magnus-madsen** [comment]
Counter-point: The region can be used to track resources (e.g. files) and threads which must be closed explicitly upon region exit.

**Comment by JonathanStarup** [comment]
We monomorphize in regards to the region - surely that can be instrumented by the compiler if we want to.

The value is the single value of the type, it seems to me like its always redundant, unless you use it as a type anotation
