### ISSUE TITLE
Namer: eliminate plural functions

### ISSUE THREAD

**Issue by mlutze** [flix/flix#8394]
We have a bunch of functions in Namer that are the plural version of existing functions, e.g. `visitTryCatchRule` and `visitTryCatchRules`.

There is no additional logic in the bodies. We should eliminate these functions, as they clutter the file and obscure the fact that the elements are treated separately.

**Comment by jaschdoc** [comment]
Oopsies... that's me. Thought it was clearer than `decls.map(visitDecl)`

**Comment by mlutze** [comment]
> Oopsies... that's me. Thought it was clearer than `decls.map(visitDecl)`

I guess it's a subjective design question, but its 2 vs 1 at the moment :P

**Comment by jaschdoc** [comment]
True but then we also have to refactor stratifier :))

**Comment by mlutze** [comment]
> True but then we also have to refactor stratifier for consistency :))

I can live with that burden.

**Comment by magnus-madsen** [comment]
> > True but then we also have to refactor stratifier for consistency :))
> 
> I can live with that burden.

Especially when its Jakob's burden :D

**Comment by jaschdoc** [comment]
Hahaha ok :D

**Comment by jaschdoc** [comment]
Should I do this? You assigned Holger but it sounds like it's my bug to fix? :)

**Comment by magnus-madsen** [comment]
> Should I do this? You assigned Holger but it sounds like it's my bug to fix? :)

Fixed.
