### ISSUE TITLE
Resolver: introduce ApplyDef, ApplySig, ApplyClo

### ISSUE THREAD

**Issue by mlutze** [flix/flix#8399]
Maybe generalize over them

**Comment by jaschdoc** [comment]
Maybe this could be a field in `Apply`?

**Comment by JonathanStarup** [comment]
They have different lengths of arguments so it seems nice to have three cases

**Comment by magnus-madsen** [comment]
What @JonathanStarup said.

**Comment by magnus-madsen** [comment]
Also backend uses this naming convention.

**Comment by jaschdoc** [comment]
Should we also add an `ApplyVar` for the case below? I assume `ApplyClo` is for direct application of a lambda, correct?
```scala
let f = x -> x + 1;
f(1)
```

**Comment by mlutze** [comment]
> Should we also add an `ApplyVar` for the case below? I assume `ApplyClo` is for direct application of a lambda, correct?
> ```scala
> let f = x -> x + 1;
> f(1)
> ```

I don't think so. `Clo` is any applied expression, including e.g., another application:

`(id(foo))(xyz)`

**Comment by jaschdoc** [comment]
Should we also rename `Lambda` to `LambdaClosure`? It seems like it is the same thing situation (in terms of naming) when it comes to `ClosureConversion`, i.e., CC eliminates `Lambda`. We could also just rename `LambdaClosure` to `Lambda` in the backend.

**Comment by magnus-madsen** [comment]
> Should we also rename `Lambda` to `LambdaClosure`? It seems like it is the same thing situation (in terms of naming) when it comes to `ClosureConversion`, i.e., CC eliminates `Lambda`. We could also just rename `LambdaClosure` to `Lambda` in the backend.

No, leave as is. Its not the same.

**Comment by jaschdoc** [comment]
Yeah but that would mean fewer `ICE`s

**Comment by magnus-madsen** [comment]
> Yeah but changing it would mean fewer `ICE`s

OK, maybe I am stupid then. Lets discuss at the meeting.
