### ISSUE TITLE
`Index` trait versus `index.html`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#8402]
We have a trait called `Index` which means that it gives rise to `index.html` overwriting the actual `index.html`.

**Comment by magnus-madsen** [comment]
@JonathanStarup @sockmaster27 @jaschdoc 😆

**Comment by magnus-madsen** [comment]
Proposal: We immediately move `Index` to `Core.Ops.Index`

**Comment by JonathanStarup** [comment]
> Proposal: We immediately move `Index` to `Core.Ops.Index`

I think its better to move everything to `flix.X`

**Comment by magnus-madsen** [comment]
> Can it not handle both `index.html` and `Index.html`? I don't think the human readability aspect really matters.

Not on Windows :(

**Comment by magnus-madsen** [comment]
Assume we cannot agree: Can we rename it to `Indexable` and `IndexableMut`. 

This is to overcome the immediate problem. Not to favor the "able".

**Comment by jaschdoc** [comment]
> > Proposal: We immediately move `Index` to `Core.Ops.Index`
> 
> I think its better to move everything to `flix.X`

I like this. It's easy to remember and sensible.

**Comment by JonathanStarup** [comment]
> Assume we cannot agree: Can we rename it to `Indexable` and `IndexableMut`?
> 
> This is to overcome the immediate problem. Not to favor the "able". 

sure, its not more inconsistant than the existing traits

**Comment by magnus-madsen** [comment]
@jaschdoc Could you rename `Index` and `IndexMut` to `Indexable` and `IndexableMut`? -- Thanks!

**Comment by magnus-madsen** [comment]
(We cannot release before this is fixed, so would be nice :))

**Comment by jaschdoc** [comment]
Roger
