### ISSUE TITLE
Refactor `CompletionProvider.Priority`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#8417]
- [x] Move `Priority` into its own `CompletionPriority.scala` class
- [x] Refactor to use the following names: 
  - highest (1)
  - higher (2)
  - high (3)
  - low (7)
  - lower (8)
  - lowest (9)

Later, we should discuss how to turn `CompletionPriority.scala` into a proper enum.

**Comment by magnus-madsen** [comment]
@lozander CC

**Comment by LoZander** [comment]
Currently, there is no priority 3 or 6, instead we have 1,2,4,5,7,8. Do you want me to also change the strings to append the numbers 1,2,3,7,8,9 instead of 1,2,4,5,7,8?

**Comment by magnus-madsen** [comment]
I don't think thats too important. Later we can turn each priority into its own case object.
