### ISSUE TITLE
Refactor `KeywordOtherCompleter`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#8419]
- [ ] Break into `KeywordDeclCompleter` and `KeywordOtherCompleter`.
- [ ] Remove outdated keywords. Check if any keywords are missing.
- [ ] Refactor both completers to use explicit priorities for each keyword based on frequency.
- [ ] Move `SnippetCompleter` into `KeywordDeclCompleter`

**Comment by magnus-madsen** [comment]
@lozander CC

**Comment by LoZander** [comment]
I know the point is to have finer filtering of suggestions given a specific context. Here we want to have fewer and more relevant suggestions when in the decl context. But i'm unsure exactly what this context entails? Is it any top level declaration i.e. type, mod, def, pub etc. or is it just top level function declarations? I'm thinking the greatest level of contextual filtering occurs if we do the latter, as there is no need to be recommended keyword like "mod" when trying to define a top level function, for instance.

**Comment by LoZander** [comment]
oh, but in most declarations, when it is certain what type, there usually aren't anymore keyword to be typed, I suppose. Like, when you've typed `pub def` there aren't really more keywords to be typed, I suppose. But when typing `pub` there are still keywords to be typed, maybe this is the kind of situation where we want to use decl completer?

**Comment by LoZander** [comment]
Or maybe just having the cursor outside as function (either top level of in module) is enough to be in the context where decl completer should be used?

**Comment by LoZander** [comment]
Maybe I started asking question rematurely ^^', because looking at `CompletionProvider.scala` I see that `KeywordOtherCompleter.getCompletions` is invoked specifically when we're in the context of
1. decl of trait
2. decl of enum
3. decl of instance
4. any ofther decl context.

So I assume the keyword to be included in `KeywordDeclCompleter` should be the ones relavent when we're in one of those context. I guess I answered my own question :p

**Comment by LoZander** [comment]
I do have one question left though: in which situations does the completion context have the suntactic context of decl? Obviously whenever we've typed `def`, `instance`, etc., but are we in that context when we've typed `pub` for instance?

**Comment by magnus-madsen** [comment]
Take a look at the parser and at the ASTs.

Declarations are things that go inside modules: defs, traits, etc. etc. etc.

To give an counter-example INSIDE an enum { ... } you cannot have any keywords other than case. So that is not a declaration context.

**Comment by LoZander** [comment]
I see.

In the PR you indicated that I should consider how to further refine syntactic contexts. Do you think I should generally consider how to improve contextual filtrering beyond the scope of this issue?

**Comment by LoZander** [comment]
I've added priorities to the `Other` and `Decl` keywords. I've based this on occurances within the examples programs in `flix/examples/`. It's gives a far from perfect picture, since a lot of the more niece keywords just don't appear, and `trait`, which I suspect would usually appear relatively often, is suspiciously rare. If I can find a list of more flix programs, I'd be able to get a bigger dataset to work with, but for now this should at least be an improvement.

I assigned priority in relation to the other keywords in the completer, not across completions. I did this assuming that those in different completer would not generally occur simultanous. But if we ever combine the completers, the priorities may not make sense anymore. Is this an issue?

**Comment by LoZander** [comment]
I do have a flix project myself I could include in the dataset. Perhaps others working on flix also have some projects I could use?

**Comment by LoZander** [comment]
> @magnus-madsen Ive been thinking about how to do completions when there's a modifier like pub.
> 
> Currently, the way I'm doing it, when you write for instance `pu` only `pub` is suggested and then after that, the suggestions for the next keyword are only the keywords that can be made public.
> 
> Altenratively, since `pub` will always be followed by another keyword, I could make it so that when you type `pu` it suggests `pub def` and `pub enum` etc.
> 
> I think the latter is preferable, but I wanna hear what you think :)

A third option could be to go full snippet and have suggestions like `pub def <f>(<args>): <T> = ???` or something like that, but I worry that could get obnoxious for a construction as simpel af normal declarations, which require very little typing already. But let me know what you think

**Comment by magnus-madsen** [comment]
> I've added priorities to the Other and Decl keyword completers. I've based this on occurances within the example programs in flix/examples/. It gives a far from perfect picture, I suspect, since a lot of the more niece keywords just don't appear, and trait, which I suspect would usually appear relatively often, is suspiciously rare. If I can find a list of more flix programs, I'd be able to get a bigger dataset to work with, but for now this should at least be an improvement.

Just use the entire Flix standard library.

**Comment by magnus-madsen** [comment]
> A third option could be to go full snippet and have suggestions like pub def <f>(<args>): <T> = ??? where etc. are snippet palceholders, or something like that, but I worry that could get obnoxious for a construction as simpel af normal declarations, which require very little typing already. But let me know what you think

That sounds like a bad idea.

**Comment by magnus-madsen** [comment]
> Currently, the way I'm doing it, when you write for instance pu only pub is suggested and then after that, the suggestions for the next keyword are only the keywords that can be made public.

Modifiers will be tricky. Let us just focus on getting all the basic syntactic contexts in place.

**Comment by magnus-madsen** [comment]
Looking at the current code, I think there is a lot of over-engineering. We just want a list of functions like:

```
def getExprKeywords(...): Iterable[Completion]
def getTraitKeywords(...): Iterable[Completion]
def getInstanceKeywords(...): Iterable[Completion]
```

and so forth. Do you think you can refactor towards that @LoZander ?

**Comment by LoZander** [comment]
> > Currently, the way I'm doing it, when you write for instance pu only pub is suggested and then after that, the suggestions for the next keyword are only the keywords that can be made public.
> 
> Modifiers will be tricky. Let us just focus on getting all the basic syntactic contexts in place.

Do you think the way I'm currently filtering out keywords depending on the preceeding modifier makes sense or is it overkill?

**Comment by LoZander** [comment]
> > Currently, the way I'm doing it, when you write for instance pu only pub is suggested and then after that, the suggestions for the next keyword are only the keywords that can be made public.
> 
> Modifiers will be tricky. Let us just focus on getting all the basic syntactic contexts in place.

Perhaps deciding whether or not we are a pub, sealed or private decl should be decided by the syntactic context instead of how I'm dying it? Is that what you mean?

**Comment by magnus-madsen** [comment]
We need a simple base to build on.

**Comment by LoZander** [comment]
alright, got it. I'll simplify it and maybe then maybe it's time to look at syntactic contexts? :)

**Comment by magnus-madsen** [comment]
Yes. But let's do a simple implementation and then build on that.

**Comment by LoZander** [comment]
Yep, sounds good. I went a bit overboard here, I see that. I got a little eager ^^'
After this simplification (which I'm doing right now) i'll start reading up on the parser and how the syntactic contexts are generated

**Comment by LoZander** [comment]
Alright, so then next up is

1. Turning priority into an enum
2. More syntactic context (e.g. instance and eff)

**Comment by LoZander** [comment]
There is a complication. My understanding was that priority added a single number for sorting, but I've just stumbled upon a usage where a sorting string that already has a priority prefix gets added another on top of it. Whether this is an error or for even finer grained priorities (e.g. `29name1` and `39name2`) is unclear
 ```scala
  /**
    * Returns a List of Completion for builtin types.
    */
def getCompletions(context: CompletionContext)(implicit flix: Flix, index: Index, root: TypedAst.Root): Iterable[TypeBuiltinCompletion] = {
    val builtinTypes = BuiltinTypeNames.map { name =>
      val internalPriority = Priority.highest _
      Completion.TypeBuiltinCompletion(name, TypeCompleter.priorityBoostForTypes(internalPriority(name))(context), TextEdit(context.range, name),
        InsertTextFormat.PlainText)
    }

    val lowPriorityBuiltinTypes = LowPriorityBuiltinTypeNames.map { name =>
      val internalPriority = Priority.lowest _
      Completion.TypeBuiltinCompletion(name, TypeCompleter.priorityBoostForTypes(internalPriority(name))(context), TextEdit(context.range, name),
        InsertTextFormat.PlainText)
    }

    val builtinTypesWithParams = BuiltinTypeNamesWithTypeParameters.map {
      case (name, tparams) =>
        val internalPriority = Priority.higher _
        val fmtTparams = tparams.zipWithIndex.map { case (name, idx) => s"$${${idx + 1}:$name}" }.mkString(", ")
        val finalName = s"$name[${tparams.mkString(", ")}]"
        Completion.TypeBuiltinCompletion(finalName, TypeCompleter.priorityBoostForTypes(internalPriority(name))(context),
          TextEdit(context.range, s"$name[$fmtTparams]"), insertTextFormat = InsertTextFormat.Snippet)
    }

    builtinTypes ++ lowPriorityBuiltinTypes ++ builtinTypesWithParams 
 }
```
This is in `TypeBuiltinCompleter.scala` and `TypeCompleter.priorityBoostForTypes` adds a priority prefix to the given string depending on whether or not the text we're currently writing is immediately preceeded by a `:`. It gives `higher` (previously `boost`) priority if there's a `:` and gives `lowest` otherwise. The use of this boosting function only really makes sense if we're working with `sortText` like `23someType`. If that wasn't the intent then, in it's current form, the use of priority here is bugged.

I'm having some trouble wrapping my head around this. Either this is already broken, or our changes to Priority will break it, I think.

What do you think? How should I proceed?

**Comment by LoZander** [comment]
Looking at more of the code in completions, it does seem that priority is used in a layered manner. Maybe we could make our Priority enum recursive to support this, or something like that?

**Comment by LoZander** [comment]
I could ofc. also just change it so there is no "boosting" or just make "boosting" set the priority to highest or something like that. That way we could keep Priority simple

**Comment by magnus-madsen** [comment]
> There is a complication. My understanding was that priority added a single number for sorting, but I've just stumbled upon a usage where a sorting string that already has a priority prefix gets added another on top of it. Whether this is an error or for even finer grained priorities (e.g. 29name1 and 39name2) is unclear

I think this is crazy. I don't think we should support such a feature going forward.

**Comment by magnus-madsen** [comment]
Let just have an enum:

```
sealed trait Priority
object Priority {
  case object Highest extends Priority
  ....
}
```

and work from there.

**Comment by magnus-madsen** [comment]
The whole idea of boosting priorities seems like a hack someone added. We should just assign the right priorities to begin with. Like we are doing in the KeywordCompleter.

**Comment by LoZander** [comment]
Alright. I'll redo how they related completers use priorities to be in line with `KeywordCompleter` then :)

**Comment by LoZander** [comment]
> Let just have an enum:
> 
> ```
> sealed trait Priority
> object Priority {
>   case object Highest extends Priority
>   ....
> }
> ```
> 
> and work from there.

Yep. That's also how I've been doing it. It was just that whole boosting thing that confused me :)

**Comment by LoZander** [comment]
I've not gone too indepth with changing the type completer, since it felt out of scope for the refactoring I did. But I do think it's worth looking at. I did also simplify some of it and removed the strange boosting hack

**Comment by LoZander** [comment]
But yeah, I think type completer is worth returning to to further simplify

**Comment by magnus-madsen** [comment]
> But yeah, I think type completer is worth returning to to further simplify

Yes. But lets maybe keep focus on finishing Keyword completers first. I think what is missing now is to (1) double check we have the right keywords and (2) add more syntactic contexts.

**Comment by magnus-madsen** [comment]
I think the next tasks are:

- [ ] Remove outdated keywords (if any -- see Parser2)
- [ ] Add missing keywords (if any -- see Parser2)
- [ ] Add priorities to all keywords in KeywordCompleter.
- [ ] Add syntactic contexts for missing declaration: `Decl.Eff`
- [ ] Add methods: `getStructKeywords` and `getEffKeywords`
- [ ] Rename `SyntacticContext.OtherDecl` to `Mod`
- [ ] Tidy up: Remove unused imports in KeywordCompleter
- [ ] Tidy up: Remove unused SyntacticContext.join method.

**Comment by magnus-madsen** [comment]
I would consider leaving these functions sorted:

```
  def getDeclKeywords: Iterable[Completion] =
    List(
      Completion.KeywordCompletion("def"      , Priority.Highest),
      Completion.KeywordCompletion("pub"      , Priority.Higher),
      Completion.KeywordCompletion("enum"     , Priority.High),
      Completion.KeywordCompletion("type"     , Priority.High),
      Completion.KeywordCompletion("instance" , Priority.High),
      Completion.KeywordCompletion("mod"      , Priority.Low),
      Completion.KeywordCompletion("eff"      , Priority.Lower),
      Completion.KeywordCompletion("struct"   , Priority.Lower),
      Completion.KeywordCompletion("sealed"   , Priority.Lowest),
      Completion.KeywordCompletion("trait"    , Priority.Lowest),
      Completion.KeywordCompletion("import"   , Priority.Lowest),
    )
```

Moreover, I would then use a default priority and only use a higher priority when there is a clash. Afterall "def" cannot clash with "import". So in my world, I would have something more like:

```
      Completion.KeywordCompletion("sealed"   , Priority.Low), // "sealed" is less common than "struct".
      Completion.KeywordCompletion("struct"   , Priority.Default),
```

**Comment by LoZander** [comment]
> I would consider leaving these functions sorted:
> 
> ```
>   def getDeclKeywords: Iterable[Completion] =
>     List(
>       Completion.KeywordCompletion("def"      , Priority.Highest),
>       Completion.KeywordCompletion("pub"      , Priority.Higher),
>       Completion.KeywordCompletion("enum"     , Priority.High),
>       Completion.KeywordCompletion("type"     , Priority.High),
>       Completion.KeywordCompletion("instance" , Priority.High),
>       Completion.KeywordCompletion("mod"      , Priority.Low),
>       Completion.KeywordCompletion("eff"      , Priority.Lower),
>       Completion.KeywordCompletion("struct"   , Priority.Lower),
>       Completion.KeywordCompletion("sealed"   , Priority.Lowest),
>       Completion.KeywordCompletion("trait"    , Priority.Lowest),
>       Completion.KeywordCompletion("import"   , Priority.Lowest),
>     )
> ```
> 
> Moreover, I would then use a default priority and only use a higher priority when there is a clash. Afterall "def" cannot clash with "import". So in my world, I would have something more like:
> 
> ```
>       Completion.KeywordCompletion("sealed"   , Priority.Low), // "sealed" is less common than "struct".
>       Completion.KeywordCompletion("struct"   , Priority.Default),
> ```

yeah, that makes sense. I think Ill look at that next. Shouldn't take too long

**Comment by magnus-madsen** [comment]
I think we are still missing SyntacticContext.Decl.Eff, yes?

**Comment by magnus-madsen** [comment]
@LoZander We continue in a couple of new tickets.

**Comment by LoZander** [comment]
> I think we are still missing SyntacticContext.Decl.Eff, yes?

yes. But I see you've made a new issue for it, so we'll continue the conversation there :)
