### ISSUE TITLE
Recent fix to argument parsing broke method completion

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#8427]
This:

```
import java.io.{File => JFile}

def main(): Unit \ IO = 
    let f = new JFile("abc");
    f.f
```

now gives:

```
❌ -- Parse Error (Unknown) -------------------------------------------------- file:///c%3A/tmp/flix/Main.flix

>> Expected at least one <ArgumentList>.

5 |     f.f
        ^^^
        Here
```

which is not a MethodNotFound error that the completer can use.

**Comment by magnus-madsen** [comment]
@JonathanStarup Do you see a way to resolve this? 

@lozander Currenly this means that method completion is broken (static method completion works).

**Comment by JonathanStarup** [comment]
it isnt a java call parsing wise 

- once we add `f.f` as a struct field / java field, the completer can use that?
- otherwise, i think the parsing context should be FieldOrJavaCall or something to that effect, which could be used?

**Comment by JonathanStarup** [comment]
I think it will be double work to fix it before we add `f.f` as valid syntax. ill put  it on the top of my list

**Comment by magnus-madsen** [comment]
Can something simple be done now because Alexander is building on this and the train stuff is far in the future

**Comment by magnus-madsen** [comment]
Trait

**Comment by JonathanStarup** [comment]
short term, `f.f` is unambiously a java field lookup no?

**Comment by magnus-madsen** [comment]
> short term, `f.f` is unambiously a java field lookup no? before the Dot trait

I think so. So maybe two birds with one stone?

**Comment by LoZander** [comment]
The tests in regards to non-static method completions now pass. Did someone fix this issue or maybe some other changed indirectly did so?

**Comment by JonathanStarup** [comment]
yeah it was fixed
