### ISSUE TITLE
Parser stuck on effect def named `throw`

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#8436]
```
eff Example {
  def throw(): Void
}
```
parser is stuck (probably since throw is a keyword now)

**Comment by jaschdoc** [comment]
Do you want this to be parsed or to reject the program gracefully?

**Comment by magnus-madsen** [comment]
Rejected gracefully

**Comment by JonathanStarup** [comment]
It is fixed on master (throw was missing in the list of keywords)
