### ISSUE TITLE
Output of `--Xprint-phases` is garbled

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#8500]

**Comment by jaschdoc** [comment]
Can you assign me to this? :)

**Comment by JonathanStarup** [comment]
@jaschdoc do you know how it happened or how to fix it?

**Comment by jaschdoc** [comment]
Nope, but thought we might figure it out together?

**Comment by JonathanStarup** [comment]
ah yes, its also due some love, its been left alone for a while with a lot of new syntax
