### ISSUE TITLE
Bug in `RenameProvider`

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#8565]
```scala
    @Test
    def record01(): Bool = region rc {
        try {
            let r = { a = Array#{0, 1, 2, 3} @ rc };
            r#a[1] = 2;
            r#a[1] == 2
        } with KeyNotFound {
            def keyNotFound(_, _) = false
        }
    }

    @Test
    def record02(): Bool = region rc {
        try {
            let r = { r = { a = Array#{0, 1, 2, 3} @ rc } };
            r#r#a[1] = 2;
            r#r#a[1] == 2
        } with KeyNotFound {
            def keyNotFound(_, _) = false
        }
    }

    @Test
    def record03(): Bool =
        let r = { r = { a = Vector#{{ a = Vector#{1, 2, 3, 4} } } } };
        handler(() -> r#r#v[0]#v[1] == 2)
```

In each record `r` the field was originally named `v`. I tried to rename the variable to `a` in `record01` using the rename variable functionality in VSCode (the cursor was point to `a` at `r#a[1] = 2;` (originally `v`) on line 5). This accidentally renamed each occurrence of `v` in `r` to `a` in the other tests too (!) where `r` is not the same `r`.

Note that the program contained the same errors as above: `handler` is not defined and `KeyNotFound` is not the correct effect. Note that VSCode does not highlight the latter as an error (maybe because compilation fails before it is considered)

**Comment by magnus-madsen** [comment]
Records are structural which means that when a label is renamed there is really no way to do the rename other than to do it globally. We simply cannot know which fields to rename otherwise.

It sounds like this global rename is what happened and got you confused.

**Comment by magnus-madsen** [comment]
EDIT: I did not mean to blame you. I agree the behavior is confusing!

**Comment by jaschdoc** [comment]
Is there any way to associate the record with the declaration site using source locations?

**Comment by magnus-madsen** [comment]
> Is there any way to associate the record with the declaration site using source locations?

I am not sure this can be done without program analysis.
