### ISSUE TITLE
Improve letrec/local def representation

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#8606]
local defs are slow in many aspects (typing / runtime) and right now we treat them very "by the book"

- `def inner(a, b) = inner(a, b + c)` becomes `inner = a -> b -> loop -> c -> loop(a)(b + c)` where the backend wires loop to be the function itself.

We need to treat local defs more like defs and less like let binders.

- [ ] Modify LetRec in weeded AST and onwards to have fparams (`def f(x, y) = f(y)(x)` instead of `letrec f = x -> y -> f(y)(x)`)
- [ ] Rename LetRec to LocalDef
- [ ] Add LocalDefSym for these symbols
- [ ] handle applications of LocalDef in resolver by either fully applying or currying, like for defs with ApplyLocalDef or applies of the curried thing
- [ ] convert other phases to do as they did before but on the new structure
- [ ] in ClosureConv (i think) handle the captured variables and hoist into a top-level def

hopefully this means that the backend then generates tail calls for local defs

**Comment by JonathanStarup** [comment]
hmm its not too easy

**Comment by magnus-madsen** [comment]
Sounds good. I agree with the approach, just worried about the details.

We should discuss @jaschdoc, you, and me.

**Comment by jaschdoc** [comment]
Can you assign this to me and maybe add a `project` label? Or as long as it does not have the `student-programmer` label then I can distinguish between the two hats :)

**Comment by jaschdoc** [comment]
Done? :)
