### ISSUE TITLE
arewefast is broken

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#8609]
... seems relate to the Console changes... but --Xbenchmark commands work fine?

**Comment by magnus-madsen** [comment]
@mlutze Can you help debug? I don't really understand what could have broken.

**Comment by mlutze** [comment]
```
$ ls /tmp | grep -c "flix-project"
125395
```

**Comment by magnus-madsen** [comment]
> ```
> $ ls /tmp | grep -c "flix-project"
> 125395
> ```

Space?
