### ISSUE TITLE
Overload resolution

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#8619]
It seems I cannot call any methods in: https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Runtime.html

I cannot even call start!

**Comment by JonathanStarup** [comment]
`TypeReduction.candidateMethods` is to blame

**Comment by JonathanStarup** [comment]
Fixed in master

**Comment by magnus-madsen** [comment]
What about constructors?

**Comment by JonathanStarup** [comment]
right. but the handler you wanted works now

**Comment by magnus-madsen** [comment]
Fixed?

**Comment by JonathanStarup** [comment]
yes
