### ISSUE TITLE
Rename `debug` commands to `dbg` to free up `debug` for `Logger`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#8626]
- [x] Rename `debug` and friends to `dbg` etc.
- [x] Rename `Logger.debug1` to `Logger.debug`
- [x] Update doc.flix.dev

**Comment by magnus-madsen** [comment]
Requires some changes to the Lexer/Parser plus Prelude.flix.

**Comment by JonathanStarup** [comment]
couldnt we add a ! to each, so `debug!`, `debug!!`, and `debug!!!`

**Comment by magnus-madsen** [comment]
That's also possible.

**Comment by sockmaster27** [comment]
> Is debug treated as a keyword?

Yes. Both in the compiler and in highlighting.

**Comment by sockmaster27** [comment]
What's the strategy with keeping highlight.js etc. up to date without spamming the maintainers?

**Comment by magnus-madsen** [comment]
We maintain our own fork of highlight.js-- they are not accepting upstream PRs for a while now.

For other packages, I think the point is just to update more rarely, so we can bundle more changes into one PR.

**Comment by sockmaster27** [comment]
Ok, so it seems like the only upstream highlighting we have is Ace, right?
Can someone with permissions make a flix/ace fork where we can buffer the changes?

**Comment by magnus-madsen** [comment]
> Ok, so it seems like the only upstream highlighting we have is Ace, right? Can someone with permissions make a flix/ace fork where we can buffer the changes?

I think it can wait. I propose when Linquist is eventually merge we can do a big round of updating all the other stuff.
