### ISSUE TITLE
Compile error using "arbitrary boolean expressions to control the purity of function arguments"

### ISSUE THREAD

**Issue by steshaw** [flix/flix#8664]
I was trying to work out what is meant by the "arbitrary boolean expressions to control the purity of function arguments" from the [effects chapter of the book](https://doc.flix.dev/effects.html). I tried entering the following example from the book into the repl with the addition of `= ???` (which could be throwing things off):

```
flix> def h(f: a -> b \ ef, g: b -> c \ { (not ef1) or ef2 }): Unit = ???
-- Kind Error -------------------------------------------------- $1

>> Expected kind 'Bool -> Bool -> Eff' here, but kind 'Bool -> Bool -> Bool' is used.

1 | def h(f: a -> b \ ef, g: b -> c \ { (not ef1) or ef2 }): Unit = ???
                                        ^^^^^^^^^^^^^^^^
                                        unexpected kind.

Expected kind: Bool -> Bool -> Eff
Actual kind:   Bool -> Bool -> Bool

Error: Declaration ignored due to previous error(s).
```

I'm using Flix 0.50.0 and noted the same error on 0.49.0.

**Comment by magnus-madsen** [comment]
Thanks-- I think the documentation has become slightly outdated. Try:

```
def h(f: a -> b \ ef1, g: b -> c \ { (~ef1) + ef2 }): Unit = 
    checked_ecast(???)
```

**Comment by magnus-madsen** [comment]
Also take a look at https://doc.flix.dev/type-level-programming.html

But note that type level Booleans and effects are not the same, and cannot be mixed.

**Comment by steshaw** [comment]
Thanks! The `checked_ecast` was redudant. So, I have now:

```scala
def h(f: a -> b \ ef1, g: b -> c \ { (~ef1) + ef2 }): Unit = ???
```
