### ISSUE TITLE
`runX` and `handleX` in effect modules

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#8702]
### Discussed in https://github.com/flix/flix/discussions/8694

<div type='discussions-op-text'>

<sup>Originally posted by **JonathanStarup** September 23, 2024</sup>
currently we have `runX: Unit -> t \ ef -> t \ ef - X`. This is nice for the simple case, but when you have multiple effects, they are hard to compose `runA(() -> runB(() -> body))`. so I propose that we have the base handler function `handleX: a -> b \ ef -> a -> b \ ef - X` where `runX` can then be a shorthand convenience method</div>

**Comment by magnus-madsen** [comment]
Fixed in master.
