### ISSUE TITLE
Benchmarks broken

### ISSUE THREAD

**Issue by mlutze** [flix/flix#8706]
Benchmarking is broken since Flix does not explore directories recursively for `*.flix` files unless it's in a `src` directory.

We can fix this by:
1. Putting the benchmarking stuff in a `src` directory.
2. Putting the benchmarking stuff in a flat directory.

In either case, we may want to adjust the testing suite thingy to make sure we catch this if it happens again.

**Comment by JonathanStarup** [comment]
yeah its on the server

**Comment by mlutze** [comment]
> > In either case, we may want to adjust the testing suite thingy to make sure we catch this if it happens again.
> 
> What do you mean by this? Tests in the Flix repo pass, so this would happen somewhere in on the benchmarking server?

Specifically, we should make it so that the new mkTestDir function doesn't explore recursively, so the test suite runner matches what the benchmark runner does

**Comment by jaschdoc** [comment]
Alright
