### ISSUE TITLE
Post `LocalDef` things

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#8782]
Once https://github.com/flix/flix/pull/8669 is merged, the following things still need to happen:

- [x] Remove `LetRec` (or deprecate if we decide to hide `LocalDef` behind a feature toggle)
- [x] Update `DocAst` to accommodate `LocalDef` / turn `LetRec` into `LocalDef`

**Comment by JonathanStarup** [comment]
maybe introduce `LocalDefSym` and `LocalDefSymUse`?

**Comment by magnus-madsen** [comment]
> maybe introduce `LocalDefSym` and `LocalDefSymUse`?

Not so sure about this. I think this will cause massive code duplication...

**Comment by JonathanStarup** [comment]
I don't think its that bad. They downside currently is that any given `ApplyLocalDef` can be malformed because its just a varsym and they can be mistaken for eachother

**Comment by magnus-madsen** [comment]
If we *try* to introduce LocalDefSym then lets keep it in one self-contained small PR.

**Comment by magnus-madsen** [comment]
So now LetRec can be removed, yes?

**Comment by jaschdoc** [comment]
Yes
