### ISSUE TITLE
Remove `WeededAst.Expr.Let`

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#8783]
`WeededAst.Expr.Let` is never constructed anywhere so it's dead code. It seems the parser just always produces `LetMatch` instead.

**Comment by jaschdoc** [comment]
Maybe we can even remove it from several ASTs

**Comment by JonathanStarup** [comment]
Let is introduced in Desugar, so probably also unused in named ast?

**Comment by magnus-madsen** [comment]
Isnt NamedAst after Desugar?
