### ISSUE TITLE
Missing `import javax.swing.JFrame` autocomplete

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#8791]
For some reason, it is not in the autocomplete, but the code works fine (Flix 0.51.0)

**Comment by magnus-madsen** [comment]
I think its because that code is not part of our ClassList

**Comment by JonathanStarup** [comment]
I didn't download anything. `java.awt` also isn't shown

**Comment by magnus-madsen** [comment]
Did you check the class list file?

**Comment by magnus-madsen** [comment]
https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/util/ClassList.scala

**Comment by JonathanStarup** [comment]
Yeah they are missing from there. Is it autogenerated?

**Comment by magnus-madsen** [comment]
Yes. It says how in the comments.

**Comment by JonathanStarup** [comment]
We pull from `src/java.base/share/classes` but the classes I need are in `src/java.desktop/share/classes/`. There is also a bunch of other modules (https://docs.oracle.com/en/java/javase/22/docs/api/)

should we include all of them?

**Comment by magnus-madsen** [comment]
I think only the most relevant.

**Comment by magnus-madsen** [comment]
Could you extend with java.desktop and java.net for now. Thanks

**Comment by magnus-madsen** [comment]
Fixed.
