### ISSUE TITLE
No type information on java method hover

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#8793]
```
import java.awt.Dimension
import javax.swing.JFrame
import javax.swing.JLabel
import javax.swing.SwingConstants

/// https://mkyong.com/swing/java-swing-hello-world-example/
def main(): Unit \ IO = {

    let frame = new JFrame("Hello World Java Swing");

    // set frame site
    frame.setMinimumSize(new Dimension(800, 600));
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    // center the JLabel
    let lblText = new JLabel("Hello World!", SwingConstants.CENTER);

    // add JLabel to JFrame
    frame.getContentPane();

    ???
}
```
Hovering on `setMinimumSize` doesn't show anything

**Comment by magnus-madsen** [comment]
Probably @LoZander's work will fix this.

**Comment by LoZander** [comment]
Yes, I think it's likely my work will fix this

**Comment by magnus-madsen** [comment]
Seems OK now

**Comment by LoZander** [comment]
Yeah. For some reason the some of the comments are included when on the hover highlighting of some of the expressions and hovering on these comments is acts as hovering on the adjacent expression. But that's a different issue. Hovering on fx `setMinimumSize` does give type and effect information now :)
