### ISSUE TITLE
No hover on function defs

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#8797]
```
/// Cool stuff.
def example(x: Int32): Int32 = example(x)
```
when I hover `example` on the left I'd like to see all the information I see when I hover on `example` on the right.

**Comment by magnus-madsen** [comment]
No. But thank you for coming to my TED talk :)

**Comment by JonathanStarup** [comment]
No? :O why not

**Comment by magnus-madsen** [comment]
> No? :O why not

The information is already there.
