### ISSUE TITLE
Number literal source locations off-by-one problem

### ISSUE THREAD

**Issue by LoZander** [flix/flix#8798]
The `SourceLocation` for number literals erroneously includes the symbol right after. fx the location for `2` in `let x = 2;` would actually include `;`. This is not the case for all number literals. It's not the case for number literals with an explicit type, like `2i32`. It is however the case for both number literals with and without decimals.

It could be that this issue resides somewhere in in the `acceptNumber` function in the lexer. Maybe a problem with how advance and retreat is used here or affects locations. But this is just speculation.

**Comment by jaschdoc** [comment]
Two questions:
1) How do you observe the behavior?
2) Does this also happen for floats / decimal numbers?
