### ISSUE TITLE
Bad `QuineMcCluskey.collectPrimeImplicants` performance (Vscode timeout)

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#8801]
This program is not too slow, but it is a boiled down example of my project where vscode timeouts. Note that `Asd.unknown` is not a valid function. In this program `QuineMcCluskey.collectPrimeImplicants` takes up 44% of total compilation time.
```scala
eff E {
    pub def op(x: Int32): Unit
}
mod E {
    import java.lang.Object

    pub type alias T1[ef1: Eff, ef2: Eff, ef3: Eff] = {
        a = Unit -> Unit \ ef2,
        b = String
    }

    pub type alias T2[ef1: Eff, ef2: Eff, ef3: Eff] = {
        a = Object -> Unit \ ef1,
        b = String
    }

    pub def f2(x: T2[ef1, ef2, ef3]): Unit \ IO + ef1 + ef2 + ef3 = {
        let _ = new Object {
            def toString(this: Object): String \ ef1 = {x#a(this); ""}
        };
        ???
    }

    pub def f1(x: T1[ef1, ef2, ef3]): Unit \ IO + (ef1 - E) + (ef2 - E) + (ef3 - E) =
        f2({
            a = Asd.unknown(x#a),
            b = x#b
        })
}
```

**Comment by JonathanStarup** [comment]
@magnus-madsen I think this highlights a scary case for resilient compilation - if I introduce a new module around some code, many of my functions are not found. All of these functions now have arbitrary types and effects, which might slow down performance enough to break the editor.

**Comment by magnus-madsen** [comment]
I think QMC will be gone soon anyway, so?

**Comment by JonathanStarup** [comment]
I guess so yeah, but we can check and see if this example is faster then

**Comment by magnus-madsen** [comment]
The example seems plenty fast to me now.
