### ISSUE TITLE
Refactor `Validation` use in `Resolver`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#8812]
The `Resolver` still has many uses of `toHardFailure`-- too many to quickly refactor.

However, I would like to get rid of `toSoftFailure`, hence I want `Resolver` refactored to a hybrid form:

- `Resolver` should use `SharedContext` for `toSoftFailure`
- `Resolver` should **continue** to use `Validation` and `toHardFailure` where it currently does.

Hence the task is to introduce `SharedContext` and refactor uses of `toSoftFailure` but stop thereafter.

**Comment by magnus-madsen** [comment]
@jaschdoc Does it make sense?

**Comment by jaschdoc** [comment]
Perfectly

**Comment by jaschdoc** [comment]
We are done with this for now so we can close it :)
