### ISSUE TITLE
Refactor return type of phases

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#8815]
Here is the signature of our good friend `Kinder`:

```scala
def run(root: ResolvedAst.Root, oldRoot: KindedAst.Root, changeSet: ChangeSet)(implicit flix: Flix): 
    Validation[KindedAst.Root, KindError] = flix.phase("Kinder") { ... } (DebugValidation())
```

I would like this to become:

```scala
def run(root: ResolvedAst.Root, oldRoot: KindedAst.Root, changeSet: ChangeSet)(implicit flix: Flix): 
     (KindedAst.Root, List[KindError]]) = flix.phase("Kinder") { ... }
```

This needs a few changes. Most importantly, we can stop using Monadic style in Flix. Instead, something like:

```scala
val errors: mutable.ListBuffer[CompilationError] = mutable.ListBuffer.empty

// previous phase
val (afterKinder, kinderErrors) = Kinder.run(afterResolver, cachedKinderAst, changeSet)
errors += kinderErrors
// next phase
```

I think this refactoring can be done gradually (i.e. phase by phase). In particular, we can keep the giant `for` during refactoring because a `for` can contain `val` decls in Scala (I think).

We might need a temporary new `flix.phase` command:

```scala
def phaseNew[A, B](phase: String)(f: => (A, B))(implicit d: Debug[A]): (A, B) = ...
```

EDIT: If a phase does not change an AST I think it should just return the list of errors.

**Comment by magnus-madsen** [comment]
@jaschdoc Does it make sense?

**Comment by magnus-madsen** [comment]
@jaschdoc I did an example PR here: https://github.com/flix/flix/pull/8816 to show the pattern.

**Comment by jaschdoc** [comment]
Yes looks good :)

**Comment by jaschdoc** [comment]
What about changing the return type to `(XAst.Root, Iterable[XError])` so we avoid the `toList` on `sctx.error.asScala.toList`? Maybe it's not that expensive really since most of the time it's just `Nil` but it's free performance

**Comment by magnus-madsen** [comment]
> What about changing the return type to `(XAst.Root, Iterable[XError])` so we avoid the `toList` on `sctx.error.asScala.toList`? Maybe it's not that expensive really since most of the time it's just `Nil` but it's free performance

No fucking way.

**Comment by magnus-madsen** [comment]
Pardon my french, but Iterable and Iterators are extremely error prone. Returning is very clearly the right thing to do: It is exactly the right data type and we know that the lists are typically empty or at least short.

**Comment by magnus-madsen** [comment]
In restrospect I should have asked for this in one single PR 😆

**Comment by jaschdoc** [comment]
Yeah, well... :shrug:

**Comment by jaschdoc** [comment]
Added some more draft PRs to help sketch out how I think we should arrive at my dreams in https://github.com/flix/flix/pull/8880
