### ISSUE TITLE
Add `App.run`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#8852]
Add a module:

```scala
mod App {
    def run(f: Unit -> a \ ef): a \ (ef - {Clock, Console, ..., Logger}) + IO = ... reuse all handlers here ...
}
```

**Comment by JonathanStarup** [comment]
shouldnt we just allow base effects to leak into the entrypoint and then add the default handlers there?

**Comment by magnus-madsen** [comment]
> shouldnt we just allow base effects to leak into the entrypoint and then add the default handlers there?

Maybe, but I would not go there just yet.

**Comment by magnus-madsen** [comment]
Fixed in master.
