### ISSUE TITLE
Collect errors from `EffectVerifier` instead of crashing

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#8867]
It looks like `EffectVerifier` just crashes with an `ICE` if there is a "no-instance". This is a verifier, but maybe it should return a `Result[Unit, VerificationError]`?

```scala
  /**
    * Throws an exception if the actual type does not match the expected type.
    */
  private def expectType(expected: Type, actual: Type, loc: SourceLocation)(implicit eqEnv: ListMap[Symbol.AssocTypeSym, Ast.AssocTypeDef], flix: Flix): Unit = {
    // mark everything as rigid
    val renv = RigidityEnv.ofRigidVars(expected.typeVars.map(_.sym) ++ actual.typeVars.map(_.sym))
    if (!Unification.unifiesWith(expected, actual, renv, eqEnv)) {
      throw InternalCompilerException(s"Expected type $expected but found $actual", loc)
    }
  }

```

**Comment by jaschdoc** [comment]
Maybe it could also just be a list of errors like the other phases

**Comment by magnus-madsen** [comment]
No, its in the backend. By definition it cannot find any errors in the program. It can only find bugs in the compiler and they always crash.

**Comment by jaschdoc** [comment]
It runs right after the typer?

```scala
      afterTyper <- Typer.run(afterDeriver, cachedTyperAst, changeSet)
      _ = EffectVerifier.run(afterTyper)
      _ <- Regions.run(afterTyper)
```

**Comment by magnus-madsen** [comment]
> It runs right after the typer?
> 
> ```scala
>       afterTyper <- Typer.run(afterDeriver, cachedTyperAst, changeSet)
>       _ = EffectVerifier.run(afterTyper)
>       _ <- Regions.run(afterTyper)
> ```

What???

**Comment by magnus-madsen** [comment]
That is strange. I am not sure why we do that. Nevertheless the doc says:

```
This phase is only for debugging; inconsistencies indicate a bug in the typer and result in a crash.
```

So it should still not return any errors.

I am just puzzled by why it is here.

**Comment by jaschdoc** [comment]
ah ok fair, I can move it up, though?

**Comment by magnus-madsen** [comment]
@JonathanStarup What's the point of EffectVerifier and can we remove it?

**Comment by JonathanStarup** [comment]
I think matt wrote it? it was born to check things that the later verifier cannot verify, like instances. this would avoid ugly monomorph crashes/faulty erasure

**Comment by magnus-madsen** [comment]
I see. So one day it might go away? It is just that effects have been through so much churn.

**Comment by magnus-madsen** [comment]
@mlutze How long do you plan to keep this around?

**Comment by mlutze** [comment]
Magnus:
> We should add an Effect Verifier.

3 months later
> This effect verifier is annoying, do we have to keep it?

Let's keep it around until after the new constraint solver is in.
Maybe we can just disable it if an error is detected in a previous phase?

**Comment by JonathanStarup** [comment]
Since it is indeed frontend, it doesn't take much work to append errors into a shared context list?

**Comment by jaschdoc** [comment]
True I opened the issue before we discussed it elsewhere
