### ISSUE TITLE
Missing `with` keyword for expressions (try-with)

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#8909]

**Comment by magnus-madsen** [comment]
@LoZander CC

**Comment by jaschdoc** [comment]
Is this LSP or what is the issue exactly?

**Comment by magnus-madsen** [comment]
`with` can also occur in an expression, so add one line here:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/api/lsp/provider/completion/syntactic/KeywordCompleter.scala#L80
