### ISSUE TITLE
Remove usage of `do` keyword

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#8926]
- [x] Fix OpCompleter
- [x] Remove uses of `do` from library and tests (e.g. `do Foo.bar` becomes just `Foo.bar`)
- [x] Remove syntax for `do` from Parser and Lexer (Magnus)
- [x] Remove keyword from VSCode, highlight.js, etc.
- [x] Update doc.flix.dev

**Comment by sockmaster27** [comment]
TODO: Ace

**Comment by magnus-madsen** [comment]
Ace and then we are done.

**Comment by magnus-madsen** [comment]
ACE is a web editor.
