### ISSUE TITLE
Unconditional Recursion

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#893]
Add a check to `Redundancy` which ensures that a function does not recurse on all paths.

For example,

```
def map(f: a -> b, xs: List[a]): List[b] = match xs {
    case Nil => map(f, Nil)
    case x :: rs => f(x) :: map(f, rs)
}
```

cannot terminate and should be reported as an error.

NB: Must account for currying.

See also: [unconditional recursion](https://doc.rust-lang.org/rustc/lints/listing/warn-by-default.html#unconditional-recursion)

**Comment by mlutze** [comment]
WIP here: https://github.com/mlutze/flix/commit/66b4f9ed85f48079f92f1e051497befaba9b6697

**Comment by magnus-madsen** [comment]
Cool! If you open a PR I can look at in detail and give some feedback on the code.

**Comment by mlutze** [comment]
I've opened a PR here: https://github.com/flix/flix/pull/940
It's still really rough but some direction would certainly be appreciated!

**Comment by magnus-madsen** [comment]
Merged into master.
