### ISSUE TITLE
Reduce usage of `StringBuilder` in library

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#9037]
As a continuation of #8861, I would like to reduce usage of StringBuilder in the library by using Iterator and `join`.

For example:

![image](https://github.com/user-attachments/assets/5e5a9618-39cb-48de-a0d7-a55daaecc3ad)

**Comment by magnus-madsen** [comment]
Ultimately the goal is that most-- but not all -- modules will not depend on string builder.

**Comment by magnus-madsen** [comment]
Did we succeed in this?

**Comment by sockmaster27** [comment]
> Did we succeed in this?

Haven't looked at it yet

**Comment by sockmaster27** [comment]
What about inside `Iterator.join` and `Foldable.join`? Is the goal to completely break the dependency, or just to move it outside of most of the files?

**Comment by magnus-madsen** [comment]
> What about inside `Iterator.join` and `Foldable.join`? Is the goal to completely break the dependency, or just to move it outside of most of the files?

I think thats OK
