### ISSUE TITLE
Economize use of `!` functions

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#9061]
We want to drop `!` from function names:

The idea is simply to rename a function, e.g. `push!` to just `push`. 

If there is already a function with that name then it is dropped. For example, we drop `sort` and `sort!` becomes the new sort.

We can start with these modules:

- [x] `MutList`
- [x] `MutMap`
- [x] `MutSet`
- [x] `Array`
- [x] Update doc.flix.dev

**Comment by magnus-madsen** [comment]
@sockmaster27 One PR per module

**Comment by sockmaster27** [comment]
What about StringBuilder?

**Comment by magnus-madsen** [comment]
> What about StringBuilder?

Yes, lets do that after the others.

**Comment by magnus-madsen** [comment]
@sockmaster27 Remaining modules:

- [ ] Vector (internal private functions)
- [ ] StringBuilder
- [x] ~File --- but skip it will be deleted~
- [x] ~Files --- but skip it will be deleted~
- [ ] Regex

For now we leave `unreachable!` as just that. (Ditto for `bug!`)

**Comment by magnus-madsen** [comment]
We missed: `MutDeque` but that is the last.

**Comment by sockmaster27** [comment]
Done?

**Comment by magnus-madsen** [comment]
Yes 🚀 !
