### ISSUE TITLE
Rework `IOError`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#9088]
Come up with a new collection of cases... Inspired by Java and Rust

**Comment by magnus-madsen** [comment]
@sockmaster27 Will you propose in this ticket a new set of cases? Thanks

**Comment by sockmaster27** [comment]
I believe these would be appropriate to include
- Generic
- InvalidPath
- AlreadyExists
- NotDirectory
- UnsupportedOperation

Though these are not always applicable, so maybe it should be split further?

**Comment by magnus-madsen** [comment]
I kind-of like what they have done in rust. They have one giant enum `ErrorKind`: https://doc.rust-lang.org/std/io/enum.ErrorKind.html which is the kitchen sink. Then they define `IOError` on top. We could do the same:

```
enum ErrorKind { ... }

enum IoError(String, ErrorKind)
```

**Comment by magnus-madsen** [comment]
OK: I want this design:

```
enum ErrorKind with Eq {
    case AlreadyExists,
    case PermissionDenied,
    case NotFound,
    case NotADirectory,
    case Interrupted,
    case InvalidPath,
    case UnexpectedEof,
    case Unsupported
    case Other
}

enum IoError(ErrorKind, String)
```

Maybe this is not the final design (we can iterate), but let us make it version 1.0

Note 1: I deliberately named it IoError to avoid a clash with IOError
Note 2: The string is just whatever message the Java exception provides. It is meant for debugging not for programming.

**Comment by magnus-madsen** [comment]
> Sounds good, but I don't think we can detect all of those errors from the java operations.

I know. But you should have enough choice now that you can map each Java exception to something meaningful.
 
> Is the intention to have both `IOError` and `IoError`?

Very short term yes, long term no. When File and Files die, IOError will die too.
