### ISSUE TITLE
Add automatic boxing/unboxing to `TypeReconstruction` for arguments to `InvokeConstructor/InvokeMethod/InvokeStaticMethod`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#9130]
- For each expression passed as a parameter, we should check if it needs to be boxed or unboxed.
- Return types are never boxed/unboxed.
- We should probably extend `TypedAstOps` with `mkBoxInt32`, `mkUnboxInt32` and so forth.

**Comment by magnus-madsen** [comment]
> This is one option but we could also disallow it during resolution to be consistent with the rest of flix

Unfortunately not without writing our own resolution logic.

**Comment by JonathanStarup** [comment]
In this case its quite easy to add on top, since its just 
1. call lib
2. check that boxing didn't happen for each param (check that seven concrete pairs of types didn't happen)

isn't that easier and also possibly better design?
