### ISSUE TITLE
Add basic tests for `FilePath` and friends

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#9131]
We don't need tests for everything, but I would like 5-8 tests like:

```
@Test
def exists01(): Unit \ IO = 
  FilePath.handle(() -> FilePath.exists("foo.txt"))()
```

or something like that.

**Comment by sockmaster27** [comment]
Wouldn't we want to assert whether or not the file actually exists?
Should `handle` pass through the return value of the inner function?

**Comment by magnus-madsen** [comment]
> Wouldn't we want to assert whether or not the file actually exists? Should `handle` pass through the return value of the inner function?

We could ask for a file we know exists.

> Should handle pass through the return value of the inner function?

What do you mean?

**Comment by sockmaster27** [comment]
Right now `FilePath.handle(() -> FilePath.exists("foo.txt"))()` returns unit. If we want to assert that `FilePath.exists("foo.txt")` actually returns the correct value, we'd have to use a mutable ref or something, which is annoying when we could just let the whole expression return the inner boolean.

**Comment by magnus-madsen** [comment]
> Right now `FilePath.handle(() -> FilePath.exists("foo.txt"))()` returns unit. If we want to assert that `FilePath.exists("foo.txt")` actually returns the correct value, we'd have to use a mutable ref or something, which is annoying when we could just let the whole expression return the inner boolean.

Are you sure? I think it should return `Result[IoError, Bool]`?

**Comment by sockmaster27** [comment]
nvm, just me being confused at 12am
