### ISSUE TITLE
Additional improvements to `MagicCompleter`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#9166]
We need one more pass over the magic completer. Here is my TODO list:

- [x] Fix a crash where if an enum is empty `enum Empty {}` we get a `java.lang.UnsupportedOperationException: empty.max`
- [x] Remove unused imports
- [x] Remove extra linebreaks between method comments and their bodies
- [x] Update the doc/comment for getCompletions to accurately reflect the indentation
- [x] Update getCaseLength to give an actual example with the computed lengths
- [x] Add explicit return types to all methods (e.g. generatedCasesString is missing one)
- [x] I think using a string builder in generateCasesString is the way to go
- [x] I would rename generateCasesString to patternMatchBody
- [x] I don't understand why padLhs needs to create a string and take its length. Why can it not be a pure arithmetic computation?

**Comment by magnus-madsen** [comment]
@stormckey I have written down several suggestions for improvements. One concerns a serious bug, the others are about code quality and maintainability. If you could take a look, thanks!

**Comment by stormckey** [comment]
Thanks for your review and all the suggestions! I will address these problems soon.
