### ISSUE TITLE
Rework and Improve Entrypoint checking

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#9185]
Issues:
- `EntryPoint` and `Safety` both somewhat handle entrypoints (bad cohesion)
- `EntryPoint` prematurely desugars main which makes some things annoying to debug
- `EntryPoint` collects entrypoints (called `reachable`) but nobody cares until the backend.

Proposal:
- `Root.entryPoint` --> `Root.mainEntryPoint` or `Root.main`
- Either
  - merge EntryPoint and Safety or
  - move EntryPoint just before Safety and call it EntryPoints. Move all entrypoint logic to EntryPoints
- Delete `Root.reachable` or rename it `Root.entrypoints`
  - Upside: less code and invariants (fx monomorpher needs to respect/update reachable)
  - Upside: less data
  - Downside: ThreeShaker1 and TreeShaker2 needs to initially traverse all defs instead of starting with the entrypoints (seem cheap?)

**Comment by JonathanStarup** [comment]
@magnus-madsen There is three "or"s in the proposal list, we can decide at the meeting?

**Comment by magnus-madsen** [comment]
- We agreed entryPoint -> mainEntryPoint
- Phase EntryPoint -> EntryPoints
- Move all checks out of Safety into EntryPoints

Algorithm:
1. Collect reachable def syms
2. Check each def sym
  - Main: Non polymorphic, Unit to ToString, only primitive effects
  - Test: Non polymorphic, Unit to Anything, only primitive effects
  - Export: Non polymorphic, Primitive/Object to Anything, only primitive effects


- Add a special error for non-primitive effect (i.e. unhandled algebraic effect) (Please handle ABC)

**Comment by magnus-madsen** [comment]
Fixed
