### ISSUE TITLE
LSP acceptor with skip

### ISSUE THREAD

**Issue by LoZander** [flix/flix#9199]
The current LSP Acceptor has this limitation wherein there is no way to visit a node's children without visting the node and invoking the consumer on it. This is an issue if you, for instance, want to visit the children of synthetic nodes but not the synthetic nodes themselves.

I propose a solution in which we generalise the signature of `accept` to output not a boolean but an enum with three cases
1. Accept: this means the node is visit/consumed and we visit it's children
2. Skip: this means that the node is _not_ visit/consumed, but it's children are
3. Stop: this means the recursion ends here.

Comparing to the current `accept`, case 1) corresponds to true and 3) corresponds to false. The new is 2). So this new model would be strictly more expressive and all current code using the Acceptors can easily be refactored to use this new model.

**Comment by LoZander** [comment]
@magnus-madsen what do you think?

**Comment by LoZander** [comment]
Overengineered or maybe that kind of "filtering" of synthetic nodes should simply take place at the use-site of the visitor?

**Comment by LoZander** [comment]
Alternatively we could just add an additional signature to the trait `skip`, that returns `true` if a node in shoud be skipped even if otherwise visited. But then if a node is already not accept, the function is irrelevant. If Skip wants to "skip" something that the acceptor would already reject, it might not be completely clear what that would do. I'd want that to mean it's not visited at all, that `accept` "over rules" `skip`. Really, `skip` is more like a special case of `accept`, or a third case all together, hence the three case proposal

**Comment by JonathanStarup** [comment]
> maybe that kind of "filtering" of synthetic nodes should simply take place at the use-site of the visitor?

I'd vote this - keep the visitor as simple as possible

**Comment by LoZander** [comment]
Yeah, I can totally see that. It's just a bit awkward, but maybe it's better to have a bit more responsibility at the use-site as opposed to increasing the complexity of the visitor

**Comment by LoZander** [comment]
Although most of the complexity introduced would be contained to the visitor itself. For a user of the visitor, they just need to deal with a slightly more complex acceptor. And the changes to the visitor are fairly boiler plate (just an additional check before consuming. But it does complicate the model of the visitor, that's true

**Comment by LoZander** [comment]
But then again, all it adds is effectively filtering, which I suspect would often be fairly easy to just do at the use-site

**Comment by LoZander** [comment]
Well I suppose that depends on what the consumers do. If the consumers do something directly, there might not be a way to "filter" that out afterwards, as if something is visited it _is_ consumed. But then you can filter stuff out in the consumer if you really need to. For all the uses we've seen so far, it's easy enough to filter synethic stuff out afterwards.

**Comment by LoZander** [comment]
Sorry for the short novel I just rough

**Comment by JonathanStarup** [comment]
Having the `accept` function say `skip` if `cond(x)` is the same as as the consume function starting with `if (cond(x)) /* do nothing */ else ..` right? Just making sure in order to compare the two

**Comment by LoZander** [comment]
yes, that's right. I guess there is actually little argument for not just leaving it up to the consumer. And if it gets too boilerplaty at someone, some abstraction on consumers can be introduced or something. I already have an idea or two, but maybe it never becomes an issue
