### ISSUE TITLE
Improve magic match completion when working with brackets

### ISSUE THREAD

**Issue by stormckey** [flix/flix#9202]
A problem with the current magic match completion is that it won't work with expressions in brackets.

Here is a example:
```
enum Color {
    case Red
}

def b(c: Color): Unit = 
    (c).ma 

```

Although a CompletionItem is sent back by the lsp, no suggestions pop up when typing `match`.

Another problem is that the generated match expression will not include the brackets, since the base expression stored in `FieldNotFound` ignores the brackets outside.

**Comment by stormckey** [comment]
@magnus-madsen Here is the ticket, any ideas?

**Comment by magnus-madsen** [comment]
I wonder if it is because the parser ignores the parens in this case?

What happens if you write:

```
f(1, 2, 3).mat
```

Does that work?

What about

```
(123, 456).mat
```
Does that work?

(By the way, we should probably extend the magic completer to support tuples as above)

**Comment by stormckey** [comment]
```
f(1, 2, 3).mat
```
works just fine. But if the brackets affect only precedence, they seem to be ignored. By the way, generating match expression without brackets works fine too. It's just a formatting problem. The main problem, I think, may be that the completion suggestion is somewhat rejected by the client.

The tuple example doesn't work since we only offer completion for enums. So adding support for tuples means a pattern matching with only one case, right?

**Comment by magnus-madsen** [comment]
>  But if the brackets affect only precedence, they seem to be ignored. 

Yes, thats probably the case.

> By the way, generating match expression without brackets works fine too. It's just a formatting problem. The main problem, I think, may be that the completion suggestion is somewhat rejected by the client.

Yeah, I wonder why VSCode skips it / does not show it?

**Comment by stormckey** [comment]
> Do you think that would be possible?

I think it's possible. I'll start a new pr to support tuples later :)

**Comment by JonathanStarup** [comment]
no judgement on their choice, but IntelliJ/scala does have the tuple version. looks cool though.

**Comment by magnus-madsen** [comment]
> no judgement on their choice, but IntelliJ/scala does have the tuple version. looks cool though.

I don't understand.

**Comment by JonathanStarup** [comment]
if you have `(e1, e2) mat|` then intellij doesnt suggest `match (exhaustive)`

**Comment by magnus-madsen** [comment]
> if you have `(e1, e2) mat|` then intellij doesnt suggest `match (exhaustive)`

OK. But we can, and you think it would be cool?
