### ISSUE TITLE
Rework Root.names to hold two maps (and use in CodeActionProvider)

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#9228]
We are currently using `ClassList.TheList` for import quickfixes. But actually this is not entirely correct because JARs that are included in a project do not appear in `ClassList.TheList`. Instead,  `TypedAst.Root` has a field: `names: MultiMap[List[String], String]`. This maps each package name to its classes. The problem is that we need the reverse map (from a class name to a set of packages). We could compute this map from `names` all the time, but that is too slow.

Instead, I propose we introduce (in package `ast.shared`):

```scala
/**
  * @param byPackage a map from a package name to a set of classes (and interfaces) in that package.
  * @param byClass a map from a class (or interface) to the packages that it occurs in.
  */
case class AvailableClasses(byPackage: MultiMap[List[String], String], byClass: MultiMap[String, List[String]])
```

We then need to replace `private var knownClassesAndInterfaces` in `Flix.scala` with this new type.

Then we can use `root.availableClasses` in CodeActionProvider.

**Comment by magnus-madsen** [comment]
@stormckey CC

**Comment by stormckey** [comment]
So which root should we use to build the AvailableClasses in Flix.scala

**Comment by magnus-madsen** [comment]
> So which root should we use to build the AvailableClasses in Flix.scala

We should build and maintain AvailableClasses in Flix.scala.

Then every AST root should have a reference to that object. (You can see how the `names` field is used today.)
