### ISSUE TITLE
Extend `CodeActionProvider` to support `UndefinedTag`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#9230]
Example:

```
enum Color {
  case Red,
  case Green
}

def foo(): Color = Red // propose to "use Color.Red"
```

**Comment by magnus-madsen** [comment]
@stormckey CC

**Comment by stormckey** [comment]
Yes, but the error reported in the above case is undefined name.

So what does undefined tag actually mean? how can we distinguish between them?

**Comment by stormckey** [comment]
Got it.

So how should we solve the this error? We could search "Red" in all the enums in the root, but that's definitely not a good idea.

It would be great if we could access the type to be matched.

**Comment by magnus-madsen** [comment]
> So how should we solve the this error? We could search "Red" in all the enums in the root, but that's definitely not a good idea.

That is actually what we have to do. We start with TypedAst.Root

There we have to go through this map:

enums: Map[Symbol.EnumSym, Enum],

Each Enum is:

case class Enum(doc: Doc, ann: Annotations, mod: Modifiers, sym: Symbol.EnumSym, tparams: List[TypeParam], derives: Ast.Derivations, cases: Map[Symbol.CaseSym, Case], loc: SourceLocation)

where `cases` will contain a CaseSym equal to "Red".

**Comment by stormckey** [comment]
Ok I'll implement that.

**Comment by magnus-madsen** [comment]
> Ok I'll implement that.
> 
> I just think that there are too much enums in the prelude so it could be time-consuming.

The number of enums is significantly smaller than the total size of the program. It will be very fast. Even if there are thousands of enums (which there are not).

**Comment by magnus-madsen** [comment]
@stormckey I think this is done?

**Comment by stormckey** [comment]
> @stormckey I think this is done?

Yes
