### ISSUE TITLE
Update CI Tests

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#9236]
We've had a lot of recent breakages (sorry), but I think the worst is over now. It would be good to bring our CI to green again.

So:

- [x] @sockmaster27? IDE tests fail (but not locally?)
- [x] @JonathanStarup community-build (JonathanStarup/Flix-ANSI-Terminal) fails because we renamed `Console.run`
- [x] @stephentetley  community-build (stephentetley/charset-locale) (pull_request) fails because effect operations are now implicitly pub.

In addition there are two upcoming breakages. You can account for them now, if you wish:

- It is now `run-with` and not `try-with`
- We will remove `File` and `Files`. The replacement is either (a) std Java interop or (b) use of `ReadFile/WriteFile` effect.

**Comment by magnus-madsen** [comment]
@mlutze I think flixball is the only one left.

**Comment by mlutze** [comment]
Flixball is done
