### ISSUE TITLE
Add `additionalTextEdits` field to `CompletionItem`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#9247]
See https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItem

This will allow us to insert import/use declarations together with auto-completions in the future.

**Comment by stormckey** [comment]
Something like this?
<img width="290" alt="image" src="https://github.com/user-attachments/assets/fbc70405-dbf3-44b1-87e2-e48edaf99318">
if we choose a completion item of `Math`(currently absent)
<img width="304" alt="image" src="https://github.com/user-attachments/assets/06978e16-27ca-4098-a3bc-accc1a267da5">

The `additionalTextEdits` field could allow us to do this.

**Comment by magnus-madsen** [comment]
Yes -- that is the ultimate goal.

**Comment by stormckey** [comment]
I’ll start a pull request to implement this once the pull request for AvailableClasses has been merged. This way, we can leverage AvailableClasses.

**Comment by magnus-madsen** [comment]
I suggest to create a PR that only changes CompletionItem

**Comment by stormckey** [comment]
> I suggest to create a PR that only changes CompletionItem

Yeah that's also what I think. I've already written some code and now wait for rebasing.
