### ISSUE TITLE
Rework `CompletionProvider` to be scope aware

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#9248]
We would like that if we write:

```
use Validation.map5

def main(): Unit \ IO =
    let foobar = 123;
    map
```

then we should be suggested "map5". This will require us to extend `ResolutionError.UndefinedName` (among others) with additional information.

Action plan:

- [x] Move `Resolver.Resolution` to `ast.shared`.
- [x] Introduce `case class Scope(env: ListMap[String, Resolution])` in `ast.shared` and refactor `Resolver` to use it.
- [x] Add `Scope` to `UndefinedName` (and similar errors).
- [x] Extend `CompletionProvider` with some `ScopeCompletionProvider`. 
- [x] Drop `VarCompleter`

**Comment by magnus-madsen** [comment]
@stormckey We should discuss this in more detail, but I wanted to write down the steps while I had them in my mind. I suggest to wait with this ticket until we have made more progress on the other tickets.

**Comment by magnus-madsen** [comment]
I think each bullet point should be a separate PR to keep things simple-- but lets talk over Zoom.

**Comment by stormckey** [comment]
oops, there is already a scope in ast.shared:
<img width="793" alt="image" src="https://github.com/user-attachments/assets/4652881f-40cf-4c46-90b9-17cf561548fb">

**Comment by magnus-madsen** [comment]
> oops, there is already a scope in ast.shared: <img alt="image" width="793" src="https://private-user-images.githubusercontent.com/109893671/388432600-4652881f-40cf-4c46-90b9-17cf561548fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxODA1MDcsIm5iZiI6MTczMjE4MDIwNywicGF0aCI6Ii8xMDk4OTM2NzEvMzg4NDMyNjAwLTQ2NTI4ODFmLTQwY2YtNGM0Ni05MGI5LTE3Y2Y1NjE1NDhmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQwOTEwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZWViMzAyNmYyNTVjMWYwNTk0OTM3ZTE3NjcxZjA0M2RhZmIwOWZhZDhlOTZmNTYxODhkY2MxMWMwMmRiYjBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Wlv47HSiFwbGA9bs-zDRmpzkOV0X2YH4W9em0cRETMY">

OOps. Lets call it "LocalScope" for lack of a better name.

**Comment by stormckey** [comment]
Okay, so I think "refactor `Resolver` to use it" means replace `ListMap[String, Resolution]` to LocalScope like this?
<img width="1239" alt="image" src="https://github.com/user-attachments/assets/37b6807e-6585-4335-89a0-cf82d5647b8a">

**Comment by magnus-madsen** [comment]
> Okay, so I think "refactor `Resolver` to use it" means replace `ListMap[String, Resolution]` to LocalScope like this? <img alt="image" width="1239" src="https://private-user-images.githubusercontent.com/109893671/388437427-37b6807e-6585-4335-89a0-cf82d5647b8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxODA5ODQsIm5iZiI6MTczMjE4MDY4NCwicGF0aCI6Ii8xMDk4OTM2NzEvMzg4NDM3NDI3LTM3YjY4MDdlLTY1ODUtNDMzNS04OWEwLWNmODJkNTY0N2I4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQwOTE4MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMGEwODYxZDcwZWFhZWRlM2E5OTQ4ODA0MGUzZTNjMzhhZDBhZmYyNzhlNTM2NTQxOGNlNDY2ZDVhMWRiZTU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._Sk3u-AxJajog8Iu5OsPVoyCHCUQeMEIS5P8yX7S5ow">

Yes. That is right.

Because then later we can add LocalScope to UndefinedName error etc. and access it in CodeActionProvider 👍

**Comment by magnus-madsen** [comment]
> > * Extend `CompletionProvider` with some `ScopeCompletionProvider`.
> 
> I think the `AutoImportCompleter` in #9276 would be one of this, also we can change `VarCompleter` to use LocalScope, any other completion?

Yes. Probably we can rework VarCompleter to be called LocalScopeCompleter.

**Comment by stormckey** [comment]
> Yes. Probably we can rework VarCompleter to be called LocalScopeCompleter.

Currently VarCompleter is triggered by SyntacticCompletion. Maybe we can delete that and introduce LocalScopeCompleter for UndefinedName in SemanticCompletion?

**Comment by magnus-madsen** [comment]
Continued in #9299
