### ISSUE TITLE
All `mkUseX` in `CodeActionProvider` should only propose visible names

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#9249]
We should not propose private names so: A name should

- be public or
- be in the root module or
- be in the same namespace

**Comment by stormckey** [comment]
Yes that makes sense, but how can we check that?

As far as I can see, we can get the namespace of a symbol by accessing its field. But we'll still need the current namespace.

And how can we check the other two conditions?🤔

**Comment by magnus-madsen** [comment]
> Yes that makes sense, but how can we check that?
> 
> As far as I can see, we can get the namespace of a symbol by accessing its field. But we'll still need the current namespace.
> 
> And how can we check the other two conditions?🤔

Lets start by checking that the declaration is public. So if you have a symbol, e.g. EnumSym, then lookup the declaration in root.enums(sym) and check that it has the modifier `Public`.
