### ISSUE TITLE
Add swing examples

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#9278]
Add two more swing examples like the one in `examples/swing`:

- [ ] One with a single button that can be clicked to open a dialog (Yes, No, Unsure)
  - The point is to show how to use event listeners.
- [ ] One with a layout of 9 buttons like on a phone (1, 2, 3 \\ 4, 5, 6 \\ 7, 8, 9). 
  - The point is to show to use more complex layout.

This is really just a Swing programming exercise in Flix.

**Comment by magnus-madsen** [comment]
@jaschdoc You should try to use the latest master and report back how well the quickfixes / autocompete helps you.

Especially when https://github.com/flix/flix/pull/9276 is merged.

**Comment by jaschdoc** [comment]
Do you want me to use higher order functions or effects?

**Comment by magnus-madsen** [comment]
For these examples, as simple as possible
