### ISSUE TITLE
Add support for auto-import to auto-completions

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#9291]
In the style of #9276. A few things to address:

- [ ] Building on #9248, we need to use `Scope` to ensure that we _do not propose completions (with imports) of names that are already in scope.
- [ ] We should ensure the feature works consistently. This means we need to check a lot of boxes:
  - [ ] Java types
  - [ ] Flix types: enums, effects, structs, type aliases, etc..
  - [ ] Flix defs, effect operations, and signatures

We should also ensures that:

- Suggestions are not duplicated
- Suggestions appear in some meaningful order
- We reuse code-- we don't want to duplicate the completer code

**Comment by stormckey** [comment]
I think #9276 has already solved the first part of the problem. But I can't much understand the left part. Does it mean we support auto-use if the type of def is not there, while avoid duplicated using?

**Comment by stormckey** [comment]
Yeah and I think the low priority thing has also been completed. I am just not sure why these things are involved:

> * [ ]  We should ensure the feature works consistently. This means we need to check a lot of boxes:
>   
>   * [ ]  Java types
>   * [ ]  Flix types: enums, effects, structs, type aliases, etc..
>   * [ ]  Flix defs, effect operations, and signatures

**Comment by magnus-madsen** [comment]
Ah- right now you only suggest local variables in scope right?

But if we have

import java.bla.bla.VeryLongName

I want to be able to write Ve|  in a type position and have it completed.

Same for everything else in the Resolution class.

**Comment by stormckey** [comment]
OK, I think we'll solve this problem in LocalScopeCompleter.

**Comment by magnus-madsen** [comment]
I am closing this to write a new issue that is more clear.
