### ISSUE TITLE
Introduce `LocalScopeCompleter`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#9299]
- [x] Rename `VarCompleter` to `LocalScopeCompleter`
- [x] Add completions for:
  - [x] case class Declaration(decl: NamedAst.Declaration) extends Resolution
  - [x] case class JavaClass(clazz: Class[?]) extends Resolution
  - [x] case class Var(sym: Symbol.VarSym) extends Resolution - **ALREADY DONE**
  - [x] case class LocalDef(sym: Symbol.VarSym, fparams: List[ResolvedAst.FormalParam]) extends Resolution
  - [x] case class TypeVar(sym: Symbol.UnkindedTypeVarSym) extends Resolution - **SKIP**

**Comment by stormckey** [comment]
Shall we still use LocalScopeCompleter or use all the VarCompleter... separately?

Another problem is where should we put these completer? SyntacticCompletion or SemanticCompletion? I put VarCompletion for it to access `err` and `err.env` directly, which is convenient.

**Comment by magnus-madsen** [comment]
> Shall we still use LocalScopeCompleter or use all the VarCompleter... separately?
> 
> Another problem is where should we put these completer? SyntacticCompletion or SemanticCompletion? I put VarCompletion for it to access `err` and `err.env` directly, which is convenient.

I am proposing to have one completer: LocalScopeCompleter. 

Its a semantic completer.

**Comment by stormckey** [comment]
Cool, let's fill it out!
