### ISSUE TITLE
Rework `RenameProvider` to use LSP visitor instead of Index

### ISSUE THREAD

**Issue by LoZander** [flix/flix#9348]

**Comment by LoZander** [comment]
While working on this, I've run into an issue relating to `use`s. When renaming, for instance, enum cases, if these are imported, we have to rename them in the `use` import.

For instance, for
```
enum Color {
  case Red,
  case Blue,
  case Green
}

def f(c: Color): Color = {
  use Color.{Red, Blue, Green}
  
  match c {
    case Red => ???
    ...
  }
}
```

If we rename the `Red` case, it should also change the name in the `use`, but currently the LSP visitor doesn't visit uses at all, so it doesn't allow us do this. I think this should be fixed, but I don't know how important this is right off the bat. Should I immediately expand the visitor or should this issue be left alone for now, to be handled in a follow up for instance? Would it be too big an issue for `use`s to not be handled by the rename provider in the initial version of the rename provider?

**Comment by magnus-madsen** [comment]
I believe this is currently broken right? So you would just leave it as broken?

**Comment by LoZander** [comment]
Yes. It is currently broken. So for now, I'll leave it broken :)

**Comment by LoZander** [comment]
There're also some deeper question about enums and cases relating to how their occurrences are represented in the AST.

Currently, something like `Color.Red` counts as an occurrence of the case `Red` with no information regarding the occurrence of the enum symbol `Color`. There is not specific location for the occurrence of the EnumSymbol `Color` either. This has implications for highlighting and hover as well, but it's more noticable here for the rename provider.

1) if you're trying to rename the case `Red` then in all occurrences of `Color.Red` we need to manually extract the source location for just the `Red` part, since currently the sourcelocation of the occurrence of red includes `Color.`. This can be worked around, but it's a little awkward, especially since an occurrence of `Red` might *not* include `Color.` if the case is imported in the current scope.

2) when trying to rename with the cursor at `C|olor.Red`, wouldn't you assume that you're trying to rename the enum itself? Currently, there is no easy way to support that, since you'd have to recognise that you're actually in the occurrence of the enum symbol not the case itself and with the current model we don't distinguish those. If you're anywhere in `Color.Red`, you're in the occurrence of the case symbol `Red`. You could with some extra logic figure this out, but it's a bit awkward, much like the for previous point.

Ideally, the AST would simply track occurrences of enum symbols as well. Maybe if we had a `SymUse.EnumAndCase` that contained both a `SymUse.Enum` and a `SymUse.Case` or something like that. Then `Color.Red` would be `SymUse.EnumAndCase(SymUse.Enum(...), SymUse.Case(...))` and when `Color.Red` is imported locally, and we have just `Red`, then this would be a `SymUse.Case(...)` without a `SymUse.EnumAndCase` parent. Something like that would be ideal, I think.

Currently, for 1) I do some local logic to figure out where the actual case symbol part starts, so only that part is renamed. It's a bit of a hack, but it seems to work. It's certainly better than before, where renaming the case `Red` to `Orange` would change occurrences like `Symbol.Red` to `Orange`, which is simply wrong. But it's still not the cleanest solution and it feels a bit fragile. As for 2), I'm thinking I'll just, for now, handle renaming where the cursor is at `S|ymbol.Red` and `Symbol.R|ed` the same, both as a renaming of the case symbol, and not the enum symbol. Then you have to actually rename the enum symbol where it occurs as a type or at it's definition site.

So I have a couple of questions:
a) are these current solutions I've come up with fine for now?
b) should we change the AST to also track occurrences of the enum symbols within case symbol occurrences to enable the LSP visitor to visit these or should we just keep handling this locally?

Also, if you have any other thoughts on this, I'd love to hear them :)

**Comment by magnus-madsen** [comment]
I agree that we need more precise symbols and source locations. But I suggest to keep focus. Get rid of the index and then solve these issues.

**Comment by LoZander** [comment]
Yep. I'll make the providers as good as I can within the current model and then if time allows for it maybe we can look at these things afterwards :)

**Comment by LoZander** [comment]
So, it's mostly done. I need to consider whether or not it makes sense to rename record fields. I also need to do some clean up. But otherwise I think we're basically there

**Comment by magnus-madsen** [comment]
Records are structural so you cannot really rename their fields.
