### ISSUE TITLE
Add support for `CompletionItemLabelDetails`?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#9349]
LSP now supports something called `CompletionItemLabelDetails`.

See

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItemLabelDetails

How does it work? What does it look like in the completion box if this extra information is provided?

**Comment by magnus-madsen** [comment]
@stormckey Could you try to find out if this will allow us to have "prettier" completions than now? What does it look like?

**Comment by magnus-madsen** [comment]
Right now AutoImportCompleter shuffles everything into label. But if we used CompletionItemLabelDetails everything might be more pretty.

**Comment by magnus-madsen** [comment]
@stormckey I think this task should be next. I think this will help us deal with the overwhelming number of completions we are now offering :)

**Comment by stormckey** [comment]
Okay, let's deal with other things first.

**Comment by magnus-madsen** [comment]
> Okay, let's deal with other things first.

My suggestion was maybe exploring this now would be a big help moving forward.

But we can also begin by trimming the suggestions. 

But I think this ticket should be high priority, but it does not have to be 1st thing.

**Comment by stormckey** [comment]
Got it.

**Comment by stormckey** [comment]
Here is how it looks like:
<img width="1137" alt="image" src="https://github.com/user-attachments/assets/624332e7-82fa-4eef-b95d-044178475929">

As said in the document, `detail` can be used for signature and `description` can be used for qualified name.

**Comment by stormckey** [comment]
I think we can move the path to `description` and remove it from documentation and label.

Should we use `import path` or just `path`?

**Comment by magnus-madsen** [comment]
> Here is how it looks like: <img alt="image" width="1137" src="https://private-user-images.githubusercontent.com/109893671/390788712-624332e7-82fa-4eef-b95d-044178475929.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3OTk4ODUsIm5iZiI6MTczMjc5OTU4NSwicGF0aCI6Ii8xMDk4OTM2NzEvMzkwNzg4NzEyLTYyNDMzMmU3LTgyZmEtNGVlZi1iOTVkLTA0NDE3ODQ3NTkyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxMzEzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YmNjZTUzOGQwMTg2OGZkOTAzYTI4MmJiYzYyYzY4MGJlYWViYjM0YjFhNzJhZDIzMmI4M2RjZDczOTcyNTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4bYIuZdB-lfe-USYIqe-q5ayDbHrEUL3Bx3xf96Eloo">
> 
> As said in the document, `detail` can be used for signature and `description` can be used for qualified name.

This seems useful to us, right? So we should definitely add it?

**Comment by magnus-madsen** [comment]
> I think we can move the path to `description` and remove it from documentation and label.
> 
> Should we use `import path` or just `path`?

Let call it namespace or  qualified name. But yes, I think that would be nice.

The internet also suggests to use the first detail for the arguments
