### ISSUE TITLE
Whether to merge two DefCompletion?

### ISSUE THREAD

**Issue by stormckey** [flix/flix#9351]
We may want to merge `DefCompletion` and `LocalDefCompletion`. But here are some problems:

Here is the definition of `Resolution.LocalDef`, where we can not access something like `sepc`:
<img width="877" alt="image" src="https://github.com/user-attachments/assets/50f11108-6b5e-4f9f-a8e6-5212b4e3425a">
<img width="1245" alt="image" src="https://github.com/user-attachments/assets/adf4005d-d949-4924-aed6-6cfbb62adcc1">

As a result, a lot of information used in `DefCompletion` is not available for `LocalDefCompletion`:
![](https://github.com/user-attachments/assets/f4ab871f-b287-4d61-b767-8f3f4ee53ebe)

And we can not reuse some functions because of type mismatch: The `fparams` in `LocalDefCompletion` is `ResolvedAst.FormalParam` while in `DefCompletion` it's `TypedAst.FormalParam`. Similary, the spec for `Resolution.Declaration(Def)` is `NamedAst.Spec` instead of `TypedAst.Spec`, the latter is used by current `DefCompletion`.

I think the extra information that `DefCompletion` is providing is valuable, so we'd better not delete that. Unless there are ways to obtain the same amount of information for local def, I suggest we just keep both of them.

**Comment by magnus-madsen** [comment]
Yes. I don't think we can merge them. 

But in the future, we may be able to track some more type information so then we can know the number of arguments etc.

But for now there is not much to do.

**Comment by stormckey** [comment]
> Yes. I don't think we can merge them.
> 
> But in the future, we may be able to track some more type information so then we can know the number of arguments etc.
> 
> But for now there is not much to do.

But the type mismatch problem remains. The main reason is that the Resolution is produced in a middle phase of compiling, while most other code is using TypedAst. So it's hard to match them.

A straightforward choice is to only use LocalScope to check existence of items, but find the detailed information from other places(like root).

**Comment by magnus-madsen** [comment]
> > Yes. I don't think we can merge them.
> > But in the future, we may be able to track some more type information so then we can know the number of arguments etc.
> > But for now there is not much to do.
> 
> But the type mismatch problem remains. The main reason is that the Resolution is produced in a middle phase of compiling, while most other code is using TypedAst. So it's hard to match them.
> 
> A straightforward choice is to only use LocalScope to check existence of items, but find the detailed information from other places(like root).

Yes, you are right.

**Comment by magnus-madsen** [comment]
(But LocalDef is different from Def, so there is no symbol you can look up, unfortunately.)

**Comment by stormckey** [comment]
> (But LocalDef is different from Def, so there is no symbol you can look up, unfortunately.)

Sad
