### ISSUE TITLE
What to use as the documentation for a java class

### ISSUE THREAD

**Issue by stormckey** [flix/flix#9354]
Currently the documentation of an auto import completion is just a repetition of the path:

<img width="764" alt="image" src="https://github.com/user-attachments/assets/358c525b-0a3f-4798-b163-0f19e48103bf">

which is redundant and useless. I suggest to delete that or find some other information to fill in.

**Comment by magnus-madsen** [comment]
Yeah, not sure we have anything. I don't think the reflective Java class maintains the documentation.
