### ISSUE TITLE
Improve Completion Item Readability with CompletionItemLabelDetails

### ISSUE THREAD

**Issue by stormckey** [flix/flix#9365]
Here are the Completions that I think can be improved with a CompletionItemLabelDetails:

- [x] AutoImportCompleter
- [x] AutoUseCompleter
- [x] DefCompleter
- [x] LocalScopeCompleter

Any other ideas?

**Comment by magnus-madsen** [comment]
It looks like a good start at least 👍

**Comment by magnus-madsen** [comment]
- [ ] InvokeMethodCompleter (similar to DefCompleter)
- [ ] SignatureCompleter (similar to DefCompleter)
- [ ] OpCompleter (similar to DefCompleter)

**Comment by stormckey** [comment]
I think this ticket has been done.

The label for most Completion is concise now.
