### ISSUE TITLE
String Escapes

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#937]
Add support for string escapes, e.g. `\n`, and so forth.

**Comment by mlutze** [comment]
Looks like Java 14 introduces something to make this an easier change: [translateEscapes()](https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/lang/String.html#translateEscapes()).

That's assuming we want the same escapes as in Java.

**Comment by magnus-madsen** [comment]
This seems useful, but we still need to translate `\uXXXX` escapes. Also, I think the parser right now is too lenient and does not require proper escaping which I am sure will come back to haunt us.

**Comment by magnus-madsen** [comment]
Oh, and it is a preview, so let us hope that it gets merged in :)

**Comment by magnus-madsen** [comment]
@mlutze Is this now done?

**Comment by mlutze** [comment]
Yep, done!
