### ISSUE TITLE
The best way to display the label for a AutoUseCompletion?

### ISSUE THREAD

**Issue by stormckey** [flix/flix#9379]
The choice of Rust:
<img width="869" alt="image" src="https://github.com/user-attachments/assets/edd0492d-27f6-4048-ada7-5f24e5c6960e">

Which is opposite to the recommendation of lsp spec. But I think it somewhat makes sense. The qualified name of an item is displayed in the most prominent place, which is also the thing that users cases most when they try to find their target completion.

For the signature, we will always display it in for the selected item on the extra panel, together with the doc(if applicable):
<img width="1079" alt="image" src="https://github.com/user-attachments/assets/a1e20f2b-6544-4c5c-9375-530269cdaf07">

**Comment by stormckey** [comment]
If we adopt the Rust way:
<img width="1068" alt="image" src="https://github.com/user-attachments/assets/67684490-e1d8-4208-b935-495754e301c7">

The signature still takes a lot of place, we may still need to find some method to simplify that.

And a minor problem is that in our AutoImportCompleter the "import xxx" message is displayed on the right, not in the middle. But I think it's not a big problem.

**Comment by magnus-madsen** [comment]
@mlutze @JonathanStarup @jaschdoc @LoZander Let us know if you have an opinion.

**Comment by mlutze** [comment]
What about

```
maximumKey(m)                           use Map.maximumKey
```

and then in the box, the full signature?

**Comment by magnus-madsen** [comment]
> What about
> 
> ```
> maximumKey(m)                           use Map.maximumKey
> ```
> 
> and then in the box, the full signature?

The box on the right is not always shown. Worse it floats around, so sometimes its on the right and sometimes its on the bottom :S

**Comment by JonathanStarup** [comment]
the schema print is a bit insider, the flix user has never seen forall, so i'd drop the forall part. but thats maybe unrelated to this?

**Comment by magnus-madsen** [comment]
> the schema print is a bit insider, the flix user has never seen forall, so i'd drop the forall part. but thats maybe unrelated to this?

The question was not so much on formatting (that can be dealt with separately.) The question was more on what to show left and right, so to speak.

**Comment by stormckey** [comment]
> What about
> 
> ```
> maximumKey(m)                           use Map.maximumKey
> ```
> 
> and then in the box, the full signature?

That will look like this:
<img width="907" alt="image" src="https://github.com/user-attachments/assets/3bd5ac1e-53df-48cc-87f9-03d6bc114967">

**Comment by magnus-madsen** [comment]
Looking at the last screenshot, what determines the order? Many functions have the same name; what are they sorted by?

**Comment by stormckey** [comment]
> Looking at the last screenshot, what determines the order? Many functions have the same name; what are they sorted by?.

sortText in CompletionItem if applicable, otherwise label

**Comment by stormckey** [comment]
> Looking at the last screenshot, what determines the order? Many functions have the same name; what are they sorted by?.

sortText in CompletionItem if applicable, otherwise label

**Comment by magnus-madsen** [comment]
Wait. But why is `map` from `Nel` then before `map` from `List`? Thats not alphabetical

**Comment by stormckey** [comment]
> Wait. But why is `map` from `Nel` then before `map` from `List`? Thats not alphabetical

It seems that the spec from VSCode:
<img width="794" alt="image" src="https://github.com/user-attachments/assets/ea1db9e7-378a-49c4-a7e0-b180b30506c7">
is a little bit different from that from microsoft:
<img width="538" alt="image" src="https://github.com/user-attachments/assets/2697d7db-4133-463f-b6f1-3dffd091533e">

It's unclear how vscode determine the relativity in the first place. But we can not determine the order just by sortText. Here is an example:
The Priority of the local java class completion is High, while the priority for use completion is lower. 
However, VSCode choose to place MatchException in the middle of use completions. I am not sure what the reason is.
<img width="769" alt="image" src="https://github.com/user-attachments/assets/b8140f25-27ba-4195-9195-df0b58445dd5">

By the way, it seems that textEdit is deprecated:
<img width="799" alt="image" src="https://github.com/user-attachments/assets/89a9ca2b-08dd-4dfc-aef8-488da396d6ed">
