### ISSUE TITLE
Make the matching for completion more flexible.

### ISSUE THREAD

**Issue by stormckey** [flix/flix#9389]
Let's take AutoUseCompleter for example. Currently we use a `startswith` to check the matching, which means we can't type `I` in this case:
<img width="763" alt="image" src="https://github.com/user-attachments/assets/57b78fa4-ab4c-404e-a877-7b1d1035f44a">
<img width="329" alt="image" src="https://github.com/user-attachments/assets/31525a8c-f63b-419d-a5c5-657418e70f9d">
But we can employ a looser matching, like checking first three characters, and let VSCode do the filtering:
<img width="753" alt="image" src="https://github.com/user-attachments/assets/dba5b019-7b9b-41e1-83c7-35f02a29a5ed">
We can let the user skip words in later completion.

**Comment by magnus-madsen** [comment]
This should explain everything:

```

def main(): Unit \ IO = 
    mapWK
    // query:       mapK => Split into [map, K]
    // actual name: mapWithKey split into [map, With, Key]
    // Recursive from left to right
    // We have head query and head actual
    // If they the two head match (actually query is a prefix of actual) then drop both and recurse.
    // Otherwise skip head of actual, and recurse with the same query head.
```
