### ISSUE TITLE
`run-with` parsing bug

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#9403]
This program from `Test.Handler.Spawn.flix` does not work. Specifically, nesting a `run-with` block inside a function call does not work. It is still unclear to me why this happens, but I will investigate a bit further.

```flix
    def runGenAsk(tx: Sender[Int32, rc]): Unit \ rc =
        try {
            Ask.ask(
                run {
                    Gen.gen()
                } with Gen {
                    def gen(k) = k(42)
                }
            )
        } with Ask {
            def ask(x, _) = Channel.send(x + x, tx)
        }
```

**Comment by magnus-madsen** [comment]
> The `run` keyword was not fully added as keyword and as start of an expression

I see. Can we make a separate PR? Also, I think we should expand all the false cases instead of using a wildcard.

**Comment by magnus-madsen** [comment]
Thanks for debugging my mistake 👍
