### ISSUE TITLE
Simplify `Lowering.mkParYield`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#9418]
Get rid of isSpawnable (i.e. assume it returns true)

**Comment by jaschdoc** [comment]
I don't quite understand why. Could you elaborate?

**Comment by magnus-madsen** [comment]
Like was there a reason for the variable special case?

**Comment by JonathanStarup** [comment]
> I don't quite understand why. Could you elaborate? Do we want to spawn everything because of virtual threads?

I think if the user wants to run a variable in parallel we can let them

**Comment by magnus-madsen** [comment]
Yes, but we don't have to optimize for it.
