### ISSUE TITLE
Frontend: Improving the Parser

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#97]
Suggestions for ways to improve the parser:
- Add support for non-parenthesized expressions like `1 + 2 + 3 + 4` and `x && y || z`.
- Add support for GetIndex/SetIndex, i.e. `a[42]` and `b[43 = 32` for use in vectors, etc.
- Add support for lambda functions without typed arguments, e.g. `x => x` and not just `x: Int => x`.
- Add proper support for UTF-8 operators.
- Add syntactic sugar for singleton enum a.k.a. newtype.
- Add support for multi-line strings with `"""triple quotes"""`.

Some ideas to be discussed more:
- Add support for binary literals.
- Add support for large integers `1_000_000`.
- Add syntactic sugar for a style of map/flatMap operations.
- Add support for markdown-style comments! :)
- Add support for postfix call (e.g. `x.length` instead of `length(x)`). 
- Add support for lambdas with `def` syntax (requires rewriting to `letrec`).
- Add support for generic enums/cases.

**Comment by magnus-madsen** [comment]
@olhotak I updated the list of parser improvements.

**Comment by mhyee** [comment]
Other things regarding parsing literals:

- Octal and hexadecimal, in addition to binary
- Scientific notation for floating points
- BigDecimal?
- Character escapes (e.g. '\n') in characters and strings

The feature for writing numeric literals as `1_000_000` is usually called "digit separators." Most languages use `_`. (C++ had conflicts so they had to use `'`).

Triple quotes does more than allow multi-line strings. They allow raw strings, i.e. whatever shows up is literally the string, so you don't need to escape `"` or `\`.

**Comment by magnus-madsen** [comment]
- Improve support for parsing of types.
- See #195 and #194

**Comment by mhyee** [comment]
Bumping this, because it looks like a number of improvements have been made recently. For example: #275 (Unicode operators), #276 (user-defined operators and operator precedence), #282 (postfix apply).

There might be more I missed.

**Comment by magnus-madsen** [comment]
I am closing this with the intention that we open individual tickets for improvements and/or bugs related to the parser.
