### ISSUE TITLE
Add Support for Separator in Integer Literals

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#979]
Allow the programmer to write e.g.:

```
1_000_000
1_000_000_000
```

**Comment by mlutze** [comment]
Do we want to follow the [java spec](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html)? Java allows underscores both in integers and floating point types. It also allows multiple underscores in a row.

**Comment by magnus-madsen** [comment]
Yes, it looks like they already thought about several issues:

```java
long creditCardNumber = 1234_5678_9012_3456L;
long socialSecurityNumber = 999_99_9999L;
float pi =  3.14_15F;
long hexBytes = 0xFF_EC_DE_5E;
long hexWords = 0xCAFE_BABE;
long maxLong = 0x7fff_ffff_ffff_ffffL;
byte nybbles = 0b0010_0101;
long bytes = 0b11010010_01101001_10010100_10010010;
```

We could always start by implementing some easier subset of this.

**Comment by mlutze** [comment]
https://github.com/flix/flix/pull/990

**Comment by magnus-madsen** [comment]
Fixed in master. Thanks @mlutze !
