### ISSUE TITLE
Main with two arguments is evaluated as closure

### ISSUE THREAD

**Issue by Herbstein** [flix/flix#983]
```scala
def main(a: List[String], b: Int): Int = {
    let len = List.length(a);
    len + b
}
```

When running a file containing the above `main` it prints a reference to a closure. I think this should either be an error about a malformed `main` method or not be called at all. Currently it's a weird in-between.

**Comment by magnus-madsen** [comment]
We should require that `main` has a specific signature. We are currently debating in #977 what that signature should be. Once this has been decided, we can enforce it in the Typer.

**Comment by magnus-madsen** [comment]
Main has a fixed signature.
