### ISSUE TITLE
Non-exhaustive match in `List.length`

### ISSUE THREAD

**Issue by Herbstein** [flix/flix#984]
```scala
def main(a: List[String]): Int = {
    test(a)(10)
}

def test(a: List[String], b: Int): Int = {
    let len = List.length(a);
    len + b
}
```

This only happens when using the `List` parameter passed to `main`. When constructing a string manually it works fine.

The error is: `Non-exhaustive match at List.flix:62:42`.

**Comment by magnus-madsen** [comment]
This is related to #983. The problem is that main is not actually passed any usable arguments.

**Comment by magnus-madsen** [comment]
Main has a fixed signature.
