### ISSUE TITLE
generate a properly typed Invokable from Flix types

### ISSUE THREAD

**Issue by olhotak** [flix/flix#99]
The user of Flix is required to provide Flix types when calling addHook.

Flix has a code generator that understands Flix types, and that generates JVM bytecode to solve the Flix program.

Flix should use its code generator to generate a customized version of the Invokable interface customized for the specific Flix types given to it in the addHook call(s). This interface would include one method for each addHook, with the name and type given to the addHook call.

Then the native Java/Scala code just needs to implement that specialized interface with the correct methods with the correct types.

If we want to have different sets of mappings of Flix types to JVM types (e.g. one for Scala collections, one for Java collections, one for some other collection library), we can provide different interface generators, one for each mapping.

This approach is simpler than macros, more user-friendly, and generalizes to include Java rather than only Scala. It is also extensible: one can add a new mapping by writing a new interface generator.

It also doesn't even require Java 8 and SAMs/invokedynamic/etc.

**Comment by magnus-madsen** [comment]
It has been 4 years, but we now have much better interoperability thanks to #939.
