### ISSUE TITLE
Incorrect `Unused Enum` error when using type aliases

### ISSUE THREAD

**Issue by Herbstein** [flix/flix#995]
The following snippet causes `Inner` to be identified as unused, even when `Outer` is used.

```scala
enum Inner {
    case D,
    case E
}

type alias Outer = { a: Inner
                   , b: Inner
                   , c: Inner
                   }
```

**Comment by Herbstein** [comment]
This also happens with opaque types as in the following example:

```scala
opaque type A = String

pub def foo(): A = ???
```

**Comment by magnus-madsen** [comment]
Flix is very strict: could it be that while  you "use" those types in signatures, you actually don't construct any values of those types?

**Comment by Herbstein** [comment]
Yeah, that would be it.

**Comment by magnus-madsen** [comment]
See #2107
